#
# This is all of the combat messages used by combat.c
# Note: all 0 values will be filled with a number greater than 1
#
# Truly Generic strings (no need for gender/number issues)
#
{100}{}{Вам нужно %d очков действия.}
{101}{}{Кончились патроны.}
{102}{}{Цель слишком далеко.}
{103}{}{Нельзя закончить бой рядом с врагами.}
{104}{}{Цель вне досягаемости.}
{105}{}{Вы не можете использовать оружие с поврежденными руками.}
{106}{}{Вы не можете использовать двуручное оружие со сломанной рукой.}
{107}{}{У вас недостаточно сил для использования этого оружия.}
{108}{}{ и }
#
# Combat Flag Strings (all of these happen to you, the MALE player)
#
{200}{}{без сознания}
{201}{}{без сознания}
{202}{}{повреждена ваша левая нога}
{203}{}{повреждена ваша правая нога}
{204}{}{повреждена ваша левая рука}
{205}{}{повреждена ваша правая рука}
{206}{}{ослеплен}
{207}{}{убиты}
{208}{}{ранен}
{209}{}{критический}
{210}{}{под огнем}
{211}{}{ваша броня пробита}
{212}{}{ваше оружие взорвалось}
{213}{}{ваше оружие уничтожено}
{214}{}{ваше оружие упало}
{215}{}{потерял следующий ход}
{216}{}{попал в себя}
{217}{}{потерял все патроны}
{218}{}{хреново выстрелил}
{219}{}{попал в себя}
{220}{}{случайно попал}
{221}{}{поврежден какой-то член тела}
{222}{}{усыпан кусками}
#
# Combat Flag Strings (all of these happen to you, the FEMALE player)
#
{250}{}{без сознания}
{251}{}{без сознания}
{252}{}{повреждена ваша левая нога}
{253}{}{повреждена ваша правая нога}
{254}{}{повреждена ваша левая рука}
{255}{}{повреждена ваша правая рука}
{256}{}{ослеплен}
{257}{}{убиты}
{258}{}{ранен}
{259}{}{критический}
{260}{}{под огнем}
{261}{}{ваша броня пробита}
{262}{}{ваше оружие взорвалось}
{263}{}{ваше оружие уничтожено}
{264}{}{ваше оружие упало}
{265}{}{потерял следующий ход}
{266}{}{попал в себя}
{267}{}{потерял все патроны}
{268}{}{хреново выстрелил}
{269}{}{попал в себя}
{270}{}{случайно попал}
{271}{}{поврежден какой-то член тела}
{272}{}{усыпан кусками}
#
# Combat Flag Strings (all of these happen to a male)
#
{300}{}{без сознания}
{301}{}{без сознания}
{302}{}{повредил его левую ногу}
{303}{}{повредил его правую ногу}
{304}{}{повредил его левую руку}
{305}{}{повредил его правую руку}
{306}{}{ослеплен}
{307}{}{убит}
{308}{}{ранен}
{309}{}{критический}
{310}{}{под огнем}
{311}{}{его броня пробита}
{312}{}{его оружие взорвалось}
{313}{}{его оружие уничтожено}
{314}{}{его оружие упало}
{315}{}{потерял следующий ход}
{316}{}{попал в себя}
{317}{}{потерял все патроны}
{318}{}{хреново выстрелил}
{319}{}{попал в себя}
{320}{}{случайно попал}
{321}{}{поврежден какой-то член тела}
{322}{}{усыпан кусками}
#
# Combat Flag Strings (all of these happen to a female)
#
{400}{}{без сознания}
{401}{}{без сознания}
{402}{}{повредили ее левую ногу}
{403}{}{повредили ее правую ногу}
{404}{}{повредили ее левую руку}
{405}{}{повредили ее правую руку}
{406}{}{ослеплена}
{407}{}{убита}
{408}{}{ранена}
{409}{}{критический}
{410}{}{под огнем}
{411}{}{ее броня пробита}
{412}{}{ее оружие взорвалось}
{413}{}{ее оружие уничтожено}
{414}{}{ее оружие упало}
{415}{}{потеряла следующий ход}
{416}{}{попала в себя}
{417}{}{потеряла все патроны}
{418}{}{хреново выстрелила}
{419}{}{попала в себя}
{420}{}{случайно попала}
{421}{}{поврежден какой-то член тела}
{422}{}{усыпана кусками}
#
# Miscellaneous combat messages (all of these happen to you, the male player)
# Note: the first  will be replaced by the value of line 506, which
#          should be the language's equivalent to 2nd person male singular,
#          which is "You" in English. The first letter of line 506 should
#          be capitalized, since it will start a sentence.
#       the second  (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 509
#          where the second  is the name of another creature
{506}{}{Вы}
{509}{}{Ой! Ранены %s, а не %s!}
{511}{}{%s были серьезные ранены в %s на %d жизней}
{512}{}{%s были ранены в %s на %d жизней}
{513}{}{%s ранены на %d жизней}
{514}{}{%s сильно промахнулись}
{515}{}{%s промазали}
{520}{}{%s были серьезно ранены на %d жизней}
{521}{}{%s были серьезно ранены в %s на 1 жизнь}
{522}{}{%s были ранены в %s на 1 жизнь}
{523}{}{%s были ранены на 1 жизнь}
{524}{}{%s были серьезно ранены на 1 жизнь}
{525}{}{%s перенесли серьезное ранение в %s без последствий}
{526}{}{%s выдержали попадание в %s без последствий}
{527}{}{%s перенесли ранение без последствий}
{528}{}{%s перенесли серьезное ранение без последствий}
{533}{}{%s промахнулись и взяли 1 жизнь}
{534}{}{%s промахнулись и взяли %d жизней}
#
# Miscellaneous combat messages (all of these happen to you, the female player)
# Note: the first  will be replaced by the value of line 556, which
#          should be the language's equivalent to 2nd person female singular,
#          which is "You" in English. The first letter of line 556 should
#          be capitalized, since it will start a sentence.
#       the second  (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 559
#          where the second  is the name of another creature
{556}{}{Вы}
{559}{}{Ой! Ранены %s, а не %s!}
{561}{}{%s были серьезные ранены в %s на %d жизней}
{562}{}{%s были ранены в %s на %d жизней}
{563}{}{%s ранены на %d жизней}
{564}{}{%s сильно промахнулись}
{565}{}{%s промазали}
{570}{}{%s были серьезно ранены на %d жизней}
{571}{}{%s были серьезно ранены в %s на 1 жизнь}
{572}{}{%s были ранены в %s на 1 жизнь}
{573}{}{%s были ранены на 1 жизнь}
{574}{}{%s были серьезно ранены на 1 жизнь}
{575}{}{%s перенесли серьезное ранение в %s без последствий}
{576}{}{%s выдержали попадание в %s без последствий}
{577}{}{%s перенесли ранение без последствий}
{578}{}{%s перенесли серьезное ранение без последствий}
{583}{}{%s промахнулись и взяли 1 жизнь}
{584}{}{%s промахнулись и взяли %d жизней}
#
# Miscellaneous combat messages (all of these happen to a male)
# Note: the first  is the name of the male creature
#       the second  (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 609
#          where the second  is the name of another creature
#
{608}{}{Ого! Вместо вас был ранен %s!}
{609}{}{Ух! Был ранен %s, а не %s!}
{611}{}{%s был серьезно ранен в %s на %d жизней}
{612}{}{%s получил ранение в %s на %d жизней}
{613}{}{%s ранен на %d жизней}
{614}{}{%s серьезно промахнулся}
{615}{}{%s промазал}
{620}{}{%s был серьезно ранен на %d жизней}
{621}{}{%s был серьезно ранен в %s на 1 жизнь}
{622}{}{%s получил ранение в %s на 1 жизнь}
{623}{}{%s получил ранение на 1 жизнь}
{624}{}{%s был серьезно ранен на 1 жизнь}
{625}{}{%s выдержал критичное попадание в %s без последствий}
{626}{}{%s перенес ранение в %s без последствий}
{627}{}{%s перенес ранение без последствий}
{628}{}{%s выдержал серьезное попадание без последствий}
{633}{}{%s ужасно промахнулся и взял 1 жизнь}
{634}{}{%s критически промахнулся и взял %d жизней}
#
# Miscellaneous combat messages (all of these happen to a female)
# Note: the first  is the name of the female creature
#       the second  (if there is one) is the hit location, which
#          will be a string from the section Hit Locations starting
#          in the 1000's in this file, with the exception of line 709
#          where the second  is the name of another creature
#
{708}{}{Ого! Вместо вас была ранена %s}
{709}{}{Эх! Была ранена %s, а не %s!}
{711}{}{%s была серьезно ранена в %s на %d жизней}
{712}{}{%s была ранена в %s на %d жизней}
{713}{}{%s ранена на %d жизней}
{714}{}{%s сильно промахнулась}
{715}{}{%s промазала}
{720}{}{%s серьезно ранена на %d жизней}
{721}{}{%s получила серьезное ранение в %s на 1 жизнь}
{722}{}{%s ранена в %s на 1 жизнь}
{723}{}{%s была ранена на 1 жизнь}
{724}{}{%s серьезно ранена на 1 жизнь}
{725}{}{%s перенесла серьезное ранение в %s без последствий}
{726}{}{%s выдержала попадание в %s без последствий}
{727}{}{%s перенесла ранение без последствий}
{728}{}{%s выдержала серьезное попадание без последствий}
{733}{}{%s сильно промахнулась и взяла 1 жизнь}
{734}{}{%s сильно промахнулась и взяла %d жизней}
#
# Hit Locations (by art_num alias)
#
# childrens
#
{1010}{}{головку}
{1011}{}{левую ручку}
{1012}{}{правую ручку}
{1013}{}{тельце}
{1014}{}{правую ножку}
{1015}{}{левую ножку}
{1016}{}{глазки}
{1017}{}{пах}
{1018}{}{неназванное}
#
# teens guys
#
{1050}{}{голову}
{1051}{}{левую руку}
{1052}{}{правую руку}
{1053}{}{корпус}
{1054}{}{правую ногу}
{1055}{}{левую ногу}
{1056}{}{глаза}
{1057}{}{пах}
{1058}{}{неназванное}
#
# teens girls
#
{1080}{}{голову}
{1081}{}{левую руку}
{1082}{}{правую руку}
{1083}{}{грудь}
{1084}{}{правую ногу}
{1085}{}{левую ногу}
{1086}{}{глаза}
{1087}{}{пах}
{1088}{}{неназванное}
#
# regular humans - MENS
#
{1100}{}{голову}
{1101}{}{левую руку}
{1102}{}{правую руку}
{1103}{}{корпус}
{1104}{}{правую ногу}
{1105}{}{левую ногу}
{1106}{}{глаза}
{1107}{}{пах}
{1108}{}{неназванное}
#
# regular humans - WOMENS
#
{1160}{}{голову}
{1161}{}{левую руку}
{1162}{}{правую руку}
{1163}{}{корпус}
{1164}{}{правую ногу}
{1165}{}{левую ногу}
{1166}{}{глаза}
{1167}{}{пах}
{1168}{}{неназванное}
#
# Lavache (Mutant 2-Headed Cows) this thil conform to file critters.lst, for exemple for brahmins - mabrom,25
#
{1250}{}{голову}
{1251}{}{заднюю ногу}
{1252}{}{заднюю ногу}
{1253}{}{корпус}
{1254}{}{переднюю ногу}
{1255}{}{переднюю ногу}
{1256}{}{глаза}
{1257}{}{вымя}
{1258}{}{неназванное}
#
# dogs
#
{1770}{}{голову}
{1771}{}{заднюю ногу}
{1772}{}{заднюю ногу}
{1773}{}{туловище}
{1774}{}{переднюю ногу}
{1775}{}{переднюю ногу}
{1776}{}{глаза}
{1777}{}{яйца}
{1778}{}{неназванное}
#
# Rat
#
{1810}{}{голову}
{1811}{}{переднюю лапку}
{1812}{}{переднюю лапку}
{1813}{}{туловище}
{1814}{}{заднюю лапку}
{1815}{}{заднюю лапку}
{1816}{}{глазки}
{1817}{}{под хвост}
{1818}{}{неназванное}
#
# Mole-Rat
#
{1820}{}{голову}
{1821}{}{левую лапу}
{1822}{}{правую лапу}
{1823}{}{туловище}
{1824}{}{правую ногу}
{1825}{}{левую ногу}
{1826}{}{глазки}
{1827}{}{гениталии}
{1828}{}{неназванное}
#
# Ant
#
{1830}{}{голову}
{1831}{}{переднюю ногу}
{1832}{}{переднюю ногу}
{1833}{}{тело}
{1834}{}{заднюю ногу}
{1835}{}{заднюю ногу}
{1836}{}{усики}
{1837}{}{брюхо}
{1838}{}{неназванное}
#
# Radscorpion
#
{1850}{}{голову}
{1851}{}{хвост}
{1852}{}{клешню}
{1853}{}{панцирь}
{1854}{}{правые ноги}
{1855}{}{левые ноги}
{1856}{}{глаза}
{1857}{}{нервный центр}
{1858}{}{неназванное}
#
# Security Robot
#
{1860}{}{голову}
{1861}{}{руку с ракетницей}
{1862}{}{руку с пушкой}
{1863}{}{туловище}
{1864}{}{правую ногу}
{1865}{}{левую ногу}
{1866}{}{сенсоры}
{1867}{}{багажник}
{1868}{}{неназванное}
#
# Robotron
#
{1870}{}{центр координации}
{1871}{}{левый манипулятор}
{1872}{}{правый манипулятор}
{1873}{}{корпус}
{1874}{}{правую ходильню}
{1875}{}{левую ходильню}
{1876}{}{узел питания}
{1877}{}{резервный модуль}
{1878}{}{неназванное}
#
# Chimeras
#
{1890}{}{рогатую голову}
{1891}{}{переднюю лапу}
{1892}{}{переднюю лапу}
{1893}{}{торс}
{1894}{}{заднюю лапу}
{1895}{}{заднюю лапу}
{1896}{}{глаза}
{1897}{}{паховую область}
{1898}{}{неназванное}
#
# Beasties
#
{1930}{}{голову}
{1931}{}{переднюю лапу}
{1932}{}{переднюю лапу}
{1933}{}{тело}
{1934}{}{заднюю лапу}
{1935}{}{заднюю лапу}
{1936}{}{глаза}
{1937}{}{пах}
{1938}{}{неназванное}
#
# Gun Turret
#
{1940}{}{ЦПУ}
{1941}{}{сервомеханизм пушки}
{1942}{}{сервомеханизм пушки}
{1943}{}{раму}
{1944}{}{сервомеханизм башни}
{1945}{}{сервомеханизм башни}
{1946}{}{дальновизор}
{1947}{}{регулятор}
{1948}{}{неназванное}
#
# Urs
#
{1950}{}{темечко}
{1951}{}{переднюю лапу}
{1952}{}{переднюю лапу}
{1953}{}{тело}
{1954}{}{заднюю лапу}
{1955}{}{заднюю лапу}
{1956}{}{глаза}
{1957}{}{пах}
{1958}{}{неназванное}
#
# Laser turret
#
{1990}{}{ЦПУ}
{1991}{}{опору фокусатора}
{1992}{}{опору фокусатора}
{1993}{}{раму}
{1994}{}{опорный кронштейн}
{1995}{}{опорный кронштейн}
{1996}{}{дальновизор}
{1997}{}{регулятор}
{1998}{}{неназванное}
#
# Minigun turret
#
{2000}{}{ЦПУ}
{2001}{}{сервомеханизм спуска}
{2002}{}{сервомеханизм спуска}
{2003}{}{раму}
{2004}{}{опорный кронштейн}
{2005}{}{опорный кронштейн}
{2006}{}{дальновизор}
{2007}{}{регулятор}
{2008}{}{неназванное}
#
# Plasma turret
#
{2010}{}{ЦПУ}
{2011}{}{сервомеханизм спуска}
{2012}{}{сервомеханизм спуска}
{2013}{}{раму}
{2014}{}{опорный кронштейн}
{2015}{}{опорный кронштейн}
{2016}{}{дальновизор}
{2017}{}{регулятор}
{2018}{}{неназванное}
#
# BOSS1
#
{2020}{}{сенсор}
{2021}{}{левую опору}
{2022}{}{правую опору}
{2023}{}{раму}
{2024}{}{правый кронштейн}
{2025}{}{левый кронштейн}
{2026}{}{контактор визионара}
{2027}{}{штепсель}
{2028}{}{неназванное}
#
# Rocket turret
#
{2030}{}{ЦПУ}
{2031}{}{сервомеханизм запуска}
{2032}{}{сервомеханизм запуска}
{2033}{}{раму}
{2034}{}{опорный кронштейн}
{2035}{}{опорный кронштейн}
{2036}{}{дальновизор}
{2037}{}{регулятор}
{2038}{}{неназванное}
#
# Left shield
#
{2040}{}{излучатель}
{2041}{}{левую опору}
{2042}{}{правую стойку}
{2043}{}{излучатель}
{2044}{}{крепление опоры}
{2045}{}{крепление опоры}
{2046}{}{питающий кабель}
{2047}{}{кожух излучателя}
{2048}{}{---}
#
# Center shield
#
{2050}{}{излучатель}
{2051}{}{левую опору}
{2052}{}{правую стойку}
{2053}{}{излучатель}
{2054}{}{крепление опоры}
{2055}{}{крепление опоры}
{2056}{}{питающий кабель}
{2057}{}{кожух излучателя}
{2058}{}{---}
#
# Right shield
#
{2060}{}{излучатель}
{2061}{}{левую опору}
{2062}{}{правую стойку}
{2063}{}{излучатель}
{2064}{}{крепление опоры}
{2065}{}{крепление опоры}
{2066}{}{питающий кабель}
{2067}{}{кожух излучателя}
{2068}{}{---}
#
# Critical Hit Messages
#
# 5000 series - men (including generics) - see file PROTO.MSG, section on line 1469 - Kill Types
#
{5000}{}{ и это больно.}
{5001}{}{. Нанесена тяжелая рана}
{5002}{}{, броня не защитила его}
{5003}{}{. Мощная атака оставила его без сознания}
{5004}{}{. Сильный удар бросил его на землю}
{5005}{}{. Сильный удар в голову оставил его без сознания}
{5006}{}{. сильный удар раскалывает череп. Спокойной ночи, приятель}
{5007}{}{, смерть была мгновенной}
{5008}{}{, заработал повреждение локтя}
{5009}{}{, он вывернул себе руку, пытаясь уклониться}
{5010}{}{, заработал большой синяк}
{5011}{}{, его левая рука повреждена}
{5012}{}{, его левая рука остается болтаться на куске кожи}
{5013}{}{. Теперь его рука похожа на кровавое месиво}
{5014}{}{, осталась поврежденной правая рука}
{5015}{}{. Его рука страшно изуродована этим мощным ударом}
{5016}{}{ после одного сильного удара}
{5017}{}{, броня насквозь пробита}
{5018}{}{, причинены добавочные повреждения}
{5019}{}{ без защиты брони, боец сбит на землю}
{5020}{}{ у него перехватило дыхание, после чего он рухнул на землю}
{5021}{}{. К сожалению, его позвоночник теперь ясно виден со стороны живота}
{5022}{}{ и это причинило серьезные повреждения его ноге}
{5023}{}{, что сбило его на землю, как кеглю после удара шаром в игре лиги}
{5024}{}{, что отбросило его и повредило ему ногу}
{5025}{}{, и это отбросило его колено очень далеко. Рыдая он упал}
{5026}{}{. Сильная боль от оторванной ноги заставляет его на мгновенье отключиться}
{5027}{}{ это причинило дополнительную боль}
{5028}{}{ что вызвало ослепление, к несчастью для него}
{5029}{}{, что безо всяких помех со стороны доспехов, причинило ему серьезную боль}
{5030}{}{, разящий удар ослепил его}
{5031}{}{. Потеря глаза причиняет ему чрезмерную боль и он падает на землю}
{5032}{}{, к несчастью, он слишком задумался, чтобы заметить приближающуюся смерть}
{5033}{}{. Ой! Это больно}
{5034}{}{, и он больше никогда не будет носить плавки}
{5035}{}{ и, не имея дополнительной защиты, он повалился, дергаясь в агонии}
{5036}{}{. Боль слишком сильна для него и он шлепнулся, как мешок дерьма}
{5037}{}{. Он бормочет "Мама", и глаза его закатываются}
#
# series 5100 - women
#
{5100}{}{ и это больно.}
{5101}{}{. Нанесена тяжелая рана}
{5102}{}{ без защиты брони}
{5103}{}{. Серьезная атака заставила ее потерять сознание}
{5104}{}{. Удар сбивает ее на землю}
{5105}{}{. Сильный удар в голову сбивает ее на землю}
{5106}{}{. Сильный удар раскалывает ее голову. Спокойной ночи, любимая}
{5107}{}{, смерть была мгновенной}
{5108}{}{, заработала повреждение локтя}
{5109}{}{, она вывернула себе руку, пытаясь уклониться}
{5110}{}{, заработала большой синяк}
{5111}{}{, ее левая рука повреждена}
{5112}{}{. Ее левая рука еле держится на обломках костей}
{5113}{}{. Теперь ее рука похожа на кровавое месиво}
{5114}{}{, осталась поврежденной правая рука}
{5115}{}{. Ее правая рука превращена сильным ударом в отбивную}
{5116}{}{ после одного сильного удара}
{5117}{}{, ее защита пробита}
{5118}{}{, причинены добавочные повреждения}
{5119}{}{ без защиты брони, удар опрокидывает женщину на землю}
{5120}{}{ она падает на землю, пока воздух со свистом выходит из ее легких}
{5121}{}{. К сожалению, ее основные органы медленно вываливаются наружу}
{5122}{}{ и это причиняет основные повреждения ее ноге}
{5123}{}{, что ошеломляет ее, как литр неразбавленного спирта}
{5124}{}{, сбита с ног, ее конечность повреждена}
{5125}{}{, ее колено разбито. Она падает на землю, корчась от боли}
{5126}{}{. Она кричит от боли в сломанной ноге}
{5127}{}{ это причинило дополнительную боль}
{5128}{}{ вызвано ослепление. Ее лицо искажает гримаса боли}
{5129}{}{, что безо всяких помех со стороны доспехов, причинило ей сильнейшую боль}
{5130}{}{. Рана вызывала сильное ослепление}
{5131}{}{. Она слабеет от ослепляющей атаки}
{5132}{}{, к несчастью, она не помолилась своим богам перед встречей с ними}
{5133}{}{. Она принимает это как мужчина. А это, кстати, больно}
{5134}{}{, это сбивает ее на землю}
{5135}{}{. Ее будущие дети под угрозой, так как она падает на землю как куча тряпок}
#
# series 5200 - little boy
#
{5200}{}{. Маленький мальчик начинает плакать}
{5201}{}{. Маленький мальчик падает без сознания}
{5202}{}{. Ой!}
{5203}{}{. Удар силен, и мальчик падает без сознания}
{5204}{}{, маленький мальчик смят, как снеговик}
{5205}{}{. Левая рука этого мальчика теперь живет своей жизнью}
{5206}{}{, равновесие малыша нарушено}
{5207}{}{, рука сломана сильным ударом. Малыш начинает плакать}
{5208}{}{, рука оторвана легко, как ветка у дерева}
{5209}{}{. Правая рука начинает пухнуть, как воздушный шар}
{5210}{}{, и начинает орать}
{5211}{}{ в чувствительное место}
{5212}{}{. Атака на жизненно важные органы опрокидывает малыша}
{5213}{}{, мальчик сбит с ног}
{5214}{}{. Этот малыш так никогда и не узнает, что такое жизнь}
{5215}{}{, и сильно порезан}
{5216}{}{. Атака сбивает малыша и его нога ломается}
{5217}{}{, малышу нанесены страшные ранения}
{5218}{}{. Мальчик смотрит вверх и начинает плакать}
{5219}{}{, и это ослепляет мальчика}
{5220}{}{, что сокрушает юный нос}
{5221}{}{. Над глазами появился порез, из которого начинает течь кровь}
{5222}{}{, и глаз лопается, как перезрелый виноград. Малыш выглядит удивленным}
{5223}{}{ вызвана слепота. Малыш бросается на землю}
{5224}{}{, удар сминает голову малыша}
{5225}{}{. Мальчик выглядит испуганным и дрожит}
{5226}{}{, и это сшибает мальчика на землю}
#
# series 5300 - Little girl
#
{5300}{}{, маленькая девочка начинает реветь от сильной боли}
{5301}{}{, удар по нежному месту}
{5302}{}{, удар по болевой точке сбивает малышку с ног}
{5303}{}{. Маленькую девочку разворачивает от удара и она плюхается наземь}
{5304}{}{. Голова девочки лопается, как перезрелый арбуз}
{5305}{}{, маленькая девочка начинает реветь от сильной боли}
{5306}{}{, девочка начинает истошно кричать и умолять о пощаде}
{5307}{}{, рука девочки судорожно болтается, как тряпка}
{5308}{}{. Взрыв дробит маленькую коленку, и это заставляет девочку закатить глаза}
{5309}{}{, девочка судорожно сжимает оторванную руку, но кровь продолжает хлестать}
{5310}{}{, девочка падает, как подкошенная}
{5311}{}{, поврежденные органы девочки повсюду разбрызгивают кровь}
{5312}{}{, это сбивает малышку на землю}
{5313}{}{. Нога девочки держится лишь на остатках кожи}
{5314}{}{, удар по болевой точке. Крича, девочка падает и ломает ногу}
{5315}{}{. Боль от сломанной ноги заставляет малышку истошно кричать и звать на помощь}
{5316}{}{, кровь заливает маленькое личико}
{5317}{}{, глаза девочки вытекли из глазниц, она начинает биться в истерике}
{5318}{}{, атака по глазам сбивает бедняжку на землю}
{5319}{}{. Девочка потеряла зрение, кровь и слезы капают на землю}
{5320}{}{, девочка ослеплена и без сознания}
{5321}{}{. Бедняжка начинает медленно оседать на землю}
#
# series 5400 - Ghouls
#
{5400}{}{. Мертвяк удивлен, и не может сопротивляться атаке}
{5401}{}{. Этот удар убивает мертвяка}
{5402}{}{. Рука ошеломленного мертвяка пролетает мимо}
{5403}{}{, броня пробита и ползадницы оторвало}
{5404}{}{, броня пробита и рука оторвана}
{5405}{}{. Он совершает неверное движение в неверный момент, и теряет глаз}
{5406}{}{. Там у мертвяка брони нет}
{5407}{}{, без брони, мертвяк ослеплен}
{5408}{}{, атака вынуждает мертвяка выглядеть разъяренным в его последние мгновения}
#
# series 5500 - La Vache
#
{5500}{}{, большой зверь сбит на землю}
{5501}{}{, это ошеломляет и убивает гигантское животное}
{5502}{}{. Корова-мутант издает громкий, протяжный крик}
{5503}{}{, одна из ног лаваша сломана}
{5504}{}{, корова-мутант серьезно ранена}
{5505}{}{, гигантский зверь не может уклониться}
{5506}{}{, сквозное проникновение через оба сердца коровы-мутанта}
{5507}{}{, все глаза ослеплены одним ударом}
{5508}{}{, обе головы ослеплены, лаваш не может понять, как так получилось}
{5509}{}{, это полностью ослепляет лаваша и вырубает его}
{5510}{}{, большой уродец на мгновение оступился}
{5511}{}{. Лаваш дрожит от ярости}
{5512}{}{. Лаваш дергается от боли}
{5513}{}{. Лаваш очень расстроен этой неожиданной атакой}
#
# series 5600 - Radscorpions
#
{5600}{}{, скорпион отправлен в полет на спину}
{5601}{}{, голова отделена от туловища}
{5602}{}{, серьезно поврежден хвост}
{5603}{}{, в основном повреждены его клыки}
{5604}{}{. Взрыв пробивает прочный панцирь скорпиона}
{5605}{}{, что сразу же пробивает прочный панцирь}
{5606}{}{, это пробивает естественную броню и сбивает скорпиона с конечностей}
{5607}{}{. Скорпион не может врубиться в происходящее и то, куда делись некоторые внутренние органы}
{5608}{}{, скорпион отправлен в полет, некоторые его ноги повреждены}
{5609}{}{. Атака пробивает незащищенное место конечности, серьезно повреждая ее}
{5610}{}{, он серьезно ранен и ослеплен}
{5611}{}{, достали почти до мозга. Просто, как жука раздавить}
{5612}{}{, проникновение почти в мозг, существо ослеплено}
{5613}{}{. Атака прекрасна, и, наверное, слишком наворочена для такого тупого существа}
{5614}{}{. Если бы это был человек, я мог бы поклясться, что он рассержен}
{5615}{}{, это оставляет бедное существо без чувств}
{5616}{}{, роняя мозги на землю}
#
# series 5700 - Rats
#
{5700}{}{. Зубы издают неприятный звук}
{5701}{}{, скулы крысса сокрушены как бумажный пакет}
{5702}{}{, а левая лапа выглядит сейчас плосковатой}
{5703}{}{. Левая лапа крысса оторвана}
{5704}{}{. Правая лапа сильно повреждена}
{5705}{}{, правая лапа оторвана нахрен}
{5706}{}{. Крысс серьезно ранен в этой атаке}
{5707}{}{, серьезное ранение сбивает крысса с ног}
{5708}{}{, крысс расплющен по полу}
{5709}{}{, повреждена правая нога}
{5710}{}{, пробита большая дыра в левой ноге}
{5711}{}{, причинены дополнительные повреждения}
{5712}{}{, эта зверюга отправлена к великому крыссолову в небесах}
#
# series 5800 - Beasties
#
{5800}{}{, повалился на землю}
{5801}{}{, он упал на землю, корчась от боли}
{5802}{}{, став препятствием своему дальнейшему существованию}
{5803}{}{, существо ошеломлено}
{5804}{}{, удар в болевую точку ошеломляет бродягу}
{5805}{}{. Удар красиво разрывает бродягу в пурпурное облако крови}
{5806}{}{, удар провоцирует нездоровую реакцию у существа}
{5807}{}{. Он неожиданно хорошо загорелся}
{5808}{}{ это становится для него сюрпризом}
{5809}{}{, удар попадает по болевой точке}
{5810}{}{. Существо, очевидно, недовольно}
#
# series 5900 - Mindless
#
{5900}{}{, после сильного толчка безумный впал в ступор и повалился на землю}
{5901}{}{ этот удар приходится в жизненно важное место}
{5902}{}{, многие органы повреждены}
{5903}{}{, он ошеломлен такой жестокой атакой}
{5904}{}{, повреждена рука}
{5905}{}{ удар в болевую точку повреждает руку}
{5906}{}{, безумный сбит с ног и повреждает коленку}
{5907}{}{, сломанная нога заставляет безумного рухнуть на землю}
{5908}{}{, безвекие глаза сильно повреждены, безумный теперь вообще ничего не видит}
{5909}{}{, безумный поражен. Он тупо стоит секунду}
{5910}{}{, грохаясь на землю, безумный выкатывает изумленные глаза из орбит}
{5911}{}{, безумный удивлен. Он падает словно куча лавашьего дерьма}
{5912}{}{. Атака не такая эффективная, как могла бы быть. Там уже давно ничего нет}
#
# series 6000 - Robots
#
{6000}{}{, причинены некоторые структурные повреждения}
{6001}{}{, летят искры и робот моментально выходит из под контроля}
{6002}{}{, удар в важную деталь выводит робота из под контроля}
{6003}{}{, удар в важный блок вызывает глубокие неполадки}
{6004}{}{. Робот пытается компенсировать}
{6005}{}{. Робот пытается компенсировать}
{6006}{}{, удар в важный узел вызывает тяжелые повреждения}
{6007}{}{, причинены серьезные структурные повреждения}
{6008}{}{, удар в важный узел вызывает серьезные неполадки}
{6009}{}{. Робот не выдерживает интенсивной атаки}
{6010}{}{, придется разобрать его на запчасти}
{6011}{}{. Робот пытается компенсировать, но ему это не удается и он падает на землю}
{6012}{}{. Робот не выдерживает удара, падая на землю}
{6013}{}{, разбиты линзы сенсоров}
#
# series 6100 - Sand Jackals
#
{6100}{}{, удар сбивает его на землю}
{6101}{}{, так как и замышлялось}
{6102}{}{. Шакал падает, но все еще дышит}
{6103}{}{, шакал кашляет, плюясь кровью}
{6104}{}{, нога шакала сильно повреждена, от его дикого воя мороз пробегает по коже}
{6105}{}{, нога повреждена. Шакал пытается устоять, но валится как куча тряпок}
{6106}{}{. Ослепленный зверь воет от боли}
{6107}{}{, шакал скулит в приступе агонии}
#
# series 6200 - Fathorners
#
{6200}{}{, это мутировавшее насекомое сбито}
{6201}{}{, и падает}
{6202}{}{. Мантис думает, стоит ли ему жить}
{6203}{}{, поврежден член}
{6204}{}{, Мантис судорожно лижет свои раны и настороженно смотрит}
{6205}{}{, хитиновый панцирь пробит}
{6206}{}{. Мантис кричит нечеловеческим голосом}
{6207}{}{, атака заставляет Мантис упасть. Он побит и готов умереть}
{6208}{}{, крылья разрезаны}
{6209}{}{, атака пробивает хитиновую броню и разбрызгивает Мантис по округе}
{6210}{}{, насекомое ослеплено аккуратной вспышкой}
#
# series 6300 - Chimeras
#
{6300}{}{. Кажется, что даже это чудовище ошеломлено такой атакой}
{6301}{}{, огромные клыки не спасают чудовище от удара. Ёимера дрожит и боится}
{6302}{}{. Результатом является обширное повреждение глаз Ёимеры}
#
# series 6400 - Turrets
#
{6400}{}{, защитный кожух турели пробит насквозь}
{6401}{}{, несколько винтов и шайб разлетелись в разные стороны}
{6402}{}{, некоторые сервоприводы шипят, выпуская воздух из пробитых шлангов}
{6403}{}{, важные механизмы получили серьезные повреждения}
{6404}{}{, одна из линз системы наведения весело разлетается на тысячу осколков}
{6405}{}{. Турель дергается и искрит. Очевидно, она почти разрушена}
{6406}{}{, многие приводы и цилиндры критически повреждены}
#
# series 6500 - The Player
#
{6500}{}{. Завтра утром у вас будет раскалываться голова, конечно, если вы проживете так долго}
{6501}{}{. От такого выстрела ваша броня вас не предохранит}
{6502}{}{. На мгновение вы чувствуете боль, и затем темнота обволакивает вас..}
{6503}{}{, ваша броня пробита. Удар сбивает вас с ног}
{6504}{}{, от шока у вас темнеет в глазах. Через секунду вы замечаете, что зрение так и не вернулось к вам}
{6505}{}{. Вы получаете хороший обзор местности, когда ваша голова летит по воздуху}
{6506}{}{. Удивительно, но ущерб оказался не очень велик}
{6507}{}{, на момент вы были ошеломлены}
{6508}{}{. Чувствуете боль}
{6509}{}{. Атака оставляет вашу руку бесполезной}
{6510}{}{, броня пробита. Удар ломает кости вашей руки, как хворост}
{6511}{}{, броня пробита. Теперь ваша рука беспомощно свисает с плеча}
{6512}{}{. Синяк будет выглядеть прекрасно, и шрамы составят ему хорошую компанию}
{6513}{}{, внутренние органы смяты. Вы можете только булькать кровью}
{6514}{}{, роняете наземь голову}
{6515}{}{, вас послали в полет и сломали вам ногу}
{6516}{}{, вашу броню прожгли. Удар сбивает вас с ног и серьезно повреждает колено}
{6517}{}{. Боль от сломанной ноги так сильна, что вы теряете сознание}
{6518}{}{. Болезненный удар заставляет вас отступить, и происходит еще что-то}
{6519}{}{. К несчастью для вас, это также вызывает немедленную потерю зрения}
{6520}{}{. За секунду вы вытираете кровь с глаз}
{6521}{}{, броня пробита. Вы стоите ошеломленным, понимая, что больше ничего не видите}
{6522}{}{. Вы чувствуете странное ощущение в голове. Вы понимаете, что это смертельная травма мозга}
{6523}{}{, вас вынуждают преклоняться}
{6524}{}{. Вы хватаетесь за яйца и падаете, корчась на пол}
{6525}{}{. Боль достаточно сильна, чтобы оставить вас без сознания}
{6526}{}{. Нет таких слов, которыми можно было бы описать боль, которую вы испытываете в этот момент}
# Fallout 2:
#
# series 6700 - Molerats
#
{6700}{}{, шкура мерзкого мутанта пробита}
{6701}{}{, часть скользкой кожи с него сорвана}
{6702}{}{, ему оторвало несколько пальцев}
{6703}{}{, ему пробило дыхалку.}
{6704}{}{, ему выпустили кишки}
{6705}{}{, он почти сбит с ног}
{6706}{}{, повреждено несколько его конечностей}
#
# series 6800 - Les ours
#
{6800}{}{, толстая шкура могучего урса пробита}
{6801}{}{, кусок шкуры оторвался и полетел по ветру. Урс рычит, сотрясая землю}
{6802}{}{, лапа урса сломана и кости торчат наружу. Глаза зверя багровеют от крови}
{6803}{}{, легкое медведя пробито и явственно слышно бульканье крови}
{6804}{}{, удар вспарывает могучему зверю брюхо и его кишки валятся в пыль}
{6805}{}{, медведь-мутант еле стоит на слабых лапах}
{6806}{}{, лапа урса сломана и кости разрывают шкуру. Медведь удивленно смотрит на обмякшую конечность}
#
# series 6900 - Giant Ant
#
{6900}{}{, хитиновый панцирь насекомого пробит}
{6901}{}{, ему оторвало несколько антенн}
{6902}{}{, ему оторвало несколько усиков}
{6903}{}{, ему снесло полжизни}
{6904}{}{, он слегка оглушен}
{6905}{}{, он почти сбит с ног}
{6906}{}{, его панцирь поврежден}
#
# series 7000 - Gun Turret  -- WIP! Won't Work!
#
{7000}{}{, пробивая хитиновый панцирь насекомого}
{7001}{}{, отрывая ему несколько антенн}
{7002}{}{, отрывая ему несколько усиков}
{7003}{}{, снося ему пол-жизни}
{7004}{}{, слегка оглушая его}
{7005}{}{, почти сбивая его с ног}
{7006}{}{, повреждая его панцирь}
# Series 7100 - Reserved
{7100}{}{, пробивая навылет броню Телохранителя}
{7101}{}{, повергая Телохранителя на колени}
{7102}{}{, разрушен механизм управления руками}
{7103}{}{, разрушен механизм поворота ног}
{7104}{}{, его синтетический глаз поврежден}
{7105}{}{, это заставило его остановиться чтобы отбить вашу атаку}
{7106}{}{, его броня повреждена}
