#
# Messages for Maps
#
#
# Map Names for (Automap) Descriptions
#	Note: This order must *NOT* change!
#
#	Note: The maximum description width is approximately:
#	  "Brotherhood of Steel (Lower Levels)" -- about 34 characters,
#	  but it's proportional, so you need to double-check it by
#	  going into mapper/game and going to the automap for that map.
#
#	Note: Descriptions *MUST* *NOT* be empty, and so temporary
#	  descriptions are just the map name itself (this also helps
#	  pinpoint unfinished ones when you go through here).
#
{100}{}{error:Maр Name}
{101}{}{error:Maр Name}
{102}{}{error:Maр Name}
{103}{}{error:Maр Name}
{104}{}{error:Maр Name}
{105}{}{error:Maр Name}
{106}{}{error:Maр Name}
{107}{}{error:Maр Name}
{108}{}{error:Maр Name}
{109}{}{error:Maр Name}
{110}{}{error:Maр Name}
{111}{}{error:Maр Name}
{112}{}{error:Maр Name}
{113}{}{error:Maр Name}
{114}{}{error:Maр Name}
{115}{}{error:Maр Name}
{116}{}{error:Maр Name}
{117}{}{error:Maр Name}
{118}{}{error:Maр Name}
{119}{}{error:Maр Name}
{120}{}{error:Maр Name}
{121}{}{error:Maр Name}
{122}{}{error:Maр Name}
{123}{}{error:Maр Name}
{124}{}{error:Maр Name}
{125}{}{error:Maр Name}
{126}{}{error:Maр Name}
{127}{}{error:Maр Name}
{128}{}{error:Maр Name}
{129}{}{error:Maр Name}
{130}{}{error:Maр Name}
{131}{}{error:Maр Name}
{132}{}{error:Maр Name}
{133}{}{error:Maр Name}
{134}{}{error:Maр Name}
{135}{}{error:Maр Name}
{136}{}{error:Maр Name}
{137}{}{error:Maр Name}
{138}{}{error:Maр Name}
{139}{}{error:Maр Name}
{140}{}{error:Maр Name}
{141}{}{error:Maр Name}
{142}{}{error:Maр Name}
{143}{}{error:Maр Name}
{144}{}{error:Maр Name}
{145}{}{error:Maр Name}
{146}{}{error:Maр Name}
{147}{}{error:Maр Name}
{148}{}{error:Maр Name}
{149}{}{error:Maр Name}
{150}{}{error:Maр Name}
{151}{}{error:Maр Name}
{152}{}{error:Maр Name}
{153}{}{error:Maр Name}
{154}{}{error:Maр Name}
{155}{}{error:Maр Name}
{156}{}{error:Maр Name}
{157}{}{error:Maр Name}
{158}{}{error:Maр Name}
{159}{}{error:Maр Name}
{160}{}{error:Maр Name}
{161}{}{error:Maр Name}
{162}{}{error:Maр Name}
{163}{}{error:Maр Name}
{164}{}{error:Maр Name}
#
# City elevation names -- AUTOMAP Names!
#
# Format: 3 (max elevations), by city
#
# 00: TestMap
{200}{}{Где-то в пустоши.}
{201}{}{}
{202}{}{}
# 01: Tartar Parking 03, TARTAR03.MAP
{203}{}{Старая Парковка}
{204}{}{}
{205}{}{}
# 02: Tartar 1st floor, TARTAR11.MAP
{206}{}{Жилой Уровень}
{207}{}{}
{208}{}{}
# 03: Tartar 1st floor, TARTAR12.MAP
{209}{}{Жилой Уровень}
{210}{}{}
{211}{}{}
# 04: Tartar 1st floor, TARTAR13.MAP
{212}{}{Жилой Уровень}
{213}{}{}
{214}{}{}
# 05: Tartar 2nd floor, TARTAR22.MAP
{215}{}{Фермы}
{216}{}{}
{217}{}{}
# 06: Tartar 2nd floor, TARTAR23.MAP
{218}{}{Фермы}
{219}{}{}
{220}{}{}
# 07: Tartar 3rd floor, TARTAR32.MAP
{221}{}{Тех. Уровень}
{222}{}{Подсобка}
{223}{}{}
# 08: Tartar 3rd floor, TARTAR33.MAP
{224}{}{Тех. Уровень}
{225}{}{Подсобка}
{226}{}{}
# 09: Purgatoir, TARCHIST.MAP
{227}{}{Чистилище}
{228}{}{}
{229}{}{}
# 10: Tartar Surface, TAREXIT.MAP
{230}{}{Поверхность}
{231}{}{}
{232}{}{}
# 11: Tartar Parking 02, TARTAR02.MAP
{233}{}{Старая Парковка}
{234}{}{}
{235}{}{}
#
########################
# Undead Cave
########################
#
# 12: PN Passage
{236}{}{Проход}
{237}{}{}
{238}{}{}
# 13: PN Station
{239}{}{Платформа}
{240}{}{}
{241}{}{}
# 14: PN Hall
{242}{}{Зал Ожидания}
{243}{}{}
{244}{}{}
# 15: PN City
{245}{}{Вход в Метро}
{246}{}{}
{247}{}{}
# 16: PN City 2
{248}{}{Окрестности Метро}
{249}{}{}
{250}{}{}
# 17: PN City Basement
{251}{}{Подвал}
{252}{}{}
{253}{}{}
#
########################
# Sunset Jackals
########################
#
# 18: SJ Enter
{254}{}{Бухта}
{255}{}{}
{256}{}{}
# 19: SJ Main
{257}{}{Штаб}
{258}{}{}
{259}{}{}
# 20: SJ Repairs
{260}{}{Мастерские}
{261}{}{}
{262}{}{}
# 21: SJ Baraks
{263}{}{Казармы}
{264}{}{}
{265}{}{}
# 22: SJ Store
{266}{}{Склад}
{267}{}{}
{268}{}{}
# 23: SJ SCI21
{269}{}{Лаборатория SCI-21}
{270}{}{}
{271}{}{}
# 24: SJ Bunker
{272}{}{Бункер}
{273}{}{}
{274}{}{}
#
########################
# Chris hidden cave
########################
#
# 25: SJ Plato
{275}{}{Плато}
{276}{}{}
{277}{}{}
# 26: SJ Chris Cave
{278}{}{Тайник Криса}
{279}{}{}
{280}{}{}
#
########################
# New World Order
########################
#
# 27: NWO Enter
{281}{}{Торговая Площадь}
{282}{}{}
{283}{}{}
# 28: NWO Shop
{284}{}{Консервный Цех}
{285}{}{Этаж Руководителей}
{286}{}{Подвал Цеха}
# 29: NWO 2nd Floor
{287}{}{Этаж Руководителей}
{288}{}{}
{289}{}{}
# 30: NWO Basement
{290}{}{Подвал Цеха}
{291}{}{}
{292}{}{}
# 31: NWO Backyard
{293}{}{Цеховой Двор}
{294}{}{}
{295}{}{}
#
########################
# Livos
########################
#
# 32: Livos Enter
{296}{}{Вход}
{297}{}{}
{298}{}{}
# 33: Livos Trade
{299}{}{Торговая Палата}
{300}{}{}
{301}{}{}
# 34: Livos Living Rooms
{302}{}{Жилой Сектор}
{303}{}{}
{304}{}{}
# 35: Livos Techroom
{305}{}{Техкомната}
{306}{}{}
{307}{}{}
# 36: Livos Filtering
{308}{}{Фильтрационная}
{309}{}{}
{310}{}{}
# 37: Livos Monster Cave
{311}{}{Пещера Монстров}
{312}{}{}
{313}{}{}
#
########################
# Rainbow Raiders
########################
#
# 38: RB Main
{314}{}{Центральная Площадь}
{315}{}{}
{316}{}{}
# 39: RB Arena
{317}{}{Арена}
{318}{}{}
{319}{}{}
# 40: RB Arena Fight
{320}{}{Арена (бой)}
{321}{}{}
{322}{}{}
# 41: RB Fabric
{323}{}{Фабрика}
{324}{}{}
{325}{}{}
# 42: RB Basement
{326}{}{Подземный Переход}
{327}{}{}
{328}{}{}
# 43: RB Ants Ferm
{329}{}{Вход в пещеры}
{330}{}{Муравьиная Ферма}
{331}{}{}
#
########################
# Oazis
########################
#
# 44: Oazis Enter
{332}{}{Проход}
{333}{}{}
{334}{}{}
# 45: Oazis Main
{335}{}{Селение}
{336}{}{}
{337}{}{}
# 46: Oazis Cave
{338}{}{Пещеры}
{339}{}{}
{340}{}{}
#
########################
# Freds House
########################
#
# 47: Fred House
{341}{}{Дом Фреда}
{342}{}{}
{343}{}{}
#
########################
# Warbase
########################
#
# 48: Warbase Enter
{344}{}{Ёижина}
{345}{}{}
{346}{}{}
# 49: Warbase Bunker
{347}{}{Бункер}
{348}{}{}
{349}{}{}
#
########################
# Tin Industries
########################
#
# 50: Tin Enter
{350}{}{Проходные}
{351}{}{}
{352}{}{}
# 51: Tin Shop
{353}{}{Жестяный Цех}
{354}{}{}
{355}{}{}
# 52: Tin Basement
{356}{}{Подвал}
{357}{}{}
{358}{}{}
#
########################
# Renessance
########################
#
# 53: Renessance Enter
{359}{}{Скалы}
{360}{}{}
{361}{}{}
# 54: Renessance City
{362}{}{Чудо-Град}
{363}{}{}
{364}{}{}
#
########################
# Olympus Tower
########################
#
# 55: Olympus Enter
{365}{}{Парадный Вход}
{366}{}{}
{367}{}{}
# 56: Olympus Horton
{368}{}{Ёолл "Ёортон"}
{369}{}{}
{370}{}{}
# 57: Olympus Organics
{371}{}{Институт Органики}
{372}{}{}
{373}{}{}
# 58: Olympus Spawn
{374}{}{Плодильня}
{375}{}{}
{376}{}{}
# 59: Olympus Engineering
{377}{}{КБ}
{378}{}{}
{379}{}{}
# 60: Olympus Terass
{380}{}{Смотровая}
{381}{}{}
{382}{}{}
# 61: Olympus Physics
{383}{}{Институт Физики}
{384}{}{}
{385}{}{}
# 62: Olympus Hi Tech
{386}{}{Ёай-Тек}
{387}{}{}
{388}{}{}
# 63: Olympus Server
{389}{}{Серверная}
{390}{}{}
{391}{}{}
# 64: Olympus Top Floor
{392}{}{103-й этаж}
{393}{}{}
{394}{}{}
# 65: Olympus Anderson
{395}{}{Обитель Богов}
{396}{}{}
{397}{}{}
#
########################
# -Special maps-
########################
#
# 66: Special Trostniki
{398}{}{Заросли}
{399}{}{Заросли}
{400}{}{Заросли}
# 67: Special Ursul Huntings
{401}{}{Поляна}
{402}{}{Поляна}
{403}{}{Поляна}
# 68: Special Chimeras
{404}{}{Пещеры}
{405}{}{Пещеры}
{406}{}{Пещеры}
# 69: Special Death Meadow
{407}{}{Пустырь}
{408}{}{Пустырь}
{409}{}{Пустырь}
########################
# -Random maps-
########################
# 70: Random Desert 1
{410}{}{Пустошь}
{411}{}{}
{412}{}{}
# 71: Random Desert 2
{413}{}{Пустошь}
{414}{}{}
{415}{}{}
# 72: Random Desert 3
{416}{}{Пустошь}
{417}{}{}
{418}{}{}
# 73: Random Desert 4
{419}{}{Пустошь}
{420}{}{}
{421}{}{}
# 74: Random Desert 5
{422}{}{Пустошь}
{423}{}{}
{424}{}{}
# 75: Random Desert 6
{425}{}{Пустошь}
{426}{}{}
{427}{}{}
# 76: Random Desert 7
{428}{}{Пустошь}
{429}{}{}
{430}{}{}
# 77: Random Desert 8
{431}{}{Пустошь}
{432}{}{}
{433}{}{}
# 78: Random Desert 9
{434}{}{Пустошь}
{435}{}{}
{436}{}{}
# 79: Random Desert 10
{437}{}{Пустошь}
{438}{}{}
{439}{}{}
# 80: Random Meadow 1
{440}{}{Заросли}
{441}{}{}
{442}{}{}
# 81: Random Meadow 2
{443}{}{Заросли}
{444}{}{}
{445}{}{}
# 82: Random Meadow 3
{446}{}{Заросли}
{447}{}{}
{448}{}{}
# 83: Random Meadow 4
{449}{}{Заросли}
{450}{}{}
{451}{}{}
# 84: Random Meadow 5
{452}{}{Заросли}
{453}{}{}
{454}{}{}
# 85: Random City 1
{455}{}{Руины}
{456}{}{}
{457}{}{}
# 86: Random City 2
{458}{}{Руины}
{459}{}{}
{460}{}{}
# 87: Random City 3
{461}{}{Руины}
{462}{}{}
{463}{}{}
# 88: Random Coast 1
{464}{}{Берег}
{465}{}{}
{466}{}{}
# 89: Random Coast 2
{467}{}{Берег}
{468}{}{}
{469}{}{}
# 90: Fred 2nd floor
{470}{}{2ой этаж}
{471}{}{}
{472}{}{}
# 91: Random Rocks 1
{473}{}{Скалы}
{474}{}{}
{475}{}{}
# 92: Random Rocks 2
{476}{}{Скалы}
{477}{}{}
{478}{}{}
# 93: Random Rocks 3
{479}{}{Скалы}
{480}{}{}
{481}{}{}
# 94: Random Rocks 4
{482}{}{Скалы}
{483}{}{}
{484}{}{}
# 95: Random Rocks 5
{485}{}{Скалы}
{486}{}{}
{487}{}{}
# 96: Random Rocks 6
{488}{}{Скалы}
{489}{}{}
{490}{}{}
# 97: Random Rocks 7
{491}{}{Скалы}
{492}{}{}
{493}{}{}
# 98: Random Rocks 8
{494}{}{Скалы}
{495}{}{}
{496}{}{}
# 99: Random Rocks 9
{497}{}{Скалы}
{498}{}{}
{499}{}{}
# 100: Random Rocks 10
{500}{}{Скалы}
{501}{}{}
{502}{}{}
# 101: SJ Main 2
{503}{}{Штаб}
{504}{}{}
{505}{}{}
# 102: PS Market
{506}{}{Торговый Район}
{507}{}{Подвал}
{508}{}{}
# 103: PS Hospital
{509}{}{Район Больницы}
{510}{}{Подвал}
{511}{}{}
# 104: Biolabory N2
{512}{}{Поверхность}
{513}{}{Подземный уровень}
{514}{}{Подземный уровень}
# 105: Spec FireFly
{515}{}{Где-то в Радиусе}
{516}{}{}
{517}{}{}
# 106: Spec Road
{518}{}{Где-то в Радиусе}
{519}{}{Бункер}
{520}{}{}
# 107: Spec MadMax
{521}{}{Где-то в Радиусе}
{522}{}{}
{523}{}{}
# 108: Spec Dredd
{524}{}{Руины}
{525}{}{Пещера}
{526}{}{}
# 109: Spec Tankgirl
{527}{}{Где-то в Радиусе}
{528}{}{}
{529}{}{}
# 110: Spec ElyBook
{530}{}{Где-то в Радиусе}
{531}{}{}
{532}{}{}
# 111: Spec LostVillage
{533}{}{Центр}
{534}{}{}
{535}{}{}
# 112: Spec SixString
{536}{}{Где-то в Радиусе}
{537}{}{}
{538}{}{}
# 113: Spec Lumeniers
{539}{}{временный Штаб}
{540}{}{}
{541}{}{}
# 114: Spec DesertPirates
{542}{}{Лагерь}
{543}{}{}
{544}{}{}
# 115: Spec FireFly
{545}{}{Где-то в Радиусе}
{546}{}{}
{547}{}{}
# 116: Spec Road
{548}{}{Где-то в Радиусе}
{549}{}{Бункер}
{550}{}{}
# 117: Spec MadMax
{551}{}{Где-то в Радиусе}
{552}{}{}
{553}{}{}
# 118: Spec Dredd
{554}{}{Руины}
{555}{}{Пещера}
{556}{}{}
# 119: Spec Tankgirl
{557}{}{Где-то в Радиусе}
{558}{}{}
{559}{}{}
#
#	Short City names
#
{1500}{}{Тартар}
{1501}{}{Станция метро}
{1502}{}{Псы Заката}
{1503}{}{Тайник Криса}
{1504}{}{Новый Мировой Порядок}
{1505}{}{Лайвос}
{1506}{}{Рэйнбоу Рэйдерз}
{1507}{}{Оазис}
{1508}{}{Паршивый Пес}
{1509}{}{Штаб Армии}
{1510}{}{Тин Индастриз}
{1511}{}{Ренессанс}
{1512}{}{"Олимп"}
{1513}{}{Тростники}
{1514}{}{Угодья Урсула}
{1515}{}{Обитель Xимер}
{1516}{}{Поляна Смерти}
{1517}{}{Случайная местность}
{1518}{}{Случайная местность}
{1519}{}{Случайная местность}
{1520}{}{Случайная местность}
{1521}{}{Случайная местность}
{1522}{}{Тартар}
{1523}{}{Пирсон Таун}
{1524}{}{Биолабория #2}
{1525}{}{Могилы}
{1526}{}{Скрытое Убежище}
{1527}{}{Брошенный Автомобиль}
{1528}{}{Пещера в Горе}
{1529}{}{Девушка и Танк}
{1530}{}{Скиталец}
{1531}{}{Заброшенное Поселение}
{1532}{}{Байкер с Гитарой}
{1533}{}{Аванпост}
{1534}{}{Палаточный лагерь}
{1535}{}{Могилы}
{1536}{}{Скрытое Убежище}
{1537}{}{Брошенный Автомобиль}
{1538}{}{Пещера в Горе}
{1539}{}{Девушка и Танк}
{1540}{}{"Олимп" ч.2}
{1541}{}{error: city name}
{1542}{}{error: city name}
{1543}{}{error: city name}
{1544}{}{error: city name}
{1545}{}{error: city name}
{1546}{}{error: city name}
{1547}{}{error: city name}
{1548}{}{error: city name}