#
#   Messages from perk.c
#
#
#   PERK NAMES
#
{101}{}{Осторожность}
{102}{}{Доп. Рукопашн. Атаки}
{103}{}{Доп. Рукопашн. Поврежд.}
{104}{}{Бонус движения}
{105}{}{Бонус Дальнобойности}
{106}{}{Бонус скорости}
{107}{}{Быстрая реакция}
{108}{}{Быстрое лечение}
{109}{}{Больше Крит. Ударов}
{110}{}{Ночное зрение}
{111}{}{Важный вид}
{112}{}{Уст. к радиации}
{113}{}{Крутизна}
{114}{}{Переноска}
{115}{}{Меткость}
{116}{}{Бесшумный бег}
{117}{}{Живучесть}
{118}{}{Торговля}
{119}{}{Образование}
{120}{}{Лекарь}
{121}{}{Везунчик}
{122}{}{Лучшие Крит. Удары}
{123}{}{Эмпатия}
{124}{}{Мясник}
{125}{}{Снайпер}
{126}{}{Киллер}
{127}{}{Человек действия}
{128}{}{Защита Сознания}
{129}{}{Сила Жизни}
{130}{}{Увертливость}
{131}{}{Змееглот}
{132}{}{Самоделкин}
{133}{}{Медицина}
{134}{}{Вор Профессионал}
{135}{}{Оратор}
{136}{}{Метание}
{137}{}{ERROR -- UNIMPED}
{138}{}{Карманник}
{139}{}{Привидение}
{140}{}{Культ личности}
{141}{}{Попрошайка}
{142}{}{Непоседа}
{143}{}{Дитя Цветов}
{144}{}{Следопыт}
{145}{}{Друг Животных}
{146}{}{Скаут}
{147}{}{Таинственный Странник}
{148}{}{Рейнджер}
{149}{}{Аккуратист}
{150}{}{Убедительная речь}
{151}{}{Самоучка}
{152}{}{Дополнительное умение!}
{153}{}{Мутация!}
{154}{}{Привыкание к "Спотс-Ап"}
{155}{}{Привыкание к "Стронгхольдину"}
{156}{}{Привыкание к "Брейниаку"}
{157}{}{Привыкание к "Комбатиду"}
{158}{}{Привыкание к "Резистанолу"}
{159}{}{Большая Дальнобойность}
{160}{}{Большая точность}
{161}{}{Большая скорость}
{162}{}{Отдача Оружия}
{163}{}{Энергодоспехи}
{164}{}{Боевые Доспехи}
{165}{}{Стрельба с прицелом}
{166}{}{Быстрая перезарядка оружия}
{167}{}{Прицел Ночного Видения}
{168}{}{Оружейный Флеймбой}
{169}{}{Усиленная Броня I}
{170}{}{Усиленная Броня II}
{171}{}{Привыкание к "Капле"}
{172}{}{Семертельное Привыкание}
{173}{}{Защищающее Обаяние}
{174}{}{Освежеватель}
{175}{}{Подкожная Броня}
{176}{}{Усиленная Штурмовая Броня}
{177}{}{Защитные Имплантанты Феникс}
{178}{}{Улучшение Имплантанта Феникс}
{179}{}{Прививки Города Убежища}
{180}{}{Выброс Адреналина}
{181}{}{Предусмотрительная Природа}
{182}{}{Понимание}
{183}{}{Эксперт-подрывник}
{184}{}{Игрок}
{185}{}{Увеличение Силы}
{186}{}{Увеличение Мудрости}
{187}{}{Увеличение Выносливости}
{188}{}{Увеличение Обаяния}
{189}{}{Увеличение Интеллекта}
{190}{}{Увеличение Ловкости}
{191}{}{Увеличение Удачи}
{192}{}{Безвредный}
{193}{}{Здесь и сейчас}
{194}{}{Ускользание}
{195}{}{Секс-монстр Кама Сутры}
{196}{}{Светоч Кармы}
{197}{}{Легкий шаг}
{198}{}{Знаток анатомии }
{199}{}{Притягивающая Личность}
{200}{}{Ведение Переговоров}
{201}{}{Упаковщик}
{202}{}{Пироман}
{203}{}{Быстрое Восстановление}
{204}{}{Продавец}
{205}{}{Каменная Стена}
{206}{}{Вор}
{207}{}{Обращение с Оружием}
{208}{}{Обучение в Городе Убежище}
{209}{}{Повышенная Алкоголем Сила Удара}
{210}{}{Повышенная Алкоголем Сила Удара II}
{211}{}{Пониженная Алкоголем Сила Удара}
{212}{}{Пониженная Алкоголем Сила Удара II}
{213}{}{Повышенные Авто-Доктором хит-поинты}
{214}{}{Повышенные Авто-Доктором хит-поинты II}
{215}{}{Пониженные Авто-Доктором хит-поинты}
{216}{}{Пониженные Авто-Доктором хит-поинты II}
{217}{}{Эксперт Экспедиции Экскрементов}
{218}{}{Усиленный Нокаут Оружия}
{219}{}{Приносящий несчастье}
#
#   PERK DESCRIPTIONS
#
{1101}{}{Вас предупреждают, давая детальнную информацию о любом об'екте, который вы изучаете. Вы видите их самые уязвимые места и получаете информацию об имеющемся у них оружии.}
{1102}{}{Вы знакомы с тайными боевыми искусствами востока, или попросту чаще бьете. Как бы там ни было, ваши рукопашные атаки занимают на 1 ОД меньше.}
{1103}{}{Большой опыт рукопашных схваток научил вас уделять внимание прежде всего наносимому повреждению. При ударе в рукопашной враг теряет на 2 очка жизней больше.}
{1104}{}{За каждый уровень бонуса вы получаете 2 ОД, которые используются только для перемещения. Кратко - с каждым уровнем бонуса Вы получаете 2 дополнительных шага.}
{1105}{}{Ваши тренировки в обращении со стрелковым оружием сделали свое дело. На каждый уровень данного бонуса наносимые вами при стрельбе повреждения увеличиваются на 2.}
{1106}{}{Теперь вы нажимаете на курок немного быстрее, но остаетесь по-прежнему точны. Время, расходуемое на атаку, уменьшается на 1 Очко Движения.}
{1107}{}{Враги всегда будут ошибаться, ведь прав тот, кто выстрелил первым, а ваш порядок действий увеличивается на 2 с каждым уровнем.}
{1108}{}{С каждым уровнем этого бонуса, вы увеличиваете на 2 свой Уровень Лечения. Это добавочное средство лечения, позволяющее вам быстрее выздоравливать.}
{1109}{}{Если у вас есть этот бонус, вероятность нанесения критических повреждений противнику увеличивается на 5 процентов. Очень неплохо для снайперов - один выстрел, один труп.}
{1110}{}{С помощью бонуса Ночного Зрения вы сможете лучше видеть в темноте. Это повысит общую ночную видимость на 20%.}
{1111}{}{Вы командуете (привлекаете) внимание, просто входя в комнату. Первоначальная реакция другого человека улучшается на 10% для каждого из уровней этого бонуса.}
{1112}{}{Вы лучше переносите пагубное воздействие радиации на организм и ее эффекты. Каждый уровень этого бонуса увеличивает вашу Устойчивость к Радиации на 15%.}
{1113}{}{Крутизна позволяет вам не замечать мелкие жизненный неприятности. Вы получаете 10 процентов устойчивости к повреждениям.}
{1114}{}{Способность таскать тяжелые грузы - далеко не лишняя в условиях пустыни. Прибавка 50 фунтов груза.}
{1115}{}{Искусство бить в цель на большом расстоянии. При определении дистанции вы получаете +2 к Наблюдательности. Теперь убивать издалека гораздо легче и приятнее.}
{1116}{}{С помощью этого бонуса вы можете передвигаться гораздо быстрее, оставаясь не слышимы. Вы можете красться и бежать одновременно.}
{1117}{}{Привычка к долгой жизни в пустыне выработала у вас невероятную живучесть. Это дает вам способность выживать в тяжелых условиях, увеличивая на 25% способность Скитальца.}
{1118}{}{Вы мастерски освоите искусство торговли и сможете покупать товары гораздо дешевле. С этим бонусом вы получаете 25% скидку на покупку товаров в магазине или у торговцев.}
{1119}{}{Каждый уровень Образования будет прибавлять вам 2 очка при получении нового уровня опытности. Данный бонус будет вам полезен на ранней стадии игры.}
{1120}{}{Излечение страждущих легче дается вам с этим бонусом. На каждом уровне вы будете получать 4-10 очков жизни, применяя способности Доктор или Первая Помощь.}
{1121}{}{У вас есть талант обнаруживать деньги в самых неожиданных местах, даже во время случайных стычек в пустыне.}
{1122}{}{Причиняемые вашим противникам критические удары более смертоносны. Вы получаете 20% бонус для крит. повреждений, хотя вероятность нанесения такового не увеличивается.}
{1123}{}{Вы хорошо изучили других людей и знаете их реакцию на ваши реплики. При разговоре вы "видите" эмоциональную реакцию собеседника и уровень его настроения.}
{1124}{}{Мясник вышел на охоту! Страшные удары ваших кулаков и ног всегда будут причинять противику критические повреждения, сеять разрушения и хаос на вашем пути.}
{1125}{}{Вы в совершенстве овладели стрелковым оружием. С данным бонусом при надлежащей проверке вашей Удачи каждое точное попадание будет критическим для вашего противника.}
{1126}{}{Если вы подкрадетесь к противнику и рукой или ногой ударите его в спину, то нанесете ему двойные повреждения. Таков этот страшный бонус - Тихая Смерть.}
{1127}{}{Человек действия все операции совершает бегом, наподобие новобранца. Это придает ему дополнительные очки действия, которые можно использовать в любых целях.}
{1128}{}{Ментальный блок - способность заглушать всякое внешнее мысленное вмешательство. Вы должно быть научлились этой способности во время хорошей ночной пьянки.}
{1129}{}{С каждым уровнем данного бонуса вы получите дополнительные 4 очка Жизни. Xоть это и немного, всякое случается, а вдруг пригодится. Выживать-то надо!}
{1130}{}{Во время боя в вас будет гораздо сложнее попасть. Независимо от одетых на вас в этот момент доспехов, вы получаете бонус в 5 процентов к классу брони.}
{1131}{}{Любые отравляющие вещества действуют на вас крайне ослабленно. Ваша устойчивость к яду повышается на 25 процентов.}
{1132}{}{Это умение дает вам бонус в +10% к умениям Починка и Наука.}
{1133}{}{Медицина добавляет бонус в 10% умениям Перевязка и Доктор. Умение забинтовать раны никогда не было лишним в бою.}
{1134}{}{Вор непревзойденный мастер по взлому замков и чистке чужих карманов. Это умение добавляет 15% к умениям Воровство и Взлом. }
{1135}{}{Наличие умения Оратор добавляет 20% к умению Ведение Разговора. Телок можно заговаривать.}
{1136}{}{Каждый уровень умения Метание добавляет 2 дополнительных очка к Силе для расчета расстояния до цели. Это умение не позволит превысит максимальную дальнобойность.}
{1137}{}{ERROR.UNIMPED!}
{1138}{}{Вы более опытны в воровстве чем обычный карманник. Благодаря этому умению сторона с которой вы стоите и размер воруемого предмета уже не имеют значение.}
{1139}{}{Вы можете передвигаться в тени как привидение. Ваша способность передвигаться Крадучись увеличивается на 20%.}
{1140}{}{Ваша репутация всегда позитивна, с кем бы Вы не вели беседу. Даже самые злые персонажи будут считать вашего "сверх-доброго" героя за своего.}
{1141}{}{Это умение позволяет находить в два раза больше патронов чем обычно.}
{1142}{}{С этим умением у вас больше шансов находить потайные и просто недоступные остальным места.}
{1143}{}{С этим умением вы в два раза слабее привыкаете к хим. препаратам и в два раза быстрее отходите от их воздействия.}
{1144}{}{Следопыт отыскивает самые короткие пути, снижая время вашего передвижения по карте на 25%.}
{1145}{}{Звери не будут атаковать своего друга пока он сам им не угрожает.}
{1146}{}{У вас улучшается зрение, увеличивается поверхность открытия карты, повышается шанс попасть в необычную ситуацию.}
{1147}{}{Благодаря этому умению вы получаете покровительство Таинственного Странника, появляющегося во время боя. Если он погибнет - не надейтесь, что он вернется.}
{1148}{}{Это умение добавляет 15% ко способности Выживания на Природе. Вам также больше везет в нахождении странных мест и людей.}
{1149}{}{Вы лучше упаковываете свои пожитки. Доступ к барахлу во время боя отнимает не 4 ОД, а 2.}
{1150}{}{Вы умеете увеличивать варианты ответа в разговоре толкои не понимая о чем он вообще.}
{1151}{}{Вы Быстрый Ученик и это позволяет вам набирать по 5% дополнительного опыта при каждом получении очков опыта!}
{1152}{}{Ваши способности выросли до уровня, когда вы можете выбрать дополнительную способность, которая будет расти в два раза быстрее обычной.}
{1153}{}{Радиация изменила вас! Одна из ваших черт подверглась мутациии.}
{1154}{}{Вы старадаете по лишней бытылке чудесного вкусненького Спотс-Апа...}
{1155}{}{Вы жить не можете без той чудесной мази, что делает Ваши мышцы крепче а кожу мягкой и упругой. И как так получилось?}
{1156}{}{Вы не можете сосредоточиться и голова постоянно кружится. Вам срочно нужна еще одна доза "Брейниака".}
{1157}{}{Вас мучают чудовищные страдания без очередной дозы "Комбатида". Вы не готовы отдать душу дьяволу за еще одну дозу, но точно могли бы ее одолжить ему на время...}
{1158}{}{Вы ощущаете невыносимый зуд, а кожа начала покрываться гнойными фурункулами. Вы уверены, что без очередного глотка "Резистанола" Ваша кожа просто слезет.}
{1159}{}{Дальнобойное Оружие.}
{1160}{}{Снайперское оружие.}
{1161}{}{Бронебойное оружие.}
{1162}{}{Отдача.}
{1163}{}{Энергетическая броня.}
{1164}{}{Боевая броня.}
{1165}{}{Дальность оптического прицела.}
{1166}{}{Быстрая перезрядка оружия.}
{1167}{}{Инфракрасный прицел.}
{1168}{}{Подствольный огнемет Флэймбой.}
{1169}{}{Улучшенная броня I}
{1170}{}{Улучшенная броня II}
{1171}{}{Вам ужасно плоху, ломит даже кончики волос. Вы начинаете размышлять, кого нужно убить, чтобы заполучить еще одну дозу "Капли"...}
{1172}{}{Я сгораю от желания открыть еще одну пачку карт.}
{1173}{}{Защищающее обаяние}
{1174}{}{Вы знаете и умеете собирать все мало-мальски полезное с тушек убитых животных.}
{1175}{}{Вы имеете врожденную защиту от физического воздействия.}
{1176}{}{Вы имеете дополнительную врожденную защиту от физического воздействия.}
{1177}{}{Вы имеете врожденную защиту от энергетических атак.}
{1178}{}{Вы имеете дополнительную врожденную защиту от энергетических атак.}
{1179}{}{Вы получаете 10% сопротивления яду и радиации.}
{1180}{}{С помощью этого умения вы получаете дополнительное очко Силы как только количество ваших хит пойнтов опускается ниже половины.}
{1181}{}{Вы более чутки и у врагов меньше шансов подкрасться к вам незамеченными. При наличии этого Умения вы получаете +3 очка Точности при случайной встрече.}
{1182}{}{Вы обращаете больше внимания на малейшие детали при чтении. Так же вы получаете на 50% больше опыта при освоении чего-либо путем чтения книг.}
{1183}{}{Вы настоящий эксперт по части подрывного дела. Бомбы, установленные вами всегда взрываются в нужное время и наносят дополнительный ущерб.}
{1184}{}{Вы можете обыгрывать самых опытных игроков. Вы получаете на +20% в дополнение к вашим способностям игрока.}
{1185}{}{При наличии этого умения вы получаете +1 к вашей Силе.}
{1186}{}{При наличии этого умения вы получаете +1 к вашей Точности.}
{1187}{}{При наличии этого умения вы получаете +1 к вашей Выносливости.}
{1188}{}{При наличии этого умения вы получаете +1 к вашему Обаянию.}
{1189}{}{При наличии этого умения вы получаете +1 к вашему Интеллекту.}
{1190}{}{При наличии этого умения вы получаете +1 к вашей Ловкости.}
{1191}{}{При наличии этого умения вы получаете +1 к вашей Удаче.}
{1192}{}{Ваш не самый честный талант помогает вам безнаказанно шарить по карманам людей и добавляет +20% к вашим изначальным воровским данным.}
{1193}{}{С этим умением вы сразу же получаете дополнительный уровень опыта.}
{1194}{}{Если оба слота для оружия пусты, каждое неиспользованное ОД дает вам +2 защиты и добавляет +1/12 опыта рукопашного боя.}
{1195}{}{Что касается сексуальных наслаждений, то тут вам равных не сыскать во всем мире.}
{1196}{}{Ваша Карма растет постоянно в удвоенном темпе независимо от направленности и причины.}
{1197}{}{Вы подвижны, осторожны и вам сопутствует удача. Это умения так же снижает шансы попадания в ловушку.}
{1198}{}{Вы имеете хорошее представление о строении живых существ. Это умение давет вам увеличение умения Доктор на 10%, и дополнительные +5% урона на удар по живым существам.}
{1199}{}{Вы можете взять себе в команду еще одного компаньона, но помните, что и пять человек - уже толпа.}
{1200}{}{Вы невероятно искусны в ведении переговоров. Вы не только можете выгодно сбить цену, но и уговорить кого угодно сделать то, что вам требуется.}
{1201}{}{Вы умело упаковываете свои вещи. Это позволяет носить вам несколько больше вещей чем обычно.}
{1202}{}{Вы наносите дополнительный огнеметами, а враги всегда умирают в особо тяжких мучениях от ожогов.}
{1203}{}{Вы быстро приходите в себя после нокаутов.}
{1204}{}{Вы прирожденный торговец. Благодаря этому умению вы получаете +20% к вашему таланту Обмена.}
{1205}{}{При наличии этого умения вероятность нокаута в бою уменьшается.}
{1206}{}{В ваших венах течет кровь профессионального вора. Это умение добавляет +10% к Краже, Взлому, умению Красться и обезвреживанию ловушек.}
{1207}{}{Обращение с оружием дается вам гораздо проще чем остальным и добавляет +3 к Силе.}
{1208}{}{Вы прошли медицинское обучение в Городе Убежище.}
{1209}{}{Ваши очки жизни немного увеличились в результате продолжительного запоя.}
{1210}{}{Ваши очки жизни еще немного увеличились в результате продолжительного запоя.}
{1211}{}{Ваши очки жизни немного уменьшились в результате продолжительного запоя.}
{1212}{}{Ваши очки жизни еще больше уменьшились в результате продолжительного запоя.}
{1209}{}{Ваши очки жизни немного увеличились в результате продолжительного использования Авто-Дока.}
{1210}{}{Ваши очки жизни еще немного увеличились в результате продолжительного использования Авто-Дока.}
{1211}{}{Ваши очки жизни немного уменьшились в результате продолжительного использования Авто-Дока.}
{1212}{}{Ваши очки жизни еще немного уменьшились в результате продолжительного использования Авто-Дока.}
{1217}{}{Ты можешь обыгрывать самых умелых из них.}
{1218}{}{Нокаут от удара оружием.}
{1219}{}{Радует то, что у всех вокруг полно критических ошибок в бою. Не радует то, что и у тебя тоже.}
