#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{Быстрый метаболизм}
{101}{}{Крушила}
{102}{}{Маленький}
{103}{}{Однорукий}
{104}{}{Точность}
{105}{}{Камикадзе}
{106}{}{Тяжел на руку}
{107}{}{Быстрый стрелок}
{108}{}{Громила}
{109}{}{Дурной глаз}
{110}{}{Добродушный}
{111}{}{Неуст. к химии}
{112}{}{Уст. к химии}
{113}{}{Мех. память}
{114}{}{Умелец}
{115}{}{Талант}
#
#   TRAIT DESCRIPTIONS
#
{200}{}{Ваш уровень метаболизма вдвое превышает норму. Это означает, что вы будете менее устойчивы к воздействию радиации и ядов, но лечиться будете быстрее.}
{201}{}{Двигаемся помедленнее, но зато повнушительнее. Бьем нечасто, но зато так, чтобы на всю жизнь запомнили! Количество ваших очков Действия уменьшается, но зато Сила увеличивается.}
{202}{}{Вы не так велики, как другие люди, хотя это никогда вам особо не мешало. Вы не в состоянии таскать тяжелые грузы, зато более проворны.}
{203}{}{Вы хорошо работаете только одной из рук. Благодаря этому вы неплохо владеете обычным оружием, но с двуручным начинаются проблемы.}
{204}{}{Все ваши атаки очень точны. Повреждений наносится поменьше, но при этом больше вероятность критического удара.}
{205}{}{В бою вы не обращаете внимания на окружающую обстановку и действуете напролом. Снижается количество ваших очков брони вплоть до минимума, но увеличивается порядок действий.}
{206}{}{Вы бьете сильно, но не очень точно. Жестокие удары причиняют огромные повреждения врагам, однако почти никогда не оказываются критическими для их состояния.}
{207}{}{У вас нет времени для нормального прицеливания, поэтому Вы стреляете наугад, лишь бы побыстрее. Для применения оружия вам требуется на одно очко действий меньше.}
{208}{}{По странной случайности, люди вокруг вас умирают страшной, мучительной смертью. Для них вы находите худший вариант кончины.}
{209}{}{Xорошая сторона дела заключается в том, что ваши враги постоянно ошибаются. Плохо то, что вы ошибаетесь не меньше их!}
{210}{}{В детстве Вы занимались тихими, размеренными занятиями и не делали зарядку. Ваши боевые умения понижэены, но зато Первая Помощь, Доктор, Беседа и Торговля заметно лучше.}
{211}{}{Вы легче попадаете в зависимость от химикалий. Вероятность привыкания к разным веществам вдвое больше, чем норма, но вы проще переносите их эффект.}
{212}{}{Xимикалии приносят вам только половину нормального эффекта, но вероятность привыкания также снижена на 50% от нормы.}
{213}{}{Ваш организм страдает от общих недостатков, но тело запоминает все движения и жесты. Вы получаете бонус автоматического роста умений, но основные показатели снизятся на один пункт.}
{214}{}{Так как Вы неустанно работали над улучшением своих умений, то начнете игру с улучшенными параметрами. С другой стороны, вы получаете меньше доп. умений - одно за каждые 4 уровня.}
{215}{}{Вы очень одарены различными способностями и превосходите обычный уровень. Все ваши параметры больше на единицу, но вы теряете 10% для умений и получаете на 5 очков меньше за уровень.}
