# Данный файл описывает сообщения,
# использующиеся в скриптах сценери
#
# Created by Artem "Rainman" Samoylov
# 30/07/2013
#
# ЧТО ЭТО?
# Это - аккумулятор для починки в Биолабории 2
#
# Описание 1
{1}{}{Вы видите: аккумулятор.}
{2}{}{Вы видите: рабочий аккумулятор.}

# Описание 2
{3}{}{Он сломан, но Вы могли бы попробовать его починить при навыке ремонта или науки не ниже 55.}
{4}{}{Он сломан, но Вам кажется, что его можно починить.}
{5}{}{Ваши золотые руки привели аккумулятор в рабочее состояние! Ваши навыки ремонта все же пригодились.}

# Действия
{6}{}{}
{7}{}{}
{8}{}{}
{9}{}{}
{10}{}{Вас ощутимо дернуло током!}
{11}{}{Порванные оголенные провода намекают, что их лучше не трогать.}
{12}{}{Да! Умело применив электроотмычку, Вы успешно восстановили цепь питания!}
{13}{}{}
{14}{}{Вы долго и напряженно всматриваетесь в мотки проводов, но ничего не происходит. Вы недостаточно умелы для такой починки.}
{15}{}{Слегка напрячь извилины, вспомнить комиксы по "оранжевый электроник", соединить синий с черным... Вуаля! Все заработало!}
{16}{}{Та-ак, красный или синий провод?... Упс, цепь замкнуло на Ваши пальцы, но похоже все заработало.}
{17}{}{}
{18}{}{}
{19}{}{}
{20}{}{}
