# Данный файл описывает сообщения,
# использующиеся в скриптах итемов
#
# Created by Artem "Rainman" Samoylov
# 16/11/2010
#
#Общие положения
#
{1}{}{Выбирай строчку: 1 - бартер; 2 - просто выход из диалога.}
{2}{}{::вариант 1::}
{3}{}{::вариант 2::}
