#############################################################
#  Message File: obj_dude.msg                               #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: April 14, 1998                                  #
#                                                           #
#  Updated:                                                 #
#############################################################
#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{}
{101}{}{}
#############################################################
{110}{}{Вы чуствуете жуткий зуд.}
{120}{}{У вас сильные опухоли на ногах.}
{130}{}{Ваша обувь очень жмет; и опухоли просто горят.}
{140}{}{Опухоли на ногах перемещаются на другие пальцы ног. Но этот нескончаемый зуд исчез.}
{141}{}{О господи, это Бесс!}
{150}{}{Вы получили }
{151}{}{опыта за добычу ГЭККа.}
