# Данный файл описывает сообщения,
# использующиеся в скриптах сценери
#
# Created by Artem "Rainman" Samoylov
# 30/07/2013
#
# ЧТО ЭТО?
# Это - надгробие Надин в городе над метро. Нужно для квеста ДЖО.
#
# Описание 1
{1}{}{You see: a fancy tombstone.}
{2}{}{You see: a tombstone with a beautiful sign.}

# Описание 2
{3}{}{Looks like someone put a lot of effort into this gravestone.}
{4}{}{A plank of a beautiful and delicate craftsmanship is attached to the tombstone. It depicts a dove, flying in the clouds. There's also an inscription: "We'll meet in Heaven, my lovely Nadine".}

# Действия
{5}{}{}
{6}{}{}
{7}{}{}
{8}{}{}
{9}{}{}
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
{20}{}{}
