##############################
#Location: NMP
#Name: Sunny
#Short Description: Girl who lost her father in Pearson Town
#Date of creation: 17.08.2015
##############################
#For the game "Olympus 2207"
#Artem "Rainman" Samoilov
##############################
#
#CRITTER DESCRIPTION
#
# before meeting
{1}{}{You see: a dirty girl.}
{2}{}{Her clothes are covered in dirt and torn in several places.}
#
# after meeting
{3}{}{You see: Sunny.}
{4}{}{Her clothes are covered in dirt and torn in several places.}
#
#HERE BEGINS A DIALOGUE
#
{5}{}{Did you find a paramedic's bag?}
{6}{}{We cannot leave without a paramedic's bag.}
{7}{}{Thank you so much! Becky and I are forever in your debt!}
{8}{}{Thanks again! You saved our lives!}
#Node001
{10}{}{[A young girl rushes to you as soon as you get into her sight. It's rather dark here, but you notice that she looks like she's been tortured, or lacked any sleep for a really long time. In her trembling hands you see a metal pipe.] You are not insane. [she lowers her "weapon" and her shoulders limp down] Thank god... I almost gave up... Wait! Did you see a man there?}
{11}{002}{Sunny, is it?}

#Node002
{20}{}{[the girl starts enthusiastically nodding her head] Yes, I am Sunny. And you are?..}
{21}{003}{.}
{22}{003}{Henry asked me to help you.}
{23}{003}{Doesn't matter, the thing is that you need to get out of here.}

#Node003
{30}{}{[the girl, as if suddenly having come to her senses, rushes to the entrance to the basement and locks the door. She listens, then sighs] Sorry, just in case. I don't want these creatures to burst in here. So, you're here to get us out, right?}
{31}{004}{Yes, exactly. Your friend asked me to find you.}

#Node004
{40}{}{Henry... [the girl smiles, but next second her joy instantly evaporates] So you've met a man in the town?}
{41}{005}{Your father? No. What happened?}
{42}{005}{Your father? No. And judging by what I've seen there - he is probably already dead.}

#Node005
{50}{}{[you hear a faint moan nearby. You catch yourself thinking that you did not immediately notice that there is someone else here] Sunny... who is there? Your father? [you notice a girl lying on the floor; she leans slightly to the side, on her elbow]}
{51}{006}{[continue]}

#Node006
{60}{}{[Sunny turns her head] Becky, get some rest. You shouldn't waste your energy. Help came. From the NMP.}
{61}{007}{[continue]}

#Node007
{70}{}{[Becky lies back, mumbling something about how no one in the NWO cared about them and it's very strange that someone came. Sunny turns back to you, putting her hand to the head, holding her thumb up to the temple.] So... Where were we... Ah! Did you see my father there?}
{71}{008}{No.}

#Node008
{80}{}{Man. It's very bad. [she shakes her head] When we entered the city, these "locals" attacked us. At first there was only one - father fended him off. But then more of them began to appear, probably attracted to the sound of shots. He drew the attention of all monsters to him and ran into the alley. Running away, he shouted to us to leave as soon as possible. We got away from the street, trying to find a secluded place nearby, where we could wait. But then we bumped into a huge jackal. He followed us to this mall. We somehow managed to make it, as I slammed through its head with something heavy, when he attacked us. I turned out alright, but not Becky - she has a whole leg covered in her blood, looks like the muscles are damaged. We decided to wait for the father here; so far I made several forays down to the city, for medicines and water. The local pharmacy in the mall is looted completely. I only found some painkillers and bandages. }
{81}{009}{How much time did you spend in this basement?}
{82}{012}{Any idea where you can get something to help Becky?}

#Node009
{90}{}{Around two days, probably.}
{91}{011}{Yeah... I think your father hardly survived...}
{92}{012}{Any idea where you can get anything to help Becky?}

#Node010
{100}{}{[Sunny stretches out her arm to take the paramedic's bag from you.] Great! What about father?}
{101}{015}{No, I have not seen him.}
{102}{015}{You know, I prefer not to talk about it.}

#Node011
{110}{}{You know, you cound stop reminding me.}
{111}{012}{Any idea where you can get anything to help Becky?}

#Node012
{120}{}{Yes. I found an old city map in the mall. There's a hospital somewhere nearby. Sorry, but I do not know which way to go, this map was in a very bad condition and I didn't really understand where we are. But I explored the city with it as much as I could. And if I understood everything correctly -  the hospital is somewhere not far from where we were attacked. Maybe... Maybe you'll even find our father. What if there's such basement too?}
{121}{013}{So, what exactly is needed?}

#Node013
{130}{}{Paramedic's bag. Dad told me about them. He said that if we find a few, it would help us get into the NMP.}
{131}{014}{Okay, I'll look for it.}
{132}{010}{Is that so?}

#Node014
{140}{}{Good luck out there. }
{141}{999}{[end of dialogue]}

#Node015
{150}{}{[Sunny hides her eyes. Her joy from receiving the bag quickly disappears.] Okay. Let's get out of here. We'll need your help. I can inject the painkiller and apply a splint, but dragging her and fighting off the beasts - that's out of question for me. [the girl is about to get to Becky, but stops, smiles at you and gives you kiss on the cheek] Thank you. I really appreciate your help, although I may be bad at showing it. After attitude we got in the NWP - to get some help is even nicer. A pity that I lost my father in this. I still hope that he fled the city and we will see him someday.}
{151}{016}{[oversee Becky's treatment]}

{160}{}{#Node016}
{161}{}{[Sunny handled the task so well as if she had been taught this. Becky looks much better after the injections. When Sunny changes the bandage on her leg, you glance at very nasty-looking wound. But in the end, the girl finally looks relieved. Probably, for the first time for days.] Well... We are ready. No more waiting for father. Let's go.}
{163}{999}{[help girls to get out of city]}

#Node017
{170}{}{[When the first joys and troubles of arriving at the NMP end, Sunny focuses her attention on you] You know, no one has ever been so good to us. I don't even know what to say... We survived only because of your help. A paramedic's bag that helped to get Becky to the NWO became our ticket to life here. Even their cheap doctor Hinder acknowledged that we can be helpful. So now we have a house. And also, we were told that "this is more than a house! This is a family!", but I would have kept their mouth shut, if I were them. I lost my father, and he was more dear to me than any "family" of this place. Anyway - I don't know how to thank you. I just wanted to say it. Know that I will always be in your debt.}
{171}{999}{I'm glad that you are getting better. See you around!}
{172}{999}{I'll remember this part, about the debt!}
{173}{999}{I would prefer payment, but it's fine. See you.}