# Данный файл описывает сообщения,
# использующиеся в скриптах сценери
#
# Created by Artem "Rainman" Samoylov
# 30/07/2013
#
# ЧТО ЭТО?
# Это - поломанный станок карла, который может случайно починить Форрест Гамп
#
# Описание 1
{1}{}{Вы видите: поломанный станок.}
{2}{}{Вы видите: отремонтированный станок.}

# Описание 2
{3}{}{Не понятно почему, но этот станок не работает.}
{4}{}{Похоже, устройство вполне себе рабочее.}

# Действия
{5}{}{Вы АБСОЛЮТНО не понимаете, что с этим можно было бы сделать.}
{6}{}{Нет, у вас нет совершенно никаких идей, как и чем это можно было бы починить.}
{7}{}{Вы попытались потянуть за рычаг, но задели гаечный ключ, и падая внутрь машины он обо что-то брякнулся, и станок запустился!}
{8}{}{Этот станок отлично работает, не нужно с ним ничего больше делать.}
{9}{}{}
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
{20}{}{}
