#
{1}{}{Архетип героя - "Танк".}
{2}{}{Архетип героя - "Лис".}
{3}{}{Архетип героя - "Форрест".}
{4}{}{Архетип героя - "Стандарт".}
{5}{}{}
{6}{}{}
{7}{}{}
{8}{}{}
{9}{}{}
#
#Подключение проводов
#
{10}{}{Ёотите попытаться вручную подобрать комбинацию проводов? При неудачной попытке Вас может ударить током, а система безопасности поменяет электрическую схему!}
{11}{}{Да, стоит попробовать!}
{12}{}{Неет, не нужен мне бесплатный разряд по пальцам!}
{13}{}{Что-то мне перехотелось в проводах ковыряться...}
{14}{}{Ну уж дудки! Я не электрик и не кабельщик! Как-нибудь и без этого обойдусь...}
{15}{}{Перед Вами 3 провода: красный, синий и зеленый. Вам нужно соединить два из них между собой. Какие Вы выбираете?}
{16}{}{Красный + Синий}
{17}{}{Зеленый + Красный}
{18}{}{Синий + Зеленый}
{19}{}{Теперь необходимо подсоединить оставшийся отдельный провод к одному из проводов в паре. К какому проводу Вы его подключите?}
{20}{}{Подсоединить Красный к Зеленому}
{21}{}{Подсоединить Красный к Синему}
{22}{}{Подсоединить Зеленый к Красному}
{23}{}{Подсоединить Зеленый к Синему}
{24}{}{Подсоединить Синий к Красному}
{25}{}{Подсоединить Синий к Зеленому}
{26}{}{Вас ощутимо ударило током.}
{27}{}{УПС! Вы получили разряд в палец.}
{28}{}{Вас дернуло током. Палец все еще ноет.}
{29}{}{Вы получили неслабый удар тока.}
#
#
#
{30}{}{БРАВО! У Вас получилось!}
{31}{}{Это солидная стальная дверь. Ее невозможно открыть ни взрывом, ни тараном.}
{32}{}{Вы сняли с двери ловушку.}
{33}{}{Ёотите попытаться вручную подобрать комбинацию проводов? При неудачной попытке Вас может ударить током, а система безопасности поменяет электрическую схему! В противном случае, для открытия этой двери Вам понадобится навык взлома не менее }
{34}{}{Вы довольно долго ковырялись в проводах, но так и не смогли определить уровень системы защиты... Ёотите попытаться вручную подобрать комбинацию проводов? При неудачной попытке Вас может ударить током, а система безопасности поменяет электрическую схему!}
{35}{}{Ваша ловушка обезврежена и перешла в личное пользование к: }
{36}{}{Дверь критически повреждена, она вот-вот развалится на части.}
{37}{}{Дверь сильно повреждена, она еле-еле держится на петлях.}
{38}{}{Если Вы хотите вручную подобрать комбинацию, то Вам нужно воспользоваться отверткой.}
{39}{}{Вы успешно вскрыли щиток панели управления.}
#
#
#
{40}{}{Заперто.}
{41}{}{Закрыто на замок.}
{42}{}{Заперто наглухо.}
{43}{}{Заперто.}
{44}{}{Эта дверь забита намертво.}
{45}{}{Похоже, открыть невозможно.}
{46}{}{Замуровано, не открыть.}
{47}{}{Двери не получают повреждений в боевом режиме. Выйдите из режима боя и заложите под дверь взрывчатку.}
{48}{}{}
{49}{}{}
#
#WC фразы
#
{50}{}{ЗАНЯТО!}
{51}{}{Не видишь? ЗАНЯТО!}
{52}{}{Дайте посидеть спокойно!}
{53}{}{Чего ломишься? ЗАНЯТО!}
{54}{}{ЗА-НЯ-ТО!!!}
{55}{}{Вставай в очередь!}
{56}{}{}
{57}{}{}
{58}{}{}
{59}{}{}
#
#Глупые попытки использовать черт знает что
#
{60}{}{Как вы себе это представляете?}
{61}{}{Нет, так у Вас ничего не выйдет.}
{62}{}{Это здесь явно не поможет.}
{63}{}{Из этого ничего не выйдет.}
{64}{}{ЭТО здесь некуда приспособить.}
{65}{}{Нужно попробовать что-то другое.}
{66}{}{Нелогично пытаться использовать это здесь.}
{67}{}{Из этого не получится ничего хорошего.}
{68}{}{Так Вы не добьетесь успеха.}
{69}{}{Может быть пальцем попробовать?}
#
#Металлические двери и замки
#
{70}{}{Навалившись всем телом и напрягши все, даже самые мелкие мышцы, Вы так и не смогли отогнуть замок.}
{71}{}{Нет, похоже, этот замок не выйдет открыть просто вот так. С металлом не поспоришь!}
{72}{}{Это ведь ЖЕЛЕЗНАЯ дверь! Вы, правда, считаете себя настолько сильным?!}
{73}{}{Не хотите позвать подмогу? Одному Вам никогда не отогнуть железную дверь!}
{74}{}{Скорее сломается ваша лучевая кость, чем отогнется этот замок!}
{75}{}{<<ЗАПОЛНИТЬ>>}
{76}{}{<<ЗАПОЛНИТЬ>>}
{77}{}{<<ЗАПОЛНИТЬ>>}
{78}{}{<<ЗАПОЛНИТЬ>>}
{79}{}{<<ЗАПОЛНИТЬ>>}
#
#Замок сломан, установка ловушек
#
{80}{}{Взрывом дверь выносит напрочь, она еле-еле держится на петлях.}
{81}{}{Мощной взрывной волной дверь распахивает настежь, кажется, она вот-вот сорвется с петель.}
{82}{}{Навалившись всем телом, вы отгибаете замок. Похоже, замок ремонту не подлежит.}
{83}{}{Вы неудачно поставили локоть и потянули связки. Вы чувствуете сильную боль.}
{84}{}{Вы неудачно поставили ногу и потянули мышцы. Вы чувствуете сильную боль.}
{85}{}{Чертыхаясь и плюясь, Вы пытаетесь вправить вывихнутый сустав. Вам это удается, но боль не проходит.}
{86}{}{Нельзя устанавливать ловушки на запертые двери, это бессмысленно.}
{87}{}{Вы успешно заминировали дверь. Остается только ждать фейерверка!}
{88}{}{Замок безнадежно сломан, эту дверь невозможно запереть!}
{89}{}{Дверь стойко выдержала удар и не сломалась.}
#
#Работа с дверями и замками
#
{90}{}{Из-за Ваших кривых рук замок заклинило.}
{91}{}{Возможно, через несколько часов Вы придумаете способ, как открыть замок, но сейчас его заклинило.}
{92}{}{У Вас не осталось идей, как можно было бы открыть этот замок.}
{93}{}{Вас просто заклинило. Замок тоже...}
{94}{}{Перед тем как запереть дверь, Вам нужно ее закрыть.}
{95}{}{Вы, как могли, заперли замок.}
{96}{}{Дверь полностью разрушена, Вы ничего не можете с ней сделать.}
{97}{}{Этой дверью больше нельзя пользоваться, она полностью сломана.}
{98}{}{От двери остались только рожки да ножки, что Вы хотите с ней сделать?!}
{99}{}{Лучше не трогать остатки бедной двери, она и так еле держится на петлях.}
#
#звуки дверей, сейфов и т. д. при открывании
#
{100}{}{чик-чик}
{101}{}{трик-трак}
{102}{}{::что-то щелкнуло::}
{103}{}{кррр-тррр-чик}
{104}{}{тррр-крр-чик}
{105}{}{::щелчок::}
{106}{}{крр-ррр-чик}
{107}{}{кррр-тррр-чик}
{108}{}{::дверца приоткрылась::}
{109}{}{::открыто::}
#
#запертые двери, сейфы, ящики
#
{110}{}{Нет. Заперто...}
{111}{}{Облом. Заперто.}
{112}{}{Не так быстро. Заперто.}
{113}{}{Просто так не откроешь. Заперто.}
{114}{}{Черт, не получилось..}
{115}{}{И чего Вы хотели этим добиться??}
{116}{}{Похоже, это не лучшая идея.}
{117}{}{Не-ет! Так дело не пойдет!}
{118}{}{Вы заперли замок и заклинили дверь.}
{119}{}{::заперто::}
#
#опять чертовы замки...
#
{120}{}{Не-ет, этот замок Вам не по зубам!}
{121}{}{Нет, сначала Вам нужно потренироваться на замках попроще.}
{122}{}{Не выйдет. Ваш навык взлома недостаточен для этого замка.}
{123}{}{Ёочется открывать замки без ключей? Нужно больше тренироваться на замках попроще.}
{124}{}{После тщательного поверхностного изучения замка вы понимаете, что для его открытия Вам потребуется навык "взлома" не менее }
{125}{}{...}
{126}{}{После непродолжительного поверхностного изучения замка вы понимаете, что ни черта в нем не понимаете...}
{127}{}{Вам нужно серьезно натренировать руку, чтобы отогнуть такой замок.}
{128}{}{Нет, Вы не достаточно сильны для подобного вандализма.}
{129}{}{Вы навалились всем телом, но Вам не хватает сил чтобы отогнуть замок. }
#
#и опять чертовы замки...
#
{130}{}{Каким бы искусным медвежатником Вы ни были, этот замок не поддастся!}
{131}{}{Очевидно, тут нужен какой-то определенный ключ.}
{132}{}{Ни фомка, ни отмычки Вам не помогут. Здесь нужен специальный ключ.}
{133}{}{Ничего не выйдет. Замок предназначен только для одного ключа.}
{134}{}{После непродолжительного ковыряния с замком Вы понимаете, что он откроется только ключом.}
{135}{}{Не-ет, здесь нужен особый ключ...}
{136}{}{Без нужного ключа его не открыть...}
{137}{}{Можно его хоть из гранатомета расстреливать, но без "своего" ключа он не откроется!}
{138}{}{Есть идеи, где достать НУЖНЫЙ КЛЮЧ?}
{139}{}{Тут нужен его, замковый, ключ. Ничто другое не поможет.}
#
#
#опыт
#
{140}{}{Вы получили }
{141}{}{Вы заработали }
{142}{}{Вы заслужили }
{143}{}{Прекрасно! Плюс }
{144}{}{ у.е. опыта.}
#
#Воровство
#
{145}{}{Вам удалось порыться в чужих карманах! }
{146}{}{Вы смогли незаметно обшарить этого персонажа! }
{147}{}{Ваши ловкие ручки забрались в чужие карманы! }
{148}{}{Вы ловко забрались в чужие карманы! }
#
#
#Батарейки
#
{150}{}{Ух ты! Вы разбогатели на }
{151}{}{Поздравляем! Вы стали богаче на }
{152}{}{В Вашем кармане прибавилось }
{153}{}{Еще немного - и Вы - БОГАЧ! Плюс }
{154}{}{Счастье не в батарейках, а в их количестве! Плюс }
{155}{}{ шт. батареек!}
#
#Ловушки на дверях
#
{160}{}{Пытаясь установить на дверь ловушку, Вы замечаете... Что здесь уже установлена ловушка!}
{161}{}{Зачем Вам это? Здесь уже установлена Ваша ловушка!}
{162}{}{Ковыряясь в замке Вы довольно болезненно вывихнули себе запястье.}
{163}{}{Вы серьезно защемили себе палец, неудачно подсунув его под отвертку.}
{164}{}{}
{165}{}{}
{166}{}{}
{167}{}{}
{168}{}{}
{169}{}{}
#
#ловушки на ящиках
#
{170}{}{В последний момент Вы замечаете скрытое лезвие под крышкой.}
{171}{}{Вы случайно замечаете растяжку, ведущую к взрывателю ловушки.}
{172}{}{Сработала ловушка!}
{173}{}{Вы успешно обезвредили ловушку!}
{174}{}{Вы обнаружили ловушку!}
{175}{}{Вы не видите здесь ничего необычного.}
{176}{}{}
{177}{}{}
{178}{}{}
{179}{}{}
#
#Кража у криттеров
#
{200}{}{Не вышло, Вас чуть-чуть не спалили!}
{201}{}{Ничего не получилось, Вам необходимо больше тренироваться.}
{202}{}{Да у Вас же руки трясутся! Успокойтесь и попробуйте еще разок!}
{203}{}{Вас едва не заметили! Будьте осторожнее в следующий раз.}
{204}{}{Ваши шансы обворовать этого персонажа равны }
{205}{}{%... Стоит ли пытаться?}
{206}{}{НА ВОРЕ ШАПКА ГОРИТ! ДЕРЖИ ЕГО!!!}
{207}{}{ВОРОВАТЬ ВЗДУМАЛ?!}
{208}{}{ЛЮ-У-У-ДИ! ГРАБЯТ!!!}
{209}{}{АX ТЫ ВОРЮГА!!!}
{210}{}{Что бы попытаться обворовать этого торговца Ваш навык воровства должен быть не менее }
{211}{}{ !}
{212}{}{}
{213}{}{}
#
#Боевые спец сообщения
#ЯДЫ
{250}{}{Вы чувствуете, как яд проникает в Ваше тело.}
{251}{}{Яд просочился в Вашу кровь.}
{252}{}{Вы ощущаете действие яда.}
{253}{}{Ядовитый укол причиняет Вам сильную боль.}
{254}{}{Вы отчетливо чувствуете жжение яда.}
#Травматическое оружие
{255}{}{ сваливается навзничь от нестерпимой боли.}
{256}{}{От резкой жгучей боли }
{257}{}{ падает на землю.}
{258}{}{Вы не можете стерпеть боль и на какое-то время отключаетесь.}
{259}{}{От сильнейшей боли на какое-то время Вы теряете сознание.}
#Отравленные дротики
{260}{}{Дротик попадает вам в незащищенное место. Вы чувствуете, как яд проникает под кожу.}
{261}{}{Отравленный дротик приносит Вам сильную боль. Голова начинает кружиться.}
{262}{}{Дротик заносит в Ваш организм неслабую дозу яда. Вы с трудом берете себя в руки.}
{263}{}{Отравленное жало проникает Вам под кожу. Яд распространяется по Вашей крови.}
{264}{}{Ядовитый укол причиняет Вам сильную боль.}
{265}{}{ корчится от боли, ощущая яд от дротика.}
{266}{}{ передергивается после попадания отравленного дротика.}
{267}{}{ хватается за пораженное место, чувствуя жжение яда.}
#костеломательное оружие
{268}{}{Невероятно сильной отдачей Вам ломает лучевую кость на правой руке!}
{269}{}{Вы не смогли сдержать чудовищную отдачу оружия, и Ваше предплечье хрустнуло пополам!}
#
#Первое посещение карты
#
{300}{}{}
{301}{}{Все те же техники бродят по все той же парковке в поисках все тех же запчастей.}
{302}{}{Вас будят теплые мамины руки.}
{303}{}{Прошло столько лет, а практически ничего не изменилось в Тартаре.}
{304}{}{Спустя еще 4 года ничего так и не поменялось.}
{305}{}{Фермы Тартара... Влажный воздух пропитан запахом гнилой кукурузы и дерьма лавашей.}
{306}{}{Вам кажется, что с каждым новым заходом на фермы, воздух здесь все противнее..}
{307}{}{Тех уровень... Беспрерывный шум агрегатов по откачке и очистке воды никогда не даст заснуть.}
{308}{}{Вонь из Жерла Аида сразу же бьет Вам в нос и чуть не валит на землю.}
{309}{}{Вот оно - Чистилище. В кромешной темноте вы ощущаете запах страха и смерти.}
{310}{}{Нестерпимо яркий солнечный свет бьет Вам в глаза, Вы начинаете задыхаться, но в скором времени приходите в себя.}
{311}{}{Старая парковка с грудой искореженного металла... Мальчиком Вы так любили здесь играть.}
{312}{}{Старая ветка метро упирается в завал, но справа виднеется отворотка.}
{313}{}{Древняя станция "Олимп". Тусклый свет освещает хилые тела местных обитателей.}
{314}{}{Здесь, судя по всему, раньше были залы ожидания и администрация станции "Олимп".}
{315}{}{Среди остатков домов виднеется спуск под землю.}
{316}{}{Как и везде, здесь царит разруха и опустошение.}
{317}{}{В старом сыром подвале явственно ощущается запах гниющего мяса...}
{318}{}{Шумное оживленное место, охраняемое вооруженными людьми. Похоже, здесь ведется торговля.}
{319}{}{Это похоже на центр базы псов. У здания ближе к Вам выставлена охрана...}
{320}{}{А вот это напоминает парковку в Тартаре: рейдеры, видимо, копаются в старом хламе в поисках нужных железок.}
{321}{}{Здесь на удивление оживленно, тут и там спят или бродят множество рейдеров, а добрая половина собрались у ринга и что-то орут.}
{322}{}{Народу здесь немного, но все хорошо вооружены. Видимо, то здание - это старый склад.}
{323}{}{Это место совсем не похоже на здания снаружи, и, судя по всему, здесь давно никто не бывал. Странно, но Вам вдруг становится страшно.}
{324}{}{Подвальная комната, больше похожая на армейский бункер на случай бомбежки.}
{325}{}{На противоположной стороне плато виднеется вход в какую-то пещеру.}
{326}{}{Здесь темно и сыро, но, похоже, кто-то сделал здесь для себя убежище.}
{327}{}{Это место похоже на оживленную торговую площадь, а в воздухе витает сладкий дух свободных рыночных отношений.}
{328}{}{С порога в нос бьет запах машинного масла и сырого мяса вперемешку с фекалиями и потом рабочих. Это заводской цех.}
{329}{}{... и еще 4 года. Вам уже 21, но в Тартаре ничего так и не изменилось.}
{330}{}{ЛИШНЯЯ КАРТА}
{331}{}{Тут и там видны жилые палатки и ветхие домики, слышно непрекращающееся мычание лавашей и жужжание мух.}
{332}{}{Огромный, богато оформленная вывеска "LIVOS" указывает на вход в пещеру, рядом с которой толкутся путники и торговцы.}
{333}{}{Своды пещеры упираются в бетонные стены, перед которыми стоит автоматическая турель. Она сразу же навелась на Вас.}
{334}{}{Ступени лестницы привели Вас в сеть комнат и коридоров, по которым туда-сюда бродят богато одетые жители убежища.}
{335}{}{В плохо освещенной комнате стоят непонятные автоматы и приборы. Похоже, это техническое помещение.}
{336}{}{Здесь довольно темно и влажно, а неподалеку слышно журчание воды и жужжание механизмов. И какое-то... хрюканье?}
{337}{}{Спертый, тяжелый воздух сразу же сбивает Ваше дыхание, но потихоньку Вы успокаиваетесь, а ваши глаза привыкают к непроглядной тьме.}
{338}{}{Это место похоже на стоянку каких-нибудь рейдеров или бродяг: некоторые из местных мертвецки пьяны, другие стонут от голода, прочие постоянно что-то ищут.}
{339}{}{В этой части селение кажется оживленнее, и похоже оживление связано с огороженной площадью, расположенной неподалеку.}
{340}{}{Вот оно - Ваш первый бой на Арене! Нужно собрать свои умения в кулак - и победить!}
{341}{}{Внутри помещения оказался самый настоящий притон, с алкоголем, блэк-джеком и шлюхами! Пьяные мужики выстукивают ногами и кулаками мелодию, задавая танцовщицам ритм.}
{342}{}{Длинный коридор, кажется, упирается в темноту. Вы готовы поспорить, что здесь уже очень давно не ступала нога человека.}
{343}{}{У прохода в пещеру стоят скучающие охранники и... да, наверняка они охраняют вход в эту пещеру.}
{344}{}{В небольшом проходе впереди Вы видите пару здоровенных аборигенов, машущих Вам руками.}
{345}{}{Похоже, поселение со всех сторон надежно укрыто, и Вы чувствовали бы себя вполне, если бы не этот сладковатый привкус в воздухе...}
{346}{}{В кромешной темноте пещеры Вы можете только слышать. И Вы слышите звуки, не обещающие приятной прогулки.}
{347}{}{Удивительно, но между скалами спрятался огромный особняк! Наверняка его прежний хозяин был очень богат и не очень гостеприимен.}
{348}{}{Посреди пустоши стоит одинокая убогая хижина. Весьма и весьма подозрительная хижина.}
{349}{}{Чуть не упав с последней ступеньки, Вы оказываетесь в душном помещении, насквозь пропитанным потом и алкоголем.}
{350}{}{Перед Вами главный вход довольно большого завода, очень похожего на НМП. Впрочем - все заводы "на один фасад".}
{351}{}{Воздух цеха пропитан запахом гнилых тряпок, а вокруг разбросаны свидетельства ушедших "квартирантов".}
{352}{}{Вы слышите странный шорох в подвале. Как будто кто-то проводит гвоздем по камням.}
{353}{}{Вокруг только скалы... Только скалы вокруг.}
{354}{}{Картина "Чудо-града", предстающая перед Вами... разочаровывает. Здесь только пара стен, плесень да пещерные бледные грибы.}
{355}{}{Перед Вами стоит, возносясь в небеса, громадина "Олимпа". Внушительные Дефендеры рядом с башней выглядят просто ничтожными.}
{356}{}{Красота внутренней отделки заставляет Вашу челюсть сильно и надолго упасть.}
{357}{}{Мужчины и женщины в белых (когда-то белых) халатах снуют туда-сюда с какими-то колбами и причудливыми инструментами.}
{358}{}{Сложно разобраться, что здесь происходит, но людей в белых халатах здесь не меньше, чем на предыдущем этаже.}
{359}{}{Местный персонал бегает от вычислителя к вычислителю с выпученными глазами и растрепанными волосами. Наверняка они заняты чем-то очень важным и срочным.}
{360}{}{Свежий горячий воздух ударяет Вам в лицо, и от открывшегося вида у Вас перехватывает дыхание.}
{361}{}{Это место похоже на высокотехнологичную лабораторию. Опять белые халаты, но суеты не так много, как на инженерном уровне.}
{362}{}{Обитель Дефендеров - по-другому и не скажешь. Вы чувствуете себя лилипутом рядом с этими воинами.}
{363}{}{Гудение трансформаторов здесь невероятно громкое, а воздух настолько наэлектризован, что Вы чувствуете, как волосы по всему телу становятся дыбом.}
{364}{}{В этой комнате нет совершенно ничего, кроме лифта и ОГРОМНОЙ двери с кодовой панелью.}
{365}{}{Вы смело шагаете вперед...}
{366}{}{Удивительно густые заросли. Это что-то вроде пригородного лесопарка, или вроде того. Но Вы уверены, что скорпионы сами Вас найдут.}
{367}{}{В пустынной местности Вы видите тропинки, но они слишком широки, чтобы их протоптали люди...}
{368}{}{В скале Вы видите обустроенный вход в пещеры, откуда доносится негромкое урчание...}
{369}{}{Чем ближе Вы подходите, тем сильнее начинает кружиться и болеть ваша голова. С этим местом явно что-то не в порядке!}
{370}{}{Кругом песок и пустошь.}
{371}{}{Кругом песок и пустошь.}
{372}{}{Кругом песок и пустошь.}
{373}{}{Кругом песок и пустошь.}
{374}{}{Кругом песок и пустошь.}
{375}{}{Кругом песок и пустошь.}
{376}{}{Кругом песок и пустошь.}
{377}{}{Кругом песок и пустошь.}
{378}{}{Кругом песок и пустошь.}
{379}{}{Кругом песок и пустошь.}
{380}{}{Кое-где видна растительность.}
{381}{}{Кое-где видна растительность.}
{382}{}{Кое-где видна растительность.}
{383}{}{Кое-где видна растительность.}
{384}{}{Кое-где видна растительность.}
{385}{}{Только пустые руины.}
{386}{}{Только пустые руины.}
{387}{}{Только пустые руины.}
{388}{}{Просто берег мертвой реки.}
{389}{}{Просто берег мертвой реки.}
{390}{}{На втором этаже уютно расположились несколько комнат, а в одной даже есть кто-то живой.}
{391}{}{Скалы и камни. И еще скалы... и камни.}
{392}{}{Скалы и камни. И еще скалы... и камни.}
{393}{}{Скалы и камни. И еще скалы... и камни.}
{394}{}{Скалы и камни. И еще скалы... и камни.}
{395}{}{Скалы и камни. И еще скалы... и камни.}
{396}{}{Скалы и камни. И еще скалы... и камни.}
{397}{}{Скалы и камни. И еще скалы... и камни.}
{398}{}{Только руины и камни.}
{399}{}{Только руины и камни.}
#
# МЕЁАНИЧЕСКАЯ ПАМЯТЬ
#
{400}{}{Навык "Ручное оружие" повышен!}
{401}{}{Навык "Тяжелое оружие" повышен!}
{402}{}{Навык "Энерго оружие" повышен!}
{403}{}{Навык "Рукопашная" повышен!}
{404}{}{Навык "Ёолодное оружие" повышен!}
{405}{}{Навык "Метание" повышен!}
{406}{}{Навык "Медбрат" повышен!}
{407}{}{Навык "Ёирург" повышен!}
{408}{}{Навык "Красться" повышен!}
{409}{}{Навык "Взламывать" повышен!}
{410}{}{Навык "Воровать" повышен!}
{411}{}{Навык "Западни" повышен!}
{412}{}{Навык "Наука" повышен!}
{413}{}{Навык "Ремонт" повышен!}
{414}{}{Навык "Общение" повышен!}
{415}{}{Навык "Бартер" повышен!}
{416}{}{Навык "Казанова" повышен!}
{417}{}{Навык "Выживание" повышен!}
#
# ПАНЕЛЬ ЛИФТА ОЛИМП
#
{420}{}{Вас приветствует мастер управления}
{421}{}{лифтом башни "Олимп"!}
{422}{}{Простите, но для пользования лифтом}
{423}{}{Вы должны вставить карту доступа.}
{424}{}{До свидания!}
{425}{}{Карта опознана: }
{426}{}{"Институт Органики"}
{427}{}{"Конструкторское Бюро"}
{428}{}{"Лабории физики"}
{429}{}{"Доступ Ё2"}
{430}{}{"Доступ Ё1"}
{431}{}{N Этажа  Название         Доступ}
{432}{}{001       Отель "Xортон"        }
{433}{}{031       "Институт Органики"  }
{434}{}{051       "Инженерная"          }
{435}{}{063       "Лабории физики"     }
{436}{}{079       "Серверная"           }
{437}{}{096       "Презентационная"    }
{438}{}{103       "Залы Контроля"       }
{439}{}{Этаж N: }
{440}{}{ДА}
{441}{}{НЕТ}
{442}{}{Пожалуйста, введите номер желаемого}
{443}{}{этажа в формате "XXX"}
{444}{}{Запрос на этаж принят.}
{445}{}{Запрос на этаж не принят.}
{446}{}{Панель не работает, питание этажа отключено.}
{447}{}{"ОТКАЗ: КАРТА ЗАБЛОКИРОВАНА"}
{448}{}{}
{449}{}{}
#
#Сообщения для окна сообщений
#
{800}{}{У Вас нет авто-маппера!}
{801}{}{У Вас нет органайзера!}
{802}{}{Вы не можете войти в режим боя!}
{803}{}{Разрешение не должно быть меньше 800х600!}
{804}{}{Вы получили новую карму!}
{805}{}{}
{806}{}{}
{807}{}{}
{808}{}{}
{809}{}{}
# Сообщения о влиянии на локацию
{810}{}{Вы значительно повлияли на судьбу жителей станции!}
{811}{}{Ваши действия значительно повлияли на жизнь в Тартаре!}
{812}{}{Своими действиями Вы сильно повлияли на судьбу НМП!}
{813}{}{Несомненно, Ваши действия будут иметь последствия для жителей Лайвос!}
{814}{}{Очевидно, после Ваших действий жизнь Псов сильно изменится!}
{815}{}{Дальнейшая судьба "Радуги" сильно изменилась из-за Ваших действий!}
{816}{}{}
{817}{}{}
{818}{}{}
{819}{}{}
# Сообщения в мини-дисплее (и для квестов)
{850}{}{Идет чтение, не вынимайте диск...}
{851}{}{Диск успешно считан на органайзер.}
{852}{}{Неверный код.}
{853}{}{Код принят.}
{854}{}{Ваше облучение увеличилось на: }
{855}{}{Кто-то больно цапнул Вас за палец!}
{856}{}{Похоже, там живет голодная крыса. Чем можно выманить крысу?..}
{857}{}{Неет, эта крыса не станет есть с рук!}
{858}{}{Ёмм, похоже на это крыса не клюет.}
{859}{}{}
{860}{}{Вы обнаружили достаточно мин, можно рассказать Фреду.}
{861}{}{Похоже, все бестии мертвы, можно рассказать об этом Кристи.}
{862}{}{Что-то щелкнуло!}
{863}{}{Похоже, Ваш навык Наблюдательности слишком низок, чтобы обнаружить мины. Но, разминирование ногой - тоже неплохой способ.}
{864}{}{Одна готова, но вокруг дома еще есть и другие.}
{865}{}{Народу набралось достаточно много, нужно сказать об этом Боно.}
{866}{}{Едва не сломав иглу о толстую шкуру монстра, Вам все же удается загнать инъекцию в незащищенное брюхо химеры!}
{867}{}{Вы облучились на }
{868}{}{ ед!}
{869}{}{На панели имеется разъем для чип-карты "2В".}
{870}{}{Похоже, эта карта сюда не подходит.}
{871}{}{Судя по всему эта дверь управляется удаленно. Просто так Вам ее не откроют.}
{872}{}{Ваше накопленное облучение составляет }
{873}{}{Вы не можете просто сбежать с охоты!}
{874}{}{Вы не можете обворовать этого персонажа.}
{875}{}{}
{876}{}{}
{877}{}{}
{878}{}{}
{879}{}{}
#
#НОВЫЕ КНИГИ
#
{880}{}{Нет, из этого выпуска Вы уже не узнаете ничего нового.}
{881}{}{Похоже, кинижки уже не смогут поднять Ваше умение.}
{882}{}{Из этого выпуска Вы узнали пару новых трюков, как можно убедить собеседника в своей правоте.}
{883}{}{В этом выпуске подробно описана техника движения кисти, чтобы бросок получился как можно точнее.}
{884}{}{Джэб, смэш, хук, апперкот и пяткой в горло! Комикс красочно и наглядно демонстрирует новые способы сломать противника пополам голыми руками!}
{885}{}{Ваш уровень интеллекта не позволяет Вам обучаться по этим комиксам.}
#
#Спец сообщения для сюжета
#
{900}{}{Вы слышите, как Вас зовет мама.}
{901}{}{Вы слышите, как Вас зовет Доктор Пэт.}
{902}{}{}
{903}{}{}
{904}{}{}
{905}{}{}
{906}{}{}
{907}{}{}
{908}{}{}
#
#РАЗГОВОРЫ ПРО РЕНЕССАНС
#
{910}{1}{Ренессанс, говоришь? Да, об этом местечке ходит множество слухов. Последний мертвяк в Радиусе знает, что есть где-то поблизости обетованный РЕНЕССАНС, где тепло, тихо, спокойно, вдоволь еды и воды... Все знают, что это место есть, но, черт, никто, абсолютно никто не знает, где оно находится.}
{911}{}{Ого... Понятно. Спасибо за информацию.}
{912}{2}{Ренессанс... [ухмыляется] Да-а, парень, есть такое теплое местечко. Знаю, многие его и искали, и, говорят, кое-кто даже находил, да вот только никто этого кое-кого не видел. Был вроде бы паренек, побывавший в Ренессансе, но вот что с ним сталось - без малейшего понятия.}
{913}{}{Если кто-то там был - значит, это место и правда существует. Спасибо и на этом.}
{914}{3}{Ага, вот значит, ты что удумал! Был один такой же пытливый, да весь вышел [усмехается] Ренессанс - это закрытый, секретный правительственный город, там наверняка живут какие-нибудь президенты или монархи, а таких, как ты - расстреляют еще за полмили на подходе к этому твоему Ренессансу! Помяни мое слово - брось ты его искать, не то плохо кончишь.}
{915}{}{Да-а, звучит опасно... Наверно, нужно быть осторожнее.}
{916}{4}{Эдемский город, да-а [закатывает глаза] Говорят, там работают хитрые автоматы, выдающие вкусную еду, обеспечивающие свет и тепло... Но, и я точно знаю, это место очень хорошо спрятано где-то в горах, да еще и окружено штуками, туманящими мысли. Вот ты можешь и не верить, а куча народу его искали, да так и не вернулись! Был, правда, один паренек, так он не только вернулся, а еще и карту нарисовал, как это место найти. Вроде как он эту карту на 4 части разделил, да в разных уголках Радиуса запрятал, но... Кто его знает, может и нет никакого Ренессанса, а?}
{917}{}{Карта? С картой было бы гораздо легче его искать. Конечно, если Ренессанс существует.}
{918}{}{Да мне нечего особо тебе рассказать. Вроде где-то что есть, но никто не знает, где и чего.}
{919}{}{Ренессанс - город-рай [подмигивает] Это как обычный рай - не факт, что он существует.}
{920}{}{Есть много слухов, но ничего конкретного никто не знает.}
{921}{}{Да люди разное говорят, тут уж сам выбираешь, чему верить, а чему - нет.}
{922}{}{Понятно.}
{923}{}{Ок, ясно.}
{924}{}{Ну понятно, да.}
#
#Реплики в Тартаре после побега ГГ
#Слуги
{930}{}{Вестник? Я... Мне... Да-да, конечно, я уже иду трудиться! Простите.}
{931}{}{Что? нет-нет, я просто... ищу тут инструменты. Конечно я буду трудиться на благо Богов.}
{932}{}{Да, конечно, все как скажут боги!}
{933}{}{Смотритель? Я выполняю все, что мне говорили.}
{934}{}{Я тут... просто... я уже иду работать, мне пора.}
{935}{}{Я ничего такого не хочу, нет-нет! Меня все устраивает, мне нравится служить Богам.}
#Детишки
{936}{}{Вестник! Расскажи мне про Богов!}
{937}{}{А это правда, что снаружи живут ужасные твари?}
{938}{}{Мама говорит, что здесь наше место. А где место Богов, Вестник?}
{940}{}{О-о-о, смотритель! Такая классная броня!}
{941}{}{Смотритель, а можно потрогать броню? ну хоть мизинчиком?}
{942}{}{[встает по стойке смирно]Докладываю! Ужасных тварей под кроватью не замечено!}
#Охранники
{943}{}{Вестник? Почему не на службе?}
{944}{}{Ну ты мне-то своих проповедей не вешай, а?}
{945}{}{Иди лучше работай, нечего тут околачиваться.}
{946}{}{Скаут? Ты здесь чего забыл? Свежей девки захотелось, а?}
{947}{}{Эй, военный-здоровенный, ты мне дежурить мешаешь.}
{948}{}{Шел бы лучше внешние границы патрулировать.}
#ГГ запалили в Тартаре после побега
{950}{}{Это тот самый еретик! Убить ЕГО!}
{951}{}{ТРЕВОГА! Убить еретика!}
{952}{}{Это он, тот самый! ОЁРАНА!}
{953}{}{Вы ловко вогнали всю дозу сыворотки в мягкие ткани девушки!}
{954}{}{}
{955}{}{}
{956}{}{}
{957}{}{}
{958}{}{}
{950}{}{}
{951}{}{}
{952}{}{}
{953}{}{}
{954}{}{}
{955}{}{}
{956}{}{}
{957}{}{}
{958}{}{}
#
#Стандартные сообщения для окончания диалога
#
{1000}{}{[ГОТОВО]}
{1001}{}{[ВЫЁОД]}
{1002}{}{[ЗАВЕРШИТЬ]}
{1003}{}{[КОНЕЦ]}
{1004}{}{[ВСЕ]}
{1005}{}{[ВЫЙТИ]}
{1006}{}{[ОК]}
#
#Найденные картофельные головы
#
{1010}{}{Вы нашли Мистера Картофельная Сила! Ваша сила увеличена на 1!}
{1011}{}{Вы нашли Мистера Картофельное Восприятие! Ваше восприятие увеличено на 1!}
{1012}{}{Вы нашли Мистера Картофельная Выносливость! Ваша выносливость увеличена на 1!}
{1013}{}{Вы нашли Мистера Картофельная Ёаризма! Ваша харизма увеличена на 1!}
{1014}{}{Вы нашли Мистера Картофельный Интеллект! Ваш интеллект увеличен на 1!}
{1015}{}{Вы нашли Мистера Картофельная Ловкость! Ваша ловкость увеличена на 1!}
{1016}{}{Вы нашли Мистера Картофельная Удача! Ваша удача увеличена на 1!}
#
