# Данный файл описывает сообщения,
# использующиеся в скриптах сценери
#
# Created by Artem "Rainman" Samoylov
# 30/07/2013
#
#
# Описание 1
{1}{}{Вы видите: стена.}
{2}{}{С виду обычная стена.}

# Описание 2
{3}{}{Вы видите: новая кирпичная кладка.}
{4}{}{Заметно, что кладка совсем новая, а раствор слабый, кирпичи можно хоть пальцем выковырять.}

# Действия
{5}{}{Чуть поднатужившись Вам удается вытащить пару кирпичей, а за ними разрушается и целый кусок стены...}
{6}{}{Свежая кладка не выдерживает мощной взрывной волны, и стена рушится, как карточный домик.}
{7}{}{Эмм... Нет, из этого ничего не выйдет.}
{8}{}{Как Вы себе ЭТО представляете?}
{9}{}{Может просто стоит пнуть? Или подуть на нее?}
{10}{}{Похоже, Вам не хватает сил, чтобы разрушить кладку.}
{11}{}{Вы недостаточно сильны чтобы этим разрушить кладку.}
{12}{}{Это же... Труп! Труп Сына Богов!}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
{20}{}{}
