# Данный файл описывает сообщения,
# использующиеся в скриптах сценери
#
# Created by Artem "Rainman" Samoylov
# 30/07/2013
#
# ЧТО ЭТО?
# Это - сейф в стене военного бункера, где лежит карта лифта для подвала Олимпа
#
# Описание 1
{1}{}{Вы видите: надежный сейф.}
{2}{}{Этот сейф выглядит очень надежным.}

# Описание 2
{3}{}{Сейф закрыт магнитным замком, стена разломана и все провода видны.}
{4}{}{Можно попытаться подобрать провода, чтобы отключить магнитный замок.}

# Действия
{5}{}{Прекратите совать свои пальцы в оголенные провода.}
{6}{}{На генераторе НЕТ рубильника, все закрыто в электрощитке.}
{7}{}{Сейф закрыт, Вы не можете просто взять и открыть его.}
{8}{}{Видно, что система электрозащиты питается от генератора.}
{9}{}{Похоже, человек с руками механика без труда отключит эту электрозащиту.}
#
#Подключение проводов
#
{10}{}{Ёотите попытаться вручную подобрать комбинацию проводов? При неудачной попытке Вас может ударить током, а система безопасности поменяет электрическую схему!}
{11}{}{Да, стоит попробовать!}
{12}{}{Неет, не нужен мне бесплатный разряд по пальцам!}
{13}{}{Что-то мне перехотелось в проводах ковыряться.}
{14}{}{Ну уж дудки! Я не электрик и не кабельщик! Как-нибудь и без этого обойдусь.}
{15}{}{Перед Вами 3 провода: красный, синий и зеленый. Вам нужно соединить два из них между собой. Какие Вы выбираете?}
{16}{}{Красный + Синий}
{17}{}{Зеленый + Красный}
{18}{}{Синий + Зеленый}
{19}{}{Теперь необходимо подсоединить оставшийся отдельный провод к одному из проводов в паре. К какому проводу Вы его подключите?}
{20}{}{Подсоединить Красный к Зеленому}
{21}{}{Подсоединить Красный к Синему}
{22}{}{Подсоединить Зеленый к Красному}
{23}{}{Подсоединить Зеленый к Синему}
{24}{}{Подсоединить Синий к Красному}
{25}{}{Подсоединить Синий к Зеленому}
{26}{}{Вас ощутимо ударило током.}
{27}{}{УПС! Вы получили разряд в палец.}
{28}{}{Вас дернуло током. Палец все еще ноет.}
{29}{}{Вы получили неслабый удар тока.}
#
#
#
{30}{}{У Вас получилось! Сейф открыт!}