##############################
#Локация: Фред
#Имя: Кристи
#Краткое описание: Девушка Фреда. Квест на защиту от бестий.
#Дата создания: 12.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a thin girl in worn-out clothes.}
{2}{}{Unlike her companion, she looks more tired than scared.}
#
# после знакомства
{3}{}{You see Christie.}
{4}{}{The girl, once saved from Jackals by Fred.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You can't help but move your eyes from her beautiful cheeky face to big red, although a little dusty, hair. Short jacket with cut-off sleeves and grey shirt leave her hollowed belly open. Ripped jeans emphasize her slender legs.] Hey... You scared the shit out of Fred! But I somehow knew from the start that you didn't come here for our heads.}
{11}{011}{I've seen a lot of people pissing their pants when seeing me. But you are right, I need only answers for some questions.}
{12}{011}{I didn't think my arrival would make such a fuss. Can you answer my questions for a bit?}
{13}{016}{Are you alright here? Need any help?}
{14}{999}{You have nothing to worry about. Talk later, okay?}


{1001}{}{[Nods to you] Did you like it here? So good you don't want to leave, right?}
{1003}{}{[She looks at you with caution] So, how is it? Did you deal with these creatures?}
{101}{011}{Kind of. Care to tell me something?}
{102}{016}{Are you alright here? Need any help?}
{103}{015}{It's done. The matter with the beasts is resolved.}
{107}{999}{I'm looking around for now. Talk later, okay?}
{1002}{}{[You see a smile appearing on her freckled face, when she sees you] Hey, hero! Want some cooked rat?}
{104}{011}{No, thank you. Better answer some questions for me.}
{105}{016}{Are you alright here? Need any help?}
{106}{999}{Later, maybe. I have something to be done.}


{110}{}{[She pulls up her loose jeans] Gladly. It's nice, for a change, to talk to someone who doesn't grab his gun every two minutes and jump to the window, screaming "They found us, Christie!".}
{111}{012}{How did you meet Fred?}
{112}{013}{Where are you from, Christie?}
{113}{999}{You know, let's talk later.}


{120}{}{[Her face became clouded and she hugs her shoulders as if feeling a cold wind] Fred and his then-bastard-friends attacked our settlement. We had not many men able to fight... That's when funny things like cutting heads and pulling out intestines started to take place. I was carried over to the pen, together with other girls, listening about what explicit things expect us now. Then suddenly something exploded, everyone started to panic - and next thing I see is Fred getting me out and pulling me away with him. And that mostly it. }
{121}{014}{So you're now, like, together forever?}
{122}{011}{Wow. I have another question.}
{123}{999}{You are very lucky, I should say. Well, I won't be distracting you anymore.}


{130}{}{[She carelessly shrugs] I don't even know. All I remember is lifeless wasteland beyond Radius. All entertainment you have is to make bets if you die from hunger or boredom. Every day you see the same endless barren land before your eyes... Then we decided to settle down in one place. That's where I understood that living in the wastes was not the worst thing that can happen to you.}
{131}{012}{Yeah? What happened?}
{132}{999}{Thank you for telling me this, Christie. See you around.}


{140}{}{[She chuckles, rubbing her turned-up nose] You wish! Of course, I'm grateful to him for saving me, but... And he is not bad guy, actually, apart from being very jumpy... He's gonna have big problems with his thing from all this nervousness. Still, it's easier to survive together, so I'm stuck with him... While I can tolerate him, at least. }
{141}{999}{Good luck with that. I'll go look around.}


{150}{}{[Seeing you enter the room, she runs off outside. You hear her cheering. When she return, she shows you Onca Devil's ripped finger] My souvenir. I wish I had claws like this... Thank you, you really helped us out. Too bad not everyone in Radius are such courageous guys like you [hearing this Fred winces, like if he was in pain, and begins to furiously polish his gun with the lining of his jacket.]}
{151}{999}{No problem, babe! If you'll need something else - just ask!}
{152}{999}{This wasn't easy, but I'm glad everything worked out.}


{1601}{}{What can I say... To sit and wait for Onca Devils to show up and rip you apart is kind of questionable pleasure. But mostly - yeah, I'm alright.}
{161}{011}{Then answer some questions for me.}
{162}{999}{Good. Let's talk later then.}
{1602}{}{You already did a lot for me. Thanks to you I'll be able to sleep tonight.}
{163}{011}{Glad to be of help. Mind answering me a couple of questions?}
{164}{999}{Good. Let's talk later then.}


{170}{}{[You are trying to walk out, but Christie stands in your way and takes your hand] Wait a minute, tough guy, slow down. Do you even understand what you and this genius did just now? The mines were the only protection from Onca Devils, and, you know, there are lots of them, judging by the howling - especially after the sunset! Could you, at least help us hold for this night? [Fred wants to say something with a delighted look, but she doesn't let him] Don't even want to hear it! Maybe we will leave this place, but not now, when these creatures can tear us to pieces on the first steps!! It's good that some of us are able to actually think with the head!}
{171}{999}{Look, honey, it's not my problem. Where have you been before? Okay now, I've got to go.}
{172}{999}{Sure, I'll help. It's been a while since I hunted these beasts...}
{173}{999}{I would be glad to stay, but I really need to go. Sorry.}
{174}{999}{Damn! Why this buddy of yours did't say so earlier? Of course I will help you.}
{175}{}{You are kidding, right? We are left without any protection and Onca Devils are going to happily feast on our corpses this beautiful moonlit night! I definitely can't count on Fred in this... [Christie looks down with sadness]}