##############################
#Локация: Фред
#Имя: Кристи
#Краткое описание: Девушка Фреда. Квест на защиту от бестий.
#Дата создания: 12.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a thin girl in worn-out clothes.}
{2}{}{Unlike her companion, she looks more tired than scared.}
#
# после знакомства
{3}{}{You see Christie.}
{4}{}{The girl that Fred once saved from the Jackals.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Your gaze involuntarily moves from a pretty high-cheekboned face to a luxurious, despite the dust that's covering it, shock of red hair. A short jacket with cut-off sleeves and a grey shirt leave her sunken belly exposed. The ripped jeans nicely emphasize her slender legs.] Hey... You scared the shit out of Fred! But I somehow knew from the start, that you didn't come here for our heads.}
{11}{011}{I've seen a lot of people pissing their pants when seeing me. But you are right, I just need answers to a couple of questions.}
{12}{011}{I didn't think my arrival would make such a fuss. Can you answer a few questions?}
{13}{016}{Everything alright here? Need any help?}
{14}{999}{You have nothing to worry about. We'll talk later, okay?}


{1001}{}{[Nods to you] Do you like it here? So good, you don't even want to leave, right?}
{1003}{}{[She looks at you cautiously] So, how's it going? Did you deal with all the creatures?}
{101}{011}{Sort of. Care to answer some questions?}
{102}{016}{Everything alright here? Need any help?}
{103}{015}{It's done. The matter with the beasts is resolved.}
{107}{999}{Just looking around. We'll talk later, okay?}
{1002}{}{[A smile appears on her freckled face when she sees you] Hey, hero! Want some rat stew?}
{104}{011}{No, thank you. But I have some questions.}
{105}{016}{Everything alright here? Need any help?}
{106}{999}{Maybe later. I have something that needs to be done.}


{110}{}{[She eagerly pulls up her loose jeans] Gladly. It's nice to talk to someone for a change, who doesn't grab his gun every two minutes, jumping to the window, screaming "They found us, Christie!".}
{111}{012}{How did you meet Fred?}
{112}{013}{Where are you from, Christie?}
{113}{999}{You know, let's talk later.}


{120}{}{[Her face becomes clouded and she hugs her shoulders as if freezing in a gust of cold wind] Fred and his then-bastard-friends attacked our settlement. We haven't had many able men that could fight... That's when all sort of fun things like beheadings and disembowelings started to happen. I was brought over to the pens, together with other girls, where they kindly explained what explicit deeds they expected from us... Then suddenly something exploded, everyone started to panic. The next thing I see is Fred getting me out, pulling me along and getting away from there with him. And that's mostly it.}
{121}{014}{So you're now, like, together forever?}
{122}{011}{Wow. I have another question.}
{123}{999}{That turned out very lucky for you, I think. Well, I won't bother you anymore.}


{130}{}{[She smiles nonchalantly and shrugs] I don't even know. All I remember is a desolate wasteland beyond Radius. The entertainment you have is to make bets if you die from hunger or boredom. Every day the same, endless barren land before my eyes... before we decided to settle down in one place. That's where I understood that living in the wastes was not the worst thing that can happen to you.}
{131}{012}{Yeah? What happened?}
{132}{999}{Thank you for telling me this, Christie. See you around.}


{140}{}{[She chuckles, rubbing her snubby nose] You wish! Of course I am grateful for him to save me, but, - not that he is a bad guy, actually he's very shy... apart from being very jumpy, naturally - soon he's gonna have even more problems with handling his tool, if you catch my drift. Still, it's easier to survive together, so I'm stuck with him... As long as I can stand him, at least.}
{141}{999}{Well, good luck with that. I'll go and look around.}


{150}{}{[Seeing you enter, she runs outside where you hear her cheer. Upon returning, she shows you a severed finger of an Onca Devil] I'll take this as a souvenir. Man, I wish I had such nails... Thank you, you really helped us out. Too bad not everyone in Radius are such courageous guys like you [hearing this Fred winces, like if he was in pain, and with a sullen face begins to furiously polish his gun with the lining of his jacket.]}
{151}{999}{No problem, babe! If you'll need something else, just ask!}
{152}{999}{This wasn't easy, but I'm glad everything worked out.}


{1601}{}{As you said... sitting around, waiting for Onca Devils to show up and rip you apart is kind of a questionable pleasure. But I am mostly fine, yea.}
{161}{011}{Answer me a question then.}
{162}{999}{Good. Let's talk later then.}
{1602}{}{You already did a lot for me. Thanks to you I'll be able to sleep tonight.}
{163}{011}{Glad to be of help. Mind answering me a couple of questions?}
{164}{999}{Good. Let's talk later then.}


{170}{}{[As you are trying to leave, Christie stands in your way and grabs your hand] Wait a minute, tough guy, slow down. Do you even understand what you and this genius did just now? The mines were the only protection from Onca Devils, and - you know - there are lots of them, judging by the howling, especially after the sunset! Could you, at least help us make it through this night? [Fred wants to say something, looking delighted, but she doesn't let him] I don't even want to hear it! Maybe we will leave this place, but not now when these creatures can tear us to pieces on the first mile on out! It's good that some of us are able to actually think with their heads!}
{171}{999}{Look, honey, it's not really my problem. Where have you been before, huh? Get out of the way, I've got to go.}
{172}{999}{Sure, I'll help. It's been a while since I hunted these beasts...}
{173}{999}{I would love to stay, but I really have to hurry. Sorry.}
{174}{999}{Damn! Why didn't this buddy of yours say so earlier? Of course, I will help you.}
{175}{}{You're kidding me, right? We're left without any protection, the beasts are going to happily feast on our corpses this beautiful moonlit night! I certainly can't count on Fred... [Christie stares at the floor with a forlorn look]}