##############################
#Локация: Фред
#Имя: Фред
#Краткое описание: Бывший Пес. Квест на мины.
#Дата создания: 12.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a nervous man.}
{2}{}{He is so pale that it looks like he's glowing.}
#
# после знакомства
{3}{}{You see Fred.}
{4}{}{A paranoid ex-Jackal.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see skinny man, pale as a ghost, dressed in a riveted jacket with lots of labels; he's having a heated argument with a tall, red-haired girl. Seeing you he nervously rushes to pull out his pistol, almost pulling trigger in the process and barely avoiding shooting himself in the leg. It makes him turn even more white, but he still manages to point gun in your direction, holding it with both trembling hands. You notice letters "FRED" tattoed on his knuckles of both hands.] Stay where you are! What the hell do you want here? How did you find this place?!}
{11}{011}{Listen here, clown, If you'll keep waving the piece like that - I'm gonna stick it up your ass. For now I need only information, but it can change at any moment.}
{12}{011}{Hey, easy, alright? I just want to ask a couple of questions, that's all.}
{13}{999}{I'm going to calmly leave now. And you pull yoursef together. Don't scare a girl.}


{1001}{}{[He starts to shiver frightened, but almost immediately takes on intimidating look. He glances on a girl, checking if she saw his fear] It would be better for everyone if you'll just go away now, fast. Do I need to repeat that?}
{101}{012}{I leave when I want to. For now aswer some questions.}
{102}{019}{I'm done with the mines.}
{103}{016}{Are we good about the jumpsuit deal? Or you decided to take on the mines yourself?}
{104}{999}{Don't twitch, I need to look around. I'll leave you soon. }
{1002}{}{[Nods to you with a weak smile] Oh, mr. Cool guy... Why the hell did you drop on my head?.. }
{105}{012}{Actually, you should be grateful. Better tell me this...}
{106}{999}{We'll part ways soon, don't sweat. I'm already tired of your whining.}
{107}{999}{Don't worry, I'll leave you in some time. Only need to finish one thing.}


{110}{}{[He slowly puts the gun down and shrivels, as if waiting for a strike. You notice displeased look on the girl's face as she sees it] Chimera's shit... I thought it's the Jackals came for my head. Still, if you are not one of them, it doesn't mean you are welcomed here, got it? What did you want, by the way?}
{111}{013}{You have found a jumpsuit with NCASTR logo some time ago. Do you still have it?}
{112}{021}{How you two ended up here?}
{113}{020}{Why are you so worried about Jackals?}
{114}{999}{Nothing for now, I need to look around.}


{120}{}{[He gives his companion a look full of misery, but she persistently avoids it] Okay, ask. It's not like you are going anywhere. As if the Jackals are not enough for me...}
{121}{013}{You have found a jumpsuit with NCASTR logo some time ago. Do you still have it?}
{122}{021}{How you two ended up here?}
{123}{020}{Why are you so worried about Jackals?}
{124}{999}{Later, I need to look around.}


{130}{}{[Fred looks surprised] A jumpsuit? Yeah, I have it. Took it from the corpse. The body was completely rotten and partially eaten by molerats, but strangely enough, the jumpsuit wasn't affected in the slightest. Why do you ask?}
{131}{014}{I am sure I need this jumpsuit more than you.}
{132}{012}{We'll talk about this later. I have other questions.}
{133}{999}{You'll know soon. When I'll come back.}


{140}{}{[He starts to thoughtfully scratch his chin] Is it, like, a memorabilia? A dead relative or something? Although, why do I care. No problem, but I need a favor from you.}
{141}{015}{Favor? What favor?}


{150}{}{[He looks back on the girl and lowers his voice] That's the thing... When we settled here, I laid some mines around the house. You know, Jackals and such. Plus, the chimeras often come around. But, uh... [he embarrassingly sniffles] I was in a hurry, so as managed to dig the mines down, I noticed some chimeras and accelerated into the house... I mean, to protect Christy, don't take me wrong! [seems like the girl heard him, after all. She gives Fred a cold look, irritatingly kicks an empty can and walks away into farther corner of the room. Fred only sighs] The thing is, with all this running I forgot where exactly I planted the mines. That's where I need help. Make us some path through the field. You would need to dig up only around five of them.}
{151}{016}{That's it? Why don't you do it yourself then?}
{152}{024}{It is easier for me to kill you off, you sinner of an asshole. And you can't hide from me, I'm not a chimera...}
{153}{999}{I need to think it over... Talk later.}


{160}{}{I wanted to, but uh, didn't have time... There is a... So much to do, you know. Housekeeping. [the girl gives out a chuckle, but then just sighs.]}
{161}{999}{Okay, I'll do it. Be back soon. In one piece, I hope.}
{162}{024}{So many problems with you. I'll better do what Jackals couldn't - paint this walls with your blood.}
{163}{017}{Hey, why do you want to miss the chance of showing Christy who you really are? You do want her to look at you differently, right? And it's not about killing a chimera with bare hands - just to dig around for a little. Girls like men who ready to take risks for them, believe my experience.}
{164}{999}{I see... I'll think about something and we'll continue the conversation.}


{170}{}{[Looks like you pushed his buttons] This, uh... Fuck me, maybe you are right. Of course, I can do it... But... [you observe his internal struggle for some time] Oh man, really, screw it, I'll do everything myself! [he grabs some kind of an instrument from the table and hurries to leave, while he didn't change his mind. You and Christy eagerly listen, awaiting for the sound of explosion, but instead, after some time, you see Fred breaking into the room, even more pale and trembling than before. Despite that, he has a smile on his face - although, a little unnatural.]}
{171}{018}{So, how did it go?}


{180}{}{[He sits down, leaning to the wall, with his legs shaking] It's done... I'm so good!! [he giggles hysterically] Man, that was... Take the jumpsuit, here is it, under the table. That's my grattitude for motivating me to do it. Now Christy is definitely impressed, right?}
{181}{999}{It's your business now. I'm going then. Maybe I'll see you around.}
{182}{999}{Sure! Exactly that. Well, I won't bother you anymore.}


{190}{}{No way! Shit, I was sure that your intestines are gonna be scattered around all the wasteland! You did great, no questions! [he puts his hand under the table and pulls out rolled jumpsuit] One moment... Here you go. Good suit, huh?}
{191}{999}{Will do. Okay, I'll go now. See you around, Jackal... I mean, ex-Jackal.}
{192}{999}{That's what I need. I need to go now. Good luck.}


{200}{}{[He nervously pulls greasy locks of hair from his forehead] What, you don't know? They are the most head-frosted gang of the whole Radius! And they doesn't forgive those who bertrays them. And that counts us, with Christy. [nods in girl's direction] If you hadn't interrupted us, I would talk her into leaving this place. It's dangerous to stay in one place for too long... [he mumbles] Maybe I'll have to leave on my own in the end...}
{201}{022}{Looks like Christy means a lot to you.}
{202}{012}{I see. Another question then.}
{203}{999}{Let's finish for now.}


{210}{}{How... We are good at running, that's how. [He stops talking, looking on the ground] It all started when me and my pack rocked some settlement... Shaked it to the bottom. We disposed of everyone, except the girls... And that's when I saw her. I mean, look at her! I would never have any chance with a girl like this in the Jackals, you know? So I dealt with it my way. I took her and ran off. Here. Me and Ursul stumbled upon this place once, while hunting. It was him who pointed you, wasn't he? No one else knows... And now we are considering our options on what to do next. That's how it is.}
{211}{022}{Looks like Christy means a lot to you.}
{212}{012}{I see. Let's talk about something else.}
{213}{999}{We'll continue the conversation later, if you don't mind.}


{220}{}{[He takes on a dreamy look, picking his teeth with a finger] I guess... I didn't even know there could be someone like her. Fuck! The rat fur stuck in my teeth again... What I mean is - this is not how I imagined everything to end. If someone told me that I would have such big problems with the Jackals, I don't know if I would took her away... [He ponders, looking at Christy. Looks like the girl is busy with trying to make something to eat.] But maybe it's worth it?}
{221}{023}{Who the hell needs you, hero? Do you think that Jackals have nothing to do without chasing off runaways? Did you see even one of them since you ran off?}
{222}{012}{You decide it. And tell me this...}
{223}{999}{Okay, I need to go. Thanks for the information.}


{230}{}{[He hesitates for a while, but then firmly shakes his head] No, I won't take such risks. Who knows what Loudmouth thinks? He's not the one you should mess with... }
{231}{012}{Suit yourself. Better answer me something else.}
{232}{999}{As you see fit. Well, I need to go.}


{240}{}{[He picks up his gun again, pulling himself back] Try it, bitch! Christy, run!!}
{241}{998}{No one leaves this place alive!}
{242}{998}{Try it? Watch!}