##############################
#Локация: Фред
#Имя: Фред
#Краткое описание: Бывший Пес. Квест на мины.
#Дата создания: 12.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a nervous man.}
{2}{}{He is so pale that it looks like he's glowing.}
#
# после знакомства
{3}{}{You see Fred.}
{4}{}{A paranoid ex-Jackal.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[A skinny man, pale as a ghost and wearing a riveted jacket with lots of patches, is in a heated argument with a tall, red-haired girl. Upon seeing you he quickly pulls out his pistol, almost shooting himself in the leg in the process. Going even more pale, he still manages to points the gun at you with two shacky hands. You notice the blurry letters "FRED" tattoed on the knuckles on both of them.] Stay where you are! What the hell do you want here? How did you find this place?!}
{11}{011}{Listen you clown, If you keep waving the piece like that, I'll shove it up your ass. I only need some information, but I can change my mind anytime.}
{12}{011}{Hey, easy, alright? I just want to ask a couple of questions, that's all.}
{13}{999}{Whoa! I'm going to slowly back up until you pull yourself together. Don't scare the girl...}


{1001}{}{[He starts to shiver, but almost immediately supresses it and looks at you menacing. Then he glances at the girl, checking if she saw his fear] It would be better for everyone if you'll just go away now, fast. Do I need to repeat that?}
{101}{012}{I leave when I want to. Better answer me some questions.}
{102}{019}{I'm done with the mines.}
{103}{016}{Are we good about the robe deal? Or have you decided to take on the mines yourself?}
{104}{999}{Don't move, I need to look around here. I'll leave this place soon.}
{1002}{}{[Nods at you with a sour smile] Oh, Mr. Cool Guy... Where did you even come from... }
{105}{012}{Actually, you should be grateful. Tell me about...}
{106}{999}{We'll split soon enough, don't sweat it. I'm already sick of your constant whining.}
{107}{999}{Don't worry, I'll leave you soon. I just need to finish one thing.}


{110}{}{[He slowly puts the gun down and cringes, as if waiting for a blow. You notice a displeased look from the girl as she sees that] Chimera shit... I thought it's the Jackals. Still, just because you're not one of them, doesn't mean you are welcomed here! Got it? What do you want from us, anyhow?}
{111}{013}{You've found a robe with the NCASTR logo some time ago. Do you still have it?}
{112}{021}{How did you two end up here?}
{113}{020}{Why are you so worried about Jackals?}
{114}{999}{Nothing for now, just looking around a bit.}


{120}{}{Okay, ask. It's not like you're going anywhere. As if the Jackals were not enough to deal with...}
{121}{013}{You've found a robe with the NCASTR logo some time ago. Do you still have it?}
{122}{021}{How did you two ended up here?}
{123}{020}{Why are you so worried about Jackals?}
{124}{999}{Later, I need to have a look around.}


{130}{}{A robe? Yeah, I have it. Took it from a corpse. The body was completely rotten and partially eaten by molerats, but strangely enough, the robe wasn't affected in the slightest. Why do you ask?}
{131}{014}{I'm sure I need this robe more than you do.}
{132}{012}{We'll talk about this later. I have other questions.}
{133}{999}{You'll find out soon enough. I'll be back.}


{140}{}{[He thoughtfully scratches his chin] What's it to you? Some kind of like... memorabilia? From a dead relative or something? Ah, what do I care? No problem, but I need a favor from you.}
{141}{015}{Favor? What favor?}


{150}{}{[He glances furtively at the girl and lowers his voice] Here's the thing... When we settled here, I laid some mines around the house. You know, against Jackals and such... plus, the Onca Devils often come around. So, uh... [He sniffles embarrassingly] when I was finishing placing the mines, I noticed some Onca Devils nearby and rushed into the house... to protect my Christie, of course! [Seems like the girl heard him after all. Giving Fred a far from affectionate look, she kicks an empty can in annoyance and walks into the farthest corner of the room. Fred sighs and continues in a normal tone] The thing is, with all this running I forgot where exactly I planted the mines. That's where I need help. Clean us a path through the field, there are only about five mines you would need to dig up..}
{151}{016}{That's it? Why don't you do it yourself then?}
{152}{024}{It is easier for me to kill you off, asshole. And you can't hide from me, I'm not an Onca Devil...}
{153}{999}{I need to think it over... We'll talk later.}


{160}{}{Yea, I wanted to, but uh, didn't have the time... There is, uh... so much to do, you know... keeping the house clan and stuff... [The girl chuckles at this, but then just looks at him sighs.]}
{161}{999}{Okay, I'll do it. Be back soon. Hopefully in one piece...}
{162}{024}{So many problems with you. I'll better do what the Jackals couldn't - paint the walls with your blood.}
{163}{017}{Hey, why would you want to miss the chance of showing Christie what you are capable of? You don't want her to look at you differently, right? It's not like about killing an Onca with your bare hands - just digging around a bit. Girls like men who are willing to take risks for them, trust my experience.}
{164}{999}{I see... I'll figure something out and we'll talk again.}


{170}{}{[You've seem to hit a nerve with that] This, uh... Fuck me, maybe you're right. Of course, I can do it... but... [You spend some time admiring the struggle of self-conceit with caution for a while] Ah, to hell with it, I'll do everything myself! [He grabs a tool from the table and hastily leaves before changing his mind. You and Christie eagerly listen, expecting the sound of an explosion. But instead an even more pale and agitated Fred bursts into the room after some time again. Despite that, he has an unnatural looking smile stuck on his face.]}
{171}{018}{So, how did it go?}


{180}{}{[He sits down with shacky legs, leaning to the wall] It's... done. I'm so good! [He giggles hysterically] Man, that was... Take the robe, here it is, under the table. As an appreciation for motivating me to do it. Now Christie is definitely impressed, right?}
{181}{999}{Well, that's your business. I'm going now. Maybe I'll see you around.}
{182}{999}{Sure! Exactly that. Well, I won't bother you anymore.}


{190}{}{No way! Shit, I was sure that all your intestines would be scattered around the wasteland! You did a great job, no question! One moment... [He puts his hand under the table and pulls out a bundle of cloth] Here you go. Looks good, right?}
{191}{999}{Will do. Okay, I'll go now. See you around. Go get her, you Dawg!}
{192}{999}{That's what I needed. Well, gotta go. Good luck to you.}


{200}{}{[He nervously pushes greasy strands of hair from his forehead] What, you don't know? They're the most hardass gang of the whole Radius! And they don't forgive those who betray them. I tossed that all for Christie. [Nods in girl's direction] If you hadn't interrupted us, I would talk her into leaving this place. It's dangerous to stay in one place for too long... [He mumbles] Maybe I'll have to leave on my own in the end...}
{201}{022}{Looks like Christie means a lot to you.}
{202}{012}{I see. Another question then.}
{203}{999}{That's all I wanted, bye.}


{210}{}{How... We ran fast, that's how. [He pauses, looking at his feet] It all started when me and my pack sacked some settlement... raised it to rubble. We disposed of everyone, except the girls... And that's when I saw her. I mean, look at her! I would never have any chance with a girl like this in the Jackals, you know? So I dealt with it my way. I picked her up and ran straight here. Found this Hut with Ursul once, surveying the area. He's the one that tipped you of, hasn't he? No one else knows... Now we are considering our options what to do next. That's how it is, Bro.}
{211}{022}{Looks like Christie means a lot to you.}
{212}{012}{I see. Let's talk about something else.}
{213}{999}{We'll continue the conversation later if you don't mind.}


{220}{}{[He picks his teeth with a finger, a dreamy look on his face] Yeah... didn't even know there could be someone like her... Fuck! The rat fur stuck in my teeth again... Not how I imagined it though... If someone told me beforehand that I would have such big problems with the Jackals from this, I don't know if I would have taken her away... [He looks thoughtfully at Christie, who is assembling something that looks like dinner] Though, maybe it's worth it in the end?}
{221}{023}{Who the hell needs you, hero? Do you think that the Jackals have nothing better to do than chasing runaways? Did you see even one of them since you ran off?}
{222}{012}{That's up to you. Tell me something else...}
{223}{999}{Okay, I need to go. Thanks for the information.}


{230}{}{[He hesitates for a while, then shakes his head firmly] No, I won't take such a risk. Who knows what Loudmouth thinks? He's not one you should mess with... }
{231}{012}{Suit yourself. Better answer me something else.}
{232}{999}{As you wish. Okay, I have to go.}


{240}{}{[He grabs his gun again, pulling away from you] Try it, bitch! Christie, run!}
{241}{998}{No one leaves this place alive!}
{242}{998}{Try it? Watch this!}