##############################
#Локация: Livos
#Имя: Абилин McKinsey
#Краткое описание: Сестра-жена Boston McKinsey, мать-курица-наседка.
#Дата создания: 26.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a sloppy woman.}
{2}{}{Somehow she sticks out of the general pomposity of this place.}
#
# после знакомства
{3}{}{You see Abilene McKinsey.}
{4}{}{The look of frustration on her face became even more noticeable. Or maybe not.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see an overweight, middle-aged woman in untidy clothes. Looks like she stopped looking after herself a long time ago] Look what the wind blew in... What are you sniffing around?}
{11}{002}{I arrived in Livos recently, meeting my new neighbors.}
{12}{003}{I'm new here. Just looking around the vault.}
{13}{004}{None of your business. I walk wherever I want.}

{20}{}{[The woman makes a disgusted face] Everyone comes here, distracting me... Meeting neighbors? Well, I'm Abilene McKinsey. And now go meet someone else.}
{21}{010}{Wait a second, Abilene. Can you answer a few questions?}
{22}{999}{Glad to meet you. And I'll go do just that.}

{30}{}{[The woman makes a disgusted face] Everyone comes here, poking their noses... Just looking around? Well, nothing to look at here. I'm Abilene McKinsey, it's only me and my belongings in here. Go look around somewhere else.}
{31}{010}{Wait a second, Abilene. Can you answer a few questions?}
{32}{999}{You are right, I'll go into other places.}

{40}{}{[The woman gets angry] You have no business here! According to paragraph 4 of our Constitution: "Every inhabitant of the New World has the right to walk around his territory of the New World, without asking permission of other inhabitants of the New World". So, this is my territory, it belongs to Abilene McKinsey! And I didn't give you permission to walk around here! Go walk around yours!}
{41}{010}{Okay, but first - answer a few questions.}
{42}{999}{I'll go wander around mine.}

{1001}{}{What can auntie Abilene do for you, patron?}
{1002}{}{[She has a disgusted look] Ask your question and stop distracting me with your petty things.}
{1003}{}{Again? What are you sniffing around this time?}
{101}{011}{Ludwig lost his book on wave science. Did you see it?}
{102}{012}{What do you do here?}
{103}{022}{What can you tell me about Livos?}
{104}{025}{Got any job for me?}
{105}{999}{I need nothing right now. Talk later.}

{110}{}{No, I didn't see any book. And even if I did, I wouldn't tell you. Ludwig completely lost his mind with all this hoity-toity tech stuff. He talks to no one, not even to his wife, maybe they don't even sleep together anymore. One time I saw my husband, Boston, hitting on Ludwig's wife, Veronica. Oh, this animal Boston ruined my life, damn womanizer! I spent my best years on him, and he doesn't even respect me!}
{111}{010}{I see. Let me ask something else.}
{112}{999}{Okay, I'll go ask others about the book.}

{120}{}{[Abilene unhappy grumbles] Nothing. I do nothing. [she raises her voice] And I have the right to do so! According to paragraph 10 of our Constitution, "Every inhabitant of the New World has the right to do nothing at all"! I know my rights and not afraid to use them! For example, do you call yourself an inhabitant of the New World, or not? }
{121}{013}{Yes, of course, I do.}
{122}{021}{No, I don't.}
{123}{020}{I have no idea what it is or what it means.}

{130}{}{Yes, According to the first paragraph of our Constitution, "Every inhabitant of the New World has the right call himself and/or others inhabitants of the New World "inhabitants of the New World". And did you attend the last official meeting of inhabitants of the New World?}
{131}{014}{No, I didn't.}
{132}{019}{Yes, I was there.}
{133}{016}{I don't understand what you are talking about.}

{140}{}{Gotcha! According to paragraph 12 of our Constitution, "Every inhabitant of the New World has the right not to attend (be absent from) official meetings of inhabitants of the New World, but if this is the case, he loses all rights until attending the next meeting". So now you don't have the right to call yourself an inhabitant of the New World!}
{141}{015}{Okay, I won't call myself that. }
{142}{017}{I'm still going to call myself that.}

{150}{}{There, listen to auntie Abilene and you will never violate the Constitution. You have a lot to learn, youngster.}
{151}{010}{Whatever you say. I want to ask something else.}
{152}{999}{I'll go think about my behavior.}

{160}{}{Gotcha! According to paragraph 15 of our Constitution, "Every inhabitant of the New World has the right to not know the rights, described in this Constitution, but if this is the case, he loses all rights, including this one, until learning the rights". So now you don't have the right to call yourself an inhabitant of the New World!}
{161}{015}{Okay, I won't call myself that. I'm going to learn my rights.}
{162}{017}{I'm still going to call myself that.}

{170}{}{[Abilene looks terribly angry] But you don't have any right! You are violating the Constitution! This is outrageous! Do you youngsters respect anything anymore?}
{171}{015}{I realized my mistake. I won't do it again.}
{172}{018}{I don't really care.}

{180}{}{[Abilene is boiling with resentment and discontent. She is visibly shaking] You don't really care?! Then get out of here, I don't want to see you anymore!!!}
{181}{999}{Okay.}

{190}{}{Good, then you are not in violation of anything. There, listen to auntie Abilene and you will never violate the Constitution. You have a lot to learn, youngster.}
{191}{010}{Whatever you say. I want to ask something else.}
{192}{999}{I'll go, need to violate a couple of rights from the Constitution. Bye.}

{200}{}{Gotcha! According to paragraph 15 of our Constitution, "Every inhabitant of the New World has the right to not know the rights, described in this Constitution, but if this is the case, he loses all rights, including this one, until learning the rights". So now you don't have the right to not know the rights of the Constitution! You have to learn them!}
{201}{015}{Okay, I will learn the rights. }
{202}{017}{I'm not going to learn anything.}

{210}{}{Okay, according to paragraph 14 of our Constitution, "Every inhabitant of the New World has the right not to be entitled to the rights described in this Constitution". So if you don't want to have the right to call yourself an inhabitant of New World, then it's your right.}
{211}{019}{Yes, I'm using my right not to be entitled to my rights.}
{212}{018}{I just don't really care what is written in this Constitution of yours.}

{220}{}{Livos is our home, and now yours too. The vault was built a very long time ago, we all live here almost without any conflicts. Why would we, the McKinseys, quarrel with other families? We are the most important here, after all! And we are very kind, so we let the other families live with us here and do their little useless jobs.}
{221}{023}{Tell me about your family.}
{222}{024}{What can you say about the other families in Livos?}
{223}{010}{I want to ask something else.}

{230}{}{[Abilene cheers up] The McKinseys are the most powerful family in Livos! My husband Boston gives speeches at meetings, my lovely son Dallas trades water. He is such a wonderful boy! If someone tries to harm him, I'm gonna choke them with my bare hands! He is the best! Even my daughter Fox is into him. And I don't really mind, I understand her really well... But Boston is categorically against them having a relationship. What choice does Fox have, if the best man in the whole of Livos is her own brother? My husband just doesn't get it.}
{231}{024}{Tell me about the other families.}
{232}{010}{Let me ask about something else.}

{240}{}{[Abilene contemptuously chuckles] What's there to say about them? A bunch of pathetic losers, that's who they are! I interact only with Emily Dunton, we play cards sometimes. She is very competitive, but she always pays her debts. Sometimes I think that if she loses her life in a game of cards, she would go as far as killing herself.}
{241}{023}{What can you tell me about your family?}
{242}{010}{I want to ask something else.}

{250}{}{No, I don't have any job for you. Ask my husband Boston. Maybe he has something for you to do.}
{251}{010}{I want to ask something else.}
{252}{999}{Okay, I'll go talk to him.}

{255}{}{I don't want to see you!}
{256}{}{I'm not going to talk to you!}
{257}{}{Get out of here!}
{258}{}{I told you, I'm not going to talk to you!}
{259}{}{I won't tell you anything!}