##############################
#Локация: Livos
#Имя: Boston McKinsey
#Краткое описание: 
#Дата создания: 23.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a chunky, plumb cowboy.}
{2}{}{His greasy squinted eyes patronizingly gaze at everyone around.}
#
# после знакомства
{3}{}{You see Boston McKinsey.}
{4}{}{Wearing dashing spurred boots, he looks very vivid.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see an obese man with a red face and shifty eyes] Whoa! Who's that? That's someone new! Hey, look, he's here! Let's get acquainted, newbie-doobie! Hahahah, I'm kidding! Come here, give a little hug to old Boston McKinsey! [He spreads his fat arms trying to hug you]}
{11}{002}{[You take a few steps back] Pleased to meet you. No need for hugging. I just want to ask a few questions.}
{12}{003}{[You lean back a little and shake his hand] Glad to meet you. I want to know something.}
{13}{004}{[You are trying to hug him back, but lack the length of hands, because of Boston's huge belly] Howdy, Boston! I'm glad to see you too!}

{20}{}{[He disappointedly puts his arms down] How impolite! So rude! He is met with open arms - and turns his nose up! Man! You must be another bore, who's afraid of his own shadow.}
{21}{005}{I just don't like hugging strangers.}
{22}{006}{Yes, I'm trying to keep a low profile.}
{23}{004}{You got it all wrong, I was just taking some acceleration for a good hug!}

{30}{}{[He looks a little disappointed] Man, how official! So sour and boring! It is not a trade deal, it's the greeting of the new inhabitant of Livos!}
{31}{005}{I don't know you too well to hug.}
{32}{006}{I want to talk business.}
{33}{004}{Hugs - only after official introduction. Which was just now!!}

{40}{}{[Boston explodes with a loud laugh] HAAHAhahahahuehue!! Man, you are quite alright! It's gonna be a lot more fun around here! Because for now, it's kinda stale, but we'll show them! Hahahahah!!}
{41}{010}{Of course we will! And now I want to ask something.}
{42}{999}{Okay, Boston, I have no time now, let's talk later.}

{50}{}{[Boston wrinkles] Man, so touchy! Boo-hoo! What do you want, your highness?}
{51}{010}{I want to ask a few questions.}
{52}{999}{Nothing for now. Let's talk later.}

{60}{}{[Boston playfully stands still, clicking heels, taking a serious look] What would you like, Mr. Boring Person? }
{61}{010}{I want to ask a few questions.}
{62}{999}{Nothing for now. Let's talk later.}

{1001}{}{Who is this I see! It's our new patron! Came to talk to good old Boston?}
{1002}{}{Ask your questions to me, but don't put nose everywhere you see! Hahahaha! }
{1003}{}{Who is that I see! Hello there! Came again to talk to good old Boston?}
{101}{024}{I want to know more about this place.}
{102}{013}{Do you know what I can do around here?}
{103}{014}{What are you busy with here?}
{104}{011}{Did you see Ludwig's book on wave science?}
{105}{029}{I want to talk about Claudia.}
{106}{041}{I've talked to Seth and Matt from NWO. They want to know with whom from Livos to forge an alliance.}
{107}{999}{Let's talk later, I need to go.}

{110}{}{A book of waste science? Hahahaha! Books? Books are boring! Let these eggheads read their books, I wouldn't buy that for a battery! Who needs it?}
{111}{012}{Would you know who might take it?}

{120}{}{No idea! This bore Ashton Horton is always digging through some books. My daughter Fox is also reading some magazines. And there's Ludwig himself. He probably put it somewhere and forgot where.}
{121}{010}{Let's talk about something else then.}
{122}{999}{Okay, I'll go look in other places.}

{130}{}{We have a lot of work, sure! There, you can go clean the toilets. Hahaha! Just kidding, I have no job for you, I handle mine just fine. Ask someone else.}
{131}{014}{And what's your job?}
{132}{010}{I want to ask something else.}

{140}{}{[Boston takes a proud look] I am the head of McKinseys, the most important family in Livos! And my job is to run the whole thing! My speeches on meetings have a tremendous influence. Sometimes even leading to fights. [he suddenly stops talking] Uhh... Also, I watch over my son, Dallas. He is busy with supplying water to other settlements.}
{141}{015}{There was a problem in NWO with your last batch of water. It has some confusing flavor. Can you tell me why?}
{142}{026}{Fights? Tell me more.}
{143}{016}{What else can you tell me about the McKinsey family?}
{144}{025}{What are the other families in Livos busy with?}

{150}{}{[Boston thinks] Hrm... I don't know what's wrong with the water. I don't poke into this kind of thing, really. Dallas deals with it himself. }
{151}{999}{Okay, I'll go ask him.}
{152}{010}{I'll talk to him later, and now I want to ask you something else.}

{160}{}{The McKinsey family is the heart of Livos! We are responsible for the most valuable thing there is - clean water! I can destroy an unfriendly town just by stopping the shipments of our water to it! And then burn their dried corpses, hahaha! So, you see that McKinseys are the most important in Livos.}
{161}{017}{What can you tell me about other McKinseys?}
{162}{010}{I want to ask about something else.}

{170}{}{My son Dallas, is responsible for water dealings. He is a little boring, but he knows his stuff. Although he is so bad at having fun! Stands silently at the meetings, so I have to carry it for all McKinseys there! My wife Abilene is always clucking with Emily Dunton, playing cards all day. [Boston makes a deep sigh] And there's my daughter Fox... Oh man, so many problems with her...}
{171}{018}{What kind of problems?}
{172}{010}{I see. Let's change the subject.}
{173}{025}{What can you tell me about other families in Livos?}

{1801}{}{[Boston suddenly flips out] That is not your business! I can deal with the problems of our family myself, hear me?}
{1802}{}{[Boston suddenly flips out] This little brat has no brains at all! Imagine that, she wants to marry her own brother! Where did she even get this from? Me and my sister are categorically against such marriage!}
{181}{010}{Okay, calm down. I want to ask something else.}
{182}{022}{Your sister? You didn't mention that you have a sister.}
{183}{021}{Who should become her husband then?}
{184}{019}{If they love each other, why not let them marry?}
{185}{999}{Easy there. We'll talk later.}

{190}{}{[Boston start shouting, flailing hands] What?! You too? I will never let that happen! This is ridiculous! One more word and I won't be responsible for my actions!}
{191}{020}{Just let them marry! And kiss, and hug each other, and sle...}
{192}{010}{Easy, calm down. Let's change the subject while it hasn't gone too far.}
{193}{999}{Looks like you're on edge. I'll come by later when you calm down.}

{200}{}{That's it, I'm sick of it! Come here, I'm gonna screw off this stupid head of yours!}
{201}{998}{Uh, wait!..}

{210}{}{Christopher Schwein! Or someone from a dozen people in the Chamber of Commerce! Oh, I know! You are not married, are you? Go talk to her! We'll marry you in a moment!}
{211}{010}{Uh... Actually, I have a- ...Let's talk about something else.}
{212}{999}{I need to go. Very urgent.}

{220}{}{I mean Abilene! She is my wife - and also my sister! We were together forever, that's why she is the one for me! And she fully supports me in this matter! Fox should forget about Dallas!}
{221}{023}{Wait a second. You are married to your sister. And you are against Fox marrying her brother?}

{230}{}{Of course I am! What's not to understand here? Where'd she get an idea like that?! Unthinkable!}
{231}{010}{Ahem... Let's talk about something else.}
{232}{999}{Yeah. You figure this out and I'll go.}

{2401}{}{Patron, you are not yourself lately, aren't you? Didn't you already study Livos? The families of McKinseys, Schweins, Hortons, and Duntons are living here. [Boston widely smiles] But, except for McKinseys, all of them are total morons! Hahahah! }
{2402}{}{Livos is the best! Here gathered the best people of Radius! You already noticed that! The families of McKinseys, Schweins, Hortons, and Duntons are living here. [Boston widely smiles] But, except for McKinseys, all of them are total morons! Hahahah! }
{241}{025}{And what are they all doing here?}

{250}{}{[Boston looks disgusted] This boring pencil-pusher Ludwig Schwein digs through his cogs, his boring son Christopher deals with boring tradings at the entrance, boring old man Edward boringly sits his pants in the surveillance room. Ashton Horton, that pompous boring fool, turns screws. And boring Emily Dunton is busy only with interfering with the others on meetings! [His smile becomes sad] Livos is a swamp, Livos is full of dumbs! Hahahaha!}
{251}{010}{I see. I have another question.}

{260}{}{[Boston becomes very nervous, turning his eyes away from you] It's nothing... There was one case... I mean, there was this accident!! [he inadvertently starts shouting] It's all their fault! They purposefully angered me! Poor Peter Horton, they threw him on me!}
{261}{027}{Who? Peter Horton?}

{270}{}{[He starts frantically fumbling his clothes] Peter... Claudia's husband... We had an argument at the meeting, about inverting the third and fourth paragraphs of the Constitution of 15 right. It is obvious that to wander around the territory is more important than to emit gases! Emily Dunton has also fanned the fire a little with her words, so I couldn't stand it and pushed Peter. He badly fell, hitting his head...}
{271}{028}{And? What happened next?}

{2801}{}{[Boston starts to whine] He died! Can you imagine? Died! Poor Peter... And his wife, Claudia, is dead too. I hope they found each other after death... [he turns away from you. Looks like he doesn't want to talk anymore.]}
{2802}{}{[Boston starts to whine] He died! Can you imagine? Died! Poor Peter... Claudia, his wife, is following me now, harassing me all the time. She is driving me crazy! [he starts shouting again] My god!! I didn't want to kill him! We were just arguing! Why won't she leave me alone?! [he turns away from you. Looks like he doesn't want to talk anymore.]}
{2803}{}{[Boston starts to whine] He died! Can you imagine? Died! Poor Peter... Claudia, his wife, used to harass me all the time. But now she forgave me.}
{281}{040}{Boston, let me handle your conflict with Claudia.}
{282}{999}{Such a sad story. Let's talk later.}

{290}{}{Yes? Did you manage to handle the conflict with Claudia? Would she stop harassing me?}
{291}{030}{She won't harass you. At all. She had an accident happening to her.}
{292}{031}{I talked Claudia into living you alone.}
{293}{032}{I talked Emily into arranging a commemorative evening dedicated to Peter. Claudia will be happy and should stop bothering you.}
{294}{033}{What if you just apologize to her?}
{295}{035}{I have an idea...}
{296}{010}{No, I'm still thinking about it. I wanted to ask something else.}
{297}{036}{I told Claudia that I avenged Peter's death. She should be calmer now.}

{300}{}{[Boston becomes pale] Oh god, what happened to her? [suddenly he smiles] But she went so crazy lately... So it's even better! Here, take it! You deserved it! [he hands you a custom-made "Slugger" pistol]}
{301}{999}{She is with her husband now... Bye, Boston.}
{302}{}{Yeah, sure [Boston smiles] She's alright now, I guess? But, about your reward - sorry, but someone already took my "Slugger" off me. [he squints and suspiciously looks at you] I wanted to give it to you, but you're not mad at me, right? Thanks for taking care of the problem with Claudia.}

{310}{}{[Boston gets visibly happier] Man, you are so good! So good! Here, take this, you deserved it! [He hands you a custom-made "Slugger" pistol]}
{311}{999}{Now she'll calm down. Bye, Boston.}

{320}{}{[Boston gets visibly happier] Man, you are so good! So good! Here, take this, you deserved it! [He hands you a custom-made "Slugger" pistol]}
{321}{999}{Now she'll calm down. Bye, Boston.}

{330}{}{What? I have nothing to apologize for! It was not my fault! I won't apologize! What are you even saying?}
{331}{034}{It's the only way to get rid of her. You are one of the smartest people in Livos! Just pretend that you're sorry, she'll believe it! No one else would be able to deceive her like that! }
{332}{999}{Okay, let's find another way...}

{340}{}{Hah, that's for sure! I can deceive her! Okay, I'll go talk to her. I'll pretend that I am very sorry about Peter. And she's gonna believe it! You are cunning, aren't you? And helpful [he winks] Here, take this, a little reward from me! [He hands you a custom-made "Slugger" pistol]}
{341}{999}{Now she'll calm down. Bye, Boston.}

{350}{}{Yeah? Which idea?}
{351}{037}{I'm going to beat you up and tell her I avenged Peter. And she will leave you alone.}

{360}{}{[Boston touches his bruises] Good that it's not for nothing. Hah, she will definitely stop following me! Here, take this, a little reward! [He hands you a custom-made "Slugger" pistol]}
{361}{999}{Now she'll calm down. Bye, Boston.}

{370}{}{What?! I won't let you beat me up! Are you out of your mind?}
{371}{038}{Listen, a couple of scratches is a small payment for your peace of mind. I will hit accurately, but hard, so it would look real.}
{372}{999}{Okay, let's find another way...}

{380}{}{Uh... Okay, I'll endure it! Come on, hit me!}
{381}{999}{[You swing your fist...]}

{390}{}{[Boston holds his head] Ow, that hurts! Careful! Ow!}
{391}{999}{Done. Now I'll go to Claudia and tell her I avenged Peter. She will leave you alone after that.}

{400}{}{[Boston swiftly turns to you. There's hope in his eyes] Really? You will? That's wonderful! I'll do everything you say! Hell, I'm going to give you my gun, if you'll pull it through! Do everything you have to, but make this freaking psycho leave me alone!}
{401}{999}{Okay, I'll think about what can be done.}

{410}{}{So let them forge an alliance with each other! They can even take turns! Hahahaha! I've never heard about these pathetic weaklings. You can tell them that I don't care. Maybe some other family might want to deal with them, but not mine.}
{411}{010}{Okay, I'll ask others.}