##############################
#Локация: ЛАЙВОС
#Имя: Кристофер Швайн 
#Краткое описание: Заносчивый и жадный торговец оружием в Торговой Палате
#Дата создания: 20.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a tough, young man.}
{2}{}{He is busy inspecting some kind of energy weapon.}
#
# после знакомства
{3}{}{You see Christopher.}
{4}{}{Looks like he tolerates you only because you are a potential buyer.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a young man in good physical shape. His sight is clear and heavy.] Come closer, pick a gun! The best weapons in Radius are made in Livos! Everybody knows the quality of Schwein weapons!}
{11}{Barter}{Let's see what you have.}
{12}{010}{I want to ask some questions.}

{1001}{}{Hey, commander. Take your time, look around. These guns are the best!}
{1002}{}{Make it quick. I'm a busy man.}
{1003}{}{Hey. Take your time, look around. These guns are the best in the whole Radius.}
{101}{Barter}{Let's see what you have...}
{102}{012}{Tell me, which goods do you have in stock?}
{103}{011}{What do you do here?}
{104}{015}{What is this place?}
{105}{036}{There was a problem with the recent water delivery at NWO. I'm here to find out the reason.}
{106}{029}{I'd like to talk about Mignon Horton.}
{107}{035}{Can you give a discount? I'm one of us, after all. I'm a Livos dweller.}
{108}{038}{Christopher! I want to talk about Mignon's behavior!  }
{109}{999}{We'll talk later, bye.}

{110}{}{I deal in the best guns. Interested?}
{111}{Barter}{Yes, let's have a look.}
{112}{012}{What kind of guns are you selling?}
{113}{999}{No, I need nothing for now. I'll come by later.}
{114}{010}{I want to ask something else.}

{120}{}{Laser and energy weapons, suited for every taste. Take your time, look, choose.}
{121}{010}{Not now. I want to ask.}
{122}{Barter}{Show me what you have.}

{130}{}{I don't like small talk. To chat is a privilege of women. I talk business. }
{131}{017}{Are you always like this?}
{132}{040}{Sometimes you can do many things with just words.}
{133}{014}{The words are meaningless. I don't like small talk too.}

{140}{}{Right. Let's get down to business. What do you want?}
{141}{Barter}{I want to look at your stock.}
{142}{010}{I want to ask a question.}
{143}{999}{Nothing for now. Talk later.}

{1501}{}{Joking, commander? This is Livos.}
{1502}{}{This is Livos. }
{151}{016}{That's it? Tell me more details about this place.}
{152}{018}{Tell me about inhabitants of Livos.}
{153}{019}{Tell me about yourself.}
{154}{033}{What is behind that big metal door?}
{155}{013}{You aren't very talkative.}

{160}{}{[He is clearly irritated] More details? What the hell do you want? This is Livos. We trade clean water to the whole Radius. Sell the best guns. That's it. Stop bugging me with your chit-chat. Want to talk - find someone else.}
{161}{018}{Who lives here?}
{162}{Barter}{Can you show me the weapons you are selling?}
{163}{017}{Let's talk more particularly about Livos. }

{170}{}{[Christopher gets angry] You are pissing me off! Go fuck yourself! If you don't want to buy - get lost! }
{171}{Barter}{Okay, show me what you have.}
{172}{998}{YOU go fuck yourself, damn psycho!}
{173}{010}{Wait, I want to ask something else.}
{174}{999}{Easy. I'm already leaving.}

{180}{}{[Christopher nervously taps his fingers on the desk] Damn... Alright. Four families are living here. Hortons, Duntons, McKinseys, and us, Schweins. We are the most influential. We are in charge of tradings, security, weapon manufacturing. My uncle, Edward, guards the entrance. My father, Ludwig, is an engineer. Mother, Veronica, is a politician. What I do is obvious.}
{181}{022}{Who are Hortons?}
{182}{020}{Tell me about McKinseys.}
{183}{021}{What can you say about Duntons?}
{184}{010}{I see. I'll ask something else.}

{190}{}{Are you kidding me? I. Sell. Weapons.}
{191}{017}{What else can you say about yourself?}
{192}{Barter}{Show me what you have.}
{193}{010}{I wanted to ask something else.}

{200}{}{[He is visibly irritated by this conversation] McKinseys are trading with water. Dallas is responsible for it. Smart guy. Capable of running the business. Except he puts his nose where he shouldn't! The other McKinseys are a bunch of clowns.}
{201}{022}{What about Hortons?}
{202}{021}{What are Duntons doing?}
{203}{023}{What's the problem with Dallas?}
{204}{010}{I want to ask something else.}

{210}{}{[Christopher frowns with contempt] Duntons... Emily is the one with balls, she keeps her husband Soup under the thumb. Thinks she runs this place. Always pushes her idiotic ideas forward in the meetings.}
{211}{022}{What about Hortons?}
{212}{020}{Tell me about McKinseys.}
{213}{010}{Another question.}

{220}{}{[Christopher becomes more lively] Claudia and Ashton - phantasists and schemers. They have a daughter, Mignon. She is a wonderful girl! A little light-headed and chatty, but in a good way. Together with her beauty, it makes her ideal girlfriend! }
{221}{021}{Tell me about Duntons.}
{222}{020}{What can you tell me about McKinseys?}
{223}{024}{I suppose you like Mignon.}
{224}{010}{I want to ask something else.}

{230}{}{[His face darkens] It's about Mignon, my girlfriend. Not exactly my, actually. Dallas is hitting on her and wants to take her away from me! If not for him, we would be married already!}
{231}{028}{What can you say about Dallas?}
{232}{027}{Who Mignon wants to be with?}
{233}{024}{Do you want to marry her?}

{240}{}{[Christopher gets excited] Damn right, I love her! And I'm proud to love the best girl in Livos! }
{241}{025}{So what are you going to do?}

{250}{}{[He ponders] Don't know. I tried everything. It's obvious I'm the best choice for her. But she and this Dallas are always talking! And she likes to talk, as you probably noticed. Unlike me. Talking is not my strongest feat. If it continues like this, I might have some accident with Dallas. So, I need to convince her. Maybe give her a present. Something valuable. She likes smelly things, for example. I understand nothing in them.}
{251}{026}{I can try to talk with Mignon and Dallas. I am very persuasive. And I can look for something valuable or perfume-like.}
{252}{999}{Continue your love games without me. I have things to do. Bye.}

{260}{}{[Christopher gets a little happier] It's a pleasure doing business with you! Talk to them. Or bring me the present for Mignon. I'll give you a gun as a reward. Maybe even some rare prototype.}
{262}{}{[Christopher gets a little happier] It's a pleasure doing business with you! Talk to them. Or bring me the present for Mignon. I'll give you a gun as a reward. Maybe even some rare prototype. But first, you need to get inside. Talk to old man Schwein near the entrance. He'll make even a Chimera a member of Livos, in exchange for batteries or some rarity.}
{261}{999}{Great. Getting to work.}

{270}{}{She didn't make her choice yet. Dallas is pulling wool over her eyes, keeping us from being together.}
{271}{024}{Do you want to be with her?}
{272}{028}{Why does she talk to Dallas?}

{280}{}{Dallas is eloquent. He is calm, smart. Puts words into stories. Can make others do something for him. He is running his own game, trying to steal Mignon from me.}
{281}{025}{And what are you going to do about it?}

{290}{}{Did you talk to Mignon and Dallas? Or - did you find a valuable present?}
{291}{030}{I've found an actual perfume. It's a rarity. She will definitely like it!}
{292}{031}{Yes, I talked to them. Mignon has agreed to marry you. Dallas won't get in your way.}
{293}{010}{Not yet, I'm still working on it. I'd like to ask something else.}

{300}{}{[Christopher carefully takes the perfume] Great! This is the best! She will definitely appreciate it! Now she is mine for sure! So, here is the reward of your choice - plasma rifle prototype or laser pistol. Pick one.}
{303}{}{[Christopher carefully takes the perfume] Great! This is the best! She will definitely appreciate it! Now she is mine for sure! So, here is the reward of your choice - a plasma rifle prototype! Unique and deadly!}
{304}{}{[Christopher carefully takes the perfume] Great! This is the best! She will definitely appreciate it! Now she is mine for sure! So, here is the reward of your choice - laser pistol! Light-weight, precise and deadly!}
{301}{032}{[take the prototype]}
{302}{032}{[take the pistol]}

{310}{}{[Christopher happily smiles] Great! You talked them into it! You deserved the reward of your choice - plasma rifle prototype or laser pistol. Pick one.}
{313}{}{[Christopher happily smiles] Great! You talked them into it! You deserved the reward of your choice - plasma rifle prototype! Unique and deadly!}
{314}{}{[Christopher happily smiles] Great! You talked them into it! You deserved the reward of your choice - laser pistol! Light-weight, precise and deadly!}
{311}{032}{[take the prototype]}
{312}{032}{[take the pistol]}

{320}{}{[He gives you the reward] Here!}
{321}{999}{Thanks, Christopher. Bye.}

{330}{}{Behind this door are the Livos quarters.}
{331}{034}{Can I enter?}
{332}{999}{I see. I'll ask something else.}

{340}{}{No. Only inhabitants of Livos can enter.}
{341}{}{Of course. You are one of us. You can go whenever you want.}
{342}{010}{Another question.}

{350}{}{No discounts. If you are one of us, then your money will return to Livos through me.}
{351}{010}{I see. Another question.}

{360}{}{Hm... Boston McKinsey is responsible for the whole water supply. He is inside the vault. I heard there's some problem with the water filter, though. }
{361}{034}{Can I talk to him?}
{362}{037}{I could fix the filter. I'm good with fixing things.}

{370}{}{You are good at repairing water filters? Livos could use your skills. You'll become one of us then! I'll tell Edward by the entrance that we have a new inhabitant, who can repair things. Welcome to Livos. You can enter.}
{371}{999}{Thanks. I'll go fix the filter.}

{3801}{}{Yes? What is it?}
{3802}{}{I've talked to Mignon. Just as you warned, she denied everything. It's okay, I'll re-educate her eventually. For now, she understands everything and won't do something like this anymore. Or else I'm going to kick her teeth out.}
{381}{041}{She behaves badly! She says so many bad things about you!}
{382}{039}{She tried to hit on me! As your friend, I should inform you about it. She called you stupid and short-sighted. And she said that she can jerk you around as much as she wants. And even if you get married, she would still have an affair behind your back. "This cluck won't suspect a thing! I'll deny everything and he will believe me!", - that's what she said! }
{383}{010}{Actually, I wanted to ask something else.}

{390}{}{[Christopher clenches fists] Bitch! Cunt! Thanks, friend, I'll go talk to her. I don't know what I'm going to do! That bitch...}
{391}{999}{Sure, go! See you later.}
{392}{}{I don't know what I'm going to do! That bitch...}
{393}{}{I'm going to go talk to her...}
{394}{}{It's okay, I'll put some sense into her...}

{400}{}{Words can lead you to some missing teeth. Are you buying or not?}
{401}{Barter}{Yes, sure.}
{402}{010}{No, I wanted only to ask.}
{403}{017}{Words bear power. You can solve many problems with them.}

{410}{}{Huh. She talks too much. Many meaningless sounds. Women...}
{411}{999}{Okay, suit yourself. I'll go now [I should probably be more convincing]}