##############################
#Локация: Livos
#Имя: Claudia Horton 
#Краткое описание: Шизофреничная вдова Питера Hortonа
#Дата создания: 24.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a nervously looking woman with a glass of wine in her hand.}
{2}{}{She drinks, but her glass stays full.}
#
# после знакомства
{3}{}{You see Claudia.}
{4}{}{She has a glassy-eyed look.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a woman with tired eyes and lowered shoulders. She is constantly looking around, turning to every rustling sound. When you approach, she proudly raises her head] So, here you are at last. You came for me. I thought he would have the courage to do it himself, but he sent you. Get it done then, let's finish this.}
{11}{002}{Yes, I came to you. But what should I get done?}
{12}{004}{What do you mean?}
{13}{003}{Who did you mean should have the courage?}

{20}{}{[She buries her stare into you] It was bound to happen at some point, I knew it - but no one believed me. Today is the last day of Claudia Horton. Now Boston McKinsey's eternal pursuit of me is over. Soon I will reunite with my husband.}
{21}{005}{I didn't understand any of that. }
{22}{006}{Are you afraid of someone?}
{23}{998}{Yes, I came to kill you.}

{30}{}{[Her stare becomes cold as a steel] Boston McKinsey. Don't try to look like you know nothing. It is him who sent you to kill me, Claudia Horton. }
{31}{006}{He wants to kill you?}
{32}{005}{I don't understand. What are you talking about?}
{33}{998}{Yes, I came to kill you.}

{40}{}{[Her stare becomes cold as a steel] So, how do you plan to kill me? What fate Boston McKinsey prepared for Claudia Horton?}
{41}{006}{He wants to kill you?}
{42}{005}{What are you even talking about? I don't understand!}
{43}{998}{A sad way to go. Let's begin.}

{50}{}{What? You weren't sent by Boston McKinsey? Are you sure you didn't come to kill me?}
{51}{007}{No! I'm just looking around Livos, getting acquaintained with everyone!}
{52}{998}{I came exactly for that. Goodbye, Claudia.}
{53}{999}{I don't want to kill no one! I'd better hurry up and get away from here.}

{60}{}{Yes, Boston McKinsey wants to kill me. Didn't he send you?}
{61}{007}{No! I'm just looking around Livos, getting acquaintained with everyone!}
{62}{998}{Yes, he actually did. Goodbye, Claudia.}
{63}{999}{I don't want to kill no one! I'd better hurry up and get away from here..}

{70}{}{[You notice a glimmer of hope in her eyes] Really? Just getting acquaintained? Well, I'm Claudia Horton, the widow of Peter Horton. How can I help you?}
{71}{010}{I want to ask a few questions.}
{72}{998}{I was looking for you to send you to your dead husband. Goodbye.}
{73}{999}{Nothing for now, we'll talk later.}

{1001}{}{Boss, you are not being followed, are you? There was some shadow over there.}
{1002}{}{Ask, but remember - we could be watched and listened to.}
{1003}{}{Hey. Careful, there's someone eavesdropping around the corner.}
{101}{011}{I'm looking for Ludwig's book of wave science. Was it you who took it?}
{102}{017}{I want to talk about Boston McKinsey.}
{103}{022}{What's the problem with you and Boston McKinsey?}
{104}{025}{Tell me about inhabitants of Livos.}
{105}{026}{What can you say about families in Livos?}
{106}{999}{I don't have the time to talk right now. Let's do it later.}

{110}{}{[Claudia becomes visibly nervous, hiding her eyes] No, no, I didn't take anything from anyone...}
{111}{012}{I know you have the book. Someone witnessed you stashing it.}
{112}{010}{Huh. Okay. Another question then. [She is definitely not telling you something]}

{120}{}{Alright then. I admit, I took the book from Ludwig. But I hid it very well and you will never find it! And I'll deny everything if you tell someone!}
{121}{013}{Why do you even need it for? Ludwig can't continue his work without it.}

{130}{}{[Claudia looks around and whispers] I am going to make a death ray and destroy all McKinseys!}
{131}{014}{Claudia, you don't understand a thing in wave science. It'll take you years to develop a functional death ray. Ludwig, on the other hand, is going to make one already! I could take the book back to him - and then ask him to give first assembled weapon to you. What do you think?}
{132}{015}{Maybe I could buy it from you?}

{140}{}{Hmm, maybe you're right... I tried to figure out what to do, but unsuccessfully. Return the book to Ludwig, tell him to give me the death ray as soon as he finishes!}
{141}{010}{Okay. I want to ask something else.}
{142}{999}{As soon as he makes a death ray, you'll get it. I'll go give him the book.}

{150}{}{[Claudia thinks] I'm not interested in batteries. But if you could get something other for me, I would gladly return the book. I like the Spot-Up soda very much, I always want more - even dream of it at nights. Bring me 20 bottles and the book is yours. I can't understand anything in it anyway.}
{151}{016}{I have 20 bottles of Spot-Up with me. Ready to trade them for a science book.}
{152}{010}{I don't have so many bottles right now. I want to ask something else.}

{160}{}{[Claudia hands you the book, grabs the soda, opens one bottle right away and starts gulping the drink.] }
{161}{999}{...Okay, I'll go return the book then.}

{170}{}{What do you want to know about this maniac, who is haunting our family and killed my husband Peter?}
{171}{018}{I know what Boston did to Peter. I got angry and beat Boston senseless. Now peter is avenged and Boston won't be haunting Hortons anymore.}
{172}{019}{I talked to Boston, he is very sorry about what happened to Peter. He wants you to forgive him.}
{173}{021}{I talked to Emily Dunton. She wants to organize a commemorative evening dedicated to your husband. After that, Boston will leave your family alone.}
{174}{010}{You are right, nothing to talk about. I want to ask something else.}

{180}{}{At last, the justice was served! So it was you, a noble fighter for rightful cause! Boston got what he deserved, I've seen the results of your doing. Now I won't be afraid for my life anymore. I'm glad Peter has been avenged.}
{181}{010}{Don't worry, you're safe. Now, to other questions. }

{190}{}{I will forgive him when he leaves our family alone and stops harassing Hortons! }
{191}{020}{He gave his word not to harm you and your family. Forgive him.}
{192}{010}{Probably, he never will. I wanted to ask something else.}

{200}{}{Okay, I'll forgive him. Lately, he is not following us as often as before. Probably he really is sorry about Peter's death.}
{201}{999}{Okay, I'll tell Boston that you forgave him.}

{210}{}{I'm so happy! At last my husband will get the honors he deserves! And Boston will stop harassing Hortons. I would be glad to participate!}
{211}{999}{Good. I'm sure Peter is worthy of it. I'll go tell everyone.}

{220}{}{Boston McKinsey wants to destroy Hortons! He killed my husband Peter in cold blood! On a meeting, in front of everyone! And he got away with it!}
{221}{023}{Maybe it was an accident?}
{222}{024}{How exactly did he kill Peter?}

{230}{}{[Claudia angrily clenches her fists] Boston makes a clown out of himself and everybody believe it. In reality, under this mask of stupidity hides a dangerous murderer, who wants to take out all our family! No one listens to me, but I know the truth! I stalk him all the time and foil his plans.}
{231}{024}{How did Peter die?}
{232}{010}{I want to ask other question.}

{240}{}{They were arguing on a meeting about changes to the Constitution. Boston made it look like he had lost control and pushed Peter hard. And he did it so precisely that Peter died!}
{241}{023}{Looks like an accident to me.}
{242}{010}{Let me ask something else.}

{250}{}{Inhabitants of Livos are the descendants of great people. It is us, who destined to revive the civilisation, spreading the laws of a New World. This laws are the greatest achievement of our society. They are reflected in the Constitution of 15 rights. We will define new rules of living. For example, according to paragraph 2 of Constitution, "Every inhabitant of New World has the right to breathe (and also, to cough and sneeze) the air of the New World, without needing the permission from other inhabitants of New World". This is going to blow the minds of humanity, leading us towards the great future!}
{251}{010}{Yes, this looks important. Let me ask something else.}

{260}{}{The most important family in Livos is us, Hortons. Our ancestors were landlords and real estate owners, and my brother Ashton is rightful successor of the rights to own this whole place. We only let other families to live here because we are very kind. Ashton is the only one who can repair the vital equipment. If not for him, everything would break down here. Livos would fall into decline without Hortons. Schweins, McKinseys and Duntons are busy with petty things and do nothing important.}
{261}{010}{I see, Hortons are really important for well-being of Livos. Let's move to other questions.}