##############################
#Локация: ЛАЙВОС
#Имя: Даллас МакКинзи 
#Краткое описание: Занимается доставкой и продажей воды в Лайвос
#Дата создания: 20.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a calm, young man.}
{2}{}{His face doesn't express any emotions. }
#
# после знакомства
{3}{}{You see Dallas.}
{4}{}{He is still methodically doing his business.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a calm and serious young man] I'm Dallas McKinsey. What can I do for you?}
{11}{010}{I'm looking around, can you answer some questions?}
{12}{999}{I was just walking by.}

{1001}{}{Hey, patron. Want to talk business?}
{1002}{}{Sure, ask your questions, go ahead.}
{1003}{}{Hey. Want to talk business?}
{101}{011}{I'm looking for Ludwig's book of wave science. Did you see it?}
{102}{020}{Heard any rumors?}
{103}{013}{Tell me about this place. What's in here?}
{104}{014}{I want to know about the inhabitants of this place.}
{105}{024}{What is it that you do here?}
{106}{025}{I want to talk about water deliveries to the NWO.}
{107}{036}{Let's talk about Mignon.}
{108}{999}{I need to go. Talk later.}

{110}{}{[Dallas calmly looks into your eyes] I don't have his book. I'm not interested in science to such a degree.}
{111}{012}{Do you know who might've taken it?}

{120}{}{[Dallas thinks for a second] Let's see... My parents didn't take it for sure - they just don't need it. Fox also has no interest in a science book. She likes to read only some old magazines, mainly because of pictures. So - it's not McKinseys. Try to ask other families - Hortons or Duntons. }
{121}{023}{Tell me about your family.}
{122}{019}{What can you tell me about other families?}
{123}{999}{I see. I'll go look somewhere else.}

{130}{}{[Dallas leisurely starts talking] This vault was built around two hundred years ago. It's inhabited by four families - Schweins, Hortons, Duntons, and us, McKinseys. We all are the descendants of famous people.}
{131}{028}{I'd like to know more about Hortons.}
{132}{022}{Tell me about Duntons.}
{133}{021}{Can you tell me about Schweins?}
{134}{023}{I want to learn about your family.}
{135}{010}{I'll ask about something else.}

{140}{}{[Dallas smiles] Dwellers of Livos is the sorrow and delight of this place. On one hand, there are many different characters and world-views. On the other, they vary in range from fanatics to schizophrenics.}
{141}{018}{Who in Livos is the fanatic and who is schizophrenic?}
{142}{019}{Tell me more about inhabitants.}
{143}{016}{Oh yeah, since I have become the inhabitant of Livos, there's plus one more fanatic and schizophrenic!}
{144}{015}{What the dwellers are busy with?}
{145}{010}{I'd like to ask about something else.}
{146}{999}{I've just remembered I need to do something. We'll talk later.}

{150}{}{Every family has responsibilities and a sphere of influence. Who you want to know about - Schweins, Duntons, Hortons or us, McKinseys?}
{151}{022}{Duntons.}
{152}{028}{Hortons.}
{153}{021}{Schweins.}
{154}{023}{Tell me about your family.}
{155}{010}{I'm not in the mood to talk about families. Let me ask something else.}
{156}{999}{I don't have time to chat right now. I'd better go.}

{160}{}{[Dallas didn't even flinch] I never doubted it. Only a psycho would run around Radius, which is full of danger, bandits, and radiation. No offense.}
{161}{017}{What if this psycho would want to cave your head in?}
{162}{010}{Maybe. Let me ask something else.}
{163}{999}{Yes, I'm a psycho. I'd better go, I think I'm being followed.}

{170}{}{[Dallas makes a gesture with the palm of his hand] No need for aggression. Let's continue the conversation peacefully, without fights.}
{171}{998}{It's too late for that! I'm gonna bash your brains out!}
{172}{010}{Okay, I'm calm. I have other questions.}
{173}{999}{I'm kinda edgy right now, so I'll go cool off a bit. Talk later.}

{180}{}{[Dallas smiles] Oh, I can't deny you the pleasure of meeting them. You are going to like it, believe me.}
{181}{019}{I want to know more about the dwellers.}
{182}{010}{I'd like to ask about something else.}
{183}{999}{I'll go look for them. See you.}

{1901}{}{I don't think it would be right to talk details about this with... Non-locals. No offense.}
{1902}{}{Livos is inhabited by four families - Schweins, Hortons, Duntons, and us, McKinseys. Who do you want to know about?}
{191}{023}{Tell me about your family.}
{192}{022}{I want to know about Duntons.}
{193}{021}{What do I need to learn about Duntons?}
{194}{028}{Tell me about Hortons.}
{195}{010}{Actually, I'd like to talk about something else.}
{196}{999}{I'm not very interested to hear about it right now. I'll go.}

{2001}{}{I'm not into rumors. If you want to talk about them, you'd better look for my sister Fox. She likes to blab. It pisses everyone around her, even me. Sometimes, she can stick to me and chirp without end. She is able to talk for hours and give zero useful information.}
{201}{010}{Okay, I want to ask something else.}
{202}{999}{I'll go speak to her. Want to learn more about local rumors.}
{2002}{}{I'm not into rumors. If you want to talk about them, you'd better look for my sister Fox. Actually, to be able to do that, you should become the inhabitant of Livos. Edward decides who is worthy to live among us.}
{203}{999}{So, it's all that I need to do then... See you around.}

{210}{}{The Schweins are not doing anything helpful. Ludwig sits in his laboratory, trying to turn his fantasies into the reality of the material world. Christopher is an average and greedy vendor, you could see him by the entrance. I can't stand him. Also, need to mention an old man Edward, who thinks that he is the most important person in the vault. When in fact, he just watches the entrance. Even the child could handle this job. Other ones are not worth mentioning.}
{211}{022}{What can you tell me about Duntons?}
{212}{028}{I want to know about Hortons.}
{213}{023}{Can you tell me about your family?}
{214}{029}{Why you don't like Christopher?}
{215}{010}{Actually, I'd like to talk about something else.}

{220}{}{Of all the Dunton family, only Emily is worth mentioning. Bossy and arrogant bitch. Thinks she is better than everyone when in reality she just has overblown self-esteem. She doesn't even take her husband for a living being, not mentioning the others. Emily gives speeches at the meetings, but for the most time, she is worthless.}
{221}{021}{What can you tell me about Schweins?}
{222}{028}{I want to learn about Hortons.}
{223}{023}{Tell me about your family, McKinseys.}
{224}{010}{I learned what I needed. Let me ask something else.}

{230}{}{[Dallas smiles and proudly continues] It's no secret that our family is the most influential in Livos. We are responsible for the vitally important product - clean water. Nothing compares to this. The head of our family is Boston McKinsey, my father. I'm doing most of the work... Practically everything. Other members of our family you'd better meet personally.}
{231}{024}{What exactly do you do here?}
{232}{028}{Tell me about Hortons.}
{233}{021}{What about the Schweins?}
{234}{022}{I'd like to know about Duntons.}
{235}{010}{Let's change the subject. I want to ask something else.}

{2401}{}{[Dallas gives you a little smile] Why, patron, can't remember who's doing what? I deal in exports of drinkable water into settlements of Radius. I make contracts and manage the deliveries. With all gallantry, I can say that my job is the most important for the survival of Livos. In exchange, we get the canned food and other goods.}
{2402}{}{[Dallas points into his papers] I deal in exports of drinkable water into settlements of Radius. I make contracts and manage the deliveries. With all gallantry, I can say that my job is the most important for the survival of Livos. In exchange, we get the canned food and other goods.}
{241}{025}{I want to talk about water deliveries to the NWO.}
{242}{042}{Can you sell me clean water?}
{243}{010}{One more question.}

{250}{}{[Dallas raises his eyebrow] Yeah? What's wrong with them? }
{251}{026}{Water is not good. I want to find out why.}
{252}{027}{The water tastes a little strange. I was asked to find out what's wrong. People are becoming nervous, if it continues - they won't buy as much as they used to. And that means your profits will drop significantly.}

{260}{}{I won't talk details about water deliveries. If there's taste, then it should be like this. Period.}
{261}{010}{Hm... Alright, I'll ask something else.}

{270}{}{[Dallas scratches his chin] Well... We are definitely not interested in profit drops. Okay, I'll tell you about the taste. Due to the large quantities of exported water, we are concerned with the stability of our water filter. So we resorted to the backup option of water processing. We use carbon canisters, charcoal filters. Still, the filtration quality stays at the highest level. You can tell them that our water is good. Nothing to worry about.}
{271}{999}{Great, I'll tell them everything is alright.}

{280}{}{Ashton Horton, the head of the family, makes repairings in the vault. He can't fix serious ones though, only something little. He and his sister, Claudia, are a little off. You'll see what I mean when you talk to them. [His voice suddenly becomes shaky, eyes looking away] And there's Mignon, daughter of Claudia and deceased Peter... A beautiful flower, blooming in the family of schizophrenic...}
{281}{030}{I see you have a thing about Mignon.}
{282}{021}{Tell me about Schweins.}
{283}{022}{What can you say about Duntons?}
{284}{023}{Can you tell me about your family?}
{285}{010}{I want to ask something else.}

{2901}{}{He was getting in the way of our relationship with Mignon, but now she will be my wife. All of this - thanks to you!}
{2902}{}{[He clenches his fists] Christopher is getting into our relationship with Mignon! Stupid, greedy haggler!}
{2903}{}{This scumbag stole my Mignon! I hate him!}
{291}{030}{You and Mignon - are you in a relationship?}
{292}{010}{I want to ask something else.}

{300}{}{Yes, I'm in love with Mignon, cute little blonde beauty... And I want to marry her. But there's this Christopher Schwein, always getting in our way! He wants to steal her from me! This insolent and rough man doesn't deserve to be a husband of such an extraordinary girl!}
{301}{031}{What does Mignon think? Who she wants to be with?}
{302}{032}{How are you going to get her love?}

{310}{}{She doesn't know yet. She likes the competition we have over her. }
{311}{032}{How exactly are you going to make your move?}

{320}{}{Mignon likes romantic things. We can talk for hours - about feelings, beauty, dreams, love. But she also likes straight-forward and brazen men. Christopher is exactly like this, despite not being able to put two words together. If only I could make a romantic evening for her... She would have definitely picked me over him. Or maybe I need her to start hating Christopher for something. That would work too.}
{321}{033}{Why don't you organize such an evening?}

{330}{}{The thing is, we don't have any music disks left in the vault. If I would have found one CD with romantic songs, her heart would definitely be mine.}
{331}{034}{I could try to look for a CD for you. And what about Christopher?}

{340}{}{Christopher attracts her with his straightforwardness and self-confidence. But in reality, this opportunistic scumbag is willing to sell his own mother for a couple of extra batteries. He tends to have a bit of a temper, so he can be provoked.}
{341}{035}{I'd like to help you with this matter.}
{342}{010}{I don't want to get involved in your love games. Let's change the subject.}

{350}{}{You would? That's great! Convince Mignon that Christopher Schwein is not right for her, that he is an aggressive and stale idiot. Or if you find any CD with romantic music, bring it to me!}
{351}{999}{Okay, I'll remember that. See you around.}

{360}{}{What do you want to talk about?}
{361}{037}{What did you want me to do, so you and Mignon could be together?}
{362}{038}{I've found a music CD for your date.}
{363}{039}{I talked to Mignon, she doesn't want to see Christopher anymore. Now you two can be together.}
{364}{040}{I talked to Christopher about you and Mignon.}
{365}{010}{Nothing for now. I'd like to ask something else.}

{370}{}{Get me some music CDs or talk Mignon into leaving Christopher. Maybe you can even get him into aggression. }
{371}{999}{I'll see what I can do.}

{380}{}{Great! That's just what I need! We are going to have a wonderful evening with my lovely Mignon, it will be unforgettable! Here, take this present from me.}
{381}{999}{Thanks, Dallas. Be happy together.}

{390}{}{Great! That's great news! Now we are going to be a couple, at last, nothing would get in our way! Here, take this present from me.}
{391}{999}{Thanks, Dallas. Be happy together.}

{400}{}{So? What are you trying to say?}
{401}{010}{Nothing. Let me ask something else.}
{402}{041}{I'm telling you this as a friend - Christopher wants to end you. So you wouldn't get in the way of him and Mignon. He would go as far as causing an accident, openly putting your life in danger, if you won't give up on Mignon.}

{410}{}{[His voice trembles] Damn... I can't handle this bastard in a fight... He would easily take me out with brute force... If he plans to threaten my life, I'm going to leave Mignon alone. My life is more valuable to me.}
{411}{999}{I'll tell him this. I'll talk him out of harming you, be sure about that. Bye, friend. }

{420}{}{I sell water in large quantities. You can take any little amount you want for your personal use, free of charge. Also, I could use your help in one matter.}
{421}{043}{What can I help you with?}

{430}{}{I am currently testing some new methods of filtration. [He hands you the bottle filled with cloudy liquid] Here's the sample of processed water. Try it and tell me what you think.}
{431}{044}{Sure, give it to me. I'm already thirsty.}
{432}{010}{No, thanks, it looks very risky. I better ask a question.}

{440}{}{Great! Here.}
{441}{045}{[take a sip]}
{442}{048}{[drink half a bottle]}
{443}{051}{[drink the whole bottle]}
{444}{010}{I changed my mind. I'd better ask something.}

{450}{}{[This water tastes not very good, but except that you feel no other effects. Dallas patiently looks at you.] So? How is it?}
{451}{046}{It's okay. Drinkable.}
{452}{048}{I didn't quite get it, let me try half a bottle.}
{453}{051}{To give you an opinion, I need to drink it whole.}
{454}{047}{No, I think you can't sell this.}

{460}{}{Good! Here are some batteries for your efforts. This water will be delivered to one of the Radius settlements.}
{461}{010}{Thanks. Onto the questions.}

{470}{}{That's a pity. Then we'll cancel the shipment of this water into Radius settlements. Here are some batteries for your efforts.}
{471}{010}{Thanks. Onto the questions.}

{480}{}{[Water has a very unpleasant taste. Just as you finish drinking half of the bottle, you feel sick. Dallas waits for your answer.] So? How is it?}
{481}{051}{I want to drink it to the bottom.}
{482}{049}{The water is okay, you can sell it.}
{483}{050}{This is awful, I feel sick.}

{490}{}{Good! Here are some batteries for your efforts. This water will be delivered to one of the Radius settlements.}
{491}{010}{Thanks. Onto the questions.}

{500}{}{That's a pity. Then we'll cancel the shipment of this water into Radius settlements. Here are some batteries for your efforts.}
{501}{010}{Thanks. Onto the questions.}

{510}{}{[You suddenly feel VERY sick. Just as you finish the bottle, you instantly throw up] Hey, are you alright? This water definitely can't be put on the market. Here, take some batteries for your efforts. And here's the cure for poisoning. I think you need it. }
{511}{010}{Yuck... [spit] Thanks... Now, onto the questions.}

{520}{}{You approved the water of questionable quality. Probably, someone is going to get sick.}
{521}{}{You didn't approve the water of questionable quality. Maybe you've just saved someone from poisoning.}
{522}{}{You approved the water of poor quality. Someone is definitely going to get sick!}
{523}{}{You didn't approve the water of poor quality. You've definitely saved someone from poisoning!}
{524}{}{You prevented the delivery of bad water to the market. It will definitely save someone from poisoning!}