##############################
#Локация: Livos
#Имя: Эмили Дантон 
#Краткое описание: Стерва, пытающаяся управлять Livosом
#Дата создания: 27.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a woman with an ice-cold stare.}
{2}{}{She looks at you arrogantly. More precisely, she looks at everyone arrogantly.}
#
# после знакомства
{3}{}{You see Emily.}
{4}{}{Desite what she was saying, she still looks at you as if you were feces.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a tall, slender woman. Her movements are very slow-paced and she looks at the people around her with a definitive superiority. She doesn't even try to hide it] Who is it that came to us? Another lowlife from Radius? What such useless thing like you would want from such an important person like me?}
{11}{002}{Watch your mouth, lady.}
{12}{003}{And what kind of important person you might be?}
{13}{004}{Sorry to bother you. I would be grateful if you could spare some of your precious time to talk to me.}
{14}{005}{Are you fucking kidding me? Wanna find out which of the two of us is the lowlife?}
{15}{006}{Important person? You are just an arrogant bitch, there are hundreds like you around.}

{20}{}{[The woman contemptuously squints] I have the right to use any words and phrases I please. Note, that you dare to initiate the conversation with me, despite the colossal differences in our social statuses. Know that I am Emily Dunton, the ruler of Livos. Do you understand how great my condescension and kindness is to just talk to you back?}
{21}{008}{I'm new at Livos. And I want to know more about people who run it.}
{22}{007}{As for me, you are just a bitch with an inflated ego.}
{23}{999}{I am sorry, Emily, I won't be bothering you anymore.}


{30}{}{[The woman raises her head even more] My condescension and kindness are so great that I forgive you your ignorance. I am Emily Dunton, the ruler of Livos. Do you realize, what luck it is for you to have a conversation with me?}
{31}{008}{I'm new at Livos. And I want to know more about people who run it.}
{32}{007}{As for me, you are just a bitch with an inflated ego.}
{33}{999}{I am sorry, Emily, I won't be bothering you anymore.}


{40}{}{[The woman slightly nods] Looks like you are not as block-headed as the most of inhabitants here. You've felt the difference in our social statuses right away. I am Emily Dunton, the ruler of Livos. What was the reason that made you distract me from my current occupation?}
{41}{008}{I'm new in Livos. And I want to know more about people who run it.}
{42}{007}{As for me, you are just a bitch with an inflated ego.}
{43}{999}{I am sorry, Emily, I won't be bothering you anymore.}


{50}{}{[The woman doesn't react to your aggression in the slightest. She only raised her eyebrow a little] I'm not surprised at all to see such manners from someone outside. I will never lower myself to your level, using brute violence to solve problems. I am Emily Dunton, the ruler of Livos. Do you realize, what luck it is for you to have a conversation with me?}
{51}{008}{I'm new in Livos. And I want to know more about people who run it.}
{52}{007}{As for me, you are just a bitch with an inflated ego.}
{53}{999}{I am sorry, Emily, I won't be bothering you anymore.}


{60}{}{[The woman contemptuously looks at you] I have no desire to continue the dialogue with some rudderless ruffian like you. Know that I am Emily Dunton, the ruler of Livos. And now get out, you, worm. I am not in the mood to tolerate your presence anymore.}
{61}{999}{Didn't really want to keep it going. Bye.}
{62}{007}{I myself decide, when to go and when to stay. And now I decide to stay.}


{70}{}{[Emily angrily clenches her fists and starts shouting] Get away from here, you miserable nobody!}
{71}{998}{Not a chance, bitch! I'm gonna teach you some manners! }
{72}{999}{Alright, alright, I'm leaving...}


{80}{}{Then you are talking to the right person. It is I who manages the running.}
{81}{010}{I want to ask you a few questions.}
{82}{999}{I'll better come by later. See you.}


{1001}{}{On what questions of yours should I shed the light of my wisdom?}
{1002}{}{What made you ask for my cleverness again?}
{1003}{}{What do you want here? Get out, you mindless worm!}
{101}{012}{Ludwig had lost his book of wave science. Was it you who took it?}
{102}{011}{I wanted to learn of your plans about Seth and Matt from NWO.}
{103}{013}{Emily, our last conversation went not very smoothly. I would like to fix this.}
{104}{017}{What can you tell me about Livos?}
{105}{025}{I have completed the assignment. Monsters aren't threatening the Livos anymore.}
{106}{031}{Emily, I'd like to play cards with you.}
{107}{040}{I want to talk about an accident with Peter. }
{108}{047}{Emily, I have something urgent I want to talk to you about.}
{109}{999}{I think I need to go.}


{110}{}{[Emily looks grossed out] I am indifferent to the desires of animals from such a hole as NWO. I won't put myself to their level to make any kind of plans together, in any field of activity.}
{111}{010}{Okay. I have other questions.}


{120}{}{[Emily arrogantly glances at you] If you had a talk with Ludwig, you have surely noticed the chaos and mess which is his living quarters. I don't visit his laboratories, because otherwise, I would have to clean myself from dirt and dust for several days. That's why I have nothing to do with Ludwig's book.}
{121}{010}{I'd like to ask something else.}
{122}{999}{I'll go look in other places then.}




{130}{}{[Emily calms down a little] Make your assumptions about why our previous communication wasn't constructive.}
{131}{014}{I talked bad things about you and insulted your dignity. For that I am sorry.}
{132}{015}{I talked bad things about you and insulted your dignity. But you must admit that I was somehow right.}
{133}{015}{I called things by their proper names. You are exactly as I said.}
{134}{016}{I was right and you didn't want to admit it. }
{135}{016}{I was right and you didn't want to admit it. And I'm waiting for you to apologize.}




{140}{}{[Emily looks completely calm] Considering the fact that you have spent many days in a destructive environment of an outside world, I accept your apologies. I am counting on the fact that such incidents won't happen in the future.}
{141}{010}{I would hope so. For now, I want to ask something.}
{142}{999}{I'm glad we've sorted out our disagreements. But now I need to go.}




{150}{}{[Emily's face twists with anger] You understood completely nothing. I won't continue the dialogue with ignorance of such kind. Get out.}
{151}{999}{I was going to. Bye.}
{152}{016}{We are not done yet. I will not go anywhere.}




{160}{}{[She is visibly shaking with hatred] Get away from my sight, worm! You don't deserve even to be standing near me!}
{161}{999}{Okay, calm down. I'm leaving.}
{162}{998}{Or what?}




{170}{}{Livos is my domain. I am the one and only leader of this place. My stellar skills in politics are reflected best in the way I run this vault. I effortlessly rule these worthless little people.}
{171}{026}{How exactly do you rule them?}
{172}{018}{Can I help you with ruling the vault?}
{173}{028}{What about others? Do they know that you treat them with such disdain?}
{174}{029}{What is there to do here?}


{1801}{}{[Emily gives you evaluating look] You don't have the proper status for leadership. Do my previous assignment and your status will be changed.}
{1802}{}{[Emily gives you evaluating look] You don't have the proper status for leadership. But you are assigned to the duties of my personal junior assistant. You can be rightfully proud.}
{1803}{}{[Emily gives you evaluating look] You don't have the proper status for leadership. But you do have an opportunity to strengthen your reputation here and increase the influence on the Livos residents. If you are capable of completing the task involving risking your life, I will assign you to the position of my personal junior assistant. Your status and influence would change greatly. I could run the things here more effectively, while you would have additional privileges.}
{181}{017}{I'm not ready to take risks for now. What were you mentioning about Livos?}
{182}{020}{I am ready for a dangerous job. What is needed to do?}
{183}{010}{I want to ask another question.}
{184}{999}{I need to finish some business, I'll be back later.}
{185}{019}{I don't want to help you enforce your power. I hate your dictatorship.}




{190}{}{[Emily gets furious] How dare you to talk to me like that! You belong to the excrements, worm! Get out!}
{191}{999}{I was just going to.}




{200}{}{The task won't be simple. A little while ago, on the floor of the filter room appeared a hole, leading to a cave. That cave is filled with dangerous monstrous creatures, who can crawl out at any time and kill everyone in Livos. Your mission is to ensure the safety of the vault.}
{201}{021}{How would I do that?}




{210}{}{I don't care what way you'll choose for protecting Livos. You can murder all monsters, you can barricade the hole. The option doesn't matter. The result does.}
{211}{999}{Okay. I'll go carry out the task.}
{212}{022}{Okay. I'll go carry out the task.}
{213}{023}{Sure. I'm going to rip them into pieces very fast!}
{214}{024}{Sure. I'm going to rip them into pieces very fast!}

{220}{}{Wait. I'll put some amount of batteries at your disposal for completing the task.}
{221}{999}{Thanks. I'll get back when it's done.}

{230}{}{Wait. I'll put some amount of batteries at your disposal for completing the task. Also, I took notice that you are quite fond of dealing with problems using brute force. Take this instrument. With its help, you'll get the job done in no time.}
{231}{999}{Cool! Little monsters, here I come!}

{240}{}{Wait. I took notice that you are quite fond of dealing with problems using brute force. Take this instrument. With its help, you'll get the job done in no time.}
{241}{999}{Cool! Little monsters, here I come!}


{250}{}{You have completed the task brilliantly. I should admit - I am quite impressed with the quality of the result. Because of that, I am rewarding you with this voice modulator.}
{251}{999}{Whoa, you can use tech to imitate someone's voice? It will surely come in handy.}

{260}{}{[Emily smugly smiles] My subtle leadership is done through manipulations with a consciousness of each of the vault residents. I recall there was an ancient phrase, which I believe belongs to one of my ancestors - "divide and conquer". And that is my exact method of ruling. I made each family believe in their exclusivity and importance for the life and fate of Livos. And now they are more concerned with their own significance, rather than with taking notice of what's happening around them. If one of the families starts to take advantage, I undertake some activities to weaken it. I throw them ideas on the official meetings - and they make it look like they are their own, never realizing the truth. Pathetic bunch of worthless pompous insects!}
{261}{027}{What if I would tell them about it?}

{270}{}{[Emily chuckles] No one would listen to you! They are so accustomed to viewing themselves as the center of the universe that they became unable to see obvious things and listen to constructive criticism! Miserable losers - that's who they are!}
{271}{017}{I see. Tell me more about Livos.}
{272}{010}{I want to ask something on another topic.}
{273}{999}{Damn, I need to get out of this place... Bye.}
{274}{019}{You are a self-righteous dictator! You make me sick!}

{280}{}{I have a right to think as I please. According to paragraph 5 of our Constitution, "Each inhabitant of the New World has the right to think of others, and of the New World itself, anything they see fit". That concludes that I am not worried even a bit with the opinion of others about my persona. In my turn, I don't consider it necessary to hide my arrogance to all these pathetic and petty worms.}
{281}{017}{I want to ask more about Livos.}
{282}{010}{Let's change the subject.}
{283}{019}{I hate such smug and bossy people like you. }
{284}{999}{I'd better go talk with someone else.}
{285}{043}{Do you have this attitude toward your relatives too?}

{290}{}{The most interesting thing to bother yourself with within Livos is obviously a game of cards. I spend a lot of time playing with my friend Abilene McKinsey. She is a worthy opponent, but more importantly, she always pays her debts. For me, gambling debt is a holy thing. To repay it is a matter of honor, even if my life depends on it.}
{291}{030}{Abilene is your friend?}
{292}{036}{Do you mean you could kill yourself if you lose?}

{300}{}{[She makes a short laugh] She means nothing to me. I don't invest my trust in such an unreliable concept as friendship. Abilene is a convenient person. Convenient to play cards with, nothing more. I should point out that her intellectual capabilities are like of a chicken - and this makes her perfect interlocutor, safe to talk with.}
{301}{017}{Tell me more about Livos.}
{302}{010}{I want to ask something else.}
{303}{019}{I knew that you use people for your own benefit. I despise you so much.}

{310}{}{[You see the fire in Emily's eyes] Play a game of cards? A wonderful idea. What are you willing to bet?}
{311}{032}{Let's play all-in! Bet everything we have at the moment!}

{320}{}{[She gives you a cunning smile] I agree with your terms. Shall we begin?}
{321}{033}{Let's do it!}

{330}{}{[For some time, you play cards with Emily. She is so involved in the process, that fails to notice how you hide a couple of cards in your sleeve, taking out some aces instead. In the end, you easily defeat her. Emily smiles] You won. I am ready to pay my debt. We agreed to play on everything we have. The thing is - I have nothing! I am paying you my debt of nothing! }
{331}{999}{Uh... Damn, I didn't see that coming. Okay, we'll play again later.}
{332}{034}{What do you mean? I told you, let's bet everything we have at the moment. Your life is what you have!}

{340}{}{[She becomes pale] What?... How?... I... }
{341}{035}{Yes, Emily, you gambled your life away. Now I can do whatever I want with it.}

{350}{}{What do I do then?..}
{351}{037}{If the word "honor" means anything to you - you'll kill yourself.}
{352}{038}{You will abandon Livos. I give your life to Radius.}
{353}{010}{Okay, I am in a good mood today, so I leave your life to yourself. Let's talk about something else.}

{360}{}{[Emily proudly raises her head] If the bet is my life, then I'll do it if I lose! }
{361}{039}{What about the Livos dwellers? What would they think about you killing yourself?}

{370}{}{[Emily clenches her teeth, squints, and proudly raises her head] I'll do it. Emily Dunton always pays her debts. Goodbye.}
{371}{999}{[observe]}

{380}{}{[Emily clenches her teeth, squints, and proudly raises her head] I'll do it. Emily Dunton always pays her debts. Goodbye.}
{381}{999}{[observe]}

{390}{}{It is my constitutional right. According to paragraph 6 of our Constitution, "Each inhabitant of the New World has the right to take his own life, if it is not harming the other inhabitants of the New World".}
{391}{010}{What a handy paragraph. Let's talk about something else.}

{400}{}{[She gives a subtle smile] If it can be called an accident. Subtle playing with the highly volatile emotions of people makes wonders, without even involving the culprit in the process. Peter presented a danger for me, so the temper of Boston McKinsey was especially appropriate. My role in this incident went totally unnoticed. Why am I saying this to you? The thing is, even if you would tell someone, nobody would take your words for the truth. }
{401}{019}{So this is your doing? You cold-hearted bitch!}
{402}{010}{Oh man, wow. Let's talk about something else...}
{403}{041}{I suggest holding a commemorative evening dedicated to Peter Horton.}

{410}{}{Why would I want to do that? Claudia Horton spends all her energy on Boston McKinsey, who always remains in stress because of that. And none one of them takes interest in matters of leading the vault.}
{411}{010}{[You think for a really long time, but fail to find a good argument] I don't even know... Okay, let's talk about something else.}
{412}{042}{If the situation will keep going like this, it could lead to a point where the Horton family will fall apart. Claudia is very close to crossing the line.}

{420}{}{[Emily hesitates] ...Actually, you might be right, her delusion is going too far. Her actions could lead to a disbalance of social powers in Livos. I will hold the commemorative evening, so Claudia would find some serenity.}
{421}{999}{Great. I'll go tell her the good news.}

{430}{}{They are just worthless worms, just as everybody else. Especially Soup, who is my husband. I married him only because of his social status, and I never let this filth approach me. Even to think about physical intimacy with Soup makes me so sick I have an urge to vomit. }
{431}{010}{Now I see why you have no children. Let's talk about something else.}

{440}{}{What? This worthless worm decided that he could take my position? I thank you for this information. I'll deal with this matter.}
{441}{010}{I see. I want to ask something else.}

{450}{}{I figured that literally not one important event can happen without me here. Lead the way!}
{451}{999}{Yes, come on...}

{460}{}{What was the reason that you brought me here? I see nothing extraordinary around the filter room.}
{461}{998}{I got you here to finally deal with you! Death to a tyrant!}
{462}{999}{I was probably mistaken. Everything is alright here, let's go back.}

{470}{}{I am carefully listening.}
{471}{044}{I had a talk with your husband, Soup. He wants you dead.}
{472}{045}{Emily! We urgently need your presence in the filter room! No one is going to do a thing without you managing!}
{473}{010}{Actually, I wanted to ask a question.}
{474}{999}{Although, not now. I need to go.}