##############################
#Локация: ЛАЙВОС
#Имя: Эштон 'ортон 
#Краткое описание: Главный по ремонту в Лайвос
#Дата создания: 25.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a man with a big moustache. }
{2}{}{As a child, you've seen an old Ninto magazine with an chubby plumber Maro on its cover. This man looks just like that plumber.}
#
# после знакомства
{3}{}{You see Ashton.}
{4}{}{Wrenches and screwdrivers are sticking out of his pockets.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a dissatisfied man with a moustache. Seeing you he starts grumbling] Another someone poking his nose around. Who are you and why did you come here? What do you want? }
{11}{002}{I'm here recently. Looking around the vault.}
{12}{009}{Who are YOU?}
{13}{011}{Hey. I'm new, meeting my neighbours.}

{20}{}{Look around, but carefully. Don't put your fingers into everything, pushing every button you see. I'm Ashton Horton, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
{21}{003}{No.}
{22}{004}{Yes.}
{23}{005}{I have no time to talk about rules right now. I'll go.}

{30}{}{The first rule of Livos is to take good care of the property! Use the local equipment only in case you need to. It's forbidden to turn everything on and off just for fun, or push any buttons when you feel like it! Understood?}
{31}{004}{Yes, understood.}
{32}{007}{No, I still don't get it.}
{33}{005}{I don't care. I'll go.}

{40}{}{Good. Then I need to test your knowledge of the rules. Are you ready?}
{41}{006}{I'm ready!}
{42}{007}{No, I'm not ready yet.}
{43}{003}{Uh, which rules? I forgot.}

{50}{}{[He grabs your hand] Wait! You can't leave until you learn the rules! You should demonstrate your knowledge of them! Are you ready?}
{51}{006}{Yes, I'm ready.}
{52}{003}{Remind me, which rules are there?}
{53}{007}{No, I'm not ready.}

{60}{}{Okay then, first question - How do you treat the property of Livos?}
{61}{012}{With a good care.}
{62}{012}{With care.}
{63}{013}{With a little care.}
{64}{013}{Usually.}
{65}{013}{You can push buttons if you feel like it.}
{66}{014}{You can poke into everything you want and push everything you find.}
{67}{014}{You can do anything, including kicking stuff around and picking into it.}

{70}{}{I won't let you go until you learn the rules! You will definitely go and break something! You should pass the test!}
{71}{003}{Well, okay. Remind me, which rules are there?}
{72}{006}{I'm ready for test.}
{73}{008}{Screw you! I don't care about that tests of yours!}

{80}{}{You are stupid moron! I'm gonna beat some sense into you!}
{81}{998}{Come on then!}

{90}{}{You have a bad temper. Probably, that's because you didn't know that you are talking to Ashton Horton himself, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
{91}{003}{No.}
{92}{004}{Yes.}
{93}{005}{I have no time to talk about rules right now. I'll go.}

{1001}{}{Come in, chief. Did something break again?}
{1002}{}{Yes, I can answer your questions.}
{1003}{}{Oh, you again. You didn't break anything, did you.}
{101}{015}{Ludwig lost his book of wave science. Did you see it?}
{102}{016}{I want to talk about Seth and Matt from NWO. Do you want to make an alliance with them?}
{103}{017}{You said that you are the most important man in Livos. Tell me more about it.}
{104}{019}{What is it that you do here?}
{105}{026}{I want to talk about water filter.}
{106}{999}{I have some things to do. Let's talk later.}

{110}{}{[The man smiles] Well, you've met the right person to talk to. I'm Ashton Horton, the head of Hortons family and the most important man in Livos. Do you know the first rule of Livos?}
{111}{003}{No.}
{112}{004}{Yes.}
{113}{005}{I have no time to talk about rules right now. I'll go.}

{120}{}{[Ashton looks satisfied] Right! You are good! If only everyone else would understand the rules as good as you. I have no more questions, you have passed. Now you can walk freely around the vault.}
{121}{010}{I would like to ask some questions first.}
{122}{999}{Okay, I'm going with a clean conscience.}

{130}{}{[Ashton raises his voice] Not exactly right! You should treat the property of Livos with a GOOD CARE! How am I supposed to make all of you to remember this simple thing... Okay, you can walk around freely, but don't poke your nose where you shouldn't.}
{131}{010}{I would like to ask some questions first.}
{132}{999}{Okay, I'll go walk around.}

{140}{}{[Ashton frantically waves his hands] Wrong! You can't do it, it's forbidden! You should take a GOOD CARE of local property! How am I supposed to make all of you to remember this simple thing... Okay, you can walk around freely, but don't touch any equipment! At least, until you learn the rules.}
{141}{010}{I would like to ask some questions first.}
{142}{999}{Okay, I'll go walk around.}

{150}{}{[Ashton carelessly shrugs] No, I didn't see any book. I have more important things to do than reading about some stupid theories. Ask others.}
{151}{010}{Okay. I have other questions.}
{152}{999}{I'll go ask someone else.}

{160}{}{[Ashton makes displeased face] Who the hell are Seth and Matt? I'm too busy to make some stupid alliances with some tramps wrom NWO! I don't care about their problems in the slightest. No alliances for them. Maybe some other families would talk about it. It's in their habit - to deal in nonsence.}
{161}{010}{Okay. I have other questions.}
{162}{999}{I'll go and do that then.}

{170}{}{[Ashton complacently raises his chin] Yes, I'm the most important person in this place. Firstly, I do the repairs of the vital equipment. No one else does. Without my skills, everything here would have fallen apart already. This lazy amoebas can't do anything, so I forbid them to even touch the mechanisms. They will only make things worse with their crooked hands. }
{171}{018}{And secondly?}

{180}{}{[His smile gets wider] And secondly, I am the one and only legitimate owner of this beautiful hotel. My ancestors, who were the proprietors of a huge hotel network, built it for me and my family. And the rest are only living here because we allow it. If Livos gets crowded, I'll throw someone outside. My word is the law here, everyone knows that I'm the rightful leader. Still, despite my high status, I don't act star-struck. I'm even proud that it doesn't get in my way of doing the hard labor of repairings.}
{181}{020}{You are able of repairing anything in the vault, right?}
{182}{010}{Okay, I want to ask something else.}

{190}{}{I'm doing repair duties. And I don't let anyone else poke into this important business. Only the hands of gold, like mine, would touch this compicated tech.}
{191}{020}{Can you fix anything here?}
{192}{010}{I see. I have other questions.}

{200}{}{[Ashton stumbles] Not exactly... For example, our nutritional mixtures machine is completely out of order. There's something burned in it. Or jammed. Or something else. Despite my highest qualification, I couldn't do anything. It's all becase of carelessness of other dwellers! I keep telling them - take a good care of the property! But they just don't. Of course, they are guests in my hotel, but as an owner, I'm not very glad.}
{201}{021}{Any other problems?}
{202}{010}{I see. I'll ask about something else.}

{2101}{}{[Ashton slowly and reluctantly continues] Uhh... You see... I don't know if I should tell you this, but, er... The thing is, there's something wrong with the water filter. He can't handle big amounts of water anymore. And I'm afraid it'll only get worse - if it breaks down completely, Livos could die out. I tried to repair it, but the situation is pretty complex. You can't just go and fix it.}
{2102}{}{No other problems for now. There was issues with broken water filter, but it forks fine now.}
{2103}{}{The water filter is completely dead. I've read the manual, spent much time, but still fail to fix it. Soon our water supply will become thin. Don't know what to do with it.}
{211}{022}{I've heard that the taste of water became strange. Is it because of a problem with filter?}
{212}{025}{I can look into the filter problem. I have a broad experience of repairing different stuff.}
{213}{023}{You are the best repairman of Livos! How come you still didn't manage?}
{214}{010}{I see. Let's talk about something else.}

{220}{}{[Ashton shakes his head] No, the quality of water is the same. The filter problem only influences the amount of water that can be filtered. Every drop of water in Livos went through this filter, the taste is the same as before. You can see for yourself.}
{221}{025}{I am experienced in repairings. I can see what has happened to filter.}
{222}{023}{How come you still didn't manage it? You are the best repairman of Livos!}
{223}{010}{Really? So it's not about the filter then. I have other questions.}
{224}{999}{I need to find out what's wrong with the water. I'll go talk to someone else. Bye.}

{230}{}{[Ashton hesitates] I don't even know... I've read the manual, but, uh, it's so difficult... I couldn't make heads or tails- I mean, I didn't have time to look into it properly! Yes, because of this other urgent business I have!}
{231}{024}{Ashton, you are the most experienced person in this vault in the matters of repairing things! I'm sure it will be very easy for you to understand this manual, if you try!}
{232}{025}{Let me see into it. I have some skills of fixing things.}
{233}{010}{I'm sure you'll fix it later. I want to ask something else.}

{240}{}{[Ashton shines] Yes! I'm the best in the whole Radius! I could fix the filter, sure, but I still need to deal with, uh, selling a couple of guns. Because, obviously, I need batteries for the parts. You could help me out if you buy one of them for, let's say, 350 batteries. Until I deal with this, I won't get into repairing the filter.}
{241}{010}{I'd better look into fixing filter myself. I have other questions.}
{242}{031}{Here are the batteries. Give me one of that guns. Now you'll have the time you need to do fixings.}
{245}{999}{I have no batteries on me right now. I'll get them to you later.}

{250}{}{[Ashton has visible doubts] I don't know... I don't let anyone to fix things around here. Hm. This is a difficult case, so I could have use a fresh eye. Okay, you can go look at the filter. But be very careful!}
{251}{999}{Okay, I'll go check the filter out.}

{260}{}{The filter is still bad at filtering. And the repair manual is so obscure!}
{261}{024}{Ashton, you are the most experienced person in this vault in the matters of repairing things! I'm sure it will be very easy for you to understand this manual, if you try!}
{262}{010}{I'm still looking into the problem too. I have some questions though.}
{263}{027}{I've repaired the filter. It works even better than before.}
{265}{027}{I'm not quite sure, but it looks like you need a NEW filter...}
{264}{030}{Can I look at the manual?}

{270}{}{That is great! I'll check... [Ashton presses some buttons on a nearby device] The wilter is really working! That is so good you had such a wise me advising you! Still, you've helped a bit too. Here are some batteries for that. And I also have a couple of guns here, so pick one as a present. }
{271}{028}{I want a plasma rifle prototype.}
{272}{029}{I'm more into that laser pistol.}

{273}{}{Wh- WHAT? You broke it completely?! [Ashton presses some buttons on a nearby device]] Damn... No signal at all... Well... All that's left is to hope that the water is not as dirty as we used to think... And I had some reward prepared for you, but now you obviously won't get it!}
{274}{999}{Oh... [shrug and leave]}
{275}{999}{Of course, you'd better hide it somewhere [wink and leave]}

{280}{}{Good choice. Here. Don't forget to take a good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk...}
{281}{999}{Thanks. Bye, Ashton.}

{290}{}{Good choice. Here. Don't forget to take a good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk...}
{291}{999}{Thanks. Bye, Ashton.}

{300}{}{No! I won't let anyone to look into my documents!}
{301}{026}{Okay then. So, what about the filter?}

{310}{}{I have a laser pistol and plasma rifle prototype. Pick something and I'll go handle the filter.}
{311}{032}{I want a plasma rifle prototype.}
{312}{033}{I'm more into that laser pistol.}

{320}{}{Good choice. Here. Don't forget to take a good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk... [Looks at you] I'll go fix the thing! Not a problem at all, especially for the best repairman in Radius!}
{321}{999}{Thanks. Bye, Ashton.}

{330}{}{Good choice. Here. Don't forget to take a good care of it! [he smiles and mumbles] Unbelievable, I finally got rid of this useless junk... [Looks at you] I'll go fix the thing! Not a problem at all, especially for the best repairman in Radius!}
{331}{999}{Thanks. Bye, Ashton.}