##############################
#Локация: Livos
#Имя: Фокс McKinsey 
#Краткое описание: Доставшая всех болтушка
#Дата создания: 18.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a young pretty girl.}
{2}{}{She whistles a simple melody.}
#
# после знакомства
{3}{}{You see Fox.}
{4}{}{She assesses you with her look.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a young cute girl with big eyes and beautiful smile] Oh, you scared me! I heard that there's someone new in the vault and I'm so glad to meet you, I'm so interested in what's happening in Radius, I couldn't wait to meet you, now I can talk to you about everything that happens outside, how are the people and what's going on there, because here is quite boring actually, no one wants to chat with me, except my friend Mignon and my brother Dallas, but he is mostly silent and sometimes asks not to distract him from his business, and he is so cute whe speaks seriously, just a tresure of a man, I'm so glad I have a brother like him, he cares about me, sometimes calls me Foxie and it's so cute, because parents always call me Fox, and sometimes more serious, Fox McKinsey...}
{11}{010}{Wait! Stop it! I just want to ask a few questions.}
{12}{002}{[Keep listening]}
{13}{999}{My brain is exploding! I need to be alone for a minute. }

{20}{}{...Just like the name of a girl from a bedtime story mom used to tell me, together with other stories about some animals, which I've never seen, and mom has also never seen, and there's not even pictures of them left, and we were imagining what would they be like, what they eat, how talk to each other, and that was so interesting, but then I grew up and it stopped being interesting, I'm now busy with choosing someone to marry, so many options here that I don't know who to pick, and I don't really want to pick, because I'm in love with someone else, who I can't marry, because mom and dad forbade me to marry my brother Dallas, but they are brother and sister too, and they are together, like, forever, but they are still against me being with Dallas, but he is so cool, no one in Livos compares to him...}
{21}{010}{Okay, stop! Answer my questions please!}
{22}{003}{[Keep listening. You have a slight feeling of pressure in your head]}
{23}{999}{I can't take it anymore. I need to take a walk.}

{30}{}{...Because he is the most smart and handsome, and he is doing water tradings, which means he is the most important person in Livos, and even dad doesn't make as much for the vault as my lovely brother, that's why our family is the most important here and that's why we are leaders of this place, although other families disagree with it, but we know how it really is - they do not affect prosperity of Livos at all, and soon Dallas will become the leader here and will be able to marry me, despite my parents barring it, but he may not want to, because he likes my friend Mignon, who also dates Christopher Schwein, so if she chooses Christopher, then Dallas would fall into me, and we will marry and I won't have to choose someone else... }
{31}{010}{Stop it! I want to ask a question!}
{32}{004}{[Keep listening. You head is buzzing loudly]}
{33}{999}{Okay, I need a break. I'll go get some rest.}

{40}{}{... And we will rule the vault, just like our parents do, just as their parents did, just as everybody before us did, starting with our ancestors who built this place, who knew that we will survive the war and start repopulating the planet and become the center of the whole world, which we already are...}
{41}{999}{[The feeling of pressure in your head becomes so painful and strong you can't take it anymore]}
{42}{005}{[With great effort you try to listen to the rest of this flood of words]}

{50}{}{...And I'm so glad you're here with us, it's so good to talk to you, because you are such a good listener, I'll tell everyone what a great person you are!}
{51}{010}{And now let me ask a question.}
{52}{999}{That's it. I'm done.}

{1001}{}{Hey, I'm flattered that our commander came by to talk to me again, I can tell you so many interesting and useful things!}
{1002}{}{Of course, go ahead and ask, I'll gladly tell you everything I know and everything I heard and everything other people tell me on the topics you need.}
{1003}{}{Hello, I'm so glad you came by to talk to me again, I can tell you so many interesting and useful things!}
{101}{011}{I'm looking for the lost book, it belongs to Ludwig. Do you know anything about it?}
{102}{012}{What do you do here?}
{103}{018}{Is there any work to do around here?}
{104}{019}{Tell me about your family.}
{105}{020}{[ask about the rumors in Livos]}
{106}{999}{I have some things to do, let's talk later.}

{110}{}{I don't like reading books, they are boring, I like magazines more, I can show you, if you want, they are so interesting and have so many colourful pictures, but I didn't hear anything about anyone stumbling upon the lost Ludwig's book, except my friend Mignon once mentioned that she have seen some book at her mom's, Claudia Horton, but Claudia hid it very fast, so Mignon didn't exactly see what kind of book it was, so it can be the book you need, and you'd better ask Mignon about it, or you even can talk straight to her mom about that book she hides.}
{111}{010}{I want to ask something else.}
{112}{999}{I'll go have a talk with Mignon.}

{120}{}{I'm so into talking with people, so I'm always looking for someone to talk to, and when I get older, I'm going to give speeches on a meetings and going to talk, talk, talk, and everyone will be listening, because according to paragraph 11 of our Constitution of 15 rights, "Every inhabitant of the New World has the right to loudly express his thoughts if he is at the official meeting of inhabitants of the New World", and I will deal with a lot of issues on this meetings and will make a lots of useful suggestions, one of which will be to add drawings into the Constitution of 15 rights, because I love them, I love to draw, I love drawings, so if you have some drawings, I will gladly look at them.}
{121}{013}{I have some drawings I painted when I was a kid.}
{122}{016}{Tell me about the Constitution.}
{123}{010}{I don't have any drawings, I want to ask something else.}

{130}{}{[With burning eyes, Fox examines your drawings] Wow, look at this, these are wonderful drawings, I got so bored by my old magazines, there's no one who would draw something new around here, but yours look so different from others I've seen, and I can look at them for a really long time and imagine what is it you drew, and if you give the to me as a present, I would be so grateful!}
{131}{014}{Sure, take it.}
{132}{015}{No, I need them for myself.}

{140}{}{Thanks! You are so cool, no one's given me a gift like this, I'm so happy, thank you, thank you, thank you! [Fox gives you a smooch in the cheek]}
{141}{010}{You're welcome, enjoy. I wanted to ask something else.}
{142}{999}{I'm glad that you are happy. I need to go, see you.}

{150}{}{[Fox immediately gets upset] Uhh... In the end, you are not so cool as I thought you are, looks like you are just as mean as everybody else, I would keep your drawings, taking care of them, one day I could show them to my children, but you don't want to give them to me, so I won' tell you anything more, because I'm angry at you, so there, go away! [She turns around, trying to make it look serious, but somehow you know that her grudge won't last even for a minute]}
{151}{999}{Okay then, I'll go.}

{160}{}{The Constitution of 15 rights is our greatest document, according to the paragraphs 13, 14 and 15 on Constitution, we have the right to have rights, the right to not have rights, and even the right not to know rights described in the Constitution, but in this case the inhabitant is deprived of any rights, including this right! }
{161}{017}{Where I can find the Constitution?}

{170}{}{Oh, I haven't seen it in a while, it always changes hands, so I don't know where is it now, it could even be accidentally left by someone somewhere, or even lost, because recently I was asking around and no one knows where is it, maybe someone hid it, so I couldn't suggest to make changes into it, so now it's hidden from me, it's so bad!}
{171}{010}{Okay, I want to ask something else.}
{172}{999}{I need to go, urgent business. Bye.}

{180}{}{[Fox hesitates for a second] Maybe Ashton Horton has some work for you, he does repairings in the vault, but he is not always able to fix everything that's broken, just like he wasn't able to repair the nutritional mixtures machine, without which we felt very bad, until we started selling water in exchange for buying canned food and other food, which everyone likes, because the machine never made such tasty things, and now it's completely broken, no one knows how to fix it, and also, my friend Mignon once overheard that her dad Ashton was telling to someone it can't be fixed at all, so we need to continue trading water to the settlements, and that means there will always be new people around here and I will always have someone to talk with!}
{181}{010}{I see. I wont to ask something else.}
{182}{999}{I'll go ask Ashton about work.}

{190}{}{Oh, I can talk about my family for hours, because we are the most important in Livos and other families couldn't live without us, and also, other settlements in Radius couldn't either, because my brother Dallas sells water to them, and without water, obviously, no one lives for long, so it turns out that McKinsey family is vital for the Radius, and the most important, so everybody respects us, and that makes me so proud of my name and my relatives, we are great family, great people doing great things, like my dad Boston, who gives speeches on a meetings, although one time he pushed Peter Horton and he badly fell and died, although my dad didn't mean to kill him, it was an accident, but Peter's wife Claudia now blames our family anyway, she is stalking us all the time, harassing dad, and it makes him really nervous!}
{191}{010}{I want to know about other things.}
{192}{999}{That's everything I wanted to ask. Bye, Fox.}

{200}{}{[As thought of asking Fox about rumors in Livos crosses your mind, you immediately try to forget it. It could be hazardous for your mental health.]}
{201}{010}{[Think about other questions]}
{202}{999}{[Leave]}

{300}{}{[You are sure that something just rolled over your head. Something huge and very heavy. You need to rest and recover.]}
{301}{}{AAAAHHHH!!! I CAN'T TAKE IT ANYMORE!!!}