##############################
#Локация: Livos
#Имя: Людвиг Швайн 
#Краткое описание: Изобретатель и техник Швайнов
#Дата создания: 23.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a tidy-looking man.}
{2}{}{He periodically takes out a pair of old glasses from his pocket and looks through them at the blueprints.}
#
# после знакомства
{3}{}{You see Ludwig Schwein.}
{4}{}{His face clearly says "do not disturb".}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see an elderly man. He is busy with his business and doesn't pay you any attention.] }
{11}{002}{Hello. I'm new here, I'm just looking around Livos.}
{12}{002}{Hello. Do you hear me?}
{13}{002}{Hello. Hey! I'm talking to you!}


{20}{}{[He doesn't react at all.]}
{21}{003}{Hello, I say! I'm new around here! I want to talk.}
{22}{004}{Heeey! Hello! Do you hear me!?}
{23}{005}{Heeey! Are you deaf or something? [give him a little push]}
{24}{006}{Heeey! MAN! ARE YOU DEAF? [kick him]}


{30}{}{[Still no answer.]}
{31}{004}{HELLO! I WANT TO TALK!}
{32}{005}{Hello! [pat his shoulder]}
{33}{006}{Hey! Look at me when I'm talking to you! [give him a hard push]}


{40}{}{[He doesn't even turn his head to you] Get out, I'm busy.}
{41}{005}{I need to talk! Spare me a minute.}
{42}{006}{I won't go anywhere until we talk! Hear me?}
{43}{007}{Are you out of your mind? Turn around, I'm talking to you!}


{50}{}{[He angrily turns to you] I am so sick of the morons who interrupt my work! What do you want?}
{51}{009}{I'm new in Livos. I want to talk.}
{52}{007}{I want to take a look at your face before punching it.}
{53}{008}{Watch your mouth, old man. Or it could be your last words.}

{60}{}{[He angrily turns to you and starts shouting] Who the hell do you think you are?! What are you doing here?!}
{61}{009}{I want to talk!}
{62}{007}{I'm teaching the local idiots to be polite! With my fists!}
{63}{008}{I came to beat the shit out of you!}


{70}{}{The hell do you want from me? Here, take this and let me work! [he gives you a bottle with something]}
{71}{009}{That's better. And now I want to talk.}
{72}{008}{What? I am going to stick this up your ass!}


{80}{}{[He makes a move towards you] That's it, I'm going to tear your tongue out, asshole!}
{81}{998}{Come on, try!}


{90}{}{I don't do conversations with just anybody! Name yourself, for a start!}
{91}{011}{I'm }
{92}{011}{.}
{93}{013}{Alzheimer Parkinson.}
{94}{014}{Little green man.}
{95}{015}{My name is not important. Call me as you like.}
{96}{016}{You first.}



{1001}{}{Tell me what's your business to me, commander. I have no time to chat with you.}
{1002}{}{Tell me what do you want! I can't spend my time chatting with you all day! }
{1003}{}{[Ludwig reluctantly stops what he was doing] What?!}
{101}{017}{Tell me about the Livos vault.}
{102}{018}{I want to know about the Livos inhabitants.}
{103}{022}{What do you do here?}
{104}{028}{About your book on wave science...}
{105}{Barter}{Show me what guns do you have.}
{106}{036}{I have some news from the Olympus...}
{107}{999}{0}
{108}{999}{0}
{109}{999}{No, nothing. I have to go.}


{110}{}{I know. I've heard that there's a newcomer. I'm Ludwig Schwein. What do you want?}
{111}{010}{Answers to a few questions.}
{112}{012}{You knew? Why did you ask then?}
{113}{999}{For some reason, I don't want to continue talking to you. I'll go.}


{120}{}{Because I felt like it! If you don't like something - get the hell out and don't talk to me!}
{121}{010}{Wait, I just wanted to ask something.}
{122}{999}{Yeah, I'll better go.}


{130}{}{Do you take me for a fool? I am old, sure, but I have neither Alzheimer's nor Parkinson's! I know who you are, I was told. I'm Ludwig Schwein. What do you want?}
{131}{010}{To ask a few questions.}
{132}{999}{For some reason, I don't want to continue talking to you. I'll go.}


{140}{}{Each of you, who come outside, always tries to come up with some loud pseudonym. I know who you are, I was told. I'm Ludwig Schwein. What do you want?}
{141}{010}{To ask a few questions.}
{142}{999}{For some reason, I don't want to continue talking to you. I'll go.}

{150}{}{I'm going to call you an idiot! Do you really think you could come in here if I didn't know who you are? I was told already! I'm Ludwig Schwein. What do you want?}
{151}{010}{To ask a few questions.}
{152}{999}{For some reason, I don't want to continue talking to you. I'll go.}

{160}{}{[He stares at you] Good. I'm Ludwig Schwein. And I know who you are, I was told. What do you want?}
{161}{010}{To ask a few questions.}
{162}{999}{For some reason, I don't want to continue talking to you. I'll go.}


{170}{}{Why don't you try to find out yourself? Go and do that! I'm not a local guide, I have things to do!}
{171}{018}{At least tell me about the inhabitants of this place.}
{172}{022}{What are you so busy with?}
{173}{999}{Okay, I'll go.}




{180}{}{I don't care about any of them! They are only good while they don't distract me from doing my work. I'm not interested in interacting with them, running around, being loud and useless... Christopher buys the parts and materials I need, the rest is none of my concern. }
{181}{019}{You don't talk to anyone?}
{182}{021}{What can you tell me about your family?}


{190}{}{[Ludwig makes a contemptuous face] Who to talk here to? Look around - they are all complete idiots! Only Ashton Horton has some resemblance of minimal technical skills, but even he is sick in the head! He thinks he lives in a Horton's hotel! A hotel! And he probably thinks that he is in charge of the whole vault.}
{191}{020}{And who is actually in charge?}
{192}{032}{Did you try talking to someone who is not from Livos? Maybe a random stranger will turn out to be an expert.}


{200}{}{All of us here are in charge. But the most of others only waste resources. Only we, Schweins, are truly beneficial to the place.}
{201}{022}{And what exactly you do here?}
{202}{021}{What can you tell about other Schweins?}
{203}{010}{Okay, I want to ask about something else.}


{210}{}{Our family is the most important. I'm busy with inventing new weapons, my son Christopher is doing external trades, and my brother Edward provides security of the entrance. We could easily do without other families. And my wife, Veronica, would handle all other matters.}
{211}{022}{What weapons are you inventing?}
{212}{010}{I want to ask about something else.}


{220}{}{[Ludwig points to a table, littered with spare parts and schematics] I specialize in laser and plasma weaponry. Currently, I'm studying plasma energy, more exactly - principles of wave science.}
{221}{024}{And? How is the study going?}
{222}{035}{Emily Dunton gave me the task of cleaning the cave from monsters. Could you arm me with a laser rifle for this mission?}
{223}{033}{I'm actually very good with tech, so I could help you with the optimization process of plasma weaponry.}


{230}{}{[Ludwig thinks] Hm... That's actually a good idea. I'd like to obtain the results of some field testings of this weapon, so I could upgrade the model. Here, return to me with the report when you finish. }
{231}{010}{Great. I'll gather the data and get back. The most difficult part of the report would be "problems and nuances after ten years of usage". Let's talk about something else.}


{2401}{}{[Ludwig furiously slams his fist into the table] That's the thing! No good! Someone of these morons stole my book on wave science! They won't even understand a thing from it! Idiots! How do I continue my work?!}
{2402}{}{With the book on wave science, my study of plasma energy processes is going quite well! Thanks for bringing it back.}
{241}{026}{I could look for the book. I'll ask around and find out who could do it.}
{242}{025}{Who could do such a thing?}
{243}{010}{Let's talk about something else.}


{250}{}{I don't know, anyone! I know for sure that it's not one of our family. We don't get in the way of each other. }
{251}{026}{I could help with searching. I'll talk with others and find out who could have it.}
{252}{010}{Let's change the subject.}


{260}{}{[His eyes glimmer with hope] You want to help me? Good, very good. I don't care how you do it, but if you will actually find it, I'll allow you to buy some of my weaponry. The best ones. And you'll have a special gift.}
{261}{027}{I'll look for it. What's that gift?}


{270}{}{[He slightly smiles] I put a lot of batteries into this thing when I was young. But now it's not very likely I'll ever use it. Find the book, you'll see what it is.}
{271}{010}{Okay. But I have some other questions.}
{272}{999}{I'll go do that right now. Bye.}


{280}{}{[Ludwig grabs your hand] Did you find it?! Give it to me!!}
{281}{029}{No, not yet. Remind me, where could I look?}
{282}{030}{Yes, I have it. Here.}


{290}{}{Why the hell are you interrupting me then!! Some idiot from Livos stole it! Talk them into returning, find it in some drawer, you can even shoot someone if that helps. But find me the book!!}
{291}{999}{Okay, I'll go looking.}


{300}{}{[Ludwig practically rips the book from your hands] Yes! Yes!! Here it is!! Now I can continue my research! Take this, just as I promised [Ludwig gives you a piece of map]. And you can now have access to my best stock.}
{301}{031}{What is it? A map?}


{310}{}{Edward bought it. He thought it was some schematics, so he sold it to me eventually. Probably it's a piece of a map, showing how to get to the Renaissance, a city of wonders. I've heard that it has clean water, fresh air. A whole city untouched by the war! I wanted to find it myself when I was younger, but now I never will. If you do, remember your old friend, who gave this to you.}
{311}{Barter}{Of course. And now show me what you have in stock.}
{312}{999}{Thanks for the map. I'll come by later.}

{320}{}{I don't have time to leave Livos and chat with some vagabonds. I got out only once, to the Chamber of Commerce by the entrance. That was the time when I chose someone to marry. Edward gathered some girls for me and I picked the best one. Veronica, my current spouse.}
{321}{010}{I see. Another question then.}


{330}{}{[Ludwig starts to dig through his drawings and documents] I do have one schematics here, which is missing a vital fragment. Take a look. Could you advise something?...}
{331}{034}{[you discuss the weapon scheme for some time, exchanging ideas and making calculations]}


{340}{}{[In the end you gave Ludwig some pointers to solving his problems. After that Ludwig completely threw himself into work.]}
{341}{999}{[Leave him alone]}

{350}{}{[Ludwig starts to wave hands] No, no-no-no! I need my weapons for research and development!}
{351}{023}{Maybe I could help with it then. I am ready to do a field testing of the weapon prototype and return with a full report about its characteristics.}

{360}{}{News? From Olympus? [he looks fascinated] What are you saying?}
{361}{037}{I have a proposition for you... Uh, to go there and, erm... Do a little science work. Let's go?}
{362}{038}{The main researcher of the Olympus wants to consult with you on the matter of some new weapon.}
{363}{999}{Nothing, only that it's calm and peaceful in there. We'll talk later.}


{370}{}{So what you really proposing is that I leave this secure and protected vault for some shady job? No way, thank you!}
{371}{010}{No means no. I'd like to ask something else.}
{372}{999}{Okay, as you wish.}


{380}{}{Sounds very tempting! It is quite risky, of course, but... I am a scientist, damn it! I should take risks! Lead the way!}
{381}{999}{Good, we are leaving immediately. Follow me.}
{382}{}{You conveniently stick the syringe into Ludwig's hip. Frowning from pain for a couple of seconds, he suddenly looks at you with eyes full of loyalty.}

{383}{}{::murmuring::}
{384}{}{...What? ...Where? ...N-no...}
{385}{}{I... I'm here... And now I'm...}
{386}{}{Who's there? Oh, yes, of course... Yeah...}
{387}{}{Nowhere... Always here...}
{388}{}{[gives a faithful look]}

{389}{}{Come on, let's go! Hurry!}
{390}{}{For how much longer? When!?}
{391}{}{Do you remember that you promised to introduce me to the scientist?}