##############################
#Локация: Livos
#Имя: Миньон Horton 
#Краткое описание: Бестолковая блондинка-болтушка
#Дата создания: 21.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a sexy young woman.}
{2}{}{She licked her lips. You mouth feels dry. Maybe you should close it?}
#
# после знакомства
{3}{}{You see Mignon.}
{4}{}{She is beautiful, as always.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a very cute blondie] Hey, stranger. I've seen you walking around, studying everything here. My name is Mignon Horton. Want to chat a little?}
{11}{002}{Yes, I was getting acquantained with my neighbours.}
{12}{999}{Not this time. I'm in a hurry.}

{20}{}{That's very nice! I'm getting tired of just loitering. I could use a good chat with someone.}
{21}{010}{I have some questions for you.}
{22}{999}{You know, I don't have time right now. Talk later.}

{1001}{}{Hey boss! Came to have a chat again?}
{1002}{}{Hey! Did you come to chat again?}
{1003}{}{Sure, I'll try to answer.}
{101}{011}{I'm looking for the Ludwig's book of wave science. Do you know where it might be?}
{102}{013}{Is there anything to do here?}
{103}{014}{Can you tell me about this place and its inhabitants?}
{104}{023}{What do you do here?}
{105}{024}{I'd like to talk about your boyfriend.}
{106}{999}{I have something to take care of. Let's talk later.}

{110}{}{[Mignon thinks] Er... I, for sure, didn't take it, this book-of-wave-something. I don't read boring books, my head always starts to ache from all this smart words and difficult drawings.}
{111}{012}{Have you seen the book at all?}

{120}{}{I've seen *some* book. At Mom's. She hid it very quickly, so I don't know is it the right one. But she doesn't like to read either, so it can be the one you looking for. My mom's name is Claudia, try asking her.}
{121}{010}{Okay, I'll go talk to her later. Another question.}
{122}{999}{I'll go do that. See you.}

{130}{}{[She look surprised, frequently blinking] You mean, like, a job? I don't know... I definitely don't have anything for you. Maybe uncle Ashton has. But why would you want a job? We have everything we need here. I don't understand why would someone look for work, it seems pretty stupid. You could better spend the time over a bottle of wine or playing cards.}
{131}{010}{I'll talk to Ashton about the job later. Another question.}
{132}{999}{I really need it. I'll go talk to Ashton.}

{140}{}{Oh, I know so many things! Me and my best friend Fox know everything about everyone! Oh, I think I've spilled it... But you can keep a secret, can't you? So! Recently, Christopher Schwein had a quarrel with Dallas McKinsey because of me. They almost started beating each other, but Dallas left just in time. They both give me the signs of affection, and it is so nice! Christopher is so strong and confident and Dallas is so calm and romantic. They make me feel very good! And...}
{141}{015}{[continue to listen]}
{142}{010}{I wanted to ask something else.}

{150}{}{...Old man Ludwig is always looking for something recently, growling at everyone, as usual. He probably lost something valuable, maybe some schematics or document. He is very absent-minded. He can forget to have lunch or to go to sleep. And then he sits all night in his lab, until his wife Veronica doesn't remind him to go to bed! He's completely obsessed with his scrap. Doesn't talk to anyone except his wife and son. By the way...}
{151}{016}{[continue to listen]}
{152}{010}{That's all I wanted to know. I'd like to ask about other things.}

{160}{}{...There's a rumor that Christopher is not Ludwig's son at all, but Boston McKinsey's. Ludwig probably never even touched his wife. At least they were never noticed. But Boston is flirting with everyone, damn womanizer. He is kinda crazy too. He jumps at people, he even pushed my father Peter Horton once, on a meeting. After that my father died. Boston is scary, because of his short temper, but no one actually takes him seriously. He's just a clown. And also...}
{161}{017}{[continue to listen]}
{162}{010}{Enough news for now. I'd like to ask about other things.}

{170}{}{...My mother, Claudia, completely lost it. She thinks that Boston McKinsey wants to murder everyone from our family. But I don't believe that, because Boston is not very smart. My best friend Fox is Boston's daughter. So, she is sure, that her father didn't want to harm Peter. And I believe her. That's why mom forbids me to talk to her. So we are hiding. And when we hide, we hear about many interesting things. For example... }
{171}{018}{[continue to listen]}
{172}{010}{Let's talk about something else.}

{180}{}{..We've heard that they want to change paragraph 9 of Constitution, which says "Every inhabitant of the New World has the right not to fornicate with any other inhabitant of the New World, even if the latter strongly insists". And they want to make it necessary to fornicate, by a special resolution. But I still think they will pass on this change. I'll ask my dad and he will definitely stand up for me on this meetings. They don't want to listen to me yet and won't let me participate in meetings. Otherwise, me and Fox would defended our rights ourselves! She also wants to participate. But...}
{181}{019}{[continue to listen]}
{182}{010}{No need for other news. I want to ask something else.}

{190}{}{...Emily Dunton doesn't allow children to participate in meetings. We can only listen and look. According to paragraph 7 of Constitution, "Every inhabitant of the New World has the right to look at any other inhabitant of the New World". So it's our defined right, to look at anyone we want, at any time we want! No matter how much they bully us, they can't take this right away! Although...}
{191}{020}{[continue to listen]}
{192}{010}{I got it. Let's talk about other things.}

{200}{}{...Many of them break this customs themselves. For example, Edward Schwein is taking advantage of being alone in his surveillance room, so he secretly sells alcohol! This worthless old man takes himself for the ruler of this vault. But everyone knows that he is tasked with the most simple job of all - he just sits in that room and doesn't let others to enter. Any idiot could handle it! The only one who does real job around here is my dad. He is busy with repairing the equipment. And he doesn't allow anyone to touch the complex mechanisms, because they would break everything with their crooked hands. Frankly speaking...}
{201}{021}{[continue to listen]}
{202}{010}{That's very interesting, but I want to talk about something else.}

{210}{}{...My uncle Ashton is the one who owns the whole vault. Our ancestors used to maintain big hotel network before the war. And that's them who created Livos as it is. I mean, this is a real paradise! Look around - everything here is just like it was in the best hotels! At least, I think it was like this in the best hotels. Floors under the ground, convenient beds, machines, producing everything you need for comfort living. Anyone would want to live in such hotel! And, by the right of succession, we are proprietary owners of this heavenly place. Except...}
{211}{022}{[continue to listen]}
{212}{010}{Enough information for me. I want to ask something else.}

{220}{}{...This arrogant bitch Emily Dunton is brazenly using every convenience of our vault, despite her thinking that other people are inferior creatures, and she is the one in charge. She rarely even talks to anyone about anything, apart from ordering everyone around. Did you hear her talking? She uses such difficult words! I don't even understand her at all sometimes. But she also has weakness. She is a gambling addict. She and Abilyn McKinsey are often playing together. I think Abilyn is the only friend Emily has. And the reason for this, I suppose, is that Abilyn is a really simple-minded chick, who understands nothing and doesn't participate in anything. In short, you should see by now, what kind of place is this. Maybe you have other questions?}
{221}{010}{Yes. I wanted to ask...}
{222}{999}{No, I learned enough. I'll go think about it.}

{230}{}{[She seems visibly stuck] Uhhh... I mean, what do you mean?... I'm just living by, as everyone else. Walking around, talking to people. Flirting with guys. Like to drink some wine with mom. In other words, I live full and bright life.}
{231}{010}{I see. Another question then.}

{2401}{}{I'm dating Christopher. He is the best in the whole Radius! I'm so happy!}
{2402}{}{I'm dating Dallas. He is the best in the whole Radius! I'm so happy!}
{2403}{}{I'm dating Dallas and Christopher. Who do you want to talk about?}
{241}{025}{Which one do you like more?}
{242}{026}{I think that Christopher Schwein suits you better.}
{243}{030}{I think you'd be better with Dallas McKinsey.}
{244}{010}{I actually wanted to ask something else.}

{250}{}{I don't know. I feel so good with any of them. Christopher is so strong and confident. Although, a little short-tempered. And Dallas is so calm and sensible. We are having such good talks! I didn't figured out myself which one I like better. And I don't want to. I'd leave it as it is.}
{251}{024}{I want to talk more about them.}
{252}{010}{I actually wanted to ask something else.}

{260}{}{Yeah? Why do you think that?}
{261}{027}{I think you'll make a great couple.}
{262}{028}{Christopher Schwein is the best, and you know it. He can achieve anything he wants. Unlike Dallas. Dallas is always going to stay in the shadow of a strong and confident Christopher.}

{270}{}{I-I don't know... I still doubt it.}
{271}{010}{Okay, let's change the subject.}
{272}{024}{I'd like to ask more about your boyfriend.}

{280}{}{I mean, yeah, Christopher can achieve so much... But I like having talks with Dallas...}
{281}{029}{You will keep your talks with Dallas even after marrying Christopher! Dallas won't say no to you. He will be glad just to talk to you anyway.}

{290}{}{You know, you are right! I definitely should be with Christopher! Dallas, probably, would do nothing to stop it.}
{291}{010}{Yes, you are going to be a great couple. Let's talk other things.}

{300}{}{Yeah? Why do you think that?}
{301}{027}{I think you'll make a great couple.}
{302}{031}{Christopher is nuts! He throws himself at people for no reason. I had a talk with him in the trade quarters - and he shouted at me, telling that he will threaten you! I came to check if you are alright.}

{310}{}{[Mignon starts whining] He came by recently... He was so angry! He was screaming, blaming me for misbehaving... I told him it wasn't true, but he didn't believe me! He even hit me... [she burst with tears] He is so bad! I hate him! I don't know if I would forgive him... Maybe in a few days...}
{311}{032}{He will always be like this. He will beat you all the time. So you'd better marry Dallas, and Christopher will leave you alone.}

{320}{}{You know, you are right... I feel so good and safe with Dallas, unlike this lunatic Christopher... I'd better choose Dallas.}
{321}{010}{I think you'll make a great couple. Let's change the subject.}