##############################
#Локация: Livos
#Имя: Соуп Дантон 
#Краткое описание: Задерганый муж-подкаблучник Эмили
#Дата создания: 30.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a thin man, definitely in his late years.}
{2}{}{He looks tired and his left eye blinks three times more often than the other one.}
#
# после знакомства
{3}{}{You see Soup.}
{4}{}{Looks like he's having a twitch.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a hunched man with lowered shoulders. He walks around very slowly, barely moving his feet. His face is a mask of doomed fate and hopelessness] Yes?.. What?... Uh, what is it? }
{11}{002}{Hello. We haven't met before. I'm new around here.}
{12}{003}{Hey, man, brighten up! You look like your face melted off!}
{13}{004}{Oh, you definitely don't look good. Is there something wrong?}


{20}{}{No, we haven't... I don't know if I'm allowed to talk to you... I think... I guess... I am, uh, Soup. Soup Dunton. Oh, I forgot - hello to you...}
{21}{010}{Do you have time for a few questions?}
{22}{999}{You are not very talkative. I'd better go.}


{30}{}{[The man nearly jumps up surprised. Now he is staring at you] W-w-w-what?.. Uhh... What's going on? Please, don't shout... I don't recall we've met before. I am, uh, Soup. Soup Dunton. Oh, I forgot - hello to you...}
{31}{010}{Do you have time for a few questions?}
{32}{999}{You are not very talkative. I'd better go.}




{40}{}{[The man shrinks even more] Nothing... Nothing's wrong... Everything is alright... I don't recall we've met before. I am, uh, Soup. Soup Dunton. Oh, I forgot - hello to you...}
{41}{010}{Do you have time for a few questions?}
{42}{999}{You are not very talkative. I'd better go.}





{1001}{}{Hello, leader. Do you want to talk again? }
{1002}{}{Yeah, of course, I'll try to answer your questions...}
{1003}{}{Yes? Oh, hello. You are, probably, have some questions again. And I, maybe, can, uh, answer them.}
{101}{011}{Ludwig Schwein had lost his book on wave science. Did you take it?}
{102}{012}{What do you do in Livos?}
{103}{019}{Tell me about your family.}
{104}{020}{I want to talk about your wife, Emily.}
{105}{028}{I want to learn of your plans about Seth and Matt from NWO.}
{106}{029}{Do you have something I could do around here?}
{107}{034}{I have dealt with the monsters. The Livos is safe again.}
{108}{999}{No, nothing. I'll come by later.}
{109}{012a}{How are you doing? After, you know, "dealing" with your wife?}


{110}{}{[Soup shakes his head] No, no-no-no, I didn't take anything... It was, probably, someone else... I don't know anything about it.}
{111}{010}{Okay, another question then.}
{112}{999}{Then I'll go ask somewhere else. Bye.}


{120}{}{Me? Nothing... I used to do many things for the vault, but now... Now I do less and less... You can even say I do nothing at all...}
{121}{013}{What things you used to do?}


{122}{}{Me? I feel much better! I can't say my mental health is fully restored, but, you know... I've been thinking... You could deal with many things just as easily.}
{123}{010}{Try to think less about such things. I had other questions.}
{124}{999}{Oh... Yeah, sure. I think I need to go...}


{130}{}{I used to be involved in managing Livos... People listened to me... I was making important decisions... [Soup looks very nervous]}
{131}{014}{What happened then?}


{140}{}{Then... Then I married Emily. Yes, Emily is my wife... She was so tall, slender and beautiful... A dream of any man. When she chose me, I was head over heels from happiness. But then... [Soup starts nervously picking his clothes. He definitely doesn't feel comfortable talking about it.]}
{141}{015}{Come on, Soup, talk to me. You'll feel better.}


{150}{}{She turned out to be cold as ice! Slowly, but surely, she took over my power and influence. After that, she started to cause quarrels between the families, using their already strained relationships. Livos descended into chaos, and it is all Emily's fault! }
{151}{016}{Looks like you really hate her.}
{152}{010}{Let's talk about something else.}


{160}{}{Yes, it's true... [he gives you a long, thoughtful look] I have an important proposition for you. You are my last hope. We need to take Emily out! Will you help?}
{161}{017}{You want me to kill her?}
{162}{010}{No, I won't be a part of it. I just wanted to ask something.}
{163}{999}{Stop! I don't want to be involved! I'd better go.}


{170}{}{I want you to remove her. Do anything you want. Even... You know... Even if you have to... For the future of Livos...}
{171}{018}{Okay. I'll do it. For the future of Livos.}
{172}{010}{For now, let's just talk. Answer some of my questions.}
{173}{999}{No, not interested. Bye.}




{180}{}{[There's a fire in his eyes] This... This is wonderful! At last, I have hope! [He gets so carried away that stops paying attention to you]}
{181}{999}{Okay. Talk later.}




{190}{}{My family is me and my wife Emily. More precise, it's only Emily. She completely took over the leadership. I make no decisions in the vault anymore... She is... She is... A bitch! That's who she is!}
{191}{016}{Looks like you really hate her.}
{192}{010}{I see. Let's talk about something else.}




{2001}{}{Did you take care of Emily? Can I represent the Dunton family again?}
{2002}{}{[Soup looks much better than before. His shoulders are straightened, eyes filled with life and enthusiasm] Now, when she's gone, I can represent Duntons again! Thank you for everything you've done!}
{201}{021}{Are there any weaknesses of Emily I should know about?}
{202}{022}{Soup, did you ever try to deal with this problem yourself? }
{203}{010}{Let's talk about something else.}
{204}{025}{Yes, I dealt with her. The vault is now free of her tyranny!}




{210}{}{Emily loves gambling. Playing cards is everything for her. She also has a grandiose sense of self-worth. That means she always pays her debts... Maybe this information would help. You could try to set up an accident using monsters in the filter room.}
{211}{010}{Okay, I'll keep that in mind. Let's talk about something else.}




{220}{}{N-no, I, uh, don't know, actually... I... I'm afraid that won't be able to do it... [Soup hesitates]}
{221}{023}{You are the head of a family! You can make the right decisions!}
{222}{010}{[You fail to find words to convince him] Okay, let's talk about something else for now.}


{230}{}{Yes, I am...  I am in charge, I should be firm... But... I don't think I'm ready... [He still hesitates]}
{231}{010}{[You fail to find words to convince him]  Okay, let's talk about something else for now.}
{232}{024}{You can do it! Come on, Soup! The fate of the whole vault depends on you!}


{240}{}{[You see a determined look on his face] Yes. I should do it. The fate of all local people depends on me. Thank you for making me believe in myself. I'll go and do what I should.}
{241}{999}{Way to go, Soup!}


{250}{}{[For the first time, you see a smile on his face] This... This is so great! I am the head of my family again! I thank you for everything you've done!}
{251}{026}{You are not only the head of the Dunton family. You also should take the responsibility of leading the whole Livos.}
{252}{027}{Yes, you are the head of your family now. And I will take the position of the Livos leader. And if someone opposes, I know what to do.}

{260}{}{[His smile becomes even wider] I... It's an honor to me... Who could imagine that - I'm in charge for Livos, again! I will do everything for the vault to prosper!}
{261}{999}{You will be a wise leader. I need to go.}

{270}{}{Of course, yes... You have deserved to be the leader of the vault... You did so much for me. You can always count on my help.}
{271}{999}{Now I can start taking my duties. Bye, Soup.}


{280}{}{What? Who are these Seth and Matt? I have enough on my plate, let alone making some plans with NWO. I don't care what they are going to do.}
{281}{010}{Understood. I want to ask something else.}


{290}{}{I have a mission for you... It is pretty dangerous, I guess. There is a hole in the filter room, leading to a cave. The cave is full of nasty creatures, who can crawl out through the hole at any time and devour all Livos inhabitants! We must protect our home!}
{291}{030}{How should I do that?}


{300}{}{It doesn't matter how. You can kill off all monsters or plug the hole with something. Just make them not a threat to us.}
{301}{999}{Okay. I'll go carry out the task.}
{302}{031}{Okay. I'll go carry out the task.}
{303}{032}{Sure. I'm going to rip them into pieces very fast!}
{304}{033}{Sure. I'm going to rip them into pieces very fast!}


{310}{}{The task is dangerous, so I'll give you some batteries. Go and buy everything you need.}
{311}{999}{Thanks. I'll get back when it's done.}


{320}{}{The task is dangerous, so I'll give you some batteries. Go and buy everything you need. I see you are determined, so take this tool - it will help you to clean the cave.}
{321}{999}{Cool! Little monsters, here I come!}


{330}{}{I see you are determined, so take this tool - it will help you to clean the cave.}
{331}{999}{Cool! Little monsters, here I come!}


{340}{}{Great! Such good news! Here, take this voice modulator as a gift from me!}
{341}{999}{Whoa, you can use tech to imitate someone's voice? It will surely come in handy. I'll go now, see you.}