##############################
#Локация: ЛАЙВОС
#Имя: Вероника Швайн 
#Краткое описание: Жена Людвига
#Дата создания: 19.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a calm woman. She smiles a bit.}
{2}{}{She oozes with confidence.}
#
# после знакомства
{3}{}{You see Veronice.}
{4}{}{As usual, she is calm, clean and confident.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a confident middle-aged woman in a rich clothing. She holds her head high, giving you arrogant look.] Did you want something, young man?}
{11}{002}{I'm new here. Getting to know my neighbours.}
{12}{006}{I just want to talk about something.}
{13}{007}{Hey! So, how is it going?}


{20}{}{Yes, I heard about a newcomer in Livos. I see the bar dropped pretty low for becoming a new inhabitants.}
{21}{003}{Yeah, to become one of you is pretty easy.}
{22}{004}{I am very useful resident of Livos, and I had to put many efforts to prove it.}
{23}{005}{Maybe you'll behave a little nicer, woman?}


{30}{}{[The woman squints] I see, Livos dwellers have completely lost their self-respect and allow anyone in. Anyway, you're one of us now, so - welcome. I am Veronica Schwein.}
{31}{010}{Glad to meet you. Can I ask some questions?}
{32}{999}{Veronica, I've just remember about one business I need to do. Talk later.}


{40}{}{[She gives you evaluating look] I don't understand what useful they found in you. Anyway, you're one of us now, so - welcome. I am Veronica Schwein.}
{41}{010}{Glad to meet you. Can I ask some questions?}
{42}{999}{Veronica, I've just remember about one business I need to do. Talk later.}


{50}{}{[The woman squints] I see, Livos dwellers have completely lost their self-respect and allow anyone in. Young man, it's a great honor for you to become one of the dwellers. And you need to learn to behave with dignity, as befits to the ancient and respected family name of Schweins. Anyway, you're one of us now, so - welcome. I am Veronica Schwein.}
{51}{010}{Glad to meet you. Can I ask some questions?}
{52}{999}{Veronica, I've just remember about one business I need to do. Talk later.}


{60}{}{[The woman indifferently turns away] I have no time nor intention to "talk" without reason. If you have no business with me, let's not waste each other's time. I am Veronica Schwein, the most well-known political figure in Livos. I don't do empty "talk".}
{61}{010}{Glad to meet you. Can I ask some questions?}
{62}{999}{Veronica, I've just remember about one business I need to do. Talk later.}


{70}{}{[The woman opens her mouth amazed, but quickly returns to her indifferent and arrogant look] You, young man, are ill-mannered and rude. I am Veronica Schwein, and I ask you to show me some respect, because I represent the ancient and great family of Schweins. You'll have to learn to be discreet and polite to fit in Livos.}
{71}{010}{Understood. Can I ask some questions?}
{72}{999}{Veronica, I've just remember about one business I need to do. Talk later.}


{1001}{}{Hello, commander. Did you come to talk business?}
{1002}{}{I'm listening.}
{1003}{}{Hello. Did you come to talk business?}
{101}{011}{Veronica, what is it you do here, in Livos?}
{102}{014}{Tell me about other families.}
{103}{012}{How can I be useful around here?}
{104}{013}{I'd like to know more about the Schwein family.}
{105}{999}{Okay, Veronica, I need to go. Bye.}


{110}{}{[Veronica proudly raises her head] I am the most influent politician in Livos. No meeting is concluded without my speech in it. I have the biggest amount of speeches and suggestions. And many of my ideas were accepted and became a reality.}
{111}{013}{What are the other members of the Schwein family doing?}
{112}{014}{What can you tell me about other families?}


{120}{}{Everyone does their part in Livos... But I think that except one-time jobs of repairing the equipment, it would be difficult for you to find something to do. All profitable areas are divided and occupied, and you can't compete with me in politics. I suppose you could be valuable as a scout, provider of some rare tech, and also in creating diplomatic connections with other Radius settlements.}
{121}{010}{I see. Another question.}


{130}{}{[She bursts with pride] The Schwein family is the greatest and the most powerful in Livos! We control tme most important aspects of vault's life. My son, Christopher, is busy with external trade. Ludwig, my husband, is an outstanding scientist and inventor, one of a kind, I must say. His brother Edward is in charge for vault's protection. And I, modestly speaking, am the most experienced and perceptive politician and spokesman in Livos.}
{131}{015}{How did you become Ludwig's wife?}
{132}{010}{Great. I have another question.}


{140}{}{[Veronica chuckles] The other families are pale imitation of the Schweins. They are nothing. They do easiest and unnecessary jobs, which could be handled by anyone. McKinseys are putting water into barrels, Hortons are busy with petty fixings, and Duntons are trying to give me a challenge in politics. In short, they all are a bunch of losers, playing the game that's too big for them.}
{141}{010}{I see. Another question.}


{150}{}{[She gives out a smile of a winner] Oh, that was such a story. Ludwig kept himself locked in his working quarters for ages. So Edward put out a rumor that Ludwig will come out to choose the best woman of all who attended. Notice that I said not the most beautiful, not the most smart, but "the best". That's why I became his wife. I was the best - best prepared, best planned everything, best dealt with competitors. So, I achieved my dream and became the member of a great family of Schweins!}
{151}{016}{Dealt with the competitors?}


{160}{}{Yes! Someone had a bit of the stomach ache in that exact day, others had their carriage broken on the way to Livos, some run into the pack of wild jackals on the way. So, the ones who made it to the vault were in a pretty bad shape. And by the entrance they were met by a couple of tough guys who can do anything for a handful of batteries. My competitors were very lucky to stay alive - but not so lucky to be of actual competition to me anymore.}
{161}{010}{Good plan, I'll give you that. I want to ask something else.}