##############################
#Location: Livos
#Name: Edward Von Vincent Schwein 
#Short description: Hoarder sitting in the room tracking Livos (at the entrance)
#Date of creation: 17.08.2014 
##############################
#For the game "Olympus 2207"
#Artem "Rainman" Samoilov
##############################
#
#CRITTER DESCRIPTION
#
# before meeting
{1}{}{You see: the old hoarder.}
{2}{}{His face reminds you of raisins. You have never eaten raisins, but you have seen them in pictures.}
#
# after meeting
{3}{}{You see: Edward Von Vincent Schwein.}
{4}{}{Today he looks even more like raisins than yesterday.}
#
#HERE BEGINS A DIALOGUE
#
{10}{}{[You see a decrepit old man at the controls. He mutters something under his breath, his small eyes constantly running around. It seems that he does not notice you]}
{11}{002}{[Knock on the glass with your finger]}
{12}{006}{Hey, old man, wake up!}
{13}{008}{Hello. May I speak to you?}




{20}{}{[The old man glances in your direction. Quietly begins to mumble] Again someone came, so tired of them, no respect at all... [Then he turns to you] Yes? Did you want something?}
{21}{003}{Actually, not you, but You.}
{22}{005}{Yes, I would like to talk to you.}
{23}{008}{Yes, I wanted to talk to you.}




{30}{}{[An old man looks at you scornfully] What? I will never call such garbage as you "You"! But you should call me and other representatives of the proud family name Schwein on "You"!}
{31}{005}{Sorry, I get it. May I speak to You?}
{32}{006}{Piss off, proud representative, you are disgusting.}
{33}{004}{Schwein? Can't be! I am so glad to speak with one of the great Schweins!}



{40}{}{[The old man smiles smugly] Yes, you are lucky, unworthy. My name is Edward Von Vincent Schwein. You can call me Edward. It is an honor for you to call me only by name.}
{41}{010}{Thank you, Edward. May I ask you a question?}
{42}{006}{Pfft, honor for me, right. I will somehow do without your favors.}
{43}{007}{You're an "arrogant piece of shit". That's the only way I'll call you}


{50}{}{[The old man softened a bit] That's better. Cause half of the vagabonds here do not understand a thing. I am Edward Von Vincent Schwein, but you can just call me Edward, because you will not remember full one anyway.}
{51}{010}{Yes, Edward. May I ask?}
{52}{006}{I remember everything well, Edward Von Vincent Schwein, my brain is fine. You, on the other hand, clearly have problems with it.}
{53}{007}{I will call you as I want. Got it, old dick?}


{60}{}{[The old man's eyes are filled with rage.] So I, Edward Schwein, have to be humiliated by some shit from the outside world? Get out of here, you bald jackal! One more word and the turret will tear you apart!}
{61}{011}{Sorry, Edward Schwein, I made a mistake! I myself do not understand what I'm saying!}
{62}{999}{Fine, I am already leaving. Will come back later, when you cool down.}
{63}{998}{Come on, turn on your turret!}




{70}{}{[Edward silently puts his hands on the control panel of the turret. You have a couple of seconds to think]}
{71}{999}{[quickly move away from the window]}
{72}{998}{[stay and wait, drilling Edward with your eyes]}
{73}{998}{I won't go anywhere until we talk!}


{80}{}{[The old man slowly pronounces every word] First, show some respect. I am Edward Von Vincent Schwein, and will not tolerate such behaviour from some tramp.}
{81}{009}{Sorry, I will show respect.}
{82}{006}{I do not respect people like you.}
{83}{007}{Or what? I don't care about you!}



{90}{}{[Edward seems to calm down a bit] That's better. You can call me Edward. What do you want?}
{91}{010}{I would like to ask you something.}
{92}{006}{In general, you're just an arrogant old man.}
{93}{007}{None of your business, ye old dick, call the one in charge!}


{1001}{}{[Edward looks at you with indifference] And here is our new commander. Something happened?}
{1002}{}{[Edward looks at you with annoyance] I remember you, tramp. You are the dick that thinks he is cool, but in fact he is just a pile of Radius' garbage.}
{1003}{}{[Edward angrily looks at you] Only quick, and then get out.}
{1004}{}{[Edward looks at you with indifference] Oh, you again? Anything you wanted?}
{1005}{}{Okay, but hurry up.}
{101}{012}{Edward, our acquaintance did not go completely smoothly. Maybe a few batteries could help our conversation?}
{102}{023}{What is this place?}
{103}{024}{Where does this exit go?}
{104}{025}{What can I do here?}
{105}{027}{Edward, what are you doing here?}
{106}{026}{Tell me about your Schwein family.}
{107}{054}{About the Constitution...}
{108}{059}{I met Seth and Matt at NWO. They want to know who Livos will make an alliance with.}
{109}{999}{I need to go. Talk later.}



{110}{}{[Edward hissed through his teeth with hatred in his voice] Okay, I'll give you a chance to quickly say what you want. It would be a waste to spend ammo on you.}
{111}{010}{I would like to ask you some questions.}
{112}{999}{I'd rather come back later.}


{120}{}{[Edward looks at you with greed] Yes, it is possible... Batteries are good... They can help the conversation, yes.}
{121}{013}{[Suggest 5 batteries]}
{122}{016}{[Suggest 10 batteries]}
{123}{018}{[Suggest 15 batteries]}
{124}{020}{[Suggest 20 batteries]}
{125}{022}{[Suggest 25 batteries]}
{126}{999}{Oh, I don't have batteries right now... I'll come back later.}


{130}{}{[Edward looks in the bag and counts the batteries.]}
{131}{014}{So, let's continue?}
{132}{015}{So, let's continue?}


{140}{}{[Without taking his eyes off the contents of the bag, Edward mutters] Yes... I like it, I like it very much... Let's continue the conversation, fine.}
{141}{010}{I'd like to ask you something.}


{150}{}{[Edward looks very disappointed while returning batteries] No! You think you can buy my attention for a penny? Remember, a good attitude of Schweins can not be cheaply bought!}
{151}{999}{That's a pity. I'll come back later. }


{160}{}{[Edward looks in the bag and counts the batteries]}
{161}{017}{Well, let's continue the conversation?}
{162}{015}{Well, let's continue the conversation?}


{170}{}{[Without taking his eyes off the contents of the bag, Edward mutters] Yes... I like it, I like it very much... Let's continue the conversation, fine.}
{171}{010}{I'd like to ask.}


{180}{}{[Edward looks in the bag, counting batteries]}
{181}{019}{Well, let's continue the conversation?}
{182}{015}{Well, let's continue the conversation?}


{190}{}{[Without taking his eyes off the contents of the bag, Edward mutters] Yes... I like it, I like it very much... Let's continue the conversation, fine.}
{191}{010}{I'd like to ask.}



{200}{}{[Edward looks in the bag, counting batteries]}
{201}{021}{Well, let's continue the conversation?}
{202}{015}{Well, let's continue the conversation?}



{210}{}{[Without taking his eyes off the contents of the bag, Edward mutters] Yes... I like it, I like it very much... Let's continue the conversation, fine.}
{211}{010}{I'd like to ask.}



{220}{}{[Without taking his eyes off the contents of the bag, Edward mutters] Yes... I like it, I like it very much... Let's continue the conversation, fine.}
{221}{010}{I'd like to ask.}



{2301}{}{What is this, commander, a test? Okay, I'll play ball. This place is called Livos. The only place in the whole Radius where families of noble aristocratic blood were preserved. Only we reign in law and order, only we have a Constitution. No dictatorship - we decide everything at general meetings. Our great leaders will soon control the entire Radius, as it befits them by birthright. We own the only source of clean water that can be provided for everyone. Should we have any enemies, we simply cut them off our supply of water, then they'll just die out. Thus, we have a great mission to create a new society and to decide the fate of people.}
{2302}{}{This is Livos, the best place in Radius, the only supplier of clean water. Now get lost.}
{2303}{}{[Edward straightened and continued with pride in his voice.] This place is called Livos. The only place in the whole Radius where families of noble aristocratic blood were preserved. Only we reign in law and order, only we have a Constitution. No dictatorship - we decide everything at general meetings. Our great leaders will soon control the entire Radius, as befits them by birthright. We own the only source of clean water that can be provided for everyone. Should we have any enemies, we simply cut them off our supply of water, then they'll just die out. Thus, we have a great mission to create a new society and to decide the fate of people.}
{231}{038}{I want to talk about supplying water to the NWO.}
{232}{049}{Constitution? Tell me more about it.}
{233}{037}{Can I get inside and talk to other residents?}
{234}{010}{One more question.}
{235}{999}{Clear. See you later, I will go.}



{2401}{}{You are such a prankster, commander. Don't you recognize your Livos?}
{2402}{}{This is the entrance to the Livos vault. That's enough, outsiders like you are not supposed to know more. Now get out of here, tramp.}
{2403}{}{This is the entrance to the Livos vault. It serves as home and shelter to the best representatives of the human race. We rarely go outside - this world is not yet worthy of our ideas. Our refuge is the heart and soul of a civilized society.}
{241}{023}{I want to hear more about this place.}
{242}{037}{Can I get inside?}
{243}{010}{I'll ask more.}
{244}{999}{Okay, I'll go, we'll talk later.}


{2501}{}{[Edward looks annoyed] You can buy and sell things near those tables and roll away from here.}
{2502}{}{[Edward makes a sour face and mutters] My god, I'm so fed up with all this... [he looks up and continues, as if explaining it to a five-year-old child] From here you can see the tables near the entrance. The things are laid out on them. You can buy there, you can sell yours, you can barter. Go to those merchants and talk to them. [he adds quietly] And if you need some good alcohol, I have a few bottles to spare.}
{251}{Barter}{Show me the alcohol you've got.}
{252}{010}{I'll ask more.}
{253}{999}{I'll go talk to the sellers.}


{2601}{}{[Edward hissed through his teeth] This is not your business, tramp. This is what you must remember: I am Edward Schwein, and I do not want to see you here.}
{2602}{}{[Edward begins to speak with a fanatical glitter in his eyes] The name of the Schweins is the most famous and significant in Livos, and therefore - in the whole Radius! Only thanks to Schweins, Livos continues to live. The Schwein family has developed all the new laser and plasma weapons. I am the Schwein-senior, and only I have been entrusted with the most important job - to guard the entrance to Livos from all kinds of vagrants. }
{261}{037}{Can I get inside?}
{262}{057}{Tell us about other representatives of the Schwein name.}
{263}{006}{Somehow you do not like a great family. More like pushers and misers.}
{264}{010}{One more question.}
{265}{999}{I'll go, talk later.}




{2701}{}{[Edward squints contemptuously] I can make that turret to turn you into a minced meat if you will not get out of here.}
{2702}{}{[Edward proudly raises his head] I am the most important member in Livos, I am responsible for its safety. Only I can allow the passage to Livos. If some tramp wants to go through the door to the vault, I turn on the turret. Though, I, as the oldest and most experienced member of the Schweins family, can afford to have a slight weakness: I really like to collect various rarities. So if you have something unusual, I would look at it.}
{271}{028}{Here [show your stuff to Edward].}
{272}{029}{Here [show your stuff to Edward].}
{273}{037}{Can you let me go through?}
{274}{010}{I'll ask more.}
{275}{061}{Which things do you have in your collection?}
{276}{999}{I'd rather go.}


{280}{}{[Edward is looking at your things from behind the glass] This is rubbish... This is also rubbish... No one needs this at all... No, you have nothing interesting for me. I need rare mechanisms, or parts of a robot, for example. }
{281}{999}{Fine, I'll go look for something.}
{282}{010}{It's a pity, then I'll ask more.}




{290}{}{[Edward is looking at your things through the glass] This is rubbish... This is also rubbish... Oh! Wow! Here is some find! What a wonderful thing! The hand of a construction robot! Listen, I really want to have one in my collection.}
{291}{030}{I don't really need it, so I can sell it to you. How much will you pay for it?}
{292}{034}{I can give it to you - in exchange for a free passage to Livos.}
{293}{032}{As a member of Livos, I can sell you this hand at a discounted price.}
{294}{010}{No, I'll keep it for myself. Maybe it will come in handy later. Let's talk about something else.}
{295}{999}{I'm going to think about whether I need it or not.}



{300}{}{[Edward crunches, eagerly going over the batteries under the table] N-no, I can not afford to buy such things... Maybe we can find another way, without costs?}
{301}{031}{I need batteries. I won't agree for anything else.}
{302}{034}{For this hand, will you let me go to Livos?}
{303}{010}{If you are not ready to pay, you will not get it. Let's talk about other things.}
{304}{999}{Batteries only. I'll come back later when you pick it up.}




{310}{}{[Edward shrinks even more, clutched at his batteries, then suddenly backs out] No! I can't spend a single battery on this! I need them more than a robot hand! Let's think of something else!}
{311}{034}{Let's do it like this: I give you this hand, and you will let me into the vault.}
{312}{010}{If there are no batteries, there is no robot arm. Let's talk about something else.}
{313}{999}{I will not give my hand without batteries. I'll go for now - and you think about the payment.}




{3201}{}{[Edward, with visible strong shakes, slowly counts out a certain amount] I only have 60 batteries, I can not afford anymore... And this is only because you are a member of Livos.}
{3202}{}{[Edward, with visible strong shakes, slowly counts out a certain amount] I only have 45 batteries, I can not afford anymore... And this is only because you are a member of Livos.}
{321}{033}{Fine, I agree.}
{322}{033}{Fine, I agree.}
{323}{010}{No I do not agree. I still want to ask.}
{324}{999}{No, I'll go look for another buyer.}




{330}{}{[Edward reluctantly gives away the bag of batteries. But when he takes the protector's hand, he begins to gently stroke and hug it.] Oh, what a wonderful thing, what a rarity... Oh, my darling...}
{331}{999}{[You leave Edward alone with this touching occupation]}


{340}{}{[Edward hesitates] I don't know, this thing is wonderful, but I can't let you in if you are not a member of Livos...}
{341}{035}{This is a great thing! You will not find it anywhere else. Make me a member of Livos - and that's it, the hand is yours!}
{342}{010}{Too bad. Let's move on to other questions.}



{350}{}{Well, you are definitely worthy of wearing the name Schwein! I will quickly sign the paper now! Come here, robot hand!}
{351}{036}{Take it!}


{360}{}{[Edward quickly gives you the paper] Here - a paper about the adoption from a family, with it you can safely pass. [he takes the protector's hand, begins to gently stroke it and cuddle it] Oh, what a wonderful thing, what a rarity... Oh, my darling...}
{361}{999}{[You leave Edward alone with this touching occupation]}


{3701}{}{Of course, you can go inside at any time, you're one of us.}
{3702}{}{No, access to Livos is allowed only to its members who are hereditary nobles and aristocrats. Vagrants are strictly forbidden. If you try to get through, I'll turn the turret on.}
{371}{038}{I was asked by the NWO to find out what happened to the water supply. There was a taste is water, people are worried.}
{372}{039}{I'm not a tramp! I am a famous nobleman in where I came from! I can become a member of your family for our common benefit.}
{373}{045}{Wonderful! I've been looking for you for so long! This is a refuge with my distant relatives, true aristocrats!}
{374}{058}{I brought you the Constitution, didn't I deserve to be one of you?}
{375}{010}{Clear. I'll ask again.}
{376}{999}{Okay. I'll come later.}



{380}{}{[Edward looks at you with bewilderment] Uh-uh... I don't know anything about this. I do not supply water. Ask Christopher, he is at the trading table, maybe he knows.}
{381}{010}{I'll ask again.}
{382}{999}{I'll go talk to him.}




{390}{}{[Edward looks at you with suspicion.] Really? You look more like an ordinary vagabond, rather than a rich and famous person. It is full of beggar rabble, novadays everyone wants to become a member of Livos. What evidence do you have?}
{391}{040}{My honest word of a nobleman - this is all I have!}
{392}{042}{I can easily prove that I am rich by donating a small amount for the development of Livos.}
{393}{041}{I have no evidence.}
{394}{010}{Let's leave this topic, I want to know about something else.}
{395}{999}{I'll think about the evidence when I find it - I'll come.}




{400}{}{[Edward burst out laughing] Shove your honest word of a nobleman up yours! The beggars are often use such tricks to get to us, but it won't do!}
{401}{042}{I can prove that I am not a beggar by donating a small amount of Livos.}
{402}{041}{I have no other evidence.}
{403}{010}{Well, then I will ask you about something else.}
{404}{999}{I will find evidence, then I will come back.}




{410}{}{Hahaha! Get out of here, nobleman! I see such nobles every day, they beg for a battery! }
{411}{999}{Fine, I'll go...}




{420}{}{[Edward stared at you greedily] A small amount, you say? This is a solid proof of noble origin... Can you donate, say, 1,500 batteries for the development of Livos?}
{421}{043}{Yes, easily. For me it is a trifle.}
{422}{041}{I do not have such funds.}




{430}{}{[Edward hatches, his hands shake.] What? Is it a minor thing for you? Of course, come here with the batteries, and I will, of course, spend them on prosperity of Livos! Just don't tell anyone about this, I want to remain anonymous. }
{431}{044}{Here, take them, I don't mind.}
{432}{999}{You know, I changed my mind. Bye.}



{440}{}{[Edward quickly counts the batteries with a smile on his face and a slight incomprehensible mumbling] Fine, very good! You really are a real nobleman, here are your papers, now you are one of us! You can safely go inside the vault. [looks like he lost all interest in you and slowly began to put the batteries in small piles]}
{441}{999}{[You leave quietly]}




{450}{}{[He looks at you incredulously. Our whole family, starting with Sebastian Schwein, the founder of this shelter, lived here and had no contact with the outside world.}
{451}{046}{Exactly! My distant ancestor is the son of Sebastian Schwein! He did not have time to get to the vault before the outbreak of war, and then all my ancestors tried to find you. And only I managed to do it! I am happy to be reunited again with the great family of the Schweins!}
{452}{047}{Exactly! My distant ancestor is the son of Sebastian Schwein! He did not have time to get to the vault before the outbreak of war, and then all my ancestors tried to find you. And only I managed to do it! I am happy to be reunited again with the great family of the Schweins!}



{460}{}{Yes, there are some old records about a certain relative of Sebastian, who didn't make it to the vault... I could never think that we would ever meet his descendant! Well, welcome to Livos! You can safely go inside.}
{461}{999}{Thank you, I will go to meet the rest of our family.}




{470}{}{Yes, there are some old records about a certain relative of Sebastian, who didn't make it to the vault... But look at yourself! You're black as coal, and all the other Shweins are white!}
{471}{048}{This long life in inhuman conditions left its mark! And the effect of radiation changed the color of my skin. But inside I am the same as you, the true descendant of the great Shweins!}
{472}{999}{Yes, it does not match... Well, see you later.}




{480}{}{Yes, radiation influenced you a lot. But I'm still glad that we met a descendant of Sebastian! Well, welcome to Livos! You can safely go inside.}
{481}{999}{Thank you, I will go to meet the rest of our family.}




{490}{}{[Edward pointedly raised his finger] The Constitution is the basis of our rights. Each member has 15 rights, which are recorded in this constitution.}
{491}{050}{Can I see these rights of the residents of Livos?}




{500}{}{No, the Constitution is only for the residents of Livos. And I do not want to talk about it, because, according to paragraph 8 of the Constitution, every inhabitant of the New World has the right not to talk to other inhabitants of the New World, even if the latter strongly insist.}
{501}{010}{It's a pity. I also wanted to ask.}
{502}{051}{You know, I am very well versed in this kind of documents. I could tell you how to use the points of the Constitution for your own benefit.}
{503}{052}{Come on, you have none! You probably accidentally sold the constitution to some kind of savage two meters tall, and now you can't get it back!}
{504}{053}{And, according to the Constitution, can anyone make someone talk by force?}




{510}{}{That would be very useful... Okay, I will tell you a secret: I accidentally sold the Constitution to some savage two meters tall, and now I do not know how to return it. Find it, give it back to me, don't tell anyone. I will reward you generously. And, of course, I will tell you where to look for this tribe.}
{511}{999}{Okay, I'll look for it among the savages.}
{512}{010}{I don't have time for this right now. Let's talk about something else.}




{520}{}{[Edward opened his mouth in surprise] Gosh, how did you know about the savage! Listen, don't tell anyone about this. Give me back the Constitution, and I will reward you generously! And, of course, I will tell you where to look for this tribe.}
{521}{999}{Ok, I'll look for it among the savages.}
{522}{010}{I don't have time for this right now. Let's talk about something else.}




{530}{}{No, there's nothing about such things in constitution. [He looks at you] You know, I like your spirit. I might need a man with your attitude. I accidentally sold the Constitution to some savage two meters tall, and now I do not know how to return it. Find it, give it back to me, don't tell anyone. I will reward you generously. And, of course, I will tell you where to look for this tribe.}
{531}{999}{Okay, I'll look for it among the savages.}
{532}{010}{I don't have time for this right now. Let's talk about something else.}




{540}{}{So, did you find the Constitution of 15 rights?}
{541}{056}{Yes, I have it with me.}
{542}{055}{Remind me what to do?}
{543}{010}{I actually wanted to ask something else.}




{550}{}{I accidentally sold the Constitution to some savage two meters tall. Find it and return it, and you will receive a reward.}
{551}{999}{Okay, I'll continue looking for it.}




{560}{}{Great! Give it to me! A generous reward awaits you!}
{561}{999}{Here, don't lose it anymore.}




{570}{}{[Edward reluctantly began to mumble] You... Why do you need to know about others? The most important thing here is me, and therefore I occupy a post in the tracking room. I am the oldest in our family. I have a brother, Ludwig. He sits all day and picks in the workshop with his lasers. His son, Christopher, is trading at that table. If you want to know more, ask him. He knows more about his parents - their names are Ludwig and Veronica.}
{571}{010}{I would like to ask more.}
{572}{999}{I'll go talk to them.}




{580}{}{Yes, for sure, you did a great service to the Livos and the Shwein family! You deserve to be with us. Welcome! You can go inside at any time.}
{581}{999}{Thank you, Edward! I'll go meet the rest.}




{590}{}{What? Who the hell are Seth and Matt? What union?}
{591}{060}{They say that Radius wants to capture Livos. They want to be your allies in this war.}




{600}{}{We will conquer everything around without the help of these assholes! I'm not going to conclude an alliance! Tell them to go where the sun don't shine with their suggestions. The Shwein family definitely won't talk to them. Ask the heads of other families, maybe they could want something from these vagrants.}
{601}{010}{Well, I'll ask the others.}



{610}{}{Oh, I have a lot of rare and unique things! From around the radius I bring them! True, I do not know what they are called. The main thing is that these are complex mechanical systems. I bring things from Oasis, Tin Industries, Rainbows, NWO and even from Olympus itself!}
{611}{062}{Can you show these places on the map?}




{620}{}{Hm... I only know where Tin Industries and Oasis are located. Let me show you...}
{621}{999}{Thank you. I want to ask more.}