#############################################################
#Critter text file << Livos resident guy in the filtration room >> 
#############################################################
#File structure:
#lines 1-9 - description of the character;
#lines 10-29 - acquaintance with a pesonage;
#lines 30-99 - I don't know yet, but I think it will be useful...
#Next, on the branches of the dialogue.
#Each branch is a multiple of 100, i.e. 100 is one topic of dialogue, 200 is another.
#Character replicas go after 10, i.e. 100, 110, 120, etc. With that
#for replica 100 use Node010, for replica 240 use Node024.
#For player answers - continuous numbering, i.e. the replica 650 responses will be 651, 652, 653, etc.
#For special branches use additional numbers (for example, the replica 360 is divided into 3601 and 3602,
#the same applies to the Node procedure, the answers will be in the usual form - 361, 362, etc.)
#############################################################
#Such an organizational system does not allow creating too complex dialogues,
#which for me personally is very good!!!
############################################################
#specially for "Olympus 2207", by Rainman, 13/04/2013
#############################################################
#
#CRITTER DESCRIPTION
#
{1}{}{You see a guy.}
{2}{}{You see a local guy.}
{3}{}{You see a young man.}
{4}{}{You see a resident of vault.}
{5}{}{You see a dweller of Livos.}
{6}{}{A young man. The web of blue veins is clearly seen through the pale skin.}
{7}{}{He dresses quite well.}
{8}{}{He does not seem to bother himself with too much work.}
{9}{}{He looks at you as if you owed him something very valuable.}
#
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#SWIMMING MESSAGES
# Positive messages
{1000}{}{Greetings brother!}
{1001}{}{Good day, friend!}
{1002}{}{Hello! Let's hang out by the wine machine some time later!}
{1003}{}{Yes, yes, I'm glad to see you too.}
{1004}{}{Wonderful day today, isn't it?}
{1005}{}{I'm so glad to see you!}
{1006}{}{I cannot express with words how glad I am to see you, my friend!}
{1007}{}{Let's make contact at any time!}
{1008}{}{You are our pride!}
{1009}{}{Without second thoughts, my dear!}
# Neutral messages
{1010}{}{What now?}
{1011}{}{N-no, just leave.}
{1012}{}{Find yourself something to do.}
{1013}{}{You are invading my personal space.}
{1014}{}{How do I say it... Scat away from me.}
{1015}{}{You are preventing me from admiring our chambers.}
{1016}{}{Go stick to the Hortons. They are friendly.}
{1017}{}{Better go irritate Schweins.}
{1018}{}{Listen, new one... On the other hand, I'm too lazy to talk to you.}
{1019}{}{Ew! The smell of you!}
# Negative messages
{1020}{}{Arrrgh! Go away!}
{1021}{}{I hate you, scum!}
{1022}{}{How dare you!?..}
{1023}{}{Get away, abomination of hell!}
{1024}{}{Oh you fucking burp of nasty beast!}
{1025}{}{I'm gonna tear out your spleen and eat it with a glass of Chianti!}
{1026}{}{We urgently need to clear the world of your presence, you bastard!}
{1027}{}{What the hell do you want from me?!}
{1028}{}{Just thinking about you makes me sick!}
{1029}{}{You... You... Bitch!}
#Sleeping messages
{1030}{}{Need. To. Keep. The. Damn. Mechanisms. Working.}
{1031}{}{I huffed and puffed and hit hard - but it still makes noise...}
{1032}{}{I definitely picked the wrong turn in life...}
{1033}{}{Why am I doomed to do this, I wonder? Is it karma? Maybe there is no such thing as fate and everything is in vain...}
{1034}{}{To knock, to spit, to scratch the back of my head... It seems that I do everything according to the instructions, but it is not being repaired.}
{1035}{}{Someone, bring me an electric hammer! I will show these gears...}
{1036}{}{I am the light of the New World! I must breed, not sweat here...}
{1037}{}{Rrrh, n- oh, come on! Work, you hellish device!}
{1038}{}{Filters don't filter, generator does not generate...}
{1039}{}{...We need to make filters filter and regenerate the generator!}