#############################################################
#Critter text file << Livos resident girl >> 
#############################################################
#File structure:
#lines 1-9 - description of the character;
#lines 10-29 - acquaintance with a pesonage;
#lines 30-99 - I don't know yet, but I think it will be useful...
#Next, on the branches of the dialogue.
#Each branch is a multiple of 100, i.e. 100 is one topic of dialogue, 200 is another.
#Character replicas go after 10, i.e. 100, 110, 120, etc. With that
#for replica 100 use Node010, for replica 240 use Node024.
#For player answers - continuous numbering, i.e. the replica 650 responses will be 651, 652, 653, etc.
#For special branches use additional numbers (for example, the replica 360 is divided into 3601 and 3602,
#the same applies to the Node procedure, the answers will be in the usual form - 361, 362, etc.)
#############################################################
#Such an organizational system does not allow creating too complex dialogues,
#which for me personally is very good!!!
############################################################
#specially for "Olympus 2207", by Rainman, 13/04/2013
#############################################################
#
#CRITTER DESCRIPTION
#
{1}{}{You see: a girl.}
{2}{}{You see: a local girl.}
{3}{}{You see: a young lady.}
{4}{}{You see: a resident of the vault.}
{5}{}{You see: a resident of Livos.}
{6}{}{A young lady with a haggled, pale face.}
{7}{}{Despite her clothes being badly battered, you are pretty sure that she never had to hunt rats or spend the night in caves.}
{8}{}{Bags under her eyes are clumsily masked by some powder. Or is it lime?..}
{9}{}{Catching your gaze, the girl blinks with her left eye. Apparently, this is some kind of a tick.}
#
#HERE BEGINS A DIALOGUE
#
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#SWIMMING MESSAGES
# Positive messages
{1000}{}{Hey, sweetie!}
{1001}{}{Good day!}
{1002}{}{Hello! Wanna hang out near the wine machine sometime?}
{1003}{}{Yes, I'm glad to see you too.}
{1004}{}{A wonderful day for sex, isn't it? [winks]}
{1005}{}{I'm so glad to see you!}
{1006}{}{Hey-hey, valiant warrior!}
{1007}{}{Honey, any whim - for you!}
{1008}{}{Oh, these pants suit you so much!}
{1009}{}{Surely! Let me just finish here something.}
# Neutral messages
{1010}{}{So, how are you?}
{1011}{}{No, you know, not today.}
{1012}{}{Find yourself something to do.}
{1013}{}{You are invading my personal space.}
{1014}{}{No, not today.}
{1015}{}{Nothing personal - you are just not my type, cowboy.}
{1016}{}{This place is not suitable for you. Or the other way around.}
{1017}{}{Do not look at me like that! So many perverts here...}
{1018}{}{Listen, new one... Forget it, I'm too lazy to talk to you.}
{1019}{}{Go away, nasty.}
# Negative messages
{1020}{}{Arrrgh! I'll scratch your face out with this fork!}
{1021}{}{I hate you, asshole!}
{1022}{}{How can you!?..}
{1023}{}{You insult my life with your presence!}
{1024}{}{Oh you fucking burp of nasty beast!}
{1025}{}{I would tie you up and slowly cut you with a knife into many little pieces!}
{1026}{}{Do a favor to the world - cut your balls off!}
{1027}{}{You nasty thing! I'm sick of you!}
{1028}{}{Goat! All goats, but you... You are archgoat!}
{1029}{}{Scum! Monster! Hypocrite! Freak!}
#Sleeping messages
{1030}{}{No, I do not need baggy pants! I clearly said - DRESS!}
{1031}{}{Oh, you stupid piece of metal! Black dress, not red!}
{1032}{}{It hurt me again... When does Peter going to repair this piece of junk!?}
{1033}{}{Oof! There is someone's tail in my oatmeal!!! Gyaaaah...}
{1034}{}{Oatmeal, oatmeal, oatmeal... I want ice cream!}
{1035}{}{Nooo, it looks like a rat poop...}
{1036}{}{If you, stupid piece of metal, will not give me tangerines right away - I'm going to rip your cogs out!}
{1037}{}{}
{1038}{}{}
{1039}{}{}