#############################################################
#Текстовый файл для криттера << Дама Livos >> 
#############################################################
#Структура файла:
#строки 1-9 - описание персонажа;
#строки 10-29 - знакомство с песонажем;
#строки 30-99 - пока не знаю, но думаю, что пригодятся...
#Далее, по веткам диалога.
#Каждая ветка кратна 100, т.е. 100 - одна тема диалога, 200 - другая.
#Реплики персонажа идут через 10, т.е. 100, 110, 120 и т.д. При чем 
#для реплики 100 использовать Node010, для реплики 240 - Node024.
#Для ответов игрока - сквозная нумерация, т.е. на реплику 650 ответы будут 651, 652, 653 и т.д. 
#Для особых ответвлений использовать дополнительные цифры (например, реплика 360 делится на 3601 и 3602,
#это же касается процедуры Node, ответы же будут в обычной форме - 361, 362 и т.д.)
#############################################################
#Такая организационная система не позволяет создавать слишком сложные диалоги,
#что для меня лично очень хорошо!!!
############################################################
#специально для "Олимп 2207", by Rainman, 13/04/2013
#############################################################
#
#ОПИСАНИЕ КРИТТЕРА
#
{1}{}{You see a lady.}
{2}{}{You see a local lady.}
{3}{}{You see an old dame.}
{4}{}{You see a dweller of the vault.}
{5}{}{You see an inhabitant of Livos.}
{6}{}{A woman of venerable age with a pale grey skin.}
{7}{}{Her look indicates that everyone else in comparison to her are just worms.}
{8}{}{Contemptuous look of this lady makes you wonder about appropriateness of you being here.}
{9}{}{Through the holes in fabric of once beautiful silk dress one can see wrinkles of saggy skin.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{}
{11}{}{}
{12}{}{}
{13}{}{}
{14}{}{}
{15}{}{}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#ПЛАВАЮЩИЕ СООБЩЕНИЯ
# Положительные сообщения
{1000}{}{Hello, dear!}
{1001}{}{Good day!}
{1002}{}{Oh, young man, it's such a pleasure to see you here!}
{1003}{}{Yes, I'm glad to see you too.}
{1004}{}{A wonderful weather today, don't you think so, young man?}
{1005}{}{Oh, such a sweet young man!}
{1006}{}{In my younger years I would give you a ride, cowboy! [winks]}
{1007}{}{Sweetie, anything for you!}
{1008}{}{What a body! What a beautiful man!}
{1009}{}{Maybe meet me later with a bottle of champagne?}
# Нейтральные сообщения
{1010}{}{Young man, do not bother me, be so kind.}
{1011}{}{Let me kindly ask, what family are you belong to?}
{1012}{}{Find yourself something to do, young man.}
{1013}{}{You are distracting me with your presence.}
{1014}{}{N-no, not on this day.}
{1015}{}{My dear, be kind to hang out somewhere else.}
{1016}{}{I can't see a family birth mark on you, young man.}
{1017}{}{Ahahah, don't even think about it!}
{1018}{}{Just step away from me to a venerable distance.}
{1019}{}{I'm busy. Yes. Thank you.}
# Отрицательные сообщения
{1020}{}{Arrrgh! I'm gonna scratch your face out with this fork!}
{1021}{}{I hate you, scum!}
{1022}{}{How dare you!?..}
{1023}{}{You are insulting me just with your presence!}
{1024}{}{Oh you fucking burp of nasty beast!}
{1025}{}{I would tie you down and cut you up into a little pieces!}
{1026}{}{Do a favor to the world by cutting your balls off!}
{1027}{}{Eeew! Yuck! I feel sick, you filthy abomination!}
{1028}{}{Asshole! All men are assholes, but you... You are the king of assholes!}
{1029}{}{Scum! Filth! Jerk! Dirtbag!}
#Спящие сообщения
{1030}{}{::Zzzzz...::}
{1031}{}{::Hrmhmmmhm...::}
{1032}{}{::Mmmmnmrm...::}
{1033}{}{::Uuuhmrmrm...::}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}
#официальные сообщения с подиума
{1040}{}{I firmly believe that Hortons should make peace with McKinseys! Effective immediately!}
{1041}{}{The Constitution of Fifteen Rights is hopelessly outdated! It should be rewritten as soon as possible!}
{1042}{}{Women, as the future mothers of the New World inhabitants, should rule over the men!}
{1043}{}{It's time for us to return to the surface and start populating the Earth with a new race!}
{1044}{}{Men! Act like men for once and fix this damn water filter!}
{1045}{}{Maybe it's time to elect the leader? I fit for the role perfectly.}
{1046}{}{I suggest to cancel the results of yesterday's poker game! The rat has been peeking into my cards!}
{1047}{}{I suggest to revoke the Wine Debt. It was a stupid idea to begin with.}
{1048}{}{Let's push the morning debates to eleven'o'clock. At least we won't have to get up early...}
{1049}{}{Has anyone seen our wonderful Constitution? I made a few notes on it and forgot what I wrote...}
#тихие проклятья про себя
{1050}{}{Damn Schweins! They think they are the smartest.}
{1051}{}{This slut Mignon is eventually gonna get what's coming.}
{1052}{}{Emily, you didn't have to perform so hard.}
{1053}{}{Soup is a decrepit wuss. He's the shame of a whole New World.}
{1054}{}{Which crazy person was first to come up with a Wine Debt?}
{1055}{}{Ashton has completely lost his marbles with his hotel.}
{1056}{}{Next time I'm going to spike Abilyn's wine with a laxative. And with sleeping pills.}
{1057}{}{This little dirty empty-headed McKinsey's bitch Fox...}
{1058}{}{They all gonna pay! They all gonna pay for the last game of poker!}
{1059}{}{I'll come up with my own Constitution. No, I won't forget about the blackjack part.}