##############################
#Локация: НМП
#Имя: Arsene
#Краткое описание: Сын Дана
#Дата создания: 21.06.2014
##############################
#Для игры "Олимп 2207"
#Сергей "Zoomer" Бокарев
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a young man in a strange jacket.}
{2}{}{His haircut makes him look like he just fell from a truck, using his head as brakes.}
#
# после знакомства
{3}{}{You see Arsene.}
{4}{}{His jacket looks worse every time.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
#Node001
{10}{}{[You see a young man with a full head of hair. His clothes are covered with dirt stains, holes, and cuts. Seems like he never washed it in his life.] Yes? }
{11}{002}{Hello. I'm new here, just looking around.}
{12}{003}{Hello. Who're you?}



#Node002
{20}{}{Well, uh, hello. Go on, it's not illegal to look.}
{21}{003}{What's your name?}



#Node003
{30}{}{I'm Arsene. Are you, uh, like, from afar?}
{31}{004}{Yes, I was born in a very distant settlement.}
{32}{009}{I was born in Olympus!}
{33}{008}{No, I lived in a nearby village, just never had the chance to get here.}
{34}{999}{Arsene, I've just remembered something I need to do. I'll come by later.}
{35}{}{I'm Arsene. And you, uh, like, our new Mayor? Did you want something?}
{36}{}{I sure am. I have some questions.}



#Node004
{40}{}{Hehe, cool. It was, like, probably difficult to get here. I mean, uh, a lot of bandits around and dangerous, or something.}
{41}{005}{Nah, no sweat. It was pretty easy.}
{42}{006}{There were some difficulties, but I managed.}
{43}{007}{Yes, the outside world is full of danger. I barely made it here, almost died a few times.}



#Node005
{50}{}{You are, like, cool, or something. Not afraid of all these, like, dangers.}
{51}{010}{Yes, nothing I couldn't handle. Let me ask you a few questions.}
{52}{010}{I didn't even meet a single bandit on my way here. Okay, let me ask something.}



#Node006
{60}{}{You must have, like, a lot of skills, to, uh, do it.}
{61}{010}{And I used them quite often. Let me ask you a few questions.}
{62}{010}{Nah, nothing special. Okay, let me ask something.}



#Node007
{70}{}{You are the lucky one. I mean, uh, a lot of folks can't make it. Even the most experienced.}
{71}{010}{Yes, sometimes I had to move under heavy fire. Let me ask you a few questions.}
{72}{010}{Caution and quick feet are what keeps you alive. Okay, let me ask something.}



#Node008
{80}{}{Oh, I see. I was thinking, uh, maybe you could tell, like, how is it there. Or something.}
{81}{010}{I've never seen much. Okay, let me ask you a few questions.}



#Node009
{90}{}{[Arsene looks at you with interest] Hehe, cool! You are, like, from Olympus? Oh man, tell me how it is there!}
{91}{011}{I was one of the chief executives there. Could do everything I wanted. Had everything I needed.}
{92}{014}{I was a Defender. Kept the world safe, maintained order in Olympus.}
{93}{015}{I was just a Technology Servant. I've never been outside of Olympus my whole life.}



#Node010
{1000}{}{Uh, sure.}
{1001}{}{Hey there. Like, came by to chat, or something?}
{1002}{}{Hello! Man, I wish we were in the Olympus already. You want, like, to talk, or something?}
{1003}{}{Mayor? It's, like, wrong. Daniel should be the Mayor. He knows what to do with the place.}
{101}{017}{What can you tell me about this place?}
{102}{019}{What do you do here?}
{103}{024}{Tell me about the people who live in this town.}
{104}{016}{Where can I find some work?}
{105}{020}{[You notice some spots of paint on Arsene's clothes as if he wiped hands with it. Looks just like the paint you put on the bucket with Lavash food] Why did you touch the Lavash food pen?}
{106}{022}{Arsene, I know that it is you who puts the machine oil into Lavash food mix.}
{107}{022}{[Your watchful eye of experienced thief notices the traces of Lavash food on Arsene's clothes] Arsene, what is it on your clothes? A Lavash food mix?}
{108}{042}{Do you mind me being the Mayor?}
{109}{999}{Let's talk later. I need to go, bye.}


#Node011
{110}{}{Oh, cool! Why did you, like, leave? It should be awesome there!}
{111}{012}{I got pretty tired, so I decided to travel the world.}
{112}{013}{I have an important mission - and that's what I have to say about it. Or I'll have to kill you.}

#Node012
{120}{}{Wow! Can you let me into the Olympus?}
{121}{010}{Of course! I can do whatever I want. But not now. Let me ask you some questions.}
{122}{010}{No, I don't think I could. I'm not so important. Okay, answer me some questions.}

#Node013
{130}{}{I won't tell anyone! I, like, can be trusted, you know. }
{131}{010}{Okay. Okay, answer me some questions then.}

#Node014
{140}{}{Wow! Can you let me into the Olympus?}
{141}{010}{Of course! I can do whatever I want. But not now. Let me ask you some questions.}
{142}{010}{No, I don't think I could. I'm not so important. Okay, answer me some questions.}

#Node015
{150}{}{Oh, nevermind then... I, uh, wanted to get into Olympus or something.}
{151}{010}{I could sneak you in. But not now. Let me ask you some questions.}
{152}{010}{I doubt it is possible. Okay, answer me some questions.}

#Node016
{160}{}{[Arsene ponders. To speed up the thinking process, he starts picking his ear] Uh... Umm... Man, I don't know. I don't like work. Nah, I really don't know. Maybe Mayor can give you some job, or, uh, the head of the guards. }
{161}{010}{Okay. Another question then.}
{162}{999}{I'll go look for them.}

#Node017
{170}{}{[Arsene cringes and looks away] What to say? This is, like, a boring and stupid town. Nothing to do for cool guys like me and Daniel. It's just, like, Lavash and tin cans around. And the folks here are mostly, you know, work all day. I don't know what for. As they say - "Dying Lavash won't give a good offspring". }
{171}{029}{Tell me about Daniel.}
{172}{018}{Do you have a job?}
{173}{023}{Dying Lavash won't give a good offspring? And what does it mean?}
{174}{010}{I'll ask something else then.}
{175}{999}{I see. I'll go ask someone else about the town.}

#Node018
{180}{}{[Arsene looks at you like you've just said something really, really stupid] Nah, come on. I, like, tried once. It's boring. Screw the job.}
{181}{010}{Um, I'm, like, helping with loading stuff. On a, like, factory. And I, uh... Hurt my leg, so I'm on a break now. Healing myself.}
{182}{010}{Really? Let's talk about something else then.}
{183}{999}{Okay. I'll go talk about work to someone else.}

#Node019
{190}{}{I mostly, uh, hang out with Daniel. We are, like, friends. And I spend time with my pa. My pa is the best! The best in all NWO!}
{191}{029}{I'd like to hear more about Daniel.}
{192}{028}{Tell me about your father.}
{193}{010}{Okay, another question.}
{194}{999}{I need to go now. Bye.}

#Node020
{200}{}{[Arsene confusingly stares at you] Er, we're, like... Me and Daniel, we... Uhh... Tried to reduce the consumption of Lavash food rations, you know! So I put some machine oil in it.}
{201}{021}{You shouldn't, really. They refuse to eat now. At all. Philip wouldn't like to learn about this...}
{202}{021}{Yeah? Are you really this dumb? I think you should be assigned the job of Philip's assistant.}

#Node021
{210}{}{Man, I never thought that Lavash are smarter than people. The local folk ate the oiled meat without complaining... Listen, don't tell Philip about me! I'll give you four packs of Combatid if you won't!}
{211}{999}{Uh, I'm sorry! I won't do it anymore, I swear! And to show you I'm honest, I'm ready to part with my supply of Combatid. Four packs. And I'd like you to not tell Philip. I don't need another enemy...}
{212}{999}{Okay, give me your Combatid, I won't tell Philip. But you should stop putting oil in everything, got it? Okay, I need to go.}
{213}{010}{I'll think about it. For now, I have some questions.}
{214}{999}{Okay, I need to go think about it.}

#Node022
{220}{}{Uhh... Well, yeah, We've been putting oil in it, to increase the, uh, amount of food. We also added it into canned meat once.}
{221}{021}{You shouldn't have, really. Lavash refuse to eat now. At all. Philip wouldn't like to learn about this...}

#Node023
{230}{}{How would I know? It sounds pretty cool though. }
{231}{010}{Okay, another question then.}
{232}{999}{I need to go now. Bye.}

#Node024
{240}{}{I can tell you about Daniel, Mark, and my pa Dan. I don't really know about others, and I'm not really interested. }
{241}{029}{I'd like to know about Daniel.}
{242}{025}{Tell me about Mark.}
{143}{028}{Tell me about your father.}
{244}{010}{Let me ask something else.}
{245}{999}{Not now, I need to go.}

#Node025
{250}{}{What to say about him... Mark is a Mayor. Daniel's father. He's, like, always busy with some papers and stuff. He tries to look as if he knows how to run things. But he actually doesn't! My pa would show him how to, uh, do it.}
{251}{026}{Why do you think that Mark doesn't know how to run the place? }
{252}{027}{What your father would do?}
{253}{010}{Okay, another question then.}
{254}{024}{I'd like to ask about someone else.}

#Node026
{261}{}{He is just wasting time on stupid things! My pa knows everything better in every way!!}
{262}{028}{Tell me about your father.}
{263}{010}{Another question then.}
{264}{024}{Tell me about others.}

#Node027
{270}{}{[Arsene gets lively] My pa doesn't like Mark! Pa wants to, like, change things around here!! He, uh, always tells us how bad Mark is in running NWO!}
{271}{010}{Okay, let me ask something else.}
{272}{028}{Tell me more about your father.}
{273}{999}{Okay. I need to go now, see you.}

#Node028
{280}{}{[Arsene's eyes bright with pride] Dan, my pa, is the smartest man in NWO! He is, like, so smart he knows everything! Man, he always tells Daniel and me about politics. So many smart things! I want to be like him, but I'm, like, not very good at it. I guess me and Daniel are not, uh, being very serious. You need to meet my pa. He will tell you everything!}
{281}{029}{I see. Tell me about Daniel.}
{282}{010}{Another question then.}
{283}{999}{Okay, I'll go talk to him.}

#Node029
{290}{}{[Arsene starts enthusiastically gesturing, his eyes are burning] Daniel is such a cool dude! My man! We're, like, best friends! We are rocking this place so hard! Like others wouldn't dare to! }
{291}{030}{And what is it that you do, exactly?}
{292}{039}{I've heard that Daniel is going to be a new Mayor of NWO.}

#Node030
{300}{}{We are doing all kinds of things together. Everyone's, like, talking about us. We are the most famous in all NWO! We, like, had a hand in every matter.}
{301}{031}{Did you have a hand into Lavash food pen too?}
{302}{032}{Tell me about something you did.}
{303}{010}{I want to ask more.}

#Node031
{310}{}{[Arsene smiles] Oh, you, like, figured it out already! Yes, it was us! I came up with, uh, an idea - to water down the Lavash food mix with machine oil or something. We already did the same with canned food a couple of times!}
{311}{021}{You shouldn't have done it, really. Lavash refuse to eat now. At all. Philip will be very pissed.}
{312}{021}{Yeah? Are you really this dumb? I think you should be assigned the job of Philip's assistant.}

#Node032
{320}{}{[Arsene mysteriously smiles] Lately, we were working, uh, very hard on the food problem in NWO. Our latest development is a secret stew! We are, like, just made one. Want some?}
{321}{034}{Sounds tempting. Okay, let's try it!}
{322}{033}{What is it made of?}
{323}{010}{I'm not very hungry now. Let me ask something else.}

#Node033
{330}{}{[Arsene's smile becomes even more mysterious] Oooh, that's, like, a big secret. I'm sure you, uh, never tried something like this, hehe. So, do you wanna try?}
{331}{034}{Okay! Let's try your stew.}
{332}{010}{No, I won't take such risks. Let me ask something else.}

#Node034
{340}{}{[Arsene gives you a bowl filled with greyish-brown gruel. You fail to determine by smell what is it made of. Looks like he is right - you've never eaten something like this] Here you go!}
{341}{035}{[Try it]}
{342}{010}{You know, I changed my mind. Looks not very tasty. Let me ask a question instead.}

#Node035
{350}{}{[You try the mysterious stew. It tastes not very good, although you've had worse. While eating, you sometimes pick from your teeth some obscure scales and thick little fragments. Still, the stew turned out to be very nutritious, so you feel recovered. Arsene carefully observes you] So? Like, tasty? How is it?}
{351}{036}{Not bad, actually. I liked it.}
{352}{036}{Not very tasty, but very nutritious.}
{353}{037}{It tastes awful. But I feel full, that's good.}

#Node036
{360}{}{Great! Now about the secret recipe! It's like, a stew made of four-tails!!}
{361}{038}{From what?! You mean these little insects in the piles of manure??}

#Node037
{370}{}{Taste is not really important, if it's, uh, nutritious. Now about the secret recipe! It's like, a stew made of four-tails!}
{371}{038}{From what?! You mean these little insects in the piles of manure??}

#Node038
{380}{}{Yeah! We came up with the recipe! There's a lot of them around here, so you can feed the whole NWO! By the way, you are the first ever to try this stew. Like, congratulations.}
{381}{010}{Cool. I need to learn how to cook it. Let me ask another question.}
{382}{999}{I really need to go pump my stomach... See you!}

#Node039
{390}{}{Yeah, Daniel is going to be in charge here. He would do great as a Mayor. Me and pa will help him. We are, like, going to make some changes around here. Big ones! But Mark doesn't, uh, trust Daniel much. Mark doesn't understand. So we came up with, like, a plan - Daniel is going to act he is good, and when he becomes Mayor - will do what he wants! }
{391}{010}{I see. I'll keep that in mind. Another question.}

#Node040
{400}{}{[Some guy in dirty clothes waves to you] Hey, wait! I've heard that you, like, asking around about Daniel. Don't side with Mark right away! Daniel is going to be a great Mayor! Come, uh, talk to me later.}
{401}{999}{Huh. Okay.}

#Node041
{410}{}{[Arsene waves to you] Hey, wait! I've heard that you, like, asking around about Daniel. Don't side with Mark right away! Daniel is going to be a great Mayor! Come, uh, talk to me later.}
{411}{999}{Okay...}

{420}{}{[Arsene looks at you, opens his mouth to say something, but suddenly interrupts himself] It doesn't really, like, matter now, right? Nevermind.}
{421}{010}{Okay, let's talk about something else.}
{422}{999}{See you around then.}
