##############################
#Локация: НМП
#Имя: Бак
#Краткое описание: Начальник охраны НМП
#Дата создания: 28.05.2014
##############################
#Для игры "Олимп 2207"
#Сергей "Zoomer" Бокарев
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a big man. He is smiling.}
{2}{}{Despite his size and age, he looks lively and dashing.}
#
# после знакомства
{3}{}{You see Burns.}
{4}{}{He is smiling at you. As usual.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
#Node001
{10}{}{[Yo see a massive man in his thirties. He is smiling through a huge mustache, rubbing his old machinegun.] Whoa! Suddenly, we have someone new-and-screwed here!}
{11}{002}{Do you know what "lexical reduplication" means?}
{12}{007}{Hello to you too, old-and-bold.}
{13}{998}{You are practically a king of jokes. Want me to shove your crown up your ass?}
{14}{011}{[don't say a word, drilling him with your stare]}
{15}{008}{Not funny.}
{16}{011}{[start to laugh loudly. When the joker laughs as loud as you, stop and stare at him with a stone face.]}

#Node002
{20}{}{Redu... What?}
{21}{003}{...plication. Your jokes correspond to the level of your intellect. I must say, it's quite low.}
{22}{006}{...plication. Nevermind. I got my joke. I'm }
{23}{006}{.}

#Node003
{29}{}{[his face becomes serious, he is silently looking right into your eyes. You have a feeling that his nostrils are about to let off some steam.]}
{30}{004}{Relax, man. Just take it a little easy on jokes. If it was somebody else, I'd already started a fistfight. But I see that you are quite alright. Peace? I'm }
{31}{004}{.}
{32}{998}{In fact, you look just like your jokes - like shit.}


#Node004
{40}{}{[he slightly calms down, although he isn't smiling anymore] The name's Burns. I'm the head of security around here. The kind of guys who can convince you that you are wrong and want to do the right thing. Hehe. [he grins]}
{41}{005}{Oh, you mean your low-ranking hominids, like you?}
{42}{010}{I came here recently and have some questions. Of course, if the head of security can spare some time to answer them.}

#Node005
{50}{}{F- What?! }
{51}{010}{Nevermind. I came here recently and have some questions. Of course, if the head of security can spare some time to answer them.}
{52}{998}{I'm saying that you are a retarded ape.}

#Node006
{60}{}{I'm Burns. I'm the head of security in NWO. }
{61}{010}{I'm new here. I'd like to ask some questions.}

#Node007
{70}{}{I see you are a funny guy too? I think we'll get along just fine.}
{71}{008}{That was sarcasm, actually.}
{72}{006}{Yeah, kinda.}
{73}{009}{No, I'm not funny. And you are not very funny too.}
{74}{006}{I hope so. And you are... }

#Node008
{80}{}{Yeah? Oh... Screw it then. I'm Burns, the head of security in this wonderful town.}
{81}{010}{I'm new here. I'd like to ask some questions.}

#Node009
{90}{}{[he gets silent] My name is Burns. I'm in charge of the town's security. }
{91}{010}{Uh-huh. Okay. I hope the head of security has some time to answer my questions?}

#Node010
{1001}{}{Hello there! What do you want?}
{1002}{}{Come on, get it on. What do you want to know?}
{1003}{}{Mark said that you are his successor now. And I think it is a wise choice. You can count on me.}
{1004}{}{Boss? Did you want something?}
{101}{013}{What can you say about this place?}
{102}{014}{Tell me about locals.}
{103}{035}{You must be thinking that you are a great joker.}
{104}{045}{I've heard that Mark is going to put Sam in charge of NWO. What do you think about it?}
{105}{999}{Nice talking to you, but I need to go.}

#Node011
{110}{}{[he hesitantly stares at you, waiting for your answer.]}
{111}{012}{I would be VERY grateful if you saved your hilarious jokes for your mom. And if you could talk not like a five-year-old child, that would also be great. I'm }
{112}{012}{.}
{113}{006}{Okay, I'll introduce myself first. I'm }
{114}{006}{.}

#Node012
{120}{}{You wouldn't make it here without jokes. Don't listen, if you don't like it. I'm Burns, the head of security.}
{121}{010}{I'm new here. I'd like to ask some questions.}

#Node013
{136}{}{[Burns points below his belt] I can tell you about THIS place for sure, haha!! Okay, this town is called NWO, short for New World Order. We live peacefully and quietly, like in Lavash's ass. And I'm responsible for it to continue to be that way.}
{130}{}{I won't tell you anything new, boss. If only you are not interested in local catfights.}
{131}{014}{Tell me about NWO's locals.}
{132}{022}{What can I do around here?}
{133}{010}{Another question.}
{134}{999}{Good. You know, I need to go now.}

#Node014
{140}{}{I don't like to brag about others, except the ones who got caught with his pants down between the legs of some beauty, hahaha!! I'm Burns, I work for NWO's mayor. Now it's Mark, so for now - I work for him.}
{141}{015}{"For now"? Why, are you leaving?}
{142}{016}{Tell me about Mark.}
{143}{019}{Tell me more about yourself.}
{144}{010}{Another question then.}
{145}{}{I don't like to brag about others, except the ones who got caught with his pants down between the legs of some beauty, hahaha!! Actually, I don't have much to say. You'd better talk with everyone personally.}
{146}{016}{Tell me about Mark.}
{147}{019}{Tell me more about yourself.}
{148}{010}{Another question then.}

#Node015
{150}{}{Hah, I'm leaving this place only when I'm dead, protecting Mayor! The thing is, his health is shittier than shit. His ass is one cheek in the grave, and soon there will be a new Leader in NWO. And I will protect the new Mayor until I die.}
{151}{016}{I want to learn about Mark.}
{152}{019}{Can you tell me about yourself?}
{153}{010}{I want to ask something else.}

#Node016
{1601}{}{Mark is our Mayor, I respect him the most. He is the hell of a man! He handles everything, without him, it would already be nothing here! But now he is sick and, unfortunately, soon will be counting the worms. And who knows what will NWO become after it!}
{1602}{}{Mark is our Mayor, I respect him the most. He is the hell of a man! Too bad he's leaving his post... But such times. I hope that you, boss, will be as good as him.}
{1603}{}{Mark is our Mayor, I respect him the most. He is the hell of a man! Too bad he's leaving his post... But such times. I hope that new management won't screw things here with their rotten brains.}
{161}{017}{Who could become a new Mayor?}
{162}{018}{What would happen with NWO if there's no Mayor, or if there's someone unsuited for the position?}
{163}{010}{I want to ask something else.}

#Node017
{1701}{}{After Mark dies, his son Daniel should succeed him. But everybody says that Daniel is a wussie and a total moron, so I suppose there are some options... Listen, I was thinking that you could help me sort this shit out. I will protect a new Mayor in any case, whoever he would be. But every person has weaknesses, enemies, and such. So, I need to prepare. Try to find out who will succeed Mark. Talk to Mark himself, and ask others around here, what do they think about it. Will you do this for me?}
{1702}{}{Shit, that's what I want to know! I'd like you to talk to people and figure it out. Would you?}
{171}{010}{Probably not, I have a lot of things to do. I'd better ask a question.}
{172}{010}{Sure. I'll talk to Mark about his successor. And now - to other questions.}

#Node018
{180}{}{NWO will quickly descend into the depths of the same ass from which Mark tried to pull it out the most of his life! The town will drown in Lavash shit and dissolve in it, like a piss in the river.}
{181}{017}{Who would be better as Mayor and won't let that happen?}
{182}{010}{Sounds like quite a grim future. I'd like to ask another question.}

#Node019
{195}{}{[Burns's smile covers most of his face] What can I say! I'm the head of security, always ready to kick ass for a crime or just because, hahaha!! People call me Burns, it's my moniker. I will tear off the balls of anyone who dares to threaten Mayor, and I'm ready to die protecting his ass!}
{190}{}{[Burns's smile covers most of his face] What can I say! Despite being the head of security, I'm always ready to kick ass for a crime or just because, hahaha!! If you didn't hear, people call me Burns. It's my moniker. I will tear off the balls of anyone who dares to threaten you, and I'm ready to die protecting your ass!}
{191}{020}{Are you really willing to do anything for Mayor?}
{192}{021}{How did you get your moniker?}
{193}{023}{How did you become the head of security?}
{194}{010}{Okay, let me ask another question.}

#Node020
{200}{}{[Burns becomes serious. His eyes glow with steel] I'll tear a new one to anyone who plans to hurt Mayor. I'll cover him from bullets with my chest if I have to. And let me be buried together with previous Mayors, as the most loyal to the very end. Even if everyone in the Radius wage war on us, I'll be in the front row, murdering these bastards, until the last one of them dies! Let everyone know - Burns won't be hiding like some lousy rat!}
{201}{021}{Burns, why do people call you that?}
{202}{010}{I see. Let me ask another question.}

#Node021
{210}{}{[he twirls his mustache, pondering about the past] Man, it was so long time ago. I wasn't even the head of security back then. With some other guys, I had been walking around the Radius, doing all kinds of shit. Nothing special. And I had these beautiful sideburns, completed with an amazing mustache. Not one dick in the whole Radius had something like this! And one day, the smartest asshole around my fellas decided to take all the loot we had for himself. And planted a bomb into our campfire. I just went to take a piss when it detonated, so I guess I was lucky - all I got was a little scorched face and completely burned mustache and sideburns. I chased the bastard, unloading all my gun into his back. And I've been walking around with burned sideburns until they grew back. So, people started calling me sideburns, then it was shortened for just Burns. That's it.}
{211}{010}{What a story. I have other questions.}

#Node022
{220}{}{[Burns smiles and, without any threat in his voice, answers] If you do problems, you could end up catching a bullet with your forehead. And If you behave, just like Lavash after copulation, then you'll be safe. People even could like you here. You don't look like Lavash herder or factory worker type, so you probably won't be interested in this boring and shitty kind of job. Maybe some of the folks would ask you to do something they are afraid to do themselves.}
{221}{010}{I won't cause problems then. Another question. }
{222}{998}{Now you're getting a bullet in your head!}
{223}{999}{Okay, I'll go talk to others about work.}

#Node023
{230}{}{[Burns flexes his muscles] Very fast and easy, haha!! When I arrived here, there was another head of security. A wuss and sucker. He was shot down in front of me by some dickhead asshole, from this exact machinegun. That asshole's next move was to send the Mayor to heaven's ass, but I interrupted his plan by beating the shit out of him with my bare hands. Took the gun as a souvenir. And that's when Mayor offered me to work for him. Of course, there were other candidates for my position, but none of them could kick my ass. So there.}
{231}{025}{You don't look too strong, you know.}
{232}{024}{Yeah, I see. You look pretty strong. I wouldn't like to squabble with you.}
{233}{010}{I see. Let me ask something else. }

#Node024
{240}{}{[Burns smiles even more. He is definitely flattered] Yes, I am!! But don't be afraid, I won't pick fights with you. I don't beat up the weaker ones, haha!!}
{241}{025}{Although, scratch that, you actually don't look that strong.}
{242}{010}{Yeah, no fights then. I want to ask something else.}

#Node025
{250}{}{[he instantly gets fierce] WHAT??? You... Fucking milksop!! I will tear your ass into pieces with my one hand!! One punch from me will make you lay down!! Didn't have your face beaten up lately?! }
{251}{026}{One punch will make me lay down? I really doubt that. Wanna bet?}
{252}{998}{You are making me sick already. It is I who is going to tear your ass, right now!}
{253}{010}{Come on, calm down. It was a joke. I'd better ask a question.}
{254}{999}{Come on, calm down. It was a joke. I'd better go wait for you to calm down. I don't want to quarrel with you.}

#Node026
{260}{}{[His eyes are flashing with excitement] A bet? Sure! Don't forget to put down something soft, so you could sleep comfortably when you fall! Don't worry, I'll punch carefully, so I wouldn't break something. Handle one blow - and you win, drop down - and I win. Are you in, or your knees are trembling too much? Haha!!}
{261}{027}{Let's do it! What we are going to bet with?}
{262}{010}{Nah, I don't really feel like getting punched in the face. I'd like to ask something.}
{263}{999}{Uh, no, thank you. I'd better go.}

#Node027
{270}{}{Whatever. I don't care. Let's bet a noogie!}
{271}{028}{Hah! Okay! Go!}
{272}{010}{To get my face punched for a noogie? No way in hell. I better ask something.}

#Node028
{280}{}{Hahaha! Here we go!!}
{281}{999}{[brace yourself for a punch]}

#Node029
{290}{}{[You barely managed to keep yourself on your feet, your head is buzzing - but you are standing. Burns looks at you with respect] Hah, aren't you a tough one? Well, looks like I lost. Give me a noogie, I deserved that.}
{291}{032}{[You concentrate all of your strength and give Burns a noogie]}

#Node030
{300}{}{[You fall on your back after a powerful blow. You see flashes, you almost pass out. Burns hoarsely laughs] Hahaha!! I told you that you will fall, like a pushed Lavash!! Now - here's your noogie!}
{301}{033}{[You concentrate all of your remaining strength to take a noogie]}

#Node031
{310}{}{[You fall down and pass out. You come to your senses in a few minutes, Burns looks concerned] Phew, it's good that you are alright. I began to think that you're done for. Okay, no noogie for you, I think you had enough.}
{311}{034}{[You concentrate all of your strength to just get up]}

#Node032
{320}{}{[Burns doesn't react at all. Looks like your finger hurts more than he is] That's it? Hahaha!!! Okay, it was great.}
{321}{010}{Yeah, just wonderful. I want to ask something else.}
{322}{999}{Agreed, that was great. I need to come to my senses, let's talk later.}

#Node033
{330}{}{[His noogie almost knocks you over. Burns hoarsely laughs] That's it? Hahaha!!! Okay, it was great.}
{331}{010}{Yeah, just wonderful. I want to ask something else.}
{332}{999}{Agreed, that was great. I need to come to my senses, let's talk later.}

#Node034
{340}{}{[Burns helps you to get up. Then he hoarsely laughs] Hahaha, you almost died!! Still, that was great.}
{341}{010}{Yeah, just wonderful. I want to ask something else.}
{342}{999}{Agreed, that was great. I need to come to my senses, let's talk later.}

#Node035
{350}{}{[he looks offended] That's how it is! I'm the funniest guy here! Not like that boring shits around. I can make a joke about anything!!}
{351}{036}{I bet you can't. What if I give you a word? Would you make a joke about it? Maybe, a rhyme?}
{352}{010}{Yes, looks like you are the funniest guy. I want to ask something else.}

#Node036
{360}{}{[he starts shouting] Yeah! Come on! Give me a word and I'll rhyme so hard that you'll tear your ass from laughing! Let's bet on a noogie!}
{361}{037}{Let's do it! I'll give you a word...}
{362}{010}{Nah, I don't want a noogie. Let me ask something else.}


#Node037
{370}{}{[Burns is rubbing his hands, awaiting for your word]}
{371}{038}{Rifle}
{372}{042}{Lavash}
{373}{039}{Triangle}
{374}{043}{Ass}
{375}{044}{Transcendence}
{376}{040}{Battery}
{377}{041}{Bottle}

#Node038
{380}{}{Rifle, rifle, shooting is delightful! Hahaha!! Here's a noogie!}
{381}{033}{Uhhh...}

#Node039
{390}{}{Triangle, triangle, my dick is phalangal! Hahaha!! Here's a noogie!}
{391}{033}{Uhhh...}

#Node040
{400}{}{Battery, battery, making me flattery! Hahaha!! Here's a noogie!}
{401}{033}{Uhhh...}

#Node041
{410}{}{Bottle with a model, ended in a brothel! Hahaha!! Here's a noogie!}
{411}{033}{Uhhh...}

#Node042
{420}{}{Lavash, oh gosh, I'm not going to wash it! Hahaha!! Here's a noogie!}
{421}{033}{Uhhh...}

#Node043
{430}{}{[Burns is confused] Uhhh... Damn, ass is fine as it is! I don't know what to say...}
{431}{032}{Hah, so you lose! Here's a noogie!}

#Node044
{440}{}{[Burns is confused] Uhhh... What? What the hell is this shit? I don't know what to say...}
{441}{032}{Hah, so you lose! Here's a noogie!}

#Node045
{450}{}{[Burns starts twirling his mustache] Hmm, Mark is a really smart-ass Mayor. I think good old Sam is the best possible option, even if he stinks like Lavash ass. Sam is an experienced leader, he started it all here. Mark, you son of a bitch, that is a great idea!}
{451}{999}{I see you don't mind. Okay, I need to go, bye.}