##############################
#Локация: НМП
#Имя: Бланка
#Краткое описание: Подружка Сайрена
#Дата создания: 02.10.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see an incredibly sexual woman.}
{2}{}{She looks very erotic in these clothes.}
#
# после знакомства
{3}{}{You see Blanca.}
{4}{}{Looking at her you have a sudden urge to find a nearest brothel.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You get a flirty smile from a girl with a perfect figure. Thin waist, amazing legs, breast, ideally fitting into a man's palm...] Hello, handsome! I don't think we've met before. I'm Blanca. Did you see Cyren, by any chance?}
{11}{002}{Yes, I saw him by the entrance, he was pretty busy. Why don't you tell me about this town?}
{12}{012}{Yes, I saw him by the entrance, he was pretty busy. I'm here on an important mission, by the way [wink at her].}
{13}{014}{Maybe I did. By the way, I have some business here concerning...}
{14}{015}{Maybe I did. Is this hole a good place to get lost?}
{15}{016}{Maybe, but it doesn't matter! I carry the holy word into masses! I...}
{16}{999}{I have no time for petty talks! I need to run, do things!}

{20}{}{This pen with dirt and shit is called New World Order. There's absolutely nothing interesting here. Well, maybe except one... One diamond in the pile of trash. His name is Cyren!}
{21}{003}{Where did the name of this town come from?}
{22}{006}{You can find something interesting anywhere, this place is no exception.}
{23}{008}{Who is Cyren?}
{24}{013}{If there's nothing interesting around, why are you here then?}
{25}{999}{I want to explore this town on my own. Talk later.}

{30}{}{How could I know! I'm not littering my head with nonsense! New World Order, and that's it.}
{31}{004}{Who could I ask about it?}
{32}{007}{What can you tell me about the town?}
{33}{013}{What do you do here?}
{34}{005}{Who is in charge here?}
{35}{999}{I'll go look for somebody who knows more.}

{40}{}{Probably, rotten Sam can tell you about it [she shrugs, and you can't help but think how beautiful her shoulders are]. He knows many things.}
{41}{018}{Who is that Sam you are talking about?}
{42}{017}{Why "rotten"?}
{43}{007}{What can you tell me about the town?}
{44}{005}{Is Sam in charge here?}
{45}{999}{Okay, I'll go ask Sam. Bye.}

{50}{}{I don't know who is in charge now. I think Mark is the Mayor. Or Daniel. Or Sam. Listen, I'm not very interested in all this stuff. Maybe even you are in charge. I could care less.}
{51}{006}{What are you interested in then?}
{52}{019}{Who's Mark?}
{53}{020}{Daniel? Who is it?}
{54}{018}{Tell me about Sam.}
{55}{009}{Do you realize that I am actually the Mayor of NWO?}
{56}{999}{I'll go talk to someone of them.}

{60}{}{Only one thing is interesting in this place - Cyren! Nothing else!}
{61}{008}{Yeah? Why?}
{62}{007}{Is there something important except Cyren?}
{63}{013}{What are you doing here, if there's nothing else? }
{64}{010}{I'd like to know more about some things.}
{65}{999}{I'll go look for this local celebrity then.}

{70}{}{All this place has to offer is Lavash, canning factory and piles of shit. And the crowd of morons. They spend all day working on a factory, like a bunch of slaves. Live only with their job. They disgust me, all of them... except Cyren.}
{71}{013}{So, what are you doing in this dump?}
{72}{005}{Who is in charge of all this?}
{73}{008}{Who is that Cyren?}
{74}{010}{I have some questions.}
{75}{999}{This town must be really boring. I'd better get out of here.}

{80}{}{[her eyes are flashing, she starts actively gesturing] Cyren is the best man in the whole Radius! He is humble, but everyone knows he is a hero! Even the last vagabond knows about his deeds! Cyren is the scout of highest tier!!}
{81}{011}{What deeds did he do?}
{82}{023}{I can see you're crazy about him.}
{83}{010}{Okay, let's talk about something else.}
{84}{999}{I need to see him. I'll go find him.}

{90}{}{[she is loudly laughing] Oh, come on! Do you really think there's something to be proud of? You are the Mayor of stinking dump! [she takes a serious look and bows] What would you like, oh lord Mayor Commander?}
{91}{013}{If this town is a dump, what are you doing here?}
{92}{021}{I can banish you from the town.}
{93}{010}{Okay, let's change the subject.}
{94}{022}{To be in cnarge of such place is a great responsibility. Not everyone could handle it.}
{95}{999}{I have a lot of important things to do and no time to chat, so - bye.}

{1001}{}{Hello, handsome! Always glad to talk to you! What do you want to know this time?}
{1002}{}{[Blanca is playing with her beautiful locks of hair. She gives you a cute smile, biting her lower lip] So, what do you want to talk about?}
{101}{005}{Who's in charge here?}
{102}{008}{Tell me about Cyren.}
{103}{013}{What are you doing here?}
{104}{003}{Where did the name of this town come from?}
{105}{038}{I have found the toy for you to take some edge off.}
{106}{999}{Actually, I've got to go. Bye.}

{110}{}{[Blanca gets overwhelmed with emotions, she almost jumps, clapping her hands. Her eyes filled with endless passion] He is a true hero! He got himself out of many really bad situations, always coming out on top!! One day, Cyren single-handedly saved the whole village from Jackals! And there was a time when he got ambushed by a pack of scorpions and killed them all!! He even saved me from a Chimera once! And he stopped an assault on NWO! And prevented the contamination of groundwater! And you should hear abour him dealing with a huge, three-meter tall murderous robot! That's just fantastic!!}
{111}{024}{Saved the village from Jackals? I'd like to know more about that.}
{112}{025}{The scorpions are pretty dangerous. How did he manage to handle them?}
{113}{026}{Tell me about him saving you from a Chimera.}
{114}{027}{What's the story about assault on NWO?}
{115}{028}{Groundwater contamination? Tell me more.}
{116}{029}{How did he deal with a murderous robot?}
{117}{010}{This is all very interesting, but let's talk about something else.}
{118}{999}{Oh wow! I'll go talk to him personally.}

{120}{}{Then you should understand that you came into NWO for nothing. Because it's nothing here. Nothing interesting. Only if your important mission doesn't involve Cyren in some way.}
{121}{006}{You can find something interesting anywhere, this place is no exception.}
{122}{013}{If there's nothing interesting around, why are you here then?}
{123}{008}{Who is Cyren?}
{124}{003}{Where did the name of this town come from?}
{125}{999}{My mission actually involves Cyren, so I'll go look for him.}

{1301}{}{I'm here temporarily. I came here together with Cyren. And when he is away, doing his heroic deeds, I wait for him. Only it's quite boring, nothing to do at all... Especially during long, lonely nights... [she sensually sighs] Without Cyren I'm cold, alone and sad...}
{1302}{}{I'm here temporarily. I came here together with Cyren. And when he is away, doing his heroic deeds, I know how to deal with loneliness. You bet I know. [she winks at you]}
{131}{008}{Tell me about Cyren.}
{132}{030}{I can make you feel less lonely, while Cyren is away.}
{133}{010}{I want to ask something else.}
{134}{999}{You know, I need to go. Bye.}

{140}{}{I know, I know! The only one in this place who can be involved in some business is Cyren! Except him, here, in New World Order, there is nothing interesting or important.}
{141}{008}{Who is Cyren?}
{142}{013}{Why are you here then?}
{143}{006}{You can find something interesting anywhere, this place is no exception.}
{144}{003}{Where did the name of this town come from?}
{145}{999}{Yes, he is the one I'm looking for. I'll go talk to him.}

{150}{}{Yes, you'll fit right in. It's a big boring hole, called New World Order. And yes, this is the place where no one is going to look for you. But you can always talk to Cyren, if someone is threatening. He will deal with your pursuers in no time.}
{151}{008}{Who is Cyren?}
{152}{013}{Why are you here then?}
{153}{006}{You can find something interesting anywhere, this place is no exception.}
{154}{003}{Where did the name of this town come from?}
{155}{999}{Okay, I'll go talk to Cyren. Bye.}

{160}{}{[she looks displeased] No one here cares about some holy words. In the New World Order there's nothing interesting for your kind of people people. Cyren won't even talk to you.}
{161}{006}{You can find something interesting anywhere, this place is no exception?}
{162}{008}{Who is Cyren?}
{163}{003}{Where did the name of this town come from?}
{164}{999}{I'm still going to find this Cyren and bring him a holy word! }

{170}{}{Because Sam is a ghoul, and he rots! Get it? Cyren liked this joke so much! }
{171}{018}{Tell me about Sam.}
{172}{008}{Cyren? Who is that?}
{173}{010}{Yeah, good one. Let's talk about something else.}
{174}{999}{I need to go and think about my sense of humor. See you.}

{180}{}{Sam is the oldest of all NWO dwellers. He is a ghoul. And he smells a hundred feet away. I think he has something to do with the local management. So as his relatives, Mark and Daniel.}
{181}{005}{Who is in charge for the place?}
{182}{019}{Tell me about Mark.}
{183}{020}{What can you say about Daniel?}
{184}{010}{Let's change the subject.}
{185}{999}{I'll go talk to them. Bye.}

{190}{}{Mark lives with his wife, I-don't-remember-her-name, and Daniel. He is his son, or nephew, I don't care. Mark is always busy with some papers or something... Look, it doesn't matter. All that matters here is what Cyren does!}
{191}{008}{Tell me about Cyren.}
{192}{020}{Tell me about Daniel.}
{193}{005}{I suppose, it's Mark who is in charge here?}
{194}{010}{Let's talk about something else.}
{195}{999}{I should go talk to Mark. See you.}

{200}{}{Daniel is Mark's son - or nephew, I don't remember. They are related to Sam, I think. And he is busy with something about running the town... I don't care. The real men, like Cyren, are not involving themselves into petty politics. }
{201}{008}{I want to learn more about Cyren.}
{202}{005}{Maybe Daniel is in charge here?}
{203}{019}{What can you tell me about Mark?}
{204}{018}{Tell me about Sam.}
{205}{010}{I'd like to talk about something else.}
{206}{999}{I'll go find Daniel and talk to him. Bye.}

{210}{}{Hah, you think you scare me? I can leave at any second! So don't threaten me with nothing. Go do your Mayor thing somewhere else.}
{211}{010}{Okay, you can stay. Let's talk about something else.}
{212}{998}{As a Mayor of NWO, I condemn you to death for disobeying me! The sentence will be carried out immediately!}
{213}{999}{You are right, I have a lot of things to do. No time talking to you. Bye.}
{214}{070}{What? What did you just say?! [Grab her by the hair and pull to the side, putting a leg to trip her over]}

{220}{}{Yes, it must be really hard, to be a king of dump. [she giggles] Mayor... Yeah, sure. Cyren is no match for you anyway! He is so far ahead of you as the Olympus tower from here!}
{221}{008}{What's with this Cyren?}
{222}{010}{Alright then. I wanterd to ask something else.}
{223}{999}{You don't know anything. It's time for me to go do great things.}
{224}{070}{What? What did you just say?! [Grab her by the hair and pull to the side, putting a leg to trip her over]}

{230}{}{[she closes her eyes and smiles] Oh yeah! I'm so crazy about him! He is so awesome, a real man! I fell for him at the first sight. And he, by the way, risked his life for me! A true hero, doing great deeds.}
{231}{011}{Tell me about his deeds.}
{232}{010}{I don't have time for heroics now. I want to ask something else.}
{233}{999}{Let's talk later. I have urgent things to do.}

{240}{}{That is a very fascinating story! One time, Cyren and his partner went on a mission to somewhere near the Rainbow, and walked into some settlement to get rest and resupply. They were already going to have lunch in one of the homes, when they heard screaming from the streets. Cyren ran outside and found out that the village was attacked by Jackals! There were no less than twenty of them, and Cyren had only a spoon in his hand, with all his stuff left inside the house. Despite that, he threw himself at enemy, killing them one by one!! Jackals ran off, so Cyren have been chasing them for several following days, killing every last one. Unfortunately, everyone in that village turned out to be dead, including his partner, and everything else - burned to the ground, including his equipment. So, Cyren came back with only a spoon, every witness of his doings - dead.}
{241}{025}{Tell me about scorpions and ambush.}
{242}{026}{Can you tell me about saving you from Chimera?}
{243}{027}{How did he stop an assault on NWO?}
{244}{028}{Tell me about him preventing the pollution of groundwater. }
{245}{029}{You were saying something about a murderous robot. Tell me about it.}
{246}{010}{Very interesting. But let's talk about something else.}
{247}{999}{I'd like to meet him in person. I'll go find him.}

{250}{}{In this story, Cyren demostrated his great skill and endurance. One day, Cyren and his partner ended up into a narrow mountain passage. Everything was very silent, Cyren immediately suspected that something is wrong. Suddenly, swarms of scorpions launched attack on them, coming from both sides, from the top, crawling from under the cliffs and stones! Cyren even got stung in a leg by one of this filthy creatures! But he didn't get scared - he grabbed nearest scorpion, ripped off his tail and started to sting other scorpions with it!! And he fended them off until none left. Only after that he bandaged his leg - he survived a dose of poison which was twice the lethal! Unfortunately, his partner died almost instantly. Cyren got back in a few days, brought tail with him, and showed everyone the leg wound, which healed and was looking like a little scratch!}
{251}{024}{Tell me about Jackals and settlement.}
{252}{026}{You were saying that he saved you from Chimera. Tell me about it.}
{253}{027}{How did he stop an assault on NWO?}
{254}{028}{Tell me about the pollution of groundwater.}
{255}{029}{How did he deal with a murderous robot?}
{256}{010}{Very interesting. But let's talk about something else.}
{257}{999}{I'd like to go look at his wound. I'm very interested.}

{260}{}{This one is my favourite! That's when I met Cyren and fell in love with him. It all started on a Rainbow, where I lived and worked. Women there have only one work, you know. I didn't mind it - no need to think much, and I became pretty good at my duties. But one time, some client started chasing me to beat me up, so I ran away. I wandered around the desert for some time, before I fell exhausted near some stone. That's where Cyren found me. He was incredible! He woke me up, shared his food and offered help. Then he pulled me aside and showed me a Chimera's corpse - he killed her while I was unconscious. She could eat me in my sleep! This Chimera smelled like a Lavash who has been dead for a week... I get goosebumps even thinking about it. So, I thanked Cyren in the way they taught me in Rainbow. We've been together since. }
{261}{024}{What's the story about settlement and Jackals?}
{262}{025}{Tell me about scorpions and ambush.}
{263}{027}{You were saying that he stopped an assault on NWO. Tell me about it.}
{264}{028}{Tell me about him preventing the pollution of groundwater.}
{265}{029}{What were you telling about a murderous robot?}
{266}{010}{I get it, Cyren's really good. Let's talk about something else.}
{267}{999}{I'll go talk with Cyren about the details of hunting the Chimeras.}

{270}{}{That's when Cyren acted like a true hero! He didn't even tell anyone about this one, because he is very humble. That's how it was: Cyren was absent for a few days. Then he returned, and started doing his usual business, as if nothing happened. But later, people started talking that some huge battle took place, not very far away from here. They suggested that two rival gangs had fought over something, with heavy casualties from both sides. But then Cyren told everyone the truth - actually, two gangs wanted to join forces to attack the NWO. And Cyren decided to meet them on their way to the town. He stormed into a crowd of enemies and killed them all! And he didn't want to cause panic in the NWO, so he kept it silent. He didn't even want to show where the battle took place! Everyone here is in a great debt to him!}
{271}{024}{I want to hear about Jackals and settlement.}
{272}{025}{Tell me about scorpions and ambush. How he managed to get out of that?}
{273}{026}{You were saying that he saved you from Chimera. How did it happen?}
{274}{028}{Tell me about him preventing the pollution of groundwater.}
{275}{029}{How did he deal with a murderous robot, I wonder?}
{276}{010}{The dwellers should really worship him, or something. Let's talk about other things.}
{277}{999}{I'll go talk to Cyren about dealing with superior enemy forces.}

{280}{}{This is a story where he saved the whole Radius from dying out! Cyren and his partner went scouting to the farthest reaches, near Tin Industries. And they stumbled upon some scientist on the way. That scientist turned out to be a total psycho - he wanted to destroy all life in Radius! Cyren decided to prevent it, and talked the scientist into trusting him. So, the psycho's plan was to pollute all groundwater with toxic waste, left from before the War. He even showed his barrels with waste! And Cyren burned them, together with the scientist! Unfortunately, his partner died too, inhaling all the poisonous fumes. Later, Cyren showed everyone the pile of rusty battels and two skeletons near them. He definitely saved the whole Radius! }
{281}{024}{Tell me about Jackals and settlement.}
{282}{025}{I want to hear about scorpions and ambush.}
{283}{026}{Tell me about him saving you from Chimera.}
{284}{027}{How did Cyren stop an assault on NWO?}
{285}{029}{I want to know about the fight with a murderous robot.}
{286}{010}{Very interesting. But let's chang the subject.}
{287}{999}{I'll go thank him. See you around.}

{290}{}{This is one of the most incredible stories! While traveling around Radius, Cyren bumped into a three-meter tall murderous robot, who was destroying everything in his way. This was some unusual robot - he was repeating that he needs to kill someone named "Sacon", but the flaw in programming made him hostile to everything he sees. Cyren engaged robot in a deadly fight, ripping off robot's hand in the process - which didn't stop him, by the way, as robot continued to fight. It ended only when Cyren took down a huge mountain cliff upon his enemy. As a souvenir, Cyren brought some rusty cogs with him. He will never forget the fading red eye of the robot...}
{291}{024}{Tell me a story about the settlement and Jackals.}
{292}{025}{I want to hear about scorpions and ambush.}
{293}{026}{How did he save you from Chimera?}
{294}{027}{Tell me about an assault on NWO.}
{295}{028}{How did he prevent the pollution of groundwater?}
{296}{010}{That's really impressive. But I want to talk about something else.}
{297}{999}{I need to go take a look at these cogs. See you later.}

{300}{}{[Blanca looks at you with interest] I doubt you'd compare to Cyren, handsome. He is a remarkable hero not only when dealing with crowds of enemies, you know. [she winks]}
{301}{033}{I just want your time away from Cyren to be more pleasant and easy.}
{302}{034}{I just want your time away from Cyren to be more pleasant and easy.}
{303}{031}{I just want your time away from Cyren to be more pleasant and easy.}
{304}{032}{I just want your time away from Cyren to be more pleasant and easy .}

{310}{}{Sorry, handsome. I don't think it could work for us.}
{311}{010}{Too bad... Okay, let's talk about something else then.}
{312}{999}{You don't know what you're missing! That's it, I'm leaving.}

{320}{}{[Blanca looks at your crotch. No, actually she STARES at your crotch for long ten seconds. You feel strange.] I will take a guess that it's too big for me. Sorry, pretty boy. No chance.}
{321}{999}{Too bad... I'll go ponder about my size...}

{330}{}{Sorry, handsome. I don't think it could work for us. [she gives you evaluating look] But I have something to ask you, a favor. While in Rainbow, I took notice that the guys with black skin are quite experienced in... Private matters. Lately, I feel that my passion is overwhelming me, waiting to come out. I need to, uh, take care of it, you know what I'm saying? Can you do something for me?}
{331}{035}{What do you want me to do?}
{332}{010}{I don't think I'm interested in this. Let's change the subject.}
{333}{999}{You know, I'm actually in a hurry. See you later.}

{340}{}{[you see flashes in her eyes] It's actually a good idea... Come around when Cyren is away, we'll try to work it out. And I have something to ask you, a favor. While in Rainbow, I took notice that the guys with black skin are quite experienced in... Private matters. Lately, I feel that my passion is overwhelming me, waiting to come out. I need to, uh, take care of it, you know what I'm saying? Can you do something for me?}
{341}{035}{I will definitely come by. What do you want me to do?}
{342}{010}{I will come around, sure. But now I'm a little busy to help you. Let's change the subject.}
{343}{999}{No, I'm in a hurry and already leaving. But I'll come by when Cyren is away.}

{350}{}{Okay. The girls in Rainbow told me a rumor about device somewhere in Livos, which could help me to... Take some edge off, during the lonely nights.}
{351}{036}{Yes, I know about the device to take some edges off. It's called trimmer.}
{352}{037}{Go on.}

{360}{}{[Blanca gives you a blank stare for a couple of seconds - and then expodes with laughter, holding on to her belly.] Ahahahaha, oh, wow!! That was good! I haven't had this much fun in a long while. Looks like I already let off some steam, even without a device. Thank you for helping me with this. I will even give you a present - here, it's something Cyren brought from one of his missions. Looks like he forgot about it.}
{361}{010}{Great. Let's talk about other things.}
{362}{999}{You're welcome. But I need to go now, see you.}

{370}{}{So, if you get me this... Device, so I, uh... Could take some edge off, I'll give you a nice gun in exchange.}
{371}{010}{Okay, I'll keep an eye out for it. Let's talk about something else.}
{372}{999}{I'm not into looking for some questionable devices. I need to go, to do more important things.}

{380}{}{Oh, what a beautiful thing! Will you teach me how to use it? Come on, let's give it a try!}
{381}{039}{Okay, let's do it.}
{382}{999}{No way, I didn't sign up for this. I have a things to do, you know.}

{390}{}{[You spend some time, studying manual and techology of the process. Then you put the device to the point of application and get to taking some edge off.]}
{391}{041}{[turn the device on]}
{392}{040}{[give up trying]}

{400}{}{...It didn't work out. Let's try again, maybe?}
{401}{039}{Sure, let's do it.}
{402}{999}{No, I've had enough.}

{410}{}{[The device emits a buzzing sound and vibrates.]}
{411}{044}{[use the device capabilities on a quarter of its length]}
{412}{043}{[use the device capabilities on a half of its length]}
{413}{043}{[use the device capabilities on a three quarters of its length]}
{414}{043}{[use the device capabilities on its full length]}
{415}{042}{[turn the device off]}

{420}{}{What are you doing? I still haven't got the taste of all possibilities of the device! }
{421}{039}{Okay, let's try again...}
{422}{999}{That's it, I can't do it anymore. I need to go get some air.}

{430}{}{Ow! That's too fast! Go a little slowly!}
{431}{041}{[return the device in its initial position]}
{432}{042}{[turn the device off]}

{440}{}{[Blanca slightly smiles.]}
{441}{047}{[keep the device in this position for a while]}
{442}{045}{[turn the device 17 degrees up]}
{443}{047}{[turn the device 17 degrees down]}
{444}{047}{[turn the device 17 degrees right]}
{445}{045}{[turn the device 17 degrees left]}
{446}{043}{[use the device capabilities on a half of its length]}
{447}{043}{[use the device capabilities on a three quarters of its length]}
{448}{043}{[use the device capabilities on its full length]}
{449}{042}{[turn the device off]}

{450}{}{[No changes have been observed. Still a slight smile on her face.]}
{451}{047}{[keep the device in this position for a while]}
{452}{046}{[turn the device 17 degrees up]}
{453}{047}{[turn the device 17 degrees down]}
{454}{047}{[turn the device 17 degrees right]}
{455}{046}{[turn the device 17 degrees left]}
{456}{043}{[use the device capabilities on a half of its length]}
{457}{043}{[use the device capabilities on a three quarters of its length]}
{458}{043}{[use the device capabilities on its full length]}
{459}{042}{[turn the device off]}

{460}{}{[Only a slight smile on her face. Nothing has changed.]}
{461}{047}{[keep the device in this position for a while]}
{462}{045}{[turn the device 17 degrees up]}
{463}{047}{[turn the device 17 degrees down]}
{464}{047}{[turn the device 17 degrees right]}
{465}{045}{[turn the device 17 degrees left]}
{466}{043}{[use the device capabilities on a half of its length]}
{467}{043}{[use the device capabilities on a three quarters of its length]}
{468}{043}{[use the device capabilities on its full length]}
{469}{042}{[turn the device off]}

{470}{}{[The rhythms of respiration is increasing. Eyes closing.]}
{471}{048}{[keep the device in this position for a while]}
{472}{048}{[turn the device 17 degrees up]}
{473}{048}{[turn the device 17 degrees down]}
{474}{048}{[turn the device 17 degrees right]}
{475}{048}{[turn the device 17 degrees left]}
{476}{050}{[use the device capabilities on a half of its length]}
{477}{043}{[use the device capabilities on a three quarters of its length]}
{478}{043}{[use the device capabilities on its full length]}
{479}{042}{[turn the device off]}

{480}{}{[No changes have been observed: heavy breathing, eyes closed]}
{481}{049}{[keep the device in this position for a while]}
{482}{049}{[turn the device 17 degrees up]}
{483}{049}{[turn the device 17 degrees down]}
{484}{049}{[turn the device 17 degrees right]}
{485}{049}{[turn the device 17 degrees left]}
{486}{050}{[use the device capabilities on a half of its length]}
{487}{043}{[use the device capabilities on a three quarters of its length]}
{488}{043}{[use the device capabilities on its full length]}
{489}{042}{[turn the device off]}

{490}{}{[Eyes are still closed, breathing is heavy.]}
{491}{048}{[keep the device in this position for a while]}
{492}{048}{[turn the device 17 degrees up]}
{493}{048}{[turn the device 17 degrees down]}
{494}{048}{[turn the device 17 degrees right]}
{495}{048}{[turn the device 17 degrees left]}
{496}{050}{[use the device capabilities on a half of its length]}
{497}{043}{[use the device capabilities on a three quarters of its length]}
{498}{043}{[use the device capabilities on its full length]}
{499}{042}{[turn the device off]}

{500}{}{[A quiet moaning is noticed.]}
{501}{051}{[keep the device in this position for a while]}
{502}{053}{[turn the device 17 degrees up]}
{503}{051}{[turn the device 17 degrees down]}
{504}{051}{[turn the device 17 degrees right]}
{505}{053}{[turn the device 17 degrees left]}
{506}{043}{[use the device capabilities on a three quarters of its length]}
{507}{043}{[use the device capabilities on its full length]}
{508}{042}{[turn the device off]}

{510}{}{[A quiet moaning continues without changes.]}
{511}{052}{[keep the device in this position for a while]}
{512}{053}{[turn the device 17 degrees up]}
{513}{052}{[turn the device 17 degrees down]}
{514}{052}{[turn the device 17 degrees right]}
{515}{053}{[turn the device 17 degrees left]}
{516}{043}{[use the device capabilities on a three quarters of its length]}
{517}{043}{[use the device capabilities on its full length]}
{518}{042}{[turn the device off]}

{520}{}{[No changes have been observed: still quiet moaning.]}
{521}{051}{[keep the device in this position for a while]}
{522}{053}{[turn the device 17 degrees up]}
{523}{051}{[turn the device 17 degrees down]}
{524}{051}{[turn the device 17 degrees right]}
{525}{053}{[turn the device 17 degrees left]}
{526}{043}{[use the device capabilities on a three quarters of its length]}
{527}{043}{[use the device capabilities on its full length]}
{528}{042}{[turn the device off]}

{530}{}{[Quiet moaning turns into a loud moaning.]}
{531}{054}{[keep the device in this position for a while]}
{532}{054}{[turn the device 17 degrees up]}
{533}{054}{[turn the device 17 degrees down]}
{534}{054}{[turn the device 17 degrees right]}
{535}{054}{[turn the device 17 degrees left]}
{536}{056}{[use the device capabilities on a three quarters of its length]}
{537}{043}{[use the device capabilities on its full length]}
{538}{042}{[turn the device off]}

{540}{}{[No changes have been observed: loud moaning continues.]}
{541}{055}{[keep the device in this position for a while]}
{542}{055}{[turn the device 17 degrees up]}
{543}{055}{[turn the device 17 degrees down]}
{544}{055}{[turn the device 17 degrees right]}
{545}{055}{[turn the device 17 degrees left]}
{546}{056}{[use the device capabilities on a three quarters of its length]}
{547}{043}{[use the device capabilities on its full length]}
{548}{042}{[turn the device off]}

{550}{}{[Nothing has changed, still loud moaning.]}
{551}{054}{[keep the device in this position for a while]}
{552}{054}{[turn the device 17 degrees up]}
{553}{054}{[turn the device 17 degrees down]}
{554}{054}{[turn the device 17 degrees right]}
{555}{054}{[turn the device 17 degrees left]}
{556}{056}{[use the device capabilities on a three quarters of its length]}
{557}{043}{[use the device capabilities on its full length]}
{558}{042}{[turn the device off]}

{560}{}{[Loud moaning is complemented by a twitching of separate limbs.]}
{561}{059}{[keep the device in this position for a while]}
{562}{057}{[turn the device 17 degrees up]}
{563}{059}{[turn the device 17 degrees down]}
{564}{057}{[turn the device 17 degrees right]}
{565}{057}{[turn the device 17 degrees left]}
{566}{043}{[use the device capabilities on its full length]}
{567}{042}{[turn the device off]}

{570}{}{[Nothing changes in the volume of moaning and amplitude of limbs twitching.]}
{571}{059}{[keep the device in this position for a while]}
{572}{058}{[turn the device 17 degrees up]}
{573}{059}{[turn the device 17 degrees down]}
{574}{058}{[turn the device 17 degrees right]}
{575}{058}{[turn the device 17 degrees left]}
{576}{043}{[use the device capabilities on its full length]}
{577}{042}{[turn the device off]}

{580}{}{[Moaning is still loud, limbs are twitching.]}
{581}{059}{[keep the device in this position for a while]}
{582}{057}{[turn the device 17 degrees up]}
{583}{059}{[turn the device 17 degrees down]}
{584}{057}{[turn the device 17 degrees right]}
{585}{057}{[turn the device 17 degrees left]}
{586}{043}{[use the device capabilities on its full length]}
{587}{042}{[turn the device off]}

{590}{}{[Loud moaning turs into a screaming, her body begins to tremble.]}
{591}{060}{[keep the device in this position for a while]}
{592}{060}{[turn the device 17 degrees up]}
{593}{060}{[turn the device 17 degrees down]}
{594}{060}{[turn the device 17 degrees right]}
{595}{060}{[turn the device 17 degrees left]}
{596}{062}{[use the device capabilities on its full length]}
{597}{042}{[turn the device off]}

{600}{}{[Her body is still trembling, screaming continues]}
{601}{061}{[keep the device in this position for a while]}
{602}{061}{[turn the device 17 degrees up]}
{603}{061}{[turn the device 17 degrees down]}
{604}{061}{[turn the device 17 degrees right]}
{605}{061}{[turn the device 17 degrees left]}
{606}{062}{[use the device capabilities on its full length]}
{607}{042}{[turn the device off]}

{610}{}{[No changes in screaming, her body is still trembling.]}
{611}{060}{[keep the device in this position for a while]}
{612}{060}{[turn the device 17 degrees up]}
{613}{060}{[turn the device 17 degrees down]}
{614}{060}{[turn the device 17 degrees right]}
{615}{060}{[turn the device 17 degrees left]}
{616}{062}{[use the device capabilities on its full length]}
{617}{042}{[turn the device off]}

{620}{}{Ooooooh! Yeeeeeeeah! Like that! Please, don't stop! Please, don't stoooop!!}
{621}{063}{[keep the device in this position for a while]}
{622}{065}{[turn the device 17 degrees up]}
{623}{063}{[turn the device 17 degrees down]}
{624}{063}{[turn the device 17 degrees right]}
{625}{065}{[turn the device 17 degrees left]}
{626}{067}{[turn the device off]}

{630}{}{Yes!! A little more! Don't stop!! Oooh!!}
{631}{064}{[keep the device in this position for a while]}
{632}{065}{[turn the device 17 degrees up]}
{633}{064}{[turn the device 17 degrees down]}
{634}{064}{[turn the device 17 degrees right]}
{635}{065}{[turn the device 17 degrees left]}
{636}{067}{[turn the device off]}

{640}{}{A little more!! Yes! Oh yes!! Don't stop, please don't stop!!}
{641}{062}{[keep the device in this position for a while]}
{642}{065}{[turn the device 17 degrees up]}
{643}{062}{[turn the device 17 degrees down]}
{644}{062}{[turn the device 17 degrees right]}
{645}{065}{[turn the device 17 degrees left]}
{646}{067}{[turn the device off]}

{650}{}{YYYYYEEEEEEEEEEEEESSS!!! [Observing the fantastic finale, you come to a conclusion that the device is fully capable of fulfilling its intended purpose.] }
{651}{066}{[wait for a while]}

{660}{}{[Blanca comes to her senses] Oh, that was unbelievable! You are the true super-lover! I don't feel so edgy anymore, so I suppose this thing does its job. Give it to me - and here's your reward, as we agreed. Thank you for these beautiful moments...  And give me a little more time.}
{661}{999}{Glad to be of help. Ask me if you need something.}

{670}{}{NOOOOO! WHAT HAVE YOU DONE?! AAHHHHH!!...}
{671}{999}{Whoops...}

{680}{}{[Blanca gives you a seductive look] Glad to see you, handsome. Do you remember that you promised to come by, when I get lonely without Cyren? I already am. Want to come for a minute?}
{681}{010}{Not now, I just wanted to ask.}
{682}{069}{Of course! I don't like it when girls are feeling lonely.}
{683}{999}{No, I was just coming by. I have a job to do. Bye.}

{690}{}{[You tried your best to impress Blanca and make her less bored] Okay, that was good. Not the worst sex in my life for sure. Come around sometime, you'll learn something interesting. }
{691}{010}{Wait, I wanted to ask something.}
{692}{999}{Right, see you later.}

{700}{}{[She drops on her knees before you. Her long hair is in your clutched hand. You feel fully in control over her.]}
{701}{071}{[unzip your pants and force her to "service" you, using blows and threats]}
{702}{072}{[beat her]}
{703}{073}{[slap her face a few times]}
{704}{999}{[push her away, down to the floor]}

{710}{}{[Blanca tries to resist, but you easily twist her arms, forcefully guiding the movements of her head. In the end, she gives up, rhytmically rocking back and forth, whining. When her cries become louder, you speed up her tempo, holding her head tighter to you. It makes her to start suffocating from the lack of air. You get the thing done and push her away. She drops down on the floor and quietly cries.]}
{711}{999}{Shut up and get yourself cleaned up. Next time I'll feed you and your lovely Cyren to Lavash. So, walk around on your toes now. }

{720}{}{[You start slapping her face and punching her ribs, don't holding back. When she gives up resisting, laying on the floor barely alive, you stop your assault.]}
{721}{999}{Shut your hole. Make one little sound again, and I'll feed you and your lovely friend to Lavash. So, be a good girl and walk around on your toes, bitch.}

{730}{}{[Blanca is crying, tears are flowing down her cheeks, red from constant slapping. She looks helpless before you.]}
{731}{071}{[Her lips are so damn attractive. Unzip your pants and force her to "service" you, using blows and threats]}
{732}{072}{[Beat her]}
{733}{074}{Say one more word, and you are going to work shifts on this factory non-stop for a month, with no days off. Do you understand me? Huh?!}

{740}{}{[Blanca trembles, crying.]}
{741}{999}{[push her away, down to the floor]}

{742}{}{It seems the poor girl's body couldn't handle such strain...}
{743}{}{0}
{744}{}{0}
{745}{}{0}
{746}{}{0}
{747}{}{0}
{748}{}{0}
{749}{}{0}