##############################
#Локация: НМП
#Имя: Дан
#Краткое описание: Лидер "Стального Закона" в НМП
#Дата создания: 01.10.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a skinny, wiry man.}
{2}{}{He patronizingly gazes on the people around him, as if knowing something they don't.}
#
# после знакомства
{3}{}{You see Dan.}
{4}{}{The leader of "Steel law". He holds beads in his right hand.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{14}{}{[He is clearly not young, but grey eyes on his shallow, cunning face are still burning with thirst for action.] So, a new face around here, huh? What brings you to me, boy? Do you think that old buddy Dan would help you become the recruit of "Steel law"? [He smiles, but his eyes stay serious.]}
{10}{011}{I am }
{11}{011}{. What "Steel law" are you talking about?}
{12}{999}{Hello, Dan. My name is }
{13}{999}{. I'm just looking around for now. Well, I won't be bothering you. Bye.}


{1001}{}{[Seeing you he slightly nods, without altering his posture] What brings you to me, outsider? I hope your brains have not yet been brainwashed by Mark and his company. You know, about the "Steel law" being the biggest threat to NWO.}
{101}{011}{Yes, I wanted to ask - what is this "Steel law"?}
{102}{015}{I've recently learned something interesting about you and Lucy... I see in whose honour Daniel was named.}
{103}{999}{I was just walking by. Talk later, Dan.}
{1002}{}{[He puts his palm to the chest and respectfully nods to you, hiding his eyes] Greetings and admiration to the worthy successor of our old man Mark! I hope now NWO will follow its new course? [he smiles a little]}
{104}{016}{What, you have some ideas about that? Tell me!}
{105}{999}{That's for me to decide, Dan. Your duty is to follow orders. Remember that. I'll see you around.}
{106}{017}{Sure! Enough of tolerating the expansion of Jackals and Rainbow! It's time to impose in Radius our law... Steel law!}
{1003}{}{[He swiftly throws beads into his left hand and squeezes your palm in a firm handshake] Glad to see you, kid! I admit, I had some doubts about you in the beginning. But now, when Daniel is behind the wheel, not without your help... What I want to say is - you are always welcomed in my home.}
{107}{018}{So, changes for the better?}
{108}{999}{I did what i thought was right... Was nice seeing you, Dan, but I have to go.}
{1004}{}{[He wraps his beads around the fist, like forming a knuckle, and hisses] I didn't like you from the start... If I only knew you would wreck everything I worked on. The deadman in charge! Do you realize what it will lead to? It's okay, my time would come eventually... And you - get lost. I have no intentions to keep our conversation going.}
{109}{999}{You mad? Just try to do something about it, I'll bury you. Peace out, little revolutionary.}
{1010}{999}{I hope one day you will understand that this was the best option... Bye, Dan.}
{1005}{}{[Dan adjusts the armband on his sleeve and salutes you] Reporting - the agitation process among local population is proceeding quite well. My Arson is very persuasive... As for me, I'm busy with making a list of those who would better be off somewhere else. Ghouls, for example... And the main thing is that we keep hoarding the weapons. We are trying to do it as quiet as we can, no need for unnecessary attention.}
{1011}{999}{That's the spirit! Everything should be ready when I decide for us to move out. Talk later.}


{110}{}{[Dan becomes more lively, his eyes assessing you] What, no one even nagged about it? Hm... Okay, why not help a good man, enlightening him on what's what? Here's the thing, now NWO is lead by a bunch of idealists, naively trying to make peace with other settlements of Radius through negotiations and establishing trade relations. How stupid is that? Fortunately, there are some people who understand that you can accomplish something in this cursed world only by the power of weapon. They call themselves "Steel law". With a good old expansionism, we could capture enough prisoners to significantly increase our production and military capacities! So it goes. And yeah, for some reason, I am considered a leader of this covert organization... We always get this dirty looks, me and my son. Have you met Arson? Good kid, except a little hot-headed... }
{111}{012}{What's wrong with peaceful ways of dealing with problems? I'm not much into violence, you know...}
{112}{013}{And you are, of course, unrelated to this "Steel law", aren't you? If I'd like to help - who should I talk to?}
{113}{014}{Hm... And why do you... I mean, they even hope for achieving the succcess? Other factions of Radius have some serious power and men.}
{114}{999}{I see. Well, I'm not very interested in local politics. See you!}


{120}{}{[He leniently chuckles] With whom? With Jackals? Or with crazy junkies from Rainbow? Or with greedy snobs from Olympus? We were attacked before, you know. It was a miracle we fought off. Want to know why? Because there were some guys, who traded their batteries for a good guns, not on some peaceful crap. You can always do more with good gun than with a good word. At any times. That's the message "Steel law" is trying to get to everyone.}
{121}{013}{But you are, of course, unrelated to this "Steel law", aren't you? If I'd like to help - who should I talk to?}
{122}{014}{Hm... And why do you... I mean, they even hope for achieving the succcess? Other factions of Radius have some serious power and men.}
{123}{999}{I need to think about it. See you around, Dan.}


{130}{}{[He shrughs with seeming indifference] How do I know? I'm very loyal to the current management. I would be glad if Daniel succeeded Mark as mayor.... [Dan smiles, gazing above your head] He is worthy of his father, you know. And he has good opinion about the "Steel law".}
{131}{015}{I bet you would. Your blood is your blood, right? You and Lucy put a lot of effort...}
{132}{012}{I still don't get it. What's wrong with peaceful ways of dealing with problems? I'm not much into violence, you know...}
{133}{014}{Why does "Steel law" even hopes for achieving the succcess? Other factions of Radius have some serious power and men.}
{134}{999}{Okay, I'll go talk to him. Thanks for the information, Dan.}


{140}{}{[He moves his shoulders, as if warming up before the fight] No one said that this would be easy. But it's going to be worth it. Besides, our advantage is that no one waits from us something like this. }
{141}{012}{I still don't get it. What's wrong with peaceful ways of dealing with problems? I'm not much into violence, you know...}
{142}{013}{And you are, of course, unrelated to this "Steel law", aren't you? If I'd like to help - who should I talk to?}
{143}{999}{Maybe there is something about it... I need to think it over. I need to go, thanks for the info.}


{150}{}{[Contrary to your expectations, Dan only lazily sits by the wall and continues to cycle through his beads] Did Sam tell you this? This ghoul is completely lost his mind from radiation. If my son and Daniel are friends - that means I banged Lucy? So logical! Go do your business, and next time think before trying to surprise me. You looked pretty stupid, pal.}
{151}{999}{Okay, I'll go. It doesn't matter much anyway. Stay on your toes, Dan. See you around.}


{160}{}{[He clears his throat and starts to eloquently speak] In my humble opinion, now is the best time to organize massive attack on all fronts. People are ready for changes and full of enthusiasm. I could develop a project plan for occupying new territories, I already have something in the works...}
{161}{017}{Sure! Enough of tolerating the expansion of Jackals and Rainbow! It's time to impose in Radius our law... Steel law!}
{162}{999}{That's for me to decide, which way to go. Your duty is to follow orders. Remember that and don't take too much upon yourself. Take care, Dan.}


{170}{}{[Dan pulls out an armband from his pocket, depicting mechanical hand, holding the skull in tight grip. He puts it on your shoulder] I knew this day would come. Me and my son will immediately take action in the name of "Steel law". I will persuade those who have doubts and punish all renegades... You'll see, soon everyone around here will join us in our crusade to Rainbow and Olympus! }
{171}{999}{Do it, but be careful. You can't rush this, we must succeed for sure. Report to me personally. For now I need to go. Good luck!}


{180}{}{True. Daniel is much more forward-looking in the matter of picking allies than his fath... Uh, Mark. He takes "Steel law" much closer to the heart, and listens to opinion of experienced people, who put their soul into the prosperity of NWO. }
{181}{999}{Time will tell, if you're right. Good luck.}