##############################
#Локация: НМП
#Имя: Даниэль
#Краткое описание: Сын руководителя НМП
#Дата создания: 05.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a young man.}
{2}{}{All his look says that he's the boss here.}
#
# после знакомства
{3}{}{You see Daniel.}
{4}{}{As usual, he looks just like a young rooster in a henhouse.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Before you stands a man in his twenties. His clothes is covered with rivets, chains and pieces of metal] Hey there! }
{11}{002}{Hello. I'm here recently, looking around the town.}

{20}{}{[he gives you a wide smile] Hah, I'm going to tell you something about this town. It should be blown the hell up, to build a new one on its place! I'm Daniel, Mayor's son. After my dad kicks the bucket, I'll be in charge. And I'm going to turn this place upside down!}
{21}{010}{Glad to meet you. I'd like to ask some questions.}
{22}{999}{Glad to meet you, but I need to go.}

{1000}{}{Hello again, wanna talk?}
{1001}{}{You are talking to the future Leader of NWO, so show me respect! Haha, just kidding! You helped me greatly to become Mayor! Did you want something?}
{1002}{}{And here's our new Mayor. How cunningly you took my place. I can still give you some advice about what to do with the town.}
{1003}{}{Okay!}
{101}{011}{What can you tell me about the town?}
{102}{030}{It's you who is going to be a new Mayor?}
{103}{024}{Tell me about your father.}
{104}{029}{What do you do here?}
{105}{036}{Yes, I'm the new Mayor. And I'd like you to keep your gimmicks to yourself.}
{106}{999}{Let's talk later, I need to go.}

{110}{}{[Daniel spits on the ground] This place is a dirty pile of heap. Everything is wrong here. And something needs to be done about it! But everyone's afraid to act, because they are afraid of my pops. And I'm the only one who doesn't hesitate to openly say that he is wrong. Also, Arsene and Dan, his father, agree with me.  }
{111}{012}{How do you want to change the town?}
{112}{013}{Tell me more about Arsene.}
{113}{019}{I'd like to learn about Arsene's father.}
{114}{}{[Daniel spits on the ground] This town is a dirty pile of heap. I could lead it to a great future, but then you appeared. Let's see what you can do.}
{115}{010}{Yeah, we'll see. And now - another question.}

{120}{}{[you see a fire in his eyes] I will knock down the half of local buldings to build a new ones! I'll chase all the shits out of town, so only the cool guys would stay! Arsene is going to help, Dan too. And mom. Together we are strong!}
{121}{013}{Can you tell me about Arsene?}
{122}{019}{Tell me about Dan.}
{123}{020}{I'd like to hear about your mom.}
{124}{021}{How are you going to build new buldings?}
{125}{022}{Who exactly do you want to chase out of town?}

{130}{}{[Daniel starts proudly talking] Arsene is my best bud! He is the smartest one around. We are doing big things together, all town knows about them.}
{131}{014}{Tell me details about your doings.}
{132}{010}{I want to ask another question.}

{140}{}{[Daniel satisfyingly smiles] Big things, all the time - that's what we do. We rock the place! Last of our jobs include political stand-off resolvement, production rate improvement and disaster prevention. What do you want to hear about?}
{141}{015}{Sounds serious. Tell me about political stand-off resolvement.}
{142}{016}{I see you actually care about the town. Tell me about production rate improvement.}
{143}{018}{You guys must be heroes. Tell me aboud disaster prevention.}
{144}{010}{I want to ask something else.}
{145}{999}{Let's talk later. I need to go.}

{150}{}{There was some chick here, trying to get on Dan, saying that he knows nothing about politics. So, me and Arsene threw a rotten lavash head into her window! Can you imagine that?! Now she keeps her mouth shut! You could say it's plus additional vote for us!}
{151}{016}{Oh, I see. Tell me about production rate improvement.}
{152}{018}{Okay. What about disaster prevention?}
{153}{010}{I want to ask other questions.}

{160}{}{A day before we secretly snuck into the canned meat factory. And Arsene poured a whole bucket of machine oil into the meat! Which lead to producing ten cans of meat more than usual! People didn't notice anything. The taste and smell got worse though, but they still eat it, no worries. }
{161}{017}{You didn't happen to pour something like this into the lavash food, did you?}
{162}{015}{Right. Tell me about political stand-off resolvement.}
{163}{018}{Tell me aboud disaster prevention.}
{164}{035}{[As in all conversation, you are carefully observing the one you speak to. You notice the silouette of oil bottle in his inner pocked] You do smell some machine oil now, you know that? Here's the bottle sticking out. Do you want to pour it somewhere again? }
{165}{010}{Another question then.}

{170}{}{Of course! We added some oil into it too. There's more food this way!}
{171}{010}{I want to ask something else.}
{172}{999}{I see. I'll go do my things, see you.}

{180}{}{One asshole wanted to get two of his friends into NWO, so they agreed to meet at dawn, on the outskirts of the town. Can you imagine three assholes in the NWO? It is a disaster! I can barely tolerate one. So, we boarded up his doors and windows at night, he didn't make it to his friends, and they left. That's it!}
{181}{015}{Tell me about political stand-off resolvement.}
{182}{016}{I want to hear about production rate improvement.}
{183}{010}{I'll ask something else.}

{190}{}{Dan is Arsene's father. A wise man! Knows politics like nobody else. He talks right things, me and Arsene like to listen to him. Sometimes I don't quite get what Dan tries to tell us, but it is definitely important.}
{191}{012}{I see. Tell me, what do you want to do with a town?}
{192}{010}{I'll ask something else.}
{193}{999}{I see. I need to go.}

{200}{}{My mom helps me greatly.  She keeps my pops away, when I screw up. And she does all my stuff at home, so I could have time to do more serious things.}
{201}{012}{I see. Tell me about your plans for a town.}
{202}{010}{I'll ask something else.}
{203}{999}{I'll go talk to her. Bye.}

{210}{}{[Daniel ponders] I have no idea. Somehow? What matters is that I know how to knock them down, and the locals will handle building new ones. What else they would do? }
{211}{012}{Okay. So, what are your plans for the town?}
{212}{010}{I'll ask something else.}

{2200}{}{I will throw all the shits out of the town, all of them! Though, I still need to decide, which ones. Ghouls for sure, I hate them! I'll drive them all off, except Sam.}
{2201}{}{I will throw all the shits out of the town, all of them! Especially Sam! This asshole took my place of Mayor!}
{221}{023}{Why won't you drive off Sam?}
{222}{010}{Another question then.}

{230}{}{Because he is my grandpa. He can stay. Even if he smells a mile away... But the other ones will be chased away!}
{231}{012}{Okay. So, what did you want to do with the town?}
{232}{010}{Another question, on difeerent topics.}
{233}{999}{I see. I'll go talk to Sam. Bye.}

{2400}{}{My father is a Mayor, his name is Mark. I don't want to talk about him, we don't see each other much. I hang out with Arsene mostly, so I talk to his father more than with mine.}
{2401}{}{My father is an ex-Mayor, his name is Mark. Also known as old and dumb jerk, who trusted the leadership of this town to a complete stranger.}
{2402}{}{My father is an ex-Mayor, his name is Mark. Also known as old and dumb jerk, who trusted the leadership of this town to a half-dead rotten corpse.}
{2403}{}{My father is a Mayor, his name is Mark. He is a bore and a fool. Although he is smart enough to put me in charge of NWO.}
{241}{025}{If he is a Mayor, you can learn many things from him.}
{242}{010}{I'll ask something else.}

{250}{}{[Daniel cringes] Meh, pops doesn't know what he is doing. He lost it for a long time already. Look what swamp NWO has become! As Arsene says, "Dying lavash won't give a good offsprings". And I am completely agree.}
{251}{026}{What Arsene actually means by that?}
{252}{027}{It's not so bad around here. You have food, water. Work.}
{253}{010}{I want to ask something else.}

{260}{}{No idea. I'm not a philosopher.}
{261}{010}{Um, okay. I'll ask something else.}
{262}{027}{But what is actually the problem? It's not so bad around here. You have food, water. Work.}

{270}{}{[Daniel starts actively gesturing. Metal things on his clothes start to chime a little] This is all bullshit! We are capable of doing much more! We could run the whole world if we want to!}
{271}{028}{And what needs to be done about it?}
{272}{010}{I'll ask something else.}

{280}{}{[Daniel is waving hands even more energetically, metal things on his clothes are chiming loudly] Who the hell cares! First, we need to destroy everything old around here, and then to think about what to do next!}
{281}{010}{Okay, I'll ask something else.}
{282}{999}{I see. Okay, we'll talk later.}

{290}{}{I have a lot of things to do in NWO! Arsene is helping. We are the coolest guys around. }
{291}{013}{Tell me about Arsene.}
{292}{014}{What exactly are you doing with Arsene?}
{293}{010}{I'll ask something else.}
{294}{}{Working.}
{295}{010}{Okay. Another question.}

{300}{}{Yeah, pops is pretty sick. And soon I'll inherit the Mayor's position. I feel sorry for the pops, of course, but he is doing his job pretty sick. Would be better if he put me into Mayor already, and got some rest.}
{301}{034}{I talked to your father. He doesn't want you to be the Mayor. But I think you are right, so just pretend you want to reform. When you become Mayor, you can do whatever you want.}
{302}{031}{I talked to your father. I think he is right. You should reform to become a better Mayor. If you do, you could carry the legacy of your father.}
{303}{032}{I think you'll make a bad Mayor. I don't like your ideas.}
{304}{033}{You'll probably do good as a Mayor.}
{305}{010}{Let's talk about something else.}
{306}{999}{I'll go talk to your father. See you around.}

{310}{}{You don't know shit about it! I won't change myself for this hole NWO turned into!}
{311}{010}{Okay then... Maybe I don't understand it. Let me ask something else.}
{312}{999}{Suit yourself. I need to go.}

{320}{}{You are just like my pops! You don't know shit! NWO is rotting because of people like you!}
{321}{010}{Okay then... Maybe I don't understand it. Let me ask something else.}
{322}{999}{Suit yourself. I need to go.}

{330}{}{[Daniel jumps in excitement. Chiming of his metal turns into some melody] That's it! You know, you're cool! You noticed straight away that this place needs changes!}
{331}{010}{Yes, a lot of changes. I'll ask something else.}
{332}{999}{Of course! You start changing, and I need to finish something. See you.}

{340}{}{[Daniel blushes. but quickly calms down] Yes, pops can put me into trouble. Your idea might work... Okay, I'll pretend. And then I'll show them!!}
{341}{010}{Deal then. Another question.}
{342}{999}{Agreed. I'll go talk to your father.}

{350}{}{[Daniel seems a little confused] Uh, I thought it's well-hidden in my pocket... Okay, here's a secret for you - me and Arsene decided to put some of machine oil into lavash food, to cut costs, so to say. They don't care, we have profit.}
{351}{010}{I see. I want to ask something else.}
{352}{999}{Understood. I need to go, see you later.}

{360}{}{Meh. What?}
{361}{037}{I'll think you'll do fine on a factory line. On the loading stage.}
{362}{040}{I'm watching you.}
{363}{999}{Nevermind. I'll go.}

{370}{}{Wh- What? What did you say?}
{371}{038}{I said that starting today you work on a factory. We are all equal here, so it doesn't look good when someone does nothing for the common good. }

{380}{}{But...}
{381}{039}{I suggest you to start working. Or the guards will be making you work everyday. With their boots }

{390}{}{[the moy gazes at you with open mouth. He is, to put it mildly, bedazzled.]}
{391}{999}{Okay, I need to go. See you.}

{400}{}{So? Watch me. Watch me all you like.}
{401}{999}{Sure. [end dialogue]}
{402}{037}{I think it would be more convenient for me to watch if you will take a job on a factory in a loading stage.}

#Плавающие фразы на заводе
{410}{}{Oh... It's you...}
{411}{}{I'm working, I'm working! Can't you see?}
{412}{}{I was just having a break!}
{413}{}{What else do you want?}