##############################
#Локация: НМП
#Имя: Люси
#Краткое описание: Жена руководителя НМП
#Дата создания: 01.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов 
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a beautiful, well-groomed woman.}
{2}{}{She looks pretty attractive, despite her age. She is definitely not of "working class".}
#
# после знакомства
{3}{}{You see Lucy.}
{4}{}{She looks flawless, as always.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a middle-aged woman. A few wrinkles on her face indicate about her age, but with impecably made hair, clean clothes and well-tended skin she look very attractive. She has a light smile and shining eyes and smells with a faint sweet scent of perfume.] Good day. I don't remember us meeting before, do I know you?}
{11}{002}{Hello. No, I'm here recently. }
{12}{014}{Hi. No, it's my first time here.}
{13}{020}{Hah, I see you for the first time too. }

{20}{}{[you hear curiosity in her voice] Oh, I'm so glad do meet a new people in our town! My name is Lucy, I'm Mark's wife. Come, make yourself at home, let's have a chat.}
{21}{003}{I'm also fond of meeting new people. You can learn so much new information from them!}
{22}{015}{I like talking to new people too. You can make a lot of benefit from it.}
{23}{017}{I don't like to talk sideways. Usually, I'm specific.}
{24}{018}{Actually I'm not much of a talker. I prefer to act first, then ask questions.}
{25}{010}{Thank you, but first I'd like to ask a few questions.}
{26}{999}{Thanks, but not now, I'm in a hurry. Talk later.}

{30}{}{[she brightens up] That's what I think too! Learning new things is so interesting! It's very boring here, no one to have a normal discussion with, while there's so much stuff going on around! For example, recently husband of my friend's sister caught my friend's brother making out with her sister, and then she... [you are caught into a long monologue about relationships between NWP's inhabitants] ...and turns out my friend actually cheated on her husband with his brother!}
{31}{004}{[you listen with you mouth wide open, with attention to every detail] How could this happen!}
{32}{008}{[you pretend to listen carefully, but actually tune out] Oh wow, I have no words!}
{33}{008}{[from very beginning of her monologue, you begin to recall every single thing that occured to you since the start your journey. You count every ammo spent by you and your enemies in battles. And just as you started to count all the food you have eaten, Lucy finishes] What a story!}
{34}{011}{[you fall asleep almost immediately. You wake up only when she finishes] What, done already?}

{40}{}{You didn't listen!}
{41}{005}{Yes I did, very carefully!}
{42}{013}{I did, but not very carefully.}
{43}{011}{Frankly speaking, no, I didn't.}


{50}{}{[she starts to get angry] Then tell me, with whom my friend's sister cheated with: my friend's husband, brother of my friend's husband, or with brother of sister's husband? You have four tries!}
{51}{007}{[you know the right answer, because you listened carefully] Of course with brother of your friend's husband!}
{52}{006}{How can it be four tries if there are three options?}


{60}{}{Don't try to change the subject with your math! Answer me!! [she is ready to explode, time to give the answer]}
{61}{007}{Of course with brother of your friend's husband!}




{70}{}{[she almost jumps up from joy] That's correct! You did listen! You are so cool!}
{71}{010}{Yeah, it was interesting. Let me ask you something.}
{72}{999}{Um, I'll go, see you around.}



{80}{}{You didn't listen!}
{81}{005}{Yes I did, very carefully!}
{82}{013}{I did, but not very carefully.}
{83}{011}{Frankly speaking, no, I didn't.}




{90}{}{[she starts to get angry] Then tell me, with whom my friend's sister cheated with: my friend's husband, brother of my friend's husband, or with brother of sister's husband? You have four tries!}
{91}{011}{with your friend's husband!}
{92}{007}{with brother of your friend's husband!}
{93}{011}{with brother of sister's husband!}
{94}{012}{How can it be four tries if there are three options?}


{1000}{}{[seeing you, Lucy smiles a little] Oh, hello! Decided to come again?}
{1001}{}{Okay then.}
{1002}{}{[Lucy gives you a wide smile, waving her hand. She is definitely fond of you]Hey! Glad to see you! Wanna chat?}
{1003}{}{[seeing, you Lucy tries to take on a serious look, crossing hands on her chest. She is definitely upset with you.] Yes, did you want something?}
{1004}{}{You! Asshole! How could you! What disgusting things did you say to Mark about my son!? Are you hungry for power or something?}
{101}{031}{What can I do in a town like this?}
{102}{027}{Lucy, you are a wonderful person. I feel so easy when we talk, because you are so so sincere and open. This qualities are so rare to meet in someone, especially in current times.}
{103}{029}{I noticed that you are remarkably good at taking care of yourself. How do you manage to be so well-groomed and good-looking among all this dirtyness and pollution around?}
{104}{040}{Can you tell me about your family?}
{105}{029}{You are so beautiful and clean. How are you doing it?}
{106}{054}{What's the problem?}
{107}{055}{Maybe you should have spent more time on parenting your son?}
{108}{999}{I'll come by later.}


{110}{}{You didn't listen at all! [she turns around and keeps silence]}
{111}{999}{[You see that Lucy is upset and don't want to talk anymore. You quietly leave.]}


{120}{}{Don't try to change the subject with your math! Answer me!! [she is ready to explode, time to give the answer]}
{121}{011}{with your friend's husband!}
{122}{007}{with brother of your friend's husband!}
{123}{011}{with brother of sister's husband!}




{130}{}{[Lucy looks a little upset, watching at you with silence. It seems though, that she wants to continue the conversation.]}
{131}{010}{Let me better ask you a few questions.}
{132}{999}{I'll go think about everything, see you later.}


{140}{}{[you hear curiosity in her voice] I'm always glad do meet a new people in our town! My name is Lucy. Come, make yourself at home, let's have a chat.}

{141}{003}{Yes, let's chat. I always like to hear new things.}
{142}{015}{We can talk. You can find something valuable in every conversation.}
{143}{017}{I don't like to talk sideways. Usually, I'm specific.}
{144}{018}{Usually I'm more of a "punch now, talk later" guy. }
{145}{010}{First I'd like to ask a few questions.}
{146}{999}{I have no time to chat. I'll see you later.}


{150}{}{Of course, every conversation is valuable! You can hear so much interesting news and gossips!}
{151}{003}{I like hearing interesting news.}
{152}{016}{I meant news that can benefit me.}
{153}{019}{No, I'd like to know something specific.}


{160}{}{[Lucy definitely didn't understand you] Oh, you must be talking about news from work or something? I'm not into that. Ask my husband Mark, maybe he can talk about such stuff.}
{161}{010}{Maybe you'll answer a few questions first?}
{162}{999}{Okay, I'll go see him.}


{170}{}{[Lucy looks disappointed] So sad, because I love to chat. I have so many interesting news to tell! But I can't make it short...}
{171}{003}{Okay, let's make an exception for today. I am starting to wonder what news do you have.}
{172}{010}{Then better don't. Let's do it like this - I'll ask you specific questions and you'll answer them. Okay?}


{180}{}{[Lucy makes a pause, looking displeasured. Then, with hope in her eyes, she continues]. Maybe you actually want to hear some of the news? They are very interesting!}
{181}{003}{Okay, I actually don't mind hearing some interesting news.}
{182}{010}{No, Lucy, I don't. Let me ask you a few questions.}


{190}{}{[she stops smiling] S-specific?.. I don't understand... I know nothing specific...}
{191}{010}{Let me ask you questions, just answer them.}
{192}{999}{Too bad you can't be specific. Talk later then. Bye.}


{200}{}{[she frowns and takes a step back] If you need something, tell me. I'm mayor's wife, therefore I'm very busy. My name is Lucy.}
{201}{021}{[You notice that your straightforwardness made her upset. You think about some words to fix the situation, but nothing comes up, as usual. You make a sad face and throw your hands up]}
{202}{010}{I want to ask a question.}
{203}{999}{I'll go. }


{210}{}{[she looks a little kinder than before] You know, you somehow remind me my son, Daniel. You have some common qualities. Wan to hear an interesting story? }
{211}{022}{Yeah, I can listen.}
{212}{025}{No, I need something.}
{213}{999}{No, I'll go.}




{220}{}{[Lucy starts to get lively] Recently, husband of my friend's sister caught my friend's brother making out with her sister, and then she... [you are caught into a long monologue about relationships between NWP's inhabitants] ...and turns out my friend actually cheated on her husband with his brother!}
{221}{023}{[You make a great effort, trying to make connection between everyone in this story, but you fail to do so]}
{222}{023}{[You pretend to try to make connection between everyone in this story, but actually you don't really try]}
{223}{024}{[You start to distract yourself, scratch your head, pick your nose.]}



{230}{}{[Lucy leniently looks at you] Okay, you probably didn't get it. Oh, well. Tell me, what do you want.}
{231}{010}{I want to ask a question.}
{232}{999}{I'll go. }




{240}{}{[Lucy leniently looks at you] You definitely didn't listen. Oh, well. Tell me, what do you want.}
{241}{010}{I want to ask a question.}
{242}{999}{I'll go. }



{250}{}{What do you want? I have nothing to treat you with. Go to Daniel, maybe you'll find common ground.}
{251}{026}{Have a job for me?}
{252}{010}{I want to ask.}
{253}{999}{I'll go to Daniel, bye.}




{260}{}{Ask my husband, Mark. Maybe he'll get a job for you.}
{261}{010}{I want to ask then.}
{262}{999}{I'll go to mark, bye.}




{270}{}{[Lucy blushes, then gives you a shiny smile] That is so nice, thank you! Mark never tells me such words... Not a lot of people here notice my talents... }
{271}{034}{How can one not notice your talents? You are the best in the topics of relationships between NWO's inhabitants. To be just that, one needs to have a wide worldview and honed skills.}
{272}{029}{You are very attractive woman, you deserve to be the face of this town. }
{273}{028}{I'm charmed by your sharp mind and wise judgement in dealing with any questions.}


{280}{}{[Lucy feels that something wrong here and becomes serious] Oh, you are flattering. Let's talk about something else.}
{281}{010}{Okay, let's change the subject. Another question.}


{290}{}{[Lucy smiles] Yes, woman should always be beautiful: at home, in the streets, at parties. I love taking care of myself. The looks is what always comes first. And I have a special, secret recipe, which helps me to keep myself young.}
{291}{028}{You look like a 20-year-old even without a secret recipe! }
{292}{030}{A secret recipe? You won't find such things just laying under your feet.}
{293}{039}{Your appearance means nothing, the intellect is everything!}
{294}{039}{The power comes first, looks doesn't matter much.}
{295}{010}{Okay, let me ask another question.}
{296}{999}{Good talk, but I need to go.}



{300}{}{No, you are wrong here. Look around: what do you see?}
{301}{}{All this buildings is not quite what I mean. What else do you see?}
{302}{}{Everyone's going somewhere, to home, to work. What else?}
{303}{}{Each has a lot of this stuff, yes. What else do you observe?}
{304}{030}{Buildings, houses... They serve us shelter.}
{305}{030}{People, ghouls... Each carries his purpose.}
{306}{030}{Guns, blades, ammo... Everyone has something on him.}
{307}{032}{Dirt, trash, shit... That's the most common thing around us on the streets.}


{310}{}{[Lucy frowns] It is very boring here, almost nothing to do. Everything is the same - same people, same days... Let's talk about something else.}
{311}{010}{Okay, let me ask another question.}


{320}{}{Correct! What's laying under our feet is capable of keeping our skin young and smooth! I use lavash manure as a base for face masks and compresses. It contans a special component, which makes the skin Glowy, Unblemished, Absolutely Natural and Organic, or as I say abbreviated - "GUANO"! Wanna rub some? }
{321}{033}{To rub some lavash GUANO into my face? Of course! I've always dreamed about it - about having such beautiful skin!}
{322}{010}{No way I'm getting this thing close... I mean, I'm good. Better ask you something else.}
{323}{999}{Nah, don't wanna. Will better go to get some fresh air...}




{330}{}{[For a while Lucy puts the thick layer of GUANO on your head and face. Sitting under it you actually feel how your skin rejuvenates and hair becomes soft and silky] And that's it! Wow, you are so beautiful now!}
{331}{010}{Yeah, I definitely feel myself a few years younger! I want to ask you about something else.}
{332}{999}{Right, I immediately need to go take a shower. I mean, to fully feel all the silkyness and freshness of my skin. See you.}





{340}{}{[Lucy shines from happiness] This is my biggest talent! It's a pity I can't use it more often. I know so many things about everyone, can talk for hours!}
{341}{035}{Let's go to a private room, where nothing will distract us. We'll continue the conversation there.}
{342}{010}{No, thanks, I have no time to listen. I have a question to ask.}
{343}{999}{Thanks for the talking, but I need to go.}




{350}{}{[The two of you go into a secluded room. Lucy flirtaciously looks at you] Well? What you want to do?}
{351}{036}{Perfect, here no one will distract us... from a game [put out a chessboard]}
{352}{037}{At last we are alone... [hug Lucy...]}
{353}{038}{I am so ready to all of your stories [Sit tightly and start to listen...]}
{354}{010}{No, it's too quiet here, let's go back and I'll ask some questions.}




{360}{}{[you easily win a couple of games in a row] Nah, It's very boring. Let's go back.}
{361}{010}{Let's go, I have some questions.}



{370}{}{[after hours of gymnastic exersises and acrobatics, tired but happy, you get back to reality] That was not bad at all. Let's go back.}
{371}{010}{Let's go, I have some questions.}



{380}{}{[Lucy, for a really long time, tells you gossips in which you have no interest in] Oh, I haven't had such talk for a while. You are very good listener. But we need to go back.}
{381}{010}{That was bloody interesting. Let's go, I have some questions.}




{390}{}{[Lucy frowns] If you were a woman, you'd understand. Okay, enough of that.}
{391}{010}{Then another question.}



{400}{}{I live with my husband Mark and my sonny Daniel. And there's this Sam, always crawling around. I hate him.}
{401}{041}{Mark? Tell me more about Mark.}
{402}{042}{Tell me about Daniel.}
{403}{043}{I'd like to hear about Sam.}
{404}{053}{Tell me about yourself. How did you end up here?}
{405}{010}{I want to ask another question.}
{406}{999}{I need to go, we'll talk later.}




{410}{}{Mark is my husband, he is the mayor of NWO. He is always busy with his job, can't even talk to me, I need it so much! Also, lately, his health is not so good as before. And all this quarrels with Dan are not helping at all!}
{411}{048}{Why does he quarrel with Dan?}
{412}{049}{Tell me about Dan.}
{413}{040}{I want to ask more about family.}
{414}{010}{I have another question.}




{420}{}{[Lucy smiles] Daniel... My favourite son! He is so bright! He's the future mayor of this place! He's the only one who can lead this place after Mark. I'm always helping him in all matters.}
{421}{051}{Do you think he will be a good successor to Mark?}
{422}{052}{What matters do you mean?}
{423}{040}{Then I want to ask more about family...}
{424}{010}{I have another question.}
{425}{999}{Okay, I'll go talk to him.}



{430}{}{[Lucy gets angrier] Sam, Mark's granddad. He should have rotted a long time ago. He always gets between me and Mark.}
{431}{}{You know, he has changed a lot lately. He apologized to me! I didn't believe at first and asked him for a favor. And he did it! And now he always helps!}
{432}{}{We are good with Sam, we made peace.}
{433}{044}{Why are you at odds with Sam?}
{434}{010}{Then another question.}


{440}{}{This old piece of a corpse always tells Mark that I'm cheating on him with anyone!}
{441}{046}{I bet that you are cheating on him not with just anyone.}
{442}{047}{Did you try to talk to him?}
{443}{045}{Lucy, try to make peace with him, please. He is half-decayed, his brains are rotten to the core. He doesn't understand what he says.}
{444}{045}{Sam is almost dead, his brains rotten. He doesn't understand what he says. Don't be angry with him, try to make peace. }
{445}{010}{Another question.}
{446}{999}{Okay, see you later.}




{450}{}{You know... You are actually saying the right things! If it was someone else telling me this, I wouldn't listen. But to you I trust. So, I'll do it! No more quarrels with Sam.}
{451}{}{You know... You are actually saying the right things, but I don't trust you much... [maybe you need to do something to make her more sympathetic to you]}
{452}{040}{Okay, then I want to ask more about family.}
{453}{010}{Then another question.}




{460}{}{That's what I mean! I'm not cheating on him with just anyone, err, I'm not cheating on him at all! }
{461}{040}{I want to ask more about family.}
{462}{010}{Yeah, I believe that. Can I ask another question?}



{470}{}{I don't want to see him, he disgusts me. Let's talk about something else.}
{471}{040}{I want to ask more about family...}
{472}{010}{Another question...}



{480}{}{They are always arguing about politics, I understand nothing they say.}
{481}{040}{I want to ask more about family...}
{482}{010}{Another question...}




{490}{}{Dan is the opposite of Mark in matter of politics. They always disagree. After Mark dies, with my sweet Daniel becoming mayor, everything will be better... Dan wouldn't quarrel with his son, after all.}
{491}{050}{Wait, so Daniel is Dan's son? Not Mark's?}




{500}{}{[Lucy stumbles] No, no-no! You got it wrong, of course he is Mark's son! I tell you!}
{501}{040}{Okay, I got it. I want to ask more about family.}
{502}{010}{I see. Another question.}



{510}{}{Of course, he is an adult now and he is ready. He can do so many things, he is so sweet! He will be the best mayor of all times! More so, with me continuing to take care of him.}
{511}{052}{How do you take care of him?}
{512}{040}{I want to ask more about family.}
{513}{010}{Another question.}




{520}{}{Oh, in everything! From dusk, when I'm tying his shoes, and until dawn, when I put him to bed. He is very mature, and with my help he will become a great mayor!}
{521}{040}{Tying his shoes? I see, he is very mature. I want to ask more about family.}
{522}{010}{He should be, if you even help him go to bed. Okay, another question.}
{523}{999}{Yeah, the best one. I'll go talk to him.}




{530}{}{I went from town to town, until I got here, to NWO. Mark noticed me right away, then we got married. Not much interesting happened until Mark, just struggling for survival.}
{531}{040}{I want to ask more about family.}
{532}{010}{Another question.}



{540}{}{That you are piece of shit! Everybody trusted you, and you... You snake! Get the hell out of here, I don't want to see you again!}
{541}{999}{[end of dialogue]}


{550}{}{What? What did you say? Wh- WHAT? You will be bossing me around here? Go to hell, you asshole!!}
{551}{999}{[end of dialogue]}

#Люси разозлилась
{560}{}{How dare you!?}
{561}{}{Get the hell out of here, "leader"!}
{562}{}{I don't want you here!}
{563}{}{Get the hell out, you jerk!}
{564}{}{You scoundrel! Get out!}