##############################
#Локация: НМП
#Имя: Мэт
#Краткое описание: Мэт - мечтательный юноша, выбравший себе необычное хобби - кулинарию. Будучи большим романтиком, он верит, что когда-нибудь станет знаменитым поваром. И он правда может им стать, однако поддержать его некому. Старший брат Сэт не воспринимает Мэта всерьез, наоборот, пытается доказать, что тот ничего не добьется. Ему нужно, чтобы Мэт уважал его как старшего и слушался его, а не занимался своими увлечениями. В ответ Мэт сначала игнорирует брата, а затем начинает его ненавидеть.
#Дата создания: 29.09.2014
##############################
#Для игры "Олимп 2207"
#Руслан Арсланов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a common-looking local dweller.}
{2}{}{A middle-aged man with a friendly face.}
#
# после знакомства
{3}{}{You see Matt.}
{4}{}{A living hope of every gourmets in Radius.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{Hello.}
{11}{031}{Hello. [You have troubles noticing the man before you. All your thoughts are about the incredibly delicious smell of meat, which is all around the tent. Your mouth is filled with saliva.]}
{12}{002}{Hello. Do you live here?}
{13}{031}{What is it that smells so good in here?}
{14}{045}{So, you are the cook who Seth hates so much?}
{15}{999}{Sorry, wrong tent.}


{24}{}{Yes, that's where I live and occasionaly cook. You can call me Matt. Are you from afar?}
{20}{003}{My name is }
{21}{003}{, I'm an ex-worker from Olympus tower.}
{22}{004}{I'm from Olympus.}
{23}{005}{Yes, quite.}


{30}{}{Pleasure to meet you, }
{31}{}{. You are my first visitor who have been into tower. [Matt pauses for a second, then sighs heavily] In truth, you are my first visitor in a long while... For all the time I'm here.}
{32}{006}{Why no one visits you?}
{33}{030}{Being alone has its advantages.}
{34}{999}{Sad to hear that. Well, see you.}


{40}{}{Oh! You are my first visitor who have been into tower. [Matt pauses for a second, then sighs heavily] In truth, you are my first visitor in a long while... For all the time I'm here..}
{41}{006}{Why no one visits you?}
{42}{030}{Being alone has its advantages.}
{43}{999}{Sad to hear that. Well, see you.}


{50}{}{Welcome to our little community then.}
{51}{039}{I'd like to know something.}
{52}{999}{Thanks. See you!}


{60}{}{I don't talk to almost anyone... We used to live together with my brother. Though we didn't have any visitors back then too, but it wasn't so lonely with the two of us together.}
{61}{007}{Where is your brother now?}
{62}{039}{Don't be depressing. I'd like to know something else.}
{63}{999}{Talk later.}


{70}{}{He lives in a nearby tent.}
{71}{008}{Why don't you live together?}
{72}{017}{So, Seth is your brother?}
{73}{999}{Talk later.}


{82}{}{[Matt suddenly gets furious] Because I hate him!!}
{80}{009}{Why?}
{81}{}{Let's talk about something else.}


{90}{}{Seth despises everyone, caring only about himself. I have been tolerating him all of my life, until one day I got fed up and decided to end this. Now I live separately and don't want to know nothing about him.}
{91}{013}{I'm glad you've found a way out of it.}
{92}{011}{What did he do to you?}


{110}{}{It's more about what he didn't do. Seth never acted like a brother, never complimented me on anything. Not one time. Never gave me support when I really needed it. All he could do is to demand listening to him and do what he says. When I tried to talk to him about what I want to do in life, he just made fun of me, telling me I won't be able to accomplish anything. So, that was the end for us.}
{111}{012}{Maybe that was his way of taking care of you. To keep you out of troubles.}
{112}{014}{Looks like he failed as a brother. But does it mean you have to be angry at him?}
{113}{015}{You're being a real jerk. Set was wrong only in one thing - not beating you up enough.}


{120}{}{That's bullshit! He triet to make me look like a whimp, unable to live without him. He just wanted to feel his superiority. But what did he actually achieve in life? So much ambition with no results. A king of his tent. A president of a toilet.}
{121}{014}{Looks like he failed as a brother. But does it mean you have to be angry at him?}
{122}{015}{You're being a real jerk. Set was wrong only in one thing - not beating you up enough.}


{131}{}{Yeah, well, that's all in the past now. I can finally leave this behind.}
{132}{039}{Let's talk about something else.}
{133}{999}{See you.}


{140}{}{Sometimes I try to forgive him, because I understand how he feels. After our parents died, we were captured by the slavers and sold to the Sunset Jackals. This was hell, especially for Seth. Every new day was making him more angry for everything he had to endure. So, that was our childhood. Then the camp we were held in was destroyed by some warriors wearing strange shiny suits of armor. But Seth was already full of hate by that point, so, I guess now he wants to have revenge on the world, or something similar.}
{141}{021}{Have you tried to talk to him about this?}
{142}{999}{Sad story. I need to go.}


{150}{}{You two are really the same kind. Good luck to both of you.}
{151}{999}{And to you too.}


{160}{}{Good for you. Seth is an egoistic, rude abomination. Stay away from him.}
{161}{039}{Okay, let's change the subject.}
{162}{999}{Right. See you then.}


{170}{}{Oh, so you've met him. Did you find a commond ground?}
{171}{016}{No, we have nothing to talk about.}
{172}{018}{I played along a little. He seemed a little crazy.}
{173}{019}{Yes, I like how he sees things.}


{180}{}{Smart. Don't play for too long though. You'll end up sharing his ideas.}
{181}{009}{As I see, you are not very fond of your brother?}
{182}{039}{Okay, let's change the subject.}


{190}{}{That is just wonderful. What's next on your to-do list? Taking over the world? Another Great War?}
{191}{010}{Don't be ridiculous. Seth just wants to clean this town from filth. I can relate to that.}
{192}{023}{You're going to end up bad anyway.}
{193}{009}{As I see, you are not very fond of your brother?}
{194}{039}{Let's change the subject.}


{200}{}{I wish you both well.}
{201}{999}{And to you too.}


{210}{}{It's like bashing your head against the wall. I don't even want to make peace with him by now, I'm perfectly fine with the way things are.}
{211}{022}{But it's wrong! Family should live in peace. I can help you both.}
{212}{051}{It's okay, I'll bash some brotherly responsibility from this wall.}
{213}{999}{Well, good for you. Bye then.}


{220}{}{Don't bother.}
{221}{999}{I'm still going to try.}


{230}{}{Oh yeah? And what are you going to do? Come on, spill it out! [he puts his hand on his belt, probably, ready to pull his weapon.]}
{231}{025}{Me? Nothing. Everything is Seth's idea. Soon there's going to be an army from an underground settlement of Livos arriving here, which would mean the end of NWO. Seth will lead the takeover - with my personal assistance, of course. That's when you'll regret that you made your brother an enemy!}
{232}{999}{Forget it, nevermind.}


{250}{}{[Matt becomes white, sweating] What?... Oh god, Seth... Just like with the slavers... How could you?! I won't go through it again.}
{251}{}{What the hell are you blabbering about? What underground settlement? Who this idiot is going to lead? You are trying to fool the wrong guy, smart-ass.}
{252}{026a}{There are two options: either I go away and in twenty four hours return with a squad of armed soldiers, who will burn this place to the ground, or you and me come to an agreement and I tell Seth that his plan about Livos has failed.}
{253}{998}{[end]}
{254}{026}{I was just kidding, calm down.}


{265}{}{You... You are insane. I'm not a boy, you know, I have a weak heart. Considering my childhood...}
{266}{039}{Sorry. Let's talk about something else.}
{267}{999}{[end]}


{260}{}{[Matt's face starts trembling. He is whining] I'll give you everything I have, only don't make me go through this nightmare again!}
{261}{027}{500.}
{262}{028}{1000!}
{263}{029}{Uhh... 1500!}
{264}{029}{2000?..}


{270}{}{Take it. Just promise me you won't do this.}
{271}{999}{Deal.}


{280}{}{Take it. Just promise me you won't do this.}
{281}{999}{Deal.}


{290}{}{Oh god... [He is crying] Where do I get such money? [suddenly, he becomes furious] Get out!! Out of here!! I know what he's trying to do, and he is going to get it!!}
{291}{999}{[end]}


{300}{}{You are right. I can stay inside my tent, enjoying to do what I like the most.}
{301}{035}{And what it would be?}
{302}{999}{Let's talk later.}


{310}{}{Oh, I see you took notice! This is my special over-baked ham from Lavash hindquarters. Take a bite, it's just out of the oven.}
{311}{032}{Gladly!}
{312}{033}{From hind... What? Thanks, but I'm not eating the food with such unappetizing name.}


{320}{}{[You try a slice of fragrant meat on a gravy with spices. It melts in your mouth instantly. You become speechless for a next few seconds.]}
{321}{037}{I've never eaten anything tastier.}
{322}{037}{A little bittery, but will do.}


{331}{}{Haha! Hindquarters is a hip part of Lavash. This name was used in old culinary books. Well, if you don't want - suit youself, I won't be forcing you.}
{332}{034}{Meh...}
{333}{032}{Okay, I'm convinced, let me try it!}
{334}{999}{Let's talk later.}


{340}{}{Are you a vegetarian? Sorry pal, I can't help you then. In my menu there's only meat.}
{341}{035}{What do you do here?}
{342}{999}{Okay, let's talk later.}


{350}{}{It could sound a little self-absorbed, but I'm somewhat a reclusive cook. Making food is my only passion in life. I don't understand when people treat food as something they just need to fill their stomachs with. What I really like is to create an unusual mix of flavors from familiar products. Here, for example [he shows you a piece of meat] - this is just a lavah meat, but it's cooked in a really special way. You won't find it anywhere else.}
{351}{036}{How are you doing this?}
{352}{038}{Why people don't know about you around here?}
{353}{039}{I have no time to talk about this. Better tell me something else...}
{354}{999}{Talk later.}


{360}{}{We have plenty of Lavash meat. In addition, I gather rare herbs that I know of. But lately it becomes harder. And to eat only meat all the time is, you know... Tiresome.}
{361}{040}{I could look for new products for you to cook with.}
{362}{039}{I see. I want to ask something else.}


{370}{}{Thanks. If there's even one thankful person, then I don't cook for nothing. [he sadly smiles]}
{371}{038}{Why people don't know about you around here?}
{372}{039}{I want to ask something.}


{380}{}{I don't like to be an eyesore for the locals. This place is not as calm as it looks like... It may seem stupid, but I'm alone, and I have no one to protect me. I'd be better sitting quietly, cooking my favourite dishes, with no one threatening me.}
{381}{036}{Where do you get your ingredients?}
{382}{039}{I see. I want to ask something else.}


{390}{}{What is it that interests you?}
{391}{035}{Tell me about yourself.}
{392}{009}{Tell me about Seth.}
{393}{006}{Why are you so reclusive?}
{394}{999}{I'll ask questions another time. See you.}


{400}{}{You could? [he suspiciously looks around, then whispers] I heard rumors about an underground treasury of food supply. They say that all kinds of pre-war delicacies are kept there! Meat dishes from the creatures that are no longer present in our world, the fruits and the plants you have never seen! You could make a heavenly lunch from these ingredients! But I don't know anyone who is able to tell where this place is...}
{401}{041}{Does it have a name?}
{402}{042}{That's not for me. I don't chase myths.}


{410}{}{Livos. I think this is how it's called. If you find it for me, I will cook the most unbelievable dishes in your life! [he gulps]}
{411}{043}{Deal, I'll try to find the place.}
{412}{042}{No, it seems too improbable to me.}


{420}{}{All that's left for me is to believe in such improbable things. What else can I hope for?}
{421}{039}{Let's talk about something else.}
{422}{043}{Okay, I'll look for your Livos.}
{423}{999}{Cheer up. I'll see you later.}


{430}{}{[Matt brightens up] Thank you so much! Return when finding the place! I'll be ready with a lot of spices by that moment.}
{431}{999}{See you then.}


{100}{}{Get the hell away. I don't talk with Seth's errand boys.}
{102}{}{[leave]}
{101}{043a}{I have a message from Seth. }
{103}{039}{I'd like to know about something.}
{104}{047}{About Livos...}


{432}{}{What this bastard wants?}
{433}{025}{NWO will meet its end for very soon. The army from an underground settlement of Livos is on the way here. Seth will lead the takeover - with my personal assistance, of course. That's when you'll regret that you made your brother an enemy!}
{434}{012}{Seth is worried about you. He wants to protect you, as an older brother. And what is it you do? Running away?}
{435}{044}{Do you know what happens to the snotty brats who run away from home? They get their ass whipped.}


{440}{}{What?!... How dare you...}
{441}{999}{Take this!}

{450}{}{I see this old bastard is spreading rumors about me. It fits him so well.}
{451}{046}{What happened between two of you?}
{453}{999}{I'll come by later.}


{460}{}{You see, Seth is my older brother. He can't just leave me in peace.}
{461}{009}{Why he hates you so much?}
{462}{999}{I need to run, see you around.}


{470}{}{Did you find it?!}
{474}{048}{Yes. Though Livos is not a treasury of foods, but an underground vault for a rich people. }
{472}{050}{Not yet.}


{480}{}{[the happiness on his face disappeares without a trace] So much hope - and now it's lost... Maybe I shouldn't have dreamed about such stupid things. Looks like my fate is to to roast iguanas and steal Lavash meat from the factory...}
{481}{049}{I'm sorry that you had to learn this. Still, don't be sad.}


{490}{}{Thank you for trying to help. Good luck to you.}
{491}{999}{And to you. Bye.}


{500}{}{Too bad, I got excited already. When you find it, don't forget to tell me!}
{501}{999}{Sure. See you soon.}


{510}{}{But please, no assaulting.}
{511}{999}{He is going to get what's coming.}


{520}{}{You have a talent in solving conflicts! Take this, as a sign of gratitude. [Matt hands you the revolver and the weapon repair kit] This belonged to our father. He wanted us to get along with each other. Now it's all yours.}
{521}{}{Thank you! Take care of yourself.}
{523}{999}{If you'll have more problems with him, tell me.}


{530}{}{I don't know how to thank you... You saved us both. Now we are a family again, and we never let stupid grudges to take us apart. Take this, as a sign of gratitude. [Matt hands you the revolver and the weapon repair kit] This belonged to our father. He wanted us to get along with each other. Now it's all yours.}
{531}{}{Thank you.}
{532}{999}{Glad to be of help.}


{540}{}{Hello! It's hard to believe, but now me and my brother have a common goal! When the underground dwellers arrive, I would cook wonderful meals from their ingredients! Thank you for uniting us. Come back to try my new dishes, when you hear the news about the takeover of NWO!}
{541}{}{Come back to try my new dishes, when you hear the news about the takeover of NWO!}
{542}{999}{[end]}


{16}{}{A storm of emotions from this incredible meal increases your maximum health by 5 points.}
{17}{}{So, you're back now, dreamer?}
{18}{}{::sob::}
{19}{}{Now you understand what happens with the ones like you in this world?}
{25}{}{Just die, you old asshole!}
{26}{}{I am so sorry, brother...}
{27}{}{There, there. Stop whining then.}
{28}{}{Damn son of a bitch!}
{29}{}{You asshole! ::sob::}
{35}{}{You came in a wrong tent.}
{36}{}{I have nothing to talk about with my brother's errand boys.}
{37}{}{I don't know how to thank you.}
{38}{}{Thanks for helping us.}
{39}{}{Let's talk later.}
{105}{}{You again. What else do you want?}