##############################
#Локация: НМП
#Имя: Сэм
#Краткое описание: Помощник руководителя НМП
#Дата создания: 05.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see an intelligently-looking ghoul.}
{2}{}{He looks quite peaceful - and surprisingly handsome.}
#
# после знакомства
{3}{}{You see Sam.}
{4}{}{He is rummaging through some papers, as usual.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see an ancient ghoul with peeling skin and some ulcers around his body. He turns to you and smiles - but you feel terrified because it looks like the death itself grins at you in your last seconds.] Hello. What can I do for you? }
{11}{002}{Hello. I'm looking around the town, I'm new here. Just came by to talk.}
{12}{003}{Do you realize that you smell bad, to say the least?}

{20}{}{Well, let's become formally introduced. I'm Sam. Are you here on business? Or just want to talk?}
{21}{010}{I'd like to ask a few questions.}

{30}{}{You got a mouth, I see... However, let's become formally introduced. I'm Sam. Are you here on business? Or just want to discuss my charming pheromones?}
{31}{010}{Uh, okay, let's talk. I want to ask something.}
{32}{004}{Phero-what?}


{40}{}{Oh... Forget it. Do you want something?}
{41}{010}{Yes, I suppose...}
{42}{010}{Yes.}

{1000}{}{Come on then, say it.}
{1001}{}{Hello. Come, let's talk.}
{1002}{}{Here comes our new Leader. I hope you won't flush my life's work down the toilet [he smiles]. Ask me if you need anything. I know every nook and cranny here.}
{1003}{}{Oh, hello! How are you? Have questions? I'm quite busy lately, but I can spare five minutes...}
{1004}{}{Hello. [he looks saddened]}
{101}{054}{Sam, what do you do here?}
{102}{051}{About the problem with the water...}
{103}{011}{There aren't many ghouls around. How did you end up here?}
{104}{019}{Tell me about yourself.}
{105}{020}{Can you tell me something about the town?}
{106}{023}{Sam, I've heard you quarrel with Lucy. Mind to tell me about it?}
{107}{058}{Sam, who is going to be the next Mayor, what do you think? Who do you want to see in this position?}
{108}{059}{How's life, Sam?}
{109}{999}{I need to go, talk later.}


{110}{}{[Sam laughs] I was born here - and died here! And will stay here until I die completely. New World Order is my reason to live, so to say.}
{111}{012}{You probably did a lot to NWO?}
{112}{016}{Is NWO everything you care about?}
{113}{015}{How come you are ghoul? How did you become like that?}
{114}{020}{What else can you tell me about this place?}
{115}{010}{I see. Another question then.}


{120}{}{[Sam looks into the distance] Some time ago, I was the Mayor of this beautiful town. I and my team built this place practically from sand and dust, turning a small settlement into a place known far beyond its borders.}
{121}{020}{And what is NWO now?}
{122}{015}{Why did you leave Leader's position?}
{123}{013}{What happened to your team?}
{124}{010}{Another question.}

{130}{}{They died, every last one of them. From old age, illnesses, hands of bandits. I outlived them all. If only they were alive, my old fellas... We could do so much more! And now you can't even find someone suitable for a Leader of this place, let alone the people with a common goal.}
{131}{018}{The current Leader is no good?}
{132}{014}{Why didn't you continue the work of your team?}
{133}{010}{Let me ask something else.}

{140}{}{Now here you are wrong - all these years I keep helping the development of NWO. Of course, when I was Mayor, I had more... Capabilities. Now I mostly assist Mark, my grandson. Now he's the Mayor.}
{141}{018}{Tell me about Mark.}
{142}{015}{Why did you leave Mayor's position?}
{143}{010}{I want to ask something else.}

{150}{}{When I was Mayor, I got very sick. I thought I won't make it to the end of the week. So, there was a need to elect a new Mayor, and they put my son in my place. For a few months, I was lying delirious, while damned radiation was doing its job. In the end, I didn't die and recovered... If you can call it that [with a smile, Sam points to pieces of skin sagging off his shoulder]. After "recovery" I started assisting my son, and then his son, Mark. You know, it's hard to see your family die... But what can I do about it? Not everyone as "lucky" as I am.}
{151}{018}{What can you say about your grandson?}
{152}{010}{I see. I have another question.}

{160}{}{Of course not. My family is what I care about the most. My town and my family. These two things are interconnected with each other. All our lives are dedicated to NWO, so the development of the town wouldn't stop. Although, lately we have some serious problems... }
{161}{021}{Tell me about your family.}
{162}{023}{What problems are you talking about?}
{163}{017}{Are you willing to develop NWO no matter what?}
{164}{010}{Okay, I'll ask something else.}

{170}{}{Of course! I'd do everything so the town would thrive. I could even apply for the Mayor and continue the legacy of our family. I even want this, damn it! No man here has such vast experience of running this settlement as me. I can handle being the Mayor, even in these sad circumstances.}
{171}{018}{Sad circumstances? What do you mean?}

{180}{}{For now, my grandson Mark is in charge. He is a good Mayor and has done a lot for the town. But he is very sick and won't last long. Mark should name his successor. And there's no one around here who is good enough for succeeding him. For example, his son Daniel is completely incapable of being the Leader. He will ruin everything! And he is a good kid, but still very light-headed. So, until he's ready, I could lead the settlement. That's what I want.}
{181}{022}{Tell me more about Daniel.}
{182}{021}{What else can you say about your family?}
{183}{010}{Okay, let me ask something else.}

{190}{}{Uh, what can I say about me... I devoted all of my life to my family and my town. I think nobody else has done so much for NWO as myself. And I love my family very much, although not everything great in it. Because of some of its members...}
{191}{023}{Who do you mean?}
{192}{020}{What can you tell me about NWO?}
{193}{010}{Let's get back to other questions.}

{200}{}{New World Order is the best place in the whole Radius. Its name reflects all the main principles we follow. Firstly, Order. We maintain peace here, ensured by our guards. Secondly, New. We are creating a new society, where anyone could feel protected and confident in his future. Thirdly, World. Our ideas and principles go far beyond us, there are more and more people in other places who support our worldview. It is possible for us to become a center of a New World, and that's what we are aiming for.}
{201}{010}{I see. I want to ask something else.}

{210}{}{Моя семья - это все, что у меня есть. Марк, мой внук, Люси, его жена, черт бы ее побрал, и Даниэль, мой правнук. Хотя, он не совсем мой правнук.}
{211}{018}{Расскажи о Марке.}
{212}{023}{Что ты расскажешь о Люси?}
{213}{022}{Я хотел бы услышать о Даниэле.}
{214}{010}{Я хотел о другом спросить.}

{220}{}{Daniel is a good kid, but he's very young. He needs to learn so much - but all he does is petty pranks all day long. I don't mind for him to become Mayor after Mark, but now he is not ready at all. And if he won't get his mind right - I won't let him become the Mayor. Even if I have to resort to extreme measures.}
{221}{023}{Why do you think Daniel is not ready?}
{222}{027}{Do you mean you are ready to kill Daniel?}
{223}{010}{I see. Another question then.}

{2301}{}{[Sam becomes moody] Lucy... Mark's wife. The problem is that she is a brainless stupid chick. I was actually against Mark marrying her... She didn't let him raise his son in the ways that Mark himself was raised. So, Daniel grew up not capable of being a Mayor at all. I wouldn't allow Lucy to tend the Lavash, let alone raising a son! She treats Danial as a little child, not letting him make the decisions by himself.}
{2302}{}{We have our problems, but the situation with Lucy gets better every day. I think soon we'll forget we were quarreling. For that, I thank you.}
{2303}{}{We have our problems, but the situation with Lucy gets better every day. No open conflicts anymore. Although, Lucy tries to sit on my head, making me help her to do dirty little jobs...}
{231}{024}{It seems like you hate her.}
{232}{025}{Sam, did you try to make peace with her?}
{233}{010}{I want to ask something else.}

{240}{}{No, I don't hate her. But I don't love her either. If Mark married her, then it's his problem. If she wouldn't interfere with raising Daniel, everything would have been alright. And also - she sleeps with everyone. And that is noticed by everybody, except Mark. We have huge fights with her lately... As you see, I'm not fond of her at all. But if she would come and try to make peace, I'd consider doing it. The family must live in peace, after all. }
{241}{025}{Didn't you think about making the first step yourself?}
{242}{010}{Yeah. I better ask something else.}

{250}{}{[Sam raises voice] You wish! I'm not going first to that windbag! The truth is on my side, and I won't let her do things she does in front of Mark and Daniel!}
{251}{010}{Maybe you're right. Let's change the subject.}
{252}{026}{Sam, maybe Lucy is not faithful to Mark, and she doesn't have a lot of brains, but she is a devoted mother. She would do anything for Daniel, and you know that. Nobody is perfect. For peace in a family, somebody should make compromises. Try to talk to her. The quarrel makes things only worse.}
{253}{047}{Sam, you will go and try to make peace with her. Or I'll tell everyone that you are stealing batteries from the treasury.}

{260}{}{You know, maybe you're right. The family always comes first - and I am willing to humiliate myself to maintain peace in it. Okay, I'll try talking to Lucy. Thank you for helping me to realize this, you deserve my respect.}
{261}{010}{The right thing to do! I want to ask something else.}
{262}{999}{That's really great. Okay, I need to go, bye.}

{270}{}{[Sam laughs] Of course not! I'm not going to kill Daniel! By extreme measures, I mean a completely different thing. I know something that won't allow Daniel to be put in charge, heh-heh. And I'm ready to use this knowledge, even if it will harm both Mark and Daniel. I'm willing to do that if NWO's future would be threatened - but I still want to consider other options of resolving the situation.}
{271}{028}{What knowledge are you talking about?}
{272}{029}{What knowledge are you talking about?}
{273}{030}{What knowledge are you talking about?}

{280}{}{Hah, aren't you a smart one. Do you really think I would tell this to anyone? I have enough problems on my plate, because of a certain someone. I don't want to make it worse. If you earn some of my respect, I would consider telling you.}
{281}{023}{Who is the certain someone, the cause of your problems?}
{282}{010}{Okay, I'll try to earn some of your respect. And now I want to ask a question.}
{283}{999}{I'll try to earn some of your respect. I'll go think about it.}

{290}{}{You helped me make peace with Lucy, so I'll tell you a secret. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!}
{291}{010}{Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}

{300}{}{You think you can threaten me with that story about stealing batteries and then ask me to trust you a secret? You get no respect from me for your actions, so I won't tell you anything. Despite making peace in our family, you should put a lot of effort to earn my respect.}
{301}{031}{How can I do it?}

{310}{}{Respect is earned through actions. For now, you did nothing. Tell me, why should I respect you?}
{311}{033}{I have trained a lot, so I'm in perfect physical shape.}
{312}{037}{I'm very smart and acute. I read a lot and learned many things.}
{313}{032}{I'm highly skilled in weaponry, I had a lot of practice.}
{314}{050}{I am pretty good at medical science, can give some advice.}
{315}{040}{I'm great with technical stuff, I know much about working with mechanisms.}
{316}{041}{How can I prove that I deserve some respect?}

{320}{}{[Sam cringes] As any bandit in Radius. I don't respect solving problems by force.}
{321}{010}{Too bad. Another question then.}

{330}{}{Well, a healthy mind means a healthy body. Show me what you're capable of. Do something.}
{331}{034}{I'm ready! [demonstrate your physical capabilities]}
{332}{035}{I'm ready! [demonstrate your physical capabilities]}
{333}{010}{I'm not quite ready now. I better ask some questions.}

{340}{}{[You do a somersault and some other tricks, demonstrating your great shape. Sam observes you, looking surprised] Impressive. You definitely put some work into your body. This deserves respect. }
{341}{036}{Told you! So, will you tell me a secret now?}

{350}{}{[You do some easy athletic tricks. Sam chuckles] Hah, not very impressive, actually. Even I can do something similar - if nothing falls off me. No, that's not enough.}
{351}{010}{A pity. Another question then.}

{360}{}{Okay, this proves you put a lot of work into yourself. I think that you have something in you. Okay, listen carefully. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!}
{361}{010}{Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}

{370}{}{Smart and acute - that's a rarity. I have one old intellectual test. Try to pass it.}
{371}{038}{Give me that test!}
{372}{039}{Give me that test!}
{373}{010}{I'm not quite ready now. I better ask some questions.}

{380}{}{[You easily solve every task in the test, even coming up with alternative solutions and recommendations to make the test harder. Sam observes you, looking surprised] Impressive. You definitely put some work into your mind. This deserves respect.}
{381}{036}{Told you! So, will you tell me a secret now?}

{390}{}{[You spend a lot of time on the test and fail to solve some tasks in it. Sam chuckles] Hah, not very impressive. The most interesting questions are skipped. No, that's not enough.}
{391}{010}{A pity. Another question then.}

{400}{}{[You help Sam to figure out details in a blueprint of an old piece of machinery, giving recommendations about how to optimize it. Sam observes you, looking surprised] Impressive. You definitely put some work into your skills. This deserves respect.}
{401}{036}{Told you! So, will you tell me a secret now?}

{410}{}{I don't even know... Although, there is one thing you can do for me...}
{411}{042}{Which one?}

{420}{}{[Sam stumbles, not answering for some time] You already know that the batteries keep disappearing from the treasury. If you'll spare me two hundred more of them, I'll tell you everything.}
{421}{043}{Of course, I have a lot of this stuff. Here's two hundred, for your healthcare.}
{422}{044}{I don't have so many.}

{430}{}{[Sam takes batteries and stashes them] You are a rich person. This deserves respect. Considering local poverty, it is an achievement. Most people spend everything on alcohol and narcotics. They are not capable of saving even small sums.}
{431}{046}{So, what's about that secret?}

{440}{}{[Sam gives you despising look] I knew it. You are just like everyone else. Living in the moment, not thinking about the future. }
{441}{045}{I will bring you the amount! Just give me more time. }

{450}{}{Well, you know where to find me. If you are capable of saving the necessary amount for me, I'll tell you a secret. Although I really doubt you could do it.}
{451}{999}{Okay, I'll go look for batteries.}

{460}{}{Okay, I'll tell you. The thing is - Daniel is not Mark's son! Lucy had an affair with Dan before Mark, the son even named after his father. If Mark learns about it, he wouldn't put Daniel in Mayor's position. And I would become NWO's Leader again!!}
{461}{010}{Oh wow, that changes things. Thanks for trusting me, Sam. I'd like to ask about something else.}

{470}{}{[Sam freezez] Damn... I knew sooner or later someone would find out... }
{471}{048}{For now it's only me. And I won't tell anyone - but only if you'll make peace with Lucy and do what she tells you. It will be better for your family.}

{480}{}{[Sam gets angry] I won't go to her, I won't apologize! She sleeps with everyone! }
{481}{049}{You will. You have no choice, if you want to keep stealing the batteries for your medications.}

{490}{}{[Sam lowers his shoulders, saddened] Okay... I'll talk to her. But no one should know about stealing.}
{491}{010}{That's better. It will be our little secret. Now, to other questions.}

{500}{}{[Sam carefully listens for your recommendations about taking care of the skin to prevent decaying] Impressive. You really are a specialist. I respect that.}
{501}{036}{Told you! So, will you tell me a secret now?}

{510}{}{Did you find out the reason behind the quality of water from Livos?}
{511}{010}{No, I'm still working on it... I wanted to ask something else.}
{512}{052}{Yes, I know the reason.}

{520}{}{And? What is it?}
{521}{053}{Due to the large quantities of exported water and increased usage of their water filter, they resorted to another option of water processing - charcoal filters. That's where the taste comes from.}

{530}{}{I see. So, the water is alright, no need to worry. We used the same kind of filtering before until our filters went out of order. Here. Thanks for solving this. [Sam gives you a bag of batteries]}
{531}{999}{Thanks, it will come in handy.}
{532}{999}{Thanks, but no need. I'm glad to help.}
{533}{999}{Thanks, but to take care of the town's prosperity is my duty as a Mayor. Put the money into other needs.}

{540}{}{My main mission is to assist the current Mayor to run NWO. Also, I'm supervising the water shipments from Livos. }
{541}{055}{Do you need something for me to do?}
{542}{010}{I see, Another question then.}

{550}{}{I guess I do have something for you. Livos regularly supplies us with water of great quality, there were never any problems with it. But the last batch worries me. }
{551}{056}{Is there something wrong?}

{560}{}{Water has some taste, which wasn't there before. So, I need to find out the reason behind it.}
{561}{010}{I'm not interested in such a job for now. I have other questions.}
{562}{057}{Okay, I'll look into it.}

{570}{}{Good. Go to Livos, find out the reason. Tell me when you do. I can show you this place on your map. Also, I'll show you the Tin Industries factory's location. It's my present to you.}
{571}{999}{Thanks. Mark it on the map, please.}
{572}{999}{I know where to go. I'll come to Livos and find out everything I can.}

{580}{}{I suppose Lucy will do everything she can to put her son in Leader's position. This will bring us nothing good. As for me, it's I who should run this place, until he comes to a right mind.}
{581}{010}{I see... Another question then.}
{582}{999}{Understood. Thanks for your honesty.}

{590}{}{Quite good. I hope you are not going to make a lot of changes here. I'd like to remind you that I am your advisor.}
{591}{}{We have a lot of things to do. Big plans! }
{592}{}{I am saddened. I hope this little jerk will become smart faster than I think. }
{593}{060}{About that job...}
{594}{073}{Do you need any help?}
{595}{074}{Come on, don't be so sad!}
{596}{999}{I need to run. Lots of work!}

{600}{}{Yes?}
{601}{061}{I don't need an advisor anymore. You are free to go. }
{602}{072}{I'd like you to run the town full-time, while I'm busy with other matters.}
{603}{066}{You know, I don't like ghouls much...}

{610}{}{[Sam hangs his head. He stays silently, gazing at his holey shoes.]}
{611}{062}{Come on, I was just joking.}
{612}{063}{You can live here. But you should find another job. }
{613}{063}{Get out of my sight.}
{614}{065}{Get out. Better if I won't see you around this town in twenty-four hours.}

{620}{}{[He eyes you with a very discouraged look.]}
{621}{999}{Relax. I'll try not to make jokes like this anymore. Come to your senses, I'll run by later.}
{622}{999}{This kind of stress keeps you in shape. Come to your senses, I'll run by later.}

{630}{}{But...}
{631}{999}{That's my order. Now get lost.}
{632}{064}{Keep talking - and I send you to beg for batteries in other towns.}

{640}{}{[Sam steps back. He is smudged, scraped off, chewed, and spat away to the roadside of life. He hunches and walks out somewhere.]}
{641}{999}{[end of dialogue]}

{650}{}{[He becomes as white as it is possible for a corpse. It seems he still didn't realize what he just heard. But his face already expresses devastation and depression] Why?}
{651}{999}{Just get out of here. I want you out of town in twenty-four hours. Hear me?}
{652}{999}{Just get out of here. Before you go, you can take your monthly payment from the treasury. Tomorrow you'd better not be here. }

{660}{}{Is it a problem?}
{661}{067}{Yes.}
{662}{069}{I don't know yet. We'll see.}

{670}{}{So, what are we going to do with it?}
{671}{068}{Nothing for now. I just want you to know that I despise you.}
{672}{063}{For starters, let's change your occupation. I think you will be just fine doing the job of a conveyor worker.}

{680}{}{Is that it? }
{681}{999}{Yes. You can go back to your petty rat duties. }

{690}{}{If that's all, can you don't distract me anymore? I'm trying to take care of the town here, solving problems. Important stuff.}
{691}{071}{Good for you. Pat yourself on the back.}
{692}{070}{I see you don't show enough respect to your management...}
{693}{999}{Yes, I think you can deal with all this shit while I take a rest.}

{700}{}{It is mutual.}
{701}{063}{Okay, if you put it like this... I think it's time to change your occupation...}

{710}{}{What?}
{711}{063}{I said I have a prize for you. A new job. }
{712}{999}{Nothing. Don't get too comfortable. And go, deal with all this shit already. The town has a fuckload of problems, they need you to deal with them. Do your job while I didn't find someone to replace you.}

{720}{}{Of course, I'll do my best. For now, I'm trying to smooch things. People ask questions, they are worried. After I deal with that - and it will take some time - we could think about expanding the town, building additional bays for the factory, and organizing new caravan routes. I'll let you know.}
{721}{999}{Great. keep me posted.}

{730}{}{Oh, no, thank you. I think I'm the one who should do the work. But thank you for the proposition, I'll keep that in mind. And now you'll have to exuse me, I have a lot of things to take care of.}
{731}{999}{Yeah, sure. See you around.}

{740}{}{Is that humor? [he rolls his eyes] Okay, you have to excuse me, but I can't talk right now. I need to make preparations for repairings of "Master's palace". }
{741}{999}{Sure, good luck.}

{750}{}{You have a thought stuck in your head that you should have taken the money. His gratitude has no physical value, after all...}
{751}{}{Huh?.. [looks through you]}
{752}{}{Huh?.. Yeah, I'm just working...}
{753}{}{Yeah, yeah, sure... As you say...}