##############################
#Локация: НМП
#Имя: Сэт
#Краткое описание: Заносчивый сноб и самодур, часто откровенный грубиян. Считает своего брата инфантильным, витающим в облаках дурнем. Ненавидит НМП, называет всех его обитателей дикарями. Считает, что Мэт не оказывает ему должного уважения как старшему брату. Мечтает о руководящей должности не ниже среднего ранга после захвата НМП. Сэт образован, но это не делает общение с ним приятным.
#Дата создания: 28.09.2014
##############################
#Для игры "Олимп 2207"
#Руслан Арсланов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a crooked man.}
{2}{}{He watchfully gazes on his tent's entrance, squirming on everyone who comes by.}
#
# после знакомства
{3}{}{You see Seth.}
{4}{}{The president and only citizen of his tent.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{My god, what an arrogant man!}
{11}{}{What do you think you're doing?!}
{12}{}{Look at this boor!}
{13}{002}{Are you talking to me?}
{14}{999}{I'm already leaving.}

{20}{}{Do you see somebody else? It's you who barges into my tent like it's your property!}
{21}{014}{What's so special about this tent?}
{22}{003}{Sorry to bother you.}
{23}{998}{Nobody dares to speak to me like that. [punch his face]}
{24}{999}{Screw you. Everybody here walk wherever they want. [leave]}

{30}{}{I'm surrounded by barbarians! Manners and politeness are forgotten completely! "New World Order" - ha! More like "Wild Bunch of Savages". The world, the order, the human nature - everything is gone to shit.}
{31}{004}{This is the most civilized town I encountered. There are places much, much worse.}
{32}{998}{Who do you call a savage?! [punch his face]}
{33}{999}{I'd better go...}

{40}{}{I don't care about other places. Now you are in MY tent and you are listening to ME.}
{41}{005}{Why?}
{42}{999}{I'm already leaving.}

{50}{}{Because my tent is my sovereign territory. And in here, my laws and my rules are applied.}
{51}{006}{What rules?}
{52}{998}{[punch his face]}
{53}{998}{No, smart-ass, actually the other rules are applied here. Here's one: you are getting your face punched.}
{54}{999}{I'm leaving your sovereign territory.}

{60}{}{People here are ought to know manners, respect elders and act like a human! Do you hear me? H-u-m-a-n, not some mindless savage! And stop looking around! I have a hunch on petty thieves. Don't you dare touching my stuff!}
{61}{007}{Sounds reasonable. I accept those rules.}
{62}{998}{That's it. That was the last drop of my patience.}
{63}{999}{Screw you! [leave]}

{70}{}{Oh, he accepts those rules! Of course you do! And call me "master Seth"!}
{71}{008}{Yes, master Seth.}
{72}{998}{[punch him into stomach as hard as you can]}
{73}{999}{[leave]}

{80}{}{[Seth ponders] Here's the thing... I see that you are not completely lost. You can be valuable. If you complete my assignment, I'll appoint you my personal assistant. Interested?}
{81}{009}{Interested.}
{82}{020}{Not interested.}

{90}{}{First you need to swar not to talk about this to anyone. Anyone! Especially to this sly cook from that tent opposite of mine.}
{91}{011}{Deal. So, what's the assignment?}
{92}{999}{I need to think about it.}

{110}{}{So. Somewhere in Radius, an underground settlement of Livos is situated. An intellectual elites on the New World live there. They are educated, respectable and cultural people. I heard a rumor that they are planning to take over the NWO. [Seth's face becomes brighten up for a moment] It's time to show these savages where they belong! }
{111}{012}{[keep listening]}
{112}{021}{I see. Not interested.}

{120}{}{Go there and talk to their leaders. Tell them that they won't make it without an inside man. Tell them that I'm willing to help and ready to be their official representative here. When their troops arrive, I'll help them establish here and deal with the locals in the shortest possible time. Of course, I'm counting on a position in middle management or higher for this. I suppose it's obvious.}
{121}{013}{Deal.}
{122}{022}{I need to think about it.}
{123}{020}{No, I won't involve myself into this.}

{130}{}{Wonderful! But keep your mouth shut! Don't tell it to that cretin from nearby tent.}
{131}{999}{See you soon.}
{132}{022}{I have some questions.}

{140}{}{What?! How you even dare! You are stepping on a sovereign territory, on my land! It's an outpost of New World! It will be the place from which the expansion of a new civilization starts!}
{141}{015}{Stop goofing around, old man. It's just an old tent.}
{142}{006}{I see. And what are the rules around here?}
{143}{999}{I'm leaving your sovereign territory.}

{150}{}{Watch your mouth, you little shit! No one allowed you to yank! Either listen to what I tell you, or get the hell out of here!}
{151}{016}{Okay, relax. It is your sovereign territory. So what?}
{152}{998}{Okay, but I'm going to punch your face before leaving.}
{153}{999}{Consider that I've never been here. [leave]}

{160}{}{Good boy. You can call me Seth. If we come to agreement, we could work out something beneficial for both of us. Who are you and where are you from?}
{161}{017}{My name is }
{162}{017}{, I'm from Olympus tower.}
{163}{018}{I am an ex-worker from Olympus.}
{164}{019}{It doesn't matter.}

{170}{}{Is that so? Well, pleasured to meet you, }
{171}{}{. I need some assistance with one job. It's hard and requires responsibility. Personal benefit is guarenteed. Interested?}
{172}{009}{Interested.}
{173}{020}{Not interested.}

{180}{}{Is that so? You got pretty far from tower. Well, pleasured to meet you. I need some assistance with one job. It's hard and requires responsibility. Personal benefit is guarenteed. Interested?}
{181}{009}{Interested.}
{182}{020}{Not interested.}

{190}{}{Don't want to talk? As you wish. I need some assistance with one job. It's hard and requires responsibility. Personal benefit is guarenteed. Interested?}
{191}{009}{Interested.}
{192}{020}{Not interested.}

{200}{}{I was never really counting on you, barbarian scum! Get the hell out of here!}
{201}{998}{Okay, but I'm going to punch your face before I leave.}
{202}{999}{[leave]}

{210}{}{Of course... Is there anything interesting for a dirty savage?! Get the hell out! You'll regret not taking my side, when you had the chance!!}
{211}{998}{Okay, but I'm going to punch your face before I leave.}
{212}{999}{[leave]}

{220}{}{Oh you need to think about it! [you see how contemptuous he is. You can see the terrible amount of effort he's making to not send you off to where the sun doesn't shine] What is there to think?}
{221}{}{What is bothering your wise head?}
{222}{023}{Where did you get the information about takeover of NWO?}
{223}{025}{Frankly speaking, the thought about occupation of NWO by dwellers of an underground settlement sounds ridiculous.}
{224}{027}{Why do you hate locals so much?}
{225}{030}{What did the guy in the nearby tent do to you??}
{226}{054I want to talk about Matt.}
{227}{999}{I need to go.}

{230}{}{I can't reveal my sources, and it shouldn't concern you. NWO is a bunch of helpless hobos, doomed to be enslaved. Someone should do it, sooner or later. Possibly, it would be Livos.}
{231}{024}{What if I tell Mark about this?}
{232}{025}{Honestly, it sounds a little crazy.}
{233}{022}{I see. I want to ask something else.}

{240}{}{Have you thought this through? This selfless ape will laugh right into your face, and should you insist, he will throw you out of town for an attempt to cause panic. But try it anyway, don't be afraid. Good luck to you.}
{241}{022}{I still have some questions.}
{242}{999}{We'll see about that.}

{250}{}{NO ONE ASKED YOU WHAT YOU THINK! SHUT UP AND DON'T TRY DOING THINGS YOU ARE NOT CAPABLE OF!! THE ONE THING YOU SHOULD DO IS TO FIND THE UNDERGROUND SETTLEMENT, AND POLITELY, DAMN YOU, TELL THEM MY MESSAGE! THAT'S IT!}
{251}{999}{Okay, I get it.}
{252}{026}{[interrupt him mid-sentence]}
{253}{022}{I have some other questions.}

{260}{}{[You don't let Seth finish his speech. Taking a good swing, you... ]}
{261}{998}{[...tear his spleen open with a single blow.]}
{262}{998}{[...knock out a handful of his teeth.]}
{263}{998}{[...punch his Adam's Apple right into his throat.]}
{264}{998}{[...turn his nose into mush of bone shreds and blood.]}
{265}{998}{[...give him an uppercut to the chin, breaking his neck.]}
{266}{998}{[...break his rib with a sharp blow.]}
{267}{998}{[...blow his eye right out of his eye socket.]}
{268}{998}{[...hit him into a solar plexus.]}
{269}{999}{[...stop yourself. Then take a deep breath and calm down.]}

{270}{}{[Seth quietly sighs and continues in a patronizing tone] Yes, some simple things can be complicated, and sometimes even beyond the reach to the one of your kind. You see, I don't actually hate them. I only call the things by their names. Whether you like it or not, NWO is a herd of cattle. A herd of brainless, stinking cattle, which doesn't know respect, doesn't care for science or art. These things are way beyond their level. Cattle by itself is not capable of making this world a better place. The cattle has only one purpose - to serve the higher power on its way to prosperity. A quite worthy purpose, by the way. But cattle has been without its herder for too long. He became prideful and wants power which it can't handle. Try to show the cattle its place - and it will stomp you to death.}
{271}{028}{[keep listening]}
{272}{022}{I see. I wanted to ask something else.}
{273}{999}{I'll listen to the rest of it some other time. [end]}

{280}{}{In the chaos of our world, cattle fights itself and other herds of the same cattle. But as all chaos seeks harmony, sooner or later the master comes for the cattle. And cattle begins to serve, fulfilling its purpose. Try to understand, I don't hate NWO at all. I'm just obliged to live near them and tolerate their smugness, ingnorance, sass and untidyness. I am patiently waiting for the master to come for his cattle. And soon my patience will be rewarded.}
{281}{029}{Your worldview disgust me, but to discuss it with you disgust me even more.}
{282}{999}{Maybe you have a point.}
{283}{022}{I still have some questions.}
{284}{999}{See you soon.}

{290}{}{[Sam grits his teeth and hisses, bulging his eyes] You know what, you, offspring of a nameless wench?! You can go and TALK about it WITH THE PILE OF MANURE OR A PUDDLE OF PUKE!! DO YOU HEAR ME, YOU, ARROGANT, PIG-FACED SAVAGE?!}
{291}{999}{[leave silently]}
{292}{026}{[interrupt him mid-sentence]}
{293}{022}{I have some other questions.}

{300}{}{It's a local lunatic, yet a very cunning manipulator. I advise you to avoid dealing with him. Before you know it, you'll be dancing to his tune, getting yourself in trouble.}
{301}{}{[Looks like Seth is trying to hide something] It's a local lunatic, yet a very cunning manipulator. I advise you to avoid dealing with him. Before you know it, you'll be dancing to his tune, getting yourself in trouble.}
{302}{031}{What exactly did he do?}
{303}{022}{I wanted to ask something else.}
{304}{999}{See you soon.}

{310}{}{Just stay away from him, if you don't want any trouble.}
{311}{022}{I see. I still have some questions.}
{312}{999}{See you soon.}

{320}{}{You wouldn't understand. That cretin never listened to me, never showed me enough respect. Instead, he chose to spend his whole life dreaming about some nonsense. Damn imbecile.}
{321}{033}{I can speak with him. Maybe I could talk some sense into him.}
{322}{034}{I hate little snots who doesn't respect elders.}
{323}{022}{I want to ask something else.}
{324}{999}{I see. See you then.}

{330}{}{Don't even bother. That idiot is convinced that he doesn't need no one. He has a lot of nerve. Life will eventually teach him a lesson. }
{331}{999}{I'm going to try though.}
{332}{022}{I want to ask about something else.}

{340}{}{If you could convince him he's going to be lost without me, you would do him a huge favor.}
{341}{999}{You can count on me.}
{342}{022}{I want to ask about something else.}

{360}{}{[Seth cringes] If I came out of the same womb as this moron, that doesn't mean he's my brother!}
{361}{032}{Why do you hate him so much?}
{362}{037}{Okay, that's not actually my business.}

{370}{}{You're goddamn right. Let's change the subject.}
{371}{022}{I still have a couple of questions.}
{372}{999}{See you later.}

{100}{}{The shits from the town are flowing into my home again... What are you sniffing here, you flea-bitten pup?!}
{101}{}{How's our deal going?}
{102}{038}{Why are you so angry all the time?}
{103}{022}{I have some questions.}
{104}{036}{I know that Matt is your brother.}
{105}{054}{I want to talk about Matt.}
{106}{039}{I got your message to the families in Livos.}
{107}{048}{Here's the thing... You brother, Matt, is looking for Livos too. And, unlike you, he pays me for helping him, instead of giving empty promises...}

{380}{}{Why are you so cretin all the time? Get out of here, stop loitering around my tent!}
{381}{014}{What's so special about this tent?}
{382}{003}{Sorry to bother you.}
{383}{999}{Screw you. Everybody here walk wherever they want. [leave]}
{384}{998}{Nobody dares to speak to me like that. [punch his face]}

{390}{}{Don't leave me hanging. What's their answer?}
{391}{040}{They won't make any alliance.}
{392}{041}{They are ready to make an alliance on your terms.}
{393}{044}{They want to make an alliance with Matt.}
{394}{046}{They want to make an alliance with both you and Matt, together.}
{395}{999}{They are thinking about it. As they make a decision, I'll tell you.}

{400}{}{[Seth spits on the ground]  To hell with these bourgeois!! "High society", my ass! A bunch of filthy snobs, intellectual trash heap! If not them, then others. Why are you still standing there?! Get out, you vagabond scum, you'll get nothing now!! Shoo!! [he waves hand in the exit's direction]}
{401}{998}{Okay, but I'm going to punch your face before I leave.}
{402}{999}{[leave]}

{410}{}{At last! At last this moment has come! The justice, the reward for me being so patient, living near these animals!! When their forces will arrive? Where should I wait for them?}
{411}{042}{Stay where you are, they are going to be here in a few weeks. They didn't tell me the exact moment, but asked you to wait.}

{420}{}{That is just wonderful! I suppose, you are waiting for your reward? Well, I'm the man of my word. As soon as their forces take over this place, you get the position you deserved: a job of my personal assistant. As for now - take this. [Seth hands you the weapon repair kit] This belonged to my father. I don't need it, and I suppose you'll put it to better use.}
{421}{043}{Thanks. Glad to be of help.}

{430}{}{Come back when you hear the good news about NWO! Your job will be waiting for you.}
{431}{999}{Bye then.}

{440}{}{[What... What did you just say?! Come again?!}
{441}{045}{They want to make an alliance with Matt.}

{450}{}{Oh... Oh that damn...  How many times I was gonna kill that bastard, but held back! I thought it wouldn't come to this. What a fool! I should have done it a long time ago... [he pulls out his revolver]}
{451}{999}{What are you going to do?}

{460}{}{I don't understand. What the hell do they want with him?}
{461}{047}{They are demanding you to join your forces first. If you two are not capable of becoming allies in the name of commong goal, how can you be capable of making an alliance with a whole faction?}

{470}{}{Tell me you're joking! I have to tolerate that idiot? Oh, stupid intellectuals! A week won't pass until they realize how wrong they are. This moron is going to do everything as he pleases... [Seth ponders for some time, then sighs] Well, if that's what they demand... }
{471}{999}{Worth a shot.}

{480}{}{I... I can't believe it. Oh you... MINDLESS BASTARDS! CONSPIRING BEHIND MY BACK! THINKING YOU CAN BLACKMAIL ME! ASSHOLES! IDIOTS! MORONS! [Seth spits and wheezes, then starts to whine] Oooooh god, why have you forsaken this world! It's now a land of scoundrels...}
{181}{049}{So, do you want my help or not? Or I can help Matt instead?}

{490}{}{[Seth gets silent. Then quietly asks] How much did he promise you?}
{491}{050}{500}
{492}{051}{1000}
{493}{052}{1500}
{494}{053}{2000}

{500}{}{[Seth hesitates for a second] Here, but remember - they won't help you, if you don't carry out what you promised.}
{501}{}{You are lying! This snot can't possibly have such money! Try to fool me again, and I'll pay you with lead instead!}
{502}{999}{Bye then.}
{503}{022}{I still have some questions.}

{510}{}{[Seth hesitates for a second] Here, but remember - they won't help you, if you don't carry out what you promised.}
{511}{}{You are lying! This snot can't possibly have such money! Try to fool me again, and I'll pay you with lead instead!}
{512}{999}{Bye then.}
{513}{022}{I still have some questions.}

{520}{}{[Seth hesitates for a second] Here, but remember - they won't help you, if you don't carry out what you promised.}
{521}{}{You are lying! This snot can't possibly have such money! Try to fool me again, and I'll pay you with lead instead!}
{522}{999}{Bye.}
{523}{022}{I still have some questions.}

{530}{}{Who do you think I am, you mindless savage?! Who in the whole Radius could have so much money?! Definitely not that degenerate! Try to fool me again, and I'll pay you with lead instead!}
{531}{}{Oh... Oh that damn...  How many times I was gonna kill that bastard, but held back! I thought it wouldn't come to this. What a fool! I should have done it a long time ago... [he pulls out his revolver]}

{532}{999}{Bye.}
{533}{022}{I still have some questions.}
{534}{999}{What are you going to do?}

{540}{}{Don't take too long.}
{541}{032}{What did he do that you are so angry?}
{542}{055}{Tell me more about him.}
{543}{057}{Matt is offended that you don't take him seriously.}
{544}{064}{Here's how it is. I listened to that guy and understood that you antagonized him all your life. Now you'll pay for this.}
{545}{022}{Let's change the subject.}
{546}{999}{Maybe, some other time.}

{550}{}{What can I say about the chump? All his life he is busy with something stupid. Never got anywhere. Now he's thinking of calling himself a cook. Ha! I bet he wants to be famous, to be loved and respected. Like anyone cares...}
{551}{056}{At least he has a dream.}
{552}{054}{I want to ask about something else.}

{560}{}{Exactly! It's everything he thinks about - his dreams. That everyone will respect him for cooking! Idiot! No one in this world cares for your talents! You need to listen to elders and learn from their experience. But you won't get it from him. Damn moron.}
{561}{054}{I want to ask about something else.}

{570}{}{You don't say! Maybe I should take lavash shit seriously too?}
{571}{058}{You think too much about yourself. Meanwhile, you don't have a half of what Matt has.}
{572}{060}{Think about him: he needs help, care and protection of his elder brother. He won't make it alone.}
{573}{063}{Look at yourself: you dream about power, so everyone would be afraid of you, but can't earn respect of your own brother.}
{574}{061}{He told me that he would kill himself if you won't make peace.}

{580}{}{Is that so? What is it that I don't have?}
{581}{059}{Dream, talent and determination.}

{590}{}{Oh Holy Mary, how could I live without it! Let's see how his talent helps him, when he and the rest of the savages will be thrown over the fence.}
{591}{062}{But why...}

{600}{}{So that's his own fault! Let him handle it!}
{601}{062}{But why...}

{610}{}{The scamp wants to make me feel sorry? It's useless. Let him do one brave thing in his life. I won't be mourning him - he's no more than a slime to me. }
{611}{062}{But why...}

{620}{}{This conversation is over, don't start it again.}
{621}{999}{[end]}

{630}{}{[Seth gets silent for a minute] So that's what it comes to... How could I let this happen? What have I become? Why are we doing this? I need to see my brother immediately.}
{631}{999}{end}

{640}{}{What?...}
{641}{999}{Get this!}

{650}{}{If not Livos, then somebody else will come for this cattle someday. I'll be waiting.}
{651}{999}{[end]}

{700}{}{Come back when you hear the good news about new power in NWO! Your job will be waiting for you.}
{701}{999}{Can't wait to see it.}

{800}{}{[You see Seth crying over the dead body of his brother. His hands and clothes are covered in blood] Oh my god, what have I done...}
{801}{081}{What happened here?}

{810}{}{He shot himself. My brother... My only brother... How could I... [he sobs] If only I could turn back time... If only I had said what I... Why? Why was I so harsh to him?... [he sobs again]}
{811}{999}{[end]}

{900}{}{Thank you for finishing the business. I respect the ones who can do the job properly. Here [Seth hands you the revolver, which he killed Matt with] A great tool to put an end to things.}
{901}{}{Thank you for finishing the business. I respect the ones who can do the job properly.}
{902}{999}{Glad to be of help.}

{950}{}{Although it all ended up not as I wanted, I am still thankful for your work. Here, take this as a token of gratitude. [Seth hands you the revolver and the weapon repair kit] We are a team now. And, to be frank, I'm very glad it turned out this way.}
{951}{}{We are a team now. And, to be frank, I'm very glad it turned out this way.}
{952}{999}{Glad to be of help.}

{960}{}{Thank you for helping us understand the most important thing. If it wasn't for you, we'd be lost. Here, take this as a token of gratitude. [Seth hands you the revolver and the weapon repair kit] This belonged to our father. He wanted us to get along with each other. Now it's all yours.}
{961}{}{Thank you for helping us understand the most important thing. If it wasn't for you, we'd be lost.}
{962}{999}{Glad to be of help.}

{5}{}{You're filled with contempt for agreeing with Seth. You remember where you came from, and feel like some part inside of you had died. Some part of you, on which you used to rely on.}
{6}{}{Die, you little shit!}
{7}{}{Shoot. I always knew it would come to this.}
{8}{}{Listen to me, Matt. Yes, we can't stand each other. But we have to unite for the common goal.}
{9}{}{And you would listen to my opinion?}
{15}{}{I will, if you would listen to mine.}
{16}{}{Deal then.}
{17}{}{Let's do it.}
{18}{}{I'm sorry, Matt.}
{19}{}{Seth, is it true that no one cares about us?}
{25}{}{Yes, Matt. I have only you and no one else.}
{26}{}{What are we doing? *sob*}
{27}{}{I'm sorry I was such a fool.}
{28}{}{And I'm sorry I didn't listen to you.}
{29}{}{It's all right, Matt...}
{34}{}{Damn, it hurts...}
{35}{}{It hurts so much...}
{36}{}{Ooooh... Pain...}
{37}{}{Matt, please forgive me for torturing you.}
{38}{}{He got what was coming. He won't be showing off anymore. Right, Seth?}
{39}{}{Uh-huh...}
{43}{}{So be it. You are forgiven.}
{44}{}{Damn Livos! Who do they think they are?!...}
{45}{}{...They will pay for this decision...}
{46}{}{It's okay, time will tell who is right!...}
{47}{}{Why, brother?}
{48}{}{God, why was I such a fool!?...}
{49}{}{Why? Just - why?...}