##############################
#Локация: НМП
#Имя: Сайрен
#Краткое описание: Разведчик-трус НМП
#Дата создания: 17.06.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a scout. He is wearing strange armor.}
{2}{}{His armor is covered in patches, holes, and metal plates. He holds his chin high.}
#
# после знакомства
{3}{}{You see Cyren.}
{4}{}{Looks like his armor got new patches, holes, and... Amulets?}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
#Node001
{10}{}{[You see a man in his thirties, wearing a smug smirk on his face. A couple of big scars on his cheeks and battered equipment identify him as someone who's been in trouble more than several times. He looks down upon you] Yes? Did you want something?}
{11}{002}{Hello. I'm just looking around, making friends...}
{12}{002}{Hey! I'm new here. Looking for someone to chat with.}
{13}{002}{I'm walking here, back and forward. Want to talk.}

#Node002
{20}{}{Hah, let's get acquainted then! I'm Cyren, the best scout in NWO! I rarely see new ones here.}
{21}{010}{A pleasure. Can you answer a few questions?}
{22}{010}{Hey, can you answer some questions?}
{23}{010}{I want to ask you a question.}
{24}{999}{I'm in a hurry, see you.}

#Node010
{100}{}{Hey, glad to see that you're okay.}
{101}{}{Sure, go ahead and ask.}
{102}{011}{What are you doing here?}
{103}{018}{Where did you get these scars?}
{104}{021}{Do you have something to trade with me?}
{105}{023}{There you are! So, why did you run away at the first signs of danger?}
{106}{024}{Hah, you didn't flee as I thought you would. Great run, was fun!}
{107}{022}{Where have you been? I was looking for you! For a long time!}
{108}{025}{It was a great run! You keep your balls for now.}
{109}{999}{Okay, see you.}

{117}{011a}{You must have heard about the changes in leadership here. What do you think, could Sam handle it?}

#Node011
{113}{}{[Cyren gives you a conceited smile] I am a scout. The best one around, mind you. Ask anyone, you'll see. I take the missions which couldn't be handled by others, the most dangerous and difficult ones.}
{110}{012}{Sounds very impressive. You must be a real pro in your business.}
{111}{012}{Cool. You must be good.}
{112}{012}{Whoa!! So cool!!! You must be the best!!}

{114}{}{Sam? Sam, the ghoul? I dunno [he takes a look of importance] On one hand, he is quite dead, isn't he? On the other, he is very experienced in leading people and knows what's what here. Let's put it like this - I won't say "no" or "yes", but if everyone else supports Sam, I definitely won't be against it.}
{115}{010}{What a firm and determined position! Okay, I want to ask something else.}
{116}{999}{I'll write it down. Need to go, see you.}

#Node012
{120}{}{[Cyren's smile becomes wider] Of course. I am well-known in all of NWO! Ask my friend, Blanca, for example. She loves to tell stories about me. And everything she says is true. [he makes a short pause, leans closer to you, and whispers] I'm even not telling her everything, because she wouldn't let me go on missions - it's so dangerous. }
{121}{016}{I'd very much like to know how you deal with all your difficult situations. I could use this knowledge.}
{122}{016}{Tell me, how you deal with problems? I'm curious.}
{123}{015}{Blanca? Tell me more.}
{124}{013}{I want the story about myself too!}
{125}{014}{Blanca?}

#Node013
{130}{}{[Cyren gets to think] Hm... You could come in handy, actually. My partners are sometimes, uh... Disappear. The last one was bitten by a scorpion... The stuff happened. [mumbles] He won't be bugging me with his chit-chat... No one will be looking for him, if he gets lost... [He shows you a wide smile again] You know, let's do a run tomorrow, to the factory! We need some rolls of tin. Big, shiny things. For cans.}
{131}{027}{Sure! Let's do it!}
{132}{999}{Nah, I'll walk by for a while. See you.}

#Node014
{140}{}{Yeah, Blanca. She's crazy about me. And she is not the only one, you know. Go talk to her, if you want.}
{141}{999}{Okay. I'll go to Blanca.}

#Node015
{150}{}{A girlfriend of mine. Follows me all the time. That's understandable - every girl wants to be with me. She should be somewhere around, you can go talk to her... She'll tell you many things. About me.}
{151}{010}{I see. Can I ask?}
{152}{999}{Okay, I'll go find her. See you later.}

#Node016
{160}{}{That's the thing! I usually go with a partner. You know, for little help, to carry things and such. But nowadays you can't find people who are experienced at least half as much as I am. They are rarely capable of handling the danger. I don't even know how many partners I've changed over time. The last one got bitten by a scorpion, poor guy. Died on the spot. And I had such high hopes for him...}
{161}{017}{Do you need a new partner? I'm really good at runs!}
{162}{010}{Yeah, a pity. Can I ask another question?}
{163}{999}{Partners die all the time, you say? I've just remembered something, I need to run!}

#Node017
{170}{}{You? [Cyren glances over you] Nah, I think you won't even make it to the destination point! Although... You know, I'll give you a chance. There is one simple job. We are almost out of the tin for cans, so I need a partner to scout Tin Industries' metalworks factory. We'll take some rolls of tin and return. }
{171}{010}{Nah, I better ask a question.}
{172}{027}{I'm in! }
{173}{999}{No, I won't go there. Okay, see you around.}

#Node018
{180}{}{Man, it was such a long time ago. We got into trouble, me and that what's-his-name, I don't even remember. Explosions, shooting, chase... Only I survived. Got hit by fragments, scarred for life.}
{181}{019}{Hm, looks just like fingernail markings.}

#Node019
{190}{}{What do YOU know about scars, greenhorn! I've been through so much, you could fill several lives! Enough talking, don't want to remember the painful past.}
{191}{020}{Yeah, you must have been very heroic... And why is this armor not of your size? And the name on the tag is scrubbed out... Maybe it's not actually yours?}

#Node020
{200}{}{That's my armor, hear me? And always was! I took it off my dead enemy, killed him with my bare hands! }
{201}{010}{Alright, alright... Another question then.}

#Node021
{210}{}{You picked the wrong person, pal! Do you want me, the best scout around, to do petty trading? Let local wussies handle this. Real men, like me, do a real man's job!}
{211}{010}{Sorry. Another question.}
{212}{999}{Then I'll go search for traders.}

#Node022
{220}{}{You don't understand a thing in the matters of scouting! I decided to go back to pick some things, I was going to find you afterward!}
{221}{026}{Let's go get the tin rolls.}
{222}{999}{Here's your tin! Shiny!}

#Node023
{230}{}{Hey, easy! A real, experienced scout is always capable of wisely assessing the situation, and timely take a step back, planning the maneuver! I was just going to get back to you, to get you out of there.}
{231}{026}{Let's go, we need to try one more time.}
{232}{999}{No need to go anywhere, I've already handled it. Here's your tin, take it and bye.}

#Node024
{240}{}{[Cyren looks tired and broken] Yeah, this was... A good run... [he lift his head up] I got you out of the mess so many times...}
{241}{026}{Let's go look for it one more time.}
{242}{999}{Here's your tin. Bye.}

#Node025
{250}{}{[Cyren looks tired and broken] This is... Encouraging... [he lift his head up] I got you out of the mess so many times...}
{251}{026}{Let's go get the tin rolls.}
{252}{999}{Here's your tin! Shiny!}

#Node026
{260}{}{[Cyren makes a dismissive gesture] No way, I'm not going there. Do it yourself, if you want. I have, uh... Um... More important mission to do!}
{261}{999}{I see, best scout around. I'll search for it myself.}

#Node027
{270}{}{Good. Come to Tin Industries factory, I'll wait for you there. Let me mark it on your map.}
{271}{999}{I'll meet you there.}

#Node028
{280}{}{Hey. I see you made it here in one piece, which is already good. Are you ready? Only let's do it quick. Or we can return to NWO, actually...}
{281}{999}{I'm ready. If you run, I'll tear your balls off! I will find you, hear me? That's it, let's go.}
{282}{999}{I'm ready. Let's go.}
{283}{999}{I'm ready. If you run, I'll tear your balls off. One by one. Now, let's go.}
{284}{999}{Uh-huh. Let's go.}

#Cyren в напарниках у ГГ
{900}{}{Let's deal with this quick.}
{901}{}{Either we go inside, or I go back to NWO.}
{902}{}{No time to talk.}
{903}{}{Come on, let's go already!}

{904}{}{Uhh... I forgot something! I mean, I'll be right back!!}