##############################
#Локация: НМП
#Имя: Скит
#Краткое описание: Завскладом, друг Оуэна
#Дата создания: 30.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a prisoner.}
{2}{}{A suspicious fellow.}
#
# после знакомства
{3}{}{You see Skeet.}
{4}{}{Skeet. He is responsible for warehouse.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a man behind bars. He has a shady look: left eye is squinted, like he's suspicious of something, some of his front teeth are missing. This guy's soft gaze makes you feel depressed. As you want to leave, he starts to talk] Hey, what are you looking at?! Another one in line to spit into my face?}
{11}{002}{Do I need to?}
{12}{003}{Why are you sitting here?}
{13}{004}{Hello, for starters.}


{20}{}{Why are you here? To mock me? You know what, get the hell out of here... [he chuckles, mumbling something]}
{21}{005}{Actually, who are you? And what are you doing there? Come out and let's talk.}
{22}{006}{You are not very talkative, I see.}


{30}{}{Hahahahaahahah! Yeah, right... No, it's a good question, really - I was just thinking about it myself. Waiting for someone to come into senses and let me out of here.}
{31}{007}{What, is this, like, a prison? Caused some trouble and they put you here to think about your behaviour? Oh! Did you kill someone?}
{32}{008}{And how did you end up here?}


{40}{}{Whaddaya want, cheeky boy?}
{41}{008}{The name's }
{42}{008}{. I see you got yourself into some mess. Tell me, don't be shy.}


{50}{}{[He covers his face with a palm of his hand and shakes his head] Oh my god, what an idiot...}
{51}{008}{Why don't you introduce yoursef and get to the point of your problem? I'm getting tired of it. }
{52}{009}{Okay, I'll leave you for now...}


{60}{}{Why the hell would I spill my beans to god-knows-who? [he stops, thinking] Although, what do I lose? Are you really interested in hearing this?}
{61}{008}{Yes. }
{62}{013}{I could try. Or I'll go.}


{70}{}{Not exactly. Someone's been stealing the canned food from warehouse, and I'm the suspect. You know, the warehouse. Near the factory. There's also a room of our sadistic doctor Hinder in it... By the way, I'm Skeet, warehouse supervisor. Guarded, keep in mind, fuckin' warehouse. Fort Knox, my ass.}
{71}{011}{I'm }
{72}{011}{. Any ideas who might be stealing?}
{73}{012}{I really hope you don't put it on some mystical force, do you?}


{80}{}{Man... [he heavily sighs] That's how it is: I'm in charge for the warehouse near the factory, the name is Skeet. The warehouse is full of canned food. [He snaps, raising his voice] Some piece of shit is regularly skimming these cans, and he's doing pretty well at it! Of course, everyone around think it's me. The thefts are still going, even now - but no one is listening to me, let alone desires to help. They say I have an accomplice, so the stealings would continue to happen. [he powerfully spits on the floor]}
{81}{999}{Okay, I'll go and try to find out something. }
{82}{999}{Won't make any promises, but if I learn something, I'll let you know.}


{90}{}{Hey! Where are you going?! Get back here! [he takes pause] Skeet, that's my name. Are you happy? Come back!}
{91}{013}{Oh wow, getting talkative all of a sudden? I'm listening. But don't mess with me this time.}


{110}{}{No. If I knew, I wouldn't be sitting here. And I don't have any fuckin' guesses.}
{111}{999}{Okay, I'll go and try to find out something. }
{112}{999}{Won't make any promises, but if I learn something, I'll let you know. And I think you are pretty tense. Let's try this - I'll go and try to find out things, and you stay here and pull your lever, okay? [leave, listening to his angry screams]}


{120}{}{Holy shoe! Brilliant! This is definitely the doings of witches of the desert!}
{121}{014}{That explains everything! Elementary! One question though, what is it in that pipe you smoking?}
{122}{013}{Enough with the jokes, tired of them. Unlike you, I'm here voluntarily. I step out that door, and you are all by yourself.}


{130}{}{Okay, okay. Listen, some asshole set me up: he steals the cans from factory warehouse at nights, with extreme success, mind that, and everyone else think it's my doing. Even after they put me here, the cans are still getting stolen - and what do they think? Of course, that I persuaded someone to continue doing it, to throw the suspicions off me! And that's all I have to tell, basically... Listen, If you can help in any way that would make me free, I won't forget that.}
{131}{999}{Now we're talking, Skeet. I'll try to help. See you around.}
{132}{999}{Won't make any promises, but if I learn something, I'll let you know.}


{140}{}{Aren't you tired of being a smart-ass? Think about it - someone set me up bloody well, using vulnerable spots of warehouse and its security, masterfully fucking up everyone, including me. }
{141}{999}{Okay, I'll go and try to find out something. }
{142}{999}{Won't make any promises, but if I learn something, I'll let you know.}


{100}{}{Hey there. How is it going?}
{101}{015}{I came up with some questions about that "elusive thief of canned food".}
{102}{016}{Good. Today you are going to be free of all charges.}
{103}{017}{Going? Good. Thought of a couple of jokes...}
{104}{999}{Good, Skeet, and I need to go, so - be seeing you! [laugh]}


{150}{}{Which ones?}
{151}{018}{Think hard, please: how does this thief manage to get into the warehouse?}
{152}{019}{Is there something special I should know while looking for a culprit?}
{153}{999}{No, nothing. I don't really want to know how you lost your teeth. [end the dialogue]}


{160}{}{Wh- WHAT? How?! You are messing with me, man! How is that possible?!}
{161}{020}{Easy - a wild Chimera has been climbing the fence poles, jumping through a hole and getting into a warehouse. After that, obviously, she had been stealing the cans with food, unpunished. }


{170}{}{Spill it.}
{171}{021}{Here's one - the man walks around the desert, thirsty. Suddenly, he notices a sign pointing right, saying "water - 3km". He gets excited, and goes right. Still very thirsty! On hands and knees he makes it to the next sign, pointing left, saying "water - 2km". So, with the last of his strength, he crawls even further, getting to the third sign - it points straight down, saying "water - 1km".}
{172}{022}{For example... Skeet - that's it, behind the bars he sit. Cursing and swearing, not doing shit...}
{173}{999}{Nah, forget it. We'll talk later.}


{180}{}{I dunno... You see, the entrance is guarded, and the fence is not of the kind that you can jump over - it's pretty high. This "someone" is really stealthy, like a kid or something... [he flips] Yeah!! It can be a slick kid! Get his ass, you hear me?! Tear his balls off!}
{182}{999}{I got it, Skeet. I'll go try my luck. And you should calm down.}
{183}{999}{I see you like kids. I'll go check it out.}


{190}{}{Special? Nah, don't think so. The warehouse is heavily guarded, and to get to the territory unnoticed - that is some fantastic shit. So it's all good: the guards are guarding, the fence is fixed recently...}
{191}{023}{Wait. The fence was broken before? For better hearing, I suppose? Tell me details!}
{192}{023}{Oh, you fixed the fence, that's solid. So what, helped?}


{200}{}{[Skeet freezes] Holy shit! What a bitch! Rip them all... To shreds!!}
{201}{999}{Okay, lord of shelves, I'll go tell this to Mark.}


{210}{}{I don't get it.}
{211}{999}{[Shrug] As you say, Skeet. See you.}


{220}{}{Ha-ha. So fucking funny.}
{221}{999}{Haha-ha! There, there. Okay, I need to go, talk later.}


{230}{}{What to say? There was a hole once. We fixed it pretty good -  partially covered it with some junk we had, somewhere even put a new pieces... Why do you care about the fence? Do you think someone could slip through? Even my dick won't fit in, you know. Maybe only in one place there... So, forget it.}
{231}{024}{Skeet, tell me, where is that hole where you put your dick?}
{232}{024}{Tell me where it is - I want to stick mine too.}


{240}{}{Look it up, man! Someone like you would't miss it. I mean, someone as naughty... Mwaahaha!}
{241}{999}{You are not completely sane, are you, Skeet? [leave in search of a mysterious hole]}




{300}{}{[You see a man of shady looks: left eye is squinted, like he's suspicious of something, some of his front teeth are missing. This guy's soft gaze makes you feel depressed. As you want to leave, he starts to talk] Hey, what are you looking at?! Another one in line to spit into my face?}
{301}{031}{Actually, I'm the new Mayor.}


{310}{}{You must be shitting me!}
{311}{032}{I'm here not to convince you, you know.}


{320}{}{Then how about an amnesty for a good old Skeet? I was set up by some scumbag, so I'm sitting here for nothing! }
{321}{033}{Yeah, sure.}
{322}{033}{Tell me details. }


{330}{}{Man... [he heavily sighs] That's how it is: I'm in charge for the warehouse near the factory, the name is Skeet. The warehouse is full of canned food. [He snaps, raising his voice] Some piece of shit is regularly skimming these cans, and he's doing pretty well at it! Of course, everyone around think it's me. The thefts are still going, even now - but no one is listening to me, let alone desires to help. They say I have an accomplice, so the stealings would continue to happen. [he powerfully spits on the floor] I'm innocent! For real!}

{331}{034}{Yeah? Isn't the warehouse guarded?}


{340}{}{It is guarded, alright. To get to the territory unnoticed - that is some fantastic shit. So it's all good: the guards are guarding, the fence is fixed recently...}

{341}{999}{Aren't you a storyteller. Sit in your camera. You belong here.}
{342}{999}{Okay, I'll go look around. Maybe you are innocent.}
{343}{035}{The fence was broken before?}


{350}{}{Well, yeah. There was a hole once. We fixed it pretty good - partially covered it with some junk we had, somewhere even put a new pieces... Why do you care about the fence? Do you think someone could slip through? I don't think so. There was some hole left, but very small. Even a kid wouldn't fit.}
{351}{036}{Can you tell me where it was?}



{360}{}{Look it up, man! Someone like you would't miss it. }
{361}{999}{[leave in search of a mysterious hole]}


{400}{}{How is it going?}
{401}{041}{Good. Today you are going to be free of all charges.}
{402}{999}{In the process.}


{410}{}{Seriously? }
{411}{042}{Yeah. Your warehouse was being robbed by a little Chimera. She dug up a fence and has been quietly stealing the supplies. Smart creature. I should tell Mark about it. }


{420}{}{Damn, thanks! Thank you, really! I owe you!}
{421}{999}{Yeah, see you around. }


{5}{}{Thank you! I'll remember that!}
{6}{}{Seriously - thanks, man!}
{7}{}{Thanks for the help! I owe you!}
{8}{}{Screw you!}
{9}{}{Get the hell out, ASSHOLE!}
{14}{}{I'm not in the mood for visitors...}
{15}{}{Listen, it's a bad time to do small talk...}