##############################
#Локация: Оазис
#Имя: Старейшина
#Краткое описание: Старейшина Оазиса. Квест на бой с Клумком
#Дата создания: 11.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see an elderly savage lady.}
{2}{}{Judging by her crystal stare, old age put its marks on her body, but not mind.}
#
# после знакомства
{3}{}{You see Elder.}
{4}{}{The head of this tribe and shaman of Oasis.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Her clothes are made of hides and pelts banded with leather straps. Her wrinkly face is shadowed by a strange, crown-like construction, mounted on her head: colored wires hold together different circuit boards, plates, antennas and withered buns of fragrant herbs. The image is completed by a skull of a child, dangling on a braided string, which is wrapped around her slender neck] You... The Twilight Viper sees you! [she howls a little on every word, stretching the vowels] Don't try to lie to the Elder, for Viper himself is looking through her eyes!}
{11}{012}{What the hell? Who? Viper?}
{12}{012}{Are you having a stroke? What are you talking about?}
{13}{011}{Elder? That means you are in charge here, right?}
{14}{017}{Did you see a sand wolf running by?}
{15}{999}{No, I'm not ready for this kind of talk. I'd better go.}


{1001}{}{[Elder cycles through a set of bone beads, quietly mumbling something] ...May the two-legged prey not escape the hands of Twilight Viper's children... [she gives you a mean look] What do you need, outsider? [she is howling on wovels again] You are bothering Elder's praying...}
{101}{012}{Who is this Viper you mentioned?}
{102}{011}{I have a couple of questions for you, Elder.}
{103}{017}{Did you see a sand wolf running by?}
{104}{999}{I won't be interrupting you anymore. See you later.}
{1002}{}{[She grabs the skull on her neck and grimly nods] You came again. Why? If you think that being part of the tribe gives you the right to bother me all day long, you are wrong, may Viper rip your throat! Go do something useful, little man! [at least now she talks without howling]}
{105}{012}{Now, can you explain me the details about your gods? Or spirits, I don't know how to call it.}
{106}{011}{I'm only going to ask a couple of questions.}
{107}{017}{Did you see a sand wolf running by?}
{108}{999}{Okay, don't be mad. See you later.}


{1101}{}{[She adjusts her headgear, so the couple of antennas now point straight at you] Spend my time wisely, outsider! Twilight Viper doesn't like when his shaman is distracted from prayings! One mistake, and you are being served to our table before due! [as she finishes her speech, her voice sounds almost like wolf-like howling]}
{111}{014}{Yeah, about your protein diet. Am I getting this right that eating people is an OK for you?}
{112}{013}{So, you are also the shaman, right? }
{113}{015}{Your tribesmen won't let me leave this place! It could be a problem...}
{114}{021}{I don't really respect elders, so if you threaten me - I'll make it harder for you to chew. }
{115}{016}{Can you tell me about your tribe?}
{116}{013}{Ha! You are communicating with spirits using this antennas?}
{117}{999}{Okay! I'm leaving...}
{1102}{}{[She thoughtfully moves her look from a ritual club on her belt to your head, and then back to a club] Very well. Ask. Maybe you'll give me the reason to rip your tongue out...}
{118}{014}{I suppose it's a delicate dish for you here. I mean, is it really necessary? But don't give me this "spirits and stuff" bullshit.}
{119}{013}{Why do you play the part of a shaman? Don't you get enough respect?}
{1110}{021}{I don't really respect elders, so if YOU threaten ME - you are risking YOUR tongue. }
{1111}{016}{Can you tell me about your tribe? In normal voice?}
{1112}{999}{Although, I need to go. See you later.}


{1201}{}{[She starts to slowly spin around, howling and tapping foot] ...And when the cleansing flame came roaming earth, Twilight Viper created these mountains to keep all of his children safe! [she then proceeds with some gibberish on a language unknown to you. Some kind of a prayer, maybe?] He filled this cliffs with his might, which had been pouring on us year after year! And we rose above all others in height and strength! Now he watches over his tribe through the eyes of his shaman and talks through her mouth... May the Viper be great and praised!}
{121}{021}{The hell? You can piss into the ears of your overgrown kin as much as you want, but it won't work with me!}
{122}{999}{Very... Interesting. Thanks for the answer.}
{1202}{}{[She puts some herbs into her mouth and starts to slowly chew] Good for your teeth, you should try it... Mmm... If I tell you, would you leave me alone? Okay... The tribe should know that someone big is watching over them. And people need to believe that their deeds will be justified by higher authorities. Our spirits are not worse than any others, that's it. And besides, this place, it's... Strange. This thingies that outsiders used to talk to each other from a distance, are of no use here, but our bodies receive this unknown strength... So it's easy to believe anything you want. Sometimes even I myself... [she pauses, thinking about something] }
{123}{021}{You are really sick in the head, worshiping such stupid things! It's time to stop this charade!}
{124}{999}{Opiate of the masses, huh? Okay, I'm leaving you alone, just as I promised.}


{1301}{}{When Elder chooses a successor, she bestows upon her this sacred headdress, through which our spirits talk to us! Because not always the feeble human mind is capable of finding answer to any question! Elder should be a shaman, so nothing could stay hidden in the shadows of unknown!}
{131}{011}{Another question then.}
{132}{022}{So only a woman can become Elder?}
{133}{999}{I see... That's it for now. See you.}
{1302}{}{[She scratches her crocheted nose with a ritual club's handle] It's one thing when some old woman, even an Elder, mumbles something, and the other - when a mighty spirit is talking through her. This knowledge is something I will eventually pass on to my successor too... }
{134}{011}{I see. Another question then.}
{135}{022}{Successor? So only a woman can become Elder?}
{136}{999}{I see. Let's take a break.}


{1401}{}{[She widely smiles, showing a set of teeth definitely not like one of an old person] People are only those of the tribe! The rest are outsiders! Eating outsiders pleases our holy spirits! You will have this great honor too!}
{141}{021}{Go fuck yourself, fucking cannibal! Let's see what your spirits are going to do when I blast your brains out! }
{142}{011}{Easy, we don't know each other this well yet. Better tell me something else...}
{143}{999}{Thank you, of course, but I'm too humble for such honors. Actually, I've got to go.}
{1402}{}{[She widely smiles, showing a set of teeth definitely not like one of an old person] Two-legged prey is easier to kill. Those who are beyond the mountains... Even with their weapons, they are still not as dangerous as wild animals - whose numbers, by the way, are diminishing with each year... And our powerful warriors need to eat a lot! How to feed them, if not forcing to eat everything there is? }
{144}{021}{I'm a lot more dangerous than any creature of the Radius. And I'm going to prove it right now. Today the hunter becomes the prey!}
{145}{011}{At least it sounds honest. I have other questions.}
{146}{999}{I see. I need to think about it...}


{150}{}{[She seems to speak with a monotonous tone, but you definitely hear sinister notes in her voice] Everyone can enter into the house of Twilight Viper, but not everyone can leave! But I will help you - by releasing your spirit on a Red Field after a ritual! Only your flesh will stay here, but you would be free to fly away wherever you like... }
{151}{023}{Sounds tempting. But I'd like to leave this place in full package.}
{152}{023}{You'd better come up with another option, while someone did't get hurt...}
{153}{021}{That's me who is going to free you from your flesh, you animals! Starting from you, old bitch!!}
{154}{999}{I'd like to think about the alternatives...}


{1601}{}{Outsider can never comprehend the thoughts of Twilight Viper's children! But ask, you have that right before the Last Supper... Last for you. }
{161}{018}{Do you have someone around here who knows healing?}
{162}{019}{I just need to know - do you have a normal family?}
{163}{020}{What does your tribe do?}
{164}{011}{To other questions...}
{1602}{}{[Sighs] Why didn't you lose to Klumk... Ask, little man.}
{165}{018}{Do you have someone around here who knows healing?}
{166}{020}{I just need to know - do you have a normal family?}
{167}{020}{What does your... Our tribe do?}
{168}{011}{To other questions...}


{170}{}{[She pulls up a hide on her shoulder] This abode of fleas has finaly ran off? Good news! Or I would have skinned him myself eventually...}
{171}{021}{Maybe that's what you actually did? Tell me, old hag, while you still has YOUR skin on yourself!  }
{172}{999}{I suppose this means no... Well, I'll continue my search elsewhere.}


{1801}{}{[Her face darkens] Khala, our healer, can treat wounds. She also cooks, and she is very protective about her duties. Too much even... You'll meet her soon.}
{181}{011}{Yes, I'll come by her, if I get the chance...}
{182}{999}{That's all I needed. All the best.}
{1802}{}{[She tries to look sad, but can't hide her smile] Khala, our healer, could treat wounds and cook... What a huge loss for us! Now this bitch- this worthy daughter of our tribe is making our spirits happy with tales of her devotion!}
{183}{011}{I share your sorrow. Now, to other questions...}
{184}{999}{We all will be there eventually. And I've got to go.}
{1803}{}{[She frowns, like biting a rotten apple] Khala... She is our cook and our healer. If only she doesn't like to shed blood so much... Doesn't matter which... But warriors treat her with respect, so we have to deal with her habits. And, to do her justice, her cooking is very good, I admit that. Outsider's thighs with brains as garnish... Yum... [she slurps]}
{185}{011}{I'll come by her, if I get the chance. Another question.}
{186}{999}{I feel hungry already. I'd better go bite on something.}
{1804}{}{[She grunts] Yes, there was... Khala. But our spirits made a present for me and took her away. That's where she belongs.}
{187}{011}{I'm truly sorry for your loss. Let's return to other questions......}
{188}{999}{We all will be there eventually. And I've got to go.}


{1901}{}{[Her vicious wrinkled face becomes calm for a while] Ptuna... Someday my daughter will be a worthy Elder, and bring the tribe to the true prosperity! }
{191}{011}{This is great. But I have another question...}
{192}{999}{Good for you. I need to go, see you.}
{1902}{}{[Her vicious wrinkled face becomes calm for a while] Ptuna is my family. She lacks the spirit for now, but when I retire, she is the one who takes my place. She never failed me... Always loved her old mother... [Looks like you see a tear in her eye, but she immediately becomes firm] That's it, go away! My memory is not as good as before, I can forget that I shouldn't eat you! }
{193}{999}{Okay, okay, I'm leaving. Talk later.}


{2001}{}{The only honorable occupation for Viper's children is the hunt! [proving her point, she smashes a rat, which was running by, with one blow of her club. Blood splatters everywhere] The feet of our warriors are fast, weapons are sharp and never miss the target!}
{201}{011}{Definitely honorable. Would you mind answering another question?}
{202}{999}{I see... Okay, I'm done with questions for now.}
{2002}{}{[She squints her faded eyes, as if trying to look beyond the mountains] What else to do here? This place has given us the height and strength, but not food. We have to get it by ourselves. To try cultivating this land is pointless, so there's only one option for the tribe. And if we need something that we can't hunt, we can trade it from outsiders.}
{203}{011}{It must be not easy to live here... Tell me about something else.}
{204}{999}{I see... Okay, I'm done with questions for now.}


{210}{}{[She is visibly angered. Slowly stepping back, she hisses through clenched teeth] How stupid an outsider can be! How hastily he desires to get into our stomachs! He doesn't understand how to talk properly here, and to whom! [she yells so loud that you become deaf for a moment] Come, Viper's warriors! Prey is here!}
{211}{998}{They won't be here in time to help you, bitch!}
{212}{998}{Man, why no one is glad to see me...}


{2201}{}{[She starts to shake, raising head to the sky and speaking in a sing-song voice] ...And so the woman's loin is from where our warriors come into this world, and so she is the one worthy of speaking the voice of spirits to the tribe!}
{221}{011}{Makes perfect sense. Let's talk about something else.}
{222}{999}{It's just an unjustified sexism! Too bad I need to go, or I would explain to you something...}
{223}{999}{So that's how it is? Okay, I leave you to enjoy your chosenness. See you around.}
{2202}{}{[She gives you a look of disdain] Who else? Men? Men, put into power... Been there, done that - just look what the old world ended up with. And I won't let that happen to my tribe!}
{224}{011}{Let's not get into details. Better answer me something else.}
{225}{999}{It's just an unjustified sexism! Too bad I need to go, or I would explain to you something...}
{226}{999}{Like I need it...  Okay, I'm going. See you around, Elder.}


{230}{}{[Looks like she is quite tired of you. Suddenly, she brights up with a new idea] Outsider can leave... If he beats mighty Klumk in battle! Twilight Viper tells me it's impossible... But it's good to show the tribe how weak outsiders are when facing our warriors! And they can feast on your flesh afterwards. So, even if an outcome is predefined, I'm offering you to participate in this. And no weapons - only what's with you from the moment you were born!}
{231}{024}{That's it? To put down one of your stupid thugs? Ha! Easy!}
{232}{024}{Well, if there's no other way... Shall we begin?}
{233}{021}{Okay, I'm sick of it. Listen here, you wrinkled carcass, now you immediately command your overgrown idiots to clear the passage, or I'm leaving anyway, but this place gets filled with your corpses!}
{234}{999}{No, I'd better search for alternative solutions. }


{240}{}{[You patienty wait in the local "diner" for a crowd of spectators to gather and for your opponent to arrive. Then he appears - naked from the waist up, body painted with blood. Elder starts to gently howl, making it louder with every minute] Here comes the mighty Klumk, to break the bones of an outsider, to drink his blood, to put his flesh on our table! Observe it carefully, my children!}
{241}{999}{Yeah, yeah. Shall we start?}
{242}{999}{I should have brought a chair...}
{243}{999}{I'm going to bury you, you scum! I'll rip off you entrails and choke you with them! Come on! Come!}


{250}{}{[The blood-stained field becomes filled with silence. The locals are looking at the defeated Klumk, not capable of believing their eyes. Then their gazes slowly turn to the Elder. She snaps out of it pretty fast, you should admit that] So, in his wisdom, Twilight Viper decided to show us what awaits those who don't follow his path! Klumk spent too many time around outsiders, and that made him weak! And our great spirit has sent us this... Man! And he... Stays with us! He will hunt with our warriors, share the food and show us our weaknesses! Let's greet him! [The crowd responds with an unstructured chorus of confused cheers. Elder nods to you, saying with her lips: "Say yes!"]}
{251}{026}{Oh... Oh yeah, that's how it is. Sure. Greet me. }
{252}{021}{What?... That wasn't our deal! You want to fuck me up, bitch? I'm leaving! Right now!}


{260}{}{[The crowd of savages spreads up, taking away the Klumk with them. You are left together with Elder again] Why did I do this? Am I out of my mind? Wanted a spectacle, was bored... [you didn't catch it immediately, but then it hits you - she speaks... Normal?] So, what to do with you? [she silently stares]}
{261}{027}{Wait. So it was all an act? Actually, I suspected that - you've been putting your words into sentences too good... Have my applause.}
{262}{027}{Ha! I knew you are just fooling this savages! Nice job with this spirits bullshit!}


{270}{}{[She takes off her headgear and slowly rotates her head, covered with rare silver locks] Oh, my neck is so tired from this thing... How else would you put even a single good thought into their heads? Only spirits can help. And besides, sometimes even I'm left to wonder that someone watches over me from the darkness of nights... Okay then. You got what you wanted, you can leave. And you should understand why I couldn't let you go just like that, in front of a whole tribe. So, now you are one of us. By the way - are you hungry? }
{271}{028}{Thanks. Don't you afraid that I tell them the truth?}
{272}{028}{No, eat human flesh by yourselves. Better tell me, what you'll give me for keeping silence?}


{280}{}{Who would believe you? I raised my children properly... One word of mine - and they'll rip you apart like a dead ursa! That's it, we're done here. [she turns around to leave, but suddenly remembers something] Oh yeah! I should give you something. The sign of you being one with the tribe. Every boy becomes a man when he is given a gift from Viper. Tradition, you know... [she digs through her hides] Maracas made of twin skulls... A necklace from caravaneer teeth... No, it's too good to give away... Oh! Here, take this. It has no pictures and nothing in it makes sense. Now leave me alone, little man! [You obtained some unknown book. Elder leisurely walks off]}
{281}{999}{"Constitution of 15 rights"? How the hell this ended up here?}