##############################
#Локация: Оазис
#Имя: Кхала
#Краткое описание: Целитльница и повар Оазиса. Квест на лечение руки, съела волка Птуны.
#Дата создания: 10.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a tanned savage woman. She is wearing a blood-stained apron.}
{2}{}{She looks at you like a food critic looks at sophisticated dish.}
#
# после знакомства
{3}{}{You see Khala.}
{4}{}{She successfully combines duties of chef and healer in this tribe.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Under thin, greasy, interwoven with little bones locks of hair, falling on her forehead, you see two hateful and curious, a bit googly, eyes. The only pieces of clothes she wears are loincloths and a torn apron, which has some kind of unusual patterns, deeply hidden under the layers of bloody stains. She smiles at you, licking her bitten lips, and you, with some uneasiness, notice her sharpened canine-like teeth] Ssoo... Unfed Silent One sent us an outsider? Mmm... Dinner or lunch? Lunch or dinner? [she stops and thinks] Aunt Khala is generous today, you can choose yourself... But don't choose for too long...}
{11}{013}{Unfed who? What are you even talking about?}
{12}{011}{I really hope you're joking. It would be better for everybody.}
{13}{014}{What an interesting choice. And you are the local cook, I suppose?}
{14}{012}{Who do you call an outsider? We are of the same blood now, your- I mean, our elder said so herself!}
{15}{025}{You didn't see a sand wolf around here by any chance, did you?}
{16}{999}{Okay, let's put away this conversation for now. And don't look at me like that!}


{1001}{}{[Khala rummages through a big basket, sorting something] Eat today... Eat tomorrow... Silly Klumk! Why brought so little salt? The food shouldn't go to waste... And this one, with maggots, Khala is going to eat herself, will cook it on fire... Mmm... Gonna be tasty! [as you come closer, you notice that the basket is filled to the top with big chunks of meat, unevenly rotten. Better not to try guessing which meat it is.] Who Unfed sends us this time? Ah, it's an outsider again... Wait, Khala will clear a place here for you...}
{101}{013}{Who's that Unfed that you are talking about all the time?}
{102}{011}{I really hope you're joking. It would be better for everybody.}
{103}{014}{Don't bother. Better tell me, what do you do here, except counting food inventory.}
{104}{012}{Why do you still call me an outsider? I proved my right to be side by side with you in battle!}
{105}{025}{You didn't see a sand wolf around here by any chance, did you?}
{106}{019}{It's about your wounds. I need to examine them one more time.}
{107}{999}{Don't get distracted, I was just coming by.}
{1002}{}{[Her teary eyes suck onto your face, as if she's choosing where to sink her sharp teeth] Outsider! The hand hurts even more! Maybe if Khala washes her wounds with your blood, she would feel better? }
{108}{027}{Calm down! I've returned to help you.}
{109}{999}{Wait for a little longer, soon it'll be dealt with.}
{1010}{031}{This pain is nothing, compared to what you are going to suffer, you crazy animal! It's time to put you down!}
{1003}{}{[she is sharpening her teeth with a broken makeshift hacksaw, but upon seeing you she hides it into one of pockets on her dirty apron. It became even more blood-soaked since your last conversation.] And again, the outsider comes to Khala... The Unfed Silent One is wise and great - he kept her from eating you right away... [she takes out a piece of meat from another pocket and tries to hand it to you] Want it? No? Why? It's tasty, just started to rot! The outsiders are so strange...}
{1011}{013}{Excuse me for interrupting your make-up, but could you tell me about this Unfed one?}
{1012}{012}{You are still calling me an outsider?}
{1013}{031}{How are you feeling, Khala?}
{1014}{025}{You didn't see a sand wolf around here by any chance, did you?}
{1015}{999}{Glad to see you, but I need to go.}


{110}{}{[she gives you a surprised look] How it would be better for everybody, if no one eats anyone? You are trying to make a joke on Khala! [She hisses through teeth, stroking the handle of a huge butcher knife] Khala doesn't like jokes. Khala likes meat...}
{111}{031}{Slow down, you wacko. Or I'm gonna find a way to make you slow down. }
{112}{014}{Alright, let's quickly change the subject. For example, tell me, what do you do here.}
{113}{999}{Oh damn, I've just remembered I have some places to be. See you around, foodie.}


{120}{}{[she shakes her head, copper earrings in her ears give out a melodic chime] For Khala you will always be an outsider. You are like a sand wolf - at first it eats with you, hunts your prey with you, then he bites you... [her face darkens when she says these words]}
{121}{025}{A wolf? Why did you come up with it now?}
{122}{014}{You wouldn't mind telling about yourself then, would you?}
{123}{999}{Okay, suit yourself. God bless.}


{130}{}{He comes with a wind in the night! He is silent and quiet, like a warrior should be! And he is always hungry... [she glances over you, like she's trying to guess how much meat and blood can be taken out from your body] the Silent One teaches us to see the others as food in the first place... And only after that - as a friend, daughter or parent...}
{131}{031}{Only the lowest of scum like you could worship a creature like this! Eat shit! }
{132}{014}{Really? So, your kitchen doubles as a local cemetery? Hm... And what else do you do here?}
{133}{999}{Wonderful. I should go, I think.}


{1401}{}{[Khala gently strokes knife handles, which stick up from the pockets of her apron] Khala cooks food, Khala heals... Unfed Silent One generously bestowed her with his gifts. [she adjusts bracelet on her wrist and frowns in pain. You notice bite wounds on her elbow. Looks very nasty.]}
{141}{015}{Did you ever try to do a little cleanup here... In your, uh, kitchen? Or you are purposely breeding maggots?}
{142}{018}{What's with your arm?}
{143}{031}{What fucking gifts? You eat people, you crazy bitch!}
{144}{016}{You know healing? Could you heal me?}
{145}{017}{Hmm... Mind teaching me some recipes?}
{146}{999}{Enough information for now. See you later.}
{1402}{}{[Khala gently strokes knife handles, sticking up from the pockets of her apron] Khala cooks food, Khala heals... Unfed Silent One generously bestowed her with his gifts. If you want, Khala can share her knowledge.}
{147}{015}{Did you ever try to do a little cleanup here... In your, uh, kitchen? Or you are purposely breeding maggots?}
{148}{031}{What fucking gifts? You eat people, you crazy bitch!}
{149}{016}{You know healing? Could you heal me?}
{1410}{017}{Hmm... Mind teaching me some recipes?}
{1411}{999}{Enough information for now. See you later.}


{150}{}{Khala likes when air smells with blood! It soaks into flesh, makes you strong! That's why Khala wears sacred clothes for her everyday eating ritual... [she touches straps of her apron. So that's what this patterns are about!]}
{151}{031}{Okay, that's it, I'm done! Now you are getting your "smell of blood in the air"!}
{152}{014}{Actually, I wanted to learn another thing about you...}
{153}{999}{I see... But I need to go.}


{160}{}{[Khala squats down and throws around her amulets, made of yellowed phalanges... human, of course] Khala knows three times ten of hexes and five fives ten of rare herbs! But her best skill is cutting. Khala saved life of Klumk's kinsman once! His finger was bit by a wild roach, so Khala chopped off his hand. Do you want Khala to cut something off you? }
{161}{031}{I have a counter-proposal - I'll chop your head down and play soccer with it! What do you think?}
{162}{014}{No, thank you. Better tell me about yourself a little bit more.}
{163}{999}{Enough information for now. See you later.}


{170}{}{[Khala generously shares her culinary wisdom with you] ...You need to hang your food by the feet while it's alive, and beat it with sticks until it dies. Then its meat will be soft and tender... [she goes on in this manner for another half an hour] ...But don't forget, main thing is to drain all the blood, while giving prayer to Unfed Silent One. If you are lucky, you'll test Khala's mastery on yourself!}
{171}{014}{Simpy amazing. A pity I didn't have chance to write it down. No, no need to repeat. Better answer my other question.}
{172}{031}{You... I'm gonna drain all of YOUR blood, even without hanging you by the feet! You are fucking nuts!}
{173}{999}{I need some time to wrap my head around it. See you later, don't walk me out, I know the way.}


{180}{}{[Khala hastily puts her hand behind and snarls at you, squinting her eyes] Why do you care about Khala's arm? Why do you ask this question?}
{181}{019}{Why so nervous? I just wanted to assess the damages and maybe do a little helping healing.}
{182}{999}{Just saying. Well, I'd better come back later, when you calm down.}


{190}{}{[Khala pulls back her hand at least twice, but still lets you examine her wounds. It seems that they are really causing her problems.] What did the outsider see? Why did he become silent?}
{191}{020}{Be calm, one moment...}


{2001}{}{[Your current knowledge is not enough to adequately evaluate the situation, but swelling and stench from wounds definitely don't look good. Khala awaits, looking more impatient with every second. She might already be estimating which part of you she should eat first.]}
{201}{021}{Uh, well.. It's nothing serious, really! This your Hungry- err, Unfed, yeah! He blessed you with this wounds as a test of your spirit. You are doing pretty good, so everything should be healed in a week or so. I don't understand myself how do I know that. Feels like sudden insight!}
{202}{022}{Frankly, I don't have enough skill... But I do have enough skill to find someone who could help you out. This things here look very nasty.}
{203}{031}{Ha, you're gonna die soon! I'd shoot you right now, to put you out of misery!}
{204}{999}{I need to think about your problem. Wait for a while.}
{2002}{}{[Judging by distinctiveness of injury, it's a typical lacerated wound. Pathogenous infection did its job, and in closest perspective Khala will probably face an amputation. A particular odor of pus only confirms your concerns. Khala awaits, looking more impatient with every second. She might already be estimating which part of you she should eat first.]}
{205}{023}{Nothing good, Khala. You won't last long without medical help. I could try to do the treatment. }
{206}{021}{Uh, well.. It's nothing serious, really! This your Hungry- err, Unfed, yeah! He blessed you with this wounds as a test of your spirit. You are doing pretty good, so everything should be healed in a week or so. I don't understand myself how do I know that. Feels like sudden insight!}
{207}{022}{The situation is pretty bad... But I won't take the job of healing you. i can only go and find someone who will.}
{208}{031}{Ha, you're gonna die soon! I'd shoot you right now, to put you out of misery!}
{209}{999}{I need to think about your problem. Wait for a while.}


{213}{}{[bloodthirsty cook gives off a relieved exhale] That's just what I thought! The Silent One loves Khala, he always did! He felt her suffering and sent her the outsider, with this words put into his mouth! Here, take this holy scribings - they give Khala energy before hard work... [she takes out of apron some magazine and ceremonially hands it to you] You are worthy of owning it, as the Silent One's wisdom condescended upon you... And Khala will take her time to think, how she could eat you later...}
{214}{999}{Then I'll leave you alone with this beautiful thoughts.}


{210}{}{[on Khala's face, you see that worry for you not returning slowly changes with fear of losing arm. In the end it looks like she values her well-being above the tribe customs] Okay... Outsider can walk away to look for the healer. Khala will tell the warriors to let him pass. But if outsider is lying - Khala will find him and eat his dirty heart! And after that, the rest too...}
{211}{999}{Don't worry, I'll return. You won't even miss me.}
{212}{999}{Maybe there are other options... Wait, I'll be back soon.}


{220}{}{[the tribe healer doesn't favour your old-fashioned ways of healing, but the pain from wounds makes her take the risk] Okay...  But Khala will hold her knife by the outsider's throat while he touches her! If Khala suspects that he means harm...}
{221}{024}{Yeah-yeah, I got it. Everything according to your Unfed's teachings. Let's begin - your luck that I have everything I need with me...}
{222}{999}{You know, I'm not quite ready to that. I'll be back when I find out some alternative method to solve this problem.}


{230}{}{[This is definitely not the case that could challenge your talents. The savage cook is remarkably stoical in enduring all the procedures. You clean the wounds - and suddenly take a wolf's fang out of one. Khala abruptly flinches, almost cutting your throat. You put your discovery on the ground and apply a bandage on Khala's arm. Piece of cake.]}
{231}{025}{Looks like we're done... Now, remember not to take off the bandage. And don't scratch it.}


{240}{}{[she rotates her forearm, evaluating quality of work] How the outsider managed to do it? He didn't even say one prayer... But hand is not in pain anymore! Outsider must have been helped by the Unfed, that's why no words were said! [she takes out of apron some magazine and ceremonially hands it to you] Here, take this holy scribings - they give Khala energy before hard work. You are worthy of owning it, as the Silent One's wisdom condescended upon you... And Khala will take her time to think, how she could eat you later...}
{241}{027}{So... Whose fang is it, I wonder?}
{242}{999}{Then I'll leave you alone with this beautiful thoughts.}


{250}{}{[Khala twitches and warily looks around] Wolf? What wolf? Khala didn't see nothing, tell Ptuna this! Why does outsider still here?}
{251}{026}{Because outsider took this fang out of Khala's wound.}
{252}{026}{Why are you so nervous? And, by the way, I never said that this was Ptuna's wolf... But the thing is that it's just a furball, while you are one of the most important people of this tribe! Even Ptuna accepts it! So what if you had some misunderstanding with his wolf, am I right? Talk to me, lighten your load!}
{253}{033}{Ha! Who said something about Ptuna? You blew it, wench! Talk immediately! Where's the wolf?}
{254}{999}{I'm already leaving.}


{260}{}{[Khala moves forward, as if going to grab you, but suddenly bursts out] Stupid wolf! Khala held it for so long! He has been stealing meat, all the time! But she caught him in the act and decided to teach him a lesson. The beast bit Khala - so Khala snapped the beast's neck. And ate him! He was so tough, Khala has been picking up him from her teeth for two days... }
{261}{999}{I figured this much. Okay, it was nice to hear your story, but I have to go.}


{270}{}{[With her healthy hand, she plows through the bushes on her head in search of some insect. Little bones in her hairlocks lightly tap on each other] Let the outsider not hesitate! Khala is tired of catching little creatures with one arm!}
{271}{029}{[make a gesture to dr. Pat] This is dr. Pat, he is a great shaman of his tribe! He will help you.}
{272}{019}{I want to examine your wounds again.}
{273}{999}{Actually, you'll have to wait... Don't be nervous! Not for long!}


{280}{}{[You don't start the procedure right away. Khala insists that she should hold her butcher knife by the throat of dr. Pat as an insurance; for some reason, dr. Pat doesn't agree to that. So, as a trade-off, you decide that if Pat makes a mistake, the blade goes through your neck. While doctor does his job with the wounds, you are having not the most pleasant experience. But then Pat wipes his hands and nods to you. All done.]}
{281}{030}{At last...}


{290}{}{[she rotates her forearm, evaluating quality of work] How the outsider managed to do it? He didn't even say one prayer... But hand is not in pain anymore! Outsider must have been helped by the Unfed, that's why no words were said! [she takes out of apron some magazine and ceremonially hands it to dr. Pat, but he is categorically against taking anything from her. Looks like the dinery of this village made its impression. The magazine goes to you.]  Here, take this holy scribings - they give Khala energy before hard work. You are worthy of owning it, as you brought here the messenger of Silent One... And Khala will take her time to think, how she could eat you later...}
{291}{999}{Then I'll leave you alone with this beautiful thoughts.}


{300}{}{[you expect her to explode in fury, but Khala only satisfyingly bares her teeth. Sticky saliva drips off her chin, her sight shows only impatience and hunger] Khala will be so delighted to eat you... Elder forbids us to be hasty with the strangers, but you are just itching to be eaten! Khala waited this for so long... [she wipes her drool and steps to you]}
{301}{998}{Choke on my bullets, you fucking maneater!}
{302}{998}{It's me who will be happy, while ripping your rotten heart out!}


{313}{}{[she gives you a wide smile, demonstrating two rows of sharp fangs] Khala feels good! She's even more hungry now. The outsider helped Khala. When Khala decides to eat the outsider, he will die fast and easy!}
{310}{026}{Thank you for that... By the way, did you see a wolf around here?}
{311}{999}{Well, great. Don't even know how I deserved it. Okay, gotta go.}
{312}{999}{I'd better move, while our conversation haven't gotten too far.}


{320}{}{[knife swiftly flashes before your eyes, almost cutting off the tip of your nose] The outsider talks too much! If he says another word, Khala will tear out his dirty tongue! She already knows about Ptuna's trouble and wants to help. The outsider walks out of here alive if he promises Khala to tell this to Ptuna!}
{321}{031}{Yeah, fat chance! That's it, I'm sick of you, fucking cannibals! It's time to mop out the area!}
{322}{999}{[nod and carefully step away]}