##############################
#Локация: Оазис
#Имя: Клумк
#Краткое описание: Воин Оазиса. ГГ должен победить его, чтоб покинуть Оазис.
#Дата создания: 11.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a huge muscular savage.}
{2}{}{His look is quite unusual for this place - look at his armor, for example.}
#
# после знакомства
{3}{}{You see Klumk.}
{4}{}{The only warrior of the tribe, who enters into other settlements of Radius with peaceful intent.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Battered leather armor, definitely smaller in size than it should be, barely covers his wide chest. On top of it there's a wide spiked collar, decorated with crooked letters, spelling out "Klumk". The armor itself is covered with all kinds of badges, bottlecaps and shells of different caliber. The gem of collection is definitely that "DO NOT ENTER" road sign on his back, covered in bullet holes] What outsider want from Klumk? Klumk make no trade now!}
{11}{011}{Hey, Klumk. So, you are not interested in fire water and beads?}
{12}{012}{I just want to ask some questions about your tribe. }
{13}{999}{Talk later then.}


{1001}{}{[He touches the bull ring in his nose and gives you a predatory look] Why you walk-run so much, oursider? Meat be tough. Klumk not like this much...}
{101}{012}{I'll remember that. For now, can you answer some questions about your tribe?}
{102}{014}{Does Klumk like the taste of his own blood? If not, he'd better shut his mouth.}
{103}{999}{Great. I'll go walk.}
{1002}{}{[He pulls his head into shoulders and covers decorations on his armor with hands, as if you want to take them from him] You want fight again? Klumk do not want! Less teeth, bad to chew...}
{104}{012}{Don't twitch, I just want to ask a few questions about my new home.}
{105}{999}{Next time you'll think before coming at me. See you around.}


{1101}{}{[He meaningfully nods, scratching his tanned face, covered in ritual scars, with long nails] Now Klumk go hunt! But Elder know that Klumk smart, she send Klumk to outsiders - exchange prey on things. Klumk keep everything here [he taps his forehead with finger]. Big Ursa hide - five times two knives or one sack of corn, wolf fangs - strong water one bottle... But outsiders not like Klumk offering them beautiful skin once. Nice, with pictures on it! Klumk peel it off an outsider by himself, ate him later! You are so strange, outsiders...}
{111}{013}{Why do you wear all this trinkets?}
{112}{014}{I'm going to peel the skin off you, deadmeat! Time to pay the piper! }
{113}{999}{Yes, we are. Bye, businessman.}
{1102}{}{[He meaningfully nods, scratching his tanned face, covered in ritual scars, with long nails] Now Klumk go hunt! But Elder know that Klumk smart, she send Klumk to outsiders - exchange prey on things. Klumk keep everything here [he taps his forehead with finger]. Big Ursa hide - five times two knives or one sack of corn, wolf fangs - strong water one bottle... But outsiders not like Klumk offering them beautiful skin once. Nice, with pictures on it! Klumk peel it off an outsider by himself, ate him later! You are so strange, outsiders... [He winces and hastily corrects himself] Klumk did not want to call you outsider! You with us now. Klumk remember!}
{114}{013}{Don't trouble yourself. Better tell me, Why do you wear all this trinkets?}
{115}{999}{Yes, you remember that. Bye, businessman.}


{120}{}{Our tribe - great! Elder said so. We go hunt! We kill any wild beast, any outsider! And Khala cook it very tasty after! But Klumk afraid Khala, she yell at him all the time...}
{121}{011}{What about you, Klumk?}
{122}{999}{So that's how it is. Well, get some rest, I need to go,}


{130}{}{[He gives you a bewildered look] Because it's COOL! That's what one outsider tell me. I exchange my prey with him all the time. And he teach me to write my name! [he points on his collar] This I did myself! You no talk this to Elder, she yell at me all the time already. And... [he staggers, nervously strumming shells on his armor, but still continues] I like Ptuna. This I buy-wear for her. }
{131}{012}{What can you say about the tribe?}
{132}{014}{I'm so sickened by all of you... I'm gonna give you some shells! Don't forget to pull bullets from your head later!}
{133}{999}{Me go... I mean, I need to go.}


{140}{}{[He straightens his shouders with a quiet howling. His muscles pop out so hard that it looks like the armor whould tear it any minute. Klumk looks like rabid lavash, ring in his nose only emphasizes the similarity.] You threaten me, outsider? I kill you, in front of all tribe! I ask Elder to let me duel and eat your kindney after! No weapon, only fists and teeth!}
{141}{999}{No problem! I'm always ready for a good warm up! Gather them!}
{142}{999}{I'll break your spine and leave you die in the pool of your own blood, you mutt! Let everyone see this!}
{143}{998}{I don't like being public... I'm going to dismember you right now!}


{150}{}{[Klumk sheds his armor, grabbing some dirt from the ground and making straight line from shoulder to hip. He starts to slowly approach you, crouching, but still, his face looms over you] Outsider ready to die? Klumk hungry already!}
{151}{016}{[rip out the ring from his nose]}
{152}{017}{[remember your martial arts training and punch him with "tiger claw"]}
{153}{998}{You are going to swallow your teeth, savage! Pray to your spirits! }
{154}{998}{Enough talk. Let's go!}


{160}{}{[A strong and sudden pull - and you have the ring. Klumk, furiously roaring, takes a step back, holding on his teared nostrils and shaking his head]}
{161}{998}{Look what I found! Catch! [throw him the ring and prepare to fight]}


{170}{}{[Your steel fingers slice through his face. His left eye flows down the cheek, he falls on his knees, howling in pain, stunned, blindly flailing hands around. Then he slowly tries to stand up, shaking, yelling something illegible]}
{171}{998}{Come on, get up. It's only the beginning.}

{172}{}{I do not want die like that!}