##############################
#Локация: Оазис
#Имя: Птуна
#Краткое описание: Дочь Старейшины. Квест на поиски волка.
#Дата создания: 10.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a savage woman wearing a woolen poncho.}
{2}{}{Unlike other locals, she looks quite friendly.}
#
# после знакомства
{3}{}{You see Ptuna.}
{4}{}{Oasis Elder's daughter.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Given everything you saw here, she looks pretty clean. Her old poncho is decorated with little flowers, the look she gives you can be viewed as friendly.] Hello, stranger. What brought you to us? I'm Ptuna. [she ineptly smiles] }
{11}{}{Hi, Ptuna. I'm }
{12}{011}{, I'm just looking around. Can you tell me about your tribe?}
{13}{999}{Hey. Sorry, I'm in a hurry.}


{1001}{}{[Ptuna gives you a friendly nod] Did you want something from Ptuna?}
{101}{011}{I want to ask you a couple of questions about this place.}
{102}{017}{I found out what happened to your wolf.}
{103}{999}{No, just walking by.}
{1002}{}{[She is clumsily trying to fix her long hair with some sharp and narrow bones, but when you approach her, she stops] Glad to see you! You are really no ordinary man... Would be a pity if it comes to eating you.}
{104}{011}{I wanted to ask you a couple of questions about this place.}
{105}{017}{I found out what happened to your wolf.}
{106}{999}{I hope it doesn't come to that. See you around, Ptuna. }


{110}{}{[Nods] Of course! I don't have a lot of people to talk to here. Ever since Robin left and Hook went missing... [she sadly sighs]}
{116}{}{[Nods] Yes. Since Robin left, I have no one to talk to here. And Hook has also disappeared... [she sadly sighs]}
{111}{012}{Who is in charge here?}
{112}{013}{Hook? A buddy of yours?}
{113}{014}{Do you have traders or doctors around here?}
{114}{015}{Who is Robin?}
{115}{999}{I will be glad to talk to you, but later, okay?}


{120}{}{[Ptuna smiles] Elder, my mother... She is a wise woman. She is able to communicate with spirits and see into the souls of people. Don't try to lie to her, if she calls upon you.}
{121}{011}{Didn't even think about it. Another question?}
{122}{999}{Thanks, I'll remember that. See you around, Ptuna.}


{130}{}{Hook is my sand wolf! [she pulls out a dog leash from under the poncho] This is what Klumk brought me. But Hook didn't like it on his neck... He was so kind, he understood everything! He was the only one who listened to me every time... [her voice trembles] But now he is missing... If you see him, tell me, okay? Don't try to catch or pet him - he will bite your hand off. Hook doesn't like strangers. I fed him with their meat myself.}
{131}{999}{Is that so? Well, I'll tell you if I find out something.}
{132}{999}{No, it's not for me. I don't look for pets. Actually, I've got to go.}


{1401}{}{Khala can heal and cook, and Klumk brings the goods from strangers. [she frowns] But I don't like both of them. Khala is cruel, she likes to hurt people... Even my mother is afraid of her. And Klumk is always trying to make me play a beast with two backs with him. Ew... [she cringes]}
{141}{011}{A what? Oh! I get it... Let's talk about something more pleasant then.}
{142}{999}{You are popular, aren't you? Was nice seeing you, but I have to go.}
{1402}{}{Khala could heal and cook, and Klumk brings the goods from strangers. [she frowns] But I didn't like any of them. Khala was cruel, she liked to hurt people... Even my mother was afraid of her. I won't mourn her death. And Klumk is always trying to make me play a beast with two backs with him. Ew... [she cringes]}
{143}{011}{A what? Oh! I get it... Let's talk about something more pleasant then.}
{144}{999}{You are popular, aren't you? Was nice seeing you, but I have to go.}
{1403}{}{Khala can heal and cook, and Klumk used to bring strange goods from strangers. [she frowns] But I didn't like any of them. Khala is cruel, she likes to hurt people... Even my mother is afraid of her. And Klumk was always trying to make me play a beast with two backs with him. Ew... [she cringes] He was a good warrior, but I'm not going to miss him. And you gave him a good death in battle. Our spirits will greet him with honors.}
{145}{011}{Yes, it was a good fight... But let's talk about something else.}
{146}{999}{He stood in my way, that's it. Was nice seeing you, but I have to go.}
{1404}{}{Khala can heal and cook, and Klumk used to bring strange goods from strangers. [she frowns] But I didn't like any of them. Khala is cruel, she likes to hurt people... Even my mother is afraid of her. And Klumk was always trying to make me play a beast with two backs with him. Ew... [she cringes] He was a good warrior, but I'm not going to miss him. And you gave him a good death in battle. Our spirits will greet him with honors.}
{147}{011}{Yes, it was a good fight... But let's talk about something else.}
{148}{999}{He stood in my way, that's it. Was nice seeing you, but I have to go.}

{150}{}{[Ptuna makes a long pause] He was one of us... I loved him, and he loved me. But Robin was kind of strange - he didn't want to eat the meat of outsiders. And he rejected our spirits! That's why he left... My mother would never let him speak with the tribe about such things. I... [her big eyes become filled with tears, but she immediately gets it together] He wanted me to go with him, but... I love my mother too much. Why, why didn't he eat this meat?! It is the same as any other!! [you notice dried bloody stains on her poncho and remind yourself about who are you dealing with]}
{151}{016}{You know, I met Robin. Do you want me to tell him something if I get the chance?}
{152}{011}{Yeah, a lot of things happen in life. Maybe let's change the subject?}
{153}{999}{Sorry, didn't want to make you sad. It's time to take a break.}


{160}{}{[There's not even a hint of emotion left in her voice] No. You can't swim against the current in a river of time. The past cannot be brought back.}
{161}{011}{As you say. Another question then...}
{162}{999}{Suit yourself. Okay, I won't be bothering you anymore.}


{170}{}{[she gets more lively] Did you see him? Where? Tell me!}
{171}{018}{It's easy, you see. He ran off to a wasteland. I mean, Hook is a wild animal, the freedom is in his blood. So - don't worry too much, it was always coming down to this. He is going to be alright.}
{172}{019}{He was killed and eaten by Khala. She told me that with great pleasure.}
{173}{020}{He was eaten by Khala. It was... An accident. She is very sorry about this and afraid to tell you the truth. }
{174}{999}{Actually, I need to check something. I'll come by later.}


{180}{}{[Ptuna sobs and hastily wipes her eyes with the bottom of a poncho] Just as I thought... But I miss him so much! Maybe he would still come back? But - I'm very grateful to you anyway. I'll tell my mother to kill you fast if it comes to this. }
{181}{999}{Thank you very much! Now I have nothing to worry about...}
{182}{999}{Ha! It would be better for everyone if this doesn't happen. See you around, Ptuna.}


{190}{}{[Her eyes immediately turn into two narrow slits] Khala! She dared to do this to my Hook?! But... I'll forgive her. When I eat her black heart!! You can come to Red Field and try her flesh too!! [she hastily walks off]}
{191}{999}{Glad to be of help... Enjoy your meal.}


{200}{}{[Ptuna sighs heavily] I want to kill her for it so much... But... If it was an accident... Khala is helpful for the tribe, and now my mother could keep her in fear... She will live then. I am grateful to you, but I ask you to leave me alone. Someone should mourn the Hook.}
{201}{999}{Already leaving. We'll talk later.}
{202}{999}{I understand what you feel. Of course, you need some time alone.}
{213}{}{[Looks like Khala is done for...]}
{214}{}{[exit]}

{210}{}{The bitch has very tough meat. Nasty.}
{211}{}{It's disgusting to eat, but necessary. I need to take her power.}
{212}{}{Want a piece? You deserved it!}