##############################
#Локация: "Олимп"
#Имя: Андерсон
#Краткое описание: Бог Олимпа, противник в финальном бою
#Дата создания: 15.08.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a man in a sphere, intertwined with hoses and cables.}
{2}{}{Wires are coming out of all possible places, connecting the sphere to the external electronics.}
#
# после знакомства
{3}{}{You see Anderson.}
{4}{}{Looks like this man is inside this sphere for such a long time that he became one with it.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
#Node001
{10}{}{Here you are, puny human. How you even dare to step a foot in here, into my Control Room? Pathetic... Now your fate is sealed!}
{11}{002}{Wh- What the hell? Who are YOU?}
{12}{003}{Sealed? No. I decide what happens next!}
{13}{004}{Puny human? Ha! Look at yourself! It's you who is pathetic!}
{14}{998}{Enough with your bragging. You are just a piece of flesh entangled in wires. And you're finished!}

#Node002
{20}{}{Who AM I!? I am your GOD! And you knew it since you were born! The question is - who are YOU? Think you are the smartest? The fairest? You are NOTHING!!}
{21}{005}{You are mad. And I'm here to make you answer for all the evil you've done to my people.}
{22}{006}{Drop it. I climbed the mountain of corpses to get to you. And I'm going to enjoy every second.}
{23}{006}{I'm the one who will tear you into a hundred little wires and feed your intestines to jackals!}
{24}{007}{You are not a God. You are just delusional. Think you are ruling the world? You're crazy!}
{25}{998}{You'll see who am I - after I'll stuff your ass with led!}

#Node003
{30}{}{You?! You think you DECIDE something?? A pathetic human with a primitive brain, not capable of comprehending your purpose! Not understanding that in fulfillment of purpose lies the prosperity of Olympus- no, the whole Radius! This is the foundation of our civilization's rebirth! And you chose to not fulfill your purpose! Do you think this makes you a chosen one? Think it makes you SPECIAL?! You are an ERROR! An inevitable FLAW, a faulty cog with an inflated ego! Do you think you came here to change the world? Make things BETTER?! NO!! You are not even the first!! But I exist to keep things in order - and I am fixing errors. Take your last breath, puny human.}
{31}{005}{You are mistaken - maybe I'm not the first to come here, but I will be the one who puts an end to your evil.}
{32}{998}{[prepare to fight]}

#Node004
{40}{}{You are so primitive... I'm surprised you even managed to go this far. This world is too complex for this tiny brain of yours. Enough talking. Adieu, brainless puppet.}
{41}{998}{Bring it on!}

#Node005
{50}{}{Evil... You, with your tiny brain, think that what I do is EVIL! Are you even capable of understanding your own words? For once in your boring little life, have you ever tried to distinguish EVIL from NECESSITY? Puny humans, unable to comprehend anything bigger than their pathetic existence... You see only the fact that people in Tartarus are bound to their way of life - yet by fulfilling their purpose they are saving the human civilization from becoming extinct. They are a crucial part of a coherent mechanism with an objective: a renaissance of mankind! Thousands of lives contributing to the greater good, each of them with a specific purpose! The order of things maintained by ME, created by the ones before me!! And you are willing to destroy EVERYTHING, leading to the fall of humanity, just because you pity your people. Isn't that evil? Selfish, cynical hypocrite!}
{51}{009}{Aren't YOU the one? You're saying that your way is the only right way! That everyone who thinks otherwise is wrong!}
{52}{998}{No! There is always another way! If I were in your place, I would do it better... And I might! Time to die!}
{53}{004}{You think too much of yourself, the "savior of a civilization"! You just like to play God!}

#Node006
{60}{}{You are so funny, puny human. So angry, so self-confident. Don't you see who you're talking to? Do you think you are the first to come here with the words like this? Yet I'm still here. And will be here tomorrow, and in ten years. And I will kill as many of you as it takes to maintain the salvation of Radius. Let's finish this. I have a lot of things to do.}
{61}{012}{Wait a second! There were others before me?}
{62}{998}{You're full of shit, false God. [reach for a weapon]}
{63}{998}{It's showtime! [fight]}

#Node007
{70}{}{You are too primitive to understand how complicated the world is. Like every other puny human, you don't know what it takes to keep mankind from dying out. Look what I turned myself into! I forfeited my humanity, bounding myself to the tower's systems. Why? Because this is what needs to be done to save the Radius... As I said, you are not able to understand. You fail to see that the real evil is the desire that brought you here. You want to kill me - and condemn the human race to die. You want to ruin everything! So I need to stop you. Right now!}
{71}{008}{I don't believe you. Your worldview is based on lies! And I'm going to bring you to justice!}
{72}{998}{No! It is ME who will stop YOU! [attack]}

#Node008
{80}{}{What is a lie, and what is justice? This world, fueled by lies, is much more complex than you can imagine with your tiny brain. Are you willing to destroy the remains of civilization and condemn humanity for justice and truth? Think about it, before you die. [you hear the turrets humming]}
{81}{998}{[attack]}

#Node009
{90}{}{You don't know what it takes to be me. What things I've seen. What sacrifices I made. I've been witnessing the effect of my actions for years! The plans that were set in motion by my predecessors! That's why I KNOW that what I do is right! And I'm even willing to suffer for it. Each Anderson before me knew that he had to sacrifice his humanity and bound himself to this tower just to fulfill his mission, his destiny. To make sure that mankind will thrive. And each of us did it without hesitation. Yet you dare to accuse me of being selfish?}
{91}{010}{Yes, I do! You make it look like you are the savior of Radius - but you have been sitting here for too long. The Olympus is not the center of the whole world!}
{92}{998}{Look at him, thinks he's the martyr. All you really want is to stay in power. Just die already!}
{93}{}{No... Each Anderson before me knew that he had to sacrifice his humanity and bound himself to this tower just to fulfill his mission, his destiny. To make sure that mankind will thrive. And each of us did it without hesitation. But you know nothing - and you shouldn't. You should only die to leave things as they are. I'm tired of you. Let's end this.}
{94}{998}{We'll see about that!}

#Node010
{100}{}{You know so little. A pity. You seemed smarter than the others. "I'll save the world from you! Die, evil creature!" - every time it's the same... No one understands... No one is ever grateful. I'm so... tired.}
{101}{011}{Grateful? You are abusing your power to make people believe in tales about you being God! You are pathetic!}

#Node011
{110}{}{You don't... NO![the wires around him start to crackle] You distracted me! I didn't have the time... NO!! I SHOULD HAVE... MAKE IT!... NO DISTRACTION!! NOOOO!!! URGHGLGHHH... [he rolls eyes, froth is coming out of his mouth] }
{111}{999}{[observe]}

#Node012
{120}{}{There are always some insolent fools, who don't want to fulfill their purpose, don't want to be a part of the mechanism. Some of them are venturing to the world outside - and end up dreaming about going back to Tartarus, spending their lives in Metro Station, or nearby settlements... But there are always others who are obsessed with a desire to change the way of things. And sometimes they come to me. They say "I'll save the world from you! Die, evil creature!". Stupid, soulless, empty humans... They fail to comprehend the complex nature of the world. And I destroy them before they do any damage with all their stupidity and insolence. It's time for you to join them. Adieu, puny human.}
{121}{998}{You are wrong! And your time has come!}