##############################
#Локация: "Олимп"
#Имя: Дэймонд Кранк
#Краткое описание: Пожилой безумный ученый
#Дата создания: 20.10.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a twitchy old man.}
{2}{}{He has dirty, bushy hair. Even from a distance, you can notice how shaky his hands are - looks like he is very nervous.}
#
# после знакомства
{3}{}{You see Diamond "the madman" Crank.}
{4}{}{Probably, in this exact second he thinks about some mad stuff. For example, a new way to kill everything alive in Radius.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[A gray-haired, unkempt man in a lab coat stands still, barely moving his lips. Fingers on his left hand are twitching as if he is writing something down. Looks like he stares right at you - but then you see that his sight goes through you. He doesn't seem to notice you at all.]}
{11}{002}{[slowly wave your hand in front of his face]}
{12}{002}{[gently touch his shoulder]}
{13}{998}{[come closer to his ear and shout as loud as you can]}


{20}{}{[No response. At least, nothing visible: lips are still whispering, the hand is still writing, eyes get even more blank.]}
{21}{003}{[wave both hands in front of him]}
{22}{003}{[shake him by the shoulders]}
{23}{998}{[kick him in the knee]}


{30}{}{[The scientist freezes for a second. Then looks at your forehead - and suddenly shouts "KA-BOOM! Oozy mess, Why didn't I put that together before?!" His sight becomes blank again.]}
{31}{004}{[accept the situation and wait]}
{32}{006}{[accept the situation and wait]}
{34}{005}{[Start to say "hey" repeatedly, shaking him by the shoulders]}
{35}{007}{[Start to say "hey" repeatedly, shaking him by the shoulders]}


{40}{}{[after another half an hour, he stops moving his fingers and takes a deep breath. Then he looks right at you - now deliberately.] Goddamn it, you distracted me twice! Piece of plasma into your pants! A bit more, and this integral would remain unresolved - because of you. Get it, oozy mess? You're guilty, and you need to make up for it! Right! Now!}
{41}{008}{Make up for it? Ha. What do you need me to do?}
{42}{009}{Easy! I only wanted to ask a couple of questions.}
{43}{999}{No, no, no. No making-ups. I'm leaving already. }


{50}{}{[he stops moving his fingers and takes a deep breath. Then he looks right at you - now deliberately.] Goddamn it, you distracted me twice! Piece of plasma into your pants! This integral slipped away from me - because of you. Get it, oozy mess? You're guilty, and you need to make up for it! Right! Now!}
{51}{008}{Make up for it, you say? Let me guess - you need me to do something for you?}
{52}{009}{Easy! I only wanted to ask a couple of questions.}
{53}{999}{No, no, no. No making-ups. I'm leaving already. }


{60}{}{[after another half an hour, he stops moving his fingers and takes a deep breath. Then he looks right at you - now deliberately.] Piece of plasma, look who we have here. A shepherd of mindless sheep. Instead of distracting me - twice! - you could think about why science is much more effective for the future of Olympus than all these religious affairs of yours! Although, oozy mess, you're just in time - and can be of some use for the greater good of science.}
{61}{008}{For a greater use of science? Let me guess - you need me to do something?}
{62}{009}{Easy! I only wanted to ask a couple of questions.}
{63}{999}{No, no, no. No science. My department is strictly faith. My "sheep" wouldn't understand. }


{70}{}{[he stops moving his fingers and takes a deep breath. Then he looks right at you - now deliberately.] Goddamn it, you distracted me twice! Piece of plasma into your pants! This integral slipped away from me - because of you. Get it, oozy mess? Did you come to tell me about your cult? I'd rather have you, fanatics, washing my test tubes instead - would be more useful. By the way, about being useful. You can be useful to science!}
{71}{008}{Be useful to science? Let me guess - you need me to do something?}
{72}{009}{Easy! I only wanted to ask a couple of questions.}
{73}{999}{No, no, no. No science. My department is strictly faith.}


{74}{}{Oozy mess! I like smart people. Yes, exactly! Do something! Something... I need a gun. "Baraka". It's riiiiiight there. [he pulls out a crumpled piece of paper with a crudely drawn map from his pocket and shoves it to you] In the Army Headquarters. Get it, oozy mess? "Baraka" gun - a big BA-BOOM! }
{75}{018}{I have been there already. And if there was a gun, I might have sold it...}
{76}{999}{Is that it? Okay... But no promises.}
{77}{009}{Why do you need it? }
{78}{015}{"Baraka"? This one? [show the gun]}
{79}{999}{No, I'll pass. Handle it yourself.}

{90}{}{No questions, piece of plasma! I'm doctor Diamond Crank. This is Billy, my robot. He needs an upgrade. Urgently. That's all you need to know. Done with the theory - now to practice. You can help me. I need a gun. "Baraka". It's riiiiiight there. [he pulls out a crumpled piece of paper with a crudely drawn map from his pocket and shoves it to you] In the Army Headquarters. Get it, ignoramus? "Baraka" gun - a big BA-BOOM!}
{91}{018}{I would gladly do it. But I had this "Baraka" gun - and I think I lost it. Maybe threw it out, maybe even sold it. I don't remember.}
{92}{999}{Okay, okay. You'll get your gun.}
{93}{999}{I don't deal with schizophrenics. Handle it yourself.}


{100}{}{[A usual picture - Crank is fully catatonic and detached from an outside world. Surely, his head must be bubbling with graphics, matrices, and numbers right now.]}
{101}{011}{Hey, we need to talk! A couple of minutes! Indulge me!}
{102}{011}{[pulll his shoulder] Heyo! Do you hear me! Get back to reality!}
{103}{999}{[leave silently]}


{110}{}{[this time you had to wait a little less. The scientist finishes calculating something in his mind - and only then turns his attention to you.] Oozy mess, you again? Okay, sin, 13,975 is approximately... Tends to zero... Damn! Piece of plasma! Speak! Fast!}
{111}{008}{You wanted me to do something, remember?}
{112}{013}{I wanted to talk about the "Baraka" gun.}
{113}{020}{About Ludwig.}
{114}{012}{Do you even rest? Ever?}


{120}{}{Oozy mess! Did you interrupt me for that? KA-BOOM! What rest? Maybe you will debug Billy instead of me? Get out of here! So, what was that... 13,975... Let's differential this... Are you still here? Het the hell out!! You're distracting me!}
{121}{999}{[leave silently]}
{122}{998}{[punch this scientist asshole's face]}


{130}{}{[Looks like Crank puts a great effort to divide his attention into two parts - one on calculations in his mind, and the other on assessing everything around and comprehending it. Although, you understand that now he sees you quite clearly.]}
{131}{014}{Remind me, what do you want me to do?}
{132}{015}{Here is it, your "Baraka".}
{133}{016}{About "Baraka" testing...}


{140}{}{KA-BOOM! Look at him! He forgot! Oozy mess, you should bring me a big KA-BOOM! "Baraka"! Bring me the "Baraka", damn you! Understand? I'm explaining it like you're stupid. Go! }
{141}{999}{Okay, okay, I'm going.}


{150}{}{[his answer is unusually fast] Wonderful... Wonderful! Wonderful, oozy mess, wonderful!! Just when I needed it. Give me that! Let's see... [he takes away the heavy weapon and disassembles it in mere seconds. Just as fast, he assembles it back, aims into the nearest wall, and shouts "KA-BOOM!!" Then he drops the gun, writes something down, and looks back at you.] Wonderful! This piece of plasma is exactly like I thought it would be. Hahahaaa! Now, take it, take this keycard and go to floor 96! Shoot at the "Defender" armor, hahahaha!! KA-BOOM!! And report back to me. Oozy mess! Go! }
{151}{999}{Right now? Let me catch a breath. Okay, I'm going.}


{160}{}{[his hair is even more messy than usual. He repeatedly throws hands up, as if aiming, shouts "KA-BOOM!!", giggles, and twitches with impatience. He notices you immediately.] Oozy mess! You kept me waiting. So? How was it? KA-BOOM? Tell me! Tell me everything!}
{161}{017}{What can I say... Everything was smooth as baby's bottom. A great penetrating effect. I'm gonna be sewing holes in my belly for a long time now.}
{162}{999}{I still haven't tested it. Wait for a little. Be back soon.}

{170}{}{Well, that's not exactly the description I was hoping for. But! I liked it, a piece of plasma! Did you? Hahaha! What were you saying? Smooth as baby's bottom? A "Defender" armor... Like baby's bottom? Haha. Hahaha! HAHAHA!! KA-BOOM!! Exactly what I needed. My Billy will become much more effective. Thanks... And now get out!! I need to work. I'm surrounded by dumb cretins!}
{171}{999}{[leave]}
{172}{998}{[stop holding back and enjoy punching his jaw]}


{180}{}{That's new. That's stupid. Are you high? Look at him! How could you lose my gun? Oozy mess. Wait! I know what to do. Look into my eyes and listen carefully. You. Take this. [he hands you a syringe, almost driving a needle into you] Poke Ludwig Schwein. And tell him "Hey, Ludwig! Go to Diamond!" And bring him to me. Understand? I'm explaining it like you're stupid. Go! How could you lose my gun, oozy mess?}
{181}{019}{Uh, I don't know how to put it... Today's not your lucky day, I guess. Ludwig is... Not going anywhere. Ever.}
{182}{999}{Don't be so steamy. It's just a gun. Bring Ludwig Schwein to you? Drugged? Smells like a dirty business... Okay, I'll do it.}
{183}{999}{You're making me very nervous. Try to be polite when asking people to do something. Bye.}


{190}{}{What the hell! I'm surrounded by dumb cretins! No! No!! No!!! Why?! [he tries to rip off a sleeve from his lab coat, but fails. He ends up tearing down his pocket. You see a keycard dropping on the floor.] Piece of plasma into my brain! Poor Billy... No upgrade for you! This oozy mess won't help me! Damn! Get out!! I need to work. Idiot. Cretin!}
{191}{999}{[leave]}
{192}{998}{[stop holding back and enjoy punching his jaw]}


{200}{}{[Looks like Crank puts a great effort to divide his attention into two parts - one on calculations in his mind, and the other on assessing everything around and comprehending it. Although, you understand that now he sees you quite clearly.]}
{201}{021}{Remind me, what do you want me to do?}
{202}{022}{I brought him.}
{203}{019}{Uh, Ludwig won't come to you... Anymore. Ever.}


{210}{}{He forgot! Piece of plasma! You poke and bring Ludwig! Goddamit. Understand? I'm explaining it like you're stupid. Go!}
{211}{999}{Okay, okay, I'm going.}


{220}{}{I need a couple of days... To properly interrogate this oozy mess. A couple of hypnosis tricks, some drugs, and KA-BOOM!! Soon I'll know everything I need about energy weapons! You, come by later - I have something for you to do. Piece of plasma. }
{221}{999}{[leave]}


{230}{}{[you see a heated "conversation" of two brightest minds in Radius. Looks like Crank used everything he could - drugs, threats, and hypnosis. Nothing has any effect on Ludwig. It looks as ridiculous as nasty and dehumanizing. Still, the scientist is so deep in the process that you won't be able to speak to him.]}
{231}{999}{[leave]}
{232}{998}{[interrupt the interrogation]}


{240}{}{[Looks like the Diamond is done "speaking" to Ludwig. He looks more brooding than before. Seeing you, he makes gestures with his hands. He definitely wants something from you.] Oh, piece of plasma! Glad to see you. Look what I have. [he shows you a huge weapon he's holding] This gun - a big KA-BOOM!! Haha! You get it. Go to floor 96 and test it on a "Defender". And then bring it back and tell me how it went. Understand, oozy mess?}
{241}{999}{As usual... Okay, but this is the last time.}
{242}{999}{No. Find someone else.}

{250}{}{[A usual picture - Crank is fully catatonic and detached from an outside world. Surely, his head must be bubbling with graphics, matrices, and numbers right now.]}
{251}{026}{Hey, we need to talk! A couple of minutes! Indulge me!}
{252}{026}{[pulll his shoulder] Heyo! Do you hear me! Get back to reality!}
{253}{027}{[wait patiently]}
{254}{}{[leave silently]}

{260}{}{[No response]}
{261}{027}{[keep waiting]}
{262}{029}{[keep waiting]}
{263}{999}{[leave silently]}


{270}{}{[Diamond is deep into his thoughts. This time you decide to wait and listen to him whispering.]}
{271}{028}{[keep waiting]}


{280}{}{[The scientist almost reflexively reaches into his pocket. Pulls out something, glances over it, then sighs and drops it. Nothing else is happening.]}
{281}{999}{[Bend down and pick up the thing]}


{290}{}{[Crank is still busy with himself. You keep waiting. Suddenly, you become interested in his quiet ramblings.]}
{291}{030}{[his whisper becomes louder. Louder. And louder. It fills everything around. Looks like this voice pushes every thought out of your head. You don't see anything, don't feel anything. You only hear a whisper: formulas, calculations, graphs descriptions... Suddenly, something clicks in your head, and you clearly say "1 874 449 234 744 934, 375 88".] }


{300}{}{What?! Goddamit, piece of plasma! What did you just say?}
{301}{031}{I don't remember!}


{310}{}{You said "1 874 449 234 744 934, 375 88", - and that's genius, piece of plasma! You are totally right! Hahaha!! Who would have thought that you have some hidden talents, oozy mess! [Crank continues to ask you questions. Somehow, you find answers to them. It goes on for hours. Diamond makes a lot of notes.]}
{311}{999}{I'm so tired... [you feel exhausted. You slowly descend to the floor and fall asleep]}

{320}{}{you open your eyes and try to stretch your neck. Looks like you've been carelessly asleep for an hour - right on this cold floor, next to a mad scientist.}

{321}{}{Huma-n-n-n... H-h-h-h...}
{322}{}{Do n-n-n-ot ap-p-roach.}
{323}{}{B-b-be carefu-u-u-u-l!}
{324}{}{KA-BOOM! Piece of p-p-p-plasma!}
{325}{}{B-b-billy is good! Ob-b-b-bedient.}