##############################
#Локация: "Олимп"
#Имя: Филлип Грей 
#Краткое описание: Ведущий ученый из лаборатории органических исследований
#Дата создания: 22.11.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see young and strong man wearing clean clothes.}
{2}{}{He is carefully studying some documents.}
#
# после знакомства
{3}{}{You see Philipp Gray.}
{4}{}{He is deep into studying some materials about biology.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[the young scientist notices you approaching him - although, he looks at the Chimera, not you] Really? So, Richards managed to get me a specimen, at last? [he slowly walks to the creature, silently staring for some moments, then touches it] Oh... What an... Instrument. [he turns to you] Remind me, what's your name?}
{11}{}{[the young scientist notices you approaching him] I have to ask you not to interrupt me. Unfortunately, I have no time to spare on talks with soldiers. Now - I need to do my work.}
{12}{999}{[end of dialogue]}
{13}{002}{I'm Gregorius...}
{14}{002}{I'm Douglas, the Seeker. }

{20}{}{Oh, a Herald? From lower levels?... Tell me, what do you think of those creatures? [he nods at Chimera]}
{21}{}{A Seeker? [he looks over your armor] You must be... One of the Richards veterans, right? Do you... Hate Chimeras as much as he does?}
{22}{003}{No, I'd say that they are interesting.}
{23}{004}{Actually yeah, they are disgusting. }
{24}{003}{This one is a fine exemplar for studying.}
{25}{004}{I'd prefer to burn any of them down. The sooner, the better.}

{30}{}{Really? I can say that I'm surprised... Pleasantly surprised. And I'd like you to do a favor... To the science. And to the whole Olympus. And this favor directly concerns this Chimera. There's one... Nasty atavism around, which slows down our cutting-edge research. And his name is Constantine Zochkis. We have an argument about the effectiveness of different types of weapon, and he says that my methods are... Questionable, let's put it like that. I'd like to prove him wrong. Say, would you want to participate in Olympus arms race?}
{31}{005}{Sounds interesting. }
{32}{006}{What do I get from it?}

{40}{}{Just as I suspected... Although, I'd like to ask you for a favor anyway. A favor... To the science. And to the whole Olympus. And it directly concerns this Chimera. There's one... Nasty atavism around, which slows down our cutting-edge research. And his name is Constantine Zochkis. We have an argument about the effectiveness of different types of weapon, and he says that my methods are... Questionable, let's put it like that. I'd like to prove him wrong. Say, would you want to participate in Olympus arms race??}
{41}{005}{Sounds interesting. }
{42}{006}{What do I get from it?}

{50}{}{Oh... Perfect! There's a way to deal with this argument with an incredible elegance. Zochkis is sitting at his office, locking himself into his motorized armor suit, because he has a strong delusion of persecution - but that's not related to the case. What is, however, is that he is afraid of Chimeras, like a little girl! But at the same time, he says that Chimeras can't be used for the defence of Olympus, because they are not very effective. So, I want you to take a Chimera and to go have a talk with this old bore. Make him attack the Chimera, so we could find out what's more effective - his armor suit or claws of my new pet. Although, if he dies in the process - I wouldn't mind... And be quite pleased too.}
{51}{007}{I'm in. }
{52}{007}{I'll think about it. If I agree, I'll come back with the results. }

{60}{}{You? [he scratches his chin] My grattitude. I think I can... Upgrade your status in the tower. Provide you with resources. And give you access to the computer of Zochkis. Should be many interesting things in there. [he winks]}
{61}{007}{I'm in. }
{62}{007}{I'll think about it. If I agree, I'll come back with the results. }

{70}{}{Great! Take this keycard from the level where Constantine works. And let me know about the results. }
{71}{999}{[end of dialogue]}

{90}{}{[scientist turns to you] Hmm... Remind me, what's your name?}
{91}{}{Yes, of course... I'm Philipp Gray. For you, it's professor Gray. I'm sure, Richards already told you about my request for a... Certain sample of Radius fauna. And I don't see the sample, so I have to ask you not to waste my time any longer.}
{92}{999}{[leave silently]}
{93}{092}{Professor, does the words "Dick", "promise" and "some plans" mean anything to you?}
{94}{}{Oh, good old man Dick... Did he decide to resort to blackmailing? Silly, he has nothing on me, only empty words. But still - a promise is a promise. I gave my word. Besides, it's a good chance to test the cloning machine after recalibration. So, please, go to the upper level - you can use the ladder at the opposite side of this floor - find dr. Moro and give him the power cell. He knows what to do.}
{95}{093}{Cloning machine?}
{96}{999}{Okay, I'll go visit this Moro.}
{97}{}{Yes, a great legacy of the past. We used these devices some time ago, to control the Tartarus population level, when we had a... "Bad harvest" of Servants, let's put it like this. Well, now we are more often presented with an opposite problem, but cloning machines are still being used sometimes - as in now. Don't waste any more time and go to Moro.}

{100}{}{I see you came back. Is there something important?}
{101}{}{Here comes our supporter of right development of the Olympus defence... Do you have any new helpful ideas?}
{105}{}{I don't know what you did, and I don't want to know, but this stupid Kelly doesn't bother me anymore. Thanks. Did you want something?}
{102}{012}{Yes. I have some news. And you're going to like it.}
{103}{011}{No.}
{104}{999}{[end of dialogue]}

{110}{}{Then we have nothing to talk about for now. }
{111}{999}{[end of dialogue]}

{120}{}{Great! I'm not interested in details... I'm more interested in the results. And I need to study the results. And your result is this - a blocked keycard. The password to the dashboard panel at that level is 2358, as for the keycard - you can unlock it using bore's computer. D-3, if I'm not mistaken. If... When my time comes - I'll reward you properly. And now I have some business to attend.}
{121}{999}{[end of dialogue]}

{130}{}{Then we have nothing to talk about for now. }
{131}{999}{[end of dialogue]}