##############################
#Локация: "Олимп"
#Имя: Джок
#Краткое описание: Охранник-мудак с зашкаливающим эго
#Дата создания: 42231,ДДММ.ГГГГ
##############################
#Для игры "Олимп 2207"
#Сергей "Zoomer" Бокарев
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a tough guard in a decorated leather jacket.}
{2}{}{He tries to make it look like he's in charge.}
#
# после знакомства
{3}{}{You see Jock.}
{4}{}{Still as brazen and confident as before.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[The leather jacket has several faded patches on it, some of which are pretty rare, maybe even pre-war. One patch inscribed with a word "Jock". The owner must really care about this jacket. When you approach, he looks at you as if you were a piece of dirt on his boot.] What the fuck do you want from me? Get the hell off, I'm busy.}
{11}{022}{Continue like that, and I'll break your jaw.}
{12}{011}{Richards sent me. For an inspection.}
{13}{027}{Where's your uniform, soldier? Why do you look like a cheap whore? Answer, when the senior officer asks a question!!}
{14}{999}{[leave silently]}


{20}{}{[Jock is breathing heavily]}
{21}{}{::sniffles::}
{22}{}{[Jock tries to pull himself together]}

{30}{}{Sir, I'm not done yet, sir!}
{31}{}{[operating plunger with a sad look]}
{32}{}{::phhhheeewwww::}

{40}{}{I hate snitches!!!}
{41}{}{[stands at attention]}

{101}{}{Sir, awaiting for orders, sir!}
{102}{033}{Recovered? Good. Give me an update.}
{103}{999}{Recovered? Good. Stay tight, I'll come by later.}
{104}{043}{You can prepare your corn cob, soldier. Kelly is coming to you. }
{105}{}{You again? I have everything alright here, you can stop trying to find screw-ups to report captain.}
{106}{025}{I convinced her. Your dream is coming to you.}
{107}{018}{Here's the thing... Your Kelly toppled a wrong vial over herself.}
{108}{014}{That's for me to decide. You were saying something about a business. Spill it.}
{109}{021}{I see you are not on the best terms with Richards?}
{1010}{}{[Jock is cleaning his jacket, whistling something. He looks pleased.] Who we have here? Want to grab a drink? Just let me finish with the jacket - this dumb whore got her blood all over it again.}
{1011}{023}{Can't get enough of Kelly now, I see?}
{1012}{999}{Maybe later. See you around, Jock.}
{1013}{999}{Don't twitch, I was just coming by. At ease, sergeant.}

{110}{}{[Hearing captain's name, he gets pale] I... What's the problem? Everything's cool! Tell captain Richards not to worry, sergeant Jock knows his stuff! And, uh... Sorry for that, serriously. Let's start again, maybe? I'm Jock, the sergeant of security. [he extends a hand]}
{111}{012}{[ignore his hand] Sergeant? Seriously?}
{112}{013}{[shake his hand] Okay, nevermind. I see it's definitely quiet around here.}

{120}{}{[he tucks his lips and starts to clean a spot from the jacket] I appointed myself. And no one seems to mind. Even captain Richards. Besides, who watches the order around here and coaches the guys? That's right, good old Jock.}
{121}{022}{That's why you need this jacket? By the way, do you know that you look like a twat wearing it?}
{122}{013}{Better tell me how it's going. I still need to make a report for Richards, you know.}

{130}{}{ Well - it's boring, mostly. My hands are itching to punch someone. And there's this Kelly... [he pauses] Listen, maybe you can help me with one delicate matter? I'll make it worth your while! And it would definitely be more interesting than run errands for captain.}
{131}{014}{Tell me more.}
{132}{014}{Errands? You're lucky I'm in a good mood. So, what do you want?}

{140}{}{[he gets lively] So, here's the thing - there's one lab assistant at the biologists, name's Kelly. She hangs out with smart-asses, but her brain is the sise of a lavash testicle. Still, why would a girl need to have a brain when she has such an awesome junk and a pair of big boobs, am I right? I bet every guy around here polishes his barrel thinking about her. And this treasure was supposed to belong to that moron Timmy! Can you believe that? But now, when Timmy is gone in Tartarus, the place is vacant... Know what I'm saying?}
{141}{015}{I think I do. What do you want from ME?}

{150}{}{Talk her into coming to me! I tried it myself, but she passed, saying "boo-hoo, only Timmy, he will get back soon". Stupid bitches... There's only two things they're good for - help us release the tention, and give birth to our future soldiers. So, would you help? You're the Richard's man, after all, and he is well-respected around here. I will give you something good - here! [he swiftly pulls out a colt "python" from a holster] Good one, right? Don't worry, it's my personal. Ony, uh... Don't tell Richards, okay? [he nervously looks around]}
{151}{016}{Before answering, I need to ask you a couple of questions.}
{152}{017}{We'll see, Jock. No promises.}
{153}{030}{And that's the kind of bullshit you are busy with here? I think I need to note it in my report. }

{160}{}{[he shrugs] Okay, ask. What's there to not understand?}
{161}{020}{I see your relationship with Richards are quite strained. What does he think about your intentions?}
{162}{024}{What did Kelly have with this Timmy?}
{163}{017}{Actually, I understood enough. I agree.}
{164}{999}{I think this job is not for me. See you. [leave]}

{170}{}{I knew it! I knew you're a nice guy! Okay, here. [gives you a keycard] It's the thing that makes guards around here ready to cut each other's throats - an access to a Biology level... To Kelly. [he smugly scoffs] Only Richards has one. And me.}
{171}{999}{Aren't you a lucky one. Okay, I'll tell you when it's done. [take the keycard and leave]}

{180}{}{[he stares at you, looking confused] So? If she had her clothes dirty, it's okay - the bitch won't be needing it with me. }
{181}{019}{It's not so simple. That vial had some virus strain. Which is highly sexually transmittable. Long story short, I wouldn't risk banging her.}

{190}{}{ That... Stupid bitch! Stupid, stupid bitch!! Science, my ass... Why are you standing here? The deal is off now! Go.}
{191}{999}{Screw you! Waste of my time. [turn around and leave]}
{192}{999}{There-there, don't cry, soldier! You can always make yourself happy in the shower. [leave]}

{200}{}{[he tries to look careless, but you notice a fear in his voice] Uh, what? We are cool with captain Richards! He trusts me completely. By the way... Don't tell captain about Kelly. Why whould you need to distract such a busy man with something this petty?}
{201}{016}{You already asked me. Another question.}
{202}{017}{You can stop reminding me. I agree.}
{203}{999}{I think this job is not for me. See you. [leave]}

{210}{}{[he tries to look careless, but you notice a fear in his voice] Uh, what? We are cool with captain Richards! He trusts me completely. By the way... Don't tell captain about Kelly. Why whould you need to distract such a busy man with something this petty?}
{211}{999}{Right. Stay tense, sergeant. [nod and leave]}

{220}{}{[he looks dazzled] Are you serious? Okay, you're going to get a good lesson. Try to not get my jacket dirty.}
{221}{998}{You're going to be buried in it!}
{233}{027}{I'm gonna cut your jacket in little slices and make you scrub toilets with it, you clown! Did you hear about the subordination? I'm your superior officer! And I'll teach you some discipline!}

{230}{}{You bet! [he pats his pands] I have a whole month's supply in here, so I need to load it off as soon as I can. I broke her claws already, so now it's a little boring - I don't even need a rope. No resistance at all. }
{231}{999}{Too bad I have no time for something like this. See you around, lucky boy.}
{232}{999}{[leave silently]}

{240}{}{[he cringes] What to say about it? Our eggheads are lost their stupid minds, if they picked a thin moron like Timmy for such a good chick. Damn selection... I mean, Timmy was okay, but I'm glad he disappeared in Tartarus. Yes, I'm honest about it. What would he do with such a girl?}
{241}{016}{I see. Another question then.}
{242}{017}{I heard enough. I agree.}
{243}{999}{I think this job is not for me. See you. [leave]}

{250}{}{Man, you've really helped me out! I won't forget it! Okay, now someone is going to learn what true love is. Wait here, okay? I'll be right back, won't beat her hard this time. [he hastily leaves]}
{251}{026}{[wait]}

{260}{}{[Jock returns. His face is shining with a smile] That was such a good fuck! If you could only see it! I almost tore the bitch in half! She resisted, can you imagine? I had to subdue her and punch her face, just in case. Anyway, here. It's yours now. [he hands you a pistol] I have other gun prioritized now! [he winks]}
{261}{999}{Glad for you. I wish I could have fun like you do. Okay, see you. [take the gun and leave]}
{262}{999}{[silently take the pistol and leave]}

{270}{}{[Jock freezes in surprise] Superior? What?}
{271}{028}{Not "what" me! You will call me SIR! Thirty push-ups, you clown!}
{272}{029}{Yes, superior! You're gonna get five shifts of guarding the Purgatory for this!}

{280}{}{[Jock stares at you, he doesn't seem to understand what's going on. He starts to slowly descend on the floor]}
{281}{999}{["help" him by punching his back] One! Two! One! Two! Keep up, clown! Maybe you have some potential!}
{282}{999}{[grab his jacket's collar and shake it] Too slow! TIme to teach you some discipline, you mutt...}

{290}{}{But... I...}
{291}{028}{Shut your pie hole, mouthy guy! I see you fail to comprehend what discipline is! Then I'm personally taking care of you, clown! Thirty push-ups! Go!}

{300}{}{Hey! I treat you like my own, and you want to snitch on me? We don't do things this way here!}
{301}{998}{You'd better pray for me to have a good mood when I'll go reporting the captain.}
{302}{031}{Oh yeah? We can figure something out. If there's nothing to report, I'll be very sad. But if I were to receive something to not be sad...}
{303}{032}{Relax, I won't put it into my report. Just keeping you in your toes. But I'll remember that.}

{310}{}{No shit. A deal is a deal. Help me - and you'll get the gun. Don't - go screw yourself. This was my personal request, it doesn't concern my duties. And it still stays. }
{311}{016}{Okay, I'll think about it. But I have some questions first.}
{312}{999}{No promises, but I'll think about it. }

{320}{}{Yeah-yeah. My offer still stands.}
{321}{016}{Okay, I'll think about it. But I have some questions first.}
{322}{999}{No promises, but I'll think about it. }

{330}{}{Sir, everything's alright. There's only lack of shag. I mean, not with my duties, with normal chicks. [Jock gets silent, assessing your reaction] Permission to make a request, sir?}
{331}{034}{Granted.}
{332}{042}{Granted. Explain your request while doing push-ups.}
{333}{038}{Denied.}

{340}{}{Sir, as part of the alleged problem, I'd like to apply for a sexual partner. Unofficially. One of lab assistants had lost her potential parnter, and I want to take his place. Official requests through captain don't have any effect... I learned that if she agrees once, we can shag as much as I want - at least until new partner is chosen. And I would really want to give her a full ride.}
{341}{035}{Why don't you carry your ass to her and try to deal with it personally, instead of bugging your superiors with such requests?}

{350}{}{Sir, she is against it. I can't subdue and bonk her at the Biology level. I'd like to lure her here, to our floor, but I failed to do so until now. I have an access keycard, maybe you could help me with this problem?}
{351}{036}{Keycard? Where did you get it? Should you even have one?}
{352}{999}{Well... Let's see what can be done. Hand over the keycard. I'll consider your request.}
{353}{999}{Tired of abstinence? I'll show you! Hand over the keycard! Thirty push-ups!}

{360}{}{Uh... Yes, sir!}
{361}{037}{Of course. Hand over the keycard, clown.}
{362}{999}{Well... Your needs are influencing you doing your duties. So, I'll consider your request. }
{363}{999}{No you don't smart-ass! Hand over the keycard! Thirty push-ups!}

{370}{}{[Jock reluctantly gives you a keycard]}
{371}{999}{Good boy. Now, thirty push-ups!}
{372}{999}{About your request - your needs are influencing you doing your duties. So, I'll consider it. }

{380}{}{[Jock looks visibly nervous, his hands are trembling. It leads to him accidentally dropping the keycard he was holding in his hand. He looks at you with his eyes wide open.]}
{381}{039}{A keycard? Why do you have it? By your rank, you shouldn't be issued with one! [pick it up]}

{390}{}{Sir, it's about my request. It's...}
{391}{999}{Didn't I forbid you to pester me with your problems? Thirty push-ups!}
{392}{040}{Tell me. But do it quickly.}

{400}{}{Sir, as part of the alleged problem, I'd like to apply for a sexual partner. Unofficially. One of lab assistants had lost her potential parnter, and I want to take his place. Official requests through captain don't have any effect... I learned that if she agrees once, we can shag as much as I want - at least until new partner is chosen. And I would really want to give her a full ride.}
{401}{041}{Why don't you carry your ass to her and try to deal with it personally, instead of bugging your superiors with such requests?}

{410}{}{Sir, she is against it. I can't subdue and bonk her at the Biology level. I'd like to lure her here, to our floor, but I failed to do so until now. I had an access keycard, but now all I can do is ask you. Would you help me with this problem?}
{411}{999}{Well... Let's see what can be done. I'll consider your request.}
{412}{999}{Tired of abstinence? I'll show you! Thirty push-ups!}

{420}{}{[Jock starts doing push-ups and talk. Because of his grunting and mumbling, you didn't understand anything he said.]}
{421}{034}{Okay, stand up! Atten-shun! I didn't get shit from what you were babbling. You talk like a scared weakling. Now, repeat.}

{430}{}{Sir, thank you, sir! }
{431}{999}{Gods forbid you to give me additional problems. I'll give you to the eggheads, they're going to test your durability with the help of Chimera males.}