##############################
#Локация: "Олимп"
#Имя: Капитан #34
#Краткое описание: Командир Дефендеров
#Дата создания: 22.10.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a Defender with insignias - one on his chest reads "Captain", and one on the left shoulder reads "#34".}
{2}{}{He is talking to someone using the radio transmitter in his helmet.}
#
# после знакомства
{3}{}{You see Captain #34.}
{4}{}{He is staring into a wall.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[seeing you, he stops talking on the radio and makes a warning gesture with his hands] Protocol D-14, unknown person detected on the floor. State your objective.}
{11}{002}{Uhh... Hello?}
{12}{004}{I have an assignment from Diamond Crank. I need to test this gun [show the weapon] on a Defender armor.}
{13}{002}{I'm just walking here.}

{20}{}{[he is silent for at least 5 seconds] State your objective. You have one attempt.}
{21}{004}{I have an assignment from Diamond Crank. I need to test this gun [show the weapon] on a Defender armor.}
{22}{003}{Are you stupid?}
{23}{003}{I'm already leaving, sorry. Won't bother you anymore.}
{24}{998}{I'll show you the objective, stupid tin can...}

{30}{}{Wrong answer. Attention! Protocol A-1 - terminate the intruder!}
{31}{998}{[fight]}

{40}{}{Request is processing. [he gets silent again. This lasts for another ten seconds.] Request denied. The Defender squad warrior is too valuable to waste his armor on weapon testing. Proceed in accordance with protocol E-11: the initiator of the experiment - that is you - will be issued with a suit of Defender armor. A firing command commences testing on the initiator wearing the suit. The testing is considered successful if the initiator is alive at the end of it. Otherwise, dr. Crank have to find another assistant to commence additional testing, and engineers will be assigned with a task of improving the armor's capabilities. The suit, in this case, should be immediately removed from the body and processed in the repairing facilities. }
{41}{005}{Such a great idea, just awesome! Are you kidding me?}
{42}{005}{What? I didn't sign up for this!}
{43}{998}{I have a better option. I'm gonna test this gun on you, right now!}
{44}{005}{Oh man...}
{45}{006}{Okay, let's proceed with this... E-11.}

{50}{}{[he gets silent for another 5 seconds] Protocol P-99: "A member of a laboratory staff or combat unit should obey direct orders of their superiors. In case of violation, the subject is to be liquidated."}
{51}{998}{Go to hell, you stupid rusty heap!}
{52}{998}{I have a better idea. I'm gonna test this gun on you, right now!}
{53}{006}{Okay, let's proceed with this... E-11.}

{60}{}{Copy. Stand by. [a group of Defenders, carrying the suit of armor, enter the room. You are ordered to change - right here, in front of them. Then you are being escorted into a testing room.]}
{61}{999}{[proceed to test]}
{62}{998}{[now, when you have the armor, you can just murder everyone... so, let's do it.]}

{70}{}{Vitals signs are stable. Given the damage sustained by your armor, I have to state that you are an excellent candidate for joining the special operations Defenders squad. So, I have an order for you - report to dr. Crank about the testing results, then return for your next assignment. Dismissed. [he turns around and immediately starts talking to someone on the radio]}
{71}{999}{[end of dialogue]}

{100}{}{For a candidate to a special operations squad, you move too slow. I expected you much earlier. Anyway, here's your Defender suit. Put it on.}
{101}{011}{[put on armor]}
{102}{012}{[put on armor]}
{103}{}{Testings failed - you attacked your teammates! Protocol A-1 - destroy him!}
{104}{998}{[fight]}
{105}{}{You have successfully completed the mission. You shall proceed to a Defender training course shortly... Stand by... [looks like he is receiving something on the radio] I have a new assignment for you - take this keycard and proceed to a "Server" floor for getting access to a Control Room. Don't delay, the order is of the highest priority.}
{106}{999}{Got it, on my way.}
{107}{}{Candidate, proceed on the floor 79 immediately, for receiving new access codes.}
{108}{}{Candidate, I have no further assignments. You shall be informed about the start of the Defender training course in some time.}
{109}{999}{Got it, on my way.}

{110}{}{Good. Protocol K-77 - Condition red. You're going to be part of a group send to the subway station. The mission is to purify the wasteland of every creature you'll find there. If the mission is a success, you will proceed to a Defender training course and become a full-time squad member.}
{111}{999}{[move out on a mission]}

{120}{}{Good. Protocol K-77 - Condition red. You're going to be part of a group send to a settlement of cannibalistic mutants. The mission is to purify the wasteland of these creatures. If it is a success, you will proceed to a Defender training course and become a full-time squad member. The additional task comes from a request #106 by dr. Philipp Gray: every Defender who delivers samples of human flesh from the operation's area will get stimulators, in addition to standard mission equipment.}
{121}{999}{[move out on a mission]}

{122}{}{Enough, you can report back to a Captain.}
{123}{}{[stares blankly]}
{124}{}{[doesn't pay any attention]}
{125}{}{[acts like a stone]}