##############################
#Локация: "Олимп"
#Имя: Константин Зочкис 
#Краткое описание: Ведущий ученый из конструкторского бюро
#Дата создания: 15.10.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a man wearing a mechanized armor suit.}
{2}{}{He is calibrating his armor while wearing it.}
#
# после знакомства
{3}{}{You see Constantine Zochkis.}
{4}{}{Because of all this armor, it's hard to say what's he really like.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[most likely, you see the head of Engineering you've heard about.]}
{11}{}{[most likely, you see the head of Engineering you've heard about. Seeing you, he makes a few steps forward, raising his hand in a warning gesture] How DARE you to come here with this abomination?! Get out of here, idiot! And take your pet away, before I wipe the floor with you both! Leave immediately!}
{12}{002}{Hey, grandpa. Where can I find Zochkis?}
{13}{003}{Hello there!}
{14}{004}{Is there a wildlife lovers club around here somewhere?}
{15}{005}{Wipe the floors? A bold statement from such a geezer.}
{16}{006}{I've heard you are into Chimeras...}
{17}{008}{There's a rumor going that you are afraid of Chimeras, screaming like a little girl when you see one. And now I can definitely say - it's the truth.}
{18}{999}{[don't start the conversation]}
{19}{999}{Okay, okay! I'm already leaving!}

{20}{}{[he stops calibrating his suit and bluntly stares] Who the hell are you, blockhead? Do you even realize who you're talking to? I am the head engineer of this place, the creator of the latest defense systems of Olympus, Constantine Zochkis! And you - how the hell did you even get on this level? What do you want here? Oh, let me guess - this incompetent and arrogant youngling Philipp sent you! You're his errand boy, am I right?}
{21}{998}{I was just making sure that you are Zochkis. Before ripping your head off.}
{22}{999}{Nothing, I want nothing. Just making sure that the rumors are true. I'm already leaving. Thank Gods, my mission is on the next level.}

{23}{011}{Actually, I'm here on behalf of Moro. He needs a power cell for a cloning machine.}

{24}{}{Moro!? Does he understand that he had spent three cells already? We don't have many of them left! No, no, and again - NO! And that's why... [suddenly, he freezes as if seen a ghost. Or heard one.] Okay... I just had an order to not interrupt the work of the Institute of Organic Science, so... Anyway, the parts are issued by Dick, you can find him on the opposite side of this level. That's it, we're done here.}
{25}{999}{Okay, I'll go visit Dick.}

{30}{}{[You are being ignored.]}
{31}{007}{Hello? I'm talking to you!}
{32}{002}{Hey, grandpa. Where can I find Zochkis?}
{33}{004}{Is there a wildlife lovers club around here somewhere?}
{34}{999}{[leave]}

{40}{}{What? What are you talking about? Get the hell out of here, or I'll throw you out myself!}
{41}{999}{Okay, okay! Just making sure that the rumors are true. I'm already leaving. I need the next floor anyway.}
{42}{999}{[leave]}

{50}{}{Are you having a psychotic break right now? I'm going to mince you!}
{51}{998}{Try it, you ancient wreckage...}
{52}{999}{Come on, old man, I was just fooling around. Relax, I'm leaving. I need the next floor anyway.}

{60}{}{[he turns to you. His armor makes loud echoing noises when he takes a step closer.] Last warning, clown.}
{61}{998}{Oh yeah? [suddenly punch him]}
{62}{999}{Come on, old man, I was just fooling around. Relax, I'm leaving. I need the next floor anyway.}
{63}{998}{[spit into the ocular of his suit]}

{70}{}{Don't disturb me. The talk is over.}
{71}{002}{Hey, grandpa. Where can I find Zochkis?}
{72}{004}{Is there a wildlife lovers club around here somewhere?}
{73}{999}{[leave]}

{80}{}{What? What the hell are you babbling about? I can kill these things with my bare hands!}
{81}{009}{Oh really?}

{90}{}{Watch me, you brat!}
{91}{999}{[watch him]}

{100}{}{[You are being ignored.]}
{101}{}{[seeing you, he makes a few steps forward, raising his hand in a warning gesture] How DARE you to come here with this abomination?! Get out of here, idiot! And take your pet away, before I wipe the floor with you both! Leave immediately!}
{102}{002}{Hey, grandpa. Where can I find Zochkis?}
{103}{003}{Hello there!}
{104}{004}{Is there a wildlife lovers club around here somewhere?}
{105}{005}{Oh yeah? I wouldn't jump to conclusions like that, if I were you.}
{106}{006}{I've heard you are into Chimeras...}
{107}{008}{There's a rumor going that you are afraid of Chimeras, screaming like a little girl when you see one. And now I can definitely say - it's the truth.}
{108}{999}{[don't start the conversation]}
{109}{999}{Okay, okay! I'm already leaving!}

{110}{}{Your punch comes into the junction of two armor plates in the abdomen. Some elements and parts puncture through the engineer's body, penetrating his intestines. Looks like you have accidentally found a sweet spot in this suit!}
{111}{}{ATTENTION! Administrator speaking. The access keycard of Constantine Zochkis is blocked. The floor is currently put under lockdown. Over.}