##############################
#Локация: Пещеры Нежити
#Имя: Боно
#Краткое описание: Мертвяк - меланхолик, лидер местных нищебродов
#Дата создания: 07.05.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов 
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see an old ghoul.}
{2}{}{This falling-apart ghoul looks ancient. He watches you with an unseeing gaze through his scant eyebrows.}
#
# после знакомства
{3}{}{You see Bono.}
{4}{}{Unspoken godfather to the family of unfortunate local exiles.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[his eyebrows slowly move upward, revealing whitish eyes] A new one, aren't you? [sighs] Why won't you all stay put in Tartarus? How do I feed another mouth?}
{11}{002}{What? A new one? What is this place?}
{12}{999}{What? No, I don't have time for this.}


{20}{}{New one - that's you, new one. Like the half of unfortunate seekers of a better life here, you just couldn't sit tight in one place...}
{21}{003}{Okay, let's sort this out. Is it a part of Tartarus? I mean, is this even a Tartarus?}
{22}{004}{I don't understand, old man. What are you talking about? You ARE an old man, right? You don't look too good...}
{23}{999}{That's it, I'm out of here.}


{30}{}{Listen, son... That's no Tartarus. I mean... There's THE REST of the world, except, Tartarus, you see? So now you are there, in THE REST of the world. We call this place "the caves of undead". I came up with the name. And I'm Bono if you are wondering.}
{31}{005}{Undead? So you all are undead? And you live here? All these people, wearing Tartarus clothes?.. Oh man...}


{40}{}{Well, let's say I'm the next step of being an old man. You could even say I'm the next step of being a DEAD man. And not the last step, unfortunately... The name's Bono. This place is called "the caves of undead". Here live the likes of you. And me.}
{41}{005}{Undead... This is no Tartarus, although you have no sky here as well. Who are all these people?.. Oh man...}


{50}{}{Don't be hasty, new one. The understanding cannot be rushed, or it will become distorted, hazy, and tangled... Let's start with the basics: what's your name?}
{51}{006}{My name is }
{52}{006}{, I came from Tartarus... And I need answers.}
{53}{999}{No, I need to think everything over first.}


{60}{}{Of course. Like literally everyone else before you [he smiles with a toothless grin]. If you already pulled yourself together, we can look into the answers you need.}
{61}{010}{Yes, I'd like to.}
{62}{999}{Not now, I need some time to think everything over first.}


{100}{}{Hmm... Hmm-hmm? Oh, it's you, }
{101}{}{. What do you need?}
{102}{}{Yeah? Something else?}
{103}{011}{Tell me about Tartarus!}
{104}{020}{How do you all live here?}
{105}{030}{Do you know anything about Gods?}
{106}{040}{My father is very sick, I need to get back to Tartarus.}
{107}{050}{You promised to help me, remember? Return the favor and all that.}
{108}{060}{You look somehow distracted. Lost something?}
{199}{065}{About that speech you want to give...}
{198}{069}{There's this guy Joe, he looks for his wife, Nadine.}
{197}{075}{I brought Priestley some fertilizer. So I've been thinking - maybe you need more of that?}
{196}{076}{I brought more fertilizer.}
{109}{999}{Nothing, we'll talk later.}


{110}{}{Tartarus... Yeah... Tartarus is a great place to, uh, live. It's interesting, really - you, who came from Tartarus, are asking me, who has never been there, to tell you about it. Better answer me, why did you run away from there?}
{111}{012}{Run away? This was an accident! I never even thought about running away from serving...}
{112}{013}{Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident.}
{113}{013}{Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident. Usually, the Sons of Gods don't make such fast accusations.}
{114}{014}{Uh, yeah, sure I ran away! I always knew that life is not only about serving Gods, there must be something more to it, some... Higher purpose, I suppose.}


{120}{}{So that's how it is, huh? Interesting, yeah... So interesting... And very unusual... [his eyes are wide open, but you see that ghoul fell into the depths of his subconsciousness. Then he comes to senses] It's not like with others here. You definitely have some kind of a mission. Or maybe not.}
{121}{015}{Why is it not like with others? Which others?}
{122}{015}{Well, of course... Others here, from Tartarus, they too ran away from serving, aren't they?}
{123}{015}{Others from Tartarus, they searched for a better life here, right? Everyone seeks what's best for them.}


{130}{}{Strange accident, you say? Every time I hear "accident", I can't help thinking about the causes. Is there anything that doesn't have cause?.. Who are we to judge about causes... Even about the reasons to leave Tartarus. Or to go back there. Did you see other people here, your fellow Tartarus dwellers? }
{131}{015}{No. Who do you mean? Old man, are you sane?}
{132}{015}{Yes, I did.  They don't seem very happy. What happened to them?}


{140}{}{Just like everyone else, my boy. [he slowly wides his lips in a wrinkled smile] All of you... No, all of US are always looking for something better... More convenient place, warmer fire, tastier apple... But in search of that, we are forced to abandon what we already have. All these people abandoned Tartarus, just like you. And now they are all here. And you are too.}
{141}{015}{All these people? Who do you mean?}
{142}{015}{Of course! Others, from Tartarus, they ran off their serving too, right?}


{150}{}{The others... All these men and women, ask any - everyone has their reasons to search for a better life. But they didn't know what they would get in return. In Tartarus, you had food, water, warmth, the roof over your head... Hah, it's funny to say, but even protection from monsters of the outside world! And here? You trade everything you had for freedom... Freedom to lay down wherever you want and wait for death from starvation, cold, or fangs.}
{151}{016}{We... They didn't know. They had a choice and they made it. }
{152}{017}{Yes, it was stupid - to abandon such a safe and warm place. Here it looks obvious.}
{153}{017}{But they didn't know it would be so bad here.}
{154}{018}{It's their choice, why should I care?}


{160}{}{Who can blame them, really? [smiles] You made your choice too, and now you're here. Another mouth to feed, keep warm, protect... feed...}
{161}{010}{Okay, I got your point. Can I ask something?}
{162}{010}{Even if so, I can take care of myself. I'd like to ask another question.}


{170}{}{The thing is, you'll never know if it's the best choice you make, or you have to go back eventually. Except there's nowhere to go back... I mean, there is, but nothing waits for you there anymore.}
{171}{010}{But Tartarus is there! Although, it's not very wise for me to return. They think I'm a murderer... Can I ask something else?}
{172}{010}{I might go back if I wish to do so. Maybe. I have other questions.}
{173}{010}{All of this is so... Philosophical. I'd like to ask something else.}


{180}{}{They are only humans, right? Who even cares about the others... [his sight loses focus and you feel transparent] You know... I think this way of treating problems is the reason we are in this hole now. I mean, all of us.}
{181}{019}{I... I think I understand. Mutual aid, working together, and such.}
{182}{010}{Uh, yeah, maybe. Can I ask something else?}
{183}{010}{Don't care. I'd like to ask another question.}


{190}{}{You are a smart young man, aren't you? People like you define the outcome of wars. Or start one [winks].}
{191}{010}{Uh, thanks, I guess. I'd like to ask another question.}


{200}{}{You call this living? It's a tough one for sure... We got lucky with this station - it protects us not only from daily heat and cold at night but also from carnivorous creatures. A pity this station doesn't protect us from hunger, hahaha... Everyone here is contributing to the common good. Even elders and children help - pick up the soil for patches, warm each other at nights, watch for the entrance... There are so many things an old person can do, you know?}
{201}{021}{Why are there so many people here?}
{202}{024}{Where do you get your food?}


{210}{}{Where do YOU come from? That's the answer... A lot of people here are runaways from Tartarus, from your favorite Gods. Some others came from Radius. Me, for example. There are even some who tried to enter the Olympus itself... And who stayed alive, of course.}
{211}{}{People... Well, they just come. From different places of Radius - wastelands, ruins... Anywhere. Any road eventually leads them here.}
{214}{023}{Why did someone try to enter the Olympus?}
{212}{023}{Enter the Olympus? To the Gods!?}
{213}{024}{And where do you get your food?}


{220}{}{Olympus, the last hope. Or so they say, new one. The rumor is this is the place where Gods live. Even if so, they are being guarded by the real Devils! Believe me, I know what I'm saying.}
{221}{023}{Devils? You mean, some terrible creatures are guarding the Gods? You must be mistaken, old man.}
{222}{023}{Devils, you say? I should keep out of them, I suppose.}


{230}{}{There is only one way for us: Tartarus. No one knows exactly what awaits us in the Olympus, but we know for sure that there are no Gods in Tartarus - and it's safer and calmer than here. We are getting there one day, I'm sure of it...}
{231}{024}{Well, there is plenty of food, that's true... And where do you get yours?}


{240}{}{Our seekers go to the road every day, searching for food, supplies, or something that could help us to live for another week. Sometimes they are lucky to put down a molerat - then it's a feast! But usually, they bring some weak crops and roots, which are pretty good if turned into flour and then baked into flatbread. And if they are not good enough, you can just wait for another day - then they taste like heavens, hahahahkhchh...}
{241}{026}{Have you ever tried to grow something? Corn, for example?}
{242}{025}{Hunting and gathering, I see. Good thing it's not cannibalism, right? [wink]}
{243}{021}{Where do all these people come from? I don't see any children.}
{244}{010}{I see... I'd like to ask more.}


{250}{}{[Bono looks at you with no response. Literally, zero reaction.]}
{251}{010}{Uh, I'd like to ask about other things.}


{260}{}{Old fellow Priestley sure had. He tried to make some crops, but nothing grows on this barren land. I made an effort to come up with something akin to fertilizer, but with no results. Nothing grew up. Poor guy, he was so disappointed by that...}
{261}{010}{Hmm... A fertilizer? Maybe something will come out of this. I'd like to ask about something else.}
{262}{010}{Yeah, no luck means no luck. Can I ask other questions?}


{300}{}{Gods? Which Gods? Oh, you mean the Olympus Gods. Olympus... I didn't meet anyone who would know exactly what it is, myself included. Not even talking about who - or what - lives inside. What is known is that the Olympus is... Alive. It's an organism, it's breathing together with the whole Radius.}
{301}{031}{What? It's just a building! How can it breathe?}
{302}{032}{No one knows then? A pity... But maybe there's someone who could tell more?}
{303}{033}{Radius is breathing? What does it mean?}


{310}{}{I have no easy way of explaining it. Let's put it like that - when you see a tree you know it's alive, despite that it doesn't have a single leaf on it. You just know, because in another case its roots wouldn't hold it in the soil. The Olympus is the same - it can't be not alive, or it would become a part of ruins long ago.}
{311}{032}{Your metaphors are making me woozy... Do you know where I can find someone, who could tell more about the Olympus?}
{312}{032}{Alive or not alive, what? Where I can learn more about the Olympus?}


{320}{}{You know where - in Tartarus! [he hoarsely laughs] Whether you want it or not, but your path leads to the same place as ours, new one. You won't survive in Radius alone, that's for sure.}
{321}{033}{Radius? Can you tell me more?}


{330}{}{Radius is not only the place, the piece of land where we stuck. Radius is our whole world. When you go out into the wasteland, standing still into the night, looking around - it's Radius. When you open some chest in a haunted house, praying it doesn't have any trap on it - it's Radius. Even when you look deep into my white eyes, it's Radius. }
{331}{034}{So Radius is everything that surrounds me, wherever I go?}
{332}{035}{You mean, Radius is our whole life?}


{340}{}{Yes. And to stay alive in it, you should let Radius into you, let it take you over. Cursed lands require cursed deeds.}
{341}{010}{I got it, enough with your explanations. I want to ask something else...}


{350}{}{Life and death, and everything after. Radius is everything except the Olympus. If you don't understand it now, you will later, new one.}
{351}{010}{Nah, enough with your explanations. I want to ask something else...}


{400}{}{Uh, you won't get there so easily, just saying "I wanna go to Tartarus", no... We are trying to find an approach for a very long time, but the guards ask so much that we could never afford it... Seems like they have an order not to let anyone outside in.}
{401}{041}{Wait, what guards? The ones that protect you from strange creatures?}
{402}{042}{Find an approach? What exactly did you try to do?}
{403}{043}{Not to let anyone in? Why's that?}


{410}{}{From WHO? [he raises his heavy eyebrows] Oh, you mean in the Purgatory... No, I'm talking about the other side. There are well-armed guards there too... The ones never let anyone out, the other ones never let anyone out. Mark my word, it has some higher goal behind it. The guards are guarding Tartarus from... From, uh... The likes of us, I suppose... But - why? No one knows.}
{411}{044}{Okay but I still need to get there somehow.}
{412}{044}{There MUST be a way to enter it. If I could get out - I will get in.}


{420}{}{We tried many things, actually - offered them hides of Ursa, a bottle of whiskey with a pack of sugar, even - but don't tell anyone! - tried to offer them our women... It's still not enough! And... Uh... Umm... Yeah... Where was I?..}
{421}{044}{I see. You don't know what the guards want. But I still need the way to get inside.}
{422}{044}{There must be another way, without offerings or batteries...}


{430}{}{Hard to say. They are guards, after all, so they are guarding it. From... From us, I guess... Or from something we could carry with us, some disease maybe... Maybe they are afraid that it will turn all of them into worthless ghouls. Like me! Hahahahaahahh-chkhh... Oh... Or maybe they don't know themselves, what they are guarding. Do you say the Gods are the ones in charge? Then it's them, who should be asked.}
{431}{044}{I have no time for Gods now, I need a way to get back into Tartarus.}
{432}{044}{Gods can wait. First, I need a way to get into Tartarus.}


{440}{}{Get into Tartarus... Yeah, sure... Wait a second [his faces becomes stretched out] You told me that they tried to shoot you, right? So they must be looking for you, and you won't get there anyway, right? But I think there IS a way to help you get back into Tartarus. Alive. But you'll have to return the favor. What do you say, new one?}
{441}{045}{You are just an old, decrepit extortionist, that's what I say. But I'm in. What do you need me to do?}
{442}{045}{Favor in exchange for a favor... Sounds fair. How do I help?}
{443}{999}{Will I have to do something? I suppose it's something dangerous? I need to think it over.}


{450}{}{We always have our hands full here, getting by as hard we can, but it's a tough time... Our seekers are already tired because they have to go further and further in search of supplies and they are exhausted afterwards... Talk to Robin, he usually stands near the entrance. Also, Gromus, our doctor, complained about the lack of materials for medical mixtures. You could stop by his bar and talk with him. He will tell better, what he needs. If you will be of any help to us, then you'll get my help in returning to Tartarus.}
{451}{010}{What a puzzle... Okay, let's see what I can do.}
{452}{999}{I see... Okay then, off to help. You keep your word.}
{453}{999}{Uh... No, I'll find a way to Tartarus myself.}


{500}{}{What? Help?... Oh yeah, yeah, I remember. How are you getting along?}
{501}{051}{Still working on it.}
{502}{052}{I helped Robin, just as I promised. Your turn to help, Bono.}
{503}{053}{Gromus is now in possession of some very... Useful tails of scorpions. Your turn to help, Bono.}
{504}{054}{I helped both. They are very happy now, said hi. Now tell me, how do I get into Tartarus?}
{505}{055}{Yes, I helped both Robin and Gromus. It wasn't easy, but I managed. Now it's your turn to help, Bono. }


{510}{}{Alright, alright... Any help is appreciated.}
{511}{010}{Yeah, of course. I had something else in mind...}
{512}{999}{I, uh, gotta go.}

{520}{}{Good. At last, the seekers can have a little rest. Thanks. You know, you are not like others, from Tartarus, who hang around here... }
{521}{057}{Ahem... So, how do I get into Tartarus?}
{522}{057}{Hey, old man, what about Tartarus? }

{530}{}{Agh-hh... Ghuuugh... Thanks a lot, new one. Our only healer couldn't handle dealing with this... RADIVATION. Now he has the means to create his anti-radiation bitter drinks... And other bitter drinks...}
{531}{057}{Ahem... So, how do I get into Tartarus?}
{532}{057}{Hey, old man, what about Tartarus?}

{540}{}{[he slyly squints his left eye] Helped, huh?.. I see you are the man of your word, so I won't go around asking how EXACTLY you helped. Instead, I'll tell you how to get into Tartarus right away, write it down: go to the platform, then follow the tracks until the end. After that you'll see the passage to the side, so - you go there. Walk until you bump into the guards. Come straight to them and say "get the hell out of my way, or else!" - and they'll let you in right away. And they'll give you food. And some medicine, I don't quite remember its name... Something like "fuk-yu-up" or "kill-yu-ded"... My memory is not serving me well lately.}
{541}{999}{No need for being sarcastic. I'll come by later.}
{542}{010}{Come on, I was just joking! I'll ask another question.}

{550}{}{[he glares at you] Helped, huh? You are fast... Still, their tasks are always simple... Okay then, listen: you are, like, fugitive, right? So you can't show your face. But the guards in Tartarus have uniforms that keep their faces covered. So you just need to obtain such uniform, and you can freely walk into Tartarus, either through the station or through the Purgatory - assuming you are not afraid of Ferals...}
{551}{056}{Obtain such uniform, you say? Okay, where do I get it?}

{560}{}{I know for sure that the Sunset Jackals are in possession of many different uniform suits. Let me point it on your map [he takes your organizer and puts coordinates into it] Hah, I remember some of our seekers had a couple of such things with them... So, the Jackals. They are scary people. Murderers, rapists - practically animals, not everyone can handle talking to them. But if you have a spine, you'll be fine. Look for Carl, the mechanic. He is alright. Should help you with the suit.}
{561}{999}{Sunset Jackals then... Frankly, I thought of more... Useful help. But thanks anyway.}
{562}{999}{Oh, so I need to visit some bandits and steal away a suit of armor? Thanks a lot, old man, for your "help"... I'll manage somehow.}

{570}{}{Tartarus? What Tar- Oh yeah, sure. I remember, new one. Okay then, listen: you are, like, fugitive, right? So you can't show your face. But the guards in Tartarus have uniforms that keep their faces covered. So you just need to obtain such uniform, and you can freely walk into Tartarus, either through the station or through the Purgatory - assuming you are not afraid of Ferals...}
{571}{056}{Obtain such uniform, you say? Okay, where do I get it?}

{600}{}{Huh?.. No, no-no, not at all... It's just... We have so many problems and things to do here... Mostly problems... I think our dwellers need something to lift their spirits, except my legs are not good enough to run around... People need hope to survive. Maybe you could walk around the station and tell people that I'm going to give a speech? They should come and listen... Tell it at least 10 people and come back. I'll get the speech ready, okay?}
{601}{QA}{Why not? 10 people, be right back.}
{602}{999}{Uh, no, find yourself another errand boy.}
{603}{999}{I have some business to do, I'll think about it.}


{650}{}{So, did you talk to people? Are they coming?}
{651}{999}{Actually, I'm working on it...}
{652}{066}{Yes, around a dozen of people should come.}
{653}{}{It took too long, }
{654}{}{, now I can't... Spare any time.}
{655}{999}{I see, so all this running's been for nothing.}
{656}{999}{I didn't know you needed it FAST. Oh well.}


{660}{}{Wonderful, I've just scribbled a couple of notes... Okay, let's go.}
{661}{StartBonoSpeach}{[follow Bono]}

{670}{}{Yeah... I think it went pretty well. Now everyone will remember that we are one big family and we'll survive only by taking care of each other. I hope it will boost the morale. Thank you for bringing everyone.}
{671}{068}{Uh... Well, you're welcome. I expected some reward though.}
{672}{999}{No problem, it was nothing.}
{673}{999}{Of course, don't sweat it, old man!}

{680}{}{A reward? You want something from ME? From US? All I can give you is advice... Advice to watch carefully where are you now, }
{681}{}{. I have nothing more.}
{682}{999}{I understand. See you later.}
{683}{999}{I got it. Goodbye, Bono.}	


{690}{}{He is looking for her again? I don't even know how to help the poor guy... He buried Nadine around 5 years ago. She was always sick, we tried to help as we could - but the death took her. Joe was very worried so much. I remembered how he locked himself inside of that old wagon for days, carving the memorial plaque for her grave. That plaque was so beautiful... I don't quite remember how it looked. Maybe you should go outside, find her grave near the fountain and look at it. Maybe if you remind Joe about the plaque, he'll get his memory back.}
{691}{999}{Oh man. Okay, I'll try.}

#
#Сообщения жителей при убеждении пойти послушать Боно																																																														
#
{700}{}{[looks at you in anticipation]}
{701}{}{Yes? Something else?}
{702}{}{Did you want to say something?}
{703}{}{What do you need?}
{704}{}{Bono is going to give some speech. Something important.}
{705}{}{You should come to listen to Bono speaking.}
{706}{}{Bono is going to give a speech soon, he asks to come by and listen.}
{707}{}{Go to Bono's place, he wants to share a couple of words.}
{708}{}{Okay, I'll come around.}
{709}{}{I don't know, so many things to do... But I'll tell my friends.}
{710}{}{Bono? Okay, I'll come to listen.}
{711}{}{Yeah, this ghoul is worth listening to. Of course, I'll come.}
{712}{}{No, nothing. Bye.}
{713}{}{I'm just wandering around. Everything's alright.}
{714}{}{Good, we'll be waiting.}
{715}{}{Very good! See you around!}
{716}{}{Okay, deal.}
{720}{}{You convinced enough dwellers to come, it's time to tell Bono that everything's ready.}	
###
### Удобрения
###
{750}{}{Yes, I've heard... It's unbelievable how ANYTHING could grow there! I think we could make an arrangement... We could buy the fertilizer from you. Say, 20 batteries for a sack. What do you think? I can't offer more, but we need at least 10 sacks!}
{751}{}{It's a deal! Wait, I'll bring the first batch.}
{752}{}{I don't know. I need to think...}
{760}{}{Very good. Put it here. Yes, like that. Peter will come by to take it. Thank you, here's your payment. [he gives you }
{761}{}{ batteries] I'm waiting for another delivery, heh-heh.}
{762}{}{ batteries] Let's call it a day. This must be enough to grow food for everyone. Thanks a lot, you saved us all.}
{763}{}{[take your reward] Sure, it won't be too long. See you soon.}
{764}{}{[take your reward] Glad to be of help. Bye.}	
###
#
#РЕЧЬ БОНО																																																														
#
{800}{}{ }
{801}{}{Greetings, my friends!}
{802}{}{You all know that now we are facing a hard times,}
{803}{}{But together we are capable of overcoming any difficulties!}
{804}{}{You know for sure that I am the man of my word!}
{805}{}{And I promise you, sooner or later we will get our right to live in Tartarus!}
{806}{}{The guards almost agreed to let us in!}
{807}{}{So it won't be long until all of us will be safe!}
{808}{}{I assure you that in the nearest future everything will be alright again.}
{809}{}{Be patient to yourself and to the ones around you, together we'll work through this hardships!}
{810}{}{Thank you for your attention, my friends.}
{811}{}{ }
{812}{}{ }																																																											
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Положительная реакция)																																																														
#																																																															
{1000}{}{}																																																															
{1001}{}{}																																																															
{1002}{}{}																																																															
{1003}{}{}																																																															
{1004}{}{}																																																															
{1005}{}{}																																																															
{1006}{}{}																																																															
{1007}{}{}																																																															
{1008}{}{}																																																															
{1009}{}{}																																																															
#																																																															
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Нейтральная реакция)																																																															
#																																																															
{1010}{}{}																																																															
{1011}{}{}																																																															
{1012}{}{}																																																															
{1013}{}{}																																																															
{1014}{}{}																																																															
{1015}{}{}																																																															
{1016}{}{}																																																															
{1017}{}{}																																																															
{1018}{}{}																																																															
{1019}{}{}																																																															
#																																																															
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Отрицательная реакция)																																																														
#																																																															
{1020}{}{}																																																															
{1021}{}{}																																																															
{1022}{}{}																																																															
{1023}{}{}																																																															
{1024}{}{}																																																															
{1025}{}{}																																																															
{1026}{}{}																																																															
{1027}{}{}																																																															
{1028}{}{}																																																															
{1029}{}{}																																																															
#																																																															
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Дополнительно)																																																															
#																																																															
{1030}{}{Peter has told me everything about Hugo, we need to leave...}																																																															
{1031}{}{We need to leave this place fast.}																																																															
{1032}{}{Vultures from Olympus can be here at any moment.}																																																															
{1033}{}{We are doomed here, Defenders will kill us all.}																																																															
{1034}{}{We need to decide where to go from here.}																																																															
{1035}{}{}																																																															
{1036}{}{}																																																															
{1037}{}{}																																																															
{1038}{}{}																																																															
{1039}{}{}