##############################
#Локация: Пещеры Нежити
#Имя: Боно
#Краткое описание: Мертвяк - меланхолик, лидер местных нищебродов
#Дата создания: 07.05.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see: an old ghoul.}
{2}{}{This falling-apart ghoul looks ancient. He watches at you with unseeing gaze through his scant eyebrows.}
#
# после знакомства
{3}{}{You see: Bono.}
{4}{}{Unspoken godfather to the family of unfortunate local exiles.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[his eyebrows slowly move upward, revealing whitish eyes] A new one, aren't you? [sighs] Why won't you all stay put in Tartarus? How do I feed another mouth?}
{11}{002}{What? A new one? What is this place?}
{12}{999}{What? No, I don't have time for this.}


{20}{}{New one - that's you, new one. Like the half of unfortunate seekers of better life here, you just couldn't sit tight in one place...}
{21}{003}{Okay, let's sort this out. Is it a part of Tartarus? I mean, is this even a Tartarus?}
{22}{004}{I don't understand, old man. What are you talking about? You *are* an old man, right? You don't look too good...}
{23}{999}{That's it, I'm out of here.}


{30}{}{Listen, son... That's no Tartarus. I mean... There's THE REST of the world, except, Tartarus, you see? So now you are there, in THE REST of the world. We call this place "the caves of undead". I myself came up with the name. And I'm Bono, if you are wondering.}
{31}{005}{Undead? So you all are undead? And you live here? All this people, wearing Tartarus' clothes?.. Oh man...}


{40}{}{Well, let's say I'm the next step of being an old man. You could even say I'm the next step of being a *dead* man. And not the last step, unfortunately... The name's Bono. This place is called "the caves of undead". Here live the likes of you. And me.}
{41}{005}{Undead... This is no Tartarus, although you have no sky here as well. Who are all these people?.. Oh man...}


{50}{}{Don't be hasty, new one. The understanding cannot be rushed, or it will become distorted, hazy and tangled... Let's start with the basics: what's your name?}
{51}{006}{My name is }
{52}{006}{, I came from Tartarus... And I need answers.}
{53}{999}{No, I need to think everything over first.}


{60}{}{Of course. Like literally everyone else before you [he smiles with toothless grin]. If you already pulled yourself together, we can look into the answers you need.}
{61}{010}{Yes, I'd like to.}
{62}{999}{Not now, I need some time to think everything over first.}


{100}{}{Hmm?... Hmm-hmm? Oh, it's you, }
{101}{}{. What do you need?}
{102}{}{Yeah? Something else?}
{103}{011}{Tell me about Tartarus!}
{104}{020}{How do you all live here?}
{105}{030}{Do you know anything about Gods?}
{106}{040}{My father is very sick, I need to get back to Tartarus.}
{107}{050}{You promised to help me, remember? Return the favor and all that.}
{108}{060}{You look somehow distracted. Lost something?}
{199}{065}{About that speech you need to give...}
{198}{069}{There's this guy Joe, he looks for his wife, Nadine.}
{197}{075}{I brought Priestley some fertilizer. So I've been thinking - maybe you need more of that?}
{196}{076}{I brought more of fertilizer.}
{109}{999}{Nothing, we'll talk later.}


{110}{}{Tartarus... Yeah... Tartarus is a great place to, uh, live. It's interesting, really - you, who came from Tartarus, are asking me, who never been there, to tell you about it. Better answer, why did you run away from there?}
{111}{012}{Run away? This was an accident! I never even thought about running away from serving...}
{112}{013}{Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident.}
{113}{013}{Run away... Serving, serving, nothing except serving the Sons of Gods - and the Gods themselves. But I didn't run away, this was... A strange accident. Usually, the Sons of Gods don't make such fast accusations.}
{114}{014}{Uh, yeah, sure I ran away! I always knew that life is not only abouut serving Gods, there must be something more to it, some... Higher purpose, I suppose.}


{120}{}{So that's how it is, huh? Interesting, yeah... So interesting... And very unusual... [his eyes are wide open, but you see that ghoul fell into the depths of his subconsciousness. Then he comes to senses] It's not like with others here. You definitely have some kind of a mission. Or maybe not.}
{121}{015}{Why is it not like with others? Which others?}
{122}{015}{Well, of course... Others here, from Tartarus, they too ran away from serving, aren't they?}
{123}{015}{Others from Tartarus, they searched for a better life here, right? Everyone seeks what's best for them.}


{130}{}{Strange accident, you say? Every time I hear "accident", I can't help thinking about the causes. Is there anything that doesn't have cause?.. Who are we to judge about causes... Even about the reasons to leave Tartarus. Or to go back there. Did you see other people here, your fellow Tartarus dwellers? }
{131}{015}{No. Who do you mean? Old man, are you sane?}
{132}{015}{Yes, I did.  They don't seem very happy. What happened to them?}


{140}{}{Just like everyone else, my boy. [he slowly wides his lips in a wrinkled smile] All of you... No, all of US are always looking something better... More convenient place, more warmer fireplace, more tasty apple... But in search for that, we are forced to abandon what we already have. All this people abandoned Tartarus, just like you. And now they are all here. And you are too.}
{141}{015}{All these people? Who do you mean?}
{142}{015}{Of course! Others, from Tartarus, they ran off their serving too, right?}


{150}{}{The others... All these men and women, ask any - everyone has their reasons to search for better life. But they didn't know what they would get in return. In Tartarus you had food, water, warmth, roof over your head... Hah, it's funny to say, but even protection from monsters of outside world! And here? You trade everything you had for a freedom... A freedom to lay down wherever you want and wait for death from starvation, cold or fangs.}
{151}{016}{We... They didn't know. They had a choice and they made it. }
{152}{017}{Yes, it was stupid - to abandon such safe and warm place. Here it looks obvious.}
{153}{017}{But they didn't know it would be so bad here.}
{154}{018}{It's their choice, why should I care?}


{160}{}{Who can blame them, really? [smiles] You made your choice too, and now you're here. Another mouth to feed, keep warm, protect... feed...}
{161}{010}{Okay, I got your point. Can I ask something?}
{162}{010}{Even if so, I can take care of myself. I'd like to ask other question.}


{170}{}{The thing is, you'll never know if it's the best choice you make, or you have to go back eventually. Except there's nowhere to go back... I mean, there is, but nothing waits for you there anymore.}
{171}{010}{But Tartarus is there! Although, it's not very wise for me to return. They think I'm a murderer... Can I ask something else?}
{172}{010}{I might go back, if I wish to do so. Maybe. I have other questions.}
{173}{010}{All of this is so... Philosophical. I'd like to ask something else.}


{180}{}{They are only humans, right? Who even cares about the others... [his sight loses focus and you feel transparent] You know... I think this way of treating problems is the reason we are in this hole now. I mean, all of us.}
{181}{019}{I... I think I understand. Mutual aid, working together and such.}
{182}{010}{Uh, yeah, maybe. Can I ask something else?}
{183}{010}{Don't care. I'd like to ask other question.}


{190}{}{You are smart young man, aren't you? People like you define the outcome of wars. Or start one [winks].}
{191}{010}{Uh, thanks, I guess. I'd like to ask other question.}


{200}{}{You call this living? It's a tough one for sure... We got lucky with this station - it protects us not only from daily heat and cold at night, but also from carnivorous creatures. A pity this station doesn't protect us from hunger, hahahah... Everyone here is contributing to the common good. Even elders and children help - pick up the soil for patches, warm each other at nights, watch for the entrance... There are so many things an old person can do, you know?}
{201}{021}{Why are there so many people here?}
{202}{024}{Where do you get your food?}


{210}{}{Where do *you* came from? That's the answer... A lot of people here are runaways from Tartarus, from your favourite Gods. Some others came from Radius. Me, for example. There are even some who tried to enter the Olympus itself... And who stayed alive, of course.}
{211}{}{People... Well, they just come. From different places of Radius - wastelands, ruins... Anywhere. Any road eventually leads them here.}
{214}{023}{Why did someone try to enter the Olympus?}
{212}{023}{Enter the Olympus? To the Gods!?}
{213}{024}{And where do you get your food?}


{220}{}{Olympus, the last hope. Or so they say, new one. The rumor is this is the place where Gods live. Even if so, they are being guarded by the real Devils! Believe me, I know what I'm saying.}
{221}{023}{Devils? You mean, some terrible creatures are guarding the Gods? You must be mistaken, old man.}
{222}{023}{Devils, you say? I should keep out of them, I suppose.}


{230}{}{There is only one way for us: Tartarus. No one knows exactly what awaits us in the Olympus, but we know for sure that there's no Gods in Tartarus - and it's more safe and calm than here. We are getting there one day, I'm sure of it...}
{231}{024}{Well, there is plenty of food, that's true... And where do you get yours?}


{240}{}{Our seekers go to the road every day, searching for food, supplies or something that could help us to live for another week. Sometimes they are lucky to put down a molerat - then it's a feast! But usually they bring some weak crops and roots, which are pretty good if turned into a flour and then baked into flat bread. And if they are not good enough, you can just wait for another day - then they taste like heavens, hahahahkhchh...}
{241}{026}{Have you ever tried to grow something? Corn, for example?}
{242}{025}{Hunting and gathering, I see. Good thing it's not cannibalism, right? [wink]}
{243}{021}{Where all these people come from? I don't see any children.}
{244}{010}{I see... I'd like to ask more.}


{250}{}{[Bono looks at you with no response. Literally, zero reaction.]}
{251}{010}{Uh, I'd like to ask about other things.}


{260}{}{Old fellow Priestley tried to make some crops here once, but nothing wants to grow on this barren land. I nade an effort to come up with something akin to a fertilizer, but with no results. Nothing grew up. Poor guy, he was so disappointed by that...}
{261}{010}{Hmm... A fertilizer? Maybe something will come up. I'd like to ask about something else.}
{262}{010}{Yeah, no luck means no luck. Can I ask other questions?}


{300}{}{Gods? Which Gods? Oh, you mean the Olympus Gods. Olympus... I didn't meet anyone who would know exactly what it is, myself included. Not even talking about who - or what - lives inside. What is known is that the Olympus is... Alive. It's an organism, it's breathing together with the whole Radius.}
{301}{031}{What? It's just a building! How can it breathe?}
{302}{032}{No one knows then? A pity... But maybe there's someone who could tell more?}
{303}{033}{Radius is breathing? What does it mean?}


{310}{}{I have no easy way of explaining it. Let's put it like that - when you see a tree you know it's alive, despite that it doesn't have a single leaf on it. You just know, because in another case its roots would't hold it in the soil. The Olympus is the same - it cannot be not alive, or it would become a part of ruins long ago.}
{311}{032}{Your metaphors are making me woozy... Do you know where I can find someone, who could tell more about the Olympus?}
{312}{032}{Alive or not alive, what? Where I can learn more about the Olympus?}


{320}{}{You know where - in Tartarus! [he hoarsely laughs] Whether you want it or not, but your path leads to the same place as ours, new one. You won't survive in Radius alone, that's for sure.}
{321}{033}{Radius? Can you tell me more?}


{330}{}{Радиус - это не место, не клочок земли, где мы все застряли. Радиус - это весь наш мир. Когда ты выходишь в Пустоши, встаешь на цыпочки, и смотришь вокруг себя, все это - Радиус. Когда ты открываешь сундук в заброшенном доме и молишься, чтобы на нем не оказалось капкана - это тоже Радиус. И даже когда ты смотришь в мои блеклые глаза - это тоже Радиус.}
{331}{034}{Значит Радиус - это все, что вокруг меня? Где бы я ни был?}
{332}{035}{То есть Радиус - это наша жизнь?}


{340}{}{Да, и чтобы выжить тут, ты должен впустить Радиус в себя, позволить ему завладеть тобой. Проклятая земля - проклятые нравы.}
{341}{010}{Я все понял, хватит с меня твоих объяснений. Мне нужно еще кое что...}


{350}{}{Жизнь, и смерть, и то, что случается потом. Радиус - это все, за вычетом Олимпа. Если ты не понимаешь сейчас - поймешь потом, новенький.}
{351}{010}{Нет-нет, спасибо, хватит с меня твоих объяснений. Мне бы еще кое что узнать...}


{400}{}{Э-э-э, туда не попасть просто вот так, сказав мол, я хочу в Тартар, не-е-е-ет... Мы давно ищем к ним подход, но охранники просят столько, что ни в жизнь не достать... Сдается мне, у них приказ, не впускать никого извне.}
{401}{041}{Подожди-ка, какие охранники? Те, что защищают нас от ужасных тварей?}
{402}{042}{Ищите подход? А что вы конкретно пытались сделать?}
{403}{043}{Никого не впускать? Почему это?}


{410}{}{От КОГО? [приподнимает кустистые брови] А-ах, ты наверное, про Чистилище... Нет-нет, с другой стороны тоже есть охрана, хорошо вооруженная охрана... Одни никого не выпускают из Тартара, другие никого не впускают. Помяни мое слово - у всего этого есть какая-то большая цель... Охранники охраняют Тартар, от... от таких, как мы, наверное.... Но вот - зачем? - никто не знает.}
{411}{044}{Хорошо, но мне все равно как-то нужно туда пробраться..}
{412}{044}{Туда ДОЛЖЕН быть вход. Раз я смог выйти оттуда - смогу и войти!}


{420}{}{Да что мы только не пытались - и шкуру урса охранникам приносили, и бутылку виски с коробкой сахара, и даже... только -тсссс! - предлагали им наших женщин... Нет, им все мало! И... и... эээ... мда-а... Так, о чем это я?..}
{421}{044}{Понятно, вы не знаете, что нужно охранникам... Но я должен найти способ туда попасть...}
{422}{044}{Должен быть другой способ, без всяких там восхищений и батареек...}


{430}{}{Сложно сказать... Они же охранники - значит, охраняют Тартар от... От нас наверно... Или от того, что мы можем с собой принести, может заразу какую, или они думают, что все там сразу станут бесполезными мертвяками, как я! Ха-ха-кха-к-кха-аааа... Оо-ох... А может, они и сами не знают, что и от кого охраняют. Ты же говоришь, Боги всем заправляют, вот, значит, у богов и нужно спрашивать.}
{431}{044}{Мне сейчас не до Богов, нужно придумать, как вернуться в Тартар...}
{432}{044}{Боги подождут, сначала нужно придумать способ пробраться в Тартар.}


{440}{}{Пробраться в Тартар... Как же... Подожди-ка [его лицо вытягивается] ты, помнится, говорил, что они в тебя стреляли, так? Значит, тебя ищут, и не пустят туда в любом случае, так? Но-о, похоже, я смогу тебе помочь вернуться туда, в Тартар. Живым. Но, услуга за услугу, помощь на помощь, а? Что скажешь, новенький?}
{441}{045}{Ты просто старый, дряхлый вымогатель, вот что скажу. Но я согласен. Что нужно делать?}
{442}{045}{Помощь на помощь - по мне звучит честно. Чем нужно помочь?}
{443}{999}{Нужно что-то делать? И, наверняка, что-то опасное, да? Мне нужно поразмыслить над этим.}


{450}{}{Тут всегда дел невпроворот, мы выживаем, как можем, но сейчас довольно тяжелые времена... Искатели уже совсем вымотались, им приходится ходить все дальше и дальше за провизией, и сил у них совсем не остается... Поговори с Робином, он обычно стоит у выхода на поверхность. И, помнится, Громус, наш врач, жаловался на недостаток сырья для лекарственных смесей. Ты бы зашел в бар да поговорил с ним сам, он лучше расскажет, что там ему опять не хватает. Поможешь хоть чем-нибудь - и я помогу тебе вернуться в Тартар.}
{451}{010}{Вот так задачка... Ну хорошо, посмотрим, что там нужно будет делать.}
{452}{999}{Ясно... Мда-а, ну что, пойду помогать. Ты только слово свое сдержи.}
{453}{999}{Эмм... Нет, я уж как-нибудь сам в Тартар пройду.}


{500}{}{Что-что? Помощь?... Ах да-да, конечно же помню. Как твои успехи?}
{501}{051}{Я пока еще работаю над этим.}
{502}{052}{Я помог Робину, как и обещал. Твой черед помогать, Боно.}
{503}{053}{Громус обзавелся несколькими очень... полезными хвостами скорпионов. Твой черед помогать.}
{504}{054}{Я помог и тому, и другому. Все очень рады и передавали тебе привет! Теперь расскажи, как пройти в Тартар?}
{505}{055}{Да, я помог и Робину, и Громусу. Было нелегко, но я справился. Теперь твоя очередь помогать мне, Боно.}


{510}{}{Хорошо, хорошо... Нам любая помощь не будет лишней...}
{511}{010}{Да-да, конечно. Я тут еще узнать хотел...}
{512}{999}{Эмм, ну я пойду.}


{520}{}{Отлично, искатели смогут немного передохнуть, сил набраться... Спасибо. А ты не похож на твоих... тех, из Тартара, что шатаются тут, как неприкаянные... }
{521}{057}{Кхм... Так как же мне попасть в Тартар?}
{522}{057}{Эй-эй, старик, как мне в Тартар попасть?}


{530}{}{Кх-хх... Ххо-о-ох... Вот спасибо, новенький. Всего один врачеватель, не справляется с лечением... этой... РАДИВАЦИИ. Теперь он спокойно сможет делать свои целебные противорадивационные настойки... И разные другие настойки...}
{531}{057}{Кхм... Так как же мне попасть в Тартар?}
{532}{057}{Эй-эй, старик, как мне в Тартар попасть?}


{540}{}{[хитро прищуривает левый глаз] Помог значит, мда?.. Ну-у, я вижу, ты человек честный, не пойду спрашивать у них, КАК ИМЕННО ты им помог, а сразу же расскажу, как попасть в Тартар. Значит, записывай... Отсюда спускаешься на платформу, потом по рельсам идешь до... до конца. Дальше - увидишь проход в сторону - так вот, идешь по нему, пока не упрешься в охранников... Подходишь к ним, и говоришь - Уйди с дороги, не то поломаю! - и они сразу же пускают тебя в Тартар. Мда-а, еще и еды с собой дадут. И очень полезные таблетки дадут... как же они называются... то ли ПРО-ПИЗ-ДЮЛЬ, то ли НЕ-ПИЗ-ДИН... Память что-то подводит меня в последнее время...}
{541}{999}{Хорошо-хорошо, не надо сарказма. Я попозже подойду.}
{542}{010}{Да брось, это же я пошутил! Хотел еще кое-что узнать.}


{550}{}{[пристально смотрит на Вас] Помог, да? Быстро же ты справился... Ну да им всегда какие-то пустяки нужны... Ну хорошо, смотри: ты же вроде как в розыске, так? Значит, лицо тебе показывать нельзя, а у охранников-то в Тартаре форма специальная, лицо закрывающая. Так тебе нужно просто форму охранника надеть - и смело в Тартар, хоть через метро, хоть через Чистилище, если конечно, Безумных не боишься...}
{551}{056}{Форму, говоришь, достать? Ну хорошо, а где мне ее взять?}


{560}{}{Точно знаю, что разных защитных костюмов много у Псов Заката, давай-ка я тебе на карте отмечу [берет Ваш органайзер и ловко вводит новые координаты в карту] Ээ-эх, помнится и у Выживальцев была парочка таких приборов... Так вот, Псы... Страшные это люди, грабители, убийцы - просто звери, и не каждый с ними сладит. Даже, почти никто не сладит. Но если у тебя есть хребет - ты с ними договоришься. Попробуй найти там Карла, механика, он добрый малый, должен помочь тебе с костюмчиком.}
{561}{999}{Значит, ПСЫ ЗАКАТА... Честно говоря, я думал о более... полезной помощи, но все равно спасибо.}
{562}{999}{Угу, отправиться к бандитам и выкрасть у них бронекостюм, да? Ну спасибо, старик, помог... Лаа-адно, как-нибудь прорвемся.}


{570}{}{Тартар?.. Каккой Тар... Ах да-да, конечно. Я помню-помню, новенький... Ну хорошо, смотри: ты же вроде как в розыске, так? Значит, лицо тебе показывать нельзя, а у охранников-то в Тартаре форма специальная, лицо закрывающая. Так тебе нужно просто форму охранника надеть - и смело в Тартар, хоть через метро, хоть через Чистилище, если конечно, Безумных не боишься...}
{571}{056}{Форму, говоришь, достать? Ну хорошо, а где мне ее взять?}


{600}{}{А?.. Нет-нет, совсем нет... тут просто... столько проблем, проблем и задач... но проблем, конечно же, больше... Нужно бы как-то подбодрить жильцов, да только ноги мне не дают вверх-вниз по лестницам бегать, да каждого утешать... Людям нужна надежда, иначе тут не выжить... А может, ты бы пробежался по станции, да рассказал людям, что я выступить хочу. Они должны меня послушать... Хотя б человек 10 предупреди -  и возвращайся сюда, а я пока речь подготовлю, а?}
{601}{QA}{Ну а почему бы и нет? 10 человек, говоришь? Я быстро.}
{602}{999}{Эмм, нет, найди себе другого мальчика на побегушках.}
{603}{999}{Ну-у, у меня тут еще дела, а потом... я подумаю.}


{650}{}{Да-да, ты оповестил достаточно человек? Они придут?}
{651}{999}{На самом деле, я еще работаю над этим...}
{652}{066}{Да, около дюжины обещали точно прийти.}
{653}{}{Ты слишком долго всех обходил, }
{654}{}{, мне некогда теперь... тратить время.}
{655}{999}{Ясно, зря бегал, значит.}
{656}{999}{Я же не знал, что нужно вот прямо быстро-быстро... ну ладно.}


{660}{}{Замечательно, я как раз успел записать пару умных мыслей... Ну что ж... пошли.}
{661}{StartBonoSpeach}{[проследовать за Боно]}


{670}{}{Да-а... Ну, думается мне, все прошло вполне неплохо. Теперь все вспомнят, что мы - одна семья, и выжить сможем только как семья, помогая друг другу. Надеюсь, это хоть чуть-чуть поможет. Спасибо, что всех собрал.}
{671}{068}{А-а... Ну, не за что. Правда, я рассчитывал на какую-нибудь награду.}
{672}{999}{Да без проблем, это мне ничего не стоило.}
{673}{999}{Конечно, не парься, старик.}


{680}{}{Награда? Ты хочешь ЧТО-ТО просить у МЕНЯ? У НАС? Самое ценно, что я могу тебе дать, так это совет... совет, трезво смотреть на то, где ты сейчас находишься, }
{681}{}{. Мне нечего дать тебе.}
{682}{999}{Ну хорошо, до скорого.}
{683}{999}{Я понял. До свиданья, Боно.}	


{690}{}{Опять ищет? Даже не знаю, как помочь бедняге... Похоронил он Надин лет 5 назад. Она болела постоянна, мы все помогали ей, чем могли, но смерть к ней пришла. Джо тогда очень сильно переживал. Помню, он заперся в старом вагоне и несколько дней вырезал табличку ей для могилки. очень красивая была табличка, вот только я запамятовал, что на ней было... Ты поднимись наружу, найди могилку ее около фонтана, да посмотри, что там за табличка. Может, если ты Джо про табличку напомнишь, к нему и память вернется.}
{691}{999}{Ох-хо. Хорошо, попробую.}

#
#Сообщения жителей при убеждении пойти послушать Боно																																																														
#
{700}{}{[смотрит на Вас в ожидании]}
{701}{}{Да? Что еще?}
{702}{}{Ты что-то хотел сказать?}
{703}{}{Ну что еще нужно?}
{704}{}{Боно собирается сказать пару слов всем, что-то очень важное.}
{705}{}{Боно собирается выступить, приходи послушать.}
{706}{}{Скоро Боно выступит с речью, просил всех прийти послушать его.}
{707}{}{Подходи в комнату Боно, он хочет сказать всем пару слов.}
{708}{}{Хорошо, я подойду.}
{709}{}{Не знаю, смогу ли. Столько дел.. Но я скажу своим друзьям.}
{710}{}{Боно? Хорошо, я приду его послушать.}
{711}{}{Да-а, к этому мертвяку стоит прислушаться. Конечно же, я приду.}
{712}{}{Нет, ничего. Пока.}
{713}{}{Да я просто мимо шел, все в порядке.}
{714}{}{Отлично, будем ждать.}
{715}{}{Замечательно, тогда - до встречи!}
{716}{}{Ок, договорились.}
{720}{}{Вы оповестили достаточно жителей, можно вернуться к Боно и рассказать, что все готово.}	
###
### Удобрения
###
{750}{}{Мда-а, я действительно уже слышал об этом... Прямо удивительно, как ТАМ у него хоть что-то выросло! Да, мы могли бы договориться покупать у тебя такое удобрение... Скажем, 20 батареек за мешок, а? Большую цену предложить не могу, но нам нужно мешков 10, не меньше!}
{751}{}{Отлично, по рукам! Скоро принесу первую партию.}
{752}{}{Даже не знаю, нужно подумать...}
{760}{}{Очень хорошо, положи все вот сюда. Да-да, вот так. Питер их заберет. Спасибо, вот твоя плата [передает вам }
{761}{}{ батареек]. Жду следующую поставку, хе-хе.}
{762}{}{ батареек]. На этом наверно и закончим. Этого должно хватить, чтобы вырастить урожая на всех. Спасибо тебе большое, ты нас просто спас.}
{763}{}{[забрать свою награду] Да конечно, ждать не долго. Я скоро.}
{764}{}{[забрать свою награду] Что ж, рад был помочь. Еще увидимся.}	
###
#
#РЕЧЬ БОНО																																																														
#
{800}{}{ }
{801}{}{Приветствую вас, друзья мои!}
{802}{}{Всем вам известно, что впереди нас ожидают трудные времена,}
{803}{}{Но вместе мы справимся со всеми трудностями!}
{804}{}{Вы прекрасно знаете, что я - человек слова!}
{805}{}{И я вам обещаю, рано или поздно, но мы добьемся права жить в Тартаре!}
{806}{}{Охранники почти уже согласились впустить нас под свой кров!}
{807}{}{И ждать нам осталось совсем немного, скоро мы все будем в безопасности!}
{808}{}{И я вас уверяю, что в самом скором будущем все наладится.}
{809}{}{Будьте терпеливы к себе и к ближним, вместе мы переживем эти трудные времена!}
{810}{}{Спасибо, друзья, за ваше внимание.}
{811}{}{ }
{812}{}{ }																																																											
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Положительная реакция)																																																														
#																																																															
{1000}{}{}																																																															
{1001}{}{}																																																															
{1002}{}{}																																																															
{1003}{}{}																																																															
{1004}{}{}																																																															
{1005}{}{}																																																															
{1006}{}{}																																																															
{1007}{}{}																																																															
{1008}{}{}																																																															
{1009}{}{}																																																															
#																																																															
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Нейтральная реакция)																																																															
#																																																															
{1010}{}{}																																																															
{1011}{}{}																																																															
{1012}{}{}																																																															
{1013}{}{}																																																															
{1014}{}{}																																																															
{1015}{}{}																																																															
{1016}{}{}																																																															
{1017}{}{}																																																															
{1018}{}{}																																																															
{1019}{}{}																																																															
#																																																															
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Отрицательная реакция)																																																														
#																																																															
{1020}{}{}																																																															
{1021}{}{}																																																															
{1022}{}{}																																																															
{1023}{}{}																																																															
{1024}{}{}																																																															
{1025}{}{}																																																															
{1026}{}{}																																																															
{1027}{}{}																																																															
{1028}{}{}																																																															
{1029}{}{}																																																															
#																																																															
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Дополнительно)																																																															
#																																																															
{1030}{}{Питер мне все рассказал про Хьюго, нам нужно уходить...}																																																															
{1031}{}{Срочно нужно куда-то уходить.}																																																															
{1032}{}{Хищники из Олимпа могут прийти в любой момент.}																																																															
{1033}{}{Здесь мы обречены, Дефендеры нас всех убьют.}																																																															
{1034}{}{Нужно придумать, куда мы могли бы уйти отсюда.}																																																															
{1035}{}{}																																																															
{1036}{}{}																																																															
{1037}{}{}																																																															
{1038}{}{}																																																															
{1039}{}{}