##############################																																													
#Локация: Пещеры Нежити	
#Имя: Громус	
#Краткое описание: Разваливающийся печальный мертвяк-лекарь	
#Дата создания: 30.09.2013	
##############################	
#Для игры "Олимп 2207"	
#Артем "Rainman" Самойлов	
##############################	
#	
#ОПИСАНИЕ КРИТТЕРА	
#	
# до знакомства	
{1}{}{You see a decomposed ghoul.}	
{2}{}{This ghoul is in really bad shape.}	
#	
# после знакомства	
{3}{}{You see Gromus.}	
{4}{}{This walking mass of flesh and bone is a local healer Gromus.}	
#	
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ	
#	
{10}{}{[This pale green corpse, covered by the webs of blue veins, is carefully looking at you with his cloudy eyes of vague color] Whathcha wanth, young man?? [he slurps]}	
{11}{002}{I'd say you need a doctor. Or a caretaker...}	
{12}{003}{Uh... Are you aright? You jaw looks a little strange.}	
{13}{999}{Wh- what? No, I was just walking by.}	
{20}{}{[His jaw hangs in a funny way, like having less bones in it] Caretakher? Mmm, aigh think I'fe awready died once. Oh-h, wath thuch a long thime ago, I don't efen remember. Yeeeah. [he slurps] But here I'm the docthor for mythelf. And for eferybody elth thoo. If fumthin' hurth - you run thu me. I will noth glue a hand back, buth can gife you a bither pothion thu make you feel good! I'm Gromuth, by the way. S, s, s... Gromus. I am thinking of changing name thu Ghomuth. [he slurps]}
{21}{004}{Oh man, Gromus, right? Okay, I'm }	
{22}{004}{, nice to meet you!}	
{23}{999}{Yeah, NICE THU MEETH YA. Well, I've got to go, see you later.}	
{30}{}{[His jaw hangs in a funny way, like having less bones in it] My jaf?.. Oh, noo, my jaf ith fine, if doesn'th bother me in any way. Yeeeah. [he slurps] But here I'm the docthor for mythelf. And for eferybody elth thoo. If fumthin' hurth - you run thu me. I will noth glue a hand back, buth can gife you a bither pothion thu make you feel good! I'm Gromuth, by the way. S, s, s... Gromus. I am thinking of changing my name thu Ghomuth. [he slurps]}	
{31}{004}{Oh man, Gromus, right? Okay, I'm }	
{32}{004}{, nice to meet you!}	
{33}{999}{Yeah, NICE THU MEETH YA. Well, I've got to go, see you later.}	
{40}{}{Yeah, yeah, I'm fery glad thoo. Yeeah... another pathienth - thath ith, of courthe, fery good. Yeeeeeah.}	
{41}{005}{I'm not a patient, alright? It's only a couple of scratches.}`	
{42}{999}{Yeah, sure. Bye.}	
{50}{}{Noth a pathienth thuday, and thumorrow you are barely walking. Here itha common thing, don'tchu doubth it. Efery newcomer efenchually cometh thu me. Yeah, you will thee.}	
{51}{010}{Anyway, can I ask something?}	
{52}{999}{Yeah! We'll see!}	
{100}{}{Yeah? [he slurps] Oh, Ith you again. Well... Whaddaya thay?}	
{101}{}{Uhh?.. [he slurps]}	
{102}{Barter}{I want to see what you are selling.}	
{103}{011}{You are for the doctor here, right? Why do you look so bad then?}	
{104}{020}{Where do you get this stuff you need for your potions?}	
{105}{030}{I'm having problems with calming down Lily... You know the scorpion stuff, don't you? Can you give some advice what to do with its bite?}	
{106}{040}{I'm kinda hurt, can you heal me?}	
{107}{050}{I, uh... [gulp] don't feel so good. And my pee is glowing.}	
{108}{Hunting}{I'm ready to hunt some "fkorpionth", let's go.}	
{109}{999}{I'm good, thanks. See you.}	
{111}{}{Well, young man, you thee, I'm noth a human, I'm a ghouwl. Ang I feel mythelf wery good for one. Yeeeah. [he slurps] By the way, I'm in exacth age of looking like thith. It was, uh... Fifthy years sinthe weborn. Ooh, itha loth of thime. Maybe I'm efen older than Bono, heh-heh. Soon, the thime will come for us thu go inthu Purgathory. Nothing can hewlp me, young man.}	
{112}{}{What mannerleth young man! Get used thu it, old ghoulth can look even worthe.}	
{113}{010}{Understood. Can I ask something else?}	
{114}{999}{Oh... Yeah. I see. Ghouls, yeah. Uh, I'll come by later.}
{115}{013}{Ghouls... Are you dead? What do you mean by that?}
{120}{012}{There's one sick girl here...}
{121}{}{You mean Lily??.. Of courthe you mean her, there ith no other girlth on this ftation, heh-heh. Yeah, poor girl has been bithen by a fkorpion, I gave her anthidote, buf she needth thu waith for a while longer, the anthidote hatha wery spethific impacth. You could try cawlming her down with a lullaby, buth you should have a great voithe for this thu work - like mine, fow example. Heh-heh. [he happily slurps] Another opthion - and there ith alwayth another opthion, righth? - is thu give her a lithle bit oh alcohol. If would calm her down. If you are noth againsth the idea of waesthin' some alcohol on her, of courthe. Yeeah.}
{130}{}{Dead? Noth eferything ith so thimple, young man... I think there are thome people, like me, who don't die afther they, you know, die. They become ghouwls. I vividly remember how I wenth thu thleep fery hungry, and woke up already as a ghouwl. The thkin ith going off all the thime, you are alwayth crafing for food, but the ghouwls don'th die from hunger - they become Feralth, they loothe their mind. Feralth are hard to kill, thow we drop them inthu a place at the other thide of Tartharus. You call this plaithe Purgathory. [he smiles]}
{131}{010}{So, that's how it is... It was much simpler in Tartarus. I want to ask more.}
{122}{999}{Hmph. Thanks for advice.}
{201}{}{Ahhahah! Thpot on, my boy, thpot on! The main ingredienth ith the fkorpion sthing! Usually our kind Seekerth bring me a couple of their teilth, buth lathely they have other problemth thu take care abouth. You know whath? We couwld go hunth some fkorpionth thugether... You would be fery helpful.}	
{202}{999}{Uh... Scorpions? That stingy poisonous little creatures? No thanks, we'll do without it.}	
{203}{QA}{Scorpions... Yeah, I think we could handle it. Okay, I agree.}	
{204}{QA}{Hmm, scorpions, scorpions... I don't seem to remember what it is. Okay, I'll help you.}	
{210}{}{Thath ith wery good. We can go righth now, if you are ready..}	
{211}{Hunting}{I'm ready. Let's go!}	
{212}{999}{I need to finish something. I'll come back when I'm ready.}
{220}{}{Well, if was pretthy dangerouth, yeah [he slurps] Okay, gimme, gimme the teilth. [he unceremoniously takes away all scorpion tails from you] Oh yeeeeeah, that shouwld be enough. Well, thankth for the help, you can thake this pothion [he hands you the bottle with a questionable murky goo inside] Ith an exthract from the teilth of the fkorpionth. Cometh in handy in case of radiathion poithoning, yeah...}	
{221}{}{Thanks doc, was glad to be of help.}	
{222}{}{Well, better than nothing. See you, doc.}	
{300}{}{Li-ly... [he ponders] Yeeeah, we love to chat ath night before fleep. I think ith could help to calm hewr down, buth Martha don'th exacthly likes me. Petulant stupid woman! Thry just thu talk with the girl, thell some sthowry.}	
{301}{999}{Tell some story? But I don't know any! Anyway, thanks for the advice.}	
{302}{999}{Yeah, I could not bother asking. To tell a bedtime story to a kid - what can be more obvious? Oh well, let's try it.}	
{400}{}{[You regain consciousness in a couple of minutes after a sharp blow in your collarbone. For some reason, you feel great!] Here, ath aigh alwayth thay - good punch health eferything!}	
{401}{999}{Wow, thanks. I really hope this aching pain in my shoulder will go away eventually.}	
{402}{999}{You could have gone easier on me, doc! But thanks anyway.}	
{403}{}{[Rapidly examining you, he shakes his head. His jaw wiggles from side to side when he does that] Thoo bad, buth you had sufferedh a fery sefere damageth. I suggesth you find yourself a docthor with some toolth. Or thearch for a Heal-Up, ith can get efen a dead one back on his feeth!}	
{404}{999}{I see, I see. I'd better go then.}	
{500}{}{Justh as aigh thought - radiathion poithoning. With such paithe you hafe efery chance of joining the ranks of ghouwls, heh-heh [cough]. So, healing then? Ith will costh you }	
{501}{}{ patterieth and will thake abouth }	
{502}{}{ hourth. Whath do you thay?}	
{503}{051}{What? How many? No, I don't have it.}	
{504}{052}{Yeah, yeah, come on, heal me already.}	
{505}{999}{Don't you think it's a little too much? Nah, I better walk around glowing, but keep my batteries. Ciao!}	
{510}{}{Yeeeeah, ith thou thad to thee the young organithm dying. Well, if you find patterieth - I'm waithing right here.}	
{511}{999}{Okay, okay, I got it. Bye, doc.}	
{520}{}{[You regain consciousness after a while. You feel a little dizzy, but mostly good.] So, how are you feeling? I thook some liberthies with the pothion compothition, buth ath far ath I can thee - you are toing pretthy well. If your pee will glow again - come thu me, I'm always glad thu help!}	
{521}{999}{Thanks doc. I'll try to glow a little less. See you around.}	
{522}{999}{Okay doc. You should really stop experimenting with you bitter drinks. What if an extra toe would grow on me because of them? If it will, I'll come to you and stick it, well, you know where. [wink]}	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Положительная реакция)	
#	
{1000}{}{}	
{1001}{}{}	
{1002}{}{}	
{1003}{}{}	
{1004}{}{}	
{1005}{}{}	
{1006}{}{}	
{1007}{}{}	
{1008}{}{}	
{1009}{}{}	
#	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Нейтральная реакция)	
#	
{1010}{}{}	
{1011}{}{}	
{1012}{}{}	
{1013}{}{}	
{1014}{}{}	
{1015}{}{}	
{1016}{}{}	
{1017}{}{}	
{1018}{}{}	
{1019}{}{}	
#	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Отрицательная реакция)	
#	
{1020}{}{}	
{1021}{}{}	
{1022}{}{}	
{1023}{}{}	
{1024}{}{}	
{1025}{}{}	
{1026}{}{}	
{1027}{}{}	
{1028}{}{}	
{1029}{}{}	
#	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Дополнительно)	
#	
{1030}{}{I don'th know. We need ath leaft a couple of their teilth.}	
{1031}{}{Thoo eawrly thu return, we need more teilth.}	
{1032}{}{No, I need mowre teilth!}	
{1033}{}{A coupwle fkorpionth more - and we can go back.}	
{1034}{}{What now? Look outh for theiled creathureth!}	
{1035}{}{Yeeeeah, lookth like we hafe enough teilth. We can rethurn.}	
{1036}{}{Yeah, let's, get out of here.}	
{1037}{}{Wait, I still didn't have enough! We need to kill them all!!}	
{1038}{}{No, wait, I need to look around a little more.}	
{1039}{}{}
