##############################
#Локация: Пещеры Нежити
#Имя: Присли
#Краткое описание: Мертвяк, разочарованный в жизни и существовании
#Дата создания: 01.05.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a sad ghoul.}
{2}{}{He looks VERY sad.}
#
# после знакомства
{3}{}{You see Priestley.}
{4}{}{As usual, Priestley mumbles something under his nose.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{Huh? Another one? It's okay, you won't suffer for long. Only if you're lucky enough to turn into something like me...}
{11}{002}{What? What are you talking about, you monster?}
{12}{003}{Who are you? And why should I turn into something like you? I wouldn't like that...}
{13}{999}{Me go there. Not here.}
{14}{999}{I think it's time for me to leave.}


{20}{}{Monster!? Monster... Yeah, I guess that's how it is. I've been a "monster" for many years now. The name's Priestley - and I WAS Priestley once if you know what I mean. Because now I'm "that".}
{21}{010}{I see. I'm }
{22}{010}{, can you tell me something?...}
{23}{999}{All I hear is blah-blah-blah. Not interested.}


{30}{}{I'm Priestley. More precisely, I WAS Priestley, before I turned into... This. As far as I know, anyone can turn into a ghoul.}
{31}{010}{I see. I'm }
{32}{010}{, I'd like to know more about it.}
{33}{999}{Looks like it's all bullshit and fairy tales. I'm out of here.}


{100}{}{[He looks at you with his sad, cloudy, ghoul's eyes] Oh, you again? [sighs] How are you? Living by?}
{101}{}{Of course. Ask anything you want.}
{102}{020}{Tell me about yourself. How did you end up here?}
{103}{030}{What is this place?}
{104}{040}{I see here some crops... What is it?}
{105}{050}{You asked me to help you with a fertilizer...}
{107}{060}{How's your garden? Grown anything?}
{108}{070}{You owe me 15 batteries. Did you get it?}
{109}{999}{Actually, I've got to go.}



{200}{}{Well, if you really want to know... [he sighs] I was once a missionary of a great god named [he furiously spits] Chiefacus. I carried his word all around the Radius, telling every peasant about the heavens and thirty beautiful virgins, awaiting them after death... And now you see how harshly Chiefacus [he furiously spits] dealt with me. I was so handsome, my beautiful holy chin dimple could get me between the legs of any woman... [he rolls eyes, pondering into memories] But then I withered.}
{201}{021}{What do you mean? Did you get sick?}
{202}{}{I was a handsome man once, but the Gods [he furiously spits] cursed me, and I turned into THIS. What else can be said?.. Thank God [he furiously spits] that Robin brought me here, or I would have been eaten by jackals in the desert.}
{203}{010}{So the Gods cursed you? I see. I have another question.}


{210}{}{Yes, probably I did. Chiefacus, may he burn in his hell, put some illness on me, as I went to nap in the shadow of a mountain cliff. I woke up already like this. Skin sagging and rotting, fell-off nose, the jaw barely holding up... Do you see what I've become!? Curse you, Gods, existing or not!!}
{211}{010}{Yeah, tough luck. I have another question.}
{212}{999}{I see it's better to leave you alone for a while.}


{300}{}{This is our home - or the hole we live in, I'd say. Here's where outcasts are settled in - I mean everyone who couldn't fit into the Radius. As you see, there are a lot of ones like you. Naive fools, why didn't they sit tight in their Tartarus, getting their stomachs full...}
{301}{031}{I got that, but what IS this place actually? I see some huge machines...}
{302}{010}{Probably, you're right. I have another question.}
{303}{999}{I'm tired of talking. See you.}


{310}{}{I think it was called "the subway" before the War. It is said that people were digging long tunnels underground to drive other people around on big iron carriages... It sounds very stupid, if you ask me. It is much easier to move by the surface. What I mean is that nowadays no one knows why the hell this place was created, but at least it gives us some protection against wild beasts.}
{311}{032}{Fascinating! I want to know more!}
{312}{010}{Interesting. I have other questions.}


{320}{}{Sorry, but that's all I know. Maybe Bono could tell you more. It is him who told us about "the subway". Although... You know, he slowly loses it. As we all are.}
{321}{010}{Hm. I'll think about it. Another question.}


{400}{}{Oh, THAT... Yes, I'm trying to grow some corn, but it's not working out. There was a girl from Tartarus with full pockets of seeds. She told me you could grow your food right beneath your feet.}
{401}{041}{So? What could go wrong?}
{402}{999}{Oh, I know, what it is. No, I'm not interested.}


{410}{}{I don't even know... I wasted a lot of time disassembling the floor tiles, preparing the soil, making patches... I even watered the crops! But I only grew stems and no cobs! [he grabs his head] Probably the soil should be fertilized, but it seems that Lavash manure only makes it worse!}
{411}{042}{Maybe you need something else then? Man, I could really use Catty's advice on that.}


{420}{}{Yeah, there is even a recipe for creating a real fertilizer, I know it... I just can't make it - have no components. And, uh, no skill... Maybe if you could bring me a little bag of it? I don't have much, but I would find what to repay you with.}
{421}{QA}{Sure, why not? Tell me details, what should I do?}
{422}{999}{Uh, no, sorry. The fertilizers are not my specialty. I need to go.}


{430}{}{Great! I'm counting on you! Listen carefully: you need to take a bag of leaves, around two stacks will do. Throw in a mashed apple and sprinkle it with some ash. After that, you should pour a bottle of whiskey into the mixture, lock the bag tight and shake it to start the fermentation process. And that's it. Not very hard, right? Except I have no time to deal with the matter. And the whiskey is not cheap, you know. There was a rumor that dwellers of some elite vault in the Radius have so much that it pours out, but is it true? I don't know, sadly...}
{431}{999}{Understood. Well, I think I can easily handle it, don't worry.}
{432}{999}{Hah. Well, I can find some apples. If I can find some apples, I can find other stuff too. Wait for your fertilizer, I'll be right back.}


{500}{}{Yes? My corns are waiting!}
{501}{999}{Sorry, it's not done yet.}
{502}{051}{Go make them happy then! Here's the bag of fertilizer you need. [give Priestley a stinky bag]}


{510}{}{[Priestley readily takes the fertilizer from your hands] At last the holy Chiefacus favors me again! Maybe I shouldn't have been so harsh to him? Thanks, my friend, may the thirty virgins be with you after you die! If I get any harvest - I'll definitely share!}
{511}{999}{Come on, this wasn't so hard at all. Good luck to you in your gardening.}
{512}{052}{That was not the deal! Pay 15 batteries!}


{520}{}{[Priestley's eyes slowly pop out] W-w-wh-what? B-b-bu-but I d-do-don't h-have s-s-uch m-money...}
{521}{Recket}{Time to pay your debts. I'll come back in a couple of days. I want my batteries. I don't care where you get it. Go.}
{522}{999}{I was just kidding. Your gratitude is enough. Good luck, Priestley.}




{600}{}{Yes! The fertilizer really helped! The corn started to yield a harvest. Here, have some cobs [gives you some corn cobs] Take it, I won't take no for an answer!}
{601}{999}{Hah, well, thanks. Glad to be of help.}
{602}{}{Yes, I think all goes better than before. In a few days I'll take harvest!}
{603}{999}{Glad I could help. Good luck.}


{700}{}{B-bu-but I d-don't h-have s-s-uch m-money... I-I-I am ho-h-honestly try to find them, b-b-bu-but... Oh, m-man...}
{701}{999}{Try better, or else!}
{702}{RecketOff}{Okay, I forgive you your debt. Don't make any promises if you can't live up to them.}