##############################																																																
#Локация: Пещеры Нежити	
#Имя: Робин	
#Краткое описание: Глава местных Искателей, бывший каннибал из Оазиса	
#Дата создания: 03.10.2013	
##############################	
#Для игры "Олимп 2207"	
#Артем "Rainman" Самойлов	
##############################	
#	
#ОПИСАНИЕ КРИТТЕРА	
#	
# до знакомства	
{1}{}{You see a very muscular man.}	
{2}{}{Looks like he is not very civilized. In other words, a savage.}	
#	
# после знакомства	
{3}{}{You see Robin.}	
{4}{}{Strong, enduring, covered in scars head of Seekers.}	
#	
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ	
#	
{10}{}{[Looks at you, not even trying to hide a smile] Hey, new one! [He furiously spits] How do you like it here, Tartarus boy?}	
{11}{002}{Tartarus boy? I have a name! It's...}	
{12}{002}{Listen, you, my name is }	
{13}{002}{, and I'm not going to...}	
{14}{999}{Uh, no, I better walk somewhere else.}	
{20}{}{I don't give a shit who you think you are, or who your Tartarus friends think you are. For me, each of you is a slobbery pissing kitten who needs his eyes opened on this vast and wonderful world, hah! Don't you want to?}
{21}{003}{I don't like you, but go on. Talk.}	
{22}{003}{Okay, okay, I'm listening.}
{23}{999}{No, I'm not going to listen to this!}	
{30}{}{You sound a little sad, Tartarus boy. Cheer up! Don't you like it here? Of course, you do! EVERYBODY likes it here. You know why? Because if you're not here - you are THERE, and THERE is the place where you will get eaten by some shit in two ticks! And you won't even get WHAT exactly bit your balls off!}	
{31}{004}{I... I... Damn! I really know nothing...}	
{32}{005}{[make a sad sigh] And how do I understand what exactly is going to bite my balls off?}	
{40}{}{Hey, limp dick, pull yourself together! Now you are part of the family, so we'll teach you everything you need, don't sweat! You know, I was just like you once. Oh, wait a second - no, I wasn't!! [he loudly laughs]}	
{41}{006}{Okay, so, what should I learn for starters?}	
{50}{}{Whoa, you ARE a tough and serious girl, aren't you? [He slaps your shoulder and you feel the bruise starting to form] It's good you have a spine, don't lose it! Without a spine, you won't handle the people of Radius - and they are even scarier than beasts! They'll bite your head instantly.}	
{51}{006}{Okay, so, what should I learn for starters?}	
{60}{}{For starters, you should get how this place works. I'm Robin, and I'm in charge of each of these sturdy guys behind my back. We are the Seekers, we drag around the Radius in search of food, water, and instruments. The leader of this place is the guy named Bono, a falling-apart ghoul. He is alright and all that, but he doesn't have the balls. I mean, he literally doesn't. Then there's Hugo, he's dead meat too, but with a head - and a spine! And with him we'll take over the Tartarus someday, only need to get around enough boys and guns for this!}
{61}{010}{Oh... I see. I get it. Can I ask something else?}	
{62}{999}{Thanks for the explanation. I'll better go.}	
{63}{999}{Such an interesting place. I think we'll get along just fine. Well, see you later.}

{100}{}{Well, well, our new Tartarus boy! Whatcha need?}	
{101}{}{Sure, ask.}	
{102}{}{Well... Go ahead, ask away.}	
{103}{011}{I want to learn more about some things.}	
{104}{030}{Can you tell me about yourself?}	
{105}{040}{Do you know how one can get into Tartarus?}
{125}{020}{Maybe you'll tell what's around here?}	
{106}{050}{Bono mentioned you need help.}	
{107}{050}{Your Seekers do not look good... Did you get back from a trip to wasteland recently?}	
{108}{060}{About your request...}	
{109}{999}{It's nothing. I need to go now.}	
{111}{}{Aren't you a curious one? [he raises an eyebrow] Hahahah, don't be afraid! It's good! The information is the thing that keeps you alive in Radius. Come on, ask!}	
{112}{}{Come on, learn then. [he grins]}	
{113}{Renessance}{Did you hear something about the Renaissance?}	
{114}{012}{I'm looking for a cure from radiation for my father.}	
{115}{013}{Do you think there's possible to get into the Olympus?}	
{116}{014}{Why I don't see any children here?}	
{117}{010}{I'd like to talk to you about something else.}	
{118}{999}{No, I need nothing for now. See you.}	
{120}{}{Radiation? If you need something more serious than the anti-radiational booze of Gromus, you'd probably go for... How was this stuff called... Oh! Antiradine! They say it's hella powerful. But where to get it - I don't know, sorry. Maybe you should check up north.}	
{121}{011}{Antiradine... Well, thank you for that. Can I ask more?}	
{122}{999}{I see. Okay, will go search for this Antiradine stuff. See you.}	
{123}{}{From radiation? Easy-peasy! Our Gromus produces this anti-rad shit in gallons, all you need is to throw him a load of scorpion tails!}	
{124}{011}{No, I think it's too weak for my case. May I ask something else?}

{200}{}{DEEEEEATH! [laughs] This is the main thing you should learn. The Radius is a very dangerous place in general. Oh, wait, there is one safe spot! Called "some-Order-something", I don't really remember the name. An old factory to the west of here. Let me show you [he starts pushing buttons of your organizer], Here! Watch out for the tin men patrol while you walk there.}
{201}{010}{Maybe I don't really need to go there. Another question.}
{202}{999}{Thanks, I'll keep it in mind. Well, off I go.}
{203}{}{Sorry, runtie, I told you everything I knew. Wander around the tower, maybe you'll find something yourself. If you won't die! [he winks and friendly pats you on the shoulder]}
{204}{010}{It can wait. I wanted to ask...}
{205}{999}{Actually, I've got to go.}

{130}{}{Into the Olympus, you say? Hmm... Well, if you manage to take out every armed and armored guard, together with all their pet Chimeras - yeah, you'll probably make it to the front door. Which doesn't open even for a Devil himself! [he laughs]}	
{131}{011}{Somehow, that's exactly what I thought. Can I ask something else?}	
{140}{}{Hah! Hahahahah! What a joker you are! Just put yourself in the place of any woman here, and try to imagine, how it is to raise a child in these conditions. Or go ask Martha, if you can't imagine. She will probably tell you a lot of stuff... About the dad of little Lily, for example. How should I put it... That girl is daughter to all of us, everyone is equally responsible for her. And that's why there are no children here. Done with this topic!}	
{141}{011}{Oh, okay then. I'd like to ask something else.}	
{142}{}{Little kids are just not suitable for surviving here, that's why no one is having them. There is Martha's daughter though, Lily.}	
{143}{011}{Yes, I guess it's really difficult to raise a child here. I wanted to ask more.}
{144}{011}{I see. That's what I thought. Can I ask more?}	
{300}{}{Uhh. Listen, I'm not used to talking about myself, but... I see you are alright. I'm here for ten years or something already. I'm not from around, came from a place to the north. We called it "Oasis". It's not exactly bad, my family is still there, but... Let's say, I couldn't accept some of their local customs. I just couldn't. Don't ask! And don't go there, this place is forbidden to outsiders.}	
{301}{031}{Fine, maybe I don't need to know the details. What happened after?}	
{302}{}{Uhh, this is what I say - the less you know, the better you sleep! Or something like it... It's enough for you to know, that if I don't like you or you dare hurt someone here, we won't be having this long talks. I mean, I won't do talking at all, if you know what I mean!}	
{303}{010}{Okay, I got that. Can I ask more?}	
{304}{999}{Right, I'll better go.}	
{310}{}{After? I just wandered Radius, went to a tower, was thinking, maybe there's someone alive there. And I was always good at running, so I managed to run away from Chimeras - and they chased me down to this place. That's how I ended up here. Great story, huh? Practically everyone here - your fellows from Tartarus included - came here this way. I can't even imagine, how many of them were not fast enough...}	
{311}{010}{A whole lot, I suppose. It's good I didn't try to go to Olympus. Can I ask something else?}	
{400}{}{Now we're talking! Go see Hugo about it, he has a plan. Hugo is a ghoul, you can find him on the lower platform. He will brag about power, courage, and other stuff, but you'll get the point. Although, you can also talk to Bono. He has a plan too, a peaceful one - but as for me, a peaceful solution in Radius is total bullshit!}	
{401}{999}{I get it. Bono and Hugo. I'll go talk to them.}	
{402}{}{Now we're talking! Go see Hugo about it, he has a plan. Hugo is a ghoul, he can easily be found on the lower platform. He will tell you stories about power, courage, and other stuff, but you'll get the point.}	
{403}{010}{Talk to Hugo... Okay, thanks. Can I ask something else?}	
{500}{}{Help? Me? This ghoul with no balls really thinks I need help? HA! Hahaha! Ha. Well, Maybe my boys actually got a little tired. Man, we are so out of luck recently! Okay, my fellas are exhausted, and we don't have enough food to eat and wood for the fire. Maybe you could help us with it, find some wood and food?}	
{501}{051}{Uhh... Where do I look for it?}	
{502}{}{Aren't you a perceptive son of a bitch? Yes, we look like we had just returned from a trip. You know why? Because we had just returned from a trip! We are venturing into the damn Radius all the time, looking for supplies, materials, and all that. And, you know... We are so out of luck recently! Fellas are exhausted, and we don't have enough food to eat and wood for the fire. Maybe you could help us with it, find some wood and food?}
{503}{051}{I don't even know. Where would I look for it?}	
{504}{999}{Are you out of your mind? I don't know anything here! No, I'll pass.}	
{510}{}{Don't be a pussy, you won't have to go far! Did you see the ruins above us? So, not long ago, before moving out, we left some dried apples and wood there, to pick up on a way back. But I don't remember where exactly. And we are too tired to look. Also, there should be something in the nearby settlement to the north of ruins. We don't need much, maybe }
{517}{}{ apples. And one wood. What do you say? Don't be in a hurry, return when you have enough. We won't go anywhere. [He smiles and winks]}	
{511}{QA}{Okay, I'll do it. Doesn't look too difficult.}	
{512}{999}{Well, I'll think about it, okay? Alright.}	
{513}{}{Great, my man! Also, try searching in nearby houses - closets, chests and such. Only be careful of traps, there were people living, they could've put something against the thieves. But I'd say it's unlikely, don't be afraid!}	
{514}{999}{You could tell me about the traps first... But I said yes, so now wait for me to return with the stuff.}	
{515}{999}{Traps, shmaps. I'll deal with them, no problem. Be right back.}	
{516}{999}{I see, thanks for the warning. I'll keep an eye out.}	
{600}{}{Show me what you got.}	
{601}{061}{I'm still looking, actually. Can't find wood for a fire. Are you sure you've seen it?}
{602}{062}{Here [drop the wood and dry apples to the floor]}	
{603}{999}{I just wanted to say that soon I'll bring everything you need.}
{604}{999}{I got some wood, will find some apples and return.}	
{610}{}{Uh, let me check on my memory. Yeah, I'm sure! In in the nearby settlement, to the northwest from ruins near the entrance to the station.}	
{611}{999}{Okay, thanks, will look there.}	
{612}{}{Of course! Do you think I would lie to you? Just search a little more.}	
{613}{999}{Alright.}	
{614}{999}{Damn, you could search a little more yourself. Fine, I'll be back soon.}	
{620}{}{So helpful! Thanks! Now my boys can have a bite and get a little warmth before we hit the road again... I see that I can count on you. And you probably deserve something for your efforts, don't you think? [he digs through his pockets and pulls out a metal piece in the shape of a petal] Here! It's my personal throwing knife, so be careful with it. And don't throw it into stones, because he will bounce back right into your eye! He likes to do it, I'm serious, hahaha!}	
{621}{063}{[take the reward] Uh, thanks. Seriously, thanks.}	
{622}{064}{[give the reward back] No, I don't need that. I'm not good at throwing things anyway.}	
{630}{}{"Thanks" will not save your life, unlike a sharp piece of metal. A word of advice - learn to handle something that kills your enemies. After that, you'll see to your full potential!}
{631}{999}{Uh. Yeah, okay, sure. Well, I'll go now.}	
{632}{999}{I know. See you around.}	
{640}{}{[He chuckles] Suit yourself, }	
{641}{}{, suit yourself... I think you are a fine lad, but if you'll continue to show off, you won't last long. Take what you are given, run when you are beaten. Remember my words.}	
{642}{999}{I will. Be sure about that.}	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Положительная реакция)	
#	
{1000}{}{}	
{1001}{}{}	
{1002}{}{}	
{1003}{}{}	
{1004}{}{}	
{1005}{}{}	
{1006}{}{}	
{1007}{}{}	
{1008}{}{}	
{1009}{}{}	
#	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Нейтральная реакция)	
#	
{1010}{}{}	
{1011}{}{}	
{1012}{}{}	
{1013}{}{}	
{1014}{}{}	
{1015}{}{}	
{1016}{}{}	
{1017}{}{}	
{1018}{}{}	
{1019}{}{}	
#	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Отрицательная реакция)	
#	
{1020}{}{}	
{1021}{}{}	
{1022}{}{}	
{1023}{}{}	
{1024}{}{}	
{1025}{}{}	
{1026}{}{}	
{1027}{}{}	
{1028}{}{}	
{1029}{}{}	
#	
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Дополнительно)	
#	
{1030}{}{}	
{1031}{}{}	
{1032}{}{}	
{1033}{}{}	
{1034}{}{}	
{1035}{}{}	
{1036}{}{}	
{1037}{}{}	
{1038}{}{}	
{1039}{}{}