##############################
#Location: NWO
#Name: Sunny
#Short Description: Girl who lost her father in Pearson Town
#Date of creation: 17.08.2015
############################## 
#For the game "Olympus 2207"
#Artem "Rainman" Samoilov
##############################
#
#CRITTER DESCRIPTION
#
# before meeting
{1}{}{You see a dirty girl.}
{2}{}{Her clothes are covered in dirt and torn in several places.}
#
# after meeting
{3}{}{You see Sunny.}
{4}{}{Her clothes are covered in dirt and torn in several places.}
#
#HERE BEGINS A DIALOGUE
#
{5}{}{Did you find a paramedic's bag?}
{6}{}{We cannot leave without a paramedic's bag.}
{7}{}{Thank you so much! Becky and I are forever in your debt!}
{8}{}{Thanks again! You saved our lives!}
#Node001
{10}{}{[A young girl rushes to you as soon as you get into the room. It's rather dark here, but you notice that she looks like was tortured, or lacked any sleep for a really long time. You notice a metal pipe in her trembling hands] You are not insane. [she lowers her "weapon" and her shoulders limp down] Thank god... I almost gave up... Wait! Did you see a man there?}
{11}{002}{Sunny, is it?}

#Node002
{20}{}{[the girl starts enthusiastically nodding her head] Yes, I am Sunny. And you are?..}
{21}{003}{.}
{22}{003}{Henry asked me to help you.}
{23}{003}{Doesn't matter, the thing is that you need to get out of here.}

#Node003
{30}{}{[as if suddenly having come to her senses, she rushes to the door and swiftly locks it. She freezes, listening, then sighs] Sorry, it's just in case. I don't want these creatures to burst in here. So! You're here to get us out, right?}
{31}{004}{Yes, exactly. Your friend Henry asked me to find you.}

#Node004
{40}{}{Henry... [the girl smiles, but next second her joy instantly evaporates] Did you see an adult man in the town?}
{41}{005}{Is he your father? No. What happened?}
{42}{005}{Is he your father? No. And judging by what I've seen here - he is probably already dead.}

#Node005
{50}{}{[you hear a faint moan nearby. You didn't notice at first that there is someone else here] Sunny... Who is there? Your father? [you notice a girl lying on the floor; she leans slightly to the side on her elbow]}
{51}{006}{[continue]}

#Node006
{60}{}{[Sunny turns her head] Becky, get some rest. You shouldn't waste your energy. Help came. From the NWO.}
{61}{007}{[continue]}

#Node007
{70}{}{[Becky leans back, mumbling something about how no one in the NWO cared about them and it's very strange that someone came. Sunny turns back to you, holding her thumb up to the temple.] So... Where were we... Ah! Did you see my father there?}
{71}{008}{No.}

#Node008
{80}{}{It's very bad. [she shakes her head] When we entered the town, these "locals" attacked us. At first there was only one - father fended him off. But then more of them appeared. He drew their attention and ran, shouting us to leave... We were trying to find a secluded place, but bumped into a huge jackal. He chased us to this mall. I slammed its head with something heavy, but he still got Becky - she has her leg wounded, it's covered in blood and she can't walk... We decided to wait for the father here. So far I made several forays to the town for medicines and water. The pharmacy in the mall is looted completely. I only found some painkillers and bandages. }
{81}{009}{How much time did you spend in this basement?}
{82}{012}{Any idea where you can get something to help Becky?}

#Node009
{90}{}{Around two days, probably.}
{91}{011}{Yeah... I think it's unlikely that your father survived...}
{92}{012}{Any idea where to find anything to help Becky?}

#Node010
{100}{}{[Sunny takes the paramedic's bag from you] Great! What about father?}
{101}{015}{I didn't see him.}
{102}{015}{You know, I'd prefer not to talk about it.}

#Node011
{110}{}{You know, you cound stop reminding me about it.}
{111}{012}{Any idea where you can get anything to help Becky?}

#Node012
{120}{}{Yes. I found an old town map in the mall. There's a hospital somewhere nearby. Sorry, but I do not know which way to go, this map was in a very bad condition and I didn't really understand it. But I explored as much of town as I could. And if I understood everything correctly, the hospital is somewhere not far from where we were attacked. Maybe... Maybe you'll even find our father. What if he's in a such basement too?}
{121}{013}{So, what exactly is needed?}

#Node013
{130}{}{A paramedic's bag dad told us about. He said that if we find a few - even one - it would help us get into the NWO.}
{131}{014}{Okay, I'll look for it.}
{132}{010}{Like this one?}

#Node014
{140}{}{Good luck out there. }
{141}{999}{[end of dialogue]}

#Node015
{150}{}{[Sunny hides her eyes. Her joy from receiving the bag quickly disappears.] Okay. Let's get out of here. We'll need your help. I can inject the painkiller and apply a splint, but dragging her and fighting off the beasts - that's out of question for me. [the girl is about to get to Becky, but stops, smiles at you and gives you kiss on the cheek] Thank you. I really appreciate your help, although I may be bad at showing it. After attitude we got in the NWP - to get some help is even nicer. A pity that I lost my father in this. I still hope he fled the town and we will meet with him eventually.}
{151}{016}{[treat Becky]}

{160}{}{#Node016}
{161}{}{[Sunny handled the task so well as if she had been taught this. Becky looks much better now. When Sunny changes the bandage on her leg, you have a glance at very nasty-looking wound. But in the end, the girl finally looks relieved. Probably, for the first time for days.] Well... We are ready. No more waiting for father. Let's go.}
{163}{999}{[lead girls out of town]}

#Node017
{170}{}{[When the first joys and troubles of arriving at the NWO end, Sunny focuses her attention on you] You know, no one has ever been so good to us. I don't even know what to say... We survived only because of your help. A paramedic's bag that helped to get Becky to the NWO became our ticket to the life here. Even their cheap doctor Hinder acknowledged that we can be helpful. So now we have a house. And also, we were told that "this is more than a house! This is a family!", but I would have kept their mouth shut, if I were them. I lost my father, and he meant more to me than anyone from "family" of this place. Anyway - I don't know how to thank you. I just wanted to say it. Know that I will always be in your debt.}
{171}{999}{I'm glad that you are alright. See you around!}
{172}{999}{I'll remember this part, about the debt!}
{173}{999}{I would prefer payment, but it's fine. See you.}