##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Аренщик
#Краткое описание: Распорядитель Арены. Проводит бои, принимает ставки и участвует в квесте "Жетон Дугласа".
#Дата создания: 08.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a mustached tough guy.}
{2}{}{It's like he walked off a healthy lifestyle propaganda poster.}
#
# после знакомства
{3}{}{You see Arena Warden.}
{4}{}{A very lively administrator of local arena.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[his shaved skull is shining under the light just like metallic teeth under his magnificent mustache. Broken nose and facial scars hint that he is an experienced fighter] A new player on our Arena? Want to bet, or to beat the shit out of someone?}
{11}{011}{What's going on here?}
{12}{999}{Maybe some other time. See you.}
#
{20}{}{OH, FUCKING HELL!! Get this monster away from here!}
{21}{}{Holy shells, what is this thing?!}
{22}{}{No, NO, NO!! Get the fuck out with this pet of yours!!}
{23}{}{Are you out of your fucking mind!? Why did you bring this thing here?!}
{24}{}{Fuck me Radius, what a creature!! Get it away, NOW!!!}

{1001}{}{[he nods to you] If you are here not to talk business, then I have no time for you. I need to prepare the Arena - everything is covered in blood again.}
{101}{014}{How about a little bet?}
{102}{015}{Can you set me up a fight?}
{103}{012}{I'd like to pick up something from the Arena.}
{104}{999}{Okay, I won't be distracting you.}
{1002}{}{[he salutes you] How are you doing, champion? Getting bloodthirsty? Ha! Everyone comes back here eventually... It gets you more than the Drop.}
{105}{014}{I want to watch the fights... And to make a bet. Maybe a couple.}
{106}{015}{Less talking. Who's ready to be put against me?}
{107}{012}{I'd like to pick up something from the Arena.}
{108}{999}{I'm taking a break today. Until next time, Warden.}
{1003}{}{[he drops his makeshift dumbbell and gives you a firm handshake] Greetings, boss! Coming by to look at the fresh meat? Although, there's no one compared to you... I'm still keeping the Hog's fangs as memorabilia of that slaughter you did.}
{109}{019}{What about you? Don't you want to warm up a little? Stop playing with dumbbells, Arena awaits!}
{1010}{021}{What about profits from fights?}
{1011}{020}{Report the situation, fighter.}
{1012}{999}{Yes, it was a good fight... I'll see you around.}
{1004}{}{[he greets you with a dismissive gesture] Everything's good... Boss. Is it urgent? I'm a little busy here.}
{1013}{021}{I don't have a lot of free time too. So, how's the profit?}
{1014}{020}{How's the situation here?}
{1015}{999}{Okay, do your job. See you later.}
{1005}{}{[with a grim look, he polishes his bald head with a dirty cloth] Oh, it's you... Sorry, I don't feel like talking today. The Hog... I had a dream - to see someone who could beat him in the Arena! Instead he was murdered in a ditch, like a Lavash in a slaughterhouse...}
{1016}{015}{Life is a bitch, huh? Still, is there anyone who wants to fight me?}
{1017}{014}{Can I make a bet though?}
{1018}{012}{I have a small favor to ask - to pick up something from the Arena.}
{1019}{999}{I won't bother you then.}
{1006}{}{[Warden looks lost, despite his huge size] What happens now?... Everything is going to hell... [he notices you] What do you come here for?}
{1020}{014}{If I'm not mistaken, this is a place where I can make bet. Is that right?}
{1021}{020}{Is now a bad time?}
{1022}{015}{I decided to make a quick buck on the Arena - while I still can.}
{1023}{999}{Just checking. Was nice to see you, but I need to go.}


{110}{}{[he spreads his arms] This is the Arena! You haven't seen the Rainbow if you didn't visit this place! Here the boys with the balls of metal turn each other into a bloody pulp to the roaring of the crowd! Even observing the Chimeras in their mating season can't compare to this! As for me, you can call me Warden. I'm leading this place, so tell me if you need something.}
{111}{014}{Can I make bets here?}
{112}{015}{Sounds good... I might even want to participate. Is that possible?}
{113}{999}{I see. Okay, see you around, Warden.}


{1201}{}{And I'd like a blowjob from both of Hog's bitches simultaneously. Want to get to the Arena? Come and fight. That's the rule.}
{121}{013}{Here's how it is... That thing belonged to one Seeker, who's at the Bar now. Get it? He's always hanging around Radius, knows every nook. You would want to have a friend like him. And if I can't go to Arena, maybe you could help? It's a badge, you can't mix it up. And I'll have a word with him for you.  }
{122}{015}{This is definitely an option. Is there anyone ready to stand against me?}
{123}{999}{If that's how it is - I'd better go.}
{1202}{}{No problem, champ! You can stop asking because this is your second home now! Haha!}
{124}{999}{Man, it really is! Be well, Warden.}
{1203}{}{[he is staring into some burned book, slowly moving his lips.] What? To pick up something? Is it about taking out the trash? It's about time for you to show up. Go to Arena, don't bother me. And come earlier next time.}
{125}{999}{Uh... Yeah, thanks. I'm going.}


{130}{}{Well, yeah, but... Wait for a moment... [he leaves. You observe local flies for some time, then he returns] Here. But if you try to fuck me up - I'll make you experience a lot of unforgettable moments in the Arena. [he smiles, showing his metal teeth]}
{131}{999}{Everything's going to be alright, man! Don't you doubt it. Okay, see you around.}
{132}{999}{Did I ever lie to you? No! Let's not waste time then. Thanks again, for your help.}


{140}{}{[his eyes are flashing] Bets? Bets are good... Of course, come closer and join our celebration! No sweat! It's easy - here's one fighter, here's another. Look at them, pick any. Bets are 1 to 3.}
{141}{016}{Let's start with a small one - I'm betting fifty.}
{142}{016}{Here's a hundred, wish me luck!}
{143}{016}{Two hundred or nothing!}
{144}{015}{Actually, I prefer to earn my coin with my fists. Can you do something about that?}
{145}{999}{No. Not today.}

{220}{}{You do realize that we have one-on-one fights only? [looks at your brother] Let the gentleman stand aside.}
{221}{}{You do realize that we have one-on-one fights only? [looks at robotron] This bucket of yours is going to destroy my whole Arena! Turn it off for now.}
{222}{}{You do realize that we have one-on-one fights only? [looks at Shaggy]. No animals. Especially Fire Wolves! Tell him to sit somewhere nearby.}
{226}{}{You do realize that we have one-on-one fights only? [looks at Ludwig, who is trying to hide behind you] I see that you two are, uh, "close", but you are not going to Arena together.}
{223}{}{You do realize that we have one-on-one fights only? [looks at your company] I won't let your team go with you. Let them stay around.}
{224}{999}{Of course. Be right back.}
{225}{999}{One-on-one only? Then I'll think about it some more.}

{1501}{}{[he critically looks at you] Hmm... Okay, as a newbie, you're getting a newbie opponent. Recently we had one guy from the east coming here - that's who you're gonna be fighting. Don't forget to pay the entrance fee - four hundred.}
{151}{018}{I'm ready. Shall we start?}
{152}{018}{I'm itching to taste his blood!}
{153}{999}{Although, I think I'll pass.}
{1502}{}{Not bad for a start. This time you will fight the ex-bodyguard of our boss. His screws are a little loose, thanks to the Drop. He bulldozes forward like a rabid Chimera, not caring about protection. Keep that in mind. The fee is four hundred, just like the last time.}
{154}{018}{I've seen worse. I'm ready.}
{155}{018}{Ha! The only one who has his screws loose is me! I hope you dug up a grave for him...}
{156}{999}{Let's do it some other time. I've got things to do.}
{1503}{}{I have a feeling that it's going to be a spectacular show today. Be warned though - your opponent is not that simple. He is a savage, bad at talking, even worse at thinking, but already put down seven guys. He doesn't mind eating some human flesh after the fight - or so I've heard. Still, if he kills you, I think you wouldn't care... The fee is usual.}
{157}{018}{It is I who will rip his liver and eat it! Let me at him!}
{158}{018}{I hope you're right about your feeling. Let me warm up a little, and we can start.}
{159}{999}{Uh... No. Not now.}
{1504}{}{I have a special one for you. Check this out - I called him from the other side or the Radius! He is a professional fighter, albeit not young. He put down so many people... I had a chance to fight him too. Those were the days... Watch for his right hook and keep distance. I'm not trying to make you piss yourself, just giving you a picture of what you're dealing with.}
{1510}{018}{Did you warn him too? If he approaches, I'll gouge his eyes out! Yeah! Time to kill!}
{1511}{018}{I'm in. Let's go.}
{1512}{999}{Wait, I need to prepare.}
{1505}{}{[he sighs] That's how it is - Mate expressed his desire to fight you. Don't look at his appearance, the Hog made him his right hand not just for kicks. He is smart and cunning... Honestly, I'm getting no joy from this kind of fight. Mate is my friend, but you, champ, are no stranger to me too. You made me so much money! Yeah... Anyway, give him your best, the crowd is waiting!}
{1513}{018}{I hear you. Let's mess his hair a little.}
{1514}{018}{I can only promise that he dies quickly... And painfully! That's it, I'm going!}
{1515}{999}{I need to prepare for this kind of fight... }
{1506}{}{[he makes a long pause] Hog himself became interested in you, champion. I don't know what's going on in his head, but... This is really serious. You've never seen anything like it. Are you aware that he doesn't sleep? Or that he can squash Ursa's skull with his one hand? Try to avoid getting close - if he grabs you, you're going to be broken in half. Ready?}
{1516}{018}{It's time to rip this Hog's fangs! Tell them I'm going!}
{1517}{018}{I'm ready. Don't worry, we'll make this beautiful.}
{1518}{999}{I need to deal with something. Talk later.}
{1507}{}{[he sighs with regret] No, champ. There's no one like you, so people are not betting against you... And I can't make a profit in this situation. Sorry.}
{1519}{999}{That's how the price of glory looks like... Okay, I had my share of fights.}


{1601}{}{[he gives you winnings] We are dealing honestly here - take your share, lucky guy. As agreed - }
{161}{}{ batteries.}
{162}{999}{Ha! The fortune favors strong! Be well.}
{1602}{}{[he shrugs in regret] Tough luck, kid. It happens sometimes.}
{163}{017}{The fight was a set-up! Get me back my batteries, bitch, or I'll carve your name on your bald head!}
{164}{999}{A fucking rip-off... I'll be back soon.}
{165}{999}{Yes, it happens. Maybe next time.}


{170}{}{[he stretches his neck] Nice, a chance to remember the glory days on the Arena... Do you know what a "windmill with a back entrance" is? Or "winky molerat"? I'll show you...}
{171}{998}{Come at me!}


{1801}{}{[he nods, looking satisfied] Pretty good. You have some potential, and the crowd likes you. Here are your winnings.}
{181}{999}{Thank you very much. Later!}
{1802}{}{[he pats you on the shoulder] Good job, kid! As you broke his jaw, I understood right away that it was a good idea to bet on you! Keep it up! And don't forget your winnings.}
{182}{999}{Yes, it was a good warm-up. Now I can get some rest.}
{1803}{}{You are just like me in my best years! Went so hard on that asshole, now I have to clean the Arena for a whole day after you... I need to think really hard about who to put you against next time. For now - here, you earned it.}
{183}{999}{Notice that I won't count it! Okay, see you.}
{1804}{}{My champion! If you only knew how much money I made on you... I'm going to fuck every girl in a brothel - and then drink every bottle of Apothecary's booze! This was a hell of a fight! Where did you learn that tricks? Teach me, when you'll get the chance. Here's your cut... And a little extra - from me.}
{184}{999}{Blood money... Nice. Until next time.}
{1805}{}{[he silently watches Mate's body, leaving a blood trail, being dragged off the Arena] Oh, Mate, my Mate... Anyway, that was his choice. And you? You did a clean job, as always. Here, champ.}
{185}{999}{Don't feel bad. Better him than we.}
{1806}{}{[he gazes at the Arena, unable to say any word] Fuck me sideways by a ghoul... It's worth living to see a fight like this! It's like the next Great War! There was Hog - and now it's just a puddle of blood with a pile of meat... Here, this is yours. [he starts counting the batteries, but suddenly gives you everything he holds] You know, take it all! Holy shit... What's going to happen now?}
{186}{999}{You'll see. Wait here, I'm going to have a talk with you very soon.}


{190}{}{[he puts his hands up, laughing] No, boss! I don't want to become a cripple for the rest of my days.}
{191}{020}{Okay then, relax. Better tell me - how's the situation around here?}
{192}{021}{Will you enlighten me about local business then?}
{193}{999}{Take care of yourself, big guy. See you around.}


{2001}{}{[he shows his clenched fist] Like this! I'm keeping the situation tightly under control, boss! The fighters are coming to me themselves! And since you put Hog down, Arena is always full with the crowd. The place is famous now! Maybe I should put a memorial sign.}
{201}{021}{A good idea, by the way... So, this means that our finances are good?}
{202}{999}{Glad to hear. Keep them on their toes, bud. And I need to go.}
{2002}{}{[he shrugs his strong shoulders] More or less. Like before, I'd say. We won't find anyone like Hog, that's for sure, but the Arena is still providing a steady income. }
{203}{021}{Elaborate on that, be so kind - what about the profits?}
{204}{999}{Good. Well, I need to go.}
{2003}{}{[he shakes his head, like stunned Ursa] Everything is shit, kid. Soon the Rainbow will become a memory of itself, especially with this fucking anarchy around. We're in dire need of a leader, someone with metal balls... Man... Only the Arena keeps me from getting drunk all the time.}
{205}{999}{This is something to think about... I won't be distracting you anymore.}


{2101}{}{[with a happy look, he weighs a little black bag in his hand] All here, boss! It's so much, my biceps are getting tired to hold it! }
{211}{999}{Great! Give it to me. Good job, tough guy!}
{2102}{}{[he bites a tip of his mustache] Steadily, boss. It's going to be a lot of money, just wait for the payday. As usual, come 5-th and 20-th.}
{212}{999}{Glad to hear. See you soon.}
{2103}{}{[he throws you a bag of batteries] All there is. It's not going to be more than that.}
{213}{999}{Money is money. See you around.}
{2104}{}{[he yawns, showing his metal teeth] There's something... Come by at 5-th or 20-th - we'll see what we have.}
{214}{999}{Right. And I need to go now. See you.}