##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Белочка и Снежинка
#Краткое описание: Наложницы Кабана. Альтернативное решение квеста с озабоченным Кирпичом и возможность отравить Кента.
#Дата создания: 03.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a couple of drug addict females.}
{2}{}{They lean to each other, gazing around with a frightened look.}
#
# после знакомства
{3}{}{You see Squirrel and Snowflake.}
{4}{}{A lifelong slaves of Rainbow's master.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[you see two quite pretty girls... If someone would clean them, feed them and change their torn clothes. The taller one stands up when seeing you, covering her friend] Please, don't hurt us... We'll behave! [her voice trembles. She discreetly pushes another girl - but that only makes her to hug her thin, shaking shoulders tighter] Give us the Drop... Just a little... We'll do anything... [she hastily begins to undress]}
{11}{011}{Whoa, easy! I just wanted to ask who are you.}
{12}{011}{Wait, that's not why I'm here. Come on, put on your clothes back on. What the hell is happening here? And who are you?}
{13}{999}{This is what I call a good service! Too bad I need to go.}


{1001}{}{[They look a little more lively than when you first met them, and they even cleaned up a little bit] Hello... Do you have some Drop for us? The Hog rarely visits lately... Which means... [another girl suddenly starts giggling and chanting] No shag - no Drop, bitches!!}
{101}{011}{So sad. Who are you again?}
{102}{012}{I don't have it, but I know who could help you.}
{103}{999}{Hey, be quiet. I'm just walking by.}
{1002}{}{[one girl blankly stares in front of her, the other one rocks back and forward, pulling her messy hair] The master is dead... No Hog - no Drop... [whines] Who would take care of us now? [she shakes her friend] We have to hurry! Mate waits for his meal! If we won't get it to him, he will beat us up again...}
{104}{015}{Hey! I can help you. In exchange for a little favor.}
{105}{011}{Shake it off for a minute and remind me, who are you?}
{106}{019}{As it gets quiet - go to the Apothecary. He has the Drop and the stuff. Do you remember what to do?}
{107}{999}{Get lost, you stupid junkie!}
{108}{999}{Damn, how low you've fallen... I need to go.}
{1003}{}{[she readily gets on her knees] What does our master wants? We will do everything! Just so master would be pleased...}
{109}{999}{This is in your best interests. Anyway, get cleaned up quickly. The master needs to release some tension.}
{1010}{020}{How are you doing, pretty girls?}
{1011}{999}{I don't have time for you now. Sit tight and don't twitch.}
{1004}{}{[there's almost nothing left of their clothes, they look very beaten. One is lying still in the corner, only a faint shivering shows that she's still alive. Another one looks a little better] Wh... Why would they do this to us? [she spits out blood and chipped tooth on the ground, staring at it] We... We would do anything, why did they hurt us?... So hungry... [quietly whines]}
{1012}{999}{Damn... What an animals... }
{1013}{999}{I'm sorry. Here, take this, at least... [give her a fruit]}
{1014}{999}{Tough luck. The life is hard, you know. Too bad I'm late to get some.}
{1015}{999}{Man, the commodity is ruined. Although... Open your pie hole, bitch. I think it's gonna be even better without the teeth. Relax, will you... [continue abusing the girls]}


{1101}{}{I'm Squirrel, this is Snowflake... [she wrinkles her forehead, pondering] Or is it the other way around? It doesn't matter. Nothing matters... Ask our master. The Hog is kind... He feeds us, takes care of us... And if we behave, he gives us the Drop.... The Drop... [the other girl smiles when hearing this. You notice she lacks some front teeth.] Will you be kind to us?}
{111}{012}{I don't have time for this, but I know someone, who would take a good care of you.}
{112}{999}{Don't even try to touch me, you stoned puddle of puke!}
{113}{999}{Try to calm down a little... I won't disturb you for now.}
{1102}{}{We are Squirrel and Snowflake, we are always together... [another girl vigorously nods] Always together! In all ways! It's so bad without the Hog... Mate notices us only when he wants to beat up someone... It hurts so much... [she sobs]}
{114}{015}{This sucks. But I can help you - if you will help me.}
{115}{013}{You know, there is one good guy who could help you... No, not me.}
{116}{999}{Life is hard. Well, take care.}
{117}{999}{I'm sorry. I'll try to figure something out. Hang on.}


{120}{}{Who? Tell us! Please! [she grabs your hand. You notice her bitten fingernails.]}
{121}{013}{Brick. The warehouse guard. You'll recognize him right away - a huge guy, not like the most around here. If you act nice, he'll help you.}
{122}{999}{You know, now is not a good time. Let's talk later.}


{1301}{}{[She struggles to put all her thoughts together] But... The Hog would be angry! No? He was angry at Squirrel once, she had to crawl to the toilet for a week after that... [she strokes her scraped knees]}
{131}{014}{Of course not! The Hog and Brick are good friends! So, he will be pleased. But don't tell this to him, let it be a... Surprise. Do you know some quiet place around here, where no one would bother you and Brick?}
{132}{999}{Suit yourself then.}
{1302}{}{[she looks scared] We would like to leave for some time.... But Mate won't let us... }
{133}{014}{Oh, come one! You said so yourself, that he doesn't pay any attention to you! Right? Good! Still - be cautious. Pick a quiet spot.}
{134}{999}{Suit yourself. I won't push it.}


{1401}{}{[she gets lively] When the Hog is pleased, he is very kind... [another girl gets closer to you, her eyes are flashing] I know the place! A quiet place, a good one... Let your friend come, we won't tell anyone...}
{141}{999}{Great. I'll let him know. And remember - not a word about it.}
{1402}{}{[she gets lively] Mate will go to the Arena soon... [another girl gets closer to you, her eyes are flashing] I know the place! A quiet place, a good one... Let your friend come, we won't tell anyone...}
{142}{999}{Great. I'll let him know. And remember - not a word about it.}

{150}{}{We will do anything! [another girl frequently nods] It's so bad for us now! What do you want?}
{151}{016}{Did you say you get meals for Mate?}
{152}{999}{Nothing for now. But be ready.}


{160}{}{Yy-yeah... He is not kind as the Hog, he punishes us... He punishes us all the time! [she stretches her arms, covered in bruises]}
{161}{017}{Stop tolerating it then! That's what you'll do - go to Apothecary, he will give you something. Put it into Mate's food. I'll reward you with the Drop for this. One dose for each!}
{162}{999}{I see. Wait here.}


{170}{}{[she shakes her head] No, we can't... We are not allowed to touch food... He'll kill us... We saw one girl beaten to death, like a dog... So bad without the Hog... [she starts to cry]}
{171}{018}{Get it together! Do you need the Drop or not? Why should I sweet-talk you into it... By the way, it's Mate who murdered your lovely Hog. It is him who ruined your life! Don't you want to settle this score?}
{173}{999}{I hate crying. I'll come by later.}
{172}{999}{You are so useless. I won't bother with it then.}


{180}{}{[her tears suddenly dry out] He... Did it? The he dies! Squirrel and Snowlake will avenge you, master... Give us your stuff! [another girl starts energetically jumping] }
{181}{019}{Not me. Go to Apothecary. He waits for you. And don't get caught.}
{182}{999}{I'll make a deal with Apothecary and be right back.}


{190}{}{We know what to do, we'll do everything... You will be pleased... Thank you so much...}
{191}{999}{Hm. Good luck to you then.}
{192}{999}{If you screw this up, I'm going to murder you both! Now, do it!}


{200}{}{[she nods so often that you see a risk of damaging her neck vertebrae] We are good! Thanks to you... We feel even better now than with the Hog! And we don't crave for the Drop as much as before...}
{201}{999}{I know what you want. Get ready to be used for your designated purpose!}
{202}{999}{I know. Here, you deserved this. [throw them fruit]}
{203}{999}{I didn't expect anything else. Okay, get some rest.}

{210}{}{She is dead... Dead...}
{211}{}{...Poor girl, I'm so alone now...}
{212}{}{I'm alone... So empty...}
{213}{}{the Drop... the Drop... the Drop...}
{214}{}{Nothing matters, Nothing makes sense...}
{215}{}{Be a little more gentle, honey.}
{216}{}{Yes, Yes... Keep going.}
{217}{}{Lower... More...}
{218}{}{You have such strong hands!}
{219}{}{Your hands are so strong...}