##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Кирпич
#Краткое описание: Озабоченный охранник склада. Квест Пастуха.
#Дата создания: 11.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a huge guard.}
{2}{}{He looks nervous. Or horny. Or both.}
#
# после знакомства
{3}{}{You see Brick.}
{4}{}{As big as lavash. Smart as much.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[This guy looks like Ursa wearing leather jacket. When you approach, he gets more tense, trying to look even bigger] Hey! Where do you think you're going? Better fetch me some beer from the bar, will you? Tell Apothecary that it's for Brick. No one goes here. Except maybe some juicy chicks with big boobs... And no more than for five minutes! [he hoarsely laughs]}
{11}{011}{Five minutes, that's it? Looks like they don't visit his place very often...}
{12}{013}{Brick, right? We need to talk.}
{13}{012}{What's it you are so furiously guarding here?}
{14}{999}{I see. Take care, bully.}


{1001}{}{[he straightens his shoulders and gets serious] You again? I told you - nothing to do here.}
{101}{013}{I'm from Shepherd. I think you know why.}
{102}{012}{And what is it so important you're guarding here?}
{103}{999}{Relax. I'm just walking around.}
{1002}{}{What else do you want?! No, I don't go to Shepherd's chicks. At all. Sitting here, polishing my gun's barrel.}
{104}{012}{Spare me the details. Better tell me, why are you hanging around here all the time? }
{105}{999}{Don't worry, you'll get lucky someday. Good day to you.}
{1003}{}{[he looks nervous] So, how are my chicks? I'm getting all shaky already - too long without a good fuck!}
{106}{019}{All set. What's left is for you to meet them and talk details.}
{107}{999}{Wait for a little more, I'll let you know when it's ready.}
{1004}{}{Chief! During my time on duty no incidents occurred! Fuck me ghoul if someone gets past me! I swear with all my chicks that it won't happen!}
{108}{013}{You're too lively, I see. I can give you problems. Why are you bothering Shepherd?}
{109}{013}{I had a talk with Shepherd. Can you guess about what?}
{1010}{023}{How's it going, soldier?}
{1011}{999}{Good job. You know what to do. Okay, later.}
{1005}{}{[he is taking a nap, leaning against the wall. Under his feet lies a whole pyramid of empty bottles. When you approach, he opens one eye] What? Get lost, don't loiter here... And tell me - does that black ass pimp still have some bitches to fuck?}
{1012}{013}{Does or doesn't, you're not getting near them anyway. Got it?}
{1013}{023}{I see you're doing pretty well.}
{1014}{999}{I'd better go.}
{1006}{}{Ha! The king of bitches has arrived! [he shows his missing teeth in a wide smile] I think it's great that you've dealt with this coal asshole! He didn't let me near his whorehouse.}
{1015}{013}{Then it's in your best interests to collaborate with me. You wouldn't mind telling me what you're guarding here, right? Or you'll have to pay for every Shepherd's girl you screwed with.}
{1016}{999}{Of course, we are always happy to see our regular customers. I hope to see you soon.}
{1017}{999}{Don't be so happy. I won't let anyone to disturb order in my establishment. Take care, guard.}
{1007}{}{[he is taking a nap, leaning against the wall. Under his feet lies a whole pyramid of empty bottles. When you approach, he opens one eye] What? Get lost, don't loiter here... And tell me - are there still bitches left to fuck in that brothel of yours?}
{1018}{023}{I see you're doing pretty well.}
{1019}{999}{I'd better go.}


{110}{}{[he stares at you, not saying anything, then gets an intimidating look] What the fuck are you implying? It's five minutes just because I can't leave my post for longer! Otherwise, I would be spinning every local chick on my device for hours!}
{111}{013}{Okay, your device is none of my concern. We need to talk.}
{112}{012}{I believe you, cut it. Tell me, what you're guarding?}
{113}{999}{Sure. See you around, sex-monster.}


{1201}{}{What am I guarding? I mean - the warehouse, of course! [he laughs] Actually, I can't talk about it. Get lost.}
{121}{013}{Are you a local retarded clown? I'll make you more serious. We need to talk.}
{122}{013}{Listen here - Shepherd has something to tell you.}
{123}{999}{See you around, funny guy.}
{1202}{}{[he stumbles, then speaks] If I tell you, would you get lost? I have enough on my plate... There's one girl in the lab. She is the daughter of smart-ass who invented the Drop. Name's Naomi. She looks important - I'm even not allowed to fuck her...}
{124}{999}{I see. I don't have time for it now, I need to go.}


{1301}{}{Shepherd, you say? I bet he told everyone shit about me and to afraid to show up himself. Did he sent you as his slut? You're not my type, you know! [he hoarsely laughs]}
{131}{016}{What did you just say, sperm bank?! Come here! [grab him]}
{132}{014}{I said I will solve this matter - and I'm going to do it. }
{133}{999}{Oh you f... I'll be back later.}
{1302}{}{[he scratches his head] So, our potato fella tattled on me... Well... Chief, try to understand - I'm hanging out here like a dick in the box! The job is dangerous, I'm nervous... How do I relax? }
{134}{025}{Don't you dare playing the pity angle! You left the post, plus you didn't pay for service! Questions?}
{135}{026}{There's an option. I can set you up with two girls. But if I'll see that you visit them on shift... I'm going to chop your dangle off!}
{1303}{}{[he spits at your feet] It's about Shepherd, huh? He can't hide behind Hog anymore. So, what're you gonna do? Suck my dick?}
{136}{021}{What did you say? You're the one who's going to suck dick!}
{137}{014}{There's always an option, which benefits everyone. And I'm going to find it.}
{138}{999}{I don't have time for this. But I'll be back.}


{140}{}{[And? What are you going to do, mr. Cool Guy? Ony don't hit me, haha!}
{141}{015}{I'm suggesting a compromise. What if I find you a worthy replacement of Shepherd's girls?}
{142}{016}{That's exactly what I'm going to do, you sex-obsessed freak! I'm going to break your bones until you understand that you have nothing to do at Shepherd's! [grab him]}
{143}{017}{Let's take a look at the situation. You are just a guard, while Shepherd is Hog's favorite. Who do you think Hog would back up? I barely talked Shepherd into not telling Hog about you...}
{144}{021}{Damn, why the hell not? Let's see if you have some muscles under this layer of fat!!}
{145}{024}{Why to have problems with Shepherd, when Hog's slave girls are now left without master? If you hurry, you can take them for yourself...}
{146}{999}{You'll learn soon. I'll be back}


{150}{}{Who can you offer me? A lavash? Every girl around here ended up it a brothel...}
{151}{018}{What about Snowflake and Squirrel?}
{152}{999}{I don't know yet. But I'll tell you when find someone.}


{160}{}{[you grab his throat with right hand, holding him with your left. He tries to break free, but you only tighten the grip. When he starts to wheeze and faint, you let him go, and he drops to the ground, coughing and shaking] Khack! Fucking... Damn... Why do you need to get steamy all of a sudden? I get it, I'm not stupid... Okay, you win. I won't go to the whores until I have enough money to pay for them. Still, you shouldn't have dealt with Shepherd. He's too greedy...}
{161}{999}{That's not your business, understood? I can handle him. That's it, I'm going.}


{170}{}{[he kicks empty bottle under his feet] This chocolate piece of shit is sticking his nose everywhere... He always feels bad when someone else feels good! Well... Okay, I'll keep quiet for now. The Hog is no joke - if he won't go to me himself, he will still send Mate. And Mate can easily cut my balls off...}
{171}{999}{You get it. I'm glad we've come to an agreement. Good day to you.}


{1801}{}{[he perplexedly blinks] Uh... You mean... To shag the Hog's bitches? Uhhh... He would fuck me up for this...}
{181}{019}{Relax, everything is already taken care of! They both, you hear, BOTH agreed to play a pink pony with you. [wink]}
{182}{019}{Don't sweat, everything's going to be alright. They are dreaming about a man like you, I've heard it myself! Just don't be afraid and try your luck. You're the man!}
{183}{999}{Maybe you're right... Let's consider other options.}
{1802}{}{[[he perplexedly blinks] Uh... You mean... To shag the Mate's bitches? Uhhh... He would fuck me up for this...}
{184}{019}{Relax, everything is already taken care of! They both, you hear, BOTH agreed to play a pink pony with you. [wink]}
{185}{019}{Don't sweat, everything's going to be alright. They are dreaming about a man like you, I've heard it myself! Just don't be afraid and try your luck. You're the man!}
{186}{999}{Maybe you're right... Let's consider other options.}


{190}{}{I knew it! Hang on, bitches, here comes the daddy!... Uh, it's still scary... [he leaves, mumbling something]}
{191}{999}{You'll show them! Uh, at least something.}

{200}{}{[he is definitely having doubts] Well, if you would deal with it... Man! What if they'll know?... But I want to fuck! Poor me... Okay, you live only once! I agree!!}
{201}{999}{Good! Stay here and wait for the news.}

{210}{}{[he gets closer] If it's about bashing heads - I'm always in. I have such a great boner after, you could chop wood with it...}
{211}{998}{You're going to be pissing with blood! Hang on...}
{212}{998}{Damn... You're so slow to understand what's happening. Okay, let's warm up a little.}

{220}{}{[Brick slowly stands up, spitting out his teeth] You broke my nose, asshole... Looks like the rib too... Okay, I won't go to Shepherd's anymore. Happy now? And now, be kind, get away, will you?...}
{221}{999}{That's better. If you pick on me again, you won't get off so easily. See you around.}

{2301}{}{It's all quiet, chief! Our smart-asses are working non-stop, afraid to even twitch... And the Rainbow became more calm. Everyone knows that it's dangerous to mess with you. Don't forget me when you're going to the Jackals! }
{231}{999}{I sure won't. As for now, look after the lab - everything can happen...}
{2302}{}{Yup. No one tries to fuck my brain now. I made a deal with Apothecary - we're trying to sell the remaining Drop all at once... So, I'm guarding it for now. And he supplies me with booze. [he gulps from the bottle] }
{232}{999}{Yeah... Good luck to you both.}
{2303}{}{Yup. No one tries to fuck my brain now. I made a deal with Apothecary - now we're partners, selling the Drop to junkies from all around Radius. So, I'm guarding it for now. And he supplies me with booze. [he gulps from the bottle]}
{233}{999}{Yeah... Good luck to you both.}

{240}{}{[he jumps up, bottles fly all over] Really?! I didn't even know!! I thought they ran off... Squirrel is such a beauty... Thank you for this. I'll go check upon them. Tell black asshole that we're good. }
{241}{999}{Good. I definitely will.}

{250}{}{[he stares at you with fright] Chief, I... I... I'm sorry! It won't happen again! I get it, really!}
{251}{999}{I believe you. But to make sure that you really get it, you're going to clean the toilet in barracks for the whole next week. You can start now. And I need to go. }
{252}{999}{Hmm. I need to think what to do with you. Talk later.}

{260}{}{[his jaw drops, he stares at you, dazzled] That means... I can do Squirrel, right? I was always into her... Ooh... Thanks, chief! I will never leave the post anymore, you can count on it!}
{261}{999}{Okay, okay, enough. But be warned, one more screw-up, and I'm going to chop off your sapling down to the root.}
{262}{999}{On the other hand, I need to think about it. Wait for my decision.}

{270}{}{[mumbles] Stupid bitch! What have you done!? Stupid... Dead... BITCH!}
{271}{}{The bitch tried to run away, I'm telling you!!}
{272}{}{Why couldn't this stupid chick just stay there?}
{273}{}{I couldn't let her go! And she resisted!}
{274}{}{[mumbles] Stupid bitch... Fuck! Why... Why did she want to run off..}