##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Дуглас
#Краткое описание: Искатель из Олимпа. Квест на жетон. 
#Дата создания: 10.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a tough guy in a suit of military armor.}
{2}{}{He is thinking about something, indifferently looking around the bar.}
#
# после знакомства
{3}{}{You see Douglas.}
{4}{}{An experienced Seeker and regular customer of all the scuzziest corners of Rainbow.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[he looks just as his old weary military armor without any insignias -  his scraggly beard almost fully covers his thin face, one eye is a little googly because of an old scar, stretched from forehead to cheekbone. His hair, which definitely used to be black, now are mostly gray. He doesn't even look at you, when you come by, too busy with his drink.] Did you want something?}
{11}{}{Sorry to bother, but it's not often you see people of your kind in these places. I'm }
{13}{011}{.}
{12}{999}{No, nothing. I was just walking by.}


{1001}{}{[nothing has changed since your last conversation. Except, maybe, he looks even more tired] Oh... You again?}
{101}{011}{Well, yeah. Forgive my intrusion, but I haven't met people of your kind before. I'm }
{99}{}{, by the way.}
{102}{023}{I got your badge.}
{103}{012}{I wanted to ask you about your adventures, if you don't mind.}
{98}{999}{Yeah. Hello... And goodbye.}
{1002}{}{[seeing you, he raises the glass. Chain on his bracelet gives a metallic ringing] Cheers, man! What Douglas can do for you?}
{104}{012}{I just wanted to hear stories about your travels around Radius.}
{105}{999}{I wanted to check upon you. Take care of yourself, Douglas.}
{1003}{}{[For a moment, he stops polishing his weapon, and salutes you, not leaving the chair.] The big boss himself! What does Rainbow wants from an old Seeker?}
{106}{025}{How do you like the local hospitality?}
{107}{999}{Not yet. I'll leave you for now.}
{1004}{}{[he is digging through a ragged army bag. When you appear, he just carelessly nods] Hey, man. Sorry, won't share a drink with you - a little busy, you see.}
{108}{025}{Going somewhere?}
{109}{999}{I won't bother you then.}
{1005}{}{[seeing you, he gets lively] The most useful person in the Rainbow! Come! How's business, is everything alright? Your girls are the only ones who can comfort me in this rotten world. Apart from booze and the Drop, of course.}
{1010}{023}{I got your badge.}
{1011}{011}{Yes, our girls are of highest tier... Sorry, don't remember your name. My bad. It's very good to know people like you better.}
{1012}{012}{I found some spare time to listen to your stories about traveling around Radius.}
{1013}{999}{Well, we're always happy to have you in our establishment. Come by anytime.}


{110}{}{Douglas. [he chuckles, but his eyes look just as indifferent as before] And what "kind" are you talking about, may I ask?}
{111}{012}{Well... You look like an experienced traveler who have been through a lot. And stayed in one piece. Considering that I'm often walking around the Radius myself, my interest is pretty clear.}
{112}{024}{I mean, the kind of lame clowns, who put some armor on them and think that there's no one better in the whole world, except the Olympus itself. Let's put it like this - you tell me who are you and what are you doing here, and I let you leave this place without any problems. Mostly.}


{120}{}{[he shrugs, rolling empty vial of Drop around the table] Yes, I've been places. Seeker who stays in one place for too long is going to die from hunger... Just like I am in this dump. [coarsely laughs]}
{121}{013}{Seeker? Is this your job?}
{122}{014}{Can you tell me about the places where you have been?}
{123}{021}{Hmm... And I wanted to ask if you have some work for me.}
{124}{999}{I see. I hope that we could have a talk before it happens.}


{130}{}{[his laugh gets filled with hysterical notes] A job... Yeah... Everyone thinks that in the beginning - all you need is to rummage through some ruins, get yourself full pockets of stuff and then live happily ever after. The thing is - you can't leave. You can't do anything about it. And nothing will help to cope, not booze, nor whores. Only the Drop - but not for long... [he shakes head and empties the whole glass in one gulp] Bullshit aside, we are looking for an old tech, trying not to die in process from something contagious, bullets, claws or radiation. Or something else.}
{131}{014}{Very interesting. Can you tell me about the places where you have been recently?}
{132}{021}{Do you need any help in your... Search?}
{133}{999}{Thanks for the info. I need to go.}


{140}{}{[he rubs his neck, covered with old burns] Well, lately I've been walking the route between bar and whorehouse back and forth. I doubt you are interested in this... You know, I'm not very used to talk with my mouth dry.}
{141}{015}{No problem! Take a ten, get yourself a drink.}
{142}{024}{So, you have been bending my ear all this time, only to ask for some change? Seeker, my ass! I bet you seeked only around local dumpsters!}
{143}{999}{You know, I don't have time for this. See you later.}


{150}{}{[he takes a long gulp] Oh shit, that's good... Okay, what do you want to hear about? Do you know about the Dead River? There's an old cryogenic lab just nearby. Such an interesting place... No one knows what sleeps in there, seeing dreams in eternal cold... And what would happen if it wakes up. But you can't get there easily - the Sunset Jackals are guarding the passage. I managed to get through once, but that way is closed now. }
{151}{016}{Okay, go on.}
{152}{999}{Enough of the tales by the campfire. Bye!}


{160}{}{So I had to find another way out. Bumped into a couple of Ferals, almost got torn to pieces... Needed to lay low somewhere, stumbled onto a house. And this house turned out to be not so simple. I tried the basement - and there was a whole military bunker! The kind of where I found myself this suit [knocks on his armor with a fist]. You can easily get a good gun in such place. Still, this bunker is now occupied by some dirty raiders. Slick bastards, I barely got away. They gave me a souvenir [he puts away his hair and you see that part of his ear is missing] Maybe I'll return there later...}
{161}{017}{Is that it?}
{162}{999}{I see. I better go, while I'm still not sleepy.}
{163}{016a}{A military bunker? Ha! Every guy I meet is always telling me about some secret places...}

{164}{}{You are too young to tell for sure what's true and what's not. In any case, here's the coordinates. Your responsibility. I would advise you to get some Resistanol, or you won't make it out of there alive.}
{165}{999}{We'll see about that. If this place exists.}
{166}{017}{I'll definitely chack it out. What else can you tell me?}

{170}{}{[he stops to take another gulp] But the most interesting things were in a destroyed town to the south-east of Olympus. My theory is this - when the war started, locals managed to get into catacombs. They tried to settle there... Except the nature is a bitch, and it had darkness and radiation to put against their hand-made shelters. So, they changed. Now they can easily smell you a hundred feet away - but their skin is thinner than a condom, I'm telling you! You look at one - and see what he had for breakfast! Well, maybe I'm exaggerating a little, but still pretty close. You can pierce them with a finger, hehe... Which is exactly what I did, when trying to get a sample... But that's another story, not for your ears. }
{171}{018}{Yeah, you see a lot of strange stuff around Radius... What about here? What are you doing here?}
{172}{999}{Thank you for telling me all this, but I need to go.}


{180}{}{[he leans forward, looking into your eyes] Why do you care? I'm so sick of you all! I am just relaxing here, alright?}
{181}{019}{You are right, that's not my business. But the folks around here are pretty suspicious. And here you are, who knows for what... Is it really such a big secret? I mean, you don't look like someone on an important mission, no offense.}
{182}{019}{Is that so? I was just thinking about giving you a discount, for our regular customer...}
{183}{019}{Really? When go fetch a badge, then you're the best buddy, and when I need some answer on a simple question - then you tell me to get the fuck away?}
{184}{024}{Either you tell me, or I'm putting you to eternal relaxation!}
{185}{999}{To hell with you then, nervous one. Relax further.}


{190}{}{[he strokes his hair and pulls away a new ampoule of the Drop from his pocket] For fuck's sake... [pops it into his mouth] Okay. In general, I'm working for the Olympus... For my all damn life. I had an assigment to gather some things for them. I even have a list with me [pats his bag]... But they will have to wait. I'm a little tired...}
{191}{020}{Why didn't you tell me this earlier?}


{200}{}{Do I have to answer to someone here? And then, that old Apothecary prick has already convinced himself that I'm a spy, or something worse. And he tells it to everyone. I could care less about this Rainbow... What I'm trying to say is that no one would believe you. Best-case scenario, they tell you... To fuck off, and in... The worst-case...  I'm so sick of it... [looks like the Drop kicks in] This Olympus... can go fuck itself... Let them handle this shit, fucking smart-asses... I'm done... [he drops his head on his arms and stops talking]}
{201}{999}{Ahem... Well, okay, see you around.}


{210}{}{Yeah, I could use some help. I lost my badge somewhere around here. Most likely, it happened when I decided to warm ap on the Arena. A pity - this thing is like a memorabilia for me...}
{211}{022}{And why can't you look for it yourself?}


{220}{}{Because locals don't like me much. Everybody suspects that I'm up to something, morons... If I'd start searching for something, it would bring more questions. And, to be completely honest, I'm too lazy to carry my ass all around the Rainbow. Besides, some little whore promised to come visit me soon... You get it. So, would you help?}
{221}{999}{Okay... Let's see what I can do.}
{222}{999}{Nah, not interested. Try "Lost and Found" box, and I have no time for this.}


{230}{}{[he looks a bit confused] You know... Somehow, I spent all of my cash on local hookers and booze. But I remember the favors! Tell me if you need something. I know a lot of people... So, will you give it to me?}
{231}{999}{Sure, take it. This was an easy job. But there will be time when I'm going to remind you about your words.}
{232}{024}{Are you out of your fucking mind, trash man? Trying to screw me over? I'll shove this badge up your ass! }


{240}{}{[He stands up and straightens his shoulders] Booze, whores, the Drop... and stupid meat, who doesn't know when to shut up. I love this place!}
{241}{998}{You are going to be sent to a local cemetery!}


{2501}{}{[he gets some weapon parts off the table and puts a bottle in their place] Can't complain. The Rainbow is getting pretty good place to have fun, with you leading it. I like it. [he nods to weapon parts] Don't mind this, it's just my habit of keeping things in order. The cost of mistake for a Seeker is very high... }
{251}{999}{Not only for a Seekers, you know. Okay, see you around.}
{2502}{}{[he shoves his bag under a table] Just taking inventory. But everything can happen. Rainbow nowadays is not the most cozy place for an old Seeker like me... And I have a job to do.}
{252}{999}{Well then, good luck to you, Douglas.}