##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Джи
#Краткое описание: Вождь  детей Радуги. Квесты на алкоголь и ограбление караванов
#Дата создания: 13.09.2014
############################## 
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a scrawny black kid.}
{2}{}{He looks at you as if he's still taking options - to attack you, or to run away.}
#
# после знакомства
{3}{}{You see G.}
{4}{}{Leader of juvenile criminals of Rainbow.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[His juvenile antics are strangely combining with the habits of a predator when he starts talking] Who the hell are ye? [he looks around as if checking for a threat] Whaddaya want from G, uncle? I have no time to spare. Hear me?}
{11}{}{Hello, G. I'm }
{12}{013}{. What are you and your friends doing here?}
{13}{}{I'm }
{14}{011}{. I'm here for work. You look like you know the streets. Mind telling me about locals?}
{15}{999}{Get lost, kid! I'm just walking by. }
{16}{999}{Got it. Already leaving.}


{1001}{}{[he hastily hides a toy in a pocket] Whaddaya doing here again? Walking around, getting on my nerves?}
{101}{013}{I want to know more about you and your friends, G.}
{102}{011}{I'm looking for a job. Could you give me directions?}
{103}{022}{It's your lucky day today - the cognac delivery is here!}
{104}{023}{You are too cocky, shorty. I think I need to beat some respect into you.}
{105}{999}{I was just walking around. Bye.}
{1002}{}{Hey, big brother! I-... We were worried about locals making ye bite the dust.}
{106}{012}{You wish. Listen, do you have any more ideas about making money?}
{107}{021}{I want to rob another caravan of these fools from NWO! Are you with me, little brother?}
{108}{999}{It's alright, G. Just decided to visit. Tell me if someone tries to bully you. Bye.}
{1003}{}{Hey, uncle! Come closer. What do ye have for me?}
{109}{013}{Just wanted to talk. For example, to ask something interesting about your friends.}
{1010}{021}{It was a good raid on the caravan. How do you feel about doing it again?}
{1011}{999}{I wanted to say hi. And now I need to go.}
{1004}{}{[you see fear in his eyes, but he gets up and steps forward to you] Look who it is, the meanest uncle on Rainbow! What does he want here? [he blows his nose and wipes his hand onto his torn pants] G doesn't get into your business, so don't get into ours!}
{1012}{024}{Listen up, businessman, you are operating on my turf. Everything around here is my business. So you'd better tell me what you're up to. If I learn about it not from you - you're getting yourself a problem.}
{1013}{025}{Are you guys still raiding the caravans?}
{1014}{026}{You can act cool in front of your friends all day, but don't forget to pay my cut in time.}
{1015}{999}{Don't be nervous, I need nothing from you. Later, G.}
{1005}{}{[G starts running to you, but hastily stops, taking a serious look] Hey, big brother! Now you are REALLY big! I told ye - be closer to G and everything's gonna be alright. No one would oppose us now... Big brother and G is a force to reckon with!}
{1016}{024}{How's it going, G?}
{1017}{025}{You bet. How's the raiding of NWO's caravans? Is it still up?}
{1018}{026}{I've come to collect your generous donation to our common great cause.}
{1019}{999}{Nobody touches my little brothers, while I'm in charge. Was nice seeing you, G, but I've got to go. }
{1006}{}{[looks like most of G's crewmembers are still celebrating the death of Rainbow's owner. G comes to you, friendly waving with an open bottle. You are not quite sure if he recognized you] H-h... Look who's h-here! A drink? No? I'm doing it... [He hastily gulps, but chokes and almost pukes on you] F-fuck... The wrong pipe... }
{1020}{028}{Ahem... Are you doing alright here?}
{1021}{999}{I think it's time for me to go...}
{1007}{}{[G drops a sharpened stick and waves to you] Hey! Come! We are thinking about hunting rats. How are your girls? Why didn't you bring it with you? It's a little dirty here, but... Still, you conked that black asshole nicely, good job!}
{1022}{012}{Do you have any ideas about how to make a quick buck? It's not easy to run a brothel, as it turns out...}
{1023}{021}{Leave small talk for later. And now, let's raid another caravan of these idiots from NWO! Are you with me, little brother?}
{1024}{999}{No one dares to put our folks in shame like that! He died for this... Anyway, I was just checking how are you doing.}
{1025}{999}{Yeah... I'll go now. Happy hunting.}
{1008}{}{[seeing you, he starts to laugh, holding his sunken belly with his skinny hands] The master of every hole in Rainbow is here! Haha! Good one, right? Never gets old! Okay, uncle, don't be mad. We are actually very grateful for kicking this black motherfucker's ass. So, whaddaya got?}
{1026}{013}{I want to learn more about you and your crew.}
{1027}{011}{I need a side job. Know anything?}
{1028}{022}{Bring the glasses! Here's a cognac. Let's drink for my promotion.}
{1029}{023}{You are too cocky, shorty. I think I need to beat some respect into you.}
{1030}{999}{I was just walking by. }
{1009}{}{[you notice that G and his henchmen are wearing some kind of a uniform, made from their ragged clothes, decorated with strange insignias. The scout commander himself is waving at you with his hand-made metal staff] Chief! Nothing of significance has happened during out... Err... Damn! Always forgetting... Oh! Our shift! I mean, everything's quiet. The borders are being supervised, uncle!}
{1031}{999}{[hand them fifty batteries] Here's a payment for a good job. Try to not spend it all at once. See you, G.}
{1032}{999}{Thank you for your service. Keep it going. If there's a problem - report to me immediately.}
{1033}{999}{If you miss an invasion, I will rip your head off before I die! That's it. At ease, little warriors.}
{10010}{}{[you notice that G and his henchmen are wearing some kind of a uniform, made from their ragged clothes, decorated with strange insignias. The scout commander himself is waving at you with his hand-made metal staff] Chief! Nothing of significance has happened during out... Err... Damn! Always forgetting... Oh! Our shift! I mean, everything's quiet. The borders are being supervised, big brother!}
{1034}{999}{[hand them fifty batteries] Here's a payment for a good job. Try to not spend it all at once. See you, little brother.}
{1035}{999}{Great job, brother! Keep it going.}


{110}{}{[he is scratching his head with both hands, driving away small insects] Don't stare at me like this! I'm trying to think here. Hmm... Do you want to work for me?}
{114}{}{Nah, we don't do any "jobs" - we are watchers now... You get it, keeping the Rainbow's borders under supervision. No time for petty things.}
{115}{}{Nah, we don't do any "jobs" now - still need to rest from the last time, to lick our wounds. I'm thinking about early retirement... Ha, just kidding! Still, we really need to rest, my fellas are tired.}
{111}{023}{Hah! Seriously, snot? And what would you pay me with? Toys?}
{112}{012}{What are you offering?}
{113}{999}{No, not interested. And I need to go.}
{116}{999}{I see, I'll come later.}


{1201}{}{There is something, alright. Would be enough for all of us. I overheard this near the bar, cleaning pockets of one drunk... There are some regular caravans from NWO coming around. All we need is to raid one. The security must be pretty weak, or so they say. Well? Are you in? You look like an experienced fella, we could use your help.}
{121}{023}{I think you are capable of raiding only local drunks! What caravan, black boy? Get out of here, don't buzz me!}
{122}{018}{I have no doubts about you, but it sounds risky... Did you think this through?}
{123}{017}{It suits me. Have you picked a place for an ambush?}
{124}{999}{I'll pass. The info is unverified, details are unknown... I don't do work this way. See you!}
{1202}{}{[he winks at you with a mysterious look] Sure, brother! I overheard something recently while cleaning pockets of one drunk white boy... About the caravans from NWO. Guards are weak, much stuff to take... Get it? A good idea, don't you think? [looks at you, waiting for your approval]}
{125}{018}{Listen, G... It's cool and all, but do you understand the consequences?}
{126}{017}{Great, little brother! Where are we going to set up our ambush? We need a good place...}
{127}{999}{Let's talk about it later. I need to go now.}


{130}{}{[he puts arms to the sides, pulling out his hollow chest] Hey, you! Watch your mouth! [his voice gets louder] They are not my friends! They are my BROTHERS! You'll see, we are going to take over here, just wait. What? The Hog is a tough guy, of course, but the Drop is doing him no good. He can't even sleep, do you know that? And about the rest... That freaking pimp Shepherd... [he blows his nose] He is a disgrace to all black brothers! Why does the Hog care about him? We are much better to deal with - we know everything around the Rainbow, every hole in the fence, every little path! And we have each other's backs. All I need is a little more people, and... [he looks at you, thinking]}
{131}{014}{Have something to add, G?}


{1401}{}{[he shakes head] Nah. Nothing.}
{141}{012}{Maybe you can tell me then - is there some job for me around here?}
{142}{999}{See you around then.}
{1402}{}{Uh... I think we could accept you into our gang... If you can prove that you are useful.}
{143}{015}{Really? I'm flattered. And what do you mean by "useful", I wonder?}
{144}{012}{I think you guys are too cool for me. But I'll think about your proposal. Say - is there some job for me around here?}
{145}{999}{No way. You hear all sorts of things these days... I'll come by later.}


{150}{}{Nothing special! Just bring us some cognac... Uh... Five bottles will be enough. You can handle it, right? You look capable.}
{151}{999}{That's it? Hmm... You'll never know what could come in handy later. I'll be back with the stuff.}
{152}{016}{Aren't you a little... underage, to get drunk? Sometimes the life is shitty, but this is definitely a bad step. Remember what you said about the Hog? The booze is just the beginning.}
{153}{999}{Yeah, to fetch some cognac to some snots... No thank you. Not today.}


{160}{}{[he chuckles] Don't lecture me, uncle. I won't do drugs, don't you worry. And the booze is okay, I'll make it. Why should I care what happens in the next twenty years, while I can die at any moment from some random shit? I should have fun! Now, at this moment! And you are spoiling my fun... [he sighs] I know how to live my life without your advice. So? Would you get us some booze? If not, we can do it ourselves.}
{161}{999}{You're right. You'll understand... Eventually. I'll bring you your cognac. Wait.}
{162}{999}{No. I won't participate in making your life more miserable.}


{170}{}{[he starts to draw something on the ground with a stick, marking points with little stones] Here's the plan... That's us, this is them... And this is- fuck! Who took my stones? This is the place where we can attack them. If something goes sideways, we can easily get away through here. If we go now, we should make it to the nearest caravan.}
{171}{999}{You are such a mastermind... Okay, we'll figure out the rest on the spot. Let's move.}
{172}{999}{No, I won't go now. If I change my mind, I'll find you.}


{180}{}{What's there that makes you doubt? I'm telling you - the security is shit, the stuff is good! Easy-peasy...}
{181}{019}{Security may be shit, but believe me, when you take a bullet it doesn't matter. Be honest, you are not experienced enough for this kind of stuff. Did you consider alternatives?}
{182}{017}{Actually, you are mostly right... Let's do this!}
{183}{999}{I won't try to change your mind. I'll come by later.}


{190}{}{What? Alter... You mean, to do something else? What exactly? The Hog's got everything under his boot...}
{191}{020}{For example, you could guard the Rainbow's borders. It's obvious that this place is not very protected from sudden invasions. The Hog obviously gets it, so if he is not doing something about it now, then he is short on people. I can talk about it with him. Make you equal partners in this matter. What do you think? }
{192}{017}{Uh... Yes, you're right. Robbing caravans is more fun anyway. What was your plan?}
{193}{999}{I'll get back when I think of something.}


{200}{}{Ahem... We need to discuss it... [he walks to the side, gathering his friends. They talk for some time, waving hands and shouting. Then G returns to you. He looks pleased] We're in. You can talk to the Hog. }
{201}{999}{Great! You're going to grow up into a good leader. I'll go resolve this matter. See you!}

{202}{}{I had a talk with the Hog about guarding the Rainbow - and he is in. He needs your services.}
{203}{}{Yeah! YEAH! The G's gang and the Hog are PARTNERS! How's that sound? We're going to be in charge here! Gonna do things! You are so helpful, man, we will not let you down! Thanks!}


{210}{}{I knew it! I knew I wasn't mistaken in you. We are of the same kind! Let's do this again, sure, we are waiting only for you to get ready!}
{211}{999}{Let's make these bitches suffer! Move out!}
{212}{999}{Good! Only wait a minute, I need to do something first.}


{220}{}{[You are getting drunk with your new brothers and sisters all night. In the morning, G declares you a member of the gang, in front of everyone who's still standing and not puking in the nearest ruins. Life feels great!]}
{221}{999}{[Go to sleep with a feeling of fulfillment]}


{230}{}{[he jumps away from you, pulling out something from under his rags] Okay, you tall bitch, now we are going to rip you up! Come on, guys!}
{231}{998}{That isn't going to be easy for me - I can die from laughter. Fighters, my ass...}


{2401}{}{[G silently stares at you. Then sighs and nods] Ye win, uncle... What can I say? We are quiet, we don't need problems with you. Besides, we have our own thing - we rob caravans from NWO. The security is shit, the stuff is good...}
{241}{027}{Caravans? Are you out of your mind? Who is going to deal with NWO if they decide to attack us? }
{242}{999}{Is that so? Sounds interesting... I'll come to you later, to talk details.}
{2402}{}{The life's good, brother! Who can oppose us with you by our side? Don't worry, we aren't shitting on your territory. We raid NWO's caravans now - the security is shit, the stuff is good... }
{243}{027}{Caravans? You know, brother, it can actually cause problems. To me and you. How many of your people have you already lost?}
{244}{999}{Is that so, brother? Sounds interesting... I'll come to you later, to talk details.}


{2501}{}{So? What do ye mean?}
{251}{027}{Listen here. I don't care how it was before. I can have problems because of this. And you too. Get it?}
{252}{999}{Nothing for now. But we haven't finished.}
{2502}{}{[he grins] We're not giving this business to anyone!}
{253}{027}{Listen, brother, I used to like this shit too. But now it can cause us problems. How many of your people have you already lost?}
{254}{999}{I have no time for this now, but I'll come to you later.}


{260}{}{[pouting, he pushes a heavy boulder, pulling out a wrapped piece of cloth laying under it] Here's everything. Take it, will you...}
{261}{999}{You could pick a better place to make a stash. See you.}


{2701}{}{What else should we do? Eat shit and die? It is you who put all Rainbow under his belt... We are literally out of options!}
{271}{029}{I'm not telling you to stop doing it. But if I have troubles, then you are paying me to compensate them. A hundred each month.}
{272}{030}{What if you'll work for me? I need scouts to watch over Rainbow's perimeter. We have many enemies, you know... For this, you get free supplies and I'm going to ignore little things like empty pockets of locals and town guests. What do you say?}
{273}{999}{I need to think. I'll come by later.}
{2702}{}{[G gets somber] Five... But what else should we do? Eat shit and die? Don't take me wrong, I get it - you are worried about us. And I appreciate it! Want me to pay you a cut for this? A hundred, for our common cause?}
{274}{029}{That's actually a very good idea. Deal, brother. I will be visiting you once a month.}
{275}{030}{I have a better proposal - let's work together. I need scouts to watch over Rainbow's perimeter. We have many enemies, you know... For this, you get free supplies and I'm going to ignore little things like empty pockets of locals and town guests. What do you say?}
{276}{999}{Sounds difficult... I'll think about it, and you take care of yourselves. Try not to get yourself killed.}

{280}{}{Y-yeh, ev-vrything'z great...  [for a moment, his sight gets sober] Just let us drink up this, take a nap and we'll go cut everyone's throat... Who can stop us? [he suddenly pukes, eyes become murky again] The R-rainbuw'z ours... }
{281}{999}{No use in talking to you now. Get yourself some sleep and we'll talk. }
{282}{999}{Ha! Quite a sight - midgets on a path to war! I'm definitely going to see it. Okay, later. Get yourself ready, warrior.}

{2901}{}{Uh, well, yes... You won't leave me alone anyway. All you white boys are the same...}
{291}{999}{Believe me, you are lucky to have me. See you next month, raider.}
{2902}{}{Now we're partners! G's cool! I'll go tell everyone. See ye.}
{292}{999}{Pleasure doing business with you, brother. Bye.}

{300}{}{Ahem... We need to discuss it... [he walks to the side, gathering his friends. They talk for some time, waving hands and shouting. Then G returns to you. He looks pleased] We're in! We won't let you down!}
{301}{999}{You should be afraid of what happens if you will.}
{302}{999}{I have no doubts, brother!}
{303}{999}{Great! You're going to grow up into a good leader. See you!}

{500}{}{Phew, this wasn't as easy as I thought. But we still did it, right? Let's grab the loot and get back to base.}
{501}{}{Well, it was easier this time, although not without damages... Okay, brothers, get the stuff and get out!}
{502}{}{That's it, this one is last for now. We need to lay low and lick wounds. Take the shit and go, brothers!}
{503}{999}{[end]}

{505}{}{From robbing the caravan, you get }
{506}{}{ batteries of profits! And bad karma.}