##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Кабан
#Краткое описание: Авторитетный любитель Капли. Квесты: переговоры с Псами, стать вожаком Радуги.
#Дата создания: 05.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a muscular raider.}
{2}{}{He seems relaxed - but you still can't shake this uncomfortable feeling...}
#
# после знакомства
{3}{}{You see the Hog.}
{4}{}{Addicted to the Drop, one and only leader of the Rainbow raiders.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[his absent gaze of drug addict contrasts remarkably with bulging muscles under his tattoed skin. Even calm, he radiates a clear threat] Fresh meat on devil's kitchen... Everyone wants to get on the Hog's table... [with a great effort, he focuses his eyes on you] What do you want?}
{11}{024}{Just looking around. Nice place you have here.}
{12}{016}{I'm pretty good at solving problems for a price. Interested?}
{13}{025}{Do you know about G? He and his crew are operating on your turf.}
{14}{999}{Looks like the time is not right. I'll come by later.}


{1001}{}{[In his eyes you see your own body, hanging by the fires of hell] If this bitch doesn't disappear, the Hog will rip both of her legs, and beat her with them to death.}
{101}{023}{Did you squeal something, Drop-head? It is I who will rip you up!}
{102}{999}{Alright, alright, I'm leaving...}
{1002}{}{[his sight is tense at first, but then he recognizes you] Again, you come... Tread lightly, don't fall off the Rainbow...}
{103}{024}{Just looking around. Nice place you have here.}
{104}{016}{I'm pretty good at solving problems for a price. Interested?}
{105}{025}{I stumbled upon a gang of kids, operating on your territory...}
{106}{020}{Negotiations with Jackals are completed.}
{1003}{}{[He looks at you strangely. You prefer to interpret his gaze as friendly] Here comes our negotiator... What brings you to me, smooth-talker?}
{107}{025}{Another matter to talk about. Lately, there's a company of little hustlers around the Rainbow, not very tall, but with a temper...}
{108}{024}{I'm looking around. Nice place you have here.}
{109}{999}{Just checking on you. And I see that everything's good. See you then.}
{1004}{}{[It's like he's waiting for an attack at any moment - his eyes are all over the place, the whole body is tense. Seeing you, he pops another dose of the Drop, throws an empty ampoule on the floor, and squishes it with his heel. Another ampoule waits for its turn] Either you brought me a handful of batteries, or your whores have problems. What option is the best one for you, what do you think?}
{1010}{028}{It's about the payment...}
{1011}{016}{I have everything under control on my territory. What about you? Do you need help?}
{1012}{025}{I stumbled upon a gang of kids, operating on your territory...}
{1013}{999}{I'm good. Just walking by. }
{1005}{}{[you get chills from the Hog's unusually calm voice] Looks like you think that local rules are not for you. Where's my money, you whore herder? And you pay a half extra - for troubles. }
{1014}{999}{Of course, here's the full amount! My apologies, it won't happen again.}
{1015}{023}{I'd better throw some punches in this pig snout of yours! You get dicks, not batteries!}
{1016}{999}{I'll get it! Everything, down to the last battery! But a little later.}
{1006}{}{[the Hog looks surprised to see you] I thought that you were smart enough to leave the Radius completely... [the ampoule in his hand crunches into mush when he clenches fists] You has been fucking me up for three fucking months! I've seen a lot of different crazy fuckers, but you - you have outdone them all! That's okay, I will take my cut now - together with your ripped intestines!}
{1017}{998}{I'm so good at picking the right moment to come...}
{1018}{998}{You get squat, bitch! Fucking you up? I haven't even started! Let's see how it's done!}


{110}{}{[With a swift motion, he pours the content of another ampoule down his throat] Looks like you and Shepherd had some problem. You have two minutes to explain yourself. [his breathing gets rapid, fists clenching] And choose words carefully, because the ice you are walking on is very fucking thin.}
{111}{012}{Well, your brown fella turned out to be too fickle for a serious fight.}
{112}{012}{There was a minor misunderstanding, which, I'm sure, won't get in the way of our good relationship.}
{113}{015}{It was all an accident, I have nothing to do with it! Seriously!}


{1202}{}{[he menacingly approaches you] Do you realize that you murdered my brother because of some cheap whore?}
{123}{023}{Are you going to organize a thorough review meet-up when every petty raider of yours is killed? It's entirely his fault - he tried to act cool while couldn't even take a punch...}
{124}{013}{There's a bright side to it - I have identified and eliminated the weak link on the Rainbow, which could lead to many of your problems.}


{130}{}{[his facial expression changes, although it is barely noticeable] What are you now trying to say to me? }
{131}{014}{Let's be objective - Shepherd couldn't handle his duties of brothel manager. Damn, he couldn't even deal with one whore! He ended up running and chasing her around the whole Rainbow. And he wasn't much of a challenge to me, by the way... How do you think it makes you look?}
{132}{023}{I mean, your Shepherd was a wussie. All he was suited for is cleaning the cesspools...}
{133}{022}{Erm... I won, he lost, what else to say? He couldn't take the blow of fate...}


{140}{}{[the Hog freezes, then stretches his thin lips in a smile] You may be right somehow... [he stops, then continues] That's how it is - I took a loss. Because of you. And you're gonna make it up to me. You take Shepherd's place. Your security payment comes once a month. Three hundred. The rest you'll figure out. And don't you dare to screw this up...}
{141}{999}{Good position, career prospects... Why not? I agree.}
{142}{023}{Whaaat? Who do you think I am? A half-assed pimp? Deal with your sluts yourself, asshole.}


{150}{}{[he stares at you, not even blinking... And suddenly starts to laugh] Hahahah!! I even fell for it for a moment! Okay, tough guy, if you are so convincing... And strong enough to make Shepherd take a dirt nap... You belong to the brothel. Don't twitch. What I mean is you take Shepherd's place. Your security payment comes once a month. Three hundred. That's it. Go. You'll figure out the rest. It's in your own interests. "I have nothing to do with it"... Fucking hell... [he sinks into his narcotic thoughts, smiling]}
{151}{999}{Uh... Thanks... I guess...}

{1601}{}{[You patiently wait for the Hog to pop another dose of the Drop] Argh... Yes, slick one, you can be of some help...}
{161}{017}{I'm listening.}
{1602}{}{[You patiently wait for the Hog to pop another dose of the Drop] Argh... I don't need you... Go...}
{162}{999}{Damn, why didn't you say so earlier...}


{170}{}{There's one crazed freak... Loudmouth. He's leading the Jackals... I used to run with him and his pack. [he shows you his crippled hand] See? This bitch took off my finger... But I'm not mad at him. I want to make peace.}
{171}{018}{And you need a middleman for that?}


{180}{}{Yes. Now it's quiet - they sell us weapons, we supply them with Drop... But everything can go to shits at any moment. [he shakes head] Fucking asshole... Never learns... You... Convince him. No one benefits from war...}
{181}{019}{Ha! You got the right man for the job, the diplomacy is what I do! Will deliver the result, just wait.}
{182}{999}{No, thank you. I don't want to go near such crazy people. All the best, bye!}


{190}{}{[he closes his eyes, waiting for a drug to kick in] Good. Go and do it... The reward... Will please you... That's it, go...}
{191}{999}{Got it, chief. Wait for the news.}


{200}{}{[Slowly shakes his head to the rhythm of your words] What did Loudmouth say?}
{201}{021}{Well, swearing and cheap bluster aside, the message is pretty short and clear - they won't attack the Rainbow, while your business relations are in the interest of both sides. As a gesture of goodwill, they even ready to give you a discount on their next batch of weapons.}


{210}{}{[he grins] You're good... If you managed to shake even this guy's stuck-up brain... [he waves to one of his raiders, who leaves the room and gets back carrying a rocket launcher] Here. Take this. Don't use it on the Rainbow though... And one more thing - if you want to fly, you can... Expect a discount from... Apothecary... [his eyes become unfocused and murky, speech is less cohesive. Looks like the conversation is over]}
{211}{999}{Christmas came earlier this year...}


{220}{}{[with an unusual speed, Hog rushes to you - and a moment later his huge fist smashes into your ribs. It's a miracle your insides didn't fly out of your throat] And you can take a punch, shithead?! Get your ass out of here!}
{221}{998}{Oh you asshole! I'll pull your innards out for this! Die, bitch! }
{222}{999}{It hurts... Okay, I'm leaving. But we haven't finished...}


{230}{}{[the Hog calmly nods. But in his cleared eyes you see death] I'm going to squeeze every last drop of blood out of you - and put it in my morning dose...}
{231}{998}{Let's get down to business, you piggy head! }
{232}{998}{That didn't sound very friendly...}


{240}{}{Yes... The best place in Radius... Girls, booze... And the Drop. [he takes out an ampoule and wistfully gazes at it] This is what started it all... And this is what will be the end... Ask, if you need something... But not... Me... [he closes eyes, delving deeply into his intoxicated dreams]}
{241}{010}{I didn't even think about bothering such a respectable man with stupid questions... Hey! Do you hear me?}
{242}{999}{[leave quietly]}


{250}{}{[he slowly turns his head. Tattoed spider on his neck moves his paws. Looks creepy.] Yes... I heard. For now, they are just making noise... But we were like this once too. All it takes is to get the taste of blood - and you will never be able to stop... [he smiles to his thoughts] Why did you mention them?}
{251}{026}{I see an opportunity to put their skills to good use. To the Rainbow's benefit.}
{252}{999}{Just... Saying. Well, I won't be bothering you anymore.}


{260}{}{How is that, may I ask? All I can think of is to boil them into a stew in a big pot and feed my guys with it... Haha... A good idea, actually...}
{261}{027}{Where's the rationality in that? You are low on people. And it's obvious that G and his fellas are not great at fights - yet - but you can use them as scouts! Put them around the Rainbow, so they could monitor the situation everywhere. There are threats in Radius except for the Jackals, you know... Did I mention that you can pay them less than grown-ups?}
{262}{999}{Uhh... I didn't mean this... Ahem... I better go think about it. Return with something better...}


{270}{}{[he nods, twirling the ampoule with his intact fingers] Yes... This will do. Tell them that I agree... We lose nothing. But if they screw up - the stew is still an option...}
{271}{999}{I hope it never comes to that. See you around, Hog.}


{280}{}{What exactly didn't you understand? A client pays and fucks whores, you maintain order. The rest is my business. [he pops another ampoule] So hand over the batteries and leave, don't ruin this for me...}
{281}{999}{Sure. Here's for this month. See you around.}
{282}{029}{What? Do you always collect twice, or it's just me?}
{283}{030}{You know, I have a difficult situation - it turned out to be not so easy...}


{290}{}{[his voice starts to growl] What are you fucking saying?}
{291}{031}{I paid you recently! You were just popping another dose...}
{292}{999}{No, nothing. Here's the cut. Sorry.}
{293}{030}{You know, I have trouble getting the necessary amount.}


{300}{}{That's your problem. Do whatever you want. Use your ass to earn it, I don't fucking care.}
{301}{999}{Damn... I have to think of something...}


{310}{}{[He wrinkles his forehead, trying to remember something. His muscles start to twitch uncontrollably, which makes tattoos of the skeletons, chimeras, and dog heads move in a wild dance. Then his sight clears] Fuck, you are right!... Okay, don't mind me, everything can happen. That's it, go, I need to rest.}
{311}{999}{Nice.}