##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Кент
#Краткое описание: Правая рука Кабана. Квест на муравьиные брюшки и возможный временный глава Радуги
#Дата создания: 09.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a raider who looks... Stylish?}
{2}{}{Despite his appearance, he looks rather serious.}
#
# после знакомства
{3}{}{You see Mate.}
{4}{}{A gloomy Hog's assistant who manages dealing with locals.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[he somehow managed to get a fancy short haircut, and even to shave. But his boots are stained with mud and dry blood, and the color of his hip jacket is hard to define because of thick layer of dust] Who are you, and what do you want from me? }
{11}{}{I'm }
{12}{011}{. And you are?...}
{13}{}{I'm just looking around the place. I'm - }
{14}{011}{. Heard the name?}

{1001}{}{[he indifferently nods] Here to talk business? Or just to get on my nerves?}
{101}{012}{If you have something to tell - I'm ready to listen.}
{102}{015}{I'm always looking to put my skills to use. But first, can you help with the directions around here?}
{103}{014}{The insects are having a bad day today. Bellies are delivered.}
{104}{999}{Just walking around. Good luck!}
{1002}{}{[he carelessly touches his hair with two fingers] Hello. What brings you?}
{105}{015}{Can you tell me who's doing what around here?}
{106}{999}{To you too. I wanted to check upon you. Be well.}
{1003}{}{[Mate looks a little battered. His jacket, covered with fresh bloodstains, is torn in some places, forehead is covered by a dirty rug] Look who we have here... What do you need?}
{107}{031}{How's life, Mate?}
{108}{999}{Just wanted to pay my respects. And I'm already leaving.}

{110}{}{[He wrinkles and raises his jacket's collar] I'm Mate. Remember this name. I don't give a fuck about yours. Again - who are you, and what do you want from me?}
{111}{012}{Let's get straight to business - do you have a job for me?}
{114}{011a}{I was told to ask around for "Antiradine". Do you know where I can get it?}
{112}{015}{I would be grateful if you told me about who's here in charge. Who should I deal with?}
{113}{999}{Look at how serious we are. Okay, I'd better go.}

{115}{}{The Rainbow is famous for its chemical thingies, am I right? [he gives you a crooked grin, squinting his eyes] You can get it right here - go ask Apothecary. Of course, I could supply you with one, but only in exchange for a certain job.}
{116}{012}{No problem, I'm ready. What's the job?}


{1201}{}{Nice approach. I don't like small talk too. So, it's something I don't have time to deal with... Lately.}
{121}{013}{Go on.}
{1202}{}{[he sarcastically smiles] The job I have is definitely not for you. You are still pretty green for it. I wouldn't trust you even with polishing my shoes. Grow up a little, then we'll talk.}
{122}{015}{Your loss... Can you at least point me out on what's what here? Maybe someone else could use my services.}
{123}{024}{What? I'm gonna polish MY shoes now, with your flashy haircut, bitch!}
{124}{999}{Suit yourself. Okay, nothing for me here. I'm going.}


{130}{}{There's a farm to the west of Rainbow, where we grow fire ants. You should go there and get eight nice and fat ant bellies. Bring them to the Apothecary in the bar, I'll inform him about you. The job is not easy, and - just because you would ask - there was a couple of guys doing this before you. But some time ago they screwed up the delivery and celebrated it with a bottle of cognac, stolen from Apothecary. The Hog fucked me up for this really good, so I ended up drowning one of these rats in the toilet, making another to run circles with a metal pole in his ass. Do you get where I'm going with this?}
{131}{999}{A great way of dealing with things, I approve that. Okay, understood, will do.}
{132}{020}{Why do you need these bellies?}
{133}{999}{Won't be any problems with me. I'm on it already.}
{134}{999}{No, this job is definitely not for my skills. See you.}


{140}{}{[he chuckles] You're cool, no comments. No, seriously - good job. In these fucking times it's a trouble to find someone even for this bullshit, who wouldn't screw everything up... Here, you earned it. [he gives you a fistful of batteries and a syringe with someithing green inside] Did you want something else?}
{141}{015}{Can you enlighten me about what is what around here?}
{142}{999}{No, I was already leaving.}


{150}{}{Okay, ask, but fast. And talk to people around here yourself.}
{151}{025}{Who is in charge here?}
{152}{016}{I prefer dealing with problems by breaking jaws. Could someone here be interested in this?}
{153}{017}{Is there a place where you can have fun with a girl - or two?}
{154}{018}{I'm interested in benefits of local chemical industry. There must be someone here who is doing it, right?}
{155}{019}{What about you, Mate? }
{156}{999}{You know, I don't actually need anything. See you!}


{160}{}{[he sighs] Another bully... You have a straight path to the Arena - to the east from center. Sometimes I let off some steam there myself. Or you can try your luck in the Shepherd's brothel - looks like his black ass is not capable of keeping place in order anymore...}
{161}{015}{Okay, got it. Another question, if you don't mind.}
{162}{999}{Thanks, that's enough for me. See you.}


{170}{}{Do I look like a fucking pimp to you? Go to Shepherd's whorehouse, near the factory. And don't ask ME such questions, I'm here not for your amusement.}
{171}{015}{Got it. Can you answer something else?}
{172}{999}{Okay, okay! Just keeping the conversation going. I'm leaving now.}


{180}{}{Are you a junkie? Right, I still don't care. Anyway, Apothecary can help you. You can find him at his bar, inside the factory. He will supply you a test batch of our shit at any moment, if you both agree on a price. And bring him a bottle of cognac, or two. He likes this stuff very much... Probably, too much.}
{181}{015}{Thanks for the info. What about the others?}
{182}{999}{I think I'll go to him right now. Thanks for the help.}


{190}{}{ What do you mean? What about me? }
{191}{023}{Don't take me wrong, but your look is quite unusual - especially for this place. }
{192}{022}{What do you do here?}
{193}{015}{Nothing, actually. Tell me about the others.}
{194}{999}{Hey, I was just asking. I won't be bugging you, I better go.}


{200}{}{We use... Fuck me, how was it called... A pheromone. Yeah, exactly, an ant pheromone. We need it to make Drop. Got it?}
{201}{021}{Fully. A question though - isn't it, like, a secret information?}
{202}{999}{Sure. I'll take the job. Wait for the news.}
{203}{999}{Uh-huh. Nah, do it yourself. And I'm going.}


{210}{}{[he snaps a beautiful silver lighter and lights up a cigarette] You think? Everyone who has a brain knows about the farm, and what we need it for. So? What are you going to do with this "secret information"? To synthesize the Drop is not like shooting bottles, smart-ass. Also, do you see any competitors? Take a guess, where they are.}
{211}{999}{Uh... Okay, I'll take the job. See you later.}
{212}{999}{I was just asking. Nah, I'll pass. Will try to find another job.}


{220}{}{I'm helping Hog to keep locals and passersby in line. We need to maintain order here. I'm also responsible for recruiting. Do you think I would spend my time on you otherwise? Anyway, act nice and easy, and we won't have any problems.}
{221}{023}{No problems at all. Pardon my curiosity, but where'd you get that style? I mean hair and everything.}
{222}{015}{Understood. can you tell me something about the others?}
{223}{999}{Thanks for the info. See you around.}


{230}{}{[he looks through you] The style... It's a thing that distinguishes a serious man from a cheap punk. I wish it was like the old days... When people were good at solving problems as much as they were in looking good. [he snaps fingers] Just like that - and your enemies are dancing with the devil. Man...}
{231}{026}{And now it's different, is that what you mean? Tell me, is everything okay in the kingdom of Rainbow?}
{232}{015}{I see... Let's get back to the questions about the Rainbow's authorities.}


{240}{}Aren't you a cheap fuck? [he rolls his sleeves] Try to repeat that while spitting blood!}
{241}{998}{You know, to hell with talking! Let the dogs out!}
{242}{998}{I think I talk too much...}


{250}{}{For now, the Hog is holding everyone here by the balls. He doesn't get involved in the matters of management, but everyone have to pay him his cut. For protection. You can find him near the barracks, hard to miss. And watch your mouth around him - he isn't quite himself lately... Last week, he ripped some bugging vagrant's jaw off almost for nothing. Fucking Drop... That guy looked somewhat like you, by the way.}
{251}{015}{You just made me feel better. Let's talk about other colleagues of yours.}
{252}{999}{Great. I'd better go and think about it.}


{2601}{}{[he gets noticeably more glum] Everything's alright... For now. Aside from the fact that all could go to shit in any moment... I tried to reason with the Hog, but he prefers to listen that black asshole, Shepherd. Got himself a favorite... But if you need to deal with something, it's always Mate - do this, do that. I tried to talk to Apothecary too, but he doesn't care about anything, except cognac... And the worst part is that it's becoming noticeable to others - we are getting weak. Jackals, for example, are just waiting for the right moment to bite our ass... Wait, why do you care?}
{261}{027}{The fish rots from the head, as they say. Know what I mean?}
{262}{024}{Ha! Did you try to get yourself a pair of balls? You should deal with it, like you always do. Not whine, like a dead-ass ghoul...}
{263}{999}{Sad story... You have your problems. I won't get in your way.}
{2602}{}{It doesn't concern you. Understood? Now, get lost.}
{264}{999}{So edgy. Okay, see you around.}


{272}{}{[he looks around] What are you talking about?}
{270}{028}{The Hog is to blame for everything that's happening. Maybe if someone more reasonable would have taken his place...}
{271}{999}{Nothing. And I've got to go.}


{285}{}{[he nervously licks his lips] Yeah? And what would be then?}
{280}{029}{Listen to me, it can't be worse that this. Look at the facts - people in charge of Rainbow are clearly failing their duties. Except you. Shepherd's obsessed with profit, Apothicary - with booze. You can't trust people with such weaknesses! Hog doesn't see it, or doesn't want to see. And this means that his time is out. When the Jackals come, who can stop them, if not you?}
{281}{029}{You are sitting on a gold mine! So many people are addicted to the Drop... Damn, it hurts to look at you not using such a powerful leverage on the Radius. You need to increase the production, supply more product. You can become much more rich and influential, than the Hog. I could even consult you in the financial matters, for a reasonable percent.}
{282}{029}{The Hog shows serious signs of nervous system disorder, which can become terminal at any time. Believe my experience, I know what I'm saying. How long will he last? Of course, you can wait for him to go nuts and unable to lead, but wouldn't it be too late to take the wheel then?}
{283}{024}{Really? Are you really that stupid, or just pretending? Your Hog should be put down!}
{284}{999}{Then... Let's talk more about it later, okay?}


{290}{}{[Mate stares at his boots for some time] I thought about it... Fuck. Of course, you are right... But how do I arrange this...  }
{291}{030}{Get the right guys, lure him somewhere quiet... Should I really explain this to you? To YOU? Don't bullshit me. You know it's the only way to Rainbow's salvation.}
{292}{024}{Not again! Do you suggest ME to do it? Why would I need you then, asshole?}


{300}{}{Let's do this. I won't waste any more time. I'll see you when I deal with Him. [he leaves]}
{301}{999}{Good luck, Mate. You're going to need it.}


{310}{}{[he nervously spits] I'll tell you, how's life! The Rainbow can explode at any moment! As it turns out, everyone not only were afraid of our tusky boss - they respected him too. I'm holding the situation under control for now, but I'm low on people...}
{311}{032}{What about the others? How are they handling it?}
{312}{999}{Who said it would be easy? It's okay, to begin anew is always hard. I'm sure you can deal with it. You always do. Good luck!}


{3201}{}{You would know. Shepherd recently got all the shit beaten out of him by some passersby... At least one good thing in a current sutiation. [he grimly scoffs] Apothecary spends all his time at the bottom of a bottle, but I can feel it - he is planning something, old fuck... Only Arena Master is supporting me. My old pal and reliable man. The Drop profits are getting lower, because of the amount of production... But I can't afford to bother myself with internal struggles. I need to take care of the outside threats. When we were Jackals, we put our foes on a stakes... Maybe we should start doing it again.}
{321}{999}{Tough times - tough decisions. I hope you will handle the situation. See you around.}
{3202}{}{You would know. Good thing that you murdered the Shepherd. He would be a problem now if you didn't... [he grimly scoffs] Apothecary spends all his time at the bottom of a bottle, but I can feel it - he is planning something, old fuck... Only Arena Master is supporting me. My old pal and reliable man. The Drop profits are getting lower, because of the amount of production... But I don't have time for this now. I need to take care of the outside threats. When we were Jackals, we put our foes on a stakes... Maybe we should start doing it again.}
{322}{999}{Tough times - tough decisions. I hope you will handle the situation. See you around.}
{3203}{}{You would know. Shepherd recently got all the shit beaten out of him by some passersby...  At least one good thing in a current sutiation. [he grimly scoffs] Apothecary spends all his time at the bottom of a bottle, but I can feel it - he is planning something, old fuck... Only Arena Master is supporting me. My old pal and reliable man. Still, we are making it, thanks to the Drop... But I can't afford to bother myself with internal struggles. I need to take care of the outside threats. When we were Jackals, we put our foes on a stakes... Maybe we should start doing it again.}
{323}{999}{Tough times - tough decisions. I hope you will handle the situation. See you around.}
{3204}{}{You would know. Shepherd recently got all the shit beaten out of him by some passersby...  At least one good thing in a current sutiation. [he grimly scoffs] Apothecary spends all his time at the bottom of a bottle, but I can feel it - he is planning something, old fuck... Only Arena Master is supporting me. My old pal and reliable man. Still, we are making it, thanks to the Drop... But I can't afford to bother myself with internal struggles. I need to take care of the outside threats. When we were Jackals, we put our foes on a stakes... Maybe we should start doing it again.}
{324}{999}{Tough times - tough decisions. I hope you will handle the situation. See you around.}