##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Apothecary
#Краткое описание: Хозяин бара Радуги. Выдает квест на Дугласа. Через него ГГ становится главой Радуги
#Дата создания: 07.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a shifty fella.}
{2}{}{He wipes glasses and looks around.}
#
# после знакомства
{3}{}{You see Apothecary.}
{4}{}{The owner or Rainbow's bar.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[The fumes of alcohol around him are so strong that could knock a Lavash down, but his faded eyes are looking at you quite soberly. You also notice that he is not as old as he looks.] Booze, drugs, and our star attraction - the Drop! If Apothecary doesn't have it, then no one has. So, what is it you like?}
{11}{011}{I'm }
{12}{011}{, I'm just looking around.}

{13}{}{Do you know something about the Renaissance?}


{1001}{}{[he nods] You know my rules. Business only.}
{101}{022}{That's exactly why I'm here. Didn't Mate tell you anything?}
{102}{014}{About Douglas...}
{103}{018}{By the way, about business - care to tell me about how you settled up here? About how it all started?}
{104}{Бартер}{I wanted to look at your assortment.}
{105}{023}{You kind of recently expressed your dissatisfaction with the current state of affairs around here...}
{106}{999}{Okay then, see you later.}
{1002}{}{[swiftly pours cognac] How about a little shot to celebrate our meeting?}
{107}{Бартер}{What happened to business? I'd like to buy something from you.}
{108}{018}{Care to tell me about how it all started here?}
{109}{023}{I'll keep you company when business on Raibow gets rolling. I was quite impressed by your story, but the old days won't come back by themselves, you know what I mean?}
{1010}{999}{Maybe later. Take care, Apothecary.}
{1003}{}{[Looks like he's strongly determined to break his own record for short-term cognac absorption. But for now he is able to stand straight and put words into sentences] What? Did you come to drink for the Hog? I bet he's boiling in a pot filled with Drop... }
{1011}{014}{Are you still interested in what's the deal with Douglas?}
{1012}{024}{The King is dead, long live the King. It happens. Are you worried?}
{1013}{Бартер}{Why not. Do you have something left in stock?}
{1014}{999}{Maybe later. If you'll still have something...}
{1004}{}{[he swiftly pours a full glass] Boss has graced my bar with his presence! Let's drink for that.}
{1015}{031}{How's the business of selling the Drop?}
{1016}{032}{All you need is an excuse. How is it going, Apothecary?}
{1017}{Бартер}{Show me what you have for sale today. And fast.}
{1018}{999}{I think it's more likely to see a two-headed Lavash than you sober... Okay, I need to go. Take care of your liver.}
{1005}{}{[drinks another shot, Not paying attention to the dirt and trash lying around] I was thinking that you left the place. Not that smart, huh?}
{1019}{Бартер}{Better pour me something strong. And show me what you have in stock.}
{1020}{030}{I see the situation leaves much to be desired?}
{1021}{999}{Yes, I've came to say bye. Cheers!}
{1006}{}{[he sniffles with his red nose] A pleasure for me! Why so glum? Is there something happened in the fucking kingdom? Take a seat, let's talk about our business. But remember - I don't take services of hookers as payment!}
{1022}{022}{That's exactly why I'm here - to talk business. Didn't Mate tell you anything?}
{1023}{014}{About Douglas...}
{1024}{018}{By the way, about business - care to tell me about how you settled up here? About how it all started?}
{1025}{Бартер}{Don't worry, I am paying with money. Show me what you have.}
{1026}{023}{I was just getting myself familiar with local affairs. Don't you think this place has some... Troubles with management? We touched on this subject earlier.}
{1027}{999}{I'm good. The business is good. Nice to see you, Apothecary.}

{400}{011a}{I'm looking for something called "Antiradine", do you know what it is?}
{401}{}{Hah, you kidding? This is just the place to get it. Deals with the radiation instantly, has almost no side-effects. We sometimes brew it right here, but mostly I'm selling the old stocks. The drug is not cheap, but sells really well. Recently I even lost one dose to Mate... [he angrily throws his dirty cloth on the table]}
{402}{Barter}{Interesting. Let's take a look at your assortment again.}
{403}{010}{Thanks for the information. I wanted to ask something else.}
{404}{999}{Mate, you say? I'll go talk to him.}

{405}{}{Do you have something you need me to do? Like, work?}


{110}{}{[he grins] Yeah. We don't like your nosy type around here, you know. }
{111}{Бартер}{What do you mean? I just wanted to look at your stock. Let's barter, maybe?}
{112}{022}{What's wrong with my type? Didn't Mate tell you about me?}
{113}{999}{Then I better go.}


{120}{}{ Why didn't you say so earlier! So, our Mate has found someone smart at last? Man, what times we live in - to put down a few ants and deliver a thing on schedule is a problem now... Hm... Okay, get them here. Tell Mate that it's all good. And I'll drink for that... [he gulps from some bottle]}
{121}{013}{A pleasure to do business with you! }
{122}{013}{You could pour me a little. How do you even manage to drink so much and still talk... Okay, see you around.}


{1301}{}{Wait a sec... [he leans closer] See that creep in army jacket? No, not that one! To the right! A suspicious fella... Always hanging here, sniffing out something. I get nervous with someone this sketchy around. Can't even drink in peace. You look like a smart guy, maybe you can figure out what's his deal. What if he is with the Jackals? And he already knows most of the locals, but not you... I'll give you something worthy for it, don't you worry.}
{131}{999}{Okay, let's see what I can do... No promises though.}
{1302}{}{[he smiles with setisfied look] We do honest deals, you know! Just like in old times...}
{132}{018}{By the way, can you tell me about the old times?}
{133}{Бартер}{Let's drink for that. WHat do you have in stock?}
{134}{999}{See you around, Apothecary.}
{135}{014}{Hah, I dealt with this already!}


{143}{}{[he leans even more closer] So? What's his deal?}
{140}{015}{He is employed by the Olympus. His mission is to gather some stuff, and...}
{141}{017}{He is no one! He got lucky with getting a good suit of armor, but now he drinks himself away here. I bet he pops the Drop too... He is not dangerous. Did he visit something except brothel and bar?}
{142}{999}{Don't know for now, but I'm working on it.}


{150}{}{[he blinks, shocked] You... What are you truing to pull off here, you little shit? Is this some kind of a joke? I need the truth, not your stupid tales!}
{151}{016}{IT IS the truth! I've got it all worked out, what else do you want from me? Is everyone around here this tight?}
{152}{017}{Huh... Er... Sorry, that was a bad one. He is just a drunkard. Not related to Jackals. Did you have something on him, except your suspicions?}
{153}{999}{Hey, hey! Chill out! I'd better come later...}


{160}{}{[very hastily, he pulls out the weapon] That's it, I'm sick of your bullshit, you asshole! Are you trying to fuck me up? Did you conspire with him? Do you think that Apothecary is senile? [shouts to the guards] Hey boys, someone here needs the shit beaten out of him!}
{161}{998}{Oh man...}


{170}{}{[disappointedly pours another shot] Well, I mean, yeah, he was never noticed near the lab or barracks... But - you know how it is. Nowadays, if you are not paranoid, it doesn't mean that no one wants to kill you. [he sighs] Okay, you did your part. Here. It's called "Admiration". It's a sample, not in mass production for now. The effect is something you've never felt before. I mean it.}
{171}{999}{If you say so... I'll figure it out. See you soon!}


{180}{}{[he scratches hs neck] Yes, now it's not like the old times... Do you know that we used to run with the Jackals? I knew the Jackal himself, he was... The real deal. Which I can't say about his son, Loudmouth - that one's totally gone off his nut. Once we raided a caravan, and one of our guys got in the line of fire. If you think that Loudmouth stopped shooting, you are fucking wrong! That lad ended up crawling around with his insides all over the place, with Loudmouth laughing... So we talked about it and decided to move on. And moved here.}
{181}{019}{Interesting. Go on.}
{182}{999}{I see. Well, it's time for me to go.}


{190}{}{This place was a pre-war factory of some kind. I mean, not completely intact, much of it was looted. But still, some big-brains settled here, kickstarting the production of chemicals. One of them, Carlos Young, invented the thing we call the Drop. Dope shit! Although, I prefer cognac... Anyway, we seized the factory. Nothing to say, really - who could oppose us? So, that's how it all started. And it was good... [he starts wiping the table with saddened look]}
{191}{020}{Why so sad, if all was good?}
{192}{999}{I think that's enough for today. I'd better go.}


{200}{}{It was good... Before. Then some started whining. Whining about how bad it is that we "exploit locals". Can you believe that? Bad! And all this despite us keeping things in order here, chopping balls of every scumbag who dares to bust things up! If it was Loudmouth who took over, everything here would go to shit already! He would definitely stuffed his ass full of Drop and murdered every smart-ass... Unlike Hog. Hog never wanted for everyone to dance to his tune. Just pay for protection in time, and have no worries at all. Except lately he is too dependent on the Drop too...}
{201}{021}{I don't quite get what you're trying to say.}


{210}{}{I mean this - look around you. No one here cares about anything anymore. The territory is full of some shady assholes loitering around, the number of problems is increasing... And the Hog, you know... I'm worried. What would happen if the Hog kicks the bucket? I'm too old for this shit, and I fail to see any worthy candidates to keep things tight... I think I'm talking too much. It's nice to remember the old times, but enough for now. Come around, if you want to make business.}
{211}{999}{Thanks for the information. I definitely will.}


{220}{}{He tells me a lot of things. He is here to prevent people I don't know from loitering around the Rainbow. And he is not good at his job, if you ask me. Still, he mentioned you. But how does it matter, if you came empty-handed?}
{221}{012}{Actually, I have a package for you. From your insect friends. Ant belly delivery!}
{222}{999}{I'll come back later then.}


{2301}{}{[he gives you a friendly smile, then swiftly grabs your throat and hisses] Here's how it is, little shit - one old man just decided to ramble about good old days with another customer. Nothing more. I don't know you. I won't discuss something serious with you. And if you keep talking like that, I'm going to feed your liver to the dogs. }
{231}{999}{Hey, no hands! I didn't mean anything bad. Let's talk later, when we... Get to know each other better.}
{232}{029}{Ow! Ye old ass, I'll cook YOUR liver if you won't get your meat hooks off me! }
{2302}{}{[he shrugs, drinking two shots simultaneously] I see you are okay. So, here's some free advice - lay off this chat. I won't make any move, while Hog is still around, keeping things in order. }
{233}{999}{Then let's drink for him staying in charge for many years to come. Although now you should be very careful when betting on someone... Think about it.}
{234}{999}{Of course. We're done with this topic.}


{240}{}{Yeah... The bloodbath can start at any moment. And, as I said, I'm getting a little old for this shit. Mate is trying to hold things up, but with little results.}
{241}{025}{Maybe it's time to deal with the situation. What do you think?}
{242}{999}{Good luck to you both then. See you around.}


{2501}{}{All you can deal with is your thingy by the toilet. Who do you think you are, telling me this? Get the fuck away, don't piss me off!}
{251}{029}{That's it asshole, I'm sick of it! Let's check if you have booze instead of blood!}
{252}{999}{Okay, better to talk about it later then.}
{2502}{}{[looks at you with caution] Why do you say that?}
{253}{026}{I have a strange feeling about this. That Mate can join the Hog soon. You know, poisoning, for example. I don't even know where this thoughts come from. Maybe it's something in the air...}
{254}{028}{I don't really want to elaborate on that. Let's talk like businessmen - if someone would pay you a huge amount of money for, I don't know, some deadly poison, to deal with a huge rats - would you question it?}
{255}{999}{I dunno... Oh! Look at the time! Bye, Apothecary.}


{260}{}{[he looks around and lowers his voice] Everything can happen... what's on your mind?}
{261}{027}{What if someone, pretty good at cooking some deadly conconctions, would make some... Food supplement? And give it to someone, representing another someone, who would remember this favor? There's nothing better for a good people than mutually beneficial partnership, right? When the secrets can be kept, of course.}


{270}{}{[he chuckles] You are such a weasel... You're gonna go far, kid. Okay, "someone" agrees - but only to produce the supplement and to give it to another "someone". Nothing more.}
{271}{999}{I don't need more. And I hope we don't have to talk about this again.}


{280}{}{[he hesitates, nervously scratching his chin, but still firmly nods] This might be possible, yeah. Why not? The rats are the size of Mate, I suppose? It's going to be a difficult job... I could try - for a thousand batteries. }
{281}{999}{Deal. Here's the money. Wait for someone from me.}
{282}{999}{Damn, that's a lot... Let's pretend we didn't talk. If something comes up, I know where to find you.}


{290}{}{[He jumps away, pulling out his weapon] Boys! Let's put down this motherfucker!}
{291}{998}{They won't help you, drunkard!}


{300}{}{Don't care. I won't be staying here for long. Just need to finish couple of matters with the Brick. By the way, can you fetch him this package of booze? Ah, forget it, you will drink it all on the way...}
{301}{999}{Then I need to go. Was nice seeing you... I guess.}


{3101}{}{Understood! [he pulls a bag from under the register] Everything is here, Boss, down to the last battery!}
{311}{999}{I believe you, it's not a hooch. See you around, Apothecary.}
{3102}{}{All good! I remember the deadlines - 5th and 20th.}
{312}{999}{Great. Try to get sober until that, for a change.}


{3201}{}{Can't really complain - and don't want to jinx it. The Drop sales are increasing, bar is thriving too. At last, the Rainbow has some order! Fuck me molerat, you do know how to pull shit together here! I couldn't even dream of something like this...}
{321}{999}{Don't forget who you owe this to. See you around.}
{3202}{}{Can't really complain - and don't want to jinx it. Of course, the profits are not the same without the Drop, but at least the Rainbow has some order! Fuck me molerat, you do know how to pull shit together here! I couldn't even dream of something like this...}
{322}{999}{Don't forget who you owe this to. See you around.}


{3301}{}{[he shows you empty hands] Easy, champ. Give a couple of minutes, we need to have a serious talk. The boys who went with Hog asked me to discuss one thing.}
{331}{034}{I hope it's worth it.}
{332}{034}{I'm listening.}
{3302}{}{[his eyes burn with strange fire, hand itches to grab the nearest bottle] So, it's done... I didn't waste my time too - pushed some of our best guys into the right direction. }
{333}{034}{And?}
{334}{034}{This is in your own interests. You didn't surprise me.}


{3401}{}{[his squinted eyes look at you for some time. Then he starts talking.] You wasted the Hog. And it is a big problem, man, because he held the place together. And we don't want everything here to go to shit. This place needs someone cheeky enough to lead it. And we are observing your doings for a long time already - the Rainbow makes everyone to show their true colors, you know... So, my boys think that you are suited for this position, and I agree with them. Your turn, champ. Tell me, what you think. And take this, as a gesture of good will. It's called "Admiration" - a pretty rare stuff, you won't find it anywhere else. [he hands you something]}
{341}{036}{Why the hell not? I think I can do it. No need for inauguration, I'm too humble for that.}
{342}{036}{I'm in. Tell me, what's the deal around here at the moment.}
{343}{035}{Nah, it's not for me. Solve your problems by yourselves.}
{3402}{}{[he makes a long gulp, pouring the rest of booze down his throat] Phew... The thing is, all the boys root for you. They think that the Hog solved problems... Not in a very flexible way - but he solved them. Mate was like that too. But in current situation we need someone smarter. That's when I thought about you, so - what do you think about leading the place? The Rainbow awaits, kid! }
{344}{036}{Good. Fill me in - what should I start with?}
{345}{035}{You know, I've been thinking... I have my own problems. It's too much to do here. I'll pass.}


{350}{}{[looks like he can't believe what you've just said] You... You are fucking... Quitting? Why the fuck did you start this mess then?}
{351}{037}{I just like to beat the shit out of people, that's it.}
{352}{037}{Maybe I had my beef with Mate? Maybe I just screwed you over because of my own interests? Maybe I don't really care about the Rainbow? As I said - no.}
{353}{037}{I had my reasons. Thanks for the offer, but my answer stays the same.}


{360}{}{[he exales in relief] Listen then. Your job is to keep things going. Business matters must be carried out without problems. Don't worry about our stuff, we will take care of it. Once in a month you will be getting you cut for security. The rest you'll figure out. Everything depends on how you act now. And - congratulations, Boss! I should definitely drink for that, wait a second...}
{361}{999}{Nice. But if you think you can relax, you are dead wrong. You are free to go. I'd like to look around my domain.}
{362}{999}{I see. Now, I need to think everything over - and don't worry, I won't forget your role in it.}

{370}{}{[looks like he is going to throw himself at you, but instead, he suddenly goes limp] That's your choice then. Don't regret it. [he walks away.]}
{371}{999}{[end]}