##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Ленни
#Краткое описание: Мертвяк, мечтающий о перерождении своего друга
#Дата создания: 03.10.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a nervous ghoul.}
{2}{}{He looks... Like a ghoul.}
#
# после знакомства
{3}{}{You see Lenny.}
{4}{}{Ghoul, who decided to help his friend to reborn.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[The ghoul walks circles around the man's bloodied corpse, fending off flies. Suddenly, he jumps to the body and starts shaking it by the shoulders] Come on, reborn, you fucking idiot! Why do I have to wait for you so long? [seeing you, he puts his rotten finger to his toothless mouth] Shhh! Quiet! The reborn is in progress!!}
{11}{011}{What the... What is happening here?}
{12}{011}{Calm down, I'm just trying to understand what I'm looking at here.}
{13}{999}{I think it would be better for me to leave.}


{1001}{}{[seeing you, he friendly nods with his wrinkled, skinny skull, covered with sticking remains of hair. His eyes are feverishly bulging out, arms clinging belt of a shotgun, hanging on his back.] Howdy, stranger! Did you come to witness a moment of Lenny and Carl's reunion? }
{101}{011}{Uhh... What are you talking about?}
{102}{019}{Reunion? Are you going to shag him, or something?}
{103}{014}{Lenny, we need to duscuss this... Situation.}
{104}{999}{No, I was just walking by.}
{1002}{}{[tries to hug you with his skinny, saggy hands, giving you a smell of decay, sweat and rotten food] My friend! I'm so glad to see you! I have a whole colony of some bugs under my shoulder blade - can you help me to put them out?}
{105}{019}{Get lost, you freak, until I puked all over this wrinkled ass-head of yours!!}
{106}{999}{I'm glad to see you too, Lenny. I don't have time for this now, but I will definitely see you later.}
{1003}{}{[Stops peeling scubs on his sunken chest and nods] Oh. it's you! You're lucko to see me - my fella is hanging out somewhere, I'm going to go look for him.}
{107}{999}{Good luck with the search. I need to go.}
{108}{019}{He just decided to screw you over. Looks like even the ghouls take you for a freak, ha-ha!}
{1004}{}{[considering he has no lips, you can't understand if he is smiling or angry at you] You're still here, stranger? I'm going to get out. Somehow, no one wants to talk to me here. I wish Carl was around...}
{109}{999}{Good luck, ghoul. Maybe your life gets better someday.}
{1010}{019}{That's right, get the hell out! Ugly freaks like you should be shot on sight!}


{110}{}{What's here you don't see? Are you thick or something? No worries, I'll explain... I'm Lenny, this is my best friend Carl. We used to hang around Radius together, looking for loot. Everything was good with the two of us. But one time, I decided to get out on a trip alone - into some old ruins, where geiger counter is screaming non-stop. That's where I stepped on a mine. Carl found the pile of shit I became and got me out, but I still received enough radiation. The result is in front of you.}
{111}{012}{And? How this explains the current situation?}


{120}{}{[he spits out a spirt of green saliva, and scratches a hole, which was once his nose] It's obvious, you see - Carl needs to became a ghoul too! And then we will continue doing our things together! I did everything by the book - threw a grenade into his toilet, carried him into the same ruins I was in. Then I waited for some time and brought him back here, so he could be reborn in comfort. I even reserved the table in bar to celebrate! See? He's already changing! Look at these spots at his skin. And the smell...}
{121}{019}{You... Your brains are completely eaten away by radiation, you freak! You should be put down, while you didn't start attacking people on the streets!}
{122}{013}{This is called decaying. Your friend is literally dead.}
{123}{999}{It's... Unusual. I may be able to help you, but first, I need to think it over.}


{130}{}{No! Don't you dare to piss into my ears! Carl's alive! I just need to wait a little more! If you don't want to help - move along!}
{131}{019}{I should put you down, you sick freak. Out of pity, at least.}
{132}{999}{Calm down. Let's talk about it later.}


{140}{}{[he squints] What's there to understand? It's all obvious.}
{141}{015}{I just wanted to say that I can cover for you here. Maybe you need to go away for something.}
{142}{016}{Listen, Lenny, your friend is dead. You know it, just don't want to admit it. And if you continue like this, you will definitely go off the rails. I see that you wanted to do best, but the life is such a thing... I mean, do you realize that you have killed your only friend?}
{143}{016}{Hey, it's wrong to let dead people lay around! Until you bury the body, he won't be at peace! So, do it - and you can be sure he will wait for you on the other side.}
{144}{018}{Lenny, your friend just screwed you over! You worked so hard for him, and he only lays under the hot sun, not even thinking about being reborn! But you know what? I can be your new best friend, instead of him! I can't stand seeing you suffer.}
{145}{019}{I see how it is. I should put you out of your misery. Get ready, ghoul.}
{146}{999}{You are right, we have nothing to talk about for now.}

{150}{}{[he loudly exhales, fending off the flies] At last! The only normal guy around here! I'm already getting tired of carrying him around. And you're just in time, I need to take off some load real fast... Don't worry, I'll be right back. [he rans off, unzipping his pants in the process]}
{151}{020}{Take your time... [wait for him to get out of your sight, then call for your ghoul ally and utilize Carl's body]}
{152}{999}{I need to do something else. Lie here for now, Carl. }

{160}{}{[Looks like Lenny is going to throw himself at you in any moment... But he starts sobbing instead] Man, I screwed up, big time... Murdered my best bud! What's wrong with me? Looks like my brains got completely messed up from that explosion... You... Thanks for compassion. No one gives a shit about anyone around here... You know, actually, you're right!! We can meet with him at the other side!!! [suddenly, he drops his shotgun from shoulder and puts it to his belly]}
{161}{999}{Uhh...}

{170}{}{[Looks like Lenny is going to throw himself at you in any moment... But he starts sobbing instead] Man, I screwed up, big time... Murdered my best bud! What's wrong with me? Looks like my brains got completely messed up from that explosion... You... Thanks for compassion. No one gives a shit about anyone around here... I don't have much, but still - take my bullets, you can trade them for batteries.}
{171}{999}{Thanks, Lenny. I'll make good use of them.}

{180}{}{[he stares at corpse in front of him, sometimes looking at you. For a moment, his sight becomes clear, but then it is immediately clouded by the veil of madness.] Damn, you are so right! I am busting my ass here for him, and he... Man, I'm so lucky to have you opening my eyes! Lemme hug you... Oh! Wait! Take this - as a sign of our friendship! [hands you his shotgun] And I need to go drop this pile of shit into a cesspool. [he grabs corpse by its feet and drags it somewhere]}
{181}{999}{Thanks, uh... Friend. Won't bother you anymore.}

{190}{}{[He may be crazy, but not slow. Shotgun, hanging out on his back, now magically appears in his hands, pointing at you] What did you just say, you son of a bitch?! Carl, come on, get up - there's another asshole to put down!}
{191}{998}{Your first, dead meat!}
{192}{998}{Yeah, go try it...}

{200}{}{[The plan goes down rather swimmingly. Seeing reborn "Carl", Lenny starts to jump around, yelling of excitement. Delighted, he hands you his shotgun. Then the couple walks away in the bar's direction]}
{201}{999}{That was too easy. And quite bizarre.}

{500}{}{What do you want? [he patiently looks at you]}
{501}{}{Oh, an outsider? Well, what do you need?}
{502}{}{You again? Is there something you want?}
{503}{}{There's an option for you to obtain the support of one nice guy... Of your kind. With a shotgun [wink]. All you need is to substitute yourself for another man's corpse.}
{504}{}{Nothing, just walking around.}
{505}{}{Not impressed. Deal with it yourself.}
{506}{}{You know, it actually sounds like a good idea! I could use a friend with a shotgun. Lately, there are strange rumors going around, about the Drop... What do you need me to do?}
{507}{}{Great! I will find you when the moment is right!}
{508}{}{Okay, it's your decision... [squint and leave]}
{509}{}{0}