##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Наоми
#Краткое описание: Дочь Карлоса Янга. Возможно уговорить ее бежать или остаться.
#Дата создания: 11.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a girl wearing lab coat.}
{2}{}{Something's clearly depressing her.}
#
# после знакомства
{3}{}{You see Naomi Young.}
{4}{}{The head of the laboratory and the chief of the Drop production.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Her lab coat is pretty worn, albeit clean. Her face is a mask of exhaustion and strain, green eyes are looking at you dismissively] Who the hell are you? How many times do I have to tell - don't bother me while I'm working! I'm not even talking about the need to disinfect the place after every other narrow-minded oligophren walking in here...}
{11}{011}{Sorry, didn't mean to interrupt. We haven't met, by the way. I'm }
{12}{999}{. And you are?}
{13}{999}{Sheesh, lady, chill! I'm already leaving. The name's }
{14}{}{, by the way. Nice to meet you.}


{1001}{011}{[She indifferently nods] Good day to you... How's the life behind the walls going? And - what's the reason I have to tolerate you here again? Maybe, you came for "de ting to have a hard-on for anoder twentee for ours"? Geez... Oh, and tell Hog that the next batch will be ready in time.}
{101}{015}{Remind me, who are you, actually?}
{102}{014}{I wanted to talk about your situation here.}
{103}{999}{I definitely will. By the way, what can you tell me about him?}
{104}{999}{I was just looking around. Good day to you too.}
{105}{}{Twenty four hours? What an interesting proposition. I'm perfectly fine in that regard, by the way. Well, see ya.}
{1002}{027}{[she gives you a cautious look as if she doesn't know what to expect] A Big Boss himself came down upon us! To what do we owe the pleasure, if I may ask? Decided to try the product yourself, or just out of punching bags?}
{106}{026}{I want to talk about the Drop. I need the product to be more effective.}
{107}{999}{Do you have questions, maybe? Complaints?}
{108}{999}{Just checking my personnel. I see you are doing fine. See you next time then.}
{109}{}{I'm not in the mood for your shit, girl. Keep your mouth shut, and remember who owes your life. That's all, I'm out.}


{114}{012}{Naomi Young. An honorary head of this fine laboratory. For life. [bows mockingly] Are you happy now? [mumbles] To serve the ones who have IQ not even approximately close to mine, even combined... Glad my father can't see me...}
{110}{021}{What is it that you create here?}
{111}{022}{What? Think you're smart, huh? Why do you work for locals non-stop then?}
{112}{999}{Who was your father?}
{113}{}{You have to excuse me, but I need to go.}


{120}{022}{What hole did you crawl from, asking questions like this? What else can be made here? Only the Drop! The blood of Rainbow... The curse of my father.}
{121}{013}{Who was your father?}
{122}{999}{Can you tell me what exactly the Drop is?}
{123}{}{Thanks for the info, but I need to go.}


{130}{022}{The Drop? The Drop is a perfect drug with instantaneous effect. Has a direct impact on the adjacent core of the limbic system, causing the feeling of euphoria, among other things. Addiction is formed from the first dose in 98,14% of cases. The pre-war "RadOut" drug is used as a basis for it. My father made some changes to the formula while researching the unique properties of fire ant pheromones and... But I don't have time for lecturing, and you wouldn't understand the details. You're lucky if even a little part of what I've just said stuck in this primate head of yours.}
{131}{021}{Your father must have been a very famous scientist. Could I hear his name?}
{132}{999}{Do you give this scientific mumbo-jumbo bullshit to everyone you see? If you do - I guess you don't have a lot of friends, haha!}
{133}{999}{Thanks for the information. but I need to go. Take care.}
{134}{}{Whaaat? Why don't you go screw yourself? Primate... I would show you who's who, but I need to go.}


{140}{013}{Take the Hog, for example. A wonderful case to demonstrate all the effects the Drop has on the human organism. It is quite ironic that someone like him got the maximum impact from it... [sadly smiles] Thanks to regular drug intake, he has become very strong and enduring. In return, he obtained a mental disorder and complete inability to sleep. I should point out that even the reality our Hog perceives in a very... Specific way. He is my reward for being locked into these walls - his phenomenon is unbelievably curious to study.}
{141}{021}{Can you tell me more details about the Drop?}
{142}{012}{Yeah, sure! Any brothel slut can make up this kind of bullshit about research. By the way, how's your situation any better?}
{143}{999}{I see. So. you produce the Drop here?}
{144}{}{Good luck in your studies. See you around.}


{153}{016}{[she raises eyebrow] What about my situation? }
{150}{017}{I think the lab can operate more effectively.}
{151}{999}{Such a brilliant scientist shouldn't be locked in this place. What do you think?}
{152}{}{No, nothing. I better go.}


{164}{023}{[she squints] And what makes you say that, sir? Why do you even care? I see no point in discussing this matter. Every local degenerate has his opinion about me... Ha!}
{160}{023}{I know enough chemistry to understand that. I could, for example, try to prolong the duration time of effects through the use of enzymatic inhibitors... Of course, it will take more time for me, but in the end... What would you say to Hog then? I won't forget to mention that you could achieve such results yourself.}
{161}{021}{I'm not good at chemistry, but I'm pretty good at people. You love this job, I can see that. And you would be glad to take some challenge. To improve the drug and lessen the side effects... To prove that you are worthy of your father's legacy, that you are a great scientist! If you have to spend all your life here, isn't it better to at least have fun with it?}
{162}{999}{Listen, bitch, you were told to do better, so do it!}
{163}{}{Okay, think about it, I'll be back later.}


{170}{024}{What are you talking about? Is this some kind of a joke?}
{171}{999}{No jokes. Is this how you wanted your life to be? Making drugs for dumb raiders?}
{172}{}{Yes, actually, it is. Ha-ha. Well, I need to go.}


{180}{019}{[You notice a shadow of emotion on her tired face] Why would I trust you? Maybe the Hog sent you to test my loyalty! And... There's that sleazy guy near the entrance...}
{181}{021}{Do you really think that Hog would do something like this? You work for him, he's satisfied with that. As for the guard - it's my problem, don't you worry.}
{182}{999}{Why should I smooth-talk you into this? Out, now!}
{183}{}{Uh, I didn't think about it... Okay. see you later then.}


{190}{020}{[She bites her lip, glancing over the entrance. Then suddenly giggles] Okay, let's do it! What do I lose? Just a second... [She opens the drawer in her table and starts to hastily put things into her pockets. Looks like she was thinking about running away before you came] Done, I'm ready!}
{191}{025}{Good. Let's not waste any more time then.}
{192}{}{Great! But, uh... Er... You go, I'm right behind you. I'll provide protection from the rear.}

{201}{999}{[she nods] Okay then... Let's go. Damn, I wasn't so nervous in a really long time... [she looks at the lab for the last time and goes to the exit]}
{200}{}{It's alright. I'm with you.}

{212}{999}{What? [She deftly grabs some flask from a table] Do you know what this is? It's aqua regia, you moron! Get out, or else you'll be drinking it!}
{210}{999}{Put that thing back, you crazy bitch! I'm leaving!}
{211}{}{Apologies. All the best.}

{223}{013}{My father was Carlos Young... The brightest mind, the best chemist in Radius. And it's not only an opinion of his daughter, but a fact. Self-taught, he showed everyone! He invented the Drop... And he always loved me... Anyway, we're not here to remember the past. Understand this - even if some kind of collective intelligence would have existed on the Rainbow, it wouldn't be able to create anything even slightly comparable to a tiny bit of his research.}
{220}{999}{You are a worthy daughter, to remember him like that. What about the Drop?}
{221}{021}{I see. Well, I'm off, all the best.}
{222}{}{I'm so sick of you bragging about your smart brain! Here's a secret for you - if the skull is smashed, they all look the same, smart or stupid! Wanna see?}


{231}{999}{[her sarcastic face becomes blank] Well... Looks like I don't have much of a choice, do I? Okay, I'll do it. For my father. I have some theories... Tell the Hog that the first results will be in a month.}
{230}{}{Just wonderful. We've spent more time talking about it... Won't be distracting you anymore, you have a lot of work to do. Good luck!}


{240}{018}{[she still sounds sarcastic, but you hear the doubt in her voice] How could YOU know something about being the scientist? I don't think you can even read... The Drop is a unique chemical compound, researching it is a delight! By the way, I have food, the roof over my head, protection... How many people in Radius can say the same?}
{241}{018}{Sure, sure. Are you trying to convince me, or yourself? I can see that this job is not making you happy. There's plenty of places where your skills could have a better application! Where you could help people, make a difference!}
{242}{999}{Oh really? Why didn't you make any progress in your research then? I know enough about chemistry to name some fields where you, judging by what I see, weren't even trying to make an improvement. Heterogeneous catalysts, enzyme inhibitors... Do I need to continue?}
{243}{999}{Suit yourself. All the best.}
{244}{}{Then stay here until you die! I've had enough, I'm leaving!}


{250}{020}{[Naomi stops halfway] Wait, what about that huge thug outside? He once killed someone from the staff for an attempt to sneak away into the local bar...}
{251}{999}{Yes, you are right. Let's leave together.}
{252}{}{Uh... Didn't I tell you? I sent him some, er, kid, with an assignment from the Hog himself. Allegedly. The coast is clear, no one would stop you. And I'll stay and watch over your ex-colleagues.}


{260}{999}{[she looks surprised] Who can even think about complaining in this paradise? We have the best kind of stability here. You have sealed us off from the outside world, so nothing could prevent us from working for the greater good. If you didn't visit us, we wouldn't even know about the changes in local management! Ahem... By the way, the changes are happening very often lately. We are worried, you know... }
{261}{999}{Don't worry about it. By the way, as a thank you for your work, I thought I'd let you relax a little. Food, drink, and girls for everyone. Only don't do drugs, geniuses. Enjoy your time!}
{262}{999}{I see you are a little sarcastic, aren't you? I'm not a fucking Hog! Let's see how you'd like to work for a week on water and rat meat! Say thank you to that big loud mouth of yours, bitch!}
{263}{}{One way or another, I intend to stay in charge for a little longer. Get used to it.}


{270}{028}{And I'd like a real man to go down on me. Except there are none on the Rainbow. Why do you even think that the Drop can be improved?}
{271}{028}{I know enough chemistry to understand that. I could, for example, try to prolong the duration time of effects through the use of enzymatic inhibitors... Of course, it will take more time for me, but in the end, it would raise a question - do I even need you? And you will lose everything you have now...}
{272}{999}{I'm not good at chemistry, but I'm pretty good at people. You love this job, I can see that. And you would be glad to take some challenge. To improve the drug and lessen the side effects... To prove that you are worthy of your father's legacy, that you are a great scientist! If you have to spend all your life here, isn't it better to at least have fun with it? Not to mention that I can make your existence here very, very painful. We wouldn't want that, right?}
{273}{999}{I was just thinking out loud. We'll talk about this later.}
{274}{}{If I had time for you, I would bend you over the table and show you a real man. It's in your interest to make the Drop better. Think about it.}


{280}{999}{[her sarcastic face becomes blank] Well... Looks like I don't have much of a choice, do I? Okay, I'll do it. For my father. I have some theories... The first results will be in a month.}
{281}{999}{Just wonderful. We've spent more time talking about it... Won't be distracting you anymore, you have a lot of work to do. Good luck!}
{282}{}{That's better. You are not the only one with a good brain here, am I right? Okay, stop talking and get to work!}

{290}{}{Talk later.}
{291}{}{We are trying to leave, right?}
{292}{}{I hope that thug won't catch us...}
{293}{}{I'm so nervous right now...}
{294}{}{Thanks, hero. I'll take it from here. See you around... Someday.}