##############################
#Локация: Рэйнбоу Рэйдерз
#Имя: Shepherd
#Краткое описание: Сутенер Радуги. Квест на озабоченного Кирпича, квест со шлюхой
#Дата создания: 04.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a black-skinned raider.}
{2}{}{He greedily looks at anyone entering.}
#
# после знакомства
{3}{}{You see Shepherd.}
{4}{}{Black, in every meaning of the word, pimp of the Rainbow.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Black skin, black eyes, black clothes. As you approach, he drops the toothpick he poked his black, rotten teeth with.] Hey, man! Come! Shepherd provides the biggest joy for any man! Interested?}
{11}{015}{Maybe. Tell me more.}
{12}{011}{Sounds tempting... But do you mind answering a few questions first?}
{13}{016}{This is great and all that, but I'm more interested in work.}
{14}{999}{I'll try to enjoy something else. See you.}


{1001}{}{[he winks at you, smiling] What, decided to have some fun at last?}
{101}{011}{Better answer me some questions.}
{102}{015}{You do know your customer. I'm here exactly for that.}
{103}{018}{I handled the matter with Brick. He won't be bothering your girls anymore.}
{104}{017}{I took care of those pricks in your joint.}
{105}{016}{Do you have something you need me to do, Shepherd?}
{106}{999}{Not yet. See you later.}
{1002}{}{[he salutes you with his toothpick] Here comes the Rainbow's new muscle. Want a girl, champ?}
{107}{015}{Yes. I need to relax.}
{108}{011}{Answer a few questions first.}
{109}{018}{I handled the matter with Brick. He won't be bothering your girls anymore.}
{1010}{016}{Do you have something you need me to do, Shepherd?}
{1011}{999}{No, I need to keep in shape. Maybe later.}
{1003}{}{[he respectfully nods at you] Hey chief, how are you doing? Our favourites, Slut and Suck- er, I mean Squirrel and Snowflake are not good enough for you anymore? We always have a wide range of new girls to offer! }
{1012}{021}{How it is going, Shepherd?}
{1013}{016}{I suppose your horizontal business is all good... See you around.}
{1014}{022}{Isn't now the time to pay? What do you think?}
{1015}{015}{Actually, let's see if you're not lying. Which new girls?}
{1016}{017}{I dealt with those trash. Clean it up.}
{1017}{018}{I handled the matter with Brick for you.}
{1018}{999}{I'm just checking things around here, Shepherd. Don't get too comfortable and keep an eye out for our merchandize. Capisce?}
{1004}{}{[Looks like somebody decided to check if black people can have bruises. Shepherd looks pretty bad, even his toothpick is missing] Hey, man... I hope you are here for business?}
{1019}{021}{Seems like your business is not doing so great.}
{1020}{016}{You could use some help, am I right?}
{1021}{015}{Well, yeah. I want a girl. Is this a problem?}
{1022}{018}{Keep your head up, slut's herder! The matter with Brick is resolved.}
{1023}{017}{I've dealt with your difficult clients.}
{1024}{999}{Er... I better leave you alone. Take care, Shepherd.}
{1005}{}{[With a depressed look, he wanders around the room, quietly mumbling something. You come closer.] Hog... How did it happen, brother? We went through so much - just for you to get smoked here... Where's the fucking righteousness in that? [he notices you] And the life goes on. What brings you here, man?}
{1025}{018}{I handled the matter with Brick. He won't be bothering your girls anymore.}
{1026}{016}{Do you have something you need me to do, Shepherd?}
{1027}{017}{I took care of those pricks in your joint.}
{1028}{015}{Unless you girls have a break for lunch, I would like to visit them.}
{1029}{999}{Just wanted to see how are you doing. I'll come by later.}


{110}{}{[his smile gets impossibly wide] Shepherd is always ready to help out a good man! For a fistful of batteries, of course. Every question costs a ten, no discounts. It's a free market, business is business, nothing personal.}
{111}{019}{Why do you have to be so greedy? Would you even work instead of your girls, if the price is right?}
{112}{012}{Okay. Tell me about the Rainbow.}
{113}{013}{Here. And tell me about the people in charge, who are worth dealing with.}
{114}{020}{What? Ten? Why don't you go suck on it, herder?}
{115}{999}{Actually, I've got to go.}


{120}{}{[he eagerly grabs the batteries] Rainbow, you ask? Rainbow is the best place in the whole Radius, man! Here you can find everything a free man needs. In our neighborhood you can come by Apothecary's bar and pop some stuff or get booze. Also, we make the Drop here - you should check it out. It hits you like a sledgehammer! Good stuff. If you want to shed some blood and make some money, then Arena is at your service. Look to the east of central square. By the way, it's the place where the most of our guys like to hang out, so - behave.}
{121}{013}{Okay. What about the local authorities? You probably have some serious people in charge here.}
{122}{999}{Thanks for the info. Take care, Shepherd.}


{130}{}{[he quickly counts and hides batteries] Well, actually, nobody's in charge. But everyone pays my man Hog for protection. He is an extremely serious fella, we're like brothers. We've been through so much shit together, you wouldn't believe. Had so much fun in raids while in Jackals... Then the Hog has Mate, that shaved motherfucking asshole, who think he's cool. You just keep in mind that he looks after the supply of raw materials for the laboratory and deals with issues that Hog does not. And there's Apothecary - he owns a bar and controls the quality of the Drop. He is pretty good at chemistry... When not wasted.}
{131}{014}{What did you say about the Jackals?}
{132}{012}{Can you tell me more about the Rainbow?}
{133}{999}{Understood. That's all I wanted. See you!}


{140}{}{[he spits on the floor] They are just a bunch of pussies. After we left them, the Jackals became nothing. Now there's Loudmouth in charge, and he is pretty fucked up. Thinks he has the longest dick in the Radius, ha! Why do you think they call him that? Because he was pissing his pants and whining non-stop as a child. His father, Jackal, was... A good boss, but a terrible parent. He fucked up his son, even with turning him into a real Jackal in the end. This loud asshole cut off Hog's finger just for kicks, can you imagine? So, when we got tired of this hysterical bitch, we moved here. Took care of every annoying shit, built the Hog's crib, the bar...  Basically, started to live as a normal, white people. Especially me! [he happily laughs]}
{141}{999}{Thanks for the info. See you around.}


{1501}{}{[he gets more lively] Now we're talking business! Here's how it is, man - for only 27 batteries per hour, best pussies in Radius are at your service! Do anything you want with them, but don't mess up the commodity's condition, be so kind. They won't say no, I promise you that. I work on them myself... In every hole, hahaha! And don't forget the condoms - it's on the house.}
{151}{999}{Such a good recommendations! I'm paying!}
{152}{999}{No, I don't need it for now.}
{1502}{}{Our fine establishment is always at your service, man! The price still stands - 27 batteries per hour.}
{153}{999}{Let's do it!}
{154}{999}{Maybe some other time.}
{1503}{}{You won't regret it, chief, I tell you! [he shouts to one of his girls] Hey you!! Prepare those two new ones I left for myself! Our boss is doing us the honors! }
{155}{999}{We'll see about that... Give me the rubbers and you can go.}


{1601}{}{Actually, yes. I might use some help. [he stares at you for a while, then continues] I've been having troubles with security in my establishment lately. Some assholes are periodically coming around, four of them. In their last visit, one of my girls ended up being torn, another had her face worked with a blade. And that means I'm having additional costs! Fuck, I couldn't get a boner for a couple of days, that's how sad I was! Of course, I could tell Hog about it, but I suspect that he would send Mate to deal with it - and I have my beef with Mate. So, will you handle the scumbags? They actually just came in... }
{161}{999}{Deal. Wait here.}
{162}{011}{Not interested. Better answer me some questions.}
{163}{999}{I need to think about it. Will be back.}
{1602}{}{There's one thing that's bugging me. A guard of the local warehouse, named Brick. This horny piece of lavash shit made a habit of visiting my girls - and he fucks them for free! Backs them into a corner and bonks them right there. How do you like that? Now, man, please, deal with him, I ask you like a brother. Apothecary supplied me with some chemical stuff to loosen up, but I'm willing to give it to you, only for that freak not to be around anymore! }
{164}{999}{Deal. Get the stuff ready.}
{165}{011}{Nah, handle him yourself. And I need answers to some questions.}
{166}{999}{I need to think about it. Will be back.}
{1603}{}{[he nods] There are actually four scumbags... When they came around last time, one of my girls ended up being torn, and another had her face worked with a blade. This not only means that I'm having additional costs - it's disrespectful to you, chief!! I would impale them on some stick myself, but I know how you like to personally break the bones of such disrespectful pricks!}
{167}{999}{Ha! You are quite right. Are they here now? Good - it's time to shed some blood...}
{168}{999}{What? I don't do such petty shit. You should deal with matters like this yourself! That's it, I'm busy, See you!}
{1604}{}{[he sends a chewed toothpick flying into the nearest prostitute] I don't even feel comfortable to distract you with such petty matters... There's one of your guys, a guard of the local warehouse, name's Brick. This horny piece of lavash shit made a habit of visiting my girls - and he fucks them for free!! Backs them into a corner and bonks them right there. How do you like that? Help me, chief, I'm pretty busy lately - trying to make more money for you!}
{169}{999}{Okay, I'll see to it. And you should think about why would I need someone who can't handle his own matters.}
{1610}{999}{And you will pay in time, I don't even doubt. As for the Brick - I don't have time for this, hear me? Later.}
{1604}{}{Nah, everything's quiet. All good, man.}
{1611}{999}{Okay. Tell me if you need something. Later, Shepherd.}
{1605}{}{[he scratches his nose with a toothpick] Chief, you are so good at dealing with this kind of shit, I can't believe it! We are so lucky to have you in charge! Everything is great, no problem at all!}
{1612}{999}{Good. But you should learn to handle the matters by yourself, because you are responsible. Later, Shepherd.}
{1606}{}{Actually, yes. I might use some help. [he stares at you for a while, then continues] I've been having troubles with security in my establishment lately. Some assholes are periodically coming around, four of them. In their last visit, one of my girls ended up being torn, another had her face worked with a blade. And that means I'm having additional costs! Fuck, I couldn't get a boner for a couple of days, that's how sad I was! As Hog went down, all this filth doesn't let met do my business! And Mate is so happy about it, that smug asshole...  So, will you handle the scumbags? They just came in...}
{1613}{999}{Deal. Wait here.}
{1614}{999}{I need to think about it. Will be back.}
{1607}{}{One thing is bugging me. There's a guard of the local warehouse, name's Brick. This horny piece of lavash shit made a habit of visiting my girls - and he fucks them for free! Backs them into a corner and bonks them right there. How do you like that? Now, man, please, deal with him, I ask you like a brother. Apothecary supplied me with some chemical stuff to loosen up, but I'm willing to give it to you, only for that freak not to be around anymore! Without Hog, all kinds of assholes are running rampant here...}
{1615}{999}{Deal. Get the stuff ready.}
{1616}{999}{I need to think about it. Will be back.}


{1701}{}{Man, what a beast you are! Everything is bloody, right to the ceiling! Good job. Here. [he gives you a shiny revolver, covered in oil] It's sad to part with it, but business is business.}
{171}{999}{Nice to do it with you! Alright, see you later.}
{1702}{}{What a bloodbath, chief! You definitely know your shit, man! Here, take this, with all respect. I used to lead the raids with it, back in the day, in Jackals. [he gives you a shiny revolver, covered in oil] }
{172}{999}{A good addition to my collection. See you around, Shepherd.}


{1801}{}{[he stretches his lips into a smug smile] Good to know... I hope that's how it is. Here's your package. Want me to tell you how and what to mix, so your hard-on would last for twenty four hours? The price is pretty small.}
{181}{999}{No thanks. I'll figure it out. See you.}
{1802}{}{[his fat lips squeeze the toothpick. Shepherd looks pleased] You got what you deserved, you walking sperm bank... No more problems with security then, chief! Here, this is for you. [he hands you a backage with some chemicals] Thanks again!}
{182}{999}{Next time you'll answer to me for such screw-ups. You can go for now.}


{190}{}{[he coarsely laughs with a pleasant look] Maybe I would. You don't have enough batteries for it anyway! Haha! I'm a businessman, man, not a cheap pimp from the streets.}
{191}{020}{Really? You ARE a pimp from the streets! I'm going to spin you right round on my device for free, if I feel like it!}
{192}{013}{Okay, businessman. Tell me about the local authorities. Who is in charge here?}
{193}{012}{Alright. Tell me about the Rainbow.}
{194}{999}{I get it. I'm leaving.}


{200}{}{[He stares at you with his bulging, red eyes]  You... Who do you think you are fucking with, bitch? You know what Hog will do to you? Screw this, you know what I will do to you? I'll show you!}
{201}{998}{Come on, you scum! I will dissect your face right to the back of your head!}
{202}{998}{As the blind man once said - let's see! Come and get it!}


{2101}{}{The business is going great, chief! The last batch of girls we got is just sweet, can't say it better. [he strokes his greasy hair] And a lot of them come to us by their own will, because they want your protection! All I have to do is to count the incoming batteries.}
{211}{022}{And how much did you count? Have something for me?}
{2102}{}{[he grabs his head] Everything is fucked... Some assholes beat the shit out of me and left without paying. The bitches are running away... I just can't handle it alone, man. Hog, why did you kick the bucket, brother... }
{212}{999}{It could be worse. Hang in there. }


{2201}{}{[he opens his little portable safe] All here, chief, down to the last battery!}
{221}{999}{Great. Tell the girls I said thanks for their hard work. See you!}
{2202}{}{All will be good, chief! You know me, man! Every 5-th and 20-th. Just come and take your cut, no problems!}
{222}{999}{I won't forget that. Later.}


{2301}{}{[You see a girl running at you, screaming. As you stumble, she gets behind you back, cowering in fear. The black guy stops nearby, gasping for air, then tosses a toothpick into his mouth.] What the... Don't get in my way, man. I'm going to beat the shit out of this bitch's stupid head! Or better, help me to capture her!}
{231}{024}{What's this all about?}
{2302}{}{[You see a girl running at you, screaming. As you stumble, she behind you back, cowering in fear. Shepherd stops nearby, gasping for air, tossing a toothpick into his mouth.]}
{232}{024}{What's this all about?}


{240}{}{I treated this slut like no other! I didn't even punched her face while fucking her! The clients liked her! And what she does in return? She starts fucking stealing! And you know why? Because of her fucking dad's meds! She tried to talk the caravan merchants into this, ain't it fucked up? Of course, they ratted her out - they are our regular customers! It's alright - if she survives after me, she'll learn some respect! [The girl squeals and covers her face] Get her, man!}
{241}{025}{Just a second! [grab the girl] Damn, ain't she a feisty one! Hold her, don't stand there! Things like this shouldn't be forgiven, so don't go easy on her. Thieves used to have their hands cut off, or so I've heard...}
{242}{026}{Hey, easy! This can be resolved without any fuss!}
{243}{027}{You won't touch her, black boy. [stand in his way]}


{250}{}{[The pimp skillfully ties the hands of resisting girl with a rope, then puts a noose on her neck] You know, she doesn't need hands to work... Thanks for the tip, by the way! Don't you worry, I'll deal with her very thoroughly. You should come visit us, man. I won't promise any discounts, sorry, but at least the girls won't be contagious, haha! [pulls the rope] Move, bitch! }
{251}{999}{You don't trust anyone these days... Okay, I overstayed my welcome. I should go.}


{260}{}{[he is staring at you astonished, with his mouth open. His toothpick is stuck on his lower lip.] What? What the hell are you blabbering about? How else would you deal with this?}
{261}{}{Be more practical! You said yourself that she is a valuable employee. And she is already terrified - look, she's barely standing. Why do you need to lose part of your income? Just remind her about this matter from time to time, and she will work even harder than before. }
{262}{025}{You know, maybe you're right! [grab the girl] Hold her legs! Ow! I'm going to rip your arms off, you slut!}
{263}{027}{How, you ask? One-on-one. With me.}


{2701}{}{[Suddenly, the pimp throws himself at you. What he tried to do - attack you or grab the girl - will always remain a mystery, because he trips over, falls down and hits the floor with his head so hard that you hear loud cracking. The girl stands frozen with her mouth agape, then sets a new world record on high-pitched yelling and hastily vanishes around the corner. You check the pimp's body for signs of life, but his broken neck indicates that he has definitely kicked the bucket.]}
{271}{999}{How's that even happened? And what should I say if someone asks?}
{2702}{}{[He approaches you, grotesquely waving his hands] Oh, so we have a hero among us! A holy saviour of poor prostitutes! Do you know what Hog will do to you if you lay a finger on me? You know what, asshole, I'm going to kill you myself, and then fuck this bitch on your cold corpse! Hear me?! [the girl is definitely waiting for the moment to sprint away from the place of conflict.]}
{272}{998}{So much talking... Let's see what you are made of.}
{273}{998}{I'm going to make a meatball out of your innards and shove it very deep into your black ass! And she gets your black balls as a souvenir! }
{274}{028}{[Heated by conversation, your opponent doesn't even think about defending himself. It's time to attack!]}


{280}{}{[Your blow is so fast that enemy didn't even notice it. With the palm of your hand, you punch his nose cartilage right into his brain. The pimp falls down like a sack of flour, twitches his leg for the last time - and stops moving. His unseeing eyes are staring into nothingness. You look around, but the girl is nowhere to be found.]}
{281}{999}{Not even a thank you... Okay, what's done is done.}

{285}{}{Armed raiders kindly escort you to their boss, pointing their guns in your back.}