##############################
#Локация: Псы Заката
#Имя: Билли
#Краткое описание: Заведует мастерскими Псов Заката. Квест с Шивой.
#Дата создания: 22.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a muscular raider with a big bushy beard covering almost all of his face.}
{2}{}{His every move is filled with impatience and fierce readiness to start a fight.}
#
# после знакомства
{3}{}{You see Billy.}
{4}{}{A fearsome chief of the Jackals workshops.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[His glorious ginger beard is littered with metallic chips and sawdust. Having his beefy hands tattoed all over with skulls and gears, with a big red scar on his forehead, he doesn't exactly comes across as a working type. When he turns around, you notice a label "Billy" sewn with wires on his jacket] Who the hell are YOU? [he glares] There's shite from all over the Radius... Why the fuck are you hanging in here?}
{11}{011}{I'm just looking around. You guys definitely have a way of organizing things. Your doing?}
{12}{014}{You'd better watch your mouth - or there is a possibility that you are going to eat shit.}
{13}{015}{I'm looking for a quick buck. Have something for a hired gun? }
{14}{999}{Easy! I'm leaving.}


{1001}{}{[Clearly disgusted, he rams through some geared mechanism] Hrrrm... No, let Carl handle this shit. [Drops it on the ground. His eyes meet you] You again? You come in here a lot. I don't like it...}
{101}{011}{By the way, what it is that you do here, exactly?}
{102}{014}{And I don't like this ginger broom on your face. I wouldn't mind setting it on fire to watch you run around. So?}
{103}{015}{I wanted to ask if there's something you want me to do.}
{104}{999}{Then I'm leaving.}
{1002}{}{[he adjusts the wide belt on his massive belly and nods to you] Have you considered joining the Jackals yet? I have a position reserved for you... Maybe we'll go to Shiva together, make a party for three? }
{105}{011}{What an interesting proposition... But, as I recall, you are still not completely in charge here, right? Or something has changed?}
{106}{999}{No, thanks. I have a lot on my plate already. See you around, Billy.}
{1003}{}{[Billy is inspecting a map before him. It crudely depicts some area of the Radius. Frowning his bushy eyebrows, he is deeply focused on moving his thick finger around it.] Here are the guards... And here's where we may be able to pull through... [he waves at you] Hey you, come here! You've traveled a lot around the Radius, right? Maybe you could be of help.}
{107}{018}{It depends on what do you want to know...}
{108}{020}{Not a whole lot, actually... What's going on here, by the way? Everybody's on their toes.}
{109}{999}{Uh... I'll be back later - need to finish one thing, okay?}


{110}{}{[he irritably pulls his beard] I'm in charge of workshops. For now. What a low thing to do, to be digging around trash heaps... A real man lives only by battle! So don't even think of pestering me about repairing stuff and shit. Ask Carl, he's into it. I already have enough problems here, dealing with the fresh meat like you.}
{111}{012}{Well, I guess your boss knows better who to put in charge and where?}
{112}{013}{If you are meeting the newcomers here, can you tell me how are the things around?}
{113}{015}{I won't be a problem. You can put me to the test.}
{114}{999}{Then I won't be distracting you. See ya.}


{120}{}{[It seems that your words triggered him] Like hell he is! The Jackal, his father - that's who was the real deal. If he hadn't kicked the bucket, we would have already taken over the Olympus itself! And all Loudmouth is able to do is to hysterically scream all the time, spooking everyone around... [he interrupts himself] What I mean is - that's not your business. You'll see the changes. When power here will change...}
{121}{013}{By the way, about Jackals - can you tell me how are the things around?}
{122}{015}{Okay, I see. Another question then - do you have something for me to do?}
{123}{999}{Got it. Okay, I need to go.}


{130}{}{Can't you see? We are the meanest and toughest pack in the whole Radius! Even if the Olympus shits suited in better armor and Rainbow fags carry more batteries in their pockets, we are still going to drown them in their blood eventually! The only thing that matters in battle is this: you are ready either to die or to grind the enemy's throat out with your teeth! And that's something they lack.}
{131}{014}{Oh wow, holy shit, so pretentious! Even I can kick anyone's ass here in a snap of fingers. And you say - Olympus...}
{132}{012}{Uh... Impressive. I guess your boss thinks in the same way?}
{133}{015}{That's why you are the kind of people I like to deal with. By the way, is there something you want me to do?}
{134}{999}{Thanks for the information. I hope to see you in action someday... Well, see you around.}


{140}{}{[Unusually fast for his size, Billy wraps the chain around his fist, pulling out the gun with another hand] I like this place so much. There's always some random asshole who is practically begging to have his head bashed in... }
{141}{998}{Hey, I was just kidding! So difficult to make an actual conversation with you... Okay, let's talk the way you understand.}
{142}{998}{Come on, bitch! Come at me! Let's see the color of your liver!}


{1501}{}{[He looks at you like if you are a squashed cockroach. Or the pile of Lavash shit] What? I won't trust you even with wanking off! A mercenary, my ass... Get some experience first, then yap!}
{151}{014}{Watch it, you son of a bitch. Or you're gonna be pissing with blood.}
{152}{999}{Oh, okay. We'll talk later.}
{1502}{}{[He glares at you, excruciatingly frowning his big furry brows. You can almost hear gears turning inside his head.] Well, uh... I might have something for a rando like you... That's it, listen closely: Loudmouth has this girl named Shiva. She is cool. Let's overlook the fact that nearly every Jackal here made his way into her holes in the past. But then this motherfucker blasted off the heads of some of our guys for her, so now everybody is afraid to even come near. Greedy son of a bitch, it's widely known that his pipe is non-functioning since ancient times, everyone's just scared shiteless to say it loud... Anyway, I've been thinking - why should such a good girl go to waste? So, I decided to pay her a visit. And I need you to keep an eye out for me. If all goes smooth, I'm gonna give you a neat gun. It's much better than batteries. You are no one here without a good weapon. }
{153}{016}{That's it? Sure, I'm in.}
{154}{999}{Uh, no, I don't want to get into a beef with that psycho. I'll pass. And I've got to go.}


{160}{}{Good. Now follow me...}
{161}{999}{[follow him]}


{170}{}{[He zips his pants with a smug look] That damn ass is the best you can find in the whole Radius! Do you want to check on her, by the way? I won't be guarding you though [he laughs]. As agreed - here. [he hands you a weapon pouch made of Lavash skin. It's soaked in oil. You hear parts clanking inside]. You handle the assembly, any dumbass can do it. Carl extended the clip, so if you are not good enough at shooting straight, it should fit you. Definitely will hit something.}
{171}{999}{Now we're talking! Thanks, Billy. I'm already itching to put it to action.}
{172}{999}{Just as we agreed, yes. Good luck. And I've got to go.}


{180}{}{[He bashes his fist into the center of the map] We are going to war with Olympus! As soon as I deal with the assholes, who still don't get who's in charge here now, I will pillage this fucking tower and burn it to the ground! It should become a memorial for the fury of Sunset Jackals! We deserved this - and we waited too long!}
{181}{999}{Are you serious? Ahem... I would gladly help, but I've never been to the Olympus. Well, good luck to you.}
{182}{014}{You are not going anywhere, mutt. And I hope your decapitated head on a spike will be enough to make the rest forget about assaulting Olympus once and for all.}
{183}{019}{Hah! Great idea, count me in. Tell me when you are ready, I'll try to get you there through the roundabouts. }


{190}{}{[He slams his huge palm into your shoulder] Now we're talking! I'll send a man for you when I'm done restoring order here. If you'll do everything well - I'll let you pick anything you want from the loot. First in a row, right after me. }
{191}{999}{Deal. I'll be waiting for your signal. And now I have some things to do...}


{200}{}{[Fiendishly squints] That's because every piece of scum here, who was kissing Loudmouth's ass, began to twitch when he got wrecked. And they should - I'm gonna skin their asses alive if they flinch! It's time for Jackals to follow the real pack leader!!}
{201}{014}{You mean YOU? Even Lavash with a wounded head fits the leader's role better!}
{202}{999}{Let's see how it turns out... See you around, Billy.}