##############################
#Локация: Псы Заката
#Имя: Карл
#Краткое описание: Престарелый ремонтник на базе Псов Заката.
#Дата создания: 24.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a senile old man.}
{2}{}{His hands are shaking very badly, but he still stubbornly tries to assemble something.}
#
# после знакомства
{3}{}{You see Carl.}
{4}{}{Local handyman, specializing in repairings of everything here.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Seems like he doesn't give you much attention, continuing with his work] What is it, young lad? Broke something?}
{11}{002}{Actually, I'm new here...}
{12}{004}{I'm looking for someone responsible for fixing things.}
{13}{999}{No, I was just coming by.}


{20}{}{Yeah, yeah... See? New here and already broke something. Youth these days... What's your name?}
{21}{003}{Uh, }
{22}{003}{, and I didn't break anything.}


{30}{}{Okay then, nice job, }
{31}{}{! I'm Carl, I'm kind of a leading repairman here. You know, armored vests, rifles and such - that's all me.}
{32}{010}{Great! I need to ask something.}
{33}{999}{Oh, I see. Glad to meet you, see you around then.}

{40}{}{Node004}
{41}{}{Oh wow, straight to the point, aren't ya? [he turns around and squints his right eye] Your name?}
{42}{005}{I'm }
{43}{005}{, and I need something.}
{44}{006}{Oh, sorry. I'm }
{45}{006}{.}


{50}{}{[He grins and returns to what he was doing] You're gonna go far, young lad }
{51}{}{! Still, behave yourself, old man Carl can fix your rifle in a way that it'll blow yer hands off, heh-hee! Carl is me, by the way. Come by if you need something.}
{52}{010}{Good, I might need something right now.}
{53}{999}{Got it. See you later, Carl.}


{60}{}{[He visibly loses interest in you and continues his repairings] Oh, don't be. You are a sorry sight to see, young lad. The ones like you don't last long around here without a good piece. If you need something - ask, I'll help with what I can.}
{61}{010}{Uh, yeah. I might need something right now.}
{62}{999}{Okay, thanks. Will keep that in mind.}

{70}{}{Carl, you know, recently there was some accident with one particular warehouse keeper... Would you like to take that position?}
{71}{}{You mean, work for Chris? Weeeell... Yeah, I suppose that lil' parts are worth it! I agree, you can tell Chris that.}
{72}{}{Great. I'll go tell him.}
{73}{}{You mean to go under Chris? Weeeell... Maybe, but... I dunno, the prospects look pretty questionable... I mean, he is one hell of a zit...}
{74}{}{Think about it, and I'll ask another question.}
{75}{}{If I can't talk you into it, maybe batteries will?}

{76}{}{Oh, you are giving me such a difficult choice... Well, okay, for four hundred I'm in, fine.}
{77}{}{Deal! Here's the money [count 400 batteries]}
{78}{}{I don't have so many... I'll go sell something.}

{79}{}{I gathered 400 batteries for you [count 400 batteries]. What about the warehouse?}
{80}{}{[With speed, unbelievable for such an old man, he grabs the batteries from your hand] I agree! You can tell Chris that.}
{81}{}{If I can't talk you into it, maybe batteries will?}
{82}{}{If I can't talk you into it, maybe batteries will?}
{83}{}{If I can't talk you into it, maybe batteries will?}

{100}{}{[He doesn't turn around] You again, young lad? Well? What did you break this time?}
{101}{}{Yeah, sure. Shoot.}
{102}{011}{I need a suit of green armor, like one the Olympus guards wear.}
{103}{020}{You asked me to help with the parts...}
{104}{Renessance}{You have seen a lot in your life. Do you know something about the Renaissance?}
{105}{040}{Can you briefly explain what's what here?}
{106}{050}{What are you always busy with?}
{107}{060}{I still can't make that armor suit...}
{108}{999}{No, nothing. Maybe I'll come by later.}
{109}{}{Yes, I'm looking for one thing... Did you hear about Ultra Repair Kit?}
{113}{070}{Carl, I have something for you to look at... [show him broken water filter engine]}
{114}{072}{You agreed to help me fix the broken engine, remember?}


{110}{}{A green armor?.. Let me think... Oh yeah I remember! You can just go and buy it from one of our vendors! That one, near the entrance! Didn't you realize that yourself?}
{111}{012}{Nah, it's too expensive... Is there any other way to get one? Or something like it?}
{112}{999}{You are actually right, I'll go check upon that vendor.}


{120}{}{Hmm, you want to get yourself a nice suit of armor and not to spend batteries? You know, there *is* a way! I might even help you out, except, you know, there's nothing free in the world... I might have some broken machinery over here, standing idle for a week already. I would fix it myself, but I need the parts, which are in the Chris warehouse. Without the machine I'm doing everything with my bare hands...}
{121}{QA}{I see. In the warehouse, you say? We'll fix your machinery, don't worry.}
{122}{QA}{Yeah-yeah, here we go again, go there, find that... Okay, will do.}
{123}{010}{Oh, I suddenly have a headache... Let's change the subject.}
{124}{999}{What? Go somewhere? Bring something? Nah, I'll do fine without it.}


{125}{}{That's wonderful! You are so acommodating, young lad, everyone else just told me to get the hell off... Uh, don't mind that. That lazy ass Chris already knows I need the parts. So be kind, bring them to me, I'll stand here and wait.}
{126}{999}{Yeah, sure, be right back.}
{127}{999}{Sounds simple. Wait here.}

{130}{}{Did I? Of course I did, that's my kit. Behind these walls they call it Ultra-Duper-Something, when it's just a dozen of different common tools in one pack, heh-heh... Only somehow our boss decided that the thing is too valuable, if so many people talk about it, so he stashed it somewhere. I wouldn't advise you to poke your nose around, searching for it - things might get nasty!}
{131}{}{Thanks for the advice. I'll go think it over.}
{132}{}{We'll see about that. I have another question.}

{200}{}{What? Oh yeah! Sure! Did you get them?}
{201}{999}{I'm still working on it.}
{202}{021}{Yeah, here. I must say this wasn't easy at all.}
{203}{022}{I, uh... I've, erm... Poked around the machine, you know... And it suddenly CLANKED, and then went BRRRRRRR! And I suppose it's fixed now...}


{210}{}{Of course it wasn't! I would get them myself otherwise! You still have a lot to learn, young lad [he gives you a judging look]. So, what are you waiting for? Yeah, like that, give them to me - and now we put this thingie into that thingie with this thingie out... Wait wor it... And now it works!}
{211}{023}{Yeah, great. So - what about the armor for me?}


{220}{}{You WHAT? It can't be! Move, I'll take a look... Holy moly, it really works! How the hell did you do it? You sure don't look like a smart type! Ye rascal, managed to surprise an old man!}
{221}{023}{Nice! So - what about the armor?}


{230}{}{Oh, of course, of course... Now listen, you could just make something which *looks* like the armor, you know? What do you think of that? You'll need only a jacket, a can of green paint... [Carl gives you a long explanation about how to make the fake armor] Here, take the necessary stuff. You definitely can assemble it yourself, I'm sure. No need to thank me! I'm just glad to help out a good fella.}
{231}{999}{Okay, I'll try to handle it.}
{232}{999}{Oh well, thank you for that.}


{400}{}{Why not? We are now standing in the workshop. I'm in charge of fixing things here and Billy Stone is in charge for talking, you know what I'm saying? As he says, as it should be. And his boss is the guy named Loudmouth, our leader and chief. He is kinda nervous one, but you would be too with the customs around here, tee-hee.}
{401}{041}{Who the hell is Billy Stone?}
{402}{010}{I see. I want to ask something else.}
{403}{}{Do not bother me, youngling. It seems you are not stupid, so you'll get how are the things here eventually.}
{404}{010}{I see. I want to ask something else.}


{410}{}{Ooooh, you *are* a green one, aren't ya? Don't talk like this out loud, there are some guys who would bury you for it. Especially Billy himself. But you will easily recognize him - big guy, huge red beard, covered in scars, shattering earth as he steps on it... Tee-hee, just kidding, of course. He is not all covered in scars, maybe only by a half. Some say he can rip a man in two with his bare hands. So be careful getting into a beef with him.}
{411}{010}{Understood, I'll keep that in mind. I want to ask something else.}


{500}{}{Don't you see it by now? Tweaking this, filling that... Mostly, I'm trying to provide our fellas with weapons they can shoot, not dig holes in the ground. Just imagine: you are young dashing Jackal, going to raid, trying to loot something far away from here - and there are some hungry mad creatures ambushing you - RRAWR! And they are biting you legs! And you would be glad to blast their ass off with your favourite sawed-off - but it's jammed! That's when - right before death - you remember that you, for a long time already, didn't take your gun to old man Carl for maintenance...}
{501}{051}{Oh... What a colourful description. Tell me then, what kind of weapons can you fix?}
{502}{010}{Yeah-yeah, don't get carried away. I want to ask something else.}
{503}{999}{Uh, I see. Okay, I need to go - have something to do...}


{510}{}{Uh, all kinds of it [he scratches the back of his head]. I remember when I had to repair rocket launchers, I even assembled miniguns a couple of times from a total scrap... One blew up, actually... Poor Jimmy, such a strong boy he was...}
{511}{010}{Okay, I got that. I want to ask something else.}


{600}{}{Wanna know why? Because you are not stubborn enough. If you would really want it, you'd do it. I'm sure, if there was a gun put to your head, you would be very motivated to figure it out! But if you are not willing to learn, I still could help. The thing is - I have a lot of work on my hands, and not a whole lot of batteries in my pocket.}
{601}{061}{Yeah, I get it. How much?}
{602}{999}{No, thank you. I'll handle it.}


{610}{}{You see, this task is, uh... Specific! I think it'll cost you something around }
{611}{}{ batteries, no less! So, deal?}
{612}{062}{Agreed. Here.}
{613}{999}{Too expensive for me. When I get this much, I'll come back to you.}
{614}{999}{HOW MUCH!? Hell no! You can buy a whole armor suit for that price! I'll better handle it myself.}


{620}{}{[Takes away your batteries and components for a fake armor] Look, it's simple: this thingie into that thingie, a rivet there, tape here, a little more, now put some paint around... add a little dust for aged effect - and would you look at that, won't tell it from real one at first sight! Here you go, klutz [gives you fake armor]}
{621}{999}{Easy to say when you know how it's done... But thanks anyway. I have to go now. See you later, Carl.}
{622}{999}{One pays, the other does the job. Hard to say who is a klutz here. Okay, I've got to go.}
{623}{999}{So neat! Thanks, Carl! Take care!}

{700}{}{As I said - you did broke something, ain't ya? Everything you touch, you break! How you can even be like that? Man, gimme that piece of yours... [he examines engine for some time] ...Yes, just as I suspected... You already toyed with it, right? Did you try to break it on purpose?}
{701}{}{Okay, I'm sick of your crap. [take engine and leave]}
{702}{}{I almost had my arm crooked while trying to pull it out! Can you fix this or not?}

{710}{}{Whaaat!? To fix hands is not my business, young lad. Although you might want to do it eventually, you know... Jokes aside, the job is tough... 300 batteries, no less!}
{711}{}{300? Okay, here goes. Now repair it.}
{712}{}{Where the hell do you think I get money? I'll better try to handle it myself.}

{720}{}{Ghyah! I do remember. Do *you* remember about my 300 batteries?}
{721}{}{Damn, I ran around the whole Radius to gather this much! Here, now repair it.}
{722}{}{Yeah-yeah, soon I'll get the necessary amount.}

{730}{}{[mocks you]..."Now repair it", of course, princess... [Carl puts a screwdriver to the side of engine and starts to smash it with a hammer, until some piece of metal breaks off the mechanism with a funny clinking sound.] Phew, barely! This thing alone costs around one hundred batteries! [He continues to poke insides of engine. After some time he ceremonially returns it to you] Here you go, lad! Use with caution! And when you break it again...}
{731}{}{Yeah, I remember - "300 batteries" [take engine]}
{732}{}{No way in hell! I'll handle it myself next time... [take engine]}