##############################
#Локация: Псы Заката
#Имя: Кайл 
#Краткое описание: Завскладом, хитрожопый вымогатель
#Дата создания: 19.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a man with a cute smile.}
{2}{}{He checks up his batteries - bites them, licks his fingers and touches the contacts.}
#
# после знакомства
{3}{}{You see Kyle.}
{4}{}{He looks at you with a warm smile of hyena.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[you see a raunchy, simple man from wasteland. He can equally fit in any settlement in Radius] Hey mate, aren't you in need of excellent package of military dry rations! In great condition, only for 300 batteries, the whole 20 packs in a package! Special one-in-a-lifetime offer, only because you reminded me my brother. Whaddaya say?}
{11}{002}{No. }
{12}{003}{What?}
{13}{004}{HOW MUCH?}
{14}{005}{Sure. Always dreamed of breaking my teeth in such extravagant way.}


{20}{}{[he wrinkles his face, but only for a moment] This kind of deal you won't find anywhere. I'm Kyle. I'm in charge of this warehouse. Wanna buy something?}
{21}{010}{No, I don't. I have some questions.}
{22}{010}{Not now. I have some questions.}
{23}{Barter}{Okay, show me what you have.}


{30}{}{Military dry rations, I said. Twenty packs, fifteen batteries each. Will keep the hunger away in a long road. Just remember not to open every pack right away... They can get spoiled pretty fast, when exposed to air.}
{31}{002}{No. I think I'm good.}


{40}{}{Three hundred.}
{41}{002}{[laugh]}
{42}{002}{No, thank you.}


{50}{}{The quality is top notch, I tell you! Anyway, I have lots of other useful stuff here, wanna look?}
{51}{010}{No, I don't. I have some questions.}
{52}{010}{Not now. I have some questions.}
{53}{Barter}{Okay, show me what you have.}


{1001}{}{So, you came back to do a little bit of shopping?}
{1002}{}{Make it quick. I won't make any profits only from talking.}
{101}{Barter}{Let's see what you have.}
{102}{011}{Listen, I've recently stumbled onto this pistol part. Here, take a look. Maybe you have other one?}
{103}{018}{I want to ask about...}
{104}{019}{Do you know that Chris wants you dead?}
{105}{999}{Although, let's talk another time.}



{110}{}{[trader carefully examines the part] Yeah, I actually have something like this: a drum for some huge revolver! Have been keeping it for quite some time already. The thing is rare, but these should fit together nicely. So - two hundred, no bargain.}
{111}{012}{Okay, deal.}
{112}{010}{I need to think about it. Let's talk something else.}
{113}{013}{Listen, your part is only one of several. There are no guarantees, that I'll manage to find each. Let's make the price more reasonable. One hundred and fifty. You'll get rid of an old junk and make a good profit out of it.}
{114}{999}{I don't have so many right now. I'll be back.}


{120}{}{Great. Here's your part, take it. Anything else?}
{121}{010}{Yes, I have some questions.}
{122}{999}{No, thanks. I'll go.}


{130}{}{One hundred and eighty. Not a battery more.}
{131}{014}{One hundred and seventy.}
{132}{013}{One hundred and sixty.}
{133}{015}{One hundred and seventy. And you include this one as a spare part [point into an old pneumatic pistol].}
{134}{012}{Deal.}


{140}{}{Okay, I'm convinced. Here's your part. Something else?}
{141}{010}{Yes, I have some questions.}
{142}{999}{No, thanks. I'll go.}


{150}{}{[quietly mumbles] You are just like that old skinflint uncle Joseph... One hundred and seventy five, and a gun as a spare part.}
{151}{017}{One hundred and seventy. And a gun as a spare part. }
{152}{016}{Deal.}


{160}{}{[he takes your batteries and gives you drum and gun] Anything else?}
{161}{010}{Yes, I have some questions.}
{162}{999}{No, thanks. I'll go.}


{170}{}{You are bleeding me dry!}
{171}{016}{It's an act of outstanding generosity!}


{180}{}{You know, I don't give a shit what you want. Shi-et. Don't care. Either buy, or get the hell away. }
{181}{Barter}{Okay, show me the goods.}
{182}{999}{You can go eat it with manners like that. I'll go buy in some other place.}
{183}{999}{[leave]}



{190}{}{[he makes a laugh] I know too much about Chris. Of course he wants to keep his secrets.}
{191}{020}{Why is he so hostile towards you?}
{192}{998}{Yes. And he hired me. Goodbye.}




{200}{}{Chris is crazed cleptomaniac. He told Loudmouth some tales about finding stash with the guns, while this was, in fact, our own stash! When I did inventory on the new stuff, I recognized one rifle that some junkie sold to me a day before. It had a letters "SFE" engraved on it.}
{203}{021}{What? What stash? What are you talking about? Are you high?}
{201}{998}{I don't believe you. Time to die!}
{202}{999}{Hmm, I'll think about it...}

{210}{}{Hah, you don't believe me? Me, honest trader?! Go check it yourself, there's nothing left there by now anyway [he gives you a piece of paper with a route to some cave].}
{211}{998}{Yeah, I'll check... But you should still die! [take out your weapon]}
{212}{999}{You know, I'll do exactly that. See you later.}