##############################
#Локация: Псы Заката
#Имя: Каспер 
#Краткое описание: Тролль, лжец и говнюк
#Дата создания: 16.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a guy looking like he was often beaten up in his childhood.}
{2}{}{He reminds you of rat. Big, disgusting rat.}
#
# после знакомства
{3}{}{You see Casper.}
{4}{}{You are very keen on reducing the amount of teeth in his mouth.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{5}{}{You little bitch! Casper told me everything about you!!}
{6}{}{Fucking shithead! Casper told me everything! You are deadman!!}
{7}{}{Hey, bitch, what were you saying about me?! Casper told me EVERYTHING!}
{8}{}{Wait, stop! Don't kill me!! You win...}

{10}{}{[You see a skinny little fella with an ugly look and annoying smirk] Whatcha lookin' at, arsehole?}
{11}{002}{Hello to you too, runt.}
{12}{003}{Watch your mouth or you're get your teeth kicked out.}
{13}{004}{Who the hell are you?}


{20}{}{Either you have no brains at all, you imbecile, or just eager to die. I'm not someone you could talk like that. I'll look past your fuckin' stupidity for this time. I'm Casper, a bookmaker. Appointed by Loudmouth himself.}
{21}{005}{So you can take bets then?}
{22}{006}{A bookmaker? You? Don't make me laugh.}
{23}{998}{It's time to teach you some manners... [attack]}


{30}{}{You shite, it's you who'll get your mouth caved in, if you talk like that. I'll look past your fuckin' stupidity for this time. You can adress me as "Mister". I'm Casper, a bookmaker. Appointed by Loudmouth himself.}
{31}{005}{So you can take bets then?}
{32}{006}{A bookmaker? You? Don't make me laugh.}
{33}{007}{"Mister"? "I'll look past it for the first time"? Are you fucking want to die?}
{34}{998}{It's time to teach you some manners... [attack]}


{40}{}{I'm a bookmaker. Taking bets, setting fights, fucking girls, picking on arseholes like you.}
{41}{008}{You are so adorable. Can I call you "sweetie"?}
{42}{998}{And I am some guy from wasteland, who will now take away your ability to do all that. [attack]}
{43}{009}{Wow. I haven't talked to such high-grade shit for a really long time.}
{44}{010}{Uh-huh. I have some questions.}


{50}{}{Yes. But not today. Today all bets are done. Plus, an outsider like you should purchase a subscription first, heh-heh. A contribution fee is 1000 batteries, for the development of hand-to-hand combat entertainment industry in this wonderful area.}
{51}{011}{You mean, for encouranging your drinking habits and whores.}
{52}{012}{Thousand? You want jam on it?}
{53}{013}{Okay, here's my donation. When I'll be able to make bets?}
{54}{014}{Too much. Not interested.}
{55}{999}{I'll better go spend the money on something more valuable.}


{60}{}{[He smirks] Yes, exactly. ME. I think we're done here. Or do you have any questions?}
{61}{010}{Yes, I do.}
{62}{999}{No, I don't. [end the dialogue]}
{63}{999}{I'm starting to disrespect myself while I talk to a dirt like you. I'm going.}


{70}{}{[He smirks, showing wide row of teeth] I think we're done here. Or do you have any questions?}
{71}{010}{Yes, I do.}
{72}{999}{No, I don't. [end the dialogue]}
{73}{999}{I'm starting to disrespect myself while I talk to a dirt like you. I'm going. }


{80}{}{No. Do you have other questions?}
{81}{010}{Yes, I do.}
{82}{999}{No, I don't. [end the dialogue]}


{90}{}{[He algrily looks at you] Do you have other questions?}
{91}{010}{Yes, I do.}
{92}{999}{No, I don't. [end the dialogue]}


{100}{}{Whaddaya want?}
{101}{}{So?}
{102}{018}{About Vince...}
{103}{005}{You were mentioning bets...}
{104}{033}{What's with the bets? When's next fight?}
{105}{034}{How much you made on my fight, fuckface?}
{106}{032}{The weather is shitty to day, don't you think?}
{107}{036}{I kicked the shit out of Stan.}
{108}{999}{I gotta go.}
{109}{038}{About the fight with that ape - I'm ready.}



{110}{}{[He loudly laughs] This doesn't concern you, fuckin' cock. I'm here the mutherfuckin' sports and gambling minister, and you are fuckin' no one.}
{111}{998}{I'm so sick of you. Let's see now who is "no one"...}
{112}{999}{[wave your hand and leave]}
{113}{010}{Nice. I have some questions.}


{120}{}{Jam is on the dicks you ate this morning. Either pay, or get the fuck away.}
{121}{998}{I'm so sick of you. Let's see now who gets the fuck away...}
{122}{999}{[wave your hand and leave]}
{123}{010}{Nice. I have some questions.}
{124}{013}{Okay, here's my donation. When I'll be able to make bets?}
{125}{014}{Too much. Not interested.}
{126}{999}{I'll better go spend the money on something more valuable.}


{130}{}{[Casper counts the batteries and puts them into a shoulder bag] Good. No bets today. Maybe they'll be availabe next week. Come by later.}
{131}{017}{Hey! You didn't say I'll be able to make bets only the next week!}
{132}{010}{Okay, I have some questions.}
{133}{015}{Next week? Give me my money back!}


{140}{}{Stop fuckin' around then, smart-ass. }
{141}{010}{I want to ask...}
{142}{999}{I'll better go take a walk.}


{150}{}{I have a better idea. I'll knock on your forehead with my dick. What do you think about that?}
{151}{998}{I'm gonna fuck you up so hard that you won't feel your dick anymore! [attack]}
{152}{016}{You are such a bitch.}
{153}{010}{Okay, let's get back to the questions...}
{154}{999}{[spit on the ground and walk away]}


{160}{}{[He smirks, showing wide row of teeth] I think we're done here. Or do you have any questions?}
{161}{010}{Yes, I do.}
{162}{999}{No, I don't. [end the dialogue]}
{163}{999}{I'm starting to disrespect myself while I talk to a dirt like you. I'm going. }


{170}{}{Tough times, you know.}
{171}{016}{You are such a bitch.}
{172}{010}{Okay, let's get back to the questions...}
{173}{999}{[spit on the ground and walk away]}


{180}{}{The bets are done until the end of fight.}
{181}{019}{I'd like to talk about some conditions. About the fight.}


{190}{}{Really?}
{191}{020}{I think I see a possibility to make money. You could take a second round of bets. Stan against me. I'll easily do him. You're going to make easy profits. Stan won't be able to fight properly after that, so Vince should be able to take him down with little to no effort. And everyone usually bets on Stan, so you are going to make even more cash. Twice in a row.}
{192}{021}{How much profit do you have on bets?}
{193}{027}{I want you to put me against Stan before his fight with Vince. Or even put me instead of Vince.}


{200}{}{[Casper ponders, rolling his eyes. Probably he's counting possible profits.] Fuck yeah! Deal. Are you ready to do it now, or you need to prepare?}
{201}{038}{Ready.}
{202}{999}{I need to prepare. Be right back.}


{210}{}{Thousand batteries. }
{211}{022}{If I pay you thousand and hundred extra, would you cancel the fight?}


{220}{}{[Casper ponders, rolling his eyes. Probably he's counting possible profits.] Three hundred extra. I'll have to deal with issues about canceling the fight. And nothing calms my nerves more than the money.}
{221}{023}{Deal.}
{222}{024}{I have only thousand. I didn't expect to spend more.}
{223}{025}{I have only thousand. I didn't expect to spend more.}
{224}{999}{Okay. I'll go get the money and come back.}


{230}{}{[Casper counts the batteries and puts them into a shoulder bag] Great. Consider the fight canceled. Something else?}
{231}{010}{I have some questions...}
{232}{999}{No, that's it. I'm going.}


{240}{}{[Casper bites his lip and scratches his head.] Deal. Give me your thousand!}
{241}{026}{[give the batteries]}
{242}{999}{Wait, I need to think...}


{253}{}{No. Pay in full or get the fuck out.}
{250}{023}{Deal.}
{251}{999}{Wait, I need to think...}
{252}{999}{Okay. I'll go get the money and come back.}


{260}{}{[Casper counts the batteries and puts them into a shoulder bag] Great. Consider the fight canceled. Something else?}
{261}{010}{I have some questions...}
{262}{999}{No, that's it. I'm going.}


{274}{}{[Casper critically looks at you] Well... Maybe. I'm still ging to have some troubles changing the conditions of a fight. It's gonna cost you... Six hundred batteries.}
{270}{028}{Deal.}
{271}{029}{I have only five hundred. I didn't expect to spend more.}
{272}{030}{I have only five hundred. I didn't expect to spend more.}
{273}{999}{Okay. I'll go get the money and come back.}


{280}{}{[Casper counts the batteries and puts them into a shoulder bag] Great. I'll make arrangements. Are you ready to do it now, or you need to prepare?}
{281}{038}{Ready.}
{282}{999}{I need to prepare. Be right back.}


{290}{}{[Casper bites his lip and scratches his head.] Deal. Give me your five hudred!}
{291}{031}{[give the batteries]}
{292}{999}{Wait, I need to think...}


{303}{}{No. Pay in full or get the fuck out!}
{300}{028}{Deal.}
{301}{999}{Wait, I need to think...}
{302}{999}{Okay. I'll go get the money and come back.}


{310}{}{[Casper counts the batteries and puts them into a shoulder bag] Great. I'll make arrangements. Are you ready to do it now, or you need to prepare?}
{311}{038}{Ready.}
{312}{999}{I need to prepare. Be right back.}


{320}{}{Such a great topic! For bitches. Go bother somebody else with your bullshit.}
{321}{010}{I have other questions.}
{322}{999}{[end the dialogue]}


{330}{}{The fight ended just before you came. The next one will be on this week. You should come here more often.}
{331}{010}{[swear]}
{332}{999}{[swear and leave]}


{340}{}{Enough for me.}
{341}{998}{Enough? Enough?! I'm going to shake all my batteries out of you!!}
{342}{035}{Don't even think about doing something like this again. Or I'll beat you up so hard no one will be able to recognize you.}
{343}{999}{[spit on the ground and leave]}


{350}{}{Uh-huh. Get lost.}
{351}{999}{[end the dialogue]}
{352}{998}{[throw a punch into his nose]}


{360}{}{Good boy. Pat yourself on the back.}
{361}{037}{What, no batteries for me? You made good profits on this fight.}
{362}{999}{[wave hand and leave]}


{372}{}{No. Maybe you want me to hug you and tell everyone what a great guy you are?}
{370}{010}{Ha-ha. Funny. Nevermind, better answer some questions.}
{371}{999}{[wave hand and leave]}


{380}{}{Okay. Follow me.}
{381}{999}{[follow Casper]}