##############################
#Локация: Псы Заката
#Имя: Крис Мурена
#Краткое описание: Завскладом
#Дата создания: 21.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a typical robber.}
{2}{}{He nervously holds onto the grip of his pistol.}
#
# после знакомства
{3}{}{You see Chris.}
{4}{}{He twitchingly chews lips, bites nails, touches his gun and pokes rivets on his armor.}

{5}{}{Get this fucking shit out of your hands, now! No second chance!}
{6}{}{A hasty one, huh!? Want to put me down, huh!? I'll fucking put YOU down!!}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a man in his thirties. He is constantly scanning his surroundings with a tense look, getting jumpy from every rustling sound he hears. His hand rests on holster, ready to pull out the gun at any moment] Who're you? What do you want?}
{11}{002}{I was just coming by.}
{12}{002}{I'm here on important mission.}
{13}{002}{Only a traveler.}
{14}{002}{I'm looking for someone.}
{15}{002}{None of your business.}




{20}{}{[As you open your mouth, he immediately interrupts] Before you say something, I'm warning you, I don't like when someone waves his weapon in front of my face. You do have a weapon, right? Do you?}
{21}{005}{Yes, I carry it with me everywhere.}
{22}{003}{Yes, I do. [show him your weapon]}
{23}{004}{No, I have nothing on me now.}
{24}{006}{I'm actually against violence. I don't use weapons.}




{30}{}{Fuck, I warned you not to flail your fucking weapon around, you asshole!!}
{31}{998}{But I just wanted to show it...}




{40}{}{[He suspiciously looks at you] Yes, sure, I get it, you don't show your aces in the hole to everyone. So don't pull it out and everything's gonna be alright, alright? I'm Chris Murena. What do you want from me?}
{41}{010}{I wanted to ask a couple of questions.}
{42}{999}{Nothing, I was looking for someone else. Bye.}




{50}{}{That's good, that's understandable. You wouldn't make it very far without a weapon. Don't pull it out and everything's gonna be alright, alright? I'm Chris Murena. What do you want from me?}
{51}{010}{I wanted to ask a couple of questions.}
{52}{999}{Nothing, I was looking for someone else. Bye.}


{60}{}{[He looks surprised] How did you make it so far in here without a weapon? I suggest you get yourself some big fucking piece, the bigger the better, or you're gonna get squashed fast. I'm Chris Murena. What do you want from me?}
{61}{010}{I wanted to ask a couple of questions.}
{62}{999}{Nothing, I was looking for someone else. Bye.}


{1001}{}{The hell do you want?}
{1002}{}{[Chris suspiciously looks at you] What do you want this time?}
{101}{011}{Why are you so afraid of weapons?}
{102}{013}{Tell me about yourself.}
{103}{025}{I'd like to talk about Kyle.}
{104}{032}{I need the spare parts for a workshop machine.}
{105}{999}{I don't need anything right now. Bye.}


{110}{}{I trust no one, you included. I have too many enemies - and they are watching me, waiting for a moment to stab me in the back. Every single damn one here wants to take my place. That's why I don't let anyone to go near me with weapon in his hands.}
{111}{013}{What is it that you do?}
{112}{012}{What will happen if I pull out the gun?}
{113}{003}{What if I do this? [pull out your weapon]}


{120}{}{[Chris immediately flips out] Don't you fucking dare! You'll end up dead here right now!}
{121}{010}{Okay, okay, easy. Let's just talk.}
{122}{003}{Let's check. [pull out your weapon]}
{123}{999}{You are kind of twitchy. I'll better go.}


{130}{}{I'm the Loudmouth's right hand. I'm in charge for this warehouse, which contains weapons, which means that *everything* here depends on me. Because gun is the most valuable thing in the world. Loudmouth has two other assistans, Oswald and Billy. They think they are important.}
{131}{018}{Tell me about Billy.}
{132}{031}{Who is Oswald?}
{133}{014}{I want to hear more about Loudmouth.}
{134}{019}{Can you sell me something from the warehouse?}
{135}{010}{Let's change the subject.}
{136}{999}{I have some things I need to do. We'll talk later.}


{140}{}{Loudmouth runs this place. He is the most ruthless man I've ever encountered. He is fucking nuts, but everyone do as he says, because the other option is a bullet between the eyes with no questions asked. }
{141}{015}{How dangerous is he?}
{142}{016}{What if I tell him about how you badmouth him here?}
{143}{010}{I want to ask about something else.}


{150}{}{As dangerous as hungry Ursa in his mating season. He can shoot you dead just for a little grin. That's why everyone here wait for him to just die already.}
{151}{017}{What would happen if he died?}
{152}{016}{He won't be glad to learn about your opinion about him.}
{153}{010}{Let's change the subject.}


{160}{}{[The corners of his lips slowly moved upward by a tiny bit. Seems like it is his maximum ability to manifest positive emotions] You can tell him anything you want! He won't listen to you anyway. One my word against yours - and you are feeding the worms. Most likely, Loudmouth will blast your head off by himself. Go try it.}
{161}{017}{You mentioned that Loudmouth's going to die soon. What happens then?}
{162}{999}{I'll go tell him anyway. We'll see the rest.}


{170}{}{[Chris moves closer to you, his sight still nervously assessing the surroundings] I'm gonna tell you a secret, a little one that is: after he dies, it's gonna be a struggle for a leader's position. There are three candidates - me, Oswald and Billy, and of course I'm gonna become the one in charge. But there will be blood.}
{171}{018}{Billy? Who is that?}
{172}{031}{Tell me about Oswald.}
{173}{020}{What would happen if you are in charge of the Jackals after Loudmouth's death?}
{174}{014}{Tell me more about Loudmouth.}
{175}{010}{I wanted to ask something else.}



{180}{}{Billy Stone, a stupid thug. Loudmouth put him responsible for workshops, but everyone's aware that this brainless idiot knows as little shit about repairing as about being in charge. You could grind stones into sand with his head. }
{181}{031}{What can you tell me about Oswald?}
{182}{014}{Tell me more about Loudmouth.}
{183}{010}{I wanted to ask something else.}


{190}{}{Speak to my assistant Kyle, he is handling the trades, fucking prick. This asshole is always trying to squeeze as much profits from everyone as he can, he's ready to sell his own mother for an extra battery. I bet he already did.}
{191}{021}{I see you are not quite fond of him.}


{200}{}{I have my plans about this place. And I'm not going to share them with you.}
{201}{010}{Okay. Another question then.}


{210}{}{I fucking hate him! [He stops and starts staring at you, mumblig something] Hm, a new man, no suspicions... [louder] This moron wants to take my place, he spreads stupid rumors about me and such. I would shoot him myself, but Loudmouth is against it. And he knows. So if Kyle dies, that's my doing. I don't need that. If you wanna make a quick profits, you could assist me.}
{211}{022}{What do you want me to do?}


{220}{}{[Chris whispers] Put this fucking prick down and you'll get rewarded. But no one should know we had this talk! And find someone to replace him, I won't handle the things here by myself. If you do that and won't rat on me, I'm gonna make you very happy.}
{221}{024}{Agreed. I'll put Kyle down and find a replacement for him.}
{222}{023}{No, I don't want to be a part of it.}


{230}{}{Suit yourself, if you change your mind, let me know. }
{231}{999}{Sure. I will definitely come to you then.}


{240}{}{Great! I'm waiting for the news. And know this - everything he says about me is a dirty fucking lie!}
{241}{999}{I'll go find Kyle and deal with him.}


{250}{}{[Chris looks at you, waiting for you to start talking.]}
{251}{027}{Kyle is dead. And you are beyond suspicions.}
{252}{026}{Remind me of what I should do.}
{253}{030}{Kyle told me that you are stealing weapons from the warehouse.}
{254}{999}{I've just remembered something. Got to go, bye!}


{260}{}{Are you kidding me? I told you to kill him off! Put this asshole down, find a replacement on the warehouse duties. Then come back.}
{261}{999}{Okay.}


{270}{}{[His voice fills with satisfied overtones] I've heard. You did good - Kyle is dead, I have nothing to do with it. Clever! Did you find a replacement?}
{271}{029}{Yes. Carl agreed to be your assistant.}
{272}{028}{Not yet, I'm still searching.}


{280}{}{Talk to the folks around, someone should say yes. When you find a volunteer, get back to me.}
{281}{999}{Sure.}


{2901}{}{Carl will make a great assistant! You are very good at what you do. Here's your reward, as I promised - it's an awesome kit for gun repairing.}
{2902}{}{Carl will make a great assistant! You are very good at what you do. Here's your reward, as I promised - it's an awesome kit for gun repairing. Also, here are the spare parts for some machinery, you could sell it to some tech for a good profit.}
{291}{999}{Thanks, Chris.}


{300}{}{I told you this prick will say and do anything to take my place! Did he tell you about the SFE letters on a rifle? He's the one who made it up! Go and finish the job with this motherfucker, bring me the good news.}
{301}{999}{Okay, I'll go deal with it.}


{310}{}{This snob Oswald Brown handles the freshmen and runs the barracks. Never met a man more cheeky and arrogant. Thinks of himself as a great leader. Let him. That's until some titsucker with baby gun makes a hole in his belly.}
{311}{018}{What can you tell me about Billy?}
{312}{014}{Tell me about Loudmouth.}


{320}{}{Yeah, I have the parts. If you need them, you're gonna do something for me.}
{321}{033}{There's no time! Carl urgently needs to get his machinery repaired, that's direct order from Loudmouth himself! If he does it on time - depends on you. And also, it depends on you what will Carl tell to Loudmouth - that you helped, or got in the way.}
{322}{034}{What do you want me to do?}
{323}{035}{What do you want me to do?}
{324}{999}{I'll go find the parts somewhere else. Bye.}


{330}{}{If that's what Loudmouth said, sure, take it, take it away. I don't want this psycho to start shoot everyone in his sight again.}
{331}{999}{Okay, I'll go handle the fixing until it's too late.}


{340}{}{As I said, you should put Kyle down and get someone to replace him in the waregouse. Then you'll get your parts. And something extra.}
{341}{999}{Okay, I'll go do that.}


{350}{}{There's this one dick helping me with trading duties. His name is Kyle and he pisses me off.}
{351}{021}{I see you are not quite fond of your assistant.}


{360}{}{Loudmouth is dead! And Billy with Oswald are out of the picture! Now I'm the leader of the Jackals! [Chris interrupts himself and starts to twitchy look around himself, even more nervously than usual] Shit, shit! It means that there are much more people who will want to take my place!! From every snot to experienced ones... Oh fuck, oh shit, oh fuck, why I didn't think about it earlier... Man, I would trade it all for a warm calm spot in the Olympus without second thoughts...}
{361}{010}{I think nothing has actually changed. Well, let me ask something else.}
{362}{999}{Congratulations. I'll better go now. Bye.}