##############################
#Локация: Псы Заката
#Имя: Гарри
#Краткое описание: Мясник и повар
#Дата создания: 23.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a man dressed like butcher.}
{2}{}{Despite trying to look like local cook, he is more resembling of a pirate from children's books.}
#
# после знакомства
{3}{}{You see Harry.}
{4}{}{He scratches his butt with a hook.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see a big hairy man with glum expression on his face. He has a hook instead of his hand. His clothes are pretty stained and dirty, but you can easily identify him as a cook by his apron. To complete picture he lacks only a chef's hat.]}
{11}{002}{Hey.}
{12}{999}{[don't start the conversation]}


{24}{}{Who're you?}
{20}{003}{I'm }
{21}{003}{. }
{22}{003}{Billy.}
{23}{005}{Why does it matter? }


{30}{}{I'm Harry [he scratches his chin with a hook]. I mince meat and make food. What do you want?}
{31}{004}{You have a nice hook there.}
{32}{Barter}{I wouldn't mind buying some food from you... [barter]}


{40}{}{Yeah.}
{41}{010}{Uh... Okay, I want to ask something.}
{42}{999}{Uh... Okay, I'll come back later.}


{50}{}{It doesn't. I really don't give a shit. Gonna call you "the feces" in my mind anyway. What do you want?}
{51}{010}{The feces? Perfect. I have a couple of questions, captain Hook.}
{52}{999}{The feces? Not the worst thing I've heard. Okay, I've got to go. Was nice meeting you.}


{100}{}{Howdy. What do you want?}
{101}{}{Ask away.}
{102}{011}{Listen, do you have some work for me? Must clarify - I'm not good at cooking.}
{103}{015}{About the whetstone...}
{104}{019}{What's the deal with the hook?}
{106}{Barter}{I wouldn't mind buying some food from you... [barter]}
{107}{999}{Okay, I've got to go. See you.}


{110}{}{Are you serious? Asking the cook for a job not on a kitchen? Don't you think it's kinda stupid?}
{111}{012}{Well, maybe you need someone to be put down.}
{112}{012}{Well, maybe you need something delivered.}
{113}{012}{Well, you know, just asking.}


{120}{}{You know, I think I might have something for you. Not a trivial task. I have a... Special approach to sharpening my kitchen tools [he scratches himself with the hook again]. I need a whetstone. A good one, not some piece of shit like that ones [Harry points at the table with some stones lying around]. So you'd understand - here [he shows you a shard of stone in his hand]. I need one like this, but new. }
{121}{013}{Where do I look for it?}
{122}{014}{How much do you pay?}
{123}{010}{Okay, if I'll come by one, I'll be back. For now I have some questions.}
{124}{999}{Okay, if I'll come by one, I'll be back. Later.}


{130}{}{[He puts hook on his chin with thoughtfull look] Well... It's a stone. The stones can be found in caves. The caves are made out of stones, don't they?}
{131}{014}{I see. How much do you pay?}
{132}{010}{Okay, if I'll come by one, I'll be back. For now I have some questions.}
{133}{999}{Okay, if I'll come by one, I'll be back. Later.}


{140}{}{If the stone is right and the quality is good - two hundred. Wanna haggle? Go to traders. If you don't like my price, remember that it's not me who came asking for work.}
{141}{013}{I didn't even try to bargain... And where should I look for such stone?}
{142}{010}{I didn't even try to bargain... Okay, if I'll come by one, I'll be back. For now I have some questions.}
{143}{999}{I didn't even try to bargain... Okay, if I'll come by one, I'll be back. Later.}


{153}{}{Well?}
{150}{016}{I found a whetstone for you. }
{151}{017}{Yeah, I wanted to ask if you had any thoughs where to look for the stone.}
{152}{018}{Is there the only one stone left in the whole fucking Radius?}


{160}{}{Let me see... [he carefully examines the stone you found, then puts it away] Yeah, looks like it's just what I need. I have one problem though. The business is not going great lately, so I'm low on batteries. But I have something better for you - one of my best butcher knives. Here. [he takes off a huge knife from his belt and gives it to you]}
{161}{010}{[take the reward] I have some other questions.}
{162}{999}{[take the reward] Great, thanks. If there's something else I can do - just tell me.}


{170}{}{No. Is that it?}
{171}{010}{I have some other questions to ask...}
{172}{999}{...I'd better go continue searching.}


{180}{}{Possibly not. But I would pay you jack shit if it was easy to find. }
{181}{010}{I have some other questions to ask...}
{182}{999}{I'll better go continue searching.}


{190}{}{Why do you care? Want yourself one like that? I can chop off your hand. The hook you'll have to find yourself.}
{191}{020}{I think I'm fine, thank you. }
{192}{020}{Hah. You are so funny. [say it with a blank face]}


{200}{}{What I'm trying to say is this - it's none of your business. }
{201}{010}{I have some other questions to ask...}
{202}{999}{I'd better go.}