##############################
#Локация: Псы Заката
#Имя: Гарри
#Краткое описание: Мясник и повар
#Дата создания: 23.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a man dressed like butcher.}
{2}{}{Despite trying to look like local cook, he is more resembling of a pirate from children's books.}
#
# после знакомства
{3}{}{You see Harry.}
{4}{}{He scratches his butt with a hook.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[You see big hairy man with glum expression on his face. He has a hook instead of his hand. His clothes are pretty stained and dirty, but you can easily identify him as a cook by his apron. To complete picture he lacks only a chef's hat.]}
{11}{002}{Hey.}
{12}{999}{[don't start the conversation]}


{24}{}{Who're you?}
{20}{003}{I'm }
{21}{003}{. }
{22}{003}{Billy.}
{23}{005}{Why does it matter? }


{30}{}{I'm Harry. [he scratches his chin with a hook] I mince meat and make food. What do you want?}
{31}{004}{You have a nice hook there.}
{32}{Barter}{I wouldn't mind buying some food from you... [barter]}


{40}{}{Yeah.}
{41}{010}{Uh... Okay, I want to ask something.}
{42}{999}{Uh... Okay, I'll come back later.}


{50}{}{It doesn't. I really don't give a shit. Gonna call you "the feces" in my mind anyway. What do you want?}
{51}{010}{The feces? Perfect. I have a couple of questions, captain Hook.}
{52}{999}{The feces? Not the worst thing I've heard. Okay, I've got to go. Was nice meeting you.}


{100}{}{Howdy. What do you want?}
{101}{}{Ask away.}
{102}{011}{Listen, do you have some work for me? Must clarify - I'm not good at cooking.}
{103}{015}{About the whetstone...}
{104}{019}{What happened to your hand?}
{106}{Barter}{I wouldn't mind buying some food from you... [barter]}
{107}{999}{Okay, I've got to go. See you.}




{110}{}{Are you serious? Asking the cook for a job not on a kitchen? Kinda stupid, don't you think?}
{111}{012}{Well, maybe you need someone to be put down.}
{112}{012}{Well, maybe you need something delivered.}
{113}{012}{Well, you know, just asking.}


{120}{}{You know, I think I might have something for you. Not a trivial task. I have a... Special relationship with a process of sharpening my kitchen tools. [he scratches himself with the hook again] I need a whetstone. A good one, not some piece of shit like that ones [Harry points at the table with some stones lying around]. So you'd understand - here [he shows you a shard of stone in his hand]. I need the one like this, but new. }
{121}{013}{Where do I look for it?}
{122}{014}{How much do you pay?}
{123}{010}{Окей, тогда если подвернется - я загляну к тебе. А сейчас у меня есть пара вопросов.}
{124}{999}{Окей, тогда если подвернется - я загляну к тебе. Бывай.}


{130}{}{[задумчиво водит крюком по подбородку] Ну-у... Это же камень, так? А камни бывают во всяких пещерах. Пещеры же состоят из камней, как думаешь?}
{131}{014}{Ясно. Сколько платишь?}
{132}{010}{Окей, тогда если подвернется - я загляну к тебе. А сейчас у меня есть пара вопросов.}
{133}{999}{Окей, тогда если подвернется - я загляну к тебе. Бывай.}


{140}{}{Если камень будет такого качества, как я показал - две сотни. Не больше. Если хочешь поторговаться - иди к торгашам. Не нравятся условия - не я к тебе пришел просить найти мне камень.}
{141}{013}{Ну, я вообще-то даже спорить не собирался... а где искать то твой камень?}
{142}{010}{Ну, я вообще-то даже спорить не собирался... ладно, найду - загляну к тебе. А пока у меня есть пара вопросов.}
{143}{999}{Ну, я вообще-то даже спорить не собирался... ладно, найду - загляну к тебе. Бывай.}


{153}{}{Ну?}
{150}{016}{Достал я твой камень. }
{151}{017}{Да хотел спросить - может у тебя появились мысли, где достать камень?}
{152}{018}{Он что, блин, один в этом сраном Радиусе?}


{160}{}{Дай-ка взглянуть... [внимательно рассматривает находку, затем откладывает ее в сторону] Да, похоже это именно то, что мне нужно. Одно но. У меня сейчас не очень хорошо идут дела, поэтому батареек я не смогу тебе отсыпать. Но, у меня есть кое-что даже получше. Один из моих тесаков. Держи. [он снимает с пояса резак и протягивает вам]}
{161}{010}{[взять награду] У меня еще пара вопросов есть.}
{162}{999}{[взять награду] Ладно, бывай. Будет работенка - дай знать.}


{170}{}{Нет. Это все?}
{171}{010}{У меня еще пара общих вопросов...}
{172}{999}{Нет, пожалуй, я продолжу поиски.}


{180}{}{Вряд ли. Но я бы хрен заплатил, если бы его было легко найти. }
{181}{010}{У меня еще пара общих вопросов...}
{182}{999}{Пожалуй, я продолжу поиски.}


{190}{}{А тебе-то какое дело? Хочешь себе такой же крюк? Могу отрубить тебе руку. Крюк сам будешь искать себе.}
{191}{020}{Я думаю, что я обойдусь как-нибудь сам. }
{192}{020}{Ага. Смешно, ой не могу. [сказать с кирпичным выражением лица]}


{200}{}{Короче, это не твоего ума дело. }
{201}{010}{У меня еще пара общих вопросов...}
{202}{999}{Пожалуй, я пойду.}