##############################
#Локация: Псы Заката
#Имя: Oswald Brown 
#Краткое описание: Старший по новеньким
#Дата создания: 25.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a man who you wouldn't want to talk to.}
{2}{}{Looks like he's a big cheese here. Unlike you.}
#
# после знакомства
{3}{}{You see Oswald.}
{4}{}{He looks for someone to eat their brains out.}
#
{5}{}{Your attack dazed Oswald. He reaches for a weapon.}
{6}{}{Your jaw makes a clicking sound, you feel like it's displaced. Your clothes are soaked with piss. You feel awful.}
{7}{}{You were ordered to guard the gate! I'll show you...}
{8}{}{Cleaning the toilets! GO, NOW!!}
{9}{}{Oswald was rotten and cocky even for a raider. Many here wanted him dead - but some respected. You should look out for your life.}
{14}{}{Here goes our schmuck. Stay away from me.}
{15}{}{Get off, wimp!}
{16}{}{Schmuck, why I see you away from the toilet?}
{17}{}{Fuck you!}
{18}{}{You should be cleaning toilets by now!}
{19}{}{Get out of me, dirty schmuck!}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[Suddenly you hear that someone's calling] Hey, you! Come here! [You look around and see a young man in very clean equipment. His jacket and pants are sewn all over with loads of pads and plates. This makes him look more like a Christmas tree than a man who regularly goes on raids. His face expresses strong resentment. Looks like you are a piece of shit.]}
{11}{002}{What?}
{12}{003}{Ask nicely.}
{13}{999}{[Give him a middle finger and walk away]}


{20}{}{I don't remember seeing your face around here. That means you are a newbie. And it's me who deal with newbies here.}
{21}{020}{And?}
{22}{003}{I don't give a shit.}
{23}{999}{[Give him a middle finger and walk away]}


{30}{}{What? [he looks very surprised. Even confused.] Do you actually know who are you talking to? Who I am?! I'm...}
{31}{005}{[interrupt him] A piece of shit. }
{32}{006}{[interrupt him] I don't give a fuck who you are. }
{33}{004}{[listen]}


{40}{}{...Oswald Brown! The king, the fucking god! I'm the one in charge here after Loudmouth! If you are gonna fuck with me, I'll bury you right where you stand!}
{41}{018}{What do you want from me?}
{42}{006}{Blah, blah, bloody blah. So interesting. }
{43}{005}{[Give him a middle finger and walk away]}

{50}{}{Node005}
{51}{}{That's it, you're done, bitch!}
{52}{998}{[fight]}


{60}{}{Are you fucking lost it? You are way too far up your ass, faggot!}
{61}{014}{Maybe it's YOU who lost it? Huh? Screaming around that you are Oswald Brown! Fuck me. I don't know who that is. And you don't fucking know who I am. And believe me, you'd better shut the hell up. I'm no fucking newb. I'm here on business. If you're going to show your cock off, I'll leave this place with your head in a bag as a souvenir.}
{62}{007}{And?}


{70}{}{Now you stand on your knees and beg for forgiveness. If you'll make enough effort, you're going to be sent to guard the gate. But if I won't like how your tongue cleans the soles of my boots - you are going to clean toilets. Got it, sucker?}
{71}{015}{What a joker. Are you the local clown?}
{72}{998}{Yeah? [grab his collar and slam his nose with a headbutt]}
{73}{008}{[keep silent]}


{80}{}{That's better, pup. [Oswald gives you a disgusting smile] Now, on your knees.}
{81}{998}{Sorry, I got carried away. [grab his collar and slam his nose with a headbutt]}
{82}{009}{[stand on knees]}
{83}{014}{I'm getting tired of your shit. I suggest you change your attitude. If you won't shut up, my old buddy Loudmouth will explain to you why it's a mistake to talk to me like that.}


{90}{}{[Oswald grins] That's better, sucker. Now - lick my boots and beg for mercy. The discipline is born through punishment, heh-heh...}
{91}{013}{[take out the knife from your boot and stab Oswald into the groin. Turn the knife around, pull off, stab twice in the belly. Stand up and cut his throat. Finish by sticking the blade into his shoulder.]}
{92}{011}{[kiss Oswald's boots]}


{100}{}{[He looks at you like if you were a piece of fresh shit.] }
{101}{030}{Have a job? }
{102}{044}{About the pistol...}
{103}{046}{I see you are getting hard from pistols? Why's that?}
{104}{047}{Are you always act like an asshole?}
{105}{048}{So you are one of the top dogs here?}
{106}{999}{[end of dialogue]}





{110}{}{[Oswald laughs, then kicks you in the face. The boot goes right into your jaw, making a loud cracking sound. You fall on your back. Oswald unzips his pants and starts pissing on you.]}
{111}{012}{[lay obediently]}
{112}{998}{[throw yourself at Oswald]}


{120}{}{Animal! Lowlife! Piece of shit! Dirtbag! Now I hereby appoint you to the honored toilet cleaner position! Don't ever let me catch you two meters away from it, or you are fucked! I will make you eat shit while standing knee-deep in it. Now get the fuck out, schmuck.}
{121}{999}{[end of dialogue]}


{130}{}{[Oswald slowly descends down, bleeding from all wounds. He makes gurgling sounds, but it doesn't last long. He is dead.]}
{131}{999}{[end of dialogue]}


{140}{}{I don't care who you are. [Oswald stares at you with his "peering" look]}
{141}{021}{[Look back into his eyes with a calm face]}
{142}{010}{Good. Let's talk business already.}


{150}{}{Yeah, the one in charge of this circus. You fucking...}
{151}{010}{Okay, forget it. Let's talk business already.}
{152}{016}{You could say, you are the biggest dick around.}


{160}{}{[Oswald turns red. He readily pulls out his gun, its barrel pokes into your forehead] Now who is talking, bitch?! Huh?! I dare you, I fuckin dare you to say one more word!!}
{161}{008}{[keep silent]}
{162}{017}{Go fuck yourself...}


{170}{}{[Oswald pulls the trigger]}
{171}{999}{[You die in an instant]}


{180}{}{That's for you to shut up and walked by me on your toes! To remember that you are a piece of shit and I'm your master!}
{181}{019}{Wow.}
{182}{016}{Why don't you go fuck yourself?}
{183}{010}{Impressive. I mean, it would have been, if I had no brain. Let's stop this dick-measuring competition and talk business.}


{190}{}{What?}
{191}{010}{I said "Wow". Let's talk business already. I'm tired of this bullshit.}


{200}{}{You have your chance to make things right. Let's see how obedient you are. Give me your weapon.}
{201}{022}{What?}
{202}{029}{Yeah, right. Doing that already.}
{203}{027}{No.}
{204}{029}{I'd rather eat it whole.}


{210}{}{[Oswald grins] A staring contest? Cute. Go play it with your mom, cocksucker.}
{211}{010}{I'm tired of this bullshit. Let's talk business already.}


{220}{}{Your weapon. Give it to me.}
{221}{023}{[give him your weapon]}
{222}{027}{No.}


{230}{}{[He takes your weapon and attaches it to his equipment] Good girl. Today you are free from duties for the good of our great community. Now fuck off.}
{231}{026}{Give. Me. Back. My. Weapon.}
{232}{025}{Are you sick of being alive or what?}
{233}{024}{[keep silent]}


{240}{}{You're still here? Shoo! Fuck off! [Oswald pushes you]}
{241}{998}{[throw yourself at Oswald]}
{242}{999}{[leave]}


{250}{}{And what are you going to do with it? Stare at me until I grow myself a consciousness?}
{251}{024}{[keep silent]}
{252}{998}{[throw yourself at Oswald]}
{253}{999}{[leave]}


{260}{}{Strange you didn't ask me to kiss you. Fuck off while you still can.}
{261}{024}{[keep silent]}
{262}{998}{[Throw yourself at Oswald]}
{263}{999}{[leave]}


{270}{}{[Oswald giggles, looking like he has some troubles with the head] So fearless... I think you and your titanium balls will make a great addition to the gate guards. Get your ass there. If I hear that you are hanging around instead of doing your job - you are fucked.}
{271}{006}{Why don't YOU go guard the gate? And while you walking there, you could come by traders and sell your asshole for a quick buck.}
{272}{999}{Yeah. [leave]}
{273}{028}{Do I look like one of your bitches?}


{280}{}{Oh, look at that! Our boy here has some balls!}
{281}{998}{And now you are lost yours. [fight]}
{282}{999 }{[sigh and leave]}
{283}{010}{[try to ask a question]}


{290}{}{Hah, maybe you'll make a great Jackal! I mean, kinda average, but real. Still, the dog should know its place, get it?}
{291}{010}{Yeah, yeah, let's change the subject...}
{292}{999}{Oh my god, I'm so tired of your bullshit... [leave]}


{300}{}{[He smiles and you have a sudden urge to punch him in the face] Toilets, trash, gate... Everything for you, buddy!}
{301}{031}{So funny. I meant a real job, with real pay.}


{310}{}{Fine, butternut, there is actually something. I like good pistols. And I'm looking for one for my collection. Called Slugger. If you'll find one, let me know.}
{311}{032}{One like this?}
{312}{036}{I have something better. Take a look. [show Jackal's revolver]}
{313}{999}{Okay. If I see one, I'll come by.}
{314}{043}{The price?}
{315}{010}{I will think about it. For now, I still have some questions.}
{316}{999}{I will think about it. }


{320}{}{[Oswald instantly nods] Yes, exactly like this one. I'll pay, let's say, five hundred. Drop the bargaining. I could just shoot you and take it. Consider it my gesture of generosity.}
{321}{034}{Deal.}
{322}{033}{I need to think. To consider options.}


{330}{}{Then come back when you do that. Fucking prude all of a sudden. }
{331}{999}{[end of dialogue]}
{332}{010}{I still have some questions.}


{340}{}{[Oswald gives you a reward and sinks into examining the pistol. His pretentious face becomes simple and contemplative, his eyes showing interest instead of resentment. Looks like he has no intention of continuing the conversation.]}
{341}{035}{Hey, Oswald, I still have some questions.}
{342}{999}{[end of dialogue]}


{350}{}{Later. I'm busy now.}
{351}{999}{[end of dialogue]}


{360}{}{[Oswald raises his eyebrows. Looks like he recognized the pistol, but has troubles believing his eyes] Where did you get THAT, greenhorn? I think I'll buy it. Thousand.}
{361}{037}{Thousand? You must be kidding. I looked for the parts, assembled it... Even the parts cost more than that!}
{362}{042}{Okay, deal.}
{363}{033}{I need to think. To consider options.}


{370}{}{Fine. Name your price.}
{371}{041}{One and a half thousand.}
{372}{039}{Two thousand.}
{373}{038}{Three thousand.}


{380}{}{The gun is good, I tell you that. But this price is a little excessive. It's easier for me to murder you instead of paying. }
{381}{041}{One and a half thousand.}
{382}{039}{Two thousand.}


{390}{}{No. }
{391}{040}{Why the hell no? Not only the gun is the rarest - it's big, powerful, and reliable. It costs more. I'm selling it to you because you are the authority. The others are less worthy.}
{392}{041}{One and a half thousand.}


{400}{}{[Oswald scratches his chin. Then painfully stares at the pistol] Okay. You win. If you'll find Slugger, come to me. [he gives you a reward and sinks into examining the pistol. In one moment his pretentious face becomes simple and contemplative, his eyes showing interest instead of resentment. Looks like he has no intention of continuing the conversation.]}
{401}{035}{Hey, Oswald, I still have some questions.}
{402}{999}{[end of dialogue]}


{410}{}{Okay. Here's your reward. If you'll find Slugger, come to me. [he gives you a reward and sinks into examining the pistol. In one moment his pretentious face becomes simple and contemplative, his eyes showing interest instead of resentment. Looks like he has no intention of continuing the conversation.]}
{411}{035}{Hey, Oswald, I still have some questions.}
{412}{999}{[end of dialogue]}


{420}{}{Here's your reward. If you'll find Slugger, come to me. [he gives you a reward and sinks into examining the pistol. In one moment his pretentious face becomes simple and contemplative, his eyes showing interest instead of resentment. Looks like he has no intention of continuing the conversation.]}
{421}{035}{Hey, Oswald, I still have some questions.}
{422}{999}{[end of dialogue]}


{435}{}{Five hundred.}
{430}{032}{One like this?}
{431}{036}{I have something better. Take a look.}
{432}{999}{Okay. If I see one, I'll come by.}
{433}{010}{I will think about it. For now, I still have some questions.}
{434}{999}{I will think about it. }



{440}{}{Did you find Slugger?}
{441}{032}{One like this?}
{442}{036}{I have something better. Take a look.}
{443}{045}{In the process. I was just thinking - maybe you need another gun? So I wouldn't waste time and looked for it too.}


{450}{}{No, you fuck. I neet the damn Slugger. If that's it - get the hell away.}
{451}{999}{[end of dialogue]}
{452}{010}{I still actually have some questions...}


{460}{}{Because. You are not my mom, I'm not chatting with you. Especially about that. }
{461}{010}{Forget it. I still have some questions.}
{462}{999}{Nevermind that. I'm going.}


{470}{}{Said piece of shit.}
{471}{010}{Forget it. I still have some questions.}
{472}{999}{Nevermind that. I'm going.}


{480}{}{I look out for greenhorn freaks like you and put some sense into them. They have no brains and no respect for authority. I'm not even talking about discipline.}
{481}{050}{Who else is in charge here?}
{482}{049}{You are pissing me off with your neglect attitude. I've seen much more of the world than you.}


{490}{}{Really? I don't give a shit.}
{491}{010}{Forget it. I still have some questions.}
{492}{999}{Nevermind that. I'm going.}


{500}{}{Loudmouth. He's the one leading. Stay away from him. Then there's Billy... And Chris. They are more like smaller management.}
{501}{051}{Billy?}
{502}{052}{Chris?}
{503}{010}{Forget it. I still have some questions.}


{510}{}{Billy fucking Stone. An asshole in charge of repairings. That's considering his crooked hands... I've heard that he likes to fuck somebody else's girls, heh-heh.}
{511}{052}{Chris?}
{512}{010}{Forget it. I still have some questions.}


{520}{}{Chris Murena. Fucking schizo. Better don't pull a gun in front of him, or he will shoot you instantly. His nerves are worse than Loudmouth's. And one more thing - watch your things while he's around. This cleptomaniac shithead never returns anything he takes. And he LOVES to take things when their owner is not around.}
{521}{051}{Billy?}
{522}{010}{Forget it. I still have some questions.}