##############################
#Локация: Псы Заката
#Имя: Крикун
#Краткое описание: Бешенный сын Шакала. Квест на Ожерелье, участие в квесте Билли и в переговорах с Радугой
#Дата создания: 21.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a raider wearing steel armor.}
{2}{}{His suit is covered with traces of previous battles and his hands never leave the weapon.}
#
# после знакомства
{3}{}{You see Loudmouth.}
{4}{}{Crazy and violent leader of the Sunset Jackals. Dangerous as a rattlesnake.}
{5}{}{Get the FUCK away from there! NOW!}
{6}{}{I fucking WARNED you, you little BITCH!!}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[His bloodshot yellowed eyes immediately capture you whole like a carcass of Lavash on a butcher table] Who is this miscarriage of a ghoul on drugs, wandering in here? What the FUCK do you want?!}
{11}{011}{Hey, lower your voice. I'm here for a business.}
{12}{012}{I'm just looking around. Care to explain me something?}
{13}{035}{Are you the Loudmouth? Hog has something to say to you...}
{14}{035}{Do you even know who you are talking to? I'm an official ambassador of Rainbow, not a low-life molerat! The Hog personally...}
{15}{040}{Did you hear the latest news from Rainbow?}
{16}{999}{I was just leaving.}


{1001}{}{You again? Get your fucking bones away from here, until I break them... [His sight becomes clouded, but, after some time he sinks it into your face again] You're still here?}
{101}{011}{Hey, lower your voice. I'm here for a business.}
{102}{012}{I have some questions, if you don't mind.}
{103}{035}{Easy! Show some respect to the Rainbow's ambassador!}
{104}{035}{I have an important message from the Hog. I wanted to talk about...}
{105}{040}{Do you know what happened to the Rainbow?}
{106}{014}{Here's your prize. [give him Chimera's teeth]}
{107}{999}{I'm already leaving.}
{1002}{}{[Loudmouth welcomes you with a wide smile of his rotting teeth] Here comes our animal lover. Whaddaya want, hotshot?}
{108}{012}{I wanted to ask you about this place.}
{109}{040}{Do you know what happened to the Rainbow?}
{1010}{035}{I wanted to talk to you about the Rainbow. There's an interesting proposition. So, the Hog offers...}
{1011}{999}{I was just leaving.}


{110}{}{[Spits on the ground in front of you] What business we could possibly do, you wasteland louse?!}
{111}{013}{Well, I don't know... For example, I could do some dirty work for you. The one your guys can't handle.}
{112}{015}{I told you to chill the hell out. Or should I punch these words into your throat, so you would understand me better?}
{113}{012}{What about some questions about this place?}
{114}{999}{Then I'm leaving for now. }


{1201}{}{Do I look like a fucking guide to you? Huh? Are you the fucking interviewer? [He gets angrier with every word, his voice sounding like raspy roaring] Are you sniffing something here for this cocksucker Hog? TALK, YOU FUCKING SHIT! }
{1202}{}{Let's do this quick, I have a lot of work to do... I need to get my collection of fingers organized. [He rifles through a crumpled box with a steel dog faces on the side] Here, check this one out, I borrowed it from the Hog. [he angrily squints] If I knew it would turn out like this - I would take the whole head of this filthy shit! I'm gonna fucking MURDER him!}
{121}{016}{I just wanted to know more about you, guys.}
{122}{018}{Interesting. Now, who the hell is Hog?}
{123}{015}{Why are you so twitchy? Didn't your dad loved you enough when you were kid? Or maybe it's the opposite... Did he do it regularly?}
{124}{999}{I won't bother you then. I'll come by later.}
{1203}{}{Do I look like a fucking guide to you? Huh? Are you the fucking interviewer? [He gets angrier with every word, his voice sounding like raspy roaring] I thought when the Hog is dead, I'm gonna fucking breath a little. But you, freaks, are still trying to piss me off, aren't you? Huh? TALK, YOU FUCKING SHIT!}
{125}{015}{Looks like you think you are immortal. Want me to arrange you a meeting with the Hog?}
{126}{016}{I just want to know more about you, guys.}
{127}{999}{Do not hassle, I'm already leaving.}
{1204}{}{Let's do this quick, I have a lot of work to do... I need to get my collection of fingers organized. [He rifles through a crumpled box with a steel dog faces on the side] Here, check this one out, I borrowed it from the Hog. [he angrily squints] Too bad that I didn't get to cut off his head! He got lucky - I was not the one who got to him first...}
{128}{016}{Care to tell me more about you and your guys?}
{129}{999}{Yeah, it happens. Well, I need to go.}


{130}{}{What are you implying?! That Jackals are not good enough for something?! Although... Wait, stand still for now... [He starts pondering, poking with hand into steel plate on his caved armor. Suddenly he violently rips it off. But when he talks to you again, his voice sounds more or less calm.] So here's my question - are you good at hunt?}
{131}{020}{Good? I can find a fly by its trace in the air!}
{132}{020}{Can do something, yes. Why do you ask?}
{133}{012}{Nah, not my thing. Better tell me something else.}
{134}{999}{Uh... I've just remembered I have some business to take care of. See you later.}


{140}{}{[He pats you on the shoulder] Nice job! Perhaps I'm not only going to leave you your fingers intact, but will also give you a honest reward. [He puts down the rifle with powerful optics from his back, and reloads it a couple of times, checking smoothness of mechanism] Such a good toy... Exactly for you. Now you'll be able to shoot any beast between the eyes from a mile away.}
{141}{012}{A pleasure doing business with you. I still have a couple of questions though.}
{142}{015}{Is that it? Do you even realize what does it take to kill a Chimera? I bet you took other teeth from an old and dead ones...}
{143}{999}{Thanks, Loudmouth. Big gun means big future! See you around.}


{150}{}{[You see how last little bits of humanity leave his yellow eyes. Looks like you went a little overboard] You! YOU FUCKING FILTH! Do you REALIZE who are you barking on?? [he starts to pull out the pistol] I murdered SO MANY PEOPLE for MUCH less!! Maybe I need ANOTHER necklace, MADE OUT OF YOUR TEETH?!}
{151}{021}{Woah, chill, chill! You had it all wrong, I never intended to insult you! My sincerest apologies, thunder of the Radius! Let's do it like that - I'll leave and we forget about this misunderstanding?}
{152}{017}{You can scare your pet bitches all you want, shithead - It won't work on me! Now I'm gonna strangle you with your own intestines!}


{160}{}{We are the Sunset Jackals!! We are the ones who take what they want by right of might! As my father used to say - real men satisfy their hunger only with blood of their victims, their kids get to sleep only with the screams of dying enemies for a lullaby! All the fucking wasteland knows and remembers the Jackal and his pack! And don't you dare to get in our way...}
{161}{018}{I see. You mentioned someone named Hog. Who is that?}
{162}{015}{Hah! Why don't you said so earlier? Another pathetic gang of shitty raiders. Only with attitudes...}
{163}{022}{Looks like your father meant real business. I'd like to learn more about him.}
{164}{999}{Fully understood. Well, I should go.}


{170}{}{[You see foam coming from the corner of his mouth, veins on the neck are starting to pop out] That's it... NO EASY DEATH FOR YOU, SLUDGY PIECE OF SHIT!! Boys, let's show that bitch - and don't touch fingers, they are mine!!!}
{171}{998}{It's showtime!}


{180}{}{[He is not amused by the question] I had one fucking degenerate in my crew before. Brought me no real benefits, only problems. And I let him to get away with so much! So what if I cut off his finger once? He pissed me off that time... Looks like he decided he can be something more - and took over some factory, turning it into narcotics lab. Now he not only produces the shit, he also puts the half of it into his own rotten fat ass. Fucking junkie...}
{181}{019}{I see you don't like him much. Maybe he should be dealt with? I can help with that.}
{182}{016}{I agree, it's so difficult to assemble a good team... By the way, what can you tell me about your other guys?}
{183}{999}{I see. See you around.}

{190}{}{Node019}
{191}{}{Well thank you VERY fucking MUCH! How we were doing here without YOUR fucking help? Listen to this - I DON'T GIVE A FLYING SHIT ABOUT HOG, HIS ASSHOLE OF A GANG, YOU, OR A WHOLE DAMN WORLD!! I don't even care if I die today or tomorrow, you hear me?!}
{192}{999}{Suit yourself, I was just asking. See you then.}


{200}{}{[looks at you sceptically] Yeah, sure, you walking dog food... Okay, what do I lose? Here's the situation - lately there's the rumor going that I piss my pants every time the word "Chimera" is said. And that there's some asshole with rifle in rotten NWO, who, unlike me, can shoot this creatures dead easy-peasy. I have no time to spare shutting up every fucking pie hole, so I decided to deal with all of them simultaneously - see this necklace? That's Chimera's teeth. But I'm too busy now to walk around wastelands getting the shit. This is where you come into picture. Kill off a couple of Chimeras and bring me their fangs, the longest ones! I need three in total. The Jackals are having their hands full, so my bet is that someone like you would carry the task. You won't regret it - I have some very good rifles, someone who knows their stuff about guns would really appreciate them.}
{201}{999}{Deal. I'll come back soon, get the guns ready.}
{202}{012}{No, it's too risky. I'll pass. Better answer some questions.}
{203}{999}{I need to think about it. Be back soon.}


{210}{}{Sure, we'll forget about it, no problem. You'll just leave... [Suddenly he punches you in the jaw - and you feel how the spikes of his glove rip through your skin] IF YOU WILL BE ABLE TO WALK ON THAT PIECES OF MEAT WE'LL LEAVE YOU WITH, INSTEAD OF YOUR LEGS!! [He turns to raiders] HEY, JACKALS! HERE'S YOUR DOG FOOD!!}
{211}{998}{Today's a very bad day...}


{220}{}{My father was - and always will be - the best of all Jackals! He has been preparing me for the role of pack leader since I was a boy. He was always letting me shoot some freaks in the face - and if I did good, he allowed me to keep fingers. I have a whole box of them!}
{221}{018}{Oh. Yeah, he should be proud - you learned so well. And who's that Hog you mentioned before?}
{222}{023}{Hah! And I've heard that your childhood wasn't all rainbows and unicorns, know what I mean?}
{223}{999}{Sure, childhood memories are so great. Well, let's stop for now. See you!}


{230}{}{[He moves forward with intimidating look. His sticking mohawk makes him look like a lizard] What the fuck are you getting at?}
{231}{017}{I'm getting at the times you've been wetting yourself and crying your shit out. I guess, that's why they call you Loudmouth, eh? Mad respect to your father for enduring for so long - If I were him, I would choke the little rat like you right at birth...}
{232}{999}{Uh, um... Just rumors, nothing serious. Well, it's time for me to go.}


{2401}{}{[He is definitely not in the mood and the sight of you doesn't make it better] Why the hell I see you ventilating your balls near the room door to my bitch, you dirty rat poop?! ANSWER ME!!}
{241}{030}{What? I didn't even know there was someone in there! I just liked this door, you know... I love doors.}
{242}{025}{There's no one inside anyway! I've just seen her walking out and going riiiight there...}
{243}{026}{At last I found you! I have a very important information, you're gonna thank me later!}
{244}{999}{How would I know that she is yours? Okay, I'm leaving...}
{2402}{}{[Loudmouth is annoyed with something - as usual. But seeing you he calms down a little] Oh, hotshot! The hell are you doing here?}
{245}{032}{Yeah, the Radius is a tight place... I was just walking by. How about you? Why are you here?}
{246}{999}{I was coming by... And going. Don't want to spoil your date. Bye!}


{250}{}{[He suspiciously moves his eyes from door to you and back] Why the hell she would go there, I wonder?}
{251}{029}{Well, I've managed to eavesdrop that she looks for the cleaner puddle to do her make-up, because she wants to see you in better shape. She vas very excited about that. You are so lucky!}
{252}{029}{Uh... Um... I don't know, maybe stomach ache?}
{253}{026}{It can wait. I have an important information for you.}
{254}{999}{How would I know? Deal with it yourself, I'm out of here...}


{260}{}{[He menacingly approaches you] The fuck? What could you possibly have to tell me?!}
{261}{027}{I managed to overhear a couple of your Jackals talking - I've always been very curious, you know. I've heard them talking about something important and snuck upon them to eavesdrop...}
{262}{027}{Yes, you are right, don't know what came over me... But your girl isn't there, I saw her walking away in that direction, just before you arrived.}
{263}{999}{I have nothing to do here, sorry. I won't stop you anymore.}


{270}{}{[His spit flies around when he talks] What? Snuck? The one like you wouldn't snuck even upon a Jackal who's blind and deaf! Try to piss into my ears one more time and I will turn your insides out!! Got it? Now fucking shoo, pick up the speed!!}
{271}{031}{Be that as it may, you won't enter this room.}
{272}{999}{I see, I'm going...}
{273}{}{[He tries not to look like it, but your words definitely sparked some interest in him] Why did you stop? Go on.}
{274}{028}{Of course, I can't tell for sure - there was dark there, I heard not very clearly... But in short they were planning to catch up with the Hog's man at some factory, near the water barrels. They meet in an hour, today.}
{275}{999}{You know, I've just remembered something! I need to run. Find you later, 'kay?}


{280}{}{A Hog's man? Another bitch running to this pig? Fucking assholes!! [He grabs for the gun with rabid look, but almost immediately comes to senses] Sure or not, I need to check on it. Right fucking now!! [he turns around and hastily walks away]}
{281}{999}{Good luck! And you're welcome.}


{2901}{}{YOU are gonna fucking get your stomach ache, you fucking joker!! Get out of my sight or I'll tear you a new one!!}
{291}{031}{I'm not going anywhere. And you are not getting into this room, fuckwad.}
{292}{999}{Already leaving.}
{2902}{}{[He scratches his head] That's what she said? Hmm... Okay, I'll come by later... But I don't want to see you here when I come back! [walks away with satisfying look]}
{293}{999}{Sure, sure, I'm leaving.}


{300}{}{I'm gonna fuck you up so hard if you don't disappear now, asshole!!}
{301}{026}{Just a moment! I have an important information for you!!}
{302}{025}{Why are you in such hurry? She already left anyway. Somewhere... There!}
{303}{999}{Hey, calm down! I'm going.}


{310}{}{[He seems enjoyed by the turn of event] You know, I won't even ask why are you so stubborn. I'm just gonna enter the room - after I wash my face with your blood! [reaches for weapon]}
{311}{998}{Nice! I didn't kill anyone for a long time!! }
{312}{998}{Maybe we still can talk it over? No?..}


{320}{}{I decided to come by my bitch... She is the trophy, after all. Okay, was nice to see you and all that, but I have no time to beat around the bush here.}
{321}{033}{You can relax - she ran away in that direction five minutes ago. But maybe you can still try to catch up.}
{322}{999}{Agree. Well, good luck.}


{3301}{}{I'm gonna do just that! She shouldn't fucking run around for no reason, I'll deal with it! Okay, see you. [slowly walks away]}
{331}{999}{Good luck?..}
{3302}{}{Nah, I'm gonna wait inside. Shoo. Shoo, I said!}
{332}{034}{We are not finished talking. You are not going anywhere.}
{333}{999}{Yeah, sure, go in.}


{340}{}{[He comes closer with evil grin] So cheeky today, aren't you, hotshot? Maybe I should beat some respect into you...}
{341}{998}{Go ahead, you bitch! Come here!}
{342}{998}{Why do we always have to resort to violence? Hey, put your hands away from there!}


{350}{}{[You fail to finish the sentense] The HOG?! You are his new BITCH, aren't you?! Bitch so stupid that you came straight to me?! ALONE?! [He pulls out a huge knife, cutting his other palm. The blood starts to drip on the floor] Just when I needed new fingers in my collection...}
{351}{036}{Hey-hey, easy! It's in your own interests!! Just listen for a minute, it won't take long.}
{352}{017}{Put away the knife, bozo. Or I'm gonna cut off something yours. For MY collection.}
{353}{036}{Listen, you know me well. And I realize who I'm dealing with here. Be sure that I wouldn't put myself into dealing with Hog for no reason.}


{3601}{}{I don't fucking believe you! Trying to fuck me up?! I'm going to rip off your rotten tongue and send it to Hog as a gift!! GET HIM, BOYS!!}
{361}{998}{Not the best of my negotiations...}
{3602}{}{[He calms down a little, but the knife stays in his hand] What this fucking PIG could possibly offer?! We are wasting time here... }
{362}{037}{So, here's the deal - the Hog wants to make peace. Yes, I know what you're going to answer. But first, think about it - Rainbow is the only supplier of the Drop, and if the war starts, where are you going to get yours? Considering the Hog would better burn down his lab together with its staff than leave it to you, if he loses. }
{363}{037}{I detailed Rainbow's defenses and military forces, together with their equipment. Even if you succeed in taking over them, your losses will be disastrous. How are you going to protect your territory after that? Considering that the factory is a sweet pie for every gang in the Radius... Of course, there are no one like you and your pack, but still. It's wiser to bid your time and don't go into direct conflict with the Hog.}
{364}{037}{Listen, I managed to sign up a very profitable trading agreement with the Rainbow. Considering approximated voume of deliveries, you are selling weapons and buying the Drop at a very good price! And the situation is going to get only better. So use it! With the big money assets, the Jackals will grow so strong that the Rainbow itself will come asking you for protection! And that's when you deal with the Hog.}
{365}{039}{Right! I'm here only to tell you this - the Hog is afraid of the Jackals! The negotiatons for peace is a sign of weakness! It's time to strike!!}
{366}{999}{Believe me, you are wrong. But I need to check on some facts. See you later.}


{370}{}{[While you speak, Loudmouth only grins, holding the bloody knife in his hand] You talk is smooth, I give you that. But something smells fishy here... [a thug approaches him and starts to quietly explain something] You too?! Okay, piss off for now... [he looks back at you] Here's the thing - we are gonna discuss it with the boys, and you stand still and don't make a sound.}
{371}{038}{Okay, no problem. I hope you'll make a good decision.}


{380}{}{[You stay in a company of two thuggish Jackals, who are busy with a very intellectual dialogue about better ways to skin a man alive. Unfortunately, when the most interesting part starts, Loudmouth comes back with his other men] Here's the answer - tell Hog that we'll take the deal. We won't touch them for now. And we will even sell the next batch of "merchandize" with a discount... A little excessive, as for me. [He glances at one of his guards] But if there ANY reason, even a little one - I fucking let loose all my Jackals and drown the whole Rainbow in blood! Got it?!}
{381}{999}{Great. I'll tell that to Hog. Was nice having business with you, but I've got to go.}


{390}{}{[He puts a knife away and pats you on the shoulder] Ha! I knew it! He doesn't have the balls to go against me! Now he's definitely done... But not now. Later. If you want to join the fun, just say, we'll find you something to do. Will pick fingers for me, hahah.}
{391}{999}{Ahem... What an honor. Okay, that's it for me, I won't be bothering you anymore.}


{4001}{}{[He gently strokes his mohawk, looking at you from under his brows] You are fast little bastard, aren't you? Just keep in mind, hotshot - Jackals WILL take over the Rainbow. Even if I die before it happens. So - enjoy your life, while you can... And while all your fingers are intact.}
{401}{017}{Is that so? You know what, let's deal with it right now! Mad animals should be put down!}
{402}{999}{I'll remember that. But you too stay focused. Good luck, Loudmouth.}
{4002}{}{[He crouches a little, as if he wants to throw himself at you] Do I suddenly need to get full of respect now?! Listen here, asshole - I DON'T GIVE A FUCK! WHO! YOU!! ARE!! Here you matter LESS than yesterday's PUKE!!! DO YOU HEAR ME?!?}
{403}{017}{I see you don't understand who are you barking on?! You gonna cough with blood after we finished, bitch!}
{404}{999}{Sure, sure. You should come by us sometimes. You won't be disappointed, I promise. Just tell us in advance, we'll dig some graves for your guys. See you around, Jackal.}
{409}{999}{At least it's honest. Okay, we'll see how it turns out eventually.}
{4003}{}{[He literally looks you from all sides] How someone like YOU could take down the Hog?! I bet I would do it fucking faster. Anyway - soon the Rainbow's gonna be ours! I'm gonna impale every fucking one of them on a stakes, that shit-eating junkies!! Don't wait for me to thank you though - I wanted to fuck up this fangy pig bitch myself.}
{405}{017}{How, you say? I can show you. If you are still good for something except babbling.}
{406}{999}{I can live with that. See you around, Jackal.}
{4004}{}{[He shakes his head so hard that you see the cloud of dust goes up from his mohawk] How the hell did that happen?! It should have been ME who put him down!! FUCK!!! Although there IS one thing that pleases me - the rainbow is now ours for sure... Okay, get the fuck where you wanted to. Do not piss me off.}
{407}{017}{You know, it was me who put the Hog down. And I'm going to do the same to you. Right now.}
{408}{999}{Okay. See you then.}