##############################
#Location: Sunset Dogs
#Name: Shiva 
#Short Description: Screamer Toy
#Date of creation: 27.09.2014
##############################
#For the game "Olympus 2207"
#Artem "Rainman" Samoilov	 
##############################	
#	
#CRITTER DESCRIPTION	
#NEED TO TEST THIS ONE
#	
# before meeting
{1}{}{You see a pretty, albeit very dirty girl.}
{2}{}{She looks damn attractive in these clothes.}
#
# after meeting
{3}{}{You see a pretty, albeit very dirty girl.}
{4}{}{She looks damn attractive in these clothes.}
#
{5}{}{Let's talk another time.}
{6}{}{You again? Pfft...}
{7}{}{Shiva's nose breaks with a crunch, she falls on her back, squealing. Her blood drips from your fist.}
#
#HERE BEGINS A DIALOGUE
#
{10}{}{[the girl starts talking before you have any chance to open your mouth] Another newcomer to the camp! Hello there. My name is Shiva.}
{11}{002}{Hello, I'm }
{12}{002}{...}


{20}{}{Yeah-yeah. So, what brings you to this extremely beautiful and interesting place? Wait a minute, let me guess: you came here from some half-dead farm because you could barely make ends meet, and decided to live by the robbery and alcoholism, like a real thug.}
{21}{003}{Well... you can say that.}
{22}{006}{No, it is not like that at all.}


{30}{}{Pffft... [girl rolls her eyes] How interesting.}
{31}{004}{Listen, I have a couple of questions.}
{32}{997}{Well, I AM quite interesting. All right, I'll go. To do other interesting things.}


{40}{}{I don't like to answer questions. I like asking them. And you are hardly going to tell me anything interesting...}
{41}{005}{Oh my, you are such a bore.}
{42}{997}{Don't care. I'll go find a more talkative companion.}


{50}{}{Me? Bore? It is you who is boring, you asshole! We have nothing to talk about!}
{51}{997}{Yeah-yeah [wave hand and leave]}
{52}{998}{Did you just call me an asshole!? [punch her face]}


{60}{}{Oh well. Tell me something interesting about yourself!}
{61}{011}{I am from Olympus!}
{62}{008}{I can punch the helmet so hard it caves in.}
{63}{007}{I can flay corpses.}
{64}{009}{I can assemble and disassemble almost any device with my eyes closed.}


{72}{}{So what? Ursul can skin Ursa before he gets eaten by one.}
{70}{005}{Oh my, you are such a bore.}
{71}{997}{Don't care. I'll go find a more talkative companion.}


{80}{}{So? Brick is literally breaking bricks with his head. He giggles while doing it, like he is tickled.}
{81}{005}{Oh my, you are such a bore.}
{82}{997}{Don't care. I'll go find a more talkative companion.}


{90}{}{Yeah? Yesterday Carl disassembled, cleaned, and assembled back Vince's rifle in seven minutes. And Vince's rifle was fully covered in shit.}
{91}{005}{Oh my, you are such a bore.}
{92}{997}{Don't care. I'll go find a more talkative companion.}


{110}{}{You're lying!}
{111}{013}{I'm not lying!}
{112}{012}{You can believe me or not. I don't give a shit. }


{120}{}{As I think that you are full of shit. Dickhead.}
{121}{997}{Yeah-yeah [wave hand and leave]}
{122}{998}{What did you say to me!? [punch her nose]}


{130}{}{Well, prove it.}
{131}{014}{[tell your story]}
{132}{012}{You wish. I have one less problem if you won't be prattling about me around here.}


{140}{}{[Shiva hears you out. At first, she was mostly rolling her eyes, but after a couple of minutes in, you had her full attention.] You are really from there! This is nuts! Usually, we are not very fond of their people, because when we approach the tower, they tend to kill us. So I wouldn't advise you to talk around here about where you are from. The others won't listen to your story and will beat the shit out of you right after the phrase "I am from Olympus." But I'll keep it a secret. [she smiles, scratching her forehead, and moves a lock of hair from her eyes] It was really interesting... Well, don't hang around here for long - one of my boyfriends could think that you are a competitor [she giggles]}
{141}{996}{Okay, I'm leaving already.}