##############################
#Локация: Псы Заката
#Имя: Стен 
#Краткое описание: Драчун
#Дата создания: 17.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a huge guy.}
{2}{}{The size of his fist equals to three of yours.}
#
# после знакомства
{3}{}{You see Stan.}
{4}{}{If you'd manage to beat him with bare hands, you could be proud of yourself. }
#
{5}{}{Your punch was unexpected to Stan. He even fazed for a little - but now he is angered.}
{6}{}{Your punch was unexpected to Stan, but he didn't even flinch. Looks like the testicles of this ogre are as non-sensitive as his brains.}
{7}{}{*growls at you*}
{8}{}{Get off, okay?}
{9}{}{Come on, enough! Get lost.}
#
{16}{}{Time to die, shmuck. [gives you a predatory grin]}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[you see a giant man. Not much taller than you, but he's very well-built. Also, his fist is as big as three of yours. Looking at him you suddenly remember the tale about a green ogre, which your mother used to tell you before bedtime. His face looks pretty simple - like the one of orangutan solving the equation. You notice a pre-war badge of supermarket employee on his leather jacket. It says "Stan".]}
{11}{002}{Uh... Hello?}
{12}{003}{Hey you!}
{13}{004}{[pose as one of the locals] Hey man.}
{14}{005}{[observe him from a distance]}
{15}{999}{[go away, don't start the conversation]}


{20}{}{[he gives you a contemptuous look] What do you want, snot?}
{21}{010}{A couple of questions...}
{22}{999}{Uh... Nothing...}


{30}{}{[Thug stares at you with studying look for a couple of moments.] What do you want?}
{31}{010}{To ask some questions.}
{32}{999}{Actually, nothing. See ya.}


{40}{}{What do you want? I don't know you.}
{41}{010}{To ask some questions.}
{42}{999}{Actually, nothing. See ya.}


{50}{}{[He actually doesn't look very scary. If not to piss him off, he probably can even be reasoned with. Although, this observation of yours doesn't make him appear smarter.]}
{51}{002}{Uh... Hello?}
{52}{003}{Hello.}
{53}{004}{[pose as one of the locals] Hey man.}
{54}{005}{[observe him from a distance]}
{55}{999}{[go away, don't start the conversation]}


{100}{}{What do you want?}
{101}{}{So?}
{102}{011}{I might have heard that you put your evil eye on my mate. Careful, I might poke it out of your eye socket...}
{103}{012}{I might have heard that you are going to beat up Vince. Is it true?}
{104}{015}{Care to tell about yourself?}
{105}{016}{Who's in charge here?}
{106}{017}{Have some change to spare?}
{107}{018}{How are you doing?}
{108}{019}{What's with your face?}
{109}{999}{Although, maybe we'll talk another time. Later.}


{110}{}{You'd better watch your tongue, lad. Wanna have a talk - go find Casper. And if you'll continue barking at me, I'm gonna hang you by your intestines on the nearest pole. Got it?}
{111}{998}{[punch him in the face]}
{112}{998}{[punch him into the groin]}
{113}{999}{[finish the conversation and go away]}


{120}{}{Maybe. So?}
{121}{013}{There's some rumor going, as far as I know: everyone's gonna bet on you in your fight with Vince, because the outcome is too obvious. So, that punk-ass bitch Casper wants to make profits of that, I tell you. He wants to set you up, so you'd drop down and he took all the cream. That cunning motherfucker...}
{122}{014}{There's an idea. A profitable one for you. You need to beat up Casper. We'll make our own bets. Deal?}


{130}{}{Fucking what?! Where's that stupid bitch, I'm gonna fuck him up so hard!! [Stan walks away in search of Casper]}
{131}{999}{[end of dialogue]}


{140}{}{You bitching rat, go try it yourself. I'm gonna stand and watch how Loudmouth will beat the shit out of you.}
{141}{010}{Oh-kay... Another question then.}
{142}{999}{Fine. I'll deal with it myself.}


{150}{}{Want me to tell you tales about my adulthood, first love and stuff? Go bother someone else with your fucking stupidity. }
{151}{010}{Oh-kay... Another question then.}
{152}{999}{Fine, I'll go...}


{160}{}{The fuck? Go sleep it off! Sitting in the camp and not remembering who the boss is. What kind of drug are you on?}
{161}{010}{Oh-kay... Another question then.}
{162}{999}{Uh, I'll go take some more of it.}


{170}{}{[Stan gives you the finger.]}
{171}{010}{Oh-kay... Another question then.}
{172}{999}{How poignant. Okay, I'll go ask someone else.}


{180}{}{It's cool. Yesterday killed eight people in the raid. One of them looked exactly like you. I punched him into the skull until it became a bone-filled puddle of goo on the asphalt. [Stan smiles fondly]}
{181}{010}{Oh-kay... Another question then.}
{182}{999}{Wonderful. I'd better go.}


{190}{}{What?}
{191}{998}{I just wanted to say that you've got the face of a monkey. And look like retard.}
{192}{010}{No, nothing. I wanted to ask...}
{193}{999}{No-no, nothing. Relax. I'd better go.}