##############################
#Локация: Псы Заката
#Имя: Урсул 
#Краткое описание: Главный охотник
#Дата создания: 18.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a big guy with grim face.}
{2}{}{With the face expression like this he must be very much used to bury people.}
#
# после знакомства
{3}{}{You see Ursul.}
{4}{}{He digs through his inventory again.}
#
{5}{}{Let's finish the cubs and return back.}
{6}{}{Look around you! Ursa is a dangerous prey.}
{7}{}{Talk less. Shoot more.}
{8}{}{No, we are not coming back without the prey.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{[A huge man is sharpening his knife, periodically checking it with a finger. He's very well-built - and dressed quite good either, especially by the local standarts. His foot rests on the skull of enormous beast.]}
{11}{002}{Hello.}
{12}{002}{[cough silently]}
{13}{002}{Hey, big guy!}


{20}{}{[He stops what he was doing and looks at you. You notice that he's wearing a necklace made of little stones, empty shells and pieces of glass. On his bandolier you see a patch which reads "Angel of Anaheim"] The name?}
{21}{003}{Does it matter?}
{22}{003}{A pain in the ass.}
{23}{003}{Name's }
{24}{003}{. Why does it matter?}


{30}{}{[Looks like he didn't hear that] Now you are no one. No name. At least until the local authorities start to show you some respect. You are a newbie. And newbies don't last long here.}
{31}{006}{Gee, thanks for a warm welcome. }
{32}{005}{How enlightening. I actually don't care about what the old geezer like you says.}
{33}{004}{So what? }


{40}{}{Just so you'd understand what you are dealing with here. I'm Ursul. Although I don't deal in newbie stuff, I often pull them into doing something useful. So maybe we'll have something to talk about.}
{41}{007}{Please do continue. I'm intrigued. }
{42}{999}{Curious, but now I'm busy. I have to go.}
{43}{999}{I don't think I'm interested. [end of dialogue]}


{50}{}{If there was some other Jackal instead of me here, you would have been already rectally pleased with a nailed bat, or something. [he stops talking, studying you for a moment] I'm Ursul. I can provide you with a job which would kick some experience into you. There's a chance that instead you'll kick be bucket though. When you'll drop your cockfighting attitude and get a little smarter, we can talk details. [he goes back to sharpening the knife]}
{51}{999}{[end of dialogue]}


{60}{}{Just so you'd understand what you are dealing with here. I'm Ursul. Although I don't deal in newbie stuff, I often pull them into doing something useful. So maybe we'll have something to talk about.}
{61}{007}{Please do continue. I'm intrigued. }
{62}{999}{Curious, but now I'm busy. I have to go.}
{63}{999}{I don't think I'm interested. [end of dialogue]}


{70}{}{[He laughs, not stopping the sharpening process] Do you like animals?}
{71}{009}{What?}
{72}{008}{No.}
{73}{008}{Yes.}


{80}{}{Although, it doesn't really matter. [he smiles again] You'll help me on the hunt. If you're in, I'd recommend to prepare some meds, ammo and get the biggest gun you can. }
{81}{999}{I'm ready, let's go.}
{82}{011}{I changed my mind - I don't really like hunting...}
{83}{999}{I need some time to prepare.}
{84}{013}{Tell me more about the hunt.}


{90}{}{Do you like bear cubs? [he nods at a huge carcass near him]}
{91}{008}{What??}


{100}{}{[Ursul nods to you.]}
{101}{}{Ask your questions.}
{102}{}{It was a good hunt, wasn't it?}
{103}{012}{About the help you needed...}
{104}{014}{You promised that there will be a reward.}
{105}{030}{You should have traveled a lot. Can you point me to some notable locations in Radius?}
{106}{034}{Maybe we could go hunting again?}
{107}{999}{Bye, Ursul.}




{110}{}{Stop wasting my time then.}
{111}{999}{[end of dialogue]}
{112}{010}{I have some questions...}


{120}{}{Yes. I need help on the hunt. Interested?}
{121}{013}{Tell me more about the hunt.}


{130}{}{I found a place not far away from here, which has been chosen as a lair by the huge pack of Ursa. The goal is simple - travel there and kill them all. After that we'll carry their corpses to the camp. The rest is not our business. If you're in, I'd recommend to prepare some meds, ammo and get the biggest gun you can. If you are ready, we can leave right away. If the hunt is good, you'll get some batteries as a reward. }
{131}{999}{I'm ready, let's go.}
{132}{011}{I changed my mind - I don't really like hunting...}
{133}{999}{I need some time to prepare.}

{140}{}{Sure. Here. [he pulls out a handful of batteries from his pocket and gives it to you] }
{141}{015}{[count the batteries] 67? Not much, considering the risks taken.}
{142}{016}{[put the batteries into your pocket]}


{150}{}{You got exactly what you deserved. }
{151}{016}{[grumble]}
{152}{016}{[be silent]}


{160}{}{You are not from Radius. Am I right?}
{161}{017}{What?}
{162}{017}{How's that?}
{163}{017}{What do you mean?}
{164}{018}{Maybe.}


{170}{}{I'm not blind. You are fighting not like the people who lived all their lives in Radius. It looks as you first laid hands on a weapon around a month ago. You kill, but lack the skill and your moves are not smooth enough. In Radius every child knows how to disassemble and assemble back the rifle, and how to shoot it in the way that brings maximum pain an suffering to the target. [he looks at you, waiting for answer]}
{171}{019}{I'm from the Olympus.}
{172}{021}{Why do you care?}
{173}{022}{What if I don't tell you?}


{180}{}{Did you come from the Olympus?}
{181}{024}{[keep silent]}
{182}{020}{Yes.}
{183}{023}{How did you know?}


{190}{}{From what I know, fighters from the Olympus can give hell to anyone in Radius. You are definitely not one of them.}
{191}{020}{Because I'm no soldier. I'm a worker.}


{200}{}{[He nods] Once me and my partner stumbled onto someone from the Olympus. Already dead, wearing strange uniform - something with NCASTR logo. My man Fred took it. That's all experience I have about meeting people from the Olympus.}
{201}{025}{NCASTR, you say? Where can I find Fred?}


{210}{}{My knowledge helps me to survive.}
{211}{022}{What if I don't tell you?}


{220}{}{You'll get the same attitude back.}
{221}{019}{Olympus. I'm from the Olympus.}

{230}{}{I'm not blind. You are fighting not like the people who lived all their lives in Radius. It looks as you first laid hands on a weapon around a month ago. You kill, but lack the skill and your moves are not smooth enough. In Radius every child knows how to disassemble and assemble back the rifle, and how to shoot it in the way that brings maximum pain an suffering to the target. [he looks at you, waiting for answer]}
{231}{020}{[continue]}


{240}{}{I'll take that as a yes.}
{241}{020}{[continue]}


{250}{}{Far away. Why do you care?}
{251}{026}{I need that uniform.}


{260}{}{Won't even ask why someone would need the clothes taken off from a corpse. [he pauses for a while, then continues] I'll tell you where to find Fred. But you promise me in return, that you'll make no mention of him to anyone. Not that someone here cares, but still.}
{261}{027}{Okay.}


{270}{}{[Ursul stares at you for a couple of moments, then starts to explain how to get to Fred's hideout.] }
{271}{028}{Great. Thanks.}
{272}{029}{How the hell did Fred manage to wind up so fucking far?}


{280}{}{Something else?}
{281}{010}{Yes, I have a couple of questions.}
{282}{999}{No, thanks again for the directions.}


{290}{}{On one of our hunts we wandered off - had some troubles catching up to the prey. Came across a mansion. An empty one. There was a skeleton inside, maybe from before the war, but the house itself was untouched. Looks like we were the first ones to find this place in years. We never told about it to anyone. And then Fred laid his eyes on one of our trophy girls. Snuck her out. I advised him to take shelter into that house. As paranoid as he is, he should still be there. Not sure for how long though. }
{291}{010}{Great, thanks. I have some questions.}
{292}{999}{Great, thanks. I've got to go.}


{300}{}{I better know the surrounding wastelands than Radius. I'm a hunter, I hunt on my territory. Was never very amused by human settlements. Although, there is one place that every Jackal knows about: Rainbow. Know where it is?}
{301}{031}{Yes.}
{302}{032}{No.}


{310}{}{Then I won't tell you nothing new.}
{311}{010}{Okay. I have some more questions.}
{312}{999}{Okay. I've got to go now.}


{320}{}{Let me show you how to get there...}
{321}{033}{[continue]}


{330}{}{[Ursul explains in details how to get to the Rainbow] The best place if you started to miss tight woman's ass, or just looking to have a fun time. }
{331}{010}{Okay. I have some more questions.}
{332}{999}{Okay. I've got to go now.}


{340}{}{At the time there are no orders neither for meat, nor for fur. Nor for anything else. We are not good with long-term storage here, that's why I hunt only when our supplies begin to run dry.}
{341}{010}{Okay. I have some more questions.}
{342}{999}{Okay. I've got to go now.}