##############################
#Локация: Псы Заката
#Имя: Винс.
#Краткое описание: Новенький Пес-охранник на воротах, совсем желторотый, но довольный тем, что стал Псом.
#Дата создания: 15.09.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a beaten-up guard.}
{2}{}{A pretty battered young man. He looks too distracted for a guard.}
#
# после знакомства
{3}{}{You see Vince.}
{4}{}{You can see on his face that guarding the entrance is not something he always desired.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{10}{}{Hey you! Yeah, you! What are you sniffing around here? Huh?}
{11}{002}{I, uh... Me- I need to get to the Sunset Jackals.}
{12}{003}{I'm one of us, let me in.}
{13}{002}{I need to enter your base.}
{14}{999}{Me? No, I just wandered in here by accident.}

{20}{}{Node002}
{21}{}{You don't say?! [he laughs] Seriously!? Wow! And I've been thinking, why the hell I spend all my time here, cooking my balls under the sun? Turns out that's to let the scum like you to walk freely into our camp! [he wipes his tears] Get the fuck out, okay? So many of you here...}
{22}{004}{But I really need to...}
{23}{005}{Hey, easy! I get it. But maybe I could get a passage for a price?}
{24}{999}{Okay, understood.}


{30}{}{Hmm, I don't remember you... Although, screw that, I'm here for a couple of days myself. Name's Vince, by the way. Okay, you can go in.}
{31}{999}{Thanks.}
{32}{999}{Wonderful!}
{33}{}{Do I look like a pussy to you, shithead!? Do you think I can't tell the real Jackal from some wasteland trash? Fuck you and get outta my sight!}
{34}{999}{Okay, okay, I get it! I'm leaving...}
{35}{005}{Don't make a fuss, I was just testing. Listen, maybe you could let me in for a price?}
{36}{999}{[leave]}


{40}{}{Fuck, are you getting soft on me? [mockingly mimics] ::I reeealie need tooo:: [he spits on the ground] Eat shit!}
{41}{005}{Well, uh... Maybe we could make a deal? A passage for a price.}
{42}{999}{Okay, got that...}


{50}{}{Want to pay your way in, huh? Hahah, do the filthy half-dead rag like you even have the money? Okay, here's the deal: you give me }
{51}{}{ batteries and I let you pass - or you can instead help me with one delicate matter.}
{52}{006}{Here are your batteries, you can choke on that. Now open.}
{53}{999}{I don't have so many... I'll come back later.}
{54}{007}{I could use the batteries myself. So... What kind of delicate matter?}


{60}{}{[Looking surprised and a little upset, he takes your batteries] Oh, would you look at that... Well, okay, uh, you can go in. Just be careful, if you fuck something up, Loudmouth will tie my legs around my neck. I'm Vince, by the way. Come by anytime, if you want to talk.}
{61}{999}{Yes, I get it, open it up already.}
{62}{010}{Vince, is it? I wanted to ask...}
{63}{999}{I see. Sure.}


{70}{}{Just as I suspected, low on cash! I have a pretty good eye, you know. Okay drifter, I'm Vince, what's your name?}
{71}{040}{I'm }
{72}{040}{ . What's that deal you talked about?}
{73}{040}{Vince, right. What's that matter you mentioned?}
{74}{999}{I'm bored. I'd better go.}


{100}{}{Oh, hey, a familiar face! Coming by for a little chat, mate?}
{101}{}{Sure, ask away.}
{102}{020}{You don't look so good, I'd say.}
{103}{030}{Can you tell me about how things are going here?}
{104}{040}{Why are you always looking around?}
{105}{045}{Remember how you asked me to deal with Stan?}
{106}{999}{I'll better go now.}


{200}{}{Oh. Well, you know... I'm actually here for a couple of days myself, I mean - here, with the Jackals. They have a simple way of doing things: if something happens - they start a fight. So I just asked, why should I stand guarding the entrance, and got punched in the face! And then they continued to beat the shit out of me. Good that I'm still alive, I've heard that many ended up worse.}
{201}{021}{So, you are here recently? Where did you come from?}
{202}{022}{Don't be a wuss, toughen up! By the way, where are you from?}
{203}{010}{I see. I wanted to ask another question...}
{204}{}{I don't really feel like opening up, especially to you. Did you even see yourself? You are more battered than I am.}
{205}{010}{Well, yeah. I wanted to ask another question...}


{210}{}{You talk shit. Maybe you'll just get the hell out?}
{211}{010}{Okay, but first I wanted to ask another question...}
{212}{999}{Okay, see you around.}


{220}{}{Hey, watch it! Although you're right, the weaklings don't last long, especially here... As far as I can remember, me and my parents had been traveling around the Ruins, through the wasteland, spending nights in caves or in basements of destroyed buildings - and we were used to such life. But one time... One time I watched a group of Jackals hunting down the pack of actual jackals. With guns and rifles, they were so fearless, so strong. That was the moment when I decided - I'd better become one of them and stand for myself than die in some cave. Still, I sent my parents away from the base. The life here is too savage for them.}
{221}{010}{What a story! I see now. I have another questions.}


{300}{}{What do you want me to tell you? I'm here for a couple of days myself... There's Loudmouth, he's in charge. Sits in his headquerters all day, deciding who's right and who's not. There's mr. B - his actual name is Oscar Brown. Or maybe Oswald Bricken, I don't care. He's in charge for newbs. And mostly that's it, I don't know anyone else. Just remember not to hang around someone for too long, because the folks here are very high-strung and can rip off your head for literally nothing.}
{301}{010}{I see, I see... Can I ask something else?}
{302}{999}{I get it, okay. I'll go learn about the situation here.}


{400}{}{Ah, fuck, well, there's a rumor going that this shit-eating little dick Casper talked Stan into kicking my ass... Man, he always sets up everyone, turning the guys here against each other - and then makes a fucking kick-ass competition out of it! But the worst part is that he takes bets on the outcome! Long story short, I have absolutely no desire to get into fight with Stan. I'm sure Casper already told him something stupid, and I really don't want to just stand here and wait for this fucking big-ass muscular disaster to sneak up on me.}
{401}{041}{And? You want ME to deal with Stan??}
{402}{999}{Oh screw that, I'm outta here.}


{410}{}{I don't know! I just don't want to have my face beaten up again, you hear me? Do something about it, anything - and there will always be open house here for you. Deal?}
{411}{QA}{Okay, I'll try to make something out.}
{412}{047}{Why won't you actually take the fight? }
{413}{999}{I don't know, I need to think about it.}


{415}{}{Great, mate! Only, uh, don't take too long, okay?}
{416}{999}{Don't sweat, we'll figure something out.}


{450}{}{Of course, mate! That's literally the only thingie I can thinkie about [he nervously smiles]. So what about it?}
{451}{999}{I'm looking into it. Soon everything will be alright.}
{452}{046}{It's cool now. Stan will leave you alone.}
{453}{}{F-fuckk... Are you kidding? [he shows you bruises all around his body] He beat me up real good... I won't even trust you with guarding the lavash shit now...}
{454}{999}{Oh, right... It kinda took longer than expected... Good that you are alive though. Okay then, see ya.}


{460}{}{I don't even want to know to whom and what you did [he hoarsely laughs]. Okay, you are now officially proven. For such guys, the door is always open.}
{461}{999}{Nice. Glad to be of help.}
{462}{999}{Cool. I could even apply for the Jackals, am I right? [wink and leave]}


{470}{}{Are you stupid? Did you even see this behemoth? I think he's capable of eating the whole lavash single-handedly. If he lands one punch, I'll be in the ground by the waist.}
{471}{048}{But you can bet against yourself and take a dive. Or bet against Stan and find a way to set him up. You'll win more than you lose anyway.}
{472}{049}{Bear in mind that by not standing for yourself you'll get the reputation of a weak schmuck. Then even the gate guarding duty is not an option. The best case scenario - to clean the toilets. }


{480}{}{[Vince thinks. Then nods] I think you're right. I'll handle it myself. And you can pass here anytime. The gate is always open.}
{481}{999}{Great. }


{490}{}{That's why I'm asking you to deal with this instead of me, you blockhead. Take the fight? Good joke, haha. }
{491}{QA}{Okay, I'll try to make something out.}
{492}{999}{I don't know, I need to think about it.}