##############################
#Локация: Тартар
#Имя: Смитти
#Краткое описание: Основной старик-ремонтник на техническом уровне тартара
#Дата создания: 03.05.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see Smitty.}
{2}{}{A good old Smitty. Chewing something, as always.}
#
# после знакомства
{3}{}{You see Smitty.}
{4}{}{A good old Smitty. Chewing something, as always.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
{100}{}{Look who we have here! Nice suit you got yourself! Did you think I wouldn't recognize you, }
{101}{}{? Of course it's you, I can tell by the way you walk that your hands are growing straight from your ass, HAH-HAHAHAHA! [he wipes tear] Well then, tell me, what brings you here?}
{102}{}{Oh! It's you again! [he smiles] You scared me, little devil. So? What do you want?}
{103}{011}{Smitty, I have to travel a lot, and I will probably get myself into all kinds of situations... Maybe you could teach me something? So I could assemble a helpful thing or two from some junk.}
{104}{020}{I have, uh... A specific task here. I need to unclog one to-i-let. It has too much... Sewage. Dangerous, and very smelly.}
{105}{021}{Remember you told me about repairing a plunger using a hammer?}
{106}{Barter}{Can you show me what you have in your stash?}
{107}{999}{I just came by to say hi. Okay, see you!}


{110}{}{Aren't you a little weasel? [he winks]. Okay, for a pack of sugar I can show you how to make a hand-grenade. Or I can teach you how to make a rusty breastplate, for two rolls of good tin. Well, you know, your hands are still pretty crooked, so I can't promise you can handle making these, but maybe in time you would do something about it? So - deal?}
{111}{012}{Deal! Here's your pack of sugar, teach me to make a grenade!}
{112}{013}{Deal, here,s your tin. Show me how to make a breastplate.}
{113}{014}{I have none of these things for now... Maybe you could just tell me this, as a friend?}
{114}{999}{No, that doesn't sound interesting. I'll come by later.}


{120}{}{[the sugar instantly disappears from your hand] Okay, here goes: you take a tin can... [Smitty starts to thoroughly explain the process of assembling hand-made grenades from junk.] ...And that's it, mostly. If you didn't get the details - it's your problem. And, of course, these grenades are not very powerful, but you still can scare the rats with them. Here, take one, for a start. Try it sometime.}
{121}{013}{Thanks, old man. By the way, I have a tin too. Tell me about making the breastplate.}
{122}{999}{Thanks, old man. This will come in handy.}


{130}{}{What a beauuuutiful tin! Look at how shiny it is! And the whole two rolls! I appreciate it greatly, now I have something to patch water tanks with. Oh, and you can use it to make a breastplate too! It will give you some protection in the wilds, which is quite good. So, here goes: you take one tin roll, and... [Smitty thoroughly explains how to create the breastplate from tin, using rolls you brought as a practical illustration] ...And there. Oh, look! While I was explaining it, I assembled a fine one! Take it, you need it more than me. Or give it to your brother, he likes to wage war against rats, heh-heh.}
{131}{012}{Thanks! This is very helpful. Hey, you know what? I also have some sugar! Come on, tell me, how do I make grenades?}
{132}{999}{That's how it is? Thank you, it will come in handy.}

{1401}{}{Hah, you're good at talking! And I can feel that you're a good man. Why wouldn't I help a good man? Okay, listen [and Smitty starts to thoroughly explain in smallest details talk about creating hand-made grenades and breastplate] ...And that's it, I hope it would come in handy.}
{141}{999}{Thanks, Smitty, it definitely will!}
{1402}{}{What a sly man! No, that doesn't work like that! You give me, then I give you, not the other way around. Sorry, friend. [he squints]}
{142}{015}{Okay, okay. When I find sugar and tin, I'll come back. Don't go anywhere! [wink]}


{150}{}{Where am I gonna go from here?}
{151}{999}{[leave Smitty to think about the meaning of your words]}


{200}{}{Oh, so, you need that, uh, how was it called... A PLUNGER! Of course, I had one somewhere... Around... Here! Wait, looks like the handle is broken... Yes, it is. I could fix it, of course, but I need a new handle. Bring me some hammer, it should do nicely.}
{201}{022}{Smitty, you're always like this: you have everything, but broken!}
{202}{023}{What a fine coincidence - I have a spare hammer with me!}
{203}{999}{I see. I'll go look for it.}


{210}{}{Of course I remember! So? Did you bring me the hammer? Or some handle?}
{211}{023}{Sure. Here.}
{212}{999}{No, I'm still looking.}


{220}{}{What do you think? That everything is easy? I'm ALWAYS making something useful practically from NOTHING. And sometimes you have to re-use the stuff you have, you know - but just to make those OTHER things better!}
{221}{999}{Yeah, for example, your Moonshine Machina Magnifico. I get it. Okay, I'll go look for a hammer.}
{222}{023}{Okay, okay. Don't get so defensive. Here's a hammer for you, give me that damn plunger.}


{230}{}{See? So many worries, so few actual problems! [Smitty instantly replaces the handle of a plunger with the one from a hammer] Here, take your "treasure", heh-heh. I hope you'll figure out how to use it.}
{231}{999}{Come on, give it to me already.}
{232}{999}{Don't you worry about it!}

#
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Положительная реакция)
# Положительные сообщения
{1000}{}{Hey, friend!}
{1001}{}{Hello! How are you doing?}
{1002}{}{Hello there!}
{1003}{}{Hey, friend! How are you?}
{1004}{}{I would gladly stop and chat... But let's do it some other time.}
{1005}{}{So good to see you!}
{1006}{}{Wanna chat? Suit yourself.}
{1007}{}{Listen, I stashed something for you. Okay, talk later.}
{1008}{}{You should come to me more often.}
{1009}{}{Of course! Come by anytime!}
# Нейтральные сообщения
{1010}{}{Don't bother me, I'm busy.}
{1011}{}{Can't you see? I have no time to spare.}
{1012}{}{Hey! I'm trying to make these damn mechanisms here to work again!}
{1013}{}{Listen, maybe not now? Good.}
{1014}{}{Instead of bugging me with questions, hand me over that wrench.}
{1015}{}{Listen, don't touch me, let me rest a little.}
{1016}{}{What else do you want?}
{1017}{}{...And then I'm like - you are sparking here! Hilarious.}
{1018}{}{...And then he's like - that's E-LEC-TREE-SEE-TEE!}
{1019}{}{Oh. Listen, let's talk a little later, okay?}
# Отрицательные сообщения
{1020}{}{Get lost, dumbass!}
{1021}{}{Get the hell out!}
{1022}{}{Better don't take your chances, you freak!}
{1023}{}{Screw you!!!}
{1024}{}{Make like a tree and get out of here.}
{1025}{}{You're gonna get punched in the face if you don't get lost!}
{1026}{}{Make yourself invisible!}
{1027}{}{What the heck do you want from me?!}
{1028}{}{How dare you?!}
{1029}{}{You piss me off! Go away!}
#
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Дополнительно)
#
{1030}{}{Alright, let's put this thingie here...}
{1031}{}{This thing into that thing, aaand... Damn it!}
{1032}{}{Wires, cords... And nothing works.}
{1033}{}{Oh! My favorite screws...}
{1034}{}{My hands are so shaky...}
{1035}{}{I definitely need a drink!}
{1036}{}{Yeah, that's a pretty bad case of hand-crookery...}
{1037}{}{It's alright, we're gonna patch you up.}
{1038}{}{May it burn in hell!}
{1039}{}{[rummages through some mechanism]}
