############################## 			
#Локация: Тартар 			
#Имя: Доктор Пэт 			
#Краткое описание: Доктор Олимпа, навсегда сосланный в Тартар 	
#Дата создания: 23.06.2013 			
############################## 			
#Для игры "Олимп 2207" 			
#Артем "Rainman" Самойлов 			
############################## 			
# 			
#ОПИСАНИЕ КРИТТЕРА 			
# 			
# до знакомства 			
{1}{}{You see dr. Pat.}			
{2}{}{A local healer, Pat. He is gloomy and dissatisfied with something, as always.}
# 			
# после знакомства 			
{3}{}{You see dr. Pat.}			
{4}{}{A local healer, Pat. He is gloomy and dissatisfied with something, as always.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ ДО ЗНАКОМСТВА
#
{10}{}{Oh, it's you... Your father is very sick. His body has accumulated too much... Harmful stuff.}
{11}{}{Doctor, is this the same thing that killed my mother and Catty's mother?}
{20}{}{Unfortunately, yes... I don't know how long will he last. Regular injections are of no use anymore. He needs a very powerful medicine, the kind of which I do not have.}
{21}{}{Surely, you can do something!... Damn. There's an injured Son of the Gods, he asked me to bring him the medicine, which is called "Heal-Up".}
{30}{}{Yes, I know. Why are you looking at me like that? The Gods informed me. Here - this is the last one.}
{31}{}{I'll deliver the medicine and be right back! Please, look after my dad.}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ ПОСЛЕ ЗНАКОМСТВА
#
{100}{}{Oh, my Gods! I didn't recognize you! Where did you get this... Wow. Looks just like the one on guards! Very smart, very!}
{104}{}{Oh, my Gods! I didn't recognize you! Where did you get this robe!? Looks just like the one on Heralds! Very smart, very!} 
{101}{011}{Yes, I know, thanks, doc. How's my father? Does he feel better?}
{102}{011}{Yeah, I'm that good. What's up with my dad?}
{103}{999}{Talk later, doc. I have a lot of things I need to do.}	
{110}{}{Of course, of course. Your father is very sick. I know you went outside, and... You probably have a lot of questions, but I can say only one thing - the cause of his illness is called "radiation". It's like invisible rays coming through everything around us. But some bodies, like your mom's - or your dad's - accumulate these rays, like a filter.}  				
{111}{014}{Too many words, doc! Just tell me, how do I help him?}	
{112}{012}{Sounds difficult. Where do these rays come from?}			
{113}{999}{I'm bored. Let's leave this boring conversation for later.}	
{120}{}{It's hard to say for sure, but it seems that these rays come from specific stones and metal. The tower beneath us is made of metal too, but only on the outside. On the inside, it is protected by anti-radiation stuff. I don't know for sure, engineers deal with it, not doctors.}   			
{121}{013}{En-gi-neers... Who? Are they the Sons of Gods too? Actually, who are these "Sons of Gods"? And who are the "Gods?" Do they live in the tower?} 
{130}{}{You are asking too many dangerous questions. I would be glad to tell you the truth, but I'm afraid this knowledge will only make more problems. I'm sure you'll find it all out in your time.}
{131}{014}{Fine, I don't have time for it anyway. How can I help my dad?} 
{132}{999}{Great! Thanks for the help. I'll go figure everything out right now.} 
{140}{}{There's only one thing that may - MAY - help your father. It's called "Antiradine". As I've heard, this drug can handle even the radiation poisoning this severe. You can get it only in one place - in the ruins of the old "Rainbow Pharmaceuticals" factory. Don't let the word "ruins" fool you - this factory is very much active and operating. They have a vile and vicious raider in charge, but I fail to see any other way to help your dad.}		
{141}{015}{So, I need to walk across the wastelands to another gang of bandits and ask them to give me rare and, obviously, not so cheap medicine?!} 	
{142}{016}{Raiders again? But... Goddamit. Someone has to answer for all this. Okay doc, tell me how to find them.} 			
{150}{}{What do you want me to do about it? Okay, here's another way - go to the surface and knock into the tower doors, then ask them to cure your father. The "Olympus" definitely possesses such kind of medicine - only they don't care about anyone, be it your father, me, or you!}
{151}{016}{I see. Well, if there's no other way - tell me how to find these "rainbow raiders".}  	
{160}{}{Why tell? Didn't you get accustomed to your organizer? [winks] I had one just like it once... Okay, look. [Pat takes your organizer and shows what buttons to press and what they do] Here, the factory's coordinates are now on your map. Remember - you should hurry with finding the cure. I don't think your father will last longer than a couple of weeks.}		
{161}{017}{I see. Antiradine then. I'll get it. Hang on, dad...}  			
{162}{018}{Understood. Thanks for the bits of advice, doc, I'll try not to be late.}  			
{163}{018}{Uh, we'll see how it goes. I wouldn't want to die looking for some stupid medicines. I'm off.}    	
{170}{}{You're just like your father. [he gives a tired smile] Go, and good luck.}  			
{171}{999}{[leave]}   	
{180}{}{I said what I had to. The rest is up to you.}  					
{181}{999}{[leave]}   	
{200}{}{Huh? Oh, it's you again, }   	
{201}{}{. I still can't get accustomed to your new appearance, hehe. What do you need?}  				
{202}{030}{Doc, how's my father?}
{203}{021}{I was thinking - maybe you need some help?}   
{204}{023}{About your request...}
{205}{Barter}{Show me what do you have in stock.}
{206}{999}{Uh, no, nothing. I better go.}

{207}{040}{Doc, I have some... Unusual female patient for you.}

{209}{}{Yes... Huh? What?}
{210}{}{Help? Hmm, why not, actually... Yes, seriously, do something helpful. But you need good hands and some medical skills. Yeah... You know how it is - we have all kinds of traumas, dislocations, and sprains here. Someone stucks something in the wrong place - and here it is, a new injury. And this someone can't work and feels pain. And there's only me here. It's not enough... So, would you help?} 
{211}{022}{Do you need me to fix dislocated wrists or something? Of course, I'll help, no problem!}  			
{212}{022}{You mean, to do a medic's job? I'm not sure... But I could try, why not.}  		
{213}{999}{To take care of sick and injured? Hell no, I don't have time for this. A lot of other things to do.}    	
{220}{}{That's wonderful! Okay, listen - run around the Farms and Maintenance level. If you see someone lying around and groaning, try to get them back on their feet. Not by force, of course, don't make it worse for them. Help at least six, and return to me. Meanwhile, I'll think about how to thank you for this. [he winks]}  			
{221}{PetsHelper}{I see, I see. Okay, off to heal injured and sprained.}  				
{222}{PetsHelper}{Assignment is taken, doc. See you soon!}   
{223}{999}{Six!? Too much, if you ask me. I was thinking about bringing you a couple of sick kids or something. Nah, some other time.}
{230}{}{So? How are my- I mean, your patients?}
{231}{999}{I'm working on it. Surprisingly, not many injured around here. I'll go look for more.}  		
{232}{024}{ are healed in total. Not without some accidental mistakes, but now everything is alright.}    
{233}{024}{I healed every injured I could find. Now they are back to work.}  					
{240}{}{Good, that's good. It's still a drop in the bucket, but at least now I can have one day off - and this means a lot! I can teach you some medical skills or give you 3 "Heal-Up" and 2 "Poison-Out". What will it be?}  	
{241}{025}{The skills are always handy! Share your skills with me.}  					
{242}{026}{A useful meds, doc! If I'm going to fight poisonous scorpions, they will help me a lot. I take them.} 
{243}{027}{I can't choose... Can I have both?}   
{250}{}{Okay, listen then... When you see a nasty wound... [he starts methodically and thoroughly describe all necessary actions for administering first aid] Okay, I hope this information comes in handy!} 	
{251}{999}{Thanks, doc. Although, I hope this information DOESN'T come in handy. See you.}  		
{260}{}{Good choice! Especially, "Poison-Out" - it has no analogs, and if you don't remove poison in time, it could be fatal to you.}					
{261}{999}{Thanks, doc. I hope I won't have to use them. See you!}  		
{2701}{}{What a sly! No, it doesn't work that way. Either I spend time teaching you or give you the meds. Oh, I have an idea! How about I just thank you and we call it a day?}
{271}{025}{Okay, I get it! Teach me some medical skills.}  			
{272}{026}{No, a deal is a deal, I take meds!!}  				
{2702}{}{It is a little unfair, don't you think? Okay, here, take your meds. And about skills - when you see a nasty wound... [he starts methodically and thoroughly describe all necessary actions for administering first aid] Okay, I hope all of this comes in handy!} 					
{273}{999}{Thanks, doc, nice to do business with you. [wink]}

{274}{999}{You know what, doc? Keep the meds and your knowledge to yourself. You would need it more around here, and I don't have time for lectures. See you.}  					
{3001}{}{Your father is barely holding up! If you won't bring me "Antiradine" soon, it can be too late.}   	
{301}{999}{I'm trying my best to find it, doc. Help my father to hold on for a little more, I'll be back soon!}    		
{302}{031}{Here, here is it! I brought the "Antiradine"! [give Pat the syringe]}    			
{3002}{}{John is getting better, nothing to worry about. He is still very weak, but your brother Kirk keeps an eye on him. I think your father will be alright. Give him time.}
{303}{020}{So good to hear good news, doc. I have some questions though.}  				
{304}{999}{Very good. I'm counting on you, doc.}    	
{3003}{}{I... I am truly sorry. You didn't make it in time.}    				
{305}{999}{I tried... I did everything I could. Father...}    				
{306}{999}{I tried... I did everything I could. [the syringe of "Antiradine" pops, crushed in your fist] Father...} 
{310}{}{What took you so long? What if it's too late? I hope it isn't... Give me that. [Pat puts a few drops into your dad's rolled eyes. John's body starts to shake uncontrollably] Don't stand there, help me to hold him! There, there, everything is going to be alright, John. [the seizure stops. Pat stands up] The condition is stable... That means he'll get better. Of course, he had to be taken care of, and periodically take drops of "Antiradine", but I think your brother Kirk will handle it just fine.}
{311}{032}{Phew... Thank Gods... I mean, it's good that I made it here in time. How long will it take for him to recover?}					
{312}{033}{Great, one less problem to worry about. I had to go through a lot to pull dad from the brink - yet he ended up there not by my fault. We are in danger because of their fault... Because of the "Gods".}  		
{313}{999}{Very good, because I need something else to do.}    			
{320}{}{I can't even assume... There were no such cases in my practice. It can potentially take months. Of course, if he was in the "Olympus", they would put him back on his feet in a week... But we are here, and we don't have the necessary equipment... I mean... Uhh...} 
{321}{033}{Again! It's always about the "Olympus"! If there's a problem, then the tower holds salvation! Is it really inhabited by the Gods?}  				
{330}{}{I know about the Gods not more than you. No one saw them. We heard their orders, saw the defiants they have killed, but no one has ever met them. Maybe you could talk to Herald Gregorius about it?}
{331}{999}{I could start from there. I will get to the truth.}    
{332}{999}{I will definitely figure it all out!}

{340}{}{Doc, look, I brought a "RadOut"! Everyone says it's good [hand doctor the injector]}
{341}{}{I've found a great potion from radiation, a well-known folk remedy! [give doctor "Wild Potion"]}
{342}{}{Here, I brought some anti-radiation pills! [show your "Radiom" pills]}

{343}{}{[Pat furiously waves hands] No, no-no-no! I told you clearly - it's "ANTIRADINE"! You should look for it in Rainbow Raiders, and it's the only thing that can help your father! Oh, Gods... If you can't remember it, write it down!}
{344}{999}{I get it. I'll go look for this... What was it again?}	


{400}{}{Unusual, you say? I bet someone from the Maintenance level is sticking their hands where they are not supposed to again...}
{401}{041}{No, actually this patient is somewhere far away from here. We have to venture outside.}
{402}{043}{Actually, I mean the savage woman, she lives in the mountains to the north. She has a nasty rotten wound.}

{410}{}{I haven't been outside in a really long time, I'm afraid that my old body won't handle the traveling.}
{411}{}{Don't worry, I know how to get there safely. Don't you want to breathe the fresh air of freedom again?}
{412}{}{I'll have you protected, I promise. That woman really needs your help.}

{420}{}{Well, if you know safe paths and protect me... Okay then! Would be nice to remember the old days and shake off some rust, right? Let's move out, while I didn't change my mind. But promise to take me back!}
{421}{}{Great! Just keep close to me.}
{422}{999}{You know, I need to do something around here. I'll be back.}

{430}{}{Not very convincing. Why would I go somewhere far to save someone I don't even know. No, I'm staying here.}
{431}{}{I can relate... Okay, I need to go.}
{432}{}{You have no compassion, doc! I'll handle it myself then.}

{50}{}{It's... You. What's even the point of talking to you? You're... Oh, Gods, how do you even live? Listen, your DAD needs a MEDICINE, it's called AN-TI-RA-DI-NE! You can find it here. [he points the Rainbow Raiders on the map of your organizer] Do you even understand what I just did?}					
{51}{999}{Ugh... Ughugh. Uh-huh. [nod and leave]}    				
{52}{}{What do you want? Oh, it's about your father. Did you bring me the "Antiradine"?}    	
{53}{Х11}{[hand him the syringe]}    				
{54}{999}{Nah. Ugh... Uglum. [leave]}    				
{55}{}{I'm sorry, but your father didn't make it. I am really sorry.}    	
{56}{999}{Woooooooo! [leave]}    				
{57}{}{Give it to me quick! [Pat puts a few drops into your dad's rolled eyes. John's body starts to shake uncontrollably] Don't stand there, help me to hold him! There, there, everything is going to be alright, John. [the seizure stops. Pat stands up] The condition is stable... That means he'll get better. Of course, he had to be taken care of, and periodically take drops of "Antiradine", but I think your brother Kirk will handle it just fine.}
{58}{999}{Ugh. Ughugugugh.}
{59}{}{What? Nothing? Just as I thought. Don't waste my time.}
{60}{999}{Brrrr... Ugh-ugh! [leave]}
#
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Положительная реакция)
#
{1000}{}{Let's deal with this quick.}
{1001}{}{Are you sure your patient is still alive by now?}
{1002}{}{It was a bad idea - to get involved in this.}
{1003}{}{This looked rigged from the start...}
{1004}{}{The faster you take me to the patient, the better for everyone.}
{1005}{}{It's done, right? Take me back to Tartarus.}
{1006}{}{Let's just get back home.}
{1007}{}{Enough of these adventures for me.}
{1008}{}{I don't really want to talk. Just take me back.}
{1009}{}{I'm very tired, let's get back to Tartarus quick.}
#
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Нейтральная реакция)
#
{1010}{}{This is a real robotron! Incredible! I've seen them only in pictures!}
{1011}{}{Wait a second, is this... You tamed a wild jackal? Unbelievable!}
{1012}{}{OH GOD! THIS BEAST IS ALWAYS GOING TO HANG AROUND, ISN'T HE?!}
{1013}{}{}
{1014}{}{}
{1015}{}{}
{1016}{}{}
{1017}{}{}
{1018}{}{}
{1019}{}{}
#
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Отрицательная реакция)
#
{1020}{}{}
{1021}{}{}
{1022}{}{}
{1023}{}{}
{1024}{}{}
{1025}{}{}
{1026}{}{}
{1027}{}{}
{1028}{}{}
{1029}{}{}
#
#ПЛАВАЮЩИЕ СООБЩЕНИЯ (Дополнительно)
#
{1030}{}{I'm busy with your father.}
{1031}{}{Are we healing or talking?}
{1032}{}{Not now, I'm tending your father.}
{1033}{}{}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}