##############################																																													
#Location: Tartar																																													
#Name: Dr. Pat																																													
#Short Description: Doctor Olympus, permanently exiled to Tartarus																																											
#Date of creation: 23.06.2013																																													
##############################																																													
#For the game "Olympus 2207"
#Artem "Rainman" Samoilov	
##############################	
#	
#CRITTER DESCRIPTION	
#	
# before meeting																																													
{1}{}{You see: Dr. Pat.}																																													
{2}{}{Local healer, Pat, looks gloomy and dissatisfied with something. As usual.}
#																																													
# after meeting																																													
{3}{}{You see: Dr. Pat.}																																													
{4}{}{Local healer, Pat, looks gloomy and dissatisfied with something. As usual.}
#
#HERE BEGINS A DIALOGUE BEFORE MEETING
#
{10}{}{Oh, it's you... Yes, your father is very sick. His body has accumulated too much... harmful stuff.}
{11}{}{Doctor, is this the same thing that killed my mother and Catty's mother?}
{20}{}{I am so sorry, but yes... I don't know how long will he last. A regular injections does not help anymore, you need a very powerful medicine, the kind of which I do not have.}
{21}{}{Sure you can do something! Hell, another son of the Gods asked me to bring medicine, Yoil-Up is called.}
{30}{}{Yes, I know. Why are you looking at me like that? I was informed about this by the gods. Here - but this is the last one.}
{31}{}{I'll take the medicine and be right back! Look after father.}
{16}{}{}
{17}{}{}
{18}{}{}
{19}{}{}
#
#HERE BEGINS A DIALOGUE AFTER MEETING
#
{100}{}{Oh, my gods! You do not know! Where did you get this... Well, it is necessary, just like the guards! Very clever, very!}
{104}{}{Ah, my gods! You do not know! Where did you get this hoodie!? Wow, just like messengers! Very clever, very!}
{101}{011}{Yes, I know, thank you. Doc, what about father? Is he feeling better?}
{102}{011}{Yes, yes, well done. What's up with the father?}
{103}{999}{Doc, listen, then we'll talk, I have a lot more to do here.}
{110}{}{Yes, of course. Your father is extremely ill. I know you were upstairs, and... Surely you have a lot of questions, but I can only say one thing: radiation. Such a thing as invisible sunshine, they permeate everything around, but some bodies, like, for example, the body of your mother and father, absorb these rays, like a filter retains in itself.}
{111}{014}{How many unnecessary words, doc! Just tell me how to help him?}
{112}{012}{This is so difficult... Where do these rays come from?}
{113}{999}{I felt bored, continue this tedious conversation later.}
{120}{}{It is difficult to say for sure, but it seems to me that these rays come from special stones and from metal. The tower that is above us is all metal, but it is covered with metal on the outside, and from the inside it is protected by anti-radiation... things. I don't know for sure, engineers, not doctors, deal with it.}
{121}{013}{Instances. Who is it? Are they also "Sons of Gods"? Who are these "Sons of Gods"? And who are the "gods"? And where do they actually live? In that tower upstairs, eh?}
{130}{}{You ask too many dangerous questions. I would be glad to share with you the truth, but I'm afraid this knowledge will harm you. I am sure you will know everything in due time. Gradually.}
{131}{014}{Well. Well, in any case, we have no time for that. How can I help my father?}
{132}{999}{Great! Thanks a lot for your help! I'll go and figure it out right now!}
{140}{}{Your father can, I repeat - only one remedy CAN help - antiradin. As far as I know, only this drug can raise such an advanced radiation sickness. You can get it only in one place - on the ruins of the old factory Rainbow Pharmaceuticals. But do not be confused by the word "ruin"! This is a functioning factory, cruel raiders are in charge of everything, but I don't know any other way to help your father.}
{141}{015}{That is, I need to go through the wasteland directly to the next gangsters and pirates, and ask them for a rare and, obviously, expensive medicine!}
{142}{016}{Readers again? But... Damn it. Someone will have to answer for all this. Yoroshko doc, let's tell me how to find them.}
{150}{}{What do you want from me? Yoroshho, here's another way for you... you go upstairs, knock on the gates of the tower and ask them to help your father! Surely in the "Olympus" e there is the right medicine, but that's just they do not care about your father! And they don't care about you! And me too...}
{151}{016}{Understandable. Well, if there is no other way - tell me how to find these "rainbow bandits."}
{160}{}{Why tell? Are you not used to the organizer? [winks] Uh-oh, I used to have this one too... Well, well, look [Pat has been digging around for some time with your organizer, telling what buttons and in what order you need to press] Well, now the coordinates of the factory crammed into the card. I just have to warn you - you'd better hurry with this anti-darling, judging by all the signs your father has not more than one and a half weeks left.}
{161}{017}{Clearly, I understood everything. So - "an-ty-ra-din." I'll get it. Father, just hold on!}
{162}{018}{I understand everything. Okay, thanks for the advice, doc. I will try not to be late.}
{163}{018}{Um, well, let's see by the circumstances. I would not like to just die there because of some drugs. I will go.}
{170}{}{All in the father [smiles exhausted]. Go, and let luck be with you.}
{171}{999}{[OUTPUT]}
{180}{}{I said what I had to say. The rest is your business.}
{181}{999}{[OUTPUT]}
{200}{}{Um? Oh, you again,}
{201}{}{. All I can not get used to your mind, hehe. Do you need anything else?}
{202}{030}{Doc, what about my father?}
{203}{021}{I thought maybe something you need help here?}
{204}{023}{About that assignment...}
{205}{Barter}{Remind me, what is left of your stock?}
{206}{999}{Um, no, nothing. I think I will go.}

{207}{040}{I have for you... an unusual patient.}

{209}{}{Yes Yes. Em, what else?}
{210}{} {Help? You? Yomm, why not help? Indeed, come on, get busy. Only here need sensitive hands. Well, skills in medicine will not interfere. Yeah, well... You know yourself, how many bruises, sprains, dislocations are here. Constantly, someone will put something somewhere in the wrong place - and here you are, an injury. And a person cannot work, and it is bad for a person, it hurts. And I'm not enough for everyone at all... Well, how can you help me?}
{211}{022}{Do I need a sprained wrist or something to insert? Well, of course, I will help without any problems!}
{212}{022}{Is this a medical man doing some work? I'm not sure... but I can try, why not.}
{213}{999}{Do you bother with the sick and bruised? Here's another. No, not before me now. Yes, and many other cases.}
{220}{}{That's wonderful! So look... go over the farms and the technical level. When you see someone wallowing and moaning - try to raise him to his feet. Not by force, of course, but the worse things are worse for the poor fellows. Man 6 podlateat - come back. In the meantime, I'll think about how to thank you for such help [winks]}
{221}{PetsHelper}{Clear, understandable. I'll go treat the bruised and stretched.}
{222}{PetsHelper}{Ok doc, the task is accepted. See you later!}
{223}{999}{6 people!? Something is a bit too much. I thought a couple of kids would be brought to you for treatment. Nah, I'm some other time.}
{230}{}{Well, how are my friends, that is, your patients?}
{231}{999}{Working on it. Surprisingly not too many injured. I'll go look for them.}
{232}{024}{fighters returned to labor. Not without a couple of annoying mistakes, but mostly everyone is happy.}
{233}{024}{Cured all those found. Now they are working, they do not complain.}
{240}{}{Well, fine. This is, of course, a drop in the ocean, but you gave me one day of quiet life, and this is at least something worth it! I can offer you a choice to teach you the skills of medicine, or 3 "Yoill-Up" and + 2 "Poison-Out" and?}
{241}{025}{Medical skills will always come in handy! Share your experience.}
{242}{026}{Useful drugs, doc! If I will fight with poisonous scorpions - they will be very useful to me! I take drugs.}
{243}{027}{I just can't choose... Can you do both?}
{250}{}{Well, see... when you see a bleeding wound... [begins to describe all the basic medical actions for a long time and in detail] Well, I hope this information will be useful to you!}
{251}{999}{Thank you, Doc. True, I hope that this information is NOT SUITABLE for me. Happily!}
{260}{}{Excellent choice, reliable! Especially "Poyzon-Out" can be useful, it has no analogues, and in fact if the poison is not removed from the body in time, the consequences can be... fatal.}
{261}{999}{Thank you, Doc. True, I hope that these drugs are NOT SUITABLE for me. Happily!}
{2701}{}{Oh, you sly! No, that won't do. Either I spend my time on your studies, or I give you my drugs. By the way, I had an idea... I'll just say thank you to you, and we'll get to it!}
{271}{025}{Understandable. Medical skills will always come in handy! Share your experience.}
{272}{026}{No, persuasion is persuasion, I take drugs!}
{2702}{}{This, of course, is a little dishonest of you, but so be it, hold the drugs. And at the expense of medicine - look... when you see a bleeding wound... [begins to describe all the basic medical actions for a long time and in detail] Well, I hope this information will be useful to you!}
{273}{999}{Thank you doc, it's nice to deal with you [wink]}

{274}{999}{And you know, the doc - keep your knowledge and medicines with you. Local, they are more useful, but now I do not have time for lessons. Stay by Do not cough.}
{3001}{}{Your father is holding out! If you don't bring antiradin as soon as possible, I'm afraid it may be too late to try to get him on his feet.}
{301}{999}{I try my best to get it. Doc, help my father hold out for a while, I'll be back soon!}
{302}{031}{Here it is, here it is! "ANTIRADIN"! [Give Pat a bottle]}
{3002}{}{John is recovering, nothing to worry about. Of course, he is still very weak, but your brother Kirk constantly looks after him, so I think over time your father will overcome the disease.}
{303}{020}{So good to hear the good news. Something else is interesting to me.}
{304}{999}{Well. That's good... I hope for you, doc.}
{3003}{}{I... sincerely... sorry. You did not have time...}
{305}{999}{I tried. I did everything I could. Father...}
{306}{999}{I tried. I did everything I could [a vial of "antiradin" and bursts in your fist] Father...}
{310}{}{Something you long, could not have time! Well, I hope it's not too late [Pat buries a few drops in your father's rolled eyes. John's body is starting to hit cramps] What are you standing for !? Help me keep it up! Doom, like this, everything will be fine, John. [convulsions pass, Pat straightens up] The reaction is normal, it means he will recover. Of course, it is necessary to look after him all the time and from time to time to bury his "antiradin", but I think your brother Kirk will cope with it perfectly.}
{311}{032}{Ffu-uh. Glory to the gods... that is... well, that I managed. How long will father come to life?}
{312}{033}{Great, one problem less. I had to go through a lot to get my father out of the world, but he was there through no fault of mine. We are all in danger because of their fault... "Gods."}
{313}{999}{Well, well, and here I need to do something else.}
{320}{}{I can't even imagine. In my practice, such cases have not yet been, it may take months to restore it. Of course, in the "Olympus" could raise it for a week... that is, we are here, and we do not have the necessary equipment here... that is... well, y...}
{321}{033}{Olimp again! If there is any problem, then its solution is in this tower. There that, however, live all-powerful "Gods", able to work wonders?}
{330}{}{I know little more about "Gods" than you. No one has ever seen them. We heard their orders, they killed the infidels, they guided us, but no one ever saw them. Maybe you should try to talk to the messenger Gregorius?}
{331}{999}{Mmm, you can start with this. You need to get to the truth.}
{332}{999}{I will definitely figure it out!}

{340}{}{Doctor, here - I brought a "glad-out"! He is all praised... [to give a doctor an injection]}
{341}{}{I found an excellent means of radiation sickness, folk! [to reach out to the doctor "iron antiradium"]}
{342}{}{Here, I brought radiation pills! [show on the palm of the tablet "radio"]}

{343}{}{[Pat furiously waves his hands] No, no, no! I clearly said - "AN-TI-RA-DIN", it should be looked for in Rainbow Raiders! Only this can help your father! Gods! you can not remember - so at least write somewhere!}
{344}{999}{Understandable. Looking for this... what did you call it there?}	


{400}{}{Unusual, you say? Someone from tech level again thrust his finger where it should not?}
{401}{041}{No, in fact, it is quite far from here. We'll have to go outside.}
{402}{043}{No, I'm talking about a savage in the rocks in the north. She has a festering wound.}

{410}{}{I haven't been outside for a long time, I'm afraid my decrepit body will not suffer any travels.}
{411}{}{Don't worry, I know the safe way. Don't you want to breathe the air of freedom just once?}
{412}{}{I will protect you, everything will be fine. A woman really needs your help.}

{420}{}{Well, since you know a safe road - why not shake the old days, eh? Come before I change my mind. But promise to bring me back!}
{421}{}{Great! Just keep up with me.}
{422}{999}{You know, I still have some things to do here. I'll be back soon.}

{430}{}{It sounds completely unconvincing. I do not see why I should go somewhere and save someone there. No, I'm not going anywhere.}
{431}{}{Yes, you can be understood. Okay, I have to go.}
{432}{}{No compassion for your neighbor! Well, I'll figure it out.}


										
{50}{}{It's you. What is the point of talking to you? You... Oh Gods, how does the earth carry you like this? Listen up Your father needs medicine, called AN-TI-RA-DIN. You can find it here [marks on your organizer the location of Raibow Raiders]. Do you even understand what I did?}
{51}{999}{Abr... Abrrybrrr. Yep [nod and leave]}
{52}{}{What else do you need? Aah, about your dad. Did you bring antiradin?}
{53}{X11}{[stretch the vial]}
{54}{999}{Nah. Cleaned up-ah [out]}
{55}{}{I'm sorry, but your father did not wait for your help. I'm really sorry.}
{56}{999}{Woo-hoo! [output]}
{57}{}{Let's get here soon! [Pat buries a few drops in your father's rolled eyes. John's body is starting to hit cramps] What are you standing for !? Help me keep it up! Doom, like this, everything will be fine, John. [convulsions pass, Pat straightens up] The reaction is normal, it means he will recover. Of course, it is necessary to look after him all the time and from time to time to bury his "antiradin", but I think your brother Kirk will cope with it perfectly.}
{58}{999}{Yeah. Yyyyyy}
{59}{}{What do you want? Nothing? I thought so. Do not take my time.}
{60}{999}{Brrr.. Um-Um! [output]}
#
#FLOATING MESSAGES (Positive reaction)
#
{1000}{}{Let's get this over with quickly.}
{1001}{}{Are you sure your patient has not died yet?}
{1002}{}{Oh, and in vain I got involved in it...}
{1003}{}{I didn't like this idea from the very beginning.}
{1004}{}{The sooner you show me the patient, the better for everyone.}
{1005}{}{It's done, right? Take me back to Tartar.}
{1006}{}{Let's just get home as soon as possible.}
{1007}{}{Fuck off your adventures.}
{1008}{}{I don't want to talk, just take me back.}
{1009}{}{I am very tired, let's get back to Tartarus soon.}
#
#FLOATING MESSAGES (Neutral Reaction)
#
{1010}{}{This is a real Robotron! Oh wow! I only saw them in the pictures!}
{1011}{}{Wait, this is... did you tame a wild jackal? Amazing!}
{1012}{}{DAMN! THIS BEAST WILL ALWAYS BE WITH US!}
{1013}{}{}
{1014}{}{}
{1015}{}{}
{1016}{}{}
{1017}{}{}
{1018}{}{}
{1019}{}{}
#
#FLOATING MESSAGES (Negative reaction)
#
{1020}{}{}
{1021}{}{}
{1022}{}{}
{1023}{}{}
{1024}{}{}
{1025}{}{}
{1026}{}{}
{1027}{}{}
{1028}{}{}
{1029}{}{}
#
#FLOATING MESSAGES (Optional)
#
{1030}{}{I am busy with your father, do not interfere.}
{1031}{}{We will treat or chat?}
{1032}{}{Not now, I'm working on your father.}
{1033}{}{}
{1034}{}{}
{1035}{}{}
{1036}{}{}
{1037}{}{}
{1038}{}{}
{1039}{}{}