##############################
#Локация: Тартар
#Имя: Грегориус
#Краткое описание: Вестник Грегориус на фермах Тартара
#Дата создания: 11.11.2014
##############################
#Для игры "Олимп 2207"
#Артем "Rainman" Самойлов
##############################
#
#ОПИСАНИЕ КРИТТЕРА
#
# до знакомства
{1}{}{You see a Herald Gregorius.}
{2}{}{A permanent Herald of the Gods. Since forever.}
#
# после знакомства
{3}{}{You see a Herald Gregorius.}
{4}{}{A permanent Herald of the Gods. Since forever.}
#
#ЗДЕСЬ НАЧИНАЕТСЯ ДИАЛОГ
#
#Node001
{10}{}{A Seeker? What do you want? It's not good for Servants to see soldiers near the Herald.}
{11}{997}{I lost my keycard to the tower somewhere around here, maybe you have seen it?}
{12}{997}{Could you remind me how to get into the Olympus?}
{13}{002}{I'm on a mission. Just checking how you are doing here.}
{14}{999}{Of course. You're right. I'm going.}

#Node002
{20}{}{Wh-What?! Oh, you must be from Richards. Why didn't you say so! Tell him that he is serving here next! [he laughs]}
{21}{997}{Who the hell is Richards? Do you want to take the wrath of Gods upon yourself?}
{22}{999}{Sure, I'll tell him. Have a good service.}

#Node003
{30}{}{Okay, it's you again. Stop hanging around, or I tell Richards. No joke.}
{31}{998}{What? I'll shut you up and you won't tell anything to anyone!}
{33}{999}{I get it, already leaving.}

#Node004
{40}{999}{Empty}
{41}{999}{Empty}

#Node005
{50}{}{Uhh... Herald? Wait, Steve? Is that really you!?}
{51}{006}{Uh, yeah. Hey, Gregorius!}
{52}{007}{Steve? No, I'm not Steve. I don't know who are you talking about.}

#Node006
{60}{}{Hey... Smart-ass. I saw poor Steve being eaten by Chimera with my own eyes. Your robe still has his blood on it. Take off your hood! Now!}
{61}{997}{I was just kidding, old man! Of course, I'm not him.}
{62}{998}{[throw yourself at Gregorius]}
{63}{997}{Don't you dare touching me, Herald!}

#Node007
{70}{}{You have to excuse me. It's just... You have his robe. I saw poor Steve being eaten by Chimera with my own eyes. The Seekers are doing a pretty good job if they managed to even bring his robe back...}
{71}{008}{I didn't have a choice, had to take what was given.}

#Node007a
{72}{}{[he stares at you for some time] I'm bad at humor. Even worse, when it's about my dead teammates, rookie. Okay, I'll let it slide for the first time. Our Seekers are doing a pretty good job if they managed to even bring his robe back... [he suspiciously squints]}
{73}{008}{I didn't have a choice, had to take what was given.}

#Node008
{80}{}{So, Richards is actually preparing someone to take my place? It's okay, I guess it's time for me to remember the old days... For now, you can hang around, maybe pick up some "voice of the Gods" manneurisms [he chuckles]}
{81}{999}{If you say so.}
{82}{008a}{Of course, "teacher". [chuckle] By the way, aren't you tired of getting here through the metro station all the time?}

{83}{}{Through a METRO STATION?! [he looks very surprised] Huh... Listen, I think Richards and Spock played a joke on you. Or maybe you did something to piss them off, if they haven't assigned the elevator keycard to you. Huh... Wait! My memory is not as good as before... The second 2B card got completely demagnetized, so Richards asked his buddy, a Seeker named Douglas, to go to some place called "Army Headquarters", to pick up a spare. I'm not giving you my keycard, that's for sure, but you can wait for Douglas - or to go look for him.}
{84}{999}{Thanks for the lead!}

#Node009
{90}{}{Are you still here, rookie? How do you like it here? The job is so-so, of course, but you are not getting shot or bitten here, that's for sure. [starts pondering]}
{91}{999}{A wise words.}
{92}{999}{Yeah, sure.}
{93}{999}{Uh-huh.}

#Node997
{98}{}{I don't know who you are - but you shouldn't be here! AN INTRUDER! ATTACK HIM!!}
{99}{998}{[fight]}

#Node100
{100}{}{You successfully recorded voice of Gregorius on your modulator.}
#Спец сообщения - Утро
#
{1030}{}{Servant? I have no tasks for you today.}
{1031}{}{I heard your father had an illness.}
{1032}{}{Remember! The will of the Gods is everything!}
{1033}{}{Don't judge the Gods, for they are the wisest!}
{1034}{}{You are keeping all of us alive by doing your serving!}
{1035}{}{No one can stay alive outside of Tartarus, our home!}
{1036}{}{Taste the food of the Gods and take upon your tasks!}
{1037}{}{Don't you dare to sleep on this fine holy day!}
{1038}{}{Wash your eyes of nightmares and go back to serving!}
{1039}{}{Praise the Gods, our protectors and patrons!}
#
{1040}{}{The Gods have given us a new day!}
{1041}{}{Let's praise the Gods with a morning prayer!}
{1042}{}{The Gods have defeated demons of the night again!}
{1043}{}{Those who are asleep shall be woken up immediately!}
{1044}{}{Rise, shine, Servants of Gods!}
{1045}{}{Wake up the children - let them live and rejoice in rise!}
{1046}{}{Taste the food of the Gods and take upon your tasks!}
{1047}{}{Don't you dare to sleep on this fine holy day!}
{1048}{}{Wash your eyes of nightmares and go back to serving!}
{1049}{}{Praise the Gods, our protectors and patrons!}
#Спец сообщения - День
{1050}{}{The day has come, diabolical heat of the sun again kills the remains of life on the surface!}
{1051}{}{Who is feeling hot - you should ask Wardens for water.}
{1052}{}{Who feels overworked - rest for a quarter of an hour.}
{1053}{}{Servants! Do not overeat!}
{1054}{}{Who left his task uncompleted - you shall tell Warden!}
{1055}{}{Rest not more than it's allowed to you by the God's law!}
{1056}{}{No time to rest, Servants! Get back to your tasks!}
{1057}{}{Patch up the water tanks, for us to have something to quench our thirst!}
{1058}{}{Do not approach the caves!}
{1059}{}{Take good care of your children!}
#Спец сообщения - Вечер
{1060}{}{The heat's coming down - evening has come!}
{1061}{}{Work relentlessly in the name of Gods!}
{1062}{}{Do not stop doing your work, and you will ALL be rewarded!}
{1063}{}{Keep working for the good of your children!}
{1064}{}{Respect Wardens and be grateful for their efforts!}
{1065}{}{Maintain the cleanliness in your lodges!}
{1066}{}{Put your children to bed early, for them not to interrupt you form working!}
{1067}{}{Finish all the daily tasks of yours!}
{1068}{}{Start your most important jobs - the evening air favors you!}
{1069}{}{Say the evening prayers to your Gods!}
#Спец сообщения - Ночь
{1070}{}{The cold of the night comes from the caves!}
{1071}{}{Do not dare to rest while the cool air lets you do your work!}
{1072}{}{Do not interrupt the dreams of your children!}
{1073}{}{The creatures of the night from the Purgatory are attacking us again!}
{1074}{}{Do not approach the caves, for not to be eaten by the demons of the night!}
{1075}{}{Do not close your eyes, as I never get tired!}
{1076}{}{Do not lay to rest without resolve from Wardens!}
{1077}{}{Praise the Gods for the freshness of this night!}
{1078}{}{Take care of a fresh water, Servants!}
{1079}{}{Feed lavash in their pens, for them to feed us with their flesh!}