{100}{}{the fire}
{101}{}{The flames light up space around them.}
{200}{}{a door}
{201}{}{An old and battered metal door.}
{300}{}{a trash can}
{301}{}{A too-small container in the fights against littering.}
{400}{}{a wooden table}
{401}{}{An old table with a dirty tablecloth.}
{500}{}{a metal barrel}
{501}{}{An old steel barrel.}
{600}{}{a metal barrel}
{601}{}{An old empty steel barrel.}
{700}{}{tires}
{701}{}{A stack of old rubber tires.}
{800}{}{a wall}
{801}{}{This section of the wall stands out.}
{900}{}{a terminal}
{901}{}{A calculator terminal.}
{1000}{}{a terminal}
{1001}{}{A calculator terminal.}
{1100}{}{a calculator}
{1101}{}{A calculator terminal is hooked to a mainframe.}
{1200}{}{a calculator}
{1201}{}{A calculator terminal is hooked to a mainframe.}
{1300}{}{a terminal}
{1301}{}{A calculator terminal.}
{1400}{}{a terminal}
{1401}{}{A calculator terminal.}
{1500}{}{a bull head}
{1501}{}{Looks like this head of a Lavash is really happy to be canned.}
{1600}{}{tires}
{1601}{}{Hardened old tires covered in sand.}
{1700}{}{a pit}
{1701}{}{A shallow indention in the ground.}
{1800}{}{a door}
{1801}{}{A high-tech metal door.}
{1900}{}{a door}
{1901}{}{A high-tech metal door.}
{2000}{}{a battery}
{2001}{}{A big and old empty battery.}
{2100}{}{a tire}
{2101}{}{A useless old tire.}
{2200}{}{a huge statue}
{2201}{}{You read somewhere that it depicts Themis, the Goddess of Justice.}
{2300}{}{a door}
{2301}{}{A high-tech metal door.}
{2400}{}{a tire}
{2401}{}{A useless old tire.}
{2500}{}{a monitor}
{2501}{}{A large wall-mounted monitor.}
{2600}{}{a monitor}
{2601}{}{A large wall-mounted monitor.}
{2700}{}{a tire}
{2701}{}{A hardened old tire, not worth digging up.}
{2800}{}{rocks}
{2801}{}{A pile of round stones.}
{2900}{}{a junk}
{2901}{}{It used to be a large important part of a machine, now it's just useless junk.}
{3000}{}{a monitor}
{3001}{}{A large wall-mounted monitor.}
{3100}{}{a monitor}
{3101}{}{A large wall-mounted monitor.}
{3200}{}{a vent}
{3201}{}{A part of the ventilation system.}
{3300}{}{a vent}
{3301}{}{A part of the ventilation system.}
{3400}{}{a bed}
{3401}{}{A very dirty bed. Your own in Tartarus is way much cleaner.}
{3500}{}{a bed}
{3501}{}{A very dirty bed. Your own in Tartarus is way much cleaner.}
{3600}{}{a bed}
{3601}{}{A very dirty bed. Your own in Tartarus is way much cleaner.}
{3700}{}{a bed}
{3701}{}{A dirty bed. Your own in Tartarus way is much cleaner.}
{3800}{}{a elevator}
{3801}{}{This is a service elevator.}
{3900}{}{a chair}
{3901}{}{A chair with armrests. It looks comfortable.}
{4000}{}{a chair}
{4001}{}{A chair with armrests. It looks comfortable.}
{4100}{}{a chair}
{4101}{}{A chair with armrests. It looks comfortable.}
{4200}{}{a chair}
{4201}{}{A chair with armrests. It looks comfortable.}
{4300}{}{a junk}
{4301}{}{Completely useless junk.}
{4400}{}{a junk}
{4401}{}{Nothing worth finding here.}
{4500}{}{a junk}
{4501}{}{Some metal fragments and old crates. It's scarcely usable.}
{4600}{}{a junk}
{4601}{}{Nothing worth finding here.}
{4700}{}{a chair}
{4701}{}{Better not to use it for its intended purpose, it looks like it's going to fall apart.}
{4800}{}{a chair}
{4801}{}{Better not to use it for its intended purpose, it looks like it's going to fall apart.}
{4900}{}{an exit grid map marker}
{4901}{}{an exit grid map marker}
{5000}{}{a well}
{5001}{}{An old dried-out well.}
{5100}{}{a chair}
{5101}{}{A common chair with armrests.}
{5200}{}{a chair}
{5201}{}{A common chair with armrests.}
{5300}{}{a chair}
{5301}{}{A common chair with armrests.}
{5400}{}{a chair}
{5401}{}{A common chair with armrests.}
{5500}{}{a vent grill}
{5501}{}{A part of the ventilation system.}
{5600}{}{a vent grill}
{5601}{}{A part of the ventilation system.}
{5700}{}{a chair}
{5701}{}{There is nothing unusual about this chair.}
{5800}{}{a chair}
{5801}{}{There is nothing unusual about this chair.}
{5900}{}{a chair}
{5901}{}{There is nothing unusual about this chair.}
{6000}{}{a chair}
{6001}{}{There is nothing unusual about this chair.}
{6100}{}{a table}
{6101}{}{It looks old and scratched.}
{6200}{}{a table}
{6201}{}{It looks old and scratched.}
{6300}{}{a cactus}
{6301}{}{A small cactus with large spines.}
{6400}{}{a cactus}
{6401}{}{You've heard that cacti make good tequila.}
{6500}{}{a cactus}
{6501}{}{Green and very prickly.}
{6600}{}{a door}
{6601}{}{A broken metal door.}
{6700}{}{a secret blocking hex}
{6701}{}{Help! I was kidnapped and forced to describe objects!}
{6800}{}{an entrance}
{6801}{}{An entrance to the factory building.}
{6900}{}{a stalagmite}
{6901}{}{A natural extension of the rock floor.}
{7000}{}{a stalagmite}
{7001}{}{A natural extension of the rock floor.}
{7100}{}{a crevice}
{7101}{}{A deep fissure in the ground.}
{7200}{}{a rock column}
{7201}{}{This thick column of rock extends from floor to ceiling.}
{7300}{}{a rock column}
{7301}{}{This thin column of rock extends from floor to ceiling.}
{7400}{}{rocks}
{7401}{}{You study the rocks for a while, but they never move.}
{7500}{}{rocks}
{7501}{}{You keep a close eye on these rocks, in case they move to attack you.}
{7600}{}{a waterflow}
{7601}{}{An underground river, that goes into the bowels of the cave. You can't see anything in the dark.}
{7700}{}{a gate}
{7701}{}{A wooden gate.}
{7800}{}{rocks}
{7801}{}{A large pile of rocks. They look indigenous to this region.}
{7900}{}{rocks}
{7901}{}{A small pile of rocks.}
{8000}{}{rocks}
{8001}{}{A small pile of rocks.}
{8100}{}{rocks}
{8101}{}{A large pile of rocks.}
{8200}{}{a hole}
{8201}{}{A small hole in the ground, very unlikely to fall in.}
{8300}{}{a hole}
{8301}{}{A small hole in the ground, very unlikely to fall in.}
{8400}{}{a crack}
{8401}{}{A quite deep cut in the ground.}
{8500}{}{cracks}
{8501}{}{Several cracks in the ground.}
{8600}{}{a crack}
{8601}{}{A quite deep cut in the ground.}
{8700}{}{gates}
{8701}{}{Wooden gates, they open and close.}
{8800}{}{a gate}
{8801}{}{A wooden gate.}
{8900}{}{a gate}
{8901}{}{A wooden gate.}
{9000}{}{a merchant shop}
{9001}{}{You can buy armor or weapons here.}
{9100}{}{a merchant shop}
{9101}{}{You can buy armor or weapons here.}
{9200}{}{rocks}
{9201}{}{Rocks, rocks, rocks! Everywhere you look, rocks!}
{9300}{}{a lamp}
{9301}{}{A source of lighting.}
{9400}{}{a lamp}
{9401}{}{A source of lighting.}
{9500}{}{a seat}
{9501}{}{It was once a car seat.}
{9600}{}{a seat}
{9601}{}{It was once a car seat. Looks dirty and uncomfortable.}
{9700}{}{a seat}
{9701}{}{It was once a car seat. Looks dirty and uncomfortable.}
{9800}{}{a seat}
{9801}{}{It was once a car seat.}
{9900}{}{a couch}
{9901}{}{A very dirty and smelly couch you don't want to sit on.}
{10000}{}{a couch}
{10001}{}{A very dirty and smelly couch you don't want to sit on.}
{10100}{}{plants}
{10101}{}{Rocks among some bushes.}
{10200}{}{a shrub}
{10201}{}{A dried outтрав€нистое растение.}
{10300}{}{a shrub}
{10301}{}{Some sort of desert weed.}
{10400}{}{a shrub}
{10401}{}{A dry herbaceous plant.}
{10500}{}{a shrub}
{10501}{}{A dry herbaceous plant.}
{10600}{}{a shrub}
{10601}{}{A dry herbaceous plant.}
{10700}{}{a shrub}
{10701}{}{Some sort of desert weed.}
{10800}{}{a shrub}
{10801}{}{A dry herbaceous plant.}
{10900}{}{a shrub}
{10901}{}{A dry herbaceous plant.}
{11000}{}{a shrub}
{11001}{}{Some sort of desert weed.}
{11100}{}{a bush}
{11101}{}{Some sort of desert weed.}
{11200}{}{a bush}
{11201}{}{A small, completely dry bush.}
{11300}{}{a bush}
{11301}{}{A small, completely dry bush.}
{11400}{}{a bush}
{11401}{}{“ипичный представитель Herba Vulgaris.}
{11500}{}{a bush}
{11501}{}{A typical representative of Herba Vulgaris.}
{11600}{}{a bush}
{11601}{}{A typical representative of Herba Vulgaris.}
{11700}{}{a plant}
{11701}{}{A typical representative of Herba Vulgaris.}
{11800}{}{a plant}
{11801}{}{A dry bush}
{11900}{}{a cactus}
{11901}{}{It's amazing how tall these cacti grow.}
{12000}{}{rocks}
{12001}{}{A pile of rocks.}
{12100}{}{rocks}
{12101}{}{You could fry eggs on these stones.}
{12200}{}{a rock}
{12201}{}{You look carefully, but it's just an ordinary stone.}
{12300}{}{rocks}
{12301}{}{A couple of rocks.}
{12400}{}{rocks}
{12401}{}{A pile of rocks.}
{12500}{}{human bones}
{12501}{}{You look at them for a while and think about the impermanence of existence.}
{12600}{}{bones}
{12601}{}{The skeleton of some poor guy.}
{12700}{}{bones}
{12701}{}{You'll be nothing but a pile of bones someday, too.}
{12800}{}{a blocking hex (nolight)}
{12900}{}{a wall}
{12901}{}{A damaged section of the wall.}
{13000}{}{a wall}
{13001}{}{A damaged section of the wall.}
{13100}{}{a wall}
{13200}{}{a wall}
{13201}{}{A damaged section of the wall.}
{13300}{}{a wall}
{13400}{}{a wall}
{13500}{}{an energy generator}
{13501}{}{It's a big, complicated machine, probably relates to electricity.}
{13600}{}{a wall}
{13601}{}{A damaged section of the wall.}
{13700}{}{a chair}
{13701}{}{This chair is ruined.}
{13800}{}{a chair}
{13801}{}{This chair is ruined.}
{13900}{}{a ladder}
{13901}{}{It's an old, fairly rickety ladder. It looks like it will barely support your weight.}
{14000}{}{a trapdoor}
{14001}{}{An outside hatch that leads down.}
{14100}{}{a light source}
{14200}{}{a door}
{14201}{}{A strong metal door.}
{14300}{}{a door}
{14301}{}{A rusty but still sturdy metal door.}
{14400}{}{a cover}
{14401}{}{A heavy manhole cover. It seems to be well-preserved.}
{14500}{}{stuff}
{14501}{}{A huge, promising pile of junk. And absolutely nothing useful... what a disappointment!}
{14600}{}{stuff}
{14601}{}{You wonder how in such a big pile of things can be nothing of value at all.}
{14700}{}{a wall}
{14800}{}{a wall}
{14900}{}{a wall}
{15000}{}{a wall}
{15100}{}{a metal rod}
{15101}{}{A thick, rusty metal rod.}
{15200}{}{a metal rod}
{15201}{}{A broken metal rod. It takes a lot of strength to break one.}
{15300}{}{a metal rod}
{15301}{}{A thick rusty metal rod.}
{15400}{}{a metal rod}
{15401}{}{A broken metal rod. It takes a lot of strength to break one.}
{15500}{}{an old poster}
{15501}{}{On the poster, a pretty lab assistant warns you to close the cage.}
{15600}{}{a metal rod}
{15601}{}{A broken metal rod. It takes a lot of strength to break one.}
{15700}{}{a table}
{15701}{}{There's a dirty rag on the table.}
{15800}{}{the grass}
{15801}{}{Some dry grass.}
{15900}{}{a shrub}
{15901}{}{A usual desert shrub.}
{16000}{}{a shrub}
{16001}{}{A common desert shrub.}
{16100}{}{a shrub}
{16101}{}{A common desert shrub.}
{16200}{}{a boat}
{16201}{}{An old, half-broken rusty boat.}
{16300}{}{a pickup truck}
{16301}{}{It was once an excellent vehicle.}
{16400}{}{a motorcycle}
{16401}{}{You dream of riding this - but, unfortunately, this one is broken.}
{16500}{}{a motorcycle}
{16501}{}{You dream of riding this - but, unfortunately, this one is broken.}
{16600}{}{a bush}
{16601}{}{Some desert plant.}
{16700}{}{a bush}
{16701}{}{Some desert plant.}
{16800}{}{a bush}
{16801}{}{Some desert plant.}
{16900}{}{a motorcycle}
{16901}{}{You dream of riding this - but, unfortunately, this one is broken.}
{17000}{}{a flag}
{17001}{}{The old flag of the USA.}
{17100}{}{a jukebox}
{17101}{}{It doesn't seem to be able to produce sound anymore.}
{17200}{}{a "Rainbow Pharmaceuticals" sign}
{17201}{}{There used to be a pharmaceutical company with that name around here.}
{17300}{}{a firepit}
{17301}{}{The fire went out a long time ago.}
{17400}{}{a wall}
{17401}{}{A damaged wall.}
{17500}{}{a billboard}
{17501}{}{It is impossible to read what was written on it.}
{17600}{}{a floor}
{17700}{}{a floor}
{17800}{}{a lighting}
{17900}{}{a lighting}
{18000}{}{a couch}
{18001}{}{Or at least it once was a couch, now it's just junk.}
{18100}{}{a couch}
{18101}{}{The best years of this couch are clearly in the very distant past.}
{18200}{}{a guitar}
{18201}{}{A battered musical instrument. Looks too complicated for you.}
{18300}{}{a powerful battery}
{18301}{}{Surprisingly, there is still some charge left, and this thing can be repaired.}
{18400}{}{stuff}
{18401}{}{It looks like these boxes have already been searched by somebody before you.}
{18500}{}{stuff}
{18501}{}{It's amazing what useless junk people can cram into boxes and store.}
{18600}{}{a bed}
{18601}{}{The bed is in a terrible, disgusting state.}
{18700}{}{a bed}
{18701}{}{You don't think anyone in their right mind would want to lie on that bed.}
{18800}{}{a bed}
{18801}{}{You don't think anyone in their right mind would want to lie on that bed.}
{18900}{}{a bed}
{18901}{}{The best thing to do with this bed is to destroy it.}
{19000}{}{a bed}
{19001}{}{It looks like a comfy bed, but the sheets on it aren't.}
{19100}{}{a bed}
{19101}{}{These sheets should have been washed, and they should have been washed a dozen years ago.}
{19200}{}{a bed}
{19201}{}{A bed with a pile of dirty sheets.}
{19300}{}{a couch}
{19301}{}{Or at least it once was a couch, now it's just junk.}
{19400}{}{a floor}
{19500}{}{a wall}
{19600}{}{tiles}
{19601}{}{Some stone tiles on the floor.}
{19700}{}{a hatch}
{19701}{}{The stairs leading down the hole descend into darkness.}
{19800}{}{a curb}
{19801}{}{A destroyed part of the sidewalk.}
{19900}{}{a curb}
{19901}{}{A destroyed part of the sidewalk.}
{20000}{}{a motorcycle}
{20001}{}{A rusty motorcycle of the Sunset Jackals.}
{20100}{}{a sign}
{20101}{}{The sign on this post is pretty rust.}
{20200}{}{a sign}
{20201}{}{It's not very clear what it was pointing at.}
{20300}{}{a sign}
{20301}{}{The sign on this post is pretty rust.}
{20400}{}{a sign}
{20401}{}{The post is pretty rust.}
{20500}{}{a sign}
{20501}{}{The sign is pretty rust.}
{20600}{}{an old mattress}
{20601}{}{This mattress discourages any desire to take a nap on or even go near it.}
{20700}{}{an old mattress}
{20701}{}{Lying on it you might feed those charming critters living in it.}
{20800}{}{a bed}
{20801}{}{It stinks even from a distance.}
{20900}{}{a bed}
{20901}{}{Even if you were to sleep by yourself on this thing, you would not be sleeping alone.}
{21000}{}{a bed}
{21001}{}{This bed has seen better days (and probably nights, too.)}
{21100}{}{a bed}
{21101}{}{There are a couple of stains of dubious origin on this well-worn sleeping device.}
{21200}{}{a bed}
{21201}{}{This bed is neatly covered with a dirty blanket}
{21300}{}{a bed}
{21301}{}{This bed has seen a lot of use and wear. Something must have crawled between the mattresses and died, too.}
{21400}{}{a counter}
{21401}{}{Portions of food are given out here.}
{21500}{}{a counter}
{21501}{}{Portions of food are given out here.}
{21600}{}{a counter}
{21601}{}{Portions of food are given out here.}
{21700}{}{a counter}
{21701}{}{Portions of food are given out here.}
{21800}{}{a counter}
{21801}{}{Portions of food are given out here.}
{21900}{}{a kitchen}
{21901}{}{The food for the whole of Tartarus is prepared here.}
{22000}{}{a broken table}
{22001}{}{Something or someone broke through the table.}
{22100}{}{a chair}
{22101}{}{It looks comfortable.}
{22200}{}{tires}
{22201}{}{You have plenty of time to look at this garbage.}
{22300}{}{a wheel}
{22301}{}{Previously part of a car.}
{22400}{}{a tire}
{22401}{}{Essentially just useless junk.}
{22500}{}{a wheel}
{22501}{}{Previously part of a car.}
{22600}{}{a wheel}
{22601}{}{Previously part of a car.}
{22700}{}{a tire}
{22701}{}{This old tire is completely hardened out.}
{22800}{}{a driving wheel}
{22801}{}{It's hard to imagine that someone could use this stuff.}
{22900}{}{a chair}
{22901}{}{This chair has already served its time.}
{23000}{}{a chair}
{23001}{}{It looks quite suitable to sit on.}
{23100}{}{a chair}
{23101}{}{This chair is rotting right before your eyes.}
{23200}{}{a chair}
{23201}{}{It doesn't look too comfortable, but it's quite sturdy.}
{23300}{}{a chair}
{23301}{}{This chair doesn't even seem to be rusty.}
{23400}{}{a chair}
{23401}{}{This chair with armrests is still in good shape.}
{23500}{}{a chair}
{23501}{}{Well preserved and also still spinning.}
{23600}{}{a chair}
{23601}{}{This chair doesn't even seem to be rusty.}
{23700}{}{a chair}
{23701}{}{This chair is slightly askew.}
{23800}{}{a chair}
{23801}{}{An old wooden chair. Still looks quite sturdy.}
{23900}{}{a chair}
{23901}{}{An old wooden chair. Still looks quite sturdy.}
{24000}{}{a chair}
{24001}{}{An old wooden chair. Still looks quite sturdy.}
{24100}{}{a chair}
{24101}{}{An old wooden chair. Still looks quite sturdy.}
{24200}{}{a chair}
{24201}{}{An old wooden chair. Still looks quite sturdy.}
{24300}{}{a fire hydrant}
{24301}{}{There's definitely no water there anymore.}
{24400}{}{a lamp post}
{24401}{}{It's covered in rust, but still standing.}
{24500}{}{a lamp post}
{24501}{}{This lamp post will never work again.}
{24600}{}{a lamp post}
{24601}{}{This lamp post will never work again.}
{24700}{}{a lamp post}
{24701}{}{It's covered in rust, but still standing.}
{24800}{}{a crate}
{24801}{}{A metal crate. Label reads "Livos".}
{24900}{}{the subway sign}
{24901}{}{The entrance to the station must be here somewhere.}
{25000}{}{a cave wall}
{25100}{}{a sign}
{25101}{}{Something dangerous is stored here.}
{25200}{}{stuff}
{25201}{}{Just some useless junk.}
{25300}{}{a crate}
{25301}{}{A sturdy metal crate.}
{25400}{}{a crate}
{25401}{}{A metal crate. Label reads "Livos".}
{25500}{}{a junk}
{25501}{}{There's nothing useful there.}
{25600}{}{rocks}
{25601}{}{Some small rocks.}
{25700}{}{rocks}
{25701}{}{A couple of small stones.}
{25800}{}{a door}
{25801}{}{This door is in good condition.}
{25900}{}{a door}
{25901}{}{This door is in good condition.}
{26000}{}{a door}
{26001}{}{A beautifully decorated door in good condition.}
{26100}{}{a door}
{26101}{}{A beautifully decorated door in good condition.}
{26200}{}{a crate}
{26201}{}{A nice wooden crate with some junk in it.}
{26300}{}{a crate}
{26301}{}{A sturdy wooden crate.}
{26400}{}{a crate}
{26401}{}{The only thing that's valuable would be the crate itself, and even that is questionable.}
{26500}{}{a newspaper machine}
{26501}{}{The newspaper machine is empty.}
{26600}{}{a newspaper machine}
{26601}{}{The newspaper machine is empty.}
{26700}{}{a newspaper machine}
{26701}{}{The newspaper machine is empty.}
{26800}{}{a newspaper machine}
{26801}{}{The newspaper machine is empty.}
{26900}{}{a newspaper machine}
{26901}{}{The newspaper machine is empty.}
{27000}{}{a newspaper machine}
{27001}{}{The newspaper machine is empty. It looks like it once held adult magazines.}
{27100}{}{an old mattress}
{27101}{}{Not usable for its intended purpose anymore, it's just useless garbage now.}
{27200}{}{an old mattress}
{27201}{}{Maybe if you were wearing a fully hermetic sealed metal armor suit, you wouldn't catch something while lying on it.}
{27300}{}{a junk}
{27301}{}{A pile of rotten old wood. It's not worth carrying around.}
{27400}{}{a junk}
{27401}{}{A pile of rotten wood.}
{27500}{}{a junk}
{27501}{}{This junk is hardly useful.}
{27600}{}{a junk}
{27601}{}{This junk is hardly useful.}
{27700}{}{a junk}
{27701}{}{Some junk that you think might have been a bed mattress before it was destroyed by the environment.}
{27800}{}{rocks}
{27900}{}{rocks}
{28000}{}{rocks}
{28100}{}{a rubble}
{28101}{}{A small pile of stone rubble. Watch your step!}
{28200}{}{a box}
{28201}{}{A sturdy wooden box.}
{28300}{}{rocks}
{28301}{}{A pile of rocks.}
{28400}{}{a box}
{28401}{}{There's some junk inside.}
{28500}{}{rocks}
{28501}{}{A pile of rocks.}
{28600}{}{a stop sign}
{28601}{}{A red sign with the word STOP written in large block letters.}
{28700}{}{a stop sign}
{28701}{}{A red sign with the word STOP written in large block letters. The large bullet hole was added after manufacturing.}
{28800}{}{a box}
{28801}{}{A large empty box.}
{28900}{}{a boxes}
{28901}{}{Two wooden boxes with contents of unknown purpose.}
{29000}{}{a box}
{29001}{}{A patched box. Its contents long lost all value.}
{29100}{}{a street lamp}
{29101}{}{It looks like it's still working.}
{29200}{}{a street lamp}
{29201}{}{It looks like it's still working.}
{29300}{}{a street lamp}
{29301}{}{It looks like it's still working.}
{29400}{}{a street lamp}
{29401}{}{It looks like it's still working.}
{29500}{}{a street lamp}
{29501}{}{Or to be precise, what is left of it.}
{29600}{}{a street lamp}
{29601}{}{This lamp can unlikely be restored.}
{29700}{}{a street lamp}
{29701}{}{It looks like it's still working.}
{29800}{}{a box}
{29801}{}{A sturdy wooden box with some useless junk.}
{29900}{}{a box}
{29901}{}{A metal box.}
{30000}{}{a table}
{30001}{}{This table has clearly been smashed, it looks like it's about to fall apart.}
{30100}{}{a table}
{30101}{}{A wooden table, relatively well preserved.}
{30200}{}{a table}
{30201}{}{A wooden table. It is put down to rest.}
{30300}{}{a table}
{30301}{}{A wooden table with a plastic surface. It has been broken for a while.}
{30400}{}{a junk}
{30401}{}{Completely useless junk.}
{30500}{}{a table}
{30501}{}{An old broken table.}
{30600}{}{a table}
{30601}{}{It looks like it could fall apart any minute.}
{30700}{}{a dirt}
{30701}{}{a dirt}
{30800}{}{a dirt}
{30801}{}{a dirt}
{30900}{}{a toilet}
{30901}{}{Whoever used it last didn't flush it away!}
{31000}{}{a junk}
{31001}{}{Pieces of wood, boxes, and other debris.}
{31100}{}{a junk}
{31101}{}{Even if you look at it more closely, you will not find anything of value.}
{31200}{}{a junk}
{31201}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31300}{}{a junk}
{31301}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31400}{}{a junk}
{31401}{}{Something that has clearly served its purpose.}
{31500}{}{a junk}
{31501}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31600}{}{a tree}
{31601}{}{A dead but still strong tree. Every beaver's dream.}
{31700}{}{a tree}
{31701}{}{A dead tree. The hollow is empty.}
{31800}{}{a stump}
{31801}{}{It was once A tree}
{31900}{}{a rope}
{32000}{}{a barrier}
{32001}{}{A small portable fence.}
{32100}{}{a barrier}
{32101}{}{A small portable fence.}
{32200}{}{a wall}
{32300}{}{a truck}
{32301}{}{The wrecked remains of a diesel truck. This pile of metal will never go again.}
{32400}{}{a truck}
{32401}{}{This diesel truck can't be fixed.}
{32500}{}{a bath tub}
{32501}{}{On closer examination, you realize that you don't want to take a bath in this.}
{32600}{}{a bath tub}
{32601}{}{This bathtub is broken and cracked.}
{32700}{}{a urinal}
{32701}{}{Not the cleanest of its kind, you wouldn't want to use it.}
{32800}{}{a table}
{32801}{}{A table with a calculator. You wonder why they need two monitors here.}
{32900}{}{a urinal}
{32901}{}{Just a dirty urinal. Nothing special.}
{33000}{}{a table}
{33001}{}{An ordinary table, in good condition.}
{33100}{}{a platform}
{33101}{}{A system of mechanisms is located on the concrete platform.}
{33200}{}{a door}
{33201}{}{A cracked wooden door.}
{33300}{}{a door}
{33301}{}{A cracked wooden door.}
{33400}{}{a truck}
{33401}{}{It will definitely not move anymore.}
{33500}{}{a truck}
{33501}{}{It will definitely not move anymore.}
{33600}{}{a truck}
{33601}{}{It will definitely not move anymore.}
{33700}{}{a truck}
{33701}{}{It will definitely not move anymore.}
{33800}{}{a truck}
{33801}{}{It's just a pile of rusty metal now.}
{33900}{}{a truck}
{33901}{}{Its back is full of broken containers and crates. Their contents lost their value a long time ago.}
{34000}{}{a wall}
{34001}{}{a wall}
{34100}{}{a wall}
{34101}{}{a wall}
{34200}{}{a road sign}
{34201}{}{A funny little man is drawn on the sign.}
{34300}{}{a road sign}
{34301}{}{A funny little man is drawn on the sign.}
{34400}{}{a block hex auto inviso}
{34401}{}{If you can see this, blame the technical designer.}
{34500}{}{a floor}
{34600}{}{a shadow}
{34601}{}{The shadow of the New World Order sign.}
{34700}{}{a pipe}
{34701}{}{Part of the pipe.}
{34800}{}{a ladder}
{34801}{}{It leads up.}
{34900}{}{a ladder}
{34901}{}{It leads down.}
{35000}{}{a ladder}
{35001}{}{It leads up.}
{35100}{}{a ladder}
{35101}{}{It leads up.}
{35200}{}{a ladder}
{35201}{}{It leads up.}
{35300}{}{a ladder}
{35301}{}{It leads down.}
{35400}{}{a ladder}
{35401}{}{It leads down.}
{35500}{}{a ladder}
{35501}{}{It leads up.}
{35600}{}{an entrance}
{35601}{}{An entrance to the factory building.}
{35700}{}{a table}
{35701}{}{An old wooden table.}
{35800}{}{a table}
{35801}{}{An old wooden table.}
{35900}{}{a well}
{35901}{}{A shallow well}
{36000}{}{a wall}
{36001}{}{a wall}
{36100}{}{a curtain}
{36101}{}{The curtain looks as if it was made with primitive tools, but it is very strong.}
{36200}{}{a curtain}
{36201}{}{The curtain looks as if it was made with primitive tools, but it is very strong.}
{36300}{}{a graffiti}
{36301}{}{Jackals Rule!}
{36400}{}{a graffiti}
{36401}{}{Jackals Rule!}
{36500}{}{a graffiti}
{36501}{}{Jackals Rule!}
{36600}{}{the boards}
{36601}{}{The fence is made of boards like these.}
{36700}{}{the boards}
{36701}{}{The fence is made of boards like these.}
{36800}{}{a sign}
{36801}{}{It says something about a certain laboratory.}
{36900}{}{a cave wall}
{37000}{}{a dirt}
{37001}{}{a dirt}
{37100}{}{a dirt}
{37101}{}{a dirt}
{37200}{}{a pot}
{37201}{}{A finely crafted clay pot.}
{37300}{}{a rake}
{37301}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37400}{}{a rake}
{37401}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37500}{}{a rake}
{37501}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37600}{}{the boards}
{37601}{}{The fence is made of boards like these.}
{37700}{}{the boards}
{37701}{}{The fence is made of boards like these.}
{37800}{}{the boards}
{37801}{}{The fence is made of boards like these.}
{37900}{}{a basin}
{37901}{}{It's full of junk. You don't want to look into it.}
{38000}{}{a basin}
{38001}{}{There's sediment and dirt inside.}
{38100}{}{a bucket}
{38101}{}{There is some water at the bottom. What would you like to see in it?}
{38200}{}{a vase}
{38201}{}{A very pretty clay vase.}
{38300}{}{a well}
{38301}{}{A typical well found in the wasteland.}
{38400}{}{a box}
{38401}{}{An empty storage box.}
{38500}{}{a box}
{38501}{}{An empty storage box.}
{38600}{}{a box}
{38601}{}{Every time you look in a box and find it empty, you get a little upset.}
{38700}{}{a box}
{38701}{}{An empty storage box.}
{38800}{}{a box}
{38801}{}{Every time you look in a box and find it empty, you get a little upset.}
{38900}{}{a box}
{38901}{}{Just a confusing storage box full of trash.}
{39000}{}{a box}
{39001}{}{Every time you look in a box and find it empty, you get a little upset.}
{39100}{}{a box}
{39101}{}{An empty storage box.}
{39200}{}{a brace}
{39201}{}{This brace helps to support the defensive wall.}
{39300}{}{a metal plate}
{39301}{}{Useless stuff.}
{39400}{}{a metal plate}
{39401}{}{Useless stuff.}
{39500}{}{a brace}
{39501}{}{This brace helps to support the defensive wall.}
{39600}{}{a metal barrel}
{39601}{}{A rusty metal barrel. It is empty.}
{39700}{}{a metal barrel}
{39701}{}{This barrel is probably empty from the hollow sound.}
{39800}{}{metal barrels}
{39801}{}{These barrels are probably empty from their hollow sound.}
{39900}{}{metal barrels}
{39901}{}{These barrels are probably empty from their hollow sound.}
{40000}{}{a air vent}
{40001}{}{This air vent appears to be for an underground structure.}
{40100}{}{a box}
{40101}{}{Every time you look in a box and find it empty, you get a little upset.}
{40200}{}{a box}
{40201}{}{An empty storage box.}
{40300}{}{a box}
{40301}{}{An empty storage box.}
{40400}{}{a rat hole}
{40401}{}{Maybe there's something inside besides rats.}
{40500}{}{a sunbed}
{40501}{}{An old rotten sunbed.}
{40600}{}{a door}
{40601}{}{A dried wooden door}
{40700}{}{a interceptor}
{40701}{}{Judging by the turbocharger on the hood, it was a very powerful car. Alas, it is not going anywhere anymore.}
{40800}{}{wooden boards}
{40801}{}{Old rotten boards}
{40900}{}{a truck}
{40901}{}{Old broken military truck.}
{41000}{}{things}
{41001}{}{A pile of useless junk, covered with a piece of tarpaulin.}
{41100}{}{things}
{41101}{}{A pile of useless junk, covered with a piece of tarpaulin.}
{41200}{}{things}
{41201}{}{A pile of useless junk, covered with a piece of tarpaulin.}
{41300}{}{a guarding booth}
{41301}{}{Either it was refurbished into a latrine, or the most comfortable way to do guarding duties is while sitting on the toilet.}
{41400}{}{a table}
{41401}{}{It is equipped with some obscure tools.}
{41500}{}{a junk}
{41501}{}{Some metal stuff. You don't think you can use it.}
{41600}{}{a junk}
{41601}{}{Old tools. Looks like they are all broken.}
{41700}{}{a box}
{41701}{}{An empty storage box.}
{41800}{}{a box}
{41801}{}{An empty storage box.}
{41900}{}{a box}
{41901}{}{An empty storage box.}
{42000}{}{a box}
{42001}{}{An empty storage box.}
{42100}{}{an elevator door}
{42101}{}{This is an elevator door. To access the elevator, you need to open this door first.}
{42200}{}{wooden boards}
{42201}{}{Wooden boards and other garbage}
{42300}{}{the stones}
{42400}{}{the stones}
{42500}{}{the stones}
{42600}{}{a bed}
{42601}{}{A piece of furniture in terrible condition}
{42700}{}{a bed}
{42701}{}{A piece of furniture in terrible condition}
{42800}{}{a box}
{42801}{}{An empty storage box.}
{42900}{}{a box}
{42901}{}{An empty storage box.}
{43000}{}{a box}
{43001}{}{An empty storage box.}
{43100}{}{a box}
{43101}{}{An empty storage box.}
{43200}{}{a junk}
{43300}{}{a junk}
{43400}{}{a junk}
{43500}{}{the stones}
{43501}{}{You examine them very carefully, but they are still usual stones.}
{43600}{}{a guarding booth}
{43601}{}{Either it was refurbished into a latrine, or the most comfortable way to do guarding duties is while sitting on the toilet.}
{43700}{}{a door}
{43701}{}{A beautifully designed wooden door, reinforced with metal ornaments and braces that give a hypnotic impression.}
{43800}{}{a door}
{43801}{}{A beautifully designed wooden door, reinforced with metal ornaments and braces that give a hypnotic impression.}
{43900}{}{picked plants}
{43901}{}{A rotting pile of picked plants}
{44000}{}{picked plants}
{44001}{}{A rotting pile of picked plants}
{44100}{}{picked plants}
{44101}{}{A rotting pile of picked plants}
{44200}{}{picked plants}
{44201}{}{This pile doesn't smell good. It is quite stinky.}
{44300}{}{picked plants}
{44301}{}{This pile doesn't smell good. It is quite stinky.}
{44400}{}{a dillweed}
{44401}{}{This plant is obviously inedible.}
{44500}{}{a dillweed}
{44501}{}{You are not a plant expert, but it looks like this one is inedible.}
{44600}{}{a dillweed}
{44601}{}{This plant is obviously inedible.}
{44700}{}{a device}
{44701}{}{A complicated mechanism with an obscure purpose.}
{44800}{}{a door}
{44801}{}{A guarded door. Looks like it's heavily reinforced.}
{44900}{}{a nuclear warhead}
{45000}{}{a generator}
{45001}{}{A sophisticated device for generating electricity.}
{45100}{}{a fence}
{45101}{}{A wooden fence.}
{45200}{}{a fence}
{45201}{}{A wooden fence.}
{45300}{}{a fence}
{45301}{}{A wooden fence.}
{45400}{}{a fence}
{45401}{}{A wooden fence.}
{45500}{}{a fence}
{45501}{}{A wooden fence.}
{45600}{}{a fence}
{45601}{}{A wooden fence.}
{45700}{}{a fence}
{45701}{}{A wooden fence.}
{45800}{}{a fence}
{45801}{}{Those who built this fence obviously weren't perfectionists.}
{45900}{}{a fence}
{45901}{}{Those who built this fence obviously weren't perfectionists.}
{46000}{}{a fence}
{46001}{}{Those who built this fence obviously weren't perfectionists.}
{46100}{}{the sewer grid}
{46101}{}{It's unlikely that the sewer itself is still operating.}
{46200}{}{the bottles}
{46201}{}{Cracked bottles and broken dishes.}
{46300}{}{the bottles}
{46301}{}{Cracked bottles and broken dishes.}
{46400}{}{a junk}
{46401}{}{A useless pile of junk.}
{46500}{}{a slot machine}
{46501}{}{You don't really think that in two hundred years it still works, do you?}
{46600}{}{a slot machine}
{46601}{}{You don't really think that in two hundred years it still works, do you?}
{46700}{}{a junk}
{46701}{}{Some useless junk.}
{46800}{}{a junk}
{46801}{}{Some useless junk.}
{46900}{}{a poster}
{46901}{}{It is impossible to tell what's on it.}
{47000}{}{an elevator door}
{47100}{}{a box}
{47101}{}{An empty storage box.}
{47200}{}{a box}
{47201}{}{This box contains nothing interesting.}
{47300}{}{a box}
{47301}{}{This box contains nothing interesting.}
{47400}{}{a box}
{47401}{}{This box contains nothing interesting.}
{47500}{}{a box}
{47501}{}{This box contains nothing interesting.}
{47600}{}{a box}
{47601}{}{This box contains nothing interesting.}
{47700}{}{a box}
{47701}{}{This box contains nothing interesting.}
{47800}{}{a box}
{47801}{}{This box contains nothing interesting.}
{47900}{}{a box}
{47901}{}{This box contains nothing interesting.}
{48000}{}{a box}
{48001}{}{This box contains nothing interesting.}
{48100}{}{a door}
{48101}{}{A sturdy metal door.}
{48200}{}{a door}
{48201}{}{A sturdy metal door.}
{48300}{}{things}
{48301}{}{A huge pile of things, which, on a closer inspection, contains nothing of interest for you.}
{48400}{}{a weapons store}
{48401}{}{There's a whole bunch of weapons on the counter.}
{48500}{}{a propeller}
{48501}{}{It is spinning.}
{48600}{}{an altar}
{48700}{}{a monitor}
{48701}{}{This big monitor is covered with a layer of dust. It is definitely not working}
{48800}{}{a floor}
{48801}{}{a floor}
{48900}{}{a barrier}
{48901}{}{It surrounds the stairs from both sides.}
{49000}{}{a wall}
{49100}{}{a barrier}
{49101}{}{Some wooden boards nailed to a sheet of iron.}
{49200}{}{a barrier}
{49201}{}{Several metal sheets put on each other.}
{49300}{}{a table}
{49301}{}{Looks like this table is missing a leg.}
{49400}{}{a table}
{49401}{}{Looks like this table is missing a leg.}
{49500}{}{a table}
{49501}{}{Old dilapidated table}
{49600}{}{a table}
{49601}{}{Better not to put anything heavy on it.}
{49700}{}{a table}
{49701}{}{Looks like it can break at any moment.}
{49800}{}{a shadow}
{49900}{}{corn}
{49901}{}{A useful domestic plant.}
{50000}{}{corn}
{50001}{}{A very small bush.}
{50100}{}{corn}
{50101}{}{You like the corn soup very much.}
{50200}{}{corn}
{50201}{}{This bush has a long way to grow.}
{50300}{}{corn}
{50301}{}{This bush has a long way to grow.}
{50400}{}{corn}
{50401}{}{Looks like this cob is almost ripe.}
{50500}{}{a parking lot entrance}
{50501}{}{It's impossible to clear this rubble.}
{50600}{}{a parking lot entrance}
{50601}{}{It's impossible to clear this rubble.}
{50700}{}{a chair}
{50701}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{50800}{}{a chair}
{50801}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{50900}{}{a boulder}
{50901}{}{The collapsed part of the roof formed this slide of rock. Your rope leads back to the surface.}
{51000}{}{corn}
{51001}{}{This corn cob will soon be ready for consumption.}
{51100}{}{a wall}
{51200}{}{a hose}
{51201}{}{An Irreplaceable tool in the business of watering crops.}
{51300}{}{corn}
{51301}{}{This bush has a long way to grow.}
{51400}{}{a pole}
{51500}{}{a hose}
{51501}{}{An Irreplaceable tool in the business of watering crops.}
{51600}{}{a chair}
{51601}{}{Looks solid.}
{51700}{}{a chair}
{51701}{}{Looks solid.}
{51800}{}{a chair}
{51801}{}{Looks solid.}
{51900}{}{a chair}
{51901}{}{Looks solid.}
{52000}{}{a bed}
{52001}{}{It's better to sleep on the floor.}
{52100}{}{a shadow}
{52200}{}{a chair}
{52201}{}{Battered, but sturdy.}
{52300}{}{things}
{52301}{}{A lot of boxes full of useless junk.}
{52400}{}{a workbench}
{52401}{}{An old workbench, it seems to have been used a lot.}
{52500}{}{a shadow}
{52600}{}{a chair}
{52601}{}{Battered, but sturdy.}
{52700}{}{a car}
{52701}{}{You see a bucket of nuts and bolts. It was a great car once.}
{52800}{}{a car}
{52801}{}{You see a bucket of nuts and bolts. It was a great car once.}
{52900}{}{a box}
{52901}{}{An empty carton box.}
{53000}{}{a box}
{53001}{}{An empty carton box.}
{53100}{}{a box}
{53101}{}{An empty carton box.}
{53200}{}{a box}
{53201}{}{An empty carton box.}
{53300}{}{a land}
{53400}{}{a land}
{53500}{}{a land}
{53600}{}{a land}
{53700}{}{a punching bag}
{53701}{}{You wouldn't want to be in its place.}
{53800}{}{a box}
{53801}{}{Sometimes you can find something useful in boxes. Not this time.}
{53900}{}{a box}
{53901}{}{Sometimes you can find something useful in boxes. Not this time.}
{54000}{}{a box}
{54001}{}{Sometimes you can find something useful in boxes. Not this time.}
{54100}{}{a box}
{54101}{}{Sometimes you can find something useful in boxes. Not this time.}
{54200}{}{a barbell}
{54201}{}{A sports apparatus}
{54300}{}{a barbell}
{54301}{}{A sports apparatus}
{54400}{}{a junk}
{54401}{}{Looks like a part of the box.}
{54500}{}{a junk}
{54501}{}{This trash is useless.}
{54600}{}{a horizontal bar}
{54601}{}{It's securely fixed in the wall.}
{54700}{}{a horizontal bar}
{54701}{}{It's securely fixed in the wall.}
{54800}{}{a horizontal bar}
{54801}{}{You don't remember the last time you did pull-ups.}
{54900}{}{a junk}
{54901}{}{You see a half-decayed cardboard box.}
{55000}{}{a junk}
{55001}{}{You see a half-decayed cardboard box.}
{55100}{}{concrete slabs}
{55101}{}{Heavy slabs, embedded in the ground.}
{55200}{}{concrete slabs}
{55201}{}{Heavy slabs, embedded in the ground.}
{55300}{}{concrete slabs}
{55301}{}{Heavy slabs, embedded in the ground.}
{55400}{}{a shadow}
{55500}{}{a covered hole in the wall}
{55501}{}{Some boards and piles of junk are covering the hole.}
{55600}{}{a covered hole in the wall}
{55601}{}{Some boards and piles of junk are covering the hole.}
{55700}{}{a poster}
{55701}{}{An old "Happy Bull" poster.}
{55800}{}{a junk}
{55801}{}{Looks like a part of the box.}
{55900}{}{a fence}
{55901}{}{Once beautiful metallic fence.}
{56000}{}{a fence}
{56001}{}{Once beautiful metallic fence.}
{56100}{}{a fence}
{56101}{}{Once beautiful metallic fence.}
{56200}{}{a fence}
{56201}{}{Once beautiful metallic fence.}
{56300}{}{a fence}
{56301}{}{Once beautiful metallic fence.}
{56400}{}{a fence}
{56401}{}{Once beautiful metallic fence.}
{56500}{}{a fence}
{56501}{}{Once beautiful metallic fence.}
{56600}{}{a fence}
{56601}{}{Once beautiful metallic fence.}
{56700}{}{a beam}
{56701}{}{This is a pretty strong beam.}
{56800}{}{a door}
{56801}{}{Entrance to the factory building.}
{56900}{}{the shelves}
{56901}{}{Vast metal shelves}
{57000}{}{the shelves}
{57001}{}{Metal shelves. They look reliable and strong.}
{57100}{}{the shelves}
{57101}{}{Metal shelves. They look reliable and strong.}
{57200}{}{the shelves}
{57201}{}{Metallic shelves. Nothing to pick up here.}
{57300}{}{a bush}
{57301}{}{A desert plant. No interest to you.}
{57400}{}{a bush}
{57401}{}{A desert plant. No interest to you.}
{57500}{}{a bush}
{57501}{}{A desert plant. No interest to you.}
{57600}{}{a haystack}
{57601}{}{A result of Life Servant's work.}
{57700}{}{a shovel}
{57701}{}{The main tool to work with the soil.}
{57800}{}{a haystack}
{57801}{}{A result of Life Servant's work.}
{57900}{}{a device}
{57901}{}{Looks like this thing was turned into producing moonshine.}
{58000}{}{a haystack}
{58001}{}{A result of Life Servant's work.}
{58100}{}{a door}
{58101}{}{A reliable door made of steel bars.}
{58200}{}{a table}
{58201}{}{A table with obscure tools lying on it.}
{58300}{}{a ladder}
{58301}{}{This ladder leads into the darkness below.}
{58400}{}{a ladder}
{58401}{}{This ladder leads into the darkness below.}
{58500}{}{the chains}
{58501}{}{This ring has chains instead of ropes. Looks brutal.}
{58600}{}{the chains}
{58601}{}{This ring has chains instead of ropes. Looks brutal.}
{58700}{}{the chains}
{58701}{}{This ring has chains instead of ropes. Looks brutal.}
{58800}{}{the chains}
{58801}{}{This ring has chains instead of ropes. Looks brutal.}
{58900}{}{the chains}
{58901}{}{This ring has chains instead of ropes. Looks brutal.}
{59000}{}{a junk}
{59001}{}{Nothing of interest.}
{59100}{}{tires}
{59101}{}{This is a ring's foundation.}
{59200}{}{tires}
{59201}{}{This is a ring's foundation.}
{59300}{}{tires}
{59301}{}{This is a ring's foundation.}
{59400}{}{tires}
{59401}{}{This is a ring's foundation.}
{59500}{}{the chains}
{59501}{}{This ring has chains instead of ropes. Looks brutal.}
{59600}{}{a moonshine machine}
{59601}{}{Designed for producing booze.}
{59700}{}{a boiler pot}
{59701}{}{A boiler for producing the "Drop"}
{59800}{}{a wall}
{59900}{}{a wall}
{60000}{}{a wall}
{60100}{}{a junk}
{60101}{}{Parts of warehouse boxes.}
{60200}{}{a floor}
{60300}{}{the tables}
{60301}{}{A pile of old tables.}
{60400}{}{a table}
{60401}{}{A wonderful example of a wooden table.}
{60500}{}{a table}
{60501}{}{A wonderful example of a wooden table.}
{60600}{}{a a broken table}
{60601}{}{It's unlikely that someone would want to use this by its purpose.}
{60700}{}{a a broken table}
{60701}{}{It used to be a table.}
{60800}{}{a table}
{60801}{}{Sturdy and reliable, let alone a little rusty.}
{60900}{}{a table}
{60901}{}{A perfect table. Looks as good as new.}
{61000}{}{a table}
{61001}{}{Sturdy and reliable, let alone a little rusty.}
{61100}{}{a table}
{61101}{}{A wonderful example of a wooden table.}
{61200}{}{a fire}
{61201}{}{You can eternally stare at the fire.}
{61300}{}{a mirror}
{61301}{}{You look at yourself for some time.}
{61400}{}{a mirror}
{61401}{}{You look at yourself for some time.}
{61500}{}{a wall}
{61501}{}{An illuminated part of the wall.}
{61600}{}{a toilet}
{61601}{}{Very clean.}
{61700}{}{a fountain}
{61701}{}{A partially destroyed town fountain.}
{61800}{}{a toilet}
{61801}{}{If you were collecting toilets, it would be a beautiful addition to your collection.}
{61900}{}{a sink}
{61901}{}{A usual sink.}
{62000}{}{a fountain}
{62001}{}{A partially destroyed town fountain.}
{62100}{}{a bed}
{62101}{}{It is dirty and smelly.}
{62200}{}{a bed}
{62201}{}{An old rotten floor bed.}
{62300}{}{a wall}
{62400}{}{a wall}
{62500}{}{the chains}
{62501}{}{This ring has chains instead of ropes. Looks brutal.}
{62600}{}{the chains}
{62601}{}{This ring has chains instead of ropes. Looks brutal.}
{62700}{}{the lights}
{62701}{}{The surrounding area is illuminated by dim lights.}
{62800}{}{the lights}
{62801}{}{The surrounding area is illuminated by dim lights.}
{62900}{}{a wall}
{63000}{}{a wall}
{63100}{}{a wall}
{63200}{}{a terminal}
{63300}{}{a terminal}
{63400}{}{a wall}
{63500}{}{a wall}
{63600}{}{a wall}
{63700}{}{a seat}
{63701}{}{The living green plant as part of the seat decoration looks very surprising.}
{63800}{}{a seat}
{63801}{}{The living green plant as part of the seat decoration looks very surprising.}
{63900}{}{a bed}
{63901}{}{The suspicious stains discourage any desire to lie down on it.}
{64000}{}{a device}
{64001}{}{Some intricate thing with an unknown purpose.}
{64100}{}{a land}
{64200}{}{a land}
{64300}{}{a land}
{64400}{}{a land}
{64500}{}{a door}
{64501}{}{Slatted door. Well-suited for a prison cell.}
{64600}{}{an elevator control terminal}
{64601}{}{Doesn't respond. Maybe it needs power.}
{64700}{}{an elevator control terminal}
{64701}{}{Looks like this one is still working.}
{64800}{}{a bed}
{64801}{}{Old and smelly.}
{64900}{}{a bed}
{64901}{}{An old rotten floor bed.}
{65000}{}{a floor}
{65100}{}{a vent}
{65101}{}{High-tech air purification system.}
{65200}{}{a vent}
{65201}{}{High-tech air purification system.}
{65300}{}{a bed}
{65301}{}{Feeding the insects living on it is not part of your plan.}
{65400}{}{a music machine}
{65401}{}{It still works perfectly.}
{65500}{}{a music machine}
{65501}{}{The song selection is not particularly varied.}
{65600}{}{a bench}
{65601}{}{A comfortable bench.}
{65700}{}{a table}
{65701}{}{A part of a broken table.}
{65800}{}{a bed}
{65801}{}{And old floor bed, covered in mold and strange stains.}
{65900}{}{a table}
{65901}{}{A broken table. A part of it.}
{66000}{}{a table}
{66001}{}{A beautifully crafted table.}
{66100}{}{a broken table}
{66101}{}{Its leg is broken.}
{66200}{}{a chair}
{66201}{}{Looks like a usual reliable chair. Its legs are a little rusty though.}
{66300}{}{a chair}
{66301}{}{It's a chair. The usual one.}
{66400}{}{a chair}
{66401}{}{Its front leg is a little bent, but the chair still looks pretty solid.}
{66500}{}{a chair}
{66501}{}{A very comfortable piece of furniture.}
{66600}{}{a lying chair}
{66601}{}{Someone dropped this chair.}
{66700}{}{a lying chair}
{66701}{}{Looks like it's resting.}
{66800}{}{a lying chair}
{66801}{}{You are hardly going to use it.}
{66900}{}{a lying chair}
{66901}{}{Someone dropped this chair.}
{67000}{}{an armchair}
{67001}{}{Probably, you wouldn't like sitting on a chair without a seat.}
{67100}{}{an armchair}
{67101}{}{It's quite well-preserved.}
{67200}{}{an armchair}
{67201}{}{It can be probably fixed.}
{67300}{}{an armchair}
{67301}{}{Looks like there's a crack in the seat.}
{67400}{}{an armchair}
{67401}{}{You see the remains of a once convenient armchair.}
{67500}{}{an armchair}
{67501}{}{You wonder what became of the seat.}
{67600}{}{an armchair}
{67601}{}{If armchairs could have had skeletons, this is what they would look like.}
{67700}{}{a junk}
{67701}{}{Looks like it was a chair once.}
{67800}{}{a bed}
{67801}{}{Too dirty.}
{67900}{}{a locker}
{67901}{}{There is definitely nothing in there.}
{68000}{}{a bed}
{68001}{}{This bed is blackened from all the dirt.}
{68100}{}{a locker}
{68101}{}{A piece of furniture. You will hardly find anything interesting there.}
{68200}{}{an oven}
{68201}{}{Looks like it is in working condition.}
{68300}{}{an oven}
{68301}{}{This one works on wood.}
{68400}{}{an oven}
{68401}{}{You have no time to cook.}
{68500}{}{an oven}
{68501}{}{In working condition. Works on wood.}
{68600}{}{a shadow}
{68700}{}{the lights}
{68701}{}{Two lights hanging on wires.}
{68800}{}{the lights}
{68801}{}{Two lights hanging on wires.}
{68900}{}{a cave entrance}
{68901}{}{The caves are usually quite cold.}
{69000}{}{a pole}
{69001}{}{Part of the pole}
{69100}{}{a mountain}
{69101}{}{Its cliffs look unapproachable}
{69200}{}{a mountain}
{69201}{}{Its cliffs look unapproachable}
{69300}{}{a mountain}
{69301}{}{Its cliffs look unapproachable}
{69400}{}{a mountain}
{69401}{}{Its cliffs look unapproachable}
{69500}{}{a mountain}
{69501}{}{Its cliffs look unapproachable}
{69600}{}{a mountain}
{69601}{}{Its cliffs look unapproachable}
{69700}{}{the light}
{69701}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{69800}{}{the light}
{69801}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{69900}{}{the light}
{69901}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{70000}{}{the light}
{70001}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{70100}{}{the light}
{70101}{}{This light has seen some things.}
{70200}{}{the light}
{70201}{}{Everything that's left of the light.}
{70300}{}{a seat}
{70301}{}{The plant looks alive. Maybe someone is watering it?}
{70400}{}{a pipe}
{70401}{}{A damaged pipe.}
{70500}{}{a pipe}
{70501}{}{A damaged pipe.}
{70600}{}{a pipe}
{70601}{}{A damaged pipe.}
{70700}{}{a pipe}
{70701}{}{A damaged pipe.}
{70800}{}{a table}
{70801}{}{A quite good wooden table.}
{70900}{}{a table}
{70901}{}{A quite good wooden table.}
{71000}{}{a table}
{71001}{}{It's pretty dirty. Looks like there's mold on it.}
{71100}{}{the lights}
{71101}{}{It would be complete darkness without it.}
{71200}{}{a table}
{71201}{}{It's pretty dirty. Looks like there's mold on it.}
{71300}{}{a lying chair}
{71301}{}{Bar stool with no back.}
{71400}{}{the lights}
{71401}{}{It would be complete darkness without it.}
{71500}{}{a chair}
{71501}{}{Bar stool with no back.}
{71600}{}{a sign}
{71601}{}{Jackals rule!}
{71700}{}{a ladder}
{71701}{}{This ladder leads up.}
{71800}{}{a ladder}
{71801}{}{This ladder leads up.}
{71900}{}{a bench}
{71901}{}{A stone bench. For hard-asses.}
{72000}{}{a bench}
{72001}{}{You should put a lot of effort to break a stone bench.}
{72100}{}{a bench}
{72101}{}{A stone bench. Must be very firm.}
{72200}{}{a bench}
{72201}{}{A stone bench. For hard-asses.}
{72300}{}{a bench}
{72301}{}{A stone bench. For hard-asses.}
{72400}{}{things}
{72401}{}{Some boxes. Nothing interesting inside.}
{72500}{}{a wall debris}
{72501}{}{Rubble from a destroyed wall.}
{72600}{}{a bench}
{72601}{}{A slightly damaged stone bench.}
{72700}{}{a bench}
{72701}{}{A stone bench. Must be very firm.}
{72800}{}{a lying chair}
{72801}{}{Bar stool with no back.}
{72900}{}{a lying chair}
{72901}{}{Just a bar stool. Someone tipped this one over.}
{73000}{}{a table}
{73001}{}{An unusually dirty piece of furniture.}
{73100}{}{a sign}
{73101}{}{Jackals rule!}
{73200}{}{a chair}
{73201}{}{Bar stool with no back.}
{73300}{}{a sign}
{73301}{}{Jackals rule!}
{73400}{}{a chair}
{73401}{}{Bar stool with no back.}
{73500}{}{a chair}
{73501}{}{Bar stool with no back.}
{73600}{}{a chair}
{73601}{}{Just a chair with no back.}
{73700}{}{a broken chair}
{73701}{}{Looks like this pile of garbage was once a chair. Made from the garbage.}
{73800}{}{a chair}
{73801}{}{Looks like this pile of garbage was once a chair. Made from the garbage.}
{73900}{}{a chair}
{73901}{}{A handmade chair, assembled from trash and car parts.}
{74000}{}{a chair}
{74001}{}{You don't have any feelings for handmade furniture.}
{74100}{}{a chair}
{74101}{}{A handmade chair, made from all kinds of stuff.}
{74200}{}{a chair}
{74201}{}{Made from junk and car parts}
{74300}{}{manure}
{74301}{}{Better not to step on it.}
{74400}{}{manure}
{74401}{}{A product of someone's waste.}
{74500}{}{manure}
{74501}{}{A product of someone's waste.}
{74600}{}{manure}
{74601}{}{Better not to step on it.}
{74700}{}{manure}
{74701}{}{A little pile of extremely fragrant shit.}
{74800}{}{manure}
{74801}{}{A little pile of extremely fragrant shit.}
{74900}{}{a table}
{74901}{}{A table with a scratched surface.}
{75000}{}{a table}
{75001}{}{Not the cleanest, but pretty tough table.}
{75100}{}{a car}
{75101}{}{Now it's just a pile of useless rusted metal.}
{75200}{}{a car}
{75201}{}{This car served its purpose a very, very long time ago}
{75300}{}{a car}
{75301}{}{It is impossible to repair this hunk.}
{75400}{}{a car}
{75401}{}{This heap of metal will never ride the highways again.}
{75500}{}{a bed}
{75501}{}{Looks comfy, but those who sleep here are not very fond of cleanliness.}
{75600}{}{a bed}
{75601}{}{Looks convenient. Although the sheets could be washed a little.}
{75700}{}{a bed}
{75701}{}{A piece of furniture. It's intended for rest and sleep.}
{75800}{}{a bed}
{75801}{}{If you wrap yourself in sheets, you can try to spook people.}
{75900}{}{a bed}
{75901}{}{No time to lay down and rest.}
{76000}{}{a bed}
{76001}{}{A piece of furniture. It's intended for rest and sleep.}
{76100}{}{a utility}
{76101}{}{You see pipes, wires, some kind of machines and other stuff.}
{76200}{}{a utility}
{76201}{}{You see pipes, wires, some kind of machines and other stuff.}
{76300}{}{a utility}
{76301}{}{You see pipes, wires, some kind of machines and other stuff.}
{76400}{}{a utility}
{76401}{}{You see pipes, wires, some kind of machines and other stuff.}
{76500}{}{a utility}
{76501}{}{You see pipes, wires, some kind of machines and other stuff.}
{76600}{}{a utility}
{76601}{}{You see pipes, wires, some kind of machines and other stuff.}
{76700}{}{a floor}
{76800}{}{a bomb}
{76801}{}{It's a nuclear bomb. You feel terrified even standing near it.}
{76900}{}{a podium}
{76901}{}{This is the podium where the nuclear bomb currently rests.}
{77000}{}{a calculator console}
{77001}{}{This is a control calculator.}
{77100}{}{a junk}
{77101}{}{Shattered bottles, shards of glass. Nothing of value.}
{77200}{}{a lying chair}
{77201}{}{It can still be used for sitting.}
{77300}{}{a lying chair}
{77301}{}{It can still be used for sitting.}
{77400}{}{a lying chair}
{77401}{}{Why do you need it? Leave it alone.}
{77500}{}{a lying chair}
{77501}{}{Why do you need it? Leave it alone.}
{77600}{}{a lying chair}
{77601}{}{Why do you need it? Leave it alone.}
{77700}{}{a lying chair}
{77701}{}{Why do you need it? Leave it alone.}
{77800}{}{a lying chair}
{77801}{}{Someone dropped this chair.}
{77900}{}{a lying chair}
{77901}{}{Someone dropped this chair.}
{78000}{}{a lying chair}
{78001}{}{A chair, peacefully laying around.}
{78100}{}{a chair}
{78101}{}{Rusty leg, busted leather - this chair doesn't look comfy.}
{78200}{}{a chair}
{78201}{}{Rusty leg, busted leather - this chair doesn't look comfy.}
{78300}{}{a chair}
{78301}{}{It served its purpose.}
{78400}{}{equipment}
{78401}{}{Some kind of technical equipment.}
{78500}{}{equipment}
{78501}{}{Some kind of technical equipment.}
{78600}{}{equipment}
{78601}{}{Some kind of technical equipment in a rusted rack.}
{78700}{}{equipment}
{78701}{}{A rack containing some technical equipment.}
{78800}{}{equipment}
{78801}{}{Some technical equipment.}
{78900}{}{equipment}
{78901}{}{Some kind of technical equipment in a rusted rack.}
{79000}{}{equipment}
{79001}{}{Some kind of technical equipment with an unknown purpose.}
{79100}{}{equipment}
{79101}{}{This rack has been dented by something. It is unlikely that the equipment is able to work.}
{79200}{}{a window}
{79201}{}{Very dirty.}
{79300}{}{a window}
{79301}{}{You notice the remains of glass, miraculously preserved somehow.}
{79400}{}{a window}
{79401}{}{Very dirty.}
{79500}{}{a window}
{79501}{}{You notice the remains of glass, miraculously preserved somehow.}
{79600}{}{a table}
{79601}{}{It can be repaired - but you don't need to do it.}
{79700}{}{a table}
{79701}{}{A little dented, but still a good table.}
{79800}{}{a chair}
{79801}{}{Despite its rusty legs, it can still do its job.}
{79900}{}{a chair}
{79901}{}{Despite its rusty legs, it can still do its job.}
{80000}{}{a chair}
{80001}{}{A usual chair.}
{80100}{}{a chair}
{80101}{}{Despite its rusty legs, it can still do its job.}
{80200}{}{a chair}
{80201}{}{It was fixed by someone. They did all they could.}
{80300}{}{a chair}
{80301}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80400}{}{a chair}
{80401}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80500}{}{a chair}
{80501}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80600}{}{a chair}
{80601}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80700}{}{a chair}
{80701}{}{There's almost nothing left of this chair.}
{80800}{}{a lying chair}
{80801}{}{Just a usual chair. It must be tired. Don't disturb it.}
{80900}{}{a chair}
{80901}{}{Now it's just junk.}
{81000}{}{a chair}
{81001}{}{Just a chair, peacefully lying on the side.}
{81100}{}{a chair}
{81101}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{81200}{}{a chair}
{81201}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{81300}{}{a chair}
{81301}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{81400}{}{a calculator}
{81401}{}{A common calculator.}
{81500}{}{a calculator}
{81501}{}{A common calculator.}
{81600}{}{equipment}
{81601}{}{Some kind of technical machinery with a purpose unknown to you.}
{81700}{}{a calculator}
{81701}{}{Looks like it's turned off.}
{81800}{}{a calculator}
{81801}{}{A common calculator.}
{81900}{}{a calculator}
{81901}{}{Looks like it's turned off.}
{82000}{}{a calculator}
{82001}{}{A large and complex calculator with levers and buttons on it.}
{82100}{}{a calculator}
{82101}{}{A large and complex calculator with levers and buttons on it.}
{82200}{}{the tubes}
{82201}{}{A knot of interwoven tubes. Some kind of communications.}
{82300}{}{the tubes}
{82301}{}{A knot of interwoven tubes. Some kind of communications.}
{82400}{}{a table with reagents}
{82401}{}{It seems that the flasks contain some chemical compounds. You'd better not touch it.}
{82500}{}{a wall}
{82600}{}{a car door}
{82601}{}{More precisely, what is left of it.}
{82700}{}{a barrel}
{82701}{}{Just a metal barrel.}
{82800}{}{a barrel}
{82801}{}{A barrel with unknown content.}
{82900}{}{a chair}
{82901}{}{A great bar stool.}
{83000}{}{a lighting panel}
{83001}{}{Converts electrical energy to light. Yes, an old physics textbook, which you read as a child, sometimes reminds of itself.}
{83100}{}{a stove}
{83101}{}{A smashed floor panels.}
{83200}{}{a stove}
{83201}{}{A smashed floor panels.}
{83300}{}{a stove}
{83301}{}{A smashed floor panels.}
{83400}{}{a stove}
{83401}{}{A smashed floor panels.}
{83500}{}{a stove}
{83501}{}{A smashed floor panels.}
{83600}{}{a supporting structure}
{83601}{}{It's falling apart right when you look at it.}
{83700}{}{a slope}
{83701}{}{A steep slope down.}
{83800}{}{a slope}
{83801}{}{A steep slope down.}
{83900}{}{a slope}
{83901}{}{A steep slope down.}
{84000}{}{a slope}
{84001}{}{A steep slope down.}
{84100}{}{a slope}
{84101}{}{A steep slope down.}
{84200}{}{a slope}
{84201}{}{A steep slope down.}
{84300}{}{a slope}
{84301}{}{A steep slope down.}
{84400}{}{a slope}
{84401}{}{A steep slope down.}
{84500}{}{a slope}
{84501}{}{A bizarre natural formation}
{84600}{}{a slope}
{84601}{}{A bizarre natural formation}
{84700}{}{a slope}
{84701}{}{A bizarre natural formation}
{84800}{}{a door}
{84801}{}{A usual wooden door.}
{84900}{}{a door}
{84901}{}{A usual wooden door.}
{85000}{}{a door}
{85001}{}{The paint is almost completely peeled off, and the wood is covered with fungus.}
{85100}{}{a table}
{85101}{}{This rag appears to act as a tablecloth.}
{85200}{}{a slope}
{85201}{}{A bizarre natural formation}
{85300}{}{a barrel}
{85301}{}{Empty fuel storage tank.}
{85400}{}{a pipe}
{85401}{}{A section of pipe.}
{85500}{}{a slope}
{85501}{}{A steep slope down.}
{85600}{}{a watchtower}
{85601}{}{A watchtower made out of all kinds of junk, but fitted with weapons.}
{85700}{}{a wall}
{85800}{}{tools}
{85801}{}{Tools you don't need.}
{85900}{}{a wall}
{86000}{}{a mechanism}
{86001}{}{This mechanism is involved in the water cleaning process.}
{86100}{}{a mechanism}
{86101}{}{This mechanism is involved in the water cleaning process.}
{86200}{}{a mechanism}
{86201}{}{This mechanism is involved in the water cleaning process.}
{86300}{}{a pipe}
{86301}{}{A section of pipe.}
{86400}{}{a pipe}
{86401}{}{A section of pipe.}
{86500}{}{a wall}
{86600}{}{a wall}
{86700}{}{a wall}
{86800}{}{a wall}
{86900}{}{a barrier}
{86901}{}{The paint is almost peeled off this metal fence, but it's still in excellent condition.}
{87000}{}{a barrier}
{87001}{}{The paint is almost peeled off this metal fence, but it's still in excellent condition.}
{87100}{}{a barrier}
{87101}{}{The regular metal fence.}
{87200}{}{a barrier}
{87201}{}{Metal fence.}
{87300}{}{a barrier}
{87301}{}{The paint is almost peeled off this metal fence, but it's still in excellent condition.}
{87400}{}{a barrier}
{87401}{}{Stacked metal fence.}
{87500}{}{a barrier}
{87501}{}{Metal fence lying on the ground.}
{87600}{}{a barrier}
{87601}{}{A battered metal fence.}
{87700}{}{a barrier}
{87701}{}{A badly battered metal fence.}
{87800}{}{a tile}
{87801}{}{A smashed floor panels.}
{87900}{}{a tile}
{87901}{}{A smashed floor panels.}
{88000}{}{a junk}
{88001}{}{Nothing interesting at all.}
{88100}{}{a land}
{88101}{}{Seems to have board fragments, but it's hard to be more precise.}
{88200}{}{a junk}
{88201}{}{Looks like parts of boxes.}
{88300}{}{a junk}
{88301}{}{Nothing interesting at all.}
{88400}{}{a junk}
{88401}{}{Parts of warehouse boxes.}
{88500}{}{a junk}
{88501}{}{Nothing interesting at all.}
{88600}{}{a toilet}
{88601}{}{It is so dirty that you would rather do your thing outdoors.}
{88700}{}{a table}
{88701}{}{Empty dirty bottles, leftover food. There's obviously nothing for you here.}
{88800}{}{a metal sheet}
{88801}{}{Rusty on both sides.}
{88900}{}{a metal sheet}
{88901}{}{Rusty on both sides.}
{89000}{}{a junk}
{89001}{}{Some unnecessary trash.}
{89100}{}{a junk}
{89101}{}{Some unnecessary trash.}
{89200}{}{a junk}
{89201}{}{Looks like a part of the box.}
{89300}{}{a toilet}
{89301}{}{Looks like it hasn't been washed in a long time.}
{89400}{}{a bed}
{89401}{}{Old and not particularly clean floor bed.}
{89500}{}{a bed}
{89501}{}{Better to sleep on bricks than on this.}
{89600}{}{the machinery}
{89601}{}{Big machinery for processing a variety of materials.}
{89700}{}{the machinery}
{89701}{}{A large machine for processing hard materials.}
{89800}{}{a pillar with spotlights}
{89801}{}{A homemade light for illuminating the surroundings.}
{89900}{}{a pillar with spotlights}
{89901}{}{A homemade light for illuminating the surroundings.}
{90000}{}{a pillar with spotlights}
{90001}{}{A homemade light for illuminating the surroundings.}
{90100}{}{a bed}
{90101}{}{Someone probably sleeps on it.}
{90200}{}{a bed}
{90201}{}{If you lie down on it, you can probably pick up a couple of nasty diseases}
{90300}{}{a bed}
{90301}{}{You don't want to look at those weird spots.}
{90400}{}{a fuel filter}
{90401}{}{A device for filtering fuel.}
{90500}{}{a junk}
{90501}{}{the parts of boxes or crates}
{90600}{}{a power armor parts}
{90601}{}{These parts fit the Power Armor.}
{90700}{}{a junk}
{90701}{}{Non-interesting trash.}
{90800}{}{a junk}
{90801}{}{Non-interesting trash.}
{90900}{}{a fencing cone}
{90901}{}{This would make a very funny hat.}
{91000}{}{a fencing cone}
{91001}{}{This would make a very funny hat.}
{91100}{}{a fencing cone}
{91101}{}{If you put such cones on your head, arms and legs, you get a starfish. You've seen one of these in a book.}
{91200}{}{a fencing cone}
{91201}{}{If you put such cones on your head, arms and legs, you get a starfish. You've seen one of these in a book.}
{91300}{}{a fencing cone}
{91301}{}{They used to mark parking lots with such.}
{91400}{}{a fencing cone}
{91401}{}{You could carry something in it. Water, for example.}
{91500}{}{a fencing cone}
{91501}{}{Sitting on one of these must be extremely uncomfortable.}
{91600}{}{a fencing cone}
{91601}{}{They used to mark parking lots with such.}
{91700}{}{the box parts}
{91800}{}{the box parts}
{91900}{}{a junk}
{92000}{}{the box parts}
{92100}{}{the parts of boxes or crates}
{92200}{}{the box parts}
{92300}{}{things}
{92301}{}{For rummaging through other people's things you can get punched in your vital organs. That's why you shouldn't touch them.}
{92400}{}{things}
{92401}{}{It feels like the owner of these things has been shoveling trash into the boxes.}
{92500}{}{a utility}
{92501}{}{You see pipes, wires, some kind of machines and other stuff.}
{92600}{}{a utility}
{92601}{}{You see pipes, wires, some kind of machines and other stuff.}
{92700}{}{a utility}
{92701}{}{You see pipes, wires, some kind of machines and other stuff.}
{92800}{}{a utility}
{92801}{}{You see pipes, wires, some kind of machines and other stuff.}
{92900}{}{a utility}
{92901}{}{You see pipes, wires, some kind of machines and other stuff.}
{93000}{}{a utility}
{93001}{}{You see pipes, wires, some kind of machines and other stuff.}
{93100}{}{a shadow}
{93200}{}{a tank}
{93201}{}{An old tank in very "fun" colors.}
{93300}{}{a shadow}
{93301}{}{The shadow of the tank.}
{93400}{}{a chair and a table with an umbrella}
{93401}{}{Looks like you can rest comfortably on this tank.}
{93500}{}{a concrete block}
{93501}{}{The block looks impossible to lift.}
{93600}{}{the stones}
{93601}{}{A pile of rocks.}
{93700}{}{a wagon}
{93701}{}{A wagon, covered with a green tent.}
{93800}{}{a trading post}
{93801}{}{Looks like you can buy armor here.}
{93900}{}{a market stall}
{93901}{}{This is usually a kind of place to buy something. If you have money to pay for it, of course.}
{94000}{}{a market stall}
{94001}{}{There's a great selection of weapons.}
{94100}{}{a market stall}
{94101}{}{There's a great selection of weapons.}
{94200}{}{a market stall}
{94201}{}{There's a great selection of weapons.}
{94300}{}{the bottles}
{94301}{}{Don't get your hopes up, they are completely empty and broken.}
{94400}{}{a metal sheet}
{94401}{}{You could call it just plain junk.}
{94500}{}{a metal sheet}
{94501}{}{You could call it just plain junk.}
{94600}{}{a metal sheet}
{94601}{}{You could call it just plain junk.}
{94700}{}{a metal sheet}
{94701}{}{You could call it just plain junk.}
{94800}{}{a metal sheet}
{98601}{}{A lantern attached to a pole.}
{94900}{}{a metal sheet}
{94901}{}{You could call it just plain junk.}
{95000}{}{a hole}
{95001}{}{A suspicious hole in the wall.}
{95100}{}{wooden boards}
{95101}{}{A few rotten boards.}
{95200}{}{wooden boards}
{95201}{}{A few rotten boards.}
{95300}{}{wooden boards}
{95301}{}{A few rotten boards.}
{95400}{}{a door}
{95401}{}{A double-leaf door.}
{95500}{}{a door}
{95501}{}{An ordinary door.}
{95600}{}{a door}
{95601}{}{This wonderful invention of mankind can open and close.}
{95700}{}{a door}
{95701}{}{This wonderful invention of mankind can open and close.}
{95800}{}{a door}
{95801}{}{This wonderful invention of mankind can open and close.}
{95900}{}{a door}
{95901}{}{This wonderful invention of mankind can open and close.}
{96000}{}{a door}
{96001}{}{An ordinary door.}
{96100}{}{a door}
{96101}{}{A usual wooden door.}
{96200}{}{a barrier}
{96201}{}{Goes up and down.}
{96300}{}{a fire}
{96301}{}{You can eternally stare at the fire.}
{96400}{}{a bed}
{96401}{}{You'd give a lot to not lie down on it.}
{96500}{}{a supporting structure}
{96501}{}{It's falling apart right when you look at it.}
{96600}{}{a cave wall}
{96601}{}{It looks like there's something buried here. But you don't have time to do excavations.}
{96700}{}{a cave wall}
{96701}{}{It looks like there's something buried here. But you don't have time to do excavations.}
{96800}{}{a cave wall}
{96801}{}{Looks like rubble.}
{96900}{}{a wall}
{97000}{}{a wall}
{97100}{}{a wall}
{97200}{}{a wall}
{97201}{}{Crack in the wall.}
{97300}{}{a cave wall}
{97400}{}{a cave wall}
{97500}{}{barrels}
{97501}{}{Empty fuel storage tanks.}
{97600}{}{a tank}
{97601}{}{A tank for supplying water.}
{97700}{}{a ladder}
{97701}{}{A sturdy metal ladder.}
{97800}{}{a door}
{97900}{}{things}
{97901}{}{Surprisingly, there is nothing of value to you in this pile.}
{98000}{}{barrels}
{98001}{}{Empty fuel storage tanks.}
{98100}{}{a stinking corpse}
{98101}{}{The corpse of a black man. Not just a corpse - a feast for flies!}
{98200}{}{a door}
{98300}{}{a door}
{98400}{}{a door}
{98500}{}{the lights}
{98501}{}{A lantern attached to a pole.}
{98600}{}{the lights}
{98601}{}{A lantern attached to a pole.}
{98700}{}{the lights}
{98701}{}{A lantern attached to a pole.}
{98800}{}{the lights}
{98801}{}{A lantern attached to a pole.}
{98900}{}{a shadow}
{99000}{}{a shadow}
{99100}{}{a garbage faucet}
{99200}{}{a garbage faucet}
{99300}{}{a well}
{99400}{}{a well}
{99500}{}{an exterior structure}
{99600}{}{a bed}
{99601}{}{Stinky old bed.}
{99700}{}{a bed}
{99701}{}{This floor bed is completely rotten.}
{99800}{}{a bed}
{99801}{}{A normal floor bed. People usually sleep on it.}
{99900}{}{a bed}
{99901}{}{You don't like these suspicious stains.}
{100000}{}{a moonshine machine}
{100001}{}{It looks like a wood-fired moonshine machine.}
{100100}{}{a bed}
{100101}{}{An old rotten floor bed.}
{100200}{}{a bed}
{100201}{}{An old rotten floor bed.}
{100300}{}{a bed}
{100301}{}{It's a stinky floor bed. It doesn't give you a desire to relax.}
{100400}{}{a bed}
{100401}{}{Looks like there's someone's blood on it.}
{100500}{}{a bed}
{100501}{}{Better to sleep on bricks than on this.}
{100600}{}{a bed}
{100601}{}{An old rotten floor bed.}
{100700}{}{a pumping device for the power plant}
{100701}{}{It's a cooling pump.}
{100800}{}{a piece of the lavash}
{100900}{}{a car}
{101000}{}{a chrysler}
{101001}{}{This Highwayman seems to be in very good shape for his age.}
{101100}{}{a car}
{101200}{}{a cemetery}
{101201}{}{The grave is located here.}
{101300}{}{a gravestone}
{101301}{}{An old headstone with a barely distinguishable inscription.}
{101400}{}{a gravestone}
{101401}{}{You will hardly be honored with one of these. Though you won't care anymore.}
{101500}{}{a gravestone}
{101501}{}{You will hardly be honored with one of these. Though you won't care anymore.}
{101600}{}{a gravestone}
{101601}{}{An old headstone with a barely distinguishable inscription.}
{101700}{}{a sign}
{101701}{}{New World Order.}
{101800}{}{a sign}
{101801}{}{New World Order.}
{101900}{}{the screen}
{101901}{}{You'd love to watch something on it, but you don't know, how.}
{102000}{}{the screen}
{102001}{}{You'd love to watch something on it, but you don't know, how.}
{102100}{}{the bottles of moonshine}
{102101}{}{Seems that their contents are valued here. But you can't carry them with you anyway.}
{102200}{}{a large water tank}
{102201}{}{A lightly rusted water storage tank.}
{102300}{}{the pipes}
{102301}{}{Slightly rusted pipes.}
{102400}{}{the pipes}
{102401}{}{Slightly rusted pipes.}
{102500}{}{the pipes}
{102501}{}{Slightly rusted pipes.}
{102600}{}{the pipes}
{102601}{}{Slightly rusted pipes.}
{102700}{}{the pipes}
{102701}{}{Slightly rusted pipes.}
{102800}{}{the pipes}
{102801}{}{Slightly rusted pipes.}
{102900}{}{the border}
{102901}{}{Separates the curb from the road.}
{103000}{}{the border}
{103001}{}{Separates the curb from the road.}
{103100}{}{the border}
{103101}{}{Separates the curb from the road.}
{103200}{}{the border}
{103201}{}{Separates the curb from the road.}
{103300}{}{the border}
{103301}{}{It used to be a border.}
{103400}{}{the border}
{103401}{}{It used to be a border - now it's just debris.}
{103500}{}{the border}
{103501}{}{It used to be a border - now it's just debris.}
{103600}{}{the border}
{103601}{}{It used to be a border - now it's just debris.}
{103700}{}{the border}
{103701}{}{It used to be a border - now it's just debris.}
{103800}{}{the border}
{103801}{}{It used to be a border - now it's just debris.}
{103900}{}{the border}
{103901}{}{Separates the curb from the road.}
{104000}{}{the border}
{104001}{}{It used to be a border - now it's just debris.}
{104100}{}{the border}
{104101}{}{Separates the curb from the road.}
{104200}{}{the border}
{104201}{}{It used to be a border - now it's just debris.}
{104300}{}{the border}
{104301}{}{It used to be a border - now it's just debris.}
{104400}{}{things}
{104401}{}{Miscellaneous junk. Nothing of value to you there.}
{104500}{}{things}
{104501}{}{Miscellaneous junk. Nothing of interest there.}
{104600}{}{things}
{104601}{}{Miscellaneous junk. Nothing of interest there.}
{104700}{}{things}
{104701}{}{Miscellaneous junk. Nothing of interest there.}
{104800}{}{things}
{104801}{}{Miscellaneous junk. Nothing of interest there.}
{104900}{}{things}
{104901}{}{Miscellaneous junk. Nothing of value to you there.}
{105000}{}{things}
{105001}{}{Miscellaneous junk. Nothing of value to you there.}
{105100}{}{things}
{105101}{}{Miscellaneous junk. Nothing of value to you there.}
{105200}{}{things}
{105201}{}{Miscellaneous junk. Nothing of value to you there.}
{105300}{}{things}
{105301}{}{Miscellaneous junk. Nothing of value to you there.}
{105400}{}{the wreckage ofa car}
{105401}{}{The front part of an old wrecked car.}
{105500}{}{things}
{105501}{}{Miscellaneous junk. Nothing of value to you there.}
{105600}{}{a junk}
{105601}{}{Looks like it used to be a car.}
{105700}{}{things}
{105701}{}{Miscellaneous junk. Nothing of value to you there.}
{105800}{}{things}
{105801}{}{Miscellaneous junk. Nothing of value to you there.}
{105900}{}{things}
{105901}{}{Miscellaneous junk. Nothing of value to you there.}
{106000}{}{things}
{106001}{}{Miscellaneous junk. Nothing of value to you there.}
{106100}{}{things}
{106101}{}{Miscellaneous junk. Nothing of value to you there.}
{106200}{}{a window}
{106201}{}{The glass is unbreakable. Don't even try.}
{106300}{}{a window}
{106301}{}{The glass is unbreakable. Don't even try.}
{106400}{}{a device}
{106401}{}{Unit attached to the tank.}
{106500}{}{a device}
{106501}{}{Unit attached to the tank.}
{106600}{}{a poster}
{106601}{}{A tattered wall poster.}
{106700}{}{a poster}
{106701}{}{A tattered wall poster.}
{106800}{}{a crate}
{106801}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{106900}{}{a crate}
{106901}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{107000}{}{a crate}
{107001}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{107100}{}{a crate}
{107101}{}{This box is definitely empty.}
{107200}{}{a crate}
{107201}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{107300}{}{a crate}
{107301}{}{It's a small but roomy box.}
{107400}{}{a crate}
{107401}{}{This box is definitely empty.}
{107500}{}{a crate}
{107501}{}{It's a small but roomy box.}
{107600}{}{a crate}
{107601}{}{It's a small but roomy box.}
{107700}{}{a crate}
{107701}{}{This box is definitely empty.}
{107800}{}{a crate}
{107801}{}{It's a small but roomy box.}
{107900}{}{a crate}
{107901}{}{It's a small but roomy box.}
{108000}{}{a crate}
{108001}{}{It's a small but roomy box.}
{108100}{}{a crate}
{108101}{}{For some reason, you can't help but think of cats when looking at these crates.}
{108200}{}{a crate}
{108201}{}{It's a small but roomy box.}
{108300}{}{a crate}
{108301}{}{It's a small but roomy box.}
{108400}{}{a crate}
{108401}{}{It's a small but roomy box.}
{108500}{}{a crate}
{108501}{}{It's a small but roomy box.}
{108600}{}{a crate}
{108601}{}{It's a small but roomy box.}
{108700}{}{a crate}
{108701}{}{For some reason, you can't help but think of cats when looking at these crates.}
{108800}{}{a crate}
{108801}{}{It's a small but roomy box.}
{108900}{}{a crate}
{108901}{}{It's a small but roomy box.}
{109000}{}{a crate}
{109001}{}{It's a small but roomy box.}
{109100}{}{the pipes}
{109101}{}{A section of massive pipe.}
{109200}{}{the pipes}
{109201}{}{A section of massive pipe.}
{109300}{}{the pipes}
{109301}{}{A section of massive pipe.}
{109400}{}{a crate}
{109401}{}{It's a small but roomy box.}
{109500}{}{a crate}
{109501}{}{It's a small but roomy box.}
{109600}{}{a crate}
{109601}{}{It's a small but roomy box.}
{109700}{}{a crate}
{109701}{}{It's a small but roomy box.}
{109800}{}{a crate}
{109801}{}{It's a small but roomy box.}
{109900}{}{a crate}
{109901}{}{For some reason, you can't help but think of cats when looking at these crates.}
{110000}{}{a crate}
{110001}{}{It's a small but roomy box.}
{110100}{}{a crate}
{110101}{}{It's a small but roomy box.}
{110200}{}{the burning barrel}
{110201}{}{This barrel is where the trash burns.}
{110300}{}{the pipes}
{110301}{}{A section of massive pipe.}
{110400}{}{a water tank}
{110401}{}{Apparently, it has a water supply in it.}
{110500}{}{the pipes}
{110501}{}{A section of massive pipe.}
{110600}{}{the pipes}
{110601}{}{A section of massive pipe.}
{110700}{}{the pipes}
{110701}{}{A section of massive pipe.}
{110800}{}{the pipes}
{110801}{}{A section of massive pipe.}
{110900}{}{a water tank}
{110901}{}{Apparently, it has a water supply in it.}
{111000}{}{a junk}
{111001}{}{A tattered box.}
{111100}{}{a barrel}
{111101}{}{Just a metal barrel.}
{111200}{}{a barrel}
{111201}{}{Just a metal barrel.}
{111300}{}{a barrel}
{111301}{}{Just a metal barrel.}
{111400}{}{a concrete block}
{111401}{}{It looks very heavy.}
{111500}{}{a tank}
{111501}{}{A container where water supplies are usually kept.}
{111600}{}{a tank}
{111601}{}{A container where water supplies are usually kept.}
{111700}{}{barrels}
{111701}{}{Empty metal barrels.}
{111800}{}{a pumping unit}
{111801}{}{A sophisticated, massive pump. It pumps out and filters water from deep underground.}
{111900}{}{a barrel}
{111901}{}{Empty metal barrel.}
{112000}{}{a concrete block}
{112001}{}{It looks very heavy.}
{112100}{}{barrels}
{112101}{}{Empty metal barrels.}
{112200}{}{a barrier}
{112201}{}{Emergency fence.}
{112300}{}{a barrier}
{112301}{}{Emergency fence.}
{112400}{}{a concrete block}
{112401}{}{It looks very heavy.}
{112500}{}{a concrete block}
{112501}{}{It looks very heavy.}
{112600}{}{a crate}
{112601}{}{Huge wooden box.}
{112700}{}{a concrete block}
{112701}{}{It looks very heavy.}
{112800}{}{a shadow}
{112900}{}{a crate}
{112901}{}{Huge wooden box.}
{113000}{}{a board}
{113001}{}{It holds no interest to you.}
{113100}{}{a board}
{113101}{}{It holds no interest to you.}
{113200}{}{a barrel}
{113201}{}{Empty metal barrel.}
{113300}{}{a barrel}
{113301}{}{Empty metal barrel.}
{113400}{}{the sandbags}
{113401}{}{Military fortification.}
{113500}{}{the sandbags}
{113501}{}{Military fortification.}
{113600}{}{the sandbags}
{113601}{}{Military fortification.}
{113700}{}{the sandbags}
{113701}{}{Military fortification.}
{113800}{}{the sandbags}
{113801}{}{Military fortification.}
{113900}{}{a shadow}
{114000}{}{the sandbags}
{114001}{}{Military fortification.}
{114100}{}{the sandbags}
{114101}{}{Military fortification.}
{114200}{}{the sandbags}
{114201}{}{Military fortification.}
{114300}{}{the sandbags}
{114301}{}{Military fortification.}
{114400}{}{the sandbags}
{114401}{}{Military fortification.}
{114500}{}{the sandbags}
{114501}{}{Military fortification.}
{114600}{}{the sandbags}
{114601}{}{Military fortification.}
{114700}{}{the sandbags}
{114701}{}{Military fortification.}
{114800}{}{the sandbags}
{114801}{}{Military fortification.}
{114900}{}{the sandbags}
{114901}{}{Military fortification.}
{115000}{}{a junk}
{115001}{}{A cardboard box.}
{115100}{}{a junk}
{115101}{}{Crumpled cardboard box and other useless junk.}
{115200}{}{a mining wagon}
{115300}{}{a mining wagon with a steel pillar}
{115400}{}{a mining wagon with dynamite}
{115500}{}{the sandbags}
{115501}{}{Military fortification.}
{115600}{}{a crate}
{115601}{}{Huge wooden box.}
{115700}{}{a crate}
{115701}{}{Huge wooden box.}
{115800}{}{a junk}
{115900}{}{a wall}
{116000}{}{a wall}
{116100}{}{a retinal scanner}
{116101}{}{This is a security device that scans a person's retina.}
{116200}{}{a crate}
{116201}{}{It is a small but roomy box in a bright color.}
{116300}{}{a crate}
{116301}{}{It's a small but roomy box.}
{116400}{}{a crate}
{116401}{}{It's a small but roomy box.}
{116500}{}{a crate}
{116501}{}{It's a small but roomy box.}
{116600}{}{a crate}
{116601}{}{The box is definitely empty.}
{116700}{}{a shadow}
{116701}{}{Nothing unusual.}
{116800}{}{a junk}
{116801}{}{Some kind of trash.}
{116900}{}{a door}
{117000}{}{a door}
{117100}{}{a junk}
{117101}{}{Part of a broken crate.}
{117200}{}{a junk}
{117201}{}{A useless pile of junk.}
{117300}{}{a junk}
{117301}{}{A useless pile of junk.}
{117400}{}{a junk}
{117401}{}{A useless pile of junk.}
{117500}{}{a junk}
{117501}{}{A useless pile of junk.}
{117600}{}{a conveyor}
{117601}{}{Part of a factory conveyor.}
{117700}{}{a conveyor}
{117701}{}{Part of a factory conveyor.}
{117800}{}{a conveyor shield}
{117801}{}{A means of holding a conveyor belt.}
{117900}{}{a conveyor shield}
{117901}{}{A means of holding a conveyor belt.}
{118000}{}{a conveyor shield}
{118001}{}{A means of holding a conveyor belt.}
{118100}{}{a conveyor shield}
{118101}{}{A means of holding a conveyor belt.}
{118200}{}{a conveyor shield}
{118201}{}{A means of holding a conveyor belt.}
{118300}{}{a conveyor shield}
{118301}{}{A means of holding a conveyor belt.}
{118400}{}{a conveyor}
{118401}{}{Part of a factory conveyor.}
{118500}{}{a conveyor}
{118501}{}{Part of a factory conveyor.}
{118600}{}{a conveyor}
{118601}{}{Part of a factory conveyor.}
{118700}{}{a conveyor}
{118701}{}{Part of a factory conveyor.}
{118800}{}{the steam}
{118900}{}{the lights}
{118901}{}{An illuminating device.}
{119000}{}{the lights}
{119001}{}{An illuminating device.}
{119100}{}{the lights}
{119101}{}{An illuminating device.}
{119200}{}{the lights}
{119201}{}{An illuminating device.}
{119300}{}{the lights}
{119301}{}{An illuminating device.}
{119400}{}{the lights}
{119401}{}{An illuminating device.}
{119500}{}{the lights}
{119501}{}{An illuminating device.}
{119600}{}{the lights}
{119601}{}{An illuminating device.}
{119700}{}{a wire}
{119701}{}{Barbed wire.}
{119800}{}{a wire}
{119801}{}{Barbed wire.}
{119900}{}{a wire}
{119901}{}{Barbed wire. Dangerous thing.}
{120000}{}{a wire}
{120001}{}{Barbed wire.}
{120100}{}{a cave wall}
{120200}{}{a cave wall}
{120300}{}{a cave wall}
{120400}{}{a cave wall}
{120500}{}{a cave wall}
{120600}{}{a cave wall}
{120700}{}{a cave wall}
{120800}{}{a cave wall}
{120900}{}{a cave wall}
{121000}{}{a cave wall}
{121100}{}{a cave wall}
{121200}{}{a cave wall}
{121300}{}{a cave wall}
{121400}{}{a cave wall}
{121500}{}{a cave wall}
{121600}{}{a bunk}
{121601}{}{This thing is used for resting.}
{121700}{}{a bunk}
{121701}{}{This thing is used for resting.}
{121800}{}{a bunk}
{121801}{}{This thing is used for resting.}
{121900}{}{a bunk}
{121901}{}{A tiered bunk. You dreamed of one as a child.}
{122000}{}{a bunk}
{122001}{}{A tiered bunk. You dreamed of one as a child.}
{122100}{}{a bunk}
{122101}{}{This thing is used for resting.}
{122200}{}{a bunk}
{122201}{}{No time to sleep!}
{122300}{}{a bunk}
{122301}{}{This thing is used for resting.}
{122400}{}{a bunk}
{122401}{}{Looks clean enough.}
{122500}{}{a bunk}
{122501}{}{This thing is used for resting.}
{122600}{}{a bunk}
{122601}{}{This thing is used for resting.}
{122700}{}{a wire}
{122701}{}{Barbed wire. Dangerous thing.}
{122800}{}{a "Wanted!" sign}
{122801}{}{The portrait of the wanted man looks just like you!}
{122900}{}{a floor}
{123000}{}{a wire}
{123001}{}{Barbed wire.}
{123100}{}{a... what is this?}
{123101}{}{This strange cannon seems to have been left from before the war. Interesting, how it ended up here.}
{123200}{}{a vent}
{123201}{}{Part of the ventilation system.}
{123300}{}{a fence}
{123301}{}{Hole in the fence.}
{123400}{}{a fence}
{123401}{}{The hole in the fence. These stains look like blood.}
{123500}{}{a vent}
{123501}{}{Part of the ventilation system.}
{123600}{}{an energy switch}
{123700}{}{a cross}
{123701}{}{A gravestone cross made from improvised materials.}
{123800}{}{a cross}
{123801}{}{The inscription on the plaque has become completely illegible.}
{123900}{}{a cross}
{123901}{}{The small tomb cross seems to have been made from old pipes.}
{124000}{}{a cross}
{124001}{}{The deceased must have worn this hat during his lifetime.}
{124100}{}{a cross}
{124101}{}{A tribute to an unknown deceased.}
{124200}{}{a cross}
{124201}{}{Everyone dies sometimes.}
{124300}{}{a broken tile}
{124400}{}{a metal sheet}
{124401}{}{A heavy, rusty piece of iron, not worth picking up.}
{124500}{}{a metal sheet}
{124501}{}{A heavy, rusty piece of iron, not worth picking up.}
{124600}{}{a tank}
{124601}{}{A container where water supplies are usually kept.}
{124700}{}{a floor}
{124800}{}{a floor}
{124900}{}{a floor}
{125000}{}{a floor}
{125100}{}{a floor}
{125200}{}{a floor}
{125300}{}{a floor}
{125400}{}{a junk}
{125401}{}{A pile of junk.}
{125500}{}{a junk}
{125501}{}{Boxes empty, tin cans all rusted over, nothing of value here.}
{125600}{}{a metal sheet}
{125601}{}{Rusty on both sides.}
{125700}{}{a metal sheet}
{125701}{}{Let it lie where it is - it's completely useless.}
{125800}{}{a table}
{125801}{}{Station attendant's desk.}
{125900}{}{a wall}
{126000}{}{a wall}
{126100}{}{a huge ladder leading up}
{126200}{}{a junk}
{126201}{}{Parts of some machines, that have obviously lost their value.}
{126300}{}{a junk}
{126301}{}{A pile of unnecessary trash.}
{126400}{}{a utility}
{126401}{}{There are pipes, cables, other equipment.}
{126500}{}{a utility}
{126501}{}{There are pipes, cables, other equipment.}
{126600}{}{a junk}
{126601}{}{Glass, iron, something else.}
{126700}{}{a bed}
{126701}{}{You will try your best to avoid resting on this stinking bed.}
{126800}{}{a bed}
{126801}{}{You will try your best to avoid resting on this stinking bed.}
{126900}{}{wooden boards}
{126901}{}{A board broke out of a nearby structure.}
{127000}{}{wooden boards}
{127001}{}{A board broke out of a nearby structure.}
{127100}{}{wooden boards}
{127101}{}{A board broke out of a nearby structure.}
{127200}{}{wooden boards}
{127201}{}{A board broke out of a nearby structure.}
{127300}{}{a pile of stones}
{127301}{}{Several large cobblestones in one place.}
{127400}{}{a wall}
{127500}{}{a tent}
{127501}{}{A tent made of sturdy materials, with reinforced wind protection.}
{127600}{}{a tent}
{127601}{}{You can see the stars through the hole in the roof.}
{127700}{}{wooden boards}
{127701}{}{A board broke out of a nearby structure.}
{127800}{}{wooden boards}
{127801}{}{A board broke out of a nearby structure.}
{127900}{}{wooden boards}
{127901}{}{A board broke out of a nearby structure.}
{128000}{}{wooden boards}
{128001}{}{A board broke out of a nearby structure.}
{128100}{}{wooden boards}
{128101}{}{A board broke out of a nearby structure.}
{128200}{}{wooden boards}
{128201}{}{A board broke out of a nearby structure.}
{128300}{}{wooden boards}
{128301}{}{A board broke out of a nearby structure.}
{128400}{}{a blocked exit to the top}
{128401}{}{This rubble is impossible to clear.}
{128500}{}{the machines}
{128501}{}{A wall of two cars.}
{128600}{}{a table}
{128601}{}{An interesting design solution - a table made of the car hood.}
{128700}{}{a table}
{128701}{}{A table made of the hood of a car.}
{128800}{}{a car}
{128801}{}{This baby won't be riding the highway anymore.}
{128900}{}{a car}
{128901}{}{This car is long gone.}
{129000}{}{the machines}
{129001}{}{A wall of two cars.}
{129100}{}{a car}
{129101}{}{An old, dilapidated car.}
{129200}{}{a car}
{129201}{}{It is unlikely to move anywhere at all now.}
{129300}{}{an elevator cabin}
{129400}{}{a beam}
{129401}{}{Supporting structure.}
{129500}{}{a beam}
{129501}{}{Supporting structure.}
{129600}{}{a beam}
{129601}{}{Supporting structure.}
{129700}{}{a rope}
{129800}{}{the way down}
{129900}{}{a floor}
{130000}{}{wooden boards}
{130001}{}{A board broke out of a nearby structure.}
{130100}{}{wooden boards}
{130101}{}{A board broke out of a nearby structure.}
{130200}{}{wooden boards}
{130201}{}{A board broke out of a nearby structure.}
{130300}{}{wooden boards}
{130301}{}{A board broke out of a nearby structure.}
{130400}{}{a floor}
{130500}{}{a car}
{130501}{}{All that's left of it is a useless pile of rusty metal.}
{130600}{}{a beam}
{130601}{}{Supporting structure.}
{130700}{}{a beam}
{130701}{}{Supporting structure.}
{130800}{}{a beam}
{130801}{}{Supporting structure.}
{130900}{}{a beam}
{130901}{}{Supporting structure.}
{131000}{}{a beam}
{131001}{}{Support structure. You wonder if a grown man can be hung on it.}
{131100}{}{a beam}
{131101}{}{Supporting structure.}
{131200}{}{a floor}
{131300}{}{a junk}
{131301}{}{Useless junk.}
{131400}{}{a floor}
{131500}{}{a floor}
{131600}{}{a floor}
{131700}{}{a car}
{131701}{}{This baby won't be riding the highways anymore.}
{131800}{}{a car}
{131801}{}{Just a rusty bucket of nuts now.}
{131900}{}{a car}
{131901}{}{This one will never go anywhere.}
{132000}{}{a utility}
{132001}{}{There are pipes, cables, other equipment.}
{132100}{}{a utility}
{132101}{}{There are pipes, cables, other equipment.}
{132200}{}{a utility}
{132201}{}{There are pipes, cables, other equipment.}
{132300}{}{a utility}
{132301}{}{There are pipes, cables, other equipment.}
{132400}{}{a car}
{132401}{}{All that junk can do now is rust.}
{132500}{}{the machines}
{132501}{}{A pile of wrecked cars.}
{132600}{}{a car}
{132601}{}{Rusty garbage, gradually absorbed by other garbage.}
{132700}{}{the lighting fixture}
{132701}{}{The dim lighting of the parking lot.}
{132800}{}{the lighting fixture}
{132801}{}{The dim lighting of the parking lot.}
{132900}{}{the lighting fixture}
{132901}{}{The fixture doesn't shine, apparently because it's broken.}
{133000}{}{a cave entrance}
{133100}{}{a floor}
{133200}{}{a floor}
{133300}{}{a floor}
{133400}{}{a floor}
{133500}{}{a terminal}
{133501}{}{Used to activate the elevator.}
{133600}{}{a terminal}
{133601}{}{Used to activate the elevator.}
{133700}{}{a control room door}
{133701}{}{Very massive and imposing. Probably it could take years to try opening it.}
{133800}{}{a vault city gate}
{133900}{}{a wall}
{134000}{}{a wall}
{134100}{}{a wall}
{134200}{}{a wall}
{134300}{}{a wall}
{134400}{}{a wall}
{134500}{}{a wall}
{134600}{}{a bench}
{134601}{}{A wide concrete bench.}
{134700}{}{a door}
{134800}{}{a door, forcibly opened.}
{134900}{}{a door wreckage.}
{135000}{}{a wall}
{135100}{}{a wall}
{135200}{}{a wall}
{135300}{}{a wall}
{135400}{}{a wall}
{135500}{}{a wall}
{135600}{}{a wall}
{135700}{}{a wall}
{135800}{}{a door}
{135900}{}{a wall}
{136000}{}{a wall}
{136100}{}{a wall}
{136200}{}{a wall}
{136300}{}{a plant}
{136301}{}{Some kind of desert plant.}
{136400}{}{a floor}
{136500}{}{a floor}
{136600}{}{a floor}
{136700}{}{a hovitaser... hmmm... or something elseЕ}
{136701}{}{This strange cannon has been left here since before the war. What an end to life's journey.}
{136800}{}{an escarpment}
{136900}{}{the crossing}
{137000}{}{a crate}
{137001}{}{Broken crate with hinges on the side.}
{137100}{}{a floor}
{137200}{}{a floor}
{137300}{}{a crate}
{137301}{}{A very heavy metal crate with some junk in it.}
{137400}{}{a crate}
{137401}{}{A very heavy metal crate with some junk in it.}
{137500}{}{a crate}
{137501}{}{A heavy but empty metal crate.}
{137600}{}{a crate}
{137601}{}{A very heavy metal crate with some junk in it.}
{137700}{}{a verti...what?}
{137701}{}{NEED A LONG DESCRIPTION.}
{137800}{}{a hole}
{137801}{}{Large hole in the ground.}
{137900}{}{a tower}
{137901}{}{A security tower with a machine gun.}
{138000}{}{a hole}
{138100}{}{a hole}
{138200}{}{a hole}
{138300}{}{a hole}
{138400}{}{a hole}
{138500}{}{a hole}
{138600}{}{the light}
{138700}{}{a door}
{138800}{}{a door}
{138900}{}{a door}
{139000}{}{a door}
{139100}{}{a door}
{139200}{}{a door}
{139300}{}{a crate}
{139301}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139400}{}{a crate}
{139401}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139500}{}{a crate}
{139501}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139600}{}{a crate}
{139601}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139700}{}{a crate}
{139701}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{139800}{}{a crate}
{139801}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{139900}{}{a crate}
{139901}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{140000}{}{a crate}
{140001}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{140100}{}{a shadow}
{140200}{}{a poster}
{140201}{}{The poster has survived quite well.}
{140300}{}{a car}
{140301}{}{An old, dilapidated car.}
{140400}{}{a car}
{140401}{}{Not even an ingenious mechanic could make this broken machine move on its own.}
{140500}{}{a big car}
{140501}{}{An old, dilapidated car.}
{140600}{}{a pole}
{140700}{}{a wall}
{140800}{}{a wall}
{140900}{}{a wall}
{141000}{}{a dispatcher's cockpit}
{141001}{}{The dispatcher from here used to court traffic. Now there is no traffic and no dispatcher.}
{141100}{}{a dispatcher's cockpit}
{141101}{}{The dispatcher from here used to court traffic. Now there is no traffic and no dispatcher.}
{141200}{}{a pole}
{141300}{}{a renesco pharmacy sign}
{141400}{}{a pole}
{141500}{}{a pole}
{141600}{}{a radio tower}
{141601}{}{Homemade radio tower.}
{141700}{}{a workshop door}
{141800}{}{a workshop door}
{141900}{}{a wall}
{142000}{}{a wall}
{142100}{}{a wall}
{142200}{}{a wall}
{142300}{}{a wall}
{142400}{}{a wall}
{142500}{}{a wall}
{142600}{}{a wall}
{142601}{}{a wall}
{142700}{}{a wall}
{142800}{}{a wall}
{142900}{}{a wall}
{143000}{}{a wall}
{143100}{}{a wall}
{143200}{}{a wall}
{143300}{}{a rope}
{143301}{}{You can climb the wall with this rope.}
{143400}{}{a door}
{143401}{}{The door that leads to the enclosed part of the terrace.}
{143500}{}{a door}
{143600}{}{an asphalt}
{143700}{}{an asphalt}
{143800}{}{an asphalt}
{143900}{}{an asphalt}
{144000}{}{an asphalt}
{144100}{}{an asphalt}
{144200}{}{a vent}
{144201}{}{Part of the ventilation system.}
{144300}{}{a vent}
{144301}{}{Part of the ventilation system.}
{144400}{}{a vent}
{144401}{}{Part of the ventilation system.}
{144500}{}{a vent}
{144501}{}{Part of the ventilation system.}
{144600}{}{a vent}
{144601}{}{Part of the ventilation system.}
{144700}{}{a vent}
{144701}{}{Part of the ventilation system.}
{144800}{}{an asphalt}
{144900}{}{a door}
{145000}{}{the pipes}
{145001}{}{Huge pipes leading under the water.}
{145100}{}{the pipes}
{145101}{}{Huge pipes leading under the water.}
{145200}{}{the pipes}
{145201}{}{Huge pipes leading under the water.}
{145300}{}{the pipes}
{145301}{}{Huge pipes leading under the water.}
{145400}{}{the pipes}
{145401}{}{Huge pipes leading under the water.}
{145500}{}{the pipes}
{145501}{}{Huge pipes leading under the water.}
{145600}{}{the pipes}
{145601}{}{Huge pipes leading under the water.}
{145700}{}{the pipes}
{145701}{}{Huge pipes leading under the water.}
{145800}{}{an escarpment}
{145900}{}{the pipes}
{145901}{}{Huge pipes leading under the water.}
{146000}{}{the pipes}
{146001}{}{Huge pipes leading under the water.}
{146100}{}{the pipes}
{146101}{}{Huge pipes leading under the water.}
{146200}{}{things}
{146201}{}{A pile of useless junk.}
{146300}{}{things}
{146301}{}{A pile of useless junk.}
{146400}{}{a huge water tank}
{146401}{}{Holes in the tank covered with metal plates.}
{146500}{}{a huge water tank}
{146501}{}{Holes in the tank covered with metal plates.}
{146600}{}{a door in the fence}
{146700}{}{a door in the fence}
{146800}{}{ the commander's seat}
{146801}{}{This is where the Overseer usually sits.}
{146900}{}{the stones}
{146901}{}{A pile of rocks and dirt.}
{147000}{}{the stones}
{147001}{}{A pile of rocks and dirt.}
{147100}{}{the stones}
{147101}{}{A pile of rocks and dirt.}
{147200}{}{the stones}
{147201}{}{A pile of rocks and dirt.}
{147300}{}{the stones}
{147301}{}{A pile of rocks and dirt.}
{147400}{}{the stones}
{147401}{}{A pile of rocks and dirt.}
{147500}{}{a huge water tank}
{147501}{}{Holes in the tank covered with metal plates.}
{147600}{}{the pipes}
{147601}{}{A section of massive pipe.}
{147700}{}{a land}
{147701}{}{The ground to the top floor is taken from here.}
{147800}{}{a wall}
{147900}{}{a door}
{148000}{}{a door}
{148100}{}{a pipe}
{148101}{}{A section of massive pipe.}
{148200}{}{a wall}
{148300}{}{water}
{148400}{}{things}
{148401}{}{There's nothing of value here.}
{148500}{}{a floor}
{148600}{}{the Mouth of Hades}
{148601}{}{It looks disgusting and scary. Smells correspondingly.}
{148700}{}{a wall}
{148800}{}{the abyss}
{148801}{}{The darkness is impenetrable.}
{148900}{}{devices}
{148901}{}{Devices to keep the boiler running.}
{149000}{}{devices}
{149001}{}{Devices to keep the boiler running.}
{149100}{}{a door}
{149200}{}{a door}
{149201}{}{This door is very poorly preserved.}
{149300}{}{a tipped bed}
{149301}{}{Tattered bed with springs sticking out.}
{149400}{}{a tipped bed}
{149401}{}{Looks like this bed has served its purpose.}
{149500}{}{a junk}
{149501}{}{Some machinery parts.}
{149600}{}{a junk}
{149601}{}{Useless junk.}
{149700}{}{a junk}
{149701}{}{Broken bottles and other debris.}
{149800}{}{a junk}
{149801}{}{Parts of old crates.}
{149900}{}{a junk}
{149901}{}{Three empty drawers.}
{150000}{}{a pattern}
{150001}{}{The shaped pattern on the wall.}
{150100}{}{a pattern}
{150101}{}{The shaped pattern on the wall.}
{150200}{}{a floor}
{150300}{}{a floor}
{150400}{}{a boxes}
{150401}{}{Apparently, someone inspected them before you - there's nothing of value there.}
{150500}{}{the machinery}
{150600}{}{a hay}
{150601}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{150700}{}{a hay}
{150701}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{150800}{}{a hay}
{150801}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{150900}{}{a hay}
{150901}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151000}{}{a hay}
{151001}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151100}{}{a hay}
{151101}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151200}{}{a hay}
{151201}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151300}{}{a junk}
{151301}{}{Boxes, boxes, something else. But absolutely nothing useful.}
{151400}{}{a debris}
{151401}{}{The ruined walls of a building.}
{151500}{}{a debris}
{151501}{}{The ruined walls of a building.}
{151600}{}{a debris}
{151601}{}{The ruined walls of a building.}
{151700}{}{a debris}
{151701}{}{The ruined walls of a building.}
{151800}{}{a door}
{151801}{}{A door from a closet.}
{151900}{}{a door}
{151901}{}{A door from a closet.}
{152000}{}{a pipe}
{152001}{}{Part of a heavy pipe.}
{152100}{}{a pipe}
{152101}{}{Part of a heavy pipe.}
{152200}{}{a pipe}
{152201}{}{Part of a heavy pipe.}
{152300}{}{a pipe}
{152301}{}{Part of a heavy pipe.}
{152400}{}{a crate}
{152401}{}{A large empty box of dry wood.}
{152500}{}{a crate}
{152501}{}{A large empty box of dry wood.}
{152600}{}{a crate}
{152601}{}{A large empty box of dry wood.}
{152700}{}{a pipe}
{152800}{}{a pipe}
{152900}{}{the parts of the box}
{153000}{}{the parts of the box}
{153100}{}{a door}
{153101}{}{The door leading into the arena.}
{153200}{}{a door}
{153201}{}{In front of you is a standard door.}
{153300}{}{a door}
{153301}{}{In front of you is a standard door.}
{153400}{}{a door}
{153401}{}{The door leading into the arena.}
{153500}{}{a door}
{153501}{}{In front of you is a standard door.}
{153600}{}{a door}
{153601}{}{In front of you is a standard door.}
{153700}{}{the factory building}
{153800}{}{a wall}
{153900}{}{a wall}
{154000}{}{a toilet}
{154001}{}{There's a horrible smell coming from it.}
{154100}{}{a wall}
{154200}{}{a pipe}
{154201}{}{Rusted in several places.}
{154300}{}{a pipe}
{154301}{}{Rusted in several places.}
{154400}{}{a toilet}
{154401}{}{This is where the pipes and other equipment go.}
{154500}{}{a utility}
{154501}{}{This is where the pipes and other equipment go.}
{154600}{}{a utility}
{154601}{}{This is where the pipes and other equipment go.}
{154700}{}{the rags}
{154701}{}{Stinky old bed.}
{154800}{}{the force field}
{154900}{}{the force field}
{155000}{}{an organ removal device}
{155001}{}{The latest model in the surgical DIY series. Removes organs at the push of a button.}
{155100}{}{a bed}
{155101}{}{It's uncomfortable to even stand next to it, and the thought of lying down makes you nauseous.}
{155200}{}{the rags}
{155201}{}{Stinky old bed.}
{155300}{}{a bed}
{155301}{}{It's uncomfortable to even stand next to it, and the thought of lying down makes you nauseous.}
{155400}{}{the rags}
{155401}{}{Perhaps it was a bed, but you're not sure.}
{155500}{}{a wall}
{155501}{}{Pipes on tattered walls.}
{155600}{}{a junk}
{155601}{}{Broken table.}
{155700}{}{a junk}
{155701}{}{Some kind of trash.}
{155800}{}{an electric box}
{155801}{}{The electrical box is used to distribute electricity.}
{155900}{}{the pipes}
{155901}{}{A whole assembly of pipes.}
{156000}{}{a fence}
{156001}{}{A structure made of rotten wood.}
{156100}{}{a fence}
{156101}{}{A structure made of rotten wood.}
{156200}{}{a pool of water}
{156201}{}{There is more dirt than water.}
{156300}{}{a pool of water}
{156301}{}{There is more dirt than water.}
{156400}{}{a pool of water}
{156401}{}{There is more dirt than water.}
{156500}{}{a fence}
{156501}{}{A structure made of rotten wood.}
{156600}{}{a pool of water}
{156601}{}{There is more dirt than water.}
{156700}{}{a destroyed wall}
{156800}{}{a destroyed wall}
{156900}{}{a wall}
{157000}{}{a wall}
{157100}{}{a floor}
{157200}{}{a floor}
{157300}{}{a door}
{157301}{}{A door with a small window.}
{157400}{}{a door}
{157401}{}{A solid door.}
{157500}{}{a door}
{157600}{}{a door}
{157700}{}{a part of a car}
{157701}{}{Looks like an engine ripped out of a car.}
{157800}{}{the bull's head}
{157801}{}{A bull in a hat peeking out of a tin can. A logo of the "Happy bull" factory.}
{157900}{}{a wall}
{157901}{}{a half-destroyed wall}
{158000}{}{a hole}
{158001}{}{There is a hole in the floor in front of you.}
{158100}{}{rocks}
{158101}{}{Look impregnable.}
{158200}{}{rocks}
{158201}{}{Look impregnable.}
{158300}{}{rocks}
{158301}{}{Look impregnable.}
{158400}{}{a beam}
{158401}{}{A moldy, rotten wooden beam.}
{158500}{}{a damaged wall}
{158600}{}{a car}
{158601}{}{An old, dilapidated car.}
{158700}{}{a fence}
{158701}{}{A structure made of rotten wood.}
{158800}{}{a damaged wall}
{158900}{}{a wall}
{159000}{}{a damaged wall}
{159100}{}{a damaged wall}
{159200}{}{a damaged wall}
{159300}{}{the pipes}
{159301}{}{A section of heavy pipe.}
{159400}{}{the pipes}
{159401}{}{A section of heavy pipe.}
{159500}{}{a damaged wall}
{159600}{}{a wall}
{159700}{}{the pipes}
{159701}{}{Slimy, mold-covered pipes.}
{159800}{}{the pipes}
{159801}{}{Slimy, mold-covered pipes.}
{159900}{}{a wall}
{160000}{}{a floor}
{160100}{}{a car}
{160101}{}{An old, dilapidated car.}
{160200}{}{the parts of the box}
{160201}{}{Dry wood box walls.}
{160300}{}{a trough}
{160301}{}{An open container of dirty water.}
{160400}{}{a trough}
{160401}{}{An open container of dirty water.}
{160500}{}{the parts of the box}
{160501}{}{Dry wood box walls.}
{160600}{}{a factory}
{160601}{}{Factory building.}
{160700}{}{a factory}
{160701}{}{Factory building.}
{160800}{}{a factory}
{160801}{}{Factory building.}
{160900}{}{a factory}
{160901}{}{Factory building.}
{161000}{}{a floor}
{161100}{}{a bed}
{161101}{}{An old stinky floor bed and some trash.}
{161200}{}{a bed}
{161201}{}{Looks like something is crawling on it.}
{161300}{}{a factory}
{161301}{}{Factory building.}
{161400}{}{a factory}
{161401}{}{Factory building.}
{161500}{}{a bed}
{161501}{}{Stinky old bed.}
{161600}{}{a pillow}
{161601}{}{Very dirty.}
{161700}{}{a bed}
{161701}{}{If you lie down on one, you can get some nasty stuff.}
{161800}{}{a bed}
{161801}{}{Stinky old bed.}
{161900}{}{parts of the fence}
{161901}{}{Parts of the factory fence.}
{162000}{}{a makeshift podium}
{162001}{}{A stage for giving speeches. It is crudely assembled from planks.}
{162100}{}{parts of the fence}
{162101}{}{Parts of the factory fence.}
{162200}{}{a bed}
{162201}{}{A very dirty, smelly, stinky floor bed.}
{162300}{}{a bed}
{162301}{}{Stinky old bed.}
{162400}{}{a bed}
{162401}{}{There's definitely fungus on it. And mold.}
{162500}{}{the pipes}
{162501}{}{A section of massive pipe.}
{162600}{}{a utility}
{162601}{}{There are pipes, cables, other equipment.}
{162700}{}{the pipes}
{162701}{}{A section of massive pipe.}
{162800}{}{a barrel}
{162801}{}{An empty wooden barrel.}
{162900}{}{a barrel}
{162901}{}{An empty wooden barrel.}
{163000}{}{a damaged wall}
{163100}{}{the pipes}
{163101}{}{A section of massive pipe.}
{163200}{}{the pipes}
{163201}{}{A section of massive pipe.}
{163300}{}{a half-destroyed wall}
{163400}{}{the shelves of medicine}
{163401}{}{You don't know the purpose of these medications.}
{163500}{}{the shelves of medicine}
{163501}{}{You don't know the purpose of these medications.}
{163600}{}{a barrel}
{163601}{}{Empty wooden barrel.}
{163700}{}{barrels}
{163701}{}{Barrels stacked on top of each other.}
{163800}{}{barrels}
{163801}{}{Barrels stacked on top of each other.}
{163900}{}{parts of the fence}
{163901}{}{A board broke out of a fence.}
{164000}{}{a tent}
{164001}{}{Rolled up tent}
{164100}{}{parts of the fence}
{164101}{}{A board broke out of a fence.}
{164200}{}{parts of the fence}
{164201}{}{A board broke out of a fence.}
{164300}{}{the machinery}
{164301}{}{Intended for handling various materials.}
{164400}{}{the machinery}
{164401}{}{Intended for handling various materials.}
{164500}{}{the stairs down}
{164600}{}{the stairs up}
{164601}{}{This stairway leads up.}
{164700}{}{an entrance to the station}
{164701}{}{The stairs end in the darkness.}
{164800}{}{the stairs down}
{164801}{}{The stairway leads into the darkness.}
{164900}{}{parts of the fence}
{164901}{}{A board broke out of a fence.}
{165000}{}{parts of the fence}
{165001}{}{A board broke out of a fence.}
{165100}{}{parts of the fence}
{165101}{}{A board broke out of a fence.}
{165200}{}{the stairs up}
{165201}{}{This stairway leads up.}
{165300}{}{the sandbags}
{165301}{}{Military fortification.}
{165400}{}{the sandbags}
{165401}{}{Military fortification.}
{165500}{}{a shaft elevator}
{165600}{}{a beam}
{165700}{}{parts of the fence}
{165701}{}{A board broke out of a fence.}
{165800}{}{the stones}
{165900}{}{parts of the fence}
{165901}{}{A board broke out of a fence.}
{166000}{}{a passageway}
{166100}{}{a fence}
{166101}{}{A structure made of rotten wood.}
{166200}{}{a pole}
{166201}{}{Supporting structure.}
{166300}{}{a pole}
{166301}{}{Supporting structure.}
{166400}{}{a pole}
{166401}{}{Supporting structure.}
{166500}{}{a pole}
{166501}{}{Supporting structure.}
{166600}{}{a pole}
{166601}{}{Supporting structure.}
{166700}{}{a pole}
{166701}{}{Supporting structure.}
{166800}{}{a pole}
{166801}{}{Supporting structure.}
{166900}{}{a hole}
{167000}{}{a pole}
{167001}{}{Supporting structure.}
{167100}{}{a hole}
{167200}{}{a barrier}
{167201}{}{Rag partition.}
{167300}{}{a barrier}
{167301}{}{Rag partition.}
{167400}{}{a half-destroyed wall}
{167500}{}{a wall that has been built recently}
{167600}{}{a part of the fence}
{167601}{}{A board broke out of a fence.}
{167700}{}{a barrier}
{167701}{}{Rag partition.}
{167800}{}{a barrier}
{167801}{}{Rag partition.}
{167900}{}{a hole}
{168000}{}{a barrier}
{168001}{}{Rag partition.}
{168100}{}{a bed}
{168101}{}{Not worth resting here.}
{168200}{}{the cylinders}
{168201}{}{Some kind of substance inside.}
{168300}{}{the cylinders}
{168301}{}{Some kind of substance inside.}
{168400}{}{a tile}
{168500}{}{a shaft elevator}
{168600}{}{a tile}
{168700}{}{a tile}
{168800}{}{a half-destroyed wall}
{168900}{}{a elevator}
{169000}{}{a elevator}
{169100}{}{a half-destroyed wall}
{169200}{}{a half-destroyed wall}
{169300}{}{a hole}
{169400}{}{the corner of the wall}
{169500}{}{a hole}
{169600}{}{a hole}
{169700}{}{things}
{169701}{}{A pile of useless junk.}
{169800}{}{a barrier}
{169801}{}{Rag partition.}
{169900}{}{a barrier}
{169901}{}{Rag partition.}
{170000}{}{a half-destroyed wall}
{170100}{}{a broken pole}
{170200}{}{a barrier}
{170201}{}{Rag partition.}
{170300}{}{a barrier}
{170301}{}{Rag partition.}
{170400}{}{a barrier}
{170401}{}{Rag partition.}
{170500}{}{a pole}
{170501}{}{Supporting structure.}
{170600}{}{the shelves}
{170601}{}{Unfortunately, you have nothing to gain here.}
{170700}{}{the shelves}
{170701}{}{There's nothing of value here.}
{170800}{}{the shelves}
{170900}{}{a door}
{171000}{}{a door}
{171100}{}{a column}
{171101}{}{A decorative structure.}
{171200}{}{a column}
{171201}{}{A decorative structure.}
{171300}{}{a decorated image}
{171301}{}{The face of the portrait is taped over with another face, neatly carved out of a photograph. You recognize one of the Livos dwellers.}
{171400}{}{a decorated image}
{171401}{}{Looking at this image makes you think that art can be extremely strange.}
{171500}{}{a decorated image}
{171501}{}{It serves a purely aesthetic function.}
{171600}{}{a decorated image}
{171601}{}{You are not a fan of this kind of painting.}
{171700}{}{a decorated image}
{171701}{}{The locals seem to appreciate art.}
{171800}{}{a decorated image}
{171801}{}{You are not a fan of this kind of painting.}
{171900}{}{a decorated image}
{171901}{}{The face of the portrait is taped over with another face, neatly carved out of a photograph. You recognize one of the Livos dwellers.}
{172000}{}{a decorated image}
{172001}{}{The locals seem to appreciate art.}
{172100}{}{a bulletproof glass}
{172200}{}{a bulletproof glass}
{172300}{}{a bulletproof glass}
{172400}{}{a decorated image}
{172401}{}{You are not a fan of this kind of painting.}
{172500}{}{a decorated image}
{172501}{}{The locals seem to appreciate art.}
{172600}{}{a stone}
{172601}{}{Huge stone with a flat facet. Very heavy.}
{172700}{}{a stone}
{172701}{}{A hard rock.}
{172800}{}{a stone}
{172801}{}{It seems to be shaped like a hat. You can also sit on it.}
{172900}{}{a stone}
{172901}{}{The stone is bizarrely shaped.}
{173000}{}{a crate}
{173001}{}{Nothing interesting about this object.}
{173100}{}{the box parts}
{173101}{}{The wall of the wooden box.}
{173200}{}{the box parts}
{173201}{}{The wall of the wooden box.}
{173300}{}{the box parts}
{173301}{}{The wall of the wooden box.}
{173400}{}{a floor}
{173500}{}{a floor}
{173600}{}{a floor}
{173700}{}{an exit}
{173800}{}{a table with a candle}
{173801}{}{Dirty table illuminated by a candle flame.}
{173900}{}{a floor}
{174000}{}{things}
{174001}{}{A pile of useless junk.}
{174100}{}{a pool of water}
{174101}{}{There is more dirt than water.}
{174200}{}{a floor}
{174300}{}{a pole}
{174301}{}{Supporting structure.}
{174400}{}{a stool}
{174401}{}{An old and completely ordinary piece of furniture.}
{174500}{}{a table}
{174501}{}{A table with a dirty, torn tablecloth and food scraps.}
{174600}{}{a tile}
{174700}{}{a tile}
{174800}{}{rocks}
{174801}{}{Look impregnable.}
{174900}{}{a part of the fence}
{174901}{}{A board broke out of a fence.}
{175000}{}{water cisterns}
{175001}{}{Large, rusty water tanks.}
{175100}{}{a pool of water}
{175101}{}{There is more dirt than water.}
{175200}{}{a decorated image}
{175201}{}{You study the image for a while, but it does not become any clearer.}
{175300}{}{a decorated image}
{175301}{}{It remains a mystery to you what the author wanted to say with this work.}
{175400}{}{a toilet}
{175401}{}{In excellent condition.}
{175500}{}{a cross}
{175600}{}{a well}
{175601}{}{A structure for extracting water.}
{175700}{}{the pipes}
{175701}{}{A section of massive pipe.}
{175800}{}{water cisterns}
{175801}{}{Large, rusty water tanks.}
{175900}{}{the pipes}
{175901}{}{There are pipes, cables, other equipment.}
{176000}{}{the pipes}
{176001}{}{Niche for the outlet of some pipes and other utilities.}
{176100}{}{a pipe}
{176101}{}{A section of massive pipe.}
{176200}{}{the pipes}
{176201}{}{A section of massive pipe.}
{176300}{}{the pipes}
{176301}{}{A section of massive pipe.}
{176400}{}{the pipes}
{176401}{}{A section of massive pipe.}
{176500}{}{the pipes}
{176501}{}{A section of massive pipe.}
{176600}{}{the pipes}
{176601}{}{A section of massive pipe.}
{176700}{}{the pipes}
{176701}{}{A section of massive pipe.}
{176800}{}{the pipes}
{176801}{}{A section of massive pipe.}
{176900}{}{the pipes}
{176901}{}{A section of massive pipe.}
{177000}{}{the pipes}
{177001}{}{A section of massive pipe.}
{177100}{}{the pipes}
{177101}{}{A section of massive pipe.}
{177200}{}{the descent to the water}
{177300}{}{water}
{177400}{}{water}
{177500}{}{water}
{177600}{}{water}
{177700}{}{the pipes}
{177701}{}{A section of massive pipe.}
{177800}{}{a bed}
{177801}{}{Not the cleanest recreational item.}
{177900}{}{a fire}
{177901}{}{You're not going to look at it forever, are you?}
{178000}{}{a bed}
{178001}{}{Seems like only someone who doesn't feel smells could sleep on it.}
{178100}{}{a bed}
{178101}{}{Seems like only someone who doesn't feel smells could sleep on it.}
{178200}{}{a bed}
{178201}{}{It looks like it's already rotten.}
{178300}{}{a bed}
{178301}{}{It's an old, stinking bed.}
{178400}{}{a bed}
{178401}{}{It's no time to rest, much less on it.}
{178500}{}{a floor}
{178600}{}{a floor}
{178700}{}{some trash in the water}
{178701}{}{Something seems to be leaked around.}
{178800}{}{a wagon}
{178801}{}{Constructed from a car.}
{178900}{}{a wagon}
{178901}{}{Constructed from a car.}
{179000}{}{a car}
{179001}{}{An old, dilapidated car.}
{179100}{}{tools}
{179101}{}{Various tools, but they are not usable.}
{179200}{}{tools}
{179201}{}{Various tools, but they are not usable.}
{179300}{}{water}
{179301}{}{Very dirty. Can't see anything through the mud.}
{179400}{}{water}
{179401}{}{Very dirty. Can't see anything through the mud.}
{179500}{}{an escarpment}
{179501}{}{There's only water. You don't want to swim in it at all.}
{179600}{}{an escarpment}
{179601}{}{There's only water. You don't want to swim in it at all.}
{179700}{}{an escarpment}
{179701}{}{There's only water.}
{179800}{}{an escarpment}
{179801}{}{There's only water.}
{179900}{}{a grate}
{179901}{}{Sewer grate.}
{180000}{}{a grate}
{180001}{}{Sewer grate.}
{180100}{}{an escarpment}
{180101}{}{There's only water.}
{180200}{}{an escarpment}
{180300}{}{the stones}
{180400}{}{a crate}
{180500}{}{the lights}
{180600}{}{the spikes}
{180601}{}{Sharp spikes, will easily puncture your foot.}
{180700}{}{an exit}
{180800}{}{a barrier}
{180801}{}{Rag partition.}
{180900}{}{a barrier}
{180901}{}{Rag partition.}
{181000}{}{a barrier}
{181001}{}{Rag partition.}
{181100}{}{water cisterns}
{181101}{}{Large, rusty water tanks.}
{181200}{}{a barrier}
{181201}{}{Rag partition.}
{181300}{}{an exit}
{181301}{}{Leads to darkness.}
{181400}{}{a stove}
{181500}{}{a barrier}
{181501}{}{Rag partition.}
{181600}{}{a barrier}
{181601}{}{Rag partition.}
{181700}{}{a bar}
{181800}{}{a door}
{181801}{}{Leads to the hotel's lobby.}
{181900}{}{a door}
{182000}{}{a blood}
{182001}{}{Somebody died here quite recently.}
{182100}{}{a blood}
{182101}{}{Not the freshest.}
{182200}{}{a blood}
{182201}{}{Mother always told you that this liquid should be INSIDE, not outside.}
{182300}{}{a blood}
{182301}{}{Looks like someone's bones are in this puddle.}
{182400}{}{a blood}
{182401}{}{Mother always told you that this liquid should be INSIDE, not outside.}
{182500}{}{bones and guts}
{182501}{}{The mortal remains that smell of fresh blood.}
{182600}{}{rocks}
{182601}{}{Look impregnable.}
{182700}{}{rocks}
{182701}{}{Look impregnable.}
{182800}{}{rocks}
{182801}{}{Look impregnable.}
{182900}{}{rocks}
{182901}{}{Look impregnable.}
{183000}{}{rocks}
{183001}{}{Look impregnable.}
{183100}{}{rocks}
{183101}{}{Look impregnable.}
{183200}{}{rocks}
{183201}{}{Look impregnable.}
{183300}{}{rocks}
{183301}{}{Look impregnable.}
{183400}{}{rocks}
{183401}{}{Look impregnable.}
{183500}{}{the staircase}
{183501}{}{The steps form a wide staircase.}
{183600}{}{a blood}
{183601}{}{The blood has already had time to soak in.}
{183700}{}{blood, guts, bones.}
{183701}{}{You see someone's rich inner world in front of you.}
{183800}{}{a tent}
{183801}{}{Used for sleeping, resting, sheltering from the weather.}
{183900}{}{rocks}
{183901}{}{Look impregnable.}
{184000}{}{rocks}
{184001}{}{Look impregnable.}
{184100}{}{a tent}
{184101}{}{Used for sleeping, resting, sheltering from the weather.}
{184200}{}{a tent}
{184201}{}{Used for sleeping, resting, sheltering from the weather.}
{184300}{}{a tent}
{184301}{}{Used for sleeping, resting, sheltering from the weather.}
{184400}{}{the way down}
{184500}{}{a bed}
{184501}{}{When you see this bed, the desire to lie down instantly disappears.}
{184600}{}{a fence}
{184700}{}{the corner of the wall}
{184800}{}{a pole}
{184801}{}{Supporting structure.}
{184900}{}{a barrel}
{184901}{}{Metal barrel.}
{185000}{}{a barrel}
{185001}{}{Metal barrel.}
{185100}{}{the steam}
{185200}{}{a barrier}
{185201}{}{Emergency sign.}
{185300}{}{a junk}
{185301}{}{Various machine parts, but nothing useful.}
{185400}{}{a junk}
{185401}{}{Fence parts.}
{185500}{}{a junk}
{185501}{}{Bricks}
{185600}{}{a junk}
{185601}{}{A barrel, car tires, something else.}
{185700}{}{a junk}
{185701}{}{A useless pile of junk.}
{185800}{}{an armchair}
{185801}{}{This chair looks like it served its purpose years ago.}
{185900}{}{the doctor's table}
{185901}{}{Dirty desk with some trash and a calculator}
{186000}{}{a car}
{186001}{}{An old rusty car.}
{186100}{}{a crate}
{186101}{}{Nothing special, just a crate.}
{186200}{}{a garbage barrel}
{186201}{}{Useless junk.}
{186300}{}{tires}
{186301}{}{Car tires, nothing interesting.}
{186400}{}{tires}
{186401}{}{Car tires, nothing interesting.}
{186500}{}{a tire}
{186501}{}{Car tire, nothing interesting.}
{186600}{}{a wagon}
{186601}{}{Constructed from a car.}
{186700}{}{a wagon}
{186701}{}{Constructed from a car.}
{186800}{}{a junk}
{186801}{}{A useless pile of junk.}
{186900}{}{a junk}
{186901}{}{A useless pile of junk.}
{187000}{}{a seat}
{187001}{}{Ripped out of a car.}
{187100}{}{tires}
{187101}{}{Car tires, nothing interesting.}
{187200}{}{a tent}
{187201}{}{Looks like this tent has served its purpose.}
{187300}{}{a tent}
{187301}{}{Looks like this tent has served its purpose.}
{187400}{}{a car}
{187401}{}{An old, dilapidated car.}
{187500}{}{a car}
{187501}{}{No one's going anywhere with this.}
{187600}{}{a car}
{187601}{}{An old, dilapidated car.}
{187700}{}{a junk}
{187701}{}{A useless pile of junk.}
{187800}{}{a car}
{187801}{}{Now it's just a pile of worthless metal and it's not going anywhere.}
{187900}{}{a car}
{187901}{}{An old, dilapidated car.}
{188000}{}{a car}
{188001}{}{An old, dilapidated car.}
{188100}{}{a car}
{188101}{}{Now it's just a pile of worthless metal and it's not going anywhere.}
{188200}{}{a car}
{188301}{}{A useless pile of junk.}
{188300}{}{a junk}
{188301}{}{A useless pile of junk.}
{188400}{}{a junk}
{188401}{}{There's nothing to eat.}
{188500}{}{a junk}
{188501}{}{Looks like bricks. You don't need them at all.}
{188600}{}{a junk}
{188601}{}{A useless pile of junk.}
{188700}{}{a junk}
{188701}{}{You won't find anything of value in here.}
{188800}{}{a junk}
{188801}{}{A useless pile of junk.}
{188900}{}{a junk}
{188901}{}{You're not likely to find anything of value in here.}
{189000}{}{things}
{189001}{}{A lot of junk. Nothing useful in here.}
{189100}{}{a junk}
{189101}{}{Bottles are empty and dirty - nothing to eat.}
{189200}{}{a car}
{189201}{}{An old, dilapidated car.}
{189300}{}{a junk}
{189301}{}{Useless junk.}
{189400}{}{a junk}
{189401}{}{Useless junk.}
{189500}{}{the shelves}
{189501}{}{Shelves of booze.}
{189600}{}{the shelves}
{189601}{}{Shelves of booze.}
{189700}{}{a table}
{189800}{}{a chair}
{189801}{}{The usual bar stool.}
{189900}{}{a junk}
{189901}{}{Useless garbage, carefully covered with a cloth.}
{190000}{}{a car}
{190001}{}{No one's going anywhere with this.}
{190100}{}{a car}
{190101}{}{Unlikely to be repairable.}
{190200}{}{a barrier}
{190201}{}{Rag partition.}
{190300}{}{a barrier}
{190301}{}{Rag partition.}
{190400}{}{a barrier}
{190401}{}{Rag partition.}
{190500}{}{a barrier}
{190501}{}{Rag partition.}
{190600}{}{a barrier}
{190601}{}{Rag partition.}
{190700}{}{a barrier}
{190701}{}{Rag partition.}
{190800}{}{a barrel with soil}
{190801}{}{These barrels contain fertile soil.}
{190900}{}{a barrel with soil}
{190901}{}{These barrels contain fertile soil.}
{191000}{}{the barrels with soil}
{191001}{}{These barrels contain fertile soil.}
{191100}{}{a barrel with soil}
{191101}{}{These barrels contain fertile soil.}
{191200}{}{a barrel with soil}
{191201}{}{These barrels contain fertile soil.}
{191300}{}{a junk}
{191301}{}{You won't find anything useful there.}
{191400}{}{a junk}
{191401}{}{A useless pile of junk.}
{191500}{}{a barrel with soil}
{191501}{}{These barrels contain fertile soil.}
{191600}{}{a bed}
{191601}{}{This recliner must have been slept on for more than a year.}
{191700}{}{a bed}
{191701}{}{It seems to stink of something.}
{191800}{}{a bed}
{191801}{}{It's an old, stinking bed.}
{191900}{}{the rags}
{191901}{}{Sleeping on it is definitely no longer possible.}
{192000}{}{a floor}
{192100}{}{a floor}
{192200}{}{a floor}
{192300}{}{a door}
{192400}{}{a door}
{192500}{}{a table}
{192501}{}{Surprisingly clean enough table.}
{192600}{}{a table}
{192601}{}{The most ordinary table with some kind of tablecloth.}
{192700}{}{a table}
{192701}{}{An ordinary table with remnants of a former feast.}
{192800}{}{a table}
{192801}{}{Just a table, nothing unusual.}
{192900}{}{a table}
{192901}{}{Bottles cracked, nothing interesting.}
{193000}{}{a tank}
{193001}{}{A tank of water.}
{193100}{}{the arena warden's table}
{193101}{}{Here you can learn more about the fights in the arena.}
{193200}{}{bones}
{193201}{}{Human bones.}
{193300}{}{bones}
{193301}{}{Human bones. This poor man died many years ago.}
{193400}{}{bones}
{193401}{}{It was a human once.}
{193500}{}{a plant}
{193501}{}{A living green herbaceous plant.}
{193600}{}{a plant}
{193601}{}{A living green herbaceous plant.}
{193700}{}{a plant}
{193701}{}{A living green herbaceous plant.}
{193800}{}{a plant}
{193801}{}{A living green herbaceous plant.}
{193900}{}{a plant}
{193901}{}{A living green herbaceous plant.}
{194000}{}{a pole}
{194001}{}{A stripping pole.}
{194100}{}{an entrance}
{194200}{}{the building}
{194201}{}{Factory building.}
{194300}{}{the building}
{194301}{}{Factory building.}
{194400}{}{a junk}
{194401}{}{A useless pile of junk.}
{194500}{}{a box}
{194501}{}{There is absolutely nothing interesting about it.}
{194600}{}{a crate}
{194601}{}{An unremarkable box.}
{194700}{}{the sheet of iron}
{194701}{}{A useless pile of junk.}
{194800}{}{the sheet of iron}
{194801}{}{That won't do you any good.}
{194900}{}{the sheet of iron}
{194901}{}{A useless pile of junk.}
{195000}{}{the sheet of iron}
{195001}{}{That won't do you any good.}
{195100}{}{the cesspool}
{195101}{}{A great solution when you can't afford a central sewer.}
{195200}{}{the cesspool}
{195201}{}{A great solution when you can't afford a central sewer.}
{195300}{}{the cesspool}
{195301}{}{A great solution when you can't afford a central sewer.}
{195400}{}{the cesspool}
{195401}{}{A great solution when you can't afford a central sewer.}
{195500}{}{a table}
{195501}{}{A simple table.}
{195600}{}{a table}
{195601}{}{A simple table.}
{195700}{}{rocks}
{195701}{}{Look impregnable.}
{195800}{}{rocks}
{195801}{}{Look impregnable.}
{195900}{}{rocks}
{195901}{}{Look impregnable.}
{196000}{}{rocks}
{196001}{}{Look impregnable.}
{196100}{}{rocks}
{196101}{}{Look impregnable.}
{196200}{}{a tribune}
{196201}{}{A speaker's pulpit.}
{196300}{}{the screen}
{196400}{}{a stove}
{196401}{}{A heating and cooking stove.}
{196500}{}{a stove}
{196501}{}{A heating and cooking stove.}
{196600}{}{a tile}
{196700}{}{a tile}
{196800}{}{a tile}
{196900}{}{a tile}
{197000}{}{a tile}
{197100}{}{a tile}
{197200}{}{the stones}
{197201}{}{Just a pile of stones.}
{197300}{}{the stones}
{197301}{}{Just a pile of stones.}
{197400}{}{the stones}
{197401}{}{Just a pile of stones.}
{197500}{}{a beam}
{197501}{}{The support beam of the tunnel.}
{197600}{}{a beam}
{197601}{}{The support beam of the tunnel.}
{197700}{}{a beam}
{197701}{}{The support beam of the tunnel.}
{197800}{}{a beam}
{197801}{}{The support beam of the tunnel.}
{197900}{}{a beam}
{197901}{}{The support beam of the tunnel.}
{198000}{}{a beam}
{198001}{}{The support beam of the tunnel.}
{198100}{}{a beam}
{198101}{}{The support beam of the tunnel.}
{198200}{}{a beam}
{198201}{}{The support beam of the tunnel.}
{198300}{}{a beam}
{198301}{}{The support beam of the tunnel.}
{198400}{}{the stones}
{198401}{}{No time to gather stones.}
{198500}{}{the stones}
{198501}{}{No time to gather stones.}
{198600}{}{the stones}
{198601}{}{Just a pile of stones.}
{198700}{}{the stones}
{198701}{}{Just a pile of stones.}
{198800}{}{a box}
{198801}{}{Empty old box. Not of any interest.}
{198900}{}{a junk}
{198901}{}{Useless junk.}
{199000}{}{a junk}
{199001}{}{That won't do you any good.}
{199100}{}{a junk}
{199101}{}{That won't do you any good.}
{199200}{}{a junk}
{199201}{}{Useless junk.}
{199300}{}{a junk}
{199301}{}{Unlikely to be of any use to anyone.}
{199400}{}{a junk}
{199401}{}{That won't do you any good.}
{199500}{}{a junk}
{199501}{}{A useless pile of junk.}
{199600}{}{a junk}
{199601}{}{That won't do you any good.}
{199700}{}{a junk}
{199701}{}{A useless pile of junk.}
{199800}{}{a junk}
{199801}{}{That won't do you any good.}
{199900}{}{a junk}
{199901}{}{A useless pile of junk.}
{200000}{}{a junk}
{200001}{}{A useless pile of junk.}
{200100}{}{a junk}
{200101}{}{That won't do you any good.}
{200200}{}{a generator}
{200201}{}{A device that generates electricity.}
{200300}{}{a generator}
{200301}{}{A device that generates electricity.}
{200400}{}{a pump}
{200401}{}{A hydraulic machine.}
{200500}{}{a pipe}
{200501}{}{A pipe going into the ground.}
{200600}{}{a pipe}
{200601}{}{A pipe going into the ground.}
{200700}{}{a junk}
{200701}{}{A useless pile of junk.}
{200800}{}{a junk}
{200801}{}{A useless pile of junk.}
{200900}{}{NO}
{201000}{}{a food machine}
{201001}{}{When you press the button with a "Risotto" label on it, the machine spits out a suspiciously green slimy lump.}
{201100}{}{a food machine}
{201101}{}{When you press the button with a "Shrimp flambe" label on it, the machine spews out three gooey blobs. Tastes like chewed boogers.}
{201200}{}{a clothing machine}
{201201}{}{Looks like it doesn't work as intended.}
{201300}{}{a food machine}
{201301}{}{When you press the button with a "Tortilla" label on it, the machine spits out a soggy clump. Smells like an old sock.}
{201400}{}{a food machine}
{201401}{}{When you press the button with a "Brownie" label on it, the machine spews out an odorless and tasteless slurred mush.}
{201500}{}{a board}
{201501}{}{It's just an ordinary board. You can hardly use it.}
{201600}{}{a board}
{201601}{}{It's just an ordinary board. You can hardly use it.}
{201700}{}{a board}
{201701}{}{It's just an ordinary board. You can hardly use it.}
{201800}{}{a board}
{201801}{}{It's just an ordinary board. You can hardly use it.}
{201900}{}{a board}
{201901}{}{It's just an ordinary board. You can hardly use it.}
{202000}{}{a plant}
{202001}{}{An excellent representative of Herba Vulgaris.}
{202100}{}{a plant}
{202101}{}{An excellent representative of Herba Vulgaris.}
{202200}{}{a plant}
{202201}{}{Some kind of desert plant.}
{202300}{}{a plant}
{202301}{}{An excellent representative of Herba Vulgaris.}
{202400}{}{a plant}
{202401}{}{Some kind of desert plant.}
{202500}{}{a plant}
{202501}{}{An excellent representative of Herba Vulgaris.}
{202600}{}{a plant}
{202601}{}{Some kind of desert plant.}
{202700}{}{a plant}
{202701}{}{An excellent representative of Herba Vulgaris.}
{202800}{}{a plant}
{202801}{}{An excellent representative of Herba Vulgaris.}
{202900}{}{a plant}
{202901}{}{Some kind of desert plant.}
{203000}{}{a plant}
{203001}{}{Some kind of desert plant.}
{203100}{}{a plant}
{203101}{}{An excellent representative of Herba Vulgaris.}
{203200}{}{a plant}
{203201}{}{Some kind of desert plant.}
{203300}{}{a plant}
{203301}{}{An excellent representative of Herba Vulgaris.}
{203400}{}{a plant}
{203401}{}{Some kind of desert plant.}
{203500}{}{a plant}
{203501}{}{Some kind of desert plant.}
{203600}{}{a metal sheet}
{203601}{}{Rusty and very heavy.}
{203700}{}{a metal sheet}
{203701}{}{Rusty and very heavy.}
{203800}{}{a plant}
{203801}{}{An excellent representative of Herba Vulgaris.}
{203900}{}{a plant}
{203901}{}{An excellent representative of Herba Vulgaris.}
{204000}{}{a weather vane}
{204001}{}{Flags are showing wind direction.}
{204100}{}{a stake with a skull}
{204101}{}{You really wouldn't want to end up like that.}
{204200}{}{a stake with a skull}
{204201}{}{A frightening sign.}
{204300}{}{a stake with a skull}
{204301}{}{You take a closer look. Looks like this poor guy had cavities.}
{204400}{}{a stake with a skull}
{204401}{}{Someone has taken up residence in this skull.}
{204500}{}{a stake with a skull}
{204501}{}{You look at the skull and think "To be or not to be?"}
{204600}{}{a stake with a skull}
{204601}{}{Its empty eye sockets seem to be watching you.}
{204700}{}{a weather vane}
{204701}{}{Flags are showing wind direction.}
{204800}{}{a plant}
{204801}{}{Some kind of desert plant.}
{204900}{}{a plant}
{204901}{}{Some kind of desert plant.}
{205000}{}{the grass}
{205001}{}{A living green grass. You can hardly resist the temptation to chew on a blade of grass.}
{205100}{}{the grass}
{205101}{}{A living green grass. You can hardly resist the temptation to chew on a blade of grass.}
{205200}{}{a plant}
{205201}{}{A living herbaceous green plant.}
{205300}{}{a stake}
{205301}{}{Its diligently pointed end prompts in you a strong desire to keep your head on your shoulders.}
{205400}{}{a stake}
{205401}{}{You seem to guess its purpose.}
{205500}{}{a stake}
{205501}{}{You would hate to decorate your skull with this wonderful stake.}
{205600}{}{a stake}
{205601}{}{You seem to guess its purpose.}
{205700}{}{a stake}
{205701}{}{It seems to you that there is definitely something missing on this stake.}
{205800}{}{a stake}
{205801}{}{It's sharp. Looks menacing.}
{205900}{}{a stake}
{205901}{}{Someone obviously went through a lot of trouble to sharpen it.}
{206000}{}{a stake}
{206001}{}{It's sharp. Looks menacing.}
{206100}{}{a stake}
{206101}{}{It could easily stab you.}
{206200}{}{a stake}
{206201}{}{It's sharp. Looks menacing.}
{206300}{}{a blood}
{206301}{}{Dried bloody stain.}
{206400}{}{a blood}
{206401}{}{Dried bloody stain.}
{206500}{}{a blood}
{206501}{}{Looks pretty old.}
{206600}{}{a blood}
{206601}{}{Dried bloody stain.}
{206700}{}{a blood}
{206701}{}{Already dried and soaked.}
{206800}{}{a weather vane}
{206801}{}{The flag shows the direction of the wind.}
{206900}{}{a blood}
{206901}{}{You wonder whose blood this is.}
{207000}{}{a blood}
{207001}{}{These remains are several days old and smell like it.}
{207100}{}{a blood}
{207101}{}{These remains stink a lot.}
{207200}{}{a blood}
{207201}{}{Somebody was very unlucky.}
{207300}{}{a blood}
{207301}{}{You're looking at someone's inner world, and it's not the freshest.}
{207400}{}{a thing to practice beating on}
{207401}{}{It's better to practice moves on it than on real people.}
{207500}{}{a thing to practice beating on}
{207501}{}{What a face! You really want to punch it!}
{207600}{}{a thing to practice beating on}
{207601}{}{A great homemade mannequin for training.}
{207700}{}{a thing to practice beating on}
{207701}{}{Replaces the punching bag.}
{207800}{}{a thing to practice beating on}
{207801}{}{Looks like he gets it a lot.}
{207900}{}{a thing to practice beating on}
{207901}{}{The last thing you want in the world is to be in his shoes.}
{208000}{}{a blocked door}
{208001}{}{Exit blocked.}
{208100}{}{a rock}
{208101}{}{Looks impregnable.}
{208200}{}{a poster}
{208201}{}{A faded prewar poster.}
{208300}{}{a poster}
{208301}{}{A faded prewar poster.}
{208400}{}{a poster}
{208401}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{208500}{}{a poster}
{208501}{}{A faded prewar poster.}
{208600}{}{a poster}
{208601}{}{You like to look at old posters. They preserve history.}
{208700}{}{a poster}
{208701}{}{Did this propaganda inspire anyone?}
{208800}{}{a poster}
{208801}{}{A faded prewar poster.}
{208900}{}{a poster}
{208901}{}{Did this propaganda inspire anyone?}
{209000}{}{a poster}
{209001}{}{A faded prewar poster.}
{209100}{}{a poster}
{209101}{}{A faded prewar poster.}
{209200}{}{a poster}
{209201}{}{Did this propaganda inspire anyone?}
{209300}{}{a poster}
{209301}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{209400}{}{a poster}
{209401}{}{The poster man died a long time ago.}
{209500}{}{a poster}
{209501}{}{It looks like a movie commercial. Too bad you only read about movies in books.}
{209600}{}{a poster}
{209601}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{209700}{}{a poster}
{209701}{}{A pre-war propaganda poster.}
{209800}{}{a poster}
{209801}{}{A pre-war propaganda poster.}
{209900}{}{a poster}
{209901}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{210000}{}{a poster}
{210001}{}{Too bad you don't collect vintage posters - this is a fine one.}
{210100}{}{a poster}
{210101}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{210200}{}{a poster}
{210201}{}{A very old faded poster.}
{210300}{}{a poster}
{210301}{}{An old faded poster.}
{210400}{}{a poster}
{210401}{}{Too bad you don't collect vintage posters - this is a fine one.}
{210500}{}{a poster}
{210501}{}{It's at least 200 years old. Very well-preserved.}
{210600}{}{a poster}
{210601}{}{A faded prewar poster.}
{210700}{}{a poster}
{210701}{}{A faded prewar poster.}
{210800}{}{bones}
{210801}{}{A handful of someone's bones.}
{210900}{}{bones}
{210901}{}{Looks like ribs.}
{211000}{}{bones}
{211001}{}{You'll end up like this someday. The existence is futile.}
{211100}{}{bones}
{211101}{}{You'll end up like this someday. The existence is futile.}
{211200}{}{bones}
{211201}{}{A handful of someone's bones.}
{211300}{}{bones}
{211301}{}{A handful of someone's bones.}
{211400}{}{bones}
{211401}{}{You'll end up like this someday. The existence is futile.}
{211500}{}{bones}
{211501}{}{It was once something alive.}
{211600}{}{bones}
{211601}{}{A handful of someone's bones.}
{211700}{}{bones}
{211701}{}{It was once something alive.}
{211800}{}{a plant}
{211801}{}{Some kind of desert plant.}
{211900}{}{a plant}
{211901}{}{Some kind of desert plant.}
{212000}{}{a plant}
{212001}{}{Some kind of desert plant.}
{212100}{}{a plant}
{212101}{}{Some kind of desert plant.}
{212200}{}{a plant}
{212201}{}{Some kind of desert plant.}
{212300}{}{a plant}
{212301}{}{Some kind of desert plant.}
{212400}{}{a plant}
{212401}{}{Some kind of desert plant.}
{212500}{}{a plant}
{212501}{}{Some kind of desert plant.}
{212600}{}{a plant}
{212601}{}{Some kind of desert plant.}
{212700}{}{a plant}
{212701}{}{Some kind of desert plant.}
{212800}{}{a plant}
{212801}{}{Some kind of desert plant.}
{212900}{}{a plant}
{212901}{}{Some kind of desert plant.}
{213000}{}{a plant}
{213001}{}{Some kind of desert plant.}
{213100}{}{bones}
{213101}{}{There won't be much more left of you.}
{213200}{}{bones}
{213201}{}{A handful of someone's bones.}
{213300}{}{bones}
{213301}{}{There won't be much more left of you.}
{213400}{}{bones}
{213401}{}{Ordinary bones, there's a lot of them.}
{213500}{}{bones}
{213501}{}{Someone's dead.}
{213600}{}{bones}
{213601}{}{Someone's dead.}
{213700}{}{bones}
{213701}{}{Very old bones.}
{213800}{}{bones}
{213801}{}{These are the bones of the rarest extinct animal. Too bad you don't collect bones.}
{213900}{}{bones}
{213901}{}{A handful of someone's bones.}
{214000}{}{bones}
{214001}{}{Very old bones.}
{214100}{}{a stake}
{214101}{}{It's sharp. Looks menacing.}
{214200}{}{a stake}
{214201}{}{It's sharp. Looks menacing.}
{214300}{}{a stake}
{214301}{}{A pole sharpened at one end.}
{214400}{}{a stake}
{214401}{}{It's sharp. Looks menacing.}
{214500}{}{a stake}
{214501}{}{It's sharp. Looks menacing.}
{214600}{}{a stake}
{214601}{}{It's sharp. Looks menacing.}
{214700}{}{a stake}
{214701}{}{This one can pierce something.}
{214800}{}{a stake}
{214801}{}{This one can pierce something.}
{214900}{}{a broken stake}
{215000}{}{a broken stake}
{215100}{}{a blood}
{215101}{}{It's old dried blood.}
{215200}{}{a blood}
{215201}{}{Mother always told you that this liquid should be INSIDE, not outside.}
{215300}{}{a blood}
{215301}{}{Blood and sand.}
{215400}{}{a blood}
{215401}{}{Dried bloody stain.}
{215500}{}{a blood}
{215501}{}{Dried bloody stain.}
{215600}{}{a blood}
{215601}{}{Dried bloody stain.}
{215700}{}{a blood}
{215701}{}{You wonder whose blood it is.}
{215800}{}{a blood}
{215801}{}{Dried bloody stain.}
{215900}{}{a blood}
{215901}{}{Dried bloody stain.}
{216000}{}{a blood}
{216001}{}{Dried bloody stain.}
{216100}{}{bones}
{216101}{}{These are the bones of the rarest extinct animal. Too bad you don't collect bones.}
{216200}{}{bones}
{216201}{}{Someone's dead.}
{216300}{}{bones}
{216301}{}{These bones are of no interest to you. Unless you're an osteologist, of course.}
{216400}{}{a skull}
{216401}{}{It looks like it was some kind of animal.}
{216500}{}{bones}
{216501}{}{They seem to be very fragile.}
{216600}{}{a blood}
{216601}{}{Dried bloody stain.}
{216700}{}{a blood}
{216701}{}{Red blood, white bones - a beautiful combination of colors.}
{216800}{}{a blood}
{216801}{}{You wonder who that blood belonged to.}
{216900}{}{a blood}
{216901}{}{Dried bloody stain.}
{217000}{}{a blood}
{217001}{}{You wonder who that blood belonged to.}
{217100}{}{a shack}
{217101}{}{It reeks of blood and urine.}
{217200}{}{a shack}
{217201}{}{And on the deserted shores stand dwellings here and there, the shelter of the wretched aborigine.}
{217300}{}{a shack}
{217301}{}{You don't want to go in there at all.}
{217400}{}{a shack}
{217401}{}{A structure of wood and dry grass.}
{217500}{}{a plant}
{217501}{}{Some kind of desert plant.}
{217600}{}{a plant}
{217601}{}{Some kind of desert plant.}
{217700}{}{a plant}
{217701}{}{Some kind of desert plant.}
{217800}{}{a plant}
{217801}{}{Some kind of desert plant.}
{217900}{}{a plant}
{217901}{}{Some kind of desert plant.}
{218000}{}{a plant}
{218001}{}{Some kind of desert plant.}
{218100}{}{a plant}
{218101}{}{Some kind of desert plant.}
{218200}{}{a plant}
{218201}{}{Some kind of desert plant.}
{218300}{}{a plant}
{218301}{}{Some kind of desert plant.}
{218400}{}{a plant}
{218401}{}{Some kind of desert plant.}
{218500}{}{a catch}
{218501}{}{Big fish here! Looks quite edible.}
{218600}{}{a tree}
{218601}{}{The trunk of a dried-out tree.}
{218700}{}{a tree}
{218701}{}{This tree can no longer be helped.}
{218800}{}{a tree}
{218801}{}{This tree looks like a carrot. An old dried gray carrot.}
{218900}{}{a tree}
{218901}{}{These dry branches are depressing.}
{219000}{}{a tree}
{219001}{}{The dry, broken trunk of a dried-up tree.}
{219100}{}{a sign}
{219101}{}{Food, water - looks like a place to eat!}
{219200}{}{a billiard table}
{219201}{}{You don't really understand how to play it, but the fabric on the table looks very worn.}
{219300}{}{a billiard table}
{219301}{}{The colored balls on the table look fun, too bad you don't know how to play.}
{219400}{}{a screen panel}
{219401}{}{Unfortunately, it's turned off. To look at the working one would be extremely interesting.}
{219500}{}{a wall}
{219600}{}{a sofa}
{219601}{}{A piece of furniture that can provide your heel with maximum comfort.}
{219700}{}{a sofa}
{219701}{}{Looks comfortable, no time to rest here.}
{219800}{}{the screens}
{219801}{}{You wonder what can be watched on so many screens. Right now there's just white noise.}
{219900}{}{a poster}
{219901}{}{An old poster advertising a gun. No one would say no a gun like that, even now!}
{220000}{}{the stairs up}
{220100}{}{the stairs down}
{220200}{}{a poster}
{220201}{}{A faded old poster.}
{220300}{}{a poster}
{220301}{}{This poster is at least two hundred years old. They used to make pretty good ones back in the day!}
{220400}{}{a poster}
{220401}{}{They don't make them like that now.}
{220500}{}{a poster}
{220501}{}{You study the poster for a while. It looks like an advertisement for canned goods.}
{220600}{}{a poster}
{220601}{}{You like old posters. They preserve history.}
{220700}{}{a poster}
{220701}{}{A faded wall poster.}
{220800}{}{a poster}
{220801}{}{This poster is at least two hundred years old. They used to make pretty good ones back in the day!}
{220900}{}{a poster}
{220901}{}{Life before the war was very different.}
{221000}{}{a poster}
{221001}{}{Huge old poster.}
{221100}{}{a poster}
{221101}{}{Be ready to strike.}
{221200}{}{a poster}
{221201}{}{The colors are blurred and faded.}
{221300}{}{a poster}
{221301}{}{You like old posters. They preserve history.}
{221400}{}{a tile}
{221500}{}{a tile}
{221600}{}{a tile}
{221700}{}{a tile}
{221800}{}{a tile}
{221900}{}{a tile}
{222000}{}{a tile}
{222100}{}{a board}
{222101}{}{Just an ordinary plaque. Nothing interesting.}
{222200}{}{a board}
{222201}{}{Just an ordinary plaque. Nothing interesting.}
{222300}{}{a board}
{222301}{}{Just an ordinary plaque. Nothing interesting.}
{222400}{}{a board}
{222401}{}{Just an ordinary plaque. Nothing interesting.}
{222500}{}{a board}
{222501}{}{Just an ordinary plaque. Nothing interesting.}
{222600}{}{a board}
{222601}{}{Just an ordinary plaque. Nothing interesting.}
{222700}{}{a board}
{222701}{}{Just an ordinary plaque. Nothing interesting.}
{222800}{}{a board}
{228101}{}{Mom told you not to eat unfamiliar stuff.}
{222900}{}{a board}
{222901}{}{Just an ordinary plaque. Nothing interesting.}
{223000}{}{a board}
{223001}{}{Just an ordinary plaque. Nothing interesting.}
{223100}{}{a board}
{223101}{}{Just an ordinary plaque. Nothing interesting.}
{223200}{}{a board}
{223201}{}{Just an ordinary plaque. Nothing interesting.}
{223300}{}{a board}
{223301}{}{Just an ordinary plaque. Nothing interesting.}
{223400}{}{a board}
{223401}{}{Just an ordinary plaque. Nothing interesting.}
{223500}{}{a board}
{223501}{}{Just an ordinary plaque. Nothing interesting.}
{223600}{}{a rusty piece of metal}
{223601}{}{What do you need it for?}
{223700}{}{a rusty piece of metal}
{223701}{}{It's completely useless.}
{223800}{}{a rusty piece of metal}
{223801}{}{You examine it carefully, but it doesn't make it any more useful.}
{223900}{}{a junk}
{223901}{}{Even the last vagabond wouldn't go for this junk.}
{224000}{}{a junk}
{224001}{}{Absolutely useless junk.}
{224100}{}{a junk}
{224101}{}{You won't find any use for this junk.}
{224200}{}{a junk}
{224201}{}{Nothing of interest.}
{224300}{}{a rusty piece of metal}
{224301}{}{It won't be of any use to you, that's for sure.}
{224400}{}{a rusty piece of metal}
{224401}{}{It's completely useless.}
{224500}{}{a rusty piece of metal}
{224501}{}{Let it rust.}
{224600}{}{a junk}
{224601}{}{You don't want to collect any junk, do you?}
{224700}{}{a junk}
{224701}{}{Even the last vagabond wouldn't go for this junk.}
{224800}{}{a junk}
{224801}{}{You won't find any use for this junk.}
{224900}{}{a junk}
{224901}{}{You don't want to collect any junk, do you?}
{224601}{}{You don't want to collect any junk, do you?}
{225000}{}{a door}
{225001}{}{This door is securely boarded up.}
{225100}{}{a bed}
{225101}{}{It's not worth the risk of laying down on it.}
{225200}{}{a bed}
{225201}{}{It's completely rotten.}
{225300}{}{a bed}
{225301}{}{What's crawling around there?}
{225400}{}{a wall}
{225500}{}{a wall}
{225600}{}{a wall}
{225700}{}{a wall}
{225800}{}{a wall}
{225900}{}{the stones}
{226000}{}{the stones}
{226100}{}{the stones}
{226200}{}{the stones}
{226300}{}{the stones}
{226400}{}{the stones}
{226500}{}{the stones}
{226600}{}{the stones}
{226700}{}{the stones}
{226800}{}{the stones}
{226900}{}{the stones}
{227000}{}{the stones}
{227100}{}{a junk}
{227101}{}{A useless pile of junk.}
{227200}{}{a metal sheet}
{227201}{}{Is that blood?}
{227300}{}{a junk}
{227301}{}{Even the last vagabond wouldn't go for this junk.}
{227400}{}{a metal sheet}
{227401}{}{It's rusty heavy and completely useless.}
{227500}{}{a metal sheet}
{227501}{}{Even the last vagabond wouldn't go for this junk.}
{227600}{}{a metal sheet}
{227601}{}{You don't want to collect any junk, do you?}
{227700}{}{a metal sheet}
{227701}{}{It's all rusted out.}
{227800}{}{a metal sheet}
{227801}{}{A useless pile of junk.}
{227900}{}{a crate}
{227901}{}{It's a nice big box, but there's nothing interesting in there.}
{228000}{}{a crate}
{228001}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{228100}{}{a cave mushroom}
{228101}{}{Mom told you not to eat unfamiliar stuff.}
{228200}{}{a cave mushroom}
{228201}{}{Mom told you not to eat unfamiliar stuff.}
{228300}{}{a cave mushroom}
{228301}{}{Mom told you not to eat unfamiliar stuff.}
{228400}{}{a cave mushroom}
{228401}{}{Mom told you not to eat unfamiliar stuff.}
{228500}{}{a cave mushroom}
{228501}{}{Mom told you not to eat unfamiliar stuff.}
{228600}{}{a cave mushroom}
{228601}{}{Mom told you not to eat unfamiliar stuff.}
{228700}{}{a cave mushroom}
{228701}{}{Mom told you not to eat unfamiliar stuff.}
{228800}{}{a cave mushroom}
{228801}{}{Mom told you not to eat unfamiliar stuff.}
{228900}{}{a cave mushroom}
{228901}{}{Mom told you not to eat unfamiliar stuff.}
{229000}{}{a cave mushroom}
{229001}{}{Mom told you not to eat unfamiliar stuff.}
{229100}{}{a metal sheet}
{229101}{}{It's nice and hardly crumpled, but you won't need it.}
{229200}{}{a metal sheet}
{229201}{}{Completely useless to you.}
{229300}{}{a metal sheet}
{229301}{}{Rusty and crumpled tin sheet.}
{229400}{}{a cave wall}
{229500}{}{a cave wall}
{229600}{}{the stones}
{229700}{}{a part of a wall}
{229800}{}{a part of a wall}
{229900}{}{a part of a wall}
{230000}{}{a part of a wall}
{230100}{}{a destroyed column}
{230200}{}{a destroyed column}
{230300}{}{a destroyed column}
{230400}{}{a destroyed column}
{230500}{}{a sign}
{230501}{}{The paint is cracked, and the letters are illegible.}
{230600}{}{a sign}
{230601}{}{The paint is cracked, and the letters are illegible.}
{230700}{}{a large hole in the floor}
{230701}{}{A crater from an explosion. Only debris and rocks lie below.}
{230800}{}{a bed}
{230801}{}{It's better to hold your breath next to that bed - it stinks.}
{230900}{}{a bed}
{230901}{}{What's crawling around there?}
{231000}{}{a bed}
{231001}{}{Dust and mildew. It's not pleasant even to stand on it.}
{231100}{}{a metal sheet}
{231101}{}{An old rusty sheet of tin.}
{231200}{}{a metal sheet}
{231201}{}{You don't need that tin can junk.}
{231300}{}{a metal sheet}
{231301}{}{Useless tin.}
{231400}{}{a poster}
{231401}{}{A huge faded poster of TIN Industries.}
{231500}{}{the tile shards}
{231501}{}{Thousands of them! And each one is unique in its own way.}
{231600}{}{the tile shards}
{231601}{}{Thousands of them! And each one is unique in its own way.}
{231700}{}{the tile shards}
{231701}{}{Thousands of them! And each one is unique in its own way.}
{231800}{}{the tile shards}
{231801}{}{Thousands of them! And each one is unique in its own way.}
{231900}{}{the tile shards}
{231901}{}{Thousands of them! And each one is unique in its own way.}
{232000}{}{the tile shards}
{232001}{}{Thousands of them! And each one is unique in its own way.}
{232100}{}{the tile shards}
{232101}{}{Thousands of them! And each one is unique in its own way.}
{232200}{}{the tile shards}
{232201}{}{Thousands of them! And each one is unique in its own way.}
{232300}{}{the tile shards}
{232301}{}{Thousands of them! And each one is unique in its own way.}
{232400}{}{the tile shards}
{232401}{}{Thousands of them! And each one is unique in its own way.}
{232500}{}{the tile shards}
{232501}{}{Thousands of them! And each one is unique in its own way.}
{232600}{}{the tile shards}
{232601}{}{Thousands of them! And each one is unique in its own way.}
{232700}{}{the tile shards}
{232701}{}{Thousands of them! And each one is unique in its own way.}
{232800}{}{the tile shards}
{232801}{}{Thousands of them! And each one is unique in its own way.}
{232900}{}{the tile shards}
{232901}{}{Thousands of them! And each one is unique in its own way.}
{233000}{}{a bed}
{233001}{}{You don't want to lie down on this filthy recline at all.}
{233100}{}{a junk}
{233101}{}{It's better not to touch it.}
{233200}{}{a junk}
{233201}{}{Totally useless thing.}
{233300}{}{a factory wall}
{233400}{}{a factory wall}
{233500}{}{a part of a wall}
{233600}{}{a part of a wall}
{233700}{}{a part of a wall}
{233800}{}{a part of a wall}
{233900}{}{a poster}
{233901}{}{It's very old.}
{234000}{}{a poster}
{234001}{}{You look at it for a while. You definitely like old posters.}
{234100}{}{a poster}
{234101}{}{It looks very patriotic.}
{234200}{}{a wall}
{234300}{}{a poster}
{234301}{}{You wish there had been a poster like this hanging over your bed when you were a kid.}
{234400}{}{a poster}
{234401}{}{Seems like mold has settled on it.}
{234500}{}{a poster}
{234501}{}{A faded wall poster.}
{234600}{}{a wall}
{234700}{}{a wall}
{234800}{}{a car}
{234801}{}{A massive excavating machine.}
{234900}{}{a car}
{234901}{}{A massive excavating machine.}
{235000}{}{a junk}
{235001}{}{Rusty iron. This junk is not worth your attention.}
{235100}{}{a sheet of rusty iron}
{235101}{}{Makes a funny sound when you knock on it.}
{235200}{}{a junk}
{235201}{}{Rusty iron. This junk is not worth your attention.}
{235300}{}{a sheet of rusty iron}
{235301}{}{Too heavy. Unlikely to be of any use to you.}
{235400}{}{a sheet of rusty iron}
{235401}{}{Too heavy. Unlikely to be of any use to you.}
{235500}{}{a junk}
{235501}{}{Not worth wasting your time on this piece of junk.}
{235600}{}{a junk}
{235601}{}{It's just useless junk now.}
{235700}{}{a junk}
{235701}{}{It's just useless junk now.}
{235800}{}{a junk}
{235801}{}{It's not worth picking up any junk.}
{235900}{}{a junk}
{235901}{}{Utterly useless trash.}
{236000}{}{rocks}
{236001}{}{Look impregnable.}
{236100}{}{rocks}
{236101}{}{Look impregnable.}
{236200}{}{rocks}
{236201}{}{Look impregnable.}
{236300}{}{a board}
{236301}{}{An unremarkable board.}
{236400}{}{the sheet of iron}
{236401}{}{Makes a funny sound when you knock on it.}
{236500}{}{the sheet of iron}
{236501}{}{Too heavy.}
{236600}{}{the sheet of iron}
{236601}{}{There is absolutely no use for you in it.}
{236700}{}{the sheet of iron}
{236701}{}{It looks sturdy, but it's useless.}
{236800}{}{a junk}
{236801}{}{This junk is useless.}
{236900}{}{a junk}
{236901}{}{This junk is useless.}
{237000}{}{a junk}
{237001}{}{This junk is useless.}
{237100}{}{a junk}
{237101}{}{Utterly useless trash.}
{237200}{}{a junk}
{237201}{}{Don't waste your time with all kinds of useless junk.}
{237300}{}{a junk}
{237301}{}{Just regular trash.}
{237400}{}{a junk}
{237401}{}{It won't be of any use to you, that's for sure.}
{237500}{}{a junk}
{237501}{}{Not of any interest to you, unless you are heavily into trash collecting.}
{237600}{}{a junk}
{237601}{}{Not of any interest to you, unless you are heavily into trash collecting.}
{237700}{}{tools}
{237701}{}{These tools are not usable.}
{237800}{}{a box}
{237801}{}{An empty old box is completely useless.}
{237900}{}{a junk}
{237901}{}{Utterly useless trash.}
{238000}{}{a junk}
{238001}{}{Utterly useless trash.}
{238100}{}{a junk}
{238101}{}{Utterly useless trash.}
{238200}{}{a poster}
{238201}{}{An old faded "Olympus" poster.}
{238300}{}{the lights}
{238400}{}{the lights}
{238500}{}{a box}
{238501}{}{An old empty box.}
{238600}{}{a box}
{238601}{}{An old empty box.}
{238700}{}{a box}
{238701}{}{An old empty box.}
{238800}{}{a box}
{238801}{}{An old empty box.}
{238900}{}{an old box}
{238901}{}{There is nothing but trash in this dirty box.}
{239000}{}{an old box}
{239001}{}{There is nothing but trash in this dirty box.}
{239100}{}{an old box}
{239101}{}{There is nothing but trash in this dirty box.}
{239200}{}{an old box}
{239201}{}{There is nothing but trash in this dirty box.}
{239300}{}{an old box}
{239301}{}{There is nothing but trash in this dirty box.}
{239400}{}{an old box}
{239401}{}{There is nothing but trash in this dirty box.}
{239500}{}{an old box}
{239501}{}{There is nothing but trash in this dirty box.}
{239600}{}{an old box}
{239601}{}{Its contents may have been of interest, but that was a long time ago.}
{239700}{}{an old box}
{239701}{}{Its contents may have been of interest, but that was a long time ago.}
{239800}{}{an old box}
{239801}{}{Its contents may have been of interest, but that was a long time ago.}
{239900}{}{an old box}
{239901}{}{Its contents may have been of interest, but that was a long time ago.}
{240000}{}{an old box}
{240001}{}{A rusty metal box, very heavy and empty.}
{240100}{}{an old box}
{240101}{}{Its contents may have been of interest, but that was a long time ago.}
{240200}{}{a junk}
{240201}{}{The lid of the box. Not likely to be of any use to you.}
{240300}{}{a junk}
{240301}{}{The lid of the box. Not likely to be of any use to you.}
{240400}{}{an old box}
{240401}{}{Tattered on the outside with useless contents inside. Just like some people.}
{240500}{}{an old box}
{240501}{}{Tattered on the outside with useless contents inside. Just like some people.}
{240600}{}{an old box}
{240601}{}{Tattered on the outside with useless contents inside. Just like some people.}
{240700}{}{an old box}
{240701}{}{Only ancient junk and dust inside.}
{240800}{}{an old box}
{240801}{}{Only ancient junk and dust inside.}
{240900}{}{an old box}
{240901}{}{Only ancient junk and dust inside.}
{241000}{}{an old box}
{241001}{}{Only ancient junk and dust inside.}
{241100}{}{an old cupboard}
{241101}{}{There's nothing in here. Looks like someone went through it before you did.}
{241200}{}{an old cupboard}
{241201}{}{There's nothing in here. Looks like someone went through it before you did.}
{241300}{}{an old box}
{241301}{}{Only ancient junk and dust inside.}
{241400}{}{an old box}
{241401}{}{Only ancient junk and dust inside.}
{241500}{}{an old box}
{241501}{}{Its contents may have been of interest, but that was a long time ago.}
{241600}{}{a barrier}
{241601}{}{A small portable fence.}
{241700}{}{a barrier}
{241701}{}{A small portable fence.}
{241800}{}{a barrier}
{241801}{}{A small portable fence.}
{241900}{}{an old box}
{241901}{}{Tattered on the outside with useless contents inside. Just like some people.}
{242000}{}{an old box}
{242001}{}{Tattered on the outside with useless contents inside. Just like some people.}
{242100}{}{a container}
{242101}{}{Sturdy, rusty container.}
{242200}{}{a crate}
{242201}{}{Nothing useful in it.}
{242300}{}{a crate}
{242301}{}{Nothing useful in it.}
{242400}{}{a wall}
{242500}{}{a wall}
{242600}{}{a column}
{242700}{}{a column}
{242800}{}{a column}
{242900}{}{a column}
{243000}{}{the lights}
{243001}{}{Lights up the area around it.}
{243100}{}{the lights}
{243101}{}{Lights up the area around it.}
{243200}{}{a wall}
{243300}{}{a wall}
{243400}{}{a column}
{243500}{}{a wall}
{243600}{}{a wall}
{243700}{}{a column}
{243800}{}{a wall}
{243900}{}{a wall}
{244000}{}{a painting}
{244001}{}{Looks real and well preserved.}
{244100}{}{a painting}
{244101}{}{For several minutes you study the painting. Art is fascinating.}
{244200}{}{a painting}
{244201}{}{A portrait of a man. Your manly face would also look good on a portrait in a gold frame.}
{244300}{}{a void}
{244400}{}{a void}
{244500}{}{a bench}
{244501}{}{This is not a good time to rest.}
{244600}{}{a bench}
{244601}{}{Four legs, a long seat, a back - it's a bench!}
{244700}{}{a bench}
{244701}{}{This is not a good time to rest.}
{244800}{}{a bench}
{244801}{}{Four legs, a long seat, a back - it's a bench!}
{244900}{}{an old box}
{244901}{}{You look inside - it's empty.}
{245000}{}{a junk}
{245001}{}{It's completely useless junk.}
{245100}{}{a junk}
{245101}{}{It's completely useless junk.}
{245200}{}{a junk}
{245201}{}{It's completely useless junk.}
{245300}{}{an old box}
{245301}{}{You examine the contents. There's nothing but garbage. You are covered in rust.}
{245400}{}{a rusty iron}
{245401}{}{Not even the last vagrant would be interested in this junk.}
{245500}{}{a rusty iron}
{245501}{}{Not even the last vagrant would be interested in this junk.}
{245600}{}{a rusty iron}
{245601}{}{Not even the last vagrant would be interested in this junk.}
{245700}{}{an old box}
{245701}{}{Looks like someone's been through it and blooded it up.}
{245800}{}{a junk}
{245801}{}{It's completely useless junk.}
{245900}{}{a junk}
{245901}{}{It's completely useless junk.}
{246000}{}{a junk}
{246001}{}{It's completely useless junk.}
{246100}{}{a junk}
{246101}{}{It's completely useless junk.}
{246200}{}{a junk}
{246201}{}{It's completely useless junk.}
{246300}{}{a junk}
{246301}{}{It's completely useless junk.}
{246400}{}{a junk}
{246401}{}{It's completely useless junk.}
{246500}{}{an old box}
{246501}{}{Its contents may have been of interest, but that was a long time ago.}
{246600}{}{an old box}
{246601}{}{Its contents may have been of interest, but that was a long time ago.}
{246700}{}{a crate}
{246701}{}{There's nothing inside. Looks like someone went through it before you did.}
{246800}{}{a crate}
{246801}{}{There's nothing inside. Looks like someone went through it before you did.}
{246900}{}{a painting}
{246901}{}{Something abstract and incomprehensible. You like the frame more than the painting.}
{247000}{}{an old painting}
{247001}{}{An interesting landscape. You realize you will never see it in reality.}
{247100}{}{a painting}
{247101}{}{For several minutes you study the painting. Real art is fascinating.}
{247200}{}{a painting}
{247201}{}{An interesting landscape. You realize you will never see it in reality.}
{247300}{}{a painting}
{247301}{}{For several minutes you study the painting. Real art is fascinating.}
{247400}{}{a painting}
{247401}{}{Something clearly edible and very important, since people have deemed this food worthy of a gold frame.}
{247500}{}{a painting}
{247501}{}{Something clearly edible and very important, since people have deemed this food worthy of a gold frame.}
{247600}{}{a painting}
{247601}{}{Something abstract and incomprehensible. You like the frame more than the painting.}
{247700}{}{a blocked staircase}
{247701}{}{The way up is blocked.}
{247800}{}{a painting}
{247801}{}{An interesting landscape. You realize you will never see it in reality.}
{247900}{}{a painting}
{247901}{}{Something clearly edible and very important, since people have deemed this food worthy of a gold frame.}
{248000}{}{a blocked staircase}
{248001}{}{The passage is blocked.}
{248100}{}{a elevator}
{248101}{}{Service elevator leading to Tartarus.}
{248200}{}{a bed}
{248201}{}{This bed is perfectly preserved.}
{248300}{}{a bed}
{248301}{}{This bed is perfectly preserved.}
{248400}{}{a bed}
{248401}{}{This bed is perfectly preserved.}
{248500}{}{a bed}
{248501}{}{This bed is perfectly preserved.}
{248600}{}{an armchair}
{248601}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{248700}{}{an armchair}
{248701}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{248800}{}{an armchair}
{248801}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{248900}{}{an armchair}
{248901}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{249000}{}{an armchair}
{249001}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249100}{}{an armchair}
{249101}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249200}{}{an armchair}
{249201}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249300}{}{an armchair}
{249301}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249400}{}{a leather sofa}
{249401}{}{You had no idea how comfortable furniture can be.}
{249500}{}{a leather sofa}
{249501}{}{You had no idea how comfortable furniture can be.}
{249600}{}{a leather sofa}
{249601}{}{You had no idea how comfortable furniture can be.}
{249700}{}{a leather sofa}
{249701}{}{You had no idea how comfortable furniture can be.}
{249800}{}{a leather sofa}
{249801}{}{Now you know what "expensive furniture" means.}
{249900}{}{a leather sofa}
{249901}{}{Now you know what "expensive furniture" means.}
{250000}{}{a leather sofa}
{250001}{}{Now you know what "expensive furniture" means.}
{250100}{}{a leather sofa}
{250101}{}{Now you know what "expensive furniture" means.}
{250200}{}{a column}
{250201}{}{A fine example of neoclassical architecture.}
{250300}{}{a hotel counter}
{250301}{}{Keys and old letters are still in it.}
{250400}{}{a column}
{250401}{}{A fine example of neoclassical architecture.}
{250500}{}{a counter}
{250501}{}{The "Horton Hotel" signposted counter.}
{250600}{}{a counter}
{250601}{}{The "Horton Hotel" signposted counter.}
{250700}{}{a counter}
{250701}{}{The "Horton Hotel" signposted counter.}
{250800}{}{the stairs up}
{250801}{}{This stairway leads to the upper floor.}
{250900}{}{a wall}
{251000}{}{a wall}
{251100}{}{a wall}
{251200}{}{the stairs down}
{251201}{}{This stairway leads to the lower floor.}
{251300}{}{the stairs}
{251301}{}{This stairway leads to the upper floor.}
{251400}{}{the stairs}
{251401}{}{This stairway leads to the upper floor.}
{251500}{}{the stairs}
{251501}{}{This stairway leads to the lower floor.}
{251600}{}{the blocked staircase}
{251601}{}{Passages to the upper and lower floors are blocked.}
{251700}{}{a generator}
{251701}{}{A device that generates electricity.}
{251800}{}{a big generator}
{251801}{}{It generates power for the tower.}
{251900}{}{a big generator}
{251901}{}{It generates power for the tower.}
{252000}{}{a trailer with stuff}
{252001}{}{Made from the trunk of a car.}
{252100}{}{a trailer with stuff}
{252101}{}{The craftsmen seem to have converted the trunk of a car into a trailer.}
{252200}{}{a floor}
{252201}{}{Digital markings on the floor.}
{252300}{}{a floor}
{252301}{}{Digital markings on the floor.}
{252400}{}{a floor}
{252401}{}{Digital markings on the floor.}
{252500}{}{a floor}
{252501}{}{Digital markings on the floor.}
{252600}{}{a floor}
{252601}{}{Digital markings on the floor.}
{252700}{}{a floor}
{252701}{}{Alphabetic markings on the floor.}
{252800}{}{a floor}
{252801}{}{Alphabetic markings on the floor.}
{252900}{}{a floor}
{252901}{}{Alphabetic markings on the floor.}
{253000}{}{a floor}
{253001}{}{Alphabetic markings on the floor.}
{253100}{}{a clogged door}
{253101}{}{You won't get through.}
{253200}{}{a table}
{253201}{}{Medical table.}
{253300}{}{a table}
{253301}{}{Medical table.}
{253400}{}{a table}
{253401}{}{Medical table.}
{253500}{}{an electrical panel}
{253501}{}{An element of the hotel's electrical system.}
{253600}{}{the Olympus}
{253601}{}{Here it is! The Olympus, abode of all hopefuls.}
{253700}{}{the Olympus}
{253701}{}{Here it is! The Olympus, abode of all hopefuls.}
{253800}{}{the Olympus}
{253801}{}{Here it is! The Olympus, abode of all hopefuls.}
{253900}{}{the Olympus}
{253901}{}{Here it is! The Olympus, abode of all hopefuls.}
{254000}{}{the Olympus}
{254001}{}{Here it is! The Olympus, abode of all hopefuls.}
{254100}{}{the Olympus}
{254101}{}{Here it is! The Olympus, abode of all hopefuls.}
{254200}{}{the Olympus}
{254201}{}{Here it is! The Olympus, abode of all hopefuls.}
{254300}{}{the Olympus}
{254301}{}{Here it is! The Olympus, abode of all hopefuls.}
{254400}{}{the Olympus}
{254401}{}{Here it is! The Olympus, abode of all hopefuls.}
{254500}{}{the Olympus}
{254501}{}{Here it is! The Olympus, abode of all hopefuls.}
{254600}{}{the Olympus}
{254601}{}{Here it is! The Olympus, abode of all hopefuls.}
{254700}{}{the Olympus}
{254701}{}{Here it is! The Olympus, abode of all hopefuls.}
{254800}{}{the Olympus}
{254801}{}{Here it is! The Olympus, abode of all hopefuls.}
{254900}{}{a elevator}
{254901}{}{It seems to be the only way to move around the floors of the tower.}
{255000}{}{a elevator}
{255001}{}{It seems to be the only way to move around the floors of the tower.}
{255100}{}{the Olympus}
{255101}{}{Here it is! The Olympus, abode of all hopefuls.}
{255200}{}{the Olympus}
{255201}{}{Here it is! The Olympus, abode of all hopefuls.}
{255300}{}{the Olympus}
{255301}{}{Here it is! The Olympus, abode of all hopefuls.}
{255400}{}{a metal archway}
{255401}{}{Rusty, but still strong.}
{255500}{}{a metal archway}
{255500}{}{a metal archway}
{255600}{}{a shadow}
{255700}{}{a coffee machine}
{255701}{}{You press the button and nothing happen. It seems to be broken.}
{255800}{}{a coffee machine}
{255701}{}{You press the button and nothing happen. It seems to be broken.}
{255900}{}{a stove}
{255901}{}{An ordinary household oven.}
{256000}{}{a monument}
{256001}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256100}{}{a monument}
{256101}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256200}{}{a monument}
{256201}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256300}{}{a monument}
{256301}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256400}{}{a boxes}
{256401}{}{These boxes are empty, there is nothing to eat here.}
{256500}{}{a boxes}
{256501}{}{These boxes are empty, there is nothing to eat here.}
{256600}{}{a boxes}
{256601}{}{These boxes are empty, there is nothing to eat here.}
{256700}{}{a table}
{256701}{}{Medical table.}
{256800}{}{a table}
{256801}{}{Medical table.}
{256900}{}{a boxes}
{256901}{}{So many boxes and absolutely nothing useful - what a disappointment!}
{257000}{}{a boxes}
{257001}{}{So many boxes and absolutely nothing useful - what a disappointment!}
{257100}{}{a boxes}
{257101}{}{These boxes are empty, there is nothing to eat here.}
{257200}{}{a elevator}
{257201}{}{The elevator doors.}
{257300}{}{a elevator}
{257301}{}{It seems to be the only way to move around the floors of the tower.}
{257400}{}{a elevator}
{257401}{}{The elevator doors.}
{257500}{}{a elevator}
{257501}{}{The elevator doors.}
{257600}{}{an armor plate}
{257601}{}{Probably protects the back wall from the spraying insides of the test subjects.}
{257700}{}{a generator}
{257701}{}{A device that generates electricity.}
{257800}{}{blocked elevator entrance}
{257801}{}{You won't get through.}
{257900}{}{a battery}
{257901}{}{Backup power source.}
{258000}{}{a table}
{258001}{}{Judging by the tools, this is the engineer's desk.}
{258100}{}{a table}
{258101}{}{Judging by the tools, this is the engineer's desk.}
{258200}{}{a table}
{258201}{}{This is the biggest desk you have ever seen.}
{258300}{}{a table}
{258301}{}{This is the biggest desk you have ever seen.}
{258400}{}{a boxes}
{258401}{}{These boxes are empty, there is nothing to eat here.}
{258500}{}{a boxes}
{258501}{}{These boxes are empty, there is nothing to eat here.}
{258600}{}{a wall}
{258700}{}{a wall}
{258800}{}{a junk}
{258801}{}{It's completely useless junk.}
{258900}{}{a junk}
{258901}{}{It's completely useless junk.}
{259000}{}{a junk}
{259001}{}{It's completely useless junk.}
{259100}{}{an old car}
{259101}{}{This bucket of nuts is definitely unable to ride.}
{259200}{}{a beam}
{259201}{}{Supporting structure.}
{259300}{}{a beam}
{259301}{}{Supporting structure.}
{259400}{}{a beam}
{259401}{}{Supporting structure.}
{259500}{}{a beam}
{259501}{}{Supporting structure.}
{259600}{}{a beam}
{259601}{}{Supporting structure.}
{259700}{}{a beam}
{259701}{}{Supporting structure.}
{259800}{}{a beam}
{259801}{}{Supporting structure.}
{259900}{}{a beam}
{259901}{}{Supporting structure.}
{260000}{}{a beam}
{260001}{}{Supporting structure.}
{260100}{}{a beam}
{260101}{}{Supporting structure.}
{260200}{}{a beam}
{260201}{}{Supporting structure.}
{260300}{}{a beam}
{260301}{}{Supporting structure.}
{260400}{}{a wall}
{260500}{}{a wall}
{260600}{}{a wall}
{260700}{}{a wall}
{260800}{}{a wall}
{260900}{}{a wall}
{261000}{}{a vent}
{261001}{}{Ventilation grille.}
{261100}{}{a vent}
{261101}{}{Dirty ventilation grill.}
{261200}{}{a vent}
{261201}{}{Ventilation grille.}
{261300}{}{a vent}
{261301}{}{Dirty ventilation grill.}
{261400}{}{an old box}
{261401}{}{Its contents may have been of interest, but that was a long time ago.}
{261500}{}{a junk}
{261501}{}{Hardly anyone can find a use for this junk.}
{261600}{}{a junk}
{261601}{}{Hardly anyone can find a use for this junk.}
{261700}{}{a bunk}
{261701}{}{A hospital bed with a monitor.}
{261800}{}{a wall}
{261900}{}{a wall}
{262000}{}{a wall}
{262100}{}{a wall}
{262200}{}{a bin}
{262201}{}{A bin, full of garbage.}
{262300}{}{a box}
{262301}{}{Nothing interesting - just useless junk.}
{262400}{}{a pipe}
{262401}{}{An element of Olympus' communication systems.}
{262500}{}{a huge machine}
{262501}{}{The sign says: "Cloning machine".}
{262600}{}{a huge machine}
{262601}{}{The sign says: "Cloning machine".}
{262700}{}{a metal plate}
{262701}{}{Highly unlikely to be of any use to you.}
{262800}{}{a metal plate}
{262801}{}{Highly unlikely to be of any use to you.}
{262900}{}{a metal plate}
{262901}{}{Highly unlikely to be of any use to you.}
{263000}{}{a box}
{263001}{}{Full box of junk, and not a single useful item.}
{263100}{}{a box}
{263101}{}{Full box of junk, and not a single useful item.}
{263200}{}{a box}
{263201}{}{Full box of junk, and not a single useful item.}
{263300}{}{a crate}
{263301}{}{Sturdy and reliable, but completely empty.}
{263400}{}{a junk}
{263401}{}{Hardly anyone can find a use for this junk.}
{263500}{}{a wall}
{263600}{}{a wall}
{263700}{}{a wall}
{263800}{}{a wall}
{263900}{}{a loudspeaker}
{263901}{}{An old, rusty loudspeaker.}
{264000}{}{a loudspeaker}
{264001}{}{An old, rusty loudspeaker.}
{264100}{}{a huge machine}
{264101}{}{The sign says: "Cloning machine".}
{264200}{}{a huge machine}
{264201}{}{The sign says: "Cloning machine".}
{264300}{}{a huge machine}
{264301}{}{The sign says: "Cloning machine".}
{264400}{}{a huge machine}
{264401}{}{The sign says: "Cloning machine".}
{264500}{}{a corpse}
{264501}{}{Something seems to have gone wrong with this machine.}
{264600}{}{an old box}
{264601}{}{So huge and so empty.}
{264700}{}{a crate}
{264701}{}{Nothing but useless junk inside.}
{264800}{}{a wall}
{264900}{}{a wall}
{265000}{}{a desk with a calculator}
{265001}{}{The engineer's workstation.}
{265100}{}{a desk with a calculator}
{265101}{}{An engineer's workstation with a calculator on.}
{265200}{}{a desk with a calculator}
{265201}{}{The engineer's workstation.}
{265300}{}{a desk with a calculator}
{265301}{}{An engineer's workstation with a calculator on.}
{265400}{}{a desk with a calculator}
{265401}{}{An engineer's workstation with a calculator on.}
{265500}{}{a desk with a calculator}
{265501}{}{The engineer's workstation.}
{265600}{}{a desk with a calculator}
{265601}{}{An engineer's workstation with a calculator on.}
{265700}{}{a desk with a calculator}
{265701}{}{The engineer's workstation.}
{265800}{}{a chair}
{265801}{}{A piece of furniture designed to support the human body in a seated position.}
{265900}{}{a chair}
{265901}{}{This chair would have been quite ordinary if it weren't for the wheels. You wonder if they used to have chair races here.}
{266000}{}{a chair}
{266001}{}{This chair would have been quite ordinary if it weren't for the wheels. You wonder if they used to have chair races here.}
{266100}{}{a chair}
{266101}{}{A piece of furniture designed to support the human body in a seated position.}
{266200}{}{a junk}
{266201}{}{Not even the last vagrant would be interested in this junk.}
{266300}{}{a box}
{266301}{}{An ordinary box of useless junk.}
{266400}{}{a box}
{266401}{}{An ordinary box of useless junk.}
{266500}{}{the wires}
{266501}{}{A floor cable.}
{266600}{}{the wires}
{266601}{}{A floor cable.}
{266700}{}{the wires}
{266701}{}{A floor cable.}
{266800}{}{the wires}
{266801}{}{A floor cable.}
{266900}{}{the wires}
{266901}{}{A floor cable.}
{267000}{}{the wires}
{267001}{}{A floor cable.}
{267100}{}{the wires}
{267101}{}{A floor cable.}
{267200}{}{a junk}
{267201}{}{It's completely useless junk.}
{267300}{}{a junk}
{267301}{}{It's completely useless junk.}
{267400}{}{a junk}
{267401}{}{It's completely useless junk.}
{267500}{}{a junk}
{267501}{}{A useless pile of junk.}
{267600}{}{a junk}
{267601}{}{A useless pile of junk.}
{267700}{}{a junk}
{267701}{}{It's completely useless junk.}
{267800}{}{a junk}
{267801}{}{There is some dubious liquid in the bottle. Better not to touch it.}
{267900}{}{a junk}
{267901}{}{Just an empty bottle.}
{268000}{}{a junk}
{268001}{}{It is hard to imagine that anyone in their right mind would be interested in this junk.}
{268100}{}{a junk}
{268101}{}{A bunch of useless junk.}
{268200}{}{a junk}
{268201}{}{It is hard to imagine that anyone in their right mind would be interested in this junk.}
{268300}{}{a junk}
{268301}{}{It is hard to imagine that anyone in their right mind would be interested in this junk.}
{268400}{}{a calculator}
{268401}{}{This is where the tower's solar panels are controlled.}
{268500}{}{a barrier}
{268501}{}{The rusted-out emergency fence.}
{268600}{}{a barrier}
{268601}{}{The rusted-out emergency fence.}
{268700}{}{a barrier}
{268701}{}{The rusted-out emergency fence.}
{268800}{}{a barrier}
{268801}{}{The rusted-out emergency fence.}
{268900}{}{a wall}
{268901}{}{The wall of the skyscraper.}
{269000}{}{a wall}
{269001}{}{The wall of the skyscraper.}
{269100}{}{a parapet}
{269101}{}{You can lean on it and look thoughtfully into the distance.}
{269200}{}{a parapet}
{269201}{}{You can lean on it and look thoughtfully into the distance.}
{269300}{}{a parapet}
{269301}{}{You can lean on it and look thoughtfully into the distance.}
{269400}{}{the lights}
{269500}{}{the lights}
{269600}{}{wasteland}
{269601}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{269700}{}{wasteland}
{269701}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{269800}{}{wasteland}
{269801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{269900}{}{wasteland}
{269901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270000}{}{wasteland}
{270001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270100}{}{wasteland}
{270101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270200}{}{wasteland}
{270201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270300}{}{wasteland}
{270301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270400}{}{wasteland}
{270401}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270500}{}{wasteland}
{270501}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270600}{}{wasteland}
{270601}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270700}{}{wasteland}
{270701}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270800}{}{wasteland}
{270801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270900}{}{wasteland}
{270901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{271000}{}{wasteland}
{271001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{271100}{}{wasteland}
{271101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{271200}{}{the bronze eagle}
{271201}{}{The enormous eagle is the symbol of an invincible country.}
{271300}{}{a wall}
{271301}{}{The wall of the skyscraper.}
{271400}{}{a wall}
{271401}{}{The wall of the skyscraper.}
{271500}{}{a wall}
{271501}{}{The wall of the skyscraper.}
{271600}{}{a wall}
{271601}{}{The wall of the skyscraper.}
{271700}{}{a wall}
{271701}{}{The wall of the skyscraper.}
{271800}{}{a wall}
{271801}{}{The wall of the skyscraper.}
{271900}{}{a wall}
{271901}{}{The wall of the skyscraper.}
{272000}{}{wasteland}
{272001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272100}{}{wasteland}
{272101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272200}{}{wasteland}
{272201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272300}{}{wasteland}
{272301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272400}{}{wasteland}
{272401}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272500}{}{wasteland}
{272501}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272600}{}{a sofa}
{272601}{}{A luxurious leather sofa.}
{272700}{}{a sofa}
{272701}{}{A luxurious leather sofa.}
{272800}{}{wasteland}
{272801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272900}{}{wasteland}
{272901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273000}{}{wasteland}
{273001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273100}{}{wasteland}
{273101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273200}{}{wasteland}
{273201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273300}{}{wasteland}
{273301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273400}{}{wasteland}
{273401}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273500}{}{wasteland}
{273501}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273600}{}{wasteland}
{273601}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273700}{}{wasteland}
{273701}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273800}{}{wasteland}
{273801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273900}{}{wasteland}
{273901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274000}{}{wasteland}
{274001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274100}{}{wasteland}
{274101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274200}{}{wasteland}
{274201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274300}{}{wasteland}
{274301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274400}{}{the biomass}
{274401}{}{Biomatter, a collection of organisms.}
{274500}{}{the biomass}
{274501}{}{Biomatter, a collection of organisms.}
{274600}{}{the biomass}
{274601}{}{Biomatter, a collection of organisms.}
{274700}{}{the biomass}
{274701}{}{Biomatter, a collection of organisms.}
{274800}{}{the biomass}
{274801}{}{Biomatter, a collection of organisms.}
{274900}{}{a elevator}
{274901}{}{The elevator doors.}
{275000}{}{a door}
{275001}{}{The passage is blocked.}
{275100}{}{a door}
{275101}{}{The passage is blocked.}
{275200}{}{a table}
{275201}{}{This is the biggest desk you have ever seen.}
{275300}{}{a table}
{275301}{}{This is the biggest desk you have ever seen.}
{275400}{}{a calculator}
{275401}{}{Cerberus security module}
{275500}{}{a calculator}
{275501}{}{Andromeda computation module}
{275600}{}{a calculator}
{275601}{}{Borealis logical module}
{275700}{}{a cooling system}
{275701}{}{You can hear the coolant circulating through the tubes.}
{275800}{}{a systematizer}
{275801}{}{A huge computing machine with a bunch of flashing lights.}
{275900}{}{a systematizer}
{275901}{}{A huge computing machine with a bunch of flashing lights.}
{276000}{}{the screen}
{276001}{}{A huge screen, covered in dust. Looks like it hasn't worked in years.}
{276100}{}{an armchair}
{276101}{}{A comfortable leather chair.}
{276200}{}{a sofa}
{276201}{}{A luxurious leather sofa.}
{276300}{}{a sofa}
{276301}{}{A luxurious leather sofa.}
{276400}{}{an armchair}
{276401}{}{A comfortable leather chair.}
{276500}{}{a calculator}
{276501}{}{Judging by its size, this machine has enormous computing power.}
{276600}{}{a calculator}
{276601}{}{Judging by its size, this machine has enormous computing power.}
{276700}{}{a calculator}
{276701}{}{Judging by its size, this machine has enormous computing power.}
{276800}{}{a calculator}
{276801}{}{Judging by its size, this machine has enormous computing power.}
{276900}{}{a camera}
{276901}{}{It's probably filming you.}
{277000}{}{a loudspeaker}
{277001}{}{An old loudspeaker. It probably still works.}
{277100}{}{a elevator}
{277101}{}{The elevator doors.}
{277200}{}{the shards}
{277201}{}{Thousands of them! And each one is unique in its own way.}
{277300}{}{the shards}
{277301}{}{Thousands of them! And each one is unique in its own way.}
{277400}{}{the shards}
{277401}{}{Thousands of them! And each one is unique in its own way.}
{277500}{}{the shards}
{277501}{}{Thousands of them! And each one is unique in its own way.}
{277600}{}{the shards}
{277601}{}{Thousands of them! And each one is unique in its own way.}
{277700}{}{the shards}
{277701}{}{Thousands of them! And each one is unique in its own way.}
{277800}{}{the shards}
{277801}{}{Thousands of them! And each one is unique in its own way.}
{277900}{}{the shards}
{277901}{}{Thousands of them! And each one is unique in its own way.}
{278000}{}{the shards}
{278001}{}{Thousands of them! And each one is unique in its own way.}
{278100}{}{the shards}
{278101}{}{Thousands of them! And each one is unique in its own way.}
{278200}{}{the shards}
{278201}{}{Thousands of them! And each one is unique in its own way.}
{278300}{}{the shards}
{278301}{}{Thousands of them! And each one is unique in its own way.}
{278400}{}{the shards}
{278401}{}{Thousands of them! And each one is unique in its own way.}
{278500}{}{the shards}
{278501}{}{Thousands of them! And each one is unique in its own way.}
{278600}{}{the shards}
{278601}{}{Thousands of them! And each one is unique in its own way.}
{278700}{}{the shards}
{278701}{}{Thousands of them! And each one is unique in its own way.}
{278800}{}{the shards}
{278801}{}{Thousands of them! And each one is unique in its own way.}
{278900}{}{the shards}
{278901}{}{Thousands of them! And each one is unique in its own way.}
{279000}{}{the shards}
{279001}{}{Thousands of them! And each one is unique in its own way.}
{279100}{}{the shards}
{279101}{}{Thousands of them! And each one is unique in its own way.}
{279200}{}{the shards}
{279201}{}{Thousands of them! And each one is unique in its own way.}
{279300}{}{the shards}
{279301}{}{Thousands of them! And each one is unique in its own way.}
{279400}{}{the shards}
{279401}{}{Thousands of them! And each one is unique in its own way.}
{279500}{}{the shards}
{279501}{}{Thousands of them! And each one is unique in its own way.}
{279600}{}{the shards}
{279601}{}{Thousands of them! And each one is unique in its own way.}
{279700}{}{the shards}
{279701}{}{Thousands of them! And each one is unique in its own way.}
{279800}{}{the shards}
{279801}{}{Thousands of them! And each one is unique in its own way.}
{279900}{}{the shards}
{279901}{}{Thousands of them! And each one is unique in its own way.}
{280000}{}{the shards}
{280001}{}{Thousands of them! And each one is unique in its own way.}
{280100}{}{the shards}
{280101}{}{Thousands of them! And each one is unique in its own way.}
{280200}{}{a tower control system}
{280201}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280300}{}{a tower control system}
{280301}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280400}{}{a tower control system}
{280401}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280500}{}{a tower control system}
{280501}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280600}{}{a floor}
{280601}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{280700}{}{a floor}
{280701}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{280800}{}{a floor}
{280801}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{280900}{}{a floor}
{280901}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{281000}{}{a floor}
{280601}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{281100}{}{an armored wall}
{281101}{}{A protective structure.}
{281200}{}{an armored wall}
{281201}{}{A protective structure.}
{281300}{}{an armored wall}
{281301}{}{A protective structure.}
{281400}{}{an armored wall}
{281401}{}{A protective structure.}
{281500}{}{an armored wall}
{281501}{}{A protective structure.}
{281600}{}{an armored wall}
{281601}{}{A protective structure.}
{281700}{}{an armored wall}
{281701}{}{A protective structure.}
{281800}{}{an armored wall}
{281801}{}{A protective structure.}
{281900}{}{an armored wall}
{281901}{}{A protective structure.}
{282000}{}{a shattered protective screen}
{282001}{}{The screen is completely shattered.}
{282100}{}{a shattered protective screen}
{282101}{}{The screen is completely shattered.}
{282200}{}{a shattered protective screen}
{282201}{}{The screen is completely shattered.}
{282300}{}{a poisonous sludge}
{282301}{}{Spookily gurgling.}
{282400}{}{a poisonous sludge}
{282401}{}{Spookily gurgling.}
{282500}{}{a poisonous sludge}
{282501}{}{Spookily gurgling.}
{282600}{}{a steel door}
{282601}{}{Rusty, but looks solid.}
{282700}{}{the corpse of a woman}
{282701}{}{The horribly stinking remains of some woman.}
{282800}{}{the sand}
{282900}{}{the sand}
{283000}{}{the sand}
{283100}{}{the sand}
{283200}{}{the sand}
{283300}{}{a junk}
{283301}{}{Some kind of debris in the water.}
{283400}{}{a vase}
{283401}{}{A clay vase filled with something very similar to blood.}
{283500}{}{a bucket}
{283501}{}{Nothing unusual - just a simple bucket with someone's guts hanging out of it.}
{283600}{}{a totem}
{283601}{}{Looks like the natives pray to this thing.}
{283700}{}{a totem}
{283701}{}{Looks like the natives pray to this thing.}
{283800}{}{a totem}
{283801}{}{Looks like the natives pray to this thing.}
{283900}{}{a totem}
{283901}{}{Looks like the natives pray to this thing.}
{284000}{}{a totem}
{284001}{}{A terrifying thing with a skull, bones, and red eyes - the natives have an original idea of the gods.}
{284100}{}{a totem}
{284101}{}{A terrifying thing with a skull, bones, and red eyes - the natives have an original idea of the gods.}
{284200}{}{a strange stump}
{284201}{}{An incomprehensible structure with burning pieces of coal inside. Probably has some religious meaning.}
{284300}{}{a strange stump}
{284301}{}{An incomprehensible structure with burning pieces of coal inside. Probably has some religious meaning.}
{284400}{}{a rod}
{284401}{}{Thick metal rod.}
{284500}{}{a tree}
{284501}{}{A dried-up tree.}
{284600}{}{a tree}
{284601}{}{A dried-up tree.}
{284700}{}{a tree}
{284701}{}{A dried-up tree.}
{284800}{}{a tree}
{284801}{}{A dried-up tree.}
{284900}{}{a tree}
{284901}{}{A dried-up tree.}
{285000}{}{a tree}
{285001}{}{A dried-up tree.}
{285100}{}{a tree}
{285101}{}{A dried-up tree.}
{285200}{}{a tree}
{285201}{}{A dried-up tree.}
{285300}{}{a tree}
{285301}{}{A dried-up tree.}
{285400}{}{a tree}
{285401}{}{A dried-up tree.}
{285500}{}{a tree}
{285501}{}{A dried-up tree.}
{285600}{}{a tree}
{285601}{}{A dried-up tree.}
{285700}{}{a tree}
{285701}{}{A dried-up tree.}
{285800}{}{a tree}
{285801}{}{A dried-up tree.}
{285900}{}{a tree}
{285901}{}{A dried-up tree.}
{286000}{}{a tree}
{286001}{}{A dried-up tree.}
{286100}{}{the leaves}
{286101}{}{Some kind of plant.}
{286200}{}{the leaves}
{286201}{}{Some kind of plant.}
{286300}{}{the leaves}
{286301}{}{Some kind of plant.}
{286400}{}{the leaves}
{286401}{}{Some kind of plant.}
{286500}{}{the leaves}
{286501}{}{Some kind of plant.}
{286600}{}{the leaves}
{286601}{}{Some kind of plant.}
{286700}{}{the leaves}
{286701}{}{Some kind of plant.}
{286800}{}{the leaves}
{286801}{}{Some kind of plant.}
{286900}{}{the leaves}
{286901}{}{Some kind of plant.}
{287000}{}{the leaves}
{287001}{}{Some kind of plant.}
{287100}{}{a stone}
{287200}{}{a stone}
{287300}{}{a stone}
{287400}{}{a stone}
{287500}{}{a stone}
{287600}{}{a stone}
{287700}{}{a stone}
{287800}{}{a stone}
{287900}{}{a stone}
{288000}{}{a stone}
{288100}{}{a stone}
{288200}{}{a stone}
{288300}{}{a stone}
{288400}{}{a stone}
{288500}{}{a stone}
{288600}{}{a stone}
{288700}{}{a stone}
{288800}{}{a stone}
{288900}{}{a stone}
{289000}{}{a stone}
{289100}{}{a stone}
{289200}{}{a stone}
{289300}{}{a stone}
{289400}{}{a stone}
{289500}{}{a stone}
{289600}{}{a stone}
{289700}{}{a stone}
{289800}{}{a stone}
{289900}{}{a stone}
{290901}{}{A stone totem, another object revered by the tribe.}
{290000}{}{a stone}
{290001}{}{No time to gather stones.}
{290100}{}{a stone}
{290101}{}{No time to gather stones.}
{290200}{}{a stone}
{290201}{}{No time to gather stones.}
{290300}{}{a fire}
{290301}{}{A fireplace neatly lined with rocks. Apparently, the stones keep the heat in.}
{290400}{}{the torch}
{290401}{}{A huge burning torch - it seems the natives revere fire.}
{290500}{}{a totem}
{290501}{}{This tribe is obviously very religious.}
{290600}{}{a totem}
{290601}{}{This tribe is obviously very religious.}
{290700}{}{a totem}
{290701}{}{This tribe is obviously very religious.}
{290800}{}{a totem}
{290801}{}{A stone totem, another object revered by the tribe.}
{290900}{}{a totem}
{290901}{}{A stone totem, another object revered by the tribe.}
{291000}{}{a totem}
{291001}{}{A stone totem, another object revered by the tribe.}
{291100}{}{a totem}
{291101}{}{There are bones sticking out of this one, and the fires inside are dying out. Do they have a schedule for setting totems on fire?}
{291200}{}{a totem}
{291201}{}{What big bones!}
{291300}{}{a totem}
{291301}{}{There are bones sticking out of this one, and the fires inside are dying out. Do they have a schedule for setting totems on fire?}
{291400}{}{a totem}
{291401}{}{What big bones!}
{291500}{}{a bench}
{291501}{}{A stiff and cold stone bench.}
{291600}{}{a stake}
{291601}{}{Looks like some kind of tribal tool.}
{291700}{}{a totem}
{291701}{}{Looks like there's meat on this stake. Their spirits demand sacrifices.}
{291800}{}{the parts of totems}
{291801}{}{And here are bones too. You wonder who they belonged to.}
{291900}{}{a roaster}
{291901}{}{You wonder what they're roasting there.}
{292000}{}{a fence}
{292001}{}{A small fence and a little table with something that looks like meat.}
{292100}{}{a strange stump}
{292101}{}{There's burning coal inside. Looks like the spirits of the tribe love fire.}
{292200}{}{a stump}
{292201}{}{There's burning coal inside. Looks like the spirits of the tribe love fire.}
{292300}{}{the stones}
{292301}{}{Spread out in an even circle around the fire.}
{292400}{}{the stones}
{292401}{}{Spread out in an even circle around the fire.}
{292500}{}{a slope}
{292501}{}{A sloped surface area.}
{292600}{}{a slope}
{292601}{}{A sloped surface area.}
{292700}{}{a totem}
{292701}{}{Shamanic totem of the tribe.}
{292800}{}{a tribune}
{292900}{}{a web}
{293000}{}{a web}
{293100}{}{a web}
{293200}{}{a web}
{293300}{}{a web}
{293400}{}{a web}
{293500}{}{a web}
{293600}{}{a web}
{293700}{}{a web}
{293800}{}{a web}
{293900}{}{a web}
{294000}{}{a web}
{294100}{}{a truck}
{294101}{}{Radioactive waste has leaked onto the ground from a broken cistern, making the place deadly.}
{294200}{}{a land}
{294300}{}{a land}
{294400}{}{a land}
{294500}{}{a land}
{294600}{}{a fence}
{294601}{}{A low fence made of planks.}
{294700}{}{a fence}
{294701}{}{A low fence made of planks.}
{294800}{}{the light}
{294801}{}{Yellow glass gives the illusion that the lantern is on.}
{294900}{}{a fence}
{294901}{}{A low fence made of planks.}
{295000}{}{a fence}
{295001}{}{A low fence made of planks.}
{295100}{}{a fence}
{295101}{}{A low fence made of planks.}
{295200}{}{a fence}
{295201}{}{A low fence made of planks.}
{295300}{}{a void}
{295301}{}{There is only a blackening emptiness. It is staring at you.}
{295400}{}{a "Warehouse" sign}
{295401}{}{You are not sure, but it could mean there is a warehouse.}
{295500}{}{a hospital poster}
{295501}{}{The poster shows a smiling doctor holding a bloody scalpel.}
{295600}{}{a tree}
{295601}{}{You can cut it down and make a fire. Or hang yourself on it.}
{295700}{}{a tree}
{295701}{}{It's a tree. It must be wooden.}
{295800}{}{a tree}
{295801}{}{You think it stands out from the others. You are seeing things.}
{295900}{}{a tree}
{295901}{}{You want to hug it and cry.}
{296000}{}{a tree}
{296001}{}{The accumulated radiation makes it shimmer slightly.}