{100}{}{Fire}
{101}{}{The flames light up the space around them.}
{200}{}{Door}
{201}{}{An old and battered metal door.}
{300}{}{Trash Can}
{301}{}{A too small container in the fights against littering.}
{400}{}{Wooden Table}
{401}{}{An old table with a dirty tablecloth.}
{500}{}{Metal Barrel}
{501}{}{An old steel barrel.}
{600}{}{Metal Barrel}
{601}{}{An old empty steel barrel.}
{700}{}{Tires}
{701}{}{A stack of old rubber tires.}
{800}{}{Wall}
{801}{}{This section of wand stands out.}
{900}{}{Terminal}
{901}{}{A computer terminal.}
{1000}{}{Terminal}
{1001}{}{A computer terminal.}
{1100}{}{Computer}
{1101}{}{A computer terminal, hooked to a mainframe computer.}
{1200}{}{Computer}
{1201}{}{A computer terminal, hooked to a mainframe computer.}
{1300}{}{Terminal}
{1301}{}{A computer terminal.}
{1400}{}{Terminal}
{1401}{}{A computer terminal.}
{1500}{}{Bull Head}
{1501}{}{Looks like this head of a lavash is really happy to be canned.}
{1600}{}{Tires}
{1601}{}{Tough old tires covered in sand.}
{1700}{}{Pit}
{1701}{}{A shallow indention in the ground.}
{1800}{}{Door}
{1801}{}{A high-tech metal door.}
{1900}{}{Door}
{1901}{}{A high-tech metal door.}
{2000}{}{Battery}
{2001}{}{An big and old empty battery.}
{2100}{}{Tire}
{2101}{}{A useless old tire.}
{2200}{}{Huge Statue}
{2201}{}{You read somewhere that it depicts Themis, the Godess of Justice.}
{2300}{}{Door}
{2301}{}{A high-tech metal door.}
{2400}{}{Tire}
{2401}{}{A useless old tire.}
{2500}{}{Monitor}
{2501}{}{A large wall-mounted monitor.}
{2600}{}{Monitor}
{2601}{}{A large wall-mounted monitor.}
{2700}{}{Tire}
{2701}{}{A hardened old tire, not worth to digging up.}
{2800}{}{Rocks}
{2801}{}{A pile of round stones.}
{2900}{}{Junk}
{2901}{}{It used to be a large important part of a machine, now it's just useless junk.}
{3000}{}{Monitor}
{3001}{}{A large wall-mounted monitor.}
{3100}{}{Monitor}
{3101}{}{A large wall-mounted monitor.}
{3200}{}{Vent}
{3201}{}{A part of the ventilation system.}
{3300}{}{Vent}
{3301}{}{A part of the ventilation system.}
{3400}{}{Bed}
{3401}{}{A very dirty bed. You own on Tartarus way much cleaner.}
{3500}{}{Bed}
{3501}{}{A very dirty bed. You own on Tartarus way much cleaner.}
{3600}{}{Bed}
{3601}{}{A very dirty bed. You own on Tartarus way much cleaner.}
{3700}{}{Bed}
{3701}{}{A dirty bed. You own on Tartarus way much cleaner.}
{3800}{}{Elevator}
{3801}{}{This is a service elevator.}
{3900}{}{Chair}
{3901}{}{A chair with armrests. It looks comfortable.}
{4000}{}{Chair}
{4001}{}{A chair with armrests. It looks comfortable.}
{4100}{}{Chair}
{4101}{}{A chair with armrests. It looks comfortable.}
{4200}{}{Chair}
{4201}{}{A chair with armrests. It looks comfortable.}
{4300}{}{Junk}
{4301}{}{Completely useless junk.}
{4400}{}{Junk}
{4401}{}{Nothing worth finding here.}
{4500}{}{Junk}
{4501}{}{Some metal fragments and old crates. It's scarcely usable.}
{4600}{}{Junk}
{4601}{}{Nothing worth finding here.}
{4700}{}{Chair}
{4701}{}{Better not to use it for its intended purpose, it looks like it's going to fall apart.}
{4800}{}{Chair}
{4801}{}{Better not to use it for its intended purpose, it looks like it's going to fall apart.}
{4900}{}{Exit Grid Map Marker}
{4901}{}{Exit Grid Map Marker}
{5000}{}{Well}
{5001}{}{An old dried out well.}
{5100}{}{Chair}
{5101}{}{A common chair with armrests.}
{5200}{}{Chair}
{5201}{}{A common chair with armrests.}
{5300}{}{Chair}
{5301}{}{A common chair with armrests.}
{5400}{}{Chair}
{5401}{}{A common chair with armrests.}
{5500}{}{Vent Grill}
{5501}{}{A part of the ventilation system.}
{5600}{}{Vent Grill}
{5601}{}{A part of the ventilation system.}
{5700}{}{Chair}
{5701}{}{There is nothing unusual about this chair.}
{5800}{}{Chair}
{5801}{}{There is nothing unusual about this chair.}
{5900}{}{Chair}
{5901}{}{There is nothing unusual about this chair.}
{6000}{}{Chair}
{6001}{}{There is nothing unusual about this chair.}
{6100}{}{Table}
{6101}{}{It looks old and scratched.}
{6200}{}{Table}
{6201}{}{It looks old and scratched..}
{6300}{}{Cactus}
{6301}{}{A small cactus with large spines.}
{6400}{}{Cactus}
{6401}{}{You've heard that cacti make good tequila.}
{6500}{}{Cactus}
{6501}{}{Green and very prickly.}
{6600}{}{Door}
{6601}{}{A broken metal door.}
{6700}{}{Secret Blocking Hex}
{6701}{}{Help! I was kidnapped and forced to describe objects!}
{6800}{}{Entrance}
{6801}{}{Entrance to the factory building.}
{6900}{}{Stalagmite}
{6901}{}{A natural extension of the rock floor.}
{7000}{}{Stalagmite}
{7001}{}{A natural extension of the rock floor.}
{7100}{}{Crevice}
{7101}{}{A deep fissure in the ground.}
{7200}{}{Rock Column}
{7201}{}{This thick column of rock extends from floor to ceiling.}
{7300}{}{Rock Column}
{7301}{}{This thin column of rock extends from floor to ceiling.}
{7400}{}{Rocks}
{7401}{}{You study the rocks for a while, but they never move.}
{7500}{}{Rocks}
{7501}{}{You keep a close eye on these rocks, in case they move to attack you.}
{7600}{}{Waterflow}
{7601}{}{An underground river that goes into the bowels of the cave. You can't see anything in the dark.}
{7700}{}{Gate}
{7701}{}{A wooden gate.}
{7800}{}{Rocks}
{7801}{}{A large pile of rocks. They look indigenous to this region.}
{7900}{}{Rocks}
{7901}{}{A small pile of rocks.}
{8000}{}{Rocks}
{8001}{}{A small pile of rocks.}
{8100}{}{Rocks}
{8101}{}{A large pile of rocks.}
{8200}{}{Hole}
{8201}{}{A small hole in the ground, very unlikely to fall in.}
{8300}{}{Hole}
{8301}{}{A small hole in the ground, very unlikely to fall in.}
{8400}{}{Crack}
{8401}{}{A quite deep cut in the ground.}
{8500}{}{Cracks}
{8501}{}{Several cracks in the ground.}
{8600}{}{Crack}
{8601}{}{A quite deep cut in the ground.}
{8700}{}{Gates}
{8701}{}{Wooden gates, they open and close.}
{8800}{}{Gate}
{8801}{}{A wooden gate.}
{8900}{}{Gate}
{8901}{}{A Wooden gate.}
{9000}{}{Merchant Shop}
{9001}{}{You can buy armor or weapons here.}
{9100}{}{Merchant Shop}
{9101}{}{You can buy armor or weapons here.}
{9200}{}{Rocks}
{9201}{}{Rocks, rocks, rocks! Everywhere you look, rocks!}
{9300}{}{Lamp}
{9301}{}{A source of lighting.}
{9400}{}{Lamp}
{9401}{}{A source of lighting.}
{9500}{}{Seat}
{9501}{}{It was once a car seat.}
{9600}{}{Seat}
{9601}{}{It was once a car seat. Looks dirty and uncomfortable.}
{9700}{}{Seat}
{9701}{}{It was once a car seat. Looks dirty and uncomfortable.}
{9800}{}{Seat}
{9801}{}{It was once a car seat.}
{9900}{}{Couch}
{9901}{}{A very dirty and smelly couch you don't want to sir on.}
{10000}{}{Couch}
{10001}{}{A very dirty and smelly couch you don't want to sir on.}
{10100}{}{Plants}
{10101}{}{Rocks among some bushes.}
{10200}{}{Shrub}
{10201}{}{A dried out  травянистое растение.}
{10300}{}{Shrub}
{10301}{}{Some sort of desert weed.}
{10400}{}{Shrub}
{10401}{}{A dry heraceous plant.}
{10500}{}{Shrub}
{10501}{}{A dry heraceous plant.}
{10600}{}{Shrub}
{10601}{}{A dry heraceous plant.}
{10700}{}{Shrub}
{10701}{}{Some sort of desert weed.}
{10800}{}{Shrub}
{10801}{}{A dry heraceous plant.}
{10900}{}{Shrub}
{10901}{}{A dry heraceous plant.}
{11000}{}{Shrub}
{11001}{}{Some sort of desert weed.}
{11100}{}{Bush}
{11101}{}{Some sort of desert weed.}
{11200}{}{Bush}
{11201}{}{A small, completely dry bush.}
{11300}{}{Bush}
{11301}{}{A small, completely dry bush.}
{11400}{}{Bush}
{11401}{}{Типичный представитель herba vulgaris.}
{11500}{}{Bush}
{11501}{}{A typical representative of herba vulgaris.}
{11600}{}{Bush}
{11601}{}{A typical representative of herba vulgaris.}
{11700}{}{Plant}
{11701}{}{A typical representative of herba vulgaris.}
{11800}{}{Plant}
{11801}{}{A dry bush}
{11900}{}{Cactus}
{11901}{}{It's amazing how tall these cacti grow.}
{12000}{}{Rocks}
{12001}{}{A pile of rocks.}
{12100}{}{Rocks}
{12101}{}{You could fry eggs on these stones.}
{12200}{}{Rock}
{12201}{}{You look carefully, but it's just an ordinary stone.}
{12300}{}{Rocks}
{12301}{}{A couple of rocks.}
{12400}{}{Rocks}
{12401}{}{A pile of rocks.}
{12500}{}{Human Bones}
{12501}{}{You look at them for a while and think about the impermanence of existence.}
{12600}{}{Bones}
{12601}{}{The skeleton of some poor guy.}
{12700}{}{Bones}
{12701}{}{You'll be nothing but a pile of bones someday, too.}
{12800}{}{Blocking Hex (NoLight)}
{12900}{}{Wall}
{12901}{}{A damaged section of wall.}
{13000}{}{Wall}
{13001}{}{A damaged section of wall.}
{13100}{}{Wall}
{13200}{}{Wall}
{13201}{}{A damaged section of wall.}
{13300}{}{Wall}
{13400}{}{Wall}
{13500}{}{Energy Generator}
{13501}{}{It's a big, complicated machine, probably relates to electricity.}
{13600}{}{Wall}
{13601}{}{A damaged section of wall.}
{13700}{}{Chair}
{13701}{}{This chair is ruined.}
{13800}{}{Chair}
{13801}{}{This chair is ruined.}
{13900}{}{Ladder}
{13901}{}{It's an old, fairly rickety ladder. It looks like it will barely support your weight.}
{14000}{}{Trapdoor}
{14001}{}{An outside hatch that leads down.}
{14100}{}{Light Source}
{14200}{}{Door}
{14201}{}{A strong metal door.}
{14300}{}{Door}
{14301}{}{A rusty but still sturdy metal door.}
{14400}{}{Cover}
{14401}{}{A heavy manhole cover. It seems to be well preserved.}
{14500}{}{Stuff}
{14501}{}{A huge, promising pile of junk. And absolutely nothing useful... what a disappointment!}
{14600}{}{Stuff}
{14601}{}{You wonder how in such a pile of things there can be nothing of value at all.}
{14700}{}{Wall}
{14800}{}{Wall}
{14900}{}{Wall}
{15000}{}{Wall}
{15100}{}{Metal Rod}
{15101}{}{A thick, rusty metal rod.}
{15200}{}{Metal Rod}
{15201}{}{A broken metal rod. It takes a lot of strength to break one.}
{15300}{}{Metal Rod}
{15301}{}{A thick rusty metal rod.}
{15400}{}{Metal Rod}
{15401}{}{A broken metal rod. It takes a lot of strength to break one.}
{15500}{}{Old Poster}
{15501}{}{On the poster, a pretty lab assistant warns you to close the cage.}
{15600}{}{Metal Rod}
{15601}{}{A broken metal rod. It takes a lot of strength to break one.}
{15700}{}{Table}
{15701}{}{There's a dirty rag on the table.}
{15800}{}{Grass}
{15801}{}{Some dry grass.}
{16000}{}{Shrub}
{16001}{}{A common desert shrub.}
{16100}{}{Shrub}
{16101}{}{A common desert shrub.}
{16200}{}{Boat}
{16201}{}{An old, hal-broken and rusty boat.}
{16300}{}{Pickup Truck}
{16301}{}{It was once an excellent vehicle.}
{16400}{}{Motorcycle}
{16401}{}{You dream of riding on this, but unfortunately it is broken.}
{16500}{}{Motorcycle}
{16501}{}{You dream of riding on this, but unfortunately it is broken.}
{16600}{}{Bush}
{16601}{}{Some desert plant.}
{16700}{}{Bush}
{16701}{}{Some desert plant.}
{16800}{}{Bush}
{16801}{}{Some desert plant.}
{16900}{}{Motorcycle}
{16901}{}{You dream of riding on this, but unfortunately it is broken.}
{17000}{}{Flag}
{17001}{}{The old flag of the USA.}
{17100}{}{Jukebox}
{17101}{}{It doesn't seem to be able to produce sound anymore.}
{17200}{}{Rainbow Pharmaceuticals}
{17201}{}{There used to be a pharmaceutical company with that name around here.}
{17300}{}{Firepit}
{17301}{}{The fire went out a long time ago.}
{17400}{}{Wall}
{17401}{}{A damaged wall.}
{17500}{}{Billboard}
{17501}{}{It is impossible to read what was written on it.}
{17600}{}{Floor}
{17700}{}{Floor}
{17800}{}{Lighting}
{17900}{}{Lighting}
{18000}{}{Couch}
{18001}{}{Or at least it once was a couch, now it's just junk.}
{18100}{}{Couch}
{18101}{}{The best years of this couch are clearly in the very distant past.}
{18200}{}{Guitar}
{18201}{}{A battered musical instrument. Looks too complicated for you.}
{18300}{}{Powerful Battery}
{18301}{}{Surprisingly, there is still some charge left and this thing can be repaired.}
{18400}{}{Stuff}
{18401}{}{It looks like these boxes have already been searched by somebody before you.}
{18500}{}{Stuff}
{18501}{}{It's amazing what useless junk people can cram into boxes and store.}
{18600}{}{Bed}
{18601}{}{The bed is in a terrible, disgusting state.}
{18700}{}{Bed}
{18701}{}{You don't think anyone in their right mind would want to lie on that bed.}
{18800}{}{Bed}
{18801}{}{You don't think anyone in their right mind would want to lie on that bed.}
{18900}{}{Bed}
{18901}{}{The best thing to do with this bed is to destroy it.}
{19000}{}{Bed}
{19001}{}{It looks like a comfy bed, but the sheets on it aren't.}
{19100}{}{Bed}
{19101}{}{These sheets should have been washed, and they should have been washed a dozen years ago.}
{19200}{}{Bed}
{19201}{}{A bed with a pile of dirty sheets.}
{19300}{}{Couch}
{19301}{}{Or at least it once was a couch, now it's just junk.}
{19400}{}{Floor}
{19500}{}{Wall}
{19600}{}{Tiles}
{19601}{}{Some stone tiles on the floor.}
{19700}{}{Hatch}
{19701}{}{The stairs leading down the hole descend into darkness.}
{19800}{}{Curb}
{19801}{}{A destroyed part of the sidewalk.}
{19900}{}{Curb}
{19901}{}{A destroyed part of the sidewalk.}
{20000}{}{Motorcycle}
{20001}{}{A rusty motorcycle of the Sunset Jackals.}
{20100}{}{Sign}
{20101}{}{The sign on this post is pretty rust.}
{20200}{}{Sign}
{20201}{}{It's not very clear what it was pointing at.}
{20300}{}{Sign}
{20301}{}{The sign on this post is pretty rust.}
{20400}{}{Sign}
{20401}{}{The sign on thist post is pretty rust.}
{20500}{}{Sign}
{20501}{}{The sign on tihs post is pretty rust.}
{20600}{}{Old Mattress}
{20601}{}{This mattress discourages any desire to take a nap on or even go near it.}
{20700}{}{Old Mattress}
{20701}{}{Lying on it you might feed those charming critters living in it.}
{20800}{}{Bed}
{20801}{}{It stinks even from a distance.}
{20900}{}{Bed}
{20901}{}{Even if you were to sleep by yourself on this thing, you would not be sleeping alone.}
{21000}{}{Bed}
{21001}{}{This bed has seen better days (and probably nights, too.)}
{21100}{}{Bed}
{21101}{}{There are a couple stains of dubious origin on this well-worn sleeping device.}
{21200}{}{Bed}
{21201}{}{This bed is neatly covered with a dirty blanket}
{21300}{}{Bed}
{21301}{}{This bed has seen a lot of use and wear. Something must have crawled between the mattresses and died, too.}
{21400}{}{Counter}
{21401}{}{Portions of foode are given out here.}
{21500}{}{Counter}
{21501}{}{Portions of foode are given out here.}
{21600}{}{Counter}
{21601}{}{Portions of foode are given out here.}
{21700}{}{Counter}
{21701}{}{Portions of foode are given out here.}
{21800}{}{Counter}
{21801}{}{Portions of foode are given out here.}
{21900}{}{Kitchen}
{21901}{}{The food for the whole of Tartarus is prepared here.}
{22000}{}{Broken Table}
{22001}{}{Something or someone broke through the table.}
{22100}{}{Chair}
{22101}{}{It looks comfortable.}
{22200}{}{Tires}
{22201}{}{You have plenty of time to look at this garbage.}
{22300}{}{Wheel}
{22301}{}{Previously part of a car.}
{22400}{}{Tire}
{22401}{}{Essentially just useless junk.}
{22500}{}{Wheel}
{22501}{}{Previously part of a car.}
{22600}{}{Wheel}
{22601}{}{Previously part of a car.}
{22700}{}{Tire}
{22701}{}{This old tire is completely hardened out.}
{22800}{}{Driving Wheel}
{22801}{}{It's hard to imagine that someone could use this stuff.}
{22900}{}{Chair}
{22901}{}{This chair has already served its time.}
{23000}{}{Chair}
{23001}{}{It looks quite suitable to sit on.}
{23100}{}{Chair}
{23101}{}{This chair is rotting right before your eyes.}
{23200}{}{Chair}
{23201}{}{It doesn't look too comfortable, but it's quite sturdy.}
{23300}{}{Chair}
{23301}{}{This chair doesn't even seem to be rusty.}
{23400}{}{Chair}
{23401}{}{This chair with armrests is still in good shape.}
{23500}{}{Chair}
{23501}{}{Well preserved and also still spinning.}
{23600}{}{Chair}
{23601}{}{This chair doesn't even seem to be rusty.}
{23700}{}{Chair}
{23701}{}{This chair is slightly askew.}
{23800}{}{Chair}
{23801}{}{An old wooden chair, looks stil quite sturdy.}
{23900}{}{Chair}
{23901}{}{An old wooden chair, looks stil quite sturdy.}
{24000}{}{Chair}
{24001}{}{An old wooden chair, looks stil quite sturdy.}
{24100}{}{Chair}
{24101}{}{An old wooden chair, looks stil quite sturdy.}
{24200}{}{Chair}
{24201}{}{An old wooden chair, looks stil quite sturdy.}
{24300}{}{Fire Hydrant}
{24301}{}{There's definitely no water there anymore.}
{24400}{}{Lamp Post}
{24401}{}{It's covered in rust, but it's still standing.}
{24500}{}{Lamp Post}
{24501}{}{This lamp post will never work again.}
{24600}{}{Lamp Post}
{24601}{}{This lamp post will never work again.}
{24700}{}{Lamp Post}
{24701}{}{It's covered in rust, but it's still standing.}
{24800}{}{Crate}
{24801}{}{A metal crate, labeled Livos.}
{24900}{}{Metro Sign}
{24901}{}{The entrance to the station must be here somewhere.}
{25000}{}{Cave Wall}
{25100}{}{Sign}
{25101}{}{Something dangerous is stored here.}
{25200}{}{Stuff}
{25201}{}{Just some useless junk.}
{25300}{}{Crate}
{25301}{}{A sturdy metal crate.}
{25400}{}{Crate}
{25401}{}{A metal crate, labeled Livos.}
{25500}{}{Junk}
{25501}{}{There's nothing useful there.}
{25600}{}{Rocks}
{25601}{}{Some small rocks.}
{25700}{}{Rocks}
{25701}{}{A couple of small stones.}
{25800}{}{Door}
{25801}{}{This door is in good condition.}
{25900}{}{Door}
{25901}{}{This door is in good condition.}
{26000}{}{Door}
{26001}{}{A beatuful decorated door, in good condition.}
{26100}{}{Door}
{26101}{}{A beatuful decorated door, in good condition.}
{26200}{}{Crate}
{26201}{}{A nice wooden crate with some junk in it.}
{26300}{}{Crate}
{26301}{}{A sturdy wooden crate.}
{26400}{}{Crate}
{26401}{}{The only thing that's valuable would be the crate itself, and even that is questionable.}
{26500}{}{Newspaper Machine}
{26501}{}{The newspaper machine is empty.}
{26600}{}{Newspaper Machine}
{26601}{}{The newspaper machine is empty.}
{26700}{}{Newspaper Machine}
{26701}{}{The newspaper machine is empty.}
{26800}{}{Newspaper Machine}
{26801}{}{The newspaper machine is empty.}
{26900}{}{Newspaper Machine}
{26901}{}{The newspaper machine is empty.}
{27000}{}{Newspaper Machine}
{27001}{}{The newspaper machine is empty. It looks like it once held adult magazines.}
{27100}{}{Old Mattress}
{27101}{}{It's not usable for it's intended purpose anymore, just useless garbage now.}
{27200}{}{Old Mattress}
{27201}{}{Maybe in a fully hermetic sealed metal armor you wouldn't catch something while lying on it.}
{27300}{}{Junk}
{27301}{}{A pile of rotten old wood. It's not worth carrying around.}
{27400}{}{Junk}
{27401}{}{A pile of rotten wood.}
{27500}{}{Junk}
{27501}{}{This junk is hardly useful.}
{27600}{}{Junk}
{27601}{}{This junk is hardly useful.}
{27700}{}{Junk}
{27701}{}{Some junk that you think might have been a bed mattress before it was destroyed by the environment.}
{27800}{}{Rocks}
{27900}{}{Rocks}
{28000}{}{Rocks}
{28100}{}{Rubble}
{28101}{}{A small pile of rubbled stones and rocks. Watch your step!}
{28200}{}{Box}
{28201}{}{A sturdy wooden box.}
{28300}{}{Rocks}
{28301}{}{A pile of rocks.}
{28400}{}{Box}
{28401}{}{There's some junk inside.}
{28500}{}{Rocks}
{28501}{}{A pile of rocks.}
{28600}{}{Stop Sign}
{28601}{}{A red sign with the word STOP written in large block letters.}
{28700}{}{Stop Sign}
{28701}{}{A red sign with the word STOP written in large block letters. The large bullet hole was added after manufacturing.}
{28800}{}{Box}
{28801}{}{A large empty box.}
{28900}{}{Boxes}
{28901}{}{Two wooden boxes with contents of unknown purpose.}
{29000}{}{Box}
{29001}{}{A patched box. It's contents long lost all value.}
{29100}{}{Street Lamp}
{29101}{}{It looks like it's still working.}
{29200}{}{Street Lamp}
{29201}{}{It looks like it's still working.}
{29300}{}{Street Lamp}
{29301}{}{It looks like it's still working.}
{29400}{}{Street Lamp}
{29401}{}{It looks like it's still working.}
{29500}{}{Street Lamp}
{29501}{}{Or to be precise, what is left of it.}
{29600}{}{Street Lamp}
{29601}{}{This lamp can unlikely be restored.}
{29700}{}{Street Lamp}
{29701}{}{It looks like it's still working.}
{29800}{}{Box}
{29801}{}{A sturdy wooden box with some useless junk.}
{29900}{}{Box}
{29901}{}{A metal box.}
{30000}{}{Table}
{30001}{}{This table has clearly been smashed, it looks like it's about to fall apart.}
{30100}{}{Table}
{30101}{}{A wooden table, relatively well preserved.}
{30200}{}{Table}
{30201}{}{A wooden table, put down to rest.}
{30300}{}{Table}
{30301}{}{A wooden table, with plastic surface, that has been broken for a while.}
{30400}{}{Junk}
{30401}{}{Completely useless junk.}
{30500}{}{Table}
{30501}{}{An old broken table.}
{30600}{}{Table}
{30601}{}{It looks like it could fall apart any minute.}
{30700}{}{Dirt}
{30701}{}{Dirt}
{30800}{}{Dirt}
{30801}{}{Dirt}
{30900}{}{Toilet}
{30901}{}{Whoever used it last didn't flush it away!}
{31000}{}{Junk}
{31001}{}{Pieces of wood, boxes and pther debris.}
{31100}{}{Junk}
{31101}{}{Even if you look at it more closely, you will not find anything of value.}
{31200}{}{Junk}
{31201}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31300}{}{Junk}
{31301}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31400}{}{Junk}
{31401}{}{Something that has clearly served its purpose.}
{31500}{}{Junk}
{31501}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31600}{}{Tree}
{31601}{}{A dead but still strong tree. Every beaver's dream.}
{31700}{}{Tree}
{31701}{}{A dead tree. The hollow is empty.}
{31800}{}{Stump}
{31801}{}{It was once a tree.}
{31900}{}{Rope}
{32000}{}{Barrier}
{32001}{}{A small portable fence.}
{32100}{}{Barrier}
{32101}{}{A small portable fence.}
{32200}{}{Wall}
{32300}{}{Truck}
{32301}{}{The wrecked remains of a diesel truck. This pile of metal will never go again.}
{32400}{}{Truck}
{32401}{}{This diesel truck can't be fixed.}
{32500}{}{Bath Tub}
{32501}{}{On closer examination, you realize that you won't be taking your bath in this tub after all.}
{32600}{}{Bath Tub}
{32601}{}{This bath tub is broken and cracked.}
{32700}{}{Urinal}
{32701}{}{Not the cleanest of its kind, you wouldn't want to use it.}
{32800}{}{Table}
{32801}{}{A table with a computator. You wonder why they need two monitors here.}
{32900}{}{Urinal}
{32901}{}{Just a dirty urinal. Nothing special.}
{33000}{}{Table}
{33001}{}{An ordinary table, in good condition.}
{33100}{}{Platform}
{33101}{}{A system of mechanisms is located on the concrete platform.}
{33200}{}{Door}
{33201}{}{A cracked wooden door.}
{33300}{}{Door}
{33301}{}{A cracked wooden door.}
{33400}{}{Truck}
{33401}{}{It will definitely not move anymore.}
{33500}{}{Truck}
{33501}{}{It will definitely not move anymore.}
{33600}{}{Truck}
{33601}{}{It will definitely not move anymore.}
{33700}{}{Truck}
{33701}{}{It will definitely not move anymore.}
{33800}{}{Truck}
{33801}{}{It's just a pile of rusty metal now.}
{33900}{}{Truck}
{33901}{}{It's back is full of broken containers and crates. Their contents lost their value a long time ago.}
{34000}{}{Wall}
{34001}{}{Wall}
{34100}{}{Wall}
{34101}{}{Wall}
{34200}{}{Road Sign}
{34201}{}{A funny little man is drawn on the sign.}
{34300}{}{Road Sign}
{34301}{}{A funny little man is drawn on the sign.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{If you can see this, blame the technical designer.}
{34500}{}{Floor}
{34600}{}{Shadow}
{34601}{}{The shadow of the New World Order sign.}
{34700}{}{Pipe}
{34701}{}{Part of the pipe.}
{34800}{}{Ladder}
{34801}{}{Going up.}
{34900}{}{Ladder}
{34901}{}{Going down.}
{35000}{}{Ladder}
{35001}{}{Going up.}
{35100}{}{Ladder}
{35101}{}{Going up.}
{35200}{}{Ladder}
{35201}{}{Going up.}
{35300}{}{Ladder}
{35301}{}{Going down.}
{35400}{}{Ladder}
{35401}{}{Going down.}
{35500}{}{Ladder}
{35501}{}{Going up.}
{35600}{}{Entrance}
{35601}{}{Entrance to the factory building.}
{35700}{}{Table}
{35701}{}{An old wooden table.}
{35800}{}{Table}
{35801}{}{An old wooden table.}
{35900}{}{Well}
{35901}{}{A shallow well}
{36000}{}{Wall}
{36001}{}{Wall}
{36100}{}{Curtain}
{36101}{}{The curtain looks as if it was made with primitive tools, but it is very strong.}
{36200}{}{Curtain}
{36201}{}{The curtain looks as if it was made with primitive tools, but it is very strong.}
{36300}{}{Graffiti}
{36301}{}{Jackals Rule!}
{36400}{}{Graffiti}
{36401}{}{Jackals Rule!}
{36500}{}{Graffiti}
{36501}{}{Jackals Rule!}
{36600}{}{Boards}
{36601}{}{The fence consists of such boards.}
{36700}{}{Boards}
{36701}{}{The fence consists of such boards.}
{36800}{}{Sign}
{36801}{}{It says something about a certain laboratory.}
{36900}{}{Cave Wall}
{37000}{}{Dirt}
{37001}{}{Dirt}
{37100}{}{Dirt}
{37101}{}{Dirt}
{37200}{}{Pot}
{37201}{}{A finely crafted clay pot.}
{37300}{}{Rake}
{37301}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37400}{}{Rake}
{37401}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37500}{}{Rake}
{37501}{}{This rake is the property of it's owners. You can't even conceive of a use for it.}
{37600}{}{Boards}
{37601}{}{The fence consists of such boards.}
{37700}{}{Boards}
{37701}{}{The fence consists of such boards.}
{37800}{}{Boards}
{37801}{}{The fence consists of such boards.}
{37900}{}{Basin}
{37901}{}{It's full of junk. You don't want to look into it.}
{38000}{}{Basin}
{38001}{}{There's sediment and dirt inside.}
{38100}{}{Bucket}
{38101}{}{There is some water at the bottom. What would you like to see in it?}
{38200}{}{Vase}
{38201}{}{A very pretty clay vase.}
{38300}{}{Well}
{38301}{}{A typical well found in the wasteland.}
{38400}{}{Box}
{38401}{}{An empty storage box.}
{38500}{}{Box}
{38501}{}{An empty storage box.}
{38600}{}{Box}
{38601}{}{Every time you look in a box and find it empty, you get a little upset.}
{38700}{}{Box}
{38701}{}{An empty storage box.}
{38800}{}{Box}
{38801}{}{Every time you look in a box and find it empty, you get a little upset.}
{38900}{}{Box}
{38901}{}{Just a confusing storage box full of trash.}
{39000}{}{Box}
{39001}{}{Every time you look in a box and find it empty, you get a little upset.}
{39100}{}{Box}
{39101}{}{An empty storage box.}
{39200}{}{Brace}
{39201}{}{This brace helps to support the defensive wall.}
{39300}{}{Metal Plate}
{39301}{}{Useless stuff.}
{39400}{}{Metal Plate}
{39401}{}{Useless stuff.}
{39500}{}{Brace}
{39501}{}{This brace helps to support the defensive wall.}
{39600}{}{Metal Barrel}
{39601}{}{A rusty metal barrel. It is empty.}
{39700}{}{Metal Barrel}
{39701}{}{This barrel is probably empty from the hollow sound.}
{39800}{}{Metal Barrels}
{39801}{}{These barrels are probably empty from their hollow sound.}
{39900}{}{Metal Barrels}
{39901}{}{These barrels are probably empty from their hollow sound.}
{40000}{}{Air Vent}
{40001}{}{This air vent appears to be for an underground structure.}
{40100}{}{Box}
{40101}{}{Every time you look in a box and find it empty, you get a little upset.}
{40200}{}{Box}
{40201}{}{An empty storage box.}
{40300}{}{Box}
{40301}{}{An empty storage box.}
{40400}{}{Rat Hole}
{40401}{}{Maybe there's something inside besides rats.}
{40500}{}{Sunbed}
{40501}{}{An old rotten sunbed.}
{40600}{}{Дверь}
{40601}{}{Рассохшаяся деревянная дверь.}
{40700}{}{Автомобиль "Перехватчик"}
{40701}{}{Судя по турбокомпрессору на капоте, это был очень мощный автомобиль. Увы, он уже никуда не поедет.}
{40800}{}{Доски}
{40801}{}{Старые полусгнившие доски.}
{40900}{}{Грузовик}
{40901}{}{Старый сломанный военный грузовик.}
{41000}{}{Вещи}
{41001}{}{Куча бесполезного барахла, накрытая тентом.}
{41100}{}{Вещи}
{41101}{}{Куча бесполезного барахла, накрытая тентом.}
{41200}{}{Вещи}
{41201}{}{Куча бесполезного барахла, накрытая тентом.}
{41300}{}{Сторожевая будка}
{41301}{}{Либо ее переоборудовали под туалет, либо сторожить удобнее всего на унитазе.}
{41400}{}{Table}
{41401}{}{Оснащен некими непонятными инструментами.}
{41500}{}{Хлам}
{41501}{}{Какие-то железяки, которым Вы вряд ли найдете применение.}
{41600}{}{Хлам}
{41601}{}{Старые инструменты, похоже, они все сломаны.}
{41700}{}{Коробка}
{41701}{}{Пустая складская коробка.}
{41800}{}{Коробка}
{41801}{}{Пустая складская коробка.}
{41900}{}{Коробка}
{41901}{}{Пустая складская коробка.}
{42000}{}{Коробка}
{42001}{}{Пустая складская коробка.}
{42100}{}{Дверь лифта}
{42101}{}{Эта дверь ведет в кабину лифта. Нужно сначала ее открыть, чтобы использовать сам лифт.}
{42200}{}{Доски}
{42201}{}{Несколько досок и другой мусор.}
{42300}{}{Камни}
{42400}{}{Камни}
{42500}{}{Камни}
{42600}{}{Bed}
{42601}{}{Мебельное изделие в ужасном состоянии.}
{42700}{}{Bed}
{42701}{}{Мебельное изделие в ужасном состоянии.}
{42800}{}{Коробка}
{42801}{}{Пустая складская коробка.}
{42900}{}{Коробка}
{42901}{}{Пустая складская коробка.}
{43000}{}{Коробка}
{43001}{}{Пустая складская коробка.}
{43100}{}{Коробка}
{43101}{}{Пустая складская коробка.}
{43200}{}{Junk}
{43300}{}{Junk}
{43400}{}{Junk}
{43500}{}{Камни}
{43501}{}{Обыкновенные камни, даже если самым пристальным образом их изучить.}
{43600}{}{Сторожевая будка}
{43601}{}{Либо ее переоборудовали под туалет, либо сторожить удобнее всего на унитазе.}
{43700}{}{Дверь}
{43701}{}{Прекрасно выполненная деревянная дверь, усиленная металлическим орнаментом и скобами, производящими гипнотическое впечатление.}
{43800}{}{Дверь}
{43801}{}{Прекрасно выполненная деревянная дверь, усиленная металлическим орнаментом и скобами, производящими гипнотическое впечатление.}
{43900}{}{Сорванные растения}
{43901}{}{Кучка сорванных и перегнивающих растений.}
{44000}{}{Сорванные растения}
{44001}{}{Кучка сорванных и перегнивающих растений.}
{44100}{}{Сорванные растения}
{44101}{}{Кучка сорванных и перегнивающих растений.}
{44200}{}{Сорванные растения}
{44201}{}{Эта кучка неважно пахнет, скорее даже воняет.}
{44300}{}{Сорванные растения}
{44301}{}{Эта кучка неважно пахнет, скорее даже воняет.}
{44400}{}{Сорняк}
{44401}{}{Это растение очевидно несъедобно.}
{44500}{}{Сорняк}
{44501}{}{Вы, конечно, не специалист по растениям, но на съедобное оно не похоже.}
{44600}{}{Сорняк}
{44601}{}{Это растение очевидно несъедобно.}
{44700}{}{Агрегат}
{44701}{}{Сложное устройство непонятного назначения.}
{44800}{}{Дверь}
{44801}{}{Охраняемая дверь. Похоже, она сильно укреплена.}
{44900}{}{Ядерная боеголовка.}
{45000}{}{Генератор}
{45001}{}{Сложное устройство для выработки электроэнергии.}
{45100}{}{Забор}
{45101}{}{Деревянный забор.}
{45200}{}{Забор}
{45201}{}{Деревянный забор.}
{45300}{}{Забор}
{45301}{}{Деревянный забор.}
{45400}{}{Забор}
{45401}{}{Деревянный забор.}
{45500}{}{Забор}
{45501}{}{Деревянный забор.}
{45600}{}{Забор}
{45601}{}{Деревянный забор.}
{45700}{}{Забор}
{45701}{}{Деревянный забор.}
{45800}{}{Забор}
{45801}{}{Построившие этот неровный забор явно не были перфекционистами.}
{45900}{}{Забор}
{45901}{}{Построившие этот неровный забор явно не были перфекционистами.}
{46000}{}{Забор}
{46001}{}{Построившие этот неровный забор явно не были перфекционистами.}
{46100}{}{Канализационная решетка}
{46101}{}{Маловероятно, что сама канализация сохранилась.}
{46200}{}{Бутылки}
{46201}{}{Треснувшие бутылки и битая посуда.}
{46300}{}{Бутылки}
{46301}{}{Треснувшие бутылки и битая посуда.}
{46400}{}{Хлам}
{46401}{}{Бесполезный мусор.}
{46500}{}{Игральный Автомат}
{46501}{}{Вы же не думаете, что через две сотни лет он по-прежнему работает.}
{46600}{}{Игральный Автомат}
{46601}{}{Вы же не думаете, что через две сотни лет он по-прежнему работает.}
{46700}{}{Хлам}
{46701}{}{Какой-то бесполезный хлам.}
{46800}{}{Хлам}
{46801}{}{Какой-то бесполезный хлам.}
{46900}{}{Плакат}
{46901}{}{Понять, что на нем изображено невозможно.}
{47000}{}{Дверь лифта}
{47100}{}{Коробка}
{47101}{}{Пустая складская коробка.}
{47200}{}{Коробка}
{47201}{}{В этой коробке нет совершенно ничего интересного.}
{47300}{}{Коробка}
{47301}{}{В этой коробке нет совершенно ничего интересного.}
{47400}{}{Коробка}
{47401}{}{В этой коробке нет совершенно ничего интересного.}
{47500}{}{Коробка}
{47501}{}{В этой коробке нет совершенно ничего интересного.}
{47600}{}{Коробка}
{47601}{}{В этой коробке нет совершенно ничего интересного.}
{47700}{}{Коробка}
{47701}{}{В этой коробке нет совершенно ничего интересного.}
{47800}{}{Коробка}
{47801}{}{В этой коробке нет совершенно ничего интересного.}
{47900}{}{Коробка}
{47901}{}{В этой коробке нет совершенно ничего интересного.}
{48000}{}{Коробка}
{48001}{}{В этой коробке нет совершенно ничего интересного.}
{48100}{}{Дверь}
{48101}{}{Прочная металлическая дверь.}
{48200}{}{Дверь}
{48201}{}{Прочная металлическая дверь.}
{48300}{}{Вещи}
{48301}{}{Огромная гора вещей, в которой при внимательном изучении на удивление нет ничего полезного для Вас.}
{48400}{}{Оружейная лавка.}
{48401}{}{На прилавке целый арсенал.}
{48500}{}{Винт}
{48501}{}{Винт вращается.}
{48600}{}{Алтарь}
{48700}{}{Монитор}
{48701}{}{Большой монитор, покрыт пылью и определенно не работает.}
{48800}{}{Floor}
{48801}{}{Floor}
{48900}{}{Ограждение}
{48901}{}{Ограждает лестницу с двух сторон.}
{49000}{}{Wall}
{49100}{}{Ограждение}
{49101}{}{Доски, прибитые к листу железа.}
{49200}{}{Ограждение}
{49201}{}{Несколько наложенных друг на друга листов металла.}
{49300}{}{Table}
{49301}{}{Похоже, этот стол потерял ножку.}
{49400}{}{Table}
{49401}{}{Похоже, этот стол потерял ножку.}
{49500}{}{Table}
{49501}{}{Старый облезший стол.}
{49600}{}{Table}
{49601}{}{Лучше не ставить на него ничего тяжелого.}
{49700}{}{Table}
{49701}{}{Кажется, он вот-вот сломается.}
{49800}{}{Тень}
{49900}{}{Кукуруза}
{49901}{}{Полезное культурное растение.}
{50000}{}{Кукуруза}
{50001}{}{Совсем маленький кустик.}
{50100}{}{Кукуруза}
{50101}{}{Вы очень любите кукурузный суп.}
{50200}{}{Кукуруза}
{50201}{}{Этому кустику еще расти и расти.}
{50300}{}{Кукуруза}
{50301}{}{Этому кустику еще расти и расти.}
{50400}{}{Кукуруза}
{50401}{}{Похоже этот початок почти созрел.}
{50500}{}{Въезд на парковку}
{50501}{}{Завал не разгрести.}
{50600}{}{Въезд на парковку}
{50601}{}{Завал не разгрести.}
{50700}{}{Стул}
{50701}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{50800}{}{Стул}
{50801}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{50900}{}{Булыжник}
{50901}{}{Обрушившаяся часть крыши образовала эту горку камня. Ваша веревка ведет обратно на поверхность.}
{51000}{}{Кукуруза}
{51001}{}{Эта кукурузина скоро будет готова к употреблению.}
{51100}{}{Wall}
{51200}{}{Шланг}
{51201}{}{Незаменимая вещь при поливе.}
{51300}{}{Кукуруза}
{51301}{}{Этому кустику еще расти и расти.}
{51400}{}{Столб}
{51500}{}{Шланг}
{51501}{}{Незаменимая вещь при поливе.}
{51600}{}{Стул}
{51601}{}{Выглядит крепким.}
{51700}{}{Стул}
{51701}{}{Выглядит крепким.}
{51800}{}{Стул}
{51801}{}{Выглядит крепким.}
{51900}{}{Стул}
{51901}{}{Выглядит крепким.}
{52000}{}{Bed}
{52001}{}{Лучше поспать на полу.}
{52100}{}{Тень}
{52200}{}{Стул}
{52201}{}{Потрепанный, но крепкий.}
{52300}{}{Вещи}
{52301}{}{Очень много коробок с каким-то ненужным хламом.}
{52400}{}{Верстак}
{52401}{}{Старый верстак, его, похоже, часто использовали.}
{52500}{}{Тень}
{52600}{}{Стул}
{52601}{}{Потрепанный, но крепкий.}
{52700}{}{Машина}
{52701}{}{Вы видите ведро с гайками - некогда отличный автомобиль.}
{52800}{}{Машина}
{52801}{}{Вы видите ведро с гайками - некогда отличный автомобиль.}
{52900}{}{Коробка}
{52901}{}{Пустая картонная коробка.}
{53000}{}{Коробка}
{53001}{}{Пустая картонная коробка.}
{53100}{}{Коробка}
{53101}{}{Пустая картонная коробка.}
{53200}{}{Коробка}
{53201}{}{Пустая картонная коробка.}
{53300}{}{Земля}
{53400}{}{Земля}
{53500}{}{Земля}
{53600}{}{Земля}
{53700}{}{Боксерская груша}
{53701}{}{Вам бы очень не хотелось оказаться на ее месте.}
{53800}{}{Коробка}
{53801}{}{Иногда коробки содержат ценные вещи, но не в этот раз.}
{53900}{}{Коробка}
{53901}{}{Иногда коробки содержат ценные вещи, но не в этот раз.}
{54000}{}{Коробка}
{54001}{}{Иногда коробки содержат ценные вещи, но не в этот раз.}
{54100}{}{Коробка}
{54101}{}{Иногда коробки содержат ценные вещи, но не в этот раз.}
{54200}{}{Штанга}
{54201}{}{Спортивный снаряд.}
{54300}{}{Штанга}
{54301}{}{Спортивный снаряд.}
{54400}{}{Junk}
{54401}{}{Похоже на часть коробки.}
{54500}{}{Junk}
{54501}{}{Этот мусор бесполезен.}
{54600}{}{Турник}
{54601}{}{Надежно закреплен в стене.}
{54700}{}{Турник}
{54701}{}{Надежно закреплен в стене.}
{54800}{}{Турник}
{54801}{}{Вы уже забыли, когда последний раз подтягивались.}
{54900}{}{Junk}
{54901}{}{Вы видите коробку в стадии полураспада.}
{55000}{}{Junk}
{55001}{}{Вы видите коробку в стадии полураспада.}
{55100}{}{Бетонные плиты}
{55101}{}{Тяжелые плиты, вросшие в землю.}
{55200}{}{Бетонные плиты}
{55201}{}{Тяжелые плиты, вросшие в землю.}
{55300}{}{Бетонные плиты}
{55301}{}{Тяжелые плиты, вросшие в землю.}
{55400}{}{Тень}
{55500}{}{Заложенная хламом дыра в стене}
{55501}{}{Несколько досок и мусор закрывают пролом в стене.}
{55600}{}{Заложенная хламом дыра в стене}
{55601}{}{Несколько досок и мусор закрывают пролом в стене.}
{55700}{}{Плакат}
{55701}{}{Старый плакат "счастливым быком".}
{55800}{}{Junk}
{55801}{}{Похоже на часть коробки.}
{55900}{}{Забор}
{55901}{}{Некогда красивая металлическая ограда.}
{56000}{}{Забор}
{56001}{}{Некогда красивая металлическая ограда.}
{56100}{}{Забор}
{56101}{}{Некогда красивая металлическая ограда.}
{56200}{}{Забор}
{56201}{}{Некогда красивая металлическая ограда.}
{56300}{}{Забор}
{56301}{}{Некогда красивая металлическая ограда.}
{56400}{}{Забор}
{56401}{}{Некогда красивая металлическая ограда.}
{56500}{}{Забор}
{56501}{}{Некогда красивая металлическая ограда.}
{56600}{}{Забор}
{56601}{}{Некогда красивая металлическая ограда.}
{56700}{}{Балка}
{56701}{}{Это прочная балка.}
{56800}{}{Дверь}
{56801}{}{Вход в здание завода.}
{56900}{}{Полки}
{56901}{}{Большие металлические полки.}
{57000}{}{Полки}
{57001}{}{Металлические полки, с виду крепкие и надежные.}
{57100}{}{Полки}
{57101}{}{Металлические полки, с виду крепкие и надежные.}
{57200}{}{Полки}
{57201}{}{Металлические полки, тут совсем нечего искать.}
{57300}{}{Куст}
{57301}{}{Пустынное растение. Для вас интереса не представляет.}
{57400}{}{Куст}
{57401}{}{Пустынное растение. Для вас интереса не представляет.}
{57500}{}{Куст}
{57501}{}{Пустынное растение. Для вас интереса не представляет.}
{57600}{}{Стог}
{57601}{}{Один из результатов работы слуг жизни.}
{57700}{}{Лопата}
{57701}{}{Главный инструмент для работы с землей.}
{57800}{}{Стог}
{57801}{}{Один из результатов работы слуг жизни.}
{57900}{}{Агрегат}
{57901}{}{Похоже переоборудован под самогонный аппарат.}
{58000}{}{Стог}
{58001}{}{Один из результатов работы слуг жизни.}
{58100}{}{Дверь}
{58101}{}{Надежная дверь из стальных прутьев.}
{58200}{}{Table}
{58201}{}{Стол с непонятными инструментами.}
{58300}{}{Ladder}
{58301}{}{Лестница, ведущая во мрак внизу.}
{58400}{}{Ladder}
{58401}{}{Лестница, ведущая во мрак внизу.}
{58500}{}{Цепи}
{58501}{}{Цепи заменяют канаты на этом ринге.}
{58600}{}{Цепи}
{58601}{}{Цепи заменяют канаты на этом ринге.}
{58700}{}{Цепи}
{58701}{}{Цепи заменяют канаты на этом ринге.}
{58800}{}{Цепи}
{58801}{}{Цепи заменяют канаты на этом ринге.}
{58900}{}{Цепи}
{58901}{}{Цепи заменяют канаты на этом ринге.}
{59000}{}{Хлам}
{59001}{}{Ничего интересного}
{59100}{}{Шины}
{59101}{}{Это основание ринга.}
{59200}{}{Шины}
{59201}{}{Это основание ринга.}
{59300}{}{Шины}
{59301}{}{Это основание ринга.}
{59400}{}{Шины}
{59401}{}{Это основание ринга.}
{59500}{}{Цепи}
{59501}{}{Цепи заменяют канаты на этом ринге.}
{59600}{}{Самогонный аппарат}
{59601}{}{Служит для производства спиртного.}
{59700}{}{Котел}
{59701}{}{Котел для производства "капли".}
{59800}{}{Wall}
{59900}{}{Wall}
{60000}{}{Wall}
{60100}{}{Junk}
{60101}{}{Части складских коробок.}
{60200}{}{Floor}
{60300}{}{Столы}
{60301}{}{Куча старых столов.}
{60400}{}{Table}
{60401}{}{Прекрасный образец деревянного стола.}
{60500}{}{Table}
{60501}{}{Прекрасный образец деревянного стола.}
{60600}{}{Сломанный стол}
{60601}{}{Вряд ли кому-то придет в голову использовать этот стол по назначению.}
{60700}{}{Сломанный стол}
{60701}{}{Когда-то это было столом.}
{60800}{}{Table}
{60801}{}{Добротный и надежный стол, хоть и ржавый.}
{60900}{}{Table}
{60901}{}{Отличный стол, выглядит почти как новый.}
{61000}{}{Table}
{61001}{}{Добротный и надежный стол, хоть и ржавый.}
{61100}{}{Table}
{61101}{}{Прекрасный образец деревянного стола.}
{61200}{}{Костер}
{61201}{}{Можно вечно смотреть, как горит огонь.}
{61300}{}{Зеркало}
{61301}{}{Смотрите на себя некоторое время.}
{61400}{}{Зеркало}
{61401}{}{Смотрите на себя некоторое время.}
{61500}{}{Wall}
{61501}{}{Участок стены с освещением.}
{61600}{}{Унитаз}
{61601}{}{Очень чистый.}
{61700}{}{Фонтан}
{61701}{}{Полуразрушенный городской фонтан.}
{61800}{}{Унитаз}
{61801}{}{Если бы вы коллекционировали унитазы, то это был бы прекрасный экземпляр.}
{61900}{}{Раковина}
{61901}{}{Обычная раковина.}
{62000}{}{Фонтан}
{62001}{}{Полуразрушенный городской фонтан.}
{62100}{}{Лежак}
{62101}{}{Он грязный и воняет.}
{62200}{}{Лежак}
{62201}{}{Старый прогнивший лежак.}
{62300}{}{Wall}
{62400}{}{Wall}
{62500}{}{Цепи}
{62501}{}{Цепи вместо канатов на этом ринге.}
{62600}{}{Цепи}
{62601}{}{Цепи вместо канатов на этом ринге.}
{62700}{}{Освещение}
{62701}{}{Вокруг распространяется тусклый свет.}
{62800}{}{Освещение}
{62801}{}{Вокруг распространяется тусклый свет.}
{62900}{}{Wall}
{63000}{}{Wall}
{63100}{}{Wall}
{63200}{}{Терминал}
{63300}{}{Терминал}
{63400}{}{Wall}
{63500}{}{Wall}
{63600}{}{Wall}
{63700}{}{Сиденье}
{63701}{}{Живое зеленое растение в качестве элемента декорации сиденья очень удивляет.}
{63800}{}{Сиденье}
{63801}{}{Живое зеленое растение в качестве элемента декорации сиденья очень удивляет.}
{63900}{}{Лежак}
{63901}{}{Подозрительные пятна на нем отбивают всякое желание прилечь.}
{64000}{}{Устройство}
{64001}{}{Какая-то сложная штука с непонятным назначением.}
{64100}{}{Земля}
{64200}{}{Земля}
{64300}{}{Земля}
{64400}{}{Земля}
{64500}{}{Дверь}
{64501}{}{Решетчатая дверь, хорошо подходит в качестве решетки в тюрьму.}
{64600}{}{Терминал управления лифтом}
{64601}{}{На нажатия не реагирует. Возможно, необходимо подать электричество.}
{64700}{}{Терминал управления лифтом}
{64701}{}{Похоже, он до сих пор работает.}
{64800}{}{Лежак}
{64801}{}{Старый и вонючий.}
{64900}{}{Лежак}
{64901}{}{Старый прогнивший лежак.}
{65000}{}{Floor}
{65100}{}{Вентиляция}
{65101}{}{Высокотехнологичная система очистки воздуха.}
{65200}{}{Вентиляция}
{65201}{}{Высокотехнологичная система очистки воздуха.}
{65300}{}{Лежак}
{65301}{}{Кормление живущих на нем насекомых не входит в Ваши планы.}
{65400}{}{Музыкальный автомат}
{65401}{}{До сих пор прекрасно работает.}
{65500}{}{Музыкальный автомат}
{65501}{}{Выбор песен выглядит не особенно разнообразным.}
{65600}{}{Скамья}
{65601}{}{Удобная скамья для отдыха.}
{65700}{}{Table}
{65701}{}{Часть сломанного стола.}
{65800}{}{Лежак}
{65801}{}{Дряхлый лежак, покрытый плесенью и странными пятнами.}
{65900}{}{Table}
{65901}{}{Сломанный стол, его часть.}
{66000}{}{Table}
{66001}{}{Прекрасно сделанный стол.}
{66100}{}{Опрокинутый стол}
{66101}{}{У него сломалась ножка.}
{66200}{}{Стул}
{66201}{}{С виду вполне надежный стул, хотя ножки немного заржавели.}
{66300}{}{Стул}
{66301}{}{Это стул, самый обычный стул.}
{66400}{}{Стул}
{66401}{}{Передняя ножка слегка погнулась, но стул выглядит вполне крепким.}
{66500}{}{Стул}
{66501}{}{Очень удобный предмет мебели.}
{66600}{}{Лежащий стул}
{66601}{}{Кто-то уронил стул.}
{66700}{}{Лежащий стул}
{66701}{}{Кажется, что он прилег отдохнуть.}
{66800}{}{Лежащий стул}
{66801}{}{Вам это вряд ли пригодится.}
{66900}{}{Лежащий стул}
{66901}{}{Кто-то уронил стул.}
{67000}{}{Кресло}
{67001}{}{Вашей пятой точке вряд ли понравится сидеть на кресле без сиденья.}
{67100}{}{Кресло}
{67101}{}{Оно неплохо сохранилось.}
{67200}{}{Кресло}
{67201}{}{Наверно его еще можно починить.}
{67300}{}{Кресло}
{67301}{}{Кажется, сиденье треснуло.}
{67400}{}{Кресло}
{67401}{}{Вы видите останки некогда удобного кресла.}
{67500}{}{Кресло}
{67501}{}{Интересно, куда делось сиденье.}
{67600}{}{Кресло}
{67601}{}{Если бы у кресел были скелеты, они выглядели бы именно так.}
{67700}{}{Хлам}
{67701}{}{Кажется, это когда-то было стулом.}
{67800}{}{Bed}
{67801}{}{Слишком грязная.}
{67900}{}{Шкаф}
{67901}{}{Там определенно ничего нет.}
{68000}{}{Bed}
{68001}{}{Почерневшая от грязи кровать.}
{68100}{}{Шкаф}
{68101}{}{Предмет мебели. Вряд ли тут что-то есть.}
{68200}{}{Печка}
{68201}{}{Похоже, она в рабочем состоянии.}
{68300}{}{Печка}
{68301}{}{Эта печка работает на дровах.}
{68400}{}{Печка}
{68401}{}{Вам сейчас некогда готовить.}
{68500}{}{Печка}
{68501}{}{В рабочем состоянии, работает на дровах.}
{68600}{}{Тень}
{68700}{}{Фонари}
{68701}{}{Два фонаря на проводах.}
{68800}{}{Фонари}
{68801}{}{Два фонаря на проводах.}
{68900}{}{Вход в пещеру}
{68901}{}{В пещерах обычно прохладно.}
{69000}{}{Столб}
{69001}{}{Обрубок столба.}
{69100}{}{Гора}
{69101}{}{Склоны горы выглядят неприступными.}
{69200}{}{Гора}
{69201}{}{Склоны горы выглядят неприступными.}
{69300}{}{Гора}
{69301}{}{Склоны горы выглядят неприступными.}
{69400}{}{Гора}
{69401}{}{Склоны горы выглядят неприступными.}
{69500}{}{Гора}
{69501}{}{Склоны горы выглядят неприступными.}
{69600}{}{Гора}
{69601}{}{Склоны горы выглядят неприступными.}
{69700}{}{Фонарь}
{69701}{}{Их использовали для освещения местности в темное время.}
{69800}{}{Фонарь}
{69801}{}{Их использовали для освещения местности в темное время.}
{69900}{}{Фонарь}
{69901}{}{Их использовали для освещения местности в темное время.}
{70000}{}{Фонарь}
{70001}{}{Их использовали для освещения местности в темное время.}
{70100}{}{Фонарь}
{70101}{}{Этому фонарю сильно досталось.}
{70200}{}{Фонарь}
{70201}{}{То, что осталось от фонаря.}
{70300}{}{Сиденье}
{70301}{}{Растение выглядит живым, неужели его кто-то поливает.}
{70400}{}{Труба}
{70401}{}{Повреждение на трубе.}
{70500}{}{Труба}
{70501}{}{Повреждение на трубе.}
{70600}{}{Труба}
{70601}{}{Повреждение на трубе.}
{70700}{}{Труба}
{70701}{}{Повреждение на трубе.}
{70800}{}{Table}
{70801}{}{Неплохой деревянный стол.}
{70900}{}{Table}
{70901}{}{Неплохой деревянный стол.}
{71000}{}{Table}
{71001}{}{Довольно грязный и, кажется, покрыт плесенью.}
{71100}{}{Освещение}
{71101}{}{Без него было бы совсем темно.}
{71200}{}{Table}
{71201}{}{Довольно грязный и, кажется, покрыт плесенью.}
{71300}{}{Опрокинутый стул}
{71301}{}{Барный стул без спинки.}
{71400}{}{Освещение}
{71401}{}{Без него было бы совсем темно.}
{71500}{}{Стул}
{71501}{}{Барный стул без спинки.}
{71600}{}{Вывеска}
{71601}{}{Вывеска сделана из частей машин, шин, и прочего хлама. Надпись: "Jackals" - шакалы.}
{71700}{}{Ladder}
{71701}{}{Большая лестница наверх.}
{71800}{}{Ladder}
{71801}{}{Большая лестница наверх.}
{71900}{}{Скамья}
{71901}{}{Каменная скамья - для суровых задниц.}
{72000}{}{Скамья}
{72001}{}{Чтобы сломать каменную скамью, нужно постараться.}
{72100}{}{Скамья}
{72101}{}{Каменная скамья, наверное, очень жесткая.}
{72200}{}{Скамья}
{72201}{}{Каменная скамья - для суровых задниц.}
{72300}{}{Скамья}
{72301}{}{Каменная скамья - для суровых задниц.}
{72400}{}{Вещи}
{72401}{}{Какие-то коробки - внутри ничего интересного.}
{72500}{}{Обломки стены}
{72501}{}{Обломки обрушенной стены.}
{72600}{}{Скамья}
{72601}{}{Слегка поврежденная каменная скамья.}
{72700}{}{Скамья}
{72701}{}{Каменная скамья, наверное, очень жесткая.}
{72800}{}{Опрокинутый стул}
{72801}{}{Барный стул без спинки.}
{72900}{}{Опрокинутый стул}
{72901}{}{Обычный барный стул, который кто-то уронил.}
{73000}{}{Table}
{73001}{}{Довольно грязный предмет мебели.}
{73100}{}{Вывеска}
{73101}{}{Вывеска сделана из частей машин, шин, и прочего хлама. Надпись: "Jackals" - шакалы.}
{73200}{}{Стул}
{73201}{}{Барный стул без спинки.}
{73300}{}{Вывеска}
{73301}{}{Вывеска сделана из частей машин, шин, и прочего хлама. Надпись: "Jackals" - шакалы.}
{73400}{}{Стул}
{73401}{}{Барный стул без спинки.}
{73500}{}{Стул}
{73501}{}{Барный стул без спинки.}
{73600}{}{Стул}
{73601}{}{Самый обычный стул без спинки.}
{73700}{}{Сломанный стул}
{73701}{}{Похоже, этот хлам когда-то был стулом, собранным из хлама.}
{73800}{}{Стул}
{73801}{}{Похоже, этот хлам когда-то был стулом, собранным из хлама.}
{73900}{}{Стул}
{73901}{}{Самодельный стул из хлама и частей машин.}
{74000}{}{Стул}
{74001}{}{Вы не испытываете особого интереса к самодельной мебели.}
{74100}{}{Стул}
{74101}{}{Самодельный стул из подручных материалов.}
{74200}{}{Стул}
{74201}{}{Сделан из хлама и частей машин.}
{74300}{}{Дерьмо}
{74301}{}{Лучше не наступать в это.}
{74400}{}{Дерьмо}
{74401}{}{Продукт чьей-то жизнедеятельности.}
{74500}{}{Дерьмо}
{74501}{}{Продукт чьей-то жизнедеятельности.}
{74600}{}{Дерьмо}
{74601}{}{Лучше не наступать в это.}
{74700}{}{Дерьмо}
{74701}{}{Небольшая кучка крайне ароматного дерьма.}
{74800}{}{Дерьмо}
{74801}{}{Небольшая кучка крайне ароматного дерьма.}
{74900}{}{Table}
{74901}{}{Стол с ободранной, поцарапанной поверхностью.}
{75000}{}{Table}
{75001}{}{Не самый чистый, но довольно крепкий стол.}
{75100}{}{Машина}
{75101}{}{Теперь это груда бесполезного ржавеющего металла.}
{75200}{}{Машина}
{75201}{}{Этот автомобиль отслужил свое очень и очень давно.}
{75300}{}{Машина}
{75301}{}{Починить эту рухлядь невозможно в принципе.}
{75400}{}{Машина}
{75401}{}{Этому металлолому уже не колесить по хайвеям.}
{75500}{}{Bed}
{75501}{}{Выглядит удобной, но спящий здесь не отличается чистоплотностью.}
{75600}{}{Bed}
{75601}{}{Выглядит удобной, но белье не помешало бы постирать.}
{75700}{}{Bed}
{75701}{}{Предмет мебели, предназначенный для сна и отдыха.}
{75800}{}{Bed}
{75801}{}{Если завернуться в простыню, можно изображать приведение.}
{75900}{}{Bed}
{75901}{}{Не время отдыхать.}
{76000}{}{Bed}
{76001}{}{Предмет мебели, предназначенный для сна и отдыха.}
{76100}{}{Коммуникации}
{76101}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{76200}{}{Коммуникации}
{76201}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{76300}{}{Коммуникации}
{76301}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{76400}{}{Коммуникации}
{76401}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{76500}{}{Коммуникации}
{76501}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{76600}{}{Коммуникации}
{76601}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{76700}{}{Floor}
{76800}{}{Бомба}
{76801}{}{Это ядерная бомба. Даже сидеть рядом очень опасно.}
{76900}{}{Подставка}
{76901}{}{На этой подставке и лежит ядерная бомба.}
{77000}{}{вычислительная Консоль}
{77001}{}{Это контрольный вычислитель.}
{77100}{}{Junk}
{77101}{}{Треснутые бутылки, осколки бутылок. Ничего ценного.}
{77200}{}{Опрокинутый стул}
{77201}{}{Если его поднять, то вполне можно сидеть.}
{77300}{}{Опрокинутый стул}
{77301}{}{Если его поднять, то вполне можно сидеть.}
{77400}{}{Опрокинутый стул}
{77401}{}{Зачем он вам? Пусть лежит.}
{77500}{}{Опрокинутый стул}
{77501}{}{Зачем он вам? Пусть лежит.}
{77600}{}{Опрокинутый стул}
{77601}{}{Зачем он вам? Пусть лежит.}
{77700}{}{Опрокинутый стул}
{77701}{}{Зачем он вам? Пусть лежит.}
{77800}{}{Опрокинутый стул}
{77801}{}{Кто-то уронил стул.}
{77900}{}{Опрокинутый стул}
{77901}{}{Кто-то уронил стул.}
{78000}{}{Опрокинутый стул}
{78001}{}{Мирно лежащий стул.}
{78100}{}{Стул}
{78101}{}{Ржавая ножка, лопнувшая обивка - этот стул не похож на удобный.}
{78200}{}{Стул}
{78201}{}{Ржавая ножка, лопнувшая обивка - этот стул не похож на удобный.}
{78300}{}{Стул}
{78301}{}{Он свое отслужил.}
{78400}{}{Оборудование}
{78401}{}{Какое-то техническое оборудование.}
{78500}{}{Оборудование}
{78501}{}{Какое-то техническое оборудование.}
{78600}{}{Оборудование}
{78601}{}{Некое техническое оборудование в заржавевшей стойке.}
{78700}{}{Оборудование}
{78701}{}{Стойка с каким-то техническим оборудованием.}
{78800}{}{Оборудование}
{78801}{}{Некое техническое оборудование.}
{78900}{}{Оборудование}
{78901}{}{Некое техническое оборудование в заржавевшей стойке.}
{79000}{}{Оборудование}
{79001}{}{Какое-то оборудование с неизвестным Вам назначением.}
{79100}{}{Оборудование}
{79101}{}{Эту стойку с оборудованием сильно помяли, вряд ли оно теперь может работать.}
{79200}{}{Окно}
{79201}{}{Очень грязное.}
{79300}{}{Окно}
{79301}{}{Вы даже можете увидеть чудом сохранившиеся стекла.}
{79400}{}{Окно}
{79401}{}{Очень грязное.}
{79500}{}{Окно}
{79501}{}{Вы даже можете увидеть чудом сохранившиеся стекла.}
{79600}{}{Table}
{79601}{}{Его конечно можно починить, но Вам это не нужно.}
{79700}{}{Table}
{79701}{}{Немного помятый, но в общем неплохой стол.}
{79800}{}{Стул}
{79801}{}{Несмотря на ржавую ножку, этот стул еще может послужить.}
{79900}{}{Стул}
{79901}{}{Несмотря на ржавую ножку, этот стул еще может послужить.}
{80000}{}{Стул}
{80001}{}{Обычный стул со спинкой.}
{80100}{}{Стул}
{80101}{}{Несмотря на ржавую ножку, этот стул еще может послужить.}
{80200}{}{Стул}
{80201}{}{Как умели, так и починили.}
{80300}{}{Стул}
{80301}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{80400}{}{Стул}
{80401}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{80500}{}{Стул}
{80501}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{80600}{}{Стул}
{80601}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{80700}{}{Стул}
{80701}{}{От этого стула мало что осталось.}
{80800}{}{Опрокинутый стул}
{80801}{}{Это самый обычный стул, наверное, прилег отдохнуть.}
{80900}{}{Стул}
{80901}{}{Теперь это просто хлам.}
{81000}{}{Стул}
{81001}{}{Мирно лежащий на боку стул.}
{81100}{}{Стул}
{81101}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{81200}{}{Стул}
{81201}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{81300}{}{Стул}
{81301}{}{Четыре ножки, сиденье и спинка - похоже перед Вами обычный стул.}
{81400}{}{Вычислитель}
{81401}{}{Обыкновенный вычислитель.}
{81500}{}{Вычислитель}
{81501}{}{Обыкновенный вычислитель.}
{81600}{}{Оборудование}
{81601}{}{Некое техническое оборудование с неизвестным Вам назначением.}
{81700}{}{Вычислитель}
{81701}{}{Кажется, он выключен.}
{81800}{}{Вычислитель.}
{81801}{}{Обыкновенный вычислитель.}
{81900}{}{Вычислитель.}
{81901}{}{Кажется, он выключен.}
{82000}{}{Вычислитель.}
{82001}{}{Большой и сложный вычислитель с какими-то рычагами.}
{82100}{}{Вычислитель.}
{82101}{}{Большой и сложный вычислитель с какими-то рычагами.}
{82200}{}{Трубки}
{82201}{}{Узел из трубок, какие-то коммуникации.}
{82300}{}{Трубки}
{82301}{}{Узел из трубок, какие-то коммуникации.}
{82400}{}{Table с приборами}
{82401}{}{Кажется в колбах какие-то химические составы. Не стоит трогать незнакомые жидкости.}
{82500}{}{Wall}
{82600}{}{Дверь машины}
{82601}{}{Точнее того, что от нее осталось}
{82700}{}{Бочка}
{82701}{}{Обыкновенная металлическая бочка.}
{82800}{}{Бочка}
{82801}{}{Бочка с неизвестным содержимым.}
{82900}{}{Стул}
{82901}{}{Замечательный барный стул.}
{83000}{}{Осветительная панель}
{83001}{}{Служит для преобразования электрической энергии в световую. Да, прочитанный в детстве старииный учебник по физике иногда напоминает о себе.}
{83100}{}{Плита}
{83101}{}{Разбитый пол.}
{83200}{}{Плита}
{83201}{}{Разбитый пол.}
{83300}{}{Плита}
{83301}{}{Разбитый пол.}
{83400}{}{Плита}
{83401}{}{Разбитый пол.}
{83500}{}{Плита}
{83501}{}{Разбитый пол.}
{83600}{}{Опорная конструкция}
{83601}{}{Разваливается на глазах.}
{83700}{}{Склон}
{83701}{}{Крутой спуск вниз.}
{83800}{}{Склон}
{83801}{}{Крутой спуск вниз.}
{83900}{}{Склон}
{83901}{}{Крутой спуск вниз.}
{84000}{}{Склон}
{84001}{}{Крутой спуск вниз.}
{84100}{}{Склон}
{84101}{}{Крутой спуск вниз.}
{84200}{}{Склон}
{84201}{}{Крутой спуск вниз.}
{84300}{}{Склон}
{84301}{}{Крутой спуск вниз.}
{84400}{}{Склон}
{84401}{}{Крутой спуск вниз.}
{84500}{}{Склон}
{84501}{}{Причудливое природное образование.}
{84600}{}{Склон}
{84601}{}{Причудливое природное образование.}
{84700}{}{Склон}
{84701}{}{Причудливое природное образование.}
{84800}{}{Дверь}                                          
{84801}{}{Обычная деревянная дверь.}
{84900}{}{Дверь}
{84901}{}{Обычная деревянная дверь.}
{85000}{}{Дверь}
{85001}{}{Краска почти слезла, а дерево покрыл грибок.}
{85100}{}{Table}
{85101}{}{Похоже, эта тряпка выполняет роль скатерти.}
{85200}{}{Склон}
{85201}{}{Причудливое природное образование.}
{85300}{}{Бочка}
{85301}{}{Пустая емкость для хранения топлива.}
{85400}{}{Труба}
{85401}{}{Участок трубы.}
{85500}{}{Склон}
{85501}{}{Крутой спуск вниз.}
{85600}{}{Сторожевая вышка}
{85601}{}{Вышка сколочена из чего попало, но оснащена оружием.}
{85700}{}{Wall}
{85800}{}{Инструменты}
{85801}{}{Какие-то ненужные Вам инструменты.}
{85900}{}{Wall}
{86000}{}{Механизм}
{86001}{}{Этот механизм задействован в обработке воды.}
{86100}{}{Механизм}
{86101}{}{Этот механизм задействован в обработке воды.}
{86200}{}{Механизм}
{86201}{}{Этот механизм задействован в обработке воды.}
{86300}{}{Труба}
{86301}{}{Участок трубы.}
{86400}{}{Труба}
{86401}{}{Участок трубы.}
{86500}{}{Wall}
{86600}{}{Wall}
{86700}{}{Wall}
{86800}{}{Wall}
{86900}{}{Ограждение}
{86901}{}{С этого металлического ограждения почти слезла краска, но оно в отличном состоянии.}
{87000}{}{Ограждение}
{87001}{}{С этого металлического ограждения почти слезла краска, но оно в отличном состоянии.}
{87100}{}{Ограждение}
{87101}{}{Обычное металлическое ограждение.}
{87200}{}{Ограждение}
{87201}{}{Металлическое ограждение.}
{87300}{}{Ограждение}
{87301}{}{С этого металлического ограждения почти слезла краска, но оно в отличном состоянии.}
{87400}{}{Ограждение}
{87401}{}{Сваленное металлическое ограждение.}
{87500}{}{Ограждение}
{87501}{}{Металлическое ограждение, лежащее на земле.}
{87600}{}{Ограждение}
{87601}{}{Помятое металлическое ограждение.}
{87700}{}{Ограждение}
{87701}{}{Сильно помятое металлическое ограждение.}
{87800}{}{Плитка}
{87801}{}{Разбитый пол.}
{87900}{}{Плитка}
{87901}{}{Разбитый пол.}
{88000}{}{Junk}
{88001}{}{Совершенно ничего интересного.}
{88100}{}{Земля}
{88101}{}{Кажется с фрагментами досок, но точнее сказать сложно.}
{88200}{}{Junk}
{88201}{}{Похоже на части коробок.}
{88300}{}{Junk}
{88301}{}{Совершенно ничего интересного.}
{88400}{}{Junk}
{88401}{}{Части складских коробок.}
{88500}{}{Junk}
{88501}{}{Совершенно ничего интересного.}
{88600}{}{Унитаз}
{88601}{}{Он настолько грязный, что Вы предпочтете сделать свои дела на свежем воздухе.}
{88700}{}{Table}
{88701}{}{Пустые грязные бутылки, остатки еды. Вам здесь явно нечем поживиться.}
{88800}{}{Лист металла}
{88801}{}{Ржавый с обеих сторон.}
{88900}{}{Лист металла}
{88901}{}{Ржавый с обеих сторон.}
{89000}{}{Junk}
{89001}{}{Какой-то ненужный мусор.}
{89100}{}{Junk}
{89101}{}{Какой-то ненужный мусор.}
{89200}{}{Junk}
{89201}{}{Похоже на часть коробки.}
{89300}{}{Унитаз}
{89301}{}{Похоже, его не мыли очень давно.}
{89400}{}{Лежак}
{89401}{}{Старый и не особенно чистый лежак.}
{89500}{}{Лежак}
{89501}{}{Лучше спать на кирпичах, чем на этом.}
{89600}{}{Станок}
{89601}{}{Высокий станок для обработки различных материалов.}
{89700}{}{Станок}
{89701}{}{Большой станок для обработки твердых материалов.}
{89800}{}{Столб с прожекторами}
{89801}{}{Самодельный предмет для освещения местности.}
{89900}{}{Столб с прожекторами}
{89901}{}{Самодельный предмет для освещения местности.}
{90000}{}{Столб с прожекторами}
{90001}{}{Самодельный предмет для освещения местности.}
{90100}{}{Лежак}
{90101}{}{Наверное, кто-то на нем спит.}
{90200}{}{Лежак}
{90201}{}{Если прилечь на такой лежак, то наверняка можно подцепить пару неприятных болячек.}
{90300}{}{Лежак}
{90301}{}{Вам не хочется рассматривать эти странные пятна.}
{90400}{}{Топливный фильтр}
{90401}{}{Устройство для фильтрации топлива.}
{90500}{}{Хлам}
{90501}{}{Части коробок или ящиков.}
{90600}{}{Части Силовых Доспехов}
{90601}{}{Эти части подходят к Силовым Доспехам.}
{90700}{}{Хлам}
{90701}{}{Не представляющий интереса мусор.}
{90800}{}{Хлам}
{90801}{}{Не представляющий интереса мусор.}
{90900}{}{Оградительный конус}
{90901}{}{Из него получилась бы очень забавная шляпа.}
{91000}{}{Оградительный конус}
{91001}{}{Из него получилась бы очень забавная шляпа.}
{91100}{}{Оградительный конус}
{91101}{}{Если надеть такие конусы на голову, руки и ноги, то получится морская звезда. Вы видели такую в книжке.}
{91200}{}{Оградительный конус}
{91201}{}{Если надеть такие конусы на голову, руки и ноги, то получится морская звезда. Вы видели такую в книжке.}
{91300}{}{Оградительный конус}
{91301}{}{Раньше такими обозначали места для парковки.}
{91400}{}{Оградительный конус}
{91401}{}{В нем можно носить, к примеру, воду.}
{91500}{}{Оградительный конус}
{91501}{}{Сидеть на таком, наверное, крайне неудобно.}
{91600}{}{Оградительный конус}
{91601}{}{Раньше такими обозначали места для парковки.}
{91700}{}{Части ящиков}
{91800}{}{Части коробок}
{91900}{}{Хлам}
{92000}{}{Части коробок}
{92100}{}{Части коробок или ящиков}
{92200}{}{Части ящиков}
{92300}{}{Вещи}
{92301}{}{За копание в чужих вещах можно схлопотать по жизненно важным органам. Поэтому не стоит их трогать.}
{92400}{}{Вещи}
{92401}{}{Такое чувство, что хозяин этих вещей распихивал по коробкам мусор.}
{92500}{}{Коммуникации}
{92501}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{92600}{}{Коммуникации}
{92601}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{92700}{}{Коммуникации}
{92701}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{92800}{}{Коммуникации}
{92801}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{92900}{}{Коммуникации}
{92901}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{93000}{}{Коммуникации}
{93001}{}{Здесь расположены выводы труб, кабелей, какие-то агрегаты и прочее оборудование.}
{93100}{}{Тень}
{93200}{}{Танк}
{93201}{}{Старый танк очень "веселенькой" расцветочки.}
{93300}{}{Тень}
{93301}{}{Тень от танка.}
{93400}{}{Стул и столик с зонтиком}
{93401}{}{Похоже, на этом танке можно отдохнуть с комфортом.}
{93500}{}{Бетонный блок}
{93501}{}{Блок выглядит неподъемным.}
{93600}{}{Камни}
{93601}{}{Куча камней.}
{93700}{}{Повозка}
{93701}{}{Накрытая зеленым тентом повозка.}
{93800}{}{Торговая лавка.}
{93801}{}{Кажется, тут можно приобрести броню.}
{93900}{}{Торговая лавка}
{93901}{}{Обычно в таких местах можно что-то купить. Конечно, если Вам есть, чем платить.}
{94000}{}{Торговая лавка}
{94001}{}{Богатый выбор оружия.}
{94100}{}{Торговая лавка}
{94101}{}{Богатый выбор оружия.}
{94200}{}{Торговая лавка}
{94201}{}{Богатый выбор оружия.}
{94300}{}{Бутылки}
{94301}{}{Не надейтесь, они абсолютно пустые и битые.}
{94400}{}{Лист металла}
{94401}{}{Это можно назвать просто обыкновенным хламом.}
{94500}{}{Лист металла}
{94501}{}{Это можно назвать просто обыкновенным хламом.}
{94600}{}{Лист металла}
{94601}{}{Это можно назвать просто обыкновенным хламом.}
{94700}{}{Лист металла}
{94701}{}{Это можно назвать просто обыкновенным хламом.}
{94800}{}{Лист металла}
{94801}{}{Это можно назвать просто обыкновенным хламом.}
{94900}{}{Лист металла}
{94901}{}{Это можно назвать просто обыкновенным хламом.}
{95000}{}{Дыра}
{95001}{}{Подозрительная дыра в стене.}
{95100}{}{Доски}
{95101}{}{Несколько прогнивших досок}
{95200}{}{Доски}
{95201}{}{Несколько прогнивших досок}
{95300}{}{Доски}
{95301}{}{Несколько прогнивших досок}
{95400}{}{Дверь}
{95401}{}{Двухстворчатая дверь.}
{95500}{}{Дверь}
{95501}{}{Самая обычная дверь.}
{95600}{}{Дверь}
{95601}{}{Это замечательное изобретение человечества может открываться и закрываться.}
{95700}{}{Дверь}
{95701}{}{Это замечательное изобретение человечества может открываться и закрываться.}
{95800}{}{Дверь}
{95801}{}{Это замечательное изобретение человечества может открываться и закрываться.}
{95900}{}{Дверь}
{95901}{}{Это замечательное изобретение человечества может открываться и закрываться.}
{96000}{}{Дверь}
{96001}{}{Самая обычная дверь.}
{96100}{}{Дверь}
{96101}{}{Обычная деревянная дверь.}
{96200}{}{Шлагбаум}
{96201}{}{Поднимается вверх и опускается вниз.}
{96300}{}{Костер}
{96301}{}{Можно вечно смотреть, как горит огонь.}
{96400}{}{Лежак}
{96401}{}{Вы бы многое отдали, чтобы не ложиться на него.}
{96500}{}{Опорная конструкция}
{96501}{}{Разваливается на глазах.}
{96600}{}{Cave Wall}
{96601}{}{Похоже, тут что-то завалено. Но Вам некогда заниматься раскопками.}
{96700}{}{Cave Wall}
{96701}{}{Похоже, тут что-то завалено. Но Вам некогда заниматься раскопками.}
{96800}{}{Cave Wall}
{96801}{}{Похоже на завал.}
{96900}{}{Wall}
{97000}{}{Wall}
{97100}{}{Wall}
{97200}{}{Wall}
{97201}{}{Трещина в стене.}
{97300}{}{Cave Wall}
{97400}{}{Cave Wall}
{97500}{}{Бочки}
{97501}{}{Пустые емкости для хранения топлива.}
{97600}{}{Бак}
{97601}{}{Бак с запасом воды.}
{97700}{}{Ladder}
{97701}{}{Прочная металлическая лестница.}
{97800}{}{Дверь}
{97900}{}{Вещи}
{97901}{}{В этой куче, как ни удивительно, ничего ценного для вас нет.}
{98000}{}{Бочки}
{98001}{}{Пустые емкости для хранения топлива.}
{98100}{}{Вонючий труп}
{98101}{}{Труп чернокожего мужчины. Не просто труп - настоящее пиршество для мух!}
{98200}{}{Дверь}
{98300}{}{Дверь}
{98400}{}{Дверь}
{98500}{}{Освещение}
{98501}{}{Прикрепленный к столбу фонарь.}
{98600}{}{Освещение}
{98601}{}{Прикрепленный к столбу фонарь.}
{98700}{}{Освещение}
{98701}{}{Прикрепленный к столбу фонарь.}
{98800}{}{Освещение}
{98801}{}{Прикрепленный к столбу фонарь.}
{98900}{}{Тень}
{99000}{}{Тень}
{99100}{}{Мусорный кран}
{99200}{}{Мусорный кран}
{99300}{}{Колодец}
{99400}{}{Колодец}
{99500}{}{Внешнее сооружение}
{99600}{}{Лежак}
{99601}{}{Старый вонючий лежак.}
{99700}{}{Лежак}
{99701}{}{Этот лежак совсем прогнил.}
{99800}{}{Лежак}
{99801}{}{Обычный лежак, на таких люди как правило спят.}
{99900}{}{Лежак}
{99901}{}{Эти подозрительные пятна Вам не нравятся.}
{100000}{}{Самогонный аппарат}
{100001}{}{Похоже, это самогонный аппарат на дровах.}
{100100}{}{Лежак}
{100101}{}{Старый прогнивший лежак.}
{100200}{}{Лежак}
{100201}{}{Старый прогнивший лежак.}
{100300}{}{Лежак}
{100301}{}{Вонючий лежак, не располагает к отдыху.}
{100400}{}{Лежак}
{100401}{}{Кажется на нем чья-то кровь.}
{100500}{}{Лежак}
{100501}{}{Лучше спать на кирпичах, чем на этом.}
{100600}{}{Лежак}
{100601}{}{Старый прогнивший лежак.}
{100700}{}{Насосный Прибор для Электростанции}
{100701}{}{Это охлаждающий насос}
{100800}{}{Часть Брамина}
{100900}{}{Автомобиль}
{101000}{}{Крайслер}
{101001}{}{Этот Хайвеймен похоже в очень хорошей форме для своего возраста.}
{101100}{}{Машина}
{101200}{}{Кладбище}
{101201}{}{Могила находится здесь.}
{101300}{}{Могильный камень}
{101301}{}{Старое надгробие с полустертой надписью.}
{101400}{}{Могильный камень}
{101401}{}{Вряд ли Вы когда-нибудь удостоитесь такого. Хотя Вам будет уже все равно.}
{101500}{}{Могильный камень}
{101501}{}{Вряд ли Вы когда-нибудь удостоитесь такого. Хотя Вам будет уже все равно.}
{101600}{}{Могильный камень}
{101601}{}{Старое надгробие с полустертой надписью.}
{101700}{}{Вывеска}
{101701}{}{"Новый мировой порядок".}
{101800}{}{Вывеска}
{101801}{}{"Новый мировой порядок".}
{101900}{}{Экран}
{101901}{}{Вы бы с удовольствием что-нибудь на таком посмотрели, но не знаете как.}
{102000}{}{Экран}
{102001}{}{Вы бы с удовольствием что-нибудь на таком посмотрели, но не знаете как.}
{102100}{}{Бутыли с самогоном}
{102101}{}{Похоже, здесь ценится их содержимое. Но вам все равно их не унести.}
{102200}{}{Большой бак с водой}
{102201}{}{Слегка проржавевший бак для хранения воды.}
{102300}{}{Трубы}
{102301}{}{Немного проржавевшие трубы.}
{102400}{}{Трубы}
{102401}{}{Немного проржавевшие трубы.}
{102500}{}{Трубы}
{102501}{}{Немного проржавевшие трубы.}
{102600}{}{Трубы}
{102601}{}{Немного проржавевшие трубы}
{102700}{}{Трубы}
{102701}{}{Немного проржавевшие трубы}
{102800}{}{Трубы}
{102801}{}{Немного проржавевшие трубы}
{102900}{}{Бордюр}
{102901}{}{Отделяет обочину от дороги.}
{103000}{}{Бордюр}
{103001}{}{Отделяет обочину от дороги.}
{103100}{}{Бордюр}
{103101}{}{Отделяет обочину от дороги.}
{103200}{}{Бордюр}
{103201}{}{Отделяет обочину от дороги.}
{103300}{}{Бордюр}
{103301}{}{Когда-то это было бордюром.}
{103400}{}{Бордюр}
{103401}{}{Точнее его обломки.}
{103500}{}{Бордюр}
{103501}{}{Точнее его обломки.}
{103600}{}{Бордюр}
{103601}{}{Точнее его обломки.}
{103700}{}{Бордюр}
{103701}{}{Точнее его обломки.}
{103800}{}{Бордюр}
{103801}{}{Точнее его обломки.}
{103900}{}{Бордюр}
{103901}{}{Отделяет обочину от дороги.}
{104000}{}{Бордюр}
{104001}{}{Точнее его обломки.}
{104100}{}{Бордюр}
{104101}{}{Отделяет обочину от дороги.}
{104200}{}{Бордюр}
{104201}{}{Точнее его обломки.}
{104300}{}{Бордюр}
{104301}{}{Точнее его обломки.}
{104400}{}{Вещи}
{104401}{}{Различное барахло. Там нет ничего ценного для Вас.}
{104500}{}{Вещи}
{104501}{}{Различное барахло. Ничего интересного там нет.}
{104600}{}{Вещи}
{104601}{}{Различное барахло. Ничего интересного там нет.}
{104700}{}{Вещи}
{104701}{}{Различное барахло. Ничего интересного там нет.}
{104800}{}{Вещи}
{104801}{}{Различное барахло. Ничего интересного там нет.}
{104900}{}{Вещи}
{104901}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105000}{}{Вещи}
{105001}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105100}{}{Вещи}
{105101}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105200}{}{Вещи}
{105201}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105300}{}{Вещи}
{105301}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105400}{}{Останки автомобиля}
{105401}{}{Передняя часть старого разбитого автомобиля.}
{105500}{}{Вещи}
{105501}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105600}{}{Хлам}
{105601}{}{Кажется когда-то это было машиной.}
{105700}{}{Вещи}
{105701}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105800}{}{Вещи}
{105801}{}{Различное барахло. Там нет ничего ценного для Вас.}
{105900}{}{Вещи}
{105901}{}{Различное барахло. Там нет ничего ценного для Вас.}
{106000}{}{Вещи}
{106001}{}{Различное барахло. Там нет ничего ценного для Вас.}
{106100}{}{Вещи}
{106101}{}{Различное барахло. Там нет ничего ценного для Вас.}
{106200}{}{Окно}
{106201}{}{Непробиваемое стекло. Даже не пытайтесь.}
{106300}{}{Окно}
{106301}{}{Непробиваемое стекло. Даже не пытайтесь.}
{106400}{}{Агрегат}
{106401}{}{Прикрепленный к баку агрегат.}
{106500}{}{Агрегат}
{106501}{}{Прикрепленный к баку агрегат.}
{106600}{}{Плакат}
{106601}{}{Ободранный настенный плакат.}
{106700}{}{Плакат}
{106701}{}{Ободранный настенный плакат.}
{106800}{}{Ящик}
{106801}{}{Вам очень интересно, что будет, если поместить внутрь радиоактивное вещество, пузырек с ядом и, например, кота.}
{106900}{}{Ящик}
{106901}{}{Вам очень интересно, что будет, если поместить внутрь радиоактивное вещество, пузырек с ядом и, например, кота.}
{107000}{}{Ящик}
{107001}{}{Вам очень интересно, что будет, если поместить внутрь радиоактивное вещество, пузырек с ядом и, например, кота.}
{107100}{}{Ящик}
{107101}{}{Этот ящик определенно пуст.}
{107200}{}{Ящик}
{107201}{}{Вам очень интересно, что будет, если поместить внутрь радиоактивное вещество, пузырек с ядом и, например, кота.}
{107300}{}{Ящик}
{107301}{}{Небольшой, но вместительный ящичек.}
{107400}{}{Ящик}
{107401}{}{Этот ящик определенно пуст.}
{107500}{}{Ящик}
{107501}{}{Небольшой, но вместительный ящичек.}
{107600}{}{Ящик}
{107601}{}{Небольшой, но вместительный ящичек.}
{107700}{}{Ящик}
{107701}{}{Этот ящик определенно пуст.}
{107800}{}{Ящик}
{107801}{}{Небольшой, но вместительный ящичек.}
{107900}{}{Ящик}
{107901}{}{Небольшой, но вместительный ящичек.}
{108000}{}{Ящик}
{108001}{}{Небольшой, но вместительный ящичек.}
{108100}{}{Ящик}
{108101}{}{Вы почему-то не можете не думать о котах, глядя на эти ящики.}
{108200}{}{Ящик}
{108201}{}{Небольшой, но вместительный ящичек.}
{108300}{}{Ящик}
{108301}{}{Небольшой, но вместительный ящичек.}
{108400}{}{Ящик}
{108401}{}{Небольшой, но вместительный ящичек.}
{108500}{}{Ящик}
{108501}{}{Небольшой, но вместительный ящичек.}
{108600}{}{Ящик}
{108601}{}{Небольшой, но вместительный ящичек.}
{108700}{}{Ящик}
{108701}{}{Вы почему-то не можете не думать о котах, глядя на эти ящики.}
{108800}{}{Ящик}
{108801}{}{Небольшой, но вместительный ящичек.}
{108900}{}{Ящик}
{108901}{}{Небольшой, но вместительный ящичек.}
{109000}{}{Ящик}
{109001}{}{Небольшой, но вместительный ящичек.}
{109100}{}{Трубы}
{109101}{}{Участок массивной трубы.}
{109200}{}{Трубы}
{109201}{}{Участок массивной трубы.}
{109300}{}{Трубы}
{109301}{}{Участок массивной трубы.}
{109400}{}{Ящик}
{109401}{}{Небольшой, но вместительный ящичек.}
{109500}{}{Ящик}
{109501}{}{Небольшой, но вместительный ящичек.}
{109600}{}{Ящик}
{109601}{}{Небольшой, но вместительный ящичек.}
{109700}{}{Ящик}
{109701}{}{Небольшой, но вместительный ящичек.}
{109800}{}{Ящик}
{109801}{}{Небольшой, но вместительный ящичек.}
{109900}{}{Ящик}
{109901}{}{Вы почему-то не можете не думать о котах, глядя на эти ящики.}
{110000}{}{Ящик}
{110001}{}{Небольшой, но вместительный ящичек.}
{110100}{}{Ящик}
{110101}{}{Небольшой, но вместительный ящичек.}
{110200}{}{Горящая бочка}
{110201}{}{В этой бочке сгорает мусор.}
{110300}{}{Трубы}
{110301}{}{Участок массивной трубы.}
{110400}{}{Бак с водой}
{110401}{}{Очевидно в нем запасы воды.}
{110500}{}{Трубы}
{110501}{}{Участок массивной трубы.}
{110600}{}{Трубы}
{110601}{}{Участок массивной трубы.}
{110700}{}{Трубы}
{110701}{}{Участок массивной трубы.}
{110800}{}{Трубы}
{110801}{}{Участок массивной трубы.}
{110900}{}{Бак с водой}
{110901}{}{Очевидно в нем запасы воды.}
{111000}{}{Хлам}
{111001}{}{Разодранная коробка.}
{111100}{}{Бочка}
{111101}{}{Просто металлическая бочка.}
{111200}{}{Бочка}
{111201}{}{Просто металлическая бочка.}
{111300}{}{Бочка}
{111301}{}{Просто металлическая бочка.}
{111400}{}{Бетонный блок}
{111401}{}{Выглядит очень тяжелым.}
{111500}{}{Бак}
{111501}{}{Емкость, в которой, как правило, хранят запасы воды.}
{111600}{}{Бак}
{111601}{}{Емкость, в которой, как правило, хранят запасы воды.}
{111700}{}{Бочки}
{111701}{}{Пустые металлические бочки.}
{111800}{}{Насосный агрегат}
{111801}{}{Сложный массивный насос, выкачивающий и фильтрующий воду из глубинных слоев земли.}
{111900}{}{Бочка}
{111901}{}{Пустая металлическая бочка.}
{112000}{}{Бетонный блок}
{112001}{}{Выглядит очень тяжелым.}
{112100}{}{Бочки}
{112101}{}{Пустые металлические бочки.}
{112200}{}{Ограждение}
{112201}{}{Аварийное ограждение.}
{112300}{}{Ограждение}
{112301}{}{Аварийное ограждение.}
{112400}{}{Бетонный блок}
{112401}{}{Выглядит очень тяжелым.}
{112500}{}{Бетонный блок}
{112501}{}{Выглядит очень тяжелым.}
{112600}{}{Ящик}
{112601}{}{Огромный деревянный ящик.}
{112700}{}{Бетонный блок}
{112701}{}{Выглядит очень тяжелым.}
{112800}{}{Тень}
{112900}{}{Ящик}
{112901}{}{Огромный деревянный ящик.}
{113000}{}{Доска}
{113001}{}{Не представляет для вас интереса.}
{113100}{}{Доска}
{113101}{}{Не представляет для вас интереса.}
{113200}{}{Бочка}
{113201}{}{Пустая металлическая бочка.}
{113300}{}{Бочка}
{113301}{}{Пустая металлическая бочка.}
{113400}{}{Мешки с песком}
{113401}{}{Военная фортификация.}
{113500}{}{Мешки с песком}
{113501}{}{Военная фортификация.}
{113600}{}{Мешки с песком}
{113601}{}{Военная фортификация.}
{113700}{}{Мешки с песком}
{113701}{}{Военная фортификация.}
{113800}{}{Мешки с песком}
{113801}{}{Военная фортификация.}
{113900}{}{Тень}
{114000}{}{Мешки с песком}
{114001}{}{Военная фортификация.}
{114100}{}{Мешки с песком}
{114101}{}{Военная фортификация.}
{114200}{}{Мешки с песком}
{114201}{}{Военная фортификация.}
{114300}{}{Мешки с песком}
{114301}{}{Военная фортификация.}
{114400}{}{Мешки с песком}
{114401}{}{Военная фортификация.}
{114500}{}{Мешки с песком}
{114501}{}{Военная фортификация.}
{114600}{}{Мешки с песком}
{114601}{}{Военная фортификация.}
{114700}{}{Мешки с песком}
{114701}{}{Военная фортификация.}
{114800}{}{Мешки с песком}
{114801}{}{Военная фортификация.}
{114900}{}{Мешки с песком}
{114901}{}{Военная фортификация.}
{115000}{}{Хлам}
{115001}{}{Картонная коробка.}
{115100}{}{Хлам}
{115101}{}{Мятая картонная коробка и прочий бесполезный хлам.}
{115200}{}{Минерная повозка}
{115300}{}{Минерная повозка со стальным столбом}
{115400}{}{Минерная повозка с динамитом}
{115500}{}{Мешки с песком}
{115501}{}{Военная фортификация.}
{115600}{}{Ящик}
{115601}{}{Огромный деревянный ящик.}
{115700}{}{Ящик}
{115701}{}{Огромный деревянный ящик.}
{115800}{}{Хлам}
{115900}{}{Wall}
{116000}{}{Wall}
{116100}{}{Сетчатый Сканнер}
{116101}{}{Это устройство безопасности, которое сканирует сетчатку глаза человека.}
{116200}{}{Ящик}
{116201}{}{Небольшой, но вместительный ящичек яркой расцветки.}
{116300}{}{Ящик}
{116301}{}{Небольшой, но вместительный ящичек.}
{116400}{}{Ящик}
{116401}{}{Небольшой, но вместительный ящичек.}
{116500}{}{Ящик}
{116501}{}{Небольшой, но вместительный ящичек.}
{116600}{}{Ящик}
{116601}{}{Ящичек определенно пуст.}
{116700}{}{Тень}
{116701}{}{Ничего необычного.}
{116800}{}{Хлам}
{116801}{}{Какой-то мусор.}
{116900}{}{Дверь}
{117000}{}{Дверь}
{117100}{}{Хлам}
{117101}{}{Часть разломанного ящика.}
{117200}{}{Хлам}
{117201}{}{Бесполезный мусор.}
{117300}{}{Хлам}
{117301}{}{Бесполезный мусор.}
{117400}{}{Хлам}
{117401}{}{Бесполезный мусор.}
{117500}{}{Хлам}
{117501}{}{Бесполезный мусор.}
{117600}{}{Конвейер}
{117601}{}{Часть заводского конвейера.}
{117700}{}{Конвейер}
{117701}{}{Часть заводского конвейера.}
{117800}{}{Щиток конвейера}
{117801}{}{Средство фиксации на конвейере.}
{117900}{}{Щиток конвейера}
{117901}{}{Средство фиксации на конвейере.}
{118000}{}{Щиток конвейера}
{118001}{}{Средство фиксации на конвейере.}
{118100}{}{Щиток конвейера}
{118101}{}{Средство фиксации на конвейере.}
{118200}{}{Щиток конвейера}
{118201}{}{Средство фиксации на конвейере.}
{118300}{}{Щиток конвейера}
{118301}{}{Средство фиксации на конвейере.}
{118400}{}{Конвейер}
{118401}{}{Часть заводского конвейера.}
{118500}{}{Конвейер}
{118501}{}{Часть заводского конвейера.}
{118600}{}{Конвейер}
{118601}{}{Часть заводского конвейера.}
{118700}{}{Конвейер}
{118701}{}{Часть заводского конвейера.}
{118800}{}{Пар}
{118900}{}{Освещение}
{118901}{}{Осветительный прибор.}
{119000}{}{Освещение}
{119001}{}{Осветительный прибор.}
{119100}{}{Освещение}
{119101}{}{Осветительный прибор.}
{119200}{}{Освещение}
{119201}{}{Осветительный прибор.}
{119300}{}{Освещение}
{119301}{}{Осветительный прибор.}
{119400}{}{Освещение}
{119401}{}{Осветительный прибор.}
{119500}{}{Освещение}
{119501}{}{Осветительный прибор.}
{119600}{}{Освещение}
{119601}{}{Осветительный прибор.}
{119700}{}{Проволока}
{119701}{}{Колючая проволока.}
{119800}{}{Проволока}
{119801}{}{Колючая проволока.}
{119900}{}{Проволока}
{119901}{}{Колючая проволока. Опасная вещь.}
{120000}{}{Проволока}
{120001}{}{Колючая проволока.}
{120100}{}{Cave Wall}
{120200}{}{Cave Wall}
{120300}{}{Cave Wall}
{120400}{}{Cave Wall}
{120500}{}{Cave Wall}
{120600}{}{Cave Wall}
{120700}{}{Cave Wall}
{120800}{}{Cave Wall}
{120900}{}{Cave Wall}
{121000}{}{Cave Wall}
{121100}{}{Cave Wall}
{121200}{}{Cave Wall}
{121300}{}{Cave Wall}
{121400}{}{Cave Wall}
{121500}{}{Cave Wall}
{121600}{}{Койка}
{121601}{}{Лежанка, предназначенная для отдыха.}
{121700}{}{Койка}
{121701}{}{Лежанка, предназначенная для отдыха.}
{121800}{}{Койка}
{121801}{}{Лежанка, предназначенная для отдыха.}
{121900}{}{Койка}
{121901}{}{Многоярусная койка. Вы мечтали о такой в детстве.}
{122000}{}{Койка}
{122001}{}{Многоярусная койка. Вы мечтали о такой в детстве.}
{122100}{}{Койка}
{122101}{}{Лежанка, предназначенная для отдыха.}
{122200}{}{Койка}
{122201}{}{Не время спать!}
{122300}{}{Койка}
{122301}{}{Лежанка, предназначенная для отдыха.}
{122400}{}{Койка}
{122401}{}{Выглядит вполне чистой.}
{122500}{}{Койка}
{122501}{}{Лежанка, предназначенная для отдыха.}
{122600}{}{Койка}
{122601}{}{Лежанка, предназначенная для отдыха.}
{122700}{}{Проволока}
{122701}{}{Колючая проволока. Опасная вещь.}
{122800}{}{Знак Разыскивается!}
{122801}{}{Портрет разыскиваемого человека очень похож на вас!}
{122900}{}{Floor}
{123000}{}{Проволока}
{123001}{}{Колючая проволока}
{123100}{}{Что это такое...}
{123101}{}{Эта странная пушка похоже осталась с предвоенных времен. Удивительно, где она закончила свой жизненный путь.}
{123200}{}{Вентиляция}
{123201}{}{Часть системы вентиляции.}
{123300}{}{Забор}
{123301}{}{Повреждение на заборе.}
{123400}{}{Забор}
{123401}{}{Повреждение на заборе. Эти пятна похожи на кровь.}
{123500}{}{Вентиляция}
{123501}{}{Часть системы вентиляции.}
{123600}{}{Выключатель Энергии}
{123700}{}{Крест}
{123701}{}{Надгробный крест из подручных материалов.}
{123800}{}{Крест}
{123801}{}{Надпись на табличке стала совсем неразборчивой.}
{123900}{}{Крест}
{123901}{}{Небольшой надгробный крест, кажется, сделан из старых труб.}
{124000}{}{Крест}
{124001}{}{Наверное, покойный при жизни носил эту шляпу.}
{124100}{}{Крест}
{124101}{}{Дань памяти неизвестному усопшему.}
{124200}{}{Крест}
{124201}{}{Все когда-нибудь умирают.}
{124300}{}{Разбитая плитка}
{124400}{}{Лист металла}
{124401}{}{Тяжеленная ржавая железка, не стоит того, чтобы ее подбирать.}
{124500}{}{Лист металла}
{124501}{}{Тяжеленная ржавая железка, не стоит того, чтобы ее подбирать.}
{124600}{}{Бак}
{124601}{}{Емкость, в которой, как правило, хранят запасы воды.}
{124700}{}{Floor}
{124800}{}{Floor}
{124900}{}{Floor}
{125000}{}{Floor}
{125100}{}{Floor}
{125200}{}{Floor}
{125300}{}{Floor}
{125400}{}{Junk}
{125401}{}{Кучка какого-то хлама.}
{125500}{}{Junk}
{125501}{}{Коробки пусты, железки совсем ржавые - тут нет ничего ценного.}
{125600}{}{Лист металла}
{125601}{}{Ржавый с обеих сторон.}
{125700}{}{Лист металла}
{125701}{}{Пусть лежит, где лежал - он совершенно бесполезен.}
{125800}{}{Table}
{125801}{}{Стол дежурного по станции.}
{125900}{}{Wall}
{126000}{}{Wall}
{126100}{}{Большая лестница наверх}
{126200}{}{Хлам}
{126201}{}{Какие-то части машин, явно потерявшие всякую ценность.}
{126300}{}{Хлам}
{126301}{}{Кучка ненужного мусора.}
{126400}{}{Коммуникации}
{126401}{}{Здесь проходят трубы, кабели, иное оборудование.}
{126500}{}{Коммуникации}
{126501}{}{Здесь проходят трубы, кабели, иное оборудование.}
{126600}{}{Хлам}
{126601}{}{Стекло, железо, что-то еще.}
{126700}{}{Лежак}
{126701}{}{Вы очень постараетесь избежать отдыха на этом вонючем лежаке.}
{126800}{}{Лежак}
{126801}{}{Вы очень постараетесь избежать отдыха на этом вонючем лежаке.}
{126900}{}{Доски}
{126901}{}{Выломанная из ближайшего строения доска.}
{127000}{}{Доски}
{127001}{}{Выломанная из ближайшего строения доска.}
{127100}{}{Доски}
{127101}{}{Выломанная из ближайшего строения доска.}
{127200}{}{Доски}
{127201}{}{Выломанная из ближайшего строения доска.}
{127300}{}{Кучка Камней}
{127301}{}{Несколько крупных булыжников в одном месте.}
{127400}{}{Wall}
{127500}{}{Палатка}
{127501}{}{Палатка из прочных материалов, с усиленной защитой от ветра.}
{127600}{}{Палатка}
{127601}{}{Через дырявую крышу можно смотреть на звезды.}
{127700}{}{Доски}
{127701}{}{Выломанная из ближайшего строения доска.}
{127800}{}{Доски}
{127801}{}{Выломанная из ближайшего строения доска.}
{127900}{}{Доски}
{127901}{}{Выломанная из ближайшего строения доска.}
{128000}{}{Доски}
{128001}{}{Выломанная из ближайшего строения доска.}
{128100}{}{Доски}
{128101}{}{Выломанная из ближайшего строения доска.}
{128200}{}{Доски}
{128201}{}{Выломанная из ближайшего строения доска.}
{128300}{}{Доски}
{128301}{}{Выломанная из ближайшего строения доска.}
{128400}{}{Заваленный выход наверх}
{128401}{}{Этот завал разгрести невозможно.}
{128500}{}{Машины}
{128501}{}{Стенка из двух машин.}
{128600}{}{Table}
{128601}{}{Интересное дизайнерское решение - стол из капота машины.}
{128700}{}{Table}
{128701}{}{Стол из капота машины.}
{128800}{}{Машина}
{128801}{}{Этой малышке больше не колесить по хайвею.}
{128900}{}{Машина}
{128901}{}{Этот автомобиль давно свое отъездил.}
{129000}{}{Машины}
{129001}{}{Стенка из двух машин.}
{129100}{}{Машина}
{129101}{}{Старый полуразбитый автомобиль.}
{129200}{}{Машина}
{129201}{}{Вряд ли она теперь вообще куда-нибудь сдвинется.}
{129300}{}{Кабина лифта}
{129400}{}{Балка}
{129401}{}{Опорная конструкция.}
{129500}{}{Балка}
{129501}{}{Опорная конструкция.}
{129600}{}{Балка}
{129601}{}{Опорная конструкция.}
{129700}{}{Веревка}
{129800}{}{Спуск вниз}
{129900}{}{Floor}
{130000}{}{Доски}
{130001}{}{Выломанная из ближайшего строения доска.}
{130100}{}{Доски}
{130101}{}{Выломанная из ближайшего строения доска.}
{130200}{}{Доски}
{130201}{}{Выломанная из ближайшего строения доска.}
{130300}{}{Доски}
{130301}{}{Выломанная из ближайшего строения доска.}
{130400}{}{Floor}
{130500}{}{Машина}
{130501}{}{От нее осталась только бесполезная груда ржавого металла.}
{130600}{}{Балка}
{130601}{}{Опорная конструкция.}
{130700}{}{Балка}
{130701}{}{Опорная конструкция.}
{130800}{}{Балка}
{130801}{}{Опорная конструкция.}
{130900}{}{Балка}
{130901}{}{Опорная конструкция.}
{131000}{}{Балка}
{131001}{}{Опорная конструкция. Интересно, можно ли ней повесить взрослого человека.}
{131100}{}{Балка}
{131101}{}{Опорная конструкция.}
{131200}{}{Floor}
{131300}{}{Junk}
{131301}{}{Бесполезный хлам.}
{131400}{}{Floor}
{131500}{}{Floor}
{131600}{}{Floor}
{131700}{}{Машина}
{131701}{}{Этой малышке больше не колесить по хайвеям.}
{131800}{}{Машина}
{131801}{}{Теперь лишь ржавое ведро с гайками.}
{131900}{}{Машина}
{131901}{}{Она уже никуда никогда не поедет.}
{132000}{}{Коммуникации}
{132001}{}{Здесь проходят трубы, кабели, иное оборудование.}
{132100}{}{Коммуникации}
{132101}{}{Здесь проходят трубы, кабели, иное оборудование.}
{132200}{}{Коммуникации}
{132201}{}{Здесь проходят трубы, кабели, иное оборудование.}
{132300}{}{Коммуникации}
{132301}{}{Здесь проходят трубы, кабели, иное оборудование.}
{132400}{}{Машина}
{132401}{}{Теперь этому металлолому остается только ржаветь.}
{132500}{}{Машины}
{132501}{}{Куча разбитых машин.}
{132600}{}{Машина}
{132601}{}{Ржавый мусор, постепенно поглощаемым другим мусором.}
{132700}{}{Осветительный прибор}
{132701}{}{Тусклое освещение парковки.}
{132800}{}{Осветительный прибор}
{132801}{}{Тусклое освещение парковки.}
{132900}{}{Осветительный прибор}
{132901}{}{Прибор не светит, видимо потому, что разбит.}
{133000}{}{Вход в пещеру}
{133100}{}{Floor}
{133200}{}{Floor}
{133300}{}{Floor}
{133400}{}{Floor}
{133500}{}{Терминал}
{133501}{}{Используется для активации лифта.}
{133600}{}{Терминал}
{133601}{}{Используется для активации лифта.}
{133700}{}{Дверь Зала Контроля}
{133701}{}{Очень массивная и внушительная. Наверное, можно потратить годы, пытаясь ее открыть.}
{133800}{}{Ворота Города Убежища}
{133900}{}{Wall}
{134000}{}{Wall}
{134100}{}{Wall}
{134200}{}{Wall}
{134300}{}{Wall}
{134400}{}{Wall}
{134500}{}{Wall}
{134600}{}{Скамья}
{134601}{}{Широкая бетонная скамья.}
{134700}{}{Дверь}
{134800}{}{Дверь, открытая насильно}
{134900}{}{Осколки Двери}
{135000}{}{Wall}
{135100}{}{Wall}
{135200}{}{Wall}
{135300}{}{Wall}
{135400}{}{Wall}
{135500}{}{Wall}
{135600}{}{Wall}
{135700}{}{Wall}
{135800}{}{Дверь}
{135900}{}{Wall}
{136000}{}{Wall}
{136100}{}{Wall}
{136200}{}{Wall}
{136300}{}{Растение}
{136301}{}{Какое-то пустынное растение.}
{136400}{}{Floor}
{136500}{}{Floor}
{136600}{}{Floor}
{136700}{}{Говитайзер... хм... или что-то еще...}
{136701}{}{Эта странная пушка осталась здесь с предвоенных времен. Какой конец жизненного пути.}
{136800}{}{Уступ}
{136900}{}{Переправа}
{137000}{}{Ящик}
{137001}{}{Разбитый ящик с петлями на боковой стенке.}
{137100}{}{Floor}
{137200}{}{Floor}
{137300}{}{Ящик}
{137301}{}{Очень тяжелый металлический ящик с каким-то хламом.}
{137400}{}{Ящик}
{137401}{}{Очень тяжелый металлический ящик с каким-то хламом.}
{137500}{}{Ящик}
{137501}{}{Тяжелый, но пустой металлический ящик.}
{137600}{}{Ящик}
{137601}{}{Очень тяжелый металлический ящик с каким-то хламом.}
{137700}{}{Верти... что?}
{137701}{}{НУЖНО ДЛИННОЕ ОПИСАНИЕ}
{137800}{}{Выбоина}
{137801}{}{Большая выбоина}
{137900}{}{Вышка}
{137901}{}{Охранная вышка с пулеметом.}
{138000}{}{Выбоина}
{138100}{}{Выбоина}
{138200}{}{Выбоина}
{138300}{}{Выбоина}
{138400}{}{Выбоина}
{138500}{}{Выбоина}
{138600}{}{Свет}
{138700}{}{Дверь}
{138800}{}{Дверь}
{138900}{}{Дверь}
{139000}{}{Дверь}
{139100}{}{Дверь}
{139200}{}{Дверь}
{139300}{}{Ящик}
{139301}{}{Этот вместительный деревянный ящик вместил кучу ненужного мусора.}
{139400}{}{Ящик}
{139401}{}{Этот вместительный деревянный ящик вместил кучу ненужного мусора.}
{139500}{}{Ящик}
{139501}{}{Этот вместительный деревянный ящик вместил кучу ненужного мусора.}
{139600}{}{Ящик}
{139601}{}{Этот вместительный деревянный ящик вместил кучу ненужного мусора.}
{139700}{}{Ящик}
{139701}{}{Удивительно какой бесполезный хлам люди иногда хранят в прочных металлических ящиках.}
{139800}{}{Ящик}
{139801}{}{Удивительно какой бесполезный хлам люди иногда хранят в прочных металлических ящиках.}
{139900}{}{Ящик}
{139901}{}{Удивительно какой бесполезный хлам люди иногда хранят в прочных металлических ящиках.}
{140000}{}{Ящик}
{140001}{}{Удивительно какой бесполезный хлам люди иногда хранят в прочных металлических ящиках.}
{140100}{}{Тень}
{140200}{}{Плакат}
{140201}{}{Плакат неплохо сохранился.}
{140300}{}{Машина}
{140301}{}{Старый полуразбитый автомобиль.}
{140400}{}{Машина}
{140401}{}{Даже гениальный механик не заставит эту сломанную машину сдвинуться с места самостоятельно.}
{140500}{}{Большая машина}
{140501}{}{Старый полуразбитый автомобиль.}
{140600}{}{Столб}
{140700}{}{Wall}
{140800}{}{Wall}
{140900}{}{Wall}
{141000}{}{Рубка диспетчера}
{141001}{}{Диспетчер отсюда кортролировал движение транспорта, теперь нет ни транспорта, ни диспетчера.}
{141100}{}{Рубка диспетчера}
{141101}{}{Диспетчер отсюда кортролировал движение транспорта, теперь нет ни транспорта, ни диспетчера.}
{141200}{}{Столб}
{141300}{}{Знак Аптеки Ренеско}
{141400}{}{Столб}
{141500}{}{Столб}
{141600}{}{Радиовышка}
{141601}{}{Самодельная радиовышка.}
{141700}{}{Дверь Мастерской}
{141800}{}{Дверь Мастерской}
{141900}{}{Wall}
{142000}{}{Wall}
{142100}{}{Wall}
{142200}{}{Wall}
{142300}{}{Wall}
{142400}{}{Wall}
{142500}{}{Wall}
{142600}{}{Wall}
{142601}{}{Wall}
{142700}{}{Wall}
{142800}{}{Wall}
{142900}{}{Wall}
{143000}{}{Wall}
{143100}{}{Wall}
{143200}{}{Wall}
{143300}{}{Веревка}
{143301}{}{Вы можете подняться по стене с этой веревкой.}
{143400}{}{Дверь}
{143401}{}{Дверь, ведущая в закрытую часть террасы.}
{143500}{}{Дверь}
{143600}{}{Асфальт}
{143700}{}{Асфальт}
{143800}{}{Асфальт}
{143900}{}{Асфальт}
{144000}{}{Асфальт}
{144100}{}{Асфальт}
{144200}{}{Вентиляция}
{144201}{}{Часть вентиляционной системы.}
{144300}{}{Вентиляция}
{144301}{}{Часть вентиляционной системы.}
{144400}{}{Вентиляция}
{144401}{}{Часть вентиляционной системы.}
{144500}{}{Вентиляция}
{144501}{}{Часть вентиляционной системы.}
{144600}{}{Вентиляция}
{144601}{}{Часть вентиляционной системы.}
{144700}{}{Вентиляция}
{144701}{}{Часть вентиляционной системы.}
{144800}{}{Асфальт}
{144900}{}{Дверь}
{145000}{}{Трубы}
{145001}{}{Огромные трубы, ведущие под воду.}
{145100}{}{Трубы}
{145101}{}{Огромные трубы, ведущие под воду.}
{145200}{}{Трубы}
{145201}{}{Огромные трубы, ведущие под воду.}
{145300}{}{Трубы}
{145301}{}{Огромные трубы, ведущие под воду.}
{145400}{}{Трубы}
{145401}{}{Огромные трубы, ведущие под воду.}
{145500}{}{Трубы}
{145501}{}{Огромные трубы, ведущие под воду.}
{145600}{}{Трубы}
{145601}{}{Огромные трубы, ведущие под воду.}
{145700}{}{Трубы}
{145701}{}{Огромные трубы, ведущие под воду.}
{145800}{}{Уступ}
{145900}{}{Трубы}
{145901}{}{Огромные трубы, ведущие под воду.}
{146000}{}{Трубы}
{146001}{}{Огромные трубы, ведущие под воду.}
{146100}{}{Трубы}
{146101}{}{Огромные трубы, ведущие под воду.}
{146200}{}{Вещи}
{146201}{}{Куча бесполезного барахла.}
{146300}{}{Вещи}
{146301}{}{Куча бесполезного барахла.}
{146400}{}{Огромный бак с водой}
{146401}{}{Пробоины в баке закрыты металлическими пластинами.}
{146500}{}{Огромный бак с водой}
{146501}{}{Пробоины в баке закрыты металлическими пластинами.}
{146600}{}{Дверь в заборе}
{146700}{}{Дверь в заборе}
{146800}{}{Командирское сиденье}
{146801}{}{Это то, где обыкновенно сидит Смотритель.}
{146900}{}{Камни}
{146901}{}{Куча камней и грязи.}
{147000}{}{Камни}
{147001}{}{Куча камней и грязи.}
{147100}{}{Камни}
{147101}{}{Куча камней и грязи.}
{147200}{}{Камни}
{147201}{}{Куча камней и грязи.}
{147300}{}{Камни}
{147301}{}{Куча камней и грязи.}
{147400}{}{Камни}
{147401}{}{Куча камней и грязи.}
{147500}{}{Огромный бак с водой}
{147501}{}{Пробоины в баке закрыты металлическими пластинами.}
{147600}{}{Трубы}
{147601}{}{Участок массивной трубы.}
{147700}{}{Земля}
{147701}{}{Отсюда берется земля на верхний этаж.}
{147800}{}{Wall}
{147900}{}{Дверь}
{148000}{}{Дверь}
{148100}{}{Труба}
{148101}{}{Участок массивной трубы.}
{148200}{}{Wall}
{148300}{}{Вода}
{148400}{}{Вещи}
{148401}{}{Тут нет ничего ценного.}
{148500}{}{Floor}
{148600}{}{"Жерло Аида"}
{148601}{}{Выглядит омерзительно и страшно. Воняет примерно также.}
{148700}{}{Wall}
{148800}{}{Пропасть}
{148801}{}{Непроглядная тьма.}
{148900}{}{Устройства}
{148901}{}{Устройства обеспечения работы котла.}
{149000}{}{Устройства}
{149001}{}{Устройства обеспечения работы котла.}
{149100}{}{Дверь}
{149200}{}{Дверь}
{149201}{}{Эта дверь очень плохо сохранилась.}
{149300}{}{Опрокинутая кровать}
{149301}{}{Разодранная кровать с торчащими пружинами.}
{149400}{}{Опрокинутая кровать}
{149401}{}{Похоже, эта кровать свое отслужила.}
{149500}{}{Хлам}
{149501}{}{Части машин.}
{149600}{}{Junk}
{149601}{}{Бесполезный хлам.}
{149700}{}{Junk}
{149701}{}{Битые бутылки и прочий мусор.}
{149800}{}{Хлам}
{149801}{}{Части старых ящиков.}
{149900}{}{Хлам}
{149901}{}{Три пустых ящика.}
{150000}{}{Узор}
{150001}{}{Фигурный узор на стене.}
{150100}{}{Узор}
{150101}{}{Фигурный узор на стене.}
{150200}{}{Floor}
{150300}{}{Floor}
{150400}{}{Коробки}
{150401}{}{Видимо, кто-то изучил их раньше, там нет ничего ценного.}
{150500}{}{Станок}
{150600}{}{Сено}
{150601}{}{Заготавливать сено из сухой пустынной травы довольно просто - ее надо только собрать.}
{150700}{}{Сено}
{150701}{}{Заготавливать сено из сухой пустынной травы довольно просто - ее надо только собрать.}
{150800}{}{Сено}
{150801}{}{Заготавливать сено из сухой пустынной травы довольно просто - ее надо только собрать.}
{150900}{}{Сено}
{150901}{}{Заготавливать сено из сухой пустынной травы довольно просто - ее надо только собрать.}
{151000}{}{Сено}
{151001}{}{Заготавливать сено из сухой пустынной травы довольно просто - ее надо только собрать.}
{151100}{}{Сено}
{151101}{}{Заготавливать сено из сухой пустынной травы довольно просто - ее надо только собрать.}
{151200}{}{Сено}
{151201}{}{Заготавливать сено из сухой пустынной травы довольно просто - ее надо только собрать.}
{151300}{}{Хлам}
{151301}{}{Ящики, коробки, что-то еще. Но совершенно ничего полезного.}
{151400}{}{Обломки}
{151401}{}{Разрушенные стены здания.}
{151500}{}{Обломки}
{151501}{}{Разрушенные стены здания.}
{151600}{}{Обломки}
{151601}{}{Разрушенные стены здания.}
{151700}{}{Обломки}
{151701}{}{Разрушенные стены здания.}
{151800}{}{Дверца}
{151801}{}{Дверца от шкафа.}
{151900}{}{Дверца}
{151901}{}{Дверца от шкафа.}
{152000}{}{Труба}
{152001}{}{Часть тяжелой трубы.}
{152100}{}{Труба}
{152101}{}{Часть тяжелой трубы.}
{152200}{}{Труба}
{152201}{}{Часть тяжелой трубы.}
{152300}{}{Труба}
{152301}{}{Часть тяжелой трубы.}
{152400}{}{Ящик}
{152401}{}{Большой пустой ящик из сухого дерева.}
{152500}{}{Ящик}
{152501}{}{Большой пустой ящик из сухого дерева.}
{152600}{}{Ящик}
{152601}{}{Большой пустой ящик из сухого дерева.}
{152700}{}{Труба}
{152800}{}{Труба}
{152900}{}{Части ящика}
{153000}{}{Части ящика}
{153100}{}{Дверь}
{153101}{}{Дверь, ведущая на арену.}
{153200}{}{Дверь}
{153201}{}{Перед вами стандартнейшая дверь.}
{153300}{}{Дверь}
{153301}{}{Перед вами стандартнейшая дверь.}
{153400}{}{Дверь}
{153401}{}{Дверь, ведущая на арену.}
{153500}{}{Дверь}
{153501}{}{Перед вами стандартнейшая дверь.}
{153600}{}{Дверь}
{153601}{}{Перед вами стандартнейшая дверь.}
{153700}{}{Здание завода}
{153800}{}{Wall}
{153900}{}{Wall}
{154000}{}{Унитаз}
{154001}{}{Оттуда исходит ужасный запах.}
{154100}{}{Wall}
{154200}{}{Труба}
{154201}{}{Проржавевшая в нескольких местах.}
{154300}{}{Труба}
{154301}{}{Проржавевшая в нескольких местах.}
{154400}{}{Унитаз}
{154401}{}{Здесь проходят трубы и иное оборудование.}
{154500}{}{Коммуникации}
{154501}{}{Здесь проходят трубы и иное оборудование.}
{154600}{}{Коммуникации}
{154601}{}{Здесь проходят трубы и иное оборудование.}
{154700}{}{Тряпье}
{154701}{}{Старый вонючий лежак.}
{154800}{}{Силовое поле}
{154900}{}{Силовое поле}
{155000}{}{Устройство для удаления органов}
{155001}{}{Самая последняя модель из хирургической серии "Сделай это сам". Удаляет органы при нажатии на кнопку.}
{155100}{}{Лежак}
{155101}{}{Рядом с ним неприятно даже стоять, а от мысли на него прилечь начинает подташнивать.}
{155200}{}{Тряпье}
{155201}{}{Старый вонючий лежак.}
{155300}{}{Лежак}
{155301}{}{Рядом с ним неприятно даже стоять, а от мысли на него прилечь начинает подташнивать.}
{155400}{}{Тряпье}
{155401}{}{Возможно это было лежаком, но Вы не уверены.}
{155500}{}{Wall}
{155501}{}{Трубы на фоне ободранных стен.}
{155600}{}{Хлам}
{155601}{}{Разломанный стол}
{155700}{}{Хлам}
{155701}{}{Какой-то мусор.}
{155800}{}{Электрощиток}
{155801}{}{Электрощиток служит для распределения электроэнергии.}
{155900}{}{Трубы}
{155901}{}{Целый узел из труб.}
{156000}{}{Забор}
{156001}{}{Сооружение из гнилой древесины.}
{156100}{}{Забор}
{156101}{}{Сооружение из гнилой древесины.}
{156200}{}{Бассейн с водой}
{156201}{}{Здесь больше грязи, чем воды.}
{156300}{}{Бассейн с водой}
{156301}{}{Здесь больше грязи, чем воды.}
{156400}{}{Бассейн с водой}
{156401}{}{Здесь больше грязи, чем воды.}
{156500}{}{Забор}
{156501}{}{Сооружение из гнилой древесины.}
{156600}{}{Бассейн с водой}
{156601}{}{Здесь больше грязи, чем воды.}
{156700}{}{Разрушенная стена}
{156800}{}{Разрушенная стена}
{156900}{}{Wall}
{157000}{}{Wall}
{157100}{}{Floor}
{157200}{}{Floor}
{157300}{}{Дверь}
{157301}{}{Дверь с небольшим окошком.}
{157400}{}{Дверь}
{157401}{}{Массивная дверь.}
{157500}{}{Дверь}
{157600}{}{Дверь}
{157700}{}{Часть автомобиля}
{157701}{}{Похоже на двигатель, выдранный из автомобиля.}
{157800}{}{Голова быка.}
{157801}{}{Бык в шляпе выглядывает из консервной банки. Символ завода Happy bull.}
{157900}{}{Wall}
{157901}{}{Полуразрушенная стена}
{158000}{}{Дыра}
{158001}{}{Перед вами нора в полу.}
{158100}{}{Скалы}
{158101}{}{Выглядят неприступными.}
{158200}{}{Скалы}
{158201}{}{Выглядят неприступными.}
{158300}{}{Скалы}
{158301}{}{Выглядят неприступными.}
{158400}{}{Балка}
{158401}{}{Трухлявая, покрывшаяся плесенью деревянная балка.}
{158500}{}{Поврежденная стена}
{158600}{}{Машина}
{158601}{}{Старый, полуразбитый автомобиль.}
{158700}{}{Забор}
{158701}{}{Сооружение из прогнившей древесины.}
{158800}{}{Поврежденная стена}
{158900}{}{Wall}
{159000}{}{Поврежденная стена}
{159100}{}{Поврежденная стена}
{159200}{}{Поврежденная стена}
{159300}{}{Трубы}
{159301}{}{Участок тяжелой трубы.}
{159400}{}{Трубы}
{159401}{}{Участок тяжелой трубы.}
{159500}{}{Поврежденная стена}
{159600}{}{Wall}
{159700}{}{Трубы}
{159701}{}{Склизкие, покрытые плесенью трубы.}
{159800}{}{Трубы}
{159801}{}{Склизкие, покрытые плесенью трубы.}
{159900}{}{Wall}
{160000}{}{Floor}
{160100}{}{Машина}
{160101}{}{Старый, полуразбитый автомобиль.}
{160200}{}{Части ящика}
{160201}{}{Стенки ящика из сухого дерева.}
{160300}{}{Корыто}
{160301}{}{Открытая емкость с грязной водой.}
{160400}{}{Корыто}
{160401}{}{Открытая емкость с грязной водой.}
{160500}{}{Части ящика}
{160501}{}{Стенки ящика из сухого дерева.}
{160600}{}{Завод}
{160601}{}{Здание завода.}
{160700}{}{Завод}
{160701}{}{Здание завода.}
{160800}{}{Завод}
{160801}{}{Здание завода.}
{160900}{}{Завод}
{160901}{}{Здание завода.}
{161000}{}{Floor}
{161100}{}{Лежак}
{161101}{}{Старый вонючий лежак и какой-то мусор.}
{161200}{}{Лежак}
{161201}{}{Вам кажется, что по нему кто-то ползает.}
{161300}{}{Завод}
{161301}{}{Здание завода.}
{161400}{}{Завод}
{161401}{}{Здание завода.}
{161500}{}{Лежак}
{161501}{}{Старый вонючий лежак.}
{161600}{}{Подушка}
{161601}{}{Очень грязная.}
{161700}{}{Лежак}
{161701}{}{Если лечь на такой, то можно подцепить какую-нибудь гадость.}
{161800}{}{Лежак}
{161801}{}{Старый вонючий лежак.}
{161900}{}{Части забора}
{161901}{}{Части забора фабрики.}
{162000}{}{Самодельная трибуна}
{162001}{}{Наспех сложенная из досок площадка для выступлений.}
{162100}{}{Части забора}
{162101}{}{Части забора фабрики.}
{162200}{}{Лежак}
{162201}{}{Очень грязный вонючий лежак.}
{162300}{}{Лежак}
{162301}{}{Старый вонючий лежак.}
{162400}{}{Лежак}
{162401}{}{На нем определенно грибок и плесень.}
{162500}{}{Трубы}
{162501}{}{Участок массивной трубы.}
{162600}{}{Коммуникации}
{162601}{}{Здесь проходят трубы, кабели, иное оборудование.}
{162700}{}{Трубы}
{162701}{}{Участок массивной трубы.}
{162800}{}{Бочка}
{162801}{}{Пустой деревянный бочонок.}
{162900}{}{Бочка}
{162901}{}{Пустой деревянный бочонок.}
{163000}{}{Поврежденная стена}
{163100}{}{Трубы}
{163101}{}{Участок массивной трубы.}
{163200}{}{Трубы}
{163201}{}{Участок массивной трубы.}
{163300}{}{Полуразрушенная стена}
{163400}{}{Полки с медикаментами}
{163401}{}{Вы не знаете назначение этих медикаментов.}
{163500}{}{Полки с медикаментами}
{163501}{}{Вы не знаете назначение этих медикаментов.}
{163600}{}{Бочка}
{163601}{}{Пустой деревянный бочонок}
{163700}{}{Бочки}
{163701}{}{Поставленные друг на друга бочки.}
{163800}{}{Бочки}
{163801}{}{Поставленные друг на друга бочки.}
{163900}{}{Части забора}
{163901}{}{Выломанная из забора доска.}
{164000}{}{Палатка}
{164001}{}{Свернутая палатка}
{164100}{}{Части забора}
{164101}{}{Выломанная из забора доска.}
{164200}{}{Части забора}
{164201}{}{Выломанная из забора доска.}
{164300}{}{Станок}
{164301}{}{Предназначен для работы с различными материалами.}
{164400}{}{Станок}
{164401}{}{Предназначен для работы с различными материалами.}
{164500}{}{Ступени вниз}
{164600}{}{Ступени наверх}
{164601}{}{Лестница ведет наверх.}
{164700}{}{Спуск на станцию}
{164701}{}{Ступени уходят в темноту.}
{164800}{}{Лестница вниз}
{164801}{}{Лестница уходит в темноту.}
{164900}{}{Части забора}
{164901}{}{Выломанная из забора доска.}
{165000}{}{Части забора}
{165001}{}{Выломанная из забора доска.}
{165100}{}{Части забора}
{165101}{}{Выломанная из забора доска.}
{165200}{}{Ступени наверх}
{165201}{}{Лестница ведет наверх.}
{165300}{}{Мешки с песком}
{165301}{}{Военная фортификация.}
{165400}{}{Мешки с песком}
{165401}{}{Военная фортификация.}
{165500}{}{Шахтный лифт}
{165600}{}{Балка}
{165700}{}{Части забора}
{165701}{}{Выломанная из забора доска.}
{165800}{}{Камни}
{165900}{}{Части забора}
{165901}{}{Выломанная из забора доска.}
{166000}{}{Проход}
{166100}{}{Забор}
{166101}{}{Сооружение из прогнившей древесины.}
{166200}{}{Шест}
{166201}{}{Опорная конструкция.}
{166300}{}{Шест}
{166301}{}{Опорная конструкция.}
{166400}{}{Шест}
{166401}{}{Опорная конструкция.}
{166500}{}{Шест}
{166501}{}{Опорная конструкция.}
{166600}{}{Шест}
{166601}{}{Опорная конструкция.}
{166700}{}{Шест}
{166701}{}{Опорная конструкция.}
{166800}{}{Шест}
{166801}{}{Опорная конструкция.}
{166900}{}{Выбоина}
{167000}{}{Шест}
{167001}{}{Опорная конструкция.}
{167100}{}{Выбоина}
{167200}{}{Ограждение}
{167201}{}{Тряпичная перегородка.}
{167300}{}{Ограждение}
{167301}{}{Тряпичная перегородка.}
{167400}{}{Полуразрушенная стена}
{167500}{}{Заложенная стена}
{167600}{}{Часть забора}
{167601}{}{Выломанная из забора доска.}
{167700}{}{Ограждение}
{167701}{}{Тряпичная перегородка.}
{167800}{}{Ограждение}
{167801}{}{Тряпичная перегородка.}
{167900}{}{Выбоина}
{168000}{}{Ограждение}
{168001}{}{Тряпичная перегородка.}
{168100}{}{Лежак}
{168101}{}{Не стоит тут отдыхать.}
{168200}{}{Баллоны}
{168201}{}{Внутри некая субстанция.}
{168300}{}{Баллоны}
{168301}{}{Внутри некая субстанция.}
{168400}{}{Плитка}
{168500}{}{Шахтный Лифт}
{168600}{}{Плитка}
{168700}{}{Плитка}
{168800}{}{Полуразрушенная стена}
{168900}{}{Лифт}
{169000}{}{Лифт}
{169100}{}{Полуразрушенная стена}
{169200}{}{Полуразрушенная стена}
{169300}{}{Выбоина}
{169400}{}{Угол стены}
{169500}{}{Выбоина}
{169600}{}{Выбоина}
{169700}{}{Вещи}
{169701}{}{Куча бесполезного барахла.}
{169800}{}{Ограждение}
{169801}{}{Тряпичная перегородка.}
{169900}{}{Ограждение}
{169901}{}{Тряпичная перегородка.}
{170000}{}{Полуразрушенная стена}
{170100}{}{Сломанный шест}
{170200}{}{Ограждение}
{170201}{}{Тряпичная перегородка.}
{170300}{}{Ограждение}
{170301}{}{Тряпичная перегородка.}
{170400}{}{Ограждение}
{170401}{}{Тряпичная перегородка.}
{170500}{}{Шест}
{170501}{}{Опорная конструкция.}
{170600}{}{Полки}
{170601}{}{К сожалению, вам тут нечем поживиться.}
{170700}{}{Полки}
{170701}{}{Тут нет ничего ценного.}
{170800}{}{Полки}
{170900}{}{Дверь}
{171000}{}{Дверь}
{171100}{}{Колонна}
{171101}{}{Декоративное сооружение.}
{171200}{}{Колонна}
{171201}{}{Декоративное сооружение.}
{171300}{}{Украшенное изображение}
{171301}{}{Лицо портрета заклеено другим лицом, аккуратно вырезанным из фотографии. Вы узнаете одного из обитателей Лайвоса.}
{171400}{}{Украшенное изображение}
{171401}{}{Глядя на это изображение, Вы думаете, что искусство бывает крайне странным.}
{171500}{}{Украшенное изображение}
{171501}{}{Выполняет чисто эстетическую функцию.}
{171600}{}{Украшенное изображение}
{171601}{}{Вы не являетесь поклонником такого рода живописи.}
{171700}{}{Украшенное изображение}
{171701}{}{Местные обитатели видимо ценят искусство.}
{171800}{}{Украшенное изображение}
{171801}{}{Вы не являетесь поклонником такого рода живописи.}
{171900}{}{Украшенное изображение}
{171901}{}{Лицо портрета заклеено другим лицом, аккуратно вырезанным из фотографии. Вы узнаете одного из обитателей Лайвоса.}
{172000}{}{Украшенное изображение}
{172001}{}{Местные обитатели видимо ценят искусство.}
{172100}{}{Пуленепробиваемое стекло}
{172200}{}{Пуленепробиваемое стекло}
{172300}{}{Пуленепробиваемое стекло}
{172400}{}{Украшенное изображение}
{172401}{}{Вы не являетесь поклонником такого рода живописи.}
{172500}{}{Украшенное изображение}
{172501}{}{Местные обитатели видимо ценят искусство.}
{172600}{}{Камень}
{172601}{}{Огромный камень с плоской гранью. Очень тяжелый.}
{172700}{}{Камень}
{172701}{}{Твердая горная порода.}
{172800}{}{Камень}
{172801}{}{Кажется, он по форме напоминает шляпу и еще на него можно присесть.}
{172900}{}{Камень}
{172901}{}{Камень причудливой формы.}
{173000}{}{Ящик}
{173001}{}{Ничего интересного в этом объекте нет.}
{173100}{}{Части ящиков}
{173101}{}{Стенка деревянного ящика.}
{173200}{}{Части ящиков}
{173201}{}{Стенка деревянного ящика.}
{173300}{}{Части ящиков}
{173301}{}{Стенка деревянного ящика.}
{173400}{}{Floor}
{173500}{}{Floor}
{173600}{}{Floor}
{173700}{}{Выход наверх}
{173800}{}{Стол со свечкой}
{173801}{}{Грязный стол, освещаемый пламенем свечи.}
{173900}{}{Floor}
{174000}{}{Вещи}
{174001}{}{Куча бесполезного барахла.}
{174100}{}{Бассейн с водой}
{174101}{}{Здесь больше грязи, чем воды.}
{174200}{}{Floor}
{174300}{}{Шест}
{174301}{}{Опорная конструкция.}
{174400}{}{Табуретка}
{174401}{}{Старый и совершенно обычный предмет мебели.}
{174500}{}{Table}
{174501}{}{Видавший виды стол с грязной разорванной скатертью и остатками еды.}
{174600}{}{Плитка}
{174700}{}{Плитка}
{174800}{}{Скалы}
{174801}{}{Выглядят неприступными.}
{174900}{}{Часть забора}
{174901}{}{Выломанная из забора доска.}
{175000}{}{Баки с водой}
{175001}{}{Большие ржавые баки с запасами воды.}
{175100}{}{Бассейн с водой}
{175101}{}{Здесь больше грязи, чем воды.}
{175200}{}{Украшенное изображение}
{175201}{}{Вы некоторое время изучаете изображение, но оно не становится от этого более понятным.}
{175300}{}{Украшенное изображение}
{175301}{}{Для Вас остается загадкой, что же этой работой хотел сказать автор.}
{175400}{}{Унитаз}
{175401}{}{В отличном состоянии.}
{175500}{}{Крест}
{175600}{}{Колодец}
{175601}{}{Сооружение для добывания воды.}
{175700}{}{Трубы}
{175701}{}{Участок массивной трубы.}
{175800}{}{Баки с водой}
{175801}{}{Большие ржавые баки с запасами воды.}
{175900}{}{Трубы}
{175901}{}{Здесь проходят трубы, кабели, иное оборудование.}
{176000}{}{Трубы}
{176001}{}{Ниша для вывода каких-то труб и прочих коммуникаций.}
{176100}{}{Труба}
{176101}{}{Участок массивной трубы.}
{176200}{}{Трубы}
{176201}{}{Участок массивной трубы.}
{176300}{}{Трубы}
{176301}{}{Участок массивной трубы.}
{176400}{}{Трубы}
{176401}{}{Участок массивной трубы.}
{176500}{}{Трубы}
{176501}{}{Участок массивной трубы.}
{176600}{}{Трубы}
{176601}{}{Участок массивной трубы.}
{176700}{}{Трубы}
{176701}{}{Участок массивной трубы.}
{176800}{}{Трубы}
{176801}{}{Участок массивной трубы.}
{176900}{}{Трубы}
{176901}{}{Участок массивной трубы.}
{177000}{}{Трубы}
{177001}{}{Участок массивной трубы.}
{177100}{}{Трубы}
{177101}{}{Участок массивной трубы.}
{177200}{}{Спуск к воде}
{177300}{}{Вода}
{177400}{}{Вода}
{177500}{}{Вода}
{177600}{}{Вода}
{177700}{}{Трубы}
{177701}{}{Участок массивной трубы.}
{177800}{}{Лежак}
{177801}{}{Не самый чистый предмет для отдыха.}
{177900}{}{Костер}
{177901}{}{Вы же не собираетесь смотреть на него вечно?}
{178000}{}{Лежак}
{178001}{}{Кажется, на нем может спать только человек, который не чувствует запахов.}
{178100}{}{Лежак}
{178101}{}{Кажется, на нем может спать только человек, который не чувствует запахов.}
{178200}{}{Лежак}
{178201}{}{Похоже он уже прогнил.}
{178300}{}{Лежак}
{178301}{}{Старый, вонючий лежак.}
{178400}{}{Лежак}
{178401}{}{Не время отдыхать, тем более на этом.}
{178500}{}{Floor}
{178600}{}{Floor}
{178700}{}{Какой-то мусор в воде}
{178701}{}{Кажется, что-то растеклось вокруг.}
{178800}{}{Повозка}
{178801}{}{Сооружена из автомобиля.}
{178900}{}{Повозка}
{178901}{}{Сооружена из автомобиля.}
{179000}{}{Машина}
{179001}{}{Старый, полуразбитый автомобиль.}
{179100}{}{Инструменты}
{179101}{}{Различные инструменты, но они не пригодны к использованию.}
{179200}{}{Инструменты}
{179201}{}{Различные инструменты, но они не пригодны к использованию.}
{179300}{}{Вода}
{179301}{}{Очень грязно. Ничего не видно сквозь муть.}
{179400}{}{Вода}
{179401}{}{Очень грязно. Ничего не видно сквозь муть.}
{179500}{}{Уступ}
{179501}{}{Дальше вода. Вы совсем не хотите в этом купаться.}
{179600}{}{Уступ}
{179601}{}{Дальше вода. Вы совсем не хотите в этом купаться.}
{179700}{}{Уступ}
{179701}{}{Дальше вода.}
{179800}{}{Уступ}
{179801}{}{Дальше вода.}
{179900}{}{Решетка}
{179901}{}{Канализационная решетка.}
{180000}{}{Решетка}
{180001}{}{Канализационная решетка.}
{180100}{}{Уступ}
{180101}{}{Дальше вода.}
{180200}{}{Уступ}
{180300}{}{Камни}
{180400}{}{Ящик}
{180500}{}{Освещение}
{180600}{}{Шипы}
{180601}{}{Острые шипы, легко проколют ступню.}
{180700}{}{Выход}
{180800}{}{Ограждение}
{180801}{}{Тряпичная перегородка.}
{180900}{}{Ограждение}
{180901}{}{Тряпичная перегородка.}
{181000}{}{Ограждение}
{181001}{}{Тряпичная перегородка.}
{181100}{}{Баки с водой}
{181101}{}{Большие ржавые баки с запасами воды.}
{181200}{}{Ограждение}
{181201}{}{Тряпичная перегородка.}
{181300}{}{Выход}
{181301}{}{Ведет в темноту}
{181400}{}{Плита}
{181500}{}{Ограждение}
{181501}{}{Тряпичная перегородка.}
{181600}{}{Ограждение}
{181601}{}{Тряпичная перегородка.}
{181700}{}{Планка}
{181800}{}{Дверь}
{181801}{}{Ведет в холлы отеля.}
{181900}{}{Дверь}
{182000}{}{Кровь}
{182001}{}{Кто-то здесь совсем недавно умер.}
{182100}{}{Кровь}
{182101}{}{Не первой свежести.}
{182200}{}{Кровь}
{182201}{}{Мама всегда Вам говорила, что эта жидкость должна быть ВНУТРИ, а не снаружи.}
{182300}{}{Кровь}
{182301}{}{Кажется в этой лужице чьи-то кости.}
{182400}{}{Кровь}
{182401}{}{Мама всегда Вам говорила, что эта жидкость должна быть ВНУТРИ, а не снаружи.}
{182500}{}{Кости и кишки}
{182501}{}{Бренные останки, пахнут свежей кровью.}
{182600}{}{Скалы}
{182601}{}{Выглядят неприступными.}
{182700}{}{Скалы}
{182701}{}{Выглядят неприступными.}
{182800}{}{Скалы}
{182801}{}{Выглядят неприступными.}
{182900}{}{Скалы}
{182901}{}{Выглядят неприступными.}
{183000}{}{Скалы}
{183001}{}{Выглядят неприступными.}
{183100}{}{Скалы}
{183101}{}{Выглядят неприступными.}
{183200}{}{Скалы}
{183201}{}{Выглядят неприступными.}
{183300}{}{Скалы}
{183301}{}{Выглядят неприступными.}
{183400}{}{Скалы}
{183401}{}{Выглядят неприступными.}
{183500}{}{Ступени}
{183501}{}{Ступени образуют широкую лестницу.}
{183600}{}{Кровь}
{183601}{}{Кровь уже успела впитаться.}
{183700}{}{Кровь, кишки, кости}
{183701}{}{Вы видите перед собой чей-то богатый внутренний мир.}
{183800}{}{Палатка}
{183801}{}{Используется для сна, отдыха, укрытия от непогоды.}
{183900}{}{Скалы}
{183901}{}{Выглядят неприступными.}
{184000}{}{Скалы}
{184001}{}{Выглядят неприступными.}
{184100}{}{Палатка}
{184101}{}{Используется для сна, отдыха, укрытия от непогоды.}
{184200}{}{Палатка}
{184201}{}{Используется для сна, отдыха, укрытия от непогоды.}
{184300}{}{Палатка}
{184301}{}{Используется для сна, отдыха, укрытия от непогоды.}
{184400}{}{Спуск вниз}
{184500}{}{Лежак}
{184501}{}{При взгляде на этот лежак желание прилечь мгновенно пропадает.}
{184600}{}{Забор}
{184700}{}{Угол стены}
{184800}{}{Шест}
{184801}{}{Опорная конструкция.}
{184900}{}{Бочка}
{184901}{}{Металлическая бочка.}
{185000}{}{Бочка}
{185001}{}{Металлическая бочка.}
{185100}{}{Пар}
{185200}{}{Заграждение}
{185201}{}{Аварийный знак.}
{185300}{}{Хлам}
{185301}{}{Различные части машин, но ничего полезного.}
{185400}{}{Хлам}
{185401}{}{Части ограждений.}
{185500}{}{Хлам}
{185501}{}{Кирпичи}
{185600}{}{Хлам}
{185601}{}{Бочка, автомобильные шины, что-то еще.}
{185700}{}{Хлам}
{185701}{}{Бесполезный мусор.}
{185800}{}{Кресло}
{185801}{}{Это кресло выглядит так, будто оно отслужило свое много лет назад.}
{185900}{}{Table доктора}
{185901}{}{Грязный стол с каким-то мусором и компьютером.}
{186000}{}{Машина}
{186001}{}{Старый ржавый автомобиль.}
{186100}{}{Ящик}
{186101}{}{Ничего особенного, просто ящик.}
{186200}{}{Бочка с мусором}
{186201}{}{Бесполезный хлам.}
{186300}{}{Шины}
{186301}{}{Автомобильные шины, ничего интересного.}
{186400}{}{Шины}
{186401}{}{Автомобильные шины, ничего интересного.}
{186500}{}{Шина}
{186501}{}{Автомобильная шина, ничего интересного.}
{186600}{}{Повозка}
{186601}{}{Сооружена из автомобиля.}
{186700}{}{Повозка}
{186701}{}{Сооружена из автомобиля.}
{186800}{}{Хлам}
{186801}{}{Бесполезный мусор.}
{186900}{}{Хлам}
{186901}{}{Бесполезный мусор.}
{187000}{}{Сиденье}
{187001}{}{Выдрано из машины.}
{187100}{}{Шины}
{187101}{}{Автомобильные шины, ничего интересного.}
{187200}{}{Палатка}
{187201}{}{Похоже, эта палатка свое отслужила.}
{187300}{}{Палатка}
{187301}{}{Похоже, эта палатка свое отслужила.}
{187400}{}{Машина}
{187401}{}{Старый, полуразбитый автомобиль.}
{187500}{}{Машина}
{187501}{}{На этом уже никто никуда не поедет.}
{187600}{}{Машина}
{187601}{}{Старый, полуразбитый автомобиль.}
{187700}{}{Хлам}
{187701}{}{Бесполезный мусор.}
{187800}{}{Машина}
{187801}{}{Теперь это просто груда бесполезного металла и она никуда не поедет.}
{187900}{}{Машина}
{187901}{}{Старый, полуразбитый автомобиль.}
{188000}{}{Машина}
{188001}{}{Старый, полуразбитый автомобиль.}
{188100}{}{Машина}
{188101}{}{Теперь это просто груда бесполезного металла и она никуда не поедет.}
{188200}{}{Машина}
{188201}{}{На этом уже никто никуда не поедет.}
{188300}{}{Хлам}
{188301}{}{Бесполезный мусор.}
{188400}{}{Хлам}
{188401}{}{Тут нечем поживиться.}
{188500}{}{Хлам}
{188501}{}{Кажется это кирпичи. Они Вам совершенно не нужны.}
{188600}{}{Хлам}
{188601}{}{Бесполезный мусор.}
{188700}{}{Хлам}
{188701}{}{Тут Вы вряд ли найдете что-то ценное.}
{188800}{}{Хлам}
{188801}{}{Бесполезный мусор.}
{188900}{}{Хлам}
{188901}{}{Тут Вы вряд ли найдете что-то ценное}
{189000}{}{Вещи}
{189001}{}{Куча барахла. Ничего полезного там нет.}
{189100}{}{Junk}
{189101}{}{Бутылки пустые и грязные - поживиться нечем.}
{189200}{}{Машина}
{189201}{}{Старый, полуразбитый автомобиль.}
{189300}{}{Junk}
{189301}{}{Бесполезный хлам.}
{189400}{}{Junk}
{189401}{}{Бесполезный хлам.}
{189500}{}{Полки}
{189501}{}{Полки с выпивкой.}
{189600}{}{Полки}
{189601}{}{Полки с выпивкой.}
{189700}{}{Table}
{189800}{}{Стул}
{189801}{}{Обычный барный стул.}
{189900}{}{Хлам}
{189901}{}{Бесполезный мусор, заботливо накрытый тканью.}
{190000}{}{Машина}
{190001}{}{На этом уже никто никуда не поедет.}
{190100}{}{Машина}
{190101}{}{Вряд ли его можно починить.}
{190200}{}{Ограждение}
{190201}{}{Тряпичная перегородка.}
{190300}{}{Ограждение}
{190301}{}{Тряпичная перегородка.}
{190400}{}{Ограждение}
{190401}{}{Тряпичная перегородка.}
{190500}{}{Ограждение}
{190501}{}{Тряпичная перегородка.}
{190600}{}{Ограждение}
{190601}{}{Тряпичная перегородка.}
{190700}{}{Ограждение}
{190701}{}{Тряпичная перегородка.}
{190800}{}{Бочка с землей}
{190801}{}{В этих бочках переносят плодородную землю.}
{190900}{}{Бочка с землей}
{190901}{}{В этих бочках переносят плодородную землю.}
{191000}{}{Бочки с землей}
{191001}{}{В этих бочках переносят плодородную землю.}
{191100}{}{Бочка с землей}
{191101}{}{В этих бочках переносят плодородную землю.}
{191200}{}{Бочка с землей}
{191201}{}{В этих бочках переносят плодородную землю.}
{191300}{}{Хлам}
{191301}{}{Вы не найдете там ничего полезного.}
{191400}{}{Хлам}
{191401}{}{Бесполезный мусор.}
{191500}{}{Бочка с землей}
{191501}{}{В этих бочках переносят плодородную землю.}
{191600}{}{Лежак}
{191601}{}{На этом лежаке видимо спали не один год.}
{191700}{}{Лежак}
{191701}{}{Кажется, он чем-то воняет.}
{191800}{}{Лежак}
{191801}{}{Старый, вонючий лежак.}
{191900}{}{Тряпье}
{191901}{}{Спать на этом точно уже невозможно.}
{192000}{}{Floor}
{192100}{}{Floor}
{192200}{}{Floor}
{192300}{}{Дверь}
{192400}{}{Дверь}
{192500}{}{Table}
{192501}{}{На удивление довольно чистый стол.}
{192600}{}{Table}
{192601}{}{Самый обычный стол с каким-то подобием скатерти.}
{192700}{}{Table}
{192701}{}{Обычный стол с остатками былого пиршества.}
{192800}{}{Table}
{192801}{}{Просто стол, ничего необычного.}
{192900}{}{Table}
{192901}{}{Бутылки треснули, ничего интересного.}
{193000}{}{Бак}
{193001}{}{Бак с запасами воды.}
{193100}{}{Стол аренщика}
{193101}{}{Здесь можно узнать больше про бои на арене.}
{193200}{}{Кости}
{193201}{}{Человеческие кости.}
{193300}{}{Кости}
{193301}{}{Человеческие кости. Этот бедняга умер много лет назад.}
{193400}{}{Кости}
{193401}{}{Когда-то давно это было человеком.}
{193500}{}{Растение}
{193501}{}{Живое зеленое травянистое растение.}
{193600}{}{Растение}
{193601}{}{Живое зеленое травянистое растение.}
{193700}{}{Растение}
{193701}{}{Живое зеленое травянистое растение.}
{193800}{}{Растение}
{193801}{}{Живое зеленое травянистое растение.}
{193900}{}{Растение}
{193901}{}{Живое зеленое травянистое растение.}
{194000}{}{Шест}
{194001}{}{Шест для стриптиза.}
{194100}{}{Вход}
{194200}{}{Здание}
{194201}{}{Здание завода.}
{194300}{}{Здание}
{194301}{}{Здание завода.}
{194400}{}{Хлам}
{194401}{}{Бесполезный мусор.}
{194500}{}{Коробка}
{194501}{}{В ней совершенно ничего интересного.}
{194600}{}{Ящик}
{194601}{}{Ничем непримечательный ящик.}
{194700}{}{Лист железа}
{194701}{}{Бесполезный мусор.}
{194800}{}{Лист железа}
{194801}{}{Это Вам не пригодится.}
{194900}{}{Лист железа}
{194901}{}{Бесполезный мусор.}
{195000}{}{Лист железа}
{195001}{}{Это Вам не пригодится.}
{195100}{}{Выгребная яма}
{195101}{}{Отличное решение, когда нет возможности провести центральную канализацию.}
{195200}{}{Выгребная яма}
{195201}{}{Отличное решение, когда нет возможности провести центральную канализацию.}
{195300}{}{Выгребная яма}
{195301}{}{Отличное решение, когда нет возможности провести центральную канализацию.}
{195400}{}{Выгребная яма}
{195401}{}{Отличное решение, когда нет возможности провести центральную канализацию.}
{195500}{}{Table}
{195501}{}{Обыкновенный стол.}
{195600}{}{Table}
{195601}{}{Обыкновенный стол.}
{195700}{}{Скалы}
{195701}{}{Выглядят неприступными.}
{195800}{}{Скалы}
{195801}{}{Выглядят неприступными.}
{195900}{}{Скалы}
{195901}{}{Выглядят неприступными.}
{196000}{}{Скалы}
{196001}{}{Выглядят неприступными.}
{196100}{}{Скалы}
{196101}{}{Выглядят неприступными.}
{196200}{}{Трибуна}
{196201}{}{Кафедра для оратора.}
{196300}{}{Экран}
{196400}{}{Печь}
{196401}{}{Отопительно-варочная печь.}
{196500}{}{Печь}
{196501}{}{Отопительно-варочная печь.}
{196600}{}{Плитка}
{196700}{}{Плитка}
{196800}{}{Плитка}
{196900}{}{Плитка}
{197000}{}{Плитка}
{197100}{}{Плитка}
{197200}{}{Камни}
{197201}{}{Просто куча камней.}
{197300}{}{Камни}
{197301}{}{Просто куча камней.}
{197400}{}{Камни}
{197401}{}{Просто куча камней.}
{197500}{}{Балка}
{197501}{}{Опорная балка туннеля.}
{197600}{}{Балка}
{197601}{}{Опорная балка туннеля.}
{197700}{}{Балка}
{197701}{}{Опорная балка туннеля.}
{197800}{}{Балка}
{197801}{}{Опорная балка туннеля.}
{197900}{}{Балка}
{197901}{}{Опорная балка туннеля.}
{198000}{}{Балка}
{198001}{}{Опорная балка туннеля.}
{198100}{}{Балка}
{198101}{}{Опорная балка туннеля.}
{198200}{}{Балка}
{198201}{}{Опорная балка туннеля.}
{198300}{}{Балка}
{198301}{}{Опорная балка туннеля.}
{198400}{}{Камни}
{198401}{}{Не время собирать камни.}
{198500}{}{Камни}
{198501}{}{Не время собирать камни.}
{198600}{}{Камни}
{198601}{}{Просто куча камней.}
{198700}{}{Камни}
{198701}{}{Просто куча камней.}
{198800}{}{Коробка}
{198801}{}{Пустая старая коробка. Не представляет никакого интереса.}
{198900}{}{Junk}
{198901}{}{Бесполезный хлам.}
{199000}{}{Junk}
{199001}{}{Это Вам не пригодится.}
{199100}{}{Junk}
{199101}{}{Это Вам не пригодится.}
{199200}{}{Junk}
{199201}{}{Бесполезный хлам.}
{199300}{}{Хлам}
{199301}{}{Это вряд ли кому-то сможет пригодиться.}
{199400}{}{Хлам}
{199401}{}{Это Вам не пригодится.}
{199500}{}{Хлам}
{199501}{}{Бесполезный мусор.}
{199600}{}{Хлам}
{199601}{}{Это Вам не пригодится.}
{199700}{}{Хлам}
{199701}{}{Бесполезный мусор.}
{199800}{}{Хлам}
{199801}{}{Это Вам не пригодится.}
{199900}{}{Хлам}
{199901}{}{Бесполезный мусор.}
{200000}{}{Хлам}
{200001}{}{Бесполезный мусор.}
{200100}{}{Хлам}
{200101}{}{Это Вам не пригодится.}
{200200}{}{Генератор}
{200201}{}{Устройство, вырабатывающее электроэнергию.}
{200300}{}{Генератор}
{200301}{}{Устройство, вырабатывающее электроэнергию.}
{200400}{}{Насос}
{200401}{}{Гидравлическая машина.}
{200500}{}{Труба}
{200501}{}{Уходящая в землю труба.}
{200600}{}{Труба}
{200601}{}{Уходящая в землю труба.}
{200700}{}{Хлам}
{200701}{}{Бесполезный мусор.}
{200800}{}{Хлам}
{200801}{}{Бесполезный мусор.}
{200900}{}{НЕТ}
{201000}{}{Автомат по производству пищи}
{201001}{}{При нажатии на кнопку "Ризотто" автомат выплевывает склизкий комок подозрительного зеленого цвета.}
{201100}{}{Автомат по производству пищи}
{201101}{}{При нажатии на кнопку "Креветки фламбе" автомат выплевывает три склизкие кляксы. На вкус как жеванные сопли.}
{201200}{}{Автомат по производству одежды}
{201201}{}{Кажется он работает не так, как планировалось.}
{201300}{}{Автомат по производству пищи}
{201301}{}{При нажатии на кнопку "Тортилья" автомат выплевывает склизкий комок. Пахнет старыми носками.}
{201400}{}{Автомат по производству пищи}
{201401}{}{При нажатии на кнопку "Брауниз" автомат выплевывает невнятную кашицу без запаха и вкуса.}
{201500}{}{Доска}
{201501}{}{Самая обычная доска. Вряд ли она вам может пригодиться.}
{201600}{}{Доска}
{201601}{}{Самая обычная доска. Вряд ли она вам может пригодиться.}
{201700}{}{Доска}
{201701}{}{Самая обычная доска. Вряд ли она вам может пригодиться.}
{201800}{}{Доска}
{201801}{}{Самая обычная доска. Вряд ли она вам может пригодиться.}
{201900}{}{Доска}
{201901}{}{Самая обычная доска. Вряд ли она вам может пригодиться.}
{202000}{}{Растение}
{202001}{}{Отличный представитель herba vulgaris.}
{202100}{}{Растение}
{202101}{}{Отличный представитель herba vulgaris.}
{202200}{}{Растение}
{202201}{}{Какое-то пустынное растение.}
{202300}{}{Растение}
{202301}{}{Отличный представитель herba vulgaris.}
{202400}{}{Растение}
{202401}{}{Какое-то пустынное растение.}
{202500}{}{Растение}
{202501}{}{Отличный представитель herba vulgaris.}
{202600}{}{Растение}
{202601}{}{Какое-то пустынное растение.}
{202700}{}{Растение}
{202701}{}{Отличный представитель herba vulgaris.}
{202800}{}{Растение}
{202801}{}{Отличный представитель herba vulgaris.}
{202900}{}{Растение}
{202901}{}{Какое-то пустынное растение.}
{203000}{}{Растение}
{203001}{}{Какое-то пустынное растение.}
{203100}{}{Растение}
{203101}{}{Отличный представитель herba vulgaris.}
{203200}{}{Растение}
{203201}{}{Какое-то пустынное растение.}
{203300}{}{Растение}
{203301}{}{Отличный представитель herba vulgaris.}
{203400}{}{Растение}
{203401}{}{Какое-то пустынное растение.}
{203500}{}{Растение}
{203501}{}{Какое-то пустынное растение.}
{203600}{}{Лист металла}
{203601}{}{Ржавый и очень тяжелый.}
{203700}{}{Лист металла}
{203701}{}{Ржавый и очень тяжелый.}
{203800}{}{Растение}
{203801}{}{Отличный представитель herba vulgaris.}
{203900}{}{Растение}
{203901}{}{Отличный представитель herba vulgaris.}
{204000}{}{Флюгер}
{204001}{}{Флажки, показывающие направление ветра.}
{204100}{}{Кол с черепом}
{204101}{}{Вам бы очень не хотелось закончить так же.}
{204200}{}{Кол с черепом}
{204201}{}{Устрашающий знак.}
{204300}{}{Кол с черепом}
{204301}{}{Вы присматриваетесь повнимательнее, кажется, у этого бедолаги был кариес.}
{204400}{}{Кол с черепом}
{204401}{}{В этом черепе кто-то поселился.}
{204500}{}{Кол с черепом}
{204501}{}{Вы смотрите на череп и в голове возникает мысль: "Быть или не быть?".}
{204600}{}{Кол с черепом}
{204601}{}{Его пустые глазницы как будто следят за Вами.}
{204700}{}{Флюгер}
{204701}{}{Флажки, показывающие направление ветра.}
{204800}{}{Растение}
{204801}{}{Какое-то пустынное растение.}
{204900}{}{Растение}
{204901}{}{Какое-то пустынное растение.}
{205000}{}{Трава}
{205001}{}{Живая зеленая трава, Вы с трудом удерживаетесь от искушения пожевать травинку.}
{205100}{}{Трава}
{205101}{}{Живая зеленая трава, Вы с трудом удерживаетесь от искушения пожевать травинку.}
{205200}{}{Растение}
{205201}{}{Живое травянистое зеленое растение.}
{205300}{}{Кол}
{205301}{}{Его старательно заостренный конец побуждает в Вас сильное желание сохранить голову на плечах.}
{205400}{}{Кол}
{205401}{}{Вы, кажется, догадываетесь о его предназначении.}
{205500}{}{Кол}
{205501}{}{Вам бы очень не хотелось украсить своим черепом этот замечательный кол.}
{205600}{}{Кол}
{205601}{}{Вы, кажется, догадываетесь о его предназначении.}
{205700}{}{Кол}
{205701}{}{Вам кажется, что на этом коле определенно чего-то не хватает.}
{205800}{}{Кол}
{205801}{}{Острый. Выглядит угрожающе.}
{205900}{}{Кол}
{205901}{}{Кто-то явно постарался, затачивая его.}
{206000}{}{Кол}
{206001}{}{Острый. Выглядит угрожающе.}
{206100}{}{Кол}
{206101}{}{Такой легко может Вас проткнуть.}
{206200}{}{Кол}
{206201}{}{Острый. Выглядит угрожающе.}
{206300}{}{Кровь}
{206301}{}{Пятно засохшей крови. }
{206400}{}{Кровь}
{206401}{}{Пятно засохшей крови.}
{206500}{}{Кровь}
{206501}{}{Выглядит довольно старой.}
{206600}{}{Кровь}
{206601}{}{Пятно засохшей крови.}
{206700}{}{Кровь}
{206701}{}{Уже высохла и впиталась.}
{206800}{}{Флюгер}
{206801}{}{Флажок показывает направление ветра.}
{206900}{}{Кровь}
{206901}{}{Интересно, чья эта кровь.}
{207000}{}{Кровь}
{207001}{}{Этим останкам уже несколько дней, запах соответствующий.}
{207100}{}{Кровь}
{207101}{}{Эти останки сильно смердят.}
{207200}{}{Кровь}
{207201}{}{Кому-то тут очень не повезло.}
{207300}{}{Кровь}
{207301}{}{Вы видите перед собой чей-то внутренний мир, причем не первой свежести.}
{207400}{}{Чучело для битья}
{207401}{}{Лучше пусть тренируют приемы на нем, чем на живых людях.}
{207500}{}{Чучело для битья}
{207501}{}{Ну и морда у него - действительно хочется врезать!}
{207600}{}{Чучело для битья}
{207601}{}{Отличный самодельный манекен для тренировок.}
{207700}{}{Чучело для битья}
{207701}{}{Заменяет боксерскую грушу.}
{207800}{}{Чучело для битья}
{207801}{}{Похоже ему часто достается.}
{207900}{}{Чучело для битья}
{207901}{}{Меньше всего на свете Вы бы хотели оказаться на его месте.}
{208000}{}{Забитая дверь.}
{208001}{}{Выход заблокирован.}
{208100}{}{Скала}
{208101}{}{Выглядит неприступной.}
{208200}{}{Плакат}
{208201}{}{Выцветший довоенный плакат.}
{208300}{}{Плакат}
{208301}{}{Выцветший довоенный плакат.}
{208400}{}{Плакат}
{208401}{}{Этому плакату не менее 200 лет. Люди тогда знали толк в изготовлении крепких плакатов.}
{208500}{}{Плакат}
{208501}{}{Выцветший довоенный плакат.}
{208600}{}{Плакат}
{208601}{}{Вам нравится смотреть на старые плакаты. Они хранят историю.}
{208700}{}{Плакат}
{208701}{}{Неужели эта агитация кого-то воодушевляла?}
{208800}{}{Плакат}
{208801}{}{Выцветший довоенный плакат.}
{208900}{}{Плакат}
{208901}{}{Неужели эта агитация кого-то воодушевляла?}
{209000}{}{Плакат}
{209001}{}{Выцветший довоенный плакат.}
{209100}{}{Плакат}
{209101}{}{Выцветший довоенный плакат.}
{209200}{}{Плакат}
{209201}{}{Неужели эта агитация кого-то воодушевляла?}
{209300}{}{Плакат}
{209301}{}{Этому плакату не менее 200 лет. Люди тогда знали толк в изготовлении крепких плакатов.}
{209400}{}{Плакат}
{209401}{}{Человек с плаката умер уже очень давно.}
{209500}{}{Плакат}
{209501}{}{Это похоже на рекламу фильма, очень жаль, что о кино Вы читали только в книжках.}
{209600}{}{Плакат}
{209601}{}{Этому плакату не менее 200 лет. Люди тогда знали толк в изготовлении крепких плакатов.}
{209700}{}{Плакат}
{209701}{}{Довоенный агитационный плакат.}
{209800}{}{Плакат}
{209801}{}{Довоенный агитационный плакат.}
{209900}{}{Плакат}
{209901}{}{Этому плакату не менее 200 лет. Люди тогда знали толк в изготовлении крепких плакатов.}
{210000}{}{Плакат}
{210001}{}{Жаль Вы не коллекционируете старинные плакаты - это прекрасный экземпляр.}
{210100}{}{Плакат}
{210101}{}{Этому плакату не менее 200 лет. Люди тогда знали толк в изготовлении крепких плакатов.}
{210200}{}{Плакат}
{210201}{}{Очень старый поблекший плакат.}
{210300}{}{Плакат}
{210301}{}{Старинный выцветший плакат.}
{210400}{}{Плакат}
{210401}{}{Жаль Вы не коллекционируете старинные плакаты - это прекрасный экземпляр.}
{210500}{}{Плакат}
{210501}{}{Ему же не менее 200 лет. Как хорошо сохранился.}
{210600}{}{Плакат}
{210601}{}{Выцветший довоенный плакат.}
{210700}{}{Плакат}
{210701}{}{Выцветший довоенный плакат.}
{210800}{}{Кости}
{210801}{}{Несколько чьих-то костей.}
{210900}{}{Кости}
{210901}{}{Кажется это ребра.}
{211000}{}{Кости}
{211001}{}{Когда-нибудь и вы так закончите. Тщетно бытие.}
{211100}{}{Кости}
{211101}{}{Когда-нибудь и вы так закончите. Тщетно бытие.}
{211200}{}{Кости}
{211201}{}{Несколько чьих-то костей.}
{211300}{}{Кости}
{211301}{}{Несколько чьих-то костей.}
{211400}{}{Кости}
{211401}{}{Когда-нибудь и вы так закончите. Тщетно бытие.}
{211500}{}{Кости}
{211501}{}{Когда-то это было чем-то живым.}
{211600}{}{Кости}
{211601}{}{Несколько чьих-то костей.}
{211700}{}{Кости}
{211701}{}{Когда-то это было чем-то живым.}
{211800}{}{Растение}
{211801}{}{Какое-то пустынное растение.}
{211900}{}{Растение}
{211901}{}{Какое-то пустынное растение.}
{212000}{}{Растение}
{212001}{}{Какое-то пустынное растение.}
{212100}{}{Растение}
{212101}{}{Какое-то пустынное растение.}
{212200}{}{Растение}
{212201}{}{Какое-то пустынное растение.}
{212300}{}{Растение}
{212301}{}{Какое-то пустынное растение.}
{212400}{}{Растение}
{212401}{}{Какое-то пустынное растение.}
{212500}{}{Растение}
{212501}{}{Какое-то пустынное растение.}
{212600}{}{Растение}
{212601}{}{Какое-то пустынное растение.}
{212700}{}{Растение}
{212701}{}{Какое-то пустынное растение.}
{212800}{}{Растение}
{212801}{}{Какое-то пустынное растение.}
{212900}{}{Растение}
{212901}{}{Какое-то пустынное растение.}
{213000}{}{Растение}
{213001}{}{Какое-то пустынное растение.}
{213100}{}{Кости}
{213101}{}{От Вас останется ненамного больше.}
{213200}{}{Кости}
{213201}{}{Несколько чьих-то костей.}
{213300}{}{Кости}
{213301}{}{От Вас останется ненамного больше.}
{213400}{}{Кости}
{213401}{}{Обычные кости, их здесь много.}
{213500}{}{Кости}
{213501}{}{Кто-то умер.}
{213600}{}{Кости}
{213601}{}{Кто-то умер.}
{213700}{}{Кости}
{213701}{}{Совсем старые кости.}
{213800}{}{Кости}
{213801}{}{Это кости редчайшего вымершего животного. Жаль, что Вы не коллекционируете кости.}
{213900}{}{Кости}
{213901}{}{Несколько чьих-то костей.}
{214000}{}{Кости}
{214001}{}{Очень старые кости.}
{214100}{}{Кол}
{214101}{}{Острый. Выглядит угрожающе.}
{214200}{}{Кол}
{214201}{}{Острый. Выглядит угрожающе.}
{214300}{}{Кол}
{214301}{}{Заостренный с одного конца шест.}
{214400}{}{Кол}
{214401}{}{Острый. Выглядит угрожающе.}
{214500}{}{Кол}
{214501}{}{Острый. Выглядит угрожающе.}
{214600}{}{Кол}
{214601}{}{Острый. Выглядит угрожающе.}
{214700}{}{Кол}
{214701}{}{Таким и проткнуть можно.}
{214800}{}{Кол}
{214801}{}{Таким и проткнуть можно.}
{214900}{}{Сломанный кол}
{215000}{}{Сломанный кол}
{215100}{}{Кровь}
{215101}{}{Это старая засохшая кровь.}
{215200}{}{Кровь}
{215201}{}{Мама всегда Вам говорила, что эта жидкость должна быть ВНУТРИ, а не снаружи.}
{215300}{}{Кровь}
{215301}{}{Кровь и песок.}
{215400}{}{Кровь}
{215401}{}{Пятно засохшей крови.}
{215500}{}{Кровь}
{215501}{}{Пятно засохшей крови.}
{215600}{}{Кровь}
{215601}{}{Пятно засохшей крови.}
{215700}{}{Кровь}
{215701}{}{Интересно, чья это кровь.}
{215800}{}{Кровь}
{215801}{}{Пятно засохшей крови.}
{215900}{}{Кровь}
{215901}{}{Пятно засохшей крови.}
{216000}{}{Кровь}
{216001}{}{Пятно засохшей крови.}
{216100}{}{Кости}
{216101}{}{Это кости редчайшего вымершего животного. Жаль, что Вы не коллекционируете кости.}
{216200}{}{Кости}
{216201}{}{Кто-то умер.}
{216300}{}{Кости}
{216301}{}{Вряд ли эти кости представляют для Вас какой-то интерес, если Вы, конечно, не остеолог.}
{216400}{}{Череп}
{216401}{}{Похоже, это было какой-то зверушкой.}
{216500}{}{Кости}
{216501}{}{Кажется они очень хрупкие.}
{216600}{}{Кровь}
{216601}{}{Пятно засохшей крови.}
{216700}{}{Кровь}
{216701}{}{Красная кровь, белые кости - прекрасное сочетание цветов.}
{216800}{}{Кровь}
{216801}{}{Интересно, кому эта кровь принадлежала.}
{216900}{}{Кровь}
{216901}{}{Пятно засохшей крови.}
{217000}{}{Кровь}
{217001}{}{Интересно, кому эта кровь принадлежала.}
{217100}{}{Хижина}
{217101}{}{От нее разит кровью и мочой.}
{217200}{}{Хижина}
{217201}{}{А на пустынных берегах стоят жилища здесь и там, приют убогого аборигена.}
{217300}{}{Хижина}
{217301}{}{Вам совсем не хочется туда заходить.}
{217400}{}{Хижина}
{217401}{}{Сооружение из дерева и сухой травы.}
{217500}{}{Растение}
{217501}{}{Какое-то пустынное растение.}
{217600}{}{Растение}
{217601}{}{Какое-то пустынное растение.}
{217700}{}{Растение}
{217701}{}{Какое-то пустынное растение.}
{217800}{}{Растение}
{217801}{}{Какое-то пустынное растение.}
{217900}{}{Растение}
{217901}{}{Какое-то пустынное растение.}
{218000}{}{Растение}
{218001}{}{Какое-то пустынное растение.}
{218100}{}{Растение}
{218101}{}{Какое-то пустынное растение.}
{218200}{}{Растение}
{218201}{}{Какое-то пустынное растение.}
{218300}{}{Растение}
{218301}{}{Какое-то пустынное растение.}
{218400}{}{Растение}
{218401}{}{Какое-то пустынное растение.}
{218500}{}{Улов}
{218501}{}{Крупная здесь рыба! Выглядит вполне съедобной.}
{218600}{}{Дерево}
{218601}{}{Ствол иссохшего дерева.}
{218700}{}{Дерево}
{218701}{}{Этому дереву уже не помочь.}
{218800}{}{Дерево}
{218801}{}{Это дерево похоже на морковку. Старую сухую серую морковку.}
{218900}{}{Дерево}
{218901}{}{Эти сухие ветви навевают уныние.}
{219000}{}{Дерево}
{219001}{}{Сухой сломанный ствол иссохшего дерева.}
{219100}{}{Вывеска}
{219101}{}{"Еда, вода" - похоже тут можно перекусить!}
{219200}{}{Бильярдный стол}
{219201}{}{Вы не очень понимаете как на нем играть, но ткань на столе выглядит очень потертой.}
{219300}{}{Бильярдный стол}
{219301}{}{Цветные шарики на столе выглядят забавно, жаль вы не умеете в это играть.}
{219400}{}{Панель экранов}
{219401}{}{К сожалению она выключена. Посмотреть на такую в деле было бы крайне любопытно.}
{219500}{}{Wall}
{219600}{}{Диван}
{219601}{}{Предмет мебели, способный обеспечить пятой точке максимальный комфорт.}
{219700}{}{Диван}
{219701}{}{Выглядит удобным, не время тут отдыхать.}
{219800}{}{Экраны}
{219801}{}{Интересно, что можно смотреть на таком количестве экранов. Сейчас там только полоски.}
{219900}{}{Плакат}
{219901}{}{Старый плакат с рекламой оружия. От такой пушки и сейчас бы никто не отказался!}
{220000}{}{Ступени наверх}
{220100}{}{Ступени вниз}
{220200}{}{Плакат}
{220201}{}{Блеклый старинный плакат.}
{220300}{}{Плакат}
{220301}{}{Этому плакату не менее двухсот лет - умели же делать плакаты!}
{220400}{}{Плакат}
{220401}{}{Сейчас таких не делают.}
{220500}{}{Плакат}
{220501}{}{Некоторое время изучаете плакат. Похоже это реклама консервов.}
{220600}{}{Плакат}
{220601}{}{Вам нравятся старые плакаты. Они хранят историю.}
{220700}{}{Плакат}
{220701}{}{Блеклый настенный плакат.}
{220800}{}{Плакат}
{220801}{}{Этому плакату не менее двухсот лет - умели же делать плакаты!}
{220900}{}{Плакат}
{220901}{}{Жизнь до войны была совсем другой.}
{221000}{}{Плакат}
{221001}{}{Огромный старинный плакат.}
{221100}{}{Плакат}
{221101}{}{"Будь готов нанести удар".}
{221200}{}{Плакат}
{221201}{}{Краски расплылись и поблекли.}
{221300}{}{Плакат}
{221301}{}{Вам нравятся старые плакаты. Они хранят историю.}
{221400}{}{Плитка}
{221500}{}{Плитка}
{221600}{}{Плитка}
{221700}{}{Плитка}
{221800}{}{Плитка}
{221900}{}{Плитка}
{222000}{}{Плитка}
{222100}{}{Доска}
{222101}{}{Самая обычная доска. Ничего интересного.}
{222200}{}{Доска}
{222201}{}{Самая обычная доска. Ничего интересного.}
{222300}{}{Доска}
{222301}{}{Самая обычная доска. Ничего интересного.}
{222400}{}{Доска}
{222401}{}{Самая обычная доска. Ничего интересного.}
{222500}{}{Доска}
{222501}{}{Самая обычная доска. Ничего интересного.}
{222600}{}{Доска}
{222601}{}{Самая обычная доска. Ничего интересного.}
{222700}{}{Доска}
{222701}{}{Самая обычная доска. Ничего интересного.}
{222800}{}{Доска}
{222801}{}{Самая обычная доска. Ничего интересного.}
{222900}{}{Доска}
{222901}{}{Самая обычная доска. Ничего интересного.}
{223000}{}{Доска}
{223001}{}{Самая обычная доска. Ничего интересного.}
{223100}{}{Доска}
{223101}{}{Самая обычная доска. Ничего интересного.}
{223200}{}{Доска}
{223201}{}{Самая обычная доска. Ничего интересного.}
{223300}{}{Доска}
{223301}{}{Самая обычная доска. Ничего интересного.}
{223400}{}{Доска}
{223401}{}{Самая обычная доска. Ничего интересного.}
{223500}{}{Доска}
{223501}{}{Самая обычная доска. Ничего интересного.}
{223600}{}{Ржавый лист металла}
{223601}{}{Зачем он Вам?}
{223700}{}{Ржавый лист металла}
{223701}{}{Он совершенно бесполезен.}
{223800}{}{Ржавый лист металла}
{223801}{}{Вы внимательно изучаете его, но более полезным он не становится.}
{223900}{}{Хлам}
{223901}{}{Даже самый последний бродяга не позарился бы на этот хлам.}
{224000}{}{Хлам}
{224001}{}{Абсолютно бесполезный хлам.}
{224100}{}{Хлам}
{224101}{}{Вы не найдете этому хламу применения.}
{224200}{}{Хлам}
{224201}{}{Ничего интересного.}
{224300}{}{Ржавый лист металла}
{224301}{}{Это Вам точно не пригодится.}
{224400}{}{Ржавый лист металла}
{224401}{}{Он совершенно бесполезен.}
{224500}{}{Ржавый лист металла}
{224501}{}{Пусть ржавеет дальше.}
{224600}{}{Хлам}
{224601}{}{Вы ведь не хотите собирать всякий мусор?}
{224700}{}{Хлам}
{224701}{}{Даже самый последний бродяга не позарился бы на этот хлам.}
{224800}{}{Хлам}
{224801}{}{Вы не найдете этому хламу применения.}
{224900}{}{Хлам}
{224901}{}{Вы ведь не хотите собирать всякий мусор?}
{225000}{}{Дверь}
{225001}{}{Эта дверь надежно заколочена.}
{225100}{}{Лежак}
{225101}{}{Не стоит рисковать и ложиться на это.}
{225200}{}{Лежак}
{225201}{}{Он совсем прогнил.}
{225300}{}{Лежак}
{225301}{}{Это что там такое по нему ползет?}
{225400}{}{Wall}
{225500}{}{Wall}
{225600}{}{Wall}
{225700}{}{Wall}
{225800}{}{Wall}
{225900}{}{Камни}
{226000}{}{Камни}
{226100}{}{Камни}
{226200}{}{Камни}
{226300}{}{Камни}
{226400}{}{Камни}
{226500}{}{Камни}
{226600}{}{Камни}
{226700}{}{Камни}
{226800}{}{Камни}
{226900}{}{Камни}
{227000}{}{Камни}
{227100}{}{Хлам}
{227101}{}{Бесполезный мусор.}
{227200}{}{Лист металла}
{227201}{}{Это что, кровь?}
{227300}{}{Хлам}
{227301}{}{Даже самый последний бродяга не позарился бы на этот хлам.}
{227400}{}{Лист металла}
{227401}{}{Он ржавый тяжелый и абсолютно бесполезен.}
{227500}{}{Лист металла}
{227501}{}{Даже самый последний бродяга не позарился бы на этот хлам.}
{227600}{}{Лист металла}
{227601}{}{Вы ведь не хотите собирать всякий мусор?}
{227700}{}{Лист металла}
{227701}{}{Совсем заржавел.}
{227800}{}{Лист металла}
{227801}{}{Бесполезный мусор.}
{227900}{}{Ящик}
{227901}{}{Хороший большой ящик, но там нет ничего интересного.}
{228000}{}{Ящик}
{228001}{}{Вам очень интересно, что будет, если поместить внутрь радиоактивное вещество, пузырек с ядом и, например, кота.}
{228100}{}{Пещерный гриб}
{228101}{}{Мама говорила Вам не есть незнакомые грибы.}
{228200}{}{Пещерный гриб}
{228201}{}{Мама говорила Вам не есть незнакомые грибы.}
{228300}{}{Пещерный гриб}
{228301}{}{Мама говорила Вам не есть незнакомые грибы.}
{228400}{}{Пещерный гриб}
{228401}{}{Мама говорила Вам не есть незнакомые грибы.}
{228500}{}{Пещерный гриб}
{228501}{}{Мама говорила Вам не есть незнакомые грибы.}
{228600}{}{Пещерный гриб}
{228601}{}{Мама говорила Вам не есть незнакомые грибы.}
{228700}{}{Пещерный гриб}  
{228701}{}{Мама говорила Вам не есть незнакомые грибы.} 
{228800}{}{Пещерный гриб}
{228801}{}{Мама говорила Вам не есть незнакомые грибы.}
{228900}{}{Пещерный гриб}
{228901}{}{Мама говорила Вам не есть незнакомые грибы.}
{229000}{}{Пещерный гриб}
{229001}{}{Мама говорила Вам не есть незнакомые грибы.}
{229100}{}{Лист металла}
{229101}{}{Отличный и почти не мятый, но Вам он не пригодится.}
{229200}{}{Лист металла}
{229201}{}{Совершенно бесполезный для Вас предмет.}
{229300}{}{Лист металла}
{229301}{}{Ржавый и мятый жестяной лист.}
{229400}{}{Cave Wall}
{229500}{}{Cave Wall}
{229600}{}{Камни}
{229700}{}{Часть стены}
{229800}{}{Часть стены}
{229900}{}{Часть стены}
{230000}{}{Часть стены}
{230100}{}{Разрушенная колонна}
{230200}{}{Разрушенная колонна}
{230300}{}{Разрушенная колонна}
{230400}{}{Разрушенная колонна}
{230500}{}{Вывеска}
{230501}{}{Краска от времени потрескалась и надпись невозможно разобрать.}
{230600}{}{Вывеска}
{230601}{}{Краска от времени потрескалась и надпись невозможно разобрать.}
{230700}{}{Большая дыра в полу}
{230701}{}{Воронка от взрыва снаряда. Внизу только обломки и камни.}
{230800}{}{Лежак}
{230801}{}{Лучше зажать нос рядом с этим лежаком - он воняет.}
{230900}{}{Лежак}
{230901}{}{Это что там такое по нему ползет?}
{231000}{}{Лежак}
{231001}{}{Пыль и плесень, на этом даже стоять неприятно.}
{231100}{}{Лист металла}
{231101}{}{Старый ржавый лист жести.}
{231200}{}{Лист металла}
{231201}{}{Этот жестяной хлам вам не нужен.}
{231300}{}{Лист металла}
{231301}{}{Бесполезная жестянка.}
{231400}{}{Плакат}
{231401}{}{Огромный поблекший плакат "TIN Industries".}
{231500}{}{Осколки плитки}
{231501}{}{Тысячи их! И каждый по-своему уникален.}
{231600}{}{Осколки плитки}
{231601}{}{Тысячи их! И каждый по-своему уникален.}
{231700}{}{Осколки плитки}
{231701}{}{Тысячи их! И каждый по-своему уникален.}
{231800}{}{Осколки плитки}
{231801}{}{Тысячи их! И каждый по-своему уникален.}
{231900}{}{Осколки плитки}
{231901}{}{Тысячи их! И каждый по-своему уникален.}
{232000}{}{Осколки плитки}
{232001}{}{Тысячи их! И каждый по-своему уникален.}
{232100}{}{Осколки плитки}
{232101}{}{Тысячи их! И каждый по-своему уникален.}
{232200}{}{Осколки плитки}
{232201}{}{Тысячи их! И каждый по-своему уникален.}
{232300}{}{Осколки плитки}
{232301}{}{Тысячи их! И каждый по-своему уникален.}
{232400}{}{Осколки плитки}
{232401}{}{Тысячи их! И каждый по-своему уникален.}
{232500}{}{Осколки плитки}
{232501}{}{Тысячи их! И каждый по-своему уникален.}
{232600}{}{Осколки плитки}
{232601}{}{Тысячи их! И каждый по-своему уникален.}
{232700}{}{Осколки плитки}
{232701}{}{Тысячи их! И каждый по-своему уникален.}
{232800}{}{Осколки плитки}
{232801}{}{Тысячи их! И каждый по-своему уникален.}
{232900}{}{Осколки плитки}
{232901}{}{Тысячи их! И каждый по-своему уникален.}
{233000}{}{Лежак}
{233001}{}{Ложиться на этот грязный лежак совсем не хочется.}
{233100}{}{Хлам}
{233101}{}{Лучше не трогайте это.}
{233200}{}{Хлам}
{233201}{}{Совершенно бесполезная вещь.}
{233300}{}{Factory Wall}
{233400}{}{Factory Wall}
{233500}{}{Часть стены}
{233600}{}{Часть стены}
{233700}{}{Часть стены}
{233800}{}{Часть стены}
{233900}{}{Плакат}
{233901}{}{Он очень старый.}
{234000}{}{Плакат}
{234001}{}{Рассматриваете его некоторое время, Вам определенно нравятся старые плакаты.}
{234100}{}{Плакат}
{234101}{}{Патриотично.}
{234200}{}{Wall}
{234300}{}{Плакат}
{234301}{}{Сожалеете, что такой плакат не висел в детстве над вашей кроватью.}
{234400}{}{Плакат}
{234401}{}{Кажется, на нем обосновалась плесень.}
{234500}{}{Плакат}
{234501}{}{Блеклый настенный плакат.}
{234600}{}{Wall}
{234700}{}{Wall}
{234800}{}{Машина}
{234801}{}{Массивная землеройная машина.}
{234900}{}{Машина}
{234901}{}{Массивная землеройная машина.}
{235000}{}{Хлам}
{235001}{}{Ржавая железка, такой хлам не стоит Вашего внимания.}
{235100}{}{Лист ржавого железа}
{235101}{}{Издает забавный звук, если по нему постучать.}
{235200}{}{Хлам}
{235201}{}{Ржавая железка, такой хлам не стоит Вашего внимания.}
{235300}{}{Лист ржавого железа}
{235301}{}{Слишком тяжелый и вряд ли Вам пригодится.}
{235400}{}{Лист ржавого железа}
{235401}{}{Слишком тяжелый и вряд ли Вам пригодится.}
{235500}{}{Хлам}
{235501}{}{Не стоить тратить время на этот хлам.}
{235600}{}{Хлам}
{235601}{}{Теперь это всего лишь бесполезный мусор.}
{235700}{}{Хлам}
{235701}{}{Теперь это всего лишь бесполезный мусор.}
{235800}{}{Хлам}
{235801}{}{Не стоит подбирать всякий хлам.}
{235900}{}{Хлам}
{235901}{}{Совершенно бесполезный мусор.}
{236000}{}{Скалы}
{236001}{}{Выглядят неприступными.}
{236100}{}{Скалы}
{236101}{}{Выглядят неприступными.}
{236200}{}{Скалы}
{236201}{}{Выглядят неприступными.}
{236300}{}{Доска}
{236301}{}{Ничем непримечательная доска.}
{236400}{}{Лист железа}
{236401}{}{Издает забавный звук, если по нему постучать.}
{236500}{}{Лист железа}
{236501}{}{Слишком тяжелый.}
{236600}{}{Лист железа}
{236601}{}{В нем нет для Вас совершенно никакой пользы.}
{236700}{}{Лист железа}
{236701}{}{Выглядит крепким, но бесполезным.}
{236800}{}{Хлам}
{236801}{}{От этого хлама никакого толку.}
{236900}{}{Хлам}
{236901}{}{От этого хлама никакого толку.}
{237000}{}{Хлам}
{237001}{}{От этого хлама никакого толку.}
{237100}{}{Хлам}
{237101}{}{Совершенно бесполезный мусор.}
{237200}{}{Хлам}
{237201}{}{Не тратьте время на всякий бесполезный хлам.}
{237300}{}{Хлам}
{237301}{}{Просто обычный мусор.}
{237400}{}{Хлам}
{237401}{}{Это Вам точно не пригодится.}
{237500}{}{Хлам}
{237501}{}{Не представляет для Вас никакого интереса, если Вы, конечно, не увлекаетесь коллекционированием мусора.}
{237600}{}{Хлам}
{237601}{}{Не представляет для Вас никакого интереса, если Вы, конечно, не увлекаетесь коллекционированием мусора.}
{237700}{}{Инструменты}
{237701}{}{Эти инструменты не пригодны к использованию.}
{237800}{}{Коробка}
{237801}{}{Пустая старая коробка - абсолютно бесполезна.}
{237900}{}{Хлам}
{237901}{}{Совершенно бесполезный мусор.}
{238000}{}{Хлам}
{238001}{}{Совершенно бесполезный мусор.}
{238100}{}{Хлам}
{238101}{}{Совершенно бесполезный мусор.}
{238200}{}{Плакат}
{238201}{}{Поблекший старый плакат "Олимп".}
{238300}{}{Освещение}
{238400}{}{Освещение}
{238500}{}{Коробка}
{238501}{}{Старая пустая коробка.}
{238600}{}{Коробка}
{238601}{}{Старая пустая коробка.}
{238700}{}{Коробка}
{238701}{}{Старая пустая коробка.}
{238800}{}{Коробка}
{238801}{}{Старая пустая коробка.}
{238900}{}{Старый ящик}
{238901}{}{В этом грязном ящике нет ничего, кроме мусора.}
{239000}{}{Старый ящик}
{239001}{}{В этом грязном ящике нет ничего, кроме мусора.}
{239100}{}{Старый ящик}
{239101}{}{В этом грязном ящике нет ничего, кроме мусора.}
{239200}{}{Старый ящик}
{239201}{}{В этом грязном ящике нет ничего, кроме мусора.}
{239300}{}{Старый ящик}
{239301}{}{В этом грязном ящике нет ничего, кроме мусора.}
{239400}{}{Старый ящик}
{239401}{}{В этом грязном ящике нет ничего, кроме мусора.}
{239500}{}{Старый ящик}
{239501}{}{В этом грязном ящике нет ничего, кроме мусора.}
{239600}{}{Старый ящик}
{239601}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{239700}{}{Старый ящик}
{239701}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{239800}{}{Старый ящик}
{239801}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{239900}{}{Старый ящик}
{239901}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{240000}{}{Старый ящик}
{240001}{}{Ржавый металлический ящик, очень тяжелый и пустой.}
{240100}{}{Старый ящик}
{240101}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{240200}{}{Junk}
{240201}{}{Крышка от ящика. Вряд ли она может Вам пригодиться.}
{240300}{}{Junk}
{240301}{}{Крышка от ящика. Вряд ли она может Вам пригодиться.}
{240400}{}{Старый ящик}
{240401}{}{Потрепанный снаружи с бесполезным содержимым внутри. Прямо как некоторые люди.}
{240500}{}{Старый ящик}
{240501}{}{Потрепанный снаружи с бесполезным содержимым внутри. Прямо как некоторые люди.}
{240600}{}{Старый ящик}
{240601}{}{Потрепанный снаружи с бесполезным содержимым внутри. Прямо как некоторые люди.}
{240700}{}{Старый ящик}
{240701}{}{Внутри только древний хлам и пыль.}
{240800}{}{Старый ящик}
{240801}{}{Внутри только древний хлам и пыль.}
{240900}{}{Старый ящик}
{240901}{}{Внутри только древний хлам и пыль.}
{241000}{}{Старый ящик}
{241001}{}{Внутри только древний хлам и пыль.}
{241100}{}{Старый шкаф}
{241101}{}{Тут ничего нет. Похоже, кто-то обшарил его до Вас.}
{241200}{}{Старый шкаф}
{241201}{}{Тут ничего нет. Похоже, кто-то обшарил его до Вас.}
{241300}{}{Старый ящик}
{241301}{}{Внутри только древний хлам и пыль.}
{241400}{}{Старый ящик}
{241401}{}{Внутри только древний хлам и пыль.}
{241500}{}{Старый ящик}
{241501}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{241600}{}{Ограждение}
{241601}{}{Небольшое переносное ограждение.}
{241700}{}{Ограждение}
{241701}{}{Небольшое переносное ограждение.}
{241800}{}{Ограждение}
{241801}{}{Небольшое переносное ограждение.}
{241900}{}{Старый ящик}
{241901}{}{Потрепанный снаружи с бесполезным содержимым внутри. Прямо как некоторые люди.}
{242000}{}{Старый ящик}
{242001}{}{Потрепанный снаружи с бесполезным содержимым внутри. Прямо как некоторые люди.}
{242100}{}{Контейнер}
{242101}{}{Прочный ржавый контейнер.}
{242200}{}{Ящик}
{242201}{}{В нем нет ничего полезного.}
{242300}{}{Ящик}
{242301}{}{В нем нет ничего полезного.}
{242400}{}{Wall}
{242500}{}{Wall}
{242600}{}{Колонна}
{242700}{}{Колонна}
{242800}{}{Колонна}
{242900}{}{Колонна}
{243000}{}{Освещение}
{243001}{}{Освещает пространство вокруг.}
{243100}{}{Освещение}
{243101}{}{Освещает пространство вокруг.}
{243200}{}{Wall}
{243300}{}{Wall}
{243400}{}{Колонна}
{243500}{}{Wall}
{243600}{}{Wall}
{243700}{}{Колонна}
{243800}{}{Wall}
{243900}{}{Wall}
{244000}{}{Картина}
{244001}{}{Похоже настоящая и отлично сохранилась.}
{244100}{}{Картина}
{244101}{}{Несколько минут изучаете картину. Настоящее искусство завораживает.}
{244200}{}{Картина}
{244201}{}{Портрет мужчины. Ваше мужественное лицо тоже неплохо бы смотрелось на портрете в золотой раме.}
{244300}{}{Пустота}
{244400}{}{Пустота}
{244500}{}{Скамейка}
{244501}{}{Не время сейчас отдыхать.}
{244600}{}{Скамейка}
{244601}{}{Четыре ножки, длинное сиденье и спинка - да это же скамейка!}
{244700}{}{Скамейка}
{244701}{}{Не время сейчас отдыхать.}
{244800}{}{Скамейка}
{244801}{}{Четыре ножки, длинное сиденье и спинка - да это же скамейка!}
{244900}{}{Старый ящик}
{244901}{}{Заглядываете внутрь - пусто.}
{245000}{}{Хлам}
{245001}{}{Совершенно бесполезный хлам.}
{245100}{}{Хлам}
{245101}{}{Совершенно бесполезный хлам.}
{245200}{}{Хлам}
{245201}{}{Совершенно бесполезный хлам.}
{245300}{}{Старый ящик}
{245301}{}{Изучаете содержимое, там один мусор - зря пачкались ржавчиной.}
{245400}{}{Ржавая железка}
{245401}{}{Даже последний бродяга не заинтересовался бы этим хламом.}
{245500}{}{Ржавая железка}
{245501}{}{Даже последний бродяга не заинтересовался бы этим хламом.}
{245600}{}{Ржавая железка}
{245601}{}{Даже последний бродяга не заинтересовался бы этим хламом.}
{245700}{}{Старый ящик}
{245701}{}{Похоже его кто-то уже обшарил и заодно испачкал кровью.}
{245800}{}{Хлам}
{245801}{}{Совершенно бесполезный хлам.}
{245900}{}{Хлам}
{245901}{}{Совершенно бесполезный хлам.}
{246000}{}{Хлам}
{246001}{}{Совершенно бесполезный хлам.}
{246100}{}{Хлам}
{246101}{}{Совершенно бесполезный хлам.}
{246200}{}{Хлам}
{246201}{}{Совершенно бесполезный хлам.}
{246300}{}{Хлам}
{246301}{}{Совершенно бесполезный хлам.}
{246400}{}{Хлам}
{246401}{}{Совершенно бесполезный хлам.}
{246500}{}{Старый ящик}
{246501}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{246600}{}{Старый ящик}
{246601}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{246700}{}{Ящик}
{246701}{}{Внутри ничего нет. Похоже кто-то обшарил его до Вас.}
{246800}{}{Ящик}
{246801}{}{Внутри ничего нет. Похоже кто-то обшарил его до Вас.}
{246900}{}{Картина}
{246901}{}{Что-то абстрактное и непонятное. Вам больше нравится рама, нежели эта картина.}
{247000}{}{Старинная картина}
{247001}{}{Интересный пейзаж. Вы понимаете, что никогда не увидите его в реальности.}
{247100}{}{Картина}
{247101}{}{Несколько минут изучаете картину. Настоящее искусство завораживает.}
{247200}{}{Картина}
{247201}{}{Интересный пейзаж. Вы понимаете, что никогда не увидите его в реальности.}
{247300}{}{Картина}
{247301}{}{Несколько минут изучаете картину. Настоящее искусство завораживает.}
{247400}{}{Картина}
{247401}{}{Что-то явно съедобное и очень важное, раз люди сочли эту еду достойной золотой рамы.}
{247500}{}{Картина}
{247501}{}{Что-то явно съедобное и очень важное, раз люди сочли эту еду достойной золотой рамы.}
{247600}{}{Картина}
{247601}{}{Что-то абстрактное и непонятное. Вам больше нравится рама, нежели эта картина.}
{247700}{}{Заваленная лестница}
{247701}{}{Проход наверх заблокирован.}
{247800}{}{Картина}
{247801}{}{Интересный пейзаж. Вы понимаете, что никогда не увидите его в реальности.}
{247900}{}{Картина}
{247901}{}{Что-то явно съедобное и очень важное, раз люди сочли эту еду достойной золотой рамы.}
{248000}{}{Заваленная лестница}
{248001}{}{Проход заблокирован.}
{248100}{}{Лифт}
{248101}{}{Служебный лифт, ведущий в Тартар.}
{248200}{}{Bed}
{248201}{}{Эта кровать отлично сохранилась.}
{248300}{}{Bed}
{248301}{}{Эта кровать отлично сохранилась.}
{248400}{}{Bed}
{248401}{}{Эта кровать отлично сохранилась.}
{248500}{}{Bed}
{248501}{}{Эта кровать отлично сохранилась.}
{248600}{}{Кресло}
{248601}{}{Настоящее кожаное кресло. Вы никогда не сидели на чем-либо настолько удобном.}
{248700}{}{Кресло}
{248701}{}{Настоящее кожаное кресло. Вы никогда не сидели на чем-либо настолько удобном.}
{248800}{}{Кресло}
{248801}{}{Настоящее кожаное кресло. Вы никогда не сидели на чем-либо настолько удобном.}
{248900}{}{Кресло}
{248901}{}{Настоящее кожаное кресло. Вы никогда не сидели на чем-либо настолько удобном.}
{249000}{}{Кресло}
{249001}{}{Очутившись в таком кресле, Ваша задница испытает неизведанные вершины комфорта.}
{249100}{}{Кресло}
{249101}{}{Очутившись в таком кресле, Ваша задница испытает неизведанные вершины комфорта.}
{249200}{}{Кресло}
{249201}{}{Очутившись в таком кресле, Ваша задница испытает неизведанные вершины комфорта.}
{249300}{}{Кресло}
{249301}{}{Очутившись в таком кресле, Ваша задница испытает неизведанные вершины комфорта.}
{249400}{}{Кожаный диван}
{249401}{}{Вы даже не представляли насколько удобной может быть мебель.}
{249500}{}{Кожаный диван}
{249501}{}{Вы даже не представляли насколько удобной может быть мебель.}
{249600}{}{Кожаный диван}
{249601}{}{Вы даже не представляли насколько удобной может быть мебель.}
{249700}{}{Кожаный диван}
{249701}{}{Вы даже не представляли насколько удобной может быть мебель.}
{249800}{}{Кожаный диван}
{249801}{}{Теперь Вы знаете что такое шикарная мебель.}
{249900}{}{Кожаный диван}
{249901}{}{Теперь Вы знаете что такое шикарная мебель.}
{250000}{}{Кожаный диван}
{250001}{}{Теперь Вы знаете что такое шикарная мебель.}
{250100}{}{Кожаный диван}
{250101}{}{Теперь Вы знаете что такое шикарная мебель.}
{250200}{}{Колонна}
{250201}{}{Прекрасный образец архитектуры эпохи неоклассицизма.}
{250300}{}{Стойка с ячейками}
{250301}{}{В ней до сих пор лежат ключи и старые письма.}
{250400}{}{Колонна}
{250401}{}{Прекрасный образец архитектуры эпохи неоклассицизма.}
{250500}{}{Стойка}
{250501}{}{Стойка с вывеской "Отель Хортон"}
{250600}{}{Стойка}
{250601}{}{Стойка с вывеской "Отель Хортон"}
{250700}{}{Стойка}
{250701}{}{Стойка с вывеской "Отель Хортон"}
{250800}{}{Лестница наверх}
{250801}{}{Лестница ведет на верхний этаж.}
{250900}{}{Wall}
{251000}{}{Wall}
{251100}{}{Wall}
{251200}{}{Лестница вниз}
{251201}{}{Лестница ведет на нижний этаж.}
{251300}{}{Ladder}
{251301}{}{Лестница на верхний этаж.}
{251400}{}{Ladder}
{251401}{}{Лестница на верхний этаж.}
{251500}{}{Ladder}
{251501}{}{Лестница на нижний этаж.}
{251600}{}{Заваленные лестницы}
{251601}{}{Проходы на верхний и нижний этажи заблокированы.}
{251700}{}{Генератор}
{251701}{}{Устройство, вырабатывающее электроэнергию.}
{251800}{}{Большой генератор}
{251801}{}{Он вырабатывает энергию для башни.}
{251900}{}{Большой генератор}
{251901}{}{Он вырабатывает энергию для башни.}
{252000}{}{Прицеп с вещами}
{252001}{}{Сделан из багажника автомобиля.}
{252100}{}{Прицеп с вещами}
{252101}{}{Умельцы похоже переделали багажник автомобиля в прицеп.}
{252200}{}{Floor}
{252201}{}{Цифровая разметка на полу.}
{252300}{}{Floor}
{252301}{}{Цифровая разметка на полу.}
{252400}{}{Floor}
{252401}{}{Цифровая разметка на полу.}
{252500}{}{Floor}
{252501}{}{Цифровая разметка на полу.}
{252600}{}{Floor}
{252601}{}{Цифровая разметка на полу.}
{252700}{}{Floor}
{252701}{}{Буквенная разметка на полу.}
{252800}{}{Floor}
{252801}{}{Буквенная разметка на полу.}
{252900}{}{Floor}
{252901}{}{Буквенная разметка на полу.}
{253000}{}{Floor}
{253001}{}{Буквенная разметка на полу.}
{253100}{}{Забитая дверь}
{253101}{}{Вы не пройдете.}
{253200}{}{Table}
{253201}{}{Медицинский стол.}
{253300}{}{Table}
{253301}{}{Медицинский стол.}
{253400}{}{Table}
{253401}{}{Медицинский стол.}
{253500}{}{Электрический щиток}
{253501}{}{Элемент системы электрообеспечения отеля.}
{253600}{}{Олимп}
{253601}{}{Вот он! Обитель надежд всех страждущих.}
{253700}{}{Олимп}
{253701}{}{Вот он! Обитель надежд всех страждущих.}
{253800}{}{Олимп}
{253801}{}{Вот он! Обитель надежд всех страждущих.}
{253900}{}{Олимп}
{253901}{}{Вот он! Обитель надежд всех страждущих.}
{254000}{}{Олимп}
{254001}{}{Вот он! Обитель надежд всех страждущих.}
{254100}{}{Олимп}
{254101}{}{Вот он! Обитель надежд всех страждущих.}
{254200}{}{Олимп}
{254201}{}{Вот он! Обитель надежд всех страждущих.}
{254300}{}{Олимп}
{254301}{}{Вот он! Обитель надежд всех страждущих.}
{254400}{}{Олимп}
{254401}{}{Вот он! Обитель надежд всех страждущих.}
{254500}{}{Олимп}
{254501}{}{Вот он! Обитель надежд всех страждущих.}
{254600}{}{Олимп}
{254601}{}{Вот он! Обитель надежд всех страждущих.}
{254700}{}{Олимп}
{254701}{}{Вот он! Обитель надежд всех страждущих.}
{254800}{}{Олимп}
{254801}{}{Вот он! Обитель надежд всех страждущих.}
{254900}{}{Лифт}
{254901}{}{Похоже, это единственный вариант перемещаться по этажам внутри башни.}
{255000}{}{Лифт}
{255001}{}{Похоже это единственный вариант перемещаться по этажам внутри башни.}
{255100}{}{Олимп}
{255101}{}{Вот он! Обитель надежд всех страждущих.}
{255200}{}{Олимп}
{255201}{}{Вот он! Обитель надежд всех страждущих.}
{255300}{}{Олимп}
{255301}{}{Вот он! Обитель надежд всех страждущих.}
{255400}{}{Металлическая арка}
{255401}{}{Изрядно проржавевшая, но все еще крепкая.}
{255500}{}{Металлическая арка}
{255501}{}{Изрядно проржавевшая, но все еще крепкая.}
{255600}{}{Тень}
{255700}{}{Кофе-машина}
{255701}{}{Вы нажимаете кнопку и ничего не происходит, видимо она сломана.}
{255800}{}{Кофе-машина}
{255801}{}{Вы нажимаете кнопку и ничего не происходит, видимо она сломана.}
{255900}{}{Печь}
{255901}{}{Обычная бытовая печь.}
{256000}{}{Памятник}
{256001}{}{Памятник символам довоенной эпохи. Заржавел, но не потерял внушительности.}
{256100}{}{Памятник}
{256101}{}{Памятник символам довоенной эпохи. Заржавел, но не потерял внушительности.}
{256200}{}{Памятник}
{256201}{}{Памятник символам довоенной эпохи. Заржавел, но не потерял внушительности.}
{256300}{}{Памятник}
{256301}{}{Памятник символам довоенной эпохи. Заржавел, но не потерял внушительности.}
{256400}{}{Коробки}
{256401}{}{Эти коробки пусты, здесь нечем поживиться.}
{256500}{}{Коробки}
{256501}{}{Эти коробки пусты, здесь нечем поживиться.}
{256600}{}{Коробки}
{256601}{}{Эти коробки пусты, здесь нечем поживиться.}
{256700}{}{Table}
{256701}{}{Медицинский стол.}
{256800}{}{Table}
{256801}{}{Медицинский стол.}
{256900}{}{Коробки}
{256901}{}{Столько коробок и совершенно ничего полезного - какое разочарование!}
{257000}{}{Коробки}
{257001}{}{Столько коробок и совершенно ничего полезного - какое разочарование!}
{257100}{}{Коробки}
{257101}{}{Эти коробки пусты, здесь нечем поживиться.}
{257200}{}{Лифт}
{257201}{}{Двери лифта.}
{257300}{}{Лифт}
{257301}{}{Похоже, это единственный вариант перемещаться по этажам внутри башни.}
{257400}{}{Лифт}
{257401}{}{Двери лифта.}
{257500}{}{Лифт}
{257501}{}{Двери лифта.}
{257600}{}{Бронепластина}
{257601}{}{Вероятно защищает заднюю стену от разлетающихся внутренностей испытуемых.}
{257700}{}{Генератор}
{257701}{}{Устройство, вырабатывающее электроэнергию.}
{257800}{}{Заблокированный вход в лифт}
{257801}{}{Вы не пройдете.}
{257900}{}{Аккумулятор}
{257901}{}{Резервный источник тока.}
{258000}{}{Table}
{258001}{}{Судя по инструментам это стол инженера.}
{258100}{}{Table}
{258101}{}{Судя по инструментам это стол инженера.}
{258200}{}{Table}
{258201}{}{Это самый большой стол, который Вы когда-либо видели.}
{258300}{}{Table}
{258301}{}{Это самый большой стол, который Вы когда-либо видели.}
{258400}{}{Коробки}
{258401}{}{Эти коробки пусты, здесь нечем поживиться.}
{258500}{}{Коробки}
{258501}{}{Эти коробки пусты, здесь нечем поживиться.}
{258600}{}{Wall}
{258700}{}{Wall}
{258800}{}{Хлам}
{258801}{}{Совершенно бесполезный хлам.}
{258900}{}{Хлам}
{258901}{}{Совершенно бесполезный хлам.}
{259000}{}{Хлам}
{259001}{}{Совершенно бесполезный хлам.}
{259100}{}{Старая машина}
{259101}{}{Вряд ли это ведро с гайками еще способно ездить.}
{259200}{}{Балка}
{259201}{}{Опорная конструкция.}
{259300}{}{Балка}
{259301}{}{Опорная конструкция.}
{259400}{}{Балка}
{259401}{}{Опорная конструкция.}
{259500}{}{Балка}
{259501}{}{Опорная конструкция.}
{259600}{}{Балка}
{259601}{}{Опорная конструкция.}
{259700}{}{Балка}
{259701}{}{Опорная конструкция.}
{259800}{}{Балка}
{259801}{}{Опорная конструкция.}
{259900}{}{Балка}
{259901}{}{Опорная конструкция.}
{260000}{}{Балка}
{260001}{}{Опорная конструкция.}
{260100}{}{Балка}
{260101}{}{Опорная конструкция.}
{260200}{}{Балка}
{260201}{}{Опорная конструкция.}
{260300}{}{Балка}
{260301}{}{Опорная конструкция.}
{260400}{}{Wall}
{260500}{}{Wall}
{260600}{}{Wall}
{260700}{}{Wall}
{260800}{}{Wall}
{260900}{}{Wall}
{261000}{}{Вентиляция}
{261001}{}{Вентиляционная решетка.}
{261100}{}{Вентиляция}
{261101}{}{Грязная вентиляционная решетка.}
{261200}{}{Вентиляция}
{261201}{}{Вентиляционная решетка.}
{261300}{}{Вентиляция}
{261301}{}{Грязная вентиляционная решетка.}
{261400}{}{Старый ящик}
{261401}{}{Возможно его содержимое и представляло интерес, но это было очень давно.}
{261500}{}{Junk}
{261501}{}{Вряд ли кто-то способен найти этому хламу применение.}
{261600}{}{Junk}
{261601}{}{Вряд ли кто-то способен найти этому хламу применение.}
{261700}{}{Койка}
{261701}{}{Больничная койка с монитором.}
{261800}{}{Wall}
{261900}{}{Wall}
{262000}{}{Wall}
{262100}{}{Wall}
{262200}{}{Урна}
{262201}{}{Полная урна мусора.}
{262300}{}{Коробка}
{262301}{}{Ничего интересного - один бесполезный хлам.}
{262400}{}{Труба}
{262401}{}{Элемент коммуникационных систем Олимпа.}
{262500}{}{Огромная машина}
{262501}{}{На машине написано "Клон-машина".}
{262600}{}{Огромная машина}
{262601}{}{На машине написано "Клон-машина".}
{262700}{}{Металлическая пластина.}
{262701}{}{Крайне маловероятно, что она Вам пригодится.}
{262800}{}{Металлическая пластина.}
{262801}{}{Крайне маловероятно, что она Вам пригодится.}
{262900}{}{Металлическая пластина.}
{262901}{}{Крайне маловероятно, что она Вам пригодится.}
{263000}{}{Коробка}
{263001}{}{Полная коробка барахла и ни единого полезного предмета.}
{263100}{}{Коробка}
{263101}{}{Полная коробка барахла и ни единого полезного предмета.}
{263200}{}{Коробка}
{263201}{}{Полная коробка барахла и ни единого полезного предмета.}
{263300}{}{Ящик}
{263301}{}{Крепкий и надежный, но совершенно пустой.}
{263400}{}{Хлам}
{263401}{}{Вряд ли кто-то способен найти этому хламу применение.}
{263500}{}{Wall}
{263600}{}{Wall}
{263700}{}{Wall}
{263800}{}{Wall}
{263900}{}{Громкоговоритель}
{263901}{}{Старый ржавый громкоговоритель.}
{264000}{}{Громкоговоритель}
{264001}{}{Старый ржавый громкоговоритель.}
{264100}{}{Огромная машина}
{264101}{}{На машине написано "Клон-машина".}
{264200}{}{Огромная машина}
{264201}{}{На машине написано "Клон-машина".}
{264300}{}{Огромная машина}
{264301}{}{На машине написано "Клон-машина".}
{264400}{}{Огромная машина}
{264401}{}{На машине написано "Клон-машина".}
{264500}{}{Труп}
{264501}{}{Кажется в этой машине что-то пошло не так.}
{264600}{}{Старый ящик}
{264601}{}{Такой огромный и такой пустой.}
{264700}{}{Ящик}
{264701}{}{Внутри только бесполезный мусор.}
{264800}{}{Wall}
{264900}{}{Wall}
{265000}{}{Стол с вычислителем}
{265001}{}{Рабочее место инженера.}
{265100}{}{Стол с вычислителем}
{265101}{}{Рабочее место инженера с включенным вычислителем.}
{265200}{}{Стол с вычислителем}
{265201}{}{Рабочее место инженера.}
{265300}{}{Стол с вычислителем}
{265301}{}{Рабочее место инженера с включенным вычислителем.}
{265400}{}{Стол с вычислителем}
{265401}{}{Рабочее место инженера с включенным вычислителем.}
{265500}{}{Стол с вычислителем}
{265501}{}{Рабочее место инженера.}
{265600}{}{Стол с вычислителем}
{265601}{}{Рабочее место инженера с включенным вычислителем.}
{265700}{}{Стол с вычислителем}
{265701}{}{Рабочее место инженера.}
{265800}{}{Стул}
{265801}{}{Предмет мебели, предназначенный для поддержания тела человека в сидячем положении.}
{265900}{}{Стул}
{265901}{}{Этот стул был бы совсем обыкновенным, если бы не колесики. Интересно, здесь устраивали гонки на стульях?}
{266000}{}{Стул}
{266001}{}{Этот стул был бы совсем обыкновенным, если бы не колесики. Интересно, здесь устраивали гонки на стульях?}
{266100}{}{Стул}
{266101}{}{Предмет мебели, предназначенный для поддержания тела человека в сидячем положении.}
{266200}{}{Хлам}
{266201}{}{Даже последний бродяга не заинтересовался бы этим хламом.}
{266300}{}{Коробка}
{266301}{}{Обычная коробка с бесполезным хламом.}
{266400}{}{Коробка}
{266401}{}{Обычная коробка с бесполезным хламом.}
{266500}{}{Провода}
{266501}{}{Напольный кабель.}
{266600}{}{Провода}
{266601}{}{Напольный кабель.}
{266700}{}{Провода}
{266701}{}{Напольный кабель.}
{266800}{}{Провода}
{266801}{}{Напольный кабель.}
{266900}{}{Провода}
{266901}{}{Напольный кабель.}
{267000}{}{Провода}
{267001}{}{Напольный кабель.}
{267100}{}{Провода}
{267101}{}{Напольный кабель.}
{267200}{}{Хлам}
{267201}{}{Совершенно бесполезный хлам.}
{267300}{}{Хлам}
{267301}{}{Совершенно бесполезный хлам.}
{267400}{}{Хлам}
{267401}{}{Совершенно бесполезный хлам.}
{267500}{}{Хлам}
{267501}{}{Бесполезный мусор.}
{267600}{}{Хлам}
{267601}{}{Бесполезный мусор.}
{267700}{}{Хлам}
{267701}{}{Совершенно бесполезный хлам.}
{267800}{}{Junk}
{267801}{}{В бутылке какая-то сомнительная жидкость, ее лучше не трогать.}
{267900}{}{Junk}
{267901}{}{Обычная пустая бутылка.}
{268000}{}{Хлам}
{268001}{}{Трудно вообразить, что кто-то в здравом уме способен заинтересоваться этим хламом.}
{268100}{}{Хлам}
{268101}{}{Кучка бесполезного хлама.}
{268200}{}{Хлам}
{268201}{}{Трудно вообразить, что кто-то в здравом уме способен заинтересоваться этим хламом.}
{268300}{}{Хлам}
{268301}{}{Трудно вообразить, что кто-то в здравом уме способен заинтересоваться этим хламом.}
{268400}{}{Вычислитель}
{268401}{}{Отсюда осуществляется управление солнечными батареями башни.}
{268500}{}{Ограждение}
{268501}{}{Заржавевшее аварийное ограждение.}
{268600}{}{Ограждение}
{268601}{}{Заржавевшее аварийное ограждение.}
{268700}{}{Ограждение}
{268701}{}{Заржавевшее аварийное ограждение.}
{268800}{}{Ограждение}
{268801}{}{Заржавевшее аварийное ограждение.}
{268900}{}{Wall}
{268901}{}{The wall of the skyscraper.}
{269000}{}{Wall}
{269001}{}{The wall of the skyscraper.}
{269100}{}{Парапет}
{269101}{}{На него можно облокотиться и задумчиво смотреть вдаль.}
{269200}{}{Парапет}
{269201}{}{На него можно облокотиться и задумчиво смотреть вдаль.}
{269300}{}{Парапет}
{269301}{}{На него можно облокотиться и задумчиво смотреть вдаль.}
{269400}{}{Освещение}
{269500}{}{Освещение}
{269600}{}{Пустоши}
{269601}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{269700}{}{Пустоши}
{269701}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{269800}{}{Пустоши}
{269801}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{269900}{}{Пустоши}
{269901}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270000}{}{Пустоши}
{270001}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270100}{}{Пустоши}
{270101}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270200}{}{Пустоши}
{270201}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270300}{}{Пустоши}
{270301}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270400}{}{Пустоши}
{270401}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270500}{}{Пустоши}
{270501}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270600}{}{Пустоши}
{270601}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270700}{}{Пустоши}
{270701}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270800}{}{Пустоши}
{270801}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{270900}{}{Пустоши}
{270901}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{271000}{}{Пустоши}
{271001}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{271100}{}{Пустоши}
{271101}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{271200}{}{Бронзовый орел}
{271201}{}{Огромный орел - символ непобедимой страны.}
{271300}{}{Wall}
{271301}{}{The wall of the skyscraper.}
{271400}{}{Wall}
{271401}{}{The wall of the skyscraper.}
{271500}{}{Wall}
{271501}{}{The wall of the skyscraper.}
{271600}{}{Wall}
{271601}{}{The wall of the skyscraper.}
{271700}{}{Wall}
{271701}{}{The wall of the skyscraper.}
{271800}{}{Wall}
{271801}{}{The wall of the skyscraper.}
{271900}{}{Wall}
{271901}{}{The wall of the skyscraper.}
{272000}{}{Пустоши}
{272001}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{272100}{}{Пустоши}
{272101}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{272200}{}{Пустоши}
{272201}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{272300}{}{Пустоши}
{272301}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{272400}{}{Пустоши}
{272401}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{272500}{}{Пустоши}
{272501}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{272600}{}{Диван}
{272601}{}{Роскошный кожаный диван.}
{272700}{}{Диван}
{272701}{}{Роскошный кожаный диван.}
{272800}{}{Пустоши}
{272801}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{272900}{}{Пустоши}
{272901}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273000}{}{Пустоши}
{273001}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273100}{}{Пустоши}
{273101}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273200}{}{Пустоши}
{273201}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273300}{}{Пустоши}
{273301}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273400}{}{Пустоши}
{273401}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273500}{}{Пустоши}
{273501}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273600}{}{Пустоши}
{273601}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273700}{}{Пустоши}
{273701}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273800}{}{Пустоши}
{273801}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{273900}{}{Пустоши}
{273901}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{274000}{}{Пустоши}
{274001}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{274100}{}{Пустоши}
{274101}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{274200}{}{Пустоши}
{274201}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{274300}{}{Пустоши}
{274301}{}{Отсюда пустоши выглядят мирными и спокойными. Понемногу Вы забываете о жестокости и опасностях Радиуса внизу.}
{274400}{}{Биомасса}
{274401}{}{Биоматерия, совокупность организмов.}
{274500}{}{Биомасса}
{274501}{}{Биоматерия, совокупность организмов.}
{274600}{}{Биомасса}
{274601}{}{Биоматерия, совокупность организмов.}
{274700}{}{Биомасса}
{274701}{}{Биоматерия, совокупность организмов.}
{274800}{}{Биомасса}
{274801}{}{Биоматерия, совокупность организмов.}
{274900}{}{Лифт}
{274901}{}{Двери лифта.}
{275000}{}{Двери}
{275001}{}{Проход заблокирован.}
{275100}{}{Двери}
{275101}{}{Проход заблокирован.}
{275200}{}{Table}
{275201}{}{Это самый большой стол, который Вы когда-либо видели.}
{275300}{}{Table}
{275301}{}{Это самый большой стол, который Вы когда-либо видели.}
{275400}{}{Вычислитель}
{275401}{}{Центр адаптивной защиты "Цербер".}
{275500}{}{Вычислитель}
{275501}{}{Центр превентивных расчетов "Андромеда".}
{275600}{}{Вычислитель}
{275601}{}{Центр логических модуляций "Борей".}
{275700}{}{Система охлаждения}
{275701}{}{Вы слышите как по трубкам циркулирует охлаждающая жидкость.}
{275800}{}{Систематизатор}
{275801}{}{Огромная вычислительная машина с кучей мигающих лампочек.}
{275900}{}{Систематизатор}
{275901}{}{Огромная вычислительная машина с кучей мигающих лампочек.}
{276000}{}{Экран}
{276001}{}{Огромный покрытый пылью экран, похоже, он не работал много лет.}
{276100}{}{Кресло}
{276101}{}{Удобное кожаное кресло.}
{276200}{}{Диван}
{276201}{}{Роскошный кожаный диван.}
{276300}{}{Диван}
{276301}{}{Роскошный кожаный диван.}
{276400}{}{Кресло}
{276401}{}{Удобное кожаное кресло.}
{276500}{}{Вычислитель}
{276501}{}{Судя по размеру, эта махина обладает огромными вычислительными мощностями.}
{276600}{}{вычислитель}
{276601}{}{Судя по размеру, эта махина обладает огромными вычислительными мощностями.}
{276700}{}{Вычислитель}
{276701}{}{Судя по размеру, эта махина обладает огромными вычислительными мощностями.}
{276800}{}{Вычислитель}
{276801}{}{Судя по размеру, эта махина обладает огромными вычислительными мощностями.}
{276900}{}{Камера}
{276901}{}{Судя по горящей лампочке она снимает, вероятно, Вас.}
{277000}{}{Громкоговоритель}
{277001}{}{Старый громкоговоритель, вероятно, он еще работает.}
{277100}{}{Лифт}
{277101}{}{Двери лифта.}
{277200}{}{Осколки}
{277201}{}{Тысячи их! И каждый по-своему уникален.}
{277300}{}{Осколки}
{277301}{}{Тысячи их! И каждый по-своему уникален.}
{277400}{}{Осколки}
{277401}{}{Тысячи их! И каждый по-своему уникален.}
{277500}{}{Осколки}
{277501}{}{Тысячи их! И каждый по-своему уникален.}
{277600}{}{Осколки}
{277601}{}{Тысячи их! И каждый по-своему уникален.}
{277700}{}{Осколки}
{277701}{}{Тысячи их! И каждый по-своему уникален.}
{277800}{}{Осколки}
{277801}{}{Тысячи их! И каждый по-своему уникален.}
{277900}{}{Осколки}
{277901}{}{Тысячи их! И каждый по-своему уникален.}
{278000}{}{Осколки}
{278001}{}{Тысячи их! И каждый по-своему уникален.}
{278100}{}{Осколки}
{278101}{}{Тысячи их! И каждый по-своему уникален.}
{278200}{}{Осколки}
{278201}{}{Тысячи их! И каждый по-своему уникален.}
{278300}{}{Осколки}
{278301}{}{Тысячи их! И каждый по-своему уникален.}
{278400}{}{Осколки}
{278401}{}{Тысячи их! И каждый по-своему уникален.}
{278500}{}{Осколки}
{278501}{}{Тысячи их! И каждый по-своему уникален.}
{278600}{}{Осколки}
{278601}{}{Тысячи их! И каждый по-своему уникален.}
{278700}{}{Осколки}
{278701}{}{Тысячи их! И каждый по-своему уникален.}
{278800}{}{Осколки}
{278801}{}{Тысячи их! И каждый по-своему уникален.}
{278900}{}{Осколки}
{278901}{}{Тысячи их! И каждый по-своему уникален.}
{279000}{}{Осколки}
{279001}{}{Тысячи их! И каждый по-своему уникален.}
{279100}{}{Осколки}
{279101}{}{Тысячи их! И каждый по-своему уникален.}
{279200}{}{Осколки}
{279201}{}{Тысячи их! И каждый по-своему уникален.}
{279300}{}{Осколки}
{279301}{}{Тысячи их! И каждый по-своему уникален.}
{279400}{}{Осколки}
{279401}{}{Тысячи их! И каждый по-своему уникален.}
{279500}{}{Осколки}
{279501}{}{Тысячи их! И каждый по-своему уникален.}
{279600}{}{Осколки}
{279601}{}{Тысячи их! И каждый по-своему уникален.}
{279700}{}{Осколки}
{279701}{}{Тысячи их! И каждый по-своему уникален.}
{279800}{}{Осколки}
{279801}{}{Тысячи их! И каждый по-своему уникален.}
{279900}{}{Осколки}
{279901}{}{Тысячи их! И каждый по-своему уникален.}
{280000}{}{Осколки}
{280001}{}{Тысячи их! И каждый по-своему уникален.}
{280100}{}{Осколки}
{280101}{}{Тысячи их! И каждый по-своему уникален.}
{280200}{}{Система контроля башни}
{280201}{}{На больших мониторах с огромной скоростью пробегают строки символов.}
{280300}{}{Система контроля башни}
{280301}{}{На больших мониторах с огромной скоростью пробегают строки символов.}
{280400}{}{Система контроля башни}
{280401}{}{На больших мониторах с огромной скоростью пробегают строки символов.}
{280500}{}{Система контроля башни}
{280501}{}{На больших мониторах с огромной скоростью пробегают строки символов.}
{280600}{}{Floor}
{280601}{}{Из под решетчатых пластин на полу пробивается красноватое свечение.}
{280700}{}{Floor}
{280701}{}{Из под решетчатых пластин на полу пробивается красноватое свечение.}
{280800}{}{Floor}
{280801}{}{Из под решетчатых пластин на полу пробивается красноватое свечение.}
{280900}{}{Floor}
{280901}{}{Из под решетчатых пластин на полу пробивается красноватое свечение.}
{281000}{}{Floor}
{281001}{}{Из под решетчатых пластин на полу пробивается красноватое свечение.}
{281100}{}{Бронестена}
{281101}{}{Защитная конструкция.}
{281200}{}{Бронестена}
{281201}{}{Защитная конструкция.}
{281300}{}{Бронестена}
{281301}{}{Защитная конструкция.}
{281400}{}{Бронестена}
{281401}{}{Защитная конструкция.}
{281500}{}{Бронестена}
{281501}{}{Защитная конструкция.}
{281600}{}{Бронестена}
{281601}{}{Защитная конструкция.}
{281700}{}{Бронестена}
{281701}{}{Защитная конструкция.}
{281800}{}{Бронестена}
{281801}{}{Защитная конструкция.}
{281900}{}{Бронестена}
{281901}{}{Защитная конструкция.}
{282000}{}{Разбитый защитный экран}
{282001}{}{Экран разлетелся вдребезги.}
{282100}{}{Разбитый защитный экран}
{282101}{}{Экран разлетелся вдребезги.}
{282200}{}{Разбитый защитный экран}
{282201}{}{Экран разлетелся вдребезги.}
{282300}{}{Ядовитая жижа}
{282301}{}{Жутковато побулькивает.}
{282400}{}{Ядовитая жижа}
{282401}{}{Жутковато побулькивает.}
{282500}{}{Ядовитая жижа}
{282501}{}{Жутковато побулькивает.}
{282600}{}{Стальная дверь}
{282601}{}{Ржавая, но выглядит вполне надежной.}
{282700}{}{Труп женщины}
{282701}{}{Ужасно смердящие останки какой-то женщины.}
{282800}{}{Песок}
{282900}{}{Песок}
{283000}{}{Песок}
{283100}{}{Песок}
{283200}{}{Песок}
{283300}{}{Хлам}
{283301}{}{Какой-то мусор в воде.}
{283400}{}{Ваза}
{283401}{}{Глиняная ваза, наполненная чем-то очень похожим на кровь.}
{283500}{}{Ведро}
{283501}{}{Ничего необычного - простое ведро, из которого свисают чьи-то кишки.}
{283600}{}{Тотем}
{283601}{}{Похоже аборигены молятся этой штуке.}
{283700}{}{Тотем}
{283701}{}{Похоже аборигены молятся этой штуке.}
{283800}{}{Тотем}
{283801}{}{Похоже аборигены молятся этой штуке.}
{283900}{}{Тотем}
{283901}{}{Похоже аборигены молятся этой штуке.}
{284000}{}{Тотем}
{284001}{}{Устрашаюшая штука с черепом, костями и красными глазами - у аборигенов оригинальные представления о богах.}
{284100}{}{Тотем}
{284101}{}{Устрашаюшая штука с черепом, костями и красными глазами - у аборигенов оригинальные представления о богах.}
{284200}{}{Странный пень}
{284201}{}{Непонятная конструкция с тлеющими углями, наверное, несет какой-то религиозный смысл.}
{284300}{}{Странный пень}
{284301}{}{Непонятная конструкция с тлеющими углями, наверное, несет какой-то религиозный смысл.}
{284400}{}{Прут}
{284401}{}{Толстый металлический прут.}
{284500}{}{Дерево}
{284501}{}{Высохшее дерево.}
{284600}{}{Дерево}
{284601}{}{Высохшее дерево.}
{284700}{}{Дерево}
{284701}{}{Высохшее дерево.}
{284800}{}{Дерево}
{284801}{}{Высохшее дерево.}
{284900}{}{Дерево}
{284901}{}{Высохшее дерево.}
{285000}{}{Дерево}
{285001}{}{Высохшее дерево.}
{285100}{}{Дерево}
{285101}{}{Высохшее дерево.}
{285200}{}{Дерево}
{285201}{}{Высохшее дерево.}
{285300}{}{Дерево}
{285301}{}{Высохшее дерево.}
{285400}{}{Дерево}
{285401}{}{Высохшее дерево.}
{285500}{}{Дерево}
{285501}{}{Высохшее дерево.}
{285600}{}{Дерево}
{285601}{}{Высохшее дерево.}
{285700}{}{Дерево}
{285701}{}{Высохшее дерево.}
{285800}{}{Дерево}
{285801}{}{Высохшее дерево.}
{285900}{}{Дерево}
{285901}{}{Высохшее дерево.}
{286000}{}{Дерево}
{286001}{}{Высохшее дерево.}
{286100}{}{Листва}
{286101}{}{Какое-то растение.}
{286200}{}{Листва}
{286201}{}{Какое-то растение.}
{286300}{}{Листва}
{286301}{}{Какое-то растение.}
{286400}{}{Листва}
{286401}{}{Какое-то растение.}
{286500}{}{Листва}
{286501}{}{Какое-то растение.}
{286600}{}{Листва}
{286601}{}{Какое-то растение.}
{286700}{}{Листва}
{286701}{}{Какое-то растение.}
{286800}{}{Листва}
{286801}{}{Какое-то растение.}
{286900}{}{Листва}
{286901}{}{Какое-то растение.}
{287000}{}{Листва}
{287001}{}{Какое-то растение.}
{287100}{}{Камень}
{287200}{}{Камень}
{287300}{}{Камень}
{287400}{}{Камень}
{287500}{}{Камень}
{287600}{}{Камень}
{287700}{}{Камень}
{287800}{}{Камень}
{287900}{}{Камень}
{288000}{}{Камень}
{288100}{}{Камень}
{288200}{}{Камень}
{288300}{}{Камень}
{288400}{}{Камень}
{288500}{}{Камень}
{288600}{}{Камень}
{288700}{}{Камень}
{288800}{}{Камень}
{288900}{}{Камень}
{289000}{}{Камень}
{289100}{}{Камень}
{289200}{}{Камень}
{289300}{}{Камень}
{289400}{}{Камень}
{289500}{}{Камень}
{289600}{}{Камень}
{289700}{}{Камень}
{289800}{}{Камень}
{289900}{}{Камень}
{289901}{}{Не время собирать камни.}
{290000}{}{Камень}
{290001}{}{Не время собирать камни.}
{290100}{}{Камень}
{290101}{}{Не время собирать камни.}
{290200}{}{Камень}
{290201}{}{Не время собирать камни.}
{290300}{}{Костер}
{290301}{}{Аккуратно обложенный камнями костер. Видимо камни сохраняют тепло.}
{290400}{}{Факел}
{290401}{}{Огромный горящий факел - похоже аборигены почитают огонь.}
{290500}{}{Тотем}
{290501}{}{Это племя, очевидно, очень религиозно.}
{290600}{}{Тотем}
{290601}{}{Это племя, очевидно, очень религиозно.}
{290700}{}{Тотем}
{290701}{}{Это племя, очевидно, очень религиозно.}
{290800}{}{Тотем}
{290801}{}{Каменный тотем, еще один почитаемый племенем объект.}
{290900}{}{Тотем}
{290901}{}{Каменный тотем, еще один почитаемый племенем объект.}
{291000}{}{Тотем}
{291001}{}{Каменный тотем, еще один почитаемый племенем объект.}
{291100}{}{Тотем}
{291101}{}{Из этого торчат кости и угли внутри потухли. Интересно, у них есть график разжигания тотемов?}
{291200}{}{Тотем}
{291201}{}{Какие большие кости!}
{291300}{}{Тотем}
{291301}{}{Из этого торчат кости и угли внутри потухли. Интересно, у них есть график разжигания тотемов?}
{291400}{}{Тотем}
{291401}{}{Какие большие кости!}
{291500}{}{Скамья}
{291501}{}{Жесткая и холодная каменная скамья.}
{291600}{}{Кол}
{291601}{}{Похоже на какое-то орудие племени.}
{291700}{}{Тотем}
{291701}{}{Похоже на этот кол насажено мясо - их боги требуют жертв.}
{291800}{}{Части тотемов}
{291801}{}{И тут кости, интересно, чьи это кости.}
{291900}{}{Жаровня}
{291901}{}{Интересно, что они там жарят.}
{292000}{}{Забор}
{292001}{}{Небольшой заборчик и маленький столик с чем-то, похожим на мясо.}
{292100}{}{Странный пень}
{292101}{}{Внутри тлеют угли - похоже боги племени любят огонь.}
{292200}{}{Пень}
{292201}{}{Внутри тлеют угли - похоже боги племени любят огонь.}
{292300}{}{Камни}
{292301}{}{Разложены ровным кругом вокруг костра.}
{292400}{}{Камни}
{292401}{}{Разложены ровным кругом вокруг костра.}
{292500}{}{Склон}
{292501}{}{Наклонный участок поверхности.}
{292600}{}{Склон}
{292601}{}{Наклонный участок поверхности.}
{292700}{}{Тотем}
{292701}{}{Шаманский тотем племени.}
{292800}{}{Трибуна}
{292900}{}{Паутина}
{293000}{}{Паутина}
{293100}{}{Паутина}
{293200}{}{Паутина}
{293300}{}{Паутина}
{293400}{}{Паутина}
{293500}{}{Паутина}
{293600}{}{Паутина}
{293700}{}{Паутина}
{293800}{}{Паутина}
{293900}{}{Паутина}
{294000}{}{Паутина}
{294100}{}{Грузовик}
{294101}{}{Из разбитой цистерны на землю попали радиоактивные отходы, сделав это место смертельно опасным.}
{294200}{}{Земля}
{294300}{}{Земля}
{294400}{}{Земля}
{294500}{}{Земля}
{294600}{}{Заборчик}
{294601}{}{Невысокий забор из досок.}
{294700}{}{Заборчик}
{294701}{}{Невысокий забор из досок.}
{294800}{}{Фонарь}
{294801}{}{Желтое стекло создает иллюзию, что фонарь горит.}
{294900}{}{Заборчик}
{294901}{}{Невысокий забор из досок.}
{295000}{}{Заборчик}
{295001}{}{Невысокий забор из досок.}
{295100}{}{Заборчик}
{295101}{}{Невысокий забор из досок.}
{295200}{}{Заборчик}
{295201}{}{Невысокий забор из досок.}
{295300}{}{Пустота}
{295301}{}{Кругом только чернеющая пустота. Она всматривается в Вас.}
{295400}{}{Табличка "Склад"}
{295401}{}{Вы не уверены, но это может означать, что там склад.}
{295500}{}{Больничная афиша.}
{295501}{}{На афише улыбающийся доктор держит окровавленный скальпель.}
{295600}{}{Дерево.}
{295601}{}{Можно его срубить и развести костер. А можно повеситься.}
{295700}{}{Дерево.}
{295701}{}{Это - дерево. Оно наверняка деревянное.}
{295800}{}{Дерево.}
{295801}{}{Вам кажется, что оно выделяется на фоне других. Да, просто кажется.}
{295900}{}{Дерево.}
{295901}{}{Вам хочется обнять его и поплакать.}
{296000}{}{Дерево.}
{296001}{}{От накопленной радиации оно слегка мерцает.}