{100}{}{.223 FMJ}
{101}{}{A case of standard .223 caliber rifle ammunition.}
{200}{}{.223 Custom}
{201}{}{Hand-made .223 caliber rifle bullets.}
{300}{}{.223 AP}
{301}{}{A case of armor-piercing .223 caliber rifle ammunition.}
{400}{}{.308 FMJ}
{401}{}{A case of standard .308 caliber rifle ammunition.}
{500}{}{.308 Custom}
{501}{}{Hand-made .308 caliber rifle bullets.}
{600}{}{.38 ACP}
{601}{}{A case of standard .38 caliber pistol ammunition.}
{700}{}{.38 Custom}
{701}{}{Hand-made .38 caliber pistol bullets.}
{800}{}{.45 ACP}
{801}{}{A case of standard .45 caliber pistol ammunition.}
{900}{}{.45 Custom}
{901}{}{Hand-made .45 caliber pistol bullets.}
{1000}{}{.50 BMG}
{1001}{}{A case of standard .50 caliber heavy machine gun ammunition.}
{1100}{}{12 ga. Buckshot}
{1101}{}{A case of standard 12 gauge shotgun buckshot shells.}
{1200}{}{12 ga. Long}
{1201}{}{A case of extra long 12 gauge shotgun shells.}
{1300}{}{12 ga. Slug}
{1301}{}{A case of standard 12 gauge shotgun slug cartriges.}
{1400}{}{12 ga. Custom}
{1401}{}{Hand-made 12 gauge buckshot shells.}
{1500}{}{25mm HE}
{1501}{}{A standard 25mm high explosive grenade.}
{1600}{}{25mm EMP}
{1601}{}{A special 25mm grenade, designed to destroy electronics and robots.}
{1700}{}{40mm HE}
{1701}{}{A standard 40mm high explosive grenade.}
{1800}{}{40mm WP}
{1801}{}{A white phosphorous 40mm incendiary grenade.}
{1900}{}{9mm JHP}
{1901}{}{A case of standard military 9mm pistol ammunition.}
{2000}{}{9mm Custom}
{2001}{}{Hand-made 9mm pistol bullets.}
{2100}{}{9mm HPS}
{2101}{}{A case of special anti-personel 9mm pistol ammunition.}
{2200}{}{9mm AP}
{2201}{}{A case of armor-piercing 9mm pistol ammuniton.}
{2300}{}{Large Battery}
{2301}{}{A large, self-contained energy cell.}
{2400}{}{Rubber Bullet}
{2401}{}{While not the most dangerous type of ammunition, rubber bullets can knock an opponent out for a while.}
{2500}{}{Poisoned Dart}
{2501}{}{Although made of junk, the darts are perfectly balanced. Inside each is a cavity containing poison. Too bad they're single use only.}
{2600}{}{12mm Nitro}
{2601}{}{A case of special 12mm incendiary ammunition for the unique Hotter shotgun.}
{2700}{}{Magnum Bullets}
{2701}{}{Very powerful magnum revolver cartriges.}
{2800}{}{Small Battery}
{2801}{}{A small, self-contained energy cell.}
{2900}{}{Napalm}
{2901}{}{A canister of a viscous incendiary substance based on gasoline.}
{3000}{}{EMP Rocket}
{3001}{}{A special rocket shell, designed to destroy electronics and robots.}
{3100}{}{HE Rocket}
{3101}{}{A standard rocket with a high explosive warhead.}
{3200}{}{AP Rocket}
{3201}{}{A special rocket shell, designed to pierce armor plating.}
{3300}{}{BB Pellets}
{3301}{}{A case of small metal ball bearings, used by pneumatic pistols and rifles.}
{3400}{}{Shotgun Fist}
{3401}{}{Whoa, someone mounted a shotgun in these knuckles. Be careful, the blood of your victims can jam the mechanism. Min ST: 5}
{3500}{}{Aluminium Knuckles}
{3501}{}{Small, light, featureless, but this brass knuckles will help you not to hurt your knuckles on someone's jaw. Min ST: 2}
{3600}{}{Brass Knuckles}
{3601}{}{That's more like it! With this brass knuckles, you can break someone's skull or kneecaps. Min ST: 4}
{3700}{}{Spiked Knuckles}
{3701}{}{The most dangerous of brass knuckles: rips the skin, breaks bones and lifts the mood of its owner! Min ST: 4}
{3800}{}{Lead Gloves}
{3801}{}{Very useful, breaks bones like it's nothing. Min ST: 5}
{3900}{}{Corkscrew}
{3901}{}{A rather dangerous and inconspicuous weapon. Aim for their eyes! Min ST: 3}
{4000}{}{Buzz Blade}
{4001}{}{A chainsaw with a handle. Chopping meat, cutting sinew, crushing bone was never easier! It's so light and comfortable that you can forget about it when you decide to scratch yourself. Min. sl: 6}
{4100}{}{Batteries}
{4101}{}{The only widely accepted means of tender in the Wastes.}
{4200}{}{Mine}
{4201}{}{A typical american made anti-personal mine with a chemical activation trigger.}
{4300}{}{C4 Explosives}
{4301}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive.}
{4400}{}{Armed C4 Explosives}
{4401}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. It's armed!}
{4500}{}{C4 Detonator}
{4501}{}{A radio-controlled detonator for C4 explosives.}
{4600}{}{C4 Deactivator}
{4601}{}{A device for canceling the activation of C4 explosives.}
{4700}{}{First Aid Kit}
{4701}{}{A small kit containing basic medical equipment. Bandages, wraps, antiseptic spray, and more.}
{4800}{}{Electric Trap}
{4801}{}{A trap that employs an electric charge when triggered.}
{4900}{}{Explosive Trap}
{4901}{}{A trap that detonates then the tripwire is triggered.}
{5000}{}{ Don't use this!}
{5001}{}{}
{5100}{}{Dynamite}
{5101}{}{A stick of good old dynamite.}
{5200}{}{Geiger Counter}
{5201}{}{A vital tool in the wasteland. It determines the exposure of gamma and beta radiation.}
{5300}{}{Watch}
{5301}{}{A "Single-Tronic" wristwatch, with a quartz mechanism and shockproof case.}
{5400}{}{Stealth Boy}
{5401}{}{A device that uses an electromagnetic field to create an invisibility effect around the user.}
{5500}{}{Lockpicks}
{5501}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks.}
{5600}{}{Expanded Lockpick Set}
{5601}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks. This set also includes some special tools for more difficult mechanical locking mechanisms.}
{5700}{}{Electronic Lockpick}
{5701}{}{An universal tools for defeating electronic locks and security devices.}
{5800}{}{Electronic Lockpick MKII}
{5801}{}{A more advanced version of electronic lockpick. For defeating electronic locks and security devices. This Mark II version includes updated software and interface tools.}
{5900}{}{Motion Sensor}
{5901}{}{A motion sensor detects even the slightest movements over a long distance, using a tuned radar device.}
{6000}{}{Chainsaw Sword}
{6001}{}{Cuts people better than wood, way better! Purge the Heretic! Kill the Xeno! Min ST: 6}
{6100}{}{Laser Saw}
{6101}{}{This tool can cut almost anything. Take extreme care when using it. Min ST: 4}
{6200}{}{Combat Throwing Knife}
{6201}{}{A very sharp and balanced knife that is excellent for throwing. You heard that squads of Navy SEALS used them for silent takedowns. Min ST: 4}
{6300}{}{Throwing Knife}
{6301}{}{A Hand-made sharpened and balanced throwing knife. Not quite as aerodynamic as factory made though. Min ST: 3}
{6400}{}{Combat Knife}
{6401}{}{A heavy knife with a wide blade to allow for much bloodloss. In the right hands this piece of cold steel can a lot of people! Min ST: 4}
{6500}{}{Cutting Knife}
{6501}{}{If you can't decide if you want to cut up bread, sausages or an annoying neighbor. Min ST: 3}
{6600}{}{Cleaver}
{6601}{}{A butcher's knife that cuts through bones in a single swing of the hand. Min ST: 5}
{6700}{}{Scalpel}
{6701}{}{A surgical scalpel, very sharp and simple to use. Be careful with it! Min ST: 2}
{6800}{}{Serrated Cleaver}
{6801}{}{The tool of maniacs! A powerful edged weapon with a serrated blade will cut down any enemy. Min ST: 4}
{6900}{}{Lightning Spear}
{6901}{}{A heavy metal spear with a power source connected to it. Hits the enemy not only with its pointed tip, but also with a hefty electric shock. Min ST: 5}
{7000}{}{Wooden Spear}
{7001}{}{A sharp wooden spear made using Stone Age technology. Min ST: 4}
{7100}{}{Iron Spear}
{7101}{}{A metal rod with a sharp, pointed head. Min ST: 5}
{7200}{}{Placeholder Spear}
{7201}{}{}
{7300}{}{Science Book}
{7301}{}{Study science, at this time any information is worth its weight in gold.}
{7400}{}{Pistol Parts}
{7401}{}{You can assemble a pistol from this, if you have the skills and a special repair kit.}
{7500}{}{Revolver Parts}
{7501}{}{You can assemble a revolver from this, if you have the skills and a special repair kit.}
{7600}{}{Engineering Book}
{7601}{}{A manual for repairing broken equipment, machines and electronics.}
{7700}{}{Rifle Parts}
{7701}{}{You can assemble a rifle from this, if you have the skills and a special repair kit.}
{7800}{}{Shotgun Parts}
{7801}{}{You can assemble a shotgun from this, if you have the skills and a special repair kit.}
{7900}{}{Torch}
{7901}{}{An old flashlight.}
{8000}{}{Medical Book}
{8001}{}{A medical reference book with an index, a convenient guide for quickly mastering the most necessary things.}
{8100}{}{Automatic Parts}
{8101}{}{You can assemble an automatic weapon from this, if you have the skills and a special repair kit.}
{8200}{}{Universal Screwdriver}
{8201}{}{A screwdriver with multiple attachments, suitable for many operations.}
{8300}{}{Tool Kit}
{8301}{}{A universal repair set, containing various useful tools, including pliers.}
{8400}{}{Pistol Repair Kit}
{8401}{}{A kit for the maintenance and assembly of pistols.}
{8500}{}{Explosives}
{8501}{}{A bundle of good old trinitrotoluene.}
{8600}{}{Scout Handbook}
{8601}{}{A book on the methods and ideals of Scouting. Very practical information regarding outdoor life.}
{8700}{}{Zeus Hammer}
{8701}{}{A huge metal hammer powered by batteries. See how merrily the crushed skull of the enemy twitches under the influence of an electric charge! Min ST: 7}
{8800}{}{Sledgehammer}
{8801}{}{This hammer can crush granite and skulls! More often it is skulls. Min ST: 7}
{8900}{}{Battlehammer}
{8901}{}{A very large hammer with a big handle. Very popular with the muscular crowd. Min ST: 7}
{9000}{}{Placeholder Hammer}
{9001}{}{}
{9100}{}{Doctor's Bag}
{9101}{}{A roomy bag that contains instruments and chems used by doctors in the application of their trade.}
{9200}{}{Light Support Weapon}
{9201}{}{A military support machine gun that was in service with the heavy infantry of the US Armed Forces from 1978 to 1989. Min ST: 7}
{9300}{}{Barrack Machinegun}
{9301}{}{An experimental super-heavy machine gun, developed by the company "Britanic Engineering" for the Advanced Research Projects Agency "Defender" project. The recoil has incredible power and can easily tear out an untrained arm! Min ST: 10}
{9400}{}{Turret Machinegun}
{9401}{}{How did you manage to wrest the machine gun from the chassis of the turret? Min ST: 9}
{9500}{}{LVS Machinegun}
{9501}{}{A heavy machine gun, developed by "Civil Defense" for the US Army for paramilitary police units. Mounted on lightly armored vehicles, it prooved itself excellent against protesters! Min ST: 8}
{9600}{}{SLR-3 Laser Rifle}
{9601}{}{A modification of the "Grand Shvain Laser Rifle" developed by Sebastian Shvain in 2198. Awkward and heavy, but damn it's a laser! Min ST: 7}
{9700}{}{SLR-4 Laser Rifle}
{9701}{}{This model replaced the "SLR-3" rifle in 2202. Differences from its predecessor are a slightly higher weight, but a greater firing range and laser pulse stability. Min ST: 8}
{9800}{}{Plasma Rifle}
{9801}{}{This unique weapon fires super-heated plasma that cuts metal like a hot knife through butter. Just don't forget to feed it with a lot of energy cells. Without your participation this beast of massive destruction would never have seen the light of day! Min ST: 9}
{9900}{}{FT2A Flamethrower}
{9901}{}{A military flamethrower that spits searing flames of napalm. Burn, baby burn! Min ST: 8}
{10000}{}{Hellbringer}
{10001}{}{The poetic name of this incendiary monster speaks for itself. With this gun, the smell of burnt meat will stick firmly in your nostrils! Min ST: 9}
{10100}{}{Festering Flamer}
{10101}{}{A Hand-made and rather playful representative of the realm of flamethrowers. Just be careful, because this baby is very unstable due to the increased supply of hot mixture into the nozzle! Min ST: 9}
{10200}{}{Gunpoint Magazine}
{10201}{}{A gun magazine devoted to the practical use of firearms, and the occasional biased review.}
{10300}{}{Taser}
{10301}{}{A fairly strong electric shock will sober up any bully who attacks you! Min ST: 5}
{10400}{}{Crowbar}
{10401}{}{Rips out nails, opens doors, knocks out teeth. The range of applications of this piece of iron is limitless! Min ST: 5}
{10500}{}{Placeholder Club}
{10501}{}{}
{10600}{}{Pipe Wrench}
{10601}{}{Old, rusty, but heavy and with a comfortable handle! Min ST: 6}
{10700}{}{Ratcatcher}
{10701}{}{Homemade weapon for clobbering small creatures. Although, it is also suitable for large ones. Min ST: 6}
{10800}{}{Hammer}
{10801}{}{A blunt instrument for work and self-defense. Min ST: 5}
{10900}{}{Nail Board}
{10901}{}{What people will come up with against other people. Min ST: 5}
{11000}{}{Bludgeon}
{11001}{}{In fact it's just an old stick, but it fits easily and comfortably in your hand. Min ST: 4}
{11100}{}{Pipe}
{11101}{}{Just a piece of rusty pipe. When you hit someone on the head, there is a cheerful ringing sound. Min ST: 6}
{11200}{}{Police Baton}
{11201}{}{An old police tool for dealing with the unruly. The Baton causes a lot of pain, but it leaves almost no traces on the body! Min ST: 5}
{11300}{}{Leather Jacket}
{11301}{}{A leather jacket, thick and heavy. Although it will hardly protect you from a bullet.}
{11400}{}{Aviator Jacket}
{11401}{}{A fashionable jacket made of very thick and high-quality leather. It will reliably protect you not only from wind and cold, but also from a knife strike!}
{11500}{}{Baseball Protector}
{11501}{}{Once sports equipment, now very good combat protection.}
{11600}{}{Super Protector}
{11601}{}{Baseball sports equipment serves as a decent protection against blows and hits from small-caliber weapons.}
{11700}{}{Hockey Protector}
{11701}{}{Durable and comfortable hockey protection, will protect you from many blows.}
{11800}{}{Rusty Cuirass}
{11801}{}{Looks like a rusty mess of scrap metal, but it still gives you good protection from bullets.}
{11900}{}{Metal Armor}
{11901}{}{Strong and heavy armor made of sheet metal. Constricts movement somewhat but offers great protection.}
{12000}{}{Military Armor}
{12001}{}{The most common armor used by army infantry in the war. Still reliable.}
{12100}{}{Combat Armor}
{12101}{}{Infantry combat armor, leather, Kevlar, metal layers. Perfectly shields against many types of projectiles.}
{12200}{}{Scout Armor}
{12201}{}{Lightweight version of combat armor, upgraded for long-term reconnaissance operations in the deep behind enemy lines. It is light, comfortable, functional, and also gives the wearer a trim and sporty look!}
{12300}{}{Fake Military Armor}
{12301}{}{While this armor looks like the classic military armor of the Olympus Scouts, it's only a fake. Oh, and don't expect any good protection while wearing it!}
{12400}{}{Enviromental Armor}
{12401}{}{The suit is designed specifically for use in extreme hostile environments, and as such most resistant to radioactive and gas contaminations. The best radiation protection in the entire Wastes!}
{12500}{}{Battle Armor}
{12501}{}{The armor offers nearly total protection, and is specially made for infantry assault groups. It increases mobility and maneuverability by reducing the thickness of the armor and using composite materials.}
{12600}{}{Battle Armor MKII}
{12601}{}{An even improved version of the standard battle armor, even stronger, even more impressive! And you will surely appreciate the comfort of the new leather inserts between the hip plates!}
{12700}{}{AS-2000}
{12701}{}{A mechanized exo-suit, driven by a nuclear battery, with hydraulic and servo motors. This model saves poorly against radiation, but the thick layer of armor is an excellent protection against firearms and energy weapons!}
{12800}{}{AS-2000 MKII}
{12801}{}{The AS-2000 has been replaced by a modern upgraded and modified MKII, that features an added programmable stabilization system and an inverse kinematics system.}
{12900}{}{MCA Defender}
{12901}{}{This is a legendary mechanized combat armor system, powered by diesel-nuclear propulsion. Only the elite defenders of Olympus, the Protectors, are worthy to wear such a suit!}
{13000}{}{Slugger}
{13001}{}{An award-winning German-made pistol, characterized by it's high accuracy, stopping power, reliability and an elegant intrinsic handle design. Min ST: 4}
{13100}{}{Detective Revolver}
{13101}{}{A short-barreled revolver Model ST-115, nicknamed "Detective" as it was a mandatory possession of any private investigator until 1988. It is said to fail at critical moments, but has also saved many! Min ST: 4}
{13200}{}{.45 Revolver}
{13201}{}{A basic average revolver, named after the fact that the mechanism feeding the loaded cartridges is revolving like rotating drum. Min ST: 5}
{13300}{}{Magnum Revolver}
{13301}{}{Being that this is the most powerful handgun in the world, and would blow your head clean off, you've got to ask yourself one question: "Do I feel lucky?" Well, do ya, punk? Min ST: 5}
{13400}{}{Flare Gun}
{13401}{}{A signal pistol, which uses flares as a cartridge. It can easily burn through leather armor. Min ST: 5}
{13500}{}{Thunderer}
{13501}{}{This weapon is made on the basis of an single-fire under-barrel 40mm grenade launcher. It will bring quite a few merry moments to its owner. Min ST: 6}
{13600}{}{9mm Glocker}
{13601}{}{The 9mm Glocker pistol, manufactured by D&R, is a classic representative of the German military industry, very accurate and reliable. Min ST: 4}
{13700}{}{9mm Glocker Auto}
{13701}{}{An improved model of the Glocker Pistol family, that can fire bursts for even more fun with 9mm. Min ST: 5}
{13800}{}{9mm Pistol}
{13801}{}{A basic average pistol in 9mm, nothing special about it. Min ST: 4}
{13900}{}{9mm Revolver}
{13901}{}{A very basic and Hand-made 9mm revolver, not very reliable. Min ST: 2}
{14000}{}{Stun Pistol}
{14001}{}{A non-lethal pistol for self-defense. Quite a weak weapon, but it could save your life. Min ST: 3}
{14100}{}{Sting}
{14101}{}{A pneumatic launching device for hurling poisonous darts at your adversaries. Min ST: 3}
{14200}{}{Python Revolver}
{14201}{}{This one blows heads clean off! One of the most popular revolvers, made famous in the cinema's of the 70's, starring many detective noir movies. Min ST: 6}
{14300}{}{.223 Pistol (Scoped)}
{14301}{}{A special custom-made pistol in .223 with an attached scope, which allows to pick off your enemies at a distance with ease. Min ST: 4}
{14400}{}{Jackal's Revolver}
{14401}{}{The signature revolver of the Jackal. A nice gun to pop the heads of your enemies like melons. Min ST: 6}
{14500}{}{SL-10 Laser Pistol}
{14501}{}{Compact and advanced version of the SL-9 laser pistol. Light, fast and deadly! Powered by small batteries. Min ST: 5}
{14600}{}{Pneumatic Pistol}
{14601}{}{A pistol that shoots small BB Pellets with the help of compressed air. Only really suitable for shooting rodents. Min ST: 2}
{14700}{}{Red Robin Pistol}
{14701}{}{A pneumatic pistol, model "Red Robin". While it is the most powerful model of airguns, that doesn't count for much. Min ST: 3}
{14800}{}{Laser Cutter}
{14801}{}{An "Isaac Industries" laser cutting tool. Designed for cutting through unyielding rocks or soft organic tissue. Min ST: 5}
{14900}{}{Gun Placeholder}
{14901}{}{}
{15000}{}{Dread SMG}
{15001}{}{A "Dread" submachine gun that was in service with the National Guard until 2002. The main value is in simplicity and reliability, as well as decent firepower. Min ST: 4}
{15100}{}{Ghetto SMG}
{15101}{}{In the personal mob of any mafia boss is at least one man with this gun. An inspiring look is half the power of this weapon, as soon as the enemy sees this piece, he immediately loses all desire to behave inappropriately. Min ST: 5}
{15200}{}{Cricket SMG}
{15201}{}{A british submachine gun that was in service with the MI-6 operational special forces. Min ST: 4}
{15300}{}{Vendetta SMG}
{15301}{}{A favorite submaschine gun of mafiosi and bandits. Light, small and lethal, what else does one want? Min ST: 5}
{15400}{}{FSP-10 SMG}
{15401}{}{An elite prototype of an assault submachine gun for the marines. A light, reliable and water-resistant deliverer of pain and suffering for all the enemies of America! Min ST: 6}
{15500}{}{Dread SMG (Scoped)}
{15501}{}{A modified "Dread" submachine gun with an optical sight, to even better keep your enemies at bay. Min ST: 4}
{15600}{}{Dread SMG (Exp. Mag.))}
{15601}{}{A modified "Dread" SMG with an added magazine for even more bursting fun. Min ST: 5}
{15700}{}{SL-9 Laser Pistol}
{15701}{}{One of the first successful models of Shvain's laser pistols. Though a bit heavy it's not just a laser pointer but quite deadly! Min ST: 5}
{15800}{}{Plasma Pistol}
{15801}{}{A strong electromagnet disperses super-heated globs of plasma at a high rate of fire. It burns easily through metal, wood, stone and of course also living tissue. Min ST: 5}
{15900}{}{9mm Submachine gun}
{15901}{}{A basic average SMG in 9mm, nothing special about it. Min ST: 6}
{16000}{}{N17A1 Assault Rifle}
{16001}{}{An automatic rifle from the 90s of the twentieth century, a reliable rifle, valuable in combat, easy to handle and not quirky to maintain. Min ST: 6}
{16100}{}{N17A1 Assault Rifle (Scoped)}
{16101}{}{A standard N17A1 with a scope attached for even more long range precission. Min ST: 6}
{16200}{}{Barrage Machinegun}
{16201}{}{A quite unique .223 modification of an old legendary Tommygun. It is rumored to have been in use by the mafia bosses of the east coast.  Min ST: 7}
{16300}{}{Civilian Carbine}
{16301}{}{A very old model of carbine, used in the pre-war period by hunters. Min ST: 5}
{16400}{}{KLH74 Assault Rifle}
{16401}{}{A legendary rifle trophy from the old wars, manufactured in the United Russian Empire. Min ST: 6}
{16500}{}{Assault Rifle}
{16501}{}{A basic average assault rifle, nothing special about it. Min ST: 6}
{16600}{}{Hunting Rifle}
{16601}{}{A hunting rifle for large animals, or bigger two legged game. Min ST: 5}
{16700}{}{Hunting Rifle (Scoped)}
{16701}{}{A hunting rifle with an attached scope that makes it easier to hunt from a distance, no matter what kind of game you're aiming for. Min ST: 5}
{16800}{}{Personal Assault Rifle}
{16801}{}{A personalized assault rifle. Min ST: 8}
{16900}{}{Bulldog Assault Rifle}
{16901}{}{A modern and decent assault rifle, named after the fact that it tears through enemies like a rabid dog through freshly killed prey. Min ST: 7}
{17000}{}{Sniper Rifle}
{17001}{}{A nice balanced rifle with an optical sight, good range and perfect accuracy. What more does a sniper need? Min ST: 6}
{17100}{}{R-6 Assault Rifle}
{17101}{}{An excellent assault rifle that was in use by the pre-war special forces. Very reliable and precise. Min ST: 7}
{17200}{}{Varmint Rifle}
{17201}{}{Despite the name and size of this rifle, this little baby can cause quite a few problems for your opponents. Min ST: 4}
{17300}{}{Lilith Rifle}
{17301}{}{A very deadly sniper rifle that many elite sniper used. Has a very long range and stopping power. Min ST: 9}
{17400}{}{Phobos Shotgun}
{17401}{}{The automatic propellant gas rapid reloading system makes this shotgun a most dreadful experience for your enemies. Min ST: 7}
{17500}{}{Double-barreled Shotgun}
{17501}{}{A double-barreled hunting shotgun, ideal for unarmored targets. Min ST: 5}
{17600}{}{Remington Shotgun}
{17601}{}{A pump-action shotgun that was widely in use as a police weapon. It's in good condition. Min ST: 5}
{17700}{}{Pump-Action Shotgun}
{17701}{}{A small and comfortable civilian pump-action shotgun. Min ST: 4}
{17800}{}{Sawn-off Shotgun}
{17801}{}{A sawn-off shotgun is the most common weapon among small-time bandits, robbers and other crooks. Min ST: 4}
{17900}{}{12 ga. Shotgun}
{17901}{}{A very basic civilian pump-action shotgun that was widely in use. Min ST: 5}
{18000}{}{Wilderer Shotgun}
{18001}{}{A big nasty revolving long range shotgun for hunting large game. Min ST: 6}
{18100}{}{Hardener Shotgun}
{18101}{}{This is more like a shotgun cannon than a normal revolving shotgun. It is definately one of the most powerful and with a very long range to boot. The downside is it needs special 12 gauge Long cartriges. Min ST: 9}
{18200}{}{EMP Launcher}
{18201}{}{A grenade launcher for special 40mm EMP grenades, designed against robots and electronics. Min ST: 8}
{18300}{}{40mm Launcher}
{18301}{}{A grenade launcher for high explosive 40mm grenades against fortified targets. Min ST: 6}
{18400}{}{Strike Launcher}
{18401}{}{Grenades shot by this grenade launcher will supress your enemies and penetrate their armor. Min ST: 7}
{18500}{}{Hotter Shotgun}
{18501}{}{This revolving shotgun fires special 12 gauge incendiary shells in the face of your enemies. Oh, and it has a burst mode too! Min ST: 5}
{18600}{}{Pneumatic Rifle}
{18601}{}{A rifle that shoots small BB Pellets with the help of compressed air. Has more power than the pistol versions. Min ST: 3}
{18700}{}{Raven Rifle}
{18701}{}{A descent rifle that shoots small BB Pellets. Even a wild coyote would not like to get hit by a bullet from this one. Min ST: 3}
{18800}{}{Repaired Rifle}
{18801}{}{A repaired and worn rifle, but still deadly. Min ST: 5}
{18900}{}{Placeholder Rifle}
{18901}{}{}
{19000}{}{Hurricane Minigun}
{19001}{}{The portable six-barreled NCASTR minigun "Hurricane" is *the* weapon for suppress your opponents. A 75,000 rounds per minute .223 rain of lead makes it not likely to leave anything standing alive. Min ST: 8}
{19100}{}{Heavy Rain Minigun}
{19101}{}{Like it's predecessor, the "Heavy Rain" minigun tears through enemies like wet paper. It even powerful enough to destroy barricades and armored vehicles. Min ST: 9}
{19200}{}{Turret Minigun}
{19201}{}{This gun made by NCASTR for automated defense turrets, makes it very hard for anyone to sneak by with it's nearly limitless 90,000 rounds per minute hail of bullets. Min ST: 10}
{19300}{}{HMG-1A4 Flamelance}
{19301}{}{A rapid-fire flamethrower that shoots small balls of red-hot burning liquid out of six muzzles at a speed of 50,000 rounds per minute. Technically it's more a plasma minigun, but nobody seems to care when they, and everything around them, melt away at a searing 3000 degrees Celsius. Min ST: 8}
{19400}{}{Placeholder Minigun}
{19401}{}{}
{19500}{}{EMP Rocket Launcher}
{19501}{}{A rocket launcher for special EMP rockets, designed against robots and electronics. Min ST: 7}
{19600}{}{Crusader Rocket Launcher}
{19601}{}{The NCASTR "Crusader" missile launcher fires surface-to-surface rockets, sufficient power and accuracy ensures a high level of target destruction. Min ST: 8}
{19700}{}{Hand-made Rocket Launcher}
{19701}{}{A short range single shot rocket launcher, basically just a pipe with a trigger mechanism. Be very careful fireing that thing! Min ST: 7}
{19800}{}{Placeholder Rokcet Launcher}
{19801}{}{Min ST: 7}
{19900}{}{SnR Rocket Launcher}
{19901}{}{A single use rocket launcher type "Shoot'n'Run" that is impossible to reload, jsut throw it away after uese. Min ST: 6}
{20000}{}{Weapon 1}
{20001}{}{}
{20100}{}{Weapon 2}
{20101}{}{}
{20200}{}{Weapon 3}
{20201}{}{}
{20300}{}{Weapon 4}
{20301}{}{}
{20400}{}{Weapon 5}
{20401}{}{}
{20500}{}{Torch (lit)}
{20501}{}{An old flashlight. It's lit}
{20600}{}{Dynamite (lit)}
{20601}{}{A stick of good old dynamite with a lit fuse.}
{20700}{}{Geiger Counter (active)}
{20701}{}{A vital tool in the wasteland. It determines the exposure of gamma and beta radiation. It's activated.}
{20800}{}{Motion Sensor}
{20801}{}{A motion sensor detects even the slightest movements over a long distance, using a tuned radar device. It's activated}
{20900}{}{Armed Explosives}
{20901}{}{A bundle of good old trinitrotoluene with a lit fuse.}
{21000}{}{Stealth Boy}
{21001}{}{A device that uses an electromagnetic field to create an invisibility effect around the user. It's activated.}
{21100}{}{EMP Grenade}
{21101}{}{This type of grenade is designed specifically for the destruction of electronics. Min ST: 5}
{21200}{}{WP Grenade}
{21201}{}{If you need to start a fire, then this grenade is just perfect. Min ST: 4}
{21300}{}{Rock}
{21301}{}{It's a rock. The Granite-Inc. model is an upgraded version. Min ST: 4}
{21400}{}{Molotov Cocktail}
{21401}{}{A home-made flammable grenade. Min ST: 5}
{21500}{}{HE Grenade}
{21501}{}{An ordinary high-explosive grenade. Min ST: 6}
{21600}{}{Fist of God}
{21601}{}{One of the strongest grenades, a secret military design. Min ST: 7}
{21700}{}{Sawblade}
{21701}{}{Sharp teeth can easily cut through unprotected flesh, and it flies perfectly! Min ST: 6}
{21800}{}{Billiard Ball}
{21801}{}{Old, cracked, but weighty and with good flight characteristics. The ball may not kill anyone, but it will lead to some heavy bruises for sure! Min ST: 2}
{21900}{}{Hand-made Grenade}
{21901}{}{A homemade grenade, dangerous for both, the enemy and the thrower. Min ST: 5}
{22000}{}{Bandages}
{22001}{}{Inefficient, yet cheap and affordable. Bandages will not reconstitute your severed arm, but they will help you heal a cut.}
{22100}{}{Painkiller}
{22101}{}{A couple of pills will reduce the pain, and will heal up light wounds!}
{22200}{}{Heal-Up}
{22201}{}{Developed on the basis of an army painkiller, this injection is designed for household use. Not really cheap, but pretty essential in the wastes.}
{22300}{}{Surge}
{22301}{}{A powerful army painkiller that heals even very deep wounds. It also increases strength and resistance to damage. Very essential in battle!}
{22400}{}{Antidote}
{22401}{}{If you are poisoned take a couple of pills and you will not face death from bloody diarrhea!}
{22500}{}{Rot Gut}
{22501}{}{The smell from the bottle of hootch knocks you off your feet, but this folk remedy let's you sweat out poisons pretty good!}
{22600}{}{Rad-Out}
{22601}{}{An injection that expels radioactive patricles from your bloodstream. Unpleasant, but useful!}
{22700}{}{Wild Potion}
{22701}{}{Scorpion tails, rat nails, mole rat scales. The thought of all the things mixed in theremakes you queasy, but this potion removes radiation better than factory drugs!}
{22800}{}{Iodide}
{22801}{}{If you are going to toy around the core of a nuclear reactor this miracle pill will help you not to burn out from your insides. Take before exposure!}
{22900}{}{Resistanol}
{22901}{}{A military miracle remedy that covers the skin with hard scales, even a knife will not harm you! May cause itching and cancer.}
{23000}{}{Combatid}
{23001}{}{If you want to rush though combat and cause mayhem and destruction stock up on Combatid. Not only does it heal your wounds, but also increases your resistances to damage. Possibly highly addictive with dangerous side effects.}
{23100}{}{Brainiac}
{23101}{}{No scientist can do without this nose spray! The composition of the drug gets directly into the brain, fully revealing its dormant potential!}
{23200}{}{Strongman}
{23201}{}{Hasn't nature awarded you with muscles of steel? Never mind, Stronghold is always there to help you. Just rub the ointment into your muscles and start clobbering!}
{23300}{}{Drop}
{23301}{}{Break off the nozzle of the ampoule and pour it into your mouth and in a second you will feel like a God!}
{23400}{}{Whiskey}
{23401}{}{Good old whiskey, with a nice bouquet and taste.}
{23500}{}{Cognac}
{23501}{}{A smooth and noble drink. If you smell if it, you certainly will be respected among your peers.}
{23600}{}{Booze}
{23601}{}{You aren't sure if this strong home-brewed hootch is meant to be used as drink, or as a desinfectant.}
{23700}{}{Spot-Up}
{23701}{}{"What's up? Spot-Up!" There are legends about this soda, including some quite scary ones, but after one sip you will forget all your fears and doubts!}
{23800}{}{Apple}
{23801}{}{An old dry apple. Looks like it has some mold on its side.}
{23900}{}{Pear}
{23901}{}{A surprisingly delicious piece of dried pear.}
{24000}{}{Shotgun Repair Kit}
{24001}{}{A kit of spare parts for the maintenance and assembly of shotguns.}
{24100}{}{Rifle Repair Kit}
{24101}{}{A kit of spare parts for the maintenance and assembly of rifles and submachine guns.}
{24200}{}{Shovel}
{24201}{}{This item is equally convenient for both digging something up and burying someone down.}
{24300}{}{Rope}
{24301}{}{A coil of good, strong rope. Decide for yourself how to use it.}
{24400}{}{Screwdriver}
{24401}{}{A typical screwdriver. Useful tool both in repairing and in self-defense.}
{24500}{}{Silk Gloves}
{24501}{}{If you want to rob someone this item of clothing will be very useful.}
{24600}{}{Energy Drink}
{24601}{}{Relieves fatigue, removes drowsiness, helps to concentrate and gives cheerfulness!}
{24700}{}{Rad-O-meter}
{24701}{}{An indispensable assistant in the fight against radiation. If there is a nuclear war, take the Rad-O-meter with you!}
{24800}{}{Instrument}
{24801}{}{}
{24900}{}{Instrument}
{24901}{}{}
{25000}{}{Rusty Locker}
{25001}{}{Do not judge the locker by its appearance but the content in it.}
{25100}{}{Rusty Locker}
{25101}{}{It is slightly askew, but it is unlikely that this affected its contents.}
{25200}{}{Rusty Lokcer}
{25201}{}{Even lying on the ground, this locker didn't stop being a locker.}
{25300}{}{Shelves}
{25301}{}{Old and dusty shelves with plenty of junk on them.}
{25400}{}{Stuff}
{25401}{}{There might be something usefull in such a large pile of stuff.}
{25500}{}{Boxes}
{25501}{}{Small boxes with unknown contents.}
{25600}{}{Tub}
{25601}{}{An old roomy bowl.}
{25700}{}{Stuff}
{25701}{}{The abundance of things in that pile does not guarantee the presence of something valuable in it, but it makes you curious.}
{25800}{}{Stuff}
{25801}{}{A pile of some stuff and boxes.}
{25900}{}{Machine}
{25901}{}{A small machine for working with different materials.}
{26000}{}{Stuff}
{26001}{}{Usually people store their stuff something like it.}
{26100}{}{Stuff}
{26101}{}{Usually people store their stuff something like it.}
{26200}{}{Stuff}
{26201}{}{Usually valuables don't pile up like this, but who knows - people are strange.}
{26300}{}{Stuff}
{26301}{}{There is always some ambiguity in closed boxes.}
{26400}{}{Stuff}
{26401}{}{Rummaging through a large pile of things is time-consuming. Sometimes it's worth it, sometimes not.}
{26500}{}{Stuff}
{26501}{}{The abundance of things in that pile does not guarantee the presence of something valuable in it, but it makes you curious.}
{26600}{}{Box}
{26601}{}{Usually people keep their stuff in something like it.}
{26700}{}{Footlocker}
{26701}{}{A great place for storing items.}
{26800}{}{Table}
{26801}{}{The station administrator's desk.}
{26900}{}{Shelves}
{26901}{}{There's a lot of junk on these shelves.}
{27000}{}{Stuff}
{27001}{}{Cartons, boxes, crates - all these are simply made for storing things.}
{27100}{}{Firehose Box}
{27101}{}{You have always liked to set things on fire rather than putting it out.}
{27200}{}{Vending Machine}
{27201}{}{Be careful with them, it seems this containers are very deranged.}
{27300}{}{Hood}
{27301}{}{A hood of a car with obvious traces of corrosion.}
{27400}{}{Trunk}
{27401}{}{The trunk of an old car.}
{27500}{}{Car Door}
{27501}{}{A badly battered car door.}
{27600}{}{Car Door}
{27601}{}{A badly battered car door.}
{27700}{}{Trunk}
{27701}{}{The trunk of an old car.}
{27800}{}{Crate}
{27801}{}{Someone left a crate in the car.}
{27900}{}{Wall Safe}
{27901}{}{It looks shabby. You wonder if time has affected its reliability.}
{28000}{}{Wall Stash}
{28001}{}{Perhaps there was someone's stash in this hole.}
{28100}{}{Old Boxes}
{28101}{}{Crumpled and dirty boxes.}
{28200}{}{Dresser}
{28201}{}{An old chest of drawers made of cracked but still strong wood.}
{28300}{}{Shelves}
{28301}{}{The wooden shelves look empty, but maybe you are lucky?}
{28400}{}{Dresser}
{28401}{}{A broken wooden commode.}
{28500}{}{Shelves}
{28501}{}{Old broken wooden shelves, they seem to have served their time.}
{28600}{}{Shelves}
{28601}{}{Wooden shelves, designed to put things on them.}
{28700}{}{Shelves}
{28701}{}{The wooden shelves look empty, but maybe you are lucky?}
{28800}{}{Shelves}
{28801}{}{Old broken wooden shelves, they seem to have served their time.}
{28900}{}{Firehose Box}
{28901}{}{You have always liked to set things on fire rather than putting it out.}
{29000}{}{*Dad's Wrench*}
{29001}{}{A small adjustable pipe wrench in perfect condition.}
{29100}{}{Corn}
{29101}{}{A mouth watering ear of corn.}
{29200}{}{Water Container}
{29201}{}{The water smells strongly of rotten meat.}
{29300}{}{*Bracket*}
{29301}{}{One of the parts for the pump valve filter.}
{29400}{}{*Filter*}
{29401}{}{One of the parts for the pump valve filter.}
{29500}{}{*Valve*}
{29501}{}{One of the parts for the pump valve filter.}
{29600}{}{Pump Valve Filter}
{29601}{}{Missing spare part for the broken water treatment unit.}
{29700}{}{Nuclear Moonshine}
{29701}{}{A bottle of an extremely strong liquor. It glows in the dark!}
{29800}{}{*Douglas's Badge*}
{29801}{}{The shiny badge of Sheriff Douglas.}
{29900}{}{*Encyclopedia*}
{29901}{}{A scientific reference guide containing useful information from various fields of life.}
{30000}{}{*Prototype Plasma Rifle*}
{30001}{}{A prototype plasma rifle, a weapon from the latest generation. Possibly the only surviving copy.}
{30100}{}{*Ultra Repair Kit*}
{30101}{}{A serious repair kit. In it you find probably almost everything you need for every repair.}
{30200}{}{*Rapture*}
{30201}{}{One does of the drug Rapture, don't misuse it.}
{30300}{}{*Elevator Card 2B*}
{30301}{}{Elevator access card 2B.}
{30400}{}{*Voice Modulator*}
{30401}{}{A device for generating sound waves in the form of specified phrases that mimic a voice.}
{30500}{}{Bag of Fertilizer}
{30501}{}{A bag of organic fertilizers. Just a handful of this fertilizer and the corn will grow fine and dandy.}
{30600}{}{*Whetstone*}
{30601}{}{This stone can be used to sharpen any edged weapon.}
{30700}{}{Chimera Fang}
{30701}{}{The tooth, or rather the fang, of the most dangerous creature, the Chimera! You are lucky that you were able to get it and remain all your limbs.}
{30800}{}{S-Virus Strain}
{30801}{}{A sealed ampoule containing a deadly virus. Be very careful with it!}
{30900}{}{Strange Book}
{30901}{}{At first glance it is difficult to determine what kind of book it is, at the second, too.}
{31000}{}{Ring Finger}
{31001}{}{This finger once belonged to a man, on the finger is a ring, at first glance it's very expensive.}
{31100}{}{*Map Piece*}
{31101}{}{This piece of paper is part of a map. This might even be useful.}
{31200}{}{*Map Piece*}
{31201}{}{Part of a map, find the rest of the pieces and solve the puzzle.}
{31300}{}{*Map Piece*}
{31301}{}{This is a map, only not complete. You need to find the rest of the pieces.}
{31400}{}{*Map Piece*}
{31401}{}{Map of an area, but not complete. Perhaps there are other pieces of this map.}
{31500}{}{Lavash Jerky}
{31501}{}{A juicy and delicious piece of Lavash jerky.}
{31600}{}{NWO Basement Key}
{31601}{}{A well-preserved key, use it for its intended purpose.}
{31700}{}{*Machine Parts*}
{31701}{}{One of the most important parts of the machine.}
{31800}{}{*Constitution of 15 Rights*}
{31801}{}{The Laivos Constitution for the inhabitants of the new world, created by the inhabitants for posterity. Perhaps it is useful to know the situation.}
{31900}{}{*Robotron Hand*}
{31901}{}{The electro-mechanical limb of a combat robotron.}
{32000}{}{*Electric Motor*}
{32001}{}{A patched but working electric motor.}
{32100}{}{Broken Electric Motor}
{32101}{}{A faulty electric motor.}
{32200}{}{*Sasou Perfume*}
{32201}{}{Women's perfume with a wonderful gentle fragrance.}
{32300}{}{Crystal Water}
{32301}{}{A bottle of the purest water.}
{32400}{}{*Romantic Collection*}
{32401}{}{A CD with calm melodic romantic music.}
{32500}{}{*Analogue*}
{32501}{}{A serious textbook on wave physics.}
{32600}{}{*Card Deck*}
{32601}{}{A deck of playing cards, 36 pieces coated in plastic.}
{32700}{}{*Glowing Ant Abdomen*}
{32701}{}{This ant's abdomen is unusually large and has a luminescent effect.}
{32800}{}{Human Flesh}
{32801}{}{A piece of human flesh. Mmm... Yes, it's definitely human flesh.}
{32900}{}{Porn Disk}
{32901}{}{A disk with a XXX video, the author of this creation is unfortunately unknown.}
{33000}{}{IOS Access Card}
{33001}{}{An electronic access card for the Institute of Organic Sciences.}
{33100}{}{BDE Access Card}
{33101}{}{An electronic access card for the Bureau of Design and Engineering.}
{33200}{}{LPS Access Card}
{33201}{}{An electronic access card for the Laboratories of Physical Sciences.}
{33300}{}{Õ2 Access Card}
{33301}{}{An electronic access card marked X2.}
{33400}{}{X1 Access Card}
{33401}{}{An electronic access card marked X1.}
{33500}{}{*Rad-Away*}
{33501}{}{A blister with a strange, slightly bubbling murky liquid. It is not clear whether this remedy is made in a factory, or Hand-made, but it is rumored to be an excellent cure for radiation.}
{33600}{}{Firewood}
{33601}{}{A huge armful of excellent wooden fuel for a nice cozy fire!}
{33700}{}{Scorpion Tail}
{33701}{}{The big fleshy tail of some poor scorpion.}
{33800}{}{*Plunger*}
{33801}{}{A stick with a rubber pump on the end. It is practical if you want to hit someone gently. It is also suitable for unclogg toilets.}
{33900}{}{"Name Certificate"}
{33901}{}{On a rotten piece of paper, it is illegibly written that "The Bearer is INDEED a member of the GREAT and ANCIENT Shvain family."}
{34000}{}{Douglas' Note}
{34001}{}{Looks like a list of things Olympus needs.}
{34100}{}{*Spare Parts Kit*}
{34101}{}{A heavy box with a lot of hardware inside.}
{34200}{}{*Vibrator*}
{34201}{}{A polished, well-oiled device for relieving female tension.}
{34300}{}{Obedience}
{34301}{}{A small chemical injection that causes loyality between the person who administers the drug and whomever it is injected to. Seems to work only on specific organisms.}
{34400}{}{Canned Meat}
{34401}{}{Seems that the food was only recently canned. The meat inside might be a suprise, though.}
{34500}{}{Torn Note}
{34501}{}{Part of the text is missing, but you can make out the ending: "... why you would need this, but hte code for the console is 2358. And remember Grey, everything depends on you!"}
{34600}{}{*Energy Cell*}
{34601}{}{An incredibly heavy battery. You can't help but wonder what will happen if you hit it with a sledgehammer.}
{34700}{}{*Stem Cell Essence*}
{34701}{}{A jar with a viscous organic substance. It's probably better not to even know what it is made of.}
{34800}{}{*Servo Motor*}
{34801}{}{It looks like a motor of rather complicated design. Partially covered with blood and skin particles.}
{34900}{}{Quest}
{34901}{}{}
{35000}{}{Quest}
{35001}{}{}
{35100}{}{Quest}
{35101}{}{}
{35200}{}{Quest}
{35201}{}{}
{35300}{}{Quest}
{35301}{}{}
{35400}{}{Quest}
{35401}{}{}
{35500}{}{Quest}
{35501}{}{}
{35600}{}{Quest}
{35601}{}{}
{35700}{}{Quest}
{35701}{}{}
{35800}{}{Quest}
{35801}{}{}
{35900}{}{Quest}
{35901}{}{}
{36000}{}{Quest}
{36001}{}{}
{36100}{}{Quest}
{36101}{}{}
{36200}{}{Quest}
{36201}{}{}
{36300}{}{Quest}
{36301}{}{}
{36400}{}{Quest}
{36401}{}{}
{36500}{}{Quest}
{36501}{}{}
{36600}{}{Quest}
{36601}{}{}
{36700}{}{Quest}
{36701}{}{}
{36800}{}{Quest}
{36801}{}{}
{36900}{}{Quest}
{36901}{}{}
{37000}{}{Quest}
{37001}{}{}
{37100}{}{Quest}
{37101}{}{}
{37200}{}{Quest}
{37201}{}{}
{37300}{}{Quest}
{37301}{}{}
{37400}{}{Quest}
{37401}{}{}
{37500}{}{Quest}
{37501}{}{}
{37600}{}{Quest}
{37601}{}{}
{37700}{}{Quest}
{37701}{}{}
{37800}{}{Quest}
{37801}{}{}
{37900}{}{Quest}
{37901}{}{}
{38000}{}{Jackal's Diary}
{38001}{}{A disk with a personal diary, travel notes, and other information regarding the Jackal.}
{38100}{}{Young's Research}
{38101}{}{Young's scientific work and research.}
{38200}{}{War Chronicle}
{38201}{}{Historical chronology of military operations.}
{38300}{}{Work in Renaissance}
{38301}{}{Report on the implementation and concerns about the use of robotrons.}
{38400}{}{PD Alloy Research}
{38401}{}{Chemical analysis of a fundamentally new metal alloy.}
{38500}{}{Tartarus Directive}
{38501}{}{A collection of edicts distributed in Tartarus.}
{38600}{}{Shvain's Notes}
{38601}{}{The notes of the gunsmith Sebastian Schwein.}
{38700}{}{Olympus Promotion}
{38701}{}{Olympus! The greatest creation of mankind!}
{38800}{}{On the Enlightened Ones}
{38801}{}{Notes of a certain person about the experience of communicating with the Enlightened Ones.}
{38900}{}{Recruit's Diary}
{38901}{}{A dusty, dirty disk from a nameless corpse.}
{39000}{}{Solar Gun}
{39001}{}{A unique pistol powered by solar energy, a great economical weapon.}
{39100}{}{MCA Predator}
{39101}{}{A mechanized combat armor system from NCASTR. Only the Enlightened Ones may wear use this Holy Armor!}
{39200}{}{SMG Parts}
{39201}{}{Spare parts for a submachine gun, still oiled.}
{39300}{}{*Personal Diary*}
{39301}{}{This is your personal diary of smart (and not so smart) thoughts. Don't lose your mother's gift.}
{39400}{}{*Herald's Robes*}
{39401}{}{Under the thick cloth cowl hides a reliable military armor, and a low hood completely hides the face of the owner.}
{39500}{}{Mr. Potato Strength}
{39501}{}{A collectible Potato Superman figurine! Rare and expensive! It will raise your strength!}
{39600}{}{Mr. Potato Perception}
{39601}{}{Feel the true power of the dark side with the collectible Potato Vader! Your power of perception increases!}
{39700}{}{Mr. Potato Endurance}
{39701}{}{A collectible human-alien-gorilla! This action figure will give you endurance.}
{39800}{}{Mr. Potato Charisma}
{39801}{}{As a real prince of the hearts, Potato Elvis will give you a bit of his charisma.}
{39900}{}{Mr. Potato Intelligence}
{39901}{}{A brainy genius should eat potatoes! The collectible Potato Nerd will make you a little smarter.}
{40000}{}{Mr. Potato Agility}
{40001}{}{Skillful as a potato bat, Potato Batman will increase your agility!}
{40100}{}{Mr. Potato Luck}
{40101}{}{Fortuna loves potatoes. Keep the collectible Potato Rabbit with you for good luck!}
{40200}{}{Orange Chucky}
{40201}{}{The sparkling character of this comic book will quickly teach you the basics of self-defense and hand-to-hand combat.}
{40300}{}{A Player Orange}
{40301}{}{In this comic, the orange baseball player will teach you throwing techniques, one of the most important skills in this world.}
{40400}{}{Annoying Orange}
{40401}{}{The orange tongue is our real hero! His witty phrases and ingenious examples can give you a lot of interesting information about communicating with people and beyond.}
{40500}{}{Grenade Launcher Module}
{40501}{}{}
{40600}{}{Minigun Module}
{40601}{}{}
{40700}{}{Laser module}
{40701}{}{}
{40800}{}{Field Medic Kit}
{40801}{}{Bandages, peroxide, painkillers, a tourniquet and this is not all that can be found in this first aid kit.}
{40900}{}{Paramedic Kit}
{40901}{}{Resuscitation kit of a paramedic, everything you need to provide quick and serious help.}
{41000}{}{Glas Marbles}
{41001}{}{Cute and smooth glass marbles, it's nice to roll them in your hands}
{41100}{}{Rusty Bolt}
{41101}{}{An old rusty bolt. It's so rusty that you don't even want to pick it up.}
{41200}{}{Tattered book}
{41201}{}{You can still make out individual phrases, but it is no longer really possible to understand what is written there.}
{41300}{}{Old Comic Book}
{41301}{}{It is quite interesting to look at the faded pictures, although there is no benefit from this.}
{41400}{}{Glass Bottle}
{41401}{}{An empty glass bottle. What would you like to fill it with?}
{41500}{}{Wooden Comb}
{41501}{}{A tool for grooming - if you still have hair left on your head.}
{41600}{}{Children's Drawing}
{41601}{}{A crude child's drawing. Questionable art.}
{41700}{}{Children's Drawing}
{41701}{}{What is drawn here? The apocalypse?}
{41800}{}{Children's Drawing}
{41801}{}{Well, if you can call this multicolored smudge a drawing.}
{41900}{}{Metal Fork}
{41901}{}{The fork is in good condition. You can eat with it, or poke yourself in the eye.}
{42000}{}{Rusty Fork}
{42001}{}{A rusty fork, does anyone really eat with this?}
{42100}{}{Nails}
{42101}{}{Some rather long nails.}
{42200}{}{Matches}
{42201}{}{Matches are not a toy for children! Hey, they still light up!}
{42300}{}{Yarn Spool}
{42301}{}{If your are into sewing, this spool of robust thread will definitely make your very happy.}
{42400}{}{Crayons}
{42401}{}{Quite a rare, but useless item. You could leave some rock paintings somewhere.}
{42500}{}{Metal Plate}
{42501}{}{Obviously, you can eat soup from this. Or porridge.}
{42600}{}{Rusty Plate}
{42601}{}{Looking at several layers of rust, it's hard to imagine HOW you can eat from it.}
{42700}{}{Iron Plates}
{42701}{}{A few iron plates, almost untouched by rust.}
{42800}{}{72% Soap}
{42801}{}{Don't eat it!!!}
{42900}{}{Old Spork}
{42901}{}{The most ingenious invention of mankind, the spork. Half spoon, halt fork, and his own best friend!}
{43000}{}{Metal Spoon}
{43001}{}{You can eat with it, or dig a grave for a rat.}
{43100}{}{Metal Cup}
{43101}{}{A container to drink liquids out of, if you don't want to use your hands.}
{43200}{}{Seal Stamp}
{43201}{}{An old seal with the letters "NCASTR" on it. If you slap it on your forehead, it will leave a nice marking.}
{43300}{}{Torn Rag}
{43301}{}{It's just a piece of blue rag. You have not seen rags of other colors.}
{43400}{}{Candy}
{43401}{}{A delicious and quite rare treat. If you eat it, it may seem that everything is not so bad.}
{43500}{}{Paint}
{43501}{}{An old can of oil paint. You could paint a wall.}
{43600}{}{Lavash Skin}
{43601}{}{The tanned skin of lavash can be used to make leather items.}
{43700}{}{*Metal Reel*}
{43701}{}{A reel of rolled up five millimeters thick metal sheets.}
{43800}{}{Tin can}
{43801}{}{An old rusty tin can.}
{43900}{}{Dried Leaves}
{43901}{}{A couple of handfuls of dried leaves. Excellent fertilizer!}
{44000}{}{Ash}
{44001}{}{A handful of wood ash.}
{44100}{}{*Dried Cheese*}
{44101}{}{A piece of very old parmesan cheese, however it has already dried to the state of wood.}
{44200}{}{Lavash Meat}
{44201}{}{A piece of raw and fresh lavash meat, rich in protein and juicy.}
{44300}{}{Sugar}
{44301}{}{A pack of sugar. Although old age and dampness made it hard as a rock, it's still as sweet as before.}
{44400}{}{Sex Pill}
{44401}{}{}
{44500}{}{Seedy Disk}
{44501}{}{Sounds like someone's amateur story.}
{44600}{}{Scientific Report}
{44601}{}{A label on the side reads "Project Gamma"}
{44700}{}{Dinosaur Figurine}
{44701}{}{The the owner probably loved this toy.}
{44800}{}{Annotated Book}
{44801}{}{The cover says The Holy Bible. In it a lot of passages are marked, annotated and many words have been crossed out or corrected.}
{44900}{}{Item}
{44901}{}{}
{45000}{}{Item}
{45001}{}{}
{45100}{}{Item}
{45101}{}{}
{45200}{}{Item}
{45201}{}{}
{45300}{}{Item}
{45301}{}{}
{45400}{}{Item}
{45401}{}{}
{45500}{}{Item}
{45501}{}{}
{45600}{}{Item}
{45601}{}{}
{45700}{}{Item}
{45701}{}{}
{45800}{}{Item}
{45801}{}{}
{45900}{}{Item}
{45901}{}{}
{46000}{}{Item}
{46001}{}{}
{46100}{}{Item}
{46101}{}{}
{46200}{}{Item}
{46201}{}{}
{46300}{}{Item}
{46301}{}{}
{46400}{}{Item}
{46401}{}{}
{46500}{}{Item}
{46501}{}{}
{46600}{}{Item}
{46601}{}{}
{46700}{}{Item}
{46701}{}{}
{46800}{}{Item}
{46801}{}{}
{46900}{}{Item}
{46901}{}{}
{47000}{}{Item}
{47001}{}{}
{47100}{}{Item}
{47101}{}{}
{47200}{}{Item}
{47201}{}{}
{47300}{}{Item}
{47301}{}{}
{47400}{}{Item}
{47401}{}{}
{47500}{}{Item}
{47501}{}{}
{47600}{}{Item}
{47601}{}{}
{47700}{}{Item}
{47701}{}{}
{47800}{}{Item}
{47801}{}{}
{47900}{}{Item}
{47901}{}{}
{48000}{}{Item}
{48001}{}{}
{48100}{}{Item}
{48101}{}{}
{48200}{}{Item}
{48201}{}{}
{48300}{}{Hintbook}
{48301}{}{Well, THIS would have been good to have at the beginning of the goddamn game.}
{48400}{}{Moonshine Tray}
{48401}{}{Made from plastic and lovingly glued together by Smitty, the tray is for his Magic Moonshine Machine.}
{48500}{}{Rusty Grate}
{48501}{}{An old rusty grate. After touching it, red spots remain on the fingers.}
{48600}{}{Moonshine Filter}
{48601}{}{A simple filter for the moonshine distiller. It looks like it should save the consumption of rare candies.}
{48700}{}{Jackal Grip}
{48701}{}{The grip of the Jackal Revolver, find the rest of the parts and build yourself a great gun.}
{48800}{}{Jackal Barrel}
{48801}{}{The barrel of the Jackal Revolver, find the rest of the parts and build yourself a great gun.}
{48900}{}{Jackal Drum}
{48901}{}{The drum of the Jackal Revolver, find the rest of the parts and build yourself a great gun.}
{49000}{}{Plasma Module}
{49001}{}{}
{49100}{}{Machinegun Module}
{49101}{}{}
{49200}{}{Item}
{49201}{}{}
{49300}{}{Item}
{49301}{}{}
{49400}{}{Item}
{49401}{}{}
{49500}{}{Item}
{49501}{}{}
{49600}{}{Item}
{49601}{}{}
{49700}{}{Item}
{49701}{}{}
{49800}{}{Item}
{49801}{}{}
{49900}{}{Item}
{49901}{}{}
{50000}{}{Item}
{50001}{}{}
{50100}{}{Item}
{50101}{}{}
{50200}{}{Item}
{50201}{}{}
{50300}{}{Item}
{50301}{}{}
{50400}{}{Item}
{50401}{}{}
{50500}{}{Item}
{50501}{}{}
{50600}{}{Item}
{50601}{}{}
{50700}{}{Item}
{50701}{}{}
{50800}{}{Item}
{50801}{}{}
{50900}{}{Item}
{50901}{}{}
{51000}{}{Item}
{51001}{}{}
{51100}{}{Item}
{51101}{}{}
{51200}{}{Item}
{51201}{}{}
{51300}{}{D.E.U.S. Weapon}
{51301}{}{This is a unique weapon, its owner was one of the "Gods" of Olympus!}
{51400}{}{Horn}
{51401}{}{A trophy from the chimera's corpse, you can use it as a weapon.}
{51500}{}{Claw}
{51501}{}{Trophy claw of the Chimera. Dangerous stuff in battle.}
{51600}{}{Fang}
{51601}{}{You could make a necklace out of these fangs. Or a kind of knife!}
{51700}{}{Sharp Fang}
{51701}{}{This jackal was clearly not eager to share this tooth with you. Appreciate it as its former owner did.}
{51800}{}{Fang}
{51801}{}{The sharp fang of a creepy mole rat.}
{51900}{}{Fang}
{51901}{}{Ursa don't like to part with their teeth very much, so whoever got it is a brave man or not a man at all.}
{52000}{}{Claw}
{52001}{}{Ursa claws are not uncommon, but they are still worth something. Sharp and dangerous! You can rip open a couple of throats.}
{52100}{}{Fang}
{52101}{}{Rats are not uncommon in these parts, so you can collect a few dozen of these fangs if you want.}
{52200}{}{Stinger}
{52201}{}{From the stinger of a scorpion, you can get a sample of its venom, which is very useful in making an antidote. Or use it as a weapon.}
{52300}{}{Fang}
{52301}{}{The owner of such a trophy can be proud of himself. The sale is very profitable, and it's also very useful as a melee weapon.}
{52400}{}{Claw}
{52401}{}{The Beast's Claw is an excellent melee weapon.}
{52500}{}{Shelves}
{52501}{}{Wooden shelves with some junk on them.}
{52600}{}{Shelves}
{52601}{}{Wooden shelves, very convenient for storing things.}
{52700}{}{Shelves}
{52701}{}{Wooden shelves, very convenient for storing things.}
{52800}{}{Desk}
{52801}{}{A wooden desk with drawers.}
{52900}{}{Desk}
{52901}{}{A wooden desk with drawers.}
{53000}{}{Boxes}
{53001}{}{You can't help but wonder about the origin of these strange brown spots on the boxes.}
{53100}{}{Boxes}
{53101}{}{You can't help but wonder about the origin of these strange brown spots on the boxes.}
{53200}{}{Stuff}
{53201}{}{Have you ever been told that it's not good to go through other people's belongings?}
{53300}{}{Stuff}
{53301}{}{Have you ever been told that it's not good to go through other people's belongings?}
{53400}{}{Junk}
{53401}{}{Sometimes there's something useful in the junk.}
{53500}{}{Junk}
{53501}{}{Sometimes there's something useful in the junk.}
{53600}{}{Stuff}
{53601}{}{Rummagin through other people's stuff can get you a hard piece of steel through your ribs very quickly. Better be discreet about it.}
{53700}{}{Junk}
{53701}{}{Some random stuff, nothing worth looking at.}
{53800}{}{Computer Desk}
{53801}{}{You're curious why they have two monitors here.}
{53900}{}{Safe}
{53901}{}{Safes were designed to hide something in them, and from people like you.}
{54000}{}{Locker}
{54001}{}{A metal storage cabinet.}
{54100}{}{Locker}
{54101}{}{A metal storage cabinet.}
{54200}{}{Locker}
{54201}{}{A metal storage cabinet.}
{54300}{}{Locker}
{54301}{}{A metal storage cabinet.}
{54400}{}{Locker}
{54401}{}{A metal cabinet, rather rusty.}
{54500}{}{Locker}
{54501}{}{A metal cabinet, rather rusty.}
{54600}{}{Locker}
{54601}{}{A rusty metal cabinet, which is also pretty dented.}
{54700}{}{Cabinet}
{54701}{}{The lack of doors usually does not prevent the use of drawers for storing all sorts of things.}
{54800}{}{Cabinet}
{54801}{}{The lack of doors usually does not prevent the use of drawers for storing all sorts of things.}
{54900}{}{Makeshift Crate}
{54901}{}{The person who built the box obviously cared little for its aesthetic properties.}
{55000}{}{Makeshift Crate}
{55001}{}{The person who built the box obviously cared little for its aesthetic properties.}
{55100}{}{Sitting Crate}
{55101}{}{A solid homemade box. It can be used as a bench, but at the risk of getting a splinter in the ass.}
{55200}{}{Sitting Crate}
{55201}{}{A solid homemade box. It can be used as a bench, but at the risk of getting a splinter in the ass.}
{55300}{}{Machine Parts}
{55301}{}{There may well be something interesting there.}
{55400}{}{Stuff}
{55401}{}{The presence of a box with unknown contents in this junk arouses your curiosity.}
{55500}{}{Stuff}
{55501}{}{The presence of a box with unknown contents in this junk arouses your curiosity.}
{55600}{}{Box}
{55601}{}{Usually people use boxes to put things in them.}
{55700}{}{Safe}
{55701}{}{Safes were designed to hide something in them, and from people like you.}
{55800}{}{Safe}
{55801}{}{Safes were designed to hide something in them, and from people like you.}
{55900}{}{Cupboard}
{55901}{}{A dirty old cupboard.}
{56000}{}{Box}
{56001}{}{Usually people use boxes to put things in them.}
{56100}{}{Box}
{56101}{}{Usually people use boxes to put things in them.}
{56200}{}{Shelves}
{56201}{}{Judging by the fresh bloodstains, some poor guy has been very unlucky here recently.}
{56300}{}{Container}
{56301}{}{Judging by the fresh bloodstains, some poor guy has been very unlucky here recently.}
{56400}{}{Locker}
{56401}{}{Its contents should definitely be examined.}
{56500}{}{Box}
{56501}{}{A large, slightly open box, something is visible inside.}
{56600}{}{Cupboard}
{56601}{}{People usually store something in them, and that's what they were invented for.}
{56700}{}{Shelves}
{56701}{}{The abundance of things on the shelves encourages you to explore them.}
{56800}{}{Casket}
{56801}{}{These laser beams can easily cut off your arm, but you are not eager to test it.}
{56900}{}{Safe}
{56901}{}{Helps it's owner to hide his belongins from the overtly curious curious. Yes, we mean you!}
{57000}{}{Box}
{57001}{}{A half-open box begs for a look at its contents.}
{57100}{}{Shelves}
{57101}{}{Wall-mounted shelves are usually used to store things.}
{57200}{}{Shelves}
{57201}{}{Wall-mounted shelves are usually used to store things.}
{57300}{}{Personal Locker}
{57301}{}{This is very convenient to store personal items and more here.}
{57400}{}{Locker}
{57401}{}{A metal cabinet with a door.}
{57500}{}{Footlocker}
{57501}{}{A metal box, which perfectly protects things from adverse external influences.}
{57600}{}{Footlocker}
{57601}{}{A metal box, which perfectly protects things from adverse external influences.}
{57700}{}{Wardrobe}
{57701}{}{If you are asked why you went into someone else's closet, answer that you were looking for a transition to a fairy-tale world in it.}
{57800}{}{Wardrobe}
{57801}{}{If you are asked why you went into someone else's closet, answer that you were looking for a transition to a fairy-tale world in it.}
{57900}{}{Shelves}
{57901}{}{The abundance of things on the shelves encourages you to explore them.}
{58000}{}{Shelves}
{58001}{}{The abundance of things on the shelves encourages you to explore them.}
{58100}{}{Shelves}
{58101}{}{The abundance of things on the shelves encourages you to explore them.}
{58200}{}{Locker}
{58201}{}{A metal cabinet with a door.}
{58300}{}{Container}
{58301}{}{}
{58400}{}{Container}
{58401}{}{}
{58500}{}{Container}
{58501}{}{}
{58600}{}{Container}
{58601}{}{}
{58700}{}{Container}
{58701}{}{}
{58800}{}{Container}
{58801}{}{}
{58900}{}{Container}
{58901}{}{}
{59000}{}{Container}
{59001}{}{}
{59100}{}{Container}
{59101}{}{}
{59200}{}{Container}
{59201}{}{}
{59300}{}{Container}
{59301}{}{}
{59400}{}{Container}
{59401}{}{}
{59500}{}{Rat Hole}
{59501}{}{It's large, deep, and there must be someone living in it.}
{59600}{}{Grave}
{59601}{}{Someone's grave.}
{59700}{}{Grave}
{59701}{}{There must be someone lying there.}
{59800}{}{Grave}
{59801}{}{It is possible that there is something to gain there.}
{59900}{}{Grave}
{59901}{}{You don't care about the Gravedigger's reputation, do you?}
{60000}{}{Grave}
{60001}{}{Don't even try to dig it up.}
{60100}{}{Grave}
{60101}{}{Where is the shovel...}
