{100}{}{.223 FMJ}
{101}{}{A case of standard .223 caliber rifle ammunition.}
{200}{}{.223 Custom}
{201}{}{Hand-made .223 caliber rifle bullets.}
{300}{}{.223 AP}
{301}{}{A case of armor-piercing .223 caliber rifle ammunition.}
{400}{}{.308 FMJ}
{401}{}{A case of standard .308 caliber rifle ammunition.}
{500}{}{.308 Custom}
{501}{}{Hand-made .308 caliber rifle bullets.}
{600}{}{.38 ACP}
{601}{}{A case of standard .38 caliber pistol ammunition.}
{700}{}{.38 Custom}
{701}{}{Hand-made .38 caliber pistol bullets.}
{800}{}{.45 ACP}
{801}{}{A case of standard .45 caliber pistol ammunition.}
{900}{}{.45 Custom}
{901}{}{Hand-made .45 caliber pistol bullets.}
{1000}{}{.50 BMG}
{1001}{}{A case of standard .50 caliber heavy machine gun ammunition.}
{1100}{}{12 ga. Buckshot}
{1101}{}{A case of standard 12 gauge shotgun buckshot shells.}
{1200}{}{12 ga. Long}
{1201}{}{A case of extra long 12 gauge shotgun shells.}
{1300}{}{12 ga. Slug}
{1301}{}{A case of standard 12 gauge shotgun slug cartridges.}
{1400}{}{12 ga. Custom}
{1401}{}{Hand-made 12 gauge buckshot shells.}
{1500}{}{25mm HE}
{1501}{}{A standard 25mm high explosive grenade.}
{1600}{}{25mm EMP}
{1601}{}{A special 25mm grenade, designed to destroy electronics and robots.}
{1700}{}{40mm HE}
{1701}{}{A standard 40mm high explosive grenade.}
{1800}{}{40mm WP}
{1801}{}{A white phosphorous 40mm incendiary grenade.}
{1900}{}{9mm JHP}
{1901}{}{A case of standard military 9mm pistol ammunition.}
{2000}{}{9mm Custom}
{2001}{}{Hand-made 9mm pistol bullets.}
{2100}{}{9mm HPS}
{2101}{}{A case of special anti-personnel 9mm pistol ammunition.}
{2200}{}{9mm AP}
{2201}{}{A case of armor-piercing 9mm pistol ammunition.}
{2300}{}{BigBat energy cell}
{2301}{}{A large, self-contained energy cell.}
{2400}{}{Rubber Bullet}
{2401}{}{While not the most dangerous type of ammunition, rubber bullets can knock an opponent out for a while.}
{2500}{}{Poisoned Dart}
{2501}{}{Although made of junk, the darts are perfectly balanced. Inside each is a cavity containing poison. Too bad they're single-use only.}
{2600}{}{12mm Nitro}
{2601}{}{A case of special 12mm incendiary ammunition for the unique "Hotter" shotgun.}
{2700}{}{Magnum Bullets}
{2701}{}{Very powerful magnum revolver cartridges.}
{2800}{}{MiniBat energy cell}
{2801}{}{A small, self-contained energy cell.}
{2900}{}{Napalm}
{2901}{}{A canister of a viscous incendiary substance based on gasoline.}
{3000}{}{EMP Rocket}
{3001}{}{A special rocket shell, designed to destroy electronics and robots.}
{3100}{}{HE Rocket}
{3101}{}{A standard rocket with a high explosive warhead.}
{3200}{}{AP Rocket}
{3201}{}{A special rocket shell, designed to pierce armor plating.}
{3300}{}{BB Pellets}
{3301}{}{A case of small metal ball bearings, used by pneumatic pistols and rifles.}
{3400}{}{Shotgun Fist}
{3401}{}{Whoa, someone mounted a shotgun in these knuckles. Be careful, the blood of your victims can jam the mechanism. Min ST: 5}
{3500}{}{Aluminum Knuckles}
{3501}{}{Small, light, featureless, but these brass knuckles will help you not to snap your fingers with someone's jaw. Min ST: 2}
{3600}{}{Brass Knuckles}
{3601}{}{That's more like it! With these brass knuckles, you can break someone's skull or kneecaps. Min ST: 4}
{3700}{}{Spiked Knuckles}
{3701}{}{The most dangerous of brass knuckles: rips the skin, breaks bones, and lifts the mood of its owner! Min ST: 4}
{3800}{}{Lead Gloves}
{3801}{}{Very useful, crushes bones like it's nothing. Min ST: 5}
{3900}{}{Corkscrew}
{3901}{}{A rather dangerous and inconspicuous weapon. Aim for the eyes! Min ST: 3}
{4000}{}{Buzz Blade}
{4001}{}{Bzzzz! A chainsaw on your hand. Chopping meat, cutting sinew, and crushing bone were never easier! It's so light and comfortable that you're likely to forget about it when deciding to scratch yourself. Min ST: 6}
{4100}{}{Batteries}
{4101}{}{The only generally accepted means of payment in the Radius.}
{4200}{}{Mine}
{4201}{}{A typical American-made anti-personnel mine with a chemical activation trigger.}
{4300}{}{C4 Explosives}
{4301}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive.}
{4400}{}{Armed C4 Explosives}
{4401}{}{!!Activated!! A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. It's armed!}
{4500}{}{C4 Detonator}
{4501}{}{A radio-controlled detonator for C4 explosives.}
{4600}{}{C4 Deactivator}
{4601}{}{A device for canceling the activation of C4 explosives.}
{4700}{}{First Aid Kit}
{4701}{}{A small kit containing basic medical equipment. Bandages, wraps, antiseptic spray, and more.}
{4800}{}{Electric Trap}
{4801}{}{A trap that employs an electric charge when triggered.}
{4900}{}{Explosive Trap}
{4901}{}{A trap that detonates then the tripwire is triggered.}
{5000}{}{Don't use this!}
{5001}{}{}
{5100}{}{Dynamite}
{5101}{}{A stick of good old dynamite.}
{5200}{}{Geiger Counter}
{5201}{}{A vital tool in the wasteland. It determines the exposure of gamma and beta radiation.}
{5300}{}{Watch}
{5301}{}{A "Singletronic" wristwatch with a quartz mechanism and shockproof case.}
{5400}{}{Stealth Boy}
{5401}{}{A device that uses an electromagnetic field to create an invisibility effect around the user.}
{5500}{}{Lockpicks}
{5501}{}{A set of locksmith tools. A key instrument of a burglar.}
{5600}{}{Expanded Lockpick Set}
{5601}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open locks. This set also includes some special tools for more difficult mechanical locking mechanisms.}
{5700}{}{Electronic Lockpick}
{5701}{}{A universal tool for defeating electronic locks and security devices.}
{5800}{}{Electronic Lockpick MKII}
{5801}{}{A more advanced version of electronic lockpick for electronic locks and security devices. Now you can open twice as many locks!}
{5900}{}{Motion Sensor}
{5901}{}{A motion sensor detects even the slightest movements over a long distance, using a tuned radar device.}
{6000}{}{Chainsaw Sword}
{6001}{}{You can chop wood with it, but chopping people feel way better. Min ST: 6}
{6100}{}{Laser Saw}
{6101}{}{This tool can cut through almost anything. Take extreme care when using it. Min ST: 4}
{6200}{}{Combat Throwing Knife}
{6201}{}{A very sharp and balanced knife that is excellent for throwing. You've read that squads of Navy SEALS used them for silent takedowns. Min ST: 4}
{6300}{}{Throwing Knife}
{6301}{}{A hand-made sharpened and balanced throwing knife. Not quite as aerodynamic as factory-made though. Min ST: 3}
{6400}{}{Combat Knife}
{6401}{}{A heavy knife with a wide blade allows dealing an extended blood loss. In the right hands, this piece of cold steel can kill a lot of people! Min ST: 4}
{6500}{}{Cutting Knife}
{6501}{}{If you can't decide if you want to cut up bread, sausages, or your annoying neighbor. Min ST: 3}
{6600}{}{Cleaver}
{6601}{}{A butcher's knife that cuts through bones in a single swing. Min ST: 5}
{6700}{}{Scalpel}
{6701}{}{A surgical scalpel, very sharp and simple to use. Be careful with it! Min ST: 2}
{6800}{}{Serrated Cleaver}
{6801}{}{The maniac's tool! A powerful, edged weapon with a serrated blade will cut down any enemy. Min ST: 4}
{6900}{}{Lightning Spear}
{6901}{}{A heavy metal spear with a power source connected to it. Hits the enemy not only with its pointed tip but also with a hefty electric shock. Min ST: 5}
{7000}{}{Wooden Spear}
{7001}{}{A sharp wooden spear made using Stone Age technology. Min ST: 4}
{7100}{}{Iron Spear}
{7101}{}{A metal rod with a sharp, pointed head. Min ST: 5}
{7200}{}{Placeholder Spear}
{7201}{}{}
{7300}{}{Science Book}
{7301}{}{Study science. At this time any information is worth its weight in gold.}
{7400}{}{Pistol Parts}
{7401}{}{You can assemble a pistol from this if you have the skills and a special repair kit.}
{7500}{}{Revolver Parts}
{7501}{}{You can assemble a revolver from this if you have the skills, persistence, and a special repair kit.}
{7600}{}{Engineering Book}
{7601}{}{A manual for repairing broken equipment, machines, and electronics.}
{7700}{}{Rifle Parts}
{7701}{}{This heap of parts can be assembled into a good rifle if you have the skills and a special repair kit.}
{7800}{}{Shotgun Parts}
{7801}{}{You can assemble a shotgun from this if you have the skills and a special repair kit.}
{7900}{}{Flashlight}
{7901}{}{An old flashlight.}
{8000}{}{Medical Book}
{8001}{}{A medical reference book with an index, a convenient guide for quickly mastering the most necessary medical skills.}
{8100}{}{Assault rifle Parts}
{8101}{}{These parts can be assembled into an assault rifle if you have the skills and a special repair kit.}
{8200}{}{Universal Screwdriver}
{8201}{}{A screwdriver with multiple attachments, suitable for many operations.}
{8300}{}{Repair Kit}
{8301}{}{A universal repair set, containing various useful tools. Pliers included.}
{8400}{}{Pistol Repair Kit}
{8401}{}{A kit for the maintenance and assembly of pistols.}
{8500}{}{Explosives}
{8501}{}{A bundle of good old trinitrotoluene.}
{8600}{}{Scout Handbook}
{8601}{}{A book on the methods and ideals of Scouting. Very practical information regarding outdoor life.}
{8700}{}{Zeus Electric Hammer}
{8701}{}{A huge metal hammer powered with batteries. See how merrily the crushed skull of the enemy twitches under the electric charge! Min ST: 7}
{8800}{}{Sledgehammer}
{8801}{}{This hammer can crush granite and skulls! More often it is skulls. Min ST: 7}
{8900}{}{Battle Sledge}
{8901}{}{A heavy, primitive, but still very efficient way to calm down a nervous bipedal. Or any-pedal. Min ST: 7}
{9000}{}{Placeholder Hammer}
{9001}{}{}
{9100}{}{Doctor's Bag}
{9101}{}{A roomy bag that contains instruments and drugs used by doctors in the application of their trade.}
{9200}{}{Light Support Weapon}
{9201}{}{A military support machine gun that was in service with the heavy infantry of the US Armed Forces from 1978 to 1989. Min ST: 7}
{9300}{}{"Baraka" Machinegun}
{9301}{}{An experimental super-heavy machinegun, developed by the company "Britannic Engineering" to be used with the "Defender" mechanized combat armor system. An incredibly powerful recoil can easily tear an arm off! Min ST: 10}
{9400}{}{Turret Machinegun}
{9401}{}{How did you manage to take the machine gun off the turret? Min ST: 9}
{9500}{}{"Law" Machinegun}
{9501}{}{A heavy machine gun, developed by "Civil Defense" company for the US Army for paramilitary police units. Usually mounted on lightly armored vehicles, it has proven itself as an excellent tool against protesters! Min ST: 8}
{9600}{}{"SLR-3" Laser Rifle}
{9601}{}{A modification of "The Great Schwein's Superior Laser Rifle", developed by Sebastian Schwein in 2198. Heavy, and uncomfortable to use, but damn - it's a laser! Min ST: 7}
{9700}{}{"SLR-4" Laser Rifle}
{9701}{}{This model is a replacement for the "SLR-3" model, made in 2202. Differences from its predecessor include a slightly bigger weight, increased firing range, and laser pulse stability. Min ST: 8}
{9800}{}{Plasma Rifle}
{9801}{}{This unique weapon fires super-heated plasma that cuts metal like a hot knife through butter. Don't forget to feed it with vast amounts of energy cells. Without your participation, this beast of mass destruction would never have seen the light of day! Be proud of yourself. Min ST: 9}
{9900}{}{"FT2A" Flamethrower}
{9901}{}{A military flamethrower that spits searing flames of napalm. Burn baby, burn! Min ST: 8}
{10000}{}{"Hellbringer"}
{10001}{}{The poetic name of this incendiary monster speaks for itself. With this gun, the smell of burnt meat will stick firmly in your nostrils! Min ST: 9}
{10100}{}{"F4ster" Flamer}
{10101}{}{A hand-made and a rather playful representative of the realm of flamethrowers. Just be careful, because this baby is very unstable due to the increased supply of hot mixture into its nozzle! Min ST: 9}
{10200}{}{Gunpoint Magazine}
{10201}{}{A gun magazine devoted to the practical use of firearms, and the occasional biased review.}
{10300}{}{Taser}
{10301}{}{A fairly strong electric shock will sober up any bully who picks on you! Min ST: 5}
{10400}{}{Crowbar}
{10401}{}{Rips out nails, opens doors, knocks out teeth. The application range of this piece of metal is limitless! Min ST: 5}
{10500}{}{Placeholder Club}
{10501}{}{}
{10600}{}{Pipe Wrench}
{10601}{}{Old, rusty, but heavy and with a comfortable handle! Min ST: 6}
{10700}{}{"Ratcatcher"}
{10701}{}{Home-made weapon for clobbering small rodents. Large ones will do too. Min ST: 6}
{10800}{}{Hammer}
{10801}{}{A blunt instrument for work and self-defense. Min ST: 5}
{10900}{}{Nail Board}
{10901}{}{When it comes to hurting others, some people get very creative. Min ST: 5}
{11000}{}{Bludgeon}
{11001}{}{It's just a handle from a pool cue. Fits in your hand easily and comfortably. Min ST: 4}
{11100}{}{Pipe}
{11101}{}{Just a piece of rusty pipe. When you hit someone on the head it makes a cheerful ringing sound. Min ST: 6}
{11200}{}{"Calmer" Police Baton}
{11201}{}{An old police tool for dealing with the protesters. The Baton causes a lot of pain, but it leaves almost no traces on the body! Min ST: 5}
{11300}{}{Leather Jacket}
{11301}{}{A leather jacket, thick and heavy. Although it will hardly protect you from a bullet.}
{11400}{}{Aviator Jacket}
{11401}{}{A fashionable jacket made of very thick and high-quality leather. It will reliably protect you not only from wind and cold, but also from being stabbed with a knife.}
{11500}{}{Baseball Gear}
{11501}{}{A sports equipment in the past, now it's very good combat protection.}
{11600}{}{"Super Catcher"}
{11601}{}{Baseball sports equipment provides decent protection against blows and hits from small-caliber weapons.}
{11700}{}{Hockey Gear}
{11701}{}{Durable and comfortable hockey protection. It will protect you from many blows.}
{11800}{}{Rusty Cuirass}
{11801}{}{Looks just like a rusty pile of scrap metal. It still gives you some protection, but don't ask too much of it.}
{11900}{}{Metal Armor}
{11901}{}{Strong and heavy armor made of sheet metal. Constricts movement but offers great protective capabilities.}
{12000}{}{Military Armor}
{12001}{}{The most widespread armor used by army infantry in the war. Still reliable.}
{12100}{}{Combat Armor}
{12101}{}{Infantry combat armor: leather, kevlar, metal layers. Perfectly shields from different projectile types.}
{12200}{}{Scout Armor}
{12201}{}{Lightweight version of combat armor, upgraded for long-term reconnaissance operations behind enemy lines. Light, comfortable, functional, and also gives its wearer a trim and sporty look!}
{12300}{}{Fake Military Armor}
{12301}{}{While this armor looks like the classic military armor of the Olympus Scouts, it's still fake. Oh, and don't expect any good protection while wearing it!}
{12400}{}{Environmental Armor}
{12401}{}{The suit is designed specifically for usage in extremely hostile environments, therefore, it is extremely resistant to radioactive and gas contaminations. The best radiation protection in the entire Radius!}
{12500}{}{Battle Armor}
{12501}{}{The armor offers almost full-body protection and is specially made for infantry assault groups. It offers increased mobility and maneuverability, because of the reduced thickness of the armor and the usage of composite materials.}
{12600}{}{Battle Armor MKII}
{12601}{}{An improved version of the standard battle armor, stronger, and more impressive! You will surely appreciate the comfort of the new leather inserts between the hip plates!}
{12700}{}{"AS-2000"}
{12701}{}{A mechanized exo-suit based on a system of hydraulic and servo-motors, powered by a nuclear battery. This model offers poor protection against radiation, but the thick layers of armor are excellent against firearms and energy weapons!}
{12800}{}{"AS-2000" MKII}
{12801}{}{The "AS-2000" has been replaced by a modern upgraded and modified MKII, now featuring the programmable stabilization system and inverse kinematics system.}
{12900}{}{MCA "Defender"}
{12901}{}{This is a legendary mechanized combat armor system, powered by diesel-nuclear propulsion. Only the elite warriors of Olympus - the Defenders - are worthy of wearing this!}
{13000}{}{"Slugger"}
{13001}{}{An award-winning German-made pistol, characterized by its high accuracy, stopping power, reliability, and elegant, intricate handle design. Min ST: 4}
{13100}{}{"Detective" Revolver}
{13101}{}{A short-barreled revolver, model ST-115, nicknamed "Detective", as it was a mandatory possession of any private investigator until 1988. It is said to fail at critical moments, but has also saved many! Min ST: 4}
{13200}{}{.45 Revolver}
{13201}{}{A basic average revolver, named after the fact that the cartridge-feeding mechanism is designed in the shape of a rotating drum. Min ST: 5}
{13300}{}{Magnum Revolver}
{13301}{}{Being that this is the most powerful handgun in the world, and would blow your head clean off, you've got to ask yourself one question: "Do I feel lucky?" Well, do ya, punk? Min ST: 5}
{13400}{}{Flare Gun}
{13401}{}{A signal pistol, which uses flares as a cartridge. It can easily burn through leather armor. Min ST: 5}
{13500}{}{"Thunder"}
{13501}{}{This pistol is a remade single-fire under-barrel 40mm grenade launcher. This little thing will give many moments of fun to its owner. Min ST: 6}
{13600}{}{9mm "Glocker" Pistol}
{13601}{}{The 9mm "Glocker" pistol, manufactured by D&R, is a classic representative of the German military industry. Very accurate and reliable. Min ST: 4}
{13700}{}{9mm "Glocker" Pistol (Auto)}
{13701}{}{An improved model of the "Glocker" pistol that can fire with bursts. Even more fun with a 9mm weapon. Min ST: 5}
{13800}{}{9mm Pistol}
{13801}{}{A basic average 9mm pistol. Nothing special about it. Min ST: 4}
{13900}{}{9mm Revolver}
{13901}{}{A very basic, hand-made 9mm revolver. Not very reliable. Min ST: 2}
{14000}{}{"Break" Stun Gun}
{14001}{}{A non-lethal pistol for self-defense. Quite a weak weapon, but it still can save your life. Min ST: 3}
{14100}{}{"Sting" Pistol}
{14101}{}{A pneumatic device for hurling poisonous darts at your adversaries. Min ST: 3}
{14200}{}{"Colt Python" Revolver}
{14201}{}{This one blows heads clean off! One of the most popular revolvers, made famous by starring in many detective noir movies of the '70s. Min ST: 6}
{14300}{}{"Optics" .223 Pistol}
{14301}{}{A technical wonder - a special custom-made pistol in .223 with an attached scope, which allows you to pick off your enemies at a distance with ease. Min ST: 4}
{14400}{}{Jackal's Revolver}
{14401}{}{The signature revolver of the Jackal himself. A nice gun to pop the heads of your enemies like melons. Min ST: 6}
{14500}{}{"SL-10" Laser Pistol}
{14501}{}{Compact and advanced version of the "SL-9" laser pistol. Light, fast and deadly! Powered by "MiniBat" energy cells. Min ST: 5}
{14600}{}{Pneumatic Pistol}
{14601}{}{A pistol that shoots small BB Pellets with the help of compressed air. The only suitable application for it is to shoot rodents. Min ST: 2}
{14700}{}{"Red Robin" Pistol}
{14701}{}{A pneumatic pistol, model "Red Robin". While it is the most powerful model of pneumatic guns, it doesn't count for much. Min ST: 3}
{14800}{}{Laser Cutter}
{14801}{}{An "Isaac Industries" laser cutting tool. Designed for cutting through unyielding rocks or soft organic tissue. Min ST: 5}
{14900}{}{Gun Placeholder}
{14901}{}{}
{15000}{}{"Helmuth" SMG}
{15001}{}{A "Helmuth" submachine gun that was widely used by the National Guard until 2002. Its main qualities are simplicity and reliability, as well as decent firepower. Min ST: 4}
{15100}{}{"Ghetto" SMG}
{15101}{}{In the personal mob of any mafia boss is at least one man with this gun. An inspiring look is half the power of this weapon: as soon as the enemy sees this piece, he immediately loses the desire to misbehave. Min ST: 5}
{15200}{}{"Cricket" SMG}
{15201}{}{A British submachine gun that was in service with the MI-6 operational special forces. Min ST: 4}
{15300}{}{"Vendetta" SMG}
{15301}{}{A favorite submachine gun of mafiosi and bandits. Light, small and lethal. What else to want? Min ST: 5}
{15400}{}{"FCP-10" SMG}
{15401}{}{An elite prototype of an assault submachine gun for the marines. A light, reliable and water-resistant deliverer of pain and suffering to every enemy of America! Min ST: 6}
{15500}{}{"Helmuth" SMG (Scoped)}
{15501}{}{A modified "Helmuth" submachine gun with an optical sight, to even better keep your enemies at bay. Min ST: 4}
{15600}{}{"Helmuth" SMG (Exp. Mag.)}
{15601}{}{A modified "Helmuth" SMG with an added magazine for even more bursting fun. Min ST: 5}
{15700}{}{"SL-9" Laser Pistol}
{15701}{}{One of the first successful models of Schwein's laser pistols. It is a bit heavy, but that is because it's more deadly than just a laser pointer! Min ST: 5}
{15800}{}{Plasma Pistol}
{15801}{}{A strong electromagnet disperses super-heated globs of plasma at a high rate of fire. It burns easily through metal, wood, stone, and - of course - living tissue. Min ST: 5}
{15900}{}{9mm Submachine Gun}
{15901}{}{A basic average SMG in 9mm, nothing special about it. Min ST: 6}
{16000}{}{"N17A1" Assault Rifle}
{16001}{}{An automatic rifle from the 90s of the twentieth century. A reliable thing - valuable in combat, easy to handle and maintain. Min ST: 6}
{16100}{}{"N17A1" Assault Rifle (Scoped)}
{16101}{}{A standard N17A1 with a scope attached, for even more long-range precision. Min ST: 6}
{16200}{}{Barrage Machinegun}
{16201}{}{A quite unique .223 modification of an old legendary Tommygun. It is rumored to have been in use by the mafia bosses of the east coast. Min ST: 7}
{16300}{}{Civilian Carbine}
{16301}{}{A very old model of a carbine, used in the pre-war period by hunters. Min ST: 5}
{16400}{}{"KLH74" Assault Rifle}
{16401}{}{A legendary rifle trophy from the old wars, manufactured in the United Empire of Russia. Min ST: 6}
{16500}{}{Assault Rifle}
{16501}{}{Just an assault rifle. Perfectly suitable for hunting small and medium-sized prey. Min ST: 6}
{16600}{}{"Hunter" Rifle}
{16601}{}{A hunting rifle for large animals. And humans. Min ST: 5}
{16700}{}{"Hunter" Rifle (Scoped)}
{16701}{}{A hunting rifle with an attached scope makes it easier to hunt from a distance, no matter what kind of game you're aiming for. Min ST: 5}
{16800}{}{Personal Assault Rifle}
{16801}{}{A personalized assault rifle. Min ST: 8}
{16900}{}{"Bulldog" Assault Rifle}
{16901}{}{A modern and decent assault rifle, named after the fact that it tears through enemies like a rabid dog through freshly killed prey. Min ST: 7}
{17000}{}{Sniper Rifle}
{17001}{}{A nice balanced rifle with an optical sight, good range, and perfect accuracy. What more does a sniper need? Min ST: 6}
{17100}{}{"Rainbow-6" Assault Rifle}
{17101}{}{An excellent assault rifle that was used by the pre-war special forces. Very reliable and precise. Min ST: 7}
{17200}{}{"Nail" Rifle}
{17201}{}{Despite the size of this rifle, this baby can cause quite a few problems for your opponents. Min ST: 4}
{17300}{}{"Lilith" Rifle}
{17301}{}{A very deadly sniper rifle that was used by many elite snipers. Has a very long range and stopping power. Min ST: 9}
{17400}{}{"Phobos" Shotgun}
{17401}{}{The automatic propellant gas rapid reloading system makes this shotgun a most dreadful experience for your enemies. Min ST: 7}
{17500}{}{Double-barreled Shotgun}
{17501}{}{A double-barreled hunting shotgun, ideal for unarmored targets. Min ST: 5}
{17600}{}{"Revengeton" Shotgun}
{17601}{}{A pump-action shotgun that was widely in use by the police against not-so-innocent civilians. It's in good condition. Min ST: 5}
{17700}{}{"Pocket" Shotgun}
{17701}{}{A small and comfortable civilian pump-action shotgun. Min ST: 4}
{17800}{}{Sawed-off Shotgun}
{17801}{}{A sawed-off shotgun is the most common weapon among small-time bandits, robbers, and other crooks. Min ST: 4}
{17900}{}{12 ga. Shotgun}
{17901}{}{A very basic civilian pump-action shotgun that was widely in use. Min ST: 5}
{18000}{}{"Wilderer" Shotgun}
{18001}{}{A big nasty revolving long-range shotgun for hunting large game. Min ST: 6}
{18100}{}{"Hardener" Shotgun}
{18101}{}{Looks more like a shotgun cannon than a normal shotgun. With a very long range to boot, it is among the most powerful ones. The downside is that it needs special 12 gauge cartridges. Min ST: 9}
{18200}{}{EMP Grenade Launcher}
{18201}{}{A grenade launcher for special 40mm EMP grenades, designed against robots and electronics. Min ST: 8}
{18300}{}{40mm Grenade Launcher}
{18301}{}{A grenade launcher for high explosive 40mm grenades against fortified targets. Min ST: 6}
{18400}{}{"Strike" Grenade Launcher}
{18401}{}{Grenades shot by this grenade launcher will suppress your enemies and penetrate their armor. Min ST: 7}
{18500}{}{"Hotter" Shotgun}
{18501}{}{This revolving shotgun fires special 12 gauge incendiary shells in the face of your enemies. Oh, and it has a burst mode too! Min ST: 5}
{18600}{}{Pneumatic Rifle}
{18601}{}{A rifle that shoots small BB Pellets with the help of compressed air. Has more power than the pistol versions. Min ST: 3}
{18700}{}{"Raven" Rifle}
{18701}{}{A decent rifle that shoots small BB Pellets. Even a wild jackal would not like to get hit by a bullet from this one. Min ST: 3}
{18800}{}{Repaired Rifle}
{18801}{}{A repaired and worn, but still a deadly weapon. Min ST: 5}
{18900}{}{Placeholder Rifle}
{18901}{}{}
{19000}{}{"Hurricane" Minigun}
{19001}{}{The portable six-barreled NCASTR minigun "Hurricane" is *the* weapon for suppressing your opponents. A 75,000 rounds per minute .223 rain of lead is unlikely to leave anything standing alive. Min ST: 8}
{19100}{}{"Heavy Rain" Minigun}
{19101}{}{Like its predecessor, the "Heavy Rain" minigun tears through enemies like they are sheets of wet paper. It is powerful enough to destroy barricades and armored vehicles. Min ST: 9}
{19200}{}{Turret Minigun}
{19201}{}{This gun, made by NCASTR for automated defense turrets, makes it very hard for anyone to sneak by. The cause of it is a nearly limitless 90,000 rounds per minute hail of bullets. Min ST: 10}
{19300}{}{"HMG-1A4" Flamelance}
{19301}{}{A rapid-fire flamethrower that shoots small balls of red-hot burning liquid out of six muzzles at a speed of 50,000 rounds per minute. Technically, it's more of a plasma minigun - but nobody seems to care, especially when everything around melts down at a searing 3000 degrees Celsius. Min ST: 8}
{19400}{}{Placeholder Minigun}
{19401}{}{}
{19500}{}{EMP Rocket Launcher}
{19501}{}{A rocket launcher for special EMP rockets, designed against robots and electronics. The strongest burst of electromagnetic impulse doesn't leave them any chance. Min ST: 7}
{19600}{}{"Crusader" Rocket Launcher}
{19601}{}{The NCASTR "Crusader" missile launcher fires surface-to-surface rockets. Sufficient power and accuracy ensure a high level of target destruction. Min ST: 8}
{19700}{}{Hand-made Rocket Launcher}
{19701}{}{A short-range single-shot rocket launcher... Basically, it's just a pipe with a trigger. Be extremely careful with this thing. Min ST: 7}
{19800}{}{Placeholder Rocket Launcher}
{19801}{}{Min ST: 7}
{19900}{}{"SnR" Rocket Launcher}
{19901}{}{An ultra-long-range rocket launcher of the "Shoot'n'Run" type. That means it is impossible to reload. Just throw it away after a single shot. Min ST: 6}
{20000}{}{Weapon 1}
{20001}{}{}
{20100}{}{Weapon 2}
{20101}{}{}
{20200}{}{Weapon 3}
{20201}{}{}
{20300}{}{Weapon 4}
{20301}{}{}
{20400}{}{Weapon 5}
{20401}{}{}
{20500}{}{Flashlight (on)}
{20501}{}{An old flashlight. It's turned on.}
{20600}{}{Dynamite (lit)}
{20601}{}{A stick of good old dynamite with a lit fuse.}
{20700}{}{Geiger Counter (active)}
{20701}{}{A vital tool in the wasteland. It determines the exposure of gamma and beta radiation. It's activated.}
{20800}{}{Motion Sensor}
{20801}{}{A motion sensor detects even the slightest movements over a long distance, using a tuned radar device. It's activated}
{20900}{}{Armed Explosives}
{20901}{}{A bundle of good old trinitrotoluene with a lit fuse.}
{21000}{}{Stealth Boy}
{21001}{}{A device that uses an electromagnetic field to create an invisibility effect around the user. It's activated.}
{21100}{}{EMP Grenade}
{21101}{}{This type of grenade is designed specifically for the destruction of electronics. Min ST: 5}
{21200}{}{WP Grenade}
{21201}{}{If you want to start a fire, this grenade is perfect. Min ST: 4}
{21300}{}{Rock}
{21301}{}{It's a rock. The "Granite-Inc." model. This one is an upgraded version. Min ST: 4}
{21400}{}{Molotov Cocktail}
{21401}{}{A good old homemade flammable grenade. Burns your enemies to the ground. Min ST: 5}
{21500}{}{HE Grenade}
{21501}{}{An ordinary high-explosive grenade. Min ST: 6}
{21600}{}{"Fist of God" Grenade}
{21601}{}{One of the strongest grenades, a secret military technology. Min ST: 7}
{21700}{}{Sawblade}
{21701}{}{Sharp teeth can easily cut through unprotected flesh. And it flies perfectly! Min ST: 6}
{21800}{}{Billiard Ball}
{21801}{}{Old, cracked, but weighty and with good flight characteristics. The ball may not kill anyone, but it will surely lead to some heavy bruises! Min ST: 2}
{21900}{}{Hand-made Grenade}
{21901}{}{A homemade grenade, dangerous for both the enemy and the thrower. Min ST: 5}
{22000}{}{Bandages}
{22001}{}{Inefficient, yet cheap and affordable. Bandages will not reconstitute your severed arm, but can help you heal the cut.}
{22100}{}{Painkiller}
{22101}{}{A couple of pills will reduce the pain, and - if you're lucky - heal minor wounds.}
{22200}{}{"Heal-Up"}
{22201}{}{Developed on the basis of an army painkiller, this injection is for personal use. Not cheap, but really essential for every person in the Radius.}
{22300}{}{"Surge"}
{22301}{}{A powerful military painkiller that heals even very deep wounds. It also increases strength and resistance to damage. Essential in battle!}
{22400}{}{"Poison-Out"}
{22401}{}{If you happened to be poisoned, take a couple of pills and you will not face death from bloody diarrhea!}
{22500}{}{Fruit Antidote}
{22501}{}{Maybe the smell from this bottle of hooch can knock you off your feet, but this folk remedy is really great in making you sweat out the poison!}
{22600}{}{"RadOut"}
{22601}{}{An injection that removes radioactive particles from your bloodstream. Unpleasant, but useful!}
{22700}{}{Wild Potion}
{22701}{}{Scorpion tails, rat claws, molerat scales. Thinking of all the things mixed in there makes you queasy, but this potion removes radiation even better than factory drugs!}
{22800}{}{"Radiom"}
{22801}{}{If you are going to toy around the core of a nuclear reactor, this miracle pill will help you not to burn out from inside. Take before exposure!}
{22900}{}{"Resistanol"}
{22901}{}{A military miracle remedy that covers the skin with hard scales, even a knife will not harm you! May cause itching and cancer.}
{23000}{}{"Combatid"}
{23001}{}{If you want to rush through combat causing mayhem and destruction, stock yourself up with a "Combatid". It does not only heal your wounds but also increases resistance to damage. Warning - a possibility of addiction with dangerous side effects.}
{23100}{}{"Brainiac"}
{23101}{}{No scientist can do without this nose spray! The composition of the drug allows to get it directly into the brain, revealing its dormant potential!}
{23200}{}{"Stronghold"}
{23201}{}{Nature didn't award you with muscles of steel? Never mind, "Stronghold" is always there to help you. Just rub the ointment into your muscles and start clobbering!}
{23300}{}{"Drop"}
{23301}{}{Break off the nozzle and pour the ampoule's content into your mouth - and in a second you will feel like a God!}
{23400}{}{Whiskey}
{23401}{}{Good old whiskey, with a nice bouquet and taste.}
{23500}{}{Cognac}
{23501}{}{A smooth and noble drink. If you smell of it, you certainly will be respected among your peers.}
{23600}{}{Booze}
{23601}{}{You aren't sure if this strong home-brewed hooch is meant to be used as a drink, or as a disinfectant.}
{23700}{}{Spot-Up}
{23701}{}{What's up? Spot-Up! There are legends about this soda, including some quite scary ones, but after one sip you will forget all your fears and doubts!}
{23800}{}{Apple}
{23801}{}{An old dry apple. Looks like it has some mold on its side.}
{23900}{}{Pear}
{23901}{}{A surprisingly delicious piece of dried pear.}
{24000}{}{Shotgun Repair Kit}
{24001}{}{A kit of spare parts for the maintenance and assembly of shotguns.}
{24100}{}{Rifle Repair Kit}
{24101}{}{A kit of spare parts for the maintenance and assembly of rifles and submachine guns.}
{24200}{}{Shovel}
{24201}{}{This item is equally convenient for both digging something up and burying someone down.}
{24300}{}{Rope}
{24301}{}{A coil of good, strong rope. Decide for yourself how to use it.}
{24400}{}{Screwdriver}
{24401}{}{A typical screwdriver. Useful tool both in repairing and in self-defense.}
{24500}{}{Silk Gloves}
{24501}{}{If you want to rob someone, this item of clothing will be very useful.}
{24600}{}{Energy Drink}
{24601}{}{Relieves fatigue, reduces drowsiness, helps to concentrate, and makes you cheerful!}
{24700}{}{Rad-O-meter}
{24701}{}{An indispensable assistant in the fight against radiation. If there is a nuclear war, take the Rad-O-meter with you!}
{24800}{}{Instrument}
{24801}{}{}
{24900}{}{Instrument}
{24901}{}{}
{25000}{}{Rusty Locker}
{25001}{}{Judge the locker not by its appearance, but by the content.}
{25100}{}{Rusty Locker}
{25101}{}{It is slightly askew, but it is unlikely that this affected its contents.}
{25200}{}{Rusty Locker}
{25201}{}{Even lying on the ground, this locker didn't stop being a locker.}
{25300}{}{the shelves}
{25301}{}{Old and dusty shelves with plenty of junk on them.}
{25400}{}{stuff}
{25401}{}{Surely, there might be something useful in such a large pile of stuff.}
{25500}{}{the boxes}
{25501}{}{Small boxes with unknown contents.}
{25600}{}{Tub}
{25601}{}{An old roomy bowl.}
{25700}{}{stuff}
{25701}{}{The abundance of things in that pile does not guarantee the presence of something valuable in it, but you are still curious.}
{25800}{}{stuff}
{25801}{}{A pile of stuff and boxes.}
{25900}{}{Machine}
{25901}{}{A small machine for working with different materials.}
{26000}{}{stuff}
{26001}{}{Usually, people store their stuff in places like this.}
{26100}{}{stuff}
{26101}{}{Usually, people store their stuff in places like this.}
{26200}{}{stuff}
{26201}{}{Usually, valuables don't pile up like this, but who knows - people are strange.}
{26300}{}{stuff}
{26301}{}{There is always some ambiguity in closed boxes.}
{26400}{}{stuff}
{26401}{}{Rummaging through a large pile of things is time-consuming. Sometimes it's worth it, sometimes not.}
{26500}{}{stuff}
{26501}{}{The abundance of things in that pile does not guarantee the presence of something valuable in it, but you are still curious.}
{26600}{}{a box}
{26601}{}{Usually, people keep their stuff in something like it.}
{26700}{}{a footlocker}
{26701}{}{A great place for storing items.}
{26800}{}{Table}
{26801}{}{The station administrator's desk.}
{26900}{}{the shelves}
{26901}{}{There's a lot of junk on these shelves.}
{27000}{}{stuff}
{27001}{}{Cartons, boxes, crates - all these made for storing things.}
{27100}{}{Firehose Box}
{27101}{}{You have always liked to set things on fire rather than putting it out.}
{27200}{}{Wall drawers}
{27201}{}{Be careful with them, it seems like these containers are very dilapidated.}
{27300}{}{Hood}
{27301}{}{A hood of a car, covered with obvious traces of corrosion.}
{27400}{}{Trunk}
{27401}{}{The trunk of an old car.}
{27500}{}{Car Door}
{27501}{}{A badly battered car door.}
{27600}{}{Car Door}
{27601}{}{A badly battered car door.}
{27700}{}{Trunk}
{27701}{}{The trunk of an old car.}
{27800}{}{Crate}
{27801}{}{Someone left a crate in the car.}
{27900}{}{Wall Safe}
{27901}{}{It looks shabby. You wonder if time has affected its reliability.}
{28000}{}{Wall Stash}
{28001}{}{Perhaps there was someone's stash in this hole.}
{28100}{}{Old Boxes}
{28101}{}{Crumpled and dirty boxes.}
{28200}{}{Dresser}
{28201}{}{An old chest of drawers made of the cracked, but still strong wood.}
{28300}{}{the shelves}
{28301}{}{The wooden shelves look empty, but maybe you are lucky?}
{28400}{}{Dresser}
{28401}{}{A broken wooden commode.}
{28500}{}{the shelves}
{28501}{}{Old broken wooden shelves. They seem to have served their time.}
{28600}{}{the shelves}
{28601}{}{Wooden shelves, designed to put things on them.}
{28700}{}{the shelves}
{28701}{}{The wooden shelves look empty, but maybe you are lucky?}
{28800}{}{the shelves}
{28801}{}{Old broken wooden shelves. They seem to have served their time.}
{28900}{}{Firehose Box}
{28901}{}{You have always liked to set things on fire rather than putting it out.}
{29000}{}{*Dad's Wrench*}
{29001}{}{A small adjustable pipe wrench in perfect condition.}
{29100}{}{Corn}
{29101}{}{A mouthwatering cob of corn.}
{29200}{}{Water Container}
{29201}{}{The water strongly smells of rotten meat.}
{29300}{}{*Bracket*}
{29301}{}{One of the parts for the pump valve filter.}
{29400}{}{*Filter*}
{29401}{}{One of the parts for the pump valve filter.}
{29500}{}{*Valve*}
{29501}{}{One of the parts for the pump valve filter.}
{29600}{}{Pump Valve Filter}
{29601}{}{Missing spare part for the broken water filtering unit.}
{29700}{}{Nuclear Moonshine}
{29701}{}{A bottle of extremely strong liquor. It glows in the dark!}
{29800}{}{*Douglas's Badge*}
{29801}{}{The shiny badge of the Seeker named Douglas.}
{29900}{}{*Encyclopedia*}
{29901}{}{A hand-written reference guide containing useful information about various life experiences.}
{30000}{}{*Plasma Rifle Prototype*}
{30001}{}{A prototype of the latest generation's plasma weapon. It may be the only copy.}
{30100}{}{*Ultra Repair Kit*}
{30101}{}{A quite serious repair kit. Within it, you can find probably almost everything you need for any repairs.}
{30200}{}{*Rapture*}
{30201}{}{One dose of the "Rapture" drug. Don't misuse it.}
{30300}{}{*Elevator Card 2B*}
{30301}{}{Elevator access card 2B.}
{30400}{}{*Voice Modulator*}
{30401}{}{A device for generating sound waves in the form of specified phrases that mimics a voice.}
{30500}{}{Bag of Fertilizer}
{30501}{}{A bag of organic fertilizer. Just a handful of this fertilizer, and the corn will grow fine and dandy.}
{30600}{}{*Whetstone*}
{30601}{}{This stone can be used to sharpen any edged weapon.}
{30700}{}{Chimera's Fang}
{30701}{}{The tooth - or rather, the fang - of the most dangerous creature in Radius, the Chimera! You are lucky that you were able to get it and keep all your limbs.}
{30800}{}{S-Virus Strain}
{30801}{}{A sealed ampoule containing a deadly virus. Be very careful with it!}
{30900}{}{Strange Book}
{30901}{}{At first glance, it is difficult to determine what kind of book it is. At the second, too.}
{31000}{}{Finger with a Ring}
{31001}{}{This finger once belonged to someone. There is a ring on it. Looks very expensive.}
{31100}{}{*Piece of a map*}
{31101}{}{This piece of paper is part of a map. This might even be useful.}
{31200}{}{*Piece of a map*}
{31201}{}{Part of a map. Find other pieces and solve the puzzle.}
{31300}{}{*Piece of a map*}
{31301}{}{This is a map, or more exactly the part of a map. To read it you need to find other pieces.}
{31400}{}{*Piece of a map*}
{31401}{}{A partial map of some area. Perhaps there are other pieces somewhere.}
{31500}{}{Sugar-coated Lavash Jerky}
{31501}{}{A juicy and delicious piece of sugar-coated Lavash jerky.}
{31600}{}{NWO Basement Key}
{31601}{}{A well-preserved key. Use it for its intended purpose.}
{31700}{}{*Machine Part*}
{31701}{}{One of the most important parts of the NWO's conveyor machinery.}
{31800}{}{*Constitution of 15 Rights*}
{31801}{}{The Livos Constitution for the Inhabitants of the New World, created by the Inhabitants for posterity. It may be useful to read it. Or not.}
{31900}{}{*Robotron Hand*}
{31901}{}{The electro-mechanical limb of a Robotron.}
{32000}{}{*Electric Motor*}
{32001}{}{A patched but working electric motor.}
{32100}{}{Broken Electric Motor}
{32101}{}{A faulty electric motor.}
{32200}{}{*Sassou Perfume*}
{32201}{}{Women's perfume with a wonderful gentle fragrance.}
{32300}{}{Crystal Water}
{32301}{}{A bottle of the purest water.}
{32400}{}{*Romantic Collection*}
{32401}{}{A CD with calm melodic romantic music.}
{32500}{}{*A Book on Wave Science*}
{32501}{}{A serious educational book on various wave science topics.}
{32600}{}{*Card Deck*}
{32601}{}{A deck of playing cards, 36 pieces. Coated in plastic.}
{32700}{}{*Glowing Ant Abdomen*}
{32701}{}{This ant's abdomen is unusually large and has a luminescent effect.}
{32800}{}{Human Flesh}
{32801}{}{A piece of human flesh. Wait a second... Yes, it's definitely human flesh.}
{32900}{}{Porn Disk}
{32901}{}{A disk with a XXX video, the author of this creation is unfortunately unknown.}
{33000}{}{Biology Access Card}
{33001}{}{An electronic access card for the "Institute of Organic Science" level.}
{33100}{}{Engineering Access Card}
{33101}{}{An electronic access card for the "Design and Engineering Bureau" level.}
{33200}{}{Physics Access Card}
{33201}{}{An electronic access card for the "Laboratories of Physical Science" level.}
{33300}{}{Õ2 Access Card}
{33301}{}{An electronic access card marked X2.}
{33400}{}{X1 Access Card}
{33401}{}{An electronic access card marked X1.}
{33500}{}{*Antiradine*}
{33501}{}{A vial with a strange, slightly bubbling murky liquid. It is not clear whether this remedy is produced in a factory or hand-made, but it is rumored to be an excellent cure for radiation.}
{33600}{}{Firewood}
{33601}{}{A huge armful of excellent wooden fuel for a nice cozy fire!}
{33700}{}{Scorpion Tail}
{33701}{}{The big fleshy tail of some poor scorpion.}
{33800}{}{*Plunger*}
{33801}{}{A stick with a rubber pump on the end. It can come in handy if you want to gently hit someone. It is also suitable for unclogging toilets.}
{33900}{}{Name Certificate}
{33901}{}{On a rotten piece of paper is illegibly written that "The bearer of this paper is INDEED a member of the GREAT and ANCIENT Schwein family."}
{34000}{}{Note from Douglas}
{34001}{}{Looks like a list of things Olympus needs.}
{34100}{}{*Spare Parts Kit*}
{34101}{}{A heavy box with a lot of hardware inside.}
{34200}{}{*Vibrator*}
{34201}{}{A polished, well-oiled device for relieving female tension.}
{34300}{}{Obedience syringe}
{34301}{}{A small chemical injection that causes chemically induced loyalty of whoever is injected to the person who administers. Seems to work only on specific organisms.}
{34400}{}{Canned Meat}
{34401}{}{Seems that the food was only recently canned. The meat inside might be a surprise, though.}
{34500}{}{Torn Note}
{34501}{}{Part of the text is missing, but you can make out the ending: "why you would need this, but the code for the console is 2358. And remember, Gray, we're in this together now!"}
{34600}{}{*Power Cell*}
{34601}{}{An incredibly heavy battery. You can't help but wonder what will happen if you hit it with a sledgehammer.}
{34700}{}{*Stem Cell Essence*}
{34701}{}{A jar with a viscous organic substance. It's probably better not to even know what it is made of.}
{34800}{}{*Servo-Actuator*}
{34801}{}{It looks like a motor of a rather complicated design. Partially covered with blood and skin particles.}
{34900}{}{Quest}
{34901}{}{}
{35000}{}{Quest}
{35001}{}{}
{35100}{}{Quest}
{35101}{}{}
{35200}{}{Quest}
{35201}{}{}
{35300}{}{Quest}
{35301}{}{}
{35400}{}{Quest}
{35401}{}{}
{35500}{}{Quest}
{35501}{}{}
{35600}{}{Quest}
{35601}{}{}
{35700}{}{Quest}
{35701}{}{}
{35800}{}{Quest}
{35801}{}{}
{35900}{}{Quest}
{35901}{}{}
{36000}{}{Quest}
{36001}{}{}
{36100}{}{Quest}
{36101}{}{}
{36200}{}{Quest}
{36201}{}{}
{36300}{}{Quest}
{36301}{}{}
{36400}{}{Quest}
{36401}{}{}
{36500}{}{Quest}
{36501}{}{}
{36600}{}{Quest}
{36601}{}{}
{36700}{}{Quest}
{36701}{}{}
{36800}{}{Quest}
{36801}{}{}
{36900}{}{Quest}
{36901}{}{}
{37000}{}{Quest}
{37001}{}{}
{37100}{}{Quest}
{37101}{}{}
{37200}{}{Quest}
{37201}{}{}
{37300}{}{Quest}
{37301}{}{}
{37400}{}{Quest}
{37401}{}{}
{37500}{}{Quest}
{37501}{}{}
{37600}{}{Quest}
{37601}{}{}
{37700}{}{Quest}
{37701}{}{}
{37800}{}{Quest}
{37801}{}{}
{37900}{}{Quest}
{37901}{}{}
{38000}{}{Jackal's Diary}
{38001}{}{A disk with a personal diary, travel notes, and other information regarding the Jackal.}
{38100}{}{Young's Research}
{38101}{}{Young's scientific work and research.}
{38200}{}{War Chronicle}
{38201}{}{Historical chronology of military operations.}
{38300}{}{Work in Renaissance}
{38301}{}{Report on the implementation and concerns about the use of Robotrons.}
{38400}{}{PD Alloy Research}
{38401}{}{Chemical analysis of a fundamentally new metal alloy.}
{38500}{}{Tartarus Directive}
{38501}{}{A collection of edicts distributed in Tartarus.}
{38600}{}{Schwein's Notes}
{38601}{}{The notes of the gunsmith Sebastian Schwein.}
{38700}{}{"Olympus" Promotion}
{38701}{}{Olympus! The greatest creation of mankind!}
{38800}{}{About the Lumeniers}
{38801}{}{Someone's diary about the experience of meeting the Lumeniers.}
{38900}{}{Recruit's Diary}
{38901}{}{A dusty, dirty disk from a nameless corpse.}
{39000}{}{Solar Gun}
{39001}{}{A unique pistol powered by solar energy, a great cost-effective weapon.}
{39100}{}{MCA "Predator"}
{39101}{}{A mechanized combat armor system from NCASTR. Only its developers may wear it!}
{39200}{}{SMG Parts}
{39201}{}{Spare parts for a submachine gun, still oiled.}
{39300}{}{*Personal Diary*}
{39301}{}{This is your personal diary for smart (and not so smart) thoughts. Try not to lose your mother's gift.}
{39400}{}{*Herald's Robes*}
{39401}{}{The thick fabric covers the layer of reliable military armor. The hood completely hides the face of the wearer.}
{39500}{}{Mr. Potato Strength}
{39501}{}{A collectible Potato Superman figurine! Rare and expensive! It will raise your strength!}
{39600}{}{Mr. Potato Perception}
{39601}{}{Feel the true power of the dark side with the collectible Potato Vader! Your power of perception increases!}
{39700}{}{Mr. Potato Endurance}
{39701}{}{A collectible human-alien-gorilla! This action figure will give you endurance.}
{39800}{}{Mr. Potato Charisma}
{39801}{}{As a real prince of the hearts, Potato Elvis will give you a bit of his charisma.}
{39900}{}{Mr. Potato Intelligence}
{39901}{}{A brainy genius should eat potatoes! The collectible Potato Nerd will make you a little smarter.}
{40000}{}{Mr. Potato Agility}
{40001}{}{Skillful as a potato bat, collectible Potato Batman will increase your agility!}
{40100}{}{Mr. Potato Luck}
{40101}{}{Fortuna loves potatoes. Keep the collectible Potato Rabbit with you for good luck!}
{40200}{}{Orange Chucky}
{40201}{}{The sparkling character of this comic book will quickly teach you the basics of self-defense and hand-to-hand combat.}
{40300}{}{Orange Pitcher}
{40301}{}{In this comic, the orange baseball player will teach you some throwing techniques, one of the most important skills in this world.}
{40400}{}{Annoying Orange}
{40401}{}{The orange babbler - that's our real hero! His witty phrases and ingenious examples can give you a lot of interesting information about communicating with people and beyond.}
{40500}{}{Grenade Launcher Module}
{40501}{}{}
{40600}{}{Minigun Module}
{40601}{}{}
{40700}{}{Laser module}
{40701}{}{}
{40800}{}{Field Medic Kit}
{40801}{}{Bandages, peroxide, painkillers - and it's not everything that can be found in this first aid kit.}
{40900}{}{Paramedic's bag}
{40901}{}{A salvage package of a paramedic - everything you need to provide quick and serious help.}
{41000}{}{Glass Marbles}
{41001}{}{Cute and smooth glass marbles. It feels very nice to roll them in your hands.}
{41100}{}{Rusty Screw}
{41101}{}{An old rusty screw. It's so rusty that you don't even want to pick it up.}
{41200}{}{Tattered book}
{41201}{}{You can still make out individual phrases, but it is not possible to fully understand what is written there.}
{41300}{}{Old Comic Book}
{41301}{}{It is quite interesting to look at the faded pictures, although there is no benefit from this.}
{41400}{}{Glass Bottle}
{41401}{}{An empty glass bottle. What would you like to fill it with?}
{41500}{}{Wooden Comb}
{41501}{}{A tool for grooming - if you still have hair left on your head.}
{41600}{}{Children's Drawing}
{41601}{}{A crude child's drawing. A questionable art.}
{41700}{}{Children's Drawing}
{41701}{}{What is drawn here? The apocalypse?}
{41800}{}{Children's Drawing}
{41801}{}{If you can call this multicolored smudge a drawing.}
{41900}{}{Metal Fork}
{41901}{}{The fork is in good condition. You can eat with it, or poke yourself in the eye.}
{42000}{}{Rusty Fork}
{42001}{}{A rusty fork, does anyone really eat with this?}
{42100}{}{Nails}
{42101}{}{Some rather long nails.}
{42200}{}{Matches}
{42201}{}{Matches are not a toy for children! Hey, they still light up!}
{42300}{}{Yarn Spool}
{42301}{}{If you are into sewing, this spool of robust thread will definitely make you very happy.}
{42400}{}{Crayons}
{42401}{}{Quite rare, but useless item. You could leave some rock paintings somewhere.}
{42500}{}{Metal Plate}
{42501}{}{Obviously, you can eat soup from this. Or porridge.}
{42600}{}{Rusty Plate}
{42601}{}{Looking at several layers of rust, it's hard to imagine HOW you can eat from it.}
{42700}{}{Iron Plates}
{42701}{}{A few iron plates, almost untouched by rust.}
{42800}{}{72% Soap}
{42801}{}{Don't eat it!!!}
{42900}{}{Old Spork}
{42901}{}{The most ingenious invention of mankind, the spork. Half spoon, halt fork, and his own best friend!}
{43000}{}{Metal Spoon}
{43001}{}{You can eat with it. Or dig a grave for a rat.}
{43100}{}{Metal Cup}
{43101}{}{A container to drink liquids out of. If you don't want to use your hands.}
{43200}{}{Stamp}
{43201}{}{An old stamp with the letters "NCASTR" on it. If you slap it on your forehead, it will leave a nice marking.}
{43300}{}{Torn Rag}
{43301}{}{It's just a piece of blue rag. You have not seen rags of other colors.}
{43400}{}{Candy}
{43401}{}{A delicious and quite rare treat. If you eat it, it may seem that everything is not so bad.}
{43500}{}{Paint}
{43501}{}{An old can of oil paint. You could paint a wall.}
{43600}{}{Lavash Skin}
{43601}{}{The tanned skin of Lavash can be used to make leather items.}
{43700}{}{*Tin Roll*}
{43701}{}{A reel of rolled up five millimeters thick metal sheets.}
{43800}{}{Tin can}
{43801}{}{An old rusty tin can.}
{43900}{}{Dried Leaves}
{43901}{}{A couple of handfuls of dried leaves. Excellent fertilizer!}
{44000}{}{Ash}
{44001}{}{A handful of wood ash.}
{44100}{}{*Dried Cheese*}
{44101}{}{A piece of very old parmesan cheese. However, it has already dried to the state of the wood.}
{44200}{}{Lavash Meat}
{44201}{}{A piece of raw and fresh Lavash meat, juicy and rich in protein.}
{44300}{}{Sugar}
{44301}{}{A pack of sugar. Although old age and dampness made it hard as a rock, it's still as sweet as before.}
{44400}{}{Sex Pill}
{44401}{}{}
{44500}{}{Seedy Disk}
{44501}{}{Sounds like someone's amateur fan-fiction.}
{44600}{}{Scientific Report}
{44601}{}{A label on the side reads "The Gamma Project"}
{44700}{}{Dinosaur Figurine}
{44701}{}{The owner probably loved this toy.}
{44800}{}{Annotated Book}
{44801}{}{The cover says "Bible". A lot of passages are marked, annotated and many words have been crossed out or corrected.}
{44900}{}{Item}
{44901}{}{}
{45000}{}{Item}
{45001}{}{}
{45100}{}{Item}
{45101}{}{}
{45200}{}{Item}
{45201}{}{}
{45300}{}{Item}
{45301}{}{}
{45400}{}{Item}
{45401}{}{}
{45500}{}{Item}
{45501}{}{}
{45600}{}{Item}
{45601}{}{}
{45700}{}{Item}
{45701}{}{}
{45800}{}{Item}
{45801}{}{}
{45900}{}{Item}
{45901}{}{}
{46000}{}{Item}
{46001}{}{}
{46100}{}{Item}
{46101}{}{}
{46200}{}{Item}
{46201}{}{}
{46300}{}{Item}
{46301}{}{}
{46400}{}{Item}
{46401}{}{}
{46500}{}{Item}
{46501}{}{}
{46600}{}{Item}
{46601}{}{}
{46700}{}{Item}
{46701}{}{}
{46800}{}{Item}
{46801}{}{}
{46900}{}{Item}
{46901}{}{}
{47000}{}{Item}
{47001}{}{}
{47100}{}{Item}
{47101}{}{}
{47200}{}{Item}
{47201}{}{}
{47300}{}{Item}
{47301}{}{}
{47400}{}{Item}
{47401}{}{}
{47500}{}{Item}
{47501}{}{}
{47600}{}{Item}
{47601}{}{}
{47700}{}{Item}
{47701}{}{}
{47800}{}{Item}
{47801}{}{}
{47900}{}{Item}
{47901}{}{}
{48000}{}{Item}
{48001}{}{}
{48100}{}{Item}
{48101}{}{}
{48200}{}{Item}
{48201}{}{}
{48300}{}{Hintbook}
{48301}{}{Well, THIS would have been good to have at the beginning of this goddamn game.}
{48400}{}{Moonshine Tray}
{48401}{}{Made from plastic and lovingly glued together by Smitty, the tray is for his Magical Moonshine Machine.}
{48500}{}{Rusty Grate}
{48501}{}{An old rusty grate. After touching it, red paint remains on the fingers.}
{48600}{}{Moonshine Filter}
{48601}{}{A simple filter for the moonshine distiller. Installing it would reduce the consumption of rare candies.}
{48700}{}{Jackal Grip}
{48701}{}{The grip of the Jackal Revolver, find the rest of the parts, and build yourself a great gun.}
{48800}{}{Jackal Barrel}
{48801}{}{The barrel of the Jackal Revolver, find the rest of the parts, and build yourself a great gun.}
{48900}{}{Jackal Drum}
{48901}{}{The drum of the Jackal Revolver, find the rest of the parts, and build yourself a great gun.}
{49000}{}{Plasma Module}
{49001}{}{}
{49100}{}{Machinegun Module}
{49101}{}{}
{49200}{}{Item}
{49201}{}{}
{49300}{}{Item}
{49301}{}{}
{49400}{}{Item}
{49401}{}{}
{49500}{}{Item}
{49501}{}{}
{49600}{}{Item}
{49601}{}{}
{49700}{}{Item}
{49701}{}{}
{49800}{}{Item}
{49801}{}{}
{49900}{}{Item}
{49901}{}{}
{50000}{}{Item}
{50001}{}{}
{50100}{}{Item}
{50101}{}{}
{50200}{}{Item}
{50201}{}{}
{50300}{}{Item}
{50301}{}{}
{50400}{}{Item}
{50401}{}{}
{50500}{}{Item}
{50501}{}{}
{50600}{}{Item}
{50601}{}{}
{50700}{}{Item}
{50701}{}{}
{50800}{}{Item}
{50801}{}{}
{50900}{}{Item}
{50901}{}{}
{51000}{}{Item}
{51001}{}{}
{51100}{}{Item}
{51101}{}{}
{51200}{}{Item}
{51201}{}{}
{51300}{}{D.E.U.S. Weapon}
{51301}{}{This is a unique weapon, its owner was one of the "Gods" of Olympus!}
{51400}{}{Chimera's Horn}
{51401}{}{A trophy from the Chimera's corpse, you can use it as a weapon.}
{51500}{}{Chimera's Claw}
{51501}{}{A claw of the Chimera. Dangerous stuff in battle.}
{51600}{}{Chimera's Fang}
{51601}{}{You could make a necklace out of these fangs. Or even a knife!}
{51700}{}{Sharp Fang}
{51701}{}{This jackal was clearly not eager to share this tooth with you. Appreciate it as its former owner did.}
{51800}{}{Molerat's Fang}
{51801}{}{The sharp fang of a creepy molerat.}
{51900}{}{Ursa Fang}
{51901}{}{Ursa doesn't like to part with their teeth very much, so whoever got this one is a brave man. Or not a man at all.}
{52000}{}{Ursa Claw}
{52001}{}{Ursa claws are not uncommon, but they are still worth something. Sharp and dangerous! You can rip open a couple of throats.}
{52100}{}{Rat Fang}
{52101}{}{Rats are not uncommon in these parts, so you can collect a few dozen of these if you want.}
{52200}{}{Stinger}
{52201}{}{From the stinger of a scorpion, you can get a sample of its venom, which is very useful in making an antidote. Or you can just use it as a weapon.}
{52300}{}{Onca's Fang}
{52301}{}{The owner of such a trophy can be proud of himself. The sale is very profitable, and it's also very useful as a melee weapon.}
{52400}{}{Claw}
{52401}{}{The Onca's Claw is an excellent melee weapon.}
{52500}{}{the shelves}
{52501}{}{Wooden shelves with some junk on them.}
{52600}{}{the shelves}
{52601}{}{Wooden shelves, very convenient for storing things.}
{52700}{}{the shelves}
{52701}{}{Wooden shelves, very convenient for storing things.}
{52800}{}{a desk}
{52801}{}{A wooden desk with drawers.}
{52900}{}{a desk}
{52901}{}{A wooden desk with drawers.}
{53000}{}{the boxes}
{53001}{}{You can't help but wonder about the origin of these strange brown spots on the boxes.}
{53100}{}{the boxes}
{53101}{}{You can't help but wonder about the origin of these strange brown spots on the boxes.}
{53200}{}{stuff}
{53201}{}{Have you ever been told that it's not good to go through other people's belongings?}
{53300}{}{stuff}
{53301}{}{Have you ever been told that it's not good to go through other people's belongings?}
{53400}{}{Junk}
{53401}{}{Sometimes there's something useful in the junk.}
{53500}{}{Junk}
{53501}{}{Sometimes there's something useful in the junk.}
{53600}{}{stuff}
{53601}{}{Rummaging through other people's stuff can get you a hard piece of steel through your ribs very quickly. Better be discreet about it.}
{53700}{}{Junk}
{53701}{}{Some random stuff, nothing worth looking at.}
{53800}{}{a terminal with a desk}
{53801}{}{You're curious why they have two monitors here.}
{53900}{}{a safe}
{53901}{}{Safes were designed to hide something in them. From people like you.}
{54000}{}{a locker}
{54001}{}{A metal storage cabinet.}
{54100}{}{a locker}
{54101}{}{A metal storage cabinet.}
{54200}{}{a locker}
{54201}{}{A metal storage cabinet.}
{54300}{}{a locker}
{54301}{}{A metal storage cabinet.}
{54400}{}{a locker}
{54401}{}{A metal cabinet, rather rusty.}
{54500}{}{a locker}
{54501}{}{A metal cabinet, rather rusty.}
{54600}{}{a locker}
{54601}{}{A rusty metal cabinet, which is also pretty dented.}
{54700}{}{the cabinet}
{54701}{}{The lack of doors usually does not prevent storing all sorts of things in these drawers.}
{54800}{}{the cabinet}
{54801}{}{The lack of doors usually does not prevent storing all sorts of things in these drawers.}
{54900}{}{a makeshift crate}
{54901}{}{The person who built the box obviously cared little for its aesthetic properties.}
{55000}{}{a makeshift crate}
{55001}{}{The person who built the box obviously cared little for its aesthetic properties.}
{55100}{}{a sturdy crate}
{55101}{}{A solid homemade box. It can be used as a bench, but there's a risk of getting a splinter in the ass.}
{55200}{}{a sturdy crate}
{55201}{}{A solid homemade box. It can be used as a bench, but there's a risk of getting a splinter in the ass.}
{55300}{}{a part of a car}
{55301}{}{There may well be something interesting there.}
{55400}{}{stuff}
{55401}{}{The presence of a box with unknown contents in this junk arouses your curiosity.}
{55500}{}{stuff}
{55501}{}{The presence of a box with unknown contents in this junk arouses your curiosity.}
{55600}{}{a box}
{55601}{}{Usually, people use boxes to put things in them.}
{55700}{}{a safe}
{55701}{}{Safes were designed to hide something in them. From people like you.}
{55800}{}{a safe}
{55801}{}{Safes were designed to hide something in them. From people like you.}
{55900}{}{Cupboard}
{55901}{}{A dirty old cupboard.}
{56000}{}{a box}
{56001}{}{Usually, people use boxes to put things in them.}
{56100}{}{a box}
{56101}{}{Usually, people use boxes to put things in them.}
{56200}{}{the shelves}
{56201}{}{Judging by the fresh bloodstains, some poor guy has been very unlucky here recently.}
{56300}{}{a container}
{56301}{}{Judging by the fresh bloodstains, some poor guy has been very unlucky here recently.}
{56400}{}{a locker}
{56401}{}{Its contents should definitely be examined.}
{56500}{}{a box}
{56501}{}{A large, slightly opened box. Its contents are slightly visible.}
{56600}{}{Cupboard}
{56601}{}{People usually store something in them, and that's what they were invented for.}
{56700}{}{the shelves}
{56701}{}{The abundance of things on the shelves encourages you to explore them.}
{56800}{}{Casket}
{56801}{}{These laser beams can easily cut off your arm, but you are not eager to test it.}
{56900}{}{a safe}
{56901}{}{Helps its owner to hide his belongings from the overtly curious. Yes, that means you!}
{57000}{}{a box}
{57001}{}{A half-open box begs for a look at its contents.}
{57100}{}{the shelves}
{57101}{}{Wall-mounted shelves are usually used to store things.}
{57200}{}{the shelves}
{57201}{}{Wall-mounted shelves are usually used to store things.}
{57300}{}{Personal Locker}
{57301}{}{This is very convenient to store personal items and more here.}
{57400}{}{a locker}
{57401}{}{A metal cabinet with a door.}
{57500}{}{a footlocker}
{57501}{}{A metal box, which perfectly protects things from adverse external influences.}
{57600}{}{a footlocker}
{57601}{}{A metal box, which perfectly protects things from adverse external influences.}
{57700}{}{a wardrobe}
{57701}{}{If you are asked why you got into someone else's closet, answer that you were looking for a dimension door to a fairy-tale world.}
{57800}{}{a wardrobe}
{57801}{}{If you are asked why you got into someone else's closet, answer that you were looking for a dimension door to a fairy-tale world.}
{57900}{}{the shelves}
{57901}{}{The abundance of things on the shelves encourages you to explore them.}
{58000}{}{the shelves}
{58001}{}{The abundance of things on the shelves encourages you to explore them.}
{58100}{}{the shelves}
{58101}{}{The abundance of things on the shelves encourages you to explore them.}
{58200}{}{a locker}
{58201}{}{A metal cabinet with a door.}
{58300}{}{a container}
{58301}{}{}
{58400}{}{a container}
{58401}{}{}
{58500}{}{a container}
{58501}{}{}
{58600}{}{a container}
{58601}{}{}
{58700}{}{a container}
{58701}{}{}
{58800}{}{a container}
{58801}{}{}
{58900}{}{a container}
{58901}{}{}
{59000}{}{a container}
{59001}{}{}
{59100}{}{a container}
{59101}{}{}
{59200}{}{a container}
{59201}{}{}
{59300}{}{a container}
{59301}{}{}
{59400}{}{a container}
{59401}{}{}
{59500}{}{a rat hole}
{59501}{}{It's large, deep, and there must be someone living in it.}
{59600}{}{a grave}
{59601}{}{Someone's grave.}
{59700}{}{a grave}
{59701}{}{There must be someone lying there.}
{59800}{}{a grave}
{59801}{}{It is possible that there is something to gain there.}
{59900}{}{a grave}
{59901}{}{You don't care about the Gravedigger's reputation, do you?}
{60000}{}{a grave}
{60001}{}{Don't even try to dig it up.}
{60100}{}{a grave}
{60101}{}{Where is the shovel...}