{100}{}{Fire}
{101}{}{The flames light up space around them.}
{200}{}{Door}
{201}{}{An old and battered metal door.}
{300}{}{Trash Can}
{301}{}{A too-small container in the fights against littering.}
{400}{}{Wooden Table}
{401}{}{An old table with a dirty tablecloth.}
{500}{}{Metal Barrel}
{501}{}{An old steel barrel.}
{600}{}{Metal Barrel}
{601}{}{An old empty steel barrel.}
{700}{}{Tires}
{701}{}{A stack of old rubber tires.}
{800}{}{Wall}
{801}{}{This section of the wall stands out.}
{900}{}{Terminal}
{901}{}{A calculator terminal.}
{1000}{}{Terminal}
{1001}{}{A calculator terminal.}
{1100}{}{Calculator}
{1101}{}{A calculator terminal is hooked to a mainframe.}
{1200}{}{Calculator}
{1201}{}{A calculator terminal is hooked to a mainframe.}
{1300}{}{Terminal}
{1301}{}{A calculator terminal.}
{1400}{}{Terminal}
{1401}{}{A calculator terminal.}
{1500}{}{Bull Head}
{1501}{}{Looks like this head of a Lavash is really happy to be canned.}
{1600}{}{Tires}
{1601}{}{Hardened old tires covered in sand.}
{1700}{}{Pit}
{1701}{}{A shallow indention in the ground.}
{1800}{}{Door}
{1801}{}{A high-tech metal door.}
{1900}{}{Door}
{1901}{}{A high-tech metal door.}
{2000}{}{Battery}
{2001}{}{A big and old empty battery.}
{2100}{}{Tire}
{2101}{}{A useless old tire.}
{2200}{}{Huge Statue}
{2201}{}{You read somewhere that it depicts Themis, the Goddess of Justice.}
{2300}{}{Door}
{2301}{}{A high-tech metal door.}
{2400}{}{Tire}
{2401}{}{A useless old tire.}
{2500}{}{Monitor}
{2501}{}{A large wall-mounted monitor.}
{2600}{}{Monitor}
{2601}{}{A large wall-mounted monitor.}
{2700}{}{Tire}
{2701}{}{A hardened old tire, not worth digging up.}
{2800}{}{Rocks}
{2801}{}{A pile of round stones.}
{2900}{}{Junk}
{2901}{}{It used to be a large important part of a machine, now it's just useless junk.}
{3000}{}{Monitor}
{3001}{}{A large wall-mounted monitor.}
{3100}{}{Monitor}
{3101}{}{A large wall-mounted monitor.}
{3200}{}{Vent}
{3201}{}{A part of the ventilation system.}
{3300}{}{Vent}
{3301}{}{A part of the ventilation system.}
{3400}{}{Bed}
{3401}{}{A very dirty bed. Your own in Tartarus is way much cleaner.}
{3500}{}{Bed}
{3501}{}{A very dirty bed. Your own in Tartarus is way much cleaner.}
{3600}{}{Bed}
{3601}{}{A very dirty bed. Your own in Tartarus is way much cleaner.}
{3700}{}{Bed}
{3701}{}{A dirty bed. Your own in Tartarus way is much cleaner.}
{3800}{}{Elevator}
{3801}{}{This is a service elevator.}
{3900}{}{Chair}
{3901}{}{A chair with armrests. It looks comfortable.}
{4000}{}{Chair}
{4001}{}{A chair with armrests. It looks comfortable.}
{4100}{}{Chair}
{4101}{}{A chair with armrests. It looks comfortable.}
{4200}{}{Chair}
{4201}{}{A chair with armrests. It looks comfortable.}
{4300}{}{Junk}
{4301}{}{Completely useless junk.}
{4400}{}{Junk}
{4401}{}{Nothing worth finding here.}
{4500}{}{Junk}
{4501}{}{Some metal fragments and old crates. It's scarcely usable.}
{4600}{}{Junk}
{4601}{}{Nothing worth finding here.}
{4700}{}{Chair}
{4701}{}{Better not to use it for its intended purpose, it looks like it's going to fall apart.}
{4800}{}{Chair}
{4801}{}{Better not to use it for its intended purpose, it looks like it's going to fall apart.}
{4900}{}{Exit Grid Map Marker}
{4901}{}{Exit Grid Map Marker}
{5000}{}{Well}
{5001}{}{An old dried-out well.}
{5100}{}{Chair}
{5101}{}{A common chair with armrests.}
{5200}{}{Chair}
{5201}{}{A common chair with armrests.}
{5300}{}{Chair}
{5301}{}{A common chair with armrests.}
{5400}{}{Chair}
{5401}{}{A common chair with armrests.}
{5500}{}{Vent Grill}
{5501}{}{A part of the ventilation system.}
{5600}{}{Vent Grill}
{5601}{}{A part of the ventilation system.}
{5700}{}{Chair}
{5701}{}{There is nothing unusual about this chair.}
{5800}{}{Chair}
{5801}{}{There is nothing unusual about this chair.}
{5900}{}{Chair}
{5901}{}{There is nothing unusual about this chair.}
{6000}{}{Chair}
{6001}{}{There is nothing unusual about this chair.}
{6100}{}{Table}
{6101}{}{It looks old and scratched.}
{6200}{}{Table}
{6201}{}{It looks old and scratched.}
{6300}{}{Cactus}
{6301}{}{A small cactus with large spines.}
{6400}{}{Cactus}
{6401}{}{You've heard that cacti make good tequila.}
{6500}{}{Cactus}
{6501}{}{Green and very prickly.}
{6600}{}{Door}
{6601}{}{A broken metal door.}
{6700}{}{Secret Blocking Hex}
{6701}{}{Help! I was kidnapped and forced to describe objects!}
{6800}{}{an entrance}
{6801}{}{An entrance to the factory building.}
{6900}{}{Stalagmite}
{6901}{}{A natural extension of the rock floor.}
{7000}{}{Stalagmite}
{7001}{}{A natural extension of the rock floor.}
{7100}{}{Crevice}
{7101}{}{A deep fissure in the ground.}
{7200}{}{Rock Column}
{7201}{}{This thick column of rock extends from floor to ceiling.}
{7300}{}{Rock Column}
{7301}{}{This thin column of rock extends from floor to ceiling.}
{7400}{}{Rocks}
{7401}{}{You study the rocks for a while, but they never move.}
{7500}{}{Rocks}
{7501}{}{You keep a close eye on these rocks, in case they move to attack you.}
{7600}{}{Waterflow}
{7601}{}{An underground river, that goes into the bowels of the cave. You can't see anything in the dark.}
{7700}{}{Gate}
{7701}{}{A wooden gate.}
{7800}{}{Rocks}
{7801}{}{A large pile of rocks. They look indigenous to this region.}
{7900}{}{Rocks}
{7901}{}{A small pile of rocks.}
{8000}{}{Rocks}
{8001}{}{A small pile of rocks.}
{8100}{}{Rocks}
{8101}{}{A large pile of rocks.}
{8200}{}{Hole}
{8201}{}{A small hole in the ground, very unlikely to fall in.}
{8300}{}{Hole}
{8301}{}{A small hole in the ground, very unlikely to fall in.}
{8400}{}{Crack}
{8401}{}{A quite deep cut in the ground.}
{8500}{}{Cracks}
{8501}{}{Several cracks in the ground.}
{8600}{}{Crack}
{8601}{}{A quite deep cut in the ground.}
{8700}{}{Gates}
{8701}{}{Wooden gates, they open and close.}
{8800}{}{Gate}
{8801}{}{A wooden gate.}
{8900}{}{Gate}
{8901}{}{A wooden gate.}
{9000}{}{Merchant Shop}
{9001}{}{You can buy armor or weapons here.}
{9100}{}{Merchant Shop}
{9101}{}{You can buy armor or weapons here.}
{9200}{}{Rocks}
{9201}{}{Rocks, rocks, rocks! Everywhere you look, rocks!}
{9300}{}{Lamp}
{9301}{}{A source of lighting.}
{9400}{}{Lamp}
{9401}{}{A source of lighting.}
{9500}{}{Seat}
{9501}{}{It was once a car seat.}
{9600}{}{Seat}
{9601}{}{It was once a car seat. Looks dirty and uncomfortable.}
{9700}{}{Seat}
{9701}{}{It was once a car seat. Looks dirty and uncomfortable.}
{9800}{}{Seat}
{9801}{}{It was once a car seat.}
{9900}{}{Couch}
{9901}{}{A very dirty and smelly couch you don't want to sit on.}
{10000}{}{Couch}
{10001}{}{A very dirty and smelly couch you don't want to sit on.}
{10100}{}{Plants}
{10101}{}{Rocks among some bushes.}
{10200}{}{Shrub}
{10201}{}{A dried outтравянистое растение.}
{10300}{}{Shrub}
{10301}{}{Some sort of desert weed.}
{10400}{}{Shrub}
{10401}{}{A dry herbaceous plant.}
{10500}{}{Shrub}
{10501}{}{A dry herbaceous plant.}
{10600}{}{Shrub}
{10601}{}{A dry herbaceous plant.}
{10700}{}{Shrub}
{10701}{}{Some sort of desert weed.}
{10800}{}{Shrub}
{10801}{}{A dry herbaceous plant.}
{10900}{}{Shrub}
{10901}{}{A dry herbaceous plant.}
{11000}{}{Shrub}
{11001}{}{Some sort of desert weed.}
{11100}{}{Bush}
{11101}{}{Some sort of desert weed.}
{11200}{}{Bush}
{11201}{}{A small, completely dry bush.}
{11300}{}{Bush}
{11301}{}{A small, completely dry bush.}
{11400}{}{Bush}
{11401}{}{Типичный представитель Herba Vulgaris.}
{11500}{}{Bush}
{11501}{}{A typical representative of Herba Vulgaris.}
{11600}{}{Bush}
{11601}{}{A typical representative of Herba Vulgaris.}
{11700}{}{Plant}
{11701}{}{A typical representative of Herba Vulgaris.}
{11800}{}{Plant}
{11801}{}{A dry bush}
{11900}{}{Cactus}
{11901}{}{It's amazing how tall these cacti grow.}
{12000}{}{Rocks}
{12001}{}{A pile of rocks.}
{12100}{}{Rocks}
{12101}{}{You could fry eggs on these stones.}
{12200}{}{Rock}
{12201}{}{You look carefully, but it's just an ordinary stone.}
{12300}{}{Rocks}
{12301}{}{A couple of rocks.}
{12400}{}{Rocks}
{12401}{}{A pile of rocks.}
{12500}{}{Human Bones}
{12501}{}{You look at them for a while and think about the impermanence of existence.}
{12600}{}{Bones}
{12601}{}{The skeleton of some poor guy.}
{12700}{}{Bones}
{12701}{}{You'll be nothing but a pile of bones someday, too.}
{12800}{}{Blocking Hex (NoLight)}
{12900}{}{Wall}
{12901}{}{A damaged section of the wall.}
{13000}{}{Wall}
{13001}{}{A damaged section of the wall.}
{13100}{}{Wall}
{13200}{}{Wall}
{13201}{}{A damaged section of the wall.}
{13300}{}{Wall}
{13400}{}{Wall}
{13500}{}{Energy Generator}
{13501}{}{It's a big, complicated machine, probably relates to electricity.}
{13600}{}{Wall}
{13601}{}{A damaged section of the wall.}
{13700}{}{Chair}
{13701}{}{This chair is ruined.}
{13800}{}{Chair}
{13801}{}{This chair is ruined.}
{13900}{}{Ladder}
{13901}{}{It's an old, fairly rickety ladder. It looks like it will barely support your weight.}
{14000}{}{Trapdoor}
{14001}{}{An outside hatch that leads down.}
{14100}{}{Light Source}
{14200}{}{Door}
{14201}{}{A strong metal door.}
{14300}{}{Door}
{14301}{}{A rusty but still sturdy metal door.}
{14400}{}{Cover}
{14401}{}{A heavy manhole cover. It seems to be well-preserved.}
{14500}{}{Stuff}
{14501}{}{A huge, promising pile of junk. And absolutely nothing useful... what a disappointment!}
{14600}{}{Stuff}
{14601}{}{You wonder how in such a big pile of things can be nothing of value at all.}
{14700}{}{Wall}
{14800}{}{Wall}
{14900}{}{Wall}
{15000}{}{Wall}
{15100}{}{Metal Rod}
{15101}{}{A thick, rusty metal rod.}
{15200}{}{Metal Rod}
{15201}{}{A broken metal rod. It takes a lot of strength to break one.}
{15300}{}{Metal Rod}
{15301}{}{A thick rusty metal rod.}
{15400}{}{Metal Rod}
{15401}{}{A broken metal rod. It takes a lot of strength to break one.}
{15500}{}{Old Poster}
{15501}{}{On the poster, a pretty lab assistant warns you to close the cage.}
{15600}{}{Metal Rod}
{15601}{}{A broken metal rod. It takes a lot of strength to break one.}
{15700}{}{Table}
{15701}{}{There's a dirty rag on the table.}
{15800}{}{Grass}
{15801}{}{Some dry grass.}
{16000}{}{Shrub}
{16001}{}{A common desert shrub.}
{16100}{}{Shrub}
{16101}{}{A common desert shrub.}
{16200}{}{Boat}
{16201}{}{An old, half-broken rusty boat.}
{16300}{}{Pickup Truck}
{16301}{}{It was once an excellent vehicle.}
{16400}{}{Motorcycle}
{16401}{}{You dream of riding this - but, unfortunately, this one is broken.}
{16500}{}{Motorcycle}
{16501}{}{You dream of riding this - but, unfortunately, this one is broken.}
{16600}{}{Bush}
{16601}{}{Some desert plant.}
{16700}{}{Bush}
{16701}{}{Some desert plant.}
{16800}{}{Bush}
{16801}{}{Some desert plant.}
{16900}{}{Motorcycle}
{16901}{}{You dream of riding this - but, unfortunately, this one is broken.}
{17000}{}{Flag}
{17001}{}{The old flag of the USA.}
{17100}{}{Jukebox}
{17101}{}{It doesn't seem to be able to produce sound anymore.}
{17200}{}{Rainbow Pharmaceuticals}
{17201}{}{There used to be a pharmaceutical company with that name around here.}
{17300}{}{Firepit}
{17301}{}{The fire went out a long time ago.}
{17400}{}{Wall}
{17401}{}{A damaged wall.}
{17500}{}{Billboard}
{17501}{}{It is impossible to read what was written on it.}
{17600}{}{Floor}
{17700}{}{Floor}
{17800}{}{Lighting}
{17900}{}{Lighting}
{18000}{}{Couch}
{18001}{}{Or at least it once was a couch, now it's just junk.}
{18100}{}{Couch}
{18101}{}{The best years of this couch are clearly in the very distant past.}
{18200}{}{Guitar}
{18201}{}{A battered musical instrument. Looks too complicated for you.}
{18300}{}{Powerful Battery}
{18301}{}{Surprisingly, there is still some charge left, and this thing can be repaired.}
{18400}{}{Stuff}
{18401}{}{It looks like these boxes have already been searched by somebody before you.}
{18500}{}{Stuff}
{18501}{}{It's amazing what useless junk people can cram into boxes and store.}
{18600}{}{Bed}
{18601}{}{The bed is in a terrible, disgusting state.}
{18700}{}{Bed}
{18701}{}{You don't think anyone in their right mind would want to lie on that bed.}
{18800}{}{Bed}
{18801}{}{You don't think anyone in their right mind would want to lie on that bed.}
{18900}{}{Bed}
{18901}{}{The best thing to do with this bed is to destroy it.}
{19000}{}{Bed}
{19001}{}{It looks like a comfy bed, but the sheets on it aren't.}
{19100}{}{Bed}
{19101}{}{These sheets should have been washed, and they should have been washed a dozen years ago.}
{19200}{}{Bed}
{19201}{}{A bed with a pile of dirty sheets.}
{19300}{}{Couch}
{19301}{}{Or at least it once was a couch, now it's just junk.}
{19400}{}{Floor}
{19500}{}{Wall}
{19600}{}{Tiles}
{19601}{}{Some stone tiles on the floor.}
{19700}{}{Hatch}
{19701}{}{The stairs leading down the hole descend into darkness.}
{19800}{}{Curb}
{19801}{}{A destroyed part of the sidewalk.}
{19900}{}{Curb}
{19901}{}{A destroyed part of the sidewalk.}
{20000}{}{Motorcycle}
{20001}{}{A rusty motorcycle of the Sunset Jackals.}
{20100}{}{Sign}
{20101}{}{The sign on this post is pretty rust.}
{20200}{}{Sign}
{20201}{}{It's not very clear what it was pointing at.}
{20300}{}{Sign}
{20301}{}{The sign on this post is pretty rust.}
{20400}{}{Sign}
{20401}{}{The post is pretty rust.}
{20500}{}{Sign}
{20501}{}{The sign is pretty rust.}
{20600}{}{Old Mattress}
{20601}{}{This mattress discourages any desire to take a nap on or even go near it.}
{20700}{}{Old Mattress}
{20701}{}{Lying on it you might feed those charming critters living in it.}
{20800}{}{Bed}
{20801}{}{It stinks even from a distance.}
{20900}{}{Bed}
{20901}{}{Even if you were to sleep by yourself on this thing, you would not be sleeping alone.}
{21000}{}{Bed}
{21001}{}{This bed has seen better days (and probably nights, too.)}
{21100}{}{Bed}
{21101}{}{There are a couple of stains of dubious origin on this well-worn sleeping device.}
{21200}{}{Bed}
{21201}{}{This bed is neatly covered with a dirty blanket}
{21300}{}{Bed}
{21301}{}{This bed has seen a lot of use and wear. Something must have crawled between the mattresses and died, too.}
{21400}{}{Counter}
{21401}{}{Portions of food are given out here.}
{21500}{}{Counter}
{21501}{}{Portions of food are given out here.}
{21600}{}{Counter}
{21601}{}{Portions of food are given out here.}
{21700}{}{Counter}
{21701}{}{Portions of food are given out here.}
{21800}{}{Counter}
{21801}{}{Portions of food are given out here.}
{21900}{}{Kitchen}
{21901}{}{The food for the whole of Tartarus is prepared here.}
{22000}{}{Broken Table}
{22001}{}{Something or someone broke through the table.}
{22100}{}{Chair}
{22101}{}{It looks comfortable.}
{22200}{}{Tires}
{22201}{}{You have plenty of time to look at this garbage.}
{22300}{}{Wheel}
{22301}{}{Previously part of a car.}
{22400}{}{Tire}
{22401}{}{Essentially just useless junk.}
{22500}{}{Wheel}
{22501}{}{Previously part of a car.}
{22600}{}{Wheel}
{22601}{}{Previously part of a car.}
{22700}{}{Tire}
{22701}{}{This old tire is completely hardened out.}
{22800}{}{Driving Wheel}
{22801}{}{It's hard to imagine that someone could use this stuff.}
{22900}{}{Chair}
{22901}{}{This chair has already served its time.}
{23000}{}{Chair}
{23001}{}{It looks quite suitable to sit on.}
{23100}{}{Chair}
{23101}{}{This chair is rotting right before your eyes.}
{23200}{}{Chair}
{23201}{}{It doesn't look too comfortable, but it's quite sturdy.}
{23300}{}{Chair}
{23301}{}{This chair doesn't even seem to be rusty.}
{23400}{}{Chair}
{23401}{}{This chair with armrests is still in good shape.}
{23500}{}{Chair}
{23501}{}{Well preserved and also still spinning.}
{23600}{}{Chair}
{23601}{}{This chair doesn't even seem to be rusty.}
{23700}{}{Chair}
{23701}{}{This chair is slightly askew.}
{23800}{}{Chair}
{23801}{}{An old wooden chair. Still looks quite sturdy.}
{23900}{}{Chair}
{23901}{}{An old wooden chair. Still looks quite sturdy.}
{24000}{}{Chair}
{24001}{}{An old wooden chair. Still looks quite sturdy.}
{24100}{}{Chair}
{24101}{}{An old wooden chair. Still looks quite sturdy.}
{24200}{}{Chair}
{24201}{}{An old wooden chair. Still looks quite sturdy.}
{24300}{}{Fire Hydrant}
{24301}{}{There's definitely no water there anymore.}
{24400}{}{Lamp Post}
{24401}{}{It's covered in rust, but still standing.}
{24500}{}{Lamp Post}
{24501}{}{This lamp post will never work again.}
{24600}{}{Lamp Post}
{24601}{}{This lamp post will never work again.}
{24700}{}{Lamp Post}
{24701}{}{It's covered in rust, but still standing.}
{24800}{}{Crate}
{24801}{}{A metal crate. Label reads "Livos".}
{24900}{}{Metro Sign}
{24901}{}{The entrance to the station must be here somewhere.}
{25000}{}{Cave Wall}
{25100}{}{Sign}
{25101}{}{Something dangerous is stored here.}
{25200}{}{Stuff}
{25201}{}{Just some useless junk.}
{25300}{}{Crate}
{25301}{}{A sturdy metal crate.}
{25400}{}{Crate}
{25401}{}{A metal crate. Label reads "Livos".}
{25500}{}{Junk}
{25501}{}{There's nothing useful there.}
{25600}{}{Rocks}
{25601}{}{Some small rocks.}
{25700}{}{Rocks}
{25701}{}{A couple of small stones.}
{25800}{}{Door}
{25801}{}{This door is in good condition.}
{25900}{}{Door}
{25901}{}{This door is in good condition.}
{26000}{}{Door}
{26001}{}{A beautifully decorated door in good condition.}
{26100}{}{Door}
{26101}{}{A beautifully decorated door in good condition.}
{26200}{}{Crate}
{26201}{}{A nice wooden crate with some junk in it.}
{26300}{}{Crate}
{26301}{}{A sturdy wooden crate.}
{26400}{}{Crate}
{26401}{}{The only thing that's valuable would be the crate itself, and even that is questionable.}
{26500}{}{Newspaper Machine}
{26501}{}{The newspaper machine is empty.}
{26600}{}{Newspaper Machine}
{26601}{}{The newspaper machine is empty.}
{26700}{}{Newspaper Machine}
{26701}{}{The newspaper machine is empty.}
{26800}{}{Newspaper Machine}
{26801}{}{The newspaper machine is empty.}
{26900}{}{Newspaper Machine}
{26901}{}{The newspaper machine is empty.}
{27000}{}{Newspaper Machine}
{27001}{}{The newspaper machine is empty. It looks like it once held adult magazines.}
{27100}{}{Old Mattress}
{27101}{}{Not usable for its intended purpose anymore, it's just useless garbage now.}
{27200}{}{Old Mattress}
{27201}{}{Maybe if you were wearing a fully hermetic sealed metal armor suit, you wouldn't catch something while lying on it.}
{27300}{}{Junk}
{27301}{}{A pile of rotten old wood. It's not worth carrying around.}
{27400}{}{Junk}
{27401}{}{A pile of rotten wood.}
{27500}{}{Junk}
{27501}{}{This junk is hardly useful.}
{27600}{}{Junk}
{27601}{}{This junk is hardly useful.}
{27700}{}{Junk}
{27701}{}{Some junk that you think might have been a bed mattress before it was destroyed by the environment.}
{27800}{}{Rocks}
{27900}{}{Rocks}
{28000}{}{Rocks}
{28100}{}{Rubble}
{28101}{}{A small pile of stone rubble. Watch your step!}
{28200}{}{Box}
{28201}{}{A sturdy wooden box.}
{28300}{}{Rocks}
{28301}{}{A pile of rocks.}
{28400}{}{Box}
{28401}{}{There's some junk inside.}
{28500}{}{Rocks}
{28501}{}{A pile of rocks.}
{28600}{}{Stop Sign}
{28601}{}{A red sign with the word STOP written in large block letters.}
{28700}{}{Stop Sign}
{28701}{}{A red sign with the word STOP written in large block letters. The large bullet hole was added after manufacturing.}
{28800}{}{Box}
{28801}{}{A large empty box.}
{28900}{}{Boxes}
{28901}{}{Two wooden boxes with contents of unknown purpose.}
{29000}{}{Box}
{29001}{}{A patched box. Its contents long lost all value.}
{29100}{}{Street Lamp}
{29101}{}{It looks like it's still working.}
{29200}{}{Street Lamp}
{29201}{}{It looks like it's still working.}
{29300}{}{Street Lamp}
{29301}{}{It looks like it's still working.}
{29400}{}{Street Lamp}
{29401}{}{It looks like it's still working.}
{29500}{}{Street Lamp}
{29501}{}{Or to be precise, what is left of it.}
{29600}{}{Street Lamp}
{29601}{}{This lamp can unlikely be restored.}
{29700}{}{Street Lamp}
{29701}{}{It looks like it's still working.}
{29800}{}{Box}
{29801}{}{A sturdy wooden box with some useless junk.}
{29900}{}{Box}
{29901}{}{A metal box.}
{30000}{}{Table}
{30001}{}{This table has clearly been smashed, it looks like it's about to fall apart.}
{30100}{}{Table}
{30101}{}{A wooden table, relatively well preserved.}
{30200}{}{Table}
{30201}{}{A wooden table. It is put down to rest.}
{30300}{}{Table}
{30301}{}{A wooden table with a plastic surface. It has been broken for a while.}
{30400}{}{Junk}
{30401}{}{Completely useless junk.}
{30500}{}{Table}
{30501}{}{An old broken table.}
{30600}{}{Table}
{30601}{}{It looks like it could fall apart any minute.}
{30700}{}{Dirt}
{30701}{}{Dirt}
{30800}{}{Dirt}
{30801}{}{Dirt}
{30900}{}{Toilet}
{30901}{}{Whoever used it last didn't flush it away!}
{31000}{}{Junk}
{31001}{}{Pieces of wood, boxes, and other debris.}
{31100}{}{Junk}
{31101}{}{Even if you look at it more closely, you will not find anything of value.}
{31200}{}{Junk}
{31201}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31300}{}{Junk}
{31301}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31400}{}{Junk}
{31401}{}{Something that has clearly served its purpose.}
{31500}{}{Junk}
{31501}{}{Some Bottles. Don't get your hopes up, they're all empty and broken.}
{31600}{}{Tree}
{31601}{}{A dead but still strong tree. Every beaver's dream.}
{31700}{}{Tree}
{31701}{}{A dead tree. The hollow is empty.}
{31800}{}{Stump}
{31801}{}{It was once A tree}
{31900}{}{Rope}
{32000}{}{Barrier}
{32001}{}{A small portable fence.}
{32100}{}{Barrier}
{32101}{}{A small portable fence.}
{32200}{}{Wall}
{32300}{}{Truck}
{32301}{}{The wrecked remains of a diesel truck. This pile of metal will never go again.}
{32400}{}{Truck}
{32401}{}{This diesel truck can't be fixed.}
{32500}{}{Bath Tub}
{32501}{}{On closer examination, you realize that you don't want to take a bath in this.}
{32600}{}{Bath Tub}
{32601}{}{This bathtub is broken and cracked.}
{32700}{}{Urinal}
{32701}{}{Not the cleanest of its kind, you wouldn't want to use it.}
{32800}{}{Table}
{32801}{}{A table with a calculator. You wonder why they need two monitors here.}
{32900}{}{Urinal}
{32901}{}{Just a dirty urinal. Nothing special.}
{33000}{}{Table}
{33001}{}{An ordinary table, in good condition.}
{33100}{}{Platform}
{33101}{}{A system of mechanisms is located on the concrete platform.}
{33200}{}{Door}
{33201}{}{A cracked wooden door.}
{33300}{}{Door}
{33301}{}{A cracked wooden door.}
{33400}{}{Truck}
{33401}{}{It will definitely not move anymore.}
{33500}{}{Truck}
{33501}{}{It will definitely not move anymore.}
{33600}{}{Truck}
{33601}{}{It will definitely not move anymore.}
{33700}{}{Truck}
{33701}{}{It will definitely not move anymore.}
{33800}{}{Truck}
{33801}{}{It's just a pile of rusty metal now.}
{33900}{}{Truck}
{33901}{}{Its back is full of broken containers and crates. Their contents lost their value a long time ago.}
{34000}{}{Wall}
{34001}{}{Wall}
{34100}{}{Wall}
{34101}{}{Wall}
{34200}{}{Road Sign}
{34201}{}{A funny little man is drawn on the sign.}
{34300}{}{Road Sign}
{34301}{}{A funny little man is drawn on the sign.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{If you can see this, blame the technical designer.}
{34500}{}{Floor}
{34600}{}{Shadow}
{34601}{}{The shadow of the New World Order sign.}
{34700}{}{Pipe}
{34701}{}{Part of the pipe.}
{34800}{}{Ladder}
{34801}{}{It leads up.}
{34900}{}{Ladder}
{34901}{}{It leads down.}
{35000}{}{Ladder}
{35001}{}{It leads up.}
{35100}{}{Ladder}
{35101}{}{It leads up.}
{35200}{}{Ladder}
{35201}{}{It leads up.}
{35300}{}{Ladder}
{35301}{}{It leads down.}
{35400}{}{Ladder}
{35401}{}{It leads down.}
{35500}{}{Ladder}
{35501}{}{It leads up.}
{35600}{}{an entrance}
{35601}{}{An entrance to the factory building.}
{35700}{}{Table}
{35701}{}{An old wooden table.}
{35800}{}{Table}
{35801}{}{An old wooden table.}
{35900}{}{Well}
{35901}{}{A shallow well}
{36000}{}{Wall}
{36001}{}{Wall}
{36100}{}{Curtain}
{36101}{}{The curtain looks as if it was made with primitive tools, but it is very strong.}
{36200}{}{Curtain}
{36201}{}{The curtain looks as if it was made with primitive tools, but it is very strong.}
{36300}{}{Graffiti}
{36301}{}{Jackals Rule!}
{36400}{}{Graffiti}
{36401}{}{Jackals Rule!}
{36500}{}{Graffiti}
{36501}{}{Jackals Rule!}
{36600}{}{Boards}
{36601}{}{The fence is made of boards like these.}
{36700}{}{Boards}
{36701}{}{The fence is made of boards like these.}
{36800}{}{Sign}
{36801}{}{It says something about a certain laboratory.}
{36900}{}{Cave Wall}
{37000}{}{Dirt}
{37001}{}{Dirt}
{37100}{}{Dirt}
{37101}{}{Dirt}
{37200}{}{Pot}
{37201}{}{A finely crafted clay pot.}
{37300}{}{Rake}
{37301}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37400}{}{Rake}
{37401}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37500}{}{Rake}
{37501}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37600}{}{Boards}
{37601}{}{The fence is made of boards like these.}
{37700}{}{Boards}
{37701}{}{The fence is made of boards like these.}
{37800}{}{Boards}
{37801}{}{The fence is made of boards like these.}
{37900}{}{Basin}
{37901}{}{It's full of junk. You don't want to look into it.}
{38000}{}{Basin}
{38001}{}{There's sediment and dirt inside.}
{38100}{}{Bucket}
{38101}{}{There is some water at the bottom. What would you like to see in it?}
{38200}{}{Vase}
{38201}{}{A very pretty clay vase.}
{38300}{}{Well}
{38301}{}{A typical well found in the wasteland.}
{38400}{}{Box}
{38401}{}{An empty storage box.}
{38500}{}{Box}
{38501}{}{An empty storage box.}
{38600}{}{Box}
{38601}{}{Every time you look in a box and find it empty, you get a little upset.}
{38700}{}{Box}
{38701}{}{An empty storage box.}
{38800}{}{Box}
{38801}{}{Every time you look in a box and find it empty, you get a little upset.}
{38900}{}{Box}
{38901}{}{Just a confusing storage box full of trash.}
{39000}{}{Box}
{39001}{}{Every time you look in a box and find it empty, you get a little upset.}
{39100}{}{Box}
{39101}{}{An empty storage box.}
{39200}{}{Brace}
{39201}{}{This brace helps to support the defensive wall.}
{39300}{}{Metal Plate}
{39301}{}{Useless stuff.}
{39400}{}{Metal Plate}
{39401}{}{Useless stuff.}
{39500}{}{Brace}
{39501}{}{This brace helps to support the defensive wall.}
{39600}{}{Metal Barrel}
{39601}{}{A rusty metal barrel. It is empty.}
{39700}{}{Metal Barrel}
{39701}{}{This barrel is probably empty from the hollow sound.}
{39800}{}{Metal Barrels}
{39801}{}{These barrels are probably empty from their hollow sound.}
{39900}{}{Metal Barrels}
{39901}{}{These barrels are probably empty from their hollow sound.}
{40000}{}{Air Vent}
{40001}{}{This air vent appears to be for an underground structure.}
{40100}{}{Box}
{40101}{}{Every time you look in a box and find it empty, you get a little upset.}
{40200}{}{Box}
{40201}{}{An empty storage box.}
{40300}{}{Box}
{40301}{}{An empty storage box.}
{40400}{}{Rat Hole}
{40401}{}{Maybe there's something inside besides rats.}
{40500}{}{Sunbed}
{40501}{}{An old rotten sunbed.}
{40600}{}{Door}
{40601}{}{A dried wooden door}
{40700}{}{"Interceptor"}
{40701}{}{Judging by the turbocharger on the hood, it was a very powerful car. Alas, it is not going anywhere anymore.}
{40800}{}{Wooden boards}
{40801}{}{Old rotten boards}
{40900}{}{Truck}
{40901}{}{Old broken military truck.}
{41000}{}{Things}
{41001}{}{A pile of useless junk, covered with a piece of tarpaulin.}
{41100}{}{Things}
{41101}{}{A pile of useless junk, covered with a piece of tarpaulin.}
{41200}{}{Things}
{41201}{}{A pile of useless junk, covered with a piece of tarpaulin.}
{41300}{}{Guarding booth}
{41301}{}{Either it was refurbished into a latrine, or the most comfortable way to do guarding duties is while sitting on the toilet.}
{41400}{}{Table}
{41401}{}{It is equipped with some obscure tools.}
{41500}{}{Junk}
{41501}{}{Some metal stuff. You don't think you can use it.}
{41600}{}{Junk}
{41601}{}{Old tools. Looks like they are all broken.}
{41700}{}{Box}
{41701}{}{An empty storage box.}
{41800}{}{Box}
{41801}{}{An empty storage box.}
{41900}{}{Box}
{41901}{}{An empty storage box.}
{42000}{}{Box}
{42001}{}{An empty storage box.}
{42100}{}{Elevator door}
{42101}{}{This is an elevator door. To access the elevator, you need to open this door first.}
{42200}{}{Wooden boards}
{42201}{}{Wooden boards and other garbage}
{42300}{}{Stones}
{42400}{}{Stones}
{42500}{}{Stones}
{42600}{}{Bed}
{42601}{}{A piece of furniture in terrible condition}
{42700}{}{Bed}
{42701}{}{A piece of furniture in terrible condition}
{42800}{}{Box}
{42801}{}{An empty storage box.}
{42900}{}{Box}
{42901}{}{An empty storage box.}
{43000}{}{Box}
{43001}{}{An empty storage box.}
{43100}{}{Box}
{43101}{}{An empty storage box.}
{43200}{}{Junk}
{43300}{}{Junk}
{43400}{}{Junk}
{43500}{}{Stones}
{43501}{}{You examine them very carefully, but they are still usual stones.}
{43600}{}{Guarding booth}
{43601}{}{Either it was refurbished into a latrine, or the most comfortable way to do guarding duties is while sitting on the toilet.}
{43700}{}{Door}
{43701}{}{A beautifully designed wooden door, reinforced with metal ornaments and braces that give a hypnotic impression.}
{43800}{}{Door}
{43801}{}{A beautifully designed wooden door, reinforced with metal ornaments and braces that give a hypnotic impression.}
{43900}{}{Picked plants}
{43901}{}{A rotting pile of picked plants}
{44000}{}{Picked plants}
{44001}{}{A rotting pile of picked plants}
{44100}{}{Picked plants}
{44101}{}{A rotting pile of picked plants}
{44200}{}{Picked plants}
{44201}{}{This pile doesn't smell good. It is quite stinky.}
{44300}{}{Picked plants}
{44301}{}{This pile doesn't smell good. It is quite stinky.}
{44400}{}{Dillweed}
{44401}{}{This plant is obviously inedible.}
{44500}{}{Dillweed}
{44501}{}{You are not a plant expert, but it looks like this one is inedible.}
{44600}{}{Dillweed}
{44601}{}{This plant is obviously inedible.}
{44700}{}{Device}
{44701}{}{A complicated mechanism with an obscure purpose.}
{44800}{}{Door}
{44801}{}{A guarded door. Looks like it's heavily reinforced.}
{44900}{}{Nuclear warhead}
{45000}{}{Generator}
{45001}{}{A sophisticated device for generating electricity.}
{45100}{}{Fence}
{45101}{}{A wooden fence.}
{45200}{}{Fence}
{45201}{}{A wooden fence.}
{45300}{}{Fence}
{45301}{}{A wooden fence.}
{45400}{}{Fence}
{45401}{}{A wooden fence.}
{45500}{}{Fence}
{45501}{}{A wooden fence.}
{45600}{}{Fence}
{45601}{}{A wooden fence.}
{45700}{}{Fence}
{45701}{}{A wooden fence.}
{45800}{}{Fence}
{45801}{}{Those who built this fence obviously weren't perfectionists.}
{45900}{}{Fence}
{45901}{}{Those who built this fence obviously weren't perfectionists.}
{46000}{}{Fence}
{46001}{}{Those who built this fence obviously weren't perfectionists.}
{46100}{}{Sewer grid}
{46101}{}{It's unlikely that the sewer itself is still operating.}
{46200}{}{Bottles}
{46201}{}{Cracked bottles and broken dishes.}
{46300}{}{Bottles}
{46301}{}{Cracked bottles and broken dishes.}
{46400}{}{Junk}
{46401}{}{A useless pile of junk.}
{46500}{}{Slot machine}
{46501}{}{You don't really think that in two hundred years it still works, do you?}
{46600}{}{Slot machine}
{46601}{}{You don't really think that in two hundred years it still works, do you?}
{46700}{}{Junk}
{46701}{}{Some useless junk.}
{46800}{}{Junk}
{46801}{}{Some useless junk.}
{46900}{}{Poster}
{46901}{}{It is impossible to tell what's on it.}
{47000}{}{Elevator door}
{47100}{}{Box}
{47101}{}{An empty storage box.}
{47200}{}{Box}
{47201}{}{This box contains nothing interesting.}
{47300}{}{Box}
{47301}{}{This box contains nothing interesting.}
{47400}{}{Box}
{47401}{}{This box contains nothing interesting.}
{47500}{}{Box}
{47501}{}{This box contains nothing interesting.}
{47600}{}{Box}
{47601}{}{This box contains nothing interesting.}
{47700}{}{Box}
{47701}{}{This box contains nothing interesting.}
{47800}{}{Box}
{47801}{}{This box contains nothing interesting.}
{47900}{}{Box}
{47901}{}{This box contains nothing interesting.}
{48000}{}{Box}
{48001}{}{This box contains nothing interesting.}
{48100}{}{Door}
{48101}{}{A sturdy metal door.}
{48200}{}{Door}
{48201}{}{A sturdy metal door.}
{48300}{}{Things}
{48301}{}{A huge pile of things, which, on a closer inspection, contains nothing of interest for you.}
{48400}{}{Weapons store}
{48401}{}{There's a whole bunch of weapons on the counter.}
{48500}{}{Propeller.}
{48501}{}{It is spinning.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{This big monitor is covered with a layer of dust. It is definitely not working}
{48800}{}{Floor}
{48801}{}{Floor}
{48900}{}{Barrier}
{48901}{}{It surrounds the stairs from both sides.}
{49000}{}{Wall}
{49100}{}{Barrier}
{49101}{}{Some wooden boards nailed to a sheet of iron.}
{49200}{}{Barrier}
{49201}{}{Several metal sheets put on each other.}
{49300}{}{Table}
{49301}{}{Looks like this table is missing a leg.}
{49400}{}{Table}
{49401}{}{Looks like this table is missing a leg.}
{49500}{}{Table}
{49501}{}{Old dilapidated table}
{49600}{}{Table}
{49601}{}{Better not to put anything heavy on it.}
{49700}{}{Table}
{49701}{}{Looks like it can break at any moment.}
{49800}{}{Shadow}
{49900}{}{Corn}
{49901}{}{A useful domestic plant.}
{50000}{}{Corn}
{50001}{}{A very small bush.}
{50100}{}{Corn}
{50101}{}{You like the corn soup very much.}
{50200}{}{Corn}
{50201}{}{This bush has a long way to grow.}
{50300}{}{Corn}
{50301}{}{This bush has a long way to grow.}
{50400}{}{Corn}
{50401}{}{Looks like this cob is almost ripe.}
{50500}{}{Parking lot entrance}
{50501}{}{It's impossible to clear this rubble.}
{50600}{}{Parking lot entrance}
{50601}{}{It's impossible to clear this rubble.}
{50700}{}{Chair}
{50701}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{50800}{}{Chair}
{50801}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{50900}{}{Boulder}
{50901}{}{The collapsed part of the roof formed this slide of rock. Your rope leads back to the surface.}
{51000}{}{Corn}
{51001}{}{This corn cob will soon be ready for consumption.}
{51100}{}{Wall}
{51200}{}{Hose}
{51201}{}{An Irreplaceable tool in the business of watering crops.}
{51300}{}{Corn}
{51301}{}{This bush has a long way to grow.}
{51400}{}{Pole}
{51500}{}{Hose}
{51501}{}{An Irreplaceable tool in the business of watering crops.}
{51600}{}{Chair}
{51601}{}{Looks solid.}
{51700}{}{Chair}
{51701}{}{Looks solid.}
{51800}{}{Chair}
{51801}{}{Looks solid.}
{51900}{}{Chair}
{51901}{}{Looks solid.}
{52000}{}{Bed}
{52001}{}{It's better to sleep on the floor.}
{52100}{}{Shadow}
{52200}{}{Chair}
{52201}{}{Battered, but sturdy.}
{52300}{}{Things}
{52301}{}{A lot of boxes full of useless junk.}
{52400}{}{Workbench.}
{52401}{}{An old workbench, it seems to have been used a lot.}
{52500}{}{Shadow}
{52600}{}{Chair}
{52601}{}{Battered, but sturdy.}
{52700}{}{Car}
{52701}{}{You see a bucket of nuts and bolts. It was a great car once.}
{52800}{}{Car}
{52801}{}{You see a bucket of nuts and bolts. It was a great car once.}
{52900}{}{Box}
{52901}{}{An empty carton box.}
{53000}{}{Box}
{53001}{}{An empty carton box.}
{53100}{}{Box}
{53101}{}{An empty carton box.}
{53200}{}{Box}
{53201}{}{An empty carton box.}
{53300}{}{Land}
{53400}{}{Land}
{53500}{}{Land}
{53600}{}{Land}
{53700}{}{Punching bag}
{53701}{}{You wouldn't want to be in its place.}
{53800}{}{Box}
{53801}{}{Sometimes you can find something useful in boxes. Not this time.}
{53900}{}{Box}
{53901}{}{Sometimes you can find something useful in boxes. Not this time.}
{54000}{}{Box}
{54001}{}{Sometimes you can find something useful in boxes. Not this time.}
{54100}{}{Box}
{54101}{}{Sometimes you can find something useful in boxes. Not this time.}
{54200}{}{Barbell}
{54201}{}{A sports apparatus}
{54300}{}{Barbell}
{54301}{}{A sports apparatus}
{54400}{}{Junk}
{54401}{}{Looks like a part of the box.}
{54500}{}{Junk}
{54501}{}{This trash is useless.}
{54600}{}{Horizontal bar.}
{54601}{}{It's securely fixed in the wall.}
{54700}{}{Horizontal bar.}
{54701}{}{It's securely fixed in the wall.}
{54800}{}{Horizontal bar.}
{54801}{}{You don't remember the last time you did pull-ups.}
{54900}{}{Junk}
{54901}{}{You see a half-decayed cardboard box.}
{55000}{}{Junk}
{55001}{}{You see a half-decayed cardboard box.}
{55100}{}{Concrete slabs.}
{55101}{}{Heavy slabs, embedded in the ground.}
{55200}{}{Concrete slabs.}
{55201}{}{Heavy slabs, embedded in the ground.}
{55300}{}{Concrete slabs.}
{55301}{}{Heavy slabs, embedded in the ground.}
{55400}{}{Shadow}
{55500}{}{A covered hole in the wall}
{55501}{}{Some boards and piles of junk are covering the hole.}
{55600}{}{A covered hole in the wall}
{55601}{}{Some boards and piles of junk are covering the hole.}
{55700}{}{Poster}
{55701}{}{An old "Happy Bull" poster.}
{55800}{}{Junk}
{55801}{}{Looks like a part of the box.}
{55900}{}{Fence}
{55901}{}{Once beautiful metallic fence.}
{56000}{}{Fence}
{56001}{}{Once beautiful metallic fence.}
{56100}{}{Fence}
{56101}{}{Once beautiful metallic fence.}
{56200}{}{Fence}
{56201}{}{Once beautiful metallic fence.}
{56300}{}{Fence}
{56301}{}{Once beautiful metallic fence.}
{56400}{}{Fence}
{56401}{}{Once beautiful metallic fence.}
{56500}{}{Fence}
{56501}{}{Once beautiful metallic fence.}
{56600}{}{Fence}
{56601}{}{Once beautiful metallic fence.}
{56700}{}{Beam}
{56701}{}{This is a pretty strong beam.}
{56800}{}{Door}
{56801}{}{Entrance to the factory building.}
{56900}{}{Shelves.}
{56901}{}{Vast metal shelves}
{57000}{}{Shelves.}
{57001}{}{Metal shelves. They look reliable and strong.}
{57100}{}{Shelves.}
{57101}{}{Metal shelves. They look reliable and strong.}
{57200}{}{Shelves.}
{57201}{}{Metallic shelves. Nothing to pick up here.}
{57300}{}{Bush}
{57301}{}{A desert plant. No interest to you.}
{57400}{}{Bush}
{57401}{}{A desert plant. No interest to you.}
{57500}{}{Bush}
{57501}{}{A desert plant. No interest to you.}
{57600}{}{Haystack}
{57601}{}{A result of Life Servant's work.}
{57700}{}{Shovel}
{57701}{}{The main tool to work with the soil.}
{57800}{}{Haystack}
{57801}{}{A result of Life Servant's work.}
{57900}{}{Device}
{57901}{}{Looks like this thing was turned into producing moonshine.}
{58000}{}{Haystack}
{58001}{}{A result of Life Servant's work.}
{58100}{}{Door}
{58101}{}{A reliable door made of steel bars.}
{58200}{}{Table}
{58201}{}{A table with obscure tools lying on it.}
{58300}{}{Ladder}
{58301}{}{This ladder leads into the darkness below.}
{58400}{}{Ladder}
{58401}{}{This ladder leads into the darkness below.}
{58500}{}{Chains}
{58501}{}{This ring has chains instead of ropes. Looks brutal.}
{58600}{}{Chains}
{58601}{}{This ring has chains instead of ropes. Looks brutal.}
{58700}{}{Chains}
{58701}{}{This ring has chains instead of ropes. Looks brutal.}
{58800}{}{Chains}
{58801}{}{This ring has chains instead of ropes. Looks brutal.}
{58900}{}{Chains}
{58901}{}{This ring has chains instead of ropes. Looks brutal.}
{59000}{}{Junk}
{59001}{}{Nothing of interest.}
{59100}{}{Tires}
{59101}{}{This is a ring's foundation.}
{59200}{}{Tires}
{59201}{}{This is a ring's foundation.}
{59300}{}{Tires}
{59301}{}{This is a ring's foundation.}
{59400}{}{Tires}
{59401}{}{This is a ring's foundation.}
{59500}{}{Chains}
{59501}{}{This ring has chains instead of ropes. Looks brutal.}
{59600}{}{Moonshine machine}
{59601}{}{Designed for producing booze.}
{59700}{}{Boiler pot}
{59701}{}{A boiler for producing the "Drop"}
{59800}{}{Wall}
{59900}{}{Wall}
{60000}{}{Wall}
{60100}{}{Junk}
{60101}{}{Parts of warehouse boxes.}
{60200}{}{Floor}
{60300}{}{Tables.}
{60301}{}{A pile of old tables.}
{60400}{}{Table}
{60401}{}{A wonderful example of a wooden table.}
{60500}{}{Table}
{60501}{}{A wonderful example of a wooden table.}
{60600}{}{A broken table.}
{60601}{}{It's unlikely that someone would want to use this by its purpose.}
{60700}{}{A broken table.}
{60701}{}{It used to be a table.}
{60800}{}{Table}
{60801}{}{Sturdy and reliable, let alone a little rusty.}
{60900}{}{Table}
{60901}{}{A perfect table. Looks as good as new.}
{61000}{}{Table}
{61001}{}{Sturdy and reliable, let alone a little rusty.}
{61100}{}{Table}
{61101}{}{A wonderful example of a wooden table.}
{61200}{}{Fire}
{61201}{}{You can eternally stare at the fire.}
{61300}{}{Mirror}
{61301}{}{You look at yourself for some time.}
{61400}{}{Mirror}
{61401}{}{You look at yourself for some time.}
{61500}{}{Wall}
{61501}{}{An illuminated part of the wall.}
{61600}{}{Toilet}
{61601}{}{Very clean.}
{61700}{}{Fountain}
{61701}{}{A partially destroyed town fountain.}
{61800}{}{Toilet}
{61801}{}{If you were collecting toilets, it would be a beautiful addition to your collection.}
{61900}{}{Sink}
{61901}{}{A usual sink.}
{62000}{}{Fountain}
{62001}{}{A partially destroyed town fountain.}
{62100}{}{Bed}
{62101}{}{It is dirty and smelly.}
{62200}{}{Bed}
{62201}{}{An old rotten floor bed.}
{62300}{}{Wall}
{62400}{}{Wall}
{62500}{}{Chains}
{62501}{}{This ring has chains instead of ropes. Looks brutal.}
{62600}{}{Chains}
{62601}{}{This ring has chains instead of ropes. Looks brutal.}
{62700}{}{Lights}
{62701}{}{The surrounding area is illuminated by dim lights.}
{62800}{}{Lights}
{62801}{}{The surrounding area is illuminated by dim lights.}
{62900}{}{Wall}
{63000}{}{Wall}
{63100}{}{Wall}
{63200}{}{Terminal}
{63300}{}{Terminal}
{63400}{}{Wall}
{63500}{}{Wall}
{63600}{}{Wall}
{63700}{}{Seat}
{63701}{}{The living green plant as part of the seat decoration looks very surprising.}
{63800}{}{Seat}
{63801}{}{The living green plant as part of the seat decoration looks very surprising.}
{63900}{}{Bed}
{63901}{}{The suspicious stains discourage any desire to lie down on it.}
{64000}{}{Device}
{64001}{}{Some intricate thing with an unknown purpose.}
{64100}{}{Land}
{64200}{}{Land}
{64300}{}{Land}
{64400}{}{Land}
{64500}{}{Door}
{64501}{}{Slatted door. Well-suited for a prison cell.}
{64600}{}{Elevator control terminal}
{64601}{}{Doesn't respond. Maybe it needs power.}
{64700}{}{Elevator control terminal}
{64701}{}{Looks like this one is still working.}
{64800}{}{Bed}
{64801}{}{Old and smelly.}
{64900}{}{Bed}
{64901}{}{An old rotten floor bed.}
{65000}{}{Floor}
{65100}{}{Vent}
{65101}{}{High-tech air purification system.}
{65200}{}{Vent}
{65201}{}{High-tech air purification system.}
{65300}{}{Bed}
{65301}{}{Feeding the insects living on it is not part of your plan.}
{65400}{}{a music machine}
{65401}{}{It still works perfectly.}
{65500}{}{a music machine}
{65501}{}{The song selection is not particularly varied.}
{65600}{}{Bench}
{65601}{}{A comfortable bench.}
{65700}{}{Table}
{65701}{}{A part of a broken table.}
{65800}{}{Bed}
{65801}{}{And old floor bed, covered in mold and strange stains.}
{65900}{}{Table}
{65901}{}{A broken table. A part of it.}
{66000}{}{Table}
{66001}{}{A beautifully crafted table.}
{66100}{}{Broken table}
{66101}{}{Its leg is broken.}
{66200}{}{Chair}
{66201}{}{Looks like a usual reliable chair. Its legs are a little rusty though.}
{66300}{}{Chair}
{66301}{}{It's a chair. The usual one.}
{66400}{}{Chair}
{66401}{}{Its front leg is a little bent, but the chair still looks pretty solid.}
{66500}{}{Chair}
{66501}{}{A very comfortable piece of furniture.}
{66600}{}{Lying chair}
{66601}{}{Someone dropped this chair.}
{66700}{}{Lying chair}
{66701}{}{Looks like it's resting.}
{66800}{}{Lying chair}
{66801}{}{You are hardly going to use it.}
{66900}{}{Lying chair}
{66901}{}{Someone dropped this chair.}
{67000}{}{Armchair}
{67001}{}{Probably, you wouldn't like sitting on a chair without a seat.}
{67100}{}{Armchair}
{67101}{}{It's quite well-preserved.}
{67200}{}{Armchair}
{67201}{}{It can be probably fixed.}
{67300}{}{Armchair}
{67301}{}{Looks like there's a crack in the seat.}
{67400}{}{Armchair}
{67401}{}{You see the remains of a once convenient armchair.}
{67500}{}{Armchair}
{67501}{}{You wonder what became of the seat.}
{67600}{}{Armchair}
{67601}{}{If armchairs could have had skeletons, this is what they would look like.}
{67700}{}{Junk}
{67701}{}{Looks like it was a chair once.}
{67800}{}{Bed}
{67801}{}{Too dirty.}
{67900}{}{Locker}
{67901}{}{There is definitely nothing in there.}
{68000}{}{Bed}
{68001}{}{This bed is blackened from all the dirt.}
{68100}{}{Locker}
{68101}{}{A piece of furniture. You will hardly find anything interesting there.}
{68200}{}{Oven}
{68201}{}{Looks like it is in working condition.}
{68300}{}{Oven}
{68301}{}{This one works on wood.}
{68400}{}{Oven}
{68401}{}{You have no time to cook.}
{68500}{}{Oven}
{68501}{}{In working condition. Works on wood.}
{68600}{}{Shadow}
{68700}{}{Lights}
{68701}{}{Two lights hanging on wires.}
{68800}{}{Lights}
{68801}{}{Two lights hanging on wires.}
{68900}{}{Cave entrance}
{68901}{}{The caves are usually quite cold.}
{69000}{}{Pole}
{69001}{}{Part of the pole}
{69100}{}{Mountain}
{69101}{}{Its cliffs look unapproachable}
{69200}{}{Mountain}
{69201}{}{Its cliffs look unapproachable}
{69300}{}{Mountain}
{69301}{}{Its cliffs look unapproachable}
{69400}{}{Mountain}
{69401}{}{Its cliffs look unapproachable}
{69500}{}{Mountain}
{69501}{}{Its cliffs look unapproachable}
{69600}{}{Mountain}
{69601}{}{Its cliffs look unapproachable}
{69700}{}{Light}
{69701}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{69800}{}{Light}
{69801}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{69900}{}{Light}
{69901}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{70000}{}{Light}
{70001}{}{The ones like this were used to illuminate the surroundings in the time of the dark.}
{70100}{}{Light}
{70101}{}{This light has seen some things.}
{70200}{}{Light}
{70201}{}{Everything that's left of the light.}
{70300}{}{Seat}
{70301}{}{The plant looks alive. Maybe someone is watering it?}
{70400}{}{Pipe}
{70401}{}{A damaged pipe.}
{70500}{}{Pipe}
{70501}{}{A damaged pipe.}
{70600}{}{Pipe}
{70601}{}{A damaged pipe.}
{70700}{}{Pipe}
{70701}{}{A damaged pipe.}
{70800}{}{Table}
{70801}{}{A quite good wooden table.}
{70900}{}{Table}
{70901}{}{A quite good wooden table.}
{71000}{}{Table}
{71001}{}{It's pretty dirty. Looks like there's mold on it.}
{71100}{}{Lights}
{71101}{}{It would be complete darkness without it.}
{71200}{}{Table}
{71201}{}{It's pretty dirty. Looks like there's mold on it.}
{71300}{}{Lying chair}
{71301}{}{Bar stool with no back.}
{71400}{}{Lights}
{71401}{}{It would be complete darkness without it.}
{71500}{}{Chair}
{71501}{}{Bar stool with no back.}
{71600}{}{Sign}
#Н/Д
{71700}{}{Ladder}
{71701}{}{This ladder leads up.}
{71800}{}{Ladder}
{71801}{}{This ladder leads up.}
{71900}{}{Bench}
{71901}{}{A stone bench. For hard-asses.}
{72000}{}{Bench}
{72001}{}{You should put a lot of effort to break a stone bench.}
{72100}{}{Bench}
{72101}{}{A stone bench. Must be very firm.}
{72200}{}{Bench}
{72201}{}{A stone bench. For hard-asses.}
{72300}{}{Bench}
{72301}{}{A stone bench. For hard-asses.}
{72400}{}{Things}
{72401}{}{Some boxes. Nothing interesting inside.}
{72500}{}{Wall debris}
{72501}{}{Rubble from a destroyed wall.}
{72600}{}{Bench}
{72601}{}{A slightly damaged stone bench.}
{72700}{}{Bench}
{72701}{}{A stone bench. Must be very firm.}
{72800}{}{Lying chair}
{72801}{}{Bar stool with no back.}
{72900}{}{Lying chair}
{72901}{}{Just a bar stool. Someone tipped this one over.}
{73000}{}{Table}
{73001}{}{An unusually dirty piece of furniture.}
{73100}{}{Sign}
#Н/Д
{73200}{}{Chair}
{73201}{}{Bar stool with no back.}
{73300}{}{Sign}
#Н/Д
{73400}{}{Chair}
{73401}{}{Bar stool with no back.}
{73500}{}{Chair}
{73501}{}{Bar stool with no back.}
{73600}{}{Chair}
{73601}{}{Just a chair with no back.}
{73700}{}{Broken chair}
{73701}{}{Looks like this pile of garbage was once a chair. Made from the garbage.}
{73800}{}{Chair}
{73801}{}{Looks like this pile of garbage was once a chair. Made from the garbage.}
{73900}{}{Chair}
{73901}{}{A handmade chair, assembled from trash and car parts.}
{74000}{}{Chair}
{74001}{}{You don't have any feelings for handmade furniture.}
{74100}{}{Chair}
{74101}{}{A handmade chair, made from all kinds of stuff.}
{74200}{}{Chair}
{74201}{}{Made from junk and car parts}
{74300}{}{Manure}
{74301}{}{Better not to step on it.}
{74400}{}{Manure}
{74401}{}{A product of someone's waste.}
{74500}{}{Manure}
{74501}{}{A product of someone's waste.}
{74600}{}{Manure}
{74601}{}{Better not to step on it.}
{74700}{}{Manure}
{74701}{}{A little pile of extremely fragrant shit.}
{74800}{}{Manure}
{74801}{}{A little pile of extremely fragrant shit.}
{74900}{}{Table}
{74901}{}{A table with a scratched surface.}
{75000}{}{Table}
{75001}{}{Not the cleanest, but pretty tough table.}
{75100}{}{Car}
{75101}{}{Now it's just a pile of useless rusted metal.}
{75200}{}{Car}
{75201}{}{This car served its purpose a very, very long time ago}
{75300}{}{Car}
{75301}{}{It is impossible to repair this hunk.}
{75400}{}{Car}
{75401}{}{This heap of metal will never ride the highways again.}
{75500}{}{Bed}
{75501}{}{Looks comfy, but those who sleep here are not very fond of cleanliness.}
{75600}{}{Bed}
{75601}{}{Looks convenient. Although the sheets could be washed a little.}
{75700}{}{Bed}
{75701}{}{A piece of furniture. It's intended for rest and sleep.}
{75800}{}{Bed}
{75801}{}{If you wrap yourself in sheets, you can try to spook people.}
{75900}{}{Bed}
{75901}{}{No time to lay down and rest.}
{76000}{}{Bed}
{76001}{}{A piece of furniture. It's intended for rest and sleep.}
{76100}{}{Utility}
{76101}{}{You see pipes, wires, some kind of machines and other stuff.}
{76200}{}{Utility}
{76201}{}{You see pipes, wires, some kind of machines and other stuff.}
{76300}{}{Utility}
{76301}{}{You see pipes, wires, some kind of machines and other stuff.}
{76400}{}{Utility}
{76401}{}{You see pipes, wires, some kind of machines and other stuff.}
{76500}{}{Utility}
{76501}{}{You see pipes, wires, some kind of machines and other stuff.}
{76600}{}{Utility}
{76601}{}{You see pipes, wires, some kind of machines and other stuff.}
{76700}{}{Floor}
{76800}{}{Bomb}
{76801}{}{It's a nuclear bomb. You feel terrified even standing near it.}
{76900}{}{Podium}
{76901}{}{This is the podium where the nuclear bomb currently rests.}
{77000}{}{Calculator console}
{77001}{}{This is a control calculator.}
{77100}{}{Junk}
{77101}{}{Shattered bottles, shards of glass. Nothing of value.}
{77200}{}{Lying chair}
{77201}{}{It can still be used for sitting.}
{77300}{}{Lying chair}
{77301}{}{It can still be used for sitting.}
{77400}{}{Lying chair}
{77401}{}{Why do you need it? Leave it alone.}
{77500}{}{Lying chair}
{77501}{}{Why do you need it? Leave it alone.}
{77600}{}{Lying chair}
{77601}{}{Why do you need it? Leave it alone.}
{77700}{}{Lying chair}
{77701}{}{Why do you need it? Leave it alone.}
{77800}{}{Lying chair}
{77801}{}{Someone dropped this chair.}
{77900}{}{Lying chair}
{77901}{}{Someone dropped this chair.}
{78000}{}{Lying chair}
{78001}{}{A chair, peacefully laying around.}
{78100}{}{Chair}
{78101}{}{Rusty leg, busted leather - this chair doesn't look comfy.}
{78200}{}{Chair}
{78201}{}{Rusty leg, busted leather - this chair doesn't look comfy.}
{78300}{}{Chair}
{78301}{}{It served its purpose.}
{78400}{}{Equipment}
{78401}{}{Some kind of technical equipment.}
{78500}{}{Equipment}
{78501}{}{Some kind of technical equipment.}
{78600}{}{Equipment}
{78601}{}{Some kind of technical equipment in a rusted rack.}
{78700}{}{Equipment}
{78701}{}{A rack containing some technical equipment.}
{78800}{}{Equipment}
{78801}{}{Some technical equipment.}
{78900}{}{Equipment}
{78901}{}{Some kind of technical equipment in a rusted rack.}
{79000}{}{Equipment}
{79001}{}{Some kind of technical equipment with an unknown purpose.}
{79100}{}{Equipment}
{79101}{}{This rack has been dented by something. It is unlikely that the equipment is able to work.}
{79200}{}{Window}
{79201}{}{Very dirty.}
{79300}{}{Window}
{79301}{}{You notice the remains of glass, miraculously preserved somehow.}
{79400}{}{Window}
{79401}{}{Very dirty.}
{79500}{}{Window}
{79501}{}{You notice the remains of glass, miraculously preserved somehow.}
{79600}{}{Table}
{79601}{}{It can be repaired - but you don't need to do it.}
{79700}{}{Table}
{79701}{}{A little dented, but still a good table.}
{79800}{}{Chair}
{79801}{}{Despite its rusty legs, it can still do its job.}
{79900}{}{Chair}
{79901}{}{Despite its rusty legs, it can still do its job.}
{80000}{}{Chair}
{80001}{}{A usual chair.}
{80100}{}{Chair}
{80101}{}{Despite its rusty legs, it can still do its job.}
{80200}{}{Chair}
{80201}{}{It was fixed by someone. They did all they could.}
{80300}{}{Chair}
{80301}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80400}{}{Chair}
{80401}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80500}{}{Chair}
{80501}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80600}{}{Chair}
{80601}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{80700}{}{Chair}
{80701}{}{There's almost nothing left of this chair.}
{80800}{}{Lying chair}
{80801}{}{Just a usual chair. It must be tired. Don't disturb it.}
{80900}{}{Chair}
{80901}{}{Now it's just junk.}
{81000}{}{Chair}
{81001}{}{Just a chair, peacefully lying on the side.}
{81100}{}{Chair}
{81101}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{81200}{}{Chair}
{81201}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{81300}{}{Chair}
{81301}{}{Four legs, a seat, a back - looks like you see a usual chair.}
{81400}{}{Calculator}
{81401}{}{A common calculator.}
{81500}{}{Calculator}
{81501}{}{A common calculator.}
{81600}{}{Equipment}
{81601}{}{Some kind of technical machinery with a purpose unknown to you.}
{81700}{}{Calculator}
{81701}{}{Looks like it's turned off.}
{81800}{}{Calculator}
{81801}{}{A common calculator.}
{81900}{}{Calculator}
{81901}{}{Looks like it's turned off.}
{82000}{}{Calculator}
{82001}{}{A large and complex calculator with levers and buttons on it.}
{82100}{}{Calculator}
{82101}{}{A large and complex calculator with levers and buttons on it.}
{82200}{}{Tubes}
{82201}{}{A knot of interwoven tubes. Some kind of communications.}
{82300}{}{Tubes}
{82301}{}{A knot of interwoven tubes. Some kind of communications.}
{82400}{}{Table with reagents}
{82401}{}{It seems that the flasks contain some chemical compounds. You'd better not touch it.}
{82500}{}{Wall}
{82600}{}{Car door}
{82601}{}{More precisely, what is left of it.}
{82700}{}{Barrel}
{82701}{}{Just a metal barrel.}
{82800}{}{Barrel}
{82801}{}{A barrel with unknown content.}
{82900}{}{Chair}
{82901}{}{A great bar stool.}
{83000}{}{Lighting panel}
{83001}{}{Converts electrical energy to light. Yes, an old physics textbook, which you read as a child, sometimes reminds of itself.}
{83100}{}{Stove}
{83101}{}{A smashed floor panels.}
{83200}{}{Stove}
{83201}{}{A smashed floor panels.}
{83300}{}{Stove}
{83301}{}{A smashed floor panels.}
{83400}{}{Stove}
{83401}{}{A smashed floor panels.}
{83500}{}{Stove}
{83501}{}{A smashed floor panels.}
{83600}{}{Supporting structure}
{83601}{}{It's falling apart right when you look at it.}
{83700}{}{Slope}
{83701}{}{A steep slope down.}
{83800}{}{Slope}
{83801}{}{A steep slope down.}
{83900}{}{Slope}
{83901}{}{A steep slope down.}
{84000}{}{Slope}
{84001}{}{A steep slope down.}
{84100}{}{Slope}
{84101}{}{A steep slope down.}
{84200}{}{Slope}
{84201}{}{A steep slope down.}
{84300}{}{Slope}
{84301}{}{A steep slope down.}
{84400}{}{Slope}
{84401}{}{A steep slope down.}
{84500}{}{Slope}
{84501}{}{A bizarre natural formation}
{84600}{}{Slope}
{84601}{}{A bizarre natural formation}
{84700}{}{Slope}
{84701}{}{A bizarre natural formation}
#Н/Д
{84801}{}{A usual wooden door.}
{84900}{}{Door}
{84901}{}{A usual wooden door.}
{85000}{}{Door}
{85001}{}{The paint is almost completely peeled off, and the wood is covered with fungus.}
{85100}{}{Table}
{85101}{}{This rag appears to act as a tablecloth.}
{85200}{}{Slope}
{85201}{}{A bizarre natural formation}
{85300}{}{Barrel}
{85301}{}{Empty fuel storage tank.}
{85400}{}{Pipe}
{85401}{}{A section of pipe.}
{85500}{}{Slope}
{85501}{}{A steep slope down.}
{85600}{}{Watchtower}
{85601}{}{A watchtower made out of all kinds of junk, but fitted with weapons.}
{85700}{}{Wall}
{85800}{}{Tools}
{85801}{}{Tools you don't need.}
{85900}{}{Wall}
{86000}{}{Mechanism}
{86001}{}{This mechanism is involved in the water cleaning process.}
{86100}{}{Mechanism}
{86101}{}{This mechanism is involved in the water cleaning process.}
{86200}{}{Mechanism}
{86201}{}{This mechanism is involved in the water cleaning process.}
{86300}{}{Pipe}
{86301}{}{A section of pipe.}
{86400}{}{Pipe}
{86401}{}{A section of pipe.}
{86500}{}{Wall}
{86600}{}{Wall}
{86700}{}{Wall}
{86800}{}{Wall}
{86900}{}{Barrier}
{86901}{}{The paint is almost peeled off this metal fence, but it's still in excellent condition.}
{87000}{}{Barrier}
{87001}{}{The paint is almost peeled off this metal fence, but it's still in excellent condition.}
{87100}{}{Barrier}
{87101}{}{The regular metal fence.}
{87200}{}{Barrier}
{87201}{}{Metal fence.}
{87300}{}{Barrier}
{87301}{}{The paint is almost peeled off this metal fence, but it's still in excellent condition.}
{87400}{}{Barrier}
{87401}{}{Stacked metal fence.}
{87500}{}{Barrier}
{87501}{}{Metal fence lying on the ground.}
{87600}{}{Barrier}
{87601}{}{A battered metal fence.}
{87700}{}{Barrier}
{87701}{}{A badly battered metal fence.}
{87800}{}{Tile}
{87801}{}{A smashed floor panels.}
{87900}{}{Tile}
{87901}{}{A smashed floor panels.}
{88000}{}{Junk}
{88001}{}{Nothing interesting at all.}
{88100}{}{Land}
{88101}{}{Seems to have board fragments, but it's hard to be more precise.}
{88200}{}{Junk}
{88201}{}{Looks like parts of boxes.}
{88300}{}{Junk}
{88301}{}{Nothing interesting at all.}
{88400}{}{Junk}
{88401}{}{Parts of warehouse boxes.}
{88500}{}{Junk}
{88501}{}{Nothing interesting at all.}
{88600}{}{Toilet}
{88601}{}{It is so dirty that you would rather do your thing outdoors.}
{88700}{}{Table}
{88701}{}{Empty dirty bottles, leftover food. There's obviously nothing for you here.}
{88800}{}{Metal sheet}
{88801}{}{Rusty on both sides.}
{88900}{}{Metal sheet}
{88901}{}{Rusty on both sides.}
{89000}{}{Junk}
{89001}{}{Some unnecessary trash.}
{89100}{}{Junk}
{89101}{}{Some unnecessary trash.}
{89200}{}{Junk}
{89201}{}{Looks like a part of the box.}
{89300}{}{Toilet}
{89301}{}{Looks like it hasn't been washed in a long time.}
{89400}{}{Bed}
{89401}{}{Old and not particularly clean floor bed.}
{89500}{}{Bed}
{89501}{}{Better to sleep on bricks than on this.}
{89600}{}{Machinery}
{89601}{}{Big machinery for processing a variety of materials.}
{89700}{}{Machinery}
{89701}{}{A large machine for processing hard materials.}
{89800}{}{Pillar with spotlights.}
{89801}{}{A homemade light for illuminating the surroundings.}
{89900}{}{Pillar with spotlights.}
{89901}{}{A homemade light for illuminating the surroundings.}
{90000}{}{Pillar with spotlights.}
{90001}{}{A homemade light for illuminating the surroundings.}
{90100}{}{Bed}
{90101}{}{Someone probably sleeps on it.}
{90200}{}{Bed}
{90201}{}{If you lie down on it, you can probably pick up a couple of nasty diseases}
{90300}{}{Bed}
{90301}{}{You don't want to look at those weird spots.}
{90400}{}{Fuel filter}
{90401}{}{A device for filtering fuel.}
{90500}{}{Junk}
{90501}{}{Parts of boxes or crates.}
{90600}{}{Power Armor Parts.}
{90601}{}{These parts fit the Power Armor.}
{90700}{}{Junk}
{90701}{}{Non-interesting trash.}
{90800}{}{Junk}
{90801}{}{Non-interesting trash.}
{90900}{}{Fencing cone.}
{90901}{}{This would make a very funny hat.}
{91000}{}{Fencing cone.}
{91001}{}{This would make a very funny hat.}
{91100}{}{Fencing cone.}
{91101}{}{If you put such cones on your head, arms and legs, you get a starfish. You've seen one of these in a book.}
{91200}{}{Fencing cone.}
{91201}{}{If you put such cones on your head, arms and legs, you get a starfish. You've seen one of these in a book.}
{91300}{}{Fencing cone.}
{91301}{}{They used to mark parking lots with such.}
{91400}{}{Fencing cone.}
{91401}{}{You could carry something in it. Water, for example.}
{91500}{}{Fencing cone.}
{91501}{}{Sitting on one of these must be extremely uncomfortable.}
{91600}{}{Fencing cone.}
{91601}{}{They used to mark parking lots with such.}
{91700}{}{Box parts.}
{91800}{}{Box parts.}
{91900}{}{Junk}
{92000}{}{Box parts.}
{92100}{}{Parts of boxes or crates.}
{92200}{}{Box parts.}
{92300}{}{Things}
{92301}{}{For rummaging through other people's things you can get punched in your vital organs. That's why you shouldn't touch them.}
{92400}{}{Things}
{92401}{}{It feels like the owner of these things has been shoveling trash into the boxes.}
{92500}{}{Utility}
{92501}{}{You see pipes, wires, some kind of machines and other stuff.}
{92600}{}{Utility}
{92601}{}{You see pipes, wires, some kind of machines and other stuff.}
{92700}{}{Utility}
{92701}{}{You see pipes, wires, some kind of machines and other stuff.}
{92800}{}{Utility}
{92801}{}{You see pipes, wires, some kind of machines and other stuff.}
{92900}{}{Utility}
{92901}{}{You see pipes, wires, some kind of machines and other stuff.}
{93000}{}{Utility}
{93001}{}{You see pipes, wires, some kind of machines and other stuff.}
{93100}{}{Shadow}
{93200}{}{Tank}
{93201}{}{An old tank in very "fun" colors.}
{93300}{}{Shadow}
{93301}{}{The shadow of the tank.}
{93400}{}{A chair and a table with an umbrella.}
{93401}{}{Looks like you can rest comfortably on this tank.}
{93500}{}{Concrete block}
{93501}{}{The block looks impossible to lift.}
{93600}{}{Stones}
{93601}{}{A pile of rocks.}
{93700}{}{Wagon}
{93701}{}{A wagon, covered with a green tent.}
{93800}{}{Trading post.}
{93801}{}{Looks like you can buy armor here.}
{93900}{}{Market stall}
{93901}{}{This is usually a kind of place to buy something. If you have money to pay for it, of course.}
{94000}{}{Market stall}
{94001}{}{There's a great selection of weapons.}
{94100}{}{Market stall}
{94101}{}{There's a great selection of weapons.}
{94200}{}{Market stall}
{94201}{}{There's a great selection of weapons.}
{94300}{}{Bottles}
{94301}{}{Don't get your hopes up, they are completely empty and broken.}
{94400}{}{Metal sheet}
{94401}{}{You could call it just plain junk.}
{94500}{}{Metal sheet}
{94501}{}{You could call it just plain junk.}
{94600}{}{Metal sheet}
{94601}{}{You could call it just plain junk.}
{94700}{}{Metal sheet}
{94701}{}{You could call it just plain junk.}
{94800}{}{Metal sheet}
{94801}{}{You could call it just plain junk.}
{94900}{}{Metal sheet}
{94901}{}{You could call it just plain junk.}
{95000}{}{Hole}
{95001}{}{A suspicious hole in the wall.}
{95100}{}{Wooden boards}
{95101}{}{A few rotten boards.}
{95200}{}{Wooden boards}
{95201}{}{A few rotten boards.}
{95300}{}{Wooden boards}
{95301}{}{A few rotten boards.}
{95400}{}{Door}
{95401}{}{A double-leaf door.}
{95500}{}{Door}
{95501}{}{An ordinary door.}
{95600}{}{Door}
{95601}{}{This wonderful invention of mankind can open and close.}
{95700}{}{Door}
{95701}{}{This wonderful invention of mankind can open and close.}
{95800}{}{Door}
{95801}{}{This wonderful invention of mankind can open and close.}
{95900}{}{Door}
{95901}{}{This wonderful invention of mankind can open and close.}
{96000}{}{Door}
{96001}{}{An ordinary door.}
{96100}{}{Door}
{96101}{}{A usual wooden door.}
{96200}{}{Barrier}
{96201}{}{Goes up and down.}
{96300}{}{Fire}
{96301}{}{You can eternally stare at the fire.}
{96400}{}{Bed}
{96401}{}{You'd give a lot to not lie down on it.}
{96500}{}{Supporting structure}
{96501}{}{It's falling apart right when you look at it.}
{96600}{}{Cave Wall}
{96601}{}{It looks like there's something buried here. But you don't have time to do excavations.}
{96700}{}{Cave Wall}
{96701}{}{It looks like there's something buried here. But you don't have time to do excavations.}
{96800}{}{Cave Wall}
{96801}{}{Looks like rubble.}
{96900}{}{Wall}
{97000}{}{Wall}
{97100}{}{Wall}
{97200}{}{Wall}
{97201}{}{Crack in the wall.}
{97300}{}{Cave Wall}
{97400}{}{Cave Wall}
{97500}{}{Barrels}
{97501}{}{Empty fuel storage tanks.}
{97600}{}{Tank}
{97601}{}{A tank for supplying water.}
{97700}{}{Ladder}
{97701}{}{A sturdy metal ladder.}
{97800}{}{Door}
{97900}{}{Things}
{97901}{}{Surprisingly, there is nothing of value to you in this pile.}
{98000}{}{Barrels}
{98001}{}{Empty fuel storage tanks.}
{98100}{}{A stinking corpse.}
{98101}{}{The corpse of a black man. Not just a corpse - a feast for flies!}
{98200}{}{Door}
{98300}{}{Door}
{98400}{}{Door}
{98500}{}{Lights}
{98501}{}{A lantern attached to a pole.}
{98600}{}{Lights}
{98601}{}{A lantern attached to a pole.}
{98700}{}{Lights}
{98701}{}{A lantern attached to a pole.}
{98800}{}{Lights}
{98801}{}{A lantern attached to a pole.}
{98900}{}{Shadow}
{99000}{}{Shadow}
{99100}{}{A garbage faucet.}
{99200}{}{A garbage faucet.}
{99300}{}{Well}
{99400}{}{Well}
{99500}{}{Exterior structure.}
{99600}{}{Bed}
{99601}{}{Stinky old bed.}
{99700}{}{Bed}
{99701}{}{This floor bed is completely rotten.}
{99800}{}{Bed}
{99801}{}{A normal floor bed. People usually sleep on it.}
{99900}{}{Bed}
{99901}{}{You don't like these suspicious stains.}
{100000}{}{Moonshine machine}
{100001}{}{It looks like a wood-fired moonshine machine.}
{100100}{}{Bed}
{100101}{}{An old rotten floor bed.}
{100200}{}{Bed}
{100201}{}{An old rotten floor bed.}
{100300}{}{Bed}
{100301}{}{It's a stinky floor bed. It doesn't give you a desire to relax.}
{100400}{}{Bed}
{100401}{}{Looks like there's someone's blood on it.}
{100500}{}{Bed}
{100501}{}{Better to sleep on bricks than on this.}
{100600}{}{Bed}
{100601}{}{An old rotten floor bed.}
{100700}{}{Pumping device for the power plant.}
{100701}{}{It's a cooling pump.}
{100800}{}{Piece of the Lavash}
{100900}{}{Car}
{101000}{}{Chrysler}
{101001}{}{This Highwayman seems to be in very good shape for his age.}
{101100}{}{Car}
{101200}{}{Cemetery}
{101201}{}{The grave is located here.}
{101300}{}{Gravestone}
{101301}{}{An old headstone with a barely distinguishable inscription.}
{101400}{}{Gravestone}
{101401}{}{You will hardly be honored with one of these. Though you won't care anymore.}
{101500}{}{Gravestone}
{101501}{}{You will hardly be honored with one of these. Though you won't care anymore.}
{101600}{}{Gravestone}
{101601}{}{An old headstone with a barely distinguishable inscription.}
{101700}{}{Sign}
{101701}{}{New World Order.}
{101800}{}{Sign}
{101801}{}{New World Order.}
{101900}{}{Screen}
{101901}{}{You'd love to watch something on it, but you don't know, how.}
{102000}{}{Screen}
{102001}{}{You'd love to watch something on it, but you don't know, how.}
{102100}{}{Bottles of moonshine.}
{102101}{}{Seems that their contents are valued here. But you can't carry them with you anyway.}
{102200}{}{Large water tank.}
{102201}{}{A lightly rusted water storage tank.}
{102300}{}{Pipes}
{102301}{}{Slightly rusted pipes.}
{102400}{}{Pipes}
{102401}{}{Slightly rusted pipes.}
{102500}{}{Pipes}
{102501}{}{Slightly rusted pipes.}
{102600}{}{Pipes}
{102601}{}{Slightly rusted pipes.}
{102700}{}{Pipes}
{102701}{}{Slightly rusted pipes.}
{102800}{}{Pipes}
{102801}{}{Slightly rusted pipes.}
{102900}{}{Border}
{102901}{}{Separates the curb from the road.}
{103000}{}{Border}
{103001}{}{Separates the curb from the road.}
{103100}{}{Border}
{103101}{}{Separates the curb from the road.}
{103200}{}{Border}
{103201}{}{Separates the curb from the road.}
{103300}{}{Border}
{103301}{}{It used to be a border.}
{103400}{}{Border}
{103401}{}{It used to be a border - now it's just debris.}
{103500}{}{Border}
{103501}{}{It used to be a border - now it's just debris.}
{103600}{}{Border}
{103601}{}{It used to be a border - now it's just debris.}
{103700}{}{Border}
{103701}{}{It used to be a border - now it's just debris.}
{103800}{}{Border}
{103801}{}{It used to be a border - now it's just debris.}
{103900}{}{Border}
{103901}{}{Separates the curb from the road.}
{104000}{}{Border}
{104001}{}{It used to be a border - now it's just debris.}
{104100}{}{Border}
{104101}{}{Separates the curb from the road.}
{104200}{}{Border}
{104201}{}{It used to be a border - now it's just debris.}
{104300}{}{Border}
{104301}{}{It used to be a border - now it's just debris.}
{104400}{}{Things}
{104401}{}{Miscellaneous junk. Nothing of value to you there.}
{104500}{}{Things}
{104501}{}{Miscellaneous junk. Nothing of interest there.}
{104600}{}{Things}
{104601}{}{Miscellaneous junk. Nothing of interest there.}
{104700}{}{Things}
{104701}{}{Miscellaneous junk. Nothing of interest there.}
{104800}{}{Things}
{104801}{}{Miscellaneous junk. Nothing of interest there.}
{104900}{}{Things}
{104901}{}{Miscellaneous junk. Nothing of value to you there.}
{105000}{}{Things}
{105001}{}{Miscellaneous junk. Nothing of value to you there.}
{105100}{}{Things}
{105101}{}{Miscellaneous junk. Nothing of value to you there.}
{105200}{}{Things}
{105201}{}{Miscellaneous junk. Nothing of value to you there.}
{105300}{}{Things}
{105301}{}{Miscellaneous junk. Nothing of value to you there.}
{105400}{}{The wreckage of a car.}
{105401}{}{The front part of an old wrecked car.}
{105500}{}{Things}
{105501}{}{Miscellaneous junk. Nothing of value to you there.}
{105600}{}{Junk}
{105601}{}{Looks like it used to be a car.}
{105700}{}{Things}
{105701}{}{Miscellaneous junk. Nothing of value to you there.}
{105800}{}{Things}
{105801}{}{Miscellaneous junk. Nothing of value to you there.}
{105900}{}{Things}
{105901}{}{Miscellaneous junk. Nothing of value to you there.}
{106000}{}{Things}
{106001}{}{Miscellaneous junk. Nothing of value to you there.}
{106100}{}{Things}
{106101}{}{Miscellaneous junk. Nothing of value to you there.}
{106200}{}{Window}
{106201}{}{The glass is unbreakable. Don't even try.}
{106300}{}{Window}
{106301}{}{The glass is unbreakable. Don't even try.}
{106400}{}{Device}
{106401}{}{Unit attached to the tank.}
{106500}{}{Device}
{106501}{}{Unit attached to the tank.}
{106600}{}{Poster}
{106601}{}{A tattered wall poster.}
{106700}{}{Poster}
{106701}{}{A tattered wall poster.}
{106800}{}{Crate}
{106801}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{106900}{}{Crate}
{106901}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{107000}{}{Crate}
{107001}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{107100}{}{Crate}
{107101}{}{This box is definitely empty.}
{107200}{}{Crate}
{107201}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{107300}{}{Crate}
{107301}{}{It's a small but roomy box.}
{107400}{}{Crate}
{107401}{}{This box is definitely empty.}
{107500}{}{Crate}
{107501}{}{It's a small but roomy box.}
{107600}{}{Crate}
{107601}{}{It's a small but roomy box.}
{107700}{}{Crate}
{107701}{}{This box is definitely empty.}
{107800}{}{Crate}
{107801}{}{It's a small but roomy box.}
{107900}{}{Crate}
{107901}{}{It's a small but roomy box.}
{108000}{}{Crate}
{108001}{}{It's a small but roomy box.}
{108100}{}{Crate}
{108101}{}{For some reason, you can't help but think of cats when looking at these crates.}
{108200}{}{Crate}
{108201}{}{It's a small but roomy box.}
{108300}{}{Crate}
{108301}{}{It's a small but roomy box.}
{108400}{}{Crate}
{108401}{}{It's a small but roomy box.}
{108500}{}{Crate}
{108501}{}{It's a small but roomy box.}
{108600}{}{Crate}
{108601}{}{It's a small but roomy box.}
{108700}{}{Crate}
{108701}{}{For some reason, you can't help but think of cats when looking at these crates.}
{108800}{}{Crate}
{108801}{}{It's a small but roomy box.}
{108900}{}{Crate}
{108901}{}{It's a small but roomy box.}
{109000}{}{Crate}
{109001}{}{It's a small but roomy box.}
{109100}{}{Pipes}
{109101}{}{A section of massive pipe.}
{109200}{}{Pipes}
{109201}{}{A section of massive pipe.}
{109300}{}{Pipes}
{109301}{}{A section of massive pipe.}
{109400}{}{Crate}
{109401}{}{It's a small but roomy box.}
{109500}{}{Crate}
{109501}{}{It's a small but roomy box.}
{109600}{}{Crate}
{109601}{}{It's a small but roomy box.}
{109700}{}{Crate}
{109701}{}{It's a small but roomy box.}
{109800}{}{Crate}
{109801}{}{It's a small but roomy box.}
{109900}{}{Crate}
{109901}{}{For some reason, you can't help but think of cats when looking at these crates.}
{110000}{}{Crate}
{110001}{}{It's a small but roomy box.}
{110100}{}{Crate}
{110101}{}{It's a small but roomy box.}
{110200}{}{Burning barrel.}
{110201}{}{This barrel is where the trash burns.}
{110300}{}{Pipes}
{110301}{}{A section of massive pipe.}
{110400}{}{Water tank.}
{110401}{}{Apparently, it has a water supply in it.}
{110500}{}{Pipes}
{110501}{}{A section of massive pipe.}
{110600}{}{Pipes}
{110601}{}{A section of massive pipe.}
{110700}{}{Pipes}
{110701}{}{A section of massive pipe.}
{110800}{}{Pipes}
{110801}{}{A section of massive pipe.}
{110900}{}{Water tank.}
{110901}{}{Apparently, it has a water supply in it.}
{111000}{}{Junk}
{111001}{}{A tattered box.}
{111100}{}{Barrel}
{111101}{}{Just a metal barrel.}
{111200}{}{Barrel}
{111201}{}{Just a metal barrel.}
{111300}{}{Barrel}
{111301}{}{Just a metal barrel.}
{111400}{}{Concrete block}
{111401}{}{It looks very heavy.}
{111500}{}{Tank}
{111501}{}{A container where water supplies are usually kept.}
{111600}{}{Tank}
{111601}{}{A container where water supplies are usually kept.}
{111700}{}{Barrels}
{111701}{}{Empty metal barrels.}
{111800}{}{Pumping unit.}
{111801}{}{A sophisticated, massive pump. It pumps out and filters water from deep underground.}
{111900}{}{Barrel}
{111901}{}{Empty metal barrel.}
{112000}{}{Concrete block}
{112001}{}{It looks very heavy.}
{112100}{}{Barrels}
{112101}{}{Empty metal barrels.}
{112200}{}{Barrier}
{112201}{}{Emergency fence.}
{112300}{}{Barrier}
{112301}{}{Emergency fence.}
{112400}{}{Concrete block}
{112401}{}{It looks very heavy.}
{112500}{}{Concrete block}
{112501}{}{It looks very heavy.}
{112600}{}{Crate}
{112601}{}{Huge wooden box.}
{112700}{}{Concrete block}
{112701}{}{It looks very heavy.}
{112800}{}{Shadow}
{112900}{}{Crate}
{112901}{}{Huge wooden box.}
{113000}{}{Board}
{113001}{}{It holds no interest to you.}
{113100}{}{Board}
{113101}{}{It holds no interest to you.}
{113200}{}{Barrel}
{113201}{}{Empty metal barrel.}
{113300}{}{Barrel}
{113301}{}{Empty metal barrel.}
{113400}{}{Sandbags}
{113401}{}{Military fortification.}
{113500}{}{Sandbags}
{113501}{}{Military fortification.}
{113600}{}{Sandbags}
{113601}{}{Military fortification.}
{113700}{}{Sandbags}
{113701}{}{Military fortification.}
{113800}{}{Sandbags}
{113801}{}{Military fortification.}
{113900}{}{Shadow}
{114000}{}{Sandbags}
{114001}{}{Military fortification.}
{114100}{}{Sandbags}
{114101}{}{Military fortification.}
{114200}{}{Sandbags}
{114201}{}{Military fortification.}
{114300}{}{Sandbags}
{114301}{}{Military fortification.}
{114400}{}{Sandbags}
{114401}{}{Military fortification.}
{114500}{}{Sandbags}
{114501}{}{Military fortification.}
{114600}{}{Sandbags}
{114601}{}{Military fortification.}
{114700}{}{Sandbags}
{114701}{}{Military fortification.}
{114800}{}{Sandbags}
{114801}{}{Military fortification.}
{114900}{}{Sandbags}
{114901}{}{Military fortification.}
{115000}{}{Junk}
{115001}{}{A cardboard box.}
{115100}{}{Junk}
{115101}{}{Crumpled cardboard box and other useless junk.}
{115200}{}{Mining wagon.}
{115300}{}{Mining wagon with a steel pillar.}
{115400}{}{Mining wagon with dynamite}
{115500}{}{Sandbags}
{115501}{}{Military fortification.}
{115600}{}{Crate}
{115601}{}{Huge wooden box.}
{115700}{}{Crate}
{115701}{}{Huge wooden box.}
{115800}{}{Junk}
{115900}{}{Wall}
{116000}{}{Wall}
{116100}{}{Retinal scanner.}
{116101}{}{This is a security device that scans a person's retina.}
{116200}{}{Crate}
{116201}{}{It is a small but roomy box in a bright color.}
{116300}{}{Crate}
{116301}{}{It's a small but roomy box.}
{116400}{}{Crate}
{116401}{}{It's a small but roomy box.}
{116500}{}{Crate}
{116501}{}{It's a small but roomy box.}
{116600}{}{Crate}
{116601}{}{The box is definitely empty.}
{116700}{}{Shadow}
{116701}{}{Nothing unusual.}
{116800}{}{Junk}
{116801}{}{Some kind of trash.}
{116900}{}{Door}
{117000}{}{Door}
{117100}{}{Junk}
{117101}{}{Part of a broken crate.}
{117200}{}{Junk}
{117201}{}{A useless pile of junk.}
{117300}{}{Junk}
{117301}{}{A useless pile of junk.}
{117400}{}{Junk}
{117401}{}{A useless pile of junk.}
{117500}{}{Junk}
{117501}{}{A useless pile of junk.}
{117600}{}{Conveyor}
{117601}{}{Part of a factory conveyor.}
{117700}{}{Conveyor}
{117701}{}{Part of a factory conveyor.}
{117800}{}{Conveyor shield.}
{117801}{}{A means of holding a conveyor belt.}
{117900}{}{Conveyor shield.}
{117901}{}{A means of holding a conveyor belt.}
{118000}{}{Conveyor shield.}
{118001}{}{A means of holding a conveyor belt.}
{118100}{}{Conveyor shield.}
{118101}{}{A means of holding a conveyor belt.}
{118200}{}{Conveyor shield.}
{118201}{}{A means of holding a conveyor belt.}
{118300}{}{Conveyor shield.}
{118301}{}{A means of holding a conveyor belt.}
{118400}{}{Conveyor}
{118401}{}{Part of a factory conveyor.}
{118500}{}{Conveyor}
{118501}{}{Part of a factory conveyor.}
{118600}{}{Conveyor}
{118601}{}{Part of a factory conveyor.}
{118700}{}{Conveyor}
{118701}{}{Part of a factory conveyor.}
{118800}{}{Steam}
{118900}{}{Lights}
{118901}{}{An illuminating device.}
{119000}{}{Lights}
{119001}{}{An illuminating device.}
{119100}{}{Lights}
{119101}{}{An illuminating device.}
{119200}{}{Lights}
{119201}{}{An illuminating device.}
{119300}{}{Lights}
{119301}{}{An illuminating device.}
{119400}{}{Lights}
{119401}{}{An illuminating device.}
{119500}{}{Lights}
{119501}{}{An illuminating device.}
{119600}{}{Lights}
{119601}{}{An illuminating device.}
{119700}{}{Wire}
{119701}{}{Barbed wire.}
{119800}{}{Wire}
{119801}{}{Barbed wire.}
{119900}{}{Wire}
{119901}{}{Barbed wire. Dangerous thing.}
{120000}{}{Wire}
{120001}{}{Barbed wire.}
{120100}{}{Cave Wall}
{120200}{}{Cave Wall}
{120300}{}{Cave Wall}
{120400}{}{Cave Wall}
{120500}{}{Cave Wall}
{120600}{}{Cave Wall}
{120700}{}{Cave Wall}
{120800}{}{Cave Wall}
{120900}{}{Cave Wall}
{121000}{}{Cave Wall}
{121100}{}{Cave Wall}
{121200}{}{Cave Wall}
{121300}{}{Cave Wall}
{121400}{}{Cave Wall}
{121500}{}{Cave Wall}
{121600}{}{Bunk}
{121601}{}{This thing is used for resting.}
{121700}{}{Bunk}
{121701}{}{This thing is used for resting.}
{121800}{}{Bunk}
{121801}{}{This thing is used for resting.}
{121900}{}{Bunk}
{121901}{}{A tiered bunk. You dreamed of one as a child.}
{122000}{}{Bunk}
{122001}{}{A tiered bunk. You dreamed of one as a child.}
{122100}{}{Bunk}
{122101}{}{This thing is used for resting.}
{122200}{}{Bunk}
{122201}{}{No time to sleep!}
{122300}{}{Bunk}
{122301}{}{This thing is used for resting.}
{122400}{}{Bunk}
{122401}{}{Looks clean enough.}
{122500}{}{Bunk}
{122501}{}{This thing is used for resting.}
{122600}{}{Bunk}
{122601}{}{This thing is used for resting.}
{122700}{}{Wire}
{122701}{}{Barbed wire. Dangerous thing.}
{122800}{}{"Wanted!" sign}
{122801}{}{The portrait of the wanted man looks just like you!}
{122900}{}{Floor}
{123000}{}{Wire}
{123001}{}{Barbed wire.}
{123100}{}{What is this...}
{123101}{}{This strange cannon seems to have been left from before the war. Interesting, how it ended up here.}
{123200}{}{Vent}
{123201}{}{Part of the ventilation system.}
{123300}{}{Fence}
{123301}{}{Hole in the fence.}
{123400}{}{Fence}
{123401}{}{The hole in the fence. These stains look like blood.}
{123500}{}{Vent}
{123501}{}{Part of the ventilation system.}
{123600}{}{Energy switch.}
{123700}{}{Cross}
{123701}{}{A gravestone cross made from improvised materials.}
{123800}{}{Cross}
{123801}{}{The inscription on the plaque has become completely illegible.}
{123900}{}{Cross}
{123901}{}{The small tomb cross seems to have been made from old pipes.}
{124000}{}{Cross}
{124001}{}{The deceased must have worn this hat during his lifetime.}
{124100}{}{Cross}
{124101}{}{A tribute to an unknown deceased.}
{124200}{}{Cross}
{124201}{}{Everyone dies sometimes.}
{124300}{}{Broken tile.}
{124400}{}{Metal sheet}
{124401}{}{A heavy, rusty piece of iron, not worth picking up.}
{124500}{}{Metal sheet}
{124501}{}{A heavy, rusty piece of iron, not worth picking up.}
{124600}{}{Tank}
{124601}{}{A container where water supplies are usually kept.}
{124700}{}{Floor}
{124800}{}{Floor}
{124900}{}{Floor}
{125000}{}{Floor}
{125100}{}{Floor}
{125200}{}{Floor}
{125300}{}{Floor}
{125400}{}{Junk}
{125401}{}{A pile of junk.}
{125500}{}{Junk}
{125501}{}{Boxes empty, tin cans all rusted over, nothing of value here.}
{125600}{}{Metal sheet}
{125601}{}{Rusty on both sides.}
{125700}{}{Metal sheet}
{125701}{}{Let it lie where it is - it's completely useless.}
{125800}{}{Table}
{125801}{}{Station attendant's desk.}
{125900}{}{Wall}
{126000}{}{Wall}
{126100}{}{A huge ladder leading up}
{126200}{}{Junk}
{126201}{}{Parts of some machines, that have obviously lost their value.}
{126300}{}{Junk}
{126301}{}{A pile of unnecessary trash.}
{126400}{}{Utility}
{126401}{}{There are pipes, cables, other equipment.}
{126500}{}{Utility}
{126501}{}{There are pipes, cables, other equipment.}
{126600}{}{Junk}
{126601}{}{Glass, iron, something else.}
{126700}{}{Bed}
{126701}{}{You will try your best to avoid resting on this stinking bed.}
{126800}{}{Bed}
{126801}{}{You will try your best to avoid resting on this stinking bed.}
{126900}{}{Wooden boards}
{126901}{}{A board broke out of a nearby structure.}
{127000}{}{Wooden boards}
{127001}{}{A board broke out of a nearby structure.}
{127100}{}{Wooden boards}
{127101}{}{A board broke out of a nearby structure.}
{127200}{}{Wooden boards}
{127201}{}{A board broke out of a nearby structure.}
{127300}{}{Pile of Stones.}
{127301}{}{Several large cobblestones in one place.}
{127400}{}{Wall}
{127500}{}{Tent}
{127501}{}{A tent made of sturdy materials, with reinforced wind protection.}
{127600}{}{Tent}
{127601}{}{You can see the stars through the hole in the roof.}
{127700}{}{Wooden boards}
{127701}{}{A board broke out of a nearby structure.}
{127800}{}{Wooden boards}
{127801}{}{A board broke out of a nearby structure.}
{127900}{}{Wooden boards}
{127901}{}{A board broke out of a nearby structure.}
{128000}{}{Wooden boards}
{128001}{}{A board broke out of a nearby structure.}
{128100}{}{Wooden boards}
{128101}{}{A board broke out of a nearby structure.}
{128200}{}{Wooden boards}
{128201}{}{A board broke out of a nearby structure.}
{128300}{}{Wooden boards}
{128301}{}{A board broke out of a nearby structure.}
{128400}{}{A blocked exit to the top.}
{128401}{}{This rubble is impossible to clear.}
{128500}{}{Machines}
{128501}{}{A wall of two cars.}
{128600}{}{Table}
{128601}{}{An interesting design solution - a table made of the car hood.}
{128700}{}{Table}
{128701}{}{A table made of the hood of a car.}
{128800}{}{Car}
{128801}{}{This baby won't be riding the highway anymore.}
{128900}{}{Car}
{128901}{}{This car is long gone.}
{129000}{}{Machines}
{129001}{}{A wall of two cars.}
{129100}{}{Car}
{129101}{}{An old, dilapidated car.}
{129200}{}{Car}
{129201}{}{It is unlikely to move anywhere at all now.}
{129300}{}{Elevator cab.}
{129400}{}{Beam}
{129401}{}{Supporting structure.}
{129500}{}{Beam}
{129501}{}{Supporting structure.}
{129600}{}{Beam}
{129601}{}{Supporting structure.}
{129700}{}{Rope}
{129800}{}{a way down}
{129900}{}{Floor}
{130000}{}{Wooden boards}
{130001}{}{A board broke out of a nearby structure.}
{130100}{}{Wooden boards}
{130101}{}{A board broke out of a nearby structure.}
{130200}{}{Wooden boards}
{130201}{}{A board broke out of a nearby structure.}
{130300}{}{Wooden boards}
{130301}{}{A board broke out of a nearby structure.}
{130400}{}{Floor}
{130500}{}{Car}
{130501}{}{All that's left of it is a useless pile of rusty metal.}
{130600}{}{Beam}
{130601}{}{Supporting structure.}
{130700}{}{Beam}
{130701}{}{Supporting structure.}
{130800}{}{Beam}
{130801}{}{Supporting structure.}
{130900}{}{Beam}
{130901}{}{Supporting structure.}
{131000}{}{Beam}
{131001}{}{Support structure. You wonder if a grown man can be hung on it.}
{131100}{}{Beam}
{131101}{}{Supporting structure.}
{131200}{}{Floor}
{131300}{}{Junk}
{131301}{}{Useless junk.}
{131400}{}{Floor}
{131500}{}{Floor}
{131600}{}{Floor}
{131700}{}{Car}
{131701}{}{This baby won't be riding the highways anymore.}
{131800}{}{Car}
{131801}{}{Just a rusty bucket of nuts now.}
{131900}{}{Car}
{131901}{}{This one will never go anywhere.}
{132000}{}{Utility}
{132001}{}{There are pipes, cables, other equipment.}
{132100}{}{Utility}
{132101}{}{There are pipes, cables, other equipment.}
{132200}{}{Utility}
{132201}{}{There are pipes, cables, other equipment.}
{132300}{}{Utility}
{132301}{}{There are pipes, cables, other equipment.}
{132400}{}{Car}
{132401}{}{All that junk can do now is rust.}
{132500}{}{Machines}
{132501}{}{A pile of wrecked cars.}
{132600}{}{Car}
{132601}{}{Rusty garbage, gradually absorbed by other garbage.}
{132700}{}{The lighting fixture.}
{132701}{}{The dim lighting of the parking lot.}
{132800}{}{The lighting fixture.}
{132801}{}{The dim lighting of the parking lot.}
{132900}{}{The lighting fixture.}
{132901}{}{The fixture doesn't shine, apparently because it's broken.}
{133000}{}{Cave entrance}
{133100}{}{Floor}
{133200}{}{Floor}
{133300}{}{Floor}
{133400}{}{Floor}
{133500}{}{Terminal}
{133501}{}{Used to activate the elevator.}
{133600}{}{Terminal}
{133601}{}{Used to activate the elevator.}
{133700}{}{Control Room Door}
{133701}{}{Very massive and imposing. Probably it could take years to try opening it.}
{133800}{}{Vault City Gate}
{133900}{}{Wall}
{134000}{}{Wall}
{134100}{}{Wall}
{134200}{}{Wall}
{134300}{}{Wall}
{134400}{}{Wall}
{134500}{}{Wall}
{134600}{}{Bench}
{134601}{}{A wide concrete bench.}
{134700}{}{Door}
{134800}{}{A door, forcibly opened.}
{134900}{}{Shards of Door.}
{135000}{}{Wall}
{135100}{}{Wall}
{135200}{}{Wall}
{135300}{}{Wall}
{135400}{}{Wall}
{135500}{}{Wall}
{135600}{}{Wall}
{135700}{}{Wall}
{135800}{}{Door}
{135900}{}{Wall}
{136000}{}{Wall}
{136100}{}{Wall}
{136200}{}{Wall}
{136300}{}{Plant}
{136301}{}{Some kind of desert plant.}
{136400}{}{Floor}
{136500}{}{Floor}
{136600}{}{Floor}
{136700}{}{Hovitaser... Hmmm... Or something else...}
{136701}{}{This strange cannon has been left here since before the war. What an end to life's journey.}
{136800}{}{Escarpment}
{136900}{}{Crossing}
{137000}{}{Crate}
{137001}{}{Broken crate with hinges on the side.}
{137100}{}{Floor}
{137200}{}{Floor}
{137300}{}{Crate}
{137301}{}{A very heavy metal crate with some junk in it.}
{137400}{}{Crate}
{137401}{}{A very heavy metal crate with some junk in it.}
{137500}{}{Crate}
{137501}{}{A heavy but empty metal crate.}
{137600}{}{Crate}
{137601}{}{A very heavy metal crate with some junk in it.}
{137700}{}{A Verti...what?}
{137701}{}{NEED A LONG DESCRIPTION.}
{137800}{}{Hole}
{137801}{}{Large hole in the ground.}
{137900}{}{Tower}
{137901}{}{A security tower with a machine gun.}
{138000}{}{Hole}
{138100}{}{Hole}
{138200}{}{Hole}
{138300}{}{Hole}
{138400}{}{Hole}
{138500}{}{Hole}
{138600}{}{Light}
{138700}{}{Door}
{138800}{}{Door}
{138900}{}{Door}
{139000}{}{Door}
{139100}{}{Door}
{139200}{}{Door}
{139300}{}{Crate}
{139301}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139400}{}{Crate}
{139401}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139500}{}{Crate}
{139501}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139600}{}{Crate}
{139601}{}{This roomy wooden crate held a bunch of unnecessary junk.}
{139700}{}{Crate}
{139701}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{139800}{}{Crate}
{139801}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{139900}{}{Crate}
{139901}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{140000}{}{Crate}
{140001}{}{It's amazing what useless junk people sometimes store in sturdy metal crates.}
{140100}{}{Shadow}
{140200}{}{Poster}
{140201}{}{The poster has survived quite well.}
{140300}{}{Car}
{140301}{}{An old, dilapidated car.}
{140400}{}{Car}
{140401}{}{Not even an ingenious mechanic could make this broken machine move on its own.}
{140500}{}{Big car}
{140501}{}{An old, dilapidated car.}
{140600}{}{Pole}
{140700}{}{Wall}
{140800}{}{Wall}
{140900}{}{Wall}
{141000}{}{Dispatcher's Cockpit.}
{141001}{}{The dispatcher from here used to court traffic. Now there is no traffic and no dispatcher.}
{141100}{}{Dispatcher's Cockpit.}
{141101}{}{The dispatcher from here used to court traffic. Now there is no traffic and no dispatcher.}
{141200}{}{Pole}
{141300}{}{Renesco Pharmacy sign.}
{141400}{}{Pole}
{141500}{}{Pole}
{141600}{}{Radio tower}
{141601}{}{Homemade radio tower.}
{141700}{}{Workshop Door.}
{141800}{}{Workshop Door.}
{141900}{}{Wall}
{142000}{}{Wall}
{142100}{}{Wall}
{142200}{}{Wall}
{142300}{}{Wall}
{142400}{}{Wall}
{142500}{}{Wall}
{142600}{}{Wall}
{142601}{}{Wall}
{142700}{}{Wall}
{142800}{}{Wall}
{142900}{}{Wall}
{143000}{}{Wall}
{143100}{}{Wall}
{143200}{}{Wall}
{143300}{}{Rope}
{143301}{}{You can climb the wall with this rope.}
{143400}{}{Door}
{143401}{}{The door that leads to the enclosed part of the terrace.}
{143500}{}{Door}
{143600}{}{Asphalt}
{143700}{}{Asphalt}
{143800}{}{Asphalt}
{143900}{}{Asphalt}
{144000}{}{Asphalt}
{144100}{}{Asphalt}
{144200}{}{Vent}
{144201}{}{Part of the ventilation system.}
{144300}{}{Vent}
{144301}{}{Part of the ventilation system.}
{144400}{}{Vent}
{144401}{}{Part of the ventilation system.}
{144500}{}{Vent}
{144501}{}{Part of the ventilation system.}
{144600}{}{Vent}
{144601}{}{Part of the ventilation system.}
{144700}{}{Vent}
{144701}{}{Part of the ventilation system.}
{144800}{}{Asphalt}
{144900}{}{Door}
{145000}{}{Pipes}
{145001}{}{Huge pipes leading under the water.}
{145100}{}{Pipes}
{145101}{}{Huge pipes leading under the water.}
{145200}{}{Pipes}
{145201}{}{Huge pipes leading under the water.}
{145300}{}{Pipes}
{145301}{}{Huge pipes leading under the water.}
{145400}{}{Pipes}
{145401}{}{Huge pipes leading under the water.}
{145500}{}{Pipes}
{145501}{}{Huge pipes leading under the water.}
{145600}{}{Pipes}
{145601}{}{Huge pipes leading under the water.}
{145700}{}{Pipes}
{145701}{}{Huge pipes leading under the water.}
{145800}{}{Escarpment}
{145900}{}{Pipes}
{145901}{}{Huge pipes leading under the water.}
{146000}{}{Pipes}
{146001}{}{Huge pipes leading under the water.}
{146100}{}{Pipes}
{146101}{}{Huge pipes leading under the water.}
{146200}{}{Things}
{146201}{}{A pile of useless junk.}
{146300}{}{Things}
{146301}{}{A pile of useless junk.}
{146400}{}{A huge water tank.}
{146401}{}{Holes in the tank covered with metal plates.}
{146500}{}{A huge water tank.}
{146501}{}{Holes in the tank covered with metal plates.}
{146600}{}{Door in a fence.}
{146700}{}{Door in a fence.}
{146800}{}{The commander's seat.}
{146801}{}{This is where the Overseer usually sits.}
{146900}{}{Stones}
{146901}{}{A pile of rocks and dirt.}
{147000}{}{Stones}
{147001}{}{A pile of rocks and dirt.}
{147100}{}{Stones}
{147101}{}{A pile of rocks and dirt.}
{147200}{}{Stones}
{147201}{}{A pile of rocks and dirt.}
{147300}{}{Stones}
{147301}{}{A pile of rocks and dirt.}
{147400}{}{Stones}
{147401}{}{A pile of rocks and dirt.}
{147500}{}{A huge water tank.}
{147501}{}{Holes in the tank covered with metal plates.}
{147600}{}{Pipes}
{147601}{}{A section of massive pipe.}
{147700}{}{Land}
{147701}{}{The ground to the top floor is taken from here.}
{147800}{}{Wall}
{147900}{}{Door}
{148000}{}{Door}
{148100}{}{Pipe}
{148101}{}{A section of massive pipe.}
{148200}{}{Wall}
{148300}{}{Water}
{148400}{}{Things}
{148401}{}{There's nothing of value here.}
{148500}{}{Floor}
{148600}{}{Mouth of Hades}
{148601}{}{It looks disgusting and scary. Smells correspondingly.}
{148700}{}{Wall}
{148800}{}{The Abyss}
{148801}{}{The darkness is impenetrable.}
{148900}{}{Devices}
{148901}{}{Devices to keep the boiler running.}
{149000}{}{Devices}
{149001}{}{Devices to keep the boiler running.}
{149100}{}{Door}
{149200}{}{Door}
{149201}{}{This door is very poorly preserved.}
{149300}{}{Tipped bed.}
{149301}{}{Tattered bed with springs sticking out.}
{149400}{}{Tipped bed.}
{149401}{}{Looks like this bed has served its purpose.}
{149500}{}{Junk}
{149501}{}{Some machinery parts.}
{149600}{}{Junk}
{149601}{}{Useless junk.}
{149700}{}{Junk}
{149701}{}{Broken bottles and other debris.}
{149800}{}{Junk}
{149801}{}{Parts of old crates.}
{149900}{}{Junk}
{149901}{}{Three empty drawers.}
{150000}{}{Pattern}
{150001}{}{The shaped pattern on the wall.}
{150100}{}{Pattern}
{150101}{}{The shaped pattern on the wall.}
{150200}{}{Floor}
{150300}{}{Floor}
{150400}{}{Boxes}
{150401}{}{Apparently, someone inspected them before you - there's nothing of value there.}
{150500}{}{Machinery}
{150600}{}{Hay}
{150601}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{150700}{}{Hay}
{150701}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{150800}{}{Hay}
{150801}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{150900}{}{Hay}
{150901}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151000}{}{Hay}
{151001}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151100}{}{Hay}
{151101}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151200}{}{Hay}
{151201}{}{Making hay from dry desert grass is pretty easy - you just have to collect it.}
{151300}{}{Junk}
{151301}{}{Boxes, boxes, something else. But absolutely nothing useful.}
{151400}{}{Debris}
{151401}{}{The ruined walls of a building.}
{151500}{}{Debris}
{151501}{}{The ruined walls of a building.}
{151600}{}{Debris}
{151601}{}{The ruined walls of a building.}
{151700}{}{Debris}
{151701}{}{The ruined walls of a building.}
{151800}{}{Door}
{151801}{}{A door from a closet.}
{151900}{}{Door}
{151901}{}{A door from a closet.}
{152000}{}{Pipe}
{152001}{}{Part of a heavy pipe.}
{152100}{}{Pipe}
{152101}{}{Part of a heavy pipe.}
{152200}{}{Pipe}
{152201}{}{Part of a heavy pipe.}
{152300}{}{Pipe}
{152301}{}{Part of a heavy pipe.}
{152400}{}{Crate}
{152401}{}{A large empty box of dry wood.}
{152500}{}{Crate}
{152501}{}{A large empty box of dry wood.}
{152600}{}{Crate}
{152601}{}{A large empty box of dry wood.}
{152700}{}{Pipe}
{152800}{}{Pipe}
{152900}{}{Parts of the box.}
{153000}{}{Parts of the box.}
{153100}{}{Door}
{153101}{}{The door leading into the arena.}
{153200}{}{Door}
{153201}{}{In front of you is a standard door.}
{153300}{}{Door}
{153301}{}{In front of you is a standard door.}
{153400}{}{Door}
{153401}{}{The door leading into the arena.}
{153500}{}{Door}
{153501}{}{In front of you is a standard door.}
{153600}{}{Door}
{153601}{}{In front of you is a standard door.}
{153700}{}{The factory building.}
{153800}{}{Wall}
{153900}{}{Wall}
{154000}{}{Toilet}
{154001}{}{There's a horrible smell coming from it.}
{154100}{}{Wall}
{154200}{}{Pipe}
{154201}{}{Rusted in several places.}
{154300}{}{Pipe}
{154301}{}{Rusted in several places.}
{154400}{}{Toilet}
{154401}{}{This is where the pipes and other equipment go.}
{154500}{}{Utility}
{154501}{}{This is where the pipes and other equipment go.}
{154600}{}{Utility}
{154601}{}{This is where the pipes and other equipment go.}
{154700}{}{Rags}
{154701}{}{Stinky old bed.}
{154800}{}{A force field}
{154900}{}{A force field.}
{155000}{}{An organ removal device.}
{155001}{}{The latest model in the surgical DIY series. Removes organs at the push of a button.}
{155100}{}{Bed}
{155101}{}{It's uncomfortable to even stand next to it, and the thought of lying down makes you nauseous.}
{155200}{}{Rags}
{155201}{}{Stinky old bed.}
{155300}{}{Bed}
{155301}{}{It's uncomfortable to even stand next to it, and the thought of lying down makes you nauseous.}
{155400}{}{Rags}
{155401}{}{Perhaps it was a bed, but you're not sure.}
{155500}{}{Wall}
{155501}{}{Pipes on tattered walls.}
{155600}{}{Junk}
{155601}{}{Broken table.}
{155700}{}{Junk}
{155701}{}{Some kind of trash.}
{155800}{}{Electric box}
{155801}{}{The electrical box is used to distribute electricity.}
{155900}{}{Pipes}
{155901}{}{A whole assembly of pipes.}
{156000}{}{Fence}
{156001}{}{A structure made of rotten wood.}
{156100}{}{Fence}
{156101}{}{A structure made of rotten wood.}
{156200}{}{Pool of water}
{156201}{}{There is more dirt than water.}
{156300}{}{Pool of water}
{156301}{}{There is more dirt than water.}
{156400}{}{Pool of water}
{156401}{}{There is more dirt than water.}
{156500}{}{Fence}
{156501}{}{A structure made of rotten wood.}
{156600}{}{Pool of water}
{156601}{}{There is more dirt than water.}
{156700}{}{Destroyed wall.}
{156800}{}{Destroyed wall.}
{156900}{}{Wall}
{157000}{}{Wall}
{157100}{}{Floor}
{157200}{}{Floor}
{157300}{}{Door}
{157301}{}{A door with a small window.}
{157400}{}{Door}
{157401}{}{A solid door.}
{157500}{}{Door}
{157600}{}{Door}
{157700}{}{Part of a car}
{157701}{}{Looks like an engine ripped out of a car.}
{157800}{}{Bull's head.}
{157801}{}{A bull in a hat peeking out of a tin can. A logo of the "Happy bull" factory.}
{157900}{}{Wall}
{157901}{}{Half-destroyed wall.}
{158000}{}{Hole}
{158001}{}{There is a hole in the floor in front of you.}
{158100}{}{Rocks}
{158101}{}{Look impregnable.}
{158200}{}{Rocks}
{158201}{}{Look impregnable.}
{158300}{}{Rocks}
{158301}{}{Look impregnable.}
{158400}{}{Beam}
{158401}{}{A moldy, rotten wooden beam.}
{158500}{}{Damaged wall.}
{158600}{}{Car}
{158601}{}{An old, dilapidated car.}
{158700}{}{Fence}
{158701}{}{A structure made of rotten wood.}
{158800}{}{Damaged wall.}
{158900}{}{Wall}
{159000}{}{Damaged wall.}
{159100}{}{Damaged wall.}
{159200}{}{Damaged wall.}
{159300}{}{Pipes}
{159301}{}{A section of heavy pipe.}
{159400}{}{Pipes}
{159401}{}{A section of heavy pipe.}
{159500}{}{Damaged wall.}
{159600}{}{Wall}
{159700}{}{Pipes}
{159701}{}{Slimy, mold-covered pipes.}
{159800}{}{Pipes}
{159801}{}{Slimy, mold-covered pipes.}
{159900}{}{Wall}
{160000}{}{Floor}
{160100}{}{Car}
{160101}{}{An old, dilapidated car.}
{160200}{}{Parts of the box.}
{160201}{}{Dry wood box walls.}
{160300}{}{Trough}
{160301}{}{An open container of dirty water.}
{160400}{}{Trough}
{160401}{}{An open container of dirty water.}
{160500}{}{Parts of the box.}
{160501}{}{Dry wood box walls.}
{160600}{}{Factory}
{160601}{}{Factory building.}
{160700}{}{Factory}
{160701}{}{Factory building.}
{160800}{}{Factory}
{160801}{}{Factory building.}
{160900}{}{Factory}
{160901}{}{Factory building.}
{161000}{}{Floor}
{161100}{}{Bed}
{161101}{}{An old stinky floor bed and some trash.}
{161200}{}{Bed}
{161201}{}{Looks like something is crawling on it.}
{161300}{}{Factory}
{161301}{}{Factory building.}
{161400}{}{Factory}
{161401}{}{Factory building.}
{161500}{}{Bed}
{161501}{}{Stinky old bed.}
{161600}{}{Pillow}
{161601}{}{Very dirty.}
{161700}{}{Bed}
{161701}{}{If you lie down on one, you can get some nasty stuff.}
{161800}{}{Bed}
{161801}{}{Stinky old bed.}
{161900}{}{Parts of the fence}
{161901}{}{Parts of the factory fence.}
{162000}{}{Makeshift podium}
{162001}{}{A stage for giving speeches. It is crudely assembled from planks.}
{162100}{}{Parts of the fence}
{162101}{}{Parts of the factory fence.}
{162200}{}{Bed}
{162201}{}{A very dirty, smelly, stinky floor bed.}
{162300}{}{Bed}
{162301}{}{Stinky old bed.}
{162400}{}{Bed}
{162401}{}{There's definitely fungus on it. And mold.}
{162500}{}{Pipes}
{162501}{}{A section of massive pipe.}
{162600}{}{Utility}
{162601}{}{There are pipes, cables, other equipment.}
{162700}{}{Pipes}
{162701}{}{A section of massive pipe.}
{162800}{}{Barrel}
{162801}{}{An empty wooden barrel.}
{162900}{}{Barrel}
{162901}{}{An empty wooden barrel.}
{163000}{}{Damaged wall.}
{163100}{}{Pipes}
{163101}{}{A section of massive pipe.}
{163200}{}{Pipes}
{163201}{}{A section of massive pipe.}
{163300}{}{Half-destroyed wall.}
{163400}{}{Shelves of medicine.}
{163401}{}{You don't know the purpose of these medications.}
{163500}{}{Shelves of medicine.}
{163501}{}{You don't know the purpose of these medications.}
{163600}{}{Barrel}
{163601}{}{Empty wooden barrel.}
{163700}{}{Barrels}
{163701}{}{Barrels stacked on top of each other.}
{163800}{}{Barrels}
{163801}{}{Barrels stacked on top of each other.}
{163900}{}{Parts of the fence}
{163901}{}{A board broke out of a fence.}
{164000}{}{Tent}
{164001}{}{Rolled up tent}
{164100}{}{Parts of the fence}
{164101}{}{A board broke out of a fence.}
{164200}{}{Parts of the fence}
{164201}{}{A board broke out of a fence.}
{164300}{}{Machinery}
{164301}{}{Intended for handling various materials.}
{164400}{}{Machinery}
{164401}{}{Intended for handling various materials.}
{164500}{}{stairs down}
{164600}{}{stairs up}
{164601}{}{This stairway leads up.}
{164700}{}{Entrance to the station}
{164701}{}{The stairs end in the darkness.}
{164800}{}{stairs down}
{164801}{}{The stairway leads into the darkness.}
{164900}{}{Parts of the fence}
{164901}{}{A board broke out of a fence.}
{165000}{}{Parts of the fence}
{165001}{}{A board broke out of a fence.}
{165100}{}{Parts of the fence}
{165101}{}{A board broke out of a fence.}
{165200}{}{stairs up}
{165201}{}{This stairway leads up.}
{165300}{}{Sandbags}
{165301}{}{Military fortification.}
{165400}{}{Sandbags}
{165401}{}{Military fortification.}
{165500}{}{Shaft elevator}
{165600}{}{Beam}
{165700}{}{Parts of the fence}
{165701}{}{A board broke out of a fence.}
{165800}{}{Stones}
{165900}{}{Parts of the fence}
{165901}{}{A board broke out of a fence.}
{166000}{}{Passageway}
{166100}{}{Fence}
{166101}{}{A structure made of rotten wood.}
{166200}{}{Pole}
{166201}{}{Supporting structure.}
{166300}{}{Pole}
{166301}{}{Supporting structure.}
{166400}{}{Pole}
{166401}{}{Supporting structure.}
{166500}{}{Pole}
{166501}{}{Supporting structure.}
{166600}{}{Pole}
{166601}{}{Supporting structure.}
{166700}{}{Pole}
{166701}{}{Supporting structure.}
{166800}{}{Pole}
{166801}{}{Supporting structure.}
{166900}{}{Hole}
{167000}{}{Pole}
{167001}{}{Supporting structure.}
{167100}{}{Hole}
{167200}{}{Barrier}
{167201}{}{Rag partition.}
{167300}{}{Barrier}
{167301}{}{Rag partition.}
{167400}{}{Half-destroyed wall.}
{167500}{}{A wall that has been built up.}
{167600}{}{Part of the fence.}
{167601}{}{A board broke out of a fence.}
{167700}{}{Barrier}
{167701}{}{Rag partition.}
{167800}{}{Barrier}
{167801}{}{Rag partition.}
{167900}{}{Hole}
{168000}{}{Barrier}
{168001}{}{Rag partition.}
{168100}{}{Bed}
{168101}{}{Not worth resting here.}
{168200}{}{Cylinders}
{168201}{}{Some kind of substance inside.}
{168300}{}{Cylinders}
{168301}{}{Some kind of substance inside.}
{168400}{}{Tile}
{168500}{}{Shaft elevator}
{168600}{}{Tile}
{168700}{}{Tile}
{168800}{}{Half-destroyed wall.}
{168900}{}{Elevator}
{169000}{}{Elevator}
{169100}{}{Half-destroyed wall.}
{169200}{}{Half-destroyed wall.}
{169300}{}{Hole}
{169400}{}{Corner of the wall}
{169500}{}{Hole}
{169600}{}{Hole}
{169700}{}{Things}
{169701}{}{A pile of useless junk.}
{169800}{}{Barrier}
{169801}{}{Rag partition.}
{169900}{}{Barrier}
{169901}{}{Rag partition.}
{170000}{}{Half-destroyed wall.}
{170100}{}{Broken pole}
{170200}{}{Barrier}
{170201}{}{Rag partition.}
{170300}{}{Barrier}
{170301}{}{Rag partition.}
{170400}{}{Barrier}
{170401}{}{Rag partition.}
{170500}{}{Pole}
{170501}{}{Supporting structure.}
{170600}{}{Shelves.}
{170601}{}{Unfortunately, you have nothing to gain here.}
{170700}{}{Shelves.}
{170701}{}{There's nothing of value here.}
{170800}{}{Shelves.}
{170900}{}{Door}
{171000}{}{Door}
{171100}{}{Column}
{171101}{}{A decorative structure.}
{171200}{}{Column}
{171201}{}{A decorative structure.}
{171300}{}{Decorated image}
{171301}{}{The face of the portrait is taped over with another face, neatly carved out of a photograph. You recognize one of the Livos dwellers.}
{171400}{}{Decorated image}
{171401}{}{Looking at this image makes you think that art can be extremely strange.}
{171500}{}{Decorated image}
{171501}{}{It serves a purely aesthetic function.}
{171600}{}{Decorated image}
{171601}{}{You are not a fan of this kind of painting.}
{171700}{}{Decorated image}
{171701}{}{The locals seem to appreciate art.}
{171800}{}{Decorated image}
{171801}{}{You are not a fan of this kind of painting.}
{171900}{}{Decorated image}
{171901}{}{The face of the portrait is taped over with another face, neatly carved out of a photograph. You recognize one of the Livos dwellers.}
{172000}{}{Decorated image}
{172001}{}{The locals seem to appreciate art.}
{172100}{}{Bulletproof glass}
{172200}{}{Bulletproof glass}
{172300}{}{Bulletproof glass}
{172400}{}{Decorated image}
{172401}{}{You are not a fan of this kind of painting.}
{172500}{}{Decorated image}
{172501}{}{The locals seem to appreciate art.}
{172600}{}{Stone}
{172601}{}{Huge stone with a flat facet. Very heavy.}
{172700}{}{Stone}
{172701}{}{A hard rock.}
{172800}{}{Stone}
{172801}{}{It seems to be shaped like a hat. You can also sit on it.}
{172900}{}{Stone}
{172901}{}{The stone is bizarrely shaped.}
{173000}{}{Crate}
{173001}{}{Nothing interesting about this object.}
{173100}{}{Box parts.}
{173101}{}{The wall of the wooden box.}
{173200}{}{Box parts.}
{173201}{}{The wall of the wooden box.}
{173300}{}{Box parts.}
{173301}{}{The wall of the wooden box.}
{173400}{}{Floor}
{173500}{}{Floor}
{173600}{}{Floor}
{173700}{}{Exit}
{173800}{}{A table with a candle.}
{173801}{}{Dirty table illuminated by a candle flame.}
{173900}{}{Floor}
{174000}{}{Things}
{174001}{}{A pile of useless junk.}
{174100}{}{Pool of water}
{174101}{}{There is more dirt than water.}
{174200}{}{Floor}
{174300}{}{Pole}
{174301}{}{Supporting structure.}
{174400}{}{Stool}
{174401}{}{An old and completely ordinary piece of furniture.}
{174500}{}{Table}
{174501}{}{A table with a dirty, torn tablecloth and food scraps.}
{174600}{}{Tile}
{174700}{}{Tile}
{174800}{}{Rocks}
{174801}{}{Look impregnable.}
{174900}{}{Part of the fence.}
{174901}{}{A board broke out of a fence.}
{175000}{}{Water cisterns.}
{175001}{}{Large, rusty water tanks.}
{175100}{}{Pool of water}
{175101}{}{There is more dirt than water.}
{175200}{}{Decorated image}
{175201}{}{You study the image for a while, but it does not become any clearer.}
{175300}{}{Decorated image}
{175301}{}{It remains a mystery to you what the author wanted to say with this work.}
{175400}{}{Toilet}
{175401}{}{In excellent condition.}
{175500}{}{Cross}
{175600}{}{Well}
{175601}{}{A structure for extracting water.}
{175700}{}{Pipes}
{175701}{}{A section of massive pipe.}
{175800}{}{Water cisterns.}
{175801}{}{Large, rusty water tanks.}
{175900}{}{Pipes}
{175901}{}{There are pipes, cables, other equipment.}
{176000}{}{Pipes}
{176001}{}{Niche for the outlet of some pipes and other utilities.}
{176100}{}{Pipe}
{176101}{}{A section of massive pipe.}
{176200}{}{Pipes}
{176201}{}{A section of massive pipe.}
{176300}{}{Pipes}
{176301}{}{A section of massive pipe.}
{176400}{}{Pipes}
{176401}{}{A section of massive pipe.}
{176500}{}{Pipes}
{176501}{}{A section of massive pipe.}
{176600}{}{Pipes}
{176601}{}{A section of massive pipe.}
{176700}{}{Pipes}
{176701}{}{A section of massive pipe.}
{176800}{}{Pipes}
{176801}{}{A section of massive pipe.}
{176900}{}{Pipes}
{176901}{}{A section of massive pipe.}
{177000}{}{Pipes}
{177001}{}{A section of massive pipe.}
{177100}{}{Pipes}
{177101}{}{A section of massive pipe.}
{177200}{}{The descent to the water.}
{177300}{}{Water}
{177400}{}{Water}
{177500}{}{Water}
{177600}{}{Water}
{177700}{}{Pipes}
{177701}{}{A section of massive pipe.}
{177800}{}{Bed}
{177801}{}{Not the cleanest recreational item.}
{177900}{}{Fire}
{177901}{}{You're not going to look at it forever, are you?}
{178000}{}{Bed}
{178001}{}{Seems like only someone who doesn't feel smells could sleep on it.}
{178100}{}{Bed}
{178101}{}{Seems like only someone who doesn't feel smells could sleep on it.}
{178200}{}{Bed}
{178201}{}{It looks like it's already rotten.}
{178300}{}{Bed}
{178301}{}{It's an old, stinking bed.}
{178400}{}{Bed}
{178401}{}{It's no time to rest, much less on it.}
{178500}{}{Floor}
{178600}{}{Floor}
{178700}{}{There's some trash in the water.}
{178701}{}{Something seems to be leaked around.}
{178800}{}{Wagon}
{178801}{}{Constructed from a car.}
{178900}{}{Wagon}
{178901}{}{Constructed from a car.}
{179000}{}{Car}
{179001}{}{An old, dilapidated car.}
{179100}{}{Tools}
{179101}{}{Various tools, but they are not usable.}
{179200}{}{Tools}
{179201}{}{Various tools, but they are not usable.}
{179300}{}{Water}
{179301}{}{Very dirty. Can't see anything through the mud.}
{179400}{}{Water}
{179401}{}{Very dirty. Can't see anything through the mud.}
{179500}{}{Escarpment}
{179501}{}{There's only water. You don't want to swim in it at all.}
{179600}{}{Escarpment}
{179601}{}{There's only water. You don't want to swim in it at all.}
{179700}{}{Escarpment}
{179701}{}{There's only water.}
{179800}{}{Escarpment}
{179801}{}{There's only water.}
{179900}{}{Grate}
{179901}{}{Sewer grate.}
{180000}{}{Grate}
{180001}{}{Sewer grate.}
{180100}{}{Escarpment}
{180101}{}{There's only water.}
{180200}{}{Escarpment}
{180300}{}{Stones}
{180400}{}{Crate}
{180500}{}{Lights}
{180600}{}{Spikes}
{180601}{}{Sharp spikes, will easily puncture your foot.}
{180700}{}{Exit}
{180800}{}{Barrier}
{180801}{}{Rag partition.}
{180900}{}{Barrier}
{180901}{}{Rag partition.}
{181000}{}{Barrier}
{181001}{}{Rag partition.}
{181100}{}{Water cisterns.}
{181101}{}{Large, rusty water tanks.}
{181200}{}{Barrier}
{181201}{}{Rag partition.}
{181300}{}{Exit}
{181301}{}{Leads to darkness.}
{181400}{}{Stove}
{181500}{}{Barrier}
{181501}{}{Rag partition.}
{181600}{}{Barrier}
{181601}{}{Rag partition.}
{181700}{}{Bar}
{181800}{}{Door}
{181801}{}{Leads to the hotel's lobby.}
{181900}{}{Door}
{182000}{}{Blood}
{182001}{}{Somebody died here quite recently.}
{182100}{}{Blood}
{182101}{}{Not the freshest.}
{182200}{}{Blood}
{182201}{}{Mother always told you that this liquid should be INSIDE, not outside.}
{182300}{}{Blood}
{182301}{}{Looks like someone's bones are in this puddle.}
{182400}{}{Blood}
{182401}{}{Mother always told you that this liquid should be INSIDE, not outside.}
{182500}{}{Bones and guts}
{182501}{}{The mortal remains that smell of fresh blood.}
{182600}{}{Rocks}
{182601}{}{Look impregnable.}
{182700}{}{Rocks}
{182701}{}{Look impregnable.}
{182800}{}{Rocks}
{182801}{}{Look impregnable.}
{182900}{}{Rocks}
{182901}{}{Look impregnable.}
{183000}{}{Rocks}
{183001}{}{Look impregnable.}
{183100}{}{Rocks}
{183101}{}{Look impregnable.}
{183200}{}{Rocks}
{183201}{}{Look impregnable.}
{183300}{}{Rocks}
{183301}{}{Look impregnable.}
{183400}{}{Rocks}
{183401}{}{Look impregnable.}
{183500}{}{a staircase}
{183501}{}{The steps form a wide staircase.}
{183600}{}{Blood}
{183601}{}{The blood has already had time to soak in.}
{183700}{}{Blood, guts, bones.}
{183701}{}{You see someone's rich inner world in front of you.}
{183800}{}{Tent}
{183801}{}{Used for sleeping, resting, sheltering from the weather.}
{183900}{}{Rocks}
{183901}{}{Look impregnable.}
{184000}{}{Rocks}
{184001}{}{Look impregnable.}
{184100}{}{Tent}
{184101}{}{Used for sleeping, resting, sheltering from the weather.}
{184200}{}{Tent}
{184201}{}{Used for sleeping, resting, sheltering from the weather.}
{184300}{}{Tent}
{184301}{}{Used for sleeping, resting, sheltering from the weather.}
{184400}{}{a way down}
{184500}{}{Bed}
{184501}{}{When you see this bed, the desire to lie down instantly disappears.}
{184600}{}{Fence}
{184700}{}{Corner of the wall}
{184800}{}{Pole}
{184801}{}{Supporting structure.}
{184900}{}{Barrel}
{184901}{}{Metal barrel.}
{185000}{}{Barrel}
{185001}{}{Metal barrel.}
{185100}{}{Steam}
{185200}{}{Barrier}
{185201}{}{Emergency sign.}
{185300}{}{Junk}
{185301}{}{Various machine parts, but nothing useful.}
{185400}{}{Junk}
{185401}{}{Fence parts.}
{185500}{}{Junk}
{185501}{}{Bricks}
{185600}{}{Junk}
{185601}{}{A barrel, car tires, something else.}
{185700}{}{Junk}
{185701}{}{A useless pile of junk.}
{185800}{}{Armchair}
{185801}{}{This chair looks like it served its purpose years ago.}
{185900}{}{Doctor's Table.}
{185901}{}{Dirty desk with some trash and a calculator}
{186000}{}{Car}
{186001}{}{An old rusty car.}
{186100}{}{Crate}
{186101}{}{Nothing special, just a crate.}
{186200}{}{Garbage barrel.}
{186201}{}{Useless junk.}
{186300}{}{Tires}
{186301}{}{Car tires, nothing interesting.}
{186400}{}{Tires}
{186401}{}{Car tires, nothing interesting.}
{186500}{}{Tire}
{186501}{}{Car tire, nothing interesting.}
{186600}{}{Wagon}
{186601}{}{Constructed from a car.}
{186700}{}{Wagon}
{186701}{}{Constructed from a car.}
{186800}{}{Junk}
{186801}{}{A useless pile of junk.}
{186900}{}{Junk}
{186901}{}{A useless pile of junk.}
{187000}{}{Seat}
{187001}{}{Ripped out of a car.}
{187100}{}{Tires}
{187101}{}{Car tires, nothing interesting.}
{187200}{}{Tent}
{187201}{}{Looks like this tent has served its purpose.}
{187300}{}{Tent}
{187301}{}{Looks like this tent has served its purpose.}
{187400}{}{Car}
{187401}{}{An old, dilapidated car.}
{187500}{}{Car}
{187501}{}{No one's going anywhere with this.}
{187600}{}{Car}
{187601}{}{An old, dilapidated car.}
{187700}{}{Junk}
{187701}{}{A useless pile of junk.}
{187800}{}{Car}
{187801}{}{Now it's just a pile of worthless metal and it's not going anywhere.}
{187900}{}{Car}
{187901}{}{An old, dilapidated car.}
{188000}{}{Car}
{188001}{}{An old, dilapidated car.}
{188100}{}{Car}
{188101}{}{Now it's just a pile of worthless metal and it's not going anywhere.}
{188200}{}{Car}
{188201}{}{No one's going anywhere with this.}
{188300}{}{Junk}
{188301}{}{A useless pile of junk.}
{188400}{}{Junk}
{188401}{}{There's nothing to eat.}
{188500}{}{Junk}
{188501}{}{Looks like bricks. You don't need them at all.}
{188600}{}{Junk}
{188601}{}{A useless pile of junk.}
{188700}{}{Junk}
{188701}{}{You won't find anything of value in here.}
{188800}{}{Junk}
{188801}{}{A useless pile of junk.}
{188900}{}{Junk}
{188901}{}{You're not likely to find anything of value in here.}
{189000}{}{Things}
{189001}{}{A lot of junk. Nothing useful in here.}
{189100}{}{Junk}
{189101}{}{Bottles are empty and dirty - nothing to eat.}
{189200}{}{Car}
{189201}{}{An old, dilapidated car.}
{189300}{}{Junk}
{189301}{}{Useless junk.}
{189400}{}{Junk}
{189401}{}{Useless junk.}
{189500}{}{Shelves.}
{189501}{}{Shelves of booze.}
{189600}{}{Shelves.}
{189601}{}{Shelves of booze.}
{189700}{}{Table}
{189800}{}{Chair}
{189801}{}{The usual bar stool.}
{189900}{}{Junk}
{189901}{}{Useless garbage, carefully covered with a cloth.}
{190000}{}{Car}
{190001}{}{No one's going anywhere with this.}
{190100}{}{Car}
{190101}{}{Unlikely to be repairable.}
{190200}{}{Barrier}
{190201}{}{Rag partition.}
{190300}{}{Barrier}
{190301}{}{Rag partition.}
{190400}{}{Barrier}
{190401}{}{Rag partition.}
{190500}{}{Barrier}
{190501}{}{Rag partition.}
{190600}{}{Barrier}
{190601}{}{Rag partition.}
{190700}{}{Barrier}
{190701}{}{Rag partition.}
{190800}{}{Barrel with soil}
{190801}{}{These barrels contain fertile soil.}
{190900}{}{Barrel with soil}
{190901}{}{These barrels contain fertile soil.}
{191000}{}{Barrels of earth.}
{191001}{}{These barrels contain fertile soil.}
{191100}{}{Barrel with soil}
{191101}{}{These barrels contain fertile soil.}
{191200}{}{Barrel with soil}
{191201}{}{These barrels contain fertile soil.}
{191300}{}{Junk}
{191301}{}{You won't find anything useful there.}
{191400}{}{Junk}
{191401}{}{A useless pile of junk.}
{191500}{}{Barrel with soil}
{191501}{}{These barrels contain fertile soil.}
{191600}{}{Bed}
{191601}{}{This recliner must have been slept on for more than a year.}
{191700}{}{Bed}
{191701}{}{It seems to stink of something.}
{191800}{}{Bed}
{191801}{}{It's an old, stinking bed.}
{191900}{}{Rags}
{191901}{}{Sleeping on it is definitely no longer possible.}
{192000}{}{Floor}
{192100}{}{Floor}
{192200}{}{Floor}
{192300}{}{Door}
{192400}{}{Door}
{192500}{}{Table}
{192501}{}{Surprisingly clean enough table.}
{192600}{}{Table}
{192601}{}{The most ordinary table with some kind of tablecloth.}
{192700}{}{Table}
{192701}{}{An ordinary table with remnants of a former feast.}
{192800}{}{Table}
{192801}{}{Just a table, nothing unusual.}
{192900}{}{Table}
{192901}{}{Bottles cracked, nothing interesting.}
{193000}{}{Tank}
{193001}{}{A tank of water.}
{193100}{}{The Arena Warden's table.}
{193101}{}{Here you can learn more about the fights in the arena.}
{193200}{}{Bones}
{193201}{}{Human bones.}
{193300}{}{Bones}
{193301}{}{Human bones. This poor man died many years ago.}
{193400}{}{Bones}
{193401}{}{It was a human once.}
{193500}{}{Plant}
{193501}{}{A living green herbaceous plant.}
{193600}{}{Plant}
{193601}{}{A living green herbaceous plant.}
{193700}{}{Plant}
{193701}{}{A living green herbaceous plant.}
{193800}{}{Plant}
{193801}{}{A living green herbaceous plant.}
{193900}{}{Plant}
{193901}{}{A living green herbaceous plant.}
{194000}{}{Pole}
{194001}{}{A stripping pole.}
{194100}{}{Entrance}
{194200}{}{The building}
{194201}{}{Factory building.}
{194300}{}{The building}
{194301}{}{Factory building.}
{194400}{}{Junk}
{194401}{}{A useless pile of junk.}
{194500}{}{Box}
{194501}{}{There is absolutely nothing interesting about it.}
{194600}{}{Crate}
{194601}{}{An unremarkable box.}
{194700}{}{A sheet of iron.}
{194701}{}{A useless pile of junk.}
{194800}{}{A sheet of iron.}
{194801}{}{That won't do you any good.}
{194900}{}{A sheet of iron.}
{194901}{}{A useless pile of junk.}
{195000}{}{A sheet of iron.}
{195001}{}{That won't do you any good.}
{195100}{}{A cesspool}
{195101}{}{A great solution when you can't afford a central sewer.}
{195200}{}{A cesspool}
{195201}{}{A great solution when you can't afford a central sewer.}
{195300}{}{A cesspool}
{195301}{}{A great solution when you can't afford a central sewer.}
{195400}{}{A cesspool}
{195401}{}{A great solution when you can't afford a central sewer.}
{195500}{}{Table}
{195501}{}{A simple table.}
{195600}{}{Table}
{195601}{}{A simple table.}
{195700}{}{Rocks}
{195701}{}{Look impregnable.}
{195800}{}{Rocks}
{195801}{}{Look impregnable.}
{195900}{}{Rocks}
{195901}{}{Look impregnable.}
{196000}{}{Rocks}
{196001}{}{Look impregnable.}
{196100}{}{Rocks}
{196101}{}{Look impregnable.}
{196200}{}{Tribune}
{196201}{}{A speaker's pulpit.}
{196300}{}{Screen}
{196400}{}{Stove}
{196401}{}{A heating and cooking stove.}
{196500}{}{Stove}
{196501}{}{A heating and cooking stove.}
{196600}{}{Tile}
{196700}{}{Tile}
{196800}{}{Tile}
{196900}{}{Tile}
{197000}{}{Tile}
{197100}{}{Tile}
{197200}{}{Stones}
{197201}{}{Just a pile of stones.}
{197300}{}{Stones}
{197301}{}{Just a pile of stones.}
{197400}{}{Stones}
{197401}{}{Just a pile of stones.}
{197500}{}{Beam}
{197501}{}{The support beam of the tunnel.}
{197600}{}{Beam}
{197601}{}{The support beam of the tunnel.}
{197700}{}{Beam}
{197701}{}{The support beam of the tunnel.}
{197800}{}{Beam}
{197801}{}{The support beam of the tunnel.}
{197900}{}{Beam}
{197901}{}{The support beam of the tunnel.}
{198000}{}{Beam}
{198001}{}{The support beam of the tunnel.}
{198100}{}{Beam}
{198101}{}{The support beam of the tunnel.}
{198200}{}{Beam}
{198201}{}{The support beam of the tunnel.}
{198300}{}{Beam}
{198301}{}{The support beam of the tunnel.}
{198400}{}{Stones}
{198401}{}{No time to gather stones.}
{198500}{}{Stones}
{198501}{}{No time to gather stones.}
{198600}{}{Stones}
{198601}{}{Just a pile of stones.}
{198700}{}{Stones}
{198701}{}{Just a pile of stones.}
{198800}{}{Box}
{198801}{}{Empty old box. Not of any interest.}
{198900}{}{Junk}
{198901}{}{Useless junk.}
{199000}{}{Junk}
{199001}{}{That won't do you any good.}
{199100}{}{Junk}
{199101}{}{That won't do you any good.}
{199200}{}{Junk}
{199201}{}{Useless junk.}
{199300}{}{Junk}
{199301}{}{Unlikely to be of any use to anyone.}
{199400}{}{Junk}
{199401}{}{That won't do you any good.}
{199500}{}{Junk}
{199501}{}{A useless pile of junk.}
{199600}{}{Junk}
{199601}{}{That won't do you any good.}
{199700}{}{Junk}
{199701}{}{A useless pile of junk.}
{199800}{}{Junk}
{199801}{}{That won't do you any good.}
{199900}{}{Junk}
{199901}{}{A useless pile of junk.}
{200000}{}{Junk}
{200001}{}{A useless pile of junk.}
{200100}{}{Junk}
{200101}{}{That won't do you any good.}
{200200}{}{Generator}
{200201}{}{A device that generates electricity.}
{200300}{}{Generator}
{200301}{}{A device that generates electricity.}
{200400}{}{Pump}
{200401}{}{A hydraulic machine.}
{200500}{}{Pipe}
{200501}{}{A pipe going into the ground.}
{200600}{}{Pipe}
{200601}{}{A pipe going into the ground.}
{200700}{}{Junk}
{200701}{}{A useless pile of junk.}
{200800}{}{Junk}
{200801}{}{A useless pile of junk.}
{200900}{}{NO}
{201000}{}{a food machine}
{201001}{}{When you press the button with a "Risotto" label on it, the machine spits out a suspiciously green slimy lump.}
{201100}{}{a food machine}
{201101}{}{When you press the button with a "Shrimp flambe" label on it, the machine spews out three gooey blobs. Tastes like chewed boogers.}
{201200}{}{a clothing machine}
{201201}{}{Looks like it doesn't work as intended.}
{201300}{}{a food machine}
{201301}{}{When you press the button with a "Tortilla" label on it, the machine spits out a soggy clump. Smells like an old sock.}
{201400}{}{a food machine}
{201401}{}{When you press the button with a "Brownie" label on it, the machine spews out an odorless and tasteless slurred mush.}
{201500}{}{Board}
{201501}{}{It's just an ordinary board. You can hardly use it.}
{201600}{}{Board}
{201601}{}{It's just an ordinary board. You can hardly use it.}
{201700}{}{Board}
{201701}{}{It's just an ordinary board. You can hardly use it.}
{201800}{}{Board}
{201801}{}{It's just an ordinary board. You can hardly use it.}
{201900}{}{Board}
{201901}{}{It's just an ordinary board. You can hardly use it.}
{202000}{}{Plant}
{202001}{}{An excellent representative of Herba Vulgaris.}
{202100}{}{Plant}
{202101}{}{An excellent representative of Herba Vulgaris.}
{202200}{}{Plant}
{202201}{}{Some kind of desert plant.}
{202300}{}{Plant}
{202301}{}{An excellent representative of Herba Vulgaris.}
{202400}{}{Plant}
{202401}{}{Some kind of desert plant.}
{202500}{}{Plant}
{202501}{}{An excellent representative of Herba Vulgaris.}
{202600}{}{Plant}
{202601}{}{Some kind of desert plant.}
{202700}{}{Plant}
{202701}{}{An excellent representative of Herba Vulgaris.}
{202800}{}{Plant}
{202801}{}{An excellent representative of Herba Vulgaris.}
{202900}{}{Plant}
{202901}{}{Some kind of desert plant.}
{203000}{}{Plant}
{203001}{}{Some kind of desert plant.}
{203100}{}{Plant}
{203101}{}{An excellent representative of Herba Vulgaris.}
{203200}{}{Plant}
{203201}{}{Some kind of desert plant.}
{203300}{}{Plant}
{203301}{}{An excellent representative of Herba Vulgaris.}
{203400}{}{Plant}
{203401}{}{Some kind of desert plant.}
{203500}{}{Plant}
{203501}{}{Some kind of desert plant.}
{203600}{}{Metal sheet}
{203601}{}{Rusty and very heavy.}
{203700}{}{Metal sheet}
{203701}{}{Rusty and very heavy.}
{203800}{}{Plant}
{203801}{}{An excellent representative of Herba Vulgaris.}
{203900}{}{Plant}
{203901}{}{An excellent representative of Herba Vulgaris.}
{204000}{}{Weather vane}
{204001}{}{Flags are showing wind direction.}
{204100}{}{A stake with a skull.}
{204101}{}{You really wouldn't want to end up like that.}
{204200}{}{A stake with a skull.}
{204201}{}{A frightening sign.}
{204300}{}{A stake with a skull.}
{204301}{}{You take a closer look. Looks like this poor guy had cavities.}
{204400}{}{A stake with a skull.}
{204401}{}{Someone has taken up residence in this skull.}
{204500}{}{A stake with a skull.}
#Н/Д
{204600}{}{A stake with a skull.}
{204601}{}{Its empty eye sockets seem to be watching you.}
{204700}{}{Weather vane}
{204701}{}{Flags are showing wind direction.}
{204800}{}{Plant}
{204801}{}{Some kind of desert plant.}
{204900}{}{Plant}
{204901}{}{Some kind of desert plant.}
{205000}{}{Grass}
{205001}{}{A living green grass. You can hardly resist the temptation to chew on a blade of grass.}
{205100}{}{Grass}
{205101}{}{A living green grass. You can hardly resist the temptation to chew on a blade of grass.}
{205200}{}{Plant}
{205201}{}{A living herbaceous green plant.}
{205300}{}{Stake}
{205301}{}{Its diligently pointed end prompts in you a strong desire to keep your head on your shoulders.}
{205400}{}{Stake}
{205401}{}{You seem to guess its purpose.}
{205500}{}{Stake}
{205501}{}{You would hate to decorate your skull with this wonderful stake.}
{205600}{}{Stake}
{205601}{}{You seem to guess its purpose.}
{205700}{}{Stake}
{205701}{}{It seems to you that there is definitely something missing on this stake.}
{205800}{}{Stake}
{205801}{}{It's sharp. Looks menacing.}
{205900}{}{Stake}
{205901}{}{Someone obviously went through a lot of trouble to sharpen it.}
{206000}{}{Stake}
{206001}{}{It's sharp. Looks menacing.}
{206100}{}{Stake}
{206101}{}{It could easily stab you.}
{206200}{}{Stake}
{206201}{}{It's sharp. Looks menacing.}
{206300}{}{Blood}
{206301}{}{Dried bloody stain.}
{206400}{}{Blood}
{206401}{}{Dried bloody stain.}
{206500}{}{Blood}
{206501}{}{Looks pretty old.}
{206600}{}{Blood}
{206601}{}{Dried bloody stain.}
{206700}{}{Blood}
{206701}{}{Already dried and soaked.}
{206800}{}{Weather vane}
{206801}{}{The flag shows the direction of the wind.}
{206900}{}{Blood}
{206901}{}{You wonder whose blood this is.}
{207000}{}{Blood}
{207001}{}{These remains are several days old and smell like it.}
{207100}{}{Blood}
{207101}{}{These remains stink a lot.}
{207200}{}{Blood}
{207201}{}{Somebody was very unlucky.}
{207300}{}{Blood}
{207301}{}{You're looking at someone's inner world, and it's not the freshest.}
{207400}{}{A thing to practice beating.}
{207401}{}{It's better to practice moves on it than on real people.}
{207500}{}{A thing to practice beating.}
{207501}{}{What a face! You really want to punch it!}
{207600}{}{A thing to practice beating.}
{207601}{}{A great homemade mannequin for training.}
{207700}{}{A thing to practice beating.}
{207701}{}{Replaces the punching bag.}
{207800}{}{A thing to practice beating.}
{207801}{}{Looks like he gets it a lot.}
{207900}{}{A thing to practice beating.}
{207901}{}{The last thing you want in the world is to be in his shoes.}
{208000}{}{Blocked door.}
{208001}{}{Exit blocked.}
{208100}{}{Rock}
{208101}{}{Looks impregnable.}
{208200}{}{Poster}
{208201}{}{A faded prewar poster.}
{208300}{}{Poster}
{208301}{}{A faded prewar poster.}
{208400}{}{Poster}
{208401}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{208500}{}{Poster}
{208501}{}{A faded prewar poster.}
{208600}{}{Poster}
{208601}{}{You like to look at old posters. They preserve history.}
{208700}{}{Poster}
{208701}{}{Did this propaganda inspire anyone?}
{208800}{}{Poster}
{208801}{}{A faded prewar poster.}
{208900}{}{Poster}
{208901}{}{Did this propaganda inspire anyone?}
{209000}{}{Poster}
{209001}{}{A faded prewar poster.}
{209100}{}{Poster}
{209101}{}{A faded prewar poster.}
{209200}{}{Poster}
{209201}{}{Did this propaganda inspire anyone?}
{209300}{}{Poster}
{209301}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{209400}{}{Poster}
{209401}{}{The poster man died a long time ago.}
{209500}{}{Poster}
{209501}{}{It looks like a movie commercial. Too bad you only read about movies in books.}
{209600}{}{Poster}
{209601}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{209700}{}{Poster}
{209701}{}{A pre-war propaganda poster.}
{209800}{}{Poster}
{209801}{}{A pre-war propaganda poster.}
{209900}{}{Poster}
{209901}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{210000}{}{Poster}
{210001}{}{Too bad you don't collect vintage posters - this is a fine one.}
{210100}{}{Poster}
{210101}{}{This poster is at least 200 years old. People back then knew how to make sturdy posters.}
{210200}{}{Poster}
{210201}{}{A very old faded poster.}
{210300}{}{Poster}
{210301}{}{An old faded poster.}
{210400}{}{Poster}
{210401}{}{Too bad you don't collect vintage posters - this is a fine one.}
{210500}{}{Poster}
{210501}{}{It's at least 200 years old. Very well-preserved.}
{210600}{}{Poster}
{210601}{}{A faded prewar poster.}
{210700}{}{Poster}
{210701}{}{A faded prewar poster.}
{210800}{}{Bones}
{210801}{}{A handful of someone's bones.}
{210900}{}{Bones}
{210901}{}{Looks like ribs.}
{211000}{}{Bones}
{211001}{}{You'll end up like this someday. The existence is futile.}
{211100}{}{Bones}
{211101}{}{You'll end up like this someday. The existence is futile.}
{211200}{}{Bones}
{211201}{}{A handful of someone's bones.}
{211300}{}{Bones}
{211301}{}{A handful of someone's bones.}
{211400}{}{Bones}
{211401}{}{You'll end up like this someday. The existence is futile.}
{211500}{}{Bones}
{211501}{}{It was once something alive.}
{211600}{}{Bones}
{211601}{}{A handful of someone's bones.}
{211700}{}{Bones}
{211701}{}{It was once something alive.}
{211800}{}{Plant}
{211801}{}{Some kind of desert plant.}
{211900}{}{Plant}
{211901}{}{Some kind of desert plant.}
{212000}{}{Plant}
{212001}{}{Some kind of desert plant.}
{212100}{}{Plant}
{212101}{}{Some kind of desert plant.}
{212200}{}{Plant}
{212201}{}{Some kind of desert plant.}
{212300}{}{Plant}
{212301}{}{Some kind of desert plant.}
{212400}{}{Plant}
{212401}{}{Some kind of desert plant.}
{212500}{}{Plant}
{212501}{}{Some kind of desert plant.}
{212600}{}{Plant}
{212601}{}{Some kind of desert plant.}
{212700}{}{Plant}
{212701}{}{Some kind of desert plant.}
{212800}{}{Plant}
{212801}{}{Some kind of desert plant.}
{212900}{}{Plant}
{212901}{}{Some kind of desert plant.}
{213000}{}{Plant}
{213001}{}{Some kind of desert plant.}
{213100}{}{Bones}
{213101}{}{There won't be much more left of you.}
{213200}{}{Bones}
{213201}{}{A handful of someone's bones.}
{213300}{}{Bones}
{213301}{}{There won't be much more left of you.}
{213400}{}{Bones}
{213401}{}{Ordinary bones, there's a lot of them.}
{213500}{}{Bones}
{213501}{}{Someone's dead.}
{213600}{}{Bones}
{213601}{}{Someone's dead.}
{213700}{}{Bones}
{213701}{}{Very old bones.}
{213800}{}{Bones}
{213801}{}{These are the bones of the rarest extinct animal. Too bad you don't collect bones.}
{213900}{}{Bones}
{213901}{}{A handful of someone's bones.}
{214000}{}{Bones}
{214001}{}{Very old bones.}
{214100}{}{Stake}
{214101}{}{It's sharp. Looks menacing.}
{214200}{}{Stake}
{214201}{}{It's sharp. Looks menacing.}
{214300}{}{Stake}
{214301}{}{A pole sharpened at one end.}
{214400}{}{Stake}
{214401}{}{It's sharp. Looks menacing.}
{214500}{}{Stake}
{214501}{}{It's sharp. Looks menacing.}
{214600}{}{Stake}
{214601}{}{It's sharp. Looks menacing.}
{214700}{}{Stake}
{214701}{}{This one can pierce something.}
{214800}{}{Stake}
{214801}{}{This one can pierce something.}
{214900}{}{A broken stake.}
{215000}{}{A broken stake.}
{215100}{}{Blood}
{215101}{}{It's old dried blood.}
{215200}{}{Blood}
{215201}{}{Mother always told you that this liquid should be INSIDE, not outside.}
{215300}{}{Blood}
{215301}{}{Blood and sand.}
{215400}{}{Blood}
{215401}{}{Dried bloody stain.}
{215500}{}{Blood}
{215501}{}{Dried bloody stain.}
{215600}{}{Blood}
{215601}{}{Dried bloody stain.}
{215700}{}{Blood}
{215701}{}{You wonder whose blood it is.}
{215800}{}{Blood}
{215801}{}{Dried bloody stain.}
{215900}{}{Blood}
{215901}{}{Dried bloody stain.}
{216000}{}{Blood}
{216001}{}{Dried bloody stain.}
{216100}{}{Bones}
{216101}{}{These are the bones of the rarest extinct animal. Too bad you don't collect bones.}
{216200}{}{Bones}
{216201}{}{Someone's dead.}
{216300}{}{Bones}
{216301}{}{These bones are of no interest to you. Unless you're an osteologist, of course.}
{216400}{}{Skull}
{216401}{}{It looks like it was some kind of animal.}
{216500}{}{Bones}
{216501}{}{They seem to be very fragile.}
{216600}{}{Blood}
{216601}{}{Dried bloody stain.}
{216700}{}{Blood}
{216701}{}{Red blood, white bones - a beautiful combination of colors.}
{216800}{}{Blood}
{216801}{}{You wonder who that blood belonged to.}
{216900}{}{Blood}
{216901}{}{Dried bloody stain.}
{217000}{}{Blood}
{217001}{}{You wonder who that blood belonged to.}
{217100}{}{Shack}
{217101}{}{It reeks of blood and urine.}
{217200}{}{Shack}
{217201}{}{"And on the deserted shores stand dwellings here and there, the shelter of the wretched aborigine."}
{217300}{}{Shack}
{217301}{}{You don't want to go in there at all.}
{217400}{}{Shack}
{217401}{}{A structure of wood and dry grass.}
{217500}{}{Plant}
{217501}{}{Some kind of desert plant.}
{217600}{}{Plant}
{217601}{}{Some kind of desert plant.}
{217700}{}{Plant}
{217701}{}{Some kind of desert plant.}
{217800}{}{Plant}
{217801}{}{Some kind of desert plant.}
{217900}{}{Plant}
{217901}{}{Some kind of desert plant.}
{218000}{}{Plant}
{218001}{}{Some kind of desert plant.}
{218100}{}{Plant}
{218101}{}{Some kind of desert plant.}
{218200}{}{Plant}
{218201}{}{Some kind of desert plant.}
{218300}{}{Plant}
{218301}{}{Some kind of desert plant.}
{218400}{}{Plant}
{218401}{}{Some kind of desert plant.}
{218500}{}{Catch}
{218501}{}{Big fish here! Looks quite edible.}
{218600}{}{Tree}
{218601}{}{The trunk of a dried-out tree.}
{218700}{}{Tree}
{218701}{}{This tree can no longer be helped.}
{218800}{}{Tree}
{218801}{}{This tree looks like a carrot. An old dried gray carrot.}
{218900}{}{Tree}
{218901}{}{These dry branches are depressing.}
{219000}{}{Tree}
{219001}{}{The dry, broken trunk of a dried-up tree.}
{219100}{}{Sign}
{219101}{}{Food, water - looks like a place to eat!}
{219200}{}{Billiard table}
{219201}{}{You don't really understand how to play it, but the fabric on the table looks very worn.}
{219300}{}{Billiard table}
{219301}{}{The colored balls on the table look fun, too bad you don't know how to play.}
{219400}{}{Screen panel.}
{219401}{}{Unfortunately, it's turned off. To look at the working one would be extremely interesting.}
{219500}{}{Wall}
{219600}{}{Sofa}
{219601}{}{A piece of furniture that can provide your heel with maximum comfort.}
{219700}{}{Sofa}
{219701}{}{Looks comfortable, no time to rest here.}
{219800}{}{Screens}
{219801}{}{You wonder what can be watched on so many screens. Right now there's just white noise.}
{219900}{}{Poster}
{219901}{}{An old poster advertising a gun. No one would say no a gun like that, even now!}
{220000}{}{stairs up}
{220100}{}{stairs down}
{220200}{}{Poster}
{220201}{}{A faded old poster.}
{220300}{}{Poster}
{220301}{}{This poster is at least two hundred years old. They used to make pretty good ones back in the day!}
{220400}{}{Poster}
{220401}{}{They don't make them like that now.}
{220500}{}{Poster}
{220501}{}{You study the poster for a while. It looks like an advertisement for canned goods.}
{220600}{}{Poster}
{220601}{}{You like old posters. They preserve history.}
{220700}{}{Poster}
{220701}{}{A faded wall poster.}
{220800}{}{Poster}
{220801}{}{This poster is at least two hundred years old. They used to make pretty good ones back in the day!}
{220900}{}{Poster}
{220901}{}{Life before the war was very different.}
{221000}{}{Poster}
{221001}{}{Huge old poster.}
{221100}{}{Poster}
{221101}{}{"Be ready to strike."}
{221200}{}{Poster}
{221201}{}{The colors are blurred and faded.}
{221300}{}{Poster}
{221301}{}{You like old posters. They preserve history.}
{221400}{}{Tile}
{221500}{}{Tile}
{221600}{}{Tile}
{221700}{}{Tile}
{221800}{}{Tile}
{221900}{}{Tile}
{222000}{}{Tile}
{222100}{}{Board}
{222101}{}{Just an ordinary plaque. Nothing interesting.}
{222200}{}{Board}
{222201}{}{Just an ordinary plaque. Nothing interesting.}
{222300}{}{Board}
{222301}{}{Just an ordinary plaque. Nothing interesting.}
{222400}{}{Board}
{222401}{}{Just an ordinary plaque. Nothing interesting.}
{222500}{}{Board}
{222501}{}{Just an ordinary plaque. Nothing interesting.}
{222600}{}{Board}
{222601}{}{Just an ordinary plaque. Nothing interesting.}
{222700}{}{Board}
{222701}{}{Just an ordinary plaque. Nothing interesting.}
{222800}{}{Board}
{222801}{}{Just an ordinary plaque. Nothing interesting.}
{222900}{}{Board}
{222901}{}{Just an ordinary plaque. Nothing interesting.}
{223000}{}{Board}
{223001}{}{Just an ordinary plaque. Nothing interesting.}
{223100}{}{Board}
{223101}{}{Just an ordinary plaque. Nothing interesting.}
{223200}{}{Board}
{223201}{}{Just an ordinary plaque. Nothing interesting.}
{223300}{}{Board}
{223301}{}{Just an ordinary plaque. Nothing interesting.}
{223400}{}{Board}
{223401}{}{Just an ordinary plaque. Nothing interesting.}
{223500}{}{Board}
{223501}{}{Just an ordinary plaque. Nothing interesting.}
{223600}{}{A rusty piece of metal.}
{223601}{}{What do you need it for?}
{223700}{}{A rusty piece of metal.}
{223701}{}{It's completely useless.}
{223800}{}{A rusty piece of metal.}
{223801}{}{You examine it carefully, but it doesn't make it any more useful.}
{223900}{}{Junk}
{223901}{}{Even the last vagabond wouldn't go for this junk.}
{224000}{}{Junk}
{224001}{}{Absolutely useless junk.}
{224100}{}{Junk}
{224101}{}{You won't find any use for this junk.}
{224200}{}{Junk}
{224201}{}{Nothing of interest.}
{224300}{}{A rusty piece of metal.}
{224301}{}{It won't be of any use to you, that's for sure.}
{224400}{}{A rusty piece of metal.}
{224401}{}{It's completely useless.}
{224500}{}{A rusty piece of metal.}
{224501}{}{Let it rust.}
{224600}{}{Junk}
{224601}{}{You don't want to collect any junk, do you?}
{224700}{}{Junk}
{224701}{}{Even the last vagabond wouldn't go for this junk.}
{224800}{}{Junk}
{224801}{}{You won't find any use for this junk.}
{224900}{}{Junk}
{224901}{}{You don't want to collect any junk, do you?}
{225000}{}{Door}
{225001}{}{This door is securely boarded up.}
{225100}{}{Bed}
{225101}{}{It's not worth the risk of laying down on it.}
{225200}{}{Bed}
{225201}{}{It's completely rotten.}
{225300}{}{Bed}
{225301}{}{What's crawling around there?}
{225400}{}{Wall}
{225500}{}{Wall}
{225600}{}{Wall}
{225700}{}{Wall}
{225800}{}{Wall}
{225900}{}{Stones}
{226000}{}{Stones}
{226100}{}{Stones}
{226200}{}{Stones}
{226300}{}{Stones}
{226400}{}{Stones}
{226500}{}{Stones}
{226600}{}{Stones}
{226700}{}{Stones}
{226800}{}{Stones}
{226900}{}{Stones}
{227000}{}{Stones}
{227100}{}{Junk}
{227101}{}{A useless pile of junk.}
{227200}{}{Metal sheet}
{227201}{}{Is that blood?}
{227300}{}{Junk}
{227301}{}{Even the last vagabond wouldn't go for this junk.}
{227400}{}{Metal sheet}
{227401}{}{It's rusty heavy and completely useless.}
{227500}{}{Metal sheet}
{227501}{}{Even the last vagabond wouldn't go for this junk.}
{227600}{}{Metal sheet}
{227601}{}{You don't want to collect any junk, do you?}
{227700}{}{Metal sheet}
{227701}{}{It's all rusted out.}
{227800}{}{Metal sheet}
{227801}{}{A useless pile of junk.}
{227900}{}{Crate}
{227901}{}{It's a nice big box, but there's nothing interesting in there.}
{228000}{}{Crate}
{228001}{}{You're really wondering what would happen if you put a radioactive substance, a vial of poison, and, for example, a cat inside.}
{228100}{}{Cave mushroom}
{228101}{}{Mom told you not to eat unfamiliar stuff.}
{228200}{}{Cave mushroom}
{228201}{}{Mom told you not to eat unfamiliar stuff.}
{228300}{}{Cave mushroom}
{228301}{}{Mom told you not to eat unfamiliar stuff.}
{228400}{}{Cave mushroom}
{228401}{}{Mom told you not to eat unfamiliar stuff.}
{228500}{}{Cave mushroom}
{228501}{}{Mom told you not to eat unfamiliar stuff.}
{228600}{}{Cave mushroom}
{228601}{}{Mom told you not to eat unfamiliar stuff.}
{228700}{}{Cave mushroom}
{228701}{}{Mom told you not to eat unfamiliar stuff.}
{228800}{}{Cave mushroom}
{228801}{}{Mom told you not to eat unfamiliar stuff.}
{228900}{}{Cave mushroom}
{228901}{}{Mom told you not to eat unfamiliar stuff.}
{229000}{}{Cave mushroom}
{229001}{}{Mom told you not to eat unfamiliar stuff.}
{229100}{}{Metal sheet}
{229101}{}{It's nice and hardly crumpled, but you won't need it.}
{229200}{}{Metal sheet}
{229201}{}{Completely useless to you.}
{229300}{}{Metal sheet}
{229301}{}{Rusty and crumpled tin sheet.}
{229400}{}{Cave Wall}
{229500}{}{Cave Wall}
{229600}{}{Stones}
{229700}{}{Part of a wall.}
{229800}{}{Part of a wall.}
{229900}{}{Part of a wall.}
{230000}{}{Part of a wall.}
{230100}{}{Destroyed column.}
{230200}{}{Destroyed column.}
{230300}{}{Destroyed column.}
{230400}{}{Destroyed column.}
{230500}{}{Sign}
{230501}{}{The paint is cracked, and the letters are illegible.}
{230600}{}{Sign}
{230601}{}{The paint is cracked, and the letters are illegible.}
{230700}{}{Large hole in the floor}
{230701}{}{A crater from an explosion. Only debris and rocks lie below.}
{230800}{}{Bed}
{230801}{}{It's better to hold your breath next to that bed - it stinks.}
{230900}{}{Bed}
{230901}{}{What's crawling around there?}
{231000}{}{Bed}
{231001}{}{Dust and mildew. It's not pleasant even to stand on it.}
{231100}{}{Metal sheet}
{231101}{}{An old rusty sheet of tin.}
{231200}{}{Metal sheet}
{231201}{}{You don't need that tin can junk.}
{231300}{}{Metal sheet}
{231301}{}{Useless tin.}
{231400}{}{Poster}
{231401}{}{A huge faded poster of TIN Industries.}
{231500}{}{Tile shards}
{231501}{}{Thousands of them! And each one is unique in its own way.}
{231600}{}{Tile shards}
{231601}{}{Thousands of them! And each one is unique in its own way.}
{231700}{}{Tile shards}
{231701}{}{Thousands of them! And each one is unique in its own way.}
{231800}{}{Tile shards}
{231801}{}{Thousands of them! And each one is unique in its own way.}
{231900}{}{Tile shards}
{231901}{}{Thousands of them! And each one is unique in its own way.}
{232000}{}{Tile shards}
{232001}{}{Thousands of them! And each one is unique in its own way.}
{232100}{}{Tile shards}
{232101}{}{Thousands of them! And each one is unique in its own way.}
{232200}{}{Tile shards}
{232201}{}{Thousands of them! And each one is unique in its own way.}
{232300}{}{Tile shards}
{232301}{}{Thousands of them! And each one is unique in its own way.}
{232400}{}{Tile shards}
{232401}{}{Thousands of them! And each one is unique in its own way.}
{232500}{}{Tile shards}
{232501}{}{Thousands of them! And each one is unique in its own way.}
{232600}{}{Tile shards}
{232601}{}{Thousands of them! And each one is unique in its own way.}
{232700}{}{Tile shards}
{232701}{}{Thousands of them! And each one is unique in its own way.}
{232800}{}{Tile shards}
{232801}{}{Thousands of them! And each one is unique in its own way.}
{232900}{}{Tile shards}
{232901}{}{Thousands of them! And each one is unique in its own way.}
{233000}{}{Bed}
{233001}{}{You don't want to lie down on this filthy recline at all.}
{233100}{}{Junk}
{233101}{}{It's better not to touch it.}
{233200}{}{Junk}
{233201}{}{Totally useless thing.}
{233300}{}{Factory Wall}
{233400}{}{Factory Wall}
{233500}{}{Part of a wall.}
{233600}{}{Part of a wall.}
{233700}{}{Part of a wall.}
{233800}{}{Part of a wall.}
{233900}{}{Poster}
{233901}{}{It's very old.}
{234000}{}{Poster}
{234001}{}{You look at it for a while. You definitely like old posters.}
{234100}{}{Poster}
{234101}{}{It looks very patriotic.}
{234200}{}{Wall}
{234300}{}{Poster}
{234301}{}{You wish there had been a poster like this hanging over your bed when you were a kid.}
{234400}{}{Poster}
{234401}{}{Seems like mold has settled on it.}
{234500}{}{Poster}
{234501}{}{A faded wall poster.}
{234600}{}{Wall}
{234700}{}{Wall}
{234800}{}{Car}
{234801}{}{A massive excavating machine.}
{234900}{}{Car}
{234901}{}{A massive excavating machine.}
{235000}{}{Junk}
{235001}{}{Rusty iron. This junk is not worth your attention.}
{235100}{}{A sheet of rusty iron}
{235101}{}{Makes a funny sound when you knock on it.}
{235200}{}{Junk}
{235201}{}{Rusty iron. This junk is not worth your attention.}
{235300}{}{A sheet of rusty iron}
{235301}{}{Too heavy. Unlikely to be of any use to you.}
{235400}{}{A sheet of rusty iron}
{235401}{}{Too heavy. Unlikely to be of any use to you.}
{235500}{}{Junk}
{235501}{}{Not worth wasting your time on this piece of junk.}
{235600}{}{Junk}
{235601}{}{It's just useless junk now.}
{235700}{}{Junk}
{235701}{}{It's just useless junk now.}
{235800}{}{Junk}
{235801}{}{It's not worth picking up any junk.}
{235900}{}{Junk}
{235901}{}{Utterly useless trash.}
{236000}{}{Rocks}
{236001}{}{Look impregnable.}
{236100}{}{Rocks}
{236101}{}{Look impregnable.}
{236200}{}{Rocks}
{236201}{}{Look impregnable.}
{236300}{}{Board}
{236301}{}{An unremarkable board.}
{236400}{}{A sheet of iron.}
{236401}{}{Makes a funny sound when you knock on it.}
{236500}{}{A sheet of iron.}
{236501}{}{Too heavy.}
{236600}{}{A sheet of iron.}
{236601}{}{There is absolutely no use for you in it.}
{236700}{}{A sheet of iron.}
{236701}{}{It looks sturdy, but it's useless.}
{236800}{}{Junk}
{236801}{}{This junk is useless.}
{236900}{}{Junk}
{236901}{}{This junk is useless.}
{237000}{}{Junk}
{237001}{}{This junk is useless.}
{237100}{}{Junk}
{237101}{}{Utterly useless trash.}
{237200}{}{Junk}
{237201}{}{Don't waste your time with all kinds of useless junk.}
{237300}{}{Junk}
{237301}{}{Just regular trash.}
{237400}{}{Junk}
{237401}{}{It won't be of any use to you, that's for sure.}
{237500}{}{Junk}
{237501}{}{Not of any interest to you, unless you are heavily into trash collecting.}
{237600}{}{Junk}
{237601}{}{Not of any interest to you, unless you are heavily into trash collecting.}
{237700}{}{Tools}
{237701}{}{These tools are not usable.}
{237800}{}{Box}
{237801}{}{An empty old box is completely useless.}
{237900}{}{Junk}
{237901}{}{Utterly useless trash.}
{238000}{}{Junk}
{238001}{}{Utterly useless trash.}
{238100}{}{Junk}
{238101}{}{Utterly useless trash.}
{238200}{}{Poster}
{238201}{}{An old faded "Olympus" poster.}
{238300}{}{Lights}
{238400}{}{Lights}
{238500}{}{Box}
{238501}{}{An old empty box.}
{238600}{}{Box}
{238601}{}{An old empty box.}
{238700}{}{Box}
{238701}{}{An old empty box.}
{238800}{}{Box}
{238801}{}{An old empty box.}
{238900}{}{Old box}
{238901}{}{There is nothing but trash in this dirty box.}
{239000}{}{Old box}
{239001}{}{There is nothing but trash in this dirty box.}
{239100}{}{Old box}
{239101}{}{There is nothing but trash in this dirty box.}
{239200}{}{Old box}
{239201}{}{There is nothing but trash in this dirty box.}
{239300}{}{Old box}
{239301}{}{There is nothing but trash in this dirty box.}
{239400}{}{Old box}
{239401}{}{There is nothing but trash in this dirty box.}
{239500}{}{Old box}
{239501}{}{There is nothing but trash in this dirty box.}
{239600}{}{Old box}
{239601}{}{Its contents may have been of interest, but that was a long time ago.}
{239700}{}{Old box}
{239701}{}{Its contents may have been of interest, but that was a long time ago.}
{239800}{}{Old box}
{239801}{}{Its contents may have been of interest, but that was a long time ago.}
{239900}{}{Old box}
{239901}{}{Its contents may have been of interest, but that was a long time ago.}
{240000}{}{Old box}
{240001}{}{A rusty metal box, very heavy and empty.}
{240100}{}{Old box}
{240101}{}{Its contents may have been of interest, but that was a long time ago.}
{240200}{}{Junk}
{240201}{}{The lid of the box. Not likely to be of any use to you.}
{240300}{}{Junk}
{240301}{}{The lid of the box. Not likely to be of any use to you.}
{240400}{}{Old box}
{240401}{}{Tattered on the outside with useless contents inside. Just like some people.}
{240500}{}{Old box}
{240501}{}{Tattered on the outside with useless contents inside. Just like some people.}
{240600}{}{Old box}
{240601}{}{Tattered on the outside with useless contents inside. Just like some people.}
{240700}{}{Old box}
{240701}{}{Only ancient junk and dust inside.}
{240800}{}{Old box}
{240801}{}{Only ancient junk and dust inside.}
{240900}{}{Old box}
{240901}{}{Only ancient junk and dust inside.}
{241000}{}{Old box}
{241001}{}{Only ancient junk and dust inside.}
{241100}{}{An old cupboard.}
{241101}{}{There's nothing in here. Looks like someone went through it before you did.}
{241200}{}{An old cupboard.}
{241201}{}{There's nothing in here. Looks like someone went through it before you did.}
{241300}{}{Old box}
{241301}{}{Only ancient junk and dust inside.}
{241400}{}{Old box}
{241401}{}{Only ancient junk and dust inside.}
{241500}{}{Old box}
{241501}{}{Its contents may have been of interest, but that was a long time ago.}
{241600}{}{Barrier}
{241601}{}{A small portable fence.}
{241700}{}{Barrier}
{241701}{}{A small portable fence.}
{241800}{}{Barrier}
{241801}{}{A small portable fence.}
{241900}{}{Old box}
{241901}{}{Tattered on the outside with useless contents inside. Just like some people.}
{242000}{}{Old box}
{242001}{}{Tattered on the outside with useless contents inside. Just like some people.}
{242100}{}{Container}
{242101}{}{Sturdy, rusty container.}
{242200}{}{Crate}
{242201}{}{Nothing useful in it.}
{242300}{}{Crate}
{242301}{}{Nothing useful in it.}
{242400}{}{Wall}
{242500}{}{Wall}
{242600}{}{Column}
{242700}{}{Column}
{242800}{}{Column}
{242900}{}{Column}
{243000}{}{Lights}
{243001}{}{Lights up the area around it.}
{243100}{}{Lights}
{243101}{}{Lights up the area around it.}
{243200}{}{Wall}
{243300}{}{Wall}
{243400}{}{Column}
{243500}{}{Wall}
{243600}{}{Wall}
{243700}{}{Column}
{243800}{}{Wall}
{243900}{}{Wall}
{244000}{}{Painting}
{244001}{}{Looks real and well preserved.}
{244100}{}{Painting}
{244101}{}{For several minutes you study the painting. Art is fascinating.}
{244200}{}{Painting}
{244201}{}{A portrait of a man. Your manly face would also look good on a portrait in a gold frame.}
{244300}{}{Void}
{244400}{}{Void}
{244500}{}{Bench}
{244501}{}{This is not a good time to rest.}
{244600}{}{Bench}
{244601}{}{Four legs, a long seat, a back - it's a bench!}
{244700}{}{Bench}
{244701}{}{This is not a good time to rest.}
{244800}{}{Bench}
{244801}{}{Four legs, a long seat, a back - it's a bench!}
{244900}{}{Old box}
{244901}{}{You look inside - it's empty.}
{245000}{}{Junk}
{245001}{}{It's completely useless junk.}
{245100}{}{Junk}
{245101}{}{It's completely useless junk.}
{245200}{}{Junk}
{245201}{}{It's completely useless junk.}
{245300}{}{Old box}
{245301}{}{You examine the contents. There's nothing but garbage. You are covered in rust.}
{245400}{}{Rusty iron.}
{245401}{}{Not even the last vagrant would be interested in this junk.}
{245500}{}{Rusty iron.}
{245501}{}{Not even the last vagrant would be interested in this junk.}
{245600}{}{Rusty iron.}
{245601}{}{Not even the last vagrant would be interested in this junk.}
{245700}{}{Old box}
{245701}{}{Looks like someone's been through it and blooded it up.}
{245800}{}{Junk}
{245801}{}{It's completely useless junk.}
{245900}{}{Junk}
{245901}{}{It's completely useless junk.}
{246000}{}{Junk}
{246001}{}{It's completely useless junk.}
{246100}{}{Junk}
{246101}{}{It's completely useless junk.}
{246200}{}{Junk}
{246201}{}{It's completely useless junk.}
{246300}{}{Junk}
{246301}{}{It's completely useless junk.}
{246400}{}{Junk}
{246401}{}{It's completely useless junk.}
{246500}{}{Old box}
{246501}{}{Its contents may have been of interest, but that was a long time ago.}
{246600}{}{Old box}
{246601}{}{Its contents may have been of interest, but that was a long time ago.}
{246700}{}{Crate}
{246701}{}{There's nothing inside. Looks like someone went through it before you did.}
{246800}{}{Crate}
{246801}{}{There's nothing inside. Looks like someone went through it before you did.}
{246900}{}{Painting}
{246901}{}{Something abstract and incomprehensible. You like the frame more than the painting.}
{247000}{}{An old painting.}
{247001}{}{An interesting landscape. You realize you will never see it in reality.}
{247100}{}{Painting}
{247101}{}{For several minutes you study the painting. Real art is fascinating.}
{247200}{}{Painting}
{247201}{}{An interesting landscape. You realize you will never see it in reality.}
{247300}{}{Painting}
{247301}{}{For several minutes you study the painting. Real art is fascinating.}
{247400}{}{Painting}
{247401}{}{Something clearly edible and very important, since people have deemed this food worthy of a gold frame.}
{247500}{}{Painting}
{247501}{}{Something clearly edible and very important, since people have deemed this food worthy of a gold frame.}
{247600}{}{Painting}
{247601}{}{Something abstract and incomprehensible. You like the frame more than the painting.}
{247700}{}{A blocked staircase.}
{247701}{}{The way up is blocked.}
{247800}{}{Painting}
{247801}{}{An interesting landscape. You realize you will never see it in reality.}
{247900}{}{Painting}
{247901}{}{Something clearly edible and very important, since people have deemed this food worthy of a gold frame.}
{248000}{}{A blocked staircase.}
{248001}{}{The passage is blocked.}
{248100}{}{Elevator}
{248101}{}{Service elevator leading to Tartarus.}
{248200}{}{Bed}
{248201}{}{This bed is perfectly preserved.}
{248300}{}{Bed}
{248301}{}{This bed is perfectly preserved.}
{248400}{}{Bed}
{248401}{}{This bed is perfectly preserved.}
{248500}{}{Bed}
{248501}{}{This bed is perfectly preserved.}
{248600}{}{Armchair}
{248601}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{248700}{}{Armchair}
{248701}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{248800}{}{Armchair}
{248801}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{248900}{}{Armchair}
{248901}{}{It's a real leather chair. You've never sat in anything so comfortable.}
{249000}{}{Armchair}
{249001}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249100}{}{Armchair}
{249101}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249200}{}{Armchair}
{249201}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249300}{}{Armchair}
{249301}{}{Once in this chair, your butt will experience uncharted heights of comfort.}
{249400}{}{Leather sofa}
{249401}{}{You had no idea how comfortable furniture can be.}
{249500}{}{Leather sofa}
{249501}{}{You had no idea how comfortable furniture can be.}
{249600}{}{Leather sofa}
{249601}{}{You had no idea how comfortable furniture can be.}
{249700}{}{Leather sofa}
{249701}{}{You had no idea how comfortable furniture can be.}
{249800}{}{Leather sofa}
{249801}{}{Now you know what "expensive furniture" means.}
{249900}{}{Leather sofa}
{249901}{}{Now you know what "expensive furniture" means.}
{250000}{}{Leather sofa}
{250001}{}{Now you know what "expensive furniture" means.}
{250100}{}{Leather sofa}
{250101}{}{Now you know what "expensive furniture" means.}
{250200}{}{Column}
{250201}{}{A fine example of neoclassical architecture.}
{250300}{}{Hotel counter.}
{250301}{}{Keys and old letters are still in it.}
{250400}{}{Column}
{250401}{}{A fine example of neoclassical architecture.}
{250500}{}{Counter}
{250501}{}{The "Horton Hotel" signposted counter.}
{250600}{}{Counter}
{250601}{}{The "Horton Hotel" signposted counter.}
{250700}{}{Counter}
{250701}{}{The "Horton Hotel" signposted counter.}
{250800}{}{stairs up}
{250801}{}{This stairway leads to the upper floor.}
{250900}{}{Wall}
{251000}{}{Wall}
{251100}{}{Wall}
{251200}{}{stairs down}
{251201}{}{This stairway leads to the lower floor.}
{251300}{}{stairs}
{251301}{}{This stairway leads to the upper floor.}
{251400}{}{stairs}
{251401}{}{This stairway leads to the upper floor.}
{251500}{}{stairs}
{251501}{}{This stairway leads to the lower floor.}
{251600}{}{Cluttered stairs.}
{251601}{}{Passages to the upper and lower floors are blocked.}
{251700}{}{Generator}
{251701}{}{A device that generates electricity.}
{251800}{}{Big generator.}
{251801}{}{It generates power for the tower.}
{251900}{}{Big generator.}
{251901}{}{It generates power for the tower.}
{252000}{}{Trailer with stuff}
{252001}{}{Made from the trunk of a car.}
{252100}{}{Trailer with stuff}
{252101}{}{The craftsmen seem to have converted the trunk of a car into a trailer.}
{252200}{}{Floor}
{252201}{}{Digital markings on the floor.}
{252300}{}{Floor}
{252301}{}{Digital markings on the floor.}
{252400}{}{Floor}
{252401}{}{Digital markings on the floor.}
{252500}{}{Floor}
{252501}{}{Digital markings on the floor.}
{252600}{}{Floor}
{252601}{}{Digital markings on the floor.}
{252700}{}{Floor}
{252701}{}{Alphabetic markings on the floor.}
{252800}{}{Floor}
{252801}{}{Alphabetic markings on the floor.}
{252900}{}{Floor}
{252901}{}{Alphabetic markings on the floor.}
{253000}{}{Floor}
{253001}{}{Alphabetic markings on the floor.}
{253100}{}{Clogged door.}
{253101}{}{You won't get through.}
{253200}{}{Table}
{253201}{}{Medical table.}
{253300}{}{Table}
{253301}{}{Medical table.}
{253400}{}{Table}
{253401}{}{Medical table.}
{253500}{}{Electrical panel.}
{253501}{}{An element of the hotel's electrical system.}
{253600}{}{Olympus}
{253601}{}{Here it is! The Olympus, abode of all hopefuls.}
{253700}{}{Olympus}
{253701}{}{Here it is! The Olympus, abode of all hopefuls.}
{253800}{}{Olympus}
{253801}{}{Here it is! The Olympus, abode of all hopefuls.}
{253900}{}{Olympus}
{253901}{}{Here it is! The Olympus, abode of all hopefuls.}
{254000}{}{Olympus}
{254001}{}{Here it is! The Olympus, abode of all hopefuls.}
{254100}{}{Olympus}
{254101}{}{Here it is! The Olympus, abode of all hopefuls.}
{254200}{}{Olympus}
{254201}{}{Here it is! The Olympus, abode of all hopefuls.}
{254300}{}{Olympus}
{254301}{}{Here it is! The Olympus, abode of all hopefuls.}
{254400}{}{Olympus}
{254401}{}{Here it is! The Olympus, abode of all hopefuls.}
{254500}{}{Olympus}
{254501}{}{Here it is! The Olympus, abode of all hopefuls.}
{254600}{}{Olympus}
{254601}{}{Here it is! The Olympus, abode of all hopefuls.}
{254700}{}{Olympus}
{254701}{}{Here it is! The Olympus, abode of all hopefuls.}
{254800}{}{Olympus}
{254801}{}{Here it is! The Olympus, abode of all hopefuls.}
{254900}{}{Elevator}
{254901}{}{It seems to be the only way to move around the floors of the tower.}
{255000}{}{Elevator}
{255001}{}{It seems to be the only way to move around the floors of the tower.}
{255100}{}{Olympus}
{255101}{}{Here it is! The Olympus, abode of all hopefuls.}
{255200}{}{Olympus}
{255201}{}{Here it is! The Olympus, abode of all hopefuls.}
{255300}{}{Olympus}
{255301}{}{Here it is! The Olympus, abode of all hopefuls.}
{255400}{}{Metal archway}
{255401}{}{Rusty, but still strong.}
{255500}{}{Metal archway}
{255501}{}{Rusty, but still strong.}
{255600}{}{Shadow}
{255700}{}{Coffee machine}
{255701}{}{You press the button and nothing happen. It seems to be broken.}
{255800}{}{Coffee machine}
{255801}{}{You press the button and nothing happen. It seems to be broken.}
{255900}{}{Stove}
{255901}{}{An ordinary household oven.}
{256000}{}{Monument}
{256001}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256100}{}{Monument}
{256101}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256200}{}{Monument}
{256201}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256300}{}{Monument}
{256301}{}{A monument to the pre-war era. Rusted, but has not lost its impressiveness.}
{256400}{}{Boxes}
{256401}{}{These boxes are empty, there is nothing to eat here.}
{256500}{}{Boxes}
{256501}{}{These boxes are empty, there is nothing to eat here.}
{256600}{}{Boxes}
{256601}{}{These boxes are empty, there is nothing to eat here.}
{256700}{}{Table}
{256701}{}{Medical table.}
{256800}{}{Table}
{256801}{}{Medical table.}
{256900}{}{Boxes}
{256901}{}{So many boxes and absolutely nothing useful - what a disappointment!}
{257000}{}{Boxes}
{257001}{}{So many boxes and absolutely nothing useful - what a disappointment!}
{257100}{}{Boxes}
{257101}{}{These boxes are empty, there is nothing to eat here.}
{257200}{}{Elevator}
{257201}{}{The elevator doors.}
{257300}{}{Elevator}
{257301}{}{It seems to be the only way to move around the floors of the tower.}
{257400}{}{Elevator}
{257401}{}{The elevator doors.}
{257500}{}{Elevator}
{257501}{}{The elevator doors.}
{257600}{}{Armor plate}
{257601}{}{Probably protects the back wall from the spraying insides of the test subjects.}
{257700}{}{Generator}
{257701}{}{A device that generates electricity.}
{257800}{}{Blocked elevator entrance.}
{257801}{}{You won't get through.}
{257900}{}{Battery}
{257901}{}{Backup power source.}
{258000}{}{Table}
{258001}{}{Judging by the tools, this is the engineer's desk.}
{258100}{}{Table}
{258101}{}{Judging by the tools, this is the engineer's desk.}
{258200}{}{Table}
{258201}{}{This is the biggest desk you have ever seen.}
{258300}{}{Table}
{258301}{}{This is the biggest desk you have ever seen.}
{258400}{}{Boxes}
{258401}{}{These boxes are empty, there is nothing to eat here.}
{258500}{}{Boxes}
{258501}{}{These boxes are empty, there is nothing to eat here.}
{258600}{}{Wall}
{258700}{}{Wall}
{258800}{}{Junk}
{258801}{}{It's completely useless junk.}
{258900}{}{Junk}
{258901}{}{It's completely useless junk.}
{259000}{}{Junk}
{259001}{}{It's completely useless junk.}
{259100}{}{An old car.}
{259101}{}{This bucket of nuts is definitely unable to ride.}
{259200}{}{Beam}
{259201}{}{Supporting structure.}
{259300}{}{Beam}
{259301}{}{Supporting structure.}
{259400}{}{Beam}
{259401}{}{Supporting structure.}
{259500}{}{Beam}
{259501}{}{Supporting structure.}
{259600}{}{Beam}
{259601}{}{Supporting structure.}
{259700}{}{Beam}
{259701}{}{Supporting structure.}
{259800}{}{Beam}
{259801}{}{Supporting structure.}
{259900}{}{Beam}
{259901}{}{Supporting structure.}
{260000}{}{Beam}
{260001}{}{Supporting structure.}
{260100}{}{Beam}
{260101}{}{Supporting structure.}
{260200}{}{Beam}
{260201}{}{Supporting structure.}
{260300}{}{Beam}
{260301}{}{Supporting structure.}
{260400}{}{Wall}
{260500}{}{Wall}
{260600}{}{Wall}
{260700}{}{Wall}
{260800}{}{Wall}
{260900}{}{Wall}
{261000}{}{Vent}
{261001}{}{Ventilation grille.}
{261100}{}{Vent}
{261101}{}{Dirty ventilation grill.}
{261200}{}{Vent}
{261201}{}{Ventilation grille.}
{261300}{}{Vent}
{261301}{}{Dirty ventilation grill.}
{261400}{}{Old box}
{261401}{}{Its contents may have been of interest, but that was a long time ago.}
{261500}{}{Junk}
{261501}{}{Hardly anyone can find a use for this junk.}
{261600}{}{Junk}
{261601}{}{Hardly anyone can find a use for this junk.}
{261700}{}{Bunk}
{261701}{}{A hospital bed with a monitor.}
{261800}{}{Wall}
{261900}{}{Wall}
{262000}{}{Wall}
{262100}{}{Wall}
{262200}{}{Bin}
{262201}{}{A bin, full of garbage.}
{262300}{}{Box}
{262301}{}{Nothing interesting - just useless junk.}
{262400}{}{Pipe}
{262401}{}{An element of Olympus' communication systems.}
{262500}{}{Huge machine.}
{262501}{}{The sign says: "Cloning machine".}
{262600}{}{Huge machine.}
{262601}{}{The sign says: "Cloning machine".}
{262700}{}{Metal plate.}
{262701}{}{Highly unlikely to be of any use to you.}
{262800}{}{Metal plate.}
{262801}{}{Highly unlikely to be of any use to you.}
{262900}{}{Metal plate.}
{262901}{}{Highly unlikely to be of any use to you.}
{263000}{}{Box}
{263001}{}{Full box of junk, and not a single useful item.}
{263100}{}{Box}
{263101}{}{Full box of junk, and not a single useful item.}
{263200}{}{Box}
{263201}{}{Full box of junk, and not a single useful item.}
{263300}{}{Crate}
{263301}{}{Sturdy and reliable, but completely empty.}
{263400}{}{Junk}
{263401}{}{Hardly anyone can find a use for this junk.}
{263500}{}{Wall}
{263600}{}{Wall}
{263700}{}{Wall}
{263800}{}{Wall}
{263900}{}{Loudspeaker}
{263901}{}{An old, rusty loudspeaker.}
{264000}{}{Loudspeaker}
{264001}{}{An old, rusty loudspeaker.}
{264100}{}{Huge machine.}
{264101}{}{The sign says: "Cloning machine".}
{264200}{}{Huge machine.}
{264201}{}{The sign says: "Cloning machine".}
{264300}{}{Huge machine.}
{264301}{}{The sign says: "Cloning machine".}
{264400}{}{Huge machine.}
{264401}{}{The sign says: "Cloning machine".}
{264500}{}{Corpse}
{264501}{}{Something seems to have gone wrong with this car.}
{264600}{}{Old box}
{264601}{}{So huge and so empty.}
{264700}{}{Crate}
{264701}{}{Nothing but useless junk inside.}
{264800}{}{Wall}
{264900}{}{Wall}
{265000}{}{A desk with a calculator}
{265001}{}{The engineer's workstation.}
{265100}{}{A desk with a calculator}
{265101}{}{An engineer's workstation with a calculator on.}
{265200}{}{A desk with a calculator}
{265201}{}{The engineer's workstation.}
{265300}{}{A desk with a calculator}
{265301}{}{An engineer's workstation with a calculator on.}
{265400}{}{A desk with a calculator}
{265401}{}{An engineer's workstation with a calculator on.}
{265500}{}{A desk with a calculator}
{265501}{}{The engineer's workstation.}
{265600}{}{A desk with a calculator}
{265601}{}{An engineer's workstation with a calculator on.}
{265700}{}{A desk with a calculator}
{265701}{}{The engineer's workstation.}
{265800}{}{Chair}
{265801}{}{A piece of furniture designed to support the human body in a seated position.}
{265900}{}{Chair}
{265901}{}{This chair would have been quite ordinary if it weren't for the wheels. You wonder if they used to have chair races here.}
{266000}{}{Chair}
{266001}{}{This chair would have been quite ordinary if it weren't for the wheels. You wonder if they used to have chair races here.}
{266100}{}{Chair}
{266101}{}{A piece of furniture designed to support the human body in a seated position.}
{266200}{}{Junk}
{266201}{}{Not even the last vagrant would be interested in this junk.}
{266300}{}{Box}
{266301}{}{An ordinary box of useless junk.}
{266400}{}{Box}
{266401}{}{An ordinary box of useless junk.}
{266500}{}{Wires}
{266501}{}{A floor cable.}
{266600}{}{Wires}
{266601}{}{A floor cable.}
{266700}{}{Wires}
{266701}{}{A floor cable.}
{266800}{}{Wires}
{266801}{}{A floor cable.}
{266900}{}{Wires}
{266901}{}{A floor cable.}
{267000}{}{Wires}
{267001}{}{A floor cable.}
{267100}{}{Wires}
{267101}{}{A floor cable.}
{267200}{}{Junk}
{267201}{}{It's completely useless junk.}
{267300}{}{Junk}
{267301}{}{It's completely useless junk.}
{267400}{}{Junk}
{267401}{}{It's completely useless junk.}
{267500}{}{Junk}
{267501}{}{A useless pile of junk.}
{267600}{}{Junk}
{267601}{}{A useless pile of junk.}
{267700}{}{Junk}
{267701}{}{It's completely useless junk.}
{267800}{}{Junk}
{267801}{}{There is some dubious liquid in the bottle. Better not to touch it.}
{267900}{}{Junk}
{267901}{}{Just an empty bottle.}
{268000}{}{Junk}
{268001}{}{It is hard to imagine that anyone in their right mind would be interested in this junk.}
{268100}{}{Junk}
{268101}{}{A bunch of useless junk.}
{268200}{}{Junk}
{268201}{}{It is hard to imagine that anyone in their right mind would be interested in this junk.}
{268300}{}{Junk}
{268301}{}{It is hard to imagine that anyone in their right mind would be interested in this junk.}
{268400}{}{Calculator}
{268401}{}{This is where the tower's solar panels are controlled.}
{268500}{}{Barrier}
{268501}{}{The rusted-out emergency fence.}
{268600}{}{Barrier}
{268601}{}{The rusted-out emergency fence.}
{268700}{}{Barrier}
{268701}{}{The rusted-out emergency fence.}
{268800}{}{Barrier}
{268801}{}{The rusted-out emergency fence.}
{268900}{}{Wall}
{268901}{}{The wall of the skyscraper.}
{269000}{}{Wall}
{269001}{}{The wall of the skyscraper.}
{269100}{}{Parapet}
{269101}{}{You can lean on it and look thoughtfully into the distance.}
{269200}{}{Parapet}
{269201}{}{You can lean on it and look thoughtfully into the distance.}
{269300}{}{Parapet}
{269301}{}{You can lean on it and look thoughtfully into the distance.}
{269400}{}{Lights}
{269500}{}{Lights}
{269600}{}{Wasteland}
{269601}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{269700}{}{Wasteland}
{269701}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{269800}{}{Wasteland}
{269801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{269900}{}{Wasteland}
{269901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270000}{}{Wasteland}
{270001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270100}{}{Wasteland}
{270101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270200}{}{Wasteland}
{270201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270300}{}{Wasteland}
{270301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270400}{}{Wasteland}
{270401}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270500}{}{Wasteland}
{270501}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270600}{}{Wasteland}
{270601}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270700}{}{Wasteland}
{270701}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270800}{}{Wasteland}
{270801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{270900}{}{Wasteland}
{270901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{271000}{}{Wasteland}
{271001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{271100}{}{Wasteland}
{271101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{271200}{}{The Bronze Eagle}
{271201}{}{The enormous eagle is the symbol of an invincible country.}
{271300}{}{Wall}
{271301}{}{The wall of the skyscraper.}
{271400}{}{Wall}
{271401}{}{The wall of the skyscraper.}
{271500}{}{Wall}
{271501}{}{The wall of the skyscraper.}
{271600}{}{Wall}
{271601}{}{The wall of the skyscraper.}
{271700}{}{Wall}
{271701}{}{The wall of the skyscraper.}
{271800}{}{Wall}
{271801}{}{The wall of the skyscraper.}
{271900}{}{Wall}
{271901}{}{The wall of the skyscraper.}
{272000}{}{Wasteland}
{272001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272100}{}{Wasteland}
{272101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272200}{}{Wasteland}
{272201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272300}{}{Wasteland}
{272301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272400}{}{Wasteland}
{272401}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272500}{}{Wasteland}
{272501}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272600}{}{Sofa}
{272601}{}{A luxurious leather sofa.}
{272700}{}{Sofa}
{272701}{}{A luxurious leather sofa.}
{272800}{}{Wasteland}
{272801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{272900}{}{Wasteland}
{272901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273000}{}{Wasteland}
{273001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273100}{}{Wasteland}
{273101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273200}{}{Wasteland}
{273201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273300}{}{Wasteland}
{273301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273400}{}{Wasteland}
{273401}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273500}{}{Wasteland}
{273501}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273600}{}{Wasteland}
{273601}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273700}{}{Wasteland}
{273701}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273800}{}{Wasteland}
{273801}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{273900}{}{Wasteland}
{273901}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274000}{}{Wasteland}
{274001}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274100}{}{Wasteland}
{274101}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274200}{}{Wasteland}
{274201}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274300}{}{Wasteland}
{274301}{}{From here, the wasteland looks peaceful and quiet. You start to forget the violence and dangers of Radius below.}
{274400}{}{Biomass}
{274401}{}{Biomatter, a collection of organisms.}
{274500}{}{Biomass}
{274501}{}{Biomatter, a collection of organisms.}
{274600}{}{Biomass}
{274601}{}{Biomatter, a collection of organisms.}
{274700}{}{Biomass}
{274701}{}{Biomatter, a collection of organisms.}
{274800}{}{Biomass}
{274801}{}{Biomatter, a collection of organisms.}
{274900}{}{Elevator}
{274901}{}{The elevator doors.}
{275000}{}{Door}
{275001}{}{The passage is blocked.}
{275100}{}{Door}
{275101}{}{The passage is blocked.}
{275200}{}{Table}
{275201}{}{This is the biggest desk you have ever seen.}
{275300}{}{Table}
{275301}{}{This is the biggest desk you have ever seen.}
{275400}{}{Calculator}
{275401}{}{"Cerberus" security module}
{275500}{}{Calculator}
{275501}{}{"Andromeda" computation module}
{275600}{}{Calculator}
{275601}{}{"Borealis" logical module}
{275700}{}{Cooling system}
{275701}{}{You can hear the coolant circulating through the tubes.}
{275800}{}{Systematizer}
{275801}{}{A huge computing machine with a bunch of flashing lights.}
{275900}{}{Systematizer}
{275901}{}{A huge computing machine with a bunch of flashing lights.}
{276000}{}{Screen}
{276001}{}{A huge screen, covered in dust. Looks like it hasn't worked in years.}
{276100}{}{Armchair}
{276101}{}{A comfortable leather chair.}
{276200}{}{Sofa}
{276201}{}{A luxurious leather sofa.}
{276300}{}{Sofa}
{276301}{}{A luxurious leather sofa.}
{276400}{}{Armchair}
{276401}{}{A comfortable leather chair.}
{276500}{}{Calculator}
{276501}{}{Judging by its size, this machine has enormous computing power.}
{276600}{}{Calculator}
{276601}{}{Judging by its size, this machine has enormous computing power.}
{276700}{}{Calculator}
{276701}{}{Judging by its size, this machine has enormous computing power.}
{276800}{}{Calculator}
{276801}{}{Judging by its size, this machine has enormous computing power.}
{276900}{}{Camera}
{276901}{}{It's probably filming you.}
{277000}{}{Loudspeaker}
{277001}{}{An old loudspeaker. It probably still works.}
{277100}{}{Elevator}
{277101}{}{The elevator doors.}
{277200}{}{Shards}
{277201}{}{Thousands of them! And each one is unique in its own way.}
{277300}{}{Shards}
{277301}{}{Thousands of them! And each one is unique in its own way.}
{277400}{}{Shards}
{277401}{}{Thousands of them! And each one is unique in its own way.}
{277500}{}{Shards}
{277501}{}{Thousands of them! And each one is unique in its own way.}
{277600}{}{Shards}
{277601}{}{Thousands of them! And each one is unique in its own way.}
{277700}{}{Shards}
{277701}{}{Thousands of them! And each one is unique in its own way.}
{277800}{}{Shards}
{277801}{}{Thousands of them! And each one is unique in its own way.}
{277900}{}{Shards}
{277901}{}{Thousands of them! And each one is unique in its own way.}
{278000}{}{Shards}
{278001}{}{Thousands of them! And each one is unique in its own way.}
{278100}{}{Shards}
{278101}{}{Thousands of them! And each one is unique in its own way.}
{278200}{}{Shards}
{278201}{}{Thousands of them! And each one is unique in its own way.}
{278300}{}{Shards}
{278301}{}{Thousands of them! And each one is unique in its own way.}
{278400}{}{Shards}
{278401}{}{Thousands of them! And each one is unique in its own way.}
{278500}{}{Shards}
{278501}{}{Thousands of them! And each one is unique in its own way.}
{278600}{}{Shards}
{278601}{}{Thousands of them! And each one is unique in its own way.}
{278700}{}{Shards}
{278701}{}{Thousands of them! And each one is unique in its own way.}
{278800}{}{Shards}
{278801}{}{Thousands of them! And each one is unique in its own way.}
{278900}{}{Shards}
{278901}{}{Thousands of them! And each one is unique in its own way.}
{279000}{}{Shards}
{279001}{}{Thousands of them! And each one is unique in its own way.}
{279100}{}{Shards}
{279101}{}{Thousands of them! And each one is unique in its own way.}
{279200}{}{Shards}
{279201}{}{Thousands of them! And each one is unique in its own way.}
{279300}{}{Shards}
{279301}{}{Thousands of them! And each one is unique in its own way.}
{279400}{}{Shards}
{279401}{}{Thousands of them! And each one is unique in its own way.}
{279500}{}{Shards}
{279501}{}{Thousands of them! And each one is unique in its own way.}
{279600}{}{Shards}
{279601}{}{Thousands of them! And each one is unique in its own way.}
{279700}{}{Shards}
{279701}{}{Thousands of them! And each one is unique in its own way.}
{279800}{}{Shards}
{279801}{}{Thousands of them! And each one is unique in its own way.}
{279900}{}{Shards}
{279901}{}{Thousands of them! And each one is unique in its own way.}
{280000}{}{Shards}
{280001}{}{Thousands of them! And each one is unique in its own way.}
{280100}{}{Shards}
{280101}{}{Thousands of them! And each one is unique in its own way.}
{280200}{}{Tower control system.}
{280201}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280300}{}{Tower control system.}
{280301}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280400}{}{Tower control system.}
{280401}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280500}{}{Tower control system.}
{280501}{}{On the large monitors, lines of characters run at a tremendous speed.}
{280600}{}{Floor}
{280601}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{280700}{}{Floor}
{280701}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{280800}{}{Floor}
{280801}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{280900}{}{Floor}
{280901}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{281000}{}{Floor}
{281001}{}{A reddish glow pierces from beneath the lattice plates on the floor.}
{281100}{}{Armor wall}
{281101}{}{A protective structure.}
{281200}{}{Armor wall}
{281201}{}{A protective structure.}
{281300}{}{Armor wall}
{281301}{}{A protective structure.}
{281400}{}{Armor wall}
{281401}{}{A protective structure.}
{281500}{}{Armor wall}
{281501}{}{A protective structure.}
{281600}{}{Armor wall}
{281601}{}{A protective structure.}
{281700}{}{Armor wall}
{281701}{}{A protective structure.}
{281800}{}{Armor wall}
{281801}{}{A protective structure.}
{281900}{}{Armor wall}
{281901}{}{A protective structure.}
{282000}{}{Shattered protective screen.}
{282001}{}{The screen is completely shattered.}
{282100}{}{Shattered protective screen.}
{282101}{}{The screen is completely shattered.}
{282200}{}{Shattered protective screen.}
{282201}{}{The screen is completely shattered.}
{282300}{}{Poisonous sludge.}
{282301}{}{Spookily gurgling.}
{282400}{}{Poisonous sludge.}
{282401}{}{Spookily gurgling.}
{282500}{}{Poisonous sludge.}
{282501}{}{Spookily gurgling.}
{282600}{}{Steel door.}
{282601}{}{Rusty, but looks solid.}
{282700}{}{The corpse of a woman.}
{282701}{}{The horribly stinking remains of some woman.}
{282800}{}{Sand}
{282900}{}{Sand}
{283000}{}{Sand}
{283100}{}{Sand}
{283200}{}{Sand}
{283300}{}{Junk}
{283301}{}{Some kind of debris in the water.}
{283400}{}{Vase}
{283401}{}{A clay vase filled with something very similar to blood.}
{283500}{}{Bucket}
{283501}{}{Nothing unusual - just a simple bucket with someone's guts hanging out of it.}
{283600}{}{Totem}
{283601}{}{Looks like the natives pray to this thing.}
{283700}{}{Totem}
{283701}{}{Looks like the natives pray to this thing.}
{283800}{}{Totem}
{283801}{}{Looks like the natives pray to this thing.}
{283900}{}{Totem}
{283901}{}{Looks like the natives pray to this thing.}
{284000}{}{Totem}
{284001}{}{A terrifying thing with a skull, bones, and red eyes - the natives have an original idea of the gods.}
{284100}{}{Totem}
{284101}{}{A terrifying thing with a skull, bones, and red eyes - the natives have an original idea of the gods.}
{284200}{}{Strange stump}
{284201}{}{An incomprehensible structure with burning pieces of coal inside. Probably has some religious meaning.}
{284300}{}{Strange stump}
{284301}{}{An incomprehensible structure with burning pieces of coal inside. Probably has some religious meaning.}
{284400}{}{Rod}
{284401}{}{Thick metal rod.}
{284500}{}{Tree}
{284501}{}{A dried-up tree.}
{284600}{}{Tree}
{284601}{}{A dried-up tree.}
{284700}{}{Tree}
{284701}{}{A dried-up tree.}
{284800}{}{Tree}
{284801}{}{A dried-up tree.}
{284900}{}{Tree}
{284901}{}{A dried-up tree.}
{285000}{}{Tree}
{285001}{}{A dried-up tree.}
{285100}{}{Tree}
{285101}{}{A dried-up tree.}
{285200}{}{Tree}
{285201}{}{A dried-up tree.}
{285300}{}{Tree}
{285301}{}{A dried-up tree.}
{285400}{}{Tree}
{285401}{}{A dried-up tree.}
{285500}{}{Tree}
{285501}{}{A dried-up tree.}
{285600}{}{Tree}
{285601}{}{A dried-up tree.}
{285700}{}{Tree}
{285701}{}{A dried-up tree.}
{285800}{}{Tree}
{285801}{}{A dried-up tree.}
{285900}{}{Tree}
{285901}{}{A dried-up tree.}
{286000}{}{Tree}
{286001}{}{A dried-up tree.}
{286100}{}{Leaves}
{286101}{}{Some kind of plant.}
{286200}{}{Leaves}
{286201}{}{Some kind of plant.}
{286300}{}{Leaves}
{286301}{}{Some kind of plant.}
{286400}{}{Leaves}
{286401}{}{Some kind of plant.}
{286500}{}{Leaves}
{286501}{}{Some kind of plant.}
{286600}{}{Leaves}
{286601}{}{Some kind of plant.}
{286700}{}{Leaves}
{286701}{}{Some kind of plant.}
{286800}{}{Leaves}
{286801}{}{Some kind of plant.}
{286900}{}{Leaves}
{286901}{}{Some kind of plant.}
{287000}{}{Leaves}
{287001}{}{Some kind of plant.}
{287100}{}{Stone}
{287200}{}{Stone}
{287300}{}{Stone}
{287400}{}{Stone}
{287500}{}{Stone}
{287600}{}{Stone}
{287700}{}{Stone}
{287800}{}{Stone}
{287900}{}{Stone}
{288000}{}{Stone}
{288100}{}{Stone}
{288200}{}{Stone}
{288300}{}{Stone}
{288400}{}{Stone}
{288500}{}{Stone}
{288600}{}{Stone}
{288700}{}{Stone}
{288800}{}{Stone}
{288900}{}{Stone}
{289000}{}{Stone}
{289100}{}{Stone}
{289200}{}{Stone}
{289300}{}{Stone}
{289400}{}{Stone}
{289500}{}{Stone}
{289600}{}{Stone}
{289700}{}{Stone}
{289800}{}{Stone}
{289900}{}{Stone}
{289901}{}{No time to gather stones.}
{290000}{}{Stone}
{290001}{}{No time to gather stones.}
{290100}{}{Stone}
{290101}{}{No time to gather stones.}
{290200}{}{Stone}
{290201}{}{No time to gather stones.}
{290300}{}{Fire}
{290301}{}{A fireplace neatly lined with rocks. Apparently, the stones keep the heat in.}
{290400}{}{Torch}
{290401}{}{A huge burning torch - it seems the natives revere fire.}
{290500}{}{Totem}
{290501}{}{This tribe is obviously very religious.}
{290600}{}{Totem}
{290601}{}{This tribe is obviously very religious.}
{290700}{}{Totem}
{290701}{}{This tribe is obviously very religious.}
{290800}{}{Totem}
{290801}{}{A stone totem, another object revered by the tribe.}
{290900}{}{Totem}
{290901}{}{A stone totem, another object revered by the tribe.}
{291000}{}{Totem}
{291001}{}{A stone totem, another object revered by the tribe.}
{291100}{}{Totem}
{291101}{}{There are bones sticking out of this one, and the fires inside are dying out. Do they have a schedule for setting totems on fire?}
{291200}{}{Totem}
{291201}{}{What big bones!}
{291300}{}{Totem}
{291301}{}{There are bones sticking out of this one, and the fires inside are dying out. Do they have a schedule for setting totems on fire?}
{291400}{}{Totem}
{291401}{}{What big bones!}
{291500}{}{Bench}
{291501}{}{A stiff and cold stone bench.}
{291600}{}{Stake}
{291601}{}{Looks like some kind of tribal tool.}
{291700}{}{Totem}
{291701}{}{Looks like there's meat on this stake. Their spirits demand sacrifices.}
{291800}{}{Parts of totems.}
{291801}{}{And here are bones too. You wonder who they belonged to.}
{291900}{}{Roaster}
{291901}{}{You wonder what they're roasting there.}
{292000}{}{Fence}
{292001}{}{A small fence and a little table with something that looks like meat.}
{292100}{}{Strange stump}
{292101}{}{There's burning coal inside. Looks like the spirits of the tribe love fire.}
{292200}{}{Stump}
{292201}{}{There's burning coal inside. Looks like the spirits of the tribe love fire.}
{292300}{}{Stones}
{292301}{}{Spread out in an even circle around the fire.}
{292400}{}{Stones}
{292401}{}{Spread out in an even circle around the fire.}
{292500}{}{Slope}
{292501}{}{A sloped surface area.}
{292600}{}{Slope}
{292601}{}{A sloped surface area.}
{292700}{}{Totem}
{292701}{}{Shamanic totem of the tribe.}
{292800}{}{Tribune}
{292900}{}{Web}
{293000}{}{Web}
{293100}{}{Web}
{293200}{}{Web}
{293300}{}{Web}
{293400}{}{Web}
{293500}{}{Web}
{293600}{}{Web}
{293700}{}{Web}
{293800}{}{Web}
{293900}{}{Web}
{294000}{}{Web}
{294100}{}{Truck}
{294101}{}{Radioactive waste has leaked onto the ground from a broken cistern, making the place deadly.}
{294200}{}{Land}
{294300}{}{Land}
{294400}{}{Land}
{294500}{}{Land}
{294600}{}{Fence}
{294601}{}{A low fence made of planks.}
{294700}{}{Fence}
{294701}{}{A low fence made of planks.}
{294800}{}{Light}
{294801}{}{Yellow glass gives the illusion that the lantern is on.}
{294900}{}{Fence}
{294901}{}{A low fence made of planks.}
{295000}{}{Fence}
{295001}{}{A low fence made of planks.}
{295100}{}{Fence}
{295101}{}{A low fence made of planks.}
{295200}{}{Fence}
{295201}{}{A low fence made of planks.}
{295300}{}{Void}
{295301}{}{There is only a blackening emptiness. It is staring at you.}
{295400}{}{A sign that reads, "Warehouse"}
{295401}{}{You are not sure, but it could mean there is a warehouse.}
{295500}{}{A hospital poster.}
{295501}{}{The poster shows a smiling doctor holding a bloody scalpel.}
{295600}{}{A tree}
{295601}{}{You can cut it down and make a fire. Or hang yourself on it.}
{295700}{}{A tree}
{295701}{}{It's a tree. It must be wooden.}
{295800}{}{A tree}
{295801}{}{You think it stands out from the others. You are seeing things.}
{295900}{}{A tree}
{295901}{}{You want to hug it and cry.}
{296000}{}{A tree}
{296001}{}{The accumulated radiation makes it shimmer slightly.}