{100}{}{Boy}
{101}{}{A little Boy.}
{200}{}{Boy}
{201}{}{A little black boy.}
{300}{}{Girl}
{301}{}{A little girl with funny ponytails}
{400}{}{Girl}
{401}{}{A little harmless girl with a ponytail.}
{500}{}{Teenager}
{501}{}{An ordinary boy of around 15 years old.}
{600}{}{Teenager}
{601}{}{An ordinary teenager with a daring look and a defiant haircut.}
{700}{}{Teenager}
{701}{}{An ordinary black kid.}
{800}{}{Girl}
{801}{}{A Teenage Girl.}
{900}{}{Girl}
{901}{}{An ordinary black girl in T-Shirt and pants.}
{1000}{}{Tech Servant}
{1001}{}{This person is responsible for the operation of the machinery in Tartarus.}
{1100}{}{Tech Servant}
{1101}{}{This person is responsible for the operation of the machinery in Tartarus.}
{1200}{}{Herald}
{1201}{}{This son of the Gods brings the word of the Lords to the Servants.}
{1300}{}{Herald}
{1301}{}{This son of the Gods brings the word of the Lords to the Servants.}
{1400}{}{Life Servant}
{1401}{}{This man provides Tartarus with food.}
{1500}{}{Water Servant}
{1501}{}{This man provides Tartarus with water.}
{1600}{}{Life Servant}
{1601}{}{This woman works on the farms of Tartarus.}
{1700}{}{Tech Servant}
{1701}{}{This woman works with technology as good as the men.}
{1800}{}{Water Servant}
{1801}{}{This woman provides Tartarus with water.}
{1900}{}{Healer}
{1901}{}{An elderly man who looks like a physician.}
{2000}{}{Scholar}
{2001}{}{With a receding hairline and shifty eyes, he looks like a natural scientist.}
{2100}{}{Guardian}
{2101}{}{An guard in an armored suit, covered in wires, tubes and whirring motors.}
{2200}{}{Feral Ghoul}
{2201}{}{A horribly nasty looking creature, it's skin hangs on like it's flapping on a rack.}
{2300}{}{Pale Ghoul}
{2301}{}{A hideous creature, it's muscles are clearly showing through the pale skin.}
{2400}{}{Warden}
{2401}{}{A Son of the Gods, he keeps order in Tartarus.}
{2500}{}{Lavash}
{2501}{}{A mutated hulking type of the bovine family, a nice source of fresh meat.}
{2600}{}{Dad}
{2601}{}{It's John, your father.}
{2700}{}{Mom}
{2701}{}{It's Elisa, your mother.}
{2800}{}{Kirk}
{2801}{}{Your obnoxious little brother Kirk.}
{2900}{}{Katie}
{2901}{}{Your childhood friend Katie. She constantly makes eyes at you.}
{3000}{}{Brook}
{3001}{}{Katie's father, always drab and sullen.}
{3100}{}{Stella}
{3101}{}{Katie's mother, one of the few female maintenance workers.}
{3200}{}{Bully}
{3201}{}{A big kid, brash and arrogant.}
{3300}{}{Carol}
{3301}{}{If something's broken, go to her. Just don't talk about men!}
{3400}{}{Smitty}
{3401}{}{A middle-aged repairman, head of the warehouse.}
{3500}{}{Dr. Pat}
{3501}{}{The ever-disgruntled doctor who provides medical care to the inhabitants of Tartarus.}
{3600}{}{Gregorius}
{3601}{}{The herald of the will of the Gods. He never seems to sleep...}
{3700}{}{Katie}
{3701}{}{Your friend Katie.}
{3800}{}{Kirk}
{3801}{}{Your brother.}
{3900}{}{Kirk}
{3901}{}{Your brother.}
{4000}{}{Kirk}
{4001}{}{Your brother.}
{4100}{}{Kirk}
{4101}{}{Your brother.}
{4200}{}{Bardock}
{4201}{}{}
{4300}{}{Bono}
{4301}{}{}
{4400}{}{Hugo}
{4401}{}{}
{4500}{}{Presley}
{4501}{}{}
{4600}{}{Robin}
{4601}{}{}
{4700}{}{Peter}
{4701}{}{}
{4800}{}{Lilly}
{4801}{}{}
{4900}{}{Martha}
{4901}{}{}
{5000}{}{Joe}
{5001}{}{}
{5100}{}{Unlucky}
{5101}{}{}
{5200}{}{Unlucky}
{5201}{}{}
{5300}{}{Elderly}
{5301}{}{}
{5400}{}{Young Resident}
{5401}{}{}
{5500}{}{Urchin}
{5501}{}{}
{5600}{}{Resident}
{5601}{}{}
{5700}{}{Hunter}
{5701}{}{}
{5800}{}{Experienced Hunter}
{5801}{}{}
{5900}{}{Hugo's Sidekick}
{5901}{}{}
{6000}{}{Escaped Servant}
{6001}{}{}
{6100}{}{Escaped Servant}
{6101}{}{}
{6200}{}{Escaped Servant}
{6201}{}{}
{6300}{}{Escaped Servant}
{6301}{}{}
{6400}{}{Loudmouth}
{6401}{}{}
{6500}{}{Billy Stone}
{6501}{}{}
{6600}{}{Chris Murena}
{6601}{}{}
{6700}{}{Oswald Brown}
{6701}{}{}
{6800}{}{Harry}
{6801}{}{}
{6900}{}{Carl}
{6901}{}{}
{7000}{}{Shiva}
{7001}{}{}
{7100}{}{Vince}
{7101}{}{}
{7200}{}{Casper}
{7201}{}{}
{7300}{}{Ursul}
{7301}{}{}
{7400}{}{Kyle}
{7401}{}{}
{7500}{}{Stan}
{7501}{}{}
{7600}{}{Small Jackal}
{7601}{}{}
{7700}{}{Raider}
{7701}{}{}
{7800}{}{Raider}
{7801}{}{}
{7900}{}{Big Jackal}
{7901}{}{}
{8000}{}{Jackal Guard}
{8001}{}{}
{8100}{}{Jackal Guard}
{8101}{}{}
{8200}{}{Arms Dealer}
{8201}{}{}
{8300}{}{Armor Merchant}
{8301}{}{}
{8400}{}{Trader}
{8401}{}{}
{8500}{}{Tramp}
{8501}{}{}
{8600}{}{Mark}
{8601}{}{}
{8700}{}{Lucy}
{8701}{}{}
{8800}{}{Daniel}
{8801}{}{}
{8900}{}{Sam}
{8901}{}{}
{9000}{}{Dan}
{9001}{}{}
{9100}{}{Arsen}
{9101}{}{}
{9200}{}{Maurissa}
{9201}{}{}
{9300}{}{Juan}
{9301}{}{}
{9400}{}{Cyren}
{9401}{}{}
{9500}{}{Blanca}
{9501}{}{}
{9600}{}{Flint}
{9601}{}{}
{9700}{}{Owen}
{9701}{}{}
{9800}{}{Skeet}
{9801}{}{}
{9900}{}{Buck}
{9901}{}{}
{10000}{}{Gunter}
{10001}{}{}
{10100}{}{Seth}
{10101}{}{}
{10200}{}{Matt}
{10201}{}{}
{10300}{}{Shaggy}
{10301}{}{}
{10400}{}{Guard}
{10401}{}{}
{10500}{}{Guard}
{10501}{}{}
{10600}{}{Guard}
{10601}{}{}
{10700}{}{Guard}
{10701}{}{}
{10800}{}{Can Salesman}
{10801}{}{}
{10900}{}{Junk Dealer}
{10901}{}{}
{11000}{}{Guard Chief}
{11001}{}{}
{11100}{}{Local Farmer}
{11101}{}{}
{11200}{}{NWO Resident}
{11201}{}{}
{11300}{}{Local Farmer}
{11301}{}{}
{11400}{}{Local}
{11401}{}{}
{11500}{}{Kid}
{11501}{}{}
{11600}{}{Kid}
{11601}{}{}
{11700}{}{Thick Lavash}
{11701}{}{}
{11800}{}{Edward Vincent von Schwein}
{11801}{}{}
{11900}{}{Christopher Schwein}
{11901}{}{}
{12000}{}{Ludwig Schwein}
{12001}{}{}
{12100}{}{Veronica Schwein}
{12101}{}{}
{12200}{}{Boston McKinsey}
{12201}{}{}
{12300}{}{Dallas McKinsey}
{12301}{}{}
{12400}{}{Fox McKinsey}
{12401}{}{}
{12500}{}{Abilene McKinsey}
{12501}{}{}
{12600}{}{Claudia Horton}
{12601}{}{}
{12700}{}{Minnie Horton}
{12701}{}{}
{12800}{}{Ashton Horton}
{12801}{}{}
{12900}{}{Emily Danton}
{12901}{}{}
{13000}{}{Sope Danton}
{13001}{}{}
{13100}{}{Guy}
{13101}{}{}
{13200}{}{Girl}
{13201}{}{}
{13300}{}{Lady}
{13301}{}{}
{13400}{}{Gentleman}
{13401}{}{}
{13500}{}{Machinegun Turret}
{13501}{}{}
{13600}{}{Hog}
{13601}{}{}
{13700}{}{Shepherd}
{13701}{}{}
{13800}{}{Healer}
{13801}{}{}
{13900}{}{Arena Warden}
{13901}{}{}
{14000}{}{Kent}
{14001}{}{}
{14100}{}{Douglas}
{14101}{}{}
{14200}{}{Naomi Young}
{14201}{}{}
{14300}{}{Brick}
{14301}{}{}
{14400}{}{Big G}
{14401}{}{}
{14500}{}{Squirrel}
{14501}{}{}
{14600}{}{Snowflake}
{14601}{}{}
{14700}{}{Bull}
{14701}{}{}
{14800}{}{Weakling}
{14801}{}{}
{14900}{}{Wimp}
{14901}{}{}
{15000}{}{Prostitute}
{15001}{}{}
{15100}{}{Drunk}
{15101}{}{}
{15200}{}{Beggar}
{15201}{}{}
{15300}{}{Thug}
{15301}{}{}
{15400}{}{Local}
{15401}{}{}
{15500}{}{Local}
{15501}{}{}
{15600}{}{Farmer}
{15601}{}{}
{15700}{}{Kid}
{15701}{}{}
{15800}{}{Tomboy}
{15801}{}{}
{15900}{}{Naomi's Assistant}
{15901}{}{}
{16000}{}{Naomi's Assistant}
{16001}{}{}
{16100}{}{Tame Wolf}
{16101}{}{}
{16200}{}{Elder}
{16201}{}{}
{16300}{}{Klumk}
{16301}{}{}
{16400}{}{Khala}
{16401}{}{}
{16500}{}{Ptuna}
{16501}{}{}
{16600}{}{Hunter}
{16601}{}{}
{16700}{}{Warrior}
{16701}{}{}
{16800}{}{Local}
{16801}{}{}
{16900}{}{Tame Wolf}
{16901}{}{}
{17000}{}{Fred}
{17001}{}{}
{17100}{}{Christie}
{17101}{}{}
{17200}{}{Kingpin}
{17201}{}{Judging by the gun, this one is definitely the Leader.}
{17300}{}{Thug}
{17301}{}{The bloodshot eyes and froth on the mouth speak volumes...}
{17400}{}{Punk}
{17401}{}{You can only talk to this one in the language of lead...}
{17500}{}{Raider}
{17501}{}{An ordinary evil and unwashed bandit.}
{17600}{}{Beast}
{17601}{}{}
{17700}{}{Robotron}
{17701}{}{}
{17800}{}{Captain Richards}
{17801}{}{}
{17900}{}{Phillip Grey}
{17901}{}{}
{18000}{}{Konstantin Zochkis}
{18001}{}{}
{18100}{}{Daimond Crank}
{18101}{}{}
{18200}{}{Captain N34}
{18201}{}{}
{18300}{}{Anderson's Shield}
{18301}{}{}
{18400}{}{Anderson}
{18401}{}{}
{18500}{}{Defender}
{18501}{}{You look in awe at his armor.}
{18502}{}{Black smoke billows from the exhaust pipes behind him.}
{18503}{}{Every movement of this warrior tells of his strength and power.}
{18504}{}{...although, underneath his armor, is likely just a normal human body...}
{18600}{}{Defender}
{18601}{}{You look in awe at his armor.}
{18602}{}{Black smoke billows from the exhaust pipes behind him.}
{18603}{}{Every movement of this warrior tells of his strength and power.}
{18604}{}{...although, underneath his armor, is likely just a normal human body...}
{18700}{}{Soldier}
{18701}{}{}
{18800}{}{Predator}
{18801}{}{His armor is entangled with a network of tubes and powered pistons.}
{18802}{}{This is a man in armored suit with an ominously flashing gas mask.}
{18900}{}{Scout}
{18901}{}{}
{19000}{}{Biologist}
{19001}{}{}
{19100}{}{Engineer}
{19101}{}{}
{19200}{}{Scientist}
{19201}{}{}
{19300}{}{Machinegun Turret}
{19301}{}{}
{19400}{}{Machinegun Turret MKII}
{19401}{}{}
{19500}{}{Grenade Turret}
{19501}{}{}
{19600}{}{Security Robot}
{19601}{}{}
{19700}{}{Chimera}
{19701}{}{}
{19800}{}{Weak Chimera}
{19801}{}{This one looks very weak.}
{19900}{}{Tame Chimera}
{19901}{}{}
{20000}{}{Mother Chimera}
{20001}{}{}
{20100}{}{Wild Dog}
{20101}{}{}
{20200}{}{Coyote}
{20201}{}{}
{20300}{}{Mole Rat}
{20301}{}{}
{20400}{}{Ursa}
{20401}{}{}
{20500}{}{Rat}
{20501}{}{}
{20600}{}{Giant Ant}
{20601}{}{}
{20700}{}{Golden Ant}
{20701}{}{}
{20800}{}{Scorpion}
{20801}{}{}
{20900}{}{Lavash}
{20901}{}{}
{21000}{}{Feral Ghoul}
{21001}{}{}
{21100}{}{Pale Ghoul}
{21101}{}{}
{21200}{}{Beastie}
{21201}{}{}
{21300}{}{Black Beastie}
{21301}{}{}
{21400}{}{Lumenier}
{21401}{}{}
{21500}{}{Lumenier Leader}
{21501}{}{}
{21600}{}{Sickly Man}
{21601}{}{}
{21700}{}{Old Man}
{21701}{}{}
{21800}{}{Old Woman}
{21801}{}{}
{21900}{}{Beggar}
{21901}{}{}
{22000}{}{Traveler}
{22001}{}{}
{22100}{}{Stranger}
{22101}{}{}
{22200}{}{Seasoned Traveler}
{22201}{}{}
{22300}{}{Trickster}
{22301}{}{}
{22400}{}{Fugitive}
{22401}{}{}
{22500}{}{Fugitive}
{22501}{}{}
{22600}{}{Fugitive}
{22601}{}{}
{22700}{}{Fugitive}
{22701}{}{}
{22800}{}{Skinny Raider}
{22801}{}{}
{22900}{}{Puny Raider}
{22901}{}{}
{23000}{}{Weak Raider}
{23001}{}{}
{23100}{}{Loser}
{23101}{}{}
{23200}{}{Nimble Raider}
{23201}{}{}
{23300}{}{Strong Raider}
{23301}{}{}
{23400}{}{Raider}
{23401}{}{}
{23500}{}{Raider}
{23501}{}{}
{23600}{}{Raider}
{23601}{}{}
{23700}{}{Seasoned Raider}
{23701}{}{}
{23800}{}{Dangerous Raider}
{23801}{}{}
{23900}{}{Raider}
{23901}{}{}
{24000}{}{NWO Merchant}
{24001}{}{}
{24100}{}{Caravan Guard}
{24101}{}{}
{24200}{}{Caravan Guard}
{24201}{}{}
{24300}{}{Caravan Guard}
{24301}{}{}
{24400}{}{Mutated Ant}
{24401}{}{}
{24500}{}{Ghoul}
{24501}{}{}
{24600}{}{Ghoul}
{24601}{}{}
{24700}{}{Ghoul}
{24701}{}{}
{24800}{}{Lenny}
{24801}{}{}
{24900}{}{Armored Soldier}
{24901}{}{}
{25000}{}{Gromus}
{25001}{}{}
{25100}{}{Predator}
{25101}{}{This fighter uses an improved version of the Guardian armor suit.}
{25200}{}{Machinegun Turret}
{25201}{}{This gun looks like it can tear up meat like nothing else.}
{25300}{}{Laser Turret}
{25301}{}{Looks like this turret can cut through flesh like butter.}
{25400}{}{Plasma Turret}
{25401}{}{It's hard to imagine what this weapon can do to a living being.}
{25500}{}{Phillip}
{25501}{}{The caretaker of the lavash.}
{25600}{}{Left Shield}
{25601}{}{Anderson's left defensive shield.}
{25700}{}{Central Shield}
{25701}{}{Anderson's central defensive shield.}
{25800}{}{Right Shield}
{25801}{}{Anderson's right defensive shield.}
{25900}{}{Woman}
{25901}{}{A female scientist.}
{26000}{}{Henry}
{26001}{}{A cowardly kid.}
{26100}{}{Sunny}
{26101}{}{A daring teenage girl.}
{26200}{}{Becky}
{26201}{}{A brave black girl.}
{26300}{}{Jock}
{26301}{}{The square-jawed sergeant.}
{26400}{}{Kelly}
{26401}{}{A little silly, but kind and sincere.}
{26500}{}{Moreau}
{26501}{}{A obstetrician technician with vicious little eyes.}
{26600}{}{Dick}
{26601}{}{Zochkis rougish assistent.}
{26700}{}{Taylor}
{26701}{}{A young and enthusiastic scientist.}
{26800}{}{Beatrice's Clone}
{26801}{}{Amazing! Even the clothes were cloned!}
{26900}{}{Tank Girl}
{26901}{}{You are absolutely sure that it is better not to annoy this girl.}
{27000}{}{}
{27001}{}{}
{27100}{}{}
{27101}{}{}
{27200}{}{}
{27201}{}{}
{27300}{}{}
{27301}{}{}
{27400}{}{}
{27401}{}{}
{27500}{}{}
{27501}{}{}
{27600}{}{}
{27601}{}{}
{27700}{}{}
{27701}{}{}
{27800}{}{}
{27801}{}{}
{27900}{}{}
{27901}{}{}
{28000}{}{}
{28001}{}{}
{28100}{}{}
{28101}{}{}
{28200}{}{}
{28201}{}{}
{28300}{}{}
{28301}{}{}
{28400}{}{}
{28401}{}{}
{28500}{}{}
{28501}{}{}
{28600}{}{}
{28601}{}{}
{28700}{}{}
{28701}{}{}
{28800}{}{}
{28801}{}{}
{28900}{}{}
{28901}{}{}
{29000}{}{}
{29001}{}{}
{29100}{}{}
{29101}{}{}
{29200}{}{}
{29201}{}{}
{29300}{}{}
{29301}{}{}
{29400}{}{}
{29401}{}{}
