#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#
#
# TARTAR Quests
#
{100}{}{Help Dr. Pat get the workers of Tartarus back on their feet.}
{101}{}{Your father is strongly irradiated. You need to find a way to return to Tartarus and help him.}
{102}{}{Your father needs Rad-Away. Find it and bring it to Dr. Pat in Tartarus.}
#
# UNDEAD CAVES Quests
#
{200}{}{Help out the hunters and bring them 6 apples and some firewood.}
{201}{}{Go hunting with Gromus and collect scorpion tails.}
{202}{}{Gather 10 local residents for Bono's performance.}
{203}{}{Presley asks me to bring him a bag of fertilizer for the gardens.}
{204}{}{Peter asks you to clean the clogged toilet. You need a special tool.}
{205}{}{You need to find a way to calm baby Lilly and help her fall asleep.}
{206}{}{Help Joe find his lost wife.}
{207}{}{Hugo needs a Combatid and 5 Heal-Ups to storm Tartarus.}
#
# SUNSET JACKALS Quests
#
{300}{}{Carl's machine broke down, and he needs spare parts from Chris Murena's warehouse.}
{301}{}{Search and get hold of an Ultra Repair Kit.}
{302}{}{Find a rare whetstone for Harry.}
{303}{}{Go and hunt with Urs, try not to die.}
{304}{}{Casper initiated a siege against Vince. You need to help Vince.}
{305}{}{Barker crafts necklaces out of chimera teeth and needs 3 more.}
{306}{}{Oswald Brown wouldn't mind to get hold of a rare vintage "Slugger" pistol.}
{307}{}{Billy Stone wants you to stand guard outside the room while he's with Shiva.}
{308}{}{Chris Morena asks to get rid of Kyle and find a replacement for him.}
#
# NEW WORLD ORDER Quests
#
{400}{}{Mark asks you to broke peace between his wife Lucy and his adviser Sam.}
{401}{}{Buck suggested that you find a replacement for the dying Mayor Mark.}
{402}{}{Juan complains about the broken machine and asks you to help him.}
{403}{}{The scout Seren is going to Tin Industries for cans, but he needs a partner.}
{404}{}{You can guard Flint's caravans for a good payoff.}
{405}{}{Clumsy Owen has dislocated his arm, and we need to help him.}
{406}{}{Someone steals meat from the warehouse in yard, and the innocently accused Skeet is sitting behind bars.}
{407}{}{Philip's lavash refuse to eat food. Find out what the reason is.}
{408}{}{The last time water came from Livos, it tasted strange. Sam asks you to look into what's going on.}
{409}{}{Brothers Seth and Mat can not get along with each other, you need to reconcile them.}
{410}{}{Bianca is passionately hungry for love. Find the "special device" and do not disappoint her!}
{411}{}{Henry asks to find Sunny and Becky's friends in Pearson Town.}
#
# LIVOS Quests
#
{500}{}{Eduard Shvain won't let you in at Livos until you can prove that you are one of the family members.}
{501}{}{The water filter is broken, and Ashton Horton wants you to fix it.}
{502}{}{The Danton family asks you to kill all the creatures in the cave under the filtration.}
{503}{}{Christopher Shvain is in love with Minnie Horton and asks you to help him hook up with her.}
{504}{}{Dallas McKinsey is in love with Minnie Horton and asks you to help him hook up with her.}
{505}{}{Ludwig Shvain says that someone stole his textbook on wave physics. Help him return the valuable book.}
{506}{}{Sopé Danton can no longer stand the tyranny of his wife Emily and asks you to "remove" her.}
{507}{}{Claudia Horton gets on Boston's nerves over her husband's death. We need to find a way to calm her down.}
{508}{}{Eduard Shvain accidentally gave the Laivos Constitution to some huge savage, and asks you to return it.}
#
# RAINBOW RAIDERS Quests
#
{600}{}{Kent asks to bring 8 ant abdomen from the farm and give them to the healer.}
{601}{}{The healer asks you to find out what kind of strange armored man is sitting in the bar.}
{602}{}{In one of the arena fights, Douglas lost his badge. Find the token and return it to him.}
{603}{}{Big G, the leader of a gang of teenagers, demands 5 bottles of cognac for the right to become a member of the gang.}
{604}{}{Big G intends to rob the caravan, this is your chance!}
{605}{}{Help the poor prostitute.}
{606}{}{The shepherd asks to deal with Brick, who constantly fucks his whores for free.}
{607}{}{Naomi asks for help to escape.}
{608}{}{Lenny doesn't understand why his friend Carl isn't coming back from the dead.}
{609}{}{Boar asks you to negotiate with the Sunset Jackals about a peace agreement.}
{610}{}{The shepherd can not cope with all the stoned visitors and asks for help.}
#
# OAZIS Quests
#
{700}{}{Defeat Klumk if you want to stay alive!}
{701}{}{Khala's hand was bitten by a ravenous animal, and she needs medical attention.}
{702}{}{Ptuna can't find her coyote fang anywhere.}
#
# FREDS HOUSE Quests
#
{800}{}{Fred has laid mines all around the house, but forgot where they are. Find and clear at least 5 of them.}
{801}{}{Fight off the attacking beasts.}
#
# OLYMPUS TOWER Quests
#
{900}{}{Richards orders you to use a pheromone to tame a feral chimera and bring it to Phillip Grey. (The injection works only for 8 days)}
{901}{}{Phillip Grey is convinced that Konstantin Zochkis, the head of the Bureau of Design and Engineering, must die as soon as possible.}
{902}{}{Daimond Crank needs a pre-war prototype of the Barrack Minigun. Bring it to him.}
{903}{}{Daimond Crank is confident that Ludwig Shvain will be able to help him break the deadlock on his research. Bring Ludwig to him.}
{904}{}{Captain N34 asks you to fill out all the documentation forms and conduct weapon tests.}
{905}{}{It's time to change the password for the Control Room. Go to the Server Floor and follow the instructions.}
{906}{}{KILL ANDERSON!}
{907}{}{Use the resources of the Olympus Tower as you see fit.}
{908}{}{Sergeant Jack has his eye on Kelly from the Biology Labs. Convince Kelly to meet with Jack.}
{909}{}{Moreau can not calibrate the cloning machine. Bring him a woman from Tartarus to experiment with.}
{910}{}{The cloning machine has run out of power. Go to Zochkis Bureau of Design and Engineering to find out what'S up with that.}
{911}{}{Dick is waiting for a clone of his wife Beatrice, promised to him by Grey for his services. Moreau might help.}
{912}{}{To complete the clone, Dr. Moreau needs the Stemm Cell Essence from Biolab Nr.2.}
{913}{}{Taylor can repair an advanced Powersuit of the Enlightened Ones, if you bring him a servo from a similar suit.}
