#
# Quest descriptons
#
#    Please leave space between the areas (like 100 or so)
#
#
# TARTAR Quests
#
{100}{}{Help Dr. Pat get the workers of Tartarus back on their feet.}
{101}{}{Your father is badly irradiated. You need to find a way back to Tartarus and help him.}
{102}{}{Your father needs something called "Antiradine". Find it and bring it to Dr. Pat in Tartarus.}
#
# UNDEAD CAVES Quests
#
{200}{}{Help out the Seekers and bring them 6 apples and some firewood.}
{201}{}{Go hunting with Gromus and collect some scorpion tails.}
{202}{}{Gather 10 local residents for Bono's speech.}
{203}{}{Priestley asked to bring him a bag of fertilizer for the gardens.}
{204}{}{Peter asked you to clean the clogged toilet. You need a special tool.}
{205}{}{You need to find a way to calm baby Lily and help her sleep.}
{206}{}{Help Joe find his lost wife.}
{207}{}{Hugo needs a Combatid and 5 Heal-Ups to storm Tartarus.}
#
# SUNSET JACKALS Quests
#
{300}{}{Carl's machine broke down, he needs parts from Chris Murena's warehouse.}
{301}{}{Search and get hold of an Ultra Repair Kit.}
{302}{}{Find a rare whetstone for Harry.}
{303}{}{Go on a hunt with Ursul. Try not to die.}
{304}{}{Casper holds a grudge against Vince. You should help Vince.}
{305}{}{Loudmouth wants to have a necklace made of Chimera fangs. He needs 3 more.}
{306}{}{Oswald Brown wouldn't mind to get hold of a rare vintage "Slugger" pistol.}
{307}{}{Billy Stone wants you to stand guard outside the room while he's with Shiva.}
{308}{}{Chris Murena asked you to get rid of Kyle and find a replacement for him.}
#
# NEW WORLD ORDER Quests
#
{400}{}{Mark asked you to make peace between his wife Lucy and his advisor Sam.}
{401}{}{Burns asked you to find out who would replace the dying Mark as a Mayor.}
{402}{}{Juan complained about the broken machine and asked you to help him.}
{403}{}{The scout Cyren is going to raid Tin Industries to get some rolls of tin. He needs a partner.}
{404}{}{You can guard Flint's caravans for a good pay.}
{405}{}{Clumsy Owen dislocated his arm, you need to help him.}
{406}{}{Someone steals canned meat from the warehouse, and the innocently accused Skeet sits behind bars.}
{407}{}{Philip's Lavash refuse to eat their food. Find out the reason behind it.}
{408}{}{The last time water was delivered from Livos, it tasted strange. Sam asks you to find out what's wrong.}
{409}{}{The brothers Seth and Matt can't get along with each other. You should help them reconcile.}
{410}{}{Blanca is passionately hungry for love. Find the "special device" and don't disappoint her!}
{411}{}{Henry asks to find his friends Sunny and Becky in Pearson Town.}
#
# LIVOS Quests
#
{500}{}{Edward Schwein won't let you into the Livos until you can prove that you are one of the family members.}
{501}{}{The water filter is broken. Ashton Horton wants you to fix it.}
{502}{}{The Dunton family asked you to kill all the creatures in the cave under the filtration room.}
{503}{}{Christopher Schwein is in love with Mignon Horton and asks you to help woo the girl.}
{504}{}{Dallas McKinsey is in love with Mignon Horton and asks you to help woo the girl.}
{505}{}{Ludwig Schwein says that someone has stolen his book of Wave Science. Help him to get the valuable book back.}
{506}{}{Sope Dunton can no longer stand the tyranny of his wife Emily and asks you to "take her out".}
{507}{}{Claudia Horton is pestering Boston about her husband's death. You need to find a way to calm Claudia down.}
{508}{}{Edward Schwein has accidentally given the Livos Constitution to some huge savage. He asks you to return it.}
#
# RAINBOW RAIDERS Quests
#
{600}{}{Mate asks to bring 8 ant bellies from the farm and give them to Apothecary.}
{601}{}{Apothecary asks you to find out who is that strange man in armor, sitting in the bar.}
{602}{}{In one of the fights in the arena, Douglas lost his badge. Find the badge and give it back to Douglas.}
{603}{}{G, the leader of a gang of teenagers, demands 5 bottles of cognac for the right to become a member of the gang.}
{604}{}{G intends to rob the caravan! This is your chance!}
{605}{}{Help the poor prostitute.}
{606}{}{The Shepherd asked you to deal with Brick, who keeps screwing his whores for free.}
{607}{}{Naomi asked to help her escape.}
{608}{}{Lenny doesn't understand why his friend Carl isn't coming back from the dead.}
{609}{}{Hog asks you to negotiate a non-aggression with the Sunset Jackals.}
{610}{}{The Shepherd can't handle all the stoned visitors and asks for help.}
#
# OAZIS Quests
#
{700}{}{Defeat Klumk if you want to live!}
{701}{}{Khala is bitten on the arm by a ravenous animal. She needs medical attention.}
{702}{}{Ptuna can't find her pet wolf Hook anywhere.}
#
# FREDS HOUSE Quests
#
{800}{}{Fred has laid mines around the house, but has forgotten where they are. Find and clear at least 5.}
{801}{}{Fight off the attacking Onca Devils.}
#
# OLYMPUS TOWER Quests
#
{900}{}{Richards ordered you to use a pheromone  feral Chimera and bring it to Phillipp Gray (The injection is only effective only for around a week).}
{901}{}{Phillipp Gray is convinced that Constantine Zochkis, the head of the Design and Engineering Bureau, must die as soon as possible. Accelerate this process.}
{902}{}{Diamond Crank needs a pre-war prototype of the "Baraka" Minigun. Bring it to him.}
{903}{}{Diamond Crank needs you to bring Ludwig Schwein to him.}
{904}{}{Captain #34 asks you to fill out all the documentation forms and conduct weapon tests.}
{905}{}{Go to the Server floor. Someone waits for you there.}
{906}{}{KILL ANDERSON!}
{907}{}{Use the resources of the Olympus Tower as you see fit.}
{908}{}{Sergeant Jock has his eye on Kelly from the biology floor. Convince Kelly to meet with Jock.}
{909}{}{Moreau can't calibrate the cloning machine. Bring him a woman from Tartarus to experiment on.}
{910}{}{The cloning machine's power cell has run out of power. Go to Zochkis on Engineering floor to find out what to do with that.}
{911}{}{Dick is waiting for a clone of his wife Beatrice, promised to him by Gray for his services. Moreau might help.}
{912}{}{To complete the clone, Dr. Moreau needs the Stem Cells Essence from Biolaboratory #2.}
{913}{}{Taylor can fix the advanced Lumenier mechanized suit if you bring him the servo from a similar suit.}
